### ISSUE TITLE
Refactor VSCode extension and enforce consistent style

### ISSUE THREAD

**Issue by aochagavia** [rust-analyzer/rust-analyzer#100]
Currently, the VSCode extension consists of a single `.ts` file full of functions and a bunch of global variables. As we add features the structure of the code becomes less clear. I think it would be worthwhile to refactor it into something more maintainable (e.g. try to avoid global variables, use multiple files, try to use classes to group related functions).

Additionally, the programming style used is not consistent (e.g. sometimes lines end on `;` and sometimes they don't). IMO the best way to solve this is to use tslint and check that there are no warnings in the CI.

@matklad if you think this is worthwhile I would like to give it a shot

**Comment by DJMcNab** [comment]
I find that prettier and tslint works quite well - using `tslint-config-prettier`.

**Comment by aochagavia** [comment]
Most of this is addressed by https://github.com/matklad/rust-analyzer/pull/103, but we still need to integrate the tslint check with the CI. See the comments in the PR for a possible approach.

I ended up leaving `prettier` out, because I have no experience with it. @DJMcNab feel free to add it yourself, especially if you are able to make it run with the CI.

**Comment by DJMcNab** [comment]
I'll look into it.

**Comment by aochagavia** [comment]
Thanks for the PR!

By the way, how does bors test PRs? Is it just merging into a branch and waiting for AppVeyor and Travis?

**Comment by aochagavia** [comment]
I think so, though I don't have the rights to do it
