### ISSUE TITLE
Bikeshed: symbol for cursor in tests and docs

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1001]
I am currently brushing up docs, and one thing I need is to show example of various assist. 

To do that, I need to somehow demarcate cursor position. Currently, we use `<|>` for this

```
        check_assist(
            add_derive,
            "#[derive(Clone)]\nstruct Foo { a: i32<|>, }",
            "#[derive(Clone<|>)]\nstruct Foo { a: i32, }",
        );
```

This is somewhat cryptic and non-obvious. Is it a terrible idea to through some unicode at it?

```
        check_assist(
            add_derive,
            "#[derive(Clone)]\nstruct Foo { a: i32🖎, }",
            "#[derive(Clone🖎)]\nstruct Foo { a: i32, }",
        );
```

Some options are:

* ✍ 
* 🖎
* ✎ 
* ⌶
* 👉

**Comment by vipentti** [comment]
One thing with the `<|>` is that it's fairly easy to search for, since it does not occur normally, and it's easyish to type. And once you learn it it's not too bad to remember. 

I'm not actually even sure without copy-pasting, how does one "type" a unicode symbol, on Windows this seems difficult at least ?

**Comment by DJMcNab** [comment]
Personally, I'm not great fan of any of those options. Using unicode also has the danger of making the code more unclear. For example, on the app I use for github on mobile, the second icon is just a blank box. That may be true for any android device (or this app could be bad!).

**Comment by vipentti** [comment]
For me Chrome on Android also shows the second symbol as a blank box.

**Comment by killercup** [comment]
For that list, I'd prefer ⌶. Alternatively use something like ◇?

You can also use a font that has a ligature for `<|>` :) This is how it looks with Iosevka, for example:

<img width="323" alt="Bildschirmfoto 2019-03-20 um 13 38 27" src="https://user-images.githubusercontent.com/20063/54684759-7de3fa80-4b15-11e9-86e2-61cc8144d8ed.png">

**Comment by killercup** [comment]
For that list, I'd prefer ⌶. Alternatively use something like ◇?

You can also use a font that has a ligature for `<|>` :) This is how it looks with Iosevka, for example:

<img width="323" alt="Bildschirmfoto 2019-03-20 um 13 38 27" src="https://user-images.githubusercontent.com/20063/54684759-7de3fa80-4b15-11e9-86e2-61cc8144d8ed.png">

**Comment by vipentti** [comment]
Are there any examples of other implementations ? I quickly glanced at intellij-rust and they seem to be using `/*caret*/` ? I agree with @DJMcNab, using unicode can make the code more unclear. So rather than using a single symbol we could just use an actual word like `<caret>` or `<cursor>` ?

**Comment by matklad** [comment]
The problem with `<caret>` (and with `<|>` for that matter) is that it's too noisy and makes the test less readable, if you don't have special editor support. (IntelliJ does have special editor support for it's own test files, so it highlights `<caret>` in a special way). 

This also plays a role when you need to compute an offset.

I guess, there's a general consensus that unicode is a 💩 choice in this case :)
