### ISSUE TITLE
Expand Derive Macros does not update if the underlying proc macro changes.

### ISSUE THREAD

**Issue by jhgg** [rust-analyzer/rust-analyzer#10027]
From the new feature #10014 (thank you so much for this btw, so helpful!) 

In a workspace where you might be working on a crate that implements some `#[derive(Whatever)]` macros, editing the proc macro functions do not seem to cause the expanded output to change (even after re-requesting a new expansion.) In order to view the new output of the generated code, you have to restart rust-analyzer. 

It would be *really* cool if rust-analyzer could detect that the proc macro crate has changed, and recompute the expanded macro output live. But at the very least, even if it was not live, re-running "expand macro recursively" should show the latest output from the proc macro.

**Comment by lnicola** [comment]
CC #9932

**Comment by jplatte** [comment]
> Quoth matklad:
> 
> > #10027 is a wont-fix in generall. We do not want to re-expand the world after a change in the derive macro.

Where is this quote from? I don't understand the "re-expand the world" part. Wouldn't you only have to re-expand crates depending on the proc-macro, rather than re-doing analysis of the entire dependency graph?

**Comment by flodiebold** [comment]
It's from Zulip. I think "the world" here means "potentially all crates in the workspace".

**Comment by jplatte** [comment]
I see. Doesn't look like the reload implemented in #10596 reloads deps anyways, at least it doesn't take that long. It also doesn't unset the 'yellow' status though. Will open a new issue.

**Comment by flodiebold** [comment]
Yes, the reload does re-expand the world, the point is that that only happens when the user triggers it.

**Comment by flodiebold** [comment]
Although to be honest, exactly the same problem exists when editing declarative macros :thinking:

**Comment by Shoeboxam** [comment]
As of Rust-Analyzer v0.3.1011, the expansion does not change to reflect edits in a proc macro, even after rebuilding, clicking the reload warning to reload rust-analyzer, and re-running the expansion command. I have to restart VSCode each time I edit a proc macro to see changes in the expansion.

It seems that this command would be more useful if it just called `cargo expand path::to::mod::or:fn` for you. [There seems to be a neat plugin that does this](https://marketplace.visualstudio.com/items?itemName=Odiriuss.rust-macro-expand), but in practice it isn't able to identify the current module or fn, like rust-analyzer can.

**Comment by jplatte** [comment]
@Shoeboxam Instead of reloading the whole editor, there is a command called `Rust Analyzer: Restart server` that you can use.

**Comment by Shoeboxam** [comment]
@jplatte That is useful, but I got impatient manually restarting rust analyzer, so I hacked this together. Perhaps other people will find it useful.

First, install `bat`. Right before returning from your proc-macro, call this function with the final TokenStream:
```rust
fn reformat(text: impl std::fmt::Display, name: String) {
    let mut rustfmt = Command::new("rustfmt")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .unwrap();
    write!(rustfmt.stdin.take().unwrap(), "{}", text).unwrap();
    let output = rustfmt.wait_with_output().unwrap();
    let formatted = String::from_utf8(output.stdout).unwrap();

    let mut bat = Command::new("bat")
        .arg("--paging")
        .arg("never")
        .arg("-l")
        .arg("rust")
        .arg("--color=always")
        .arg(format!("--file-name={}", name))
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .unwrap();
    write!(bat.stdin.take().unwrap(), "{}", formatted).unwrap();
    let output = bat.wait_with_output().unwrap();
    let highlighted = String::from_utf8(output.stdout).unwrap();

    print!("\x1B[2J\x1B[1;1H");
    println!("{}", highlighted)
}
```

Also open a terminal:
```shell
nodemon --exec "clear && cargo build" -e rs
```
