### ISSUE TITLE
Convert to manual impl should add generic parameters

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#10041]
![manul](https://user-images.githubusercontent.com/1711539/130954421-4df2ade9-2391-44cd-9dd5-721848486fb3.gif)

Code & tests in question:  https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs

**Comment by rishit-khandelwal** [comment]
Can i work on this issue?

**Comment by lnicola** [comment]
Sure!

**Comment by rishit-khandelwal** [comment]
Ok thanks!

**Comment by TheDoctor314** [comment]
@rishit-khandelwal Are you still working on this? If not, I would like to take it up.

**Comment by rishit-khandelwal** [comment]
@TheDoctor314 ah no I'm not working on it.
