### ISSUE TITLE
Rust-analyzer dies when there's an error in a tokio::select macro

### ISSUE THREAD

**Issue by FredrikNoren** [rust-analyzer/rust-analyzer#10051]
Hi,

First of all; thanks for an amazing tool!

However, I'm having an issue that several times per day rust-analyzer just seems to die and stops showing the cargo check messages (only showing a few seemingly random warning messages but no errors). I usually try to restart rust-analyzer, restart VS Code, and re-save random files at this point, and sometimes that helps but sometimes that doesn't even seem to help (I have no idea what makes it come back to life after that, perhaps a rebuild).

This is on OSX, rust-analyzer version 0.2.718, VSCode version 1.59.1, but the problem has been around since I started using rust-analyzer about a year ago.

Edit: I've realized that this only happens when there's an error in a `tokio::select!` macro.

**Comment by knopp** [comment]
Somewhat relevant, recently cargo check seems to misbehave in multi project workspaces (it only shows errors from one project).

**Comment by FredrikNoren** [comment]
I finally figured out when this is happening: it's when there's an error in a `tokio::select!` macro.

**Comment by lnicola** [comment]
@FredrikNoren can you make a test project which reproduces the issue? If not, I'll try to do it when I have some time.

**Comment by FredrikNoren** [comment]
@lnicola This stops producing "problems" in vscode for me:

```rust
use std::time::Duration;

#[tokio::main]
async fn main() {
    tokio::select! {
        x = tokio::time::sleep(Duration::from_secs_f32(1.)) => {
            let x = ;
        }
    }
    println!("";
}
```

**Comment by lnicola** [comment]
Confirmed, thanks for the lovely repro.

**Comment by Veykril** [comment]
Just
```rs
fn main() {
    tokio::select! {
        x
    }
}
```
is enough to get diagnostics stuck.
For one we hit the macro expansion depth limit, which happens due to us doing a bad recovery job for picking a macro matcher, since no matcher matches. That somehow causes us to end in a recursive arm which we repick over and over again. Though it is odd that this seems to get diagnostics stuck

**Comment by Veykril** [comment]
minimal macro that causes this
```rs
macro_rules! select {
    (@ { $($t:tt)* } ) => {
        // No `else` branch
        select!(@{ $($t)*; unreachable!() })
    };
    ( $p:pat = $($t:tt)* ) => {
        select!(@{ () } $p = $($t)*)
    };
    () => {};
}

fn main() {
    select! {
        x
    }
}

```

**Comment by Veykril** [comment]
Huh so this might be a code bug
```rs

macro_rules! f {
    () => {
        compile_error!("");
    };
}

f!();
```
breaks the diagnostics of the file, which I assume is because we post an empty diagnostics message(which also happens in the select macro, though I am not sure why that happens there)
