### ISSUE TITLE
proc macro server crashed for derive serde::Deserialize and bevy_ecs::schedule::SystemLabel

### ISSUE THREAD

**Issue by ElnuDev** [rust-analyzer/rust-analyzer#10064]
If I have any `struct` that derives `serde::Deserialize`,  `bevy_ecs::schedule::SystemLabel`, or possibly others I immediately get the entire block underlined in red with a `proc macro server crashed` error. Any ideas how to fix this? I'm running rust-analyzer v0.2.637 with VSCodium 1.56.0 on Pop!_OS 20.04 LTS. Thank you!

**Comment by lnicola** [comment]
Are you using a nightly toolchain? You should try upgrading rust-analyzer, in any case.

**Comment by ElnuDev** [comment]
I'm not on a nightly toolchain. I managed to fix the issue! I reinstalled my VSCodium snap package from the latest/edge channel (version 1.59.1) instead of latest/stable (1.56.0), and after doing so rust-analyzer updated itself to v0.2.710 and the problem went away.
