### ISSUE TITLE
WASM demo

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1007]
It would be super cool to have a web-page which demoes rust-analyzer by running it with WASM. This could be a prototype of a WASM-powered rust-playground, which, for example, does syntax checking on the fly. 

The MVP would probably be to compile ra to WASM and create a github page, with a text-area where you can edit rust code, and another text area where you see the syntax tree.

To make it **really** cool, we need to add Monaco editor with rust-analyzer powered syntax highlighting and simple completions support.

**Comment by georgio** [comment]
I could give that a shot and let you know if I come up with anything! Super cool idea :grin:

**Comment by matklad** [comment]
Recently introdced `Analysis::from_single_file` would be of help here:

https://github.com/rust-analyzer/rust-analyzer/commit/3eb56f7a6aab1e9814cb901c8cd90c2b4b3138af

**Comment by matklad** [comment]
For syntax highlighting, see https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodel.html#deltadecorations. We should **not** used the approximate monarch infra for this.

**Comment by detrumi** [comment]
There's still an issue with the proptest dependency, I've opened [proptest#137](https://github.com/AltSysrq/proptest/issues/137) and have a workaround branch [here](https://github.com/detrumi/proptest/commit/c3a2555fe74419238c7d9d364936504ddb84f32c) that can be used to patch `proptest`, using which I successfully built `ra_ide_api` using `wasm-pack` :tada:

**Comment by matklad** [comment]
I guess, just patching proptest in root `Cargo.toml` using `[patch]` to a git repo :)

**Comment by Lapz** [comment]
In the future we could just use https://devblogs.microsoft.com/visualstudio/intelligent-productivity-and-collaboration-from-anywhere/

**Comment by matklad** [comment]
We have wasm demo here now: https://github.com/rust-analyzer/rust-analyzer.github.io!

I bet it can be greatly improved, but I don't have capacity to drive the improvements. If you have desire to tinker with WASM, feel free to hack on it how you see fit!
