### ISSUE TITLE
Debounce `textDocument/didChange` events to avoid sending too many `$/progress` events

### ISSUE THREAD

**Issue by jenanwise** [rust-analyzer/rust-analyzer#10075]
I'm using `lsp-mode` with Emacs. It sends a `textDocument/didChange` event with every keystroke, which causes rust-analyzer to respond with thousands of immediate `$/progress` events. In some clients, this can cause client performance issues (see e.g. #7590). 

In my case, the issue is visual noise: `lsp-mode` displays each `$/progress` update in the modeline. These can be disabled by setting `lsp-progress-function` to `'ignore`, but loses important information (particularly when loading a new project). See also brotzeit/rustic#251 which I believe has the same root issue.

The `lsp-mode` devs on discord suggested that `rust-analyzer` should be debouncing the `textDocument/didChange` events, and that a similar fix was made with `clojure-lsp`.

**Comment by lnicola** [comment]
I don't think we want debouncing just yet because it adds latency and makes for a worse user experience.

Instead, we should stop sending those progress messages on each keypress, like in #9922.

**Comment by jenanwise** [comment]
Looks like 53d20500859fa22fb1c5d96a7c34d72d933ddbea solved it!
