### ISSUE TITLE
server panicked: internal error: entered unreachable code: disjunction in conjunction

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#10073]
Code that triggered this error (I was mucking around in hyper's code):

```rust
#[cfg(any(
    feature = "server",
    all(any(feature = "http1", feature = "http2"), feature = "client"),
))]
pub(crate) use std::marker::Unpin;
```

Logs:

```
thread '<unnamed>' panicked at 'internal error: entered unreachable code: disjunction in conjunction', crates/cfg/src/dnf.rs:157:36
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> 
version: 996300f4a 2021-08-23 dev
request: textDocument/codeAction CodeActionParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/home/jplatte/code/hyper/src/error.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 278,
            character: 53,
        },
        end: Position {
            line: 278,
            character: 53,
        },
    },
    context: CodeActionContext {
        diagnostics: [],
        only: None,
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}

thread '<unnamed>' panicked at 'internal error: entered unreachable code: disjunction in conjunction', crates/cfg/src/dnf.rs:157:36
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jonas-schievink** [comment]
Hmm, that snippet alone is not enough to reproduce the bug for me. And adding that `cfg` expression to the tests also results in a reasonable DNF expression: `#![cfg(any(feature = "server", all(feature = "http1", feature = "client"), all(feature = "http2", feature = "client")))]`.

**Comment by jplatte** [comment]
Oh, hm. Well I didn't save a snapshot of the repo when RA produced this error message unfortunately, and can't find a simple repro either. Should I close this?

**Comment by jonas-schievink** [comment]
No, it's still useful to track, in case someone else runs into this

**Comment by matklad** [comment]
Let's through [arbitrary](https://docs.rs/arbitrary/1.0.2/arbitrary/) at it? [This](https://github.com/rust-analyzer/rust-analyzer/blob/bb1987b45e90a4f4bceabe4added1998dc0b2092/crates/cfg/src/dnf.rs#L30) looks very amendable to property-based testing, and I want it to be easy to prop-test stuff in rust-analyzer. 

We did, and removed property-based tests for text edits, but that's because there wasn't a nice composable way to do prop-testing. 

With the arbitrary crate, I think we can now reasonably arbitrary all the things.

**Comment by matklad** [comment]
To clarify, I don't think we should outright libFuzzer it, but running arbitratry with just some random seeds might be enough.

**Comment by jonas-schievink** [comment]
Good call, it instantly found a reproducer: `#![cfg(all(all(any())))]`
