### ISSUE TITLE
RA flags many safe macro invocations as unsafe

### ISSUE THREAD

**Issue by spencerkohan** [rust-analyzer/rust-analyzer#10072]
Since updating to the most recent version of rust-analyzer,  I am getting many fals-positive `missing-unsafe` errors.

Basically every invocation of `format!`, `eprintln!` and `write!` macro results in a diagnostic complaining about a missing unsafe block.

When I run a cargo build, the diagnostics go away.

**Comment by bjorn3** [comment]
Probably a duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/10022. The next stable version will include the fix. Stable is released on Monday, so you can either switch to nightly which already includes the fix or wait ~12h.

**Comment by spencerkohan** [comment]
Seems to be working on nightly, thanks!
