### ISSUE TITLE
Const generics declaration is highlighted differently from uses

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#10077]
```rust
struct ByteArray<const C: usize>(ByteArrayInner<C>);

struct ByteArrayInner<const C: usize>([u8; C]);
```

![screenshot-2021-08-29-20:49:18](https://user-images.githubusercontent.com/1786438/131261998-5d0f5805-2215-41d1-bec4-d6a17f86e610.png)

The red `C` is expected, since we don't lower or resolve anonymous consts like array lengths, but the use of `C` in `ByteArray` should be colored the same way as the declaration.

**Comment by Veykril** [comment]
That might be an issue with your theme? They get tagged appropriately for me 
![Code_zJi8cS0zzD](https://user-images.githubusercontent.com/3757771/131262736-a9c96cb7-37df-4cd9-b022-2b036749626a.png)
![Code_bCs70h3tNS](https://user-images.githubusercontent.com/3757771/131262733-bf300041-3e78-4b34-ae48-b32b0f9c7014.png)

**Comment by jonas-schievink** [comment]
It doesn't seem to work with any of the built-in themes at least. Is that something we can/want to fix?

**Comment by Veykril** [comment]
We should be able to add a textmate scope mapping for this I believe, https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#custom-textmate-scope-mappings

**Comment by arzg** [comment]
The TextMate scope mappings are located here: https://github.com/rust-analyzer/rust-analyzer/blob/2e3322d3f536e619ec67d05846c1b1bac8b36721/editors/code/package.json#L1217-L1259
