### ISSUE TITLE
Merge ra_ide_api_light into ra_ide_api

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1009]
The original idea behind [ra_ide_api_light](https://github.com/rust-analyzer/rust-analyzer/blob/90ff3ba64133c1bcae9d49709c4dd704ae59b1ee/crates/ra_ide_api_light/src/lib.rs) was to allow light weight editors to run some analysis on a single file, without messing up with cargo, sysroot and file-system. Originally, it was restricted to only know about the syntax tree.

However, this separation proved to be harmless. Even for single file, you should be able to, say, run type inference, and that's not possible if you use **only** syntax trees. And *even* for pure syntax-tree operations like "extend selection" you want to try to expand macros!

We've recently introduced `Analysis::from_single_file` to create a fully-featured analysis from a single file, so now we can remove `ra_ide_api_light`. To do so, we should move its modules one-by-one into [ra_ide_api](https://github.com/rust-analyzer/rust-analyzer/blob/90ff3ba64133c1bcae9d49709c4dd704ae59b1ee/crates/ra_ide_api/src/lib.rs). See https://github.com/rust-analyzer/rust-analyzer/pull/1008 for an example. So, pick a module from a list, move it, check that test pass, refactor the code after movement, if necessary, send a PR!

* [x] folding_ranges
* [x] line_index
* [x] line_index_utils
* [ ] structure
* [x] test_utils
* [x] join_lines
* [ ] typing
* [x] diagnostics

**Comment by detrumi** [comment]
Working on `typing` now, alongside some refactoring of `LocalEdit` and such.

**Comment by pasa** [comment]
Seams that this issue can be closed by now.
