### ISSUE TITLE
Show deref target in ranged hover

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#10106]
While we are at it...

![image](https://user-images.githubusercontent.com/1711539/131378719-9d550f45-ecc2-4182-b2d7-fbb40f742469.png)

This should mention deref somehow. BTW, do we have an official name for winking pretzel `&*` ?

_Originally posted by @matklad in https://github.com/rust-analyzer/rust-analyzer/issues/9954#issuecomment-908530342_

**Comment by theo-lw** [comment]
I'd like to try working on this.

**Comment by lnicola** [comment]
Should this have been implemented in #10204? It doesn't work for me.

**Comment by lnicola** [comment]
Well, it does this:

![image](https://user-images.githubusercontent.com/308347/134001345-06a437a4-a027-4876-90f5-a1836d194b6d.png)
