### ISSUE TITLE
Deriving `serde::Serialize` causes an error to incorrectly be displayed

### ISSUE THREAD

**Issue by Smittyvb** [rust-analyzer/rust-analyzer#10104]
When a `struct` has `serde::Serialize` `#[derive]`d on it, rust-analyzer shows an error tooltip despite no actual errors occurring. [Here is a minimized example.](https://github.com/Smittyvb/ra-proc-macro-repro)
```
proc macro returned error: proc-macro panicked: called `Result::unwrap()` on an `Err` value: ParseFloatError { kind: Invalid }
```
![A tooltip on top of code that says "struct X" saying "proc macro returned error: proc-macro panicked: called `Result::unwrap()` on an `Err` value: ParseFloatError { kind: Invalid }", then saying "rust-analyzer(macro-error)" in gray](https://user-images.githubusercontent.com/10530973/131579277-b7aa1156-6164-427a-adab-9128e8e1e46a.png)

This was also happening to @Animeshz (https://github.com/rust-analyzer/rust-analyzer/issues/7100#issuecomment-858631472) and @Grimmp (https://github.com/rust-analyzer/rust-analyzer/issues/7100#issuecomment-859061227).

I am running `b641a6607 2021-08-16 stable` on VSCodium 1.57.1.

**Comment by lnicola** [comment]
Which Rust toolchain are you using and do you have any RA settings în Code?

**Comment by Smittyvb** [comment]
@lnicola It seems like this got fixed by updating rustc to the latest nightly. (RA settings are the default).
Broken:
```bash
$ rustc -V
rustc 1.56.0-nightly (a6ece5615 2021-08-03)
```
Fixed:
```bash
$ rustc -V
rustc 1.56.0-nightly (29ef6cf16 2021-08-31)
```
