### ISSUE TITLE
fn-like macros in attribute macros break IDE functionality

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#10115]
![screenshot-2021-09-02-01:01:24](https://user-images.githubusercontent.com/1786438/131756502-9e9c2e3b-79b5-422b-b6fa-06383eb5e0f4.png)

Turning attribute macros off fixes this and highlights everything correctly.

**Comment by jonas-schievink** [comment]
I am still seeing this in https://github.com/stm32-rs/bxcan/blob/master/testsuite/tests/integration.rs

**Comment by Veykril** [comment]
Oh okay so if I see this right, the cause now is that we can expand bang macros in the non-attribute expanded item as well as the attribute expanded item. So the current logic expands the bang call in the non-attribute expanded items which probably messes with token ids.
