### ISSUE TITLE
Suppress "Overly long loop turn" messages until workspace has been loaded

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#10120]
I am seeing a number of these pop up when loading the rust-analyzer workspace. They should probably be suppressed until the workspace has been fully loaded/indexed.

**Comment by flodiebold** [comment]
Even during loading, we shouldn't have overly long loop turns, I think? Maybe it's only due to CPU usage, but still.

**Comment by lnicola** [comment]
Do you happen to have logging enabled?

**Comment by brunojabs** [comment]
I'm seeing this message as well.
I see that it's just a warning, but my editor thinks treats it as an error. 

I would appreciate some help on how to suppress this at least for nvim + lspconfig

Thanks in advance

**Comment by polyzen** [comment]
@lnicola, doesn't seem to do the trick. What I tried:

```diff
diff --git a/lua/lspconfig/rust_analyzer.lua b/lua/lspconfig/rust_analyzer.lua
index bbe86b3..f19d750 100644
--- a/lua/lspconfig/rust_analyzer.lua
+++ b/lua/lspconfig/rust_analyzer.lua
@@ -14,6 +14,9 @@ end
 configs.rust_analyzer = {
   default_config = {
     cmd = { 'rust-analyzer' },
+    cmd_env = {
+      RA_LOG = 'rust_analyzer=error'
+    },
     filetypes = { 'rust' },
     root_dir = function(fname)
       local cargo_crate_dir = util.root_pattern 'Cargo.toml'(fname)
```

**Comment by lnicola** [comment]
Sorry, I'm not really familiar with `nvim-lspconfig`, I'd try `export RA_LOG=rust_analyzer=error`.

But are you maybe building from source or do you have `RA_PROFILE` set somewhere? What does `rust-analyzer --version` say?

**Comment by Veykril** [comment]
Source builds always print these messages unconditionally, https://github.com/rust-analyzer/rust-analyzer/blob/ed4b312fa777ebb39ba1348fe3df574c441a485e/crates/rust-analyzer/src/lsp_utils.rs#L61-L67

You could set the `RUST_ANALYZER_REV` to something custom that does not contain `dev` when building the server to get around this for example, as `REV` is being set here https://github.com/rust-analyzer/rust-analyzer/blob/079e9fe49645fab8cb20a8cfb2da81915f018b04/crates/rust-analyzer/build.rs#L30-L51

**Comment by lnicola** [comment]
Oh, I didn't realize you were the Arch packager.

Well, this is awkward: https://github.com/rust-analyzer/rust-analyzer/blob/5fb2eb23148afc109b6ea9c12d5627bbff4318f0/crates/rust-analyzer/src/lsp_utils.rs#L61. We set `REV` in the GitHub binaries to prevent the message from showing up.

**Comment by polyzen** [comment]
Thank you both for the resolution!

**Comment by Milo123459** [comment]
I presume this is related, but when I open the rust repo locally I get loads of these: 
<img width="344" alt="image" src="https://user-images.githubusercontent.com/50248166/148645037-49d92b54-354d-4c11-8d1c-91f8c8b94d21.png">

I want to try and fix this but I'm not exactly sure how: could someone point me in the right direction? Thanks.

**Comment by Veykril** [comment]
From the looks of it you probably only have to add a check to this part here for whether the global state was quiescent(there is a var `was_quiescent` there already). Not 100% sure though
https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/rust-analyzer/src/main_loop.rs#L527-L533

**Comment by Milo123459** [comment]
Created #11287

**Comment by glepnir** [comment]
open rust in neovim and do quick edit no wait rust_analyzer init this message also print. because it's output of `window/showMessage` . and the `MessageType` is  `1` (Error). when it's error type neovim will popup it . I saw rust_analyzer use `tracing::warn!` macro to record this .so I think it's not very important right ? can change it `MessageType` to warn of info (2 or 3) ?
