### ISSUE TITLE
Generate function assist should default the return type to _ instead of ()

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#10123]
This will unconditionally result in a compiler error, but a rather useful one:

```rust
fn f() -> _ {
    vec!["hello, world".to_owned()]
}
```

```
error[E0121]: the type placeholder `_` is not allowed within types on item signatures
 --> src/lib.rs:1:11
  |
1 | fn f() -> _ {
  |           ^
  |           |
  |           not allowed in type signatures
  |           help: replace with the correct return type: `Vec<String>`
```

Maybe this error / assist could even be added to rust-analyzer, so after generating a function and filling in the body you would only have to accept its suggestion for filling the return type (as opposed to having to save, then wait for `cargo check`).

**Comment by Veykril** [comment]
We already have an assist to add a functions return type in case its not written out or written as `-> _`/`-> `. So it would make sense to me that we should put a `_` instead of `()` here.
