### ISSUE TITLE
feature request: scope lead-in peek / lens (vscode)

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [rust-analyzer/rust-analyzer#10131]
For particularly long scopes it can be easy to get lost while scrolling, especially if the code is similar throughout the function. I then scroll back up to double-check which if/else, match etc I'm in.

Just to clarify, I'm using the work scope here for sections of code between brackets -- so the inside of an `if` or `match` etc.

I was thinking of having a view of the current scope lead-in pinned at the top while scrolling through long sections. Say for example you're in an `if` statement, then the `if condition` would be pinned to the top once its out of view. One could have multiple pinned levels for nested scopes. Multi-line condition / scope entry text would need special consideration, but I'm sure one can make a compromise somehow.

This is not an issue for functions themselves since vscode can show the function path at the top already.

Similar extensions
- [bracket lens](https://marketplace.visualstudio.com/items?itemName=wraith13.bracket-lens)
- [bracket peek](https://marketplace.visualstudio.com/items?itemName=jomeinaster.bracket-peek) (doesn't work at all for me)

Issue with these extensions is that they just don't take into account the language, but simply use the text of the line prior to the scope.

**Comment by Veykril** [comment]
cc https://github.com/rust-analyzer/rust-analyzer/issues/7315

**Comment by Mirko-von-Leipzig** [comment]
> 
> 
> cc #7315

Thanks I would never have found that.
