### ISSUE TITLE
Importing a sibling of an enum wildcard moves the wildcard to the module

### ISSUE THREAD

**Issue by teor2345** [rust-analyzer/rust-analyzer#10136]
When I am importing all enum variants using a wildcard, then I use Rust Analyzer to import another item from the same module, it puts the wildcard on the module.

But I expect the wildcard to stay on the enum.

I'm using emacs, lap-rust, and nightly rust analyzer 2021-08-22.

Steps to reproduce:
1. Import all variants of an enum using a wildcard
2. Import an item in the same module as the enum, using the Rust Analyzer action

Minimal reproducible code:
1. `use m::Foo::*`
2. Import `m::Baz` using the Rust Analyzer action

```rust
mod m {
    pub enum Foo {
        Bar,
    }

    pub struct Baz;
}

use m::Foo::*;

fn main() {
    let _ = Bar;
    let _ = Baz;
}
```

Sorry about the lack of a video in this bug report.
If it would help, I'll try to do one when I get time.

**Comment by dzvon** [comment]
Can't be reproduced with `rust-analyzer d15f646ff 2021-08-31`.

**Comment by lnicola** [comment]
Yeah, I can't reproduce it either.

**Comment by lnicola** [comment]
@teor2345 does this still happen in a newer version?

**Comment by teor2345** [comment]
I can't manage to reproduce it with `rust-analyzer f1d7f98 2021-09-23 dev`.

(If I see it again, I'll double-check that I have a working reproduction.)
