### ISSUE TITLE
"Reached recursion limit during macro expansion"

### ISSUE THREAD

**Issue by BlackDex** [rust-analyzer/rust-analyzer#10134]
Hello there, i use RA main for the following project https://github.com/dani-garcia/vaultwarden and when i open `config.rs` i get the macro recursion error. The main problem here is that RA has a limit of 128, while the project it self has a limit set of 512 in `main.rs`. Is there some way that we can increase this limit manually per workspace or have it read the main/lib.rs file or something?

**Comment by bjorn3** [comment]
The limit it is hard-coded: https://github.com/rust-analyzer/rust-analyzer/blob/43ed5368d2a54e3332f4cafadd2d5f666fcd2337/crates/hir_def/src/body.rs#L60 Rust-analyzer doesn't read `#![recursion_limit = "512"]`, nor does it provide any other way to configure it.

**Comment by lnicola** [comment]
Here's what the crates I have in my cargo registry use:

```
$ rg -NI '^#!\[recursion_limit\s*=\s*"(\d+)"\]' -r '$1' -o ~/.cargo/registry/src | sort | uniq -c
      2 100
      1 1000
    184 1024
    122 128
      1 1500
      2 192
      1 196
      4 200
     13 2048
     68 256
      3 2563
      2 4096
      9 500
     38 512
      1 750
```

**Comment by BlackDex** [comment]
Well maybe i should rephrase my question then. Would it be possible to add a way to configure this item per workspace 😄

Since as seen in the output above, it is used a lot and a lot is above 128.

**Comment by lnicola** [comment]
Ah, I forgot to write my conclusion. It would be nice to make it configurable, but increasing the limit a little might not so terrible in the meanwhile.

**Comment by BlackDex** [comment]
I have lowered the amount of recursion to 87 right now for the project.
Though, a configurable option could be nice, i think I'm going to close this.
