### ISSUE TITLE
feature request: Promote / Downgrade module

### ISSUE THREAD

**Issue by longfangsong** [rust-analyzer/rust-analyzer#10143]
IntelliJ's Rust plugin supports:
- Promote Module to directory, which means make a `.rs` file module into a directory style module with the same name.
- Downgrade Module to file, which means make a directory style module with only a `mod.rs` inside into a file module.

I use these feature a lot, but when migrating to vscode and rust-analyzer, I found there're no such things.

So is it possible for rust-analyzer to support these?

(I'd love to have a try to implment this feature if you think this is a good idea.)

**Comment by lnicola** [comment]
There's a ["Move inline module to file"](https://github.com/rust-analyzer/rust-analyzer/blob/f0f0278ebe4c48cb8f9986e485d4746cb96ce4ed/crates/ide_assists/src/handlers/move_module_to_file.rs) assist that might work as a starting point.
