### ISSUE TITLE
Question: Any way to set settings without editing global settings

### ISSUE THREAD

**Issue by JulianRuiseco** [rust-analyzer/rust-analyzer#10140]
I have several different linkedProjects for each of my repos. Example below

```
"rust-analyzer.linkedProjects": [
  
    "./src/bevy_egui/src/egui-0.14.2/cargo.toml",
    "Cargo.toml",
    "./src/dig_line_optimizer/Cargo.toml",
    "./deps/rust-bridge/src/declusterer/Cargo.toml",
    "./deps/rust-bridge/Cargo.toml"
  ],
```

Is there any way for me to save this on the folder instead of global settings so I don't have to have this shared for all my projects?

**Comment by bjorn3** [comment]
VSCode allows per workspace settings using the `.vscode/settings.json` file in the workspace directory. You can put `"rust-analyzer.linkedProjects"` there. See for example https://github.com/bjorn3/rustc_codegen_cranelift/blob/ddaa7459b2f6e4a8840f038003417d0b0037b859/.vscode/settings.json#L8

**Comment by JulianRuiseco** [comment]
Thank you very much!
