### ISSUE TITLE
RA not working when using `#[tonic::async_trait]`

### ISSUE THREAD

**Issue by n1c00o** [rust-analyzer/rust-analyzer#10150]
This is a serious regression in nightly and it's important to fix it before the next release.
@matklad, please take a look.

Hi. For more than two hours, I tried debugging my VSCode since Rust-Analyzer was not working while I was implementing a gRPC Service using `tonic`.
By not working I mean that I do not get any autocompletion/IntelliSense for variables, structs, functions...
However, I still get errors reported by `cargo check`.

I figured out that when I was implementing methods in `#[tonic::async_trait]`, Rust-Analyzer was not working, but when I remove `#[tonic::async_trait]` Rust-Analyzer is working.

I chose the **Critical Nightly Regression** since Rust-Analyzer is unusable in `#[tonic::async_trait]` and working in `#[tonic::async_trait]`-like traits is pretty common. *(Sorry if it was not the good choice)*

## Versions

Code-Insider
```sh
1.61.0-insider
87260247dc7b912db6e6a21a366e6f50dca759ba
x64
```

In WSL2 on Windows 10

**Comment by matklad** [comment]
To clarify, is is the case that every version of rust-analyzer isn't working for you? Or is there some version that used to work, and it's just the latest nightly that's broken?

**Comment by n1c00o** [comment]
I had the same problem yesterday. Since I got a new RA update today and it is also not working, I guess the problem exists in multiple nightly versions.

**Comment by matklad** [comment]
Ok, so my understanding is that is not a regression that -- it's just that this never fully worked in the first place. The current state is:

* you can set `"rust-analyzer.experimental.procAttrMacros": true`, which will enable better completions *outside* of proc macroed code, at the cost of completely disabling completion inside, eg, impls annotated with `#[async_trait]`
* you can set `"rust-analyzer.experimental.procAttrMacros": false`, then you'll have partial completions both inside and outside of the macros
* you can try #10126 -- it is the next step in us fully supporting the feature. Locally it doesn't work for the example from [async_trait](https://docs.rs/async-trait) though (cc @Veykril). 

We understand that fully supporting async_trait and the like is important for adequate UX in may cases -- it's just that procedural macros are in general a pain in the back to support in an IDE. We are working on it, but it's hard :)

**Comment by n1c00o** [comment]
Thanks for the response! 
I totally understand it is a pain and I wish good lucks to you guys. I disabled `"rust-analyzer.experimental.procAttrMacros": false` for now and it work as expected for now.
