### ISSUE TITLE
Missing `::` on editor hover tip

### ISSUE THREAD

**Issue by EFanZh** [rust-analyzer/rust-analyzer#10172]
See this screenshot:

![hover](https://user-images.githubusercontent.com/2160692/132277707-94a41a1f-3289-4bc0-874b-119b18031591.png)

I expect the hover tip shows `fn foo() -> crate::X`, but I got `fn foo() -> crateX`, the `::` is missing.

**Comment by lnicola** [comment]
Also

```rust
struct X;

mod m {
    fn foo() -> super::X {
        X
    }
}

fn main() {
    m::foo()
}
```
