### ISSUE TITLE
macro-error, when using  #[cfg_attr(test, derive(Serialize))]

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rust-analyzer/rust-analyzer#10189]
https://github.com/IWANABETHATGUY/vue-template-compiler/blob/4a2f334692f82776a5558e89b3203ef64322817e/src/core/error.rs#L7
![2021-09-10 01-14-56 的屏幕截图](https://user-images.githubusercontent.com/17974631/132732059-ff420bb6-8d49-40e0-93b8-52b7b71f491a.png)

restart the rust-analyzer does't resolve this issue

**Comment by IWANABETHATGUY** [comment]
varsion: 1.60.0
commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
date: 2021-09-01T10:43:02.136Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-27-generic

**Comment by lnicola** [comment]
FWIW, I can't reproduce this. What error are you getting and which rust version are you using?

![image](https://user-images.githubusercontent.com/308347/132870622-9a5f40a4-d093-4746-a5e8-eb2d22cc5d77.png)

**Comment by IWANABETHATGUY** [comment]
broken with rust nightly, works fine with latest stable release

**Comment by IWANABETHATGUY** [comment]
Thanks!

**Comment by lnicola** [comment]
If it doesn't work, we want to fix it, but it seems fine for me on `rustc 1.57.0-nightly (fdf65053e 2021-09-07)`.
