### ISSUE TITLE
Steps for getting function signature info

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#102]
What are the steps involved in determining function signature information? I want to take a crack at implementing `textDocument/signatureHelp` and I think this could also be used in `hover`.

**Comment by matklad** [comment]
The main thing would be resolving function call to a definition: given a call like `foo(42)`, finding a corresponding `fn foo(param: i32) { ... }`. I *think* that `approximately_resolve_symbol` might actually work good enough for this.

The signature should be constructed from an `FnDef` straightforwardly: iterating over formal parameters and collecting types. There's `param_list` method to get parameters.

**Comment by kjeremy** [comment]
That gets me pretty close. I think we may need something like
`approximately_resolve_symbol` that returns ast nodes instead of
`FileSymbol` that we can then layer things on top.

**Comment by matklad** [comment]
>that returns ast nodes

It might be prudent to return some `FnDescriptor` object, which stores an AST node inside: besides functions, there are tuple structs, which also work like function calls, and signature help should handle both of them:

```
struct Foo(i32, String);

fn main() {
    let foo = Foo(92, "hello".to_string())
}

```

**Comment by kjeremy** [comment]
Ok I have something that sort of works. One issue I'm having is determining which parameter we are currently on when editing.

```rust
        let root = self.root(file_id);
        let file = root.syntax(file_id);
        let syntax = file.syntax();

        // Find the calling expression
        let call_expr: ast::CallExpr = find_node_at_offset(syntax, offset)?;
        let call_offset = call_expr.syntax().range().start();

        // If we have a calling expression let's find which argument we are on
        let mut current_parameter = None;
        if let Some(arg_list) = call_expr.arg_list() {
            current_parameter = arg_list.args()
                .position(|arg| contains_offset_nonstrict(arg.syntax().range(), offset ));
        }
```

I think my usage of `contains_offset_nonstrict` is incorrect since `current_parameter` is always `None`. I'm trying to determine which argument the cursor is on.

**Comment by matklad** [comment]
Hm, on the first blush everything seems correct. One common gotcha with offsets is mixing absolute offsets (from the beginning of the file) and relative offsets (from the beginning of node). We try to use abs offsets everywhere, and this code also seems correct in this case.

Perhaps

```
            current_parameter = arg_list.args()
                .inspect(|arg| eprintln!("{:?} {}", arg.syntax().range(), offsets))
                .position(|arg| contains_offset_nonstrict(arg.syntax().range(), offset ));

```

will explain what's going on?
