### ISSUE TITLE
use `Ctrl+.` or `Alt+shift+.` to override methods that give me message that is `no auto fixes available` 

### ISSUE THREAD

**Issue by shuqiangzhou** [rust-analyzer/rust-analyzer#10205]
vs code version
```
Version: 1.60.0 (user setup)
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:41:52.311Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19041
```
RA version:
v0.2.735

How I can to fix it?

![image](https://user-images.githubusercontent.com/26402118/132952816-030a3bf4-8d7f-4965-af2b-370117a34d19.png)

**Comment by lnicola** [comment]
Strange, you should get an "Implement missing members" assist on `Display`.

**Comment by lnicola** [comment]
Do you have any errors in the Output panel, if you select any of the Rust Analyzer entries? And can you test it in an empty project?

**Comment by shuqiangzhou** [comment]
![image](https://user-images.githubusercontent.com/26402118/132953702-f22dac4b-1334-4e18-91fb-55d41a5a541f.png)

No any errors

**Comment by jonas-schievink** [comment]
VS Code is saying "auto fixes", but `Ctrl+.` should run the "Quick Fix" command. I don't get any fixed either when I run the "Auto Fix" command. Maybe your keyboard shortcuts are misconfigured?

**Comment by shuqiangzhou** [comment]
I'm keyboard shortcuts is misconfigured,when I misconfigured of the  "Quick Fix" command,use `Ctrl+.`,it's ask for me `implement missing members`,use `Ctrl+shift+.` ask for me `no auto fixes available`
