### ISSUE TITLE
Fill struct fields action sometimes put fields to the beginning of file

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#10217]
Let's say I called this action at line `156`
![image](https://user-images.githubusercontent.com/33961674/133042772-4024cdef-58bb-48fd-8a88-9f9480899402.png)

the fields went to line `10` however and it broke lint
![image](https://user-images.githubusercontent.com/33961674/133042906-c4a8d2f3-5587-4dc3-931a-e6dc8088a6ea.png)

**Comment by GopherJ** [comment]
if I continue to call this action, fields went to the same place but just after the previous element
![Uploading image.png…]()

**Comment by lnicola** [comment]
Is that on `parallel`?

**Comment by lnicola** [comment]
Duplicate of #5393.
