### ISSUE TITLE
Add assist to turn `while` loop into `loop` loop

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#10214]
Before:

```rust
while cond {
    foo();
}
```

After:

```rust
loop {
    if !cond {
        break;
    }

    foo();
}
```

This is useful when editing code to add more complex conditions or control flow.

**Comment by agluszak** [comment]
This seems to be a rather simple addition, right? Could I take it as my first contribution to rust-analyzer? :)

**Comment by Veykril** [comment]
It's all yours
