### ISSUE TITLE
Can't go to definition in the files non member of workspace

### ISSUE THREAD

**Issue by eldenpark** [rust-analyzer/rust-analyzer#10227]
I am experiencing an issue where I can't go to the definition of symbols written in the files that are not members of the workspace. 

The project is configured the following way.

```
<project_root>
- member1
-- src/main.rs
- non_member1
-- src/main.rs
- Cargo.toml // (1)
```

Project root level `Cargo.toml` (1) is defined this way. Just so we know, if I don't specify `exclude` here, language server complains.

```toml
[workspace]
members = [
  "member1"
]

exclude = [
  "non_member1"
]
```

We might be able to assume all the members and non-members are just empty fresh-out-of-cargo packages because that is what seems to matter here.

Now, when I open VSCode from the project root, and attempt to go to the definition of any symbol written in non_member1 `non_member1/src/main.rs`, it finds nothing, even the function that is defined within the same file `non_member1/src/main.rs`. In contrast, going into `println!`, for instance, from a member file such as `member1/src/main.rs` works as expected.

When I open VSCode at `non_member1`, it can correctly go to the definition whether that's standard library `std` or local functions. When opening non_member1, VSCode knew that it is inside the umbrella "workspace" project and corrected me to specify `exclude` in root-level `Cargo.toml`.

What could be an issue here? Am I missing something in the configuration? I tried to find some previous reports of any such thing without any success.

**Comment by lnicola** [comment]
You're excluding `non_member1` from the workspace, so we don't load it.

**Comment by eldenpark** [comment]
@lnicola So in a workspace project where there might be some unavoidable "excluded" members, we can't get the functionality of "go-to-definition" in those excluded ones. For your information, I did the exclusion in order to keep the build-automation-related codebase (written in Rust) separate from the core. I'll check if there are other ways to organize the project.

Part of me tells that there might be such a need in various scenarios though. But if this is the decision the community has made, I'll take it as it is. Thanks for the answer.

**Comment by lnicola** [comment]
You could use a Code workspace containing the two (or more) projects and open either the Cargo workspace or the Code one, when you need it.

> But if this is the decision the community has made, I'll take it as it is.

It's not a decision. We run `cargo metadata` to detect the projects and dependencies between them, and `cargo check` for `rustc` diagnostics. Neither of works for excluded projects from a workspace.

Exclusions mean "there's no code here, don't look at it", which is in direct conflict with what you seem to want.

**Comment by eldenpark** [comment]
> You could use a Code workspace containing the two (or more) projects and open either the Cargo workspace or the Code one, when you need it.

Never thought we could also achieve something similar with Code's `workspace`. Good to know.

> rust-analyzer has that too, but it's code that's part of the workspace. We want to know if it builds, and we want to be able to work on it with all the IDE features available.

Yes, it looks like I might just as well include the component as part of the project as many other projects including rust-analyzer do.

Closing this issue.
