### ISSUE TITLE
match <-> if-let assist should have better target ranges

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#10220]
```rust
                if let Some(' ' | '!' | '/') = contents.chars().next() {
                    contents = &contents[1..]
                }
```

here, the "if-let to mach" assist is available in the whole body:

https://github.com/rust-analyzer/rust-analyzer/blob/c45792ae8f1e39aba86d2999482ee9f1a7c6e4a5/crates/ide_assists/src/handlers/replace_if_let_with_match.rs#L82

Instead, it should only be avaialbe between `if` and `{`. 

While we are at it, we should also audit other assist to check if their ranges can be narrowed down.

**Comment by vringar** [comment]
Why is this issue not closed, when the respective PR has been merged?

**Comment by matklad** [comment]
Good call!

**Comment by lnicola** [comment]
> While we are at it, we should also audit other assist to check if their ranges can be narrowed down.

**Comment by lnicola** [comment]
I don't know, it might still be easier to file issues when we spot these than to check the code.

**Comment by matklad** [comment]
It’s a bit hard to spot this, unless you know what to look for: if you are not aware about impl details (target-range), than the “bug” manifests as slightly annoying ide

**Comment by rainy-me** [comment]
> While we are at it, we should also audit other assist to check if their ranges can be narrowed down.

Yes this is the reason I didn't let https://github.com/rust-analyzer/rust-analyzer/pull/10267 close this issue. I did take a look at other assists but not very sure about their original intended target range. Maybe it's better to have a tracking list and have each assist's the target range documented and tested?

**Comment by Veykril** [comment]
`add_missing_match_arms` is another candidate we give a better target range to, its currently applicable everywhere in a match expression.

**Comment by Veykril** [comment]
I went through most assists we have and didn't find any unusual target ranges anymore(we also addressed a bunch since this issue came to be).
