### ISSUE TITLE
Proc macros crash on nightly

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#10235]
Because the following method is not implemented:

       3: <proc_macro_srv::abis::abi_1_56::rustc_server::Rustc as proc_macro_srv::abis::abi_1_56::proc_macro::bridge::server::Span>::save_span

**Comment by jonas-schievink** [comment]
What macro is needed to reproduce this? `serde::Serialize` doesn't seem to be enough

**Comment by lnicola** [comment]
I saw it on `analysis-stats`  IIRC.
