### ISSUE TITLE
failed to load workspace: Failed to read Cargo metadata from Cargo.toml file

### ISSUE THREAD

**Issue by AuroraLantean** [rust-analyzer/rust-analyzer#10242]
rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /mnt/sda5/0Programming/Solana/1project1/Cargo.toml, cargo 1.55.0 (32da73ab1 2021-08-23): Failed to run `cargo metadata --manifest-path /mnt/sda5/0Programming/Solana/1project1/Cargo.toml`: `cargo metadata` exited with an error: error: package `/mnt/sda5/0Programming/Solana/1project1/farmStaking/programs/farm/Cargo.toml` is a member of the wrong workspace
expected: /mnt/sda5/0Programming/Solana/1project1/Cargo.toml
actual:   /mnt/sda5/0Programming/Solana/1project1/farmStaking/Cargo.toml

My project structure is
- Cargo.toml (root Cargo.toml)
|- farmStaking/Cargo.toml
|- farmStaking/programs/farm/Cargo.toml

root Cargo.toml:
```
[workspace]
members = [
    "farmStaking/programs/farm",
]
exclude = [
    "tests/*",
]
```

farmStaking/Cargo.toml
```
[workspace]
members = [
    "programs/*"
]
```

farmStaking/programs/farm/Cargo.toml
[package]
name = "farm"
version = "0.1.0"
description = "staking farm program"
edition = "2018"
...

**Comment by bjorn3** [comment]
You need to exclude `farmStaking/programs/farm` from the inner workspace. You ae currently saying that it belongs to both workspaces, which isn't allowed.

**Comment by AuroraLantean** [comment]
Hi, thank you. did you mean to change farmStaking/Cargo.toml into the following ?
```
[workspace]
members = [
    "programs/*"
]
exclude = [
    "farmStaking/programs/farm",
]
```

**Comment by bjorn3** [comment]
The exclude should be

```toml
exclude = [
    "programs/farm",
]
```

**Comment by AuroraLantean** [comment]
farmStaking/Cargo.toml
```
[workspace]
members = [
    "programs/*"
]
exclude = [
    "programs/farm",
]
```
Oh I see. The first the root Cargo.toml has already specified the members: ["farmStaking/programs/farm",], so the second Cargo.toml should not specify it again. Wow. it is working now! Thank you!
