### ISSUE TITLE
rust-analyzer doesn't pass attributes to derive macros the same way rustc does

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#10246]
I have a proc-macro that uses doc comments. It gets invoked through a `macro_rules!` macro which seems somewhat relevant, but I can actually reproduce the issue by writing out `#[doc = "something"]` and bypassing the `macro_rules!` macro:

```rust
#[doc = "some docs"]
#[derive(SomeMacroThatFailsIfThereIsNoDocAttribute)]
pub struct MyStruct;
```

Works with rustc, fails with rust-analyzer.

**Comment by Veykril** [comment]
Ah we are stripping all attributes up to after the derive that is being expanded currently, https://github.com/rust-analyzer/rust-analyzer/blob/726a2aa211974a6bb1a612fe8824df7baf59faf6/crates/hir_expand/src/db.rs#L321-L328
Instead we only want to strip the derive attributes in that range here.
