### ISSUE TITLE
Inlay hint for parameter is included in VSCode bracket highlighting 

### ISSUE THREAD

**Issue by FylmTM** [rust-analyzer/rust-analyzer#10255]
In VSCode "Editor: Match Brackets" configuration is by default set to "always".

For some reason VSCode considers inlay hint that is near bracket as part of said bracket.

Example:
![image](https://user-images.githubusercontent.com/626772/133597170-1af75113-de96-4759-b5f1-7f3f88ef3722.png)

In screenshot above it can be seen that `input:` inlay hint is outlined together with bracket.

Expected behaviour: only bracket is highlighted.

**Comment by lnicola** [comment]
Inlay hints are basically a hack, which is also why the cursor movement is weird around them. Future Code versions will have built-in inlay hint support which might still be buggy in the same or in different ways.

**Comment by FylmTM** [comment]
@HKalbasi Yeap, I can confirm that in provided link problem does not exists anymore ❤️

**Comment by Veykril** [comment]
This is now fixed with us having swapped to the native hints.
