### ISSUE TITLE
Feature: wrap string with format! macro

### ISSUE THREAD

**Issue by gilescope** [rust-analyzer/rust-analyzer#10258]
Please if someone's got the time:

`"hello {}"`
  ^--- would be great to have an option to wrap with `format!` and changes it to:
`&format!("hello {}", <I>)`

where `<I>` is the new location of the cursor

(why: quite often you want to add something into an &str string so you add {} and then you have to surround it with the format macro. I think adding the `&` before the format! is a nice touch too because it was a &str before so that makes it still be one.)

**Comment by lnicola** [comment]
Don't we already have a format postfix completion?

Anyway, format string literals can't come soon enough :-).

**Comment by gilescope** [comment]
Nice, didn't see that. That's just as good.
