### ISSUE TITLE
Rust Source not found under Gentoo with Portage installation

### ISSUE THREAD

**Issue by AZMCode** [rust-analyzer/rust-analyzer#10262]
I've recently installed Gentoo and have been setting up a developer environment and found that rust-analyzer cannot find rust sources the same way rust RLS can if Rust is installed under Portage.

As far as I can tell, this is caused because the std library sources are not under the path reported by `rustc --print sysroot`, which in my current installation is `/usr/lib/rust/<version>`. Instead rust sources installed under Portage are located under `/usr/lib/rustlib-<version>`, at least as far as I can tell.

Whatever the case may be, it appears rust-analyzer does not have an option to set the directory under which to look for sources to the std lib, and they might be useful in cases like this.

**Comment by bjorn3** [comment]
This would be a bug in the way gentoo patches rustc. The source has to be at `$(rustc --print sysroot)/lib/rustlib/src/rust`. Both rust-analyzer and `cargo -Zbuild-std` depends on this too. RLS doesn't depend on the standars library source at all. Instead it depends on the save-analysis files which are stored somewhere else.

There should be a symlink created by ebuild though: https://github.com/gentoo/gentoo/blob/6db838d02c636a09a735bd787e4616fa9f496620/dev-lang/rust/rust-1.55.0.ebuild#L612

**Comment by AZMCode** [comment]
Thanks for the guidance, I'll keep chasing this rabbit hole. Closing.
