### ISSUE TITLE
Generate function assist creates bad param names for const/static item args

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#10278]
```rs
const VALUE: usize = 0;
fn main() {
    foo(VALUE);
}
```
generates
```rs
fn foo(v_a_l_u_e: usize) {}
```
we should special case the naming heuristic to consider `value` as a name here, that is for arguments that are `const` or `static` items we should just simply lowercase all chars.

Relevant code is here https://github.com/rust-analyzer/rust-analyzer/blob/a435e49d34bc8cd0129b4440f4804c987acc1b31/crates/ide_assists/src/handlers/generate_function.rs#L511

**Comment by Veykril** [comment]
Alternatively, it might also make sense to just not insert underscores between neighbouring capital letters in general instead.

**Comment by lnicola** [comment]
What does rustc do here?

**Comment by Veykril** [comment]
is there any occasion where rust even does such a conversion? I guess here for `let FOOBAR = ...` it seems to propose `foobar`.

**Comment by lnicola** [comment]
Yeah, I think our code for this was borrowed from the rustc suggestions.
