### ISSUE TITLE
`into_iterator` on `Vec` is not resolved in nightly

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#10296]
```rust
fn main() {
    let mut x = Vec::new();
    x.push(42);
    x.into_iter();
}
```

![image](https://user-images.githubusercontent.com/308347/134025787-119a419a-8dc2-4d62-b1bb-9fbd40282ca9.png)

Tested on `rustc 1.57.0-nightly (51e514c0f 2021-09-12)`.

**Comment by jonas-schievink** [comment]
This is working on `rustc 1.57.0-nightly (9dbb26efe 2021-10-03)` and current r-a master

**Comment by lnicola** [comment]
Confirmed.
