### ISSUE TITLE
custom path for lldb-vscode in Debug code-lens for tests

### ISSUE THREAD

**Issue by jan-xyz** [rust-analyzer/rust-analyzer#10308]
Is it possible to specify the path to the LLDB-vscode binary? I searched the docs and also this repo and the lldb-vscode repo to no avail.

Any call to the debug code-lens on tests comes back with `lldb-vscode not found. Please install lldb`. I installed `llvm` via Homebrew and the binary can be found at `/usr/local/opt/llvm/bin/lldb-vscode`.

**Comment by lnicola** [comment]
It might be worth adding it to `PATH`, so it works everywhere.

**Comment by jan-xyz** [comment]
Thanks for the quick reply. I am usually able to configure the path, but I'm also OK with extending my `PATH`

Would you symlink the binary itself it to somewhere like `/usr/local/bin` or would you add `/usr/local/opt/llvm/bin/` to `PATH`?

**Comment by lnicola** [comment]
It doesn't matter, try whichever you prefer so you don't get surprised next time you look for it (assuming you're relatively consistent about these things).

By the way, I don't think we invoke `lldb-vscode` (I don't even know what it does). Doesn't `vadimcn.vscode-lldb` already package it?

**Comment by jan-xyz** [comment]
I am not in vscode, but in `neovim` so I can't install `vadimcn.vscode-lldb`, that's why I installed `lldb-vscode` via Homebrew.

**Comment by lnicola** [comment]
How does it work? Who runs `lldb-vscode`?

**Comment by jan-xyz** [comment]
I assume that `rust-analyzer` does that, I am just invoking the code-lens from the neovim built-in lsp-client

**Comment by bjorn3** [comment]
Rust-analyzer doesn't invoke a debugger. It tells an existing debugger extension to start a debugging session for the given executable. Do you have a debugger extension installed?

**Comment by jan-xyz** [comment]
I'm lost. I don't know how to answer your question. I don't have any debug extension installed. Is there anything I can do? Is the debugger only supported in vscode?

**Comment by lnicola** [comment]
The Code extension looks for a couple of known debugger extensions and nudges them when required. `rust-analyzer` doesn't do anything else for debugging.

If your setup is working, I guess that's fine. If not, you can look into a Vim debugging extension.

**Comment by jan-xyz** [comment]
it works after adding it to my `PATH`

**Comment by lnicola** [comment]
Out of curiosity, can you `grep -Rn lldb-vscode ~/.config/nvim`? And I suppose we can close this?

**Comment by jan-xyz** [comment]
comes back empty :(

**Comment by jan-xyz** [comment]
thanks ya'll for your help 😊
