### ISSUE TITLE
Keyboard shortcut for toggleInlayHints is creating a .vscode folder

### ISSUE THREAD

**Issue by rodrigocfd** [rust-analyzer/rust-analyzer#10318]
I assigned a keyboard shortcut to `rust-analyzer.toggleInlayHints` command, so I can quickly toggle the inlay hints. I'm using latest VSCode (v1.60.2).

However, for some reason, now every time I hit the shortcut key, a new `.vscode` folder is created at the root of my project, with a `settings.json` file contaning this:

    {
        "rust-analyzer.inlayHints.enable": false
    }

I guess this started happening a few versions ago.

This behavior doesn't happen with the [Error Lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens) extension, for example, to which I also have a keyboard shortcut to `errorLens.toggle`.

**Comment by bjorn3** [comment]
Error Lens toggles the global configuration: https://github.com/usernamehw/vscode-error-lens/blob/17291ae2204ed3d7ad4dc3ee82dce64c5b958a3d/src/commands.ts#L8

Rust-analyzer toggles the workspace configuration: https://github.com/rust-analyzer/rust-analyzer/blob/88a214f2dc1c85bda1666f303f7658834d61780d/editors/code/src/commands.ts#L291

**Comment by lnicola** [comment]
Yeah, the folder is a bit annoying. Should we change the global instead?
