### ISSUE TITLE
failed to switch build data, could not compile 'memchr'

### ISSUE THREAD

**Issue by Inspirateur** [rust-analyzer/rust-analyzer#10317]
[Windows 10] rust-analyser stopped working on my VSCode yesterday I think, this is the error log (on "verbose"):
```
[ERROR rust_analyzer::reload] failed to switch build data: rust-analyzer failed to run build scripts:
error: could not compile `memchr` due to 2 previous errors
``` 
I installed it through VSCode, tried re-installing it with the same result.
I do not know where it is installed and I couldn't run any `rust-analyzer ...` commands because `the term 'rust-analyzer' is not recognized` 
I can tell you my dependencies are 
```
itertools = "*"
lipsum = "*"
difflib = "*"
regex = "*"
```
but i got no minimal example, sorry :v

**Comment by bjorn3** [comment]
Does `cargo check` work?

**Comment by Inspirateur** [comment]
`cargo check` fails with this
```
= note: LINK : fatal error LNK1181: cannot open input file 'kernel32.lib'


error: could not compile `memchr` due to previous error
```

**Comment by bjorn3** [comment]
Maybe try re-installing visual studio or the msbuild tools? I don't know which one you originally installed to get the linker.

**Comment by Inspirateur** [comment]
Thanks, I ended up having to re-install the whole msbuild tools C++ from 
https://visualstudio.microsoft.com/visual-cpp-build-tools/

I understand it wasn't really a rust-analyzer issue but at least that's one more reference on google for the future x)
