### ISSUE TITLE
"implement the missing item: …" helper does not substitute type parameter

### ISSUE THREAD

**Issue by Tamschi** [rust-analyzer/rust-analyzer#10327]
This seems distinct from #10326.

Given

```rust
trait A<T> {
    fn a(&self) -> &T;
}
struct B {}

impl<'a, T> A<B> for T {} // <-- not all trait items implemented, missing: `a` in implementation
```

, applying the "implement the missing item: …" helper leads to the following code (after formatting):

```rust
trait A<T> {
    fn a(&self) -> &T;
}
struct B {}

impl<'a, T> A<B> for T {
    fn a(&self) -> &T { // <-- method `a` has an incompatible type for trait\nexpected fn pointer `fn(&T) -> &B`\n found fn pointer `fn(&T) -> &T`
        todo!()
    }
}
```

This should instead be

```rust
trait A<T> {
    fn a(&self) -> &T;
}
struct B {}

impl<'a, T> A<B> for T {
    fn a(&self) -> &B { // <-- Ok
        todo!()
    }
}
```

as with the "Implement missing members" helper.

**Comment by Veykril** [comment]
We do not have control over the rustc diagnostic fixes, we only apply what rustc suggests in that case.

**Comment by Tamschi** [comment]
> We do not have control over the rustc diagnostic fixes, we only apply what rustc suggests in that case.

Ah sorry, that explains the different capitalisation and why it appears later. I'll close this and file it with rustc.
