### ISSUE TITLE
'inline local' assist

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#1033]
We have the 'introduce local' assist, so it'd be nice to have the inverse: 'inline local'. This should be available on the definition of a (non-mutable) local variable and replace all uses of the local variable by its definition. E.g.
```rust
{
    let var_name = 1;
    var_name.foo()
}
```
=>
```rust
{
    1.foo()
}
```

**Comment by matklad** [comment]
The relevant code and tests live in the ra_assist crate. Here's how "introdce variable" implemented: 

https://github.com/rust-analyzer/rust-analyzer/blob/18a8f48039fbfcbbf58e1dadcc95465fe9503691/crates/ra_assists/src/introduce_variable.rs

And this is the bit that collects all known assists:

https://github.com/rust-analyzer/rust-analyzer/blob/18a8f48039fbfcbbf58e1dadcc95465fe9503691/crates/ra_assists/src/lib.rs#L88-L116

**Comment by matklad** [comment]
Also, I've wanted this in IntelliJ for years (https://github.com/intellij-rust/intellij-rust/issues/1095), but never actually got to implementing...
