### ISSUE TITLE
Generate function assist puts .await and ? in the wrong order

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#10333]
When generating an `async fn` that returns a `Result` with "generate function", rust-analyzer replaces the previous code with `fun_name(/* arguments... */)?.await`. It should be `.await?`.

**Comment by feniljain** [comment]
Hey @flodiebold, can I take this up?

**Comment by lnicola** [comment]
It's yours!

**Comment by feniljain** [comment]
Nice, thanks, I am still confused a bit, is it possible I could get a MRE?

**Comment by bjorn3** [comment]
I would guess it is something like:

```rust
async fn foo() -> Result<(), ()> {
    Ok(())
}
```

and then extracting `Ok(())` as new function using an assist.

**Comment by feniljain** [comment]
Shifted discussion to https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Issue.20.2310333
