### ISSUE TITLE
Mut and &mut local variables don't show the default modifiers

### ISSUE THREAD

**Issue by linqingyao** [rust-analyzer/rust-analyzer#10342]
I'm currently using the Shades of Purple theme in vscode, but I can't show modifiers (underscores) under mut and &mut local variables, even though I've edited them in settings.json.What can I do to get modifiers for variables in the extension theme?If anyone can help me, I will be very grateful to you.
![isure](https://user-images.githubusercontent.com/83944508/134769305-538435e0-76db-4cb9-a474-7a3a0b0d8185.png)

**Comment by Veykril** [comment]
I believe the reason for that is that the theme does not enable semantic highlighting, cc https://github.com/ahmadawais/shades-of-purple-vscode/issues/90. As such the mutable modifier doesn't change things. I don't think this can be fixed with a semantic token mapping from our side, so what you can try is to forcefully enable semantic highlighting for your theme by doing something like:
```json
"editor.semanticTokenColorCustomizations": {
    "[Shades of Purple]": {
        "enabled": true,
        "rules": {}
    }
},
```
The `[Shades of Purple]` might be incorrect as I don't know the key the theme registers itself with.

**Comment by linqingyao** [comment]
> 我相信这是因为主题没有启用语义突出显示，cc [ahmadawais/shades-of-purple-vscode#90](https://github.com/ahmadawais/shades-of-purple-vscode/issues/90)。因此，可变修饰符不会改变事物。我不认为这可以通过我们这边的语义标记映射来解决，因此您可以尝试通过执行以下操作来强制为您的主题启用语义突出显示：
> 
> ```json
> “ editor.semanticTokenColorCustomizations ”：{
>      “ [紫色阴影] ”：{
>          “启用”： true，
>          “规则”：{}
>     }
> }，
> ```
> 
> 在`[Shades of Purple]`我不知道的主题与自己注册的关键可能不正确。

Oh, my God!That's good. Thank you very much for your help

**Comment by linqingyao** [comment]
> I believe the reason for that is that the theme does not enable semantic highlighting, cc [ahmadawais/shades-of-purple-vscode#90](https://github.com/ahmadawais/shades-of-purple-vscode/issues/90). As such the mutable modifier doesn't change things. I don't think this can be fixed with a semantic token mapping from our side, so what you can try is to forcefully enable semantic highlighting for your theme by doing something like:
> 
> ```json
> "editor.semanticTokenColorCustomizations": {
>     "[Shades of Purple]": {
>         "enabled": true,
>         "rules": {}
>     }
> },
> ```
> 
> The `[Shades of Purple]` might be incorrect as I don't know the key the theme registers itself with.

Oh, my God!That's good. Thank you very much for your help
