### ISSUE TITLE
How show inline errors/warnings ?

### ISSUE THREAD

**Issue by leo-frank** [rust-analyzer/rust-analyzer#10348]
I am new to rust-analyzer and happy to find such a great extension. I find others who use this extension have inline errors/warnings, but I can't find inline errors/warnings in my own VScode. that's why?

**Comment by lnicola** [comment]
You're probably thinking of the https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens extension.

**Comment by lnicola** [comment]
I'll close this, but feel free to reopen if you had something else in mind.
