### ISSUE TITLE
Ra plugins can't step into standard libraries for quick debugging through buttons

### ISSUE THREAD

**Issue by linqingyao** [rust-analyzer/rust-analyzer#10351]
Ra plugins don't have access to the library when they call (codeLLDB)debug, only to see their own code and endless assembly (please allow me to be stupid, I still can't read assembly), so this is so bad for me.I do not know whether this is the problem of RA or LLDB, but I hope to get your inspiration, so that I can better understand and run the code logic.
For example:
```rust
#[derive(Debug)]
struct Counter {
    count: u32,
}

impl Counter {
    fn new() -> Counter {
        Counter { count: 0 }
    }
}

impl Iterator for Counter {
    type Item = u32; // 指定关联类型为u32
    fn next(&mut self) -> Option<Self::Item> {
        self.count += 1;

        if self.count < 6 {
            Some(self.count)
        } else {
            None
        }
    }
}
fn main() {
    let sum: u32 = Counter::new()
        .zip(Counter::new().skip(1))
        .map(|(a, b)| a * b)
        .filter(|x| x % 3 == 0)
        .sum();
    assert_eq!(18, sum);
}
```

**Comment by iDawer** [comment]
Debugging is feature of CodeLLDB. Run `rustc -Vv` to get rustc's commit hash, find path to std sources then configure `lldb.launch.sourceMap` in settings:
```
{
  "lldb.executable": "rust-lldb",
  "lldb.launch.sourceLanguages": ["rust"],
  "lldb.launch.sourceMap": {
    "/rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/": "/Users/jessegrosjean/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/"
  },
}
```


More info https://users.rust-lang.org/t/solved-how-to-step-into-std-source-code-when-debugging-in-vs-code/25319/4

**Comment by linqingyao** [comment]
> 调试是 CodeLLDB 的功能。运行`rustc -Vv`以获取 rustc 的提交哈希，找到 std 源的路径，然后`lldb.launch.sourceMap`在设置中进行配置：
> 
> ```
> {
>   "lldb.executable": "rust-lldb",
>   "lldb.launch.sourceLanguages": ["rust"],
>   "lldb.launch.sourceMap": {
>     "/rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/": "/Users/jessegrosjean/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/"
>   },
> }
> ```
> 
> 更多信息https://users.rust-lang.org/t/solved-how-to-step-into-std-source-code-when-debugging-in-vs-code/25319/4

I tried to include the code you mentioned above into settings.json, but to my surprise there was no "lldb.executable": "rust-lldb" in the option, which code showed as not having even if I forcibly added it.Thankfully, I was only too happy that THE LLDB was able to jump to the standard library when I only added the other code (you know how annoying it is to debug with only assembly code).Thank you very much for your answer.Thanks!!

**Comment by lnicola** [comment]
So is it working now?

**Comment by linqingyao** [comment]
> So is it working now?

Yes, it is working now. Thank you very much for your questions

**Comment by lnicola** [comment]
Let's close it unless we can do anything better here.
