### ISSUE TITLE
Backtraces on windows

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#10371]
Currently `short` backtraces on windows seem to be somewhat broken and just don't work for the shipped rust-analyzer binaries at all and while the user can now overwrite the `RUST_BACKTRACE` env var for the server to enable `full` backtraces they just turn into a bunch of `<unknown>` frames. This is most likely due to us not shipping the `pdb` files(just guessing I don't know how these things work).

Zulip discussion: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/panic.20backtrace

**Comment by wesleywiser** [comment]
> This is most likely due to us not shipping the pdb files(just guessing I don't know how these things work).

Just wanted to chime in. This is definitely due to not shipping pdbs. Windows relies on debug info to demangle Rust symbols and without it, it really has no idea what's going on.

**Comment by lnicola** [comment]
Small update here: we can publish the PDBs, but downloading them automatically is less easy because our Windows artifacts are GZ files. Since we're planning to bundle the server binary with the extension, we'll probably wait for that.

**Comment by lnicola** [comment]
@Veykril can you try with the latest release?

**Comment by Veykril** [comment]
Already tried earlier today, wasn't sure if we shipped the PDBs already now but no it does not work unfortunately, the stacktrace is still missing(bunch of `<unknown>` for a FULL one)

**Comment by lnicola** [comment]
:sob: the PDB should be in there, at least.

**Comment by bjorn3** [comment]
Does it work if you rename the pdb to `rust-analyzer.pdb` (from `rust_analyzer.pdb`)?

**Comment by lnicola** [comment]
I checked and the `.exe` seems to reference `rust_analyzer.pdb`, not `rust-analyzer.pdb`. But yeah, it's worth a try.

**Comment by Veykril** [comment]
Nope 😕

**Comment by lnicola** [comment]
Can you check that it's actually running the bundled server and not some random one in `%HOME%/.cargo/bin` or somewhere else?

**Comment by Veykril** [comment]
running the version command from vscode gives me the latest nightly so that seems correct.

**Comment by Veykril** [comment]
So it looks in the working directory but not the location of the exe
![grafik](https://user-images.githubusercontent.com/3757771/146810889-4cd29c0b-e67b-49d0-8b07-c26398ef1974.png)
