### ISSUE TITLE
How could I disable formatting feature?

### ISSUE THREAD

**Issue by s3pt3mb3r** [rust-analyzer/rust-analyzer#10381]
Hello. Im using rust-analyzer on Visual Studio Code.
its auto formatting feature when saved annoys me so I'd like to know how to disable it.
other than that it's really good plugin!

**Comment by lnicola** [comment]
`"editor.formatOnSave": false` should work, but that's already the default.

**Comment by s3pt3mb3r** [comment]
Thank you so much it's fixed.
Idk why formatOnSave was on in my env, (probably when i installed prettier ages ago, i set it to true. not sure)
Thanks anyways!

**Comment by lnicola** [comment]
You can also disable it per-language, or configure the style in `rustfmt.toml`.

**Comment by s3pt3mb3r** [comment]
oh really, I'll take a look at it! thanks
