### ISSUE TITLE
Client for communicating with the language server

### ISSUE THREAD

**Issue by nerdondon** [rust-analyzer/rust-analyzer#10380]
Hi,

I'm looking to make a vscode extension and it would be nice if it could communicate with the rust-analyzer language server and use it's functionality. i see that i could probably just create a language client in the [same way](https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/src/client.ts#L161-L166) as the rust-analyzer vscode extension:

```
const client = new lc.LanguageClient(
        'rust-analyzer',
        'Rust Analyzer Language Server',
        serverOptions,
        clientOptions,
);
```

but is there a more supported way? is there an official client interface (node package) that i could add as a dependency of my own project?

if such a thing does not exist, i guess this becomes a sort of feature request for official client specs. it seems that this sort of thing can be generated via protobuff or thrift.

**Comment by lnicola** [comment]
Do you want to write a replacement for the `rust-analyzer` Code extension or something that runs along it? Making another LSP client might start a new server instance of both are installed, which would not be ideal.

If you want a replacement, then LSP _is_ the official and supported protocol, and Protobuf or Thrift are not involved in any way. If it's something that runs alongside it, there's no API but it would be interesting to hear what use case you have in mind.

**Comment by nerdondon** [comment]
I am writing something that would just communicate with the existing server instance. AFAIK, it seems like a new client should be able to re-use the existing instance. it seems strange for the server to run out of band just for new clients to spawn new instances but im still new to this.

I'm not trying to replace the LSP protocol, i was just curious if even with the protocol a client could be generated instead of needing to rely on the documentation. i am writing a vscode test explorer extension and would like to see about retrieving test information from the LSP server. Specifically, `cargo test -- --list` does not return any line numbers for the listed tests and it seems like the `Runnable` object that one of the LSP extensions provides would be helpful for this information.

**Comment by lnicola** [comment]
> AFAIK, it seems like a new client should be able to re-use the existing instance.

Calling `start()` on a new `LanguageClient` spawns another server process.

For a test explorer, see also https://github.com/rust-analyzer/rust-analyzer/pull/5765 (if you haven't already).

**Comment by nerdondon** [comment]
welp thats good to know. thanks for the pointer. i guess i'll look forward to the official testing explorer support.
