### ISSUE TITLE
Semantic highlighting for format macros

### ISSUE THREAD

**Issue by digama0** [rust-analyzer/rust-analyzer#10394]
The `{}` in `println!("{}", 1)` is highlighted specially, which is a very nice feature. However, it only works for some of the format-like macros:

* [x] `asm!`
* [x] `assert!`
* [x] `assert_eq!`
* [x] `assert_ne!`
* [x] `debug_assert!`
* [x] `debug_assert_eq!`
* [x] `debug_assert_ne!`
* [x] `eprint!`
* [x] `eprintln!`
* [x] `format!`
* [x] `format_args!`
* [x] `format_args_nl!`
* [x] `panic!` *
* [x] `print!`
* [x] `println!`
* [x] `todo!` *
* [x] `unimplemented!` *
* [ ] `unreachable!`
* [x] `write!`
* [x] `writeln!`

Arguably, support for `asm` is more complicated, but it seems close enough to `format_args` style input in the first argument that I think that applying the usual syntax highlighting will work well enough. Here's a rust snippet containing all the macros for quick testing:

```rust
fn main() {
    asm!("mov {}, 0", out(reg) _);
    assert!(true, "{}", 1);
    assert_eq!(1, 2, "{}", 1);
    assert_ne!(1, 2, "{}", 1);
    debug_assert!(true, "{}", 1);
    debug_assert_eq!(1, 2, "{}", 1);
    debug_assert_ne!(1, 2, "{}", 1);
    eprint!("{}", 1);
    eprintln!("{}", 1);
    format!("{}", 1);
    format_args!("{}", 1);
    format_args_nl!("{}", 1);
    panic!("{}", 1);
    print!("{}", 1);
    println!("{}", 1);
    todo!("{}", 1);
    unimplemented!("{}", 1);
    unreachable!("{}", 1);
    write!((), "{}", 1);
    writeln!((), "{}", 1);
}
```

Tested on rust-analyzer v0.2.760 on VSCode with `rustc 1.57.0-nightly (11491938f 2021-09-29)`. The macros marked with `*` are recent regressions, which work on stable but not on the latest nightly, presumably due to a change in the implementation of `panic!` relating to rust 2021.

**Comment by jonas-schievink** [comment]
#10397 fixes `panic!`, `assert!` and `debug_assert!`

**Comment by jonas-schievink** [comment]
`todo!` and `unimplemented!` both expand to

    $crate::panic!("not (yet) implemented: {}", $crate::format_args!($($arg)+))

which we should already handle, so there's another bug in there.

`unreachable!` on the other hand expands to

    $crate::panic!($crate::concat!("internal error: entered unreachable code: ", $fmt), $($arg)*)

which is hard to handle correctly, since the actual format string passed to `(const_)format_args!` differs from the one the user sees

**Comment by digama0** [comment]
Oh, `todo!` and `unimplemented!` are working as intended - they don't take any format string, so the first arg is just a plain string literal. I have removed them from the list.

**Comment by jonas-schievink** [comment]
No, they do:

```rust
fn main() {
    todo!("TODO: {}", 123);
}
```
```
thread 'main' panicked at 'not yet implemented: TODO: 123', src/main.rs:2:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jonas-schievink** [comment]
#10412 highlights `asm!` as a format string (note that there's also https://github.com/rust-analyzer/rust-analyzer/issues/6031 for actual assembly syntax highlighting)
