### ISSUE TITLE
"run test" lens on any attribute containing the string "test"

### ISSUE THREAD

**Issue by eminence** [rust-analyzer/rust-analyzer#10393]
When applying a custom attribute macro to a function, it seems that RA will look for the substring `test` when deciding if to show the "Run Test" code lens:

![image](https://user-images.githubusercontent.com/402454/135378355-2aedddec-08c4-4a3d-b84f-46d8c9c390cc.png)

This is a little annoying, because the `#[contested]` attribute doesn't create a test (so clicking on "Run Test" doesn't do anything useful or meaningful)

I can see how this would be hard to solve -- RA can't expand this macro so it doesn't know at all what `#[contested]` does.   Maybe instead of looking for "test" anywhere in the attribute, it can look for "test" only at the start or end?

https://github.com/rust-analyzer/rust-analyzer/blob/b21f15a23767c8d06ab5da60f59b8b197c45831a/crates/ide_assists/src/utils.rs#L68-L79

**Comment by Veykril** [comment]
I think we can just remove this once we stabilize attribute macro expansion no?

**Comment by bjorn3** [comment]
[`#[wasm_bindgen_test]`](https://docs.rs/wasm-bindgen-test/0.3.28/wasm_bindgen_test/attr.wasm_bindgen_test.html) doesn't expand to a `#[test]` attribute, yet `cargo test --target wasm32-unknown-unknown` does work for it if you add the following to `.cargo/config.toml`:

```toml
[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'
```

as such the "run test" lens should still exist IMO.

https://rustwasm.github.io/docs/wasm-bindgen/wasm-bindgen-test/usage.html#appendix-using-wasm-bindgen-test-without-wasm-pack

**Comment by Veykril** [comment]
Ah okay, in that case it does make sense to keep it then, though as described in this issue we probably want to change up the heuristic a bit.

**Comment by eminence** [comment]
That's neat how wasm-bindgen works.  

What about looking for `test` at either the start or end of the attribute name?  I'm aware of the following attribute names, and they would all work with this approach:

* `#[test]`
* `#[wasm_bindgen_test]`
* [`#[test_case]`](https://crates.io/crates/test-case)
* [`#[rstest]`](https://crates.io/crates/rstest)
* `#[tokio::test]`

But I'm sure I'm missing a few.
