### ISSUE TITLE
Manually trigger indexing

### ISSUE THREAD

**Issue by jeluard** [rust-analyzer/rust-analyzer#10409]
(Sorry I can't figure where to ask questions)

Is there a way to manually (e.g. via a binary) the indexing?
I'm looking for ways to embed rust-analyzer in a docker image and have indexing pre done, before vscode is started.

**Comment by lnicola** [comment]
Not yet, see https://github.com/rust-analyzer/rust-analyzer/issues/4712.

**Comment by lnicola** [comment]
You can ask questions on https://users.rust-lang.org/c/ide/14.
