### ISSUE TITLE
rust-analyzer calling `xcodebuild`

### ISSUE THREAD

**Issue by winterqt** [rust-analyzer/rust-analyzer#10419]
For some reason, when using rust-analyzer with the VS Code extension, it's calling `xcodebuild`, which I do not have installed (so a dialog pops up asking if I want to install it). But when `cargo build`ing outside of VS Code, I can build just fine without `xcodebuild`. I'm really not sure what's making it call `xcodebuild` of all things, honestly. Nothing seems to fail, either...

How would I begin to debug this? I can't even find any mention to `xcodebuild` in RA or rustc sources. (note: `xcodebuild` is not my `$CC`, that's Clang.)

RA version: `2021-09-06`
System: `aarch64-darwin`

**Comment by lnicola** [comment]
Do you have any environment variables in `settings.json` (or maybe in a per-worskpace `settings.json`)?

**Comment by winterqt** [comment]
No, not in `settings.json`. What environment variables would affect this, though? Just in case they're set elsewhere (although I doubt it, it doesn't hurt to check).

**Comment by lnicola** [comment]
I'm not sure. Maybe `CC`, `RUSTC_LINKER`, `CARGO_TARGET_<triple>_LINKER`, `RUSTFLAGS`. `RUSTC_WRAPPER`.

Does it happen in an empty project?

**Comment by winterqt** [comment]
> I'm not sure. Maybe `CC`, `RUSTC_LINKER`, `CARGO_TARGET_<triple>_LINKER`, `RUSTFLAGS`. `RUSTC_WRAPPER`.

None of those are set, except `CC` which is set to `clang`, which corresponds to my Nix install of Clang, not the Xcode Command Line Tools wrapper. Additionally, this only happens when using rust-analyzer, and not when building with the same environment (including environment variables) from the CLI.

> Does it happen in an empty project?

It does not.

**Comment by lnicola** [comment]
> Additionally, this only happens when using rust-analyzer, and not when building with the same environment (including environment variables) from the CLI.

Does it happen if you start Code from a terminal?

> It does not.

Hmm. Any build scripts or `.cargo/config.toml` files?

**Comment by winterqt** [comment]
> Does it happen if you start Code from a terminal?

Yes (this is the primary way I start Code, so that it inherits my `direnv`).

> Hmm. Any build scripts or `.cargo/config.toml` files?

A dependency probably has a build script (is there a quick way I can check this?), but I don't directly.

The thing that I'm confused about is that this builds fine from my terminal, but not when Code is launched with the exact same environment...

**Comment by lnicola** [comment]
Does `cargo check --all-features` work, too?

We don't write much to the environment outside of the `rust-analyzer.server.extraEnv` setting. Maybe you can try https://apple.stackexchange.com/questions/140327/how-can-i-inspect-the-environment-variables-of-a-running-process for a running server (or `cargo`) to see if anything fishy is set.

Anyway, I'm not a Mac user, so if there's any OS-specific place to stash environment variables, I won't guess it.

**Comment by bjorn3** [comment]
If @lnicola's suggestion doesn't help, could you try closing vscode, ensuring that none of it's processes still run and then launch it prefixed with `truss -f -a -t exec`? That should list all programs being exec'ed I think. This may help with figuring out which program requires the xcode commandline utils.

Oh, and how do you launch vscode? Do you directly execute the executable inside of the vscode .app bundle or do you use `open`?

**Comment by winterqt** [comment]
> Does `cargo check --all-features` work, too?

Yes, from a terminal.

The environment variables that rust-analyzer is being run with is consistent with my terminal, including `PATH` and `CC`, where `cargo check --all-features` et al. works fine.

> Oh, and how do you launch vscode? Do you directly execute the executable inside of the vscode .app bundle or do you use `open`?

I directly execute the executable inside the `.app`.

**Comment by winterqt** [comment]
> If @lnicola's suggestion doesn't help, could you try closing vscode, ensuring that none of it's processes still run and then launch it prefixed with `truss -f -a -t exec`? That should list all programs being exec'ed I think. This may help with figuring out which program requires the xcode commandline utils.

Sadly `dtruss` requires me to disable SIP, but I'll try it anyways.

**Comment by lnicola** [comment]
Make a new user account!

**Comment by winterqt** [comment]
SIP is system-wide.

Anyways, that sadly doesn't work since the Code CLI spawns a new process entirely, which DTruss can't pick up. 😕

**Comment by lnicola** [comment]
I meant you could try to make another user so any account-specific settings no longer apply.

**Comment by winterqt** [comment]
> But that probably means another Xcode install so it might take a while.

I don't even have Xcode installed, the only reason I know it's trying to call it is because I get a pop up that says `"xcodebuild" requires the Xcode Command Line Tools...`, nothing even visibly fails due to its absence.

**Comment by bjorn3** [comment]
> Sadly dtruss requires me to disable SIP, but I'll try it anyways.

You can also enable dtrace without disabling SIP entirely using `csrutil enable --without dtrace` in recovery mode.

**Comment by bjorn3** [comment]
> But that probably means another Xcode install so it might take a while.

Only the xcode command line tools seem to be necessary, which can be installed a lot quicker.

> I don't even have Xcode installed, the only reason I know it's trying to call it is because I get a pop up that says "xcodebuild" requires the Xcode Command Line Tools..., nothing even visibly fails due to its absence (which makes this situation even stranger).

When trying to run system installations for programs like clang or git without the xcode command line tools installed, this popup will show. I have no clue why it tries to run any of them though.

**Comment by lnicola** [comment]
Does the `.app` Code inherit `PATH` from the shell?

**Comment by winterqt** [comment]
> You can also enable dtrace without disabling SIP entirely using `csrutil enable --without dtrace` in recovery mode.

```
csrutil: Requesting an unsupported configuration. This is likely to break in the future and leave your machine in an unknown state.
```

😅

**Comment by winterqt** [comment]
> When trying to run system installations for programs like clang or git without the xcode command line tools installed, this popup will show. I have no clue why it tries to run any of them though.

The thing that I don't understand is that it should not be trying to run the system versions of these tools. The `PATH` that RA is running under has versions of those tools before the system versions.

**Comment by winterqt** [comment]
> Does the `.app` Code inherit `PATH` from the shell?

Turns out, yes, with the correct flag.

@bjorn3 The `dtruss` flags you noted seem to not show any details for the `exec` calls 😕

**Comment by winterqt** [comment]
It's definitely some instance of rust-analyzer that's running it, but I can't even tell which since it spawns like 10 at once according to Activity Monitor. (so I can't even `dtruss` the PIDs.)

**Comment by winterqt** [comment]
Trying to `ps` my way through this (to see the arguments `xcodebuild` is spawned with, if any) doesn't work either :/

```fish
while true;
  ps Aa >> aaaaaaaa
end
```

I see every process including `Install Command Line Tools.app`, but never once `xcodebuild`. Perhaps it's quitting too quickly to show?

**Comment by winterqt** [comment]
I tried to use Objective-See's [Process Monitor](https://objective-see.com/products/utilities.html) to find the arguments (since it shows them), but Process Monitor isn't seeing the `xcodebuild` process being spawned at all.

So then I used `execsnoop` and Process Monitor at the same time, grepping for the `xcodebuild` PID that `execsnoop` found in the Process Monitor log, and came up with nothing.

😕

**Comment by winterqt** [comment]
Even weirder is the fact that Process Monitor shows that my Nix installs of `clang` and such are being used, so why is `xcodebuild` being invoked???

**Comment by winterqt** [comment]
I have found the culprit!

https://github.com/alexcrichton/curl-rust/blob/b0b6c68997833675a842c2fa46f361c5a44d4a2a/curl-sys/build.rs#L499

Closing as this is not a RA issue. Thanks @lnicola and @bjorn3 for helping out. ❤️
