### ISSUE TITLE
Emit `unresolvedReference` for `self` outside of methods

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#10435]
Currently using `self` even in a freestanding function is highlighted as a `selfKeyword`,

<img width="322" alt="Screen Shot 2021-10-03 at 5 34 30 pm" src="https://user-images.githubusercontent.com/31783266/135742901-9466e699-7a32-45b3-8466-4449a33c8196.png">

when arguably it should be highlighted as `unresolvedReference`, since the `self` function parameter is not present.

**Comment by lnicola** [comment]
Is it a keyword? Is it an unresolved reference? Is it a namespace?

(`self::foo()`)

**Comment by arzg** [comment]
Wow, I hadn’t considered that usage! I think you’re right; given the profusion of different uses, I guess it makes little sense to highlight `self` as unresolved in only one of the uses (method receiver).
