### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by gipsyh** [rust-analyzer/rust-analyzer#10470]
<img width="542" alt="Screenshot 2021-10-06 200039" src="https://user-images.githubusercontent.com/42509521/136198169-6cba4d01-c5a1-4e6e-8301-1316a5107544.png">

but it can be compiled...

```rust
#[macro_use]
extern crate rocket;

use rocket::response::Redirect;
use rocket::uri;
use std::{fs::File, path::Path};

#[get("/image/<file>")]
fn image(file: &str) -> File {
    let path = Path::new("images").join(file);
    File::open(path).unwrap()
}

#[get("/image")]
fn random_image() -> Redirect {
    Redirect::to(uri!(image("aaa")))
}

#[rocket::launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![image, random_image])
}
```

rust-analyzer 88a214f 2021-09-23 dev

**Comment by gipsyh** [comment]
> What exactly is the error being reported here?
<img width="517" alt="Screenshot 2021-10-06 201535" src="https://user-images.githubusercontent.com/42509521/136200299-371dc2ce-a84c-4d26-8ff8-4241c5951022.png">

**Comment by Veykril** [comment]
Note that the `procAttrMacros` setting is enabled by default with the last stable rust-analyzer.
