### ISSUE TITLE
VS Code: Platform-specific Extensions

### ISSUE THREAD

**Issue by jonasbb** [rust-analyzer/rust-analyzer#10483]
VS Code 1.61 allows using platform-specific extensions: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions
This allows creating extensions which bundle the correct binary for each platform. This would remove the need to download rust-analyzer on the first run after an update and provide a better experience for offline use or when the CI fails to upload the artifacts (https://github.com/rust-analyzer/rust-analyzer/issues/10341#issuecomment-927011682).
It might also help with updates on Windows.

It might be worthwhile to consider using this feature in the future.

**Comment by matklad** [comment]
wow wow wow, we definitely should do this. It'll allow us to cur the whole download business away, which is very welcome!
