### ISSUE TITLE
Attribute proc-macro expansion issue

### ISSUE THREAD

**Issue by liuw** [rust-analyzer/rust-analyzer#10498]
Commit https://github.com/rust-analyzer/rust-analyzer/commit/81891f7abecbcdd8d97bf878dd1dbce595755d6a enabled attribute proc macro by default (released in v0.2.768). That rendered rust-analyzer unusable in my case. Basically whenever I change something, the whole function is marked as problematic. Please see the two screenshots for comparison.

First screenshot shows the result when that option is enabled; second screenshot shows the result when the option is disabled.

In the second screenshot, rust-analyzer correctly points out that `let x` is problematic.

![image](https://user-images.githubusercontent.com/138514/136671739-d1b33e8e-9b59-4258-a791-4820c4804256.png)

![image](https://user-images.githubusercontent.com/138514/136671750-9c8260ac-ad60-4596-866a-c8e1db108f74.png)

**Comment by Veykril** [comment]
The crate is `legion` I believe

**Comment by liuw** [comment]
If this is helpful, this is what I get when running `cargo c`. It is able to pinpoint the correct location of the incomplete code.

![image](https://user-images.githubusercontent.com/138514/136674924-d4a1bc1a-1585-478b-997b-ba2e0c4ceba4.png)

**Comment by lucacasonato** [comment]
Beautiful, thank you for the hard work everyone :heart:

**Comment by Veykril** [comment]
Closing in favor of https://github.com/rust-analyzer/rust-analyzer/issues/11014
