### ISSUE TITLE
async move blocks yield syntax errors

### ISSUE THREAD

**Issue by Globidev** [rust-analyzer/rust-analyzer#1053]
`async` blocks are correctly recognized since #954 but not in combination with `move`:
![image](https://user-images.githubusercontent.com/2079561/54970610-1b5e8480-4f83-11e9-8903-69a0c144d160.png)

**Comment by sigoden** [comment]
`async || "Hello, world!"`  yield syntax errors too. @memoryruins

**Comment by memoryruins** [comment]
good look! from the [async_await rfc](https://github.com/rust-lang/rfcs/blob/master/text/2394-async_await.md), that also includes move closures:
> async closures can be annotated with move to capture ownership of the variables they close over.
