### ISSUE TITLE
Issue with macros: `range end index 8 out of range for slice of length 4`

### ISSUE THREAD

**Issue by bugadani** [rust-analyzer/rust-analyzer#10540]
Repro repository: https://github.com/bugadani/ra-macro-issue-repro

A simple proc macro that processes a string literal crashes.
![image](https://user-images.githubusercontent.com/977627/137322683-fc3c50b4-9856-4585-a644-80a699a3e7a9.png)

rust-analyzer version: ed4b312fa 2021-10-11 stable

**Comment by bugadani** [comment]
```
rustc 1.56.0-nightly (2827db2b1 2021-08-01)
binary: rustc
commit-hash: 2827db2b137e899242e81f1beea39ae26e245153
commit-date: 2021-08-01
host: x86_64-pc-windows-msvc
release: 1.56.0-nightly
LLVM version: 12.0.1
```

**Comment by lnicola** [comment]
Also works for me in stable (1.55). Let's close this, but feel free to reopen if it happens again.

![image](https://user-images.githubusercontent.com/308347/137627374-c8ffe43f-c23a-4a94-9ceb-5d8ed0338ebb.png)

> Maybe RA could warn if I have an old rustc?

But 1.56 is not an old rustc, it's newer than stable.

**Comment by rahul-soshte** [comment]
i ran `rustup default stable` and it worked. earlier it was running on some nightly version but not it switched to `rustc v1.56.1` and it worked.
