### ISSUE TITLE
LSIF: Emit Monikers to allow cross-repository references

### ISSUE THREAD

**Issue by sandhose** [rust-analyzer/rust-analyzer#10559]
LSIF supports emitting [`Moniker`](https://microsoft.github.io/language-server-protocol/specifications/lsif/0.6.0/specification/#exportsImports) vertex to identify a `ResultSet` (token) across repositories. Sourcegraph is able to index those to allow looking up symbols across multiple repositories.

Monikers have a scheme, an identifier and a scope for that identifier. In the examples in the spec, they use the `tsc` scheme for referencing typescript symbols, and use the absolute import path + export name as identifier (e.g. `dependency:Class.method`).

From what I understand, the LSIF spec suggest to emit two "levels" of monikers:
 - one local to the workspace, with no knowledge from the package manager, but rather references to Rust import/exports. Those could look like this:
   ```json
   {"type": "vertex", "label": "moniker", "scheme": "rust",
    "identifier": "path/to/the/crate/root::mylib::module::Whatever",
    "type": "export", "unique": "workspace"} 
   ```
 - one with [informations from the package manager](https://microsoft.github.io/language-server-protocol/specifications/lsif/0.6.0/specification/#packageManagers), to help linking to the right version and the right repository

In the end, if I understood the spec correctly, the monikers for an import would look something like this:
```js
// A resultSet, aka. a token. We already emit those in rust-analyzer
{ id: 10, type: "vertex", label: "resultSet" }
// The moniker with the "rust" scheme
{ id: 11, type: "vertex", label: "moniker",
  kind: "import", scheme: "rust",
  identifier: "path/to/the/crate/root::mylib::module::Whatever",
  unique: "workspace" }
// Attaching the moniker to the resultSet
{ id: 12, type: "edge", label: "moniker", outV: 10, inV: 11 }
// Now, informations from Cargo
{ id: 20, type: "vertex", label: "packageInformation",
  name: "mylib", manager: "cargo", version: "1.2.3",
  repository: { type: "git", url: "git+https://github.com/org/mylib.git" } }
// Have a second moniker with the "cargo" scheme
{ id: 21, type: "vertex", label: "moniker",
  kind: "import", scheme: "cargo",
  identifier: "mylib::module::Whatever", unique: "scheme" }
// Link the package informations to the moniker
{ id: 22, type: "edge", label: "packageInformation",
  outV: 21, inV: 20 }
// Attach the "cargo" moniker to the "rust" moniker
{ id: 23, type: "edge", label: "attach",
  outV: 21, inV: 11 }
```

When exporting symbols the story is pretty much the same.

However, where I'm not completely sure how we should build identifiers. With the `cargo` scheme, maybe they should include the registry, e.g. `crates.io/mylib::module::Whatever`? I'm also not sure how to deal with `std`/`core`, etc.

Maybe it would be useful to have some input from the Sourcegraph team. There is an issue open to track rust indexing support in Sourcegraph: https://github.com/sourcegraph/sourcegraph/issues/26086

**Comment by olafurpg** [comment]
> Maybe it would be useful to have some input from the Sourcegraph team.

Hello! I work on the code intel team at Sourcegraph.

> In the end, if I understood the spec correctly, the monikers for an import would look something like this

It's not necessary to emit two monikers like the LSIF spec alludes to. For Java, we only emit a single moniker node per symbol and I think that makes the graph structure a bit easier to follow. The following structure should be sufficient:
```jsonc
// Define a result set
{"id": 1, "type":"vertex", "label":"resultSet"}

// Define a moniker node
{ id: 2, type: "vertex", label: "moniker",
  kind: "import", scheme: "rust-analyzer",
  identifier: "mylib::module::Whatever"}

// Define Cargo packageInformation node
{ id: 3, type: "vertex", label: "packageInformation",
  name: "mylib", manager: "cargo", version: "1.2.3",
  repository: { type: "git", url: "git+https://github.com/org/mylib.git" } }


// Attach the moniker to the resultSet
{ id: 4, type: "edge", label: "moniker",
  outV: 1, inV: 2 }

// Link the rust-analyzer moniker to the Cargo packageInformation node
{ id: 5, type: "edge", label: "packageInformation",
  outV: 2, inV: 3 }
```

For cross-repo navigation to work, at least two repositories need to emit matching moniker/packageInformation identifiers (including the version of the packageInformation node). One of the repos must define an `export` moniker to specify where the symbol is defined.

**Comment by HKalbasi** [comment]
I started to work on this today, but I don't know how to get the repository url of crates.io packages. It seems it isn't in the `Cargo.toml` or `Cargo.lock` and cargo cli doesn't get it. Is it ok for rust analyzer to directly make network request? It seems it currently outsource network requests to cargo and rustup, so it isn't clear that it is ok or not.

**Comment by bjorn3** [comment]
You can look at the `Cargo.toml` of the dependency to find the `repository` key and then at the `.cargo_vcs_info.json` file next to it to see which commit and which path inside the repo. (if `.cargo_vcs_info.json` doesn't exist, either it wasn't published from a git repo or there were changes since the last commit.)
