### ISSUE TITLE
New assist to unwrap from type

### ISSUE THREAD

**Issue by bnjjj** [rust-analyzer/rust-analyzer#10565]
I recently felt the need for a new assist to unwrap a type. Let me show you an example:

```rust
fn foo() -> Box<String<|>> { ... }

// After
fn foo() -> String { ... }
```

I just wanted to know if you think it could be interesting to implement it ? I plan to implement it myself but I'm wondering if you think it could be useful for everyone and not just for me.

**Comment by bnjjj** [comment]
Not related to the return type specific at all. I can add another example:

```rust
let x: Vec<Box<usize<|>>>;

// TO
let x: Vec<usize>;
```

so no impacts on the body

**Comment by Veykril** [comment]
Isn't this https://github.com/rust-analyzer/rust-analyzer/pull/8070 then?
