### ISSUE TITLE
Deprioritize ops methods in completion

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#10593]
`PatialEq::ne` is always scored higher for me than inherent `new`, and that's super annoying.

**Comment by matklad** [comment]
I ... just realized something very important about issues in general. 

There are two distinct things which both go into the issues bin:

* users create *reports* about desired behavior (they report where current behavior falls short)
* maintainers create *work items* to track progress

The litmus test between the two is imagining a world where the hand-crafted software binary is replaced with a neural network, which just arrives at the answer through the magic of matrix multiplication. In this world, issues of the first kind basically don't change, while the issues of the second kind become meaningless. 

Confusion between the two creates two specific problems:

* closing specific, narrow *report* in favor of work items. While it is true that a single commit might close both work-item and a report, semantically they are not equivalent. We might end up fixing report in some other way (eg, realize that it's important enough to apply an isolated hack), and we might end up closing work items without fixing the report (ie, we realize that the problem is deeper than it seems)
* turning original report into a work-item. That is, when title says something "add support for `#[cfg(rust-analyzer)]`" but the comments say "fix non-snake-case diagnositc in macros, and also check what's up with identifier mapping".

**Comment by gfreezy** [comment]
`ne` still comes before `new` as of 2022-01-28 nightly

**Comment by Veykril** [comment]
Right I forgot to reopen this, realized that as well after implementing https://github.com/rust-analyzer/rust-analyzer/pull/11210#issuecomment-1013679756
We are probably missing something in the protocol conversion
