### ISSUE TITLE
Custom target not being detected (or the --target flag is not being passed?) if a custom toolchain is set using rust-toolchain.toml

### ISSUE THREAD

**Issue by PizzaFlavoured** [rust-analyzer/rust-analyzer#10615]
I have no idea what's going on but that title is the only conclusion I have been able to draw so far.

* Generate a project using cargo-generate from the following template: https://github.com/Rahix/avr-hal-template :
cargo generate --git https://github.com/Rahix/avr-hal-template.git
* Open src/main.rs and an error from avr-device should pop up, asking to make sure the target is set to AVR.

cargo build works fine and builds an AVR file, respecting .cargo/config.toml and rust-toolchain.toml. Deleting rust-toolchain.toml makes the error disappear, however, the project now fails to compile as, apparently, the old version is necessary, but that's outside of the scope of this issue.

I'm using vim with youcompleteme, but I doubt this matters that much. All rust-analyzer options are the default.

**Comment by fenjalien** [comment]
Hi, I've just run into the same issue idk why it happens but you can fix it by setting the config option `rust-analyzer.cargo.target` to what the build target is set to in `.cargo/config.toml`.
I'm using vscode and an atmega328p so `.vscode/settings.json` is
```json
{
    "rust-analyzer.cargo.target": "avr-specs/avr-atmega328p.json",
}
```

**Comment by matze** [comment]
I use LSPs in neovim but that info is a good hint, thanks!

**Comment by PizzaFlavoured** [comment]
> I am running into the same issue. What exactly did you do that made you close this issue?

I honestly thought this was me doing something wrong and not an actual issue. I'll reopen the issue since other people ran into the same problem. My bad.

> Hi, I've just run into the same issue idk why it happens but you can fix it by setting the config option `rust-analyzer.cargo.target` to what the build target is set to in `.cargo/config.toml`. I'm using vscode and an atmega328p so `.vscode/settings.json` is
> 
> ```json
> {
>     "rust-analyzer.cargo.target": "avr-specs/avr-atmega328p.json",
> }
> ```

I had tried doing but it did not help, unfortunately. I ended up disabling the feature (setting `rust-analyzer.procMacro.enable` to `false`) as a workaround.

**Comment by Veykril** [comment]
From the looks of it it seems like we are failing to use `cargo` to fetch the cfgs here, therefor we fall back to querying rustc directly which means we skip the `cargo/.config.toml`. For some reason calling `cargo -Zunstable-options rustc --print cfg` fails with 
```
error: Found argument '--print' which wasn't expected, or isn't valid in this context

USAGE:
    cargo.exe rustc [OPTIONS] [--] [args]...

For more information try --help
```
on the toolchain `nightly-2021-01-07` that is specified by that toolchain file. This works on newer toolchains though so I assume the way we call this has been fixed after that toolchain release. Running `cargo -Zunstable-options rustc -- --print cfg` makes it work, but will cause the command to fail for virtual workspaces(like rust-analyzer itself for example).

Given we don't tend to go out of our way to support older versions currently I propose to mark this as a wont-fix?

**Comment by Veykril** [comment]
> Given we don't tend to go out of our way to support older versions currently I propose to mark this as a wont-fix?

Closing as stated previously.
