### ISSUE TITLE
Warning when building vscode extension with vsce v1.100.2

### ISSUE THREAD

**Issue by oxalica** [rust-analyzer/rust-analyzer#10632]
After https://github.com/microsoft/vscode-vsce/pull/628, `vsce` raises an warning and ask user to confirm because it cannot found `LICENSE.md` or `LICENSE.txt`. It hurts automatic build process.

Since we are specifying `"vsce": "^1.95.1"`, regenerating `package-lock.json` will encounter this.

**Comment by oxalica** [comment]
Seems fixed in https://github.com/rust-analyzer/rust-analyzer/commit/acd5c1f19bf7246107aaae7b6fe3f676a516c6d2

**Comment by lnicola** [comment]
Oh wow, I missed this issue :smile:.
