### ISSUE TITLE
feature request: make mut assist

### ISSUE THREAD

**Issue by jhgg** [rust-analyzer/rust-analyzer#10658]
Pardon if this is already a duplicated issue, I did some searching but couldn't find anything:

Given this code:

```rust
fn foo() {
    let x = vec![];
    x.pu$0sh(5);
}
```

It would be cool if it could provide an assist that when invoked on `$0`, would fix the compile error by making `x` mut. 

```rust
fn foo() {
    let mut x = vec![];
    x.push(5);
}
```

Right now, you have to save (assuming you have cargo checkOnSave), and then apply the assist (which I think is generated from the cargo check suggest) here:

```rust
fn foo() {
    let x$0 = vec![];
    x.push(5);
}
```

But it'd be *really* quite nice if you didn't have to move your cursor back to x to make it mut! 

Additionally it could also apply in the following situations:

```rust
fn foo(x: Vec<i32>) {
    x.pu$0sh(5);
}
```
-> 
```rust
fn foo(mut x: Vec<i32>) {
    x.push(5);
}
```

And also:

```rust
fn foo(x: &Vec<i32>) {
    x.pu$0sh(5);
}
```
-> 
```rust
fn foo(x: &mut Vec<i32>) {
    x.push(5);
}
```

**Comment by jplatte** [comment]
I opened an issue about this a while ago: #8449

**Comment by lnicola** [comment]
Let's close this as a dupe.
