### ISSUE TITLE
Implementation method of struct inside function scope breaks code analyze

### ISSUE THREAD

**Issue by gr8den** [rust-analyzer/rust-analyzer#10676]
Code analyze works when I implement method outside function scope:
<img width="465" alt="Screenshot 2021-11-02 at 00 09 44" src="https://user-images.githubusercontent.com/19634251/139704501-8cc0b66c-8707-4af7-95e2-896ea88b53a3.png">

But when I try implement method inside function scope it breaks code analyze. Return type of `is_even()` displayed
 as `{unknown}` instead `bool`
<img width="543" alt="Screenshot 2021-11-02 at 00 10 11" src="https://user-images.githubusercontent.com/19634251/139705065-cc631bf1-2f20-4e76-bb66-944972cd6204.png">

In both cases code compile and run successfully

## Code

```rust
// struct SomeStruct(i32);

// impl SomeStruct {
//     fn is_even(&self) -> bool {
//         self.0 % 2 == 0
//     }
// }

// fn main() {
//     let o = SomeStruct(3);
//     let is_even = o.is_even();
//     println!("{:?} is even? {}", o.0, is_even);
// }

// -------------

fn main() {
    struct SomeStruct(i32);

    impl SomeStruct {
        fn is_even(&self) -> bool {
            self.0 % 2 == 0
        }
    }

    let o = SomeStruct(3);
    let is_even = o.is_even();
    println!("{:?} is even? {}", o.0, is_even);
}


```

**Comment by lnicola** [comment]
Confirmed. I was sure there's already an issue for this, but I can't find it right now.

**Comment by XFFXFF** [comment]
https://github.com/rust-analyzer/rust-analyzer/blob/2c0f433fd2e838ae181f87019b6f1fefe33c6f54/crates/hir_ty/src/infer/expr.rs#L985-L995  
I found that it cannot lookup the method called `is_even`
