### ISSUE TITLE
`Itertools::max` is misdetected as `Ord::max`, resulting in `expected 1 argument, found 0` error

### ISSUE THREAD

**Issue by TonalidadeHidrica** [rust-analyzer/rust-analyzer#10673]
## Steps to reproduce

Create a new bin crate, and replace `src/main.rs` with the following code.

`src/main.rs`
```rust
fn main() {
    let _ = vec![vec![1, 2, 3]]
        .iter()
        .flat_map(|x| x.iter().flat_map(|x| Some(x)))
        .max()
        .unwrap();
}
```

When `edition = "2021"`, nothing is wrong.
When `edition = "2018"`, `rust-analyzer` points out that there is an error on the fifth line (`.max()`): `[rust-analyzer mismatched-arg-count] [E] expected 1 argument, found 0`.
Hovering on the `max` shows `core::cmp::Ord`, not `std::iter::Iterator`.

In both case, `cargo check` shows no errors or warnings.

Probably there is an issue in resolving traits in prelude.

## Version info
`rustup show`
```
active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.56.0 (09c42c458 2021-10-18)
```
`:CocInfo`
```
## versions

vim version: NVIM v0.6.0-dev+nightly-756-g8c74c895b
node version: v14.18.1
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /Users/username/.vim/dein/.cache/init.vim/.dein
term: tmux
platform: darwin
```

**Comment by TonalidadeHidrica** [comment]
I forgot to mention, but I guess I was using `2021-10-25` then.  Now I updated to `[coc.nvim] rust-analyzer 04f03a360 2021-11-01 stable`.  Then I found similar error, even in Edition 2021.  I was looking for how to reproduce it, then suddenly everything went well -- even for the one I explained initially!!  I have no idea why it happened, but since I cannot reproduce it anymore, I'll close this issue.  Please reopen if some could reproduce it.

**Comment by lnicola** [comment]
No, this is a real bug, I can reproduce it in `1.57.0-beta.2`, but only in the 2018 edition.

**Comment by johnmave126** [comment]
I can reproduce a similar issue in 1.56.1 with 2021-11-01 rust-analyzer in the 2021 edition by shadowing `try_into` with a custom trait. See an example at [rustcc](https://rustcc.cn/article?id=d093f682-f2c2-4121-933f-b4c0bc5ff8ca)

**Comment by flodiebold** [comment]
@johnmave126 would you mind reporting that as a separate issue, including the code example and what the problem is? It's not obvious it's actually the same problem, misresolved methods can have many underlying causes.
