### ISSUE TITLE
Reduce target dir lock contention with explicit `CARGO_TARGET_DIR` override for all `cargo check` operations

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#10684]
When `rust-analyzer` runs `cargo check` during the initial project loading or when reloading the workspace metadata after changes to `Cargo.toml` files, then `cargo` process acquires the file lock on `target` directory.

It is very annoying to wait for that lock to be released when all you wanted is just to open the project in an IDE and build it immediately.

I suggest adding an opt-in configuration to use a separate target dir for all `cargo check` operations that `rust-analyzer` does. It will let us get rid of file lock contention at the cost of spending more CPU cycles to do repeated incremental builds and FS memory for a separate build directory owned exclusively by `rust-analyzer`.

**Comment by Veykril** [comment]
I don't think we need an extra flag for that, the user can just set the `CARGO_TARGET_DIR` explicitly in the server env vars(`rust-analyzer.server.extraEnv`).

**Comment by Veetaha** [comment]
Yep, that seems to resolve this question, thank you!
