### ISSUE TITLE
Request: auto-complete for lints

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#10682]
When adding attributes to adjust lint levels, such as `warn(missing_docs)`, `allow(non_snake_case)`, and so on, there is no auto-complete support.

Since lints are pulled from a fairly fixed list, this is hopefully simple enough to provide suggestions for.

**Comment by Veykril** [comment]
Where exactly is no autocomplete support? Typing inside a `#[allow($0)]` ($0 being the cursor) should give you completions.
![grafik](https://user-images.githubusercontent.com/3757771/140064212-1703ca50-ece0-4de1-bfcc-506e9528f82e.png)

**Comment by Lokathor** [comment]
Ah, then perhaps it's missing only for inner attributes.

![Screenshot 2021-11-03 17 06 51](https://user-images.githubusercontent.com/5456384/140230975-b77901ba-dfc4-4ac9-b4f2-dabfa4c2f33d.png)

**Comment by Veykril** [comment]
Ah no, the problem here is that the parentheses is unclosed, `#![allow($0)` works but `#![allow($0` does not. Will have to investigate if we can fix this as effectively the entire file turns into the attribute's input.
