### ISSUE TITLE
curl: (23) Failure writing output to destination

### ISSUE THREAD

**Issue by adsick** [rust-analyzer/rust-analyzer#10687]
Hi, I was trying to install server binary but it doesn't work.
I'm on Fedora 35.

code I ran: 
```
sudo curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz | gunzip -c - > ~/.local/bin/rust-analyzer
```

**Comment by lnicola** [comment]
There's no need to use `sudo curl` here. In any case, what do you mean by "doesn't work"? Do you have a `~/.local/bin` directory? Does `curl -LO https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz` work?

**Comment by adsick** [comment]
works, but the guide says nothing about '~/.local/bin' existance. I think if on provides obscure-lookingcurs commands they should "just work"

**Comment by lnicola** [comment]
The command in the manual is a starting point. You need to update it for your architecture, and to make sure that the destination directory is in `PATH`, but mentioning that the destination directory has to exist would be a good idea.

**Comment by adsick** [comment]
agree on the last one. also I'd suggest simply using more common directory (which probably exists already) e.g. ```usr/local/bin``` (not ~)

**Comment by lnicola** [comment]
`/usr/local/bin` is worse because the user might not be able to write there (you don't need `sudo` rights to write Rust). I use `~/.cargo/bin` myself.

**Comment by adsick** [comment]
I thought the whole point of  ```usr/local/bin``` is that user writes to it but well... yes, ```~/.cargo/bin``` seems good
