### ISSUE TITLE
Neovimprintln is unsafe operation

### ISSUE THREAD

**Issue by AlePon123** [rust-analyzer/rust-analyzer#10694]

**Comment by AlePon123** [comment]
![image](https://user-images.githubusercontent.com/72556979/140383296-f26fbb5c-b7f3-4abf-b331-2a692d03ee34.png)

**Comment by flodiebold** [comment]
Please make sure you're using the newest rust-analyzer version, I'm pretty sure this has been fixed.

**Comment by AlePon123** [comment]
i make rustup update
but its not fixed

**Comment by lnicola** [comment]
How did you install `rust-analyzer`?

**Comment by AlePon123** [comment]
> How did you install `rust-analyzer`?

by rustup

**Comment by lnicola** [comment]
What does `rust-analyzer --version` print?

**Comment by AlePon123** [comment]
> What does `rust-analyzer --version` print?

![image](https://user-images.githubusercontent.com/72556979/140767783-5c99fee1-dd21-47d6-8c91-89c1c5fb9179.png)

**Comment by lnicola** [comment]
That's a version from the 8th of June.

**Comment by AlePon123** [comment]
so how can i update it?

**Comment by lnicola** [comment]
If it's really the `rustup` version, `rustup update nightly` should do it. But it's also possible that you have a from-source build installed somewhere, in which case you need to remove or update that. Try `which rust-analyzer` to see where it's installed.
