### ISSUE TITLE
Crashes on Fedora 35 (VSCode)

### ISSUE THREAD

**Issue by adsick** [rust-analyzer/rust-analyzer#10693]
Hi, I'm getting unexpected crashes while rust-analyzer is working in startup mode (after 1-3 minutes of work)
I see high ram usage (I've got 6Gb of ram on my system and it is full) I know it is not much ram, but interestingly: if startup was successful rust-analyzer is using **much less ram in the end** so I wonder what is going wrong with it in init phase.

**Comment by lnicola** [comment]
Does `rust-analyzer analysis-stats .` work in your project directory? And how much memory does it use?

**Comment by adsick** [comment]
I'm not sure what do you mean.

**Comment by lnicola** [comment]
Open a terminal, `cd` to the project directory, then run `time rust-analyzer analysis-stats .` while keeping an eye on the RAM usage in another terminal.

**Comment by adsick** [comment]
it is installed via VSCode extensions, so it can not be called from the terminal.

**Comment by lnicola** [comment]
I thought you weren't using Code because of https://github.com/rust-analyzer/rust-analyzer/issues/10687. You can run it from `~/.config/Code/User/globalStorage/matklad.rust-analyzer`.

**Comment by adsick** [comment]
#10687 was the reason I'm trying to use it through VSC. Ok, I'll try

**Comment by lnicola** [comment]
The worse performance problems I've seen were on trait-heavy code like in some crypto projects. Is your code open-source?

**Comment by adsick** [comment]
yes, and it is crypto

**Comment by adsick** [comment]
```
Database loaded:     5.75s, 520minstr (metadata 3.33s, 47minstr; build 591.64ms, 16minstr)
  crates: 1, mods: 3, decls: 16, fns: 8
Item Collection:     52.46s, 146ginstr
  exprs: 126, ??ty: 0 (0%), ?ty: 0 (0%), !ty: 0  
Inference:           13.71s, 42ginstr
Total:               66.17s, 188ginstr

real	1m14.579s
user	1m9.631s
sys	0m1.949s
````

**Comment by adsick** [comment]
https://github.com/nearcomponents/nearapps/tree/develop/makewallets/contract

**Comment by lnicola** [comment]
For me, `rust-analyzer` doesn't go over 1.2 GB on that code, not even if I open it in Code (1 GB on `analysis-stats`).

![image](https://user-images.githubusercontent.com/308347/140304052-067d0f44-7997-4565-9aea-a20a627d8a52.png)

I noticed some C++ code being built. Are you sure the memory usage was from RA and not from the C++ compiler and linker?

**Comment by adsick** [comment]
and you're right, as I mentioned RA does not like enormous amounts of RAM (in this case) 
I see a lot of Cpp related processes who eat the ram. Now I order a new ram module.

**Comment by lnicola** [comment]
Well, a `cargo check` or `cargo build` will do the same thing. There's not much we can do about it. The good news is that it should only happen on the first load or build.
