### ISSUE TITLE
`self` is has unresolvedReference semantic token when using async-trait

### ISSUE THREAD

**Issue by jhgg** [rust-analyzer/rust-analyzer#10708]
Given this code:

```rust
#[async_trait::async_trait]
trait Foo {
    async fn foo(&self);
}

struct Bar {
    x: usize,
}

#[async_trait::async_trait]
impl Foo for Bar {
    async fn foo(&self) {
        let y = self.x;
        //      ^^^^ unresolvedReference
    }
}
```

`self` is marked as an `unresolvedReference`

However, type inference does appear to work, and we can see inlay hints display:

![image](https://user-images.githubusercontent.com/5489149/140591519-b0554493-2123-439d-b12c-acb9b8289d06.png)

**Comment by Veykril** [comment]
`async_trait` rewrites `self` accesses to use a new local `__self`, so our downmapping infra seems to break down here somewhere(as the attribute does properly set the spans for these).
