### ISSUE TITLE
shadowed trait in a generic argument causes incorrect name resolution.

### ISSUE THREAD

**Issue by jhgg** [rust-analyzer/rust-analyzer#10707]
Consider this code:

```rust
trait A {
    fn woop(&self);
}
trait B {
    const X: usize;
    fn woop(&self);
}

impl<A> B for A
where
    A: B,
{
    const X: usize = 1;

    fn woop(&self) {
        println!("{}", A::X);
        //             ^ this is considered as `trait A` not the generic param `A` by r-a.
    }
}

fn main() {}
```

See: 

![image](https://user-images.githubusercontent.com/5489149/140581619-02ea7dcb-d51c-428a-b7aa-df568d0e550b.png)

This also impacts rename, which gets a tad confused:

![2021-11-05_14-40-02](https://user-images.githubusercontent.com/5489149/140581703-e057e93d-9fd6-4a4a-89a1-b94bf7944519.gif)

Rustc however does resolve this properly and the program provided compiles fine.

**Comment by lnicola** [comment]
The might be two issues here:

 - we don't support const generics much outside of parsing
 - this still happens if you replace the const with an associated type, which may or may not be https://github.com/rust-analyzer/rust-analyzer/issues/8282

**Comment by jhgg** [comment]
> * we don't support const generics much outside of parsing

This occurs if you were to do:

```rust
     fn woop(&self) {
        println!("{}", A::woot());
        //             ^ this is considered as `trait A` not the generic param `A` by r-a.
    }
```

As well, so probably not related to const generic 🤔

**Comment by flodiebold** [comment]
`A::X` gets correctly resolved, so this seems to be a problem purely in the IDE layer name resolution.
