### ISSUE TITLE
Enabling `Proc Attr Macros` result in error `called 'Option::unwrap()' on a 'None' value`

### ISSUE THREAD

**Issue by BlackDex** [rust-analyzer/rust-analyzer#10710]
While coding on the [Vaultwarden](https://github.com/dani-garcia/vaultwarden) project and having `Proc Attr Macros` enabled i receive several errors. I receive these errors using a current open PR [Macro recursion decrease and other optimizations](https://github.com/dani-garcia/vaultwarden/pull/2084), else i would receive a macro recursion error.

Is there something i can change or do, or can i provide some more information to help and solve this :).

```json
[{
	"resource": "/vaultwarden/src/api/admin.rs",
	"owner": "rustc",
	"code": {
		"value": "macro-error",
		"target": {
			"$mid": 1,
			"external": "https://rust-analyzer.github.io/manual.html#macro-error",
			"path": "/manual.html",
			"scheme": "https",
			"authority": "rust-analyzer.github.io",
			"fragment": "macro-error"
		}
	},
	"severity": 8,
	"message": "not implemented",
	"source": "rust-analyzer",
	"startLineNumber": 72,
	"startColumn": 1,
	"endLineNumber": 75,
	"endColumn": 2
}]
```

```json
[{
	"resource": "/vaultwarden/src/api/admin.rs",
	"owner": "rustc",
	"code": {
		"value": "macro-error",
		"target": {
			"$mid": 1,
			"external": "https://rust-analyzer.github.io/manual.html#macro-error",
			"path": "/manual.html",
			"scheme": "https",
			"authority": "rust-analyzer.github.io",
			"fragment": "macro-error"
		}
	},
	"severity": 8,
	"message": "called `Option::unwrap()` on a `None` value",
	"source": "rust-analyzer",
	"startLineNumber": 139,
	"startColumn": 1,
	"endLineNumber": 153,
	"endColumn": 2
}]
```

**Comment by Veykril** [comment]
What is your current rustc version you are running? Might be that you have a recent nightly that changed the proc-macro abi again

**Comment by BlackDex** [comment]
I was using 2021-10-14, and i updated yesterday to the latest available.

**Comment by lnicola** [comment]
This crashes because we don't implement `Span::source_file`. As noted in https://github.com/rust-analyzer/rust-analyzer/pull/10378, this is unstable, but it doesn't help when using `rocket`.

I was surprised about this because `rocket 0.5` is supposed to build on `stable` -- [and it does](https://github.com/SergioBenitez/Rocket/runs/3461025672?check_suite_focus=true) --, but `valutwarden` is on a revision from [July 2020](https://github.com/SergioBenitez/Rocket/commits/263e39b5b429de1913ce7e3036575a7b4d88b6d7).

**Comment by BlackDex** [comment]
Ok, we have created a new branch now which is using the 0.5rc version that indeed seems to solve it when using stable.
Though i now have a regression i think with some other stuff, i will need to create a new ticket for that.

Thanks for 'pushing' us to go and update it.
