### ISSUE TITLE
[VSCode] Rust Analyzer never stops loading

### ISSUE THREAD

**Issue by AqilCont** [rust-analyzer/rust-analyzer#10715]
I don't know if I leave this issue here, but this has been the same for the past 15 hours and literally stops me from compiling since rust-analyzer is blocking. I can't work on the app at all without these suggestions either, since I'm a beginner and need some help with docs and types and stuff. I really hope someone can help :(

Project: A bevy game project that usually takes about 20 mins on first compile, a minute after.

![image](https://user-images.githubusercontent.com/32044067/140655259-4c9762bf-4f4f-4a47-aa2e-b49e6dc5935c.png)

**Comment by lnicola** [comment]
What happens if you run `rust-analyzer analysis-stats .` in your project directory?

**Comment by AqilCont** [comment]
Sorry, I had to install rust-analyzer separately for a bit but it's been like this for a while:
![image](https://user-images.githubusercontent.com/32044067/140655814-230cdbec-8a13-4db7-8aa0-0b28c3e78151.png)

**Comment by lnicola** [comment]
Give it some time, it runs `cargo check` the first time. Do you see anything in Task Manager?

**Comment by AqilCont** [comment]
It's technically not doing anyting, if looknig at just task manager:
![image](https://user-images.githubusercontent.com/32044067/140656170-eb4f245b-bad3-47e1-88d9-b723be262226.png)
![image](https://user-images.githubusercontent.com/32044067/140656194-f7637a37-b292-44dc-a7ca-b66f1068337e.png)

**Comment by lnicola** [comment]
Can you kill it and all the other rustc and cargo processes, then try again from the command line?

**Comment by AqilCont** [comment]
Huh.. I killed every cargo, rustc, and rust-analyzer process but the commandline didn't die, and instead actually started to produce output :o
![image](https://user-images.githubusercontent.com/32044067/140656436-32812252-2522-482e-992e-23989dfd751f.png)

Sorry, I guess the directory could still have been locked even after I closed VSC, and that Task Manager didn't actually display the exact command-line process.

**Comment by lnicola** [comment]
Yeah, it was probably locked, though I don't know why they didn't make any progress. Does it load fine in Code now?

**Comment by AqilCont** [comment]
I guess, this has been going on at least:
![image](https://user-images.githubusercontent.com/32044067/140657241-69e0b34c-b0d3-4636-a04e-184161d13912.png)

It's taking a really long time tho. I'll wait a bit more and then report back to see if it finally loads. I wish I could use it straightaway even before it loads every single module :<

**Comment by AqilCont** [comment]
Other than this, rust analyzer was sort of slow for hover and autocomplete(me having to wait for about 4-10 seconds sometimes), but that's probably another issue. Thanks a lot for helping me solve this! I guess I should check for residual processes next time :D

**Comment by MrImmortal09** [comment]
Thanks for the solution. Helped me too.
