### ISSUE TITLE
Can't find crate for `test` error

### ISSUE THREAD

**Issue by caemor** [rust-analyzer/rust-analyzer#10716]
It seems to be a new error or I always manually compiled with the specific target but rust analyzer outputs that it can't find crate for `test` with the target set to a the target seen below (and maybe to others as well?). For each bin, lib.rs or main.rs it outputs the exact same message once.

Reduced example: 
Create new rust project with `cargo new SomeName` and then modify the following files:
`.cargo/config.toml`:
```
[build]
target = "thumbv7em-none-eabihf"
```
`main.rs`:
```
#![no_std]
fn main() {}
```

Rust Analyzer: v0.2.801

Copied Error Message: 
```
{
	"resource": "/tmp/rustanalyzertest/src/main.rs",
	"owner": "rustc",
	"code": {
		"value": "E0463",
		"target": {
			"$mid": 1,
			"external": "https://doc.rust-lang.org/error-index.html#E0463",
			"path": "/error-index.html",
			"scheme": "https",
			"authority": "doc.rust-lang.org",
			"fragment": "E0463"
		}
	},
	"severity": 8,
	"message": "can't find crate for `test`\ncan't find crate",
	"source": "rustc",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
```

**Comment by Veykril** [comment]
probably same as in https://github.com/rust-analyzer/rust-analyzer/issues/10659#issuecomment-954739511
> This is due to rust-analyzer implicitly passing `--all-targets` to the flycheck cargo invocation which makes it include the `test` crate which depends on `std`. You can get around this by setting the corresponding setting `rust-analyzer.checkOnSave.allTargets` to `false`.

**Comment by caemor** [comment]
Yes this fixed the issue, thanks.

**Comment by amchen2310** [comment]
![Image](https://github.com/user-attachments/assets/020ac0d9-5f86-426b-ac48-ed39ce00402f)
yes it works
