### ISSUE TITLE
Possible regression parsing marcro's

### ISSUE THREAD

**Issue by BlackDex** [rust-analyzer/rust-analyzer#10721]
Upon version `0.2.792` there was no issue, but after that i receive the following error message.
I'm using [async branch](https://github.com/dani-garcia/vaultwarden/tree/async) which is using Rust Stable v1.56.1.
Though this also happens on the main branch using the nightly rustc.

If you need more information, please let me know.

```json
[{
	"resource": "/vaultwarden/src/config.rs",
	"owner": "rustc",
	"code": {
		"value": "macro-error",
		"target": {
			"$mid": 1,
			"external": "https://rust-analyzer.github.io/manual.html#macro-error",
			"path": "/manual.html",
			"scheme": "https",
			"authority": "rust-analyzer.github.io",
			"fragment": "macro-error"
		}
	},
	"severity": 8,
	"message": "unexpected token in input",
	"source": "rust-analyzer",
	"startLineNumber": 930,
	"startColumn": 5,
	"endLineNumber": 930,
	"endColumn": 40
}]
```

**Comment by bjorn3** [comment]
For reference the error happens at https://github.com/dani-garcia/vaultwarden/blob/39ea7fcf2d65c73d53da42877eb3993a052d045a/src/config.rs#L930

**Comment by Veykril** [comment]
Might be https://github.com/rust-analyzer/rust-analyzer/pull/10623 as that seems to be the only PR that has touched mbe recently

**Comment by Veykril** [comment]
repro:
```rs
macro_rules! reg {
    ($name:expr) => {{
        concat!($name);
    }};
    ($name:expr, $ext:expr) => {
        reg!(concat!($name, $ext));
    };
}

reg!("email/change_email", ".html");
```
