### ISSUE TITLE
Drop mocha as testing framework

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#10723]
We currently have a couple of client-side test, using `vscode-test` and `mocha`. The latter seems popular, but looking over its dependency tree made me quite [uncomfortable](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/RFC.3A.20dropping.20client-side.20tests).

Let's try to implement simple a replacement for it, if possible.

**Comment by Aloso** [comment]
I wouldn't recommend writing a testing framework from scratch, that would be reinventing the wheel. There are testing libraries with no (or very few) dependencies, for example [QUnit](https://github.com/qunitjs/qunit).

**Comment by lnicola** [comment]
> QUnit has no dependencies

I... don't even know what that means.

![image](https://user-images.githubusercontent.com/308347/144384232-6f3aa308-5ec0-4307-96e2-476da750e77e.png)

**Comment by Aloso** [comment]
@lnicola the `devDependencies` aren't installed when you use a NPM package, only the `dependencies`. So QUnit has 3 direct dependencies (5 in total). But QUnit was just an example, there are other options as well.

**Comment by flodiebold** [comment]
> I wouldn't recommend writing a testing framework from scratch, that would be reinventing the wheel.

It's not so much reinventing the wheel, as realizing we don't need a wheel because we're completely stationary :wink:
