### ISSUE TITLE
Poor semantic highlighting inside Yew procedural macros

### ISSUE THREAD

**Issue by al2me6** [rust-analyzer/rust-analyzer#10727]
Semantic highlighting inside Yew's `html` proc macros are nonsensical, with many types and identifiers being highlighted as `keyword.operator`, `string` , or `meta.attribute.rust`:

![image](https://user-images.githubusercontent.com/35266431/140813483-b115f9ca-eefe-437d-ad0a-02ec5cdbe3e1.png)

![image](https://user-images.githubusercontent.com/35266431/140813887-3bf80128-4f17-490d-93f7-6ff5fdcdff84.png)

(Here, blue is types, red is operators, yellow is strings, and gray is attributes.)

Without semantic highlighting, for comparison:

![image](https://user-images.githubusercontent.com/35266431/140814021-35b82be7-be51-47e1-956f-757f10b8c321.png)

![image](https://user-images.githubusercontent.com/35266431/140814060-f50ee750-fa06-411c-9d94-9ce14203df7b.png)

This is the macro expansion result of the second snippet:

```rust
{
    #[allow(clippy::useless_conversion, unused_braces)]
    ::yew::virtual_dom::VNode::from({
        #[allow(unused_braces)]
        let mut __yew_vtag =
            ::yew::virtual_dom::VTag::new(::std::borrow::Cow::<'static, str>::Borrowed(
                "option",
            ));
        __yew_vtag.attributes = ::yew::virtual_dom::Attributes::Vec(
            (<[_]>::into_vec(box [
                (::yew::virtual_dom::PositionalAttr::new("value", idx.to_string())),
                (::yew::virtual_dom::PositionalAttr::new_boolean(
                    "selected",
                    item == selected_item,
                )),
            ])),
        );
        #[allow(clippy::redundant_clone, unused_braces)]
        __yew_vtag.add_children({
            let mut __yew_v = ::std::vec::Vec::new();
            __yew_v.extend(::std::convert::Into::<::yew::utils::NodeSeq<_, _>>::into(
                display,
            ));
            __yew_v
        });
        ::yew::virtual_dom::VNode::from(__yew_vtag)
    })
}
```

**Comment by Veykril** [comment]
The weird coloring comes from the macro reusing spans for things, so `selected` is yellow for example, because the identifiers span gets remapped to a string of it, as such we resolve it to a string in the macro input. Therefor this is issue lies with the yew macro, so you should open an issue on that repository about he usage of the spans if this is an issue.

**Comment by Veykril** [comment]
Closing as this is a non-ra issue
