### ISSUE TITLE
Support cfg options and features

### ISSUE THREAD

**Issue by zbuc** [rust-analyzer/rust-analyzer#1073]
Based on discussion from Zulip: It would be nice if the VSCode extension, and rust-analyzer, supported `cfg` options, for example detecting the running OS, and passing feature flags.

RLS supports this via a few configuration options: `rust.features`, `rust.all_features`, `rust.no_default_features`: https://github.com/rust-lang/rls-vscode/commit/b7ff59cb6c88a21a259cce593e31deb9c9696377

**Comment by kiljacken** [comment]
This seems to have been fixed, with #1928 and the support to specify custom features in the server config. Time to close?
