### ISSUE TITLE
rust-analyzer crashes when inputting a particular character in a comment.

### ISSUE THREAD

**Issue by foo-jin** [rust-analyzer/rust-analyzer#10746]
### Description
When inputting the unicode character `𝛂` (U+1D6C2) in a comment and typing another character afterwards, rust-analyzer crashes with the following message:
`thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)'`. The same thing happens any time the server starts up and I edit the character directly following  `𝛂`. MATHEMATICAL BOLD SMALL ALPHA seems to be a proper unicode character as far as I can tell, so I'm not sure what the issue is here.

### Minimal reproducible example
1. Insert the following snippet:
```rust
fn main() {
    // 𝛂
    println!("hello world!")
}
```
2. add/edit the character following `𝛂` on line 2, and RA crashes.

### Versions
rust-analyzer 2021-11-08
emacs 28.0.60
lsp-mode 20211110.1617

**Comment by bjorn3** [comment]
This is probably https://github.com/emacs-lsp/lsp-mode/issues/2080.

**Comment by foo-jin** [comment]
Okay, I'll close up this issue then since its not caused by RA.
