### ISSUE TITLE
Failed to load manifest for workspace member

### ISSUE THREAD

**Issue by SingularisArt** [rust-analyzer/rust-analyzer#10742]
Hello all

I just cloned the repo, and when I run `cargo xtask install --server`, I get the following error:

error: failed to load manifest at `rust-analyzer/xtask/Cargo.toml`

Caused by:
   failed to parse manifest at `rust-analyzer/xtask/Cargo.toml`

Caused by:
   feature `edition2021` is required

   consider adding `cargo-features = ["edition2021"]` to the manifest

Can someone please help me? I really want to have a rust server up and running because currently, I'm learning rust.
Huge thanks to anyone who tries to help! :)

**Comment by bjorn3** [comment]
You will need to update your rustc version. Rustc 1.56 is the oldest currently supported version: https://github.com/rust-analyzer/rust-analyzer/blob/3b3063fb2d1804b3dc42184027ef08073de03fd9/xtask/Cargo.toml#L7

**Comment by lnicola** [comment]
If you're on Debian/Ubuntu, you should install the toolchain using https://rustup.rs, not the system package.

**Comment by SingularisArt** [comment]
I'm trying to update Rust from 1.53 to 1.56, but is version 1.56 supported on 32 bit? I'm currently running 32 bit ubuntu, but after running: `curl -sf -L https://static.rust-lang.org/rustup.sh | sh`, I keep getting an error saying:

`could not download file from `https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256`: failed to make network requestion: error sending requestion for url: operation timed out: operation timed out.

**Comment by bjorn3** [comment]
> but is version 1.56 supported on 32 bit? 

Yes, 32bit linux and windows are still tier 1 platforms (guaranteed to build and pass all tests): https://doc.rust-lang.org/nightly/rustc/platform-support.html 32bit support for macos had to be dropped to tier 3 (not guaranteed to build) though for the reasons outlined in https://blog.rust-lang.org/2020/01/03/reducing-support-for-32-bit-apple-targets.html.

Downloading https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256 works for me. Maybe it was just a spurious error on your side?

**Comment by SingularisArt** [comment]
How do you update rust with rustup? I tried `rustup update stable, rustup update nightly`, but they all don't work. What do you do to update your version?

**Comment by lnicola** [comment]
`rustup toolchain list` to see the installed toolchains and `rustup update` or `rustup update stable` to update one. If it's the latest version, it will say:

```
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.56.1 (59eed8a2a 2021-11-01)
```

**Comment by SingularisArt** [comment]
When I run `rustup toolchain list`, I don't have any installed toolchains. And when I try to install it running `rustup install stable`, I get the same error.

**Comment by lnicola** [comment]
What error, `operation timed out`? That's a network problem, do you need a proxy server?

**Comment by SingularisArt** [comment]
Yeah. The error says:

`Could not download file from 'link to channel-rust-stable.toml.sha256': failed to make network requestion: error sending requestion url: error trying to connect: dns error: failed to look up address information: name or service not known

**Comment by lnicola** [comment]
That's a different error (DNS, not timeout). Does `curl -L https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256` work?

**Comment by SingularisArt** [comment]
It works. I don't get any error messages. When running:

```
curl -L https://static.rust-lang.org/dist/channel-rust-stable.toml
```

I get the same output as yours. And when running

```
curl -L https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256
```

I get the same output as yours

**Comment by SingularisArt** [comment]
Okay, I finally got it to work. For those who have the same issue, use this command:

`curl https://sh.rustup.rs -sSf  | sh`

That will, hopefully, install and/or update your `rustc` version. Thanks for all of your help.
I'm going to go ahead and close this issue now, since I found the solution.

**Comment by TheEhsanSarshar** [comment]
I am using the latest version of rustc `rustc 1.60.0-nightly (27f5d830e 2022-02-02)`
but still have the same error

**Comment by SingularisArt** [comment]
Honestly, I don't know much, but try out the command @lnicola told me to try and post the output here. The command is:
```bash
curl -L https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256
```

**Comment by TheEhsanSarshar** [comment]
I have globally installed latest version `rustc 1.60.0-nightly (27f5d830e 2022-02-02)`, but my local project was using an older version.

after updating rust version inside `rust-toolchain` everthing is now working.

**Comment by Alef-gabriel** [comment]
I have installed latest. I update local with `cargo install --force cargo´ everthing is now working.

**Comment by realyukii** [comment]
I'm new in rust, does this error cause any functionality issues? or it just inform the user that it fail to load manifest? so far I'm not seeing malfunction of rust-analyzer from this issues

**Comment by ChayimFriedman2** [comment]
@realyukii Are you referring to this error when installing rust-analyzer from source or when using it?

**Comment by realyukii** [comment]
I'm using it as LSP with neovim
