### ISSUE TITLE
Tests generated from macros lead to funky CodeLens in VS Code

### ISSUE THREAD

**Issue by matthew-e-brown** [rust-analyzer/rust-analyzer#10744]
When working on old Advent of Code problems, I was writing up the examples as test cases. To be DRY, I decided to use the [`test-case` crate](https://crates.io/crates/test-case):

```rs
    #[test_case("(())",      0 ; "case 1")]
    #[test_case("()()",      0 ; "case 2")]
    #[test_case("(((",       3 ; "case 3")]
    #[test_case("(((",       3 ; "case 4")]
    #[test_case("))(((((",   3 ; "case 5")]
    #[test_case("())",      -1 ; "case 6")]
    #[test_case("))(",      -1 ; "case 7")]
    #[test_case(")))",      -3 ; "case 8")]
    #[test_case(")())())",  -3 ; "case 9")]
    fn example(str_sequence: &str, result: i32) {
        let sequence = directions_from_string(str_sequence).unwrap();
        assert_eq!(run_1(&sequence), result);
    }
```

Unfortunately, it leads to some pretty unsightly results in the CodeLens:

![](https://user-images.githubusercontent.com/43387454/141339930-d6e64e11-70e6-425f-8321-abbc2000bf01.png)

All of the 'Run fn_name Tests | Debug' options are strung together and not separated, and fly way off the side of the page. If I wanted to use one of them, it would be near impossible to find which of the chunks I'm supposed to click on for which test. I'm not sure if this is more to do with Rust Analyzer or VS Code itself, but since an issue here will get more eyes than one in the VSC repo, it's probably best to start here—if this is not the right place for this issue, please direct me to the right place! Thanks.

**Comment by Veykril** [comment]
Hmm looks like something broke here, those lenses are supposed to be `Run case_1 Test` etc. `rstest` also seems to not work anymore.

Though the lenses going off to the right is technically a problem with VSCode, the only thing we could do is limit how many runnables we can show.
