### ISSUE TITLE
failed to write request: Broken pipe (os error 32)rust-analyzermacro-error

### ISSUE THREAD

**Issue by kulame** [rust-analyzer/rust-analyzer#10766]
```rust
/// Instructions supported by the generic Name Registry program
#[derive(Clone, BorshSerialize, BorshDeserialize, PartialEq)]
pub enum AggregatorInstruction {
    /// Accounts:
    ///   0. [writable] The aggregator to initialize
    ///   1. [sign] Owner
    ///   2. [] Rent sysvar
    ///   3. [] Clock sysvar
    Initialize(Config),
    /// Accounts:
    ///   0. [writable] The aggregator
    ///   1. [sign] Oracle
    ///   2. [] Clock sysvar
    Submit { timestamp: Timestamp, value: Value },
}
```

it show some error 
```shell
failed to write request: Broken pipe (os error 32)rust-analyzermacro-error
failed to write request: Broken pipe (os error 32)rust-analyzermacro-error
```

**Comment by bjorn3** [comment]
Just to confirm. Are those proc macros from the [borsh](https://crates.io/crates/borsh) crate?

**Comment by kulame** [comment]
yep, it used borsh

**Comment by yotamofek** [comment]
This is breakage probably caused by the merging of this PR: https://github.com/rust-lang/rust/pull/87264
I'm guessing it has to do with being on the latest rustc nightly rather than a specific crate's proc macros :)

**Comment by kulame** [comment]
TvT

**Comment by bjorn3** [comment]
https://github.com/rust-lang/rust/pull/87264/files#diff-b42e9adad2cfc0be65632a15d616c95b812effe27357d9f5aee13cd949d68190R65

the proc macro bridge will need to be updated. https://github.com/rust-analyzer/rust-analyzer/tree/master/crates/proc_macro_srv/src/abis needs to get a new directory for the 1.58 abi. @alexjg would you mind doing this?

**Comment by alexjg** [comment]
I'll sort it out tomorrow!

**Comment by qm3ster** [comment]
idk if tomorrow means fix will ship this Monday or next, but to whomst'd've it may've concerned, the temporary fix is:
```
rustup default nightly-2021-11-12
```
to undo:
```
rustup default nightly
rustup uninstall nightly-2021-11-12
```

**Comment by kulame** [comment]
great!!!

**Comment by UsmannK** [comment]
I'm using `nightly-2021-11-12-x86_64-unknown-linux-gnu unchanged - rustc 1.58.0-nightly (936238a92 2021-11-11)` and rust-analyzer extension `v0.2.817` from VSCode and still getting this error. 

Do either of these version seem wrong? Thanks!

**Comment by Sword-Smith** [comment]
Having the same problem in VS Code with `rust-analyzer`. Will prefer to stay on stable and not upgrade to nightly, so there is no fix for me yet.

**Comment by qm3ster** [comment]
@Sword-Smith we were **down**grading the nightly, and that has since been resolved in #10769 and released yesterday.
We can all return to the current nightly now.
If you are currently having a problem with `stable` rustc, [which is `1.56.1`](https://www.whatrustisit.com/), it's either a regression for the old ABI or an unrelated problem altogether.

Please make sure:
1. you `rustup update` your stable
2. Ctrl-Shift-P > Rust Analyzer: Show RA Version shows `rust-analyzer version: 183ef048f 2021-11-22 stable` (that's the actual rust-analyzer binary that the `matklad.rust-analyzer` VS Code extension downloads separately). If not, close __all__ your VS Code windows, it will try to update on next open.
3. `cargo clean` your project

and then post the particular error you are getting.

**Comment by Sword-Smith** [comment]
> @Sword-Smith we were **down**grading the nightly, and that has since been resolved in #10769 and released yesterday. We can all return to the current nightly now. If you are currently having a problem with `stable` rustc, [which is `1.56.1`](https://www.whatrustisit.com/), it's either a regression for the old ABI or an unrelated problem altogether.
> 
> Please make sure:
> 
>     1. you `rustup update` your stable
> 
>     2. Ctrl-Shift-P > Rust Analyzer: Show RA Version shows `rust-analyzer version: 183ef048f 2021-11-22 stable` (that's the actual rust-analyzer binary that the `matklad.rust-analyzer` VS Code extension downloads separately). If not, close **all** your VS Code windows, it will try to update on next open.
> 
>     3. `cargo clean` your project
> 
> 
> and then post the particular error you are getting.

I went through all your steps but had to add another one, even though VS Code showed the version you described in step 2:

4. Close **all** VS Code windows and open them again.

**Comment by ErwanDL** [comment]
Just encountered the same problem as @Sword-Smith, I believed it happened just after I updated to the latest version of VSCode. I ran `rustup update` and then quit VSCode and restarted it and the error messages went way (not sure if the `rustup update` was necessary or if fully restarting VSCode would have sufficed).

**Comment by alexjg** [comment]
Unfortunately this error message is fairly general and will be caused by many different scenarios. I'm fairly sure the code posted in this issue no longer causes the problem. If you're experiencing a problem I think the best way to proceed would be to open a new issue with your rust-analyzer and rustc versions and a sample of code which causes the problem, it's much easier to diagnose the problem that way.

**Comment by Voronar** [comment]
Same issue with `rust-analyzer v0.2.826`.
```bash
rustup 1.24.3 (ce5817a94 2021-05-31)
info: The currently active `rustc` version is `rustc 1.54.0 (a178d0322 2021-07-26)`
```

**Comment by taylorlee** [comment]
I also encountered  `[rust-analyzer macro-error] [E] failed to write request: Broken pipe (os error 32)` when using `rust-analyzer d9b2291f5 2021-11-29 stable` via `coc-rust-analyzer  v0.56.0`, but only on codeblocks using `derive(StructOpt)` https://docs.rs/structopt/0.3.25/structopt/index.html#how-to-derivestructopt on a project that had pinned the rust-toolchain to 1.54.0. Upgrading the toolchain to 1.56.1 fixed the issue for me.

**Comment by rahul-soshte** [comment]
I also encountered this error. My system was VSCode + WSL. I made a mistake of using WSL on Windows FileSystem, but then I came to know about the Remote-WSL extension. I switched VSCode to Ubuntu 20.04 filesystem(WSL) and then error was no more. Weird things happen if VSCode is used on Windows Filesystem.

I referred this link for getting the Extension idea. Follow this if you are using WSL + VSCode: https://harsimranmaan.medium.com/install-and-setup-rust-development-environment-on-wsl2-dccb4bf63700

**Comment by GalvinGao** [comment]
> > ```
> > 1. you `rustup update` your stable
> > 
> > 2. Ctrl-Shift-P > Rust Analyzer: Show RA Version shows `rust-analyzer version: 183ef048f 2021-11-22 stable` (that's the actual rust-analyzer binary that the `matklad.rust-analyzer` VS Code extension downloads separately). If not, close **all** your VS Code windows, it will try to update on next open.
> > 
> > 3. `cargo clean` your project
> > ```
> 
> I went through all your steps but had to add another one, even though VS Code showed the version you described in step 2:
> 
> 4. Close **all** VS Code windows and open them again.
> 
> Edit: I took the liberty to post this on Stack Exchange as there is there are too few Rust questions on Stack Exchange: [stackoverflow.com/questions/70079983/rust-analyzer-failed-to-write-request-broken-pipe-os-error-32/70079984](https://stackoverflow.com/questions/70079983/rust-analyzer-failed-to-write-request-broken-pipe-os-error-32/70079984)

For me another key step was to ensure the `rustc` version you are using is actually the one that is provided by `rustup`. I ended up using a Homebrew installation of my rust toolchain and it has a higher precedence in my `PATH` and in result I'm using a more older rust toolchain, specifically `rustc 1.54.0`.

Check using `which rustc` gives me `/usr/local/bin/rustc`, which clearly isn't where `rustup` is installing the toolchain to. By using `brew uninstall rust` and `cargo clean` then `cargo run` everything now works like a charm! :heart:

**Comment by gpeacock** [comment]
> 4. Installed RA Version 0.2.817 (2 versions prior)
> 5. Restarted VSCode, everything worked.

I tried all the other steps and reverting to an older version of the plugin was the only thing that worked for me. I don't want to stop using RA, so I'll stay on this version until this issue gets resolved.

**Comment by syddo** [comment]
Hi. I'm still seeing this error in v0.2.853 when using the crate https://crates.io/crates/builder-pattern with just the example code.
