### ISSUE TITLE
`tokio::test` no longer triggers test runner

### ISSUE THREAD

**Issue by crepererum** [rust-analyzer/rust-analyzer#10768]
With the 2021-11-15 release, rust-analyzer now longer shows a clickable `Run Tests | Debug` helper for tests using `tokio::tests`.

## Example

Code can be found here: <https://github.com/crepererum/rust-analyzer_issue_10768>

### Before (2021-11-08 release)
![Screenshot from 2021-11-15 10-34-45](https://user-images.githubusercontent.com/1529400/141758221-a70ca07f-1c52-49af-8f8d-0d323dafc98d.png)

### After (2021-11-15 release)
![Screenshot from 2021-11-15 10-35-15](https://user-images.githubusercontent.com/1529400/141758277-6d23e7ad-cf7b-4d65-b39e-bfb9fff88cfd.png)

**Comment by lnicola** [comment]
Maybe https://github.com/rust-analyzer/rust-analyzer/pull/10747?

**Comment by Veykril** [comment]
Ye thats cause of #10747, for some reason the expansion is missing the `#[test]` even though the macro emits it.
