### ISSUE TITLE
Doc Links Are Not Always Highlighted Correctly

### ISSUE THREAD

**Issue by alexkolson** [rust-analyzer/rust-analyzer#10782]
Thanks so much for rust-anaylzer! It is amazing! 

Very minor, but recently I wrote this line as part of a documentation comment in rust:

```rust
/// [std::mem::drop] blah blah blah [std::vec::Vec::from_raw_parts]
```

I noticed that the first doc link was highlighted but not the second one.  They both create links to the right items in rust's std documentation when run through `rustdoc`. Is this a bug? Is this known behavior? Am I doing something wrong here?

Thanks!

**Comment by Veykril** [comment]
Yep this is a known problem currently, https://github.com/rust-analyzer/rust-analyzer/issues/9694
