### ISSUE TITLE
Error message given when features are enabled but not present is not accurate

### ISSUE THREAD

**Issue by alexschrod** [rust-analyzer/rust-analyzer#10797]
I had set the "Rust-analyzer > Cargo: Features" setting to have a feature `chrono`, which, when I opened another project without said feature, caused rust-analyzer to be unhappy. The error message I got, however, wasn't particularly good:

> rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file c:\Users\alexs\Documents\Projects\foobar\Cargo.toml, cargo 1.56.0 (4ed5d137b 2021-10-04): Failed to run `cargo metadata --manifest-path c:\Users\alexs\Documents\Projects\foobar\Cargo.toml`: `cargo metadata` exited with an error: error: none of the selected packages contains these features: chrono

The complaint I have is that the "failed to run" command runs perfectly fine if you try to do it manually. I'm guessing the real command contains a "--features chrono" or something like that, but for some reason, that part isn't included in the provided "failed to run" command, so when you try to run it yourself, you don't get an error, just confusion.

**Comment by Veykril** [comment]
The error message is created here:
https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/project_model/src/cargo_workspace.rs#L290
We should probably debug format the executed command here instead

**Comment by jhgg** [comment]
This will become much easier once rust 1.57 releases that stabilizes command_access. This will let us use https://docs.rs/cargo_metadata/0.14.1/cargo_metadata/struct.MetadataCommand.html#method.cargo_command + https://doc.rust-lang.org/std/process/struct.Command.html#method.get_args to print the actual command ran.

**Comment by lnicola** [comment]
> This will become much easier once rust 1.57 releases that stabilizes command_access.

FWIW, that happened today.
