### ISSUE TITLE
No quick fix availabe for "cannot borrow `x` as mutable, as it is not declared as mutable

### ISSUE THREAD

**Issue by jrmuizel** [rust-analyzer/rust-analyzer#10801]
rustc suggests "consider changing this to be mutable: `mut x`". It would be nice of rust-analyzer could easily do this.

**Comment by lnicola** [comment]
We have a quick fix, but it's on the declaration site:

![image](https://user-images.githubusercontent.com/308347/142449126-d174113c-f2e7-46c1-a3df-b27aa9e35264.png)

**Comment by jrmuizel** [comment]
Yeah, I just realized this. Is there a way to make it so that you don't need to jump to the declaration first?

**Comment by lnicola** [comment]
We show the quick fix where `rustc` suggests a replacement, but I don't know if we could also show it on the error location. I think @jonas-schievink experimented with this a while ago.

**Comment by jhgg** [comment]
cc #10658

**Comment by lnicola** [comment]
Let's close this in favor of #10658.
