### ISSUE TITLE
Impl trait bounds in argument position (sometimes?) duplicated as where clauses

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#10800]
Just got the following signature shown in a popup (the `Fn` should also use the usual syntax sugar, that's #8157) for `druid::widget::Button::on_click`:

```rust
pub fn on_click(self, f: impl Fn<(&mut EventCtx, &mut T, &Env), Output = ()> + 'static) -> ControllerHost<Self, Click<T>>
where
    {unnamed}: Fn<(&mut EventCtx, &mut T, &Env), Output = ()> + 'static,
```

I don't think the `impl Fn` argument should be duplicated as a where clause on `{unnamed}`.

**Comment by jonas-schievink** [comment]
This is printed here, should be pretty straightforward to fix:

https://github.com/rust-analyzer/rust-analyzer/blob/a60e009b48a00c6248feca75497648bf16e4a853/crates/hir/src/display.rs#L336
