### ISSUE TITLE
Add support for 2-space formatting

### ISSUE THREAD

**Issue by atlx** [rust-analyzer/rust-analyzer#10818]
Add support for 2-space formatting please, it's forcing me to use 4-spaces but I prefer 2-spaces. I have looked thoroughly through the VSCode extension settings and there is no place to change this. I think there should be an option to select 2 or 4 spaces for document formatting.

Additionally, the formatter doesn't respect my VSCode indentation preference (it should by default).

**Comment by flodiebold** [comment]
rust-analyzer just calls rustfmt. See [here](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#tab_spaces) for its configuration options. Indentation for generated code is covered by #1191.

**Comment by q2333gh** [comment]
here is my solution. it works for me : 
```bash
mkdir -p ~/.config/rustfmt
touch ~/.config/rustfmt/rustfmt.toml
echo -e "\ntab_spaces = 2" >> ~/.config/rustfmt/rustfmt.toml
cargo fmt 
```

**Comment by thisislvca** [comment]
You can also create the file at the root of your project, then add `tab_spaces = 2`.
