### ISSUE TITLE
name resolution with `pub extern crate` not working

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#10836]
https://github.com/matklad/repros/commit/bcac6cd82a187f6daca6f82a6dc855d3a61d0fee

![image](https://user-images.githubusercontent.com/1711539/142875575-79de1c72-694f-4bcb-ae14-39e71deebbe2.png)

The relevant bit of the crate: 

![image](https://user-images.githubusercontent.com/1711539/142875619-cbe38a13-3ac0-43e5-bfc5-ab905283f41c.png)

**Comment by Veykril** [comment]
The problem here is actually a `#![cfg(not(test))]`, cc https://github.com/rust-analyzer/rust-analyzer/issues/7243
