### ISSUE TITLE
Wonky syntax highlighting for indoc macros

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#10845]
*I know macros are super hard to support well, but I couldn't find an existing bug report about this (open or closed) so I thought I'd open this, even if it might not be actionable (I hope it is!).*

When using `formatdoc!` from the [indoc](https://lib.rs/crates/indoc) crate, rust-analyzer tries to highlight `{}`s but fails to do so in the correct positions:

![Screenshot_2021-11-23_135908](https://user-images.githubusercontent.com/951129/143028621-97269167-d2b6-477f-8a4d-ad7509015726.png)

rust-analyzer version: 1b938ef1c 2021-11-23 nightly

**Comment by Veykril** [comment]
I don't think this is fixable unfortunately, having taken a quick look at the implementation the proc-macro rewrites the string literal, to well not contain indentation of course. Meaning it changes the string but keeps the span, so our offsets are wrong(I wonder if this could cause a panic in r-a somewhere, I hope not 😶).

I think the best we can do here is to *not* do the formatting injection when the string literal changes between macro invocations. Though maybe we can also do the injection on the original string in these cases.

**Comment by jplatte** [comment]
> I think the best we can do here is to _not_ do the formatting injection when the string literal changes between macro invocations.

FWIW, I think that would be a lot better than the current state of affairs 😄

> Though maybe we can also do the injection on the original string in these cases.

This would be stellar, of course!

**Comment by Veykril** [comment]
#10849 *should* fix this, I haven't tested it yet though. Will check after tomorrows nightly is out.
