### ISSUE TITLE
[Maybe a feature request] warn deprecated items in completion

### ISSUE THREAD

**Issue by TonalidadeHidrica** [rust-analyzer/rust-analyzer#10844]
During completion, I want to recognize which items are deprecated at a glance.  Maybe showing ⚠️ before item names in the completion list would be nice.

The problem is that I am not quite sure this issue should be filed in this repository.  Is it rather a problem of LSP client?  Anyway, let me submit this so that I won't at least forget my new idea...  Sorry if it bothers you.

**Comment by lnicola** [comment]
We mark them as deprecated and they show up in Code like this:

![image](https://user-images.githubusercontent.com/308347/142991424-ba084eeb-e9ca-484b-ad9b-2412a7c771c5.png)

**Comment by TonalidadeHidrica** [comment]
Alright, so this is coc.nvim issue, which is what I use.  Sorry for the noise.
