### ISSUE TITLE
Feature request: show compact list of fileds/variants of ADT in hover

### ISSUE THREAD

**Issue by andreytkachenko** [rust-analyzer/rust-analyzer#10852]
Changes introduced by  #10783 seems to me quite reasonable and I would like to suggest to go further and show bodies of structs, enums and unions as well. Look at ReScript's hover:
![resript](https://user-images.githubusercontent.com/1773973/143231678-d92ee85b-c8d1-4868-8dcb-32e31082bd74.png)

**Comment by lnicola** [comment]
Duplicate of #3197, can you post the screenshot in there?

**Comment by andreytkachenko** [comment]
Duplicate of #3197
