### ISSUE TITLE
regression of derive detection in rust 1.51.0

### ISSUE THREAD

**Issue by jhgg** [rust-analyzer/rust-analyzer#10851]
in 91bbc55eedbc0f6947b69a0158a7b6c81264024e - the mechanism for detecting a derive macro has changed, in such a way that only works on rust 1.52+ (probably because of https://github.com/rust-lang/rust/pull/79078) 

Here we can see that it cannot find the implementation for Default (either in the code lens, "0 implementations", and in the unresolvedReference scope in `Foo::default()` 

![image](https://user-images.githubusercontent.com/5489149/143213386-859caa01-9f91-468d-ba48-ff4efb1dc86a.png)

~~unfortunately at work we are currently on a nightly on 1.51.0... so this causing a lot of broken analysis. :(~~ took this opportunity to update us to a more recent nightly.

**Comment by flodiebold** [comment]
Since we don't usually support older compiler versions, and you updated your version, I think we can close this.

**Comment by lnicola** [comment]
Stable, in theory, but in practice we support more.
