### ISSUE TITLE
Latest release breaks on .collect() invocation

### ISSUE THREAD

**Issue by NinnOgTonic** [rust-analyzer/rust-analyzer#10868]
I've created the following reproduction and confirmed that this seems to break when i run `rust-analyzer version: 183ef048f 2021-11-22 stable`.

Meanwhile it does seems to work on `rust-analyzer version: 73668334f 2021-11-15 stable`.

1. Create new crate: `cargo new hello_world --bin`
2. Fill main.rs with:
```
use std::{
    collections::HashMap,
    ffi::OsStr,
    fs::{self, DirEntry, File},
    io::{self, Read},
    path::PathBuf,
    sync::mpsc::channel,
    time::Duration,
};

#[derive(Debug, Clone)]
struct BootInfo {
    pub id: String,
    pub idx: u32,
    pub start_time: String,
    pub end_time: String,
}

fn find_boots() -> io::Result<HashMap<String, BootInfo>> {
    let mut res: HashMap<String, BootInfo> = HashMap::new();
    Ok(res)
}
fn gg() -> io::Result<()> {
    let boots = find_boots()?;

    
    let foo = boots.values().cloned().collect::<Vec<BootInfo>>();
    println!("{:?}", foo);
    Ok(())
}
fn main() {
    gg().unwrap();
}
```

4. Inline typehits and hover types missing after `.collect::<Vec<BootInfo>>();` in line 24: 

![Screenshot 2021-11-26 at 14 17 05](https://user-images.githubusercontent.com/301172/143586888-b0ec316d-2241-4d51-8594-cb942705538e.png)

**Comment by jhgg** [comment]
What version of rustc are you using?

**Comment by jhgg** [comment]
This is most definitely #10851 - I cannot reproduce on 1.52.0, but can on 1.51.0. 

Please upgrade to a stable version >= 1.52.0 and your issue should be resolved!

**Comment by vallentin** [comment]
If that's the case, then this solves the issue, as we're currently upgrading from Rust 1.49 to Rust 1.54.
