### ISSUE TITLE
Is the keyboard shortcut missing for showing up documentation on hover

### ISSUE THREAD

**Issue by fassn** [rust-analyzer/rust-analyzer#10879]
I love the documentation on mouse hover feature and I'd like to know whether it is possible toggle it with a keyboard shortcut aswell? 

The [user manual](https://rust-analyzer.github.io/manual.html) mentions the following:

>  Shows additional information, like the type of an expression or the documentation for a definition when "focusing" code. Focusing is usually hovering with a mouse, but can also be triggered with a shortcut.

I've been looking around but couldn't find any binding in the rust-analyzer settings. Am I missing something ?

Best regards,

**Comment by fassn** [comment]
Thanks for your reply! I forgot to mention that I am using the rust analyzer extension for vscode. As far as I could see, no such bindings seem to exist for it.

**Comment by Veykril** [comment]
`crtl + k + i` seems to be the default for it in VSCode, it's named `Debug: Show Hover`.

**Comment by lnicola** [comment]
To clear up possible confusion, that's `Ctrl-K, I` (don't press `K` and `I` at once).
