### ISSUE TITLE
cargo install

### ISSUE THREAD

**Issue by nnovikov** [rust-analyzer/rust-analyzer#10885]
Is it possible to use `cargo install` for rust-analyzer installation?

**Comment by lnicola** [comment]
`cargo install --git https://github.com/rust-analyzer/rust-analyzer` might work.

**Comment by nnovikov** [comment]
Why not simple `cargo install rust-analyzer`?

**Comment by bjorn3** [comment]
You can do `cargo install ra_ap_rust-analyzer` I think.
