### ISSUE TITLE
Struct constructor completion qualifies path even if already typed

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#10889]
**rust-analyzer version**: `d9b2291f5 2021-11-29 stable`

**rustc version**: `rustc 1.56.1 (59eed8a2a 2021-11-01)`

https://user-images.githubusercontent.com/31783266/144040120-c895b924-a9bc-44bb-ad54-f63e9f08fb04.mov

Even though I have already qualified the name of the struct being completed, the completion still inserts the full path to the struct. Could this be related to #10846?

**Comment by andrewleverette** [comment]
Yeah, that is likely related to #10846. I must have missed something with the previous fix. I can take another look at this.

**Comment by andrewleverette** [comment]
I submitted a pull request #10909 that I believe will fix this issue.
