### ISSUE TITLE
Nightly RA completely breaks with traits annotated with `#[async_trait::async_trait]` outside of the current module

### ISSUE THREAD

**Issue by leocth** [rust-analyzer/rust-analyzer#10895]
Using RA version `2d0db312b 2021-12-01 nightly`

Any trait annotated with `#[async_trait::async_trait]` outside of the current module is not recognized by RA as a trait.
`use` statements result in an `unresolved-import` error, and any `impl` blocks using `#[async_trait]` results in this error:
```
range end index 4 out of range for slice of length 3 rust-analyzer(macro-error)
```
Which is just, clearly an internal bug.

[Minimally reproducible example](https://github.com/leocth/ra-nightly-regression-example)

This is a serious regression in nightly and it's important to fix it before the next release.
@matklad, please take a look.

**Comment by jhgg** [comment]
What version of rustc are you on? I checked out your repo r-a at 2d0db312b543343f1c208b6be21a7a001cec7dd6 and I can't reproduce. 

![image](https://user-images.githubusercontent.com/5489149/144167108-087de14d-d942-47b6-9d5b-3849c8f3c0c9.png)

**Comment by leocth** [comment]
Wow, it didn't even remotely occur to me that an old nightly version is to blame. I had an one-month-old nightly and apparently that's enough to break things lol. Thanks!
