### ISSUE TITLE
Gitcoin funding for Rust-Analyzer

### ISSUE THREAD

**Issue by gilescope** [rust-analyzer/rust-analyzer#10907]
Rust-Analyzer is a public good.

Gitcoin grant round 12 is starting with quadratic funding. As half the crypto infrastruture is built in rust (the other half in go) it would be great to be able to give back and sponsor rust-analyzer. To do so it might be nice to bag rust-analyzer.eth address to receive the funds ( https://app.ens.domains/name/rust-analyzer.eth/register ).

https://gitcoin.co/grants/new

Then we as a decentralised world, we could fund the project. Until we do it, we don't know how much demand there is to back this project, but it could turn out to be a very significant income stream for the project. I would suggest we try it once and see if it raises a non-trivial amount.

**Comment by jonas-schievink** [comment]
You can already financially contribute to rust-analyzer via [OpenCollective](https://opencollective.com/rust-analyzer) or [GitHub Sponsors](https://github.com/sponsors/rust-analyzer). We're not currently planning on adding another funding platform.

As https://github.com/rust-analyzer/rust-analyzer/issues/4224 is being implemented, there also won't be an official way to contribute funding on a project-level anymore (instead, funding explicitly goes to individuals, groups, or companies that work on rust-analyzer), so closing.
