### ISSUE TITLE
Feature request: Add while-let-to-loop assist

### ISSUE THREAD

**Issue by fmease** [rust-analyzer/rust-analyzer#10901]
Currently, Rust Analyzer only supports the assist to transform a plain `while` loop to a `loop {}`.

The desired assist should transform the following code (where `$pat`, `$expr` and `$body` are placeholders):

```rust
fn main() {
    while let $pat = $expr {
        $body
    }
}
```

to the code below when the cursor is placed inside the snippet `while let`:

```rust
fn main() {
    loop {
        if let $pat = $expr {
            $body
        } else {
            break;
        }
    }
}
```

Actually, this is exactly the desugaring rustc is doing (try `rustc <file> -Zunpretty=hir`).

**Comment by Veykril** [comment]
Instead of a new assist, this should just be implemented for the current convert_while_to_loop assist
