### ISSUE TITLE
FR: Inlay hints on error types in function signatues

### ISSUE THREAD

**Issue by jrmoulton** [rust-analyzer/rust-analyzer#10912]
I don't know if this would be in the scope of the project or if it's just a bad idea but it would be great to have inlay hints on error types in function signatures. I see this being useful because often I want to quickly see what the type of a particular error type being returned by a function from a library is so that I can forward it out myself but the function signature usually only has typed out ```Error```. So I then have to search for the use statement in the file and then inspect it and see exactly which error type that it is. This also might be too specific of a use case but I figured I'd ask to open the discussion.

**Comment by jhgg** [comment]
Can you be a bit more specific with what you mean by "only has typed out error"?

**Comment by Veykril** [comment]
We offer type links on hover that you can click to get to the types in signatures, we do this for return types as well now so I think we can close this.
