### ISSUE TITLE
How do I run and debug the VSCode extension?

### ISSUE THREAD

**Issue by Zingam** [rust-analyzer/rust-analyzer#10918]
I managed to build the extension but I'm unable to find out how to debug it. Is there any documentation or tips how to do that?

**Comment by Veykril** [comment]
Take a look at https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/debugging.md

**Comment by Zingam** [comment]
@Zingam Thank you! I was opening the wrong "root" folder!

**Comment by Zingam** [comment]
@Veykril I'm sorry about bothering you again. I'm trying to debug a Rust "launch.json" workflow. I made a FR and I think it's easy to implement, so I decided to look into it myself.
Unfortunately I still cannot get debugging to work properly. For my needs I need the CodeLLDB to be enabled. I created the following `launch.json` configuration for launching the development host:

```json
    {
      // Used for testing the extension with a local build of the LSP server (in `target/debug`).
      "name": "Run Extension (Debug Build) with Extensions",
      "type": "extensionHost",
      "request": "launch",
      "runtimeExecutable": "${execPath}",
      "args": [
        "--disable-extension", "matklad.rust-analyzer",
        "--extensionDevelopmentPath=${workspaceFolder}/editors/code"
      ],
      "outFiles": [
        "${workspaceFolder}/editors/code/out/**/*.js"
      ],
      "preLaunchTask": "Build Server and Extension",
      "skipFiles": [
        "<node_internals>/**/*.js"
      ],
      "env": {
        "__RA_LSP_SERVER_DEBUG": "${workspaceFolder}/target/debug/rust-analyzer"
      }
    },
```

With this I can launch, activate the extension and and even breakpoints in `main.ts` get hit. But only in this file during activation/deactivation and nowhere else. And I still couldn't figure out where `console.log` output goes. I must be missing something like a noob. If it matters I am on Windows 10.

**Comment by Veykril** [comment]
Hmm, usually the `console.log` output should appear in an extra debugging output tab of code if memory serves right. I haven't really debugged the extension itself in the past months so I don't really know too much about this matter either. Though with the launch definitions in the r-a repo I could usually breakpoint anywhere from what I remember 😕
