### ISSUE TITLE
Configurable parser lookahead limit instead of a hard 10_000_000 cap

### ISSUE THREAD

**Issue by JRF63** [rust-analyzer/rust-analyzer#10948]
Getting multiple
```sh
thread '<unnamed>' panicked at 'the parser seems stuck', crates\parser\src\parser.rs:51:9
```
when enabling the `UI_Xaml_Controls` feature on the windows-rs crate (VSCode on Window 10). [Min repro](https://github.com/JRF63/rust-analyzer-stuck-parser).

```rust
// crates/parser/src/parser.rs
pub(crate) fn nth(&self, n: usize) -> SyntaxKind {
    assert!(n <= 3);

    let steps = self.steps.get();
    assert!(steps <= 10_000_000, "the parser seems stuck");
    self.steps.set(steps + 1);

    self.token_source.lookahead_nth(n).kind
}
```
Tried raising it from 10 million to `u32::MAX` and it seemed to work. I think having this be configurable instead of raising the current 10 million limit would be more reasonable?

**Comment by lnicola** [comment]
FWIW, we wouldn't have to increase that limit by much, only to 15M or so.

**Comment by lnicola** [comment]
As mentioned in #10949, this doesn't actually make the limit configurable, but only bumps it a little. If the parser is really stuck, this makes it crash slightly later, and if it's not, this makes it work instead of crashing, so it's not so bad.
