### ISSUE TITLE
#[cfg(...)] attribute resolves to cfg! macro in hover/go-to-definition.

### ISSUE THREAD

**Issue by jhgg** [rust-analyzer/rust-analyzer#10942]
![image](https://user-images.githubusercontent.com/5489149/144749628-8a5a0f04-e5ac-49b6-89ad-ddb28a32164e.png)

rustc version: 1.57.0
r-a version: 6434ada19 2021-12-05 dev

**Comment by Veykril** [comment]
Huh, right this name collision exists. I guess rust is alright with a builtin macro colliding with an inert attribute. I wasn't aware of that.
