### ISSUE TITLE
Stop calling rust-analyzer “alpha” in Visual Studio Marketplace

### ISSUE THREAD

**Issue by kpreid** [rust-analyzer/rust-analyzer#10955]
The description of the `matklad.rust-analyzer` extension [in Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer) (and from [this file?](https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/README.md)) reads:

> Provides support for rust-analyzer: novel LSP server for the Rust programming language.
>
> **Note** the extension may cause conflicts with the official Rust extension. It is recommended to disable the Rust extension when using the rust-analyzer extension.
>
> **Note** the project is in alpha status: it is already useful in practice, but can't be considered stable.

“Alpha status” does not seem like an appropriate description of rust-analyzer's current status (since it is widely used and generally considered the best option for Rust), and it may be steering users away from installing the rust-analyzer extension.

I suggest that the “alpha” description should be removed; and preferably, more information about rust-analyzer's capabilities be added.

**Comment by MunchyYDL** [comment]
Rust-alphalyzer, the bestest there is! :zany_face:

**Comment by jonas-schievink** [comment]
This was fixed by https://github.com/rust-analyzer/rust-analyzer/pull/11122
