### ISSUE TITLE
HIR validation API

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1095]
https://github.com/rust-analyzer/rust-analyzer/pull/1034 implemented diagnosis API for HIR. The next step wold be to employ this API to write fixes for compiler errors. 

A good model problem here would be to re-implement [`fill_struct_fields`](https://github.com/rust-analyzer/rust-analyzer/blob/fdbebccd71d38c4dffffe918b036bbfa39355c5f/crates/ra_assists/src/fill_struct_fields.rs) as a fix. This is the assist that adds missing fields to struct literals. Currently, the logic "are there enough fields" is implemented in the assist itself, but it belongs in HIR.

Here's what we should do to make this better:

* introduce `validate_body` function, which takes a type-checked HIR for a function body and produces additional HIR diagnostics. It probably doesn't even need to be a query. Note that we want to do this in a separate pass, and not directly during type-checking, to simplify things. This validation should be called [from here](https://github.com/rust-analyzer/rust-analyzer/blob/fdbebccd71d38c4dffffe918b036bbfa39355c5f/crates/ra_hir/src/code_model_api.rs#L570-L572)

* implement struct validation in `validate_body`: for every struct_literal expression, check if it is missing some fields, and , if this is the case, produce a diagnostic that stores the list of missing fields. 

* in the IDE layer, fetch the diagnostics and produce the corresponding fix. The assist could be removed after that. Here's the [fix registration code](https://github.com/rust-analyzer/rust-analyzer/blob/fdbebccd71d38c4dffffe918b036bbfa39355c5f/crates/ra_ide_api/src/diagnostics.rs#L39-L49)

Marking as E-hard as this needs some important API design around what exactly is a validation layer, but otherwise this shouldn't be too hard to implement

**Comment by pasa** [comment]
I would like to take it.

**Comment by pasa** [comment]
Hi! 
I've got a couple of questions about api.
As I understand I need to process all Expr::StructLit expressions. I can't figure out the meaning of 'spread' field. What does it mean?
I experimented with MockDatabase and found out that StructLit is not distinguish situation when you initialize struct from another instance (e.g.  TestSruct{ ..another } ). Is it a bug or just unimplemented feature?

**Comment by matklad** [comment]
`spread` is `..another` syntax :) Might be a good idea to add a comment explaining it!

For `S { ..foo }`, I get the following syntax tree (you can use **Rust Analyzer: syntax tree** command)

```
STRUCT_LIT@[23; 34)
  PATH@[23; 24)
    PATH_SEGMENT@[23; 24)
      NAME_REF@[23; 24)
        IDENT@[23; 24) "S"
  WHITESPACE@[24; 25) " "
  NAMED_FIELD_LIST@[25; 34)
    L_CURLY@[25; 26) "{"
    WHITESPACE@[26; 27) " "
    DOTDOT@[27; 29) ".."
    PATH_EXPR@[29; 32)
      PATH@[29; 32)
        PATH_SEGMENT@[29; 32)
          NAME_REF@[29; 32)
            IDENT@[29; 32) "foo"
    WHITESPACE@[32; 33) " "
    R_CURLY@[33; 34) "}"
```

It sees reasonable? The  `DOTDOT PATH_EXPR` bit is the spread

**Comment by pasa** [comment]
Yes, I see in in the ast level, but  seams it is not propagated to the HIR level.
I'm trying something like [this](https://github.com/pasa/rust-analyzer/blob/ca0621e874912e7190e6fe1b3994a0e483c4747c/crates/ra_hir/src/code_model_api.rs#L593) and print Body [here](https://github.com/pasa/rust-analyzer/blob/ca0621e874912e7190e6fe1b3994a0e483c4747c/crates/ra_hir/src/code_model_api.rs#L579). And spread is always `None`.  
May be I just use MockDatabase wrong.

**Comment by pasa** [comment]
I just delved it dipper and figured out that hir level was expecting spread expression as a child of StructLit node but was a child of NamedFIledList. I've fixed the parser in [this commit](https://github.com/pasa/rust-analyzer/commit/855a9eea3b63f62944166d6c3795c7f23e7adc47) and all started to work nicely. 
Is it correct?

**Comment by matklad** [comment]
I don’t think we should fix the parser: spread is inside curly braces, so it should be part of field list. Rather, we should fix hir construction and AST to look for spread on field list

**Comment by pasa** [comment]
That was may second thought. I'll do it such way.

**Comment by pasa** [comment]
> I don’t think we should fix the parser: spread is inside curly braces, so it should be part of field list. Rather, we should fix hir construction and AST to look for spread on field list

I agree. But for now we have `ast::StructLit::spread()` function in `generated.rs` which always return `None`.
It's quite confusing.

**Comment by matklad** [comment]
this function should be moved to the `NamedFIeldList`

**Comment by pasa** [comment]
Ok. Will try to figure out how to do it.

**Comment by pasa** [comment]
So, I've made changes according PR conversation. One place where I'm not sure is [validate_struct_literal()](https://github.com/rust-analyzer/rust-analyzer/blob/837f82b7a25a8c08b529a92dd2a32eba2d9fb1ed/crates/ra_hir/src/expr/validation.rs#L28). There are to many arguments in it to my mind. I'm not sure about Rust way to deal with it. Should I create struct with some of this arguments encapsulated or something?

**Comment by pasa** [comment]
I've fixed PR issues. Take a look please.

**Comment by matklad** [comment]
The API side of this is mostly fixed
