### ISSUE TITLE
Crate name has no semantic token type in macro call with absolute path when in module scope

### ISSUE THREAD

**Issue by CleanCut** [rust-analyzer/rust-analyzer#10962]
**rust-analyzer version**: rust-analyzer version: d9b2291f5 2021-11-29 stable

**rustc version**: rustc 1.57.0 (f1edd0429 2021-11-29)

**VS Code version**:

```
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

# What I Expect (correct)

Normally, the crate name in an absolute path to a macro call will have a _semantic token type_ of `namespace`, as on line 17 in the code below.  In this screenshot I typed in `rusty_engine::init()` (a call to a macro) on line 17 inside of the `main()` function just to demonstrate what I _expect_ to happen.

<img width="905" alt="image" src="https://user-images.githubusercontent.com/5838512/145159871-0dbf32c1-4cba-4f0c-8ce1-0a18e7921b38.png">

# What I Get (incorrect)

However, my macro is creating a bunch of `struct`s which need to be at module scope, so [I actually call](https://github.com/CleanCut/rusty_engine/blob/0e1f08e04e9d058ea8cf40f1fc7d6ad578aa969b/examples/scenarios/road_race.rs#L12) the macro out at module scope. [The code](https://github.com/CleanCut/rusty_engine/blob/0e1f08e04e9d058ea8cf40f1fc7d6ad578aa969b/examples/scenarios/road_race.rs#L12) _runs_ just fine, but rust-analyzer doesn't assign a semantic token type to the crate in this usage, so the style is all wrong (I've set the style of `namespace` to the blue of the screenshot above).

<img width="909" alt="image" src="https://user-images.githubusercontent.com/5838512/145159888-e45ea740-5622-4a6a-b40d-3af851709fe2.png">

# Reproduce

This is trivial to reproduce!

```toml
# Cargo.toml
[package]
name = "scratch"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty_engine = { git = "https://github.com/CleanCut/rusty_engine", rev = "0e1f08e04e9d058ea8cf40f1fc7d6ad578aa969b" }
```

```rust
// src/main.rs

// `rusty_engine` on the next line doesn't get its semantic token type set
rusty_engine::init!();

fn main() {
    println!("Hello, world!");
}
```

# The Fix?

I'd be happy to do the legwork of making a PR with a fix if this is at all straightforward to resolve and someone can point me in the right direction to get started.

**Comment by Veykril** [comment]
Highlighting mainly happens here https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/syntax_highlighting.rs and here https://github.com/rust-analyzer/rust-analyzer/blob/77f2d349306f137acb296561d10ff745fcf6fed9/crates/ide/src/syntax_highlighting/highlight.rs

Given that we don't even assign an unresolved highlighting there we seem to not traverse the node for highlighting properly

With tests here https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/syntax_highlighting/tests.rs

**Comment by Veykril** [comment]
Ah I assume it might be this check here, https://github.com/rust-analyzer/rust-analyzer/blob/77f2d349306f137acb296561d10ff745fcf6fed9/crates/ide/src/syntax_highlighting.rs#L299-L305

We note down that we are inspecting a macro call, and then check if the token we are highlighting is inside the input of the macro, if not we skip. This is wrong because we will also try to highlight the path of the macro which lies outside, so for the non token tree tokens and nodes we want to highlight without descending into the macro.

**Comment by CleanCut** [comment]
Thanks, @Veykril! ❤️
