### ISSUE TITLE
VSCode - Workspaces fail to load in remote repositories

### ISSUE THREAD

**Issue by KubaP** [rust-analyzer/rust-analyzer#10968]
### The bug
I was trying to navigate a remote workspace in vscode, but the RA extension flat-out failed to load correctly. The error is:
```text
[ERROR rust_analyzer] failed to find any projects in [AbsPathBuf("C:\\Program Files\\Microsoft VS Code")]
```

### Steps to reproduce
1. Open any repository (such as https://github.com/alexheretic/glyph-brush) in vscode using the [Github Repositories](https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub) extension.
2. Observe the error pop-up `rust-analyzer failed to discover workspace`

I'm not sure if support by RA for vscode remote workspaces is planned or not; in any case, I thought I'd at least post this as a bug.

**rust-analyzer version**: 7d6fcbc0b 2021-12-06 stable
**rustc version**: rustc 1.55.0 (c8dfcfe04 2021-09-06)

**Comment by jhgg** [comment]
I don't think this is actionable. That extension doesn't actually download the files to your file-system, so rust-analyzer can't really perform any meaningful analysis. To quote the limitations section:

> When you work in a traditional git workflow (i.e. git clone), files are saved to your computer’s local file system. **But when working with GitHub Repositories, the code doesn’t live on your local computer: it’s still just on GitHub.** You work with the code through a virtual file system, which is an abstraction that simulates having local files while getting the content from somewhere else; GitHub in this case. When you open a workspace on a virtual file system, it’s known as a virtual workspace.

And although rust-analyzer can probably populate its vfs from this extension (assuming there's a means to list and read files from it...), stuff like `cargo` still very much rely on the files existing somewhere on disk.

**Comment by KubaP** [comment]
Ah fair enough. I forgot that RA depends on cargo. Ah well, it's not the end of the world.

*Side note: What exactly is the purpose of a vfs if applications need to be explicitly programmed to support it? Isn't the whole idea behind a vfs that it emulates a real file system, and behaves exactly like one?*

**Comment by lnicola** [comment]
> What exactly is the purpose of a vfs if applications need to be explicitly programmed to support it? Isn't the whole idea behind a vfs that it emulates a real file system, and behaves exactly like one?

A lot of Code extensions are written in TypeScript and don't depend on native code, so they can be updated relatively easily to work in the browser or remotely. rust-analyzer is a Rust program and uses cargo and the Rust standard library source code, so that's harder (although we have a sample WASM build with a more limited feature set).

But we do support remote development (the old SSH/WSL/Docker features of Code).

**Comment by KubaP** [comment]
Ah sorry, I was making an incorrect assumption.

I was assuming that the `Github Repositories` extension creates some sort of OS-native vfs, and then through which vscode (and extensions) can access the files. But now I'm assuming that's not the case, and rather, the github extension "fakes" it within vscode.

It seems that Windows does have a concept of a "virtual file system", but it actually needs to be implemented and written (and is probably quite complex to do so I imagine), and I'm guessing the `Github Repos` team didn't actually do that? Hence why `cargo` doesn't "just work", since it exists outside of the repo extension.

In regards to running in the browser, I totally get why RA would have trouble, since it has to run in WASM and that's more limited than native code.

**Comment by lnicola** [comment]
> It seems that Windows does have a concept of a "virtual file system", but it actually needs to be implemented and written (and is probably quite complex to do so I imagine), and I'm guessing the Github Repos team didn't actually do that?

So does Linux, but yeah, I doubt that a Code extension is going to use it.

**Comment by KubaP** [comment]
Aight. That's cleared up my confusion.

Seems a bit half-arsed if you ask me, but I guess I can't really complain since it's free and all.
