### ISSUE TITLE
Shorthand to print a variable

### ISSUE THREAD

**Issue by willparsons** [rust-analyzer/rust-analyzer#10967]
IntelliJ has a feature that lets you type out the name of a variable and suffix it with `.println` and it will autocomplete to a matching valid print statement for that variable. Similar actions exist for `for` to loop over something iterable, etc.

I think this could be a nice QoL feature.

**Comment by lnicola** [comment]
See https://rust-analyzer.github.io/manual.html#format-string-completion

**Comment by lnicola** [comment]
So we have `.println` for format strings and `dbg` for general expressions and also user-defined postfix snippets: https://rust-analyzer.github.io/manual.html#user-snippet-completions.

I think this should be enough for this use case, but feel free to reopen or comment if you disagree.
