### ISSUE TITLE
sql_function! from diesel causes "unexpected token in input" error. Regression.

### ISSUE THREAD

**Issue by staninprague** [rust-analyzer/rust-analyzer#10984]
Not sure between which versions of rust analyser did it happen, but when I open the file containing diesel's sql_function!, e.g.:

sql_function! {
    fn fn_delete_zone_for_collection_id(collection_uuid: diesel::sql_types::Uuid) -> Int4;
}

Rust analyser gives the following error per each of these sql_function!:

unexpected token in input

![ra-sql_function_error](https://user-images.githubusercontent.com/3834343/145674790-c8dc217a-d5a4-4fae-bcba-0c67f0c55781.jpg)

Cargo check and Cargo build are not seeing any errors.

I have the following settings related to macros:

![ra-macro-settings](https://user-images.githubusercontent.com/3834343/145674955-15cdc131-cc95-483d-95b6-7d8997c18510.jpg)

This just used to work alright, any settings I could have missed between the RA versions?

How can I help to troubleshoot the issue?

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
v0.2.842
**rustc version**: (eg. output of `rustc -V`)
rustc 1.57.0 (f1edd0429 2021-11-29)

**Comment by Veykril** [comment]
Error most likely comes from the proc macro emitting a `concat!` macro call, https://github.com/diesel-rs/diesel/blob/3f3ce57ca1a89274ecf915b70826234c45bd261e/diesel_derives/src/sql_function.rs#L137

This should be fixed in today's nightly / next monday's stable

**Comment by staninprague** [comment]
Will test on Monday after the update then. Thanks!

**Comment by staninprague** [comment]
Fixed in Monday's release. Thank you!
