### ISSUE TITLE
"move if to guard" should work even if there's an else

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#10997]
![image](https://user-images.githubusercontent.com/1711539/145723660-2f438027-a4ef-4963-9285-ac2902b3ffce.png)

This should suggest moving if conditon to the guard (duplicating the pattern). Relevant code:

https://github.com/rust-analyzer/rust-analyzer/blob/db2a7087b994e20f264f26ad6db75184282ad120/crates/ide_assists/src/handlers/move_guard.rs#L121-L123

**Comment by weirane** [comment]
I think this is a good issue to work on as my first contribution to rust-analyzer!
