### ISSUE TITLE
Hover on 

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#1099]
Hovering produces interesting results here:
https://github.com/rust-analyzer/rust-analyzer/blob/c6c88070c4f25cd3710f03b7461cb277de8d3cc5/crates/ra_lsp_server/src/main_loop.rs#L294

If we hover like so  `han<|>dlers` we get: 
> `fn handle_analyzer_status(ServerWorld, ()) -> Result<String, {unknown}>`

If hovering here `handle_anal<|>yzer_status` we get:

> `pub fn handle_analyzer_status(world: ServerWorld, _: ()) -> Result<String>`

I was more surprised about the `{unknown}` than anything else.

May be related to #904

**Comment by flodiebold** [comment]
Yes, it's the same thing -- the first example is the type of the whole expression `handlers::handle_analyzer_status`, which happens to print quite similarly to the function definition; the second one is the actual function definition.

**Comment by sigoden** [comment]
```rs
let mut v1 = HashMap::<i32, Vec<i32>>::new();
let mut v2: HashMap<i32, Vec<i32>> = HashMap::new();
let mut v3 = HashMap::new() as HashMap<i32, Vec<i32>>;
```

hover on `v1`:  `HashMap<{unknown}, {unknown}, RandomState>`
hover on `v2`:  `HashMap<i32, Vec<i32>, RandomState>`
hover on `v3`:  `HashMap<i32, Vec<i32>, {unknown}>`

**Comment by flodiebold** [comment]
That's a different thing, mostly related to us not handling type parameter defaults (at all). (Not sure why the first one doesn't work, probably we're not plugging in the type arguments correctly for the associated function...)

**Comment by edwin0cheng** [comment]
I played around this problem a little bit (v1 case), here is a simplified version which shows the bugs and do not depends on outside crate):

```rust
struct Foo<T> { _a: T } 

impl<T> Foo<T> {
    fn f1() -> Foo<T> {
        loop {} // loop is ! type
    }    
    fn f2(_a: u8) -> Foo<T> {
        loop {}
    }
    fn f3(_a: T) -> Foo<T> {
        loop {}
    }
}

fn main() {    
    let v1 = Foo::<i32>::f1();      // v1 => Foo<{unknown}>
    let v2 = Foo::<i32>::f2(0);     // v2 => Foo<{unknown}>
    let v3 = Foo::<i32>::f3(0);     // v3 => Foo<i32>
    
    let _ = v1;     // suppress warning
    let _ = v2;     // suppress warning
    let _ = v3;     // suppress warning
}
```

**Comment by flodiebold** [comment]
I think the problem is that we lose track of the 'self type' when resolving associated items in `infer_path_expr`. That is, we have the self type (`Foo::<i32>` in your example) here:
https://github.com/rust-analyzer/rust-analyzer/blob/2fc2d4373b2c4e96bebf320a84270eee3afe34aa/crates/ra_hir/src/ty/infer.rs#L421
(and I'm assuming we correctly apply the type arguments), but we then only use it to find the item:
https://github.com/rust-analyzer/rust-analyzer/blob/2fc2d4373b2c4e96bebf320a84270eee3afe34aa/crates/ra_hir/src/ty/infer.rs#L447
`ty` isn't used after that, but we would actually have to 'plug it' into the impl declaration to get the correct values of the impl parameters (i.e. to find out the value of `T` in your example).

**Comment by edwin0cheng** [comment]
@flodiebold Thanks for the information, it let me understand more about the current `infer` code. 

If you don't mind, Do you think the following code would works to 'plug in' the impl declaration:
```rust

// resolve intermediate segments
for segment in &path.segments[remaining_index..] {
    let ty = match resolved {
        Resolution::Def(def) => {
            let typable: Option<TypableDef> = def.into();
            let typable = typable?;

            let mut substs =
                Ty::substs_from_path_segment(self.db, &self.resolver, segment, typable);

            if remaining_index > 0 {
                substs = Ty::substs_from_path_segment(self.db, &self.resolver, &path.segments[remaining_index-1], typable);
            }

            self.db.type_for_def(typable, Namespace::Types).subst(&substs)
        }

       ...........................
    };

    // Attempt to find an impl_item for the type which has a name matching
    // the current segment
    log::debug!("looking for path segment: {:?}", segment);
    impl_ty = Some(ty.clone());
    
    ............................
   
    resolved = Resolution::Def(item.into());
}

match resolved {
    Resolution::Def(def) => {
        let typable: Option<TypableDef> = def.into();
        let typable = typable?;
        let substs = Ty::substs_from_path(self.db, &self.resolver, path, typable);                
        let mut ty = self.db.type_for_def(typable, Namespace::Values).subst(&substs);

        // plug the old parent_ty in
        if let Some(Ty::Apply(impl_ty)) = impl_ty {
            if let crate::ModuleDef::Function(func) = def {                    
                let gen = func.generic_params(self.db);
                if gen.count_parent_params() > 0 {
                    ty = ty.apply_substs(impl_ty.parameters.clone());
                }
            }
        }

        let ty = self.insert_type_vars(ty);
        Some(ty)
    }
    ....................
}
```

**Comment by flodiebold** [comment]
`apply_substs` wouldn't be the right way to plug the type parameters in. Imagine something like this:
```rust
struct S<A, B>;
impl<T> for S<u32, T> {
   fn foo<U>() {}
}
...
S::<u32, str>::foo()
```
the parent params of `foo` aren't `A` and `B`, but `T`. Plugging in `<u32, str>` as the parent params for `foo` would be wrong; we need to instead unify `<u32, T>` with it, and infer that `T = str` and hence the substs for the parent are `<str>`.

**Comment by edwin0cheng** [comment]
After PR #1145 , @sigoden example became :
```rust
let mut v1 = HashMap::<i32, Vec<i32>>::new();
let mut v2: HashMap<i32, Vec<i32>> = HashMap::new();
let mut v3 = HashMap::new() as HashMap<i32, Vec<i32>>;
```
```
hover on v1: HashMap<i32, Vec<i32>, RandomState>
hover on v2: HashMap<i32, Vec<i32>, RandomState>
hover on v3: HashMap<i32, Vec<i32>, {unknown}>
```

V3 cases are still incorrect, and here is a simplified version which shows the bugs and do not depends on outside crate):
```rust
struct Q<T=u32> {
    _val_t : T,
}

impl<T> Q<T> {
    fn new() -> Q<T> {
        loop {}
    }
}

fn main(){
    let _v1 : Q = Q::new();
}
```
```
hover on v1:  Q<{unknown}>
```


I think the reason is, we didn't handle default type params yet, right?

**Comment by flodiebold** [comment]
Yes:
https://github.com/rust-analyzer/rust-analyzer/blob/112fd0ec7d65b5f23865410fd3e188e761d97110/crates/ra_hir/src/ty/lower.rs#L198

**Comment by flodiebold** [comment]
Basically, the way I imagine this working is:
 - add the (unresolved) defaults from the definition to `GenericParams`
 - add a query `generic_defaults` that resolves those defaults to types and returns a `Substs`
 - use that query in the line mentioned above to fill in missing parameters :)
There might be other places where generic param defaults need to be handled, but that's the main one.

**Comment by edwin0cheng** [comment]
@kjeremy Can it be closed ?

**Comment by kjeremy** [comment]
The `{unknown}` has gone away in the first example which is great (good job!).  However the inconsistency in presentation still happens. I'm also seeing that the code pasted in https://github.com/rust-analyzer/rust-analyzer/issues/1099#issuecomment-484107913 gives me a bunch of `{unknown}` so I'm inclined to leave this open for now.

**Comment by edwin0cheng** [comment]
I just tested the code pasted in comment. It should be resolved as following: which seems to be correct (current master (c8f93ff5) ):
```
use std::collections::HashMap;

fn main() {
    let v1 = HashMap::<i32, Vec<i32>>::new();
    let v2: HashMap<i32, Vec<i32>> = HashMap::new();
    let v3 = HashMap::new() as HashMap<i32, Vec<i32>>;

    let _v1 = v1;
    let _v2 = v2;
    let _v3 = v3;
}
```

```
hover on v1: HashMap<i32, Vec<i32>, RandomState>
hover on v2: HashMap<i32, Vec<i32>, RandomState>
hover on v3: HashMap<i32, Vec<i32>, RandomState>
```

And the inconsistency of ` .on::<req::AnalyzerStatus>(handlers::handle_analyzer_status)? ` is about the different of expression and definition. I actually don't know how to fix it or i even don't know whether it should consider as a bug.

**Comment by kjeremy** [comment]
Ah I missed the `use`. Once I added that it worked.

**Comment by kjeremy** [comment]
> And the inconsistency of `.on::<req::AnalyzerStatus>(handlers::handle_analyzer_status)?` is about the different of expression and definition. I actually don't know how to fix it or I even don't know whether it should consider as a bug.

So... I guess since the `{unknown}` was the biggest problem here for me that maybe we can close this and address the inconsistency in #904. I agree that it may not be an issue but it IS confusing.
