### ISSUE TITLE
LSP request timed out: [Ca [Error]: canceled by client

### ISSUE THREAD

**Issue by lizkes** [rust-analyzer/rust-analyzer#11003]
**rust-analyzer version**: rust-analyzer version: db2a7087b 2021-12-13 stable

**rustc version**: rustc 1.59.0-nightly (efec54529 2021-12-04)

After I installed rust-analyzer in vscode, I found that it did not work properly, and then I found this error in the output  -> rust analyzer client:
```
WARN: LSP request timed out {
  method: 'rust-analyzer/inlayHints',
  param: {
    textDocument: {
      uri: 'file:///f%3A/Code/MyProject/xxx/src/main.rs'
    }
  },
  error: [Ca [Error]: canceled by client
  	at gr (c:\Users\Lizkes\.vscode\extensions\matklad.rust-analyzer-0.2.853\out\main.js:4:223)
  	at Or (c:\Users\Lizkes\.vscode\extensions\matklad.rust-analyzer-0.2.853\out\main.js:3:6574)
  	at Immediate.<anonymous> (c:\Users\Lizkes\.vscode\extensions\matklad.rust-analyzer-0.2.853\out\main.js:3:6424)
  	at processImmediate (internal/timers.js:461:21)] {
    code: -32800,
    data: undefined
  }
}
```

**Comment by bjorn3** [comment]
Which project did you open?

**Comment by Veykril** [comment]
Also what vscode version are you using? There have been some problems with VSCode 1.62 and our syntax highlighting.

**Comment by lizkes** [comment]
my vscode version is 1.63.0.

I tried restarting vscode repeatedly to observe this error. I noticed that this error does not appear every time, but the Rust Analyzer Language Server Trace window is always empty, does this mean that the extension is not connected to the lsp at all? 
![图片](https://user-images.githubusercontent.com/20457790/146007905-2b980d7d-5bbb-4a57-bfc2-fb7013ac49a7.png)

By the way, I tried to open various rust projects, all of which had the same failure

**Comment by Veykril** [comment]
That seems odd, that makes it sound like VSCode isn't starting the server properly? Maybe some other extension is interferring here.

**Comment by lizkes** [comment]
Although there is still no output in the Rust Analyzer Language Server Trace window, does this picture indicate that rust-analyzer is working properly? 
![图片](https://user-images.githubusercontent.com/20457790/146012932-5efbf518-b049-4dfd-94e9-66669383b64f.png)

**Comment by Veykril** [comment]
Ye those inlay hints come from r-a so it is starting properly

**Comment by Veykril** [comment]
What exactly is/was not working for you? As the screenshot implies r-a seems to work fine for you

**Comment by lizkes** [comment]
When I wrote code, I could only see the error message of the incorrect
type, and other error messages such as unused variables would not be
displayed.

**Comment by definitelynobody** [comment]
I'm also experiencing the same issue. I've only just noticed this today. I thought upgrading Rust would fix it but it does not.

```
WARN [12/17/2021, 11:15:11 PM]: LSP request timed out {
  method: 'rust-analyzer/inlayHints',
  param: {
    textDocument: {
      uri: 'REDACTED'
    }
  },
  error: [Ca [Error]: canceled by client
  	at gr (/home/REDACTED/.vscode/extensions/matklad.rust-analyzer-0.2.853/out/main.js:4:223)
  	at Or (/home/REDACTED/.vscode/extensions/matklad.rust-analyzer-0.2.853/out/main.js:3:6574)
  	at Immediate.<anonymous> (/home/REDACTED/.vscode/extensions/matklad.rust-analyzer-0.2.853/out/main.js:3:6424)
  	at processImmediate (internal/timers.js:461:21)] {
    code: -32800,
    data: undefined
  }
}
```

**Comment by definitelynobody** [comment]
Removing `#![cfg(feature = "json")]` from the top of a file fixed analysis for me. Type hints and errors show up again immediately.

**Comment by lizkes** [comment]
After testing, I found that rust-analyzer still works properly even if this error occurs, so close this issue.

**Comment by wqsz7xn** [comment]
Facing a similar issue to @lizkes using vscode `1.63.2` with r-a `v0.3.872` (prerelease from vscode marketplace). r-a starts fine and gives type type hints but has the LSP timeout issue from the r-a client log and an empty r-a language server trace. This issue disables intellisense beyond string suggestions. I know it's a wide scope but this only seems to occur with https://github.com/paritytech/substrate-archive

**Comment by lizkes** [comment]
@wqsz7xn try to delete the target folder in the project, it works for me

**Comment by wqsz7xn** [comment]
Turns out this is a well known issue on code blocks with a attributed function. Removing the attribute as reflected with definitelynobody solves it as a workaround
