### ISSUE TITLE
Intra-doc links using Markdown references get rendered incorrectly

### ISSUE THREAD

**Issue by teohhanhui** [rust-analyzer/rust-analyzer#11008]
For example: https://github.com/rust-lang/rust/blob/7ca74ea0afe87b2cb173ea1fea190853c3c3d860/library/std/src/error.rs#L308

gets rendered as:
![Screenshot from 2021-12-14 18-14-28](https://user-images.githubusercontent.com/548843/145979384-b88e295d-bf11-487e-92f5-baebb8de7b0b.png)

There are 2 problems here:

> Converts a [`str`] into a box of dyn [`Error`](https://doc.rust-lang.org/nightly/std/error/trait.Error.html) + [`Send`](https://doc.rust-lang.org/nightly/core/marker/trait.Send.html) + [`Sync`](https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html).

and

> []: https://doc.rust-lang.org/nightly/alloc/str/index.html

**rust-analyzer version**: 7d6fcbc0b 2021-12-06 stable

**rustc version**: rustc 1.57.0 (f1edd0429 2021-11-29)

**Comment by palango** [comment]
Similar problem I just encountered:

The end of the third paragraph is rendered as "like a <", whereas it should be "like a Vec<u8>"
![Screen Shot 2021-12-14 at 12 18 22](https://user-images.githubusercontent.com/90851/145988792-d6da2668-4c38-4564-970d-97964a42f6c6.png)

Correct rendering in rustdoc:

![Screen Shot 2021-12-14 at 12 18 48](https://user-images.githubusercontent.com/90851/145988945-b6ac0292-2368-4e9a-88e3-efeee20b26ae.png)

**Comment by Veykril** [comment]
That one is probably a different problem, the markdown for that is `<code>[Vec]\<u8></code>`. The first issue seems to be a problem with `pulldown_cmark` I think, or that using backticks in links is not valid cmark(don't know the spec too well).

The Vec issue I am not sure yet.

**Comment by palango** [comment]
@Veykril Should I move this to a new issue then?

**Comment by Veykril** [comment]
Sounds reasonable 👍

**Comment by Veykril** [comment]
Okay checked a bit more thoroughly, this is indeed a bug in `pulldown-cmark-to-cmark`

**Comment by Veykril** [comment]
Fixed in https://github.com/rust-analyzer/rust-analyzer/pull/11418
