### ISSUE TITLE
3 #[derives(...)] show up in autocomplete suggestions.

### ISSUE THREAD

**Issue by jhgg** [rust-analyzer/rust-analyzer#11012]
![image](https://user-images.githubusercontent.com/5489149/146001634-4e0e11ac-0674-41c1-9ae4-8b181d0aa298.png)

the bottom one is the best, because it fills in with Debug. 

rust-analyzer version: 9efa355a6 2021-12-14 dev
rustc 1.57.0

**Comment by jhgg** [comment]
> Ah, one of those is probably the actual macro from the prelude while the other two are our hardcoded versions.
> 
> I think all that has to be done is to remove the `"derive"` here
> 
> https://github.com/rust-analyzer/rust-analyzer/blob/9efa355a629badd9eb680b0ae9067757bff05f96/crates/ide_completion/src/completions/attribute.rs#L147

This puts us down to 2...!

![image](https://user-images.githubusercontent.com/5489149/146156304-5a351cc8-707f-41ed-9e4f-bd6d606b704d.png)

**Comment by Veykril** [comment]
Ideally we should show two here, the one that prefills debug(which has the triple dot in its label) and one that only fille the `derive` identifier, removing the place I mentioned removes the `Debug` prefill one I assume from your screenshot. I think the stuff there doesn't allow one to only keep the snippet one but without the "bare" identifier completion hmm.

**Comment by Veykril** [comment]
We could probably make label here optional as well, https://github.com/rust-analyzer/rust-analyzer/blob/9efa355a629badd9eb680b0ae9067757bff05f96/crates/ide_completion/src/completions/attribute.rs#L116
make a new constructor like this one https://github.com/rust-analyzer/rust-analyzer/blob/9efa355a629badd9eb680b0ae9067757bff05f96/crates/ide_completion/src/completions/attribute.rs#L116 but for pure snippets and adjust the completion code accordingly?

**Comment by jhgg** [comment]
> Ideally we should show two here, the one that prefills debug(which has the triple dot in its label) and one that only fille the `derive` identifier, removing the place I mentioned removes the `Debug` prefill one I assume from your screenshot. I think the stuff there doesn't allow one to only keep the snippet one but without the "bare" identifier completion hmm.

I'd agree, removing https://github.com/rust-analyzer/rust-analyzer/blob/9efa355a629badd9eb680b0ae9067757bff05f96/crates/ide_completion/src/completions/attribute.rs#L147 seems to render https://github.com/rust-analyzer/rust-analyzer/blob/0001a425702f3c3f163d25f63cf3eebd321097dc/crates/ide_completion/src/completions/attribute.rs#L245 inoperable however - and the two dupes are otherwise identical in function.

**Comment by jhgg** [comment]
Oh I see what you mean...

**Comment by jhgg** [comment]
> We could probably make label here optional as well,
> 
> https://github.com/rust-analyzer/rust-analyzer/blob/9efa355a629badd9eb680b0ae9067757bff05f96/crates/ide_completion/src/completions/attribute.rs#L116
> 
> 
> make a new constructor like this one
> https://github.com/rust-analyzer/rust-analyzer/blob/9efa355a629badd9eb680b0ae9067757bff05f96/crates/ide_completion/src/completions/attribute.rs#L116
> 
> but for pure snippets and adjust the completion code accordingly?
> Assuming the two you got rid of are from this place.

I don't follow!

**Comment by Veykril** [comment]
Ah i pasted the wrong link sorry, meant to link this when I said constructor, https://github.com/rust-analyzer/rust-analyzer/blob/9efa355a629badd9eb680b0ae9067757bff05f96/crates/ide_completion/src/completions/attribute.rs#L132-L138

Basically we should allow this infra to have "pure snippet" completions, so as to be able to get rid of the `derive` completion, but not the `derive(...)` one.

**Comment by Veykril** [comment]
Ye I think our best bet is to remove the `derive` attribute from that list entirely, and just special case that one `derive(Debug)` completion for Structs, Unions and Enums here https://github.com/rust-analyzer/rust-analyzer/blob/9efa355a629badd9eb680b0ae9067757bff05f96/crates/ide_completion/src/completions/attribute.rs#L54-L113

That is just check `attribute_annotated_item_kind` once more if it is one of those three kinds and add that completion separately.

**Comment by Veykril** [comment]
Okay I figured the problem out, I was on the completely wrong track with my assumption, sorry for the confusion! Turns out I added the proper completions for attributes on another path last week or so, fixed in #11040
