### ISSUE TITLE
Add "Stop Light" cargo check status indicator to bottom toolbar. 

### ISSUE THREAD

**Issue by brochington** [rust-analyzer/rust-analyzer#11018]
In VSCode I often will save my work, which will trigger a `cargo check`, but I won't know the status of the check, and have to run `cargo check` again myself. The second check is instantaneous if the check finds no errors, but takes a bit of time if there are errors. Either situation feels like "double work".

I propose a small red/yellow/green indicator in the bottom toolbar so I may at a quick glance, see if I need to fix anything.

**Comment by bjorn3** [comment]
In the statusbar there should be a circle with a cross and a number next to it. This indicates the amount of errors there are. Next to it is a warning sign and another number. This represents the amount of warnings. If you click on it you will see the problems pane with a list of all errors and warnings.

**Comment by brochington** [comment]
@bjorn3 Ahhh, beautiful! This is enough for me. Thank you!
