### ISSUE TITLE
Handle macros in type checking / HIR

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#1102]
Since we have the basic macro expansion infrastructure, we should look into handling macros during typechecking etc. as well. There's two parts to this, as far as I see it:
 - expanding macros in expression position: I think an easy example should be `let v = vec![1, 2, 3];`. I think this should probably happen during conversion from AST to HIR; this is done by the `collect_expr` function, which has a case for `ExprKind::MacroCall` which is currently unhandled:
https://github.com/rust-analyzer/rust-analyzer/blob/84d8665e13007b0ee27e2a42ff74db815923cdce/crates/ra_hir/src/expr.rs#L762
This would need to resolve and expand the macro.

 - making use of items defined by macros: I actually don't know if this isn't already working; in theory we're expanding item-level macros. Maybe this just needs some tests.

@matklad I really don't know a lot of details about the existing macro expansion, so please correct me if I'm wrong or missed something :slightly_smiling_face:

**Comment by matklad** [comment]
In the current infra, macros can only expand to items. This is not a hard limititation, it's just the code to expand to expressions is not written yet. 

Items defined by macros should be mostly working, except for the fact that we don't translate offsets properly, so, for example, go to definitions uses the wrong offset.

One relatively simple bit where we don't handle items, but where we should, is handling of `impls`. Currently, collecting impls looks only at the source file itself, but it should expand macros as well.

**Comment by Lapz** [comment]
I've started working on this and have come up with a plan on how to support this.
1. Find the macro rules definition.This will probably involving adding a resolver and a query during the lowering phase
2. Once the ouput is found use the ```MacroRules::expand``` method to expand the call
3. Insert the output into the current sourcefile ? This and the 1 first point are things that I'm currently thinking on how to do

**Comment by flodiebold** [comment]
Re 1: Yes, you'll need to resolve the macro, and I'm not sure how much the infrastructure for that is exposed outside of the name resolution currently.

Re 3: You wouldn't really insert the output into the sourcefile, you'd just continue lowering it with `collect_expr` and return the resulting `ExprId`, I think.

**Comment by Lapz** [comment]
The biggest problem that I'm having is that macro's are defined in terms of macros. This means that we see macro_rules! vec {
    ($($item:expr),*) => 
    {
        {
            let mut v = Vec::new();
            $(
                v.push($item);
            )*
            v
        }
    };
} and vec![dfdfd] as both a macro call because macro_rules is implemented in terms of a macro. This makes resoultion kinda hard as when we look at a macro call we need the macro's rules on what to expand it to. Since we dont treat them seperaterly it makes the transformation much harder. The problem is how would I go about storing  things within the database. i.e would i be able to store all macros which expand to rules and query them depending on the name.

**Comment by DJMcNab** [comment]
Is this fixed by #1147?

**Comment by flodiebold** [comment]
Yeah, I think this is fixed by now.
