### ISSUE TITLE
Clippy lint groups are not included in autocomplete

### ISSUE THREAD

**Issue by lilyball** [rust-analyzer/rust-analyzer#11027]
If I type `#![allow(` and autocomplete, rust-analyzer offers the standard lint groups, such as `nonstandard_style` or `future_incompatible`. If I type `#![allow(clippy::` and autocomplete, rust-analyzer offers clippy lints but notably it does not offer any clippy lint groups such as `clippy::style` or `clippy::suspicious`.

**rust-analyzer version**: db2a7087b 2021-12-13 stable

**rustc version**: 1.57.0 (f1edd0429 2021-11-29)

**Comment by Veykril** [comment]
We only complete the lints, but not the groups here https://github.com/rust-analyzer/rust-analyzer/blob/b75d4d3dbe703093be18c64d28f11d9f6e29dd62/crates/ide_completion/src/completions/attribute.rs#L37-L38
https://github.com/rust-analyzer/rust-analyzer/blob/b75d4d3dbe703093be18c64d28f11d9f6e29dd62/crates/ide_db/src/helpers/generated_lints.rs#L7903

**Comment by pitaj** [comment]
Never mind, guess @k-nasa is working on it.

**Comment by k-nasa** [comment]
sorry @pitaj 🙇 
 I was working without saying anything ...
