### ISSUE TITLE
Support multi-root workspace in vscode

### ISSUE THREAD

**Issue by zimond** [rust-analyzer/rust-analyzer#1104]
I think we could use the approach in https://github.com/rust-lang/rls-vscode/pull/333/files, start analyzer for every dir in the workspace

**Comment by matklad** [comment]
We don’t need to start separate instances of analyzer, the code is well prepared to handling arbitrary crate graphs. This is he bit where this happens: https://github.com/rust-analyzer/rust-analyzer/blob/84d8665e13007b0ee27e2a42ff74db815923cdce/crates/ra_lsp_server/src/main_loop.rs#L60

As you see, we already construct a vector of workspaces(of length one at the moment).

To support multiroot setup, we should extend this code to scan several roots

**Comment by jrvidal** [comment]
I've been experimenting a bit with this and it looks like VSCode reloads the extension completely when a folder is added to the workspace. That would mean that supporting multiple workspaces doesn't yet require full-fledged dynamic workspace loading. I could prepare a PR for this "hack" and/or work on the "full" solution later (if nobody is working on this).

Maybe related/interesting https://github.com/Microsoft/vscode/issues/28122

**Comment by matklad** [comment]
@jrvidal if the "hack" works for your / @zimond use-case, I'd be happy to merge it. 

And yeah, loading ws *dynamically* would be much harder then just reloading the whole thing: the latter would require changes to how vfs works, which is a whole new can of worms.

**Comment by CMCDragonkai** [comment]
Does multiroot workspace really work? I've got a workspace, with projects, and within a particular project, there is subdirectory with the rust project.

I read somewhere that this extension only detects rust projects 1 level deep. Is there a way to configure this or to tell the extension where the rust project is?

**Comment by bjorn3** [comment]
You can use the rust-analyzer.linkedProjects config in case rust-analyzer failed to auto-detect it. Make sure to also include the Cargo.toml files that previously got auto-detected. Setting it disables all auto-detection.

**Comment by iamshreeram** [comment]
Hi @bjorn3 / @matklad , Has there been any update on the "multi-root workspace" feature in the past year? I have a similar question that I posted (#16030). Would you please review it?

**Comment by erikschul** [comment]
@iamshreeram https://users.rust-lang.org/t/multi-root-workspace/104572
