### ISSUE TITLE
Uploading release artifacts fails too often

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#11056]
It failed again last night, two times in a row. These are `ECONNRESET`s during the upload.

We're using some older code, but I fail to see what could be wrong there.

**Comment by lnicola** [comment]
In a commit linked in https://github.com/actions/upload-release-asset/issues/69, the solution was to use the `gh release` command.

**Comment by lnicola** [comment]
I started https://github.com/github/feedback/discussions/9121 about this.

**Comment by ishanjain28** [comment]
There is a bad release again. 

Please restart the pipeline

**Comment by lnicola** [comment]
@ishanjain28 if you're getting an error, try updating or reinstalling the extension.

**Comment by ishanjain28** [comment]
@lnicola I tried that but I still get, 

```
ERROR [12/21/2021, 11:48:03 AM]: Assertion failed: Bad release: {"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/55709944","assets_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/55709944/assets" ...
```

I believe it maybe because the latest release failed with ECONNRESET errors https://github.com/rust-analyzer/rust-analyzer/actions/runs/1604540158

**Comment by lnicola** [comment]
I restarted the release. Are you on the nightly channel?

**Comment by ishanjain28** [comment]
Hey @lnicola, Yes, I am on the nightly channel and that fixed it. Thank you so much

**Comment by villem** [comment]
I cannot update nightly channel. I get bad release too.  This is VScode 
```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

```
INFO [12/25/2021, 5:31:58 PM]: PersistentState: {
  lastCheck: 1639817407179,
  nightlyReleaseId: 55583095,
  serverVersion: '0.3.861'
}
ERROR [12/25/2021, 5:32:04 PM]: Assertion failed: Bad release: {"url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/55967417","assets_url":"https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/55967417/assets","upload_url":"https://uploads.github.com/repos/rust-analyzer/rust-analyzer/releases/55967417/assets{?name,label}","html_url":"https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly","id":55967417,"author":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
```

**Comment by lnicola** [comment]
@villem that's to be expected. You can remove the channel setting and install a new version, but please read https://rust-analyzer.github.io/thisweek/2021/12/27/changelog-109.html before.

**Comment by villem** [comment]
Thanks! Manually installation worked. I understood that this only an issue with "released" version of RA, not with nightlies.

**Comment by lnicola** [comment]
Your original problem was strictly related to nightly channel updates: the old nightlies didn't know which VSIX to download in order to update. We could have implemented that, but we would have needed to support both for a time because not everyone updates daily.

The Open VSX problem is probably affecting every installation. I don't know how the extension gets published there, but it's likely that the nightlies from the Code Marketplace end up on Open VSX as stable version. Even the Code Marketplace is pretty buggy and can't differentiate between stable and nightly. These are all nightlies:

![image](https://user-images.githubusercontent.com/308347/147535494-9ee4ec60-dd75-4084-86c9-5d86e7a9e766.png)

The "installs old version" problem with the official marketplace probably affects only stable users. If you were using nightly before, you can try to opt in to pre-release versions and see what happens.

**Comment by lnicola** [comment]
Between #11103 and #11127, we've probably done all we could on our side. GitHub is still pretty unreliable, though.
