### ISSUE TITLE
RA unable to deduce the type of hashmap collected from iterator chain

### ISSUE THREAD

**Issue by OleStrohm** [rust-analyzer/rust-analyzer#11072]
**rust-analyzer version**: 2021-12-13

**rustc version**: 1.56.1

In this code example RA seems unable to figure out the type of the HashMap.
This gets resolved either by removing the second map, or by making the tuple something simpler, like `((0, 0), 0)`.
```
use std::collections::HashMap;

let _conversions = (0..1)
    .map(|_| (0, ((0, 0, 0), 0)))
    .map(|c| c)
    .collect::<HashMap<_, _>>();
```

**Comment by lnicola** [comment]
Possibly related to #10673.

**Comment by flodiebold** [comment]
Hm, the fact that it works with `((0, 0), 0)` seems to point to the type size limit. Does it work if you set the `CHALK_SOLVER_MAX_SIZE` environment variable to e.g. `100`?

**Comment by lnicola** [comment]
Good point, it works with 40.

**Comment by flodiebold** [comment]
Still a bit weird though, either I misunderstand how the size limit works or there shouldn't be such big types there :thinking:
