### ISSUE TITLE
set current working directory for procedural macros

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#11079]
In 

https://github.com/rust-analyzer/rust-analyzer/blob/8dc3a270f6a893a592db1a5fe3cf8752521987e1/crates/proc_macro_srv/src/cli.rs#L8-L24

nothing sets currend dir explicitly, it gets inherited. This is wrong, as proc-macros generally can look at pwd. Note that this is per-macro thing -- we run a single expander process, but each crates' macros want to see their own pwd. 

I think we need to add `current_dir` to this struct: 

https://github.com/rust-analyzer/rust-analyzer/blob/8dc3a270f6a893a592db1a5fe3cf8752521987e1/crates/proc_macro_api/src/msg.rs#L31-L52

and call `std::env::set_env` when serving a request.

**Comment by matklad** [comment]
cc https://github.com/intellij-rust/intellij-rust/issues/8238

**Comment by bjorn3** [comment]
Cargo has changed the current working directory of rustc invocations in the past. (from package root to workspace root) I don't think there is any guarantee that it won't change it again in the future.

**Comment by matklad** [comment]
Yeah, to be clear:

* macros that look at pwd are technically borken, this isn't something guaranteed to work and they shouldn't do that
* macros do look at pwd sometimes, and it would be useful if that worked more often than not.
