### ISSUE TITLE
Reordered imports and comments mixed up

### ISSUE THREAD

**Issue by NickLarsenNZ** [rust-analyzer/rust-analyzer#11087]
I've noticed an issue where comments on imports end up on the wrong line after the imports are reordered:

Before hitting save:

![image](https://user-images.githubusercontent.com/10092581/146962197-6d8bd584-d8ee-43f0-a950-57994c7b6f09.png)

After hitting save:
 
> __Notice the comment on the wrong line__

![image](https://user-images.githubusercontent.com/10092581/146962298-5f80794f-dba1-4c8a-8e02-fe33c34d9d50.png)

**rust-analyzer version**: `rust-analyzer version: 0add6e95e 2021-12-20 stable`

**rustc version**: `rustc 1.57.0 (f1edd0429 2021-11-29)`

**Comment by Veykril** [comment]
We merely invoke `rustfmt` on save, so this is a bug with `rustfmt`, not rust-analyzer.

**Comment by NickLarsenNZ** [comment]
I wasn't aware, thanks @Veykril.

For posterity, the (currently open) `rustfmt` issue is: https://github.com/rust-lang/rustfmt/issues/4027
