### ISSUE TITLE
Parameter completions should insert a `,` if followed by another parameter

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#11085]
```rs
fn foo(bar: ()) {}
fn foo2(ba$0 baz: ()) {}
```
Selecting the `bar: ()` completion here should insert `bar: (), ` instead of just `bar: ()`

**Comment by Veykril** [comment]
Relevant code is here https://github.com/rust-analyzer/rust-analyzer/blob/0e5d8883ccbe4a125e8da07a4be6c791838e9134/crates/ide_completion/src/completions/fn_param.rs#L61-L82

So we should simply check whether after our cursor position follows another parameter.

**Comment by dbofmmbt** [comment]
I'm taking a look at some adjustments in the param completion which should solve this and other small issues too.
