### ISSUE TITLE
Wrong proc macro expansion in match arm

### ISSUE THREAD

**Issue by tamasfe** [rust-analyzer/rust-analyzer#11097]
Given the following code:

```rs
use my_macro::select_type;

enum DummyType {
    Type1,
    Type2,
    Type3,
}

fn does_it_work(ty: DummyType) -> bool {
    match ty {
        select_type!(1,2,3) => true,
    }
}
```

Where `select_type` expands to `DummyType::Type1 | DummyType::Type2 | DummyType::Type3`, but RA only expands it to `DummyType::Type1`, and thus shows a [missing match arm](https://rust-analyzer.github.io/manual.html#missing-match-arm) error even though the code compiles fine.

**rust-analyzer version**:  851af5a52 2021-12-21 nightly

**rustc version**: rustc 1.57.0 (f1edd0429 2021-11-29)

**Comment by xudesheng** [comment]
@tamasfe Magic, if I change "Type" to "T" in both the `select_type` macro definition and the enum definition, the rust_analyzer will work as expected.

I just tested it on my Mac.
