### ISSUE TITLE
Implement missing members on an #[async_trait] generates invalid code

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#11100]
I just used `Implement missing members` on the `#[async_trait]` `axum::extract::FromRequest` (which isn't all too helpful, but I hadn't thought about the async'ness), and noticed that the return type of `from_request` was written out as

```rust
core::pin::Pin<
    Box<
        dyncore::future::Future<Output = Result<Self, Self::Rejection>>
            + core::marker::Send
            + 'async_trait,
    >,
>
```

It looks like some printing logic inside RA missed the required space between `dyn` and `core`.

**Comment by Veykril** [comment]
Relevant code for "pretty-printing" macro expansion ast is here https://github.com/rust-analyzer/rust-analyzer/blob/012ff79a0d1fc5337cb6e6cda39e7a2c45aba717/crates/ide_db/src/helpers/insert_whitespace_into_node.rs

**Comment by jplatte** [comment]
I'll try fixing this one myself :)

**Comment by Veykril** [comment]
A relevant test for this is here https://github.com/rust-analyzer/rust-analyzer/blob/012ff79a0d1fc5337cb6e6cda39e7a2c45aba717/crates/ide_assists/src/handlers/add_missing_impl_members.rs#L908-L944

**Comment by jplatte** [comment]
It *seems* like this should already be handled by the first branch in the big match there:

https://github.com/rust-analyzer/rust-analyzer/blob/012ff79a0d1fc5337cb6e6cda39e7a2c45aba717/crates/ide_db/src/helpers/insert_whitespace_into_node.rs#L60-L62

`is_text` is `is_keyword || is_literal || _ == IDENT` (the keyword check includes `DYN_KW`) so has to be true for `dyn`. `is_punct` should absolutely be `false` for `core`. I was thinking this would be an obvious fix, but looks like I'm not getting that. This doesn't mean I need help (yet), just need to allocate more than a few minutes to work on this :)

**Comment by jplatte** [comment]
There's one thing I'd like to ask before getting back to this: Are there tests for 'implement missing member' somewhere? I think stepping in with a debugger might be a good next step, and a test as an entry point would be great.

**Comment by Veykril** [comment]
You can copy the test here https://github.com/rust-analyzer/rust-analyzer/blob/012ff79a0d1fc5337cb6e6cda39e7a2c45aba717/crates/ide_assists/src/handlers/add_missing_impl_members.rs#L908-L944
to use `add_missing_impl_members,` instead of `add_missing_default_members` and removing the default impl in the trait.

**Comment by jplatte** [comment]
I can't get it to reproduce with a `macro_rules!` macro 😅

<details><summary>Working test case:</summary>

```rust
    #[test]
    fn test_async_trait() {
        check_assist(
            add_missing_impl_members,
            r#"
mod m {
    trait ObjectSafe {}
}

struct Generic<T: ?Sized>(&'static T);

macro_rules! foo {
    () => {
        trait MacroTrait {
            fn trait_method() -> Generic<dyn m::ObjectSafe + 'static>;
        }
    }
}
foo!();
struct Foo;

impl MacroTrait for Foo {
    $0
}
"#,
            r#"
mod m {
    trait ObjectSafe {}
}

struct Generic<T: ?Sized>(&'static T);

macro_rules! foo {
    () => {
        trait MacroTrait {
            fn trait_method() -> Generic<dyn m::ObjectSafe + 'static>;
        }
    }
}
foo!();
struct Foo;

impl MacroTrait for Foo {
    fn trait_method() -> Generic<dyn m::ObjectSafe+ 'static> {
        ${0:todo!()}
    }

}
"#,
        )
    }
```

</details>

When mixing my own test case based on a `macro_rules!` macro and `#[async_trait]` I also got RA to produce both a correct and a wrong `dyn` in one go:

<details><summary>Still failing with <code>#[async_trait]</code></summary>

```rust
use async_trait::async_trait;

mod m {
    pub trait ObjectSafe {}
}

struct Generic<T: ?Sized + 'static>(&'static T);

#[async_trait]
trait MacroTrait {
    async fn trait_method() -> Generic<dyn m::ObjectSafe + 'static>;
}

struct Foo;

impl MacroTrait for Foo {
    fn trait_method<'async_trait>() -> core::pin::Pin<
        Box<
            dyncore::future::Future<Output = Generic<dyn m::ObjectSafe + 'static>>
                + core::marker::Send
                + 'async_trait,
        >,
    > {
        todo!()
    }
}
```

</details>

**Comment by Veykril** [comment]
Hmm interesting, will take a look, interesting observation here is also that it works for one use of `dyn` in `async_trait` but not all

**Comment by Veykril** [comment]
Looking at our current `Expand macro recursively` output on the `#[async_trait]` trait def gives us:
```rs
trait MacroTrait {
  #[must_use]
  #[allow(clippy::type_complexity,clippy::type_repetition_in_bounds)]
  fn trait_method< 'async_trait>() ->  ::core::pin::Pin<Box<dyn::core::future::Future<Output = Generic<dyn m::ObjectSafe+ 'static> > + ::core::marker::Send+ 'async_trait> > ;
  

  }
```
Note the leading `::` for the core paths, which are missing in the paste from the assist, so what I assume happens here is that we see a `dyn` keyword followed by a `::` which we don't insert a whitespace into(just a guess) and then something rewrites paths here that loses the `::`. In all cases we should isnert a whitespace between a keyword followed by a `::` and that should fix the problem here, if my assumption is correct.

**Comment by jplatte** [comment]
Interesting! I will try reproducing with a `macro_rules!` macro that uses `dyn ::Something`.

**Comment by flodiebold** [comment]
I guess it's our `PathTransform` that rewrites the paths then? So you would just need something where the path is already in scope.
