### ISSUE TITLE
Attribute macro expansion fails in `impl` block (`fehler`)

### ISSUE THREAD

**Issue by 1Dragoon** [rust-analyzer/rust-analyzer#11104]
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
rust-analyzer version: 0add6e95e 2021-12-20 stable
Also tried with an identical result: rust-analyzer version: 4ea1f58bf 2021-12-23 nightly
**rustc version**: (eg. output of `rustc -V`)
rustc 1.58.0-nightly (c9c4b5d72 2021-11-17) (Nightly is required for the connectorx crate)

I'm running into a situation where rust-analyzer doesn't seem to show the inline implicit data types. It happens right after I call the destination.polars() method.

![image](https://user-images.githubusercontent.com/4461926/147175164-35a2153a-70ea-4d93-b62e-906601ccc004.png)

It should (on that same line) show "data: DataFrame =", but just shows "data =" instead, and everything afterwards is missing until I start from another explicit type. Rustc seems to be able to infer the types without any problem, and it compiles and runs fine. If I bring polars_core in scope and explicitly type that line as DataFrame from that crate, rust-analyzer is then able to infer the types, but it won't compile.

Minimally working example:

Cargo.toml:
```toml
[dependencies]
tokio = { version = "1.14.0", features = ["net", "macros", "rt-multi-thread"] }
connectorx = { version = "0.2.2", features = ["src_mssql", "dst_arrow2"] }
```

main.rs:
```rust
use connectorx::{destinations::arrow2::Arrow2Destination, prelude::*};
use std::sync::Arc;
use tokio::runtime::Runtime;

fn main() {
    let rt = Arc::new(Runtime::new().unwrap());
    let conn = "mssql://server:1433/mydb?trusted_connection=true";
    let source = MsSQLSource::new(rt, conn, 1).unwrap();
    let mut destination = Arrow2Destination::new();
    let queries = ["SELECT TOP (1) id FROM mytable"];
    let dispatcher = Dispatcher::<MsSQLSource, Arrow2Destination, MsSQLArrow2Transport>::new(
        source,
        &mut destination,
        &queries,
        None,
    );
    dispatcher.run().unwrap();
    let data = destination.polars().unwrap();
    let a = data.column("id").unwrap();
    let b = a.get(0).to_string();
    println!("{}", b);
}
```

**Comment by lnicola** [comment]
Looks like we're having trouble expanding `fehler::throws`.

**Comment by lnicola** [comment]
Repro:

```rust
use fehler::throws;

struct S;
impl S {
    #[throws(std::io::Error)]
    fn example() {}
}
```

**Comment by Veykril** [comment]
Looks like it, we resolve attributes on moditems here https://github.com/rust-analyzer/rust-analyzer/blob/4ea1f58bf6b3fd5bb59ed583f2ac432e237e1e1e/crates/hir_def/src/nameres/collector.rs#L1440-L1453 which would exclude inherent items

Impl processing is done here https://github.com/rust-analyzer/rust-analyzer/blob/4ea1f58bf6b3fd5bb59ed583f2ac432e237e1e1e/crates/hir_def/src/nameres/collector.rs#L1501-L1507 so I don't us expanding attributes in impl blocks(simple way to check this should be trying to run the expand macro command as well)

**Comment by jonas-schievink** [comment]
Early nameres doesn't look at impl contents, these attributes need to be expanded here (which would also handle trait items):

https://github.com/rust-analyzer/rust-analyzer/blob/7b7a1ed062edd438caa824b6a71aaaa56b48e7d4/crates/hir_def/src/data.rs#L335
