### ISSUE TITLE
Convert struct argument between pattern and object

### ISSUE THREAD

**Issue by masklinn** [rust-analyzer/rust-analyzer#11113]
Some times manipulating a single object is useful, other times it's preferable / more convenient to explode the struct right at the parameter and manipulate its sub-components only.

Would be useful to have that built-in.

This might be part of a wider set of conversions around parameters e.g. "introduce parameter object" is a classic, in Rust it could be replacing multiple parameters by a single tuple or struct, and converting name to pattern (and pattern to name) could be a sibling assist.

**Comment by Veykril** [comment]
This is https://github.com/rust-analyzer/rust-analyzer/issues/8673 if I understand this correctly, right?

**Comment by masklinn** [comment]
> This is #8673 if I understand this correctly, right?

If #8673 is supposed to work for function parameters then yes, but also the inverse of #8673 where the tuple is "restructured" and the indirect accesses have to be reintroduced (the reverse is actually the one I was looking for but I figured an issue for both sides would make sense).

**Comment by Veykril** [comment]
Yes #8673 is supposed to be applicable for all patterns, irrefutable and refutable.

The reverse idea hasn't come up yet though.

**Comment by masklinn** [comment]
Ok i’ll close this and comment on the other one then (assuming I don’t forget), sorry for the bother.
