### ISSUE TITLE
Cannot activate rust-analyzer: bootstrap error.

### ISSUE THREAD

**Issue by prismatic-obloquy** [rust-analyzer/rust-analyzer#11121]
**rust-analyzer version**: ???

**rustc version**: `rustc 1.57.0 (f1edd0429 2021-11-29)`

Running the `rust-analyzer` binary with literally any options, including `--version`, produces this error:

```
Error relocating /lib/libgcc_s.so.1: __cpu_indicator_init: symbol not found
Error relocating /lib/libgcc_s.so.1: __cpu_model: symbol not found
```

Of course, when the VS Code extension tries to call `rust-analyzer --version`, it fails, because it gets this error.

I have no idea what made this start. It worked fine two days ago. Today, without any changes or even internet access so automatic changes could happen, it breaks.

Also, when the entire extension breaks like this, `rust-analyzer.onEnter` breaks too. This isn't that surprising, but what *is* surprising is that it just... does nothing, not even the default newline behavior. Surely if the rest of the extension fails you can just have the advanced enter trigger the normal behavior instead.

**Comment by prismatic-obloquy** [comment]
On reread I think this is the same issue as #11080, but I'm on the proprietary VS Code. The same fix works: I installed from that VSIX and the problem went away. It could be an ephemeral issue with their service so I'll check back tomorrow and see if it's still happening and if not, close it.

**Comment by bjorn3** [comment]
> Also, when the entire extension breaks like this, rust-analyzer.onEnter breaks too. This isn't that surprising, but what is surprising is that it just... does nothing, not even the default newline behavior. Surely if the rest of the extension fails you can just have the advanced enter trigger the normal behavior instead.

This is the reason `rust-analyzer.onEnter` isn't enabled by default AFAIK. While you can still use shift+enter to insert an enter, any attempt to use the enter key will fail as the extension itself will crash if the server fails to start. This happens because of the vscode lsp client I think. Not sure if there is any way to avoid this.

**Comment by prismatic-obloquy** [comment]
> Not sure if there is any way to avoid this.

Well, that would be annoying. I'd be genuinely surprised if that's the case, but then again, I don't know anything about writing VS Code extensions. Regardless thank you for the explanation.

**Comment by lnicola** [comment]
Which version of the extension were you on?

**Comment by prismatic-obloquy** [comment]
...whoops! I forgot to close this; the issue has indeed gone away after a few days. (In my defense I've been away from internet.)

I'm not certain, unfortunately. I *think* it was 0.2.867? I remembered checking at the time and seeing the version matched the other issue.

Regardless, the closed-source one is working (for me) now, so I'm closing this issue.
