### ISSUE TITLE
VS Code extension breaks Vim extension

### ISSUE THREAD

**Issue by theduke** [rust-analyzer/rust-analyzer#1113]
Currently, there seems to be some conflict between the ra-lsp extension and the [Vim](https://github.com/VSCodeVim/Vim) extension.

When I enable both, non of the Vim keybindings work (although the normal mode cursor is shown).

When I disable ra-lsp, everything works normally again.

## Versions

rust-analyzer: `84d8665e13007b0ee27e2a42ff74db815923cdce`
VS Code: `1.32.2`
Vim extension: `1.3.0`
OS: Arch Linux / i3 WM

**Comment by matklad** [comment]
That is a known issue, you should disable his setting: https://github.com/rust-analyzer/rust-analyzer/blob/bb3b159fb7d377f667732ade715cbe019da84d71/editors/code/package.json#L160-L164

**Comment by uHOOCCOOHu** [comment]
I also run into this issue just after the installation. It prevents my editing not only `.rs` file but **any** file, including the `config.json` itself. 
I think it should be disabled by default for compatibility.
@matklad

**Comment by matklad** [comment]
I don't have strong opinion about default here, but I slightly lean towards keeping the default on: it's easy to disable feature than to enable it, because, for the latter, you need to know that the feature exists.

**Comment by zaphar** [comment]
It would be good to document this conflict a little more clearly. I had to google search to find this issue and use the workaround there.

**Comment by juliandemille** [comment]
This option doesn't even appear in the VSCode settings UI when using the extension from the marketplace.

**Comment by lnicola** [comment]
@juliandemille see https://github.com/rust-analyzer/rust-analyzer/issues/3013.
