### ISSUE TITLE
Does the vscode extension no longer need to download binary file?

### ISSUE THREAD

**Issue by RXDA** [rust-analyzer/rust-analyzer#11133]
Does the vscode extension no longer need to download binary files? I deleted the binary and reinstalled the extension, but there was no prompt to download the binary, and `rust-analyzer.updates.askBeforeDownload` became an unknown configuration

**Comment by lnicola** [comment]
It now contains the server binary, see https://rust-analyzer.github.io/thisweek/2021/12/27/changelog-109.html#known-issues.

**Comment by RXDA** [comment]
> It now contains the server binary, see https://rust-analyzer.github.io/thisweek/2021/12/27/changelog-109.html#known-issues.

thanks!
