### ISSUE TITLE
Remove `SemanticScope::speculative_resolve_as_mac`

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#11132]
This currently exists solely for `try_resolve_derive_input`, but that can be implemented in a more direct way, using `resolve_derive_macro` functionality from #11131. Though, I think we need to change return type from `Vec<MacroDef>` to `Vec<Option<MacroDef>>` -- that is, we should explicitly record *unresolved* macros, such that we can make the indices match. 

What happens internally is that today `try_resolve_derive_input` works in a funny way -- in the guts, it literally converts an attribute to a *string*, than parses that as `ast::Path`, than resolves this. Internally, we definitely already do the same thing in a more principled way (`Attr::parse_derive`), so this is just duplication, and the only difficulty is communicating this info back to the IDE layer.

**Comment by Veykril** [comment]
Hmm, we won't be able to get rid of the `Attr::parse_derive` duplication unfortunately as we are also interested in the qualifier paths here for IDE purposes, which do not resolve to derive macros...

**Comment by matklad** [comment]
Yeah, I do think that we need to keep some amount of logical duplication here, but it should be encapsulated in the HIR.

The situation here is similar to resolving & completing paths in `use`. In the hir, we don't actually record where intermediate segments of imports resolve to. So, when we need to compute goto-def, we re-create a prefix of a path, and resolve that. The crucial thing though, is that this is hidden in the API, `Semantics::resolve_path(ast::Path)` takes a very specific path with identity, and resolves that (even if internally it creates "path as value"). So, if one day we refactor our name resolution to actually record intermediate results, than the API would work as is. 

For derives, I think we want the API like this:

```rust
Semantics::resolve_derive_attr(ast::Ident)
```

where the `ident` is a specific token, `Clone` in `#[derive(Clone)]`. That would be consistent with the overall shape of semantics, which uses identity, rather than value semantics. This alone I think should remove "convert tokens to string, than parse them as AST" from IDE layer. 

But I think we could go further than that and avoid `Path::parse(tt.to_string())` even internally -- when we are inside semantics, we can actually grab `hir::Attr` which corresponds to `ast::Ident` using `AttrSourceMap`. With that at hand, we can do logic like

* our `ast::Ident` is the third ident in a path-looking thing
* so we can do `hir_attr.parse_derive().nth(3)`

This is still sketchy and awkward logic, as it hits #3407, but it's less sketchy than converting `tt`  to string.
