### ISSUE TITLE
Auto-complete list fails in VSCode when typing fast

### ISSUE THREAD

**Issue by simonborje** [rust-analyzer/rust-analyzer#11147]
extension version: v0.2.853 and v0.3.884
rustc version: 1.57.0
VSCode: 1.63.2
Windows 10

Once the auto-completion list has popped up once and I continue to type faster than the list can be updated, the list often either disappears or returns "No suggestions.". The list does work correctly as long as I type slow enough so that the list has time to update the results for every new letter.
When the list disappears it is possible to force it to reappear by pressing Ctrl + space, but if it has started to report "No suggestions" that does not help to restore the suggestions.

Example below: typing the letters "g" "n" at the end of "align" with a pause between keeps the list populated, but typing the two letters fast causes it to fail.
![49kulA7g91](https://user-images.githubusercontent.com/3867784/147792164-f1c6b754-adbb-4ab8-aa49-d7509c68466d.gif)
.

**Comment by SomeoneToIgnore** [comment]
Duplicates https://github.com/rust-analyzer/rust-analyzer/issues/7560 and https://github.com/rust-analyzer/rust-analyzer/issues/10187
