### ISSUE TITLE
regression in semantic highlighting of comments within a `#[salsa::query_group(...)`

### ISSUE THREAD

**Issue by jhgg** [rust-analyzer/rust-analyzer#11176]
I noticed this in rust-analyzer's source code, the `string` semantic token modifier is being applied to comments:

![image](https://user-images.githubusercontent.com/5489149/147893956-6d2900c0-5e08-4e0c-9481-001196adf591.png)

I've bisected this to #11169

cc @Veykril

**Comment by Veykril** [comment]
Ah, now I see why we didn't descend comments in highlighting, descending maps them down to doc attributes so they get tagged as the string literal of the attribute(this really should've had a comment explaining that though I guess that can be added now).

Culprit being this line that I removed here https://github.com/rust-analyzer/rust-analyzer/pull/11169/files#diff-6d95bdbd0359e449fe1d50d3788dba4e270e3ac2f68e395a754aa3bb56accd96L295
