### ISSUE TITLE
regression of `self` semantic highlighting in async-trait

### ISSUE THREAD

**Issue by jhgg** [rust-analyzer/rust-analyzer#11174]
I landed a fix for this in #10899 - however, due to lack of proc macro testing infrastructure didn't write a test :( 

It looks like this recently regressed, and a bisect has shown the following PR as the culprit: #11171

cc @Veykril

**Comment by Veykril** [comment]
Ah I made a mistake when rewriting things earlier, should be fixed by https://github.com/rust-analyzer/rust-analyzer/pull/11175
