### ISSUE TITLE
rust-analyzer underlines sqlx queries as erroneous

### ISSUE THREAD

**Issue by nicoSix** [rust-analyzer/rust-analyzer#11172]
I'm using the ```sqlx::query!``` macro in my code, which triggers a query verification at compile-time, thus requiring a connection to a database to perform this verification. 

It works when executing ```cargo run```, but in VSCode each query is displayed as erroneous by rust-analyzer, showing this error:

![error](https://user-images.githubusercontent.com/17080744/147891775-f403c13c-2200-4174-9975-e05a81497880.png)

Note that I'm using a localhost PostgreSQL database running on port 5433 rather than 5432 (default port). It is not an issue when compiling as I defined a .env file containing the connection string required by sqlx to compile query macros, but I suspect this might be an issue for rust-analyzer. Is there a possibility to configure it somewhere?

My version of rust-analyzer is ```v0.3.887```, a preview version.

**Comment by Veykril** [comment]
You can set env vars for the server(and all processes it starts up including proc-macros) with the `"rust-analyzer.server.extraEnv"` setting, or start VSCode with the env vars set.

**Comment by nicoSix** [comment]
> You can set env vars for the server(and all processes it starts up including proc-macros) with the `"rust-analyzer.server.extraEnv"` setting, or start VSCode with the env vars set.

Thank you for this answer, it perfectly solves my issue!
