### ISSUE TITLE
How do I disable placeholders(?) on match arms filling and similar places

### ISSUE THREAD

**Issue by pacak** [rust-analyzer/rust-analyzer#11185]
Currently when I have code like this

```rust
  match foo {}
```

RA will suggest to fill in match arms, which is a good behavior. But when it does so it will fill in something that looks like this:

```rust
  match foo {
      Event::Mouse(${0:_}) => todo!(),
      Event::Resize(_, _) => todo!(),
  }
```

How do I make it to fill in this instead, note `_` instead of `${0:_}`:

```rust
  match foo {
      Event::Mouse(_) => todo!(),
      Event::Resize(_, _) => todo!(),
  }
```

**Comment by flodiebold** [comment]
These placeholders should be replaced by the client. What LSP client / editor are you using?

**Comment by pacak** [comment]
> These placeholders should be replaced by the client. What LSP client / editor are you using?

neovim with `neovim/nvim-lspconfig` and `simrat39/rust-tools.nvim`.

**Comment by pacak** [comment]
The client removes them now.
