### ISSUE TITLE
Duplicate &mut insertion on parameter auto-completion

### ISSUE THREAD

**Issue by mvtec-bergdolll** [rust-analyzer/rust-analyzer#11199]
rust-analyzer version: 0add6e95e 2021-12-20 stable

rustc 1.56.1 (59eed8a2a 2021-11-01)

# Problem

When I  enter `func(&mut <some_var_name_partial>` I get the suggestion `&mut  <some_var_name_full>` as first suggestion, when I select it I get `func(&mut &mut <some_var_name_full>` the double `&mut` is not what I want, I always have to go back and delete it. Quite annoying.

# Possible Resolutions

A) Offer just `<some_var_name_full>` as first suggestion
B) Make sure it doesn't duplicate the &mut when inserting

# Example

![image](https://user-images.githubusercontent.com/62337596/148256579-1ecdd272-eccd-4d2b-9e29-8eecb5ac3f73.png)
![image](https://user-images.githubusercontent.com/62337596/148256631-ed7c5676-c54b-4e6f-be96-21ed7f215654.png)

**Comment by weirane** [comment]
I want to work on this but I don't know where to change the code? I've scanned through `crates/ide_completion/src/completions` but can't find where is the relavent code.

**Comment by Veykril** [comment]
I am not too sure how we do this either but I think the `compute_ref_match` here https://github.com/rust-analyzer/rust-analyzer/blob/2e33bf23c94e7053eb657d1a318bd1b66cabec95/crates/ide_completion/src/render.rs#L304-L322 is somewhat related
