### ISSUE TITLE
Unclear error message is shown when an older unsupported toolchain is used via rustup override

### ISSUE THREAD

**Issue by jtroo** [rust-analyzer/rust-analyzer#11191]
As the title suggests, when I override the toolchain used via `rustup override set 1.46.0`, rust-analyzer can no longer load the workspace, with the error `can't load standard library from sysroot`.

I've run `rustup component add rust-src` as well as `rustup component add rust-src --toolchain 1.46.0-x86_64-unknown-linux-gnu`.

I have verified that the source code exists in both `$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust` and `$HOME/.rustup/toolchains/1.46.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust`.

The toolchain was added with `rustup toolchain add 1.46.0`

**rust-analyzer version**: `rust-analyzer 8e9ccbf97 2022-01-03 stable`

**rustc version**: (eg. output of `rustc -V`)
`rustc 1.57.0 (f1edd0429 2021-11-29)` (default, works)
`rustc 1.46.0 (04488afe3 2020-08-24)` (override, does not work)

**Comment by bjorn3** [comment]
Rust changed the organization of the source directory a while ago. Rust-analyzer only supports the new organization. Rustc 1.46 still uses the previous organization.

**Comment by jtroo** [comment]
Thanks for the quick reply. It could use a better error message if it's possible to detect this issue, but feel free to close this issue if it doesn't seem worth doing.

**Comment by lnicola** [comment]
I think we can close this. The message is technically correct, but we can't tell why we can't find the libraries unless we special-case the pre-1.46 directory structure. Since nominally only the latest stable is supported, that's probably not worth it.
