### ISSUE TITLE
Visual Studio Code, editor.formatOnSave, Message: The pipe has been ended. (os error 109)

### ISSUE THREAD

**Issue by Zageron** [rust-analyzer/rust-analyzer#11196]
**rust-analyzer version**: rust-analyzer version: c5049bdcd 2022-01-05 nightly

**rustc version**: rustc 1.59.0-nightly (399ba6bb3 2022-01-03)

**operating system**: Windows 10, 10.0.19044 Build 19044, x64

Using powershell as back-end, not using WSL2 or gitbash.

1. Enable formatOnSave for rust.
2. Open a file.
3. Save.

```bash
[Error - 7:38:27 p.m.] Request textDocument/formatting failed.
  Message: The pipe has been ended. (os error 109)
  Code: -32603 
```

- Running `cargo fmt` works, even with the file open.
- Files are using LF endings.
- Happens in both elevated and non-elevated VSC.

**Comment by jazvit** [comment]
I had the same problem. Reinstallation of nightly toolchain helped. please check are you using a nightly formatter?
`rust-analyzer.rustfmt.extraArgs`.

**Comment by Zageron** [comment]
```json
    "rust-analyzer.rustfmt.extraArgs": [
        "--all",
        "--",
        "--check"
    ]
```
I found the problem, `--all` breaks it. What a foolish error. Thank you @jazvit.
