### ISSUE TITLE
`#[derive]` after doc comment loses hover and go to def

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#11215]
Repro:

```rust
/// a
#[derive(PartialEq)]
struct S;
```

Hovering over `PartialEq` does nothing, and "go to def" also doesn't work on it. It does still work on the `derive` token though.

Removing the doc comment or moving it below the derive restores functionality.

**Comment by Veykril** [comment]
I think there is more to this, because every second derive also doesn't work properly 😆
![image](https://user-images.githubusercontent.com/3757771/148393851-2bb01407-2a59-492a-bb7f-8d14f4960de3.png)

**Comment by jonas-schievink** [comment]
I think I've fixed that part in https://github.com/rust-analyzer/rust-analyzer/pull/11211

**Comment by jonas-schievink** [comment]
This bug is caused by this code not taking into account doc comments:

https://github.com/rust-analyzer/rust-analyzer/blob/c574cf351a9ab4c5610693ba979dd29dd7fde99c/crates/hir/src/semantics/source_to_def.rs#L218-L224

`attrs` contains doc comments and attributes, but it's indexed by the attribute's index, ignoring doc comments.

**Comment by Veykril** [comment]
Ah ye that looks like the problem, I guess using dynmap for that would be a decent fix then
