### ISSUE TITLE
Attribute macros inside impl blocks seem to ignore/remove function bodies

### ISSUE THREAD

**Issue by tamasfe** [rust-analyzer/rust-analyzer#11228]
## Expected Behaviour

After adding `tracing`'s `instrument` macro to the list implemented in [#11193](https://github.com/rust-analyzer/rust-analyzer/pull/11193).

I expect `bar` in the following to be recognized as just an ordinary function:

```rs
impl Foo {
  #[tracing::instrument]
  fn bar() {}
}
```

## Actual Behaviour

Attribute macro expansion "Not Available" inside `impl` blocks, and seems to break ~both outside function completions and~ all ra features inside the function body ~as well~.

```rs
#[tracing::instrument] // Works
fn foo() {
    #[tracing::instrument] // Also works
    fn foo_inner(s: String) {
    }
}

impl Foo {
    #[tracing::instrument] // Does not work
    fn no_rust_analyzer_allowed() {
        // This function body is guaranteed 100% rust-analyzer-free.
    }
}
```

Adding/removing the macros from `rust-analyzer.procMacro.ignored` does not make a difference.

**rust-analyzer version**: 2fb6f5e46 2022-01-07 nightly

**rustc version**: rustc 1.57.0 (f1edd0429 2021-11-29)

**Comment by tamasfe** [comment]
Actually, even with `rust-analyzer.experimental.procAttrMacros: false` the mere presence of the attribute seems to break the function body in all cases I tried.

**Comment by Veykril** [comment]
Might be a result of https://github.com/rust-analyzer/rust-analyzer/pull/11208

**Comment by Veykril** [comment]
The problem is most likely the FIXMEs here, https://github.com/rust-analyzer/rust-analyzer/pull/11208/files#diff-d8dfb3db867db48288d543c75638f4eb67e70d7ec2a0b48a3253ddedd20fc04d

The file id check fails, because we are querying sources for the source file id, but the assoc items live in macro file ids so we skip them.
