### ISSUE TITLE
vscode  rust-analyzer + remote ssh extension cause internal error: entered unreachable code

### ISSUE THREAD

**Issue by httaotao** [rust-analyzer/rust-analyzer#11221]
when I use vscode extensions and install rust-analyzer and remote-ssh , it shows the error. I guess the extension could not use with remote-ssh extension. thanks

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
all  0.2.x and 0.3.x preleease versions have these debug  

**rustc version**: (eg. output of `rustc -V`)
rustc 1.58.0-nightly (baba6687d 2021-11-03)

**Comment by jhgg** [comment]
there is something else afoot here - i exclusively use r-a in vscode remote ssh and it is fine.

**Comment by lnicola** [comment]
Can you post the whole error? The one saying "unreachable code".

**Comment by httaotao** [comment]
> 
it shows the macro-error , if the code with ``` #[async_trait]```  , it shows this error

**Comment by httaotao** [comment]
> Can you post the whole error? The one saying "unreachable code".

where can i find the error ? I am not sure ,thanks.

**Comment by lnicola** [comment]
If only `async_trait` has issues and the rest of the features work, it's related to proc macros. Maybe try upgrading to a different nightly: https://github.com/rust-analyzer/rust-analyzer/issues/10837#issuecomment-1007076392.

**Comment by httaotao** [comment]
> If only `async_trait` has issues and the rest of the features work, it's related to proc macros. Maybe try upgrading to a different nightly: [#10837 (comment)](https://github.com/rust-analyzer/rust-analyzer/issues/10837#issuecomment-1007076392).

Good jobs, it works. thanks
