### ISSUE TITLE
`rust-analyzer.completion.snippets` is formatted badly in the manual

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#11234]
![image](https://user-images.githubusercontent.com/308347/148638976-d1cdf716-03f8-4d5f-89b8-18fc69492710.png)

**Comment by weirane** [comment]
Seems like to be a limitation of adoc. It breaks on multiline defaults. Should we display the default in the description with the doc, maybe like this https://github.com/weirane/rust-analyzer/blob/ac3d44ea6a8/docs/user/generated_config.adoc#user-content-rust-analyzer.completion.snippets ?

**Comment by lnicola** [comment]
I'd put the default below, but that looks nice.
