### ISSUE TITLE
Cargo metadata runs with unknown feature and fails

### ISSUE THREAD

**Issue by Nevsden** [rust-analyzer/rust-analyzer#11243]
**Edited the output for readability**

I am working on an `Ubuntu 20.04.3 LTS` 64-bit version with the latest vs-code. Until just recently the rust-analyzer worked just fine. Ever since I have added permission for vs-code to push to `Github` for a certain project, the rust-analyzer fails with the following error:

```
rust-analyzer failed to load workspace: 
Failed to read Cargo metadata from Cargo.toml file /home/linden/Documents/code/gitlab/cavalier_contours/Cargo.toml, 
cargo 1.57.0 (b2e52d7ca 2021-10-21): 
Failed to run `"cargo" "metadata" "--format-version" "1" "--features" "viewer" "--manifest-path" "/home/linden/Documents/code/gitlab/cavalier_contours/Cargo.toml" 
"--filter-platform" "x86_64-unknown-linux-gnu"`: `cargo metadata` exited with an error: error: none of the selected packages contains these features: viewer
```

I want to mention two things here:
1. There is no feature "viewer". It has never been inside any of the crates nor workspaces `.toml`. If there is a way to somehow reset the rust-analyzer to build its routine anew, I would much appreciate an answer.
2. Ofc adding the `Github` permission and the rust-analyzer may just be a coincidence.

**rust-analyzer version**: rust-analyzer version: 0add6e95e 2021-12-20 stable
**rustc version**: rustc 1.57.0 (f1edd0429 2021-11-29)

**Comment by bjorn3** [comment]
> There is no feature "viewer". It has never been inside any of the crates nor workspaces .toml. If there is a way to somehow reset the rust-analyzer to build its routine anew, I would much appreciate an answer.

Can you look at your vscode preferences? There should be an option named `rust-analyzer.cargo.features` I think.

**Comment by Nevsden** [comment]
Thanks a bunch! That has been it. I added a feature in the past for some other crate that I was maintaining and didn't realize, it would interfere with other crates.
