### ISSUE TITLE
"unresolved_proc_macro" with rustc nightly

### ISSUE THREAD

**Issue by yezuochang** [rust-analyzer/rust-analyzer#11256]
rust-analyzer version: rust-analyzer db2a708 2021-12-19 dev

rustc version: rustc 1.59.0-nightly (e95e084a1 2021-12-19)

![image](https://user-images.githubusercontent.com/12656236/148943042-6a7266ba-1aff-4ca7-9463-ae91d7b6f450.png)

The following script would reproduce the issue in any project, suppose macro_crate is some crate with proc macro. 

```bash
rm -rf ~/.rustup
rm -rf ~/.cargo
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env
rustup install nightly-2021-12-20
rustup default nightly-2021-12-20
rustup component add rust-src
rustup component add rust-analyzer-preview
cargo clean
cargo build -p macro_crate
cargo build
```

**Comment by lnicola** [comment]
Can you upload somewhere the source code of the macro? You said it requires a nightly feature.

**Comment by yezuochang** [comment]
> Can you upload somewhere the source code of the macro? You said it requires a nightly feature.

This is the reproduction of rust-analyzer without the nightly feature.

in macro_crate
```
extern crate proc_macro;
extern crate proc_macro2;
extern crate quote;
extern crate syn;

use proc_macro::TokenStream;

#[proc_macro]
pub fn testmacro(input: TokenStream) -> TokenStream {
    return input;
}
```
in tests
```
use super::testmacro;
#[test]
fn test1() {
    testmacro! {1};
}
```

**Comment by lnicola** [comment]
You seem to be running Code. Did you set `"rust-analyzer.server.path": "~/.rustup/toolchains/nightly-2021-12-20-x86_64-unknown-linux-gnu/bin/rust-analyzer"`?

**Comment by yezuochang** [comment]
> You seem to be running Code. Did you set `"rust-analyzer.server.path": "~/.rustup/toolchains/nightly-2021-12-20-x86_64-unknown-linux-gnu/bin/rust-analyzer"`?

Yes, I did. The following is settings.json.

```json
{
	"rust-analyzer.server.path": "/home/zuochang/.rustup/toolchains/nightly-2021-12-20-x86_64-unknown-linux-gnu/bin/rust-analyzer",
	"[rust]": {
		"editor.defaultFormatter": "matklad.rust-analyzer",
	},
}
```

**Comment by lnicola** [comment]
You don't need to do that. The Code extension comes with its own server binary, but it's a bit hard to install now. Try to comment out that line and/or download the binary from https://github.com/rust-analyzer/rust-analyzer/releases/tag/2022-01-10.

**Comment by yezuochang** [comment]
Using the server binary with the code extension fixes the issue. Thank you.
