### ISSUE TITLE
Unresolved macro: __cpp_closure_impl! 

### ISSUE THREAD

**Issue by gikari** [rust-analyzer/rust-analyzer#11250]
## How to reproduce

1. Create an MRE from https://docs.rs/cpp/latest/cpp/
2. Save and run the example (it runs just fine).
3. Rust Analyzer shows error: "Unresolved macro __cpp_closure_impl!"

![Screenshot_20220111_015659](https://user-images.githubusercontent.com/14205339/148851940-1764ad19-c762-455b-8392-eb10c115b51c.png)

**rust-analyzer version**: rust-analyzer version: db2a7087b 2021-12-13 stable

**rustc version**: rustc 1.57.0 (f1edd0429 2021-11-29)

**Comment by lnicola** [comment]
That's a MBE macro defined by a derive, we probably don't expand those.

**Comment by jonas-schievink** [comment]
Repro:

```rust
use cpp::cpp;

fn f() {
    let _r = cpp!(unsafe [] -> u32 as "uint32_t" { return 0; });

    #[derive(cpp::__cpp_internal_closure)]
    enum CppClosureInput {
        Input = (stringify!([] -> u32 as "uint32_t" { return 0; }), 0).1,
    }
    unsafe {
        __cpp_closure_impl![];
    }
}
```

According to "expand macro recursively" the expansion is empty. Removing the `cpp!()` invocation above makes the custom derive panic when expanded by rustc, but we seem to ignore it (this could be a diagnostics bug in item bodies).

If the expansion produced the expected `macro_rules!` item, we shouldn't have a problem expanding it.

**Comment by bjorn3** [comment]
Looks like cpp-macros reads a file produced by the build script of the to be compiled crate into a global. This is incompatible with the way rust-analyzer loads proc macros. It only works when each time a crate is compiled a new process is started to ensure that the global isn't shared between different crates and is always reloaded if the build script runs again. This works for rustc at the moment as each compilation happens in a different process, but it doesn't work with rust-analyzer as a single proc macro server loads all used proc macros once and then is reused every time a macro needs to be expanded. This means that an outdated version for whichever crate had a proc macro of the cpp crate expanded first remains used for all crates even if the build script runs again.

https://github.com/mystor/rust-cpp/blob/b826bc5beb7abc15c4862be748e0c3ac0b8b2d61/cpp_macros/src/lib.rs#L37

**Comment by jonas-schievink** [comment]
I've fixed the missing diagnostics in https://github.com/rust-analyzer/rust-analyzer/pull/11257.

Given that rust-analyzer will never really be able to deal with macros that rely on things like mutable global state and the precise expansion ordering, closing this as wontfix.

**Comment by gikari** [comment]
Do I understand correctly from the discussion above, that cpp macro does something, that rust analyzer cannot analyze, and therefore the fix will be, that rust analyzer will just ignore the cpp macro and will not produce an error message?

**Comment by jonas-schievink** [comment]
For now, the fix is probably to add `__cpp_internal_closure` to `rust-analyzer.procMacro.ignored`.

**Comment by gikari** [comment]
I'm probably doing something wrong, but it didn't help:

VSCode settings.json:

```json
  "rust-analyzer.procMacro.ignored": {
    "cpp_macros": ["__cpp_internal_closure"],
    "cpp": ["__cpp_internal_closure"]
  }
```
The result:

![Screenshot_20220111_175002](https://user-images.githubusercontent.com/14205339/148965089-5b39247b-d4da-44bd-9149-e638ea4323ae.png)

**Comment by jonas-schievink** [comment]
Ah, right, that won't fix the knock-on errors. I don't think there's a way to avoid this other than completely disabling `unresolved-macro-call`.
