### ISSUE TITLE
"not implemented" macro_error with rustc nightly feature "source_file"

### ISSUE THREAD

**Issue by yezuochang** [rust-analyzer/rust-analyzer#11264]
rust-analyzer version: rust-analyzer 54782428a 2022-01-12 nightly
rustc version: nightly-2021-12-20-x86_64-unknown-linux-gnu

When using the span().source_file() to get the path of the caller, RA reports the "not implemented" macro error. 

The code works find with cargo build. 

The whole project reproducing the issue is in: https://github.com/yezuochang/proc_macro_example

```
#[proc_macro]
pub fn testmacro(input: TokenStream) -> TokenStream {
    let _caller_path = input
        .clone()
        .into_iter()
        .last()
        .unwrap()
        .span()
        .source_file()
        .path();
    return input;
}
```

![image](https://user-images.githubusercontent.com/12656236/149136364-d3cc1081-7142-44d9-995b-23a5e2e3d1cd.png)

**Comment by lnicola** [comment]
CC https://github.com/rust-analyzer/rust-analyzer/issues/10570
