### ISSUE TITLE
Build targets of workspace crates do not appear to be honoured

### ISSUE THREAD

**Issue by huntc** [rust-analyzer/rust-analyzer#11268]
**rust-analyzer version**: `rust-analyzer version: 54782428a 2022-01-12 dev`

**rustc version**: `rustc 1.59.0-nightly (c5ecc1570 2021-12-15)`

Further to the "[Respect .cargo/config.toml](https://github.com/rust-analyzer/rust-analyzer/pull/8774)" PR, the `config.toml` file of a crate within a workspace does not appear to be honoured. For example, if I have a project named `client` and it has two crates, `app` and `embedded-app`, and `embedded-app` has a `.cargo/config.toml`, then the latter does not appear to be considered when determining build targets.

To reproduce this issue:

1. Download the branch at https://github.com/titanclass/embassy-start/pull/4
2. `rustup target add thumbv7em-none-eabihf` if you don't have that target
2. Open the project's workspace file (`embassy-start.code-workspace`) in VSC
3. Navigate to `client/embedded-app/src/boards/nrf52840_dk.rs`
4. Wait for RA to complete its indexing
5. Note that `interrupt::take!` on L18 is able to be resolved
6. Remove the `"rust-analyzer.cargo.target": "thumbv7em-none-eabihf"` from the workspace file
7. Reload RA
8. Wait for RA to complete its indexing
9. Note that `interrupt::take!` can no longer be resolved

My expectation is that the build target of `client/.embedded-app/.cargo/config.toml` should be honoured, and that I should not have to declare a `rust-analyzer.cargo.target`.

Related? https://github.com/rust-analyzer/rust-analyzer/issues/8521

**Comment by huntc** [comment]
I made some progress by running my own RA build and printing out the cargo.toml's that were being used to determine the various targets. In my example, this is what I get:

config ManifestPath { file: AbsPathBuf("/Users/huntc/Projects/titanclass/embassy-start/client/Cargo.toml") } "cargo" "-Z" "unstable-options" "config" "get" "build.target"
result None
config ManifestPath { file: AbsPathBuf("/Users/huntc/Projects/titanclass/embassy-start/network-protocol/Cargo.toml") } "cargo" "-Z" "unstable-options" "config" "get" "build.target"
result None
config ManifestPath { file: AbsPathBuf("/Users/huntc/Projects/titanclass/embassy-start/server/Cargo.toml") } "cargo" "-Z" "unstable-options" "config" "get" "build.target"
result None
...meaning that no target is being resolved out of the cargo.toml's that are used.

client/embedded-app/Cargo.toml and server/embedded-app/Cargo.toml would be needed to determine the needed build targets here.

**Comment by huntc** [comment]
I've come to the conclusion that RA is working as intended. When it performs a `cargo check`, it does so at the workspace level if there is one, or if there's not, then just the crate. Cargo workspaces aren't effective when there are multiple targets being used as expressed by `config.toml`. In fact, `config.toml`s are only applied when `cargo` is working within that particular directory.

I have since removed workspaces from situations where there are no common targets between crates.

**Comment by robbie-mac** [comment]
If rust-analyzer is using cargo check, maybe the different behavior of cargo check when run i a workspace is contributing to the issue:
https://github.com/rust-lang/cargo/issues/15785
