### ISSUE TITLE
Use inline snapshots for completion tests

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1127]
We use the insta library to test completions. Currently, gold results are stored in the external `.snap` files. This is less than ideal because it makes tests harder to understand and it also adds a ton of files. which makes "go to file" feature of the editor less useful.

Luckily, most of the snapshots contain only a few completions, so [inline snapshots](https://github.com/mitsuhiko/insta/#inline-snapshots) should not be too bad.

We should migrate completion tests (found [here](https://github.com/rust-analyzer/rust-analyzer/tree/master/crates/ra_ide_api/src/completion)) to inline snapshots! It might be a good idea to not do this in one go, but to migrate a single module at a time.

**Comment by CRogers** [comment]
It would be pretty awesome if you could write something in insta to do this migration automagically (no idea if feasible).

**Comment by matklad** [comment]
I bet it's possible to write such migration tool in rust-analyzer itself :) At this scale, don't know which is fasatr, doing by hand, or writing an assist.

**Comment by theotherphil** [comment]
(Commenting for the sake of avoiding multiple people simultaneously working on the same thing) I would like to complete this ticket - I'll create a PR with one commit per remaining .snap file, to be merged or cherry-picked depending on whether inlining is reasonable for that test.
