### ISSUE TITLE
Formatting file empties file

### ISSUE THREAD

**Issue by Ten0** [rust-analyzer/rust-analyzer#11285]
**rust-analyzer version**: 0add6e95e 2021-12-20 stable
**rustc version**: rustc 1.58.0 (02072b482 2022-01-11)

Formatting files that have `@generated` instead empties the whole file.
This issue will hit more users as we had to use `rustfmt +nightly` before to encounter it, while with the 1.58 release all users will be affected.

This only happens if [`format_generated_files`](https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#format_generated_files) is `false` in `rustfmt.toml` (newly released in 1.58).

**Comment by bjorn3** [comment]
This is a rustfmt bug. It doesn't return any code if the input to format contains `@generated`.

```bash
$ echo "//@notgenerated\nfn   foo() {}" | rustfmt
//@notgenerated
fn foo() {}
$ echo "//@generated\nfn   foo() {}" | rustfmt
```
Instead it should emit the original code.

**Comment by bjorn3** [comment]
Opened https://github.com/rust-lang/rustfmt/issues/5172.

**Comment by bjorn3** [comment]
Rust 1.58.1 will contain a fix (https://github.com/rust-lang/rust/pull/93071). It will probably be released tomorrow.
