### ISSUE TITLE
An examples dev dependency is incorrectly highlighted as undefined

### ISSUE THREAD

**Issue by huntc** [rust-analyzer/rust-analyzer#11300]
**rust-analyzer version**: 0f8c96c92 2022-01-10 stable

**rustc version**: rustc 1.58.0 (02072b482 2022-01-11)

RA is reporting that an external dev dependency crate is unresolved within an examples file. However, all is well from the command line. This is a multi-root VSC project and if I open the singular project in another VSC window then RA is happy.

`cargo check` doesn't reveal any issue from that folder. The `show status` VSC/RA command shows that the dependency is there also.

My `embassy-start` project is able to reproduce the problem. Steps:

1. Open the workspace file `embassy-start.code-workspace` from VSC.
2. Navigate to `client/examples/test-harness/main.rs`.
3. Observe the `extern crate menu;` redlined. It shouldn't be as the dev dependency is valid.
4. Separately open the `client/app` project in another VSC window.
5. The `extern crate menu;` isn't redlined and RA appears to be happy with the project in general.

Here's the project: https://github.com/titanclass/embassy-start.

**Comment by jonas-schievink** [comment]
With  #11308 you can see what's actually going on:

```
File info:
Crate: test_harness(CrateId(73))
Dependencies: proc_macro=CrateId(65), core=CrateId(62), alloc=CrateId(61), std=CrateId(67), test=CrateId(69), app=CrateId(72), defmt=CrateId(166), heapless=CrateId(265)
Crate: test_harness(CrateId(11))
Dependencies: proc_macro=CrateId(4), core=CrateId(1), alloc=CrateId(0), std=CrateId(6), test=CrateId(8), app=CrateId(10), heapless=CrateId(24), menu=CrateId(35), pancurses=CrateId(47)
```

I'm not sure why the version *with* defmt is missing the dev-dependencies though, that shouldn't really happen.

**Comment by huntc** [comment]
Also, don’t forget that things are fine if the client/app project is opened directly ie without the VS workspace.

**Comment by jonas-schievink** [comment]
Opened  #11314 with a fix that I'm not completely sure about.
