### ISSUE TITLE
Getting error "Function `x` don't exist for type `T`" when it does and the code compiles fine

### ISSUE THREAD

**Issue by RpxdYTX** [rust-analyzer/rust-analyzer#11306]
I was making some edits when my notebook was turned off because of low battery, but since VSCode saves the changes made, i was not left without having the changes applied.
When I turned my notebook on again, the code compiled and ran fine, but RA keeps saying that the method `on_window_mut` does not exist for type `Viewport`, even though when hovering over it, vscode shows the whole declaration, and ctrl clicking it leads to exact place where it was declared:

![20220116_213058](https://user-images.githubusercontent.com/74186130/149787228-363bf06b-8f49-4146-9f6d-b2fc9b82e800.jpg)

**rust-analyzer version**: `9700addc8 2022-01-17 stable`

**rustc version**: `rustc 1.57.0 (f1edd0429 2021-11-29)`

**Comment by lnicola** [comment]
Try closing Code and running `cargo clean`.

**Comment by RpxdYTX** [comment]
Thanks, it fixed that annoying false error
