### ISSUE TITLE
Trait method completions expand incorrectly

### ISSUE THREAD

**Issue by The0x539** [rust-analyzer/rust-analyzer#11301]
**rust-analyzer version**: `rust-analyzer 0f8c96c92 2022-01-10 stable`

**rustc version**: `rustc 1.60.0-nightly (ec4bcaac4 2022-01-15)`

Steps to reproduce:
- Type this: 
![image](https://user-images.githubusercontent.com/7350294/149679507-dd511883-3952-4b45-948f-9fe1f605259e.png)
- Select/activate the completion

Expected behavior: the correct expansion:
```rs
impl Default for Foo {
    fn default() -> Self {
        
    }
}
```
(whitespace and closing brace are nice to have, but unimportant for the purpose of this issue, and probably not related anyway)

Actual behavior: something like this: 
![image](https://user-images.githubusercontent.com/7350294/149679673-9a58a745-6bcb-47fd-8770-7f425208e393.png)

[Reproduction in Kakoune](https://asciinema.org/a/dTLd0XOphTS5pH26t3kNeoWj3)

Something similar happens in some other cases, I believe, but I can't remember what.

This bug has haunted me for what feels like years, across neovim+coc.nvim, neovim+nvim-lsp, kakoune+kak-lsp, and now helix. In helix, it seems to go away when I hit enter to "perform the completion", but in the others, it's a real persistent thing that I need to go back and delete.

This doesn't happen in vscode, so until today I've, with increasing doubt, chalked it up to being a problem on the editor's side, but helix marks the third unrelated editor and fourth unrelated LSP client that I've experienced this with over a very long period of time.

Am I somehow the only one experiencing this? What's going on?

**Comment by flodiebold** [comment]
Hm. I can't reproduce this in Emacs. Looking at the completion response, it seems we for some reason return a text edit replacing the `de` (whatever part of the identifier you typed), but an *additional text edit* removing the `fn ` including the space. Maybe these editors have a problem with additional text edits, or specifically additional text edits touching the same lines? Do 
completion autoimports work, considering those also use additional text edits?

**Comment by The0x539** [comment]
Yep, I can definitely summon [*some* jank](https://asciinema.org/a/P1vJe7fYc1tKb54mv8vfPO4vo) with imports. That might be the majority of the "other cases" I mentioned. I think I'm remembering import code actions causing this sort of jank at one point, probably in a similar case where a single-item path becomes brace-y.
