### ISSUE TITLE
rust-analyzer-2022-01-17 build breakage

### ISSUE THREAD

**Issue by 0-wiz-0** [rust-analyzer/rust-analyzer#11331]
Compiling rust-analyzer-2022-01-17 on NetBSD with rust-1.57.0 I see:
```
   Compiling ide_db v0.0.0 (/scratch/lang/rust-analyzer/work/rust-analyzer-2022-01-17/crates/ide_db)
error: there is no argument named `string`
  --> crates/ide_db/src/helpers/format_string.rs:16:14
   |
16 |     format!("{string} {bar}", bar = string);
   |              ^^^^^^^^

error: could not compile `ide_db` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```
2022-01-10 was fine.

**Comment by Veykril** [comment]
We usually only try to have rust-analyzer build on the latest stable, the code there uses a feature introduced with 1.58, so you need to upgrade your toolchain to be able to build that release.

**Comment by 0-wiz-0** [comment]
Ok.
Is there a workaround patch I can use for now?

**Comment by Veykril** [comment]
There is not. Your options here are to either upgrade your toolchain, stick with an old release or try and patch out the parts in r-a that require 1.58 features.

**Comment by 0-wiz-0** [comment]
Ok, thanks for the comments.

**Comment by lnicola** [comment]
@0-wiz-0 see https://github.com/rust-analyzer/rust-analyzer/pull/11321.

**Comment by 0-wiz-0** [comment]
@lnicola Thank you, that patch (not surprisingly) fixes the problem.
Also, today's release (which includes this) works fine with rust 1.57 again.

**Comment by lnicola** [comment]
Is the toolchain lagging on NetBSD? It's Tier 2, so I think it should build, but I don't know if you have binary packages for it.

Unfortunately, we do use newly-released features as soon as they reach stable.

**Comment by 0-wiz-0** [comment]
I'm packaging for pkgsrc, and for that reason I'm using the rust toolchain that's packaged.
Since we try to test rust on a couple platforms for breakage in the other packages we have in pkgsrc, it takes a couple of weeks after a rust update for pkgsrc's rust to be up-to-date.
The upstream-provided rust for x86_64 is up-to-date AFAIK (https://forge.rust-lang.org/infra/other-installation-methods.html - x86_64-unknown-netbsd).
pkgsrc also provides rust on NetBSD for aarch64, arm, powerpc, and some non-NetBSD operating systems.
