### ISSUE TITLE
Vulnerable dependencies on 2022-01-24

### ISSUE THREAD

**Issue by leonardohn** [rust-analyzer/rust-analyzer#11341]
I ran `cargo audit` on the current version of `rust-analyzer` and got the following report:

```
Found 2 vulnerabilities:

Crate:    dashmap
Version:  5.0.0
Title:    Unsoundness in `dashmap` references
Date:     2022-01-10
ID:       RUSTSEC-2022-0002
URL:      https://rustsec.org/advisories/RUSTSEC-2022-0002
Solution: No solution available

Crate:    thread_local
Version:  1.1.3
Title:    Data race in `Iter` and `IterMut`
Date:     2022-01-23
ID:       RUSTSEC-2022-0006
URL:      https://rustsec.org/advisories/RUSTSEC-2022-0006
Solution: Upgrade to >=1.1.4
```

**rust-analyzer version**: 2022-01-24

**rustc version**: 1.58.1

**Comment by lnicola** [comment]
These are pretty harmless, I don't think we keep references to `dashmap` items like that, and `thread_local` is only a transitive `dev-dependency`. If you're worried about crashes, there are other, worse, bugs that lead to crashes. If you're worried about the security implications, make sure to disable `cargo check`, proc macros and build scripts.
