### ISSUE TITLE
Rename "Named" structs to Record structs?

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1134]
In wg-grammar, they are using record for braced struct syntax and I feel like this is a good idea. Should we do the same?

```
pub enum StructKind<'a> {
    Tuple(&'a ast::TupleFieldDefList), // was Tuple(&'a ast::PosFieldDefList),
    Record(&'a ast::RecordFieldDefList), // was  Named(&'a ast::NamedFieldDefList),
    Unit,
}

PosFieldDef -> TupleFieldDef
NamedFieldDef -> RecordFieldDef

StructLit -> RecordExpr
NamedFieldList -> RecordFieldList
NamedField -> RecordField
```

**Comment by matklad** [comment]
And also `hir::Expr::StructLit` -> `hir::Expr::Record`

**Comment by matklad** [comment]
cc @vlad20012, might be a good name for IntelliJ Rust as well

**Comment by vlad20012** [comment]
As for me, `StructLit`/`Named*` name is much more understandable. Perhaps this is a matter of habit.

**Comment by matklad** [comment]
will be closed by https://github.com/rust-analyzer/rust-analyzer/pull/1731
