### ISSUE TITLE
Env vars set by proc macros should be cleared after a macro expansion

### ISSUE THREAD

**Issue by vlad20012** [rust-analyzer/rust-analyzer#11355]
Some macros change their environment variables. For example, `sqlx` loads [all variables from `.env` file](https://github.com/launchbadge/sqlx/blob/2182925e92bc58ec4579c5b1e63377dcf5c6ae37/sqlx-macros/src/query/mod.rs#L85). These envs can affect the expansion of other macros. For example, an `sqlx` macro from crate `A` can affect `sqlx` macros from crate `B`.

Demo:

```rust
#[proc_macro]
pub fn set_var(_: TokenStream) -> TokenStream {
    std::env::set_var("FOO", "bad");
    TokenStream::new()
}

#[proc_macro]
pub fn read_var(_: TokenStream) -> TokenStream {
    let var = std::env::var("FOO").unwrap_or_else(|_| "good".to_string());
    format!("\"{}\"", var).parse().unwrap()
}
```

then use them like this:

```rust
fn main() {
    my_proc_macro::set_var!();
    let b = my_proc_macro::read_var!();
}
```

`read_var!()` should be expanded to "good", but it will likely be expanded to "bad".

**Comment by bjorn3** [comment]
I think sqlx should be changed to read `.env` without changing the environment. The env vars will affect other proc macros in the same rustc invocation too. In addition it will break the env var change tracking of rustc/cargo.

**Comment by vlad20012** [comment]
Yes, I agree. Also, I think that the expander should be resilient to such an abusing

**Comment by bjorn3** [comment]
Rustc isn't robust against it either.

**Comment by vlad20012** [comment]
Rustc is a bit more robust. Since a new rustc process is created for each crate, these env vars are not shared between crates.
I'm sorry that my example did not show this. We just need to put `set_var!` and `read_var!` into different crates.
A real-world example - consider a crate `A` that uses `sqlx` and has `.env` with `SQL_OFFLINE=true`, and a crate `B` that uses `sqlx` and does not have `.env`. Then, when compiled by rustc, `sqlx` in crate `B` assumes that `SQL_OFFLINE=false` since it does not exist. But when expanded by RA, envs from crate `A` can be shared with macros in crate `B`, hence the behavior of `sqlx` macros may differ
