### ISSUE TITLE
Add Return Type Tooltip For .await

### ISSUE THREAD

**Issue by danii** [rust-analyzer/rust-analyzer#11359]
I think it would be really useful to be able to hover over `.await`s and see the value they return.

Something among the lines of this should be enough:
![image](https://user-images.githubusercontent.com/39541871/151465292-e5232565-72f8-4d87-83b8-ae61634f64a8.png)

**Comment by jonas-schievink** [comment]
This should work with any expression already, as long as you select it

**Comment by flodiebold** [comment]
It does make sense to also show it when hovering the await though.

**Comment by Veykril** [comment]
Would probably make sense to show the type of any expression a keyword is being hovered over for(where it makes sense that is)? That is `if`, `loop`, etc.

**Comment by Veykril** [comment]
keyword hovers are rendered here https://github.com/rust-analyzer/rust-analyzer/blob/93036aa0e201474d43c38be3862f4a899defe267/crates/ide/src/hover/render.rs#L232-L258

So all that has to be done is take the parent node of the `token`, check if its an `ast::Expr` then ask `sema.type_of_expr(..)` for the type and add that to the message appropriately(behind the keyword, as shown in the screenshot makes sense).

**Comment by danii** [comment]
I suppose anyone with a little bit of Rust knowledge could add that with that information...
Oh, hey! I know Rust! How do I self assign?
