### ISSUE TITLE
the most simple completion

### ISSUE THREAD

**Issue by davemilter** [rust-analyzer/rust-analyzer#1135]
I try the most simple variant of completetions: 

```Rust
fn main() {
    struct Foo {
        i: i32,
    }

    let foo = Foo { i: 17 };
    foo.
}
```

But without success, completions not yet implemented?

![a](https://user-images.githubusercontent.com/26097083/55970682-ab414580-5c88-11e9-892d-6d85d0196cf9.png)

**Comment by matklad** [comment]
We don't support items declared in item bodies yet, try delcaring Foo outside

**Comment by davemilter** [comment]
@matklad 

Ok, what about builtin types, like `&str`,
also not yet ?

```Rust
fn main() {
    let s = "abc";
    s.
}
```
I've expected things like `len()`, `is_empty()`, `as_bytes()`

![b](https://user-images.githubusercontent.com/26097083/55971348-fc056e00-5c89-11e9-9634-cbecbbdbb7a6.png)

**Comment by matklad** [comment]
yeah, built-in types are mostly unsupported as well.

**Comment by davemilter** [comment]
@matklad 

Thank you, I thought that something wrong in my setupu.

**Comment by flodiebold** [comment]
I opened #1139 for primitive type methods.
