### ISSUE TITLE
feat: set target-dir for rust-analyzer in extension

### ISSUE THREAD

**Issue by CAD97** [rust-analyzer/rust-analyzer#11362]
You can currently add `--target-dir $RA_TARGET_DIR` (placeholder, not actual env var) to the rust-analyzer check on save extra args, but this only changes the target dir for `check` operations, and not e.g. the proc macro runner.

**Comment by K4rakara** [comment]
:+1: this would be great for projects that utilize the meson build system (like several GNOME applications)

**Comment by flodiebold** [comment]
I think you can just set `CARGO_TARGET_DIR` in `rust-analyzer.server.extraEnv`? In general we don't want to add settings for every possible rustc parameter.
