### ISSUE TITLE
replace usages of `algo::generate` with `iter::successors` from std

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1136]
1.34 is out, so we no longer need to copy-paste generate everywhere!

https://github.com/rust-analyzer/rust-analyzer/blob/e6e2571bdf780d304c792d4317bbaf1d6f5d7a0a/crates/ra_syntax/src/algo.rs#L50-L51

**Comment by lnicola** [comment]
Probably closed by #1143.

**Comment by matklad** [comment]
indeed, thanks!

**Comment by matklad** [comment]
oh, btw we have a similar `generate` in rowan, it should be replaced as well: https://github.com/rust-analyzer/rowan
