### ISSUE TITLE
No autocomplete for as_i32_ref

### ISSUE THREAD

**Issue by dodalovic** [rust-analyzer/rust-analyzer#11372]
![image](https://user-images.githubusercontent.com/6358061/151655216-e1739358-8b9c-406f-93f1-3110b26e6ca1.png)

**Comment by Veykril** [comment]
is `NumRef` defined in the function where the `impl` is, or is it outside? In the latter case I think this behaviour is currently expected due to technical reasons

**Comment by dodalovic** [comment]
The latter one :(

**Comment by flodiebold** [comment]
Actually AFAIK we look for impls in the same block as the method call? The only thing that doesn't work is using impls defined in a completely unrelated block. So there seems to be some bug here.

**Comment by flodiebold** [comment]
It seems to be a completion problem; I can reproduce the missing completion, but if you write the method call the return type gets inferred correctly.
