### ISSUE TITLE
doc: binary set-up documentation

### ISSUE THREAD

**Issue by schwrzstrbn** [rust-analyzer/rust-analyzer#11371]
We currently have no clear documentation for the binary installation of rust-analyzer.

**Comment by lnicola** [comment]
https://rust-analyzer.github.io/manual.html#rust-analyzer-language-server-binary is more Unix-oriented, but to me it seems like it should be pretty clear for a software developer, even if they're not using Linux. Do you want to file a PR with improvements?

**Comment by schwrzstrbn** [comment]
> https://rust-analyzer.github.io/manual.html#rust-analyzer-language-server-binary is more Unix-oriented, but to me it seems like it should be pretty clear for a software developer, even if they're not using Linux. Do you want to file a PR with improvements?

yeah seems like I missed that part. I'm using linux and that is exactly what I'm looking for.

**Comment by schwrzstrbn** [comment]
> https://rust-analyzer.github.io/manual.html#rust-analyzer-language-server-binary is more Unix-oriented, but to me it seems like it should be pretty clear for a software developer, even if they're not using Linux. Do you want to file a PR with improvements?

I'm closing this issue now, Thank you.
