### ISSUE TITLE
Feature request: convert explicit paths to import.

### ISSUE THREAD

**Issue by vi** [rust-analyzer/rust-analyzer#11374]
I want Rust Analyzer to have a code assist to do something like this:

```rust
fn main() {
    let x : std::path::PathBuf;
    let y : std::path::PathBuf;
}
```

to

```rust
use std::path::PathBuf;
fn main() {
    let x : PathBuf;
    let y : PathBuf;
}
```

It can already import `PathBuf` when I write it from the beginning, but I typically prefer having explicit paths unless they get really repetitive, and replace them all in one go.

**Comment by lnicola** [comment]
There is already a quick fix for this.

**Comment by vi** [comment]
How do I trigger it? I see "extract type as type alias" when I select the path, but that's not it. And it does not replace other usages of the path.

rust-analyzer plugin is version 0.3.921.

**Comment by flodiebold** [comment]
Put the cursor on the `PathBuf` and trigger code actions. You should get a "Replace qualified name with use" assist.

There's a list of assists in the manual: https://rust-analyzer.github.io/manual.html#assists-code-actions

**Comment by vi** [comment]
Indeed, I need to select (or place cursor to) the last component, not the whole path.

---

Can rust_analyzer somehow monitor manual code edits and detect that user's behaviour matches some existing code assist, for a tip about specific code action to be shown exactly when user needs (or very recently neeed) it?

**Comment by flodiebold** [comment]
> Can rust_analyzer somehow monitor manual code edits and detect that user's behaviour matches some existing code assist

That would be very complicated and error-prone, I don't think it's really feasible.

Let's close this issue since the assist exists.
