### ISSUE TITLE
Usability: Reporting of errors in source code not friendly

### ISSUE THREAD

**Issue by shoffmeister** [rust-analyzer/rust-analyzer#11376]
**rust-analyzer version**: rust-analyzer version: 6634eaf13 2022-01-30 nightly

My rust source code has errors, and the way errors are presented (in vscode) is not optimal in helping me addressing these errors.

My (faulty) source code is:
```
fn returns_option() -> Option<i32> {
    return None;
}

pub fn wombat() {
    println!("hello
    
    
    
    
    
    
    
    ");

    let x = returns_option()?;
    println!("{x}");


    let y = returns_option()?;
    println!("{y}");
}
```

Obviously, `returns_option()?` on `pub fn wombat() {` is no good, so there's that.

The way this is _presented_ to me in vscode is not really helpful, though:

![image](https://user-images.githubusercontent.com/3868036/151696330-6d7895d7-1e5d-435a-b2cd-2c57d2f4579f.png)

There are three different "issues" that I expect to be raised
a) `wombat` does not return Option, although the `?` operator is present inside the body: line 5
b) `?` operator is present in two locations: lines 16, 20

Not friendly (I): While I get diagnostics for all three issues, the `?` diagnostics get duplicated. I'd prefer to not see these diagnostics. Imagine pasting copy with a bunch of `?` operators ... It seems as if the "label" and the "help" (rustc terminology) are each issued as distinct diagnostics, while they'd apply both to the one root problem.

Not friendly (II): The complete body of the function has red squiggles. Already in my light-on-text sample, the red squiggles dominate everything, make the function hard to read. And, of course, by marking the complete body of the function, any squiggles _only_ applied to each of the `?` operators gets masked, making it somewhat less convenient to visually locate those cases.

**Comment by shoffmeister** [comment]
rustc presentation is much more approachable, IMHO:

![image](https://user-images.githubusercontent.com/3868036/151696760-2da0dc3b-300d-4f2a-a25d-22469354d8ef.png)

**Comment by shoffmeister** [comment]
When it comes to highlighting errors in functions, would it make sense to render the squiggles not over the complete span of the function at large, but leave out the body block (i.e. the `{ ... }` implementation part) and only squiggle the function's sort-of-declaration part (in my case `pub fn wombat()`)

**Comment by shoffmeister** [comment]
Reducing the number of diagnostics by collapsing "hint" text and the "help:" component would help into the same diagnostic entry would probably reduce visual load, too.

It seems as if there are "error", "label", "hint" and "help" components for each diagnostic? If so, get them all into the same diagnostic, prefix consistently in text? (vscode doesn't support custom drawn visual cues in that panel, I believe)

**Comment by Veykril** [comment]
What rustc version are you compiling on?(Since these are rustc diagnostics)
Interestingly enough, what I get is the following: ![image](https://user-images.githubusercontent.com/3757771/151700752-339c978d-8574-434c-aba6-32a815fdc7eb.png)
It seems for one the help span is not being collapsed into the first three characters of the function like it is for me, and secondly your diagnostic entries are duplicated in the problems pane. Now I am not sure why that is though.

**Comment by shoffmeister** [comment]
❯ rustc -V
rustc 1.58.1 (db9d1b20b 2022-01-20)

And, for good measure: vscode 1.63.2

**Comment by shoffmeister** [comment]
FWIW, I am on Fedora Linux 35, and I have a ... handful ... of extensions active in this workspace (none of which matters, I would seriously hope)

**Comment by shoffmeister** [comment]
I just disabled every vscode extension for that workspace except for
* codelldb
* rust-analyzer
... was forced to "reload" the vscode <whatever - extension host?> ... and  ...

It works well.

This must have been some extension, because the box I restart often enough, vscode I restart often enough ... Blech.

**Comment by shoffmeister** [comment]
I suspect that https://marketplace.visualstudio.com/items?itemName=panicbit.cargo (v0.2.3) is the culprit for "my mess".

Above extension
* disabled - very usable error diagnostics from rust analyzer
* enabled - see my mess

Anybody able to confirm?

**Comment by Veykril** [comment]
That would explain the duplicate errors and different spans.

> Checks your code using cargo check (can be disabled)

You probably want to disable this part of the extension, since r-a already does that for you.

**Comment by flodiebold** [comment]
I think this has been resolved then.
