### ISSUE TITLE
Server doesn't advertise cababilites: matchingBrace, externalDocs, inlayHints, moveItems

### ISSUE THREAD

**Issue by nemethf** [rust-analyzer/rust-analyzer#11389]
The way I understand the [documentation][doc], the server should advertise its capability if it supports the 'Matching Brace' functionality. The documentation is not so clear about the other experimental capabilities.  However, some are advertised (which seems logical) and some are not. This is what I get (it is not in json, but hopefully not hard to read): 
```
            :experimental
            (:joinLines t :openCargoToml t :ssr t :onEnter t :parentModule t :hoverRange t :runnables
                        (:kinds
                         ["cargo"])
                        :workspaceSymbolScopeKindFiltering t))

```
The fix might be as easy as the following patch:
```diff --git a/crates/rust-analyzer/src/caps.rs b/crates/rust-analyzer/src/caps.rs
index 648f6ae..e2c2626 100644
--- a/crates/rust-analyzer/src/caps.rs
+++ b/crates/rust-analyzer/src/caps.rs
@@ -113,6 +113,10 @@ pub fn server_capabilities(config: &Config) -> ServerCapabilities {
         ),
         moniker_provider: None,
         experimental: Some(json!({
+            "matchingBrace": true,
+            "externalDocs": true,
+            "inlayHints": true,
+            "moveItems": true,
             "joinLines": true,
             "openCargoToml": true,
             "ssr": true,
```
Although it would probably make sense to sort the lines alphabetically.
Thanks.

**rust-analyzer version**:  rust-analyzer 17afa2e77 2022-01-24 stable
**rustc version**: rustc 1.58.1 (db9d1b20b 2022-01-20)

[doc]: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#matching-brace

**Comment by bjorn3** [comment]
For inlay hints we are using rust-analyzer.inlayHints and not (yet) experimental.inlayHints, advertising experimental.inlayHints is not right.
