### ISSUE TITLE
"Unnecessary `async`" diagnostic / quick fix

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#11392]
Functions whose body does not use `.await` do generally not have to be marked `async` (unless they're in a trait, once those support async). I think it would be helpful to diagnose this and offer a quickfix that removes the `async` and every `.await` where the function in question is currently called.

**Comment by ChayimFriedman2** [comment]
rustc does not report it: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0f11fa5a57ab0c74b94afda552a92a3d.

But a quickfix may be nice.
