### ISSUE TITLE
Support inherent methods of primitive types

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#1139]
We should support the inherent methods of primitive types, e.g. [str](https://doc.rust-lang.org/std/primitive.str.html#methods). 'Support' here means resolving them during type inference, and providing them as completions.

I think we're actually pretty close to this working: The methods are defined in normal `impl`s in libcore, e.g. here:
https://github.com/rust-lang/rust/blob/9a612b2348212d84fa0b839a4c18e4a13fafaf05/src/libcore/str/mod.rs#L2033
We index impls in each crate by implemented type (without type parameters) and use them for method resolution and completion:
https://github.com/rust-analyzer/rust-analyzer/blob/e6e2571bdf780d304c792d4317bbaf1d6f5d7a0a/crates/ra_hir/src/ty/method_resolution.rs#L40
The problem is that we only look for impls for a type in the crate where the type is defined (since they are only allowed there), and primitive types just don't have a crate in which they are defined. That's why the impls in libcore are marked as *lang items*, e.g. with `#[lang = "str"]`. I think to support this, we need to introduce a bit of infrastructure for collecting these lang items, and then just fix the [def_crate function](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_hir/src/ty/method_resolution.rs#L125) to return the crate containing the corresponding lang item for primitives.

(Once we have the lang item infrastructure, which we'll also need for a few other features, this will probably be E-easy...)

(The impls for the number types use a lot of macros, so getting them working completely will also depend on the macro infrastructure...)

**Comment by flodiebold** [comment]
About lang items:
The workspace may (in theory) contain completely disjoint crate graphs, so there's not *one* set of lang items, but a set of lang items for a specific crate. So I'm imagining there will be a query `lang_items(krate: Crate) -> Arc<LangItems>`, which recursively calls itself for the dependencies of `krate` and then walks all of `krate` to find more.

I'm not completely clear on what `LangItems` will look like; I think something like a struct of maps for different types of item might work, so e.g.
```rust
struct LangItems {
    impl_items: HashMap<String, ImplBlock>,
    ...
}
```
It also makes sense to look into how rustc represents them, of course, which I haven't done yet.

**Comment by marcogroppo** [comment]
I'd like to give this a try, but I'd need (probably a lot of) help... is this ok? I've got some questions already... `ImplBlock` does not seem to implement `AttrsOwner`: is this by design or I should add it to `grammar.ron`? Since we're already collecting all crate impls... can the new `lang_items_query` directly use the `impls_in_crate` query? And finally: is this the right place to ask questions? 😂

**Comment by lnicola** [comment]
> is this the right place to ask questions?

@marcogroppo you can also try https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0

**Comment by flodiebold** [comment]
> I'd like to give this a try, but I'd need (probably a lot of) help... is this ok?

Sure :)
> `ImplBlock` does not seem to implement `AttrsOwner`: is this by design or I should add it to `grammar.ron`?

I don't think it's by design, just no one needed it so far. Adding it to grammar.ron is the right thing to do.
> Since we're already collecting all crate impls... can the new `lang_items_query` directly use the `impls_in_crate` query? 

I think the `lang_items` query will not just go over impls (there are also e.g. trait lang items), so it should do its own walk, I think. Although I guess collecting the different types of lang items separately would be a possible approach as well :thinking: 
> And finally: is this the right place to ask questions?

As Inicola wrote, Zulip works as well. Best to create a new topic with this issue referenced in the title (i.e. `rust-analyzer#1139`.
