### ISSUE TITLE
Cleanup grammar generation

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#114]
Looks like we mess up whitespace when generating ast:

https://github.com/rust-analyzer/rust-analyzer/blob/31c8ebb743572ef07ac4ca77ddd17eddbcf4b24c/crates/ra_syntax/src/ast/generated.rs#L207-L210

It would be cool to avoid that!

https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_syntax/src/ast/generated.rs.tera is the template, and `cargo gen-kinds` command regenrates ast from it.

**Comment by ReinierMaas** [comment]
The part that generates that code is visible below:

https://github.com/rust-analyzer/rust-analyzer/blob/3c41087bf83a4ffda87a7bee16d8eb31562bac23/crates/ra_syntax/src/ast/generated.rs.tera#L60-L87

Especially lines 71-86.

How to generate a newline is described on this [page](https://tera.netlify.com/docs/templates/#introduction).
Possibly by removing a single `-` on line:column 61:3 the entire problem is solved.

**Comment by matklad** [comment]
Indeed this should be closed now!
