### ISSUE TITLE
`print!` and `println!` postfix completion snippets

### ISSUE THREAD

**Issue by JosephTLyons** [rust-analyzer/rust-analyzer#11408]
If you have a variable, `value` and add `.dbg`, then complete it, RA will generate `dbg!(value)`.
It would be great if something existed for `print!` and `println!`.

`value`, type `.println`, complete it, and RA generates `println!("{value}")` or `println!("{}, value")`

If this is something the maintainers would be interested in, I wouldn't mind trying to add it, but if not, then maybe some simple guidance on how to add this as a user snippet would be great.  Reading the [documentation](https://rust-analyzer.github.io/manual.html#user-snippet-completions), I don't quite understand how to make this a custom snippet for VS Code.

**Comment by Veykril** [comment]
Here is how you could make a simple custom snippet for this
```json
  "rust-analyzer.completion.snippets": {
    "print": {
        "postfix": "println",
        "body": [
            "println!(\"{}\", ${receiver})",
        ],
        "scope": "expr",
    }
  }
```

**Comment by lnicola** [comment]
CC #10967

**Comment by JosephTLyons** [comment]
> 

Sorry, I didn't really explain what my actual issue is - I'm not sure where custom snippets go.  Does this go into the normal snippets area in VS Code?  Or some special snippets area that relates to RA only?

**Comment by JosephTLyons** [comment]
> Here is how you could make a simple custom snippet for this
> 
> ```json
>   "rust-analyzer.completion.snippets": {
>     "print": {
>         "postfix": "println",
>         "body": [
>             "println!(\"{}\", ${receiver})",
>         ],
>         "scope": "expr",
>     }
>   }
> ```

Sorry, I didn't really explain what my actual issue is - I'm not sure where custom snippets go. Does this go into the normal snippets area in VS Code? Or some special snippets area that relates to RA only?

**Comment by Veykril** [comment]
it's a r-a specific config, either in your settings.json under the path `rust-analyzer.completion.snippets`, or somewhere in the UI(which will probably prompt you to write the json object out)

**Comment by lnicola** [comment]
https://rust-analyzer.github.io/manual.html#user-snippet-completions

**Comment by JosephTLyons** [comment]
Yep, these work for me.  Just curious, so there is no desire for these to be included directly in RA over custom snippets?  If not, I'll close this.

**Comment by Veykril** [comment]
There is probably little incentive to do so. We should look out that we do not add too many builtin ones since users aren't in control of the builtin snippets. So unless the snippet requires some semantic understanding that custom snippets can't use it is unlikely to be added as a builtin one. At least that's my view on this matter.
