### ISSUE TITLE
[Suggestion]Take rust edition from Cargo.toml itself when .rustfmt.toml is introduced in the project

### ISSUE THREAD

**Issue by rishadbaniya** [rust-analyzer/rust-analyzer#11419]
Can you guys please take rust edition from "Cargo.toml" implicitly for the rustfmt when ".rustfmt.toml" file is introduced in the project. It took me quite a while to figure out why my rust files were not getting formatted, default edition when .rustfmt.toml file is introduced is "2015" and it makes code with "async" keyword be ignored. It was quite a headache for few minutes.

**Comment by lnicola** [comment]
Do you have a cargo workspace with some crates on the 2015 and some on the 2018 edition?

**Comment by rishadbaniya** [comment]
no

**Comment by lnicola** [comment]
Then we should pass the edition. Did you set `rust-analyzer.rustfmt.overrideCommand`?

**Comment by rishadbaniya** [comment]
Yeah, i had set the edition to 2021 explicity on the .rustfmt.toml file, that worked. Wouldn't it be lot more easier if default rust edition was set from the "Cargo.toml" file when its not mentioned on the ".rustfmt.toml"?

**Comment by rishadbaniya** [comment]
I guess i changed my mind, now all i want to know is why "rustfmt.toml" has default edition set to "2015", when editions are not explicitly mentioned, wouldn't new edition be a better choice as a default edition ? I'm so confused here, can you help me understand this

**Comment by rishadbaniya** [comment]
![image](https://user-images.githubusercontent.com/54678051/152680641-1c02c435-8027-499d-98fc-9d2639e3dbd2.png)
 
It says, it picks up edition from the ```Cargo.toml``` when **cargo fmt** is used. Is rust analyzer using "cargo fmt" or purely "rust fmt"?

**Comment by lnicola** [comment]
We're calling `rustfmt`. I don't know if passing `--edition` still works if a config file already exists. If it doesn't, it's not our bug.

**Comment by flodiebold** [comment]
It works as far as I can tell. Even if I specify `edition = "2015"` in rustfmt.toml, formatting through LSP still works with async functions.

**Comment by rishadbaniya** [comment]
I guess now i understand how rustfmt and rust analyzer fits in with .rustfmt.toml
