### ISSUE TITLE
workspace/symbol: inconsistency between documentation and implementation

### ISSUE THREAD

**Issue by nemethf** [rust-analyzer/rust-analyzer#11414]
The [documentation] says the attributes of WorkspaceSymbolParams are searchScope and searchKind, but the client must send search_scope and search_kind instead.

**rust-analyzer version**: rust-analyzer 17afa2e77 2022-01-24 stable

**rustc version**: rustc 1.58.1 (db9d1b20b 2022-01-20)

[documentation]: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#workspace-symbols-filtering

**Comment by Veykril** [comment]
Looks like the struct def is missing a `#[serde(rename_all = "camelCase")]`

https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/rust-analyzer/src/lsp_ext.rs#L498-L512
