### ISSUE TITLE
file/module rename mangles the starting text of the file declaring the module.

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#11417]
So I have a `main.rs` like this:
```rust
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

// ...

submodule!(defer);
```

In this case the `submodule!` macro just takes a module name once and then spits out the `mod` as well as the `pub use`:
```rust
#[macro_export]
macro_rules! submodule {
  ($sub_module_vis:vis $sub_module_name:ident) => {
    $sub_module_vis mod $sub_module_name;
    pub use $sub_module_name::*;
  }
}
```

Okay, so given all that, if I use the "rename" feature to change the name of the `defer` module to something like `defertest`, then the identifier in the macro use gets changed properly, and the file on disk is renamed properly, but *also* part of the top line of the `main.rs` file is mangled to have the new module name in it:
```rust
#![defertestttr(not(debug_assertions), windows_subsystem = "windows")]
```

**Comment by Veykril** [comment]
Looks like we forgot to map the name range for module declarations out of the macro expansion here https://github.com/rust-analyzer/rust-analyzer/blob/668947056a9abb668a17e99134bb677e13828f59/crates/ide_db/src/rename.rs#L191-L200
