### ISSUE TITLE
Highlight continue keywords for loops when the cursor is on the loop or continue keyword

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#11422]
We currently highlight all loop break points and the loop keyword itself when the cursor is on a loop or `break` keyword. We should also highlight all related `continue`s in some cases, that is the following when the cursor is on:

- a loop keyword, that is `for`, `while` and `loop`, highlight all `break` and `continue` that belong to the given loop as well the loop keyword
- `break`: Highlight all `break` that belong to the loop as well as the loop keyword
- `continue`: Highlight all `continue` that belong to the loop as well as the loop keyword

Relevant code is here:
https://github.com/rust-analyzer/rust-analyzer/blob/ba330548023607717295f0dfd61b72eda41aa9dd/crates/ide/src/highlight_related.rs#L66-L69
https://github.com/rust-analyzer/rust-analyzer/blob/ba330548023607717295f0dfd61b72eda41aa9dd/crates/ide/src/highlight_related.rs#L188-L245

**Comment by HansAuger** [comment]
I'll try that one :)
