### ISSUE TITLE
Nixos package

### ISSUE THREAD

**Issue by bkchr** [rust-analyzer/rust-analyzer#1142]
Hey, 
@matklad as you use Nixos, do you already have some Nixos package? :)

**Comment by matklad** [comment]
Nope, I just build from source using Cargo. Rust analyzer itself has no native deps, so packaging it should be trivial. The vscode plugin though uses npm and vscode tooling, so it might be more challenging

**Comment by matklad** [comment]
Closing: we are not at the stage where having official package would make sense, and having a `.nix`  in this repo is not too valuable, because the build process is mostly unexciting :)

**Comment by bkchr** [comment]
Okay :)

**Comment by matklad** [comment]
Apparently, someone has made a package for AUR though: https://aur.archlinux.org/packages/rust-analyzer-git/

**Comment by matklad** [comment]
btw, do we have something like AUR for nixos? I know you can basically publish a gist with nix-expression and it would be usable, but it won't be as user-friendly as AUR with aur-helpers.

**Comment by DJMcNab** [comment]
Have you seen https://www.reddit.com/r/rust/comments/bew0mr/comment/el9bybe? It looks like the AUR package (? - don't know the term) isn't working right?

**Comment by matklad** [comment]
Yeah, that's how I learned that AUR package exists

**Comment by bkchr** [comment]
We have this https://github.com/nix-community/NUR

**Comment by matklad** [comment]
https://github.com/NixOS/nixpkgs/pull/77752
