### ISSUE TITLE
Rust analyzer panics when used in Emacs: assertion failed: c.num == crate_map.len() as u32

### ISSUE THREAD

**Issue by joshualex** [rust-analyzer/rust-analyzer#11421]
**rust-analyzer version**: rust-analyzer db2a7087b 2021-12-13 stable

**rustc version**: rustc 1.58.1 (db9d1b20b 2022-01-20)

When opening a new project, Emacs fails to communicate with rust-analyzer, and I get a panic in the rust analyzer stderr:
```
thread '<unnamed>' panicked at 'assertion failed: c.num == crate_map.len() as u32', src/tools/rls/rls-analysis/src/lowering.rs:140:13
```

**Comment by Veykril** [comment]
`rc/tools/rls/rls-analysis/src/lowering.rs`: this is a panic coming from rls, not rust-analyzer. So for some reason your emacs seems to run rls instead of/with rust-analyzer

**Comment by joshualex** [comment]
Oh you're right... It probably remained there after I tried switching back and forth between rls and RA. However the fact remains that RA doesn't work for me. I'm trying to spot an error message or artifact I can attach here...

**Comment by joshualex** [comment]
I will open a new issue with more specific details. Thanks in the mean time
