### ISSUE TITLE
Setting rust-analyzer.onEnter breaks code completion

### ISSUE THREAD

**Issue by CleanCut** [rust-analyzer/rust-analyzer#11432]
**rust-analyzer version**: `rust-analyzer version: 0add6e95e 2021-12-20 stable`

**rustc version**: `rustc 1.58.1 (db9d1b20b 2022-01-20)`

Several months ago VS Code stopped reliably doing code completion on my high-end Mac hardware. At first it was subtle, but in recent months my code completion has basically been broken, unless I slowly. type. one. letter. at. a. time. Resuming normal typing speed at any time _mostly_ results in no code completion at all, though occasionally something shows up.

Then I chanced upon [this reddit thread](https://www.reddit.com/r/rust/comments/smksn4/comment/hvxjygd/?utm_source=reddit&utm_medium=web2x&context=3) and tried removing this from my `keybindings.json`:

```json
    {
        "key": "Enter",
        "command": "rust-analyzer.onEnter",
        "when": "editorTextFocus && !suggestWidgetVisible && editorLangId == rust"
    }
```

and EVERYTHING WORKS AGAIN!!!

I've had that setting in my config since I switched to VS Code somewhere between 1.5 and 2.5 years ago (or maybe it was when the feature was introduced and I saw it in a changelog? ...my memory is so fuzzy...), and I'll miss the feature--but I want code completion more. Until recent months, everything worked fine.  I don't know what's up, but it'd be nice to at least put a warning [on that setting](https://rust-analyzer.github.io/manual.html#on-enter), if it can't be fixed anyway.

**Comment by lnicola** [comment]
Well, there's a reason why it's disabled by default. I'll add a warning to the docs. By the way, we now also have some regex-based heuristics for comment continuation.

Do you have other extensions installed? What if you disable them and re-enable `onEnter`?

**Comment by jhgg** [comment]
> I slowly. type. one. letter. at. a. time. 

This... seems unrelated to the keybind. I'm not even sure how this would break autocomplete.

**Comment by CleanCut** [comment]
Bleh. After more testing, it's apparent that removing this setting didn't fix the problem. 😞 Sorry for the noise.
