### ISSUE TITLE
Action: Build x86_64-unknown-linux-gnu target with a lower version glibc?

### ISSUE THREAD

**Issue by jmjoy** [rust-analyzer/rust-analyzer#11434]
Yesterday I run vscode remote with rust-analyzer extension on a centos7 server, but the auto-downloaded rust-analyzer binary start failed, because the glibc version of centos7 is lower than ubuntu-20.04 used by github action.

I think it is better to build the binary using [`cross`](https://github.com/cross-rs/cross#supported-targets), which can guarantee the glibc version will not be too newer.

**Comment by lnicola** [comment]
I suggest using `rustup` to get a  server binary instead.

We could use `cross` (or even build in a CentOS 7 container), but the actions are already pretty complicated. I don't know how much complexity we want to pack in there.

**Comment by jmjoy** [comment]
> I suggest using `rustup` to get a server binary instead.
> 
> We could use `cross` (or even build in a CentOS 7 container), but the actions are already pretty complicated. I don't know how much complexity we want to pack in there.

But now rustup component rust-analyzer still nighlty.

**Comment by lnicola** [comment]
Yes, it's nightly, but it's (approximately, I slacked lately) the same code that's being shipped with the Code extension, only built on different infra. And you can use the nightly RA with the stable toolchain.

**Comment by jmjoy** [comment]
> Yes, it's nightly, but it's (approximately, I slacked lately) the same code that's being shipped with the Code extension, only built on different infra. It's marked as a preview and only available on nightly because of organizational reasons, not because it's less stable than what you get in Code. And you can use the nightly RA with the stable toolchain.

You are right, it's a good idea to use rustup to install rust-analyzer.

**Comment by lnicola** [comment]
Just because it's not clear: we usually bump RA in rustup after every release, so you only get stable RA versions, but not on Mondays.
