### ISSUE TITLE
Immovable generator syntax (static ||) not recognized

### ISSUE THREAD

**Issue by vorot93** [rust-analyzer/rust-analyzer#11448]
```
#![feature(generators)]

fn main() {
    let gen = static || {
        yield 123;
    };
}
```

```
Syntax Error: expected expression
Syntax Error: expected SEMICOLON
```

**rust-analyzer version**: 08348d79f 2022-02-10 nightly

**rustc version**: rustc 1.60.0-nightly (0c292c966 2022-02-08)

**Comment by Veykril** [comment]
Relevant code is here https://github.com/rust-analyzer/rust-analyzer/blob/08348d79fa3ccb2aeeea87e758dcd5f1614c7ad8/crates/parser/src/grammar/expressions/atom.rs#L245-L248

**Comment by bellau** [comment]
I think we can resolve the issue
