### ISSUE TITLE
Macro error with slog::record_static!

### ISSUE THREAD

**Issue by remoun** [rust-analyzer/rust-analyzer#11456]
Using [`slog::record_static!`](https://docs.rs/slog/latest/slog/macro.record_static.html) yields in an `unresolved-macro-call` error.

This seems different from #6835 in that the macro in question does not use `proc_macro_hack`

**rust-analyzer version**: ba3305480 2022-02-07 stable

**rustc version**: rustc 1.55.0-nightly (b41936b92 2021-07-20)

**Comment by remoun** [comment]
When I turned on RA logging, I notice a bunch of errors around macro parsing: `[WARN hir_expand::db] fail on macro_parse: (reason: UnresolvedProcMacro macro_call: #[derive(Debug, Display)]`

Pretty much the same error, repeated for many definitions.

**Comment by bjorn3** [comment]
That nightly version is several months old. We only support the latest nightly, latest beta and several stable releases. The proc macro abi is unstable and may have changed between the nightly you use and the final stable release in which case rust-analyzer can't expand it. Try updating your nightly or switching to stable.

**Comment by jonas-schievink** [comment]
`record_static!` works fine for me, on the current r-a master and Rust stable 1.58.1, so this looks indeed like an issue caused by using an unsupported Rust version
