### ISSUE TITLE
Outdated docs for `rust-analyzer.server.path`

### ISSUE THREAD

**Issue by nsunderland1** [rust-analyzer/rust-analyzer#11468]
The documentation for the `rust-analyzer.server.path` setting still mentions the `rust-analyzer.updates.channel` setting, which was removed in https://github.com/rust-analyzer/rust-analyzer/pull/11106. The provided link in the setting docs is dead.

![image](https://user-images.githubusercontent.com/16548079/153781572-0eeaa7e0-f5be-435c-84c9-53fbab1629b9.png)

**rust-analyzer version**: rust-analyzer version: ba3305480 2022-02-07 stable
**rustc version**: rustc 1.60.0-nightly (e7aca8959 2022-02-09)

**Comment by nsunderland1** [comment]
As an extra note on the side: neither the relevant PR nor the associated [changelog](https://rust-analyzer.github.io/thisweek/2021/12/27/changelog-109.html) make it super clear what the alternative to the `rust-analyzer.updates.channel` setting is, now that it's been removed.

**Comment by lnicola** [comment]
Just in case you missed it, you can switch back to the nightlies using this button here:

![image](https://user-images.githubusercontent.com/308347/155263415-932d7dbe-8389-46c1-9718-e8898c8a4613.png)
