### ISSUE TITLE
Request: Generics doc_test -- format with escape characters or quotes

### ISSUE THREAD

**Issue by KarlWithK** [rust-analyzer/rust-analyzer#11489]
Information:
**rust-analyzer version**: rust-analyzer fd3942eb6 2022-01-31 dev
**rustc version**: rustc 1.59.0-beta.8 (1945ce657 2022-02-12)
nvim with coc-rust-analyzer

Hey, so when I'm running a test that is implemented in a impl with generics like this:
```rust
impl<C: ColorSpace> Canvas<C>
where
    Rgb: From<C>,
{
/// ... implementations
}
```
And I try to run a doc_test, I am having to edit the command output as my shell does not handle `<` and `>`. I thought this was just my shell, but I tried it multiple shells and got the same error:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/31679231/154549136-24270e7a-64ee-473f-853d-da449990a42e.png">

When I replace the command from this:
```zsh
cargo test --doc --package curves_rs -- graphics::draw::Canvas<C>::draw_line --nocapture
```
to this:
```zsh
cargo test --doc --package curves_rs -- graphics::draw::Canvas\<C\>::draw_line --nocapture
```
The command works as expected. Is there any way to make sure redirection is handled by adding escape characters? 

Thanks so far for this awesome project!

**Comment by Veykril** [comment]
Would it also work if the path was put in quotes(`"`)? That would sound like the more appropriate fix here

**Comment by KarlWithK** [comment]
Yep, it did, that is a good solution.
