### ISSUE TITLE
cannot work due to `munmap_chunk(): invalid pointer`

### ISSUE THREAD

**Issue by YoshieraHuang** [rust-analyzer/rust-analyzer#11485]
**rust-analyzer version**: rust-analyzer version: 02904e99a 2022-02-14 stable

**rustc version**: 1.58.1 (db9d1b20b 2022-01-20)

VS code shows this error:
```
rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /home/yoshiera/dynx/Cargo.toml, cargo 1.58.0 (f01b232bc 2022-01-19): Failed to run `"cargo" "metadata" "--format-version" "1" "--manifest-path" "/home/yoshiera/dynx/Cargo.toml" "--filter-platform" "x86_64-unknown-linux-gnu"`: `cargo metadata` exited with an error: error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (signal: 6, SIGABRT: process abort signal)
  --- stderr
  munmap_chunk(): invalid pointer
```
How can i fix this?

**Comment by bjorn3** [comment]
This is not a rust-analyzer issue, but potentially a rustc one. Does running `echo | rustc - --crate-name ___ --print=file-names --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` fail too? Do you by any chance use a musl based distro rather than a glibc based one? If so you need to use the rustc for  `x86_64-unknown-linux-musl` instead.

**Comment by YoshieraHuang** [comment]
> This is not a rust-analyzer issue, but potentially a rustc one. Does running `echo | rustc - --crate-name ___ --print=file-names --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` fail too? Do you by any chance use a musl based distro rather than a glibc based one? If so you need to use the rustc for `x86_64-unknown-linux-musl` instead.

The command does not fail and show this:
```
___
lib___.rlib
lib___.so
lib___.so
lib___.a
lib___.so
/home/yoshiera/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
debug_assertions
proc_macro
target_arch="x86_64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_os="linux"
target_pointer_width="64"
target_vendor="unknown"
unix
```

**Comment by bjorn3** [comment]
Does `cargo metadata --format-version 1 --manifest-path /home/yoshiera/dynx/Cargo.toml --filter-platform x86_64-unknown-linux-gnu` fail?

**Comment by YoshieraHuang** [comment]
> 

Yes. It failed. Should I turn to the `cargo` project?

**Comment by YoshieraHuang** [comment]
> Does `cargo metadata --format-version 1 --manifest-path /home/yoshiera/dynx/Cargo.toml --filter-platform x86_64-unknown-linux-gnu` fail?

Yes. It failed. Should I turn to the cargo project?

**Comment by YoshieraHuang** [comment]
> Maybe?

Ok. Thank you. I will close this issue.

**Comment by YoshieraHuang** [comment]
The cache problem. Works well after cleaning the building cache.
