### ISSUE TITLE
Ability to disable the dead_code yellow underline in VSCode

### ISSUE THREAD

**Issue by xsrvmy** [rust-analyzer/rust-analyzer#11495]
In VSCode, dead code warning produces a lot of visual noise because they are underlined as a rustc warning, but also faded out. It would be nice to be able to disable the warning only in VSCode for this specific rule.
I should note that this is not some new idea. The ESLint extension has the option to change the warning level of any rule.

**Comment by jhgg** [comment]
I do the following in my config:

```
  "rust-analyzer.diagnostics.warningsAsHint": ["dead_code", "unused_variables"],
```

Reducing these to a hint will cause the unused variables to be faded, w/o the yellow underline.

**Comment by xsrvmy** [comment]
Oh I wasn't aware there is a option already.
Maybe this should be closed then
