### ISSUE TITLE
tokio::runtime::Runtime not found?

### ISSUE THREAD

**Issue by Dushistov** [rust-analyzer/rust-analyzer#1149]
For some reason it impossible find `runtime` and `Runtime` in `tokio::runtime::Runtime` (**Rust 2018**):

```Rust
fn main() {
    let mut runtime = tokio::runtime::Runtime::new().expect("Can not create runtime");
}
```

but it finds tokio in `~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.18/src/`,
but for some reason can not understand that `tokio::runtime` means `~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.18/src/runtime/mod.rs` ?

**Comment by flodiebold** [comment]
I'm pretty sure [this](
https://github.com/tokio-rs/tokio/blob/6e4945025cdc6f2b71d9b30aaa23c5517cca1504/tokio/src/lib.rs#L136) is why:
```rust
if_runtime! {
    extern crate tokio_executor;
    extern crate tokio_trace_core;
    pub mod executor;
    pub mod runtime;

    pub use executor::spawn;
    pub use runtime::run;
}
```
The definitions are behind a macro. We're beginning to have macro support, but currently don't support `item` matchers yet, which this macro uses.

**Comment by edwin0cheng** [comment]
`bors` just accidentally closed this issue, someone please reopen it again. 

Just tested, it still didn't work, I thing part of the reason is,  we are still not handling `cfg` correctly.

`if_runtime` is defined as :

```rust
macro_rules! if_runtime {
    ($($i:item)*) => ($(
        #[cfg(any(feature = "rt-full"))]
        $i
    )*)
}
```

On the other hand, there is an interesting error when i try this testcase :
```rust
macro_rules! if_runtime {
    ($($i:item)*) => ($(
        $i
    )*)
}


if_runtime! {
    mod runtime {
        pub struct Runtime;

        impl Runtime {
            pub fn new() -> Option<u32> {
                None
            }
        }
    }
}

fn main() {
    let r = runtime::Runtime::new().expect("Can not create runtime");

    let _ = r   /// suppress warning.
}
```
When hovering on `runtime`, it just show `loading...` and the traces didn't show anything useful.

May be related to #904 again?

**Comment by flodiebold** [comment]
We completely ignore `cfg`, so I don't think that's the reason. Are you sure it's not the problem fixed in #1164?

**Comment by edwin0cheng** [comment]
Just tested, that is not the problem, but seem like we didn't even implement handling macro file : :stuck_out_tongue_closed_eyes:

https://github.com/rust-analyzer/rust-analyzer/blob/403cd78baee7e9c2410d04ca0304575e7bbab16d/crates/ra_hir/src/ids.rs#L55

**Comment by edwin0cheng** [comment]
I just checked, it works properly now.
