### ISSUE TITLE
Document symbols includes Enum variants and functions, but workspace symbols do not

### ISSUE THREAD

**Issue by nph278** [rust-analyzer/rust-analyzer#11494]
**rust-analyzer version**: 2022-01-31

**rustc version**: 1.58.1

I am using Neovim's built-in LSP support with Telescope.nvim.

When in a cargo project, querying workspace symbols only seems to show Enums and Structs, while querying the document symbols for one file also shows enum variants and functions. I would expect that the workspace symbols would also include enum variants and functions.

**Comment by ChayimFriedman2** [comment]
IIRC this is the intended behavior to save time but you can customize it.
