### ISSUE TITLE
"Replace qualified path with use" using turbofish

### ISSUE THREAD

**Issue by mehmooda** [rust-analyzer/rust-analyzer#11505]
**rust-analyzer version**: 02904e99a 2022-02-14 stable

**rustc version**: rustc 1.58.1 (db9d1b20b 2022-01-20)

Using replace qualified path with use on:

```rust
std::mem::size_of::<String>()
```
results in:

```rust
use std::mem::size_of::<;
```

**Comment by Veykril** [comment]
Problematic part is this here https://github.com/rust-analyzer/rust-analyzer/blob/1d53f695f0408f47c5cce5cefa471eb0e86b0db7/crates/ide_assists/src/handlers/replace_qualified_name_with_use.rs#L90

We should be dropping all generic arg lists in the path
