### ISSUE TITLE
Supporting web-sys and other packages with generated bindings

### ISSUE THREAD

**Issue by chinedufn** [rust-analyzer/rust-analyzer#1150]
Auto generated bindings such as those in `web-sys` don't show up in auto complete.

So, for example: if you typed:

```rust
fn main () {
  web_sys::WebG
}
```

You'd expect the auto completion to suggest `WebGlRenderingContext`, but it doesn't suggest anything.

---

Here are some related issues in `intellij-rust` (I include them because my uneducated assumption is that `rust-analyzer` has the same challenge. If they're unrelated I'd be happy to remove the links!)

https://github.com/intellij-rust/intellij-rust/issues/1908
https://github.com/intellij-rust/intellij-rust/issues/3131

---

Cheers!

**Comment by edwin0cheng** [comment]
I think this issue related to following things `RA` is missing right now:
* `proc_macro` 
* allow register internal macro in ra_mbe , related `rustc` code : [link](https://github.com/rust-lang/rust/blob/a5dfdc589a1b44f01cb640cd0244372dcbbd6f37/src/libsyntax_ext/lib.rs#L72)
* Support `target/......../out` directory in `ra_vfs` ?! 
* how to handle `std::env` ? It is quite tricky..

**Comment by jrvidal** [comment]
Re: `env!(...)`/`std::env`... how would one even go about that? Does cargo expose that information in any way?

**Comment by matklad** [comment]
> how would one even go about that? 

We should have a white-list of environmental variables that are exposed to analyzer as an input:

```
#[salsa::input]
fn env_var(&self, crate: CrateId, name: SmolStr) -> SmolStr
```

Note that we have a `CrateId` parameter there as well: env vars could be different for various crates.

**Comment by chinedufn** [comment]
Are there any open issues related to some of the things that are necessary for this to be possible that I can follow? 
Thanks so much!

**Comment by lnicola** [comment]
@chinedufn I guess https://github.com/rust-analyzer/rust-analyzer/issues/1428 wouldn't hurt here.

**Comment by matklad** [comment]
Let's close this in favor of more specific #1964

**Comment by CGMossa** [comment]
This is still relevant, I think #4150 is the most recent issue that is related to this.
