### ISSUE TITLE
Setting to re-run proc-macros only after save, not every keypress

### ISSUE THREAD

**Issue by trevyn** [rust-analyzer/rust-analyzer#11515]
Since proc-macros are difficult and sometimes fragile, I'd like a setting somewhere between "disable completely" and "run after every keypress". I think a configuration setting to re-run only on save would be a nice balance.

**Comment by flodiebold** [comment]
This is not technicall possible. I would suggest reporting bugs for such fragile proc macros, and using the `rust-analyzer.procMacro.ignored` setting if necessary.

**Comment by trevyn** [comment]
Would you be open to a PR if I could make it work?

**Comment by flodiebold** [comment]
That's hard to answer. If it was done in a maintainable way sure, but I don't think it's possible without severe hacks or fundamental changes to the architecture, which would not be acceptable.

Maybe I just don't understand what behavior you would expect. If you have some code
```rust
#[some_macro]
fn foo() {
}
```
and type something in the function, what would happen?
