### ISSUE TITLE
Feature request: Find all references should hide the reference under the cursor

### ISSUE THREAD

**Issue by mrpink76** [rust-analyzer/rust-analyzer#11546]
In the screenshot below the cursor was on line 94 on the text "run_background_task"

1. I selected "References: Find all references" from the command palette (or using the shortcut).
2. (If there were only one caller of the method the cursor would have been moved to the call site, which I like!).
3. If there are more than one caller the image below is displayed. 

![Screenshot 2022-02-24 at 20 58 16](https://user-images.githubusercontent.com/7203676/155598276-8bfd6cd7-f2f9-41fe-b83c-f30ad5aeab6a.png)

What I feel is unnecessary is that the "function definition" is displayed in bottom right. 
Personally I use the functionality to find the usages of a function and thus are only interested in the callers, not the function definition ("self").

If this is a good default behavior then maybe it would be possible to add a configuration to filter the "self" reference?

I hope this is the correct place to send feature requests?

**Comment by mrpink76** [comment]
When I think about it, maybe this function works as it should, maybe I'm just missing a "find usages" function?

**Comment by Veykril** [comment]
The protocol allows to query references without declarations and we already have that implemented, so the lack is with the client VSCode not exposing a way to not include the declaration.

**Comment by mrpink76** [comment]
I will close this issue as it sounds like a vscode problem :)
