### ISSUE TITLE
MacOS VScode pre-release has not been updated in a about week

### ISSUE THREAD

**Issue by villem** [rust-analyzer/rust-analyzer#11542]
Hi,

There hasn't been a new pre-release after Feb 14. Am I just too impatient?

Here is the vscode details:
`Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0`

This what vscode shows in RA extension info

`More Info
Released on
10/02/2020, 10:24:28
Last updated
14/02/2022, 07:15:25
Identifier
matklad.rust-analyzer`

**Comment by bjorn3** [comment]
Should have been fixed yesterday: https://github.com/rust-analyzer/rust-analyzer/issues/11523#issuecomment-1047821462

**Comment by lnicola** [comment]
It was fixed, but last nightly didn't work because GitHub Actions got tired or something: https://github.com/rust-analyzer/rust-analyzer/actions/runs/1884679607/attempts/1.

**Comment by villem** [comment]
Great, I'll close this one when an update arrives.

**Comment by lnicola** [comment]
It's up: https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer.

**Comment by villem** [comment]
Updated fine! Thanks!
