### ISSUE TITLE
Associated constants aren't completed in pattern position

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#11555]
```rust
#[derive(PartialEq, Eq)]
struct Ty(u8);

impl Ty {
    const ABC: Self = Self(0);
}

fn f(t: Ty) {
    match t {
        Ty::$0
    }
}
```

This provides 0 completions, but I expected to see `ABC` here, since constants are valid in patterns.

**Comment by Veykril** [comment]
Now I wonder what made me think differently here, I could swear I tried this 🤔 https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide_completion/src/completions/pattern.rs#L158

**Comment by jonas-schievink** [comment]
Ah, you were kind of right – this only actually compiles if the struct has `#[derive(PartialEq, Eq)]` on it. I've updated the code above to include that.

**Comment by Veykril** [comment]
Ah right, that was probably it. So to do this properly we need to emit [StructuralPartialEq](https://doc.rust-lang.org/core/marker/trait.StructuralPartialEq.html) and [StructuralEq](https://doc.rust-lang.org/core/marker/trait.StructuralEq.html) as well so that we can check for these.

**Comment by jonas-schievink** [comment]
I think it's fine to always show the completion, since we never guarantee that a completion will actually compile. And if the user applies it, rustc will explain to add the right `#[derive]` already.

**Comment by hi-rustin** [comment]
I am working on this.
