### ISSUE TITLE
Macro Expansion fails

### ISSUE THREAD

**Issue by Lapz** [rust-analyzer/rust-analyzer#1155]
Whilst working on #1102 I've realised that the `parse_macro` always fails. I've tested this with the macros that we test and a few random ones. This is the relevant code :
```rust 
 fn parse_macro(db: &impl DefDatabase, macro_call_id: MacroCallId) -> Option<TreeArc<SourceFile>> {
    let loc = macro_call_id.loc(db);
    let macro_call = loc.ast_id.to_node(db);

    let (macro_arg, _) = macro_call.token_tree().and_then(mbe::ast_to_token_tree)?;

    log::debug!("macro call expansion {:?}", macro_arg);

    let macro_rules = db.macro_def(loc.def)?;

    log::debug!("macro expansions rules {:#?}", macro_rules);

    let tt = macro_rules.expand(&macro_arg);

    log::debug!("expanded macro {:#?}", tt);
    let tt = tt.ok()?;

    Some(mbe::token_tree_to_ast_item_list(&tt))
}
```
@matklad @edwin0cheng

**Comment by edwin0cheng** [comment]
May i know what is the actual macro you try to expand ?

**Comment by edwin0cheng** [comment]
So does it fail in the following line ?
```rust
let tt = macro_rules.expand(&macro_arg);
```

If so , what is the `macro_arg` values ? i.e, What is the arguments it tried to expand for ?

**Comment by edwin0cheng** [comment]
Just want to make sure the whole `hir` pipeline works, would you mind to try a trivial case ?  
For example :
```rust
macro_rules! foo {
    ($ i:ident) => (
        fn $i() -> usize { 0 }
    )
}
```

**Comment by Lapz** [comment]
The macro args corresponds to the def macro subtree not to the call subtree. It a bug on my side so I'll close this issue
