### ISSUE TITLE
Fields are not completed in union literals

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#11568]
```rust
union MyUnion {
    field: u8,
    otherfield: u32,
}

fn f() -> MyUnion {
    MyUnion {
        $0
    }
}
```

This completes nothing, I expected to see both `field` and `otherfield` there.

**Comment by Veykril** [comment]
This probably needs some special handling for `missing_fields` here https://github.com/rust-analyzer/rust-analyzer/blob/bc2ce4c655852e37822031cd31e8625597b1c85a/crates/ide_completion/src/completions/record.rs#L12-L43

**Comment by hi-rustin** [comment]
I am working on this.

**Comment by m0rg-dev** [comment]
Turns out we don't complete fields for tuple structs or enum variants either. I'm going to go ahead and work on unifying the struct and enum completion logic, then it should be easy to extend that to unions.
