### ISSUE TITLE
`test_runnables_project` dead lock in Windows with rustc 1.34

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#1156]
In recent commit  (546d9be at least but not sure), In Windows machine, running `cargo test` seem to be dead lock in `test_runnables_project` .

I tried to step through all code in debugger, here are the symptoms:
* The `RawMessage` between server and test instance are very slow.
* When `shutdown` is reply and the main thread are joining, it just dead lock.

Note that as @matklad mention before, we explicitly don't test rust-analyzer on windows in hope that it is cross-platform by construction. (https://github.com/rust-analyzer/rust-analyzer/issues/819). So i marked the issue here just for the record.

**Comment by jrvidal** [comment]
I've reproduced it on a Windows VM. The deadlock seems to occur when trying to drop the Vfs:
https://github.com/rust-analyzer/rust-analyzer/blob/d3afb1b3782683c3e800b38b4c24b7581918fb7f/crates/ra_lsp_server/src/main_loop.rs#L106-L109

**Comment by matklad** [comment]
Looking into this! See also https://github.com/rust-analyzer/rust-analyzer/pull/1158

I wonder if we should just switch our CI to docerized azure pipelines, which perhaps can have fast windows builds?

**Comment by edwin0cheng** [comment]
> I wonder if we should just switch our CI to docerized azure pipelines, which perhaps can have fast windows builds?

It depends on your current workloads. : ), But in my opinion, it is not a must right now.
And I just wonder why it affect Windows only, the deadlock itself should be `cross-platform`, right?

**Comment by matklad** [comment]
>And I just wonder why it affect Windows only

It is related to virtual file system, and vfs is basically a minefield of platform-specific behavior ;(

Good news is that just properly updating vfs to the latest version seems to fix the issue.

Could you check that the current master works?

**Comment by edwin0cheng** [comment]
Yeah, it works now. Thanks.

**Comment by matklad** [comment]
I guess that means that testing in ra_vfs works, as long as I actually publish the right code from the master branch, and not the random stuff that was laying around :D
