### ISSUE TITLE
Workspace symbols not finding all symbols with same name

### ISSUE THREAD

**Issue by JosephTLyons** [rust-analyzer/rust-analyzer#11575]
**rust-analyzer version**: d6ed146a1 2022-02-22 stable

**rustc version**: rustc 1.59.0 (9d1b2106e 2022-02-23)

I'm looking for the `signature` function, so I type it in, but only the `Signature` struct is found:

![SCR-20220227-fcr](https://user-images.githubusercontent.com/19867440/155889951-ec65435c-adfd-464f-90b1-0d4774e9f894.jpeg)

If I type in additional text that isn't in the `Signature` struct name, other results appear, but I'm not able to get to the function named `signature`, since it doesn't have any extra text to match on:

![SCR-20220227-fdn](https://user-images.githubusercontent.com/19867440/155889957-cafc6879-963d-4615-ac84-7db5af9df4c2.jpeg)

The project I'm using is [Nushell](https://github.com/nushell/nushell)

**Comment by flodiebold** [comment]
The `#` trick does not work in VSCode anymore. Quoting the manual:
> Note that filtering does not currently work in VSCode due to the editor never sending the special symbols to the language server. Instead, you can configure the filtering via the rust-analyzer.workspace.symbol.search.scope and rust-analyzer.workspace.symbol.search.kind settings.

**Comment by JosephTLyons** [comment]
I guess I'm a little confused.  Im currently a beta tester for a new text editor that just added a bunch of Rust support via rust-analyzer and it suffers from the same exact issue of not being able to find all symbols of with same name as others, so I would think it's not a VS Code-specific issue, I just reported it using that editor.  I could be misunderstanding this though..

**Comment by flodiebold** [comment]
The workspace symbol search by default only searches for types, not functions. In most editors you can append `#` to widen the search:
![Peek 2022-02-27 19-00](https://user-images.githubusercontent.com/906069/155894016-76b0ef93-7176-429d-a2c8-e5985aec458a.gif)
But you can also configure it to search in all symbols by default using the settings mentioned above.

**Comment by JosephTLyons** [comment]
Ah ok, I understand now.  My apologies for misinterpreting it and thanks for explaining it to me.  I suppose this should just be closed then.
