### ISSUE TITLE
Value of string constant is not displayed correctly when hovered over

### ISSUE THREAD

**Issue by SeekingBlues** [rust-analyzer/rust-analyzer#11582]
**rust-analyzer version**: `rust-analyzer 4e72700e3 2022-02-28 stable`

**rustc version**: `rustc 1.59.0 (9d1b2106e 2022-02-23)`

**relevant settings**: None

<img width="415" src="https://user-images.githubusercontent.com/51911626/155995100-50505f93-9d6b-4ea8-af78-f3dc8a725352.png">

The definition incorrectly shows that `HELLO_WORLD` is an empty string.

**Comment by tysg** [comment]
Currently when lowering from a String Literal AST to HIR, we discard the content and replace it with empty strings. #11595 fixes that by bringing over the literal string content to HIR. However this may cause r-a to consume more memory.
