### ISSUE TITLE
Unsolved import when using the derivative crate

### ISSUE THREAD

**Issue by ChrisGreenaway** [rust-analyzer/rust-analyzer#11581]
**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
v0.2.956

**rustc version**: (eg. output of `rustc -V`)
rustc 1.59.0 (9d1b2106e 2022-02-23)

**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
Using VS Code

The following project causes an "unresolved import" on the first line of `main.rs`:

```
Cargo.toml
==========
[package]
name = "scratch"
version = "0.1.0"
edition = "2021"

[dependencies]
derivative = "2.2.0"


main.rs
=======
use derivative::Derivative;

#[derive(Derivative)]
#[derivative(Debug)]
struct Test;

fn main() {
    let value = Test;
    println!("{value:?}");
}
```

It compiles and runs fine.

**Comment by lnicola** [comment]
Duplicate of #7459. You can try setting `rust-analyzer.cargo.unsetTest`.

**Comment by ChrisGreenaway** [comment]
Setting unsetTest, as recommended in #7459, solved this. Thanks.
