### ISSUE TITLE
Question: What are the .rast files for expect tests?

### ISSUE THREAD

**Issue by ChayimFriedman2** [rust-analyzer/rust-analyzer#11597]
The parser tests has a corresponding of `.rast` file for some of the tests. Some only have `.rs` and `.txt`. The `cargo test` command seems to ignore them. What is their role? Are they remains from the past? Can they be safely deleted? If not, how can they be updated automatically (`UPDATE_EXPECT=1` does not help)?

**Comment by flodiebold** [comment]
From reading the source code, it seems like they're used in the validation tests, but apparently the other tests use `.txt`. They may indeed be remains from the past; looks like they became useless in commit b360ea91f2ad89a4d22e7adb4dc3cad54eeb1159. Maybe we should remove the txt files instead and make the tests use the rast files; I think the advantage is that we have some syntax highlighting for them in VSCode.

**Comment by Veykril** [comment]
cc @matklad it might be helpful to clarify the difference between the txt and rast outputs somewhere

**Comment by ChayimFriedman2** [comment]
Thanks! I indeed think it would be beneficial if we'd used them and not `.txt` files.

**Comment by matklad** [comment]
Excellent catch @ChayimFriedman2, thanks! Fixed in #11632
