### ISSUE TITLE
[feature request] hidden type display

### ISSUE THREAD

**Issue by miffyrcee** [rust-analyzer/rust-analyzer#11608]
as the picture shows
![image](https://user-images.githubusercontent.com/43992258/156594622-98f8d72f-15d2-4861-821f-7c1b83a25fc5.png)

```
let p1: Point<i32, f64> = Point { x: 5, y: 10.4 };
let p2: Point<&str, char> = Point { x: "Hello", y: 'C' };
```
Please, can I hide the greyed out type inference, it's annoying me. I wonder if it is possible to use a floating window to display when my mouse or cursor is on the current variable.

**Comment by lnicola** [comment]
We hide these in some places, but I'd argue they might be useful in cases like `Point { x: f(), y: g() }` where you might not know what `f` and `g` return.

**Comment by Veykril** [comment]
Do you mean disabling them in general or only in specific cases? Overall disabling for type inference inlay hints can be toggled via the `rust-analyzer.inlayHints.typeHints` setting.

**Comment by miffyrcee** [comment]
> Do you mean disabling them in general or only in specific cases? Overall disabling for type inference inlay hints can be toggled via the `rust-analyzer.inlayHints.typeHints` setting.
