### ISSUE TITLE
[Question] Usage as a library

### ISSUE THREAD

**Issue by setzer22** [rust-analyzer/rust-analyzer#11615]
(Note: I looked around but couldn't find a better place to ask questions about rust-analyzer.)

I need to build an application to parse Rust crates and extract some information about them (e.g. how many types implement a certain trait). Seeing what it's capable of doing as an IDE plugin, Rust analyzer looks like the perfect fit for my use case.

The user guide states (emphasis mine):
> At its core, rust-analyzer is a **library** for semantic analysis of Rust code as it changes over time

However, I couldn't find any reference about whether this is a supported use case of rust-analyzer. Do you think that would work? Or will I face too many issues when trying to use RA as a standalone library?

**Comment by ChayimFriedman2** [comment]
I think you can use rust-analyzer for that, but keep in mind that while rust-analyzer can be used as a library, it doesn't really support this well. Breaking changes are done regulary, API is not stable and sometimes not well-documented, etc.. This was a goal at the start, but now...

**Comment by flodiebold** [comment]
> This was a goal at the start, but now...

It's still a goal and guides the architecture, it's just that making the library usable by other projects is not a priority right now.

There are some projects using RA as a library, but you will have to pin the version or handle regular breaking changes. Also, the analysis regarding types and traits is not 100% perfect yet. It's easier if you're just looking for impls, but then you could probably also do that with rustdoc's json output.

**Comment by setzer22** [comment]
Thanks for the replies! The idea to parse the output or rustdoc looks promising.

@flodiebold  Could you point me to some other projects you mentioned using RA as a library? That would help me get a good idea of the kind of work involved.

**Comment by flodiebold** [comment]
You can look up dependents on crates.io: https://crates.io/crates/ra_ap_ide/reverse_dependencies and https://crates.io/crates/ra_ap_rust-analyzer/reverse_dependencies for example.

**Comment by flodiebold** [comment]
Let's close this since the question was answered.
