### ISSUE TITLE
Pre-built binaries need to invoke rustc

### ISSUE THREAD

**Issue by joshcangit** [rust-analyzer/rust-analyzer#11618]
The installation instructions were kind of wrong.
For the downloaded LSP binary, I needed to use `rustc` to run it.

```
gunzip rust-analyzer-x86_64-unknown-linux-musl.gz
mv rust-analyzer-x86_64-unknown-linux-musl.gz rust-analyzer
rustc rust-analyzer --version
```

But if I build it, then that can run on it's own. No need to invoke `rustc`.

```
git clone https://github.com/rust-analyzer/rust-analyzer.git
(cd rust-analyzer && cargo xtask install --server)
rust-analyzer --version
```

**Comment by bjorn3** [comment]
> rustc rust-analyzer --version

This doesn't invoke rust-analyzer. It invokes rustc with the option to print it's version. It ignores the rust-analyzer argument as `--version` takes precedence. Why do you think you need to prefix `rustc`?

**Comment by lnicola** [comment]
Did you  miss a `chmod +x rust-analyzer`?

**Comment by joshcangit** [comment]
> Did you miss a `chmod +x rust-analyzer`?

No, I did not. I've just checked it again.
If not invoking `rustc`, I get this error.
```
bash: ./rust-analyzer: No such file or directory
```

**Comment by bjorn3** [comment]
The executable is likely called rust-analyzer-x86_64-unknown-linux-musl.

**Comment by flodiebold** [comment]
It doesn't look like you're following the instructions in the manual. You wrote
```
gunzip rust-analyzer-x86_64-unknown-linux-musl.gz
mv rust-analyzer-x86_64-unknown-linux-musl.gz rust-analyzer
```
which means you're moving the original gz file to `rust-analyzer`. That's not going to work.

**Comment by joshcangit** [comment]
Like I've said, it doesn't matter if I rename it.
I still get the same error.
```
bash: ./rust-analyzer-aarch64-unknown-linux-gnu: No such file or directory
```

**Comment by bjorn3** [comment]
What does `ls` show?

**Comment by joshcangit** [comment]
Nevermind, I figured it out.
I just use the binary with the same toolchain or build target as my system.
