### ISSUE TITLE
Feature Request: Rename assist for modules

### ISSUE THREAD

**Issue by nurmohammed840** [rust-analyzer/rust-analyzer#11612]
It would be nice, If we could rename a module through assist, For example:

```rust
// src/foo.rs
mod foo; // renamed with `bar`
```
Would transform into.
```rust
// src/foo.rs -> src/bar.rs   |   src/foo/mod.rs -> src/bar/mod.rs
mod bar;
```

Although, renaming module  feature is supported,
But there should be a assist for that.

**Comment by bjorn3** [comment]
Renaming the `foo` symbol using f2 or "rename symbol" will rename the file too.

**Comment by nurmohammed840** [comment]
Thanks @[bjorn3](https://github.com/bjorn3), I didn't know that, So closing...
