### ISSUE TITLE
Update debug snapshots

### ISSUE THREAD

**Issue by Lapz** [rust-analyzer/rust-analyzer#1162]
The debug formatting in rust has recently changed and since we use `assert_debug_snapshot_matches` a lot of the snapshots need to be changed

**Comment by edwin0cheng** [comment]
OH... would you mind to tell me what rustc version you are using ?

**Comment by Lapz** [comment]
Stable

**Comment by edwin0cheng** [comment]
Yeah, i remember they talked about it in Zulip : https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/.5Bsolved.5D.20rust-analyzer.3A.20snap.20update.3F

**Comment by matklad** [comment]
Ouch. I guess we'll change that once the new formatting is stable? I personally use stable for rust-analyzer :)

**Comment by Lapz** [comment]
Done in #1321
