### ISSUE TITLE
Buggy diagnostics

### ISSUE THREAD

**Issue by FooqX** [rust-analyzer/rust-analyzer#11626]
**rust-analyzer version**: f1f9163b2 2022-03-05 nightly, but the same happens in release version too

**rustc version**: rustc 1.59.0 (9d1b2106e 2022-02-23)

Buggy and super annoying diagnostics, please fix
https://streamable.com/ucbk1q

**Comment by bjorn3** [comment]
The errors that reset when you save the file are emitted by rustc and not rust-analyzer. It is only possible to run rustc when saving as rustc can only read the source from the disk and not from the memory of the editor, unlike rust-analyzer. See https://github.com/rust-analyzer/rust-analyzer/issues/1471. If that is the only issue you have I think this can be closed as duplicate.

**Comment by lnicola** [comment]
In addition (not sure whether you're also trying to show this in the recording), `fn main() { println!("hello") }` is valid Rust code.
