### ISSUE TITLE
Group "Generate ..." assists for enums

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#11636]
This is a bit to noisy:

![image](https://user-images.githubusercontent.com/1711539/156931014-d8ff9a61-0d8b-49ab-84ba-6aa918fade43.png)

Let's make it a single "Generate `is_`, `as_`, `try_into_`.". 

Look how generate getter/setter work to get an idea of how to implement this:

https://github.com/rust-analyzer/rust-analyzer/blob/5b9e46b960c37f04a26742c186e0a26b7bc131b3/crates/ide_assists/src/handlers/generate_setter.rs#L49

**Comment by jakevossen5** [comment]
I'll take a crack at this - will be my first issue
