### ISSUE TITLE
Filter out or deprioritize already-imported names when completing in a `use`-tree

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#11640]
```rust
mod module {
    pub struct A;
    pub struct B;
    pub struct C;
}

use module::{A, B, $0};
```

This currently completes, `A`, `B`, `C`, and `self`. Since `A` and `B` are already imported, I think it would make sense to filter those out, or at least give them a low priority (they are currently at the top of the list).

**Comment by feniljain** [comment]
Hey, I was having a look at the issue and it seems the low priority is already present, I get this while completing:

<img width="566" alt="Screenshot 2022-04-09 at 13 32 34" src="https://user-images.githubusercontent.com/49019259/162562699-08d1aa10-5077-4b4f-82c5-9b710b5a15a7.png">

**Comment by lnicola** [comment]
I thought we should filter them out, but maybe `use foo::{Bar, Bar as Baz}` can be useful at times?

**Comment by feniljain** [comment]
This maybe kind of off-topic, but when do importing them twice, once with original name and next with an alias help?

**Comment by lnicola** [comment]
Not very often. But a crate might want to implement some trait for two different versions of a dependency (imagine `serde_10` and `serde_20`, this is quite common), but also use the latest version in internal code.

So you could presumably do

```rust
#[cfg(feature = "with-serde-10")]
use serde_10::Serialize as Serialize_10;
#[cfg(feature = "with-serde-20")]
use serde_20::Serialize as Serialize_20;
use serde::Serialize;
```

I can imagine doing something similar on a single `use` statement.

But yeah, these cases are pretty far-fetched.

**Comment by Veykril** [comment]
Also sometimes you have two different things clash names in general so you need to alias one of them there as well

**Comment by feniljain** [comment]
Keeping in mind these explanations, maybe we should not filter these out?

**Comment by Veykril** [comment]
Ye I don't think we should filter them, but deprioritizing seems fine.

**Comment by feniljain** [comment]
Cool then, will leave it upto you guys to close it 😄
Thnx!

**Comment by lnicola** [comment]
> Also sometimes you have two different things clash names in general so you need to alias one of them there as well

But in that case you won't import the same thing twice, right?

> Ye I don't think we should filter them, but deprioritizing seems fine.

Can we close this, then?

**Comment by Veykril** [comment]
> Can we close this, then?

Well, the depriorization isn't really implemented afaik. This might just have changed ordering due to changes in how we emit keywords vs resolutions.
