### ISSUE TITLE
Can't rename variable when using yew framework and macros on methods

### ISSUE THREAD

**Issue by dodalovic** [rust-analyzer/rust-analyzer#11650]
https://user-images.githubusercontent.com/6358061/157106666-dd4be727-392a-43d7-9b49-9efd79dd0adc.mp4

**Comment by Veykril** [comment]
I assume this is a dupe of https://github.com/rust-analyzer/rust-analyzer/issues/11272,  that is the attribute causes us to not associate things properly.
