### ISSUE TITLE
Binary is not being patched on NixOS in the latest nightly

### ISSUE THREAD

**Issue by cab404** [rust-analyzer/rust-analyzer#11695]
@lnicola This is cursed, and should never have been accepted:
https://github.com/rust-analyzer/rust-analyzer/blob/0182f7451600e1700873549c324f7d13585547f4/editors/code/src/main.ts#L272
```
cat /etc/os-release
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="22.05.20220305.062a0c5"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID="nixos"
LOGO="nix-snowflake"
NAME="NixOS"
PRETTY_NAME="NixOS 22.05 (Quokka)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="22.05 (Quokka)"
VERSION_CODENAME="quokka"
```

This is a serious regression in nightly and it's important to fix it before the next release.
@matklad, please take a look.

**Comment by lnicola** [comment]
What do you mean by regression? That code has been like this for almost two and a half years.

**Comment by cab404** [comment]
IIRC NixOS detection were at first detecting /etc/nixos folder (which is cursed as well)

**Comment by lnicola** [comment]
Yeah, but that was 15 months ago. Maybe you updated your distro (is that a thing on Nix?) and they added this quotes recently.

**Comment by cab404** [comment]
That's probable
```ts
const idString = contents.split('\n').find((a) => a.startsWith("ID="))
return idString?.toLowerCase()?.indexOf("nixos") !== -1;
```
should probably work?

**Comment by lnicola** [comment]
We could also look for the three ways of spelling it. Is that file even a shell script?

**Comment by cab404** [comment]
It looks like it's a bit simpler than that https://www.linux.org/docs/man5/os-release.html

**Comment by cab404** [comment]
I've tested it with the patch I suggested above — detection works correctly with it.
