### ISSUE TITLE
RA memory usage

### ISSUE THREAD

**Issue by Rose1917** [rust-analyzer/rust-analyzer#11697]
Hi, RA developers and users.
When I used to use RA on my own computer, I didn't care about the memory use of RA, but recently, when I tried to run some simple rust programs on the server (only 2G RAM), I found that the server became very slow.

After some simple detection, I found everytime I open a rust file, a new RA instance will be created, even I open the same source file. Can this situation be changed?  Or if there is anything wrong with my configuration?
I use vim + vundle + rust.vim.

here is my vimrc snippets.
![image](https://user-images.githubusercontent.com/49433992/158046148-06b48f8b-342e-433a-a902-122e6f601791.png)
![image](https://user-images.githubusercontent.com/49433992/158046157-e086a188-26d1-400e-a91a-c255b2f14ef3.png)

this is the pstree after reopened the same source file.
![image](https://user-images.githubusercontent.com/49433992/158046175-750ee391-13f5-4dcb-b560-fa2bb3fbd381.png)

**Comment by lnicola** [comment]
I don't see Vim in your screenshot, does the Python LSP plugin keep running until you close it? Also, are you using a standard project, or plain `.rs` files?

We recommend other Vim plugins in [the manual](https://rust-analyzer.github.io/manual.html#vimneovim), but those choices come from users. I haven't used Vim in many years, so I don't know how well `rust.vim` does. In any case, this is a client (editor) bug, we can't do anything about it.

**Comment by Rose1917** [comment]
> I don't see Vim in your screenshot, does the Python LSP plugin keep running until you close it? Also, are you using a standard project, or plain `.rs` files?
> 
> ~We recommend other Vim plugins in [the manual](https://rust-analyzer.github.io/manual.html#vimneovim), but those choices come from users. I haven't used Vim in many years, so I don't know how well `rust.vim` does.~ Never mind, I just noticed YCM. In any case, this is a client (editor) bug, we can't do anything about it.

Thanks for your kind reply:). Python LSP works fine. For me, I just want to know if this situation is normal. Now I will try to reinstall the plugins, I use too many vim plugins...

**Comment by lnicola** [comment]
> Python LSP works fine.

I meant that YCM uses a Python helper to implement LSP. So if you close Vim, but that Python process is still running, it's a YCM problem. I assume you closed Vim because the Python process got reparented to `systemd`.

**Comment by Rose1917** [comment]
> > Python LSP works fine.
> 
> I meant that YCM uses a Python helper to implement LSP. So if you close Vim, but that Python process is still running, it's a YCM problem. I assume you closed Vim because the Python process got reparented to `systemd`.
> 
> Maybe you can give NeoVim a try? It's nicer, but keeping track of the plugins got too hard for me.

Well, the problem has been solved by removing the nerdtree autocmd. 
![image](https://user-images.githubusercontent.com/49433992/158067996-db76499f-9ac6-4205-9049-1fb1865d8be1.png)

I guess the reason is everytime i close the .rs file, the nerd tree tab is still there, and this affect the ycm workflow...

**Comment by Rose1917** [comment]
But I am still curious why only rust is affected...😥
