### ISSUE TITLE
Remove RwLock from ServerWorld

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1169]
I've noticed that we have an `RwLock` around Vfs in server world and that doesn't make much sense: we must gurantee that all snapshots are dead when we change the world.

I guess, we should replace a mutex with `Arc::get_mut().unwrap()`?

This needs closer investigation though.

**Comment by kiljacken** [comment]
A cursory look at this: We do send `WorldSnapshot`s to a worker threads in `PoolDispatcher::on`, so we'd need some sort of cancellation of pending work in the pool to be able to achieve this.

**Comment by matklad** [comment]
We have that via salsa: after salsa modification requests completes, we guarantee that all pending requests are cancelled. Internally, salsa sets a flag *before* actual modification, then all existing salsa's snapshot notice the flag (on the next query) and panic with `Cancelled`, then the modification thread notices that it has a single salsa left, and proceeds with modification. 


We definitely should simplify this, there must be a *single* global lock, which encompases all states. The deep problem, however, is that salsa has it's internal lock, which we ideally want to expose and control ourselves... So, yeah, this E-needs-design, across three components vfs, salsa and the server itself.
