### ISSUE TITLE
AST is incorrect for struct def

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#117]
Hm, looks like the ast is wrong: the structure should be this:

```
STRUCT_DEF
   NAMED_FIELD_LIST
      NAMED_FIELD
```

So, there should be a `NamedFieldList` between `NamedFieldDef` and `StructDef`, and the same for `PosFieldDef`. So, you need to tweak the ast section of `grammar.ron`.

Perhaps its best to add some kind of 

```
enum StructFlavor {
    Tuple(PosFieldList),
    Named(NamedFieldList),
    Unit,
}
```

enum? I think it needs to be implemented manually, in the ast/mod.rs file.

_Originally posted by @matklad in https://github.com/rust-analyzer/rust-analyzer/pull/110#issuecomment-428509963_

**Comment by flodiebold** [comment]
I'm currently doing this since I need it for struct types.

**Comment by flodiebold** [comment]
Looks like this didn't get closed automatically, but my commit is merged now.
