### ISSUE TITLE
rust-analyzer crashes on startup

### ISSUE THREAD

**Issue by cjhopman** [rust-analyzer/rust-analyzer#11709]
This is a serious regression in nightly and it's important to fix it before the next release.
@matklad, please take a look.

https://github.com/rust-analyzer/rust-analyzer/commit/ce4b61003d8eb5383c4e759d919cdc72a137bc11 introduced a startup crash if the /etc/os-release file exists and doesn't contain a line that starts with `ID=`

For example, a file with the contents:
```
VERSION_ID=11
```

Will hit a crash (because isNixOs() incorrectly returns true and then it tries to run nix-build to patch the elf file).

idk typescript or I'd send a fix myself, but I confirmed that that is almost certainly the problem in this [repl](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBBCcQQ0MwAUVWDEQC0gADVHBQGNJ3KAALygABEAAkYNAMOB4GRonzFBTBPB3AERcwABS0+mM9ysygc9wASmCKhwzQ8ZC8iHFzmB7BoXzcZmY7AYzEg-Fg0HUiQ58D0Ii8fLpDKZgj5SWxfPADlQAHJhAA5SASPlBFQAeS+ZHegmdWkgR1QjgUrmkeFATjNOmGWH0KAQiGhwkuNok4uiIgMHGxCyYrA4PCCJWSXFg9UarZjFFWycESp1+XG8DlHi8AG9FCUSqgyMWV2ud2jKTQKQptsJeQADRQAYlAxCQ1aQdcUAA0AJIAEW5AEYP6vdyVTwBuH9fxldJuGIDcK15Q8UVQQQAkEBZ5CVSMAB1OEjHUAmSDJuCVFUdR5AA+MR4LzMhYPAXYlT5N9uT5HUdUA38SicVB8S8CgwIgzhmAAfgCdBnngKQyAAYQYTNp34nC1mTZJqM4cd4CDAiAEJuV5UoPyYtcAF9RlQDRQG3ZjWPYnEGGgTMdJKXTFDs6VGlleVFSVIQxwnKcGKAA)

**Comment by cjhopman** [comment]
@cab404

**Comment by cab404** [comment]
I am sorry :pray: 
I guess it will be okay to revert the change altogether

**Comment by lnicola** [comment]
@cjhopman just wondering, which distro is that?

**Comment by cjhopman** [comment]
@lnicola it's mac (which normally doesn't have a /etc/os-release), to work around a libdnf 
bug/behavior (https://github.com/rpm-software-management/libdnf/issues/1221).
