### ISSUE TITLE
How can rust-analyzer be made more performant?

### ISSUE THREAD

**Issue by Milo123459** [rust-analyzer/rust-analyzer#11719]
Hey! 

I want to contribute to rust-analyzer and was wondering how *theoretically* speaking I / other contributors could make rust-analyzer more performant. For example, using less memory.

**Comment by lnicola** [comment]
There's some discussion in https://github.com/rust-analyzer/rust-analyzer/issues/11325, but I don't think there's an easy way to make it use less memory.

**Comment by lnicola** [comment]
Closing, since this isn't really useful as-is.
