### ISSUE TITLE
server panicked: mismatched kinds in substitution

### ISSUE THREAD

**Issue by umanwizard** [rust-analyzer/rust-analyzer#11717]
**rust-analyzer version**: rust-analyzer 88ade4203 2022-03-15 dev

**rustc version**: rustc 1.59.0 (9d1b2106e 2022-02-23)

**relevant settings**: using emacs and lsp-mode.

To reproduce:
1. Check out https://github.com/MaterializeInc/materialize at commit 10db3265f2628cfae1fcc534c8fa40cf841e2eda
2. Navigate to src/dataflow-types/src/types.rs, line 146 (`pub id: GlobalId`) and put the cursor on `id`.
3. Find all references.

LSP will output `server panicked: mismatched kinds in substitution`.

**Comment by Veykril** [comment]
cc https://github.com/rust-analyzer/rust-analyzer/pull/11688#issuecomment-1066824954

**Comment by HKalbasi** [comment]
Can you try #11718 ?

**Comment by umanwizard** [comment]
The repro instructions here should be specific enough that anyone can try it.

I'm not able to do so now, but will try to remember to do so later tonight if nobody else gets around to it before I do.

**Comment by lnicola** [comment]
This seems to work now, please reopen if not:

![image](https://user-images.githubusercontent.com/308347/158580511-4ffa8ef1-aa33-4f0a-b28d-32eb8fca9752.png)
