### ISSUE TITLE
error: When the function argument uses the #[cfg(test)] macro

### ISSUE THREAD

**Issue by BaymaxHWY** [rust-analyzer/rust-analyzer#11723]
this is rust-analyzer show the error
<img width="691" alt="image" src="https://user-images.githubusercontent.com/20529584/158544339-588e2028-8278-4add-b36a-735fc455c480.png">
this is this function declaration
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/20529584/158544822-2450e4a2-e792-4c0e-a732-2d1ea8504e75.png">

but `cargo build` and `cargon run` can compile and run this code, use the lldb debug also no problem. 

**rust-analyzer version**: 5e8515870 2022-03-14 stable

**rustc version**: 1.60.0-nightly (5e57faa78 2022-01-19)

**editor**: VSCode(MacOS)

**Comment by bjorn3** [comment]
Rust-analyzer enables `cfg(test)` by default. Otherwise ide features wouldn't work in tests. You can use `rust-analyzer.cargo.unsetTest` to unset cfg(test) for specific crates.

**Comment by BaymaxHWY** [comment]
It's normal now, thanks!
