### ISSUE TITLE
Add assist for #[test] on fn

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#1173]
In following along with [this tutorial](https://bodil.lol/parser-combinators) I had to write a lot of test functions. It would be nice to have an assist that adds `#[test]` to functions. I imagine it would work similarly to the assist that adds derive.

**Comment by bjorn3** [comment]
Link gives 404 for me.

**Comment by matklad** [comment]
@kjeremy we have tfn snippet for this purpose. I feel snippet works better thanassist here, because you know you are writing test function from the start

**Comment by kjeremy** [comment]
Ah missed the snippet thanks.
