### ISSUE TITLE
Inlay hints highlighted 

### ISSUE THREAD

**Issue by YounessBird** [rust-analyzer/rust-analyzer#11733]
First of all, massive thanks for creating this tool. 
I have been using rust analyzer's "Inlay hints" for quite a while and I noticed yesterday that this feature is now somehow highlighted in my code. I thought maybe it was an automatic update, so I tried previous version of rust analyser but I still could see the highlight, I have also tried the options in the settings, and that didn't work either.

I am using VsCode, version: 1.65.2. 
here is a screenshot of what the highlight looks like 
![rust-analyzer](https://user-images.githubusercontent.com/67457600/158689262-acf85490-515a-4cec-b16e-473d4ecf26e0.png)

Please let me know if there are any more information required.

**Comment by lnicola** [comment]
This is the styling of the native inlay hints (released this week, see https://rust-analyzer.github.io/thisweek/2022/03/14/changelog-120.html). They can be configured, though.

But never mind the styling, what happened with the function argument there?

**Comment by bayedieng** [comment]
How to revert to making the inlay transparent like it used to?

**Comment by YounessBird** [comment]
@lnicola 

>  what happened with the function argument there?

I have only noticed that after I took the screenshot, I also couldn't reproduce whatever glitch that was. Maybe it's worth noting though, that at least in my case I have noticed that the `inlay hints` take longer now to render in my VsCode for whatever reason.
I also couldn't find an option to disable the inlay hints background colour, maybe because of this [merged pull request](https://github.com/rust-analyzer/rust-analyzer/pull/11708) it says there that: 

 ```
 "rust_analyzer.inlayHints.foreground.typeHints": "#fdb6fdf0",
  "rust_analyzer.inlayHints.foreground.paramHints": "#fdb6fdf0",
  "rust_analyzer.inlayHints.background.chainingHints": "#6b0c0c81"
```
are now customized using native VSCode settings instead of rust-analyzer-specific ones. 
And that possibly there is no equivalent for the chainingHints color available in VScode settings yet.
I have looked in the VSCode setting as well but to no avail. 
I have also tried different themes to see what the background color will look like and in some themes it doesn't look good at all I can post a screenshot as an example if required. 
if there is a way to disable this new feature please provide guidance.

**Comment by jhgg** [comment]
FYI - I opened an issue about making the inlay hints look more like the old-style inlay hints via a config in vs-code here: https://github.com/microsoft/vscode/issues/145191

Discussion is ongoing!

**Comment by lnicola** [comment]
See also the docs: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/manual.adoc#color-configurations.

**Comment by lnicola** [comment]
Let's close this, since there's nothing we can do about the formatting (except coordinating with Code, like jhgg did). If you run into glitchy hints again, please check the `Rust Analyzer Language Server` output channel for any errors and file a new issue.

**Comment by YounessBird** [comment]
@lnicola Thanks for the link, maybe it's worth noting that those changes are not reflected in the rust-analyser website specifically in the link provided under [configuration](https://rust-analyzer.github.io/manual.html#vs-code-2) in the extension's home page. I will be happy to contribute if you can provide me guidance.

**Comment by lnicola** [comment]
The published manual is updated automatically on Monday after the release. So there's no need to do anything about it.

**Comment by lnicola** [comment]
@Fenex what if you set the hint background to black?

**Comment by jhgg** [comment]
> They're slower while typing because Code intentionally delays updating them.

https://github.com/microsoft/vscode/issues/145377

I've opened a feature request on vscode's end to allow the delay to be user configurable!
