### ISSUE TITLE
Feature Request / Discussion: should `Generate new` insert `#[must_use]`?

### ISSUE THREAD

**Issue by Walther** [rust-analyzer/rust-analyzer#11736]
The `Generate new` -helper in rust-analyzer is very useful!

There is a clippy lint [return_self_not_must_use](https://rust-lang.github.io/rust-clippy/master/#return_self_not_must_use) that encourages functions that return `Self` to be tagged with `#[must_use]`.

One could perhaps strawman-argue that this is "just a pedantic lint, allowed by default", but on the other hand this has been deemed important enough for the standard library:

> In Rust 1.57, many library functions got the #[must_use] attribute to prevent subtle mistakes. With Rust 1.58, this effort is now completed, and all functions that should have #[must_use] according to the accepted guidelines now have that attribute.
> <https://twitter.com/m_ou_se/status/1481684384096923652>

Should rust-analyzer's `Generate new` -helper insert this attribute by default, to conform with best practices?

**Comment by lnicola** [comment]
Sounds like a good idea.
