### ISSUE TITLE
Proc macros not expanded warning

### ISSUE THREAD

**Issue by onichandame** [rust-analyzer/rust-analyzer#11749]
### Problem

Some proc macros are throwing weird warnings. Without compile-time error it shows `unresolved-proc-macro` warning. But if the expanded code is faulted, it shows the actual error. See [this file](https://github.com/onichandame/ra-issue-demo/blob/master/src/dto.rs) for example:

correct usage:
![image](https://user-images.githubusercontent.com/23728505/158987358-ead0aa21-1bb6-4a1f-ba47-aeb9fd9ec9b0.png)

incorrect usage:
![image](https://user-images.githubusercontent.com/23728505/158987494-af2077d3-630a-490d-9778-14e6e0ed4db8.png)

Another related problem is that the autocompletion relating to the expanded code is broken.

**rust-analyzer version**: (eg. output of "Rust Analyzer: Show RA Version" command)
db2a7087b 2021-12-13 stable
**rustc version**: (eg. output of `rustc -V`)
rustc 1.59.0 (9d1b2106e 2022-02-23)
**relevant settings**: (eg. client settings, or environment variables like `CARGO`, `RUSTUP_HOME` or `CARGO_HOME`)
procMacro: { enable: true, server: null }

**Comment by lnicola** [comment]
This works for me:

![image](https://user-images.githubusercontent.com/308347/158988568-310c6a53-2246-4313-ad14-e15aa28ce9f7.png)

I'm not sure whether we fixed anything in the meanwhile, but you could try a newer version from https://github.com/rust-analyzer/rust-analyzer/releases/tag/2022-03-14.

**Comment by lnicola** [comment]
Yeah, I can confirm the problem on the 2021-12-13 release:

![image](https://user-images.githubusercontent.com/308347/158989040-3cbbdc60-fc3c-408e-8c31-380d4a08809b.png)

**Comment by onichandame** [comment]
Good to know that the error is reproducible and already fixed in the latest release.Will the latest release be synced to vscode's ra extension soon? I installed ra through the latest extension so I assume many people will be bugged if they naively follow the same path.

**Comment by lnicola** [comment]
I assume you're using VSCodium, where RA no longer updates because of https://github.com/rust-analyzer/rust-analyzer/issues/11080.

**Comment by onichandame** [comment]
Ah indeed. I am using code-server actually. It also downloads extensions from OpenVSX. So for now the issue is when the extension can be brought up to date. Thx @lnicola

**Comment by lnicola** [comment]
You could still give the new version a try, just to make sure it works.

Updates depend on an OpenVSX fix, which I expect to be merged in the next 1-3 weeks: https://github.com/eclipse/openvsx/pull/406.

**Comment by onichandame** [comment]
For anyone using vscode below v1.65(which the latest RA requires), the [second latest release](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2022-03-07) is compatible with vscode ^1.63 and also has the fix.
