### ISSUE TITLE
Call Info shows second parameter as active when the cursor is after the call

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#11758]
```rust
fn m(a: u8, b: u8, c: u8) {}

fn f() {
    m(1)$0
}
```

Call info at this position incorrectly looks like this:

![screenshot-2022-03-18-19:22:30](https://user-images.githubusercontent.com/1786438/159061318-bbd6913e-d79e-4bff-a2a4-585970b1fe06.png)

Presumably no signature help should be returned at all if we're after a completed function call? Not sure.

**Comment by Veykril** [comment]
Duplice of https://github.com/rust-analyzer/rust-analyzer/issues/11624
