### ISSUE TITLE
Signature help doesn't open when accepting generic type completion

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#11763]
In this code, accepting the `Vec<...>` completion places the cursor inside the `<>` brackets, but unlike when typing `<` by hand it does not open the signature help popup:

```rust
fn f() {
    let t: Ve$0
}
```

For function calls, this appears to work fine. For example, typing `Vec::with_cap` and accepting the `with_capacity(...)` completion places the cursor inside the parentheses, prefills the `capacity` argument with a placeholder, and opens the signature help popup. Such a placeholder is not included in the type completion, so that might be why it doesn't work there.

**Comment by Veykril** [comment]
The completion needs to explicitly trigger the call info/signature help via https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide_completion/src/item.rs#L514-L517
