### ISSUE TITLE
rust_analyzer.inlayHints color properties are not allowed

### ISSUE THREAD

**Issue by sgon00** [rust-analyzer/rust-analyzer#11764]
![Screenshot_20220320_013436](https://user-images.githubusercontent.com/1555508/159132830-c10c6ac7-b337-4378-8cd3-4d7e7199aaec.png)

There is an existing closed bug: https://github.com/rust-analyzer/rust-analyzer/issues/4334

I can not re-open it, so I am opening another one here. 

Basically, I just copied the [official manual's JSONC codes](https://rust-analyzer.github.io/manual.html#color-configurations) to my settings.json. It doesn't work at all. VSCode will complain these properties are not allowed. (maybe does not exist at all). 

I have no ideas why. Can anyone please let me know what's wrong with it?

Both VSCode (1.65.2) and rust-analyzer (releaseTag: 2022-03-14) are in the latest version. I am running debian 11.2.

**Comment by lnicola** [comment]
See https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/manual.adoc#color-configurations and https://github.com/rust-analyzer/rust-analyzer/issues/11733.

**Comment by sgon00** [comment]
@lnicola thank you very much for your help. The new way works.
Btw, should we keep the issue opened as a documentation (manual) bug?
[This manual](https://rust-analyzer.github.io/manual.html#color-configurations) is wrong.

**Comment by lnicola** [comment]
The manual has been updated (I linked to it), but it will be published on Monday. We usually close issues when they are fixed, not when the new version comes out.

**Comment by sgon00** [comment]
@lnicola ok, understand.
Hopefully, people can find this bug when they meet such problem before Monday.
I have spent 4 hours on this issue (nearly a day).

**Comment by lnicola** [comment]
Sorry for that. If it happens again, feel free to ask right from the start (or look at the existing issues, they're generally reported multiple times).

**Comment by sgon00** [comment]
OK, got it. thank you very much for your quick answer and help. 😄👍
