### ISSUE TITLE
Multiline documentation is sent with newlines

### ISSUE THREAD

**Issue by oblitum** [rust-analyzer/rust-analyzer#11787]
I'm not sure what approach is best at this, but I don't feel it's best to have line breaks as described here:

- https://github.com/neoclide/coc.nvim/issues/3720

**Comment by oblitum** [comment]
I tried to find a previous related issue but failed.

**Comment by Veykril** [comment]
Judging from the issue coc.nvim requests hovers with the markdown format. What we are sending is valid markdown, it is not the client's responsibility to use an appropriate markdown parser for the message which in this case would get rid of the line breaks as they are semantically meaningless to the paragraph block.

**Comment by oblitum** [comment]
You're right indeed.
