### ISSUE TITLE
Erroneous `erroneous constant used` error caused by unrelated warning

### ISSUE THREAD

**Issue by JohnDowson** [rust-analyzer/rust-analyzer#11784]
Borrow warning causes erroneous  errors to appear. Cargo check does not show this error.

Code causing this error:
![2022-03-21-23:00:30](https://user-images.githubusercontent.com/40003182/159355051-f82a2457-e91d-47b0-98ea-d4d49f6e40fd.png)

Code that doesn't cause this:
![2022-03-21-23:00:46](https://user-images.githubusercontent.com/40003182/159355054-45353858-23cc-4ea9-99fb-5fc173fadb43.png)

Repository in a state that should reproduce the error: https://github.com/JohnDowson/rotth/tree/ra-error

**rust-analyzer version**: b594f9c44 2022-03-21

**rustc version**: rustc 1.61.0-nightly (532d3cda9 2022-02-23)

**Comment by bjorn3** [comment]
Does `cargo check --workspace --all-targets` show it?

**Comment by JohnDowson** [comment]
> Does `cargo check --workspace --all-targets` show it?

Nope, it does not.

**Comment by flodiebold** [comment]
As bjorn3 alludes to, this error is produced by rustc, not RA's own analysis, so it *has* to come from `cargo check` in some way. I.e. it seems there is some difference in how RA is calling `cargo check` that produces this. Have you tried `cargo clean`?

**Comment by JohnDowson** [comment]
`cargo check` does not produce this error under any circumstances. However, `cargo clippy` does. I guess this issue is better filed in it's repository.

**Comment by flodiebold** [comment]
Indeed. I'll close this issue then.
