### ISSUE TITLE
VSCode `rust-analyzer`.

### ISSUE THREAD

**Issue by Jerrody** [rust-analyzer/rust-analyzer#11807]
VSCode `rust-analyzer`.
When I fast type suggestions disappear. What's problem?

**Comment by flodiebold** [comment]
See https://github.com/rust-analyzer/rust-analyzer/issues/7560 and https://github.com/rust-analyzer/rust-analyzer/issues/10187.

**Comment by Jerrody** [comment]
> See #7560 and #10187.

Thanks!
