### ISSUE TITLE
Type mismatch T vs () when last expression is noreturn asm 

### ISSUE THREAD

**Issue by VisualDevelopment** [rust-analyzer/rust-analyzer#11820]
**rust-analyzer version**: rust-analyzer 68dfda6e4 2022-03-25 dev
**rustc version**: rustc 1.61.0-nightly (63b8f01bb 2022-03-24)

Sample:
```rs
pub unsafe fn somefunc() -> u64 {
    // Rust analyser will complain for the entire function body 
    // that there is a type mismatch: expected u64 got ()
    core::arch::asm!("call {}", options(noreturn));
}
```

**Comment by jonas-schievink** [comment]
The easiest way to fix this is probably to make it expand to `loop {}` intead of `()` here:

https://github.com/rust-analyzer/rust-analyzer/blob/e30747dfa885d3e4e4cd0b5efcd740ea037a524c/crates/hir_expand/src/builtin_fn_macro.rs#L298
