### ISSUE TITLE
VSCode | Feature request.

### ISSUE THREAD

**Issue by Jerrody** [rust-analyzer/rust-analyzer#11838]
Adding to `mod.rs` a module at the moment of creation.

**Comment by lnicola** [comment]
Can you expand on this a little? We have a couple of relevant assists like `move_module_to_file` in https://rust-analyzer.github.io/manual.html, but `mod.rs` files are less used since the 2018 edition.

**Comment by Jerrody** [comment]
> Can you expand on this a little? We have a couple of relevant assists like `move_module_to_file` in https://rust-analyzer.github.io/manual.html, but `mod.rs` files are less used since the 2018 edition.

Oh, I didn't know this and what should be used than `mod.rs`?

**Comment by lnicola** [comment]
You can still use `mod.rs` files, but see https://doc.rust-lang.org/edition-guide/rust-2018/path-changes.html#no-more-modrs.

**Comment by Jerrody** [comment]
> You can still use `mod.rs` files, but see https://doc.rust-lang.org/edition-guide/rust-2018/path-changes.html#no-more-modrs.
Thanks!
