### ISSUE TITLE
Suggest infered type in auto complete after colon

### ISSUE THREAD

**Issue by HKalbasi** [rust-analyzer/rust-analyzer#11855]
That is, suggest entire `Vec<Option<i32>>` here:
```rust
fn foo() {
  let x: /* auto complete */ = vec![Some(2)];
}
```
It helps when compiler mandates type annotation, e.g. function parameters and consts.

**Comment by flodiebold** [comment]
Same for function/closure return types actually; there we have an assist, but suggesting it in completion would also make sense.

**Comment by matklad** [comment]
brilliant idea, we need more of these dwim things!
