### ISSUE TITLE
Investigate alternative SyntaxPtr repr

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1185]
We have SyntaxPtr infra to allow to get syntax nodes after reparse:

https://github.com/rust-analyzer/rust-analyzer/blob/5e1c29543cd49ab9f0833acbffd572d6b9f50da8/crates/ra_syntax/src/ptr.rs

Currently it is implemented in a naive way, by storing node's text range. I think a more efficient way to do this is to store a path from root to this node. Ptr like `[0, 3, 0]` means:

* pick zeroth child of ro0t
* pick third child of this node
* pick first child of this node

I assume that most nodes are shallow and have few children. So, we can encode this as an `[u8]`, where we use var-length encoding for child nodes. Current size of SYntaxPtr is 12 bytes (I think? maybe it's 16?). If most nodes have depth less than 12, than that's a win!

So, what we should do is we should parse all of rust-analyzer source code and collect the depth and number of children of each nodes, and produce some kind of histograms. If the data confirms that nodes are few and shallow, we should refactor SyntaxPtr.

**Comment by yanchith** [comment]
Found some time to work on `ra` again ❤️ 

Would like to try this. Will post progress/questions.

**Comment by yanchith** [comment]
Okay, I managed to get a very basic analysis going. I will continue working on this tomorrow and come with proper histograms, percentiles, and whole project analysis.

So far the info is only collected from a single source file (I used `ra_syntax/src/syntax_node.rs`) - I still need to figure out how to collect the info for the whole project but I guess mimicking what `analysis_stats.rs` does will point me in the the general direction.

I wasn't sure whether to also count tokens or not (`SyntaxNodePtr` looks like it can't point to tokens, only nodes), so I collected the info both with and without tokens. 

Results for `ra_syntax/src/syntax_node.rs` *including tokens*:
```
Syntax tree stats: DebugStats {
    hist_node_depth: {
        0: 1,
        1: 106,
        2: 392,
        3: 544,
        4: 1093,
        5: 1515,
        6: 1184,
        7: 1096,
        8: 1114,
        9: 1065,
        10: 896,
        11: 774,
        12: 617,
        13: 541,
        14: 384,
        15: 256,
        16: 177,
        17: 111,
        18: 91,
        19: 64,
        20: 56,
        21: 39,
        22: 39,
        23: 46,
        24: 29,
        25: 37,
        26: 17,
        27: 9,
        28: 4,
        29: 3
    },
    hist_node_children: {
        1: 3815,
        2: 469,
        3: 686,
        4: 330,
        5: 235,
        6: 53,
        7: 19,
        8: 72,
        9: 53,
        10: 67,
        11: 10,
        12: 10,
        13: 5,
        15: 8,
        17: 1,
        18: 3,
        19: 1,
        21: 3,
        23: 2,
        30: 1,
        69: 1,
        106: 1
    },
    max_node_depth: 29,
    max_node_children: 106
}
```

Results for `ra_syntax/src/syntax_node.rs` *excluding tokens*:
```
Syntax tree stats: DebugStats {
    hist_node_depth: {
        0: 1,
        1: 45,
        2: 160,
        3: 206,
        4: 537,
        5: 455,
        6: 523,
        7: 610,
        8: 561,
        9: 564,
        10: 490,
        11: 418,
        12: 341,
        13: 273,
        14: 193,
        15: 133,
        16: 78,
        17: 58,
        18: 43,
        19: 29,
        20: 21,
        21: 20,
        22: 15,
        23: 13,
        24: 14,
        25: 10,
        26: 7,
        27: 3,
        28: 2
    },
    hist_node_children: {
        0: 1743,
        1: 2981,
        2: 753,
        3: 217,
        4: 53,
        5: 64,
        6: 4,
        7: 3,
        9: 1,
        10: 2,
        33: 1,
        45: 1
    },
    max_node_depth: 28,
    max_node_children: 45
}
```

Good news is no syntax node in that file even came close to having `u8::MAX` children. `hist_node_depth` also seems to peak well under 12.

Btw how would the new `SyntaxPtr` struct definition look like? Wouldn't it have to be a DST if it needs to contain `[u8]`?

**Comment by matklad** [comment]
>Btw how would the new SyntaxPtr struct definition look like? Wouldn't it have to be a DST if it needs to contain [u8]?

It should use smallvec internally.

**Comment by matklad** [comment]
Hm, we do have quite a number of deep nodes though...

**Comment by yanchith** [comment]
Here is the full project analysis (I think). The file count is somewhat mismatched (214 reported by `ra` vs 466 reported by `tokei`). Very weird at first, but when looking closer, the files ignored by `ra` seem to just not have `mod` declarations anywhere in the project, such as: `ra_hir/src/module_tree.rs`, which is also empty.

As for the results, there is exactly one node having more children than `u8::MAX` without tokens: the `SOURCE_FILE` node for `ra_syntax/src/ast/generated.rs` (a really big file).

When including tokens, two more syntax nodes have more children than `u8::MAX`:  `ENUM_VARIANT_LIST` for `SyntaxKind` defined in `ra_parser/src/syntax_kind/generated.rs` and the `MATCH_ARM_LIST` in `pub(crate) fn info(self) -> &'static SyntaxInfo` in the same file.

The depth seems to be peaking at 7 for syntax nodes excluding tokens and 8 for syntax including tokens.

Overall, both some nodes surpassing `u8::MAX` children and the depth histograms don't look too favorable. Also, when thinking about it, while the current `SyntaxNodePtr` representation has an upfront cost of 10-12 bytes, that cost does not increase with syntax tree size depth, and therefore it should scale well even for extremely deep and branchy trees.

I will have to be offline until Monday, but if anyone would like to verify these results, here is the branch containing the dirty tools I used to get them: https://github.com/rust-analyzer/rust-analyzer/compare/master...yanchith:syntax-ptr-analysis (I mostly tweaked the `analysis-stats` cli)

The raw results (without percentiles, sorry):

Results *including tokens*
```
Total source files: 214
Syntax stats: DebugStats {
    hist_node_depth: {
        0: 214,
        1: 7838,
        2: 27645,
        3: 39682,
        4: 62419,
        5: 75011,
        6: 69006,
        7: 60960,
        8: 69928,
        9: 57747,
        10: 49595,
        11: 43169,
        12: 36412,
        13: 29991,
        14: 23929,
        15: 18131,
        16: 14429,
        17: 10963,
        18: 8423,
        19: 6363,
        20: 4893,
        21: 3590,
        22: 2887,
        23: 2232,
        24: 1757,
        25: 1324,
        26: 1013,
        27: 738,
        28: 536,
        29: 331,
        30: 253,
        31: 175,
        32: 126,
        33: 76,
        34: 55,
        35: 39,
        36: 30,
        37: 22,
        38: 23,
        39: 18,
        40: 20,
        41: 16,
        42: 19,
        43: 16,
        44: 19,
        45: 16,
        46: 19,
        47: 16,
        48: 19,
        49: 16,
        50: 19,
        51: 16,
        52: 19,
        53: 16,
        54: 19,
        55: 16,
        56: 19,
        57: 16,
        58: 19,
        59: 16,
        60: 18,
        61: 11,
        62: 10,
        63: 9,
        64: 5,
        65: 3,
        66: 1
    },
    hist_node_children: {
        1: 232391,
        2: 26923,
        3: 31644,
        4: 19767,
        5: 11169,
        6: 5391,
        7: 2220,
        8: 5763,
        9: 3901,
        10: 1300,
        11: 942,
        12: 1062,
        13: 423,
        14: 168,
        15: 469,
        16: 68,
        17: 125,
        18: 218,
        19: 82,
        20: 36,
        21: 126,
        22: 32,
        23: 53,
        24: 54,
        25: 29,
        26: 16,
        27: 42,
        28: 16,
        29: 17,
        30: 24,
        31: 15,
        32: 7,
        33: 34,
        34: 13,
        35: 10,
        36: 8,
        37: 8,
        38: 9,
        39: 12,
        40: 5,
        41: 10,
        42: 13,
        43: 3,
        44: 4,
        45: 12,
        46: 4,
        47: 3,
        48: 4,
        49: 2,
        50: 3,
        51: 4,
        52: 2,
        53: 4,
        54: 4,
        55: 2,
        56: 1,
        57: 2,
        59: 1,
        60: 4,
        61: 1,
        62: 3,
        63: 1,
        64: 8,
        65: 2,
        66: 4,
        67: 1,
        68: 1,
        69: 1,
        70: 3,
        71: 4,
        74: 1,
        75: 4,
        76: 3,
        77: 1,
        78: 1,
        82: 1,
        84: 1,
        85: 1,
        86: 1,
        87: 2,
        88: 1,
        89: 1,
        90: 1,
        93: 1,
        94: 1,
        96: 1,
        97: 2,
        99: 1,
        102: 1,
        103: 1,
        106: 1,
        110: 1,
        114: 1,
        115: 1,
        140: 1,
        142: 1,
        152: 1,
        159: 1,
        171: 1,
        184: 1,
        211: 1,
        672: 2,
        1522: 1
    },
    max_node_depth: 66,
    max_node_children: 1522
}
```

Results *excluding tokens*
```
Total source files: 214
Syntax stats: DebugStats {
    hist_node_depth: {
        0: 214,
        1: 3522,
        2: 10189,
        3: 13153,
        4: 27778,
        5: 27334,
        6: 28926,
        7: 34364,
        8: 33127,
        9: 30177,
        10: 26019,
        11: 22789,
        12: 19142,
        13: 15450,
        14: 11959,
        15: 9326,
        16: 7347,
        17: 5664,
        18: 4323,
        19: 3327,
        20: 2429,
        21: 1897,
        22: 1444,
        23: 1185,
        24: 926,
        25: 731,
        26: 543,
        27: 378,
        28: 255,
        29: 175,
        30: 124,
        31: 93,
        32: 58,
        33: 44,
        34: 30,
        35: 20,
        36: 12,
        37: 14,
        38: 11,
        39: 12,
        40: 9,
        41: 11,
        42: 9,
        43: 11,
        44: 9,
        45: 11,
        46: 9,
        47: 11,
        48: 9,
        49: 11,
        50: 9,
        51: 11,
        52: 9,
        53: 11,
        54: 9,
        55: 11,
        56: 9,
        57: 11,
        58: 9,
        59: 11,
        60: 9,
        61: 8,
        62: 7,
        63: 5,
        64: 3,
        65: 1
    },
    hist_node_children: {
        0: 100565,
        1: 178821,
        2: 45092,
        3: 14369,
        4: 3273,
        5: 1666,
        6: 309,
        7: 156,
        8: 112,
        9: 73,
        10: 48,
        11: 35,
        12: 36,
        13: 24,
        14: 29,
        15: 16,
        16: 9,
        17: 11,
        18: 9,
        19: 5,
        20: 5,
        21: 10,
        22: 4,
        23: 5,
        24: 4,
        25: 9,
        26: 3,
        27: 1,
        28: 6,
        29: 5,
        30: 4,
        31: 4,
        32: 5,
        33: 1,
        34: 3,
        37: 1,
        38: 1,
        40: 2,
        41: 2,
        42: 1,
        43: 1,
        45: 1,
        49: 1,
        51: 1,
        53: 1,
        54: 1,
        89: 1,
        223: 2,
        754: 1
    },
    max_node_depth: 65,
    max_node_children: 754
}
```

**Comment by matklad** [comment]
cc @CAD97 here are some fun stats which might inform design of sorbus (which I should get to reviewing already :fearful: )

**Comment by CAD97** [comment]
https://github.com/rust-analyzer/rust-analyzer/blob/b63e23e98e7dfbe57de93ebe256254825512e148/crates/ra_syntax/src/ptr.rs#L11-L17

`SyntaxPtr` is thus currently roughly `(u32, u32, u16)`, which pads to `u32×3` for 12 bytes. The _absolute_ smallest an `[offset]` "trace" design could be is `(usize, u8)`, which would pad to `usize×2` for 16 bytes. (This is required because it needs to be able to spill to the rough equivalent of `Box<[offset]>`.)

But how many `SyntaxPtr` are being stored in memory? If that number is small, it may be worth it, because it allows (*d* = node depth, *w* = node width) ***O*(*d*)** resolution, as opposed to the best possible design for a `(range, kind)` pair which sees ***O*(*d* log *w*)** resolution.

Additionally to the asymptotically faster resolution, using a "trace" `SyntaxPtr` would allow for reducing the amount of information stored in a node (well, in sorbus, which does the acceleration; rowan doesn't yet). This is roughly a 1/3 saving per child edge -- definitely meaningful, and vastly simplifies some of the [ugliest unsafe code in sorbus](https://github.com/CAD97/sorbus/blob/main/src/green/element.rs).

With _very_ rough estimates of deduplication factors (I just used 10 for anything with < 4 children), I estimate that a full tree of r-a to be about 300 KiB heavier if it carries offsets in the tree. At that estimate, over 2000 Ptrs of maximal size would have to be stored to eat up the memory saving. I think this serves as enough evidence to remove storage of cumulative child offsets from the sorbus tree and go ahead with implementing a "trace" pointer.

**Comment by matklad** [comment]
I guess our current log(N) design actually works good enough!
