### ISSUE TITLE
Completion order: should postfix completions be interleaved with symbols?

### ISSUE THREAD

**Issue by fasterthanlime** [rust-analyzer/rust-analyzer#11850]
**rust-analyzer version**: bc08b8eff 2022-03-28 stable

**rustc version**: rustc 1.59.0 (9d1b2106e 2022-02-23)

**relevant settings**: none really

I'm a completion enthusiast - I like to `ctrl-space` and just see what I can do with a type, at the very least what fields and methods are available.

rust-analyzer makes that harder by peppering the (otherwise very handy) postfix snippets throughout:

![completions for socket2::Socket. - it shows accept, accept4, accept_raw, then the postfix arc, some more methods, then some more methods, then box, some methods, then call](https://user-images.githubusercontent.com/7998310/160825445-d78bc18a-da04-4597-9c14-d2e57936bd66.png)

(That's [socket2::Socket](https://docs.rs/socket2/latest/socket2/))

(Also, god, having `owo-colors` in a project makes completion nearly unusable - surely if we need to import a package it should score lower?)

I can of course disable those completely:

![the Completion: Postfix setting for rust-analyzer](https://user-images.githubusercontent.com/7998310/160825777-1d9fb406-155e-4708-bc75-8784b6ad9b79.png)

But I don't wan't to - I do occasionally do the `.arc`, `.pinbox`, `.box`, etc. And there's no way I know of to hide them from the list or deprioritize them so they show up at the end.

I figured maybe that's just a VSCode thing and that's how life is, but circumstances led me to do some TypeScript again, and I noticed that they show fields/methods first, and _then_ postfix completions (and then deprecated symbols):

![completions for e.e where e is a DOM Event: it shows an Emmet abbreviation (don't like these), a field, then two postfix completions: expand template string and error, then deprecated fields](https://user-images.githubusercontent.com/7998310/160826471-10610d67-7a5c-4b3a-b662-dcdda5ca1232.png)

Would it be possible to have that behavior in rust-analyzer? I don't know how many others feel like I do, but as-is, I feel like it's an unfortunate default at least.

**Comment by jonas-schievink** [comment]
We do very limited completion sorting at the moment, so the quality of our completions is not all that great in general: https://github.com/rust-analyzer/rust-analyzer/issues/7935

**Comment by Veykril** [comment]
Sounds reasonable sorting them last (same for deprecated symbols), score ranking basically happens here https://github.com/rust-analyzer/rust-analyzer/blob/63c4d6b20dd9445bea135473a6bf203644cfdd65/crates/ide_completion/src/item.rs#L192-L219
So this mainly requires adding a few more fields to `CompletionItemRelevance` and populating that in the according completion accumulators.
