### ISSUE TITLE
Trait item completions could work better

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#11860]
Given this code:

```rust
trait Tr {
    type Ty;
    const KONST: u8;
    fn required();
    fn provided() {}
}

impl Tr for () {
    $0
}
```

The completion we provide are generally pretty bad:

* [x] Requesting completions at `$0` without typing anything else just shows generic completions. We should prioritize completions of missing trait items to be at the very top there.
  * (in fact I cannot find them in the list at all, do they only show up if at least one character is typed?)
* [x] Replacing `$0` with `fn ` and then requesting completions shows *nothing*. Instead, both `required` and `provided` should show up.
  * (the same happens when typing other keywords)
* [ ] Applying the completion for `Ty` and `KONST` does not complete the required `;` at the end, but the `fn` completions do include the function body and place the cursor inside.
* [x] Impl items generated by macros are still suggested.

**Comment by Veykril** [comment]
> (in fact I cannot find them in the list at all, do they only show up if at least one character is typed?)

That's https://github.com/rust-analyzer/rust-analyzer/issues/11467
