### ISSUE TITLE
"Remove the unused import" should act on the whole selected block, not just the first import. Also there is a bug.

### ISSUE THREAD

**Issue by vi** [rust-analyzer/rust-analyzer#11885]
In the code I am editing now:

Before:

```
┃use websocat_api::anyhow;
use websocat_api::{tracing, Result};
use websocat_api::{Bipipe, RunnableNode, Sink, Source};
use websocat_derive::WebsocatNode;┃
```

(from [here](https://github.com/vi/websocat/blob/56d11f7742cb271a8da7b2e841df670207b10aa9/crates/websocat-readline/src/lib.rs#L1-L4))

The cursor is blinking at the beginning. Anything besides `tracing` and `WebsocatNode` is underlined as unused.

"remove the unused import"

```
┃use websocat_api::anyhow;
use websocat_api::{tracing};
use websocat_api::{Bipipe, RunnableNode, Sink, Source};
use websocat_derive::WebsocatNode;┃
```

OK, but not enough. Also why it removed the second unused import, not the first?

"remove the unused import" again.

```
┃use websocat_api::anyhow;
use websocat_api::{tracing
use websocat_api::{Bipipe, RunnableNode, Sink, Source};
use websocat_derive::WebsocatNode;┃
```

It has removed `};` instead of `Bipipe, ` for some reason.

---

Expected:

"remove unused imports" instead of "remove the unused import" when multiple unused imports are selected.

```
┃use websocat_api::{tracing};
use websocat_derive::WebsocatNode;┃
```

`rust-analyzer version: b8e1d09b9 2022-03-24 nightly`.
Also reproducible in `rust-analyzer version: bc08b8eff 2022-03-28 stable` (including the broken syntax after second application of remove unused import, though different substring gets removed).

**Comment by jhgg** [comment]
This diagnostic is currently provided by rustc, and the edit is suggested by "cargo check". There is unfortunately a race where if you try and execute this twice in a row, the edit would be outdated (in this case, from the last time cargo check ran, which is most likely when you last hit save.). 

I don't think this can be fixed until rust-analyzer adds this as a built in diagnostic/assist.

**Comment by flodiebold** [comment]
Yeah, this quickfix comes from rustc, so this is not an RA issue. See #5131 for the topic of implementing this in RA instead.
