### ISSUE TITLE
Autocompleting functions and enum variants no longer works right

### ISSUE THREAD

**Issue by umanwizard** [rust-analyzer/rust-analyzer#11898]
**rust-analyzer version**: `rust-analyzer f5c069c9d 2022-04-04 dev`

**rustc version**: `rustc 1.59.0 (9d1b2106e 2022-02-23)`

**relevant settings**: using recent emacs compiled from tip of master

I'm getting these weird `$0`, `$1`, etc. placeholders when autocompleting functions or enum variants, that I wasn't seeing before:

<img width="428" alt="image" src="https://user-images.githubusercontent.com/1893159/161597358-152387e5-5cac-407c-a800-f59a1e9270e3.png">

**Comment by bjorn3** [comment]
The lsp client is supposed to put the cursor at $0 and turn `${1:()}` and similar into placeholders with the part between the `:` and `}` as placeholder text. Which lsp client are you using and which version?

**Comment by umanwizard** [comment]
Emacs lsp-mode 20220401.1003.

Should I submit a bug to them?

**Comment by bjorn3** [comment]
I think so.

**Comment by umanwizard** [comment]
The issue seems to be [this](https://emacs-lsp.github.io/lsp-mode/page/faq/#the-completion-does-not-work-fine-and-inserts-arguments-and-placeholders-what-i-am-doing-wrong), sorry for the noise.
