### ISSUE TITLE
I get "permission denied" error when click "run tests" in vscode

### ISSUE THREAD

**Issue by FischLu** [rust-analyzer/rust-analyzer#11917]
I am using rust-analyzer with vscode on macos. There is an automatically generated test mod in any library project for example generated by the command `cargo new libtest1 --lib`

above the test mod I see two clickable words, "Run Tests" and "Debug" as shown in the following image.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/10261662/162053036-96e120c3-c82d-49f9-a8ce-04d009d0747a.png">

The "Debug" works fine, I am able to start debug and set break points etc. But the "Run Tests" doesn't, I got error message

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/10261662/162053176-f643a10d-6330-4e82-b9b8-392c8916c2df.png">

I think my configuration of rust-analyzer should be correct, because in a binary project, I am able to start debug by hitting F5, and rust-analyzer can generate a working launch.json file for me. Does anyone know what is the reason for this error? At where the permission is denied? Thank you.

**rust-analyzer version**: v0.2.1002

**rustc version**: rustc 1.59.0 (9d1b2106e 2022-02-23)

**relevant settings**: in vscode, my rust-analyzer settings are
```
"rust-analyzer.server.extraEnv": {
        "CARGO": "/usr/local/bin/cargo/bin/cargo",
        "RUSTC": "/usr/local/bin/cargo/bin/rustc"
    },
```

**Comment by mahdi-frms** [comment]
The command is being executed by the integrated terminal if I'm not mistaken, so not really sure if this concerns RA or not. I might suggest to check permission of your cargo home directory. closing vscode and running `cargo clean` is also an option.

**Comment by FischLu** [comment]
> The command is being executed by the integrated terminal if I'm not mistaken, so not really sure if this concerns RA or not. I might suggest to check permission of your cargo home directory. closing vscode and running `cargo clean` is also an option.

Yes, I think the command is executed by the integrated terminal, and if I copy the generated command `cargo test --package libTest1 --lib -- tests::it_works --exact --nocapture ` and manually paste into the integrated terminal, everything is fine, the test runs without problem... On the other hand, the "Debug" always works fine. What actually happened once I click "Run Test", is it possible to generate some log file?

**Comment by lnicola** [comment]
The `CARGO` variable in `rust-analyzer.server.extraEnv` only applies to the language server, but the runnables are invoked by the LSP client. The error makes it sound like you're invoking some non-executable -- a regular file or directory called `cargo`.

I strongly suggest using the recommended `rustup` installation method. See https://github.com/rust-analyzer/rust-analyzer/issues/11493#issuecomment-1064375371= and #11673 as examples of issues caused by this kind of setup.

**Comment by mahdi-frms** [comment]
> The error makes it sound like you're invoking some non-executable -- a regular file or directory called `cargo`.

So if that's the case, how can he invoke it from the terminal without an error?

**Comment by lnicola** [comment]
The terminal will be running a shell, so if environment variables like `PATH` or `RUSTUP_HOME` are configured in a `rc` or `profile` file, they will be available there.

A Code instance started from a DE will probably see a different set of environment variables. Running Code from a terminal might work.

**Comment by FischLu** [comment]
> The `CARGO` variable in `rust-analyzer.server.extraEnv` only applies to the language server, but the runnables are invoked by the LSP client. The error makes it sound like you're invoking some non-executable -- a regular file or directory called `cargo`.
> 
> I strongly suggest using the recommended `rustup` installation method. See [#11493 (comment)](https://github.com/rust-analyzer/rust-analyzer/issues/11493#issuecomment-1064375371) and #11673 as examples of issues caused by this kind of setup.

Thank you very much for your help, my rust is installed via rustup, but not into the default path, that's the reason for the problem. I solved it according to #11673, by adding `"rust-analyzer.runnableEnv": {"PATH": "/usr/local/bin/cargo/bin/"}` in my vscode `settings.json`.

I list my installation steps below, if any other user has the same problem and a similar installation method to mine, try to add `rust-analyzer.runnableEnv`

1. install `rustup` via `brew install rustup-init`
2. add the following part in to my .zshrc
```
export RUSTUP_HOME=/usr/local/bin/rushup
export CARGO_HOME=/usr/local/bin/cargo
path+=('/usr/local/bin/cargo/bin')
export PATH
```
3. install rust by `rustup`

**Comment by lnicola** [comment]
> "rust-analyzer.runnableEnv": {"PATH": "/usr/local/bin/cargo/bin/"}

Unfortunately, I'm not sure that's a complete fix. Some crates like `prost` might have build scripts that invoke commands, so you might have to add `/usr/bin` to that path.

**Comment by FischLu** [comment]
> The error makes it sound like you're invoking some non-executable -- a regular file or directory called `cargo`.

I paid more attention to this sentence again and I think it was very accurate, the `/usr/local/bin` is in the `PATH` of MacOS by default, but `/usr/local/bin/cargo` is not, if the LSP client was been running in an environment which doesn't include my customized `PATH`, it will see a cargo folder and try to run it, therefore the error. At least next time I see the error I know where to go.
