### ISSUE TITLE
rust-analyzer in VS Code will stick in the save action for a long time

### ISSUE THREAD

**Issue by pan93412** [rust-analyzer/rust-analyzer#11933]
## Brief Description

After upgrading to rust-analyzer for VS Code 0.3.1006, I found that `rust-analyzer` **often took a long time to run the pre-save action**. It would take about 7 seconds for a save, and I can neither run my code nor commit to Git at this moment.

Therefore, I made a bisection, and located the first reproducible version to 0.3.1005, while the last correct version is 0.3.1004. However, there are 12 commits between the versions. Thus, I managed to run `git bisect` with my build script to find the first reproducible commit, and I found the commit 4e6390bb129f212614eda8a0cd6662d9cb4440f3:

![the first bad commit is 4e6390b](https://user-images.githubusercontent.com/28441561/162355187-5dc194dc-bd34-4661-b0f3-6688b8318e25.jpg)

I compared 4e6390bb129f212614eda8a0cd6662d9cb4440f3 with its parent commit fa06e3d0f9dcd5568ae8fd386c63c91924df8710 many times, and I confirmed that 4e6390bb129f212614eda8a0cd6662d9cb4440f3 is the first commit introducing this issue.

## Expected behavior

`rust-analyzer` should check the file fast after I perform the save action to my file.

https://user-images.githubusercontent.com/28441561/162355689-701269b6-1cad-4713-a57b-7dcaf366dda0.mov

## Actual behavior

VS Code is stuck waiting for the rust-analyzer to check my file:

https://user-images.githubusercontent.com/28441561/162355903-15e1fd52-5bab-4e62-92a3-df7ac87a0c0b.mov

## Reproducible Repository

https://github.com/UnblockNeteaseMusic/server-rust/tree/ra-bug/ra4e6390b

You can locate the position that I used for my test by finding `// REPRO_POINT` in the codebase.

## rust-analyzer version

    rust-analyzer version: 4e6390b 2022-04-08 nightly

(Don't mind the build date - it is built by me.)

## rustc version

    rustc 1.61.0-beta.1 (0f231250b 2022-04-05)

## Relevant Settings

The verbose information with the configuration of the rust-analyzer:

```
INFO [4/8/2022, 10:52:14 AM]: Extension version: 0.3.1002
INFO [4/8/2022, 10:52:14 AM]: Using configuration {
  cargoRunner: null,
  runnableEnv: { CHALK_SOLVER_MAX_SIZE: '100' },
  inlayHints: {
    enable: true,
    renderColons: true,
    maxLength: 25,
    parameterHints: true,
    typeHints: true,
    chainingHints: true,
    closureReturnTypeHints: false,
    reborrowHints: false,
    lifetimeElisionHints: { enable: 'never', useParameterNames: false },
    hideNamedConstructorHints: false
  },
  server: { path: null, extraEnv: null },
  trace: { server: 'off', extension: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  assist: {
    exprFillDefault: 'todo',
    importGranularity: 'crate',
    importEnforceGranularity: false,
    importPrefix: 'plain',
    importGroup: true,
    allowMergingIntoGlobImports: true
  },
  cache: { warmup: true },
  callInfo: { full: true },
  cargo: {
    autoreload: true,
    allFeatures: false,
    unsetTest: [ 'core' ],
    features: [],
    runBuildScripts: true,
    useRustcWrapperForBuildScripts: true,
    noDefaultFeatures: false,
    target: null,
    noSysroot: false
  },
  checkOnSave: {
    enable: true,
    allFeatures: null,
    allTargets: true,
    command: 'clippy',
    noDefaultFeatures: null,
    target: null,
    extraArgs: [],
    features: null,
    overrideCommand: null
  },
  completion: {
    addCallArgumentSnippets: true,
    addCallParenthesis: true,
    snippets: {
      'Arc::new': {
        postfix: 'arc',
        body: 'Arc::new(${receiver})',
        requires: 'std::sync::Arc',
        description: 'Put the expression into an `Arc`',
        scope: 'expr'
      },
      'Rc::new': {
        postfix: 'rc',
        body: 'Rc::new(${receiver})',
        requires: 'std::rc::Rc',
        description: 'Put the expression into an `Rc`',
        scope: 'expr'
      },
      'Box::pin': {
        postfix: 'pinbox',
        body: 'Box::pin(${receiver})',
        requires: 'std::boxed::Box',
        description: 'Put the expression into a pinned `Box`',
        scope: 'expr'
      },
      Ok: {
        postfix: 'ok',
        body: 'Ok(${receiver})',
        description: 'Wrap the expression in a `Result::Ok`',
        scope: 'expr'
      },
      Err: {
        postfix: 'err',
        body: 'Err(${receiver})',
        description: 'Wrap the expression in a `Result::Err`',
        scope: 'expr'
      },
      Some: {
        postfix: 'some',
        body: 'Some(${receiver})',
        description: 'Wrap the expression in an `Option::Some`',
        scope: 'expr'
      }
    },
    postfix: { enable: true },
    autoimport: { enable: true },
    autoself: { enable: true },
    privateEditable: { enable: false }
  },
  diagnostics: {
    enable: true,
    enableExperimental: false,
    disabled: [],
    remapPrefix: {},
    warningsAsHint: [],
    warningsAsInfo: []
  },
  experimental: { procAttrMacros: false },
  files: { watcher: 'client', excludeDirs: [] },
  highlightRelated: {
    references: true,
    exitPoints: true,
    breakPoints: true,
    yieldPoints: true
  },
  highlighting: { strings: true },
  hover: { documentation: true, linksInHover: true },
  hoverActions: {
    debug: true,
    enable: true,
    gotoTypeDef: true,
    implementations: true,
    references: false,
    run: true
  },
  joinLines: {
    joinElseIf: true,
    removeTrailingComma: true,
    unwrapTrivialBlock: true,
    joinAssignments: true
  },
  lens: {
    debug: true,
    enable: true,
    implementations: true,
    run: true,
    methodReferences: false,
    references: false,
    enumVariantReferences: false,
    forceCustomCommands: true
  },
  linkedProjects: [],
  lruCapacity: null,
  notifications: { cargoTomlNotFound: true },
  primeCaches: { numThreads: 0 },
  procMacro: {
    enable: false,
    server: null,
    ignored: { 'napi-derive': [ 'napi' ] }
  },
  runnables: { overrideCargo: null, cargoExtraArgs: [] },
  rustcSource: null,
  rustfmt: {
    extraArgs: [],
    overrideCommand: null,
    enableRangeFormatting: false
  },
  workspace: {
    symbol: { search: { scope: 'workspace', kind: 'only_types', limit: 128 } }
  }
}
INFO [4/8/2022, 10:52:14 AM]: PersistentState: { serverVersion: '0.3.1002' }
INFO [4/8/2022, 10:52:15 AM]: Using server binary at /Users/pan93412/.vscode-insiders/extensions/matklad.rust-analyzer-0.3.1002/server/rust-analyzer
```

## My build script for bisection

**script.fish**

```fish
set -gx RA_TARGET aarch64-apple-darwin
set CURRENT_REV (git rev-parse --short HEAD)
set REV_DISTANCE (git rev-list --count "2366d8e..$CURRENT_REV")

git reset --hard HEAD

cargo xtask dist --client-patch-version "100$REV_DISTANCE"

pushd editors/code
npx vsce package -o "../../dist/rust-analyzer-$CURRENT_REV.vsix" --target darwin-arm64 --pre-release
popd
```

**Comment by lnicola** [comment]
I can't seem to be able to reproduce this. Do you have any error in this output panel?

![image](https://user-images.githubusercontent.com/308347/162378793-79c42fc2-300b-4688-83e7-fd9f90a17da2.png)

And does anything change if you disable clippy (or even check) on save?

**Comment by lnicola** [comment]
Does that cover auto-formatting? I don't think we fix anything on save.

**Comment by pan93412** [comment]
> Does that cover auto-formatting? I don't think we fix anything on save.

Seems no. I still need to run `cargo fmt` eventually.

**Comment by lnicola** [comment]
This is still probably our bug. What happens sometimes is that a LSP request either takes too much or crashes the server, and then format-on-save takes too long to run. I usually notice it when the server panics (which will happen more often in source builds).

**Comment by pan93412** [comment]
Just changed the title to make this issue covers wider.

**Comment by Sytten** [comment]
I am also experiencing this since yesterday so it must be a recent change because I didn't change anything on my end.

**Comment by jhgg** [comment]
I've noticed this historically, it seems like the language server doesn't format on save in a timely manner when there is an ongoing cargo metadata running. Simple repro is in a large project/workspace edit a dependency in cargo.toml and then go to save a file right after. Format on save will take a very long time until rust analyzer acquiesces.

**Comment by lnicola** [comment]
CC #11430 which has a better analysis.

**Comment by lnicola** [comment]
@pan93412 I can reproduce this with `editor.codeActionsOnSave` set to `{ "source.fixAll.eslint": true }`.

**Comment by jhgg** [comment]
I think the issue I described is separate from this one. I don't have any code actions on save.

**Comment by lnicola** [comment]
I also managed to make RA burn a ton of CPU just by saving a file:

> [Trace - 08:54:31] Received response 'textDocument/codeAction - (227)' in 209670ms.

---

Yes, I think your issue is the thing I hinted a couple of comments above, but let's see if the OP uses code actions.

It's not very clear to me how this can be fixed. I think we're supposed to add some categories to the code actions we support and only run if [`only`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction) is missing or if some of our actions are in there.

**Comment by lnicola** [comment]
Filed #11944.

**Comment by lnicola** [comment]
#11912 was reverted in #11946, this seems to work okay now.

**Comment by jost-s** [comment]
@lnicola It is still waiting for me in Rust files while I have set
```json
"editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
  },
```
When I disable the setting, RA isn't waiting.

I'm on v0.3.1148.

**Comment by jost-s** [comment]
I haven't seen this issue lately.
Now on v0.3.1258.

**Comment by teddav** [comment]
I'm still getting the same issue, even though I removed "editor.codeActionsOnSave" from settings.json.
It's not just when saving a file. rust-analyzer doesnt work at all, even while working on the file, I can't even cmd+click, it hangs forever
