### ISSUE TITLE
No hover docs

### ISSUE THREAD

**Issue by Supetorus** [rust-analyzer/rust-analyzer#11937]
I'm not getting any pop-ups when I hover over anything, docs or errors. I've tried restarting vs, disabling all other extensions, even reinstalling vs. The vs config says hover docs is active. I've tried everything I could think of and can't see why they aren't showing up.

I am getting info in "Problems" tab, and other features such as in-line hints and error squiggles.

**Comment by lnicola** [comment]
Does it happen in a new project? Is there anything particular to your setup?

**Comment by Supetorus** [comment]
I have a folder open with multiple cargo projects. This cargo project is just a freshly generated one and I'm writing in src/main.rs.

**Comment by lnicola** [comment]
Do you have any errors in here?

![image](https://user-images.githubusercontent.com/308347/162487024-a97d71d2-c16d-4884-b91b-409706c7369b.png)

Does it still happen if you open a Rust project (instead of a folder with more than one)?

Can you post a screenshot?

**Comment by Supetorus** [comment]
I tried opening just a rust project, didn't change anything.
There isn't any output for Rust Analyzer Language Server.
Not sure what you want screenshots of, it just looks like code without a pop up. I took this screenshot and introduced an error for demonstration.
![image](https://user-images.githubusercontent.com/66396555/162499057-a5ace951-eb2b-4b4e-b9a1-e538cb44be74.png)

**Comment by lnicola** [comment]
Strange, I can only reproduce this with `"editor.hover.enabled": false`. Can you set `"rust-analyzer.trace.server": "verbose"`, then check the output in `Rust Analyzer Language Server Trace` (no need to reload the window)? There should be something like

```
[Trace - 21:21:33] Sending request 'textDocument/hover - (27)'.
Params: {
    "textDocument": {
        "uri": "file:///~/Projects/rust-analyzer/crates/syntax/src/ast/node_ext.rs"
    },
    "position": {
        "line": 9,
        "character": 6
    }
}

[Trace - 21:21:33] Received response 'textDocument/hover - (27)' in 10ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "\n```rust\nextern crate rowan\n```\n\n---\n\nA generic library for lossless syntax trees.\nSee `examples/s_expressions.rs` for a tutorial."
    },
    "range": {
        "start": {
            "line": 9,
            "character": 4
        },
        "end": {
            "line": 9,
            "character": 9
        }
    }
}
```

**Comment by Supetorus** [comment]
I did that and searched for "textDocument/hover" and got 0 results.

**Comment by lnicola** [comment]
Are you sure you didn't disable `editor.hover.enabled`?

**Comment by Supetorus** [comment]
Aha, that was it. I had checked the rust-analyzer>Hover:documentation and that was checked but I didn't know about the editor.hover.enabled. 

I have one other quick question if that's okay before this thread is closed. The error highlighting and problems don't seem to calculate until I save the file. Is there a way to make it update more often so it shows errors as I'm typing?

**Comment by lnicola** [comment]
Those are the cargo check diagnostics, which run when saving the file. You can enable auto-save, but I advise against it (it's a big waste of CPU time).

Instead, you can enable our experimental diagnostics. They don't don't always work well, but there's one for functions called with an invalid number of parameters, one for missing struct fields and one for type mismatches. You can also set up highlighting for unresolved references (I can't show how, but I think there's an example in the manual). This way you can see when you made a typo.

The native diagnostics work a bit differently: they only run for the open files. But overall I think they're pretty useful.

**Comment by Supetorus** [comment]
Awesome, thank you!

**Comment by lnicola** [comment]
These are the settings I mentioned:

```json
    "editor.semanticTokenColorCustomizations": {
        "rules": {
            "unresolvedReference": "#ff0000",
        },
    },
    "rust-analyzer.diagnostics.enableExperimental": true
```
