### ISSUE TITLE
Do not skip character to right of type annotation when navigating with vscode vim extension.

### ISSUE THREAD

**Issue by tlietz** [rust-analyzer/rust-analyzer#11949]
When navigating the cursor through the type annotations with the vscode vim extension, it skips the character directly to the right of the type annotations:

https://user-images.githubusercontent.com/25965706/162586393-7f3a3d5f-5058-4349-908f-11397e617225.mov

Is this something that can be dealt with in rust-analyzer, or is it a problem for the vim extension?

**rust-analyzer version**: 0.2.1002
**rustc version**: rustc 1.60.0 (7737e0b5c 2022-04-04)

**Comment by lnicola** [comment]
Does it still happen if you disable RA?

**Comment by lnicola** [comment]
I think this is how the inlay hints work. Even without the Vim extension the cursor moves ina weird way around them, depending on the direction you're coming from.

You could also try with another implementation of the hints (the TS extension has them, disabled by default IIRC).

**Comment by Veykril** [comment]
This isn't something we control but what VSCode does in regards to inlay hints.
