### ISSUE TITLE
Macro expansion produces syntax nodes that dont exist in the current file

### ISSUE THREAD

**Issue by Lapz** [rust-analyzer/rust-analyzer#1196]
Macro expansion produces syntax nodes that dont exist in the current file which causes a panic in the tests definded in ty. To work around this I've added a boolean flag to workaround the panic.

In the future we need to remove the hack specifically we need to look at

- [ ] replacing local ptrs in source map with global ptrs
- [ ] Add macro-generated exprs to a global sourcemap

**Comment by matklad** [comment]
This actually was fixed a while ago!
