### ISSUE TITLE
GIve nice error in TypeScript extension if `ra_lsp_server` not in PATH

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1199]
See https://github.com/rust-analyzer/rust-analyzer/issues/1198.

This should be implemented somewhere around here : https://github.com/rust-analyzer/rust-analyzer/blob/e2835b46f6928eda21b7edb44f305f20473a3a98/editors/code/src/server.ts#L22

**Comment by kiljacken** [comment]
Would this be considered fixed after #2714?
