### ISSUE TITLE
self suport for goto definition?

### ISSUE THREAD

**Issue by Dushistov** [rust-analyzer/rust-analyzer#1204]
For simple code bellow,
it is possible jump from `Boo` in ` fn f(&self, _: Boo) {}` to `struct Boo;`,
also it possible to jump from `Self` in ` fn new() -> Self` to `struct Foo;`,
but for some reason it is impossible to jump from `self` in ` fn f(&self, _: Boo) {}`
to `struct Foo;`

I use 6009af9b7c1270e612b3a21118283b9bc6925aac

```Rust
struct Foo;

struct Boo;

impl Foo {
    fn new() -> Self {
        Foo
    }

    fn f(&self, _: Boo) {}
}
```

**Comment by flodiebold** [comment]
I don't think go to definition should go to the *type* of `self`, similar to how in
```rust
fn f(foo: Foo) {}
```
go to definition for `foo` doesn't go to the type `Foo`.

*Go to type definition* on the other hand should do that, and I would guess that with #1203 merged this should actually work now?

**Comment by kjeremy** [comment]
It does not currently go to the typedef of `self`.

**Comment by umanwizard** [comment]
@flodiebold Bumping this -- go to type does not work for me on `&mut self` and similar params.

**Comment by lnicola** [comment]
Go to type definition seems to work now. Even if it's older, closing in favour of #4912, which has more technical details.
