### ISSUE TITLE
Assist: move guard to arm body and back

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1206]
Add assist to change this:

```
return match first_char {
            '\t' | '\n' | '\'' => Err(UnescapeCharError::EscapeOnlyChar),
            '\r' if chars.clone().next() == Some('\n') => Err(UnescapeCharError::EscapeOnlyChar),
            '\r' => Err(UnescapeCharError::BareCarriageReturn),
            _ => Ok(first_char),
        }
```

to this

```
return match first_char {
            '\t' | '\n' | '\'' => Err(UnescapeCharError::EscapeOnlyChar),
            '\r' => if chars.clone().next() == Some('\n')  { Err(UnescapeCharError::EscapeOnlyChar) },
            '\r' => Err(UnescapeCharError::BareCarriageReturn),
            _ => Ok(first_char),
        }
```

The assists are added here: https://github.com/rust-analyzer/rust-analyzer/blob/4e49dc2914492fe97eb7d65ae36c1452413af1eb/crates/ra_assists/src/lib.rs

See https://github.com/rust-analyzer/rust-analyzer/pull/1122 for an example

**Comment by JeanMertz** [comment]
I was wondering, what's the use case for wanting this?

At first I thought this was to go from arm body to a match guard, which seems useful, but the other way around, I'm not sure.

Also, after applying the fix, wouldn't the second `'\r'` match arm become unreachable?

**Comment by matklad** [comment]
>I was wondering, what's the use case for wanting this?

It is occasionally useful when, for example, you want to write a complex condition that moves out thigs, or, as in this case, when you realise that you need an `else` branch as well.

>Also, after applying the fix, wouldn't the second '\r' match arm become unreachable?

It will, yeah, and you'll have to manually remove it and add an appropriate `else` branch. Assists should not create valid code, they are there to just help you transform things without typing out stuff yourself. 

>At first I thought this was to go from arm body to a match guard

We also should add this! The original issue is fixed, but let's keep it open until we implement refactoring in the opposite direction

**Comment by unrealhoang** [comment]
Should we create another assist or we should use the same assist with positional cursor detection?

**Comment by matklad** [comment]
It should be another assist, but it makes sense to put it into the same file

**Comment by theotherphil** [comment]
It looks like these two assists are now available in https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_assists/src/move_guard.rs. Please could someone with perms close this issue if so.

**Comment by matklad** [comment]
Oh, indeed, thanks!
