### ISSUE TITLE
Switch from `std::collections::Hash[Map|Set]` to rustc_hash

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#121]
https://github.com/rust-lang-nursery/rustc-hash

**Comment by matklad** [comment]
This should be faster

**Comment by mominul** [comment]
I'd like to take this issue!

**Comment by mominul** [comment]
I have found the uses of `HashMap` in `ra_analysis`, `ra_editor`, `ra_lsp_server`, `salsa` and `tools` crate. Do we need to replace the usage in `tools` and in `salsa` crate though it's going to be replaced?

**Comment by matklad** [comment]
No, let's use std in salsa (b/c we are getting rid of it anyway) and in tools (runtime performance does not matter here, but one less dep will lead to faster compile times)
