### ISSUE TITLE
Failed to resolve module name with raw name

### ISSUE THREAD

**Issue by max-frai** [rust-analyzer/rust-analyzer#1211]
I have file/module with name `match` and rust-analyzer fails to find it:

<img width="252" alt="изображение" src="https://user-images.githubusercontent.com/24208746/56804601-fa61ab80-682e-11e9-8c9a-6d92444d9b11.png">

**Comment by andreevlex** [comment]
some problem.

**Comment by matklad** [comment]
Some pointers:

The relevant function is here:

https://github.com/rust-analyzer/rust-analyzer/blob/cd1ff2e2a11dd781e051060c650537802dfbbe99/crates/ra_hir/src/nameres/collector.rs#L634-L666

It doesn't handle raw identifiers and `#[path]` attributes, but it should be possible to add. The inputs to this function are from [`ModuleData`](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_hir/src/nameres/raw.rs#L128-L132) struct.  So, when we construct `ModuleData`, we should pay a closer attention to raw identifiers and attributes

**Comment by matklad** [comment]
Oh, and example tests for modules are here: 

https://github.com/rust-analyzer/rust-analyzer/blob/cd1ff2e2a11dd781e051060c650537802dfbbe99/crates/ra_hir/src/nameres/tests.rs#L316-L339

https://github.com/rust-analyzer/rust-analyzer/blob/cd1ff2e2a11dd781e051060c650537802dfbbe99/crates/ra_hir/src/nameres/tests.rs#L559-L576

We are going to extend this logic a bit, so it makes sense to move this tests and all new tests in a new test submodule, `mods_and_files`

**Comment by andreevlex** [comment]
`#[path]` attributes where read docs?

**Comment by matklad** [comment]
https://doc.rust-lang.org/reference/items/modules.html#the-path-attribute

IntelliJ test suite might be useful as well:

https://github.com/intellij-rust/intellij-rust/blob/9e9969d8692e2ddbbe5adaeb74669a81e2d82b6d/src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt#L63-L341

**Comment by andreevlex** [comment]
after #1499 need more support `#[path]`

- [ ] `#[path ="./foo.rs"]`
- [ ]  `#[path ="../foo.rs"]`
- [ ] super module with `#[path ="a"]` and module `#[path ="b.rs"]`
- [ ] super module with `#[path ="a/b"]` and module `#[path ="c.rs"]`

**Comment by andreevlex** [comment]
this issue complete.
Resolve path attributes continue in #1529
