### ISSUE TITLE
Fix tuple struct initializer parsing 

### ISSUE THREAD

**Issue by JasperDeSutter** [rust-analyzer/rust-analyzer#1218]
rustc allows initializing tuple struct fields just like a normal struct, but using field indices instead of field names.

example:
```rust
struct Weird(i32);

fn main() {
    let w = Weird { 0: 1 };
}
```

Rust analyzer currently marks the `0: 1` part as a syntax error. The message is:
> Syntax Error: expected identifierrust-analyzer

I did not find any documentation yet (must be well hidden) that describes that this should work, but rustc compiles it fine as is.

**Comment by memoryruins** [comment]
It does seem more hidden than it should be:

https://doc.rust-lang.org/stable/reference/expressions/struct-expr.html
>The following are examples of struct expressions:
```
TuplePoint(10.0, 20.0);
TuplePoint { 0: 10.0, 1: 20.0 }; // Results in the same value as the above line
```

**Comment by eupn** [comment]
@matklad should we make a new syntax kind for tuple field indices? It seems that we can't use existing `INT_NUMBER` for that.

**Comment by matklad** [comment]
@eupn, hm, I would think that `INT_NUMBER` should just work? It works for filed accesses:

```
x.a

FIELD_EXPR@[11; 14)
  PATH_EXPR@[11; 12)
    PATH@[11; 12)
      PATH_SEGMENT@[11; 12)
        NAME_REF@[11; 12)
          IDENT@[11; 12) "x"
  DOT@[12; 13) "."
  NAME_REF@[13; 14)
    IDENT@[13; 14) "a"
```

```
x.0

FIELD_EXPR@[11; 14)
  PATH_EXPR@[11; 12)
    PATH@[11; 12)
      PATH_SEGMENT@[11; 12)
        NAME_REF@[11; 12)
          IDENT@[11; 12) "x"
  DOT@[12; 13) "."
  INT_NUMBER@[13; 14) "0"
```

**Comment by eupn** [comment]
@matklad isn't `INT_NUMBER` represent a superset of numbers allowed for tuple indices? Since `INT_NUMBER` can describe numbers of a non-decimal base, using it in tuple field initialization would make the following invalid code pass ra-analyzer:
```rust
struct S(usize, usize);
let s = S { 0x00: 1, 0x01: 2 };
```

**Comment by matklad** [comment]
That should be a special-cased error at the validation layer. See `validate_field_expr_node`
