### ISSUE TITLE
[Suggestion] Investigate inline parameter hints

### ISSUE THREAD

**Issue by DJMcNab** [rust-analyzer/rust-analyzer#123]
Microsoft/vscode#16221 is the primary tracking/suggestion issue for this.

The exact design of the communication between the client and server for this feature has not been created, blocking a direct proposal in the language server protocol. This repository seems like a good place to prototype and investigate such a feature.

It has been suggested that such a feature could remove any need for explicit parameter naming at call sites in Rust, as linked in my comment in the attached issue. 

Sorry if bad formatting! Written on mobile.

**Comment by aochagavia** [comment]
Why does this need LSP support? It looks like it is already possible to implement something like this, even without changes to the LSP (see [this extension](https://github.com/lannonbr/vscode-js-annotations) for JavaScript/Typescript)

**Comment by DJMcNab** [comment]
It's more that it should be implemented directly in tsserver if it is useful, which would be better if it was an explicit feature of the lsp. It is possible to use the custom protocols, but they are non-standard and need custom clientside code for every one (although we already have a lot of that, so 🤷‍♂️)

(That extension it would still uses another copy of the typescript library, so it has to store another version of the world state to work, which is a waste of memory).

**Comment by kjeremy** [comment]
Once #110 is merged we should have the machinery available to at least get function signature info.

**Comment by DJMcNab** [comment]
Related for the goal of compiling into WASM: https://github.com/integer32llc/rust-playground/issues/188

**Comment by matklad** [comment]
Closing as this is really an editor's feature, not a language-server one.

**Comment by DJMcNab** [comment]
It's an editor feature which needs information from the language server. I might try to make a quick prototype, see how it goes.
