### ISSUE TITLE
workspace/executeCommand not supported

### ISSUE THREAD

**Issue by JeanMertz** [rust-analyzer/rust-analyzer#1232]
The [lsp-features.md](https://github.com/rust-analyzer/rust-analyzer/blob/8ee8542de23253ec29f1b817aeb975313875885d/docs/dev/lsp-features.md) file mentions that `workspace/executeCommand` is supported (specifically, `apply_code_action`):

https://github.com/rust-analyzer/rust-analyzer/blob/a71d0ecd774008bbfe8cb2215ffa6dedd5024877/docs/dev/lsp-features.md#L19-L20

I want to make rust-analyzer code actions work in Vim by updating [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim), but from what I can tell, `workspace/executeCommand` is not actually supported anymore?

I can see the `handle_execute_command` handler being removed in https://github.com/rust-analyzer/rust-analyzer/commit/8abf5363433e977c5393bb569e2a5d559cb0a602#diff-43d4f175343e385858e9f5a752c17d57L370.

Instead, from what I understand, I have to do a `textDocument/codeAction` request, pick one of the actions to perform, match on the `rust-analyzer.applySourceChange` command, and then parse the `arguments` data to apply the changes locally on the client:

https://github.com/rust-analyzer/rust-analyzer/blob/a71d0ecd774008bbfe8cb2215ffa6dedd5024877/crates/ra_lsp_server/src/main_loop/handlers.rs#L630-L633

Are my assumptions correct? If so, then I'll start adding this feature to Vim, and I guess it would make sense to uncheck the box in the supported features list, right?

**Comment by matklad** [comment]
Yeah, right, `rust-analyzer.applySourceChange` should be supported by the client. 

We need https://github.com/Microsoft/language-server-protocol/issues/724 to switch to build-in facilities for our code actions

**Comment by kjeremy** [comment]
Would it be better to move `applySourceChange` into the server and implement `workspace/executeCommand` and `workspace/applyEdit`?

**Comment by matklad** [comment]
@kjeremy  we can't do that because, because:

* we can't tell the client to open specific file (needed for unresolved modle fix)
* we can't tell the client about cursor position (needed for many intentions like add derive)

Ideally, we extend LSP with support for those use-cases, yeah.

**Comment by JeanMertz** [comment]
When [adding support for this in Vim](https://github.com/autozimu/LanguageClient-neovim/pull/815), I noticed that the client already had something similar implemented for the/a Java language server.

So apparently it's not unprecedented to leave it up to the clients to handle this (probably for the same reasons you mentioned, @matklad, the LSP spec does not provide the flexibility needed in this case).

**Comment by lnicola** [comment]
This can be closed, I think?

**Comment by matklad** [comment]
right, we don't intend to have server-side commands.

**Comment by jan-xyz** [comment]
Do I understand this right, that this is a custom implementation needed in every client? I'm coming from Neovim and basically can't use any of the code lenses (Run Test, Debug...) because it's considered a "custom extension/handler" (https://github.com/neovim/neovim/issues/14874#issuecomment-865279747) and it needs custom implementation. If that's true then it's quite sad and we are again at a point pre-LSP where each editor needs to provide custom code to fully support some features (albeit much less then before).

**Comment by matklad** [comment]
@jan-xyz you need https://github.com/simrat39/rust-tools.nvim to gain access to rust-analyzer specific extensions in neovim. If you want to see our extensions upstreamed into the protocol, show your support for corresponding issues on the lsp repo: https://github.com/microsoft/language-server-protocol/issues/created_by/matklad

**Comment by jan-xyz** [comment]
Thanks for your reply, I played around with rust-tools and it covers at least some aspect ( I can run individual tests 🤗 ) but the code lenses aren't implemented, I guess I vote and hope that Microsoft will hear our plea...

**Comment by matklad** [comment]
>( I can run individual tests hugs ) but the code lenses aren't implemented,

If this is about this functionality:

![image](https://user-images.githubusercontent.com/1711539/126894146-3001886c-6e61-4312-b1cb-a0b30956f4dd.png)

then the situation here is even more confusing. What we do here is entirely standard LSP, but still requires custom support from the client. Basically, in the LSP code lens contains a string name of the command to be executed by the client (like `"rust-analyzer.runSingle"`), and that command needs to be implemented by the client. That is, the way LSP is specced here is "invoke this custom command on the client side".

This particular feature really should have first-class support in the protocol, upstream issue is https://github.com/microsoft/language-server-protocol/issues/944

**Comment by jan-xyz** [comment]
Yes! That's the functionality, did I comment on the wrong issue? Since Neovim invokes `workspace/executeCommand` when I run those code lenses, I thought this is related to this issue.

So what a plugin like `rust-tools` needs to do is implement `rust-analyser.runSingle` on the built-in client?

**Comment by matklad** [comment]
Aha, my understanding is that shouldn't be happening, opened https://github.com/neovim/neovim/issues/15183 for that.
