### ISSUE TITLE
emacs M-x lsp for every buffer?

### ISSUE THREAD

**Issue by davemilter** [rust-analyzer/rust-analyzer#1233]
I configure things according to
https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user#emacs
and it works,
but for some reason I have to run `M-x lsp` for every file in the same crate.

For example I open `crates/ra_lsp_server/src/lib.rs` and run `M-x lsp-find-definition`,
it reports back:
```
lsp-find-definition: Capability not supported by the language server: "definitionProvider"
```
I run `M-x lsp` and then `M-x lsp-find-definition` works and I jump to `crates/ra_lsp_server/src/main_loop.rs`,
then again I run `M-x lsp-find-definition` and get:
```
lsp-find-definition: Capability not supported by the language server: "definitionProvider"
```
and again I have to run `M-x lsp` and things start work for this buffer.

Is some step missed in setup instruction and there is way to force `lsp` works for all buffer inside crate?

**Comment by matklad** [comment]
I *think* they way it is solved is that you add `lsp` to `rust-mode-hooks`. i unfortunatelly don't remmeber the precise syntax. If you happen to use spacemacs, I guess you can steal @flodiebold 's config?

https://github.com/flodiebold/dotfiles/blob/5dfb1e702eb8c0e60dab5557676414594acccf8c/emacs/.emacs.d/private/rust-rls2/packages.el#L66

**Comment by flodiebold** [comment]
It's best to refer to the emacs-lsp documentation for this: https://github.com/emacs-lsp/lsp-mode#configure-lsp-mode
Maybe we should link it from the docs.
Specifically, you probably want to do `(add-hook 'rust-mode-hook #'lsp)`.

**Comment by davemilter** [comment]
@matklad  and @flodiebold 

```
(add-hook 'rust-mode-hook #'lsp)
```

this works, but `lsp-ui` looks really strange,
it is impossible to edit text under error message (on the top with gray background),
plus sideline looks really strange and reformat code. Not sure is this lsp-ui issue,
or `ra_lsp_server` reports error about trait in some unusual way in compare with other lsp servers.

![a](https://user-images.githubusercontent.com/26097083/57184011-87ef6c00-6ebd-11e9-9a6a-c3d2fd892c26.png)

**Comment by flodiebold** [comment]
`lsp-ui` issue, not related to RA
