### ISSUE TITLE
Add command to run `cargo check` and show errors/warnings in the editor

### ISSUE THREAD

**Issue by aochagavia** [rust-analyzer/rust-analyzer#124]
Without this feature, you have to run `cargo check` in your terminal and go back and forth from the terminal to the editor to fix the issues in your code. It would be great to take the output of `cargo check` and somehow integrate the errors and warning in the editor itself (i.e. the same way we show syntax errors, for instance)

**Comment by matklad** [comment]
This actually works right now: there's `Rust run` action in VS Code which does this (a custom extension to LSP).
