### ISSUE TITLE
Incorrect name resolution about mbe

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#1243]
When parsing [this](https://github.com/rust-lang-nursery/rustc-perf/tree/6906bc305feb0d9dc52aff6a1700effd87c282db/collector/benchmarks/packed-simd) crate, there is an error of macro parsing: 

```
WARN [ra_hir::ids] fail on macro_parse: (reason: NoMatchingRule) macro call [file: "src/v16.rs"] : impl_swap_bytes ! ( [ i8 ; 2 ] : i8x2 | test_v16 ) ;
```

There are two marco_rules with that name in the same crate which contents are different:

https://github.com/rust-lang-nursery/rustc-perf/search?q=impl_swap_bytes&unscoped_q=impl_swap_bytes

And in [lib.rs](https://github.com/rust-lang-nursery/rustc-perf/blob/6906bc305feb0d9dc52aff6a1700effd87c282db/collector/benchmarks/packed-simd/src/lib.rs#L261-L264):

```
#[macro_use]
mod api;
mod codegen;
mod sealed;
```
which use `macro_use` to control the visibility of the macros.

So maybe `hir` found the wrong macro to expand ?

**Comment by bjorn3** [comment]
I can't reproduce this with the latest rust-analyzer.
