### ISSUE TITLE
Code actions are slow

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1244]
We spend quite a chunk of time on code actions:

```
        166ms - handle_code_action
        174ms - handle_code_action
        138ms - handle_code_action
        191ms - handle_code_action
```

This profiling comes from here:

https://github.com/rust-analyzer/rust-analyzer/blob/9c302980e386734472f9bae50a0db59247cba623/crates/ra_lsp_server/src/main_loop/handlers.rs#L634

My gut feeling is that code actions could be a an order of magnitude faster. We need to investigate this slowness, and fix it!. I think just adding more `let _p = profile` calls should help us to locate bottleneck. 

Here's the code that is called by `handle_code_action`:

https://github.com/rust-analyzer/rust-analyzer/blob/9c302980e386734472f9bae50a0db59247cba623/crates/ra_assists/src/lib.rs#L64

And here are some docs about our profiling infra:

https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/README.md#profiling

**Comment by marcogroppo** [comment]
Apparently most of this time is usually spent computing diagnostics: 

https://github.com/rust-analyzer/rust-analyzer/blob/9c302980e386734472f9bae50a0db59247cba623/crates/ra_lsp_server/src/main_loop/handlers.rs#L640
https://github.com/rust-analyzer/rust-analyzer/blob/9c302980e386734472f9bae50a0db59247cba623/crates/ra_ide_api/src/diagnostics.rs#L20

**Comment by matklad** [comment]
@marcogroppo we definitely should add a profile call for `fn diagnostics`. Would you send a PR. I also wonder what exactly is slow about them?

**Comment by marcogroppo** [comment]
@matklad I'm seeing very high values for `handle_code_action` when loading a file in the IDE. Here, most of the time is spent in `diagnostics` (specifically in `Module::diagnostics`). Once the file has been loaded, when I click on a source code line, `handle_code_action` takes usually less than 10ms. Just to understand: you're observing these values before or after loading the file?

**Comment by marcogroppo** [comment]
@matklad I've found a impl block where `handle_code_action` is (relatively) slow every time a click on a source code line: `ra_syntax/src/string_lexing.rs:47-85` - but it's still faster than what you're observing. Here is my profiling info when clicking on a source code line in this range: https://gist.github.com/marcogroppo/72c71c9506dca2a8f3744360dff9e237 - here most of the time is taken by the `add_missing_impl_members` assist.

**Comment by matklad** [comment]
Interesting! `add_missing_impl_members` definitely should be a fast-ish assist

**Comment by kjeremy** [comment]
Here's a trace that I'm seeing quite a bit of when running the server under a debug session:

- 4929ms - handle_code_action
  - 4928ms - diagnostics
    - 0ms - diagnostics::syntax_errors
    - 4384ms - module diagnostics
      - 488ms - module diagnostics
        - 487ms - function diagnostics
        - 0ms - function diagnostics
        - 0ms - function diagnostics
      - 3896ms - function diagnostics

Typically the first `Function::diagnostics` eats up the most time (maybe due to `db.infer`?)

**Comment by matklad** [comment]
>Typically the first Function::diagnostics eats up the most time (maybe due to db.infer?)

Let's add a profiling call! I would think that `infer`, and diagnostics in general, would be kicked by diagnostics notification, eagarly after modification, but it might not be the case.

https://crates.io/crates/cpuprofiler is a useful tool to dig deeply into perf issues

**Comment by kjeremy** [comment]
Looks like the CPU profiler for gperftools doesn't work under windows.

**Comment by kjeremy** [comment]
I'm seeing a hot spot from `lookup_method`. It looks like chalk can take up to 4 seconds to solve trait method candidates. On runs where chalk does not I still see `iterate_inherent_methods` take a few 100ms

**Comment by flodiebold** [comment]
Hm, this might be the same problem I'm currently looking into then -- I've implemented support for where clauses, and now some queries basically never finish. There seems to be some behavior at least quadratic in the number of impls in the logic lowering code (or maybe our integration is somehow causing it).

**Comment by matklad** [comment]
closing in favor of https://github.com/rust-analyzer/rust-analyzer/issues/1309
