### ISSUE TITLE
self.advance called in assert!

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#1246]
Is it weird that `advance(&mut self)` is called in an `assert!`? 

https://github.com/rust-analyzer/rust-analyzer/blob/5cdf525caa51311515854c4dd398d3fb907d1368/crates/ra_syntax/src/string_lexing.rs#L50-L60

**Comment by matklad** [comment]
It's OK: in rust, unlike other langauges, assert is always executed. If it were debug_assert, it would had been a bug indeed!

**Comment by kjeremy** [comment]
Great thanks!
