### ISSUE TITLE
Implement Token! macro for syntax kinds, a-la syn

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1248]
Syn has a lovely `Token!` macro for defining tokens without naming them: `Token![,]`:

https://docs.rs/syn/0.15.33/syn/macro.Token.html

We should add a similar macro for our SyntaxKind, to make code like this more readable:

https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_ide_api/src/extend_selection.rs#L137-L138

**Comment by matklad** [comment]
Though, I am not sure if macros are allowed in patterns. If they aren't, then probably we should stick with the current approach.

**Comment by edwin0cheng** [comment]
Macro is allowed in pattern :)

**Comment by pasa** [comment]
Hi. I've made PR with T! macro apply for whole project. I hope it will be helpful. 
In addition I figured out that `T![(]` and `T![)]` are not working so I've changed them to `T!['(']` and `T![')']`.

**Comment by lnicola** [comment]
Can this be closed?
