### ISSUE TITLE
Code action: Merge match branches

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#1250]
I've often wished for this after using "fill match branches":
```rust
match x {
    Foo => (),<|>
    Bar => (),
    Baz => (),
}
```
->
```rust
match x {
    Foo |
    Bar => (),<|>
    Baz => (),
}
```
I think it should only apply if the branch expressions are the same, and only merge two branches (you can repeat it to merge more then). The reverse would of course also be useful.

**Comment by matklad** [comment]
Note that we currently don't have a good API to check if two arms are equivalent, but I guess for starters "compare lengths, then compare text" would work

**Comment by flodiebold** [comment]
> only merge two branches
Actually, I guess if you select a range including multiple branches it could merge all of them...

**Comment by theotherphil** [comment]
I'd like to try this issue.
