### ISSUE TITLE
Diagnostics: wrap return value in Ok() if required

### ISSUE THREAD

**Issue by JeanMertz** [rust-analyzer/rust-analyzer#1254]
Sometimes you're implementing a function that returns some `Result<T>`. When you're done, you notice that you returned `T` at the end, instead of `Ok(T)`. It would be nice if you could quickly wrap `T` in that case.

It's not a huge time saver, but sometimes you return large structs, and so it takes you a few selects + keystrokes to turn it into an `Ok(T { ..., ... })`.

**Comment by matklad** [comment]
This probably should be a fix for a type-error diagnostic rather than code action.

**Comment by JeanMertz** [comment]
> This probably should be a fix for a type-error diagnostic

Ah yes, that makes sense.

**Comment by theotherphil** [comment]
I'd like to try this issue.

**Comment by matklad** [comment]
This should be added to 

https://github.com/rust-analyzer/rust-analyzer/blob/ad63fbe61a2e024bab8baadc22863a0795d20a95/crates/ra_ide_api/src/diagnostics.rs

and

https://github.com/rust-analyzer/rust-analyzer/blob/ad63fbe61a2e024bab8baadc22863a0795d20a95/crates/ra_hir/src/diagnostics.rs

Specifically, I think we should special case a "type mismatch" diagnostics (which doesn't exist anyway yet) to something like `MissingOkInTailExpr` diagnostic. In hir diagnostics, it should have a definition, ra_ide_api diagnostics should provide a relevant fix, and a test.

The diagnostic itself should be produced by a validator, after type inference: https://github.com/rust-analyzer/rust-analyzer/blob/ad63fbe61a2e024bab8baadc22863a0795d20a95/crates/ra_hir/src/expr/validation.rs

**Comment by theotherphil** [comment]
Thanks for the tips @matklad.

**Comment by theotherphil** [comment]
@matklad I've got a hopefully easy question: how do I go about comparing the return type from a function with the type of an expression here? 

https://github.com/theotherphil/rust-analyzer/blob/wrap/crates/ra_hir/src/expr/validation.rs#L102

**Comment by matklad** [comment]
@theotherphil `Ty` implemnts `Eq`, so you should be able to use `==`. So you should check that fn's type is `Ty::Appply(ApplicationTy { ctor, params})`, check that `ctor` is an `Adt::Enum` which is equal(`==`) to the result of resolving `std::result::Result`, and that the first element of `params` is equal(`==`) to the expr type.

**Comment by theotherphil** [comment]
This is now fixed (the linked PR was closed without merging, but @matklad rebased and merged in https://github.com/rust-analyzer/rust-analyzer/pull/1734)
