### ISSUE TITLE
Make code binary dynamically changable

### ISSUE THREAD

**Issue by nycex** [rust-analyzer/rust-analyzer#1260]
I use vscodium and the binary for it isn't code, but vscodium. But i think the rest should work fine for it. So it would be good if you could change it, to make it work for vscodium without editing the crates/tools/src/main.rs

**Comment by matklad** [comment]
Good suggestions!

I think we can do even better and just document fully the manual way of installing extension. This way, we'll help all people with unconventional setups, and make troubleshooting installation easier as well.

Added the docs in https://github.com/rust-analyzer/rust-analyzer/pull/1261
