### ISSUE TITLE
Infinite loop in trait solving

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#1269]
When i try to run `ra_cli analysis-stats` on `rust-analysis` source code, it seem to be going in infinite loop inside https://github.com/rust-analyzer/rust-analyzer/blob/b22614f0b500c351d3abf33a4ed6beaea6861bca/crates/ra_hir/src/ty/traits.rs#L94

Is it because of the `fuse` things in Chalk we are talking in Zulip , or other reasons ?

**Comment by flodiebold** [comment]
It's not an infinite loop, just a very long one ;)

Are you on current master? I thought I made sure that with #1266 it worked again.

**Comment by edwin0cheng** [comment]
Yes i am in master (b22614f0b500c351d3abf33a4ed6beaea6861bca) , and i waited over 10 mins :), although my pc is quite old. (Windows i5-4440).

**Comment by flodiebold** [comment]
Hm, I must have accidentally tested with the wrong binary :( I'll look into it.

**Comment by flodiebold** [comment]
#1270 should fix this for rust-analyzer for now, at least it works for me again now. We need rust-lang/chalk#227 or something like that to make sure this can never happen, though.

**Comment by edwin0cheng** [comment]
Closed #1270
