### ISSUE TITLE
Consider using ASDL to define AST structure

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1279]
See https://www.oilshell.org/blog/2016/12/11.html and https://www.cs.princeton.edu/research/techreps/TR-554-97.

This ASDL could replace parts of our grammar.ron

**Comment by matklad** [comment]
BTW, even if we don't use ASDL, having an ASDL parser in the ecosystem seems like a good idea. So if anyone wants to take a stab at it, please go ahead!

**Comment by pasa** [comment]
It's interesting. I will take a look.

**Comment by pasa** [comment]
Hi!
I've implemented the first draft of the asdl parser [here](https://github.com/pasa/asdl-rs).
For now I'm trying to imagine the code generation process. I would like to keep a possibility to generate code for different languages so it should be some kind of template processing like in rust-analyzer. So it will be pretty much similar with generated.rs.tera. 

The only problem I see is how to represent an information of traits like `NameOwner`. Seems that asdl is not suited for this information.

I see to possibilities here.
1. make extension for asdl notation to keep this language or project specific information.
2. keep such information in some external file. In this case we should synchronize names in this file and asdl file. Not very convenient.

Do you have any ideas?

**Comment by jens1o** [comment]
What are the advantages for this pretty major refactor? Does it increase performance?

**Comment by matklad** [comment]
@jens1o it should have zero impact on performance. The primary motivation here is to move AST defitition from home-grown solution to a (admittedly niche) standard.

**Comment by pasa** [comment]
@matklad are there some issues that prevent to merge my PR? Is there something that I need to do?

**Comment by matklad** [comment]
The only issue is the lack of time on my side :(

**Comment by pasa** [comment]
> The only issue is the lack of time on my side :(
Ok. I'll wait.  It's easy! :smile:

**Comment by lnicola** [comment]
@matklad this should probably be closed.
