### ISSUE TITLE
`CargoWorkspace` do not contains non-normal dependencies of dependent crates

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#1282]
In cargo_workspace.rs:

https://github.com/rust-analyzer/rust-analyzer/blob/f7112371ee646d8ecc68861e9fe832af9729878e/crates/ra_project_model/src/cargo_workspace.rs#L159-L167

We add the resolved dependencies in each packages. The ` meta.resolve` is from `cargo-metadata` crate, which is de-serialized from following command :
```
cargo metadata --format-version 1 --all-features
```

For example, It is the output json of "packages" part of `parking lot`:
<details>

```
{
	"name": "parking_lot",
	"version": "0.8.0",
	"id": "parking_lot 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)",
	"license": "Apache-2.0/MIT",
	"license_file": null,
	"description": "More compact and efficient implementations of the standard synchronization primitives.",
	"source": "registry+https://github.com/rust-lang/crates.io-index",
	"dependencies": [
		{
			"name": "lock_api",
			"source": "registry+https://github.com/rust-lang/crates.io-index",
			"req": "^0.2",
			"kind": null,
			"rename": null,
			"optional": false,
			"uses_default_features": true,
			"features": [],
			"target": null,
			"registry": null
		},
		{
			"name": "parking_lot_core",
			"source": "registry+https://github.com/rust-lang/crates.io-index",
			"req": "^0.5",
			"kind": null,
			"rename": null,
			"optional": false,
			"uses_default_features": true,
			"features": [],
			"target": null,
			"registry": null
		},
		{
			"name": "bincode",
			"source": "registry+https://github.com/rust-lang/crates.io-index",
			"req": "^1.1.3",
			"kind": "dev",
			"rename": null,
			"optional": false,
			"uses_default_features": true,
			"features": [],
			"target": null,
			"registry": null
		},
		{
			"name": "lazy_static",
			"source": "registry+https://github.com/rust-lang/crates.io-index",
			"req": "^1.0",
			"kind": "dev",
			"rename": null,
			"optional": false,
			"uses_default_features": true,
			"features": [],
			"target": null,
			"registry": null
		},
		{
			"name": "rand",
			"source": "registry+https://github.com/rust-lang/crates.io-index",
			"req": "^0.6",
			"kind": "dev",
			"rename": null,
			"optional": false,
			"uses_default_features": true,
			"features": [],
			"target": null,
			"registry": null
		},
		{
			"name": "rustc_version",
			"source": "registry+https://github.com/rust-lang/crates.io-index",
			"req": "^0.2",
			"kind": "build",
			"rename": null,
			"optional": false,
			"uses_default_features": true,
			"features": [],
			"target": null,
			"registry": null
		}
	],
...
```

</details>

However, in the output json of "Resolved" part:

<details>

```
resolve": {
    "nodes": [   	
    ...
	{
		"id": "parking_lot 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)",
		"dependencies": [
			"rustc_version 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)",
			"parking_lot_core 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)",
			"lock_api 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)"
		],
		"deps": [
			{
				"name": "rustc_version",
				"pkg": "rustc_version 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)"
			},
			{
				"name": "parking_lot_core",
				"pkg": "parking_lot_core 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)"
			},
			{
				"name": "lock_api",
				"pkg": "lock_api 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)"
			}
		],
		"features": [
			"default"
		]
	},
	
```
</details>

It do not contains any non-Normal dependencies. (note that there is no `lazy_static` crate, which should be a `dev` dep). So the `CargoWorkspace` do not have any non-Normal dependencies too. So, it is a bug as we should include dev-depdendencies into our crate graph by default.

**Comment by matklad** [comment]
Huh, that's interesting!

So, we depend on parking lot, and parking lot has a dev-dependency on lazy_static.

I think it is reasonable that we don't see a lazy-static dependency in metadata, because it's not our dev dep. So I guess the solution to the original probelm in #1277 is to disable `#[cfg(test)]` code *for dependencies*....

**Comment by edwin0cheng** [comment]
> I think it is reasonable that we don't see a lazy-static dependency in metadata, because it's not our dev dep. So I guess the solution to the original probelm in #1277 is to disable #[cfg(test)] code for dependencies....

Yes, agreed. However, do you think any other configurations we have to disable for dependencies too? How about some feature gates in dependencies which depends on other crates? Do we have to wait for the proper handling of `#[cfg(xxx)]` to solve this problem completely ?

**Comment by matklad** [comment]
> In general, do we have to wait for the proper handling of #[cfg(xxx)] to solve this problem completely ?

Yeah, we should just solve the `cfg`. Note that we already have the almost all neccessary infra in place.

The fix here would be:

* to add `Cfg` struct to each crate in CrageGraph
* for starters, set only `test` for local crates
* In `RawItem` collector, skip items under `cfg(test)` if the test is disabled

**Comment by matklad** [comment]
> disable #[cfg(test)] code for dependencies....

We now do this.
