### ISSUE TITLE
Constructing a union causes error "fill structure fields"

### ISSUE THREAD

**Issue by LPGhatguy** [rust-analyzer/rust-analyzer#1285]
Given this code:

```rust
union Foo {
    a: f32,
    b: i32,
}

fn foo() -> Foo {
    Foo {
        a: 32.0,
    }
}
```

rust-analyzer emits a warning on line 7, column 9 indicating that I should fill my struct fields. I hit this running rust-analyzer on a codebase using [Ash](https://crates.io/crates/ash), which is fairly union-heavy.

**Comment by kjeremy** [comment]
Can't reproduce. I think @matklad fixed this with the recent `union` support.
