### ISSUE TITLE
Better syntax highlighting

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1294]
[TreeSitter](https://github.com/georgewfraser/vscode-tree-sitter/blob/e4602179410eb53036e721b3d31ceb366e564b18/src/extension.ts) plugin shows that it is actually possible to implement decent highlighting with the current API.

Things we should steal:

* visibleRanges support
* VS.ThemeColor

Note that we need to make our internal highlightling infra "enterprise-ready" as well :-)

**Comment by matklad** [comment]
(Note: it is E-everything, because this is a large issue with isolated easy parts and harder parts)

**Comment by kjeremy** [comment]
There was talk of a semantic LSP extension here: https://github.com/microsoft/vscode-languageserver-node/issues/368

**Comment by killercup** [comment]
Any interest for adding a mode with binding-specific coloring? If bindings and their use cases have unique IDs, picking colors them might be as simple as using the ID as seed in a function like [this](https://gist.github.com/bendc/76c48ce53299e6078a76).

**Comment by matklad** [comment]
>Any interest in adding a mode with binding-specific coloring? I

That is, coloring each funcition parameter in unique color? We can do that, yeah.

**Comment by killercup** [comment]
Yeah, function parameter, variable bindings, maybe also module names

**Comment by univerz** [comment]
> picking colors them might be as simple as using the ID as seed in a function like this.

KDevelop have state of the art semantic highlighting and afaik was first IDE doing it (~2009). Through the years, they tried several approaches - I would like to suggest to look [there](https://github.com/KDE/kdevelop/blob/4eba104df6e639c67a18698f8206d08a48adf0c9/kdevplatform/language/highlighting/codehighlighting.cpp#L225) for [inspiration](https://github.com/KDE/kdevelop/blob/4eba104df6e639c67a18698f8206d08a48adf0c9/kdevplatform/language/highlighting/colorcache.cpp#L106).

Semantic highliting looks funny at first, but I'm half-blind without it now.

**Comment by matklad** [comment]
>and afaik was first IDE doing it

That's true! Though, IntelliJ has this feature as well. If only they named it less ambitious... Like, there's much more to semantic that coloring different references differently... The basic rule of semantic highlighting in a general sense is that the reference should be colored in the same color as the corresponding definition.

**Comment by univerz** [comment]
> ...

True. I just wanted to point out that generating readable and good-looking colors, in sufficient quantity, is not a purely programming problem and there is more "science" behind it (i'm not an expert myself).

**Comment by chriskrycho** [comment]
It'd also be appreciated if the colors were derived from the user's existing theme choice. I really don't want to have to supply custom colors for a *specific editor plugin*; I want my editor's theming to drive everything.

**Comment by lnicola** [comment]
https://github.com/microsoft/vscode-languageserver-node/issues/368 would help here, but I don't think there's much the extension can do.

The current colors are based on the default VS Code themes.
