### ISSUE TITLE
Possible typo in the README

### ISSUE THREAD

**Issue by TomasHubelbauer** [rust-analyzer/rust-analyzer#1298]
> latest stable npm and VS Code for VS Code extension (code should be in path)

Is this supposed to say Rust for VS Code extension? I have no experience with rust-analyzer, but the quoted line made me do a double take and I don't think it makes sense as-is and probably refers to the Rust extension, right? If correct, I am happy to PR, but I am not sure yet.

**Comment by DJMcNab** [comment]
I think it means we only support the latest version of visual studio code, hence you need the latest (stable) version of visual studio code installed for the visual studio code extension

**Comment by TomasHubelbauer** [comment]
Oh I see now. Had trouble parsing that before. Thanks
