### ISSUE TITLE
gen_lsp_server: Can't get a minimal setup working

### ISSUE THREAD

**Issue by dmoonfire** [rust-analyzer/rust-analyzer#1304]
I'm trying to create a minimal LSP server using `gen_lsp_server` crate. However when I use the example code from the [docs](https://docs.rs/gen_lsp_server/0.1.0/gen_lsp_server/), it doesn't compile. I've tried a few things to get it working but I seem to be stuck. Any or all help would be appreciative. I'm trying basically get something that handles basic class that I can extend for my own language service.

I have a minimal example in https://github.com/dmoonfire/minimal-rust-lsp

Thank You.

## Changes from the Example

- I copied the dependencies from the [gen_lsp_server's Cargo.toml](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/gen_lsp_server/Cargo.toml) and added the [gen_lsp_server](https://crates.io/crates/gen_lsp_server) to the dependencies.
- I switched the `lsp-types` to `languageserver-types 0.51.1` because it failed the build and I saw the line in the `cargo build` command.
- I removed the `extern crate` lines.
- I removed the `run_server` from the `use` line since we use `gen_lsp_server::run_server` directly.

## Current Problems

When I try to build the example, I get this:

```
/*
error[E0631]: type mismatch in function arguments
  --> src\main.rs:12:5
   |
12 |       gen_lsp_server::run_server(
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected signature of `fn(languageserver_types::InitializeParams, &crossbeam_channel::internal::channel::Receiver<gen_lsp_server::RawMessage>, &crossbeam_channel::internal::channel::Sender<gen_lsp_serv
er::RawMessage>) -> _`
...
22 | / fn main_loop(
23 | |     _params: InitializeParams,
24 | |     receiver: &Receiver<RawMessage>,
25 | |     sender: &Sender<RawMessage>,
...  |
51 | |     Ok(())
52 | | }
   | |_- found signature of `for<'r, 's> fn(languageserver_types::InitializeParams, &'r crossbeam_channel::Receiver<gen_lsp_server::RawMessage>, &'s crossbeam_channel::Sender<gen_lsp_server::RawMessage>) -> _`
   |
   = note: required by `gen_lsp_server::run_server`

error[E0308]: mismatched types
  --> src\main.rs:30:54
   |
30 |                 let req = match handle_shutdown(req, sender) {
   |                                                      ^^^^^^ expected struct `crossbeam_channel::internal::channel::Sender`, found struct `crossbeam_channel::Sender`
   |
   = note: expected type `&crossbeam_channel::internal::channel::Sender<gen_lsp_server::RawMessage>`
              found type `&crossbeam_channel::Sender<gen_lsp_server::RawMessage>`

error: aborting due to 2 previous errors
    */
```

It appears to be an issue of `crossbeam_channel::internal:channel` references instead of `crossbeam_channel`.

## Versions

```
> cargo --version
cargo 1.36.0-nightly (c4fcfb725 2019-05-15)
> rustup show
Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-2019-05-21-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

nightly-2019-05-21-x86_64-pc-windows-msvc (default)
rustc 1.36.0-nightly (d35181ad8 2019-05-20)

>
```

**Comment by matklad** [comment]
Yeah, the `gen_lsp_server` is not really `gen` at the moment: it works inside rust-analyzer, but I wasn't really good at creating a proper API for it. That said, I've published the current code as 0.2 right now, it might be useful still.

Your specific error looks like a mismatch between versions of crossbeam_channel. Could you check the lockfile and see if you have two different version there?

**Comment by dmoonfire** [comment]
I did have two versions of `crossbeam_channel` but didn't notice it. Using the lock file, I figured out what versions it needed to get working to build (mostly) cleanly. In addition, using the 0.2.0 let me use the same versions as the [Cargo.toml](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/gen_lsp_server/Cargo.toml) in the repository and it also works.

That got me to the next step (which I'm still trying to figure out how to get a response). If I have questions, would you rather I add them here or just open a new topic? And would a PR to update the example to work be helpful? (I had to change a `use` line so far and remove the `extern crates` for 2018.)

**Comment by dmoonfire** [comment]
Looking at the next step, this might be something I'm missing. When I use the example, it hangs and doesn't get a response. I tried to isolate where it wasn't working to see what I'm doing wrong, but I can't seem to find it.

If I copy the `read_msg_text` method, it seems to parse everything correctly to blow up.

```
fn main() -> Result<(), failure::Error> {
    simple_logger::init()?;
    info!("starting example server");

    // This seems to work and shows the proper debug message and fails because we asked it to.
    {
        let stdin = std::io::stdin();
        let mut stdin = stdin.lock();
        info!("stdin");
        let buffer = read_msg_text(&mut stdin)?;
        info!("buffer {:?}", buffer);
    }
```

When I send it the following:

```
Content-Length: 86

{"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": { "capabilities": {} }}
```

I get this response:

```
2019-05-21 12:56:55,943 DEBUG [lsp] < {"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": { "capabilities": {} }}
2019-05-21 12:56:55,943 INFO  [lsp] buffer Some("{\"jsonrpc\": \"2.0\", \"id\": 1, \"method\": \"initialize\", \"params\": { \"capabilities\": {} }}\r")
2019-05-21 12:56:55,943 TRACE [lsp] before receiver.recv
```

However, when I go up a level and duplicate the function in the `gen_lsp_server/src/lib.rs` `initialize` function (basically stripping out the `cast` just to dump the output, it hangs on me.

```
fn main() -> Result<(), failure::Error> {
    simple_logger::init()?;
    info!("starting example server");

    // This is pulled out from the gen_lsp_serv::server. This just hangs and never gives even
    // the debug message that it got something.
    {
        let (receiver, _sender, io_threads) = stdio_transport();

        trace!("before receiver.recv");
        let req = match receiver.recv() {
            Ok(req) => req,
            msg => bail!("expected initialize request, got {:?}", msg),
        };
        info!("req {:?}", req);
        io_threads.join()?;
        info!("after join");
    }

    Ok(())
}
```

If ou have a quick suggestion where to look, I'd appreciate it.

**Comment by matklad** [comment]
>If I have questions, would you rather I add them here or just open a new topic?

For more real-time discussion, Zulip might be a better place:

https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0

>And would a PR to update the example to work be helpful?

Sure!

>If ou have a quick suggestion where to look, I'd appreciate it.

My guess would be that some io buffer is not flushed

**Comment by dmoonfire** [comment]
Thank you for all your help. I got it working and created a PR to update the examples to remove warnings and to document/example the results.

https://github.com/rust-analyzer/rust-analyzer/pull/1313
