### ISSUE TITLE
Make use of LSP file system operations

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#131]
The latest version of the protocol has added file&folder operations: https://microsoft.github.io/language-server-protocol/specification#version_3_13_0, see `resourceOperations` in `WorkspaceEdit`. We should use it instead of our own [`FileSystemEdit`](https://github.com/rust-analyzer/rust-analyzer/blob/a230b438e025c5878b8d17e11d3928cbad95bb28/crates/ra_lsp_server/src/req.rs#L165-L178). Note that we probably need to preserve bespoke `SourceChange`, because it contains `cursor_position`: something that LSP 's edits currently are incapable of expressing.

**Comment by vemoo** [comment]
Should this be closed by #415?

**Comment by vemoo** [comment]
It turns out that there's multiple overloads of `vscode.workspace.openTextDocument` and we should use https://code.visualstudio.com/api/references/vscode-api#2280 but if a `string` is passed it means something different.

**Comment by matklad** [comment]
>It turns out that there's multiple overloads of vscode.workspace.openTextDocument and we should use https://code.visualstudio.com/api/references/vscode-api#2280 but if a string is passed it means something different.

:fearful: 

>Now that that's working a textDocument/didOpen and then a textDocument/publishDiagnostics notification is recieved for the new file, should there be others?

No, that's all that is expected. It would still be good to fix underlying vfs issue, but that can be tricky. Opened https://github.com/rust-analyzer/rust-analyzer/issues/433 for that.
