### ISSUE TITLE
Breaks vsvim

### ISSUE THREAD

**Issue by jondot** [rust-analyzer/rust-analyzer#1310]
Hi,
Since adding this extension, [vscode vim](https://github.com/VSCodeVim/) stopped working, getting:

```
Error: command 'type' already exists
```
I've tried on older VSCodes, older vscode vims, and same result.

Happy to fix it myself, but first -- any idea where to start or why it might happen?

**Comment by matklad** [comment]
That is a known issue in VS Code API, which doesn't allow to compose type handlers. Set `rust-analyzer.enableEnhancedTyping` to false in settings.

**Comment by jondot** [comment]
Amazing, thanks! would it make sense to add it to the README?

**Comment by matklad** [comment]
good call, added in https://github.com/rust-analyzer/rust-analyzer/commit/a25e103e4542637047fe388a926aebddca07b3b7
