### ISSUE TITLE
Fix hover to use `classify_name_ref`

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1314]
In #1311, we've introduced `classify_name_ref`, which allows one to conveniently go from an `ast::NameRef` to semantic information. We should use that method in

https://github.com/rust-analyzer/rust-analyzer
/blob/44665685257f18d182ab116855dd9e8b054c49da/crates/ra_ide_api/src/hover.rs#L76-L87

After that, we should remove

https://github.com/rust-analyzer/rust-analyzer/blob/44665685257f18d182ab116855dd9e8b054c49da/crates/ra_ide_api/src/display.rs#L74-L82

**Comment by kjeremy** [comment]
Can `doc_text_for` be removed? Don't we need it for the indexed case or if the cursor is on an `ast::Name`?

**Comment by matklad** [comment]
I think this cases should deal with underlying data (`ast::Name` and `FileSymbol` respectively), rather than go via `NavigationTarget`. But yeah, it's a good call that we can't "just" remove `doc_text_for`

**Comment by kjeremy** [comment]
@matklad does it make sense to implement `Docs` for `ImplBlock`, `AdtDef` and `ModuleDef`? Maybe there should be a method on `NameRefKind` that returns `Option<Documentation>` too?

**Comment by matklad** [comment]
yes, it makes sense to impl Docs for all thouse things

**Comment by edwin0cheng** [comment]
@matklad Can it be closed now ?
