### ISSUE TITLE
Install plugin for Visual Studio Code - Insiders

### ISSUE THREAD

**Issue by lwshang** [rust-analyzer/rust-analyzer#1323]
The VSCode plugin can be used with the Insiders version by manually install it from the `vsix` package . It will be great to have `cargo install-code` do this for users.

**Comment by matklad** [comment]
I would say that, if you are using insiders, you probably should just install manually? We *could* add this to `install-code`, but then we'd need to decide what to do if you have both insiders and usual code.... It seems like we are hitting the point of diminishing returns here?

**Comment by quantumZebraPDX** [comment]
I primarily use the insiders build and what I’ve done is set `code` as an alias for code-insiders in my shell config. Then `cargo install-code` installs it to insiders.

**Comment by lnicola** [comment]
Maybe add a `cargo install-code-insiders`?

**Comment by DJMcNab** [comment]
Or just a command line flag `--code-binary`

**Comment by kiljacken** [comment]
We currently support several versions of VSCode when installing via xtask, and we're also on the marketplace. Closing.
