### ISSUE TITLE
coc.nvim  setup for [neo]vim

### ISSUE THREAD

**Issue by oblitum** [rust-analyzer/rust-analyzer#1324]
I've added `rust-analyzer` setup for [coc.nvim](https://github.com/neoclide/coc.nvim) at https://github.com/neoclide/coc.nvim/wiki/Language-servers#rust. I'm not sure it's worth a mention in README. Feel free to add. I just tested it and it's working great, specially on NeoVim master/nightly due to floating window support, which is great for signatureHelp and docs.

**Comment by oblitum** [comment]
Member completion though (after `.`) isn't behaving as expected, it's not completing any member, and simply giving `if`, `match`, `while` and other statements as completion itens.

**Comment by matklad** [comment]
>Member completion for variables though (after foo.) isn't behaving as expected, it's not completing any member, 

This means that type inference doesn't work in this particular case. Can you try something trivial like

```rust
struct Foo { }
impl Foo { fn frobnicate(&self) {} }

fn bar(foo: Foo) { foo.frob }
```

>I'm not sure it's worth a mention in README. Feel free to add

It definitely **is** worth mentioning in the readme, lot's of users ask for vim support. I unfortunately don't know about vim enough to write this. Could you add a paragraph or to to 

https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user

?

It doesn't need to be anything fancy: I guess once we have *something* about vim, folks will be glad to expand upon it!

**Comment by oblitum** [comment]
> This means that type inference doesn't work in this particular case. Can you try something trivial like

OK, I tried and that works.

>  Could you add a paragraph or two

#1330
