### ISSUE TITLE
unresolved modules

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#1325]
![afbeelding](https://user-images.githubusercontent.com/17426603/58367854-b375dd00-7ee4-11e9-9755-e81a7669fff8.png)

**Comment by bjorn3** [comment]
Using the create module quick fix fixes it without clearing the already existing files.

**Comment by bjorn3** [comment]
```
$ git rev-parse HEAD
9800699bab04e97996f0aebec528714165a2619b
```

**Comment by bjorn3** [comment]
I am seeing a lot of:

```
2019-05-25 13:54 ra_lsp_server[10552] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
```

Could it be related?

**Comment by matklad** [comment]
This may be related, yeah, we've updated `notify` recently:

https://github.com/rust-analyzer/rust-analyzer/commit/60cdd95e1729733bea20a81f7892feab20245379#diff-d2ede298d9a75c849170d6ef285eda1eL811

Could you run `cargo update -p notify --precise 4.0.11` to downgrade it and see if the issue is still there?

**Comment by bjorn3** [comment]
That fixes the `2019-05-25 13:54 ra_lsp_server[10552] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)` but not the `unresolved module` problem.

**Comment by flodiebold** [comment]
In my experience, this sometimes happens during startup and then gets cleared when I do any edit on that file.

**Comment by bjorn3** [comment]
I got the notify problem again with `notify 4.0.11` :(

**Comment by kiljacken** [comment]
Are you still getting this issue? As it was related to notify the recent-ish change to client-side watching by default might've helped

**Comment by bjorn3** [comment]
I can't remember having seen this recently, even before the client-side watching change.
