### ISSUE TITLE
Bad recovery with missing } after use

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#1329]
```rust
use symbols::{SymbolBuilder, SymbolTable, Symbol

// some code
```

gives syntax errors for almost every token.

**Comment by matklad** [comment]
That's a tricky one, because we maintain the invariant that `{` are balanced in the syntax tree.

**Comment by lnicola** [comment]
Presumably same as https://github.com/rust-analyzer/rust-analyzer/issues/3434, closing.
