### ISSUE TITLE
Member completion of variables is most often broken

### ISSUE THREAD

**Issue by oblitum** [rust-analyzer/rust-analyzer#1332]
Example:

```rust
#![allow(unused)]

struct Foo {}
impl Foo {
    fn frobnicate(&self) {}
}

fn main() {
    let foo = Foo {};
    // foo. works
    let v = vec![1, 2, 3];
    // v. doesn't work
}
```

**Comment by edwin0cheng** [comment]
Yes, macro expansions of expression are still work in process right now. Your case maybe related to name resolution of macro.

**Comment by oblitum** [comment]
Correct. But I'm also missing it in non macro cases:

```rust
extern crate postgres;

use postgres::{Connection, Result, TlsMode};

fn main() -> Result<()> {
    let conn = Connection::connect("postgres://postgres@localhost/random_db", TlsMode::None)?;
    // conn. doesn't work
    for row in &conn.query("SELECT * FROM random_table", &[])? {
        // row. doesn't work
        let v: i32 = row.get("numbers");
        print!("{} ", v);
    }
    Ok(())
}
```

**Comment by oblitum** [comment]
Maybe in that case `?` is making it not work for the same reason macro expansion doesn't.

**Comment by flodiebold** [comment]
We don't have type inference for the `?` operator or `for` loops yet, because that requires handling associated types, which we've only recently gained the foundations for.

**Comment by oblitum** [comment]
Update after  #1512:

extern crate postgres;

use postgres::{Connection, Result, TlsMode};

fn main() -> Result<()> {
    let conn = Connection::connect("postgres://postgres@localhost/random_db", TlsMode::None)?;
    // conn. now works!
    for row in &conn.query("SELECT * FROM random_table", &[])? {
        // row. still doesn't work
        let v: i32 = row.get("numbers");
        print!("{} ", v);
    }
    Ok(())
}

**Comment by flodiebold** [comment]
`for` loops still have a problem with the associated type normalization for the `IntoIterator` trait, which will probably need to be solved in Chalk (which is why #1425 isn't closed yet).

**Comment by oblitum** [comment]
Awesome work, everything is completing fine now in the examples above. Such progress!

**Comment by oblitum** [comment]
There's a regression for this on master now. On https://github.com/rust-analyzer/rust-analyzer/issues/1332#issuecomment-509474566, `row.` stopped working.

**Comment by oblitum** [comment]
For what's worth, it was working at the time #1425 was closed.

**Comment by oblitum** [comment]
Folks, this got fixed in the last release (2020-01-20).
