### ISSUE TITLE
Support rename for local variables

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#135]
With the help of `resolve_local_name` I think we should be able to rename local variables pretty reliably, so we should expose this functionality via our language server.

@kjeremy you might be interested in this.

**Comment by kjeremy** [comment]
@matklad I think the first step to this may be some sort of `find_references` exposed via the analysis that would (for now) use `resolve_local_name` under the hood and then... (somehow?) find usages in the FnDef? . Does that make sense?

**Comment by matklad** [comment]
yep!

**Comment by kjeremy** [comment]
How do I traverse the FnDef? I tried `fn_def.syntax().descendants()` but that doesn't seem to give me what I need. Do I need to use `visitor`?  Right now I'm looking for `ast::NameRef` directly but I think I'm missing something.

**Comment by kjeremy** [comment]
Sorry... I'm looking for `ast::NameRef`s to pass into `resolve_local_name` and to compare with

**Comment by kjeremy** [comment]
Ok I had a bug. It looks like either approach (`descendants()` or `vistor()`) works. Are they equivalent?

**Comment by kjeremy** [comment]
Oh nice this also works for find all references

**Comment by kjeremy** [comment]
Implemented in #143

**Comment by DJMcNab** [comment]
What would it take to extend this to private items too (i.e. `(!pub) struct, mod, enum, union, fn, use as, `) or enum variants? I'd imagine this could also work for crate private items? Because of cargo workspaces, renaming crate public items could rapidly develop issues.

**Comment by matklad** [comment]
>What would it take to extend this to private items too (i.e. (!pub) struct, mod, enum, union, fn, use as, ) or enum variants?

I don't think that we can carve out an *easy* subset by restricting visibility: Even private items can be used across the module hierarchy and reexported, and usages across crates are not really that different from usages across modules. 

So, we "just" need to implement the module system properly. This is harder than it seems (due to reexports, we need to run some kind of fixed-point iteration algo), but should be totally doable.

**Comment by aochagavia** [comment]
Today I found the following bug: if you rename a `let mut x` variable, the rename strips the `mut` away, as shown below.

Before:

```rust
fn test() {
    let mut x = 42;
    let y = x;
}
```

After (rename x to foo):

```rust
fn test() {
    let foo = 42;
    let y = foo;
}
```


Btw if you think this can better go into its own issue I can close this one again and create a separate issue

**Comment by kjeremy** [comment]
@aochagavia Yes please make that a new issue since it's a legitimate bug.

**Comment by kjeremy** [comment]
@aochagavia We probably need to massage the value passed into `DeclarationDescriptor::new` before hand to solve that (or adjust the node passed in to that function which is more likely).
