### ISSUE TITLE
There should be a setting to disable the implementations code lens

### ISSUE THREAD

**Issue by JMS55** [rust-analyzer/rust-analyzer#1355]

**Comment by matklad** [comment]
Good idea! I personally disable all lenses in the editor (there are shortcuts for them anyway), but we really should have a per-lense control.

**Comment by kjeremy** [comment]
Yes I started down this route in and old PR but never got around to finishing it. You'll need to add support for workspace/configuration (something like that, sorry on mobile) which sends requests from the lsp to the client. Once that is implemented it should be pretty easy to add a configuration struct or something and check it during codelens requests.

**Comment by mikeyhew** [comment]
This would be pretty handy, because I like to use the code lens to help solve git conflicts, but I don't have any need for the implementations code lens (especially since I can just right-click and click on "Go to Implementations") and it gets in the way.

**Comment by kiljacken** [comment]
Closing this one as we already have a general issue #757 :)
