### ISSUE TITLE
Memory profiling

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1365]
We have an awesome hierarchical profiling for wall-clock time. We also need something like this for memory. 

Ideally, we should see how many instances are there of any data-type, and how much memory these instances occupy. Unfortunatelly, I don't know a way to get this information, except for instrumenting every datatype...

**Comment by skade** [comment]
Servo has https://github.com/servo/servo/tree/master/components/malloc_size_of and for that https://github.com/servo/servo/blob/master/components/profile/mem.rs.

(Thanks @simonsapin for the hint!)

**Comment by matklad** [comment]
I think this actually can be reasonable closed by https://github.com/rust-analyzer/rust-analyzer/pull/1463

That hack doesn't give us "live" memory usage, but works good for "after the fact" profiling, and that should be enough for memory.
