### ISSUE TITLE
Syntax errors for valid syntax

### ISSUE THREAD

**Issue by Proximyst** [rust-analyzer/rust-analyzer#1372]
Given this minimal case, the errors as described in comments occur:

```rust
trait Trait {
    fn func() -> Result<bool, String>;
/*
This occurs on the } on the next line:

Syntax Error: expected identifier
Syntax Error: expected COMMA
*/
}

impl Trait for () {
    fn func() -> Result<bool, String> {
        fn inner() -> Result<u8, String> {
            Ok(0x00)
        }

        Ok(inner()? == 0x01)
    }
}
```

There is no relevant logging in the verbose log in VSCode.

**Comment by Erk-** [comment]
This is likely connected with #909

**Comment by matklad** [comment]
Can't reproduce this. Could it be the case that you use some outdated version of rust-analyzer?

**Comment by Proximyst** [comment]
It was compiled the same day. I'll try it again sometime this week, though might've been fixed already or some special case where VSC displayed old data.

**Comment by kiljacken** [comment]
This is definitely working on master, should be safe to close
