### ISSUE TITLE
Semicolon not allowed after function-local item

### ISSUE THREAD

**Issue by etaoins** [rust-analyzer/rust-analyzer#1384]
As seen in etaoins/arret@9e2989198556c8f0ef322cde0913d98299c65e05 `rust-analyzer` does not allow a semicolon after a function-local enum:

```rust
fn simple_function() {
    enum LocalEnum {
        One,
        Two,
    };
}
```

This is accepted by `rustc` but `rust-analyzer` complains with:

```rust
Syntax Error: expected item, found `;`
consider removing this semicolon
```

**Comment by zbelial** [comment]
I'd like to try to tackle this issue :)
