### ISSUE TITLE
Syntax error when using existential types

### ISSUE THREAD

**Issue by callym** [rust-analyzer/rust-analyzer#1387]
I'm assuming this is because existential types aren't stable so I didn't really expect them to work, but at least not getting an error would be nice - if this isn't too complicated I'd be happy to give it a shot if someone could point me to where to get started

```
Syntax Error: expected EXCL
Syntax Error: expected `{`, `[`, `(`
Syntax Error: expected SEMI
```

**Comment by matklad** [comment]
Yeah, it shouldn't be to hard to fix. THe code for parsing type aliases is here:

https://github.com/rust-analyzer/rust-analyzer/blob/9c92c05ca614fcded456153b1bc6717d17f0dafb/crates/ra_parser/src/grammar/items.rs#L292-L317

for exsitentail types, we'll need `existential` contextual keyword, which hare handled like this:

https://github.com/rust-analyzer/rust-analyzer/blob/9c92c05ca614fcded456153b1bc6717d17f0dafb/crates/ra_parser/src/grammar/items.rs#L106

keyword should also be added to grammar.ron
