### ISSUE TITLE
fill match arms assist should work with default arm

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1399]
We have two features which interract not as good as the could.

`.match` postfix completion turns `foo.match` into `match foo { _ => ()}`

fill match arms assits allows one to fill *empty* match arms with all variants in `match foo {}`

Because `.match` adds a catch all branch, it prevents the assist from firing. We should fix the assist to also trigger in the case where there's only a single trivial `_ => ()` branch.

The relevant bit of code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/a3a03b65dca9dc174bd58cd3d877ede18fc58637/crates/ra_assists/src/fill_match_arms.rs#L15-L20

The tests can be fond in the same file.

**Comment by kanru** [comment]
I'd like to take this one :smiley:

**Comment by kanru** [comment]
It looks like the unit type `()` doesn't have it's own token. Is it correct to match it like a empty tuple?

**Comment by matklad** [comment]
There are different ways to check if the match arm is trivial, and I don't know which is the best.

I think the high order bit is to have 

```
fn is_trivial_arm(arm: &ast::MatchArm) -> bool {
  ...
}
```

function which we can adjust later. The simplest first step would be comparing the text of match arm to `"_ => ()"`. The more robust way would be to check that the `ast::Pat` is trivial and that `ast::Expr` is either a unit or an empty block

**Comment by ironyman** [comment]
@kanru are you still working on this? I want to work on this too 😃

**Comment by kanru** [comment]
@ironyman feel free to take it! I probably won't be able to work on it for a couple days.

**Comment by theotherphil** [comment]
This issue is now fixed. Please could someone with perms close it.
