### ISSUE TITLE
Replace all uses of failure with std::Error

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1400]
We are not actually using any cool features of failure, backtrace collection can slow us down and, today, implementing `std::error::Error` is as simple as `impl Error for MyType`. 

We should remove failure dependecy and just replace it with `Box<dyn std::Error>`. For bail macro, we can do just `Err("error message")?` (there's `From<&str> for Box<dyn std::Error>`).

Here's how I've done this transition for another project recently: https://gitlab.com/jD91mZM2/rnix/merge_requests/13

**Comment by lnicola** [comment]
> today, implementing std::error::Error is as simple as impl Error for MyType

Well, there's also `cause()` and `fmt`.

I also like https://docs.rs/snafu/0.4.1/snafu/ as an alternative to `failure`.

**Comment by matklad** [comment]
Snafu is cool, but we don't actually do that much error handing, so I'd prefer to stick with `std::Error` for now. 

Fixing this issue should also close https://github.com/rust-analyzer/rust-analyzer/issues/1331

**Comment by mominul** [comment]
I'd like to take this! ☺️

**Comment by matklad** [comment]
go for it! It maybe makes to not do this all at once, and instead send a spearate PR for crate
