### ISSUE TITLE
HRTB plus an additional bound in container whithout dyn

### ISSUE THREAD

**Issue by leudz** [rust-analyzer/rust-analyzer#1422]
Having something like:
```rust
type Alias = Box<for<'a> Test<'a> + Send>;
```
triggers some syntax errors:
* `expected COMMA` and `expected R_ANGLE` right after `Test<'a>`
* `expected SEMI` and `expected an item` at the last angle bracket
* `expected an item` at the semi-colon

It works perfectly fine if I add the `dyn` that should have been there from the beginning.
I tried a few things and only the first two errors seem to be related to this issue, the others being a result of them.

Here's a [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f65a87fac6b1fdfced4527d7884b0299).

**Comment by bjorn3** [comment]
triage: still an issue
