### ISSUE TITLE
Expand ~ in rust-analyzer.raLspServerPath

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#1424]
See https://github.com/rust-analyzer/rust-analyzer/issues/1423#issuecomment-504645478.

**Comment by matklad** [comment]
This should happen here: https://github.com/rust-analyzer/rust-analyzer/blob/7d79be32801036c39507fe96f87ed316e3934662/editors/code/src/server.ts#L23

I bet there's a nodejs function for this.

**Comment by lnicola** [comment]
Ugh: https://stackoverflow.com/questions/21077670/expanding-resolving-in-node-js

**Comment by lnicola** [comment]
A workaround could to be add `PATH DEFAULT=${PATH}:@{HOME}/.cargo/bin` to `~/.pam_environment`. It's a bit finicky, though: it seems to add it twice, and doesn't work with `su -l`. It works over SSH, though.
