### ISSUE TITLE
Type inference for ? operator

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#1426]
Now that basic support for associated types is there, we should be able to
implement type inference for the `?` operator. For example, in
```rust
let x = Ok(1u32);
let y = x?;
y;
```
hovering `y` should say `u32`.

Like [`for` loops](1425), rustc implements the `?` operator [via desugaring](https://github.com/rust-lang/rust/blob/305930cffeac1da0fd73a08d9f5680e4a49bfb9f/src/librustc/hir/lowering.rs#L4972).
So the same thing as there goes here: we could do the same, but it's probably
simpler for now to handle them directly during type inference.

This should work very similarly as `for` loops, so basically the same steps as
[there](1425) apply, except we need to project to `std::ops::Try::Ok`. Note that we
don't really care about the error part at this moment, because there are no
types to be inferred there -- the error type almost always needs to be already
known because `Into` is used to convert it to the function's error type.

Since this shares a few steps and the general approach with `for`, I'd suggest
doing one after the other.

[Here](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/for.20loops.20.26.20.3F.20operator)'s a Zulip stream for questions about this.

**Comment by oblitum** [comment]
related #1332
