### ISSUE TITLE
Support built-in derives

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#1427]
We should support the built-in derives, e.g. with
```rust
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
struct SomeStruct { ... }
```
we should know that the type implements those traits and pass corresponding impls to Chalk when doing trait solving. The most noticeable case where this currently matters is `Clone` since that gets called directly all the time; the other ones are more likely to be used in bounds, so we're probably missing some trait implementations because of this.

Here are some general notes about this (I haven't thought about / investigated this in detail yet):
 - we don't need to generate code for the impls, so just producing a 'fake' impl without any actual method implementations should be enough
 - We *could* generate actual `ra_hir::ImplBlock`s for this, or we could collect the derives in some separate data structure and just generate fake impls for Chalk (i.e. in [`impls_for_trait`](https://github.com/rust-analyzer/rust-analyzer/blob/7d79be32801036c39507fe96f87ed316e3934662/crates/ra_hir/src/ty/traits/chalk.rs#L458)). I'm not sure which would be the better/nicer approach.
 - as far as I know / think, the derived impls just have a bound for each type parameter of the struct (e.g. `#[derive(Clone)] struct S<T>` would result in `impl<T: Clone> Clone for S<T>`), but I haven't checked this.

**Comment by lnicola** [comment]
> We could generate actual ra_hir::ImplBlocks for this, or we could collect the derives in some separate data structure and just generate fake impls for Chalk (i.e. in impls_for_trait). I'm not sure which would be the better/nicer approach.

It would be nice if "go to definition" on a method of a derived trait would work and point to the attribute.

> as far as I know / think, the derived impls just have a bound for each type parameter of the struct

Yes, see https://github.com/rust-lang/rust/issues/41481 and https://github.com/rust-lang/rust/issues/26925.

**Comment by flodiebold** [comment]
> It would be nice if "go to definition" on a method of a derived trait would work and point to the attribute.

Currently "go to definition" will go to the definition of the method in the trait. I don't know if we should go to the impl if possible, or if we should have a separate command that does that... In many cases it's not possible anyway :thinking: 
In any case, I think neither approach precludes that, though the approach with actual `ImplBlocks` may make it a bit simpler (at the cost of needing to refactor a lot of the source handling for `ImplBlock` at the outset).

**Comment by matklad** [comment]
I think the more future proof version (supporing custom derives) would be to generate actual source code when we do macro expansion.

**Comment by eupn** [comment]
>I think the more future proof version (supporting custom derives) would be to generate actual source code when we do macro expansion.

@matklad hey, where the `#[derive(...)]` attribute expansion should go in that case?

**Comment by lnicola** [comment]
A hacky and maybe easy way to get this (and also custom derives) would be to assert that types with `#[derive(Trait)]` on them implement `Trait`.

**Comment by flodiebold** [comment]
Yes, as a midterm solution, we could basically provide synthetic impls for derives. Nowadays, I think we have all of the necessary infrastructure for that. It'd involve adding a variant to the `Impl` enum [here](https://github.com/rust-analyzer/rust-analyzer/blob/9d786ea221b27fbdf7c7f7beea0290db448e0611/crates/ra_hir/src/ty/traits.rs#L297), adding code [here](https://github.com/rust-analyzer/rust-analyzer/blob/9d786ea221b27fbdf7c7f7beea0290db448e0611/crates/ra_hir/src/ty/traits/chalk.rs#L437) to return those impls when there's a derive, and providing the right data to Chalk [here](https://github.com/rust-analyzer/rust-analyzer/blob/9d786ea221b27fbdf7c7f7beea0290db448e0611/crates/ra_hir/src/ty/traits/chalk.rs#L605). It's not quite simply asserting the type implements the trait though; if the type has parameters, the impl needs to have variables for those and bound each of them with the trait.

This won't work for custom derives though, since they can do basically anything, not just implementing a trait, and even for the ones that do, I don't think we have a good way of knowing what the trait being implemented is. Still, I think this could be worth it for the built-in derives, since proper support for custom derives may still take quite some time.

**Comment by flodiebold** [comment]
This is actually fixed :slightly_smiling_face:
