### ISSUE TITLE
Vs Code - Special Case/Ignore .rs Fiels in target/

### ISSUE THREAD

**Issue by theduke** [rust-analyzer/rust-analyzer#1428]
This is a relatively minor issue, but:

When opening a `.rs` file inside `./target`, for example auto-generated FFI bindings, VS Code constantly (re)opens the console, spams a lot of error messages and re-displays the "a request has failed" popup.

It would be sensible to somehow disable LSP integration for those files in the plugin.

**Comment by lnicola** [comment]
Wouldn't completion support be useful for the generated files?

**Comment by theduke** [comment]
Sure, ideally, but I imagine that's not something that will happen overnight.

**Comment by lnicola** [comment]
Rather, why is RA panicking on those files?

**Comment by theduke** [comment]
```[Error - 9:18:23 PM] Request textDocument/codeAction failed.
  Message: Rust file outside current workspace is not supported yet```

**Comment by matklad** [comment]
fixd
