### ISSUE TITLE
Add more postfix completions

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#1431]
- `Rc::new`, `Arc::new`, `Cell::new`, `RefCell::new`
- `Rc::clone`, `Arc::clone` -- these seem harder, since ideally they'd be context-sensitive
- `String::from`

Anything else?

CC @kanru ~~, whom apparently I can't tag~~.

**Comment by matklad** [comment]
Hm, I'd rather not add these completions: too many completions make it harder to discover the useful ones. 

Box is somewhat special because is a language built-in. Rcs and Cells are just library types. 

Ideally, what we want here is "surround with box" quick fix for type error.

**Comment by flodiebold** [comment]
I think `Rc::clone` and `Arc::clone` make sense if they only appear on expressions of the respective type.

**Comment by lnicola** [comment]
`String::from` is probably useful, too.

**Comment by DJMcNab** [comment]
It makes sense to also implement a fixable validator, in addition to `.clone` completion surrounding with `Rc::clone`. We would need a way to disable that I suppose. A setting would do for now.

**Comment by SomeoneToIgnore** [comment]
How about `println` and `format` postfix template for the corresponding macros to speed up the printing?

I have a very simple support for those implemented:
https://github.com/rust-analyzer/rust-analyzer/compare/master...SomeoneToIgnore:add-formatter-macros-postfixes

It can be improved if there's a way to check if the type we apply the template to implements a trait, but I failed to find any suitable API for this.

**Comment by matklad** [comment]
>How about println and format postfix template for the corresponding macros to speed up the printing?

There's `pd` for "debug-print" case. For general-purpose formatting, we really should have something like this: 

https://user-images.githubusercontent.com/4854600/56230729-90564300-6085-11e9-8682-722e073e9539.gif

**Comment by lnicola** [comment]
That's not much of an improvement over `println!("{name}");` :smile:.

**Comment by SomeoneToIgnore** [comment]
> There's pd for "debug-print" case.

Nice, was not aware of such things as snippet completions, thanks.
It was a but not intuitive to me, since I've got used to the postfix completions :)

I think postfix completions are a bit better in the current case since we are able to determine variable's type and generate a proper formatter for it, but `pd` covers 80% of the job already.

**Comment by matklad** [comment]
Oh, there's also `.dbg` postfix completion for debugging as well

**Comment by lnicola** [comment]
Do we want to do anything about this or should it be closed?

**Comment by matklad** [comment]
Yeah, I think it makes sense to close!
