### ISSUE TITLE
Incorrect postfix completion for integer literals

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1435]
`42.dbg` completes to `dbg!(42.)`, while it should complete to `dbg!(42)`. The most likely cause here is that `42.` is a valid expression: floating point literal.

I think we should just hard-code the fix here. The relevant code is https://github.com/rust-analyzer/rust-analyzer/blob/b34f65bcedadf2bb8fb738711a01be9c825c98c9/crates/ra_ide_api/src/completion/complete_postfix.rs#L20-L24. We should check if `dot_receiver` is float literal that ends with `.`.  I think we should even do this when we search for dot_reciver in the original file:

https://github.com/rust-analyzer/rust-analyzer/blob/b34f65bcedadf2bb8fb738711a01be9c825c98c9/crates/ra_ide_api/src/completion/completion_context.rs#L209

THat is, we should store a flag like `dot_reciver_is_ambigious_float_literal`, and use the flag when computing an edit.

**Comment by pasa** [comment]
I will take this

**Comment by Geobert** [comment]
To be closed then?

**Comment by lnicola** [comment]
@matklad this is working now.
