### ISSUE TITLE
Hovering over `return` keyword gives `!`

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#1437]

**Comment by bjorn3** [comment]
The return statement never returns to the next statement, so it kinda diverges. Also the following is valid rust:

```rust
fn main() {
    let _: Option<u8> = return;
}
```

**Comment by killercup** [comment]
[Have you heard of our lord and savior?](https://github.com/rust-lang/rust/blob/bbbb3e597482bec1260ea733f7d3fc813bc136ae/src/test/run-pass/weird-exprs.rs#L32-L52)

**Comment by kjeremy** [comment]
My guess is this is also #1508

**Comment by flodiebold** [comment]
No, even with #1508 fixed the type of the whole return statement will still be `!`. Actually I think this is working as intended.
