### ISSUE TITLE
Return ResponseError from LSP requests

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#145]
My rust error handling skills are pretty weak. 

From `textDocument/rename` params:

```typsescript
        /**
	 * The new name of the symbol. If the given name is not valid the
	 * request must return a [ResponseError](#ResponseError) with an
	 * appropriate message set.
	 */
	newName: string;
```

How do I return a `ResponseError`?

The following does not work from `handle_rename`:

```rust
if params.new_name.is_empty() {
        return Err(RawResponseError {
            code: ErrorCode::InvalidParams.into(),
            message: "New name cannot be empty".into(),
            data: None
        });
    }
```

**Comment by DJMcNab** [comment]
https://github.com/rust-analyzer/rust-analyzer/blob/4dbf0379ccd5c7643d48658f0ecc224add5a5c5c/crates/ra_lsp_server/src/main_loop/mod.rs#L364-L366

This line uses `failure::Error::to_string` on the result. It would probably be better to use something like `Into<RawResponseError>`.

For your case @kjeremy, I think you could use `Err("New name cannot be empty")?`, which will unfortunately allocate twice (once in the conversion to `failure::Error`, and once in the `to_string`, if my understanding is correct) where no allocations should be needed (as we use an `&'static str` anyway).

**Comment by matklad** [comment]
>The following does not work from handle_rename:

I think just `bail!("invalid name")` should do the trick, though it won't set the proper error code.

To do it 100% correctly, I think we should define an 

```
struct LspError {
    code: i32
    message: String,
}

impl Fail for LspError {
}
```

Then, [here](https://github.com/rust-analyzer/rust-analyzer/blob/2ded93a78a108c1f7e0dd0a9036c88c786f21dce/crates/ra_lsp_server/src/main_loop/mod.rs#L367-L369) we should try to [downcast](https://docs.rs/failure/0.1.1/failure/struct.Error.html#method.downcast) the error to `LspError` and set the code appropriately.

**Comment by matklad** [comment]
>which will unfortunately allocate twice 

I'd say that extra allocations are totally fine in the lsp layer: we'll be converting all the stuff to JSON string, and then parse it via JS on the other side, so allocation overhead will be dwarfed.

We should be more mindful of performance in the "analysis" layer, because it operates on the much larger volumes of data then that we send over the wire.

**Comment by DJMcNab** [comment]
> I'd say that extra allocations are totally fine...

Fair enough - I know that much of the Rust community is (rightly) zealous about unnecessary allocations, but for the additional overhead I see the cost is negligible.
