### ISSUE TITLE
Rename should work when invoked on the definition as well

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#146]
Consider this code:

```
fn foo(x/*2*/: i32) {
    let _ = x; /*1*/
}
```

when the cursor is at the position `1`, rename works correctly. However, at the position `2`, nothing happens, while the rename should proceed as usual. The feature was introduced at https://github.com/rust-analyzer/rust-analyzer/pull/143.

**Comment by kjeremy** [comment]
I believe this is due to #142
