### ISSUE TITLE
"expected pattern" when parsing slice patterns

### ISSUE THREAD

**Issue by estebank** [rust-analyzer/rust-analyzer#1479]
The parser cannot cope with [the following code using slice patterns](https://github.com/rust-lang/rust/blob/0b15a66a806a8f46af6ae24f640814f3a69eddfb/src/librustc_typeck/check/mod.rs#L1807):

```rust
if let &[ref start.., ref end] = &variant_spans[..] {
```

**Comment by matklad** [comment]
The relevant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/4e8664d9d37021e85d72b6228fa45e7edf4a1a74/crates/ra_parser/src/grammar/patterns.rs#L225-L254

Note that comments are executable tests

**Comment by tomjakubowski** [comment]
That particular case parses without errors with `cargo run --bin ra_cli parse`.

```rust
fn main() {
    if let &[ref start.., ref end] = &variant_spans[..] {}
}
```

```
          LET_KW@[19; 22) "let"
          WHITESPACE@[22; 23) " "
          REF_PAT@[23; 46)
            AMP@[23; 24) "&"
            SLICE_PAT@[24; 46)
              L_BRACK@[24; 25) "["
              RANGE_PAT@[25; 36)
                BIND_PAT@[25; 34)
                  REF_KW@[25; 28) "ref"
                  WHITESPACE@[28; 29) " "
                  NAME@[29; 34)
                    IDENT@[29; 34) "start"
                DOTDOT@[34; 36) ".."
              COMMA@[36; 37) ","
              WHITESPACE@[37; 38) " "
              BIND_PAT@[38; 45)
                REF_KW@[38; 41) "ref"
                WHITESPACE@[41; 42) " "
                NAME@[42; 45)
                  IDENT@[42; 45) "end"
              R_BRACK@[45; 46) "]"
          WHITESPACE@[46; 47) " "
```

But it's a misparse: the `RANGE_PAT` is wrong, and should probably match a new SyntaxKind.

Another test case produces a `RANGE_PAT` but this one does error the parser:

```rust
fn main() {
    let [a, b..] = [];
}
```

```
      LET_STMT@[16; 34)
        LET_KW@[16; 19) "let"
        WHITESPACE@[19; 20) " "
        SLICE_PAT@[20; 28)
          L_BRACK@[20; 21) "["
          BIND_PAT@[21; 22)
            NAME@[21; 22)
              IDENT@[21; 22) "a"
          COMMA@[22; 23) ","
          WHITESPACE@[23; 24) " "
          RANGE_PAT@[24; 28)
            BIND_PAT@[24; 25)
              NAME@[24; 25)
                IDENT@[24; 25) "b"
            DOTDOT@[25; 27) ".."
            ERROR@[27; 28)
              R_BRACK@[27; 28) "]"
        WHITESPACE@[28; 29) " "
        EQ@[29; 30) "="
```

**Comment by matklad** [comment]
@estebank hm, I am now confused, what `ref start..` means exactly? Is it a "subslice pattern" from https://github.com/rust-lang/rfcs/pull/2359? Shouldn't it be spelled s `ref start @ ..` really soon?

**Comment by estebank** [comment]
I believe you're correct in all your understanding. I don't think the syntax accepted in the RFC has been implemented, so `rustc` is using the previous syntax I'm showing here. It might be acceptable for rust-analyzer not to support it and skip straight to the finalized syntax, but I wanted to flag it.

**Comment by Centril** [comment]
The syntax in the RFC was implemented in https://github.com/rust-lang/rust/pull/62550. cc https://github.com/rust-lang/rust/issues/62254
