### ISSUE TITLE
Migrate from vscode package to @types/vscode and @types/vscode-test

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#1483]
See: https://code.visualstudio.com/updates/v1_36#_extension-authoring and https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode

**Comment by kiljacken** [comment]
We got rid of our extension integration tests alongside the cargo watch functionality as it was the only thing being tested. Closing for now, hopefully we'll remember this if we add new integration tests at some point :)
