### ISSUE TITLE
Look through token trees

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#1498]
It would be nice to hover/gotodef/etc. this:

```rust
fn f() {
    let x = 0i32;
     println!("x is {}", x<|>);
}
```

Relevant syntax tree:
```
SOURCE_FILE@[0; 23)
  MACRO_CALL@[0; 23)
    PATH@[0; 7)
      PATH_SEGMENT@[0; 7)
        NAME_REF@[0; 7)
          IDENT@[0; 7) "println"
    EXCL@[7; 8) "!"
    TOKEN_TREE@[8; 22)
      L_PAREN@[8; 9) "("
      STRING@[9; 18) "\"x is {}\""
      COMMA@[18; 19) ","
      WHITESPACE@[19; 20) " "
      IDENT@[20; 21) "x"
      R_PAREN@[21; 22) ")"
    SEMI@[22; 23) ";"
```

**Comment by edwin0cheng** [comment]
I will take a look on this issue :)

**Comment by kiljacken** [comment]
Minimal repro of a case where hover doesn't work yet:
```rust
fn test(foo: String) {
    let bar: Vec<_> = vec![
        "site".into(),
        foo,
    ]
    .into_iter()
    .collect();
}
```

**Comment by kiljacken** [comment]
It might have to do with the method chaining as the following works:
```rust
fn test(foo: String) {
    let bar: Vec<_> = vec![
        "site".into(),
        foo,
    ];
}
```

**Comment by flodiebold** [comment]
Even putting the macro call inside parentheses doesn't work, e.g.
```rust
fn test(foo: String) {
    vec![foo]; // hover works
    (vec![foo]); // hover doesn't work
}
```

**Comment by edwin0cheng** [comment]
> Also type inference apparently doesn't work either in the second case,
Seem like there are some bugs inside lowering macro:

```rust
macro_rules! bar { () => {0} }
fn test(foo: u32) {
    let _a = (bar!());  // no infer
}
```

**Comment by edwin0cheng** [comment]
#2785 should fixed the paren infer bug

**Comment by flodiebold** [comment]
@edwin0cheng Ok, the original case was a call expression though, so I guess we're missing a few more cases :)

**Comment by edwin0cheng** [comment]
@flodiebold Submitted #2787, which add back all possible expr cases, but let me add back the tests for these infer test in future as it is very time consuming .

**Comment by edwin0cheng** [comment]
I just tested, all cases in mentioned here works now in master (a9ba32e2), feel free to reopen it if there are other problems.
