### ISSUE TITLE
replace `KnownName` with `const Name`s

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1503]
We have `KnownName` `enum` which we use to work-around a lack of const-fn way to construct a `Name`:

https://github.com/rust-analyzer/rust-analyzer/blob/fee552d4873b1cce4e622c7eb2f0189b276b01be/crates/ra_hir/src/name.rs#L134-L160

In the recent version of `smol_str`, we did gain a const-fn constructor:

https://github.com/rust-analyzer/smol_str/commit/c7ce079a24cdd67eaf972f070874c6be7c166082#diff-b4aea3e418ccdb71239b96952d9cddb6R26

So we should replace `KnownName` enum with just a bunch of constants, so that instead of `KnownName::SelfParam` one uses `hir::name::SELF_PARAM`, where it is defined as

```rust
const SELF_PARAM: Name = Name::new(SmolStr::new_inline_from_ascii(4, b"self"));
```

**Comment by flodiebold** [comment]
We could even define a macro for this then, similar to rustc, e.g.
```rust
known_names! {
    std,
    iter,
}
...
hir::name::iter
```

**Comment by mominul** [comment]
I'd like to work on this issue!
