### ISSUE TITLE
Match with early return fails inference

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#1505]
Having a `return` of a different type in a `match` defeats inference.

For instance we have this in `handlers.rs`: 
```rust
let nav_info = match world.analysis().goto_implementation(position)? {
        None => return Ok(None),
        Some(it) => it,
    };
```

Hovering on `nav_info` gives us `!` and not the expected `GotoDefinitionResponse` which is the type of `it`.

**Comment by DJMcNab** [comment]
So this is probably an issue in unifying the never type?

**Comment by kjeremy** [comment]
Most likely. I just noticed it while mucking around `handlers.rs`. Haven't had a chance to investigate yet.

**Comment by kjeremy** [comment]
Reduced:

```rust
fn test(a: i32) {
    let i = match a {
        0 => 0,
        _ => return
    };
    i<|>
}
```

**Comment by flodiebold** [comment]
Never doesn't unify with other types, it just coerces to them, and we basically ignore coercions currently. To properly handle this, we'll probably need something like rustc's [CoerceMany](https://github.com/rust-lang/rust/blob/db592f4627251cfd8571a05cf8e06a56be9470c2/src/librustc_typeck/check/coercion.rs#L968).
