### ISSUE TITLE
Infer break with return value

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#1508]
@flodiebold 

What are the steps needed to infer breaks with values as seen in:

https://github.com/rust-analyzer/rust-analyzer/blob/1b38ca3b8739230af1cc69884b5b11650b5fcb46/crates/ra_hir/src/ty/infer.rs#L983
https://github.com/rust-analyzer/rust-analyzer/blob/1b38ca3b8739230af1cc69884b5b11650b5fcb46/crates/ra_hir/src/ty/infer.rs#L1081

**Comment by flodiebold** [comment]
Basically, I think we need the same [CoerceMany](https://github.com/rust-lang/rust/blob/db592f4627251cfd8571a05cf8e06a56be9470c2/src/librustc_typeck/check/coercion.rs#L968)s we need for #1505 as well; and then we need to keep a stack of them (together with their labels) and add the break value to the correct `CoerceMany` when we encounter it. [Here](https://github.com/rust-lang/rust/blob/db592f4627251cfd8571a05cf8e06a56be9470c2/src/librustc_typeck/check/mod.rs#L493) is how rustc keeps track of them, [here](https://github.com/rust-lang/rust/blob/db592f4627251cfd8571a05cf8e06a56be9470c2/src/librustc_typeck/check/mod.rs#L3579) is how it typechecks a block (including setting the breakable context), with some interesting comments, and [here](https://github.com/rust-lang/rust/blob/db592f4627251cfd8571a05cf8e06a56be9470c2/src/librustc_typeck/check/expr.rs#L507)'s the actual break handling.

**Comment by kjeremy** [comment]
I'm assuming that the stack of `CoerceManys` needs to be kept in the `InferenceContext`? What exactly are labels in this case?

**Comment by flodiebold** [comment]
> I'm assuming that the stack of CoerceManys needs to be kept in the InferenceContext?

Yes.
> What exactly are labels in this case?

E.g.
```rust
'a: loop {
  'b: loop {
    break 'a 1;
  }
}
```

**Comment by kjeremy** [comment]
Hopefully I'll have some time this weekend to work on it.

**Comment by flodiebold** [comment]
I think this is fixed (breaks with labels are not yet though).
