### ISSUE TITLE
Resolve out-of-line modules, declared inside inline modules

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1510]
In rust, it's possible to place `mod foo;` inside `mod bar {}`:

https://github.com/rust-lang/rust/blob/db592f4627251cfd8571a05cf8e06a56be9470c2/src/librustdoc/lib.rs#L63-L73

In such cases, module is to be found in `bar/foo.rs` file. We need to support this as well. Take a look at https://github.com/rust-analyzer/rust-analyzer/pull/1499 which adjust similar functionality, it contains both the relevant code (`resolve_submodule`) as well as the tests.

Here's the relevant section of rust reference:

https://doc.rust-lang.org/reference/items/modules.html#module-source-filenames

cc @andreevlex

**Comment by andreevlex** [comment]
I will work on the implementation of this opportunity

**Comment by andreevlex** [comment]
Where to find examples for this type of module name resolution?

https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_hir/src/nameres/collector.rs#L651
