### ISSUE TITLE
Unwanted completion suggestions

### ISSUE THREAD

**Issue by oblitum** [rust-analyzer/rust-analyzer#1516]
On all variable member access I'm getting a couple of spurious suggestions coming from language server in my client:

```rust
#![allow(unused)]

fn main() {
    let x = 42;
    x.
}
```

![NRis1Cs](https://user-images.githubusercontent.com/1269815/60855912-d4b43380-a1db-11e9-99bb-a6f2e89438ca.png)

I just used an `i32` as extreme case. I do get correct members for structs, but there's also always these ones coming along.

**Comment by unrealhoang** [comment]
They’re actually features of rust analyzer: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/features.md#magic-completions

**Comment by oblitum** [comment]
@unrealhoang ah... OK, thanks. Sadly it's not expanding as expected for me on `coc.nvim`, the expansion, for `.if` for example, is just being appended. I don't use VS Code, can you tell me whether this is working there, so I can report the issue with coc.nvim?

**Comment by matklad** [comment]
@oblitum it works in VS Code, see https://youtu.be/jNnvaHbnhK8?t=22

**Comment by oblitum** [comment]
@matklad thanks!

**Comment by oblitum** [comment]
I reported this feature to coc.nvim author and he concluded the server needs to check whether client is able to support magic completions or have an option for disabling it. What do you think?

**Comment by oblitum** [comment]
Fixed on coc.nvim.
