### ISSUE TITLE
{unknown} when using crossbeam::channel::unbounded

### ISSUE THREAD

**Issue by gerred** [rust-analyzer/rust-analyzer#1517]
I'm noticing an issue with crossbeam::channel::unbounded that works in RLS 1.0 and shows "{unknown}" in rust-analyzer. I've boiled it down to the most simple use case:

```rust
use crossbeam::channel::unbounded;

fn main() {
    let (s, r) = unbounded::<i32>();
    s.send(10).unwrap();
    let value = r.recv().unwrap();
    println!("{}", value);
}
```

In this case, s (Sender<i32>), r (Receiver<i32>), and unbounded() all show {unknown} when hovering in VSCode.

Hope this helps!

**Comment by gerred** [comment]
I realized I was on master from july 3rd, so I updated and rebuilt. This is still true as of commit `61135d4d4df0a16cbd39831e23b7b0deeeea44a9`.

**Comment by matklad** [comment]
This case should work:

![image](https://user-images.githubusercontent.com/1711539/60891244-9f542800-a265-11e9-97ff-64ef4e0a5be3.png)

could it be the case that something about project configuration is wrong?

Just "go to definition" works for `unbounded`?

**Comment by sinkuu** [comment]
`crossbeam::channel` re-export is defined behind `cfg_if` macro.

```rust

cfg_if! {
    if #[cfg(feature = "std")] {
        ...

        mod _channel {
            pub extern crate crossbeam_channel;
            pub use self::crossbeam_channel::*;
        }
        #[doc(inline)]
        pub use _channel::crossbeam_channel as channel;

        ...
    }
}
```

**Comment by gerred** [comment]
That's what it was - I needed to be using the crossbeam-channel crate as well instead of crossbeam::channel. Thanks!

**Comment by sinkuu** [comment]
Probably a duplication of #1149
