### ISSUE TITLE
Disabling "magic" completion

### ISSUE THREAD

**Issue by cloudhead** [rust-analyzer/rust-analyzer#1526]
Hey there - I'm using rust-analyzer with `coc.vim`, and wondering how I can disable some of the more magic completion features? There's a few things I'd like to disable:

First, given (cursor on `|`):
```rust
FooB|self.foobar  // auto-complete gives me `FooBar`, which is correct.  
```
Now I press `<Enter>`, and the result is:
```rust
FooBar.foobar
```
Somehow `self` was swallowed!
So ideally I'd like to disable this and have it work like a "dumb" completion.

Second, the auto-complete menu is littered with completions like `if~`, `ref~` etc. which aren't really "completions" per se, and it would be nice if they could be hidden/disabled to leave more room for standard completions :smile: 

Third, it would be nice to disable the feature which adds `()` and moves to cursor to the center when completing methods, as it is a bit wonky in vim.

I searched the docs, but couldn't find any settings that could disable these. I tried setting `"rust-analyzer.enableEnhancedTyping": false` - but that doesn't seem to make a difference.

Thanks!

**Comment by oblitum** [comment]
> Third, it would be nice to disable the feature which adds `()` and moves to cursor to the center when completing methods, as it is a bit wonky in vim.

I think the above perhaps pertains to another problem domain. This is commented about in the following thread: https://github.com/rust-analyzer/rust-analyzer/issues/769#issuecomment-498159980.

**Comment by oblitum** [comment]
In this matter specifically, rust-analyzer is behaving like golsp, not providing a full snippet expansion with placeholders, just an empty `()`. Other LSP servers do the full expansion, which I prefer.

**Comment by oblitum** [comment]
With that said, I'm not sure why have this expansion in particular disabled. It does no harm, if you don't want the snippet expansion you can simply avoid expanding by simply selecting the completion but not confirming it.

**Comment by oblitum** [comment]
And I think possibly the same applies for the FooBar example. If you simply selected the completion, without confirmation, you would get your expected non-magic completion, it does magic when you confirm menu, which seems you're using <kbd>Enter</kbd> for. In coc.nvim, confirmation is for snippet expansion, so if you don't want snippet expansion, you should avoid confirmation in your workflow.

**Comment by matklad** [comment]
Heh, these are all interesting issues!

The first one is about a missing feature in the LSP: https://github.com/microsoft/language-server-protocol/issues/793. Both "replace" and "append" behaviors are reasonable, but LSP doesn't have a way to chose this per-completion. We can and should add a global settings for this, if only to make sure that our completion infra can handle both cases. 

The second one also should be disable able with a feature flag: we just didn't get to implementing proper feature-flags infra yet :0) Long-term, when our type inference becomes 100% precise we should make these completions less noisy by, for example, only offering `.if` if lhs is a `bool`. We don't do this now because type inference fails sometimes, and, for this feature, predictability is very important. I wonder if we maybe shouldn't show these completions unless the identifier after the dot matches exactly? That seems more useful for folks, who know about this feature, but harms discoverability. Seems like another case for a feature flag!


The third one though sounds like a problem with vim plugin :)

**Comment by flodiebold** [comment]
> Long-term, when our type inference becomes 100% precise we should make these completions less noisy by, for example, only offering .if if lhs is a bool.
I think we could do that now already and just fall back to always providing it if the lhs type is unknown :thinking:

**Comment by cloudhead** [comment]
Thanks for the answers!

> With that said, I'm not sure why have this expansion in particular disabled. It does no harm, if you don't want the snippet expansion you can simply avoid expanding by simply selecting the completion but not confirming it.

Indeed, I didn't realize there was a difference until you pointed it out, using `<C-n>` seems to do what I want. Do you happen to know how to close the completion menu without exiting insert mode?

> The second one also should be disable able with a feature flag: we just didn't get to implementing proper feature-flags infra yet :0) 

Cool, that's good news!

> I wonder if we maybe shouldn't show these completions unless the identifier after the dot matches exactly?

This makes sense to me.

**Comment by oblitum** [comment]
> Indeed, I didn't realize there was a difference until you pointed it out, using `<C-n>` seems to do what I want. Do you happen to know how to close the completion menu without exiting insert mode?

I never bothered to close popup b/c in general it closes by itself once you keep typing after selection, besides I frequently go to normal mode, so for me it seems the most efficient approach since I don't need to type anything to hide stuff.

**Comment by cloudhead** [comment]
This is pretty much fixed, thanks everyone!

**Comment by oblitum** [comment]
> In this matter specifically, rust-analyzer is behaving like golsp, not providing a full snippet expansion with placeholders, just an empty (). Other LSP servers do the full expansion, which I prefer.

fwiw. Actually, `golsp` provides a `usePlaceholders` option for this: https://github.com/golang/tools/blob/master/gopls/doc/settings.md, which can be set in `initializationOptions`. I wish `rust-analyzer` provided the same, or at least that there was a fix for #2036.

**Comment by cloudhead** [comment]
Yeah I realized later that it wasn't completely fixed although things have improved. For now I stay away from pressing `<enter>` and simply complete with ctrl-n/p.

**Comment by oblitum** [comment]
@cloudhead fyi, rust-analyzer is now expanding argument placeholders in snippets. Not sure whether there's an option on that, but it's doing it by default now, and #2036 seems to have fixed by itself.
