### ISSUE TITLE
Conditional compilation not works correctly for individual items

### ISSUE THREAD

**Issue by limira** [rust-analyzer/rust-analyzer#1527]
My crate `browser-app` depends on a crate `share_lib` that supports both `wasm32` and native (Linux). In `share_lib`:
```rust
impl SomeStruct {
    // #[cfg()] on an item
    #[cfg(target_arch = "wasm32")]
    pub fn first_method(&self) {    }
}

// #[cfg()] on the whole impl block
#[cfg(target_arch = "wasm32")]
impl SomeStruct {
    pub fn second_method(&self) {    }
}
```
In `browser-app` (`target=wasm32-unknown-unknown`), the `second_method` is ok, but `rust-analyzer` complains that *no method named `first_method` found for `&share_lib::SomeStruct` in the current scope*.

I just switch from RLS to `rust-analyzer`, the whole of my `browser-app` are mark in red because of this. I try to put `.cargo/config` (with a [build] that says `target="wasm32-unknown-unknown"`) at the root of `browser-app` but it has no effect.

**Comment by jiegec** [comment]
Just encountered the same issue.

**Comment by matklad** [comment]
>but rust-analyzer complains that no method named first_method found for &share_lib::SomeStruct in the current scope.

This is error from `cargo check`, you can set feature for it using `rust-analyzer.checkOnSave.extraArgs` or `rust-analyzer.checkOnSave.overrideCommand`.
