### ISSUE TITLE
Cargo watch infinite loop

### ISSUE THREAD

**Issue by s-panferov** [rust-analyzer/rust-analyzer#1539]
Hello, I have a problem with `cargo watch` in my project. Standalone run of `cargo watch` in the console works great, but when invoked from IDE it appears to go into an infinite loop:

https://monosnap.com/file/XMcSlzqSGTtofIzCK0xkoETGGHNuhC

What information I can provide to help with debugging?

* `rust-analyzer` from master
* `vscode` stable 1.36.1

**Comment by s-panferov** [comment]
I've found the problem, I had a `build.rs` file which generated code and that triggered `cargo watch`. It would be nice to be able to configure `cargo watch` excludes.

**Comment by lnicola** [comment]
Can you use `cargo:rerun-if-changed` or such to avoid re-running the build script?

**Comment by s-panferov** [comment]
I don't think so. The problem is bigger than this, I have a monorepo where I have TypeScript code as well and I don't want `cargo watch` to trigger when I change them, so it would be nice to have an exclude list (or to be able to provide one using `cargo watch` flags).

**Comment by lnicola** [comment]
> or to be able to provide one using cargo watch flags

Maybe `rust-analyzer.cargo-watch.check-arguments`?

**Comment by s-panferov** [comment]
These arguments go "inside" the command, they are not related to `cargo watch` itself.

**Comment by kiljacken** [comment]
@s-panferov Are you still having this issue with the new in-server check watching?

**Comment by bjorn3** [comment]
> I had a build.rs file which generated code and that triggered cargo watch.

`build.rs` should never write to the source dir. Instead it should write to `OUT_DIR`. Cargo will prevent publishing a crate writing to the source dir.
