### ISSUE TITLE
Code blocks in comments aren't marked as rust

### ISSUE THREAD

**Issue by YaLTeR** [rust-analyzer/rust-analyzer#1540]
I'm using `LanguageClient-neovim` with `ra_lsp_server` c7ceea82 and the hover info it returns doesn't add the `rust` language tag to the fenced code blocks from the doc comments.

Example file:
```rust
/// Some comment.
/// ```
/// let a = 1;
/// ```
fn main() {
    let a = 1;
    let b = 2;
    let c = a + b + a + b + a + b + a;
    println!("Hello, world!");
}
```
Calling hover on `main`:
```json
{"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":3,"line":4},"textDocument":{"uri":"file:///home/yalter/Source/rust/test-project/src/main.rs"}},"id":3}
{"jsonrpc":"2.0","id":3,"result":{"contents":{"kind":"markdown","value":"```rust\nfn main()\n```\n\nSome comment.\n```\nlet a = 1;\n```"},"range":{"end":{"character":7,"line":4},"start":{"character":3,"line":4}}}}
```

**Comment by kjeremy** [comment]
So this happens here: https://github.com/rust-analyzer/rust-analyzer/blob/c7ceea82a5ab8aabab2f98e7c1e1ec94e82087c2/crates/ra_lsp_server/src/main_loop/handlers.rs#L482

The output of `to_markup()` probably needs to go through `ra_lsp_server::markdown::mark_fenced_blocks_as_rust()` which happens for `Documentation` (see https://github.com/rust-analyzer/rust-analyzer/blob/c7ceea82a5ab8aabab2f98e7c1e1ec94e82087c2/crates/ra_lsp_server/src/conv.rs#L174).

There may need to be some logic depending on if hover returned an exact match or something though. This would make a good first issue for someone.

**Comment by kjeremy** [comment]
Actually it would be a good thing if we could cleanup our markdown handling.  Right now we have both `ra_ide_api::display::rust_code_markup_with_doc` and `ra_lsp_server::markdown::mark_fenced_blocks_as_rust`

**Comment by kjeremy** [comment]
This is closed now. Added an explicity test in #1642.
