### ISSUE TITLE
Hassle-free rustfmt setup

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#155]
It would be cool to have all the code formatted with `rustfmt`. The problem is that setting up rustfmt is not-trivial (mainly because you need to know the precise version). I think a (probably slightly over-engineered) solution to this is to add `format` command to [tools](https://github.com/rust-analyzer/rust-analyzer/blob/ed736b1ac1d75eaea650d5d953950f0aed947865/crates/tools/src/main.rs) which should

* install rustfmt for a specific version of rust (command can assume rustup is used)
* run rustfmt on all code

The end goal is that `git clone ... && cd rust-analyzer && cargo format` always works.

As a bonus, add `cargo format --instal-hook`, which installs pre-commit hook for reformatting changed files. 

As an extra bonus, package that as a reusable crate.

**Comment by kjeremy** [comment]
We should probably have stuff in our `rustfmt.toml` as well

**Comment by mominul** [comment]
As I have worked on the `tools` crate earlier, I'd like to take this issue!

**Comment by alanhdu** [comment]
For installing the right version of `rustfmt`, if we're assuming that `rustup` is installed can we just used `rust-toolchain` to specify the right version or Rust and Rustfmt to use? Or is the tool supposed to do something like:

1. Push `nightly-2018-10-xx` onto override stack
2. `rustup component add rustfmt-preview` (if necessary)
3. Run `cargo fmt`
4. Pop `nightly-2018-10-xx` off of the override stack to use whatever version dev had before

?

**Comment by CAD97** [comment]
```
rustup install nightly-2018-xx-xx
rustup component add rustfmt-preview --toolchain nightly-2018-xx-xx
cargo +nightly-2018-xx-xx fmt
```

Should be sufficient. Both `rustup install` and `rustup component add` return a success code without doing work when the said toolchain/component is already installed.

**Comment by matklad** [comment]
@alanhdu more like the second approach, though, instead of overrides, you can directly call `rustup run toolchain-version -- cargo fmt`.

I don't want to pick a particular blessed rust version, I think it is OK if you, for example, just use the current nightly. For formatting though, it is important to pin the version.

**Comment by matklad** [comment]
Status update: we now have `cargo format` which reformats everything. The only thing we need is a one-time `cargo format --install-commit-hook` which adds `cargo format` as a pre-commit hook.

Unfortunatelly, we cant' just commit hooks to the repository.

**Comment by mominul** [comment]
> Unfortunatelly, we cant' just commit hooks to the repository.

I know we haven't implemented it yet, are there any restrictions you talking about?

**Comment by DJMcNab** [comment]
I think he means that we can't create a commit containing a `.git/hooks/pre-commit` file, as git doesn't support that.

The precommit hook must be manually installed
