### ISSUE TITLE
Function-local types are not resolved

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#1559]
```rust
fn main() {
    struct S;
    let _s = S;
}
```

Same for type aliases. Found in https://github.com/rust-analyzer/rust-analyzer/pull/1549.

**Comment by matklad** [comment]
Yeah, we just don't support local items at all yet :(

**Comment by flodiebold** [comment]
See #1165.

**Comment by crumblingstatue** [comment]
Funny, the original example now seems to resolve, but not if it's a record struct.

**Comment by lnicola** [comment]
Hmm, maybe https://github.com/rust-analyzer/rust-analyzer/pull/2600 partially implemented this.

**Comment by crumblingstatue** [comment]
It doesn't work, at least for me.
I did the array thing because if I just do `let foo = Bar{};`, it shows nothing instead of `{unknown}`. But if you hover over it, it will still say `{unknown}`.
![image](https://user-images.githubusercontent.com/1521976/87977811-9ed4ab00-cacf-11ea-9951-22abd45ce828.png)

**Comment by ice1000** [comment]
> It doesn't work, at least for me.
> I did the array thing because if I just do `let foo = Bar{};`, it shows nothing instead of `{unknown}`. But if you hover over it, it will still say `{unknown}`.
> ![image](https://user-images.githubusercontent.com/1521976/87977811-9ed4ab00-cacf-11ea-9951-22abd45ce828.png)

Can you fix this?

**Comment by lnicola** [comment]
> It doesn't work, at least for me.

I think you're right. I wonder why unit and tuple structs work but not record ones.

> Can you fix this?

I wish :-).

**Comment by pksunkara** [comment]
I am not sure if this is the same issue or not, but my gut says it is. Please correct me if I am wrong and I will create a new one. In the below working code, `a.foo()` doesn't resolve to a type. As you can see `impl A { fn foo() }` is actually inside a dummy mod. (This is one of pattern some derives use to reduce share some common stuff without exposing it to the user).

<img width="375" alt="main_rs_—_nested" src="https://user-images.githubusercontent.com/174703/98728606-03c35200-239a-11eb-8c3b-4376ebcd25e8.png">

**Comment by lnicola** [comment]
Yeah, it looks like the same issue.

**Comment by flodiebold** [comment]
That (a local impl used outside that block) actually a special case that might never be supported by RA, and IMO should be deprecated in the language. We don't want to have to parse all function (or constant) bodies just because they might contain an impl that we need; this would have a bad impact on lazyness.

> This is one of pattern some derives use to reduce share some common stuff without exposing it to the user

If the impl is only used in that block, that's fine, but I don't see the point otherwise.

**Comment by pksunkara** [comment]
I agree about the impact but I think we should partially support this, i.e. only if we encounter them in `const` items.

I don't think there's another way to solve the issue of scoping the use statements in expanded proc-macros.

**Comment by flodiebold** [comment]
> I don't think there's another way to solve the issue of scoping restrictions in expanded proc-macros.

Again, I don't see the point. Note that we certainly want to support using impls defined in the same block. But if you're relying on the fact that impls in blocks are available outside of that block, I don't see how that's solving any scoping issue.

**Comment by jonas-schievink** [comment]
Fixed by https://github.com/rust-analyzer/rust-analyzer/pull/7614 / https://github.com/rust-analyzer/rust-analyzer/pull/7627

The issue with `const _: () = { ... };` that @pksunkara mentioned is now tracked in https://github.com/rust-analyzer/rust-analyzer/issues/7550
