### ISSUE TITLE
Glitching syntax highlighting

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#1563]
![Schermafbeelding 2019-07-20 om 13 13 58](https://user-images.githubusercontent.com/17426603/61578013-4780b100-aaf0-11e9-951a-12c8c08f5206.png)

**Comment by matklad** [comment]
The workaround is to disable rainbow highlighitng in the settings.

https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/rainbow.20mode

**Comment by bjorn3** [comment]
That works!

**Comment by bjorn3** [comment]
Still an issue

**Comment by matklad** [comment]
This probably will be fixed once we switch to the proposed syntax highlighting API

**Comment by bjorn3** [comment]
Got it with rainbow highlighting disabled too

![afbeelding](https://user-images.githubusercontent.com/17426603/73594212-84e8e100-450c-11ea-837d-b804600cd8f7.png)

I guess I will have to wait for the syntax highlighting API.
