### ISSUE TITLE
CI: ra_vfs and proptest are not cached

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#1565]
Because they get matched by:

```bash
rm -fr ./target/debug/{deps,.fingerprint}/{*ra_*,*test*,*gen_lsp*,*thread_worker*}
```

Consider https://github.com/rust-lang/cargo/issues/573#issuecomment-468793358 as a workaround.

**Comment by matklad** [comment]
wow, that's genions! It never occured to me to use `-no-deps` for **this**
use case.

**Comment by lnicola** [comment]
Hmm, `cargo clean -p $(cd crates; ls)`?

**Comment by matklad** [comment]
let me try this out...

**Comment by bjorn3** [comment]
I think it should be:

```bash
for crate in $(cd crates; ls); do
cargo clean -p $crate
done
```

**Comment by matklad** [comment]
Let's see how https://github.com/rust-analyzer/rust-analyzer/pull/1567 looks like

**Comment by matklad** [comment]
fixed
