### ISSUE TITLE
VSCODE: command 'rust-analyzer.extendSelection' not found

### ISSUE THREAD

**Issue by jannikkeye** [rust-analyzer/rust-analyzer#1571]
I did not find an issue for this:

In VSCode when using ALT-SHIFT-ArrowKey to extend a selection left or right, a notification with `command 'rust-analyzer.extendSelection' not found` pops up.

```
Version: 1.37.0-insider
Commit: fd5985489982fe14381dd56e6f0b29c53d5f991b
Date: 2019-07-18T14:07:42.132Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0
```

**Comment by matklad** [comment]
It looks like you are using a very old version of the vscode plugin. Could you pull from master and run cargo install-code?

**Comment by max-frai** [comment]
@matklad I have same issue with last version

**Comment by matklad** [comment]
oups, looks like I forgot to remove the actual keybiding, should be fixed
now (that is, this functionality now uses build-in VS Code capabilities)
