### ISSUE TITLE
fill type info assist 

### ISSUE THREAD

**Issue by ssendev** [rust-analyzer/rust-analyzer#1580]
Since the type information is currently not perfect i often find myself typing in some type i know is wrong to get the error message with the right type and then copy paste it.

It would be nice if this could be automated. The way i imagine this to work is that when a let binding or other thing is selected that allows to explicitly name a type with `: Type` that a `: RustAnalyzerTypeCompletionDummy` is inserted. Then a `cargo check` is run and the correct type from the resulting error message is inserted.

It's probably easiest to only enable this assist when `cargo watch` is enabled but just running `cargo check` when it's activated would probably work as well.

**Comment by eupn** [comment]
> RustAnalyzerTypeCompletionDummy is inserted

IMHO the more commonly used pattern for that is to insert unit type `()` as a dummy to let rustc's type inference do the job for you.

For example, consider following code is selected:
```rust
let a = fn_returns_unknown_type();
```

after applying an "insert dummy type" assist it will look like this:

```rust
let a: () = fn_returns_unknown_type();
```

*****

Another way how it can be done is by creating a more common `specify_type` assist that will let the user specify a type of a variable in `let` binding:

```rust
let a = fn_returns_unknown_type();
```

->

```rust
let a: <|> = fn_returns_unknown_type();
```

*`<|>` denotes current cursor position*

And then you can quickly type in the `()` there.

**Comment by eupn** [comment]
Probably can be done in a similar way as in [add_explicit_type.rs](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_assists/src/add_explicit_type.rs), but without type inference.

**Comment by 0x7CFE** [comment]
Don't sure if it's the same thing as the issue, but I'd like to have an assist that would fill-in the type in the following (actually, quite common) scenario:

![type_hint](https://user-images.githubusercontent.com/3784017/66265399-f2775000-e83f-11e9-8c5c-596ad7532a94.png)

In this example we see, that Rust Analyzer was able to infer the `weights` type. So, it would be cool to put a cursor on `_` and be able to replace it with an inferred type.

**Comment by matklad** [comment]
@0x7CFE that seems slightly different, filed https://github.com/rust-analyzer/rust-analyzer/issues/1965

**Comment by bjorn3** [comment]
We have the "Insert explicit type `...`" assist now.
