### ISSUE TITLE
Can't complete `String::from`

### ISSUE THREAD

**Issue by oblitum** [rust-analyzer/rust-analyzer#1593]
Sorry if there's an issue for this already, but I'm not sure to which more general problem this relates to. I noticed that I can't get `from` after `String::`, and if I create a variable from that `let mut s = String::from("foo")`, then there's no `String` methods for completion on this variable `s`.

**Comment by lnicola** [comment]
Probably https://github.com/rust-analyzer/rust-analyzer/issues/909.

**Comment by oblitum** [comment]
This got fixed.
