### ISSUE TITLE
File not found while installing VS Code extension

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#1595]
```
> ra-lsp@0.0.1 compile /Users/djc/src/rust-analyzer/editors/code
> tsc -p ./ && shx cp src/utils/terminateProcess.sh out/utils/terminateProcess.sh

This extension consists of 194 separate files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension. You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 DONE  Packaged: /Users/djc/src/rust-analyzer/editors/code/ra-lsp-0.0.1.vsix (194 files, 343.77KB)

will run: code --install-extension ./ra-lsp-0.0.1.vsix --force
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

**Comment by matklad** [comment]
does running `code --install-extension ./ra-lsp-0.0.1.vsix --force` manually work?

**Comment by djc** [comment]
Nope -- `code` is not on my `PATH`, I guess. (This is on macOS, I've just installed the app.)

**Comment by ivfranco** [comment]
Did ecb1327 break extension installation process? Looks like the change skipped `npm run package` on windows platform and no .vsix file will be generated.

**Comment by matklad** [comment]
Heh, indeed! Looks like local testing worked only because I had an old version already packaged :(

**Comment by matklad** [comment]
Oh, this was fixed a while ago in https://github.com/rust-analyzer/rust-analyzer/commit/e29cbcbedd9586707d46e82a32c553e0a95632da#diff-5f8f2f68d562545e52b0eaa91c949db5
