### ISSUE TITLE
{p}.x = 8 doesn't parse.

### ISSUE THREAD

**Issue by jrmuizel** [rust-analyzer/rust-analyzer#1598]
The following doesn't parse in rust-analyzer but does with rustc.
```
fn main() {
    let mut p = 5;
    {p} = 8;
}
```

**Comment by flodiebold** [comment]
In which rustc version does this parse? I [get an error](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=33c91d1504348e09bcf9c61257d66447):
```
error: expected expression, found `=`
 --> src/main.rs:3:9
  |
3 |     {p} = 8;
  |     --- ^ expected expression
  |     |
  |     help: parentheses are required to parse this as an expression: `({p})`
```

**Comment by jrmuizel** [comment]
None :). I screwed up when simplifying the example. Here's a better one.
```
struct F {
    x: u32
}

fn main() {
    let mut p = F{x:5 };
     {p}.x = 8;
}
```
