### ISSUE TITLE
LSP: use rustfmt for format document/range request

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#160]
Invoking cargo fmt shouldn't be too terrible but we will need to figure out how to handle installed versions and possibly installation if missing.

**Comment by matklad** [comment]
SGTM, as long as we don't depend on rustfmt ourselves!

My long-term plan is to move rustfmt over to ra_syntax, so that we could format incomplete code, and format only selected blocks.

**Comment by matklad** [comment]
Couple of clarifications:

>SGTM, as long as we don't depend on rustfmt ourselves!

That is, we should run rustfmt as a subprocess, and all the functionality should live in `ra_lsp_server` crate, not in the `ra_analysis`. 

> document/range 

rustfmt only supports formatting whole documents.

**Comment by aleksanb** [comment]
I'll be having a stab at this issue. Trying to get up some code as a PR today!

**Comment by kjeremy** [comment]
> rustfmt only supports formatting whole documents.

You can use `rustfmt --file-lines` to format a range. From my `rustfmt -h file-lines`:

> If you want to restrict reformatting to specific sets of lines, you can
use the `--file-lines` option. Its argument is a JSON array of objects
with `file` and `range` properties, where `file` is a file name, and
`range` is an array representing a range of lines like `[7,13]`. Ranges
are 1-based and inclusive of both end points. Specifying an empty array
will result in no files being formatted. For example,

```
rustfmt --file-lines '[
    {"file":"src/lib.rs","range":[7,13]},
    {"file":"src/lib.rs","range":[21,29]},
    {"file":"src/foo.rs","range":[10,11]},
    {"file":"src/foo.rs","range":[15,15]}]'
```

would format lines `7-13` and `21-29` of `src/lib.rs`, and lines `10-11`,
and `15` of `src/foo.rs`. No other files would be formatted, even if they
are included as out of line modules from `src/lib.rs`.

**Comment by matklad** [comment]
@kjeremy IIRC, `rustfmt` actually does not support formatting lines: it can only format a specific module.

I don't think we should try too hard to support formatting specific bits of the document until we've rewritten rustfmt on top of ra_syntax.
