### ISSUE TITLE
Import missing namespace

### ISSUE THREAD

**Issue by theotherphil** [rust-analyzer/rust-analyzer#1600]
(Sorry if there's already an issue for this - I had a quick look and didn't spot any).

One of the most useful assists in Rider/Resharper is automatically importing missing namespaces: https://www.jetbrains.com/help/rider/Coding_Assistance__Importing_Namespaces.html

Do you have any pointers for how I could go about adding support for something similar to rust analyser?

**Comment by natanfudge** [comment]
I'm interested in this feature as well.

**Comment by matklad** [comment]
closing in favor of https://github.com/rust-analyzer/rust-analyzer/issues/2180
