### ISSUE TITLE
"{unkown}" type annotations could be more useful as "impl Trait"

### ISSUE THREAD

**Issue by umanwizard** [rust-analyzer/rust-analyzer#1608]
Minimal example:

```rust
trait T {}

struct S;

impl T for S {}

fn f ()-> impl T {
    S {}
}

fn main() {
    let t = f();
}
```

In VSCode with the Rust Analyzer, if I hover over `t` (in `main`) I get `{unknown}`. I suppose it's too much to hope for the analyzer to look into the definition of `f` and compute that the type is `S` (in particular since in a more complete example the type might be unnameable). However, it would be quite useful if the Analyzer could tell me `impl T` instead of just `{unknown}`.

**Comment by flodiebold** [comment]
We just haven't implemented support `impl Trait` yet.

**Comment by flodiebold** [comment]
To expand on that a bit now that I'm at a keyboard: We're kind of waiting for [support in Chalk](https://github.com/rust-lang/chalk/pull/226) for this, but we could actually already implement part of it:
 - add `Ty::Opaque` similar to the Chalk version
 - add an `ImplTrait` variant to [TypeRef](https://github.com/rust-analyzer/rust-analyzer/blob/359b3376b32b38548c71e2b6e3a7393c4396ccf6/crates/ra_hir/src/type_ref.rs#L40) (the 'unresolved' type enum)
 - implement lowering from AST to `TypeRef::ImplTrait` and from that to `Ty::Opaque`
Then we would show `impl T` in your example, we just wouldn't actually know that that means it implements `T` ;)

**Comment by unrealhoang** [comment]
@flodiebold Sounds fun, I will bug you for more details when I can find time to work on this.
