### ISSUE TITLE
Document that updating the vscode extension requires a restart between uninstall and reinstall

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#1615]
If you don't stop vscode and restart it, the old version will still be in the extensions dir and reinstall will use the old version.

**Comment by lnicola** [comment]
Do you mean "Reload window" in VS Code?

**Comment by bjorn3** [comment]
> Do you mean "Reload window" in VS Code?

No, complete restart

**Comment by lnicola** [comment]
It does? I never had any issues.

**Comment by bjorn3** [comment]
> It does? I never had any issues.

Yes, I tried to update it to get the new inlay type hints working. While trying to figure out why updating the ext didn't add the necessary setting, I found the old ext still in the extensions dir until I restarted vscode completely. I had already reloaded the window by then by clicking the reload required button.

**Comment by bjorn3** [comment]
cc https://github.com/microsoft/vscode/issues/72308

> Reload or/and restart (because sometimes if I install the updated VSIX I get the old version instead unless I rev package.json/version every time)
