### ISSUE TITLE
Make it possible to ignore directories

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#1616]
For example by reading `.gitignore`. I have a project which contains a full rust-lang/rust checkout in a subdirectory. I would like that to be ignored by ra, because I don't edit it anyway, and it takes a lot of time to index it. (Especially because it does contain artifacts from a `./x.py test` run. Those are several files for every single test file.)

Update(12min later): Currently indexing `src/llvm-project`.

**Comment by csmoe** [comment]
cc https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/ra_lsp_server.20exclude.20folderss
