### ISSUE TITLE
Rustdoc ignored lines are shown in completion and hover

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#1620]
![image](https://user-images.githubusercontent.com/308347/62045282-b1ded300-b20d-11e9-88ca-45326f5a0756.png)
![image](https://user-images.githubusercontent.com/308347/62045607-75f83d80-b20e-11e9-95cb-66e7f8e88a21.png)

**Comment by lnicola** [comment]
Could probably be fixed [here](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_syntax/src/ast/traits.rs#L117) by ignoring the lines that start with `#`.

**Comment by rizakrko** [comment]
I would like to work on this issue.

**Comment by kjeremy** [comment]
> Could probably be fixed [here](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_syntax/src/ast/traits.rs#L117) by ignoring the lines that start with `#`.

That's supposed to return the raw comment. It may make more sense to do it on the display side in [markdown::mark_fenced_blocks_as_runs](https://github.com/rust-analyzer/rust-analyzer/blob/cacdb0eab8131bfb945eb7ed0150c92ec56eefe2/crates/ra_lsp_server/src/markdown.rs#L1) (or rename that method and modify it as appropriate).
