### ISSUE TITLE
Cursor position is pretty weird in inlay hints

### ISSUE THREAD

**Issue by davyzhang** [rust-analyzer/rust-analyzer#1623]
I actually place it after p so it should look like p|, instead, it was placed after the whole inlay hints.
If I type something, it correctly put the characters behind "p" though.
In this case, it is trivial.
![image](https://user-images.githubusercontent.com/576863/62090221-392e5400-b2ab-11e9-9101-0b52e9267a39.png)

But if the inlay hints are long, this would be awkward to handle. See the demo below
![image](https://user-images.githubusercontent.com/576863/62090109-d2a93600-b2aa-11e9-8c87-7b5de137da57.png)

**Comment by killercup** [comment]
I guess this is a VSCode constraint, especially since decorations aren't really meant to be used like this. An easy way to make this a bit better might be to shorten the max length of inlay hints, i.e. showing just `RootNode<…>` in your second case. Not sure if people will like this trade-off, though.

**Comment by SomeoneToIgnore** [comment]
That will remain as is for now, unfortunately.

Here's a VS Code issue about true parameter hints support: https://github.com/microsoft/vscode/issues/16221

**Comment by matklad** [comment]
What we might want to try is attaching the decoration *before* the following token, and not after the binding. Not sure if it's a good idea though.

**Comment by killercup** [comment]
inb4

```rust
let really_long_identifier_that_is_very_descriptive
    = "but it also like to have my equal signs on the next line";
```

**Comment by matklad** [comment]
@killercup the next token here is whitespace ;)

**Comment by p-avital** [comment]
> What we might want to try is attaching the decoration _before_ the following token, and not after the binding. Not sure if it's a good idea though.

I think I've tried that on the rls-vscode client, and the cursor still insists on going to the right of the decoration. Also, keeping the decoration tied to the variable name makes hovering over the hint behave the same as Hovering over the variable, which is more convenient and might be used to show a more detailed type hint (without the abridgements for example)

**Comment by matklad** [comment]
Thanks for the input @p-avital 

Closing as an upstream issue then!

Just a reminder, it's possible to completely disable hints in the settings

**Comment by corneliusroemer** [comment]
I think the rust-analyzer extension has switched to using native type hints recently. So maybe some of these issues can now be addressed?
https://github.com/rust-lang/rust-analyzer/pull/11445

**Comment by Veykril** [comment]
This is still a client side issue with VSCode, not something r-a has control over

**Comment by caass** [comment]
I don't mean to spam a long-closed issue, but is the workaround just disabling inlay hints? Is there an issue with vscode i can track?
