### ISSUE TITLE
Receiving type hints from rust-analyzer

### ISSUE THREAD

**Issue by eupn** [rust-analyzer/rust-analyzer#1632]
Is it currently possible to get type hints from the rust-analyzer? I'm interested in getting IDEA-like experience with overlay type hints like on the following screenshot:
<img width="244" alt="image" src="https://user-images.githubusercontent.com/36292692/62315588-d6fa6c80-b4bf-11e9-96a9-d6d74fab3b84.png">

If it is possible, I wondering if there is a Vim plugin (or `coc-nvim` extension) that can talk to rust-analyzer's language server and can print those type hints in Vim.

**Comment by lnicola** [comment]
Um, have you seen https://github.com/rust-analyzer/rust-analyzer/pull/1586?

**Comment by eupn** [comment]
@lnicola thank you! That's what I was looking for. For Vim, I should probably go with custom `coc-nvim` extension for that.

**Comment by lnicola** [comment]
Note that it only works in some 80% of the cases because of other limitations of rust-analyzer.
