### ISSUE TITLE
Type hints are sometimes weird

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#1639]
![image](https://user-images.githubusercontent.com/308347/62416347-aa6e5e00-b641-11e9-80b9-29be53e39f15.png)

Bonus: check out the split `return` at the start of `fn get`. Closing the file fixed it.

**Comment by lnicola** [comment]
CC @SomeoneToIgnore

**Comment by SomeoneToIgnore** [comment]
That does not look good indeed.
If I understand it correctly, the screen shot is from the `subtree_source.rs` file, isn't it?
Any ideas on how can I reproduce it?

**Comment by lnicola** [comment]
Nope. It just happened while I was editing the file -- after adding the outer braces in the large block, I think. But I can't reproduce it.

**Comment by lnicola** [comment]
Ah. I think it's a race condition. The hints are for another file, `text_token_source.rs`, which I was looking at. I still can't reproduce it, but maybe it applied the decorations to the wrong file.

**Comment by SomeoneToIgnore** [comment]
Hm, looks like I've managed to reproduce something similar, thanks!

Hints are updated whenever we switch to a new editor tab or when we change something in the current tab.
If you open the two files, change one of them and immediately switch to the other, it may happen that the analysis results for the former file will come later than the analysis for the latter one, causing all kinds of nonsense:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/2690773/62416697-50bd6200-b648-11e9-9406-9529b4cc35de.png">

**Comment by SomeoneToIgnore** [comment]
The question is how to fix the issue properly.

Is there a way to cancel the server request from the client?
I find no code occurrences in the actual client code so I wonder if it's ok to do so in the current situation.

If not, the only way that comes to my mind currently is to store the id of the document we've queried the hints for and double check that the same document is still open before updating the decorations.

**Comment by lnicola** [comment]
Checking that the buffer is the same sounds like a good idea. Can the decorations in an inactive file be updated?

**Comment by SomeoneToIgnore** [comment]
In theory, yes, we just have to keep the reference to the corresponding `vscode.TextEditor` instance and use it when setting the decorations.
But I have no idea what will happen to the decorations if we reopen the tab after the permutations.

I'll give it a try tomorrow — if it works, we can also avoid requesting hints for the subsequent reopenings of the file.

**Comment by SomeoneToIgnore** [comment]
Looks like the decorations themselves disappear from the file when it is not displayed and we need to set them again ourselves.

**Comment by SomeoneToIgnore** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/1652 got merged, my case is not reproducible with it.

Could you double check that your issue is also gone with the fresh `master`?

**Comment by lnicola** [comment]
No, sorry, I wasn't able to reproduce it anyway. But I trust it's fixed now :-).
