### ISSUE TITLE
Feature request: add_new assist

### ISSUE THREAD

**Issue by theotherphil** [rust-analyzer/rust-analyzer#1644]
It would be useful to have an assist that generates an associated new function that populates all fields of a struct.

I'd like to give this a go. Just creating a function with one parameter for each struct field and forwarding them should be easy. To make this more useful we probably want to do something a bit smarter, but hopefully that can come later.

**Comment by matklad** [comment]
[add_impl](https://github.com/rust-analyzer/rust-analyzer/blob/658382c1f5d27813daf93495f4cbd5aada1f0567/crates/ra_assists/src/add_impl.rs) can serve as a good template. 

I am not sure what is the best UI here though. Just an assist on `struct` would work, but I fear it wouldn't be discoverable. 

Thus, it would be cool to provide this as a *code completion* as well. Basically, if user types `fn new`, suggest to pre-fill it with stuff.

**Comment by rep-nop** [comment]
Since this nor the (now closed) PR have been active in a while, I'd like to take a stab at both parts :)

**Comment by rep-nop** [comment]
Should this be applicable to tuple structs? I'm running into issues with trying to generate names for the parameters :thinking:

**Comment by memoryruins** [comment]
Since tuple structs [generate functions already](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cf76eefb799207ddbec41d4e6c884f87), it seems less important to make it applicable there. For names, the parameters could be `field0, field1, field2`, but that doesn't seem great.

**Comment by rep-nop** [comment]
Yeah I think I agree with that. @matklad would you be able to point me in a direction to find if there's already an impl block for the struct? I looked at the `impls.rs` file (I think that was it) but I can't quite figure out how to get a `Module` or `Crate` to be able to look up the impls from. I think I was on the route of looking at the ancestor of the struct to see if it was in there but trying to get a `TypeRef` from the `StructDef` wasn't obvious. Other than that a simple version of the actual fn generation seemed to work, will just need some polishing after I figure out the other stuff for this part :)

**Comment by matklad** [comment]
@rep-nop so there are two approaches we can take here, syntactic and semantic. 

For semantic analysis, you should use `FromSource::from_source` to go from `ast::StructDef` to `hir::Struct`. `hir::Struct` is associated with module and crate. It also has a type (`Ty`), which you can use with `CrateImplBlocks::lookup_impl_blocks`.

For syntactic approach, you should get the `ast::Module` / `ast::SourceFile` ancestor of `ast::Struct`, then iterate `items` of this container and find the one which is an inherent impl for our struct. 

I am not sure what's the best approach for these kind of assists, but my gut feeling is that we should go with syntactic approach, as it will naturally skip impls generated by macros, impls in other modules, etc.

**Comment by rep-nop** [comment]
Thanks for the rundown! I'll work on getting that written up soon :+1:

**Comment by rep-nop** [comment]
Looks like I have some working code, I'm going to let it bake in my mind overnight and take a look at it again tomorrow for any obvious things to clean up/fix. :D

In the mean time though, here's a quick demo of it working so far! (in the form of APNGs)

![new-fn-1](https://user-images.githubusercontent.com/24203105/67913100-4edd3f00-fb62-11e9-8db7-39f8708d5790.png)

![new-fn-2](https://user-images.githubusercontent.com/24203105/67912721-37ea1d00-fb61-11e9-8576-dc191ee57455.png)

**Comment by flodiebold** [comment]
This is done
