### ISSUE TITLE
Type hints break cursor movement

### ISSUE THREAD

**Issue by theotherphil** [rust-analyzer/rust-analyzer#1651]
Moving the cursor one character right from here:

<img width="258" alt="image" src="https://user-images.githubusercontent.com/1974256/62424616-f0bad000-b6c8-11e9-9ddf-1d660a917e6b.png">

Moves the cursor here:

<img width="258" alt="image" src="https://user-images.githubusercontent.com/1974256/62424610-e3054a80-b6c8-11e9-9976-82e0cbfb0313.png">

Typing in the new location results in text being added or removed where I'd like, but with the cursor in the wrong position. This is very confusing!

**Comment by lnicola** [comment]
https://github.com/rust-analyzer/rust-analyzer/issues/1623

**Comment by theotherphil** [comment]
Thanks. I'll just disable type hints for now then.

**Comment by lnicola** [comment]
I initially thought they would annoy me, but they're pretty useful when looking at unfamiliar code. YMMV.

**Comment by theotherphil** [comment]
I find them very useful when reading code (which was a pleasant surprise - I find similar annotations in C# to be distracting), but too much of a nuisance when editing it.

**Comment by matklad** [comment]
closing as a duplicate and an upstream issue
