### ISSUE TITLE
Server doesn't get installed when client installation fails

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#1658]
I don't have `code` in my path, but I want to use `cargo install-ra` to install the server and package the client, so that I can manually install it. The only way to compile the server even though installing the extension fails is to run `cargo install-ra --server`, which doesn't package the client extension. Maybe let `cargo install-ra` install the server and then try to install the client extension.

**Comment by matklad** [comment]
yeah, makes sense to start with the server
