### ISSUE TITLE
Code: support the new deprecated tag

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#1671]
https://code.visualstudio.com/updates/v1_37#_diagnosticstagdeprecated

**Comment by DJMcNab** [comment]
This is not supported in the protocol - see https://github.com/microsoft/language-server-protocol/issues/500. So this is currently waiting on upstream.

**Comment by lnicola** [comment]
See also https://code.visualstudio.com/updates/v1_38#_deprecation-tags-for-symbols-and-completions.

**Comment by kjeremy** [comment]
We already fill in the deprecated field on the LPS's `SymbolInformation`. I'm assuming the proposed extension API uses that?

**Comment by lnicola** [comment]
```rs
vscode.languages.registerCompletionItemProvider('plaintext', {
  provideCompletionItems() {
    const item = new vscode.CompletionItem("deprecated_completion");
    item.tags = [vscode.CompletionItemTag.Deprecated];
    return [item];
  }
});
```

**Comment by kjeremy** [comment]
Yep but that's in a custom completion provider. If it's handled in the LSP
spec then we don't have to make a custom provider.
