### ISSUE TITLE
Replace AST visitors with macros

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1672]
We have visit module which implements a visitor pattern for `AstNode`s:

https://github.com/rust-analyzer/rust-analyzer/blob/5f82012779c374d9f6b518634aefb14ce28e17e6/crates/ra_syntax/src/algo/visit.rs

It's pretty complex, but doesn't actually pull its weight. I suggest replacing it with a bunch of macros.

So, if the current code says this:

```rust
        let _ = visitor_ctx(&mut errors)
            .visit::<ast::Literal, _>(validate_literal)
            .visit::<ast::Block, _>(block::validate_block_node)
            .visit::<ast::FieldExpr, _>(|it, errors| validate_numeric_name(it.name_ref(), errors))
            .visit::<ast::NamedField, _>(|it, errors| validate_numeric_name(it.name_ref(), errors))
            .accept(&node);
```

the new code should say this instead:

```rust
        match_ast! {
            match node {
                ast::Literal(it) => validate_literal(it, &mut errors),
                ast::Block(it) => block::validate_block_node(it, &mut errors),
                ast::FieldExpr(it) => validate_numeric_name(it, &mut errors),
                ast::NamedField(it) => validate_numeric_name(it, &mut errors),
                _ => ()
            }
        }
```

and generate a chain of `if let Some(it) = ast::Foo::cast()`. Note that this should nicely sidestep the problem of borrowing a context to several closures.

**Comment by eupn** [comment]
@matklad I would like to give it a go! Did I understand correctly that `match_ast!` macro is not only the one that needs to be implemented but one of many patterns that would be simplified by introducing a macro?

**Comment by eupn** [comment]
@matklad 
>a chain of `if let Some(it) = ast::Foo::cast()`

It seems that `ast::Foo::cast(node: SyntaxNode)` requires `node` to be consumed. Since `SyntaxNode` doesn't implement `Copy`, it is required to call `.clone()` on parameter of each `cast()` call. Therefore, the chain of those `cast`s will cause `.clone()` to be called possibly many times:

```rust
if let Some(it) = ast::Literal::cast(node.clone()) {
    validate_literal(it, &mut errors);
} else if let Some(it) = ast::Block::cast(node.clone()) {
    validate_block_node(it, &mut errors);
} else if let Some(it) = ast::FieldExpr::cast(node.clone()) {
    validate_numeric_name(it.name_ref(), &mut errors);
} else if let Some(it) = ast::NamedField::cast(node.clone()) { // <- cloning can be avoided since it's a last one, but whatever
    validate_numeric_name(it.name_ref(), &mut errors);
}
```

To avoid that, I propose to generate a chain of expressions that first call `ast::Foo::can_cast(node.kind())` (`SyntaxKind` implements `Copy`) and, if `true` was returned, would perform the `ast::Foo::cast` check on cloned `node`:

```rust
if ast::Literal::can_cast(node.kind()) {
    if let Some(it) = ast::Literal::cast(node.clone()) {
        validate_literal(it, &mut errors);
    }
} else if ast::Block::can_cast(node.kind()) {
    if let Some(it) = ast::Block::cast(node.clone()) {
        validate_block_node(it, &mut errors);
    }
} else if ast::FieldExpr::can_cast(node.kind()) {
    if let Some(it) = ast::FieldExpr::cast(node.clone()) {
        validate_numeric_name(it.name_ref(), &mut errors);
    }
} else if ast::NamedField::can_cast(node.kind()) {
    if let Some(it) = ast::NamedField::cast(node.clone()) {
        validate_numeric_name(it.name_ref(), &mut errors);
    }
}
```

**Comment by matklad** [comment]
>will cause .clone() to be called possibly many times:

`.clone` on `SyntaxNode` is extremely cheap and I would even think that LLVM should be able to optimize it out. I'd rather start with the simplest possible solution.
