### ISSUE TITLE
Most of macros from std are not resolved

### ISSUE THREAD

**Issue by uHOOCCOOHu** [rust-analyzer/rust-analyzer#1688]
I'm using rust-analyzer from [master](https://github.com/rust-analyzer/rust-analyzer/commit/b1b6a90ab168c3d04038a28a3c02c69a507a3f52) with vscode extension.

I found it failed to infer the type of `vec!` (no type decorator, even no `{unknown}`), but it works well with my simple implementation using `macro_rules`. So I think there is something wrong  resolving them.

Most of macros from std do not work, except `std::dbg!`, while `dbg!` (without prefix) still fails.

The output from "Rust Analyzer Language Server Trace" contains no errors.

Screenshot:
<img width="327" alt="Screenshot_20190816_020553" src="https://user-images.githubusercontent.com/14816024/63115789-970cac80-bfca-11e9-9c10-121edb7f5c07.png">

**Comment by DJMcNab** [comment]
This is actually because we don't yet support macros in expression position

**Comment by DJMcNab** [comment]
I think this is actually because we don't yet support macros in expression position.

**Comment by DJMcNab** [comment]
I think this is actually because we don't yet support macros in expression position.

**Comment by uHOOCCOOHu** [comment]
It seems to be caused by `#[macro_use]` not working. Is it implemented yet?
Related: #60

Here is a simple example:
In `crate1/src/lib.rs`:
```rust
#[macro_export]
macro_rules! foo {
    () => { 42 };
}
```
In `crate2/src/main.rs`:
```rust
#[macro_use] // This has no effect
extern crate crate1;

// use crate1::*; // Uncomment this, and everything works

fn main() {
    let _t = foo!(); // No type inferred
}
```

**Comment by uHOOCCOOHu** [comment]
Some related issue (may be blocking issue):
1. [Textual scoped macro](https://doc.rust-lang.org/reference/macros-by-example.html#textual-scope) is partial handled now, only module level macros will be resolved (in an approximate way) and expanded.
2. `$crate` in macro is not supported.

**Comment by lnicola** [comment]
So this is still not working, however `vec!` is a bit problematic because it has two versions, gated with `#[cfg]`. Neither `vec!` nor `std::vec!` work.

But note that `vec!` is defined in `liballoc`. `format!` is defined in the same crate, and while `format!` doesn't work, `std::format!` does. So my suspicion is that there are two bugs:

 - `#[cfg]` is not supported
 - there's a prelude definition problem preventing `format!` from working

**Comment by uHOOCCOOHu** [comment]
`#[cfg]` works. The current issue is still in name resolving and importing, and I'm working on it.
