### ISSUE TITLE
Syntax Highlighting doesn't update properly

### ISSUE THREAD

**Issue by DianaNites** [rust-analyzer/rust-analyzer#1690]
Syntax Highlighting in the current tab fails to update properly with changes.

A workaround is to switch to another tab and then back, which I guess makes it recompute highlighting, but thats not very practical when writing code.

Examples:

Normal: 
![image](https://user-images.githubusercontent.com/5275194/63144445-f796ec00-bfc0-11e9-95fd-d6012aa28d9a.png)

After typing a comment:
![image](https://user-images.githubusercontent.com/5275194/63144435-e2ba5880-bfc0-11e9-8e6c-9a6effbc557a.png)

Even weirder, *some* parts of the line actually have updated, the `=`, `:`, `;`, `(`, and `)` characters are green. But `/` is blue?

----

Using VSCode 1.37.1 and rust-analyzer master, commit c7d37e424f1e04f87982233f97e1e9385191b7f1

Not using `rust-analyzer.rainbowHighlightingOn`

**Comment by shekohex** [comment]
I'm facing the same issue.

```
$ code --version     
1.37.1
f06011ac164ae4dc8e753a3fe7f9549844d15e35
x64

$ rustc -Vv                               
rustc 1.38.0-nightly (dddb7fca0 2019-07-30)
binary: rustc
commit-hash: dddb7fca09dc817ba275602b950bb81a9032fb6d
commit-date: 2019-07-30
host: x86_64-unknown-linux-gnu
release: 1.38.0-nightly
LLVM version: 9.0
```

**Comment by matklad** [comment]
That was a really stupid bug, sorry! Will be fixed by #1712 

https://github.com/rust-analyzer/rust-analyzer/pull/1712/files#diff-9234de0bfa99228a67ea76a4391c86f1R202

**Comment by matklad** [comment]
To clarify, you need to update vscode plugin to get the fix, with

cargo install-ra —client-code

**Comment by DianaNites** [comment]
Works great now, thanks!

**Comment by shekohex** [comment]
works fine :+1:  , thank you!

**Comment by DianaNites** [comment]
This same issue seems to have cropped up again, I'm on commit dbdf0e24d51ce425c0066a76a0efc723e41e5071.

Same symptoms, same repro, same workaround.

Using VSCode 1.38.1

**Comment by Geobert** [comment]
I've done `cargo install-ra --client-code` and still suffer from this:
![image](https://user-images.githubusercontent.com/72570/67641409-ee4bc900-f8f9-11e9-95ac-f12d8b7b546b.png)

**Comment by ice1000** [comment]
Very confusing highlight:
![image](https://user-images.githubusercontent.com/16398479/69763516-61d03880-113b-11ea-829b-3550469c303b.png)

Steps to reproduce: open up a properly-highlighted code file, select a bunch of code, drag them elsewhere (which messes everything up 🤣) and undo. You'll see highlighting like this.

**Comment by DianaNites** [comment]
This has regressed for me too, including for newly opened projects. Have to switch tabs to get highlighting at all when first opening a project.

**Comment by DianaNites** [comment]
Unable to test the new commit right now, but says the fix is windows only? I use Linux and experience this issue, though.

**Comment by ice1000** [comment]
But it really fixes the issue (though yet tested on Windows only)! You may check it out.

**Comment by DianaNites** [comment]
Tested now, no change on Linux from my last comment. Open new project, wait for highlighting, never highlights until tab switch.
