### ISSUE TITLE
Code Action: make pub(crate)

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#170]
when the cursor is on the leading item token: `fn`, `mod`, `struct`, `enum`, `trait`, and the item does not have a visibility, provide an "make pub(crate)" code action, which adds `pub(crate)`.

Code actions and the tests are in this file:

https://github.com/rust-analyzer/rust-analyzer/blob/46cce4f8f1b71458029ebfd391c37e27cc6c5c9c/crates/ra_editor/src/code_actions.rs

Take a look at how "flip_comma" is implemented. I think that is the only file which needs to be modified, but, if you are curios, here's the bit of code reponsible for surfacing code action to the LSP:

https://github.com/rust-analyzer/rust-analyzer/blob/46cce4f8f1b71458029ebfd391c37e27cc6c5c9c/crates/ra_lsp_server/src/main_loop/handlers.rs#L556-L586

**Comment by farodin91** [comment]
I will try this also.

**Comment by h-michael** [comment]
Does the status update?
If not, may I try it? @matklad

**Comment by Bobo1239** [comment]
This can be closed, right?
