### ISSUE TITLE
Clippy fails to run due to std::mem::drop on Copy structs

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#1704]
There are a few things that cause clippy to error out on the repo. They are all this variants of this error below:

> error: calls to `std::mem::drop` with a value that implements Copy. Dropping a copy leaves the original intact.
>    --> crates\ra_lsp_server\src\main_loop.rs:199:21
>     |
> 199 |           let event = select! {
>     |  _____________________^
> 200 | |             recv(msg_receiver) -> msg => match msg {
> 201 | |                 Ok(msg) => Event::Msg(msg),
> 202 | |                 Err(RecvError) => Err("client exited without shutdown")?,
> ...   |
> 209 | |             recv(libdata_receiver) -> data => Event::Lib(data.unwrap())
> 210 | |         };
>     | |_________^
>     |
> note: argument has type [(&dyn crossbeam_channel::select::SelectHandle, usize, *const u8); 4]
>    --> crates\ra_lsp_server\src\main_loop.rs:199:21
>     |
> 199 |           let event = select! {
>     |  _____________________^
> 200 | |             recv(msg_receiver) -> msg => match msg {
> 201 | |                 Ok(msg) => Event::Msg(msg),
> 202 | |                 Err(RecvError) => Err("client exited without shutdown")?,
> ...   |
> 209 | |             recv(libdata_receiver) -> data => Event::Lib(data.unwrap())
> 210 | |         };
>     | |_________^
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#drop_copy
>     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

I am not sure if this is an issue within clippy or points to bad usage of `drop` on our part.

**Comment by matklad** [comment]
That's https://github.com/crossbeam-rs/crossbeam/issues/404
