### ISSUE TITLE
Recommended approach with RLS

### ISSUE THREAD

**Issue by max-sixty** [rust-analyzer/rust-analyzer#1710]
I've looked for guidance elsewhere but haven't found anything, so thought it OK to venture an issue here.

What's the recommended approach in VSCode for working with RLS? Currently:
- If I turn RLS _off_, then I miss a few errors, particularly errors caught with `cargo check --all`
- If I turn RLS _on_, I get duplicate entries in autocomplete & go to definition. While it's very manageable, it does add some minor friction for what's otherwise seamless actions.

Thank you for such an awesome tool - the latency makes rust so much nicer to work with!

**Comment by DJMcNab** [comment]
I think you should use the cargo watch integration

**Comment by matklad** [comment]
Yeah, you should turn the RLS off and enable cargo-watch. To enable cargo watch, either answer "Yes" to the notification on project loading, or set the `"rust-analyzer.enableCargoWatchOnStartup": "enabled",` setting. 

Closing, but feel free to reopen if this doesn't work!

**Comment by lnicola** [comment]
Does the `cargo-watch` integration pass `--all`? There's a parameter for extra arguments, but it might explain this issue.

**Comment by max-sixty** [comment]
Thanks for the fast reply. I did have cargo-watch enabled.

I'm appreciative of rust-analyzer and the latency is awesome. For a relative newbie, a complete list of suggestions are v helpful. Is rust-analyzer expected to find as many suggestions as RLS? Or is the speed a tradeoff for completeness?

And next time I find a case where rust-analyzer doesn't have suggestions, and RLS does - should I post an issue?

**Comment by matklad** [comment]
yeah, ra with cargo watch should be equivalent to rls. Could it be the case
that RLS runs clippy by default as well, and we don't? It's possible to
override `cargo watch` command such that it triggers clippy.

**Comment by max-sixty** [comment]
I do actually get clippy lint warnings. 
I had remembered a few instances i wasn't getting 'suggestions' (what VSCode calls autocomplete), and so had to context switch into docs in the browser. I can put an issue in if that comes up again, assuming expected. (I realize difficult to engage without an actual example)

**Comment by flodiebold** [comment]
I would be surprised if there are many cases left where RLS (i.e. racer) gives better completions than RA. Feel free to open issues if you find such examples.

**Comment by max-sixty** [comment]
Great, thanks @flodiebold

**Comment by davemilter** [comment]
@flodiebold 
> I would be surprised if there are many cases left where RLS (i.e. racer) gives better completions than 
> Feel free to open issues if you find such examples.

Something off the top of my head: 

1. racer works for preprocessed files (
    https://doc.rust-lang.org/cargo/reference/build-scripts.html#case-study-code-generation),
    while rust-analyzer just reports every second: "Rust file outside current workspace is not supported 
    yet", which is very annoying.

2. racer supports autocompletition of macroses from `std::`,
  `unimplemented!` is the most used by me for new code, and I just type `un` and racer does the rest.

**Comment by max-sixty** [comment]
This is another, I think? https://github.com/rust-analyzer/rust-analyzer/issues/1622

Would be great to have this from RLS and everything else from rust-analyzer, for example. But maybe that's best implemented as a setting in RLS to exclude everything else

**Comment by oblitum** [comment]
I switched to cargo-watch+clippy but I strongly miss instant diagnostics from RLS. Is there anything being worked on in that area? On Neovim I was using rust-analyzer through coc.nvim with diagnostics disabled, and RLS through ALE for diagnostics. FWIW I didn't enable diagnostics on every input, just when leaving insert mode and normal mode edits, which is a good balance, and better than being forced to save the file to sync diagnostics.
