### ISSUE TITLE
Switch from proptest to quickcheck

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1720]
We currently use [proptest](https://docs.rs/proptest/) for testing, but it takes very long time to build (16 seconds, according to `cargo bloat`). I feel like we should switch to [quickcheck](https://docs.rs/quickcheck/), which does less.

**Comment by andreevlex** [comment]
I can try to implement this issue.
Need more info.

**Comment by matklad** [comment]
The main thing we use proptest for is generation of arbitrary text edits: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_text_edit/src/test_utils.rs#L26-L67. It is then use to check out utf8 <-> utf16 translation here:

https://github.com/rust-analyzer/rust-analyzer/blob/ebfba461123928363da55e75195d76314c51fa7e/crates/ra_ide_api/src/line_index_utils.rs#L321-L330

**Comment by andreevlex** [comment]
For what used `prop_union` here?

**Comment by matklad** [comment]
It allows to pick one of insert/replace/delete iedits

**Comment by kjeremy** [comment]
Maybe relevant: https://fitzgeraldnick.com/2020/01/16/better-support-for-fuzzing-structured-inputs-in-rust.html

**Comment by matklad** [comment]
I've removed property-based tests altogether for now.
