### ISSUE TITLE
Raw string assists

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1730]
Add the following assists:

* make raw string: `"hello" -> r#"hello"#`
* add hash: `r#"hello"# -> r##"hello"##`
* remove hash: `r#"hello"#  -> r"hello"`
* make usual string: `r"hello" -> "hello"`

Note that, ideally, we should apply escape/unescape for the first and last assist, but it's ok to *not* do it for the first pass.

Example assits are here: https://github.com/rust-analyzer/rust-analyzer/blob/e055cfacdfe3b3451484dae5d6ed08aefba133ca/crates/ra_assists/src/lib.rs

Each familiy lives in a separate mode, which contains the tests as well. See https://github.com/rust-analyzer/rust-analyzer/pull/1281 for an example of PR which adds an assist.

**Comment by bjorn3** [comment]
```diff
-make usual string: r"hello" -> r"hello"
+make usual string: r"hello" -> "hello"
```

**Comment by bjorn3** [comment]
> Note that, ideally, we should apply escape/unescape for the first and last assist, but it's ok to not do it for the first pass.

Maybe add two variants of the first assist. One which doesn't unescape and one which does. You may have the invalid `"C:\Users"` (`\U` is not a valid escape) and want to turn it into `r"C:\Users"`, or you may want to make a valid normal string into a raw string to prevent having to escape stuff.

**Comment by matklad** [comment]
The unescaping one is better as a quick fix for lexer error, and not as a separe assits, but yeah, this sounds right (but out of scope for this particular issue).

**Comment by Geobert** [comment]
What should be the result of applying `make_raw_string` to "aaa\nbbb"?
Same question with `make_usual_string` and different cases.

**Comment by matklad** [comment]
>What should be the result of applying make_raw_string to "aaa\nbbb"?

Just `r#"aaa\nbbb"#` for the first pass. Ideally, it shoould be 

```
r#"aaa
bbb"#
```

You can use `rustc_lexer::unescape` module to deal with escape sequqneces properly.

**Comment by Geobert** [comment]
Quick notice: I'm still on this, holidays are gone so less time, but I'll complete that PR :)

**Comment by Geobert** [comment]
Maybe not closing yet, I still need to do the unescape version of make_raw_string

**Comment by Geobert** [comment]
> You can use `rustc_lexer::unescape` module to deal with escape sequqneces properly.

Is there example of the usage of `unescape_str` not in an error context? (as in ra_syntax `validation.rs`)

**Comment by matklad** [comment]
@Geobert : https://github.com/rust-lang/rust/blob/4ff32c07da9d97e6dc315a4a5c9ffbb797cb27bb/src/libsyntax/parse/literal.rs#L142-L161

**Comment by Geobert** [comment]
Thanks! You mean it's `unescape_raw_str` that I need?

**Comment by matklad** [comment]
I am actually not sure I you realllu need thouse functions, or if escape default would be enough. But thouse functions definitely can tell you anything about the semantics of the literals

**Comment by Geobert** [comment]
I think I need them, `escape_default` is doing `\n` -> `\\n` and we want `\n` -> `<LF>`

My question was about choosing between `unescape_raw_str` and `unescape_str`

**Comment by Geobert** [comment]
So it's done now?
