### ISSUE TITLE
Code: use the progress reporting API

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#1762]
https://code.visualstudio.com/updates/v1_38#_language-server-protocol

**Comment by kjeremy** [comment]
Note that the proposed protocol in the npm packages from that link already diverges with what will be the final 3.15 LSP.

**Comment by matklad** [comment]
Note that we should have some notion of internal tracking of progress to add this first, and that seems pretty complicated.

**Comment by lnicola** [comment]
If we do choose to trigger an initial analysis of the project (as discussed in #1650), I suppose that's pretty similar to `ra_cli analysis-stats`.

**Comment by kjeremy** [comment]
I think it's time to revisit this.

The progress reporting protocol is now in lsp-types. LSP spec: https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workDoneProgress

Off the top of my head I can think of three things that would most benefit from this and would be relatively "easy":
1. Initial loading of the workspace
2. Finding all refs
3. Call hierarchy

**Comment by matklad** [comment]
We already do this for loading. It would be cool to use this for all requests, but I don't think this will relally work with lazy  computations.
