### ISSUE TITLE
Switch to pico-args

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1768]
We use clap, which is slow to compile. However, we only use it for internal tools, so it makes sense to switch to https://github.com/RazrFalcon/pico-args instead, which is much smaller.

**Comment by Geobert** [comment]
As RA uses subcommand, I believe this part will be manually handled? As a free param and then, according to which subcommand we have, we'll parse the relevant flags and error as needed?

**Comment by bjorn3** [comment]
Quoting pico-args readme:

> Arguments are parsed in a linear order. From first to last.

:(

**Comment by matklad** [comment]
It’s fine to change subcommand to flags

**Comment by bjorn3** [comment]
It should also be possible to handle the subcommand part by matching on the first argument and then use `Arguments::from_vec` to pass the other arguments to pico_args.

**Comment by Geobert** [comment]
Another question: what is the CLI used for? I believe it's usefull enough to trigger the will to enhance compilation time and size of the CLI binary but I can't see why

**Comment by matklad** [comment]
Two crates have cli binaries: ra_tools and ra_cli

The ra_tools is basically what's plugged into aliases in `.cargo/config`, and is used for varios development tasks like codegeneration

ra_cli is used to provide simple command-line interface for rust-analyzer, and is used mainly to check performance during development.

In short, both uses are internal, so it makes sense to compromise on CLI convenience to have smaller compile times.

**Comment by Geobert** [comment]
Thanks! I've started the task, hope it will not be too long but I'm also on a task on cobalt so I'll do my best

**Comment by Geobert** [comment]
Hi again,

Do we need help message?

**Comment by bjorn3** [comment]
A help message would be useful, as it is quicker to run `ra_cli -h` than to open `Readme.md`.
