### ISSUE TITLE
Block expression not accepted as scrutinee for 'match'

### ISSUE THREAD

**Issue by alexreg** [rust-analyzer/rust-analyzer#1773]
It is valid for the scrutinee (the expression matched upon) of a `match` expression to be a block expression, but rust-analyzer currently does not accept it.

Example:
```rust
match { 123 } {
    _ => (),
}
```

This wrongly gives syntax errors in VS Code.

**Comment by sinkuu** [comment]
`if` and `while` have this bug too.

```rust
if { true } {} else {}
//             ^ expected expression
```

```rust
while { true } {}
```

```
    WHILE_KW@[16; 21) "while"
    WHITESPACE@[21; 22) " "
    CONDITION@[22; 22)
    BLOCK_EXPR@[22; 30)
        BLOCK@[22; 30)
        L_CURLY@[22; 23) "{"
        WHITESPACE@[23; 24) " "
        LITERAL@[24; 28)
            TRUE_KW@[24; 28) "true"
        WHITESPACE@[28; 29) " "
        R_CURLY@[29; 30) "}"
WHITESPACE@[30; 31) " "
BLOCK_EXPR@[31; 33)
    BLOCK@[31; 33)
    L_CURLY@[31; 32) "{"
    R_CURLY@[32; 33) "}"
```

**Comment by matklad** [comment]
Not sure what's the issue here, but shouldb't be hard to fix. The relevant code is in https://github.com/rust-analyzer/rust-analyzer/blob/3bd99af197ea238043b364b995ec6d6069804635/crates/ra_parser/src/grammar/expressions.rs
