### ISSUE TITLE
Loading workspace failed in nightly rust

### ISSUE THREAD

**Issue by Fullstop000** [rust-analyzer/rust-analyzer#1774]
```
loading workspace failed: cargo metadata failed: Error during execution of `cargo metadata`: error: 'cargo' is not installed for the toolchain 'nightly-2019-07-19-x86_64-apple-darwin'
To install, run `rustup component add cargo --toolchain nightly-2019-07-19-x86_64-apple-darwin
```

But when I try to follow the hint: 

```
$ rustup component add cargo --toolchain nightly-2019-07-19-x86_64-apple-darwin

component 'cargo' for target 'x86_64-apple-darwin' was automatically added because it is required for toolchain 'nightly-2019-07-19-x86_64-apple-darwin'
```

And even after I reset the environment by `rustup default stable`, the error still isn't gone.

**Comment by matklad** [comment]
Does running cargo metadata from the command line work? 

This also could be a PATH issue: cargo might not be in PATH for the editor

**Comment by Fullstop000** [comment]
Thank you @matklad . 
I solved this by completely reinstalling the relative rust toolchains. Maybe something is wrong when a cargo project specifies a rust toolchain in certain version.
