### ISSUE TITLE
Process ra_lsp_server still run after vscode closed

### ISSUE THREAD

**Issue by chessnokov** [rust-analyzer/rust-analyzer#1775]
After VS code closed ra_lsp_server still run.
```bash
ps -a | grep 'ra_lsp_server\|code'
 2823 tty2     00:00:14 ra_lsp_server
```

**Comment by matklad** [comment]
I think that's #1541, which is an upstream issue (https://github.com/passcod/notify/issues/208) but https://github.com/rust-analyzer/rust-analyzer/pull/1780 implements a work-around

**Comment by matklad** [comment]
Hm, nope, this looks like a recent regression, looking into this!
