### ISSUE TITLE
Assist: replace with guarded return

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1782]
Add assist (code action, light bulb, <kbd>cltr+.</kbd>) to replace if with early return

```rust
fn foo() {
    if cond { body }
}
```

->

```rust
fn foo() {
    if !cond { return }
    body
}
```

```rust
while p {
    if cond { body }
}
```

->

```rust
while p {
    if !cond { continue }
    body
}
```

the assists should be available on the `if` expression. See https://github.com/rust-analyzer/rust-analyzer/commit/acb89d2be12f6a1556d9a366231604371a62fdcd for the recent example of the new assist addition.

**Comment by weiwei-lin** [comment]
I want to give it a try. Could take a while since I'm not familiar with the code base.

**Comment by mikhail-m1** [comment]
sorry @weiwei-lin , I should have added a comment that I am on it, but I wasn't sure in result.

**Comment by weiwei-lin** [comment]
Alright. I’ll leave it to you then.

Best Regards,
Weiwei Lin

**Comment by mikhail-m1** [comment]
Interesting, but maybe in this case should be two assists, one to convert
```
 match &self.input {
                Some(AttrInput::TokenTree(subtree)) => Some(subtree),
                _ => None,
            }
```
to  `if let ....`
and after https://github.com/rust-lang/rust/issues/53667 join in one if?
or you just want to swap branches?

**Comment by matklad** [comment]
Ah, sorry, I've forgot to specify the desired end state:


```rust
pub(crate) fn as_cfg(&self) -> Option<&Subtree> {
    if ! self.is_simple_atom("cfg") {
        return None
    }
    match &self.input {
        Some(AttrInput::TokenTree(subtree)) => Some(subtree),
        _ => None,
    }
}
```

Basically, check if `if` has two branches, one trivial and one not-trivial, and suggest making a trivial branch into an early exit

**Comment by matklad** [comment]
This is now fixed, but see https://github.com/rust-analyzer/rust-analyzer/issues/2124 for a possible extension.
