### ISSUE TITLE
{unknown} in vec

### ISSUE THREAD

**Issue by Geobert** [rust-analyzer/rust-analyzer#1785]
Here: https://github.com/cobalt-org/cobalt.rs/blob/f5381714b2cdec2abe90baa63be3d18795659c5f/src/cobalt.rs#L141

`global_collection` is marked as `{unknown}` type, but the type is in the function's param

**Comment by flodiebold** [comment]
That's just the whole `vec![...]` being of unknown type; because we don't yet manage to expand the macro, we don't even know that `global_collection` is an expression that could have a type there.

**Comment by Geobert** [comment]
Oh I see. I believe there's already an issue to track macro expansion?

**Comment by flodiebold** [comment]
Several, I think :slightly_smiling_face: #1688 seems the most directly related, but I think we could keep this open anyway and see whether this works after #1784 gets merged.

**Comment by flodiebold** [comment]
(Also, hover and autocomplete in macro invocations will probably require more fixes to work correctly.)

**Comment by ice1000** [comment]
> Several, I think slightly_smiling_face #1688 seems the most directly related, but I think we could keep this open anyway and see whether this works after #1784 gets merged.

The PR is merged, is this issue fixed?

**Comment by Geobert** [comment]
It's worse ^^' no tooltip at all

**Comment by kiljacken** [comment]
This is still reproducible, seems to be an general issue with hover inside macro arguments.

**Comment by kiljacken** [comment]
Yeah, this seems to be just #1498 now. Should we close this one and keep the other one around?

**Comment by flodiebold** [comment]
The case in #1498 actually works already though, and I'm getting hover/goto def inside `vec!` invocations as well.

**Comment by flodiebold** [comment]
I seem to remember some issue where `vec!` didn't expand correctly in some cases, but I can't find it currently.

**Comment by kiljacken** [comment]
Closing this one in favor of #1498 to keep discussion centralized :)
