### ISSUE TITLE
Rust-analyzer does not function with non-root Cargo.toml

### ISSUE THREAD

**Issue by LDSpits** [rust-analyzer/rust-analyzer#1798]
Most of the code in the vscode extension seems to assume that the cargo.toml is located in the workspace root. And that there is one cargo.toml (or project) available. 

Currently, when you try to use rust-analyzer with a cargo.toml not in the root the following error message get's shown ``[ra_lsp_server::main_loop] loading workspace failed: can't find Cargo.toml``

**Comment by LDSpits** [comment]
One of the ways that I can think of how to resolve this is to use ``vscode.workspace.findFiles()`` to locate the ``cargo.toml``, after that we can use the directory the cargo.toml is located in to specify the current working directory for both the ``CargoWatchProvider`` and the language server.

**Comment by xedrac** [comment]
Is there a way to point rust analyzer to the Cargo.toml file(s) of interest?  I've got a C++/CMake project with some Rust parts which are built with Cargo (invoked by CMake).  Currently rust analyzer doesn't work when I load the entire source tree.  It seems to assume the entire project is written in Rust.

**Comment by mitsukuri** [comment]
Same with Sublime via LSP plugin, if there's a project with code in different languages in their respective folders, it's impossible to work with the project as a whole, the only workaround is creating a separate project for Rust code just to keep the analyzer happy. The ability to set location of `cargo.toml` manually, if not automatically, is needed badly.

**Comment by matklad** [comment]
I am unlikely to have time to look into this in the nearest future, but I can leave a couple of pointers to the code where this should be handled:

* https://github.com/rust-analyzer/rust-analyzer/blob/6a5dea778b16a35d765a3a98f2ac303c5cc3df25/crates/ra_lsp_server/src/main.rs#L42-L48
* https://github.com/rust-analyzer/rust-analyzer/blob/6a5dea778b16a35d765a3a98f2ac303c5cc3df25/crates/ra_lsp_server/src/main_loop.rs#L64-L85

I think we need some kind of `additional_roots: [PathBuf]` setting, which is just added to this list.

**Comment by xedrac** [comment]
@matklad Thanks for pointing out the code of interest.  If I can find a bit of time I may attempt to implement your `additional_roots` idea.

**Comment by JP-Ellis** [comment]
Might it be worth considering what `rust-lang.rust` have done with `rust-client.enableMultiProjectSetup`?

In my case, I have a workspace with multiple rust projects, and although I get the correct code completions in each project, I don't get any warnings/errors being raised.

**Comment by Luminoth** [comment]
I'd just like to note that, with the RFC up now to transition RA to be the official Rust LSP, this issue is the single blocking issue for me and all of my coworkers looking to make the switch. It unfortunately makes RA completely unusable in all of our projects so we can't even begin to consider the transition to help with reporting issues until this is fixed.

**Comment by edwin0cheng** [comment]
cc #2649

**Comment by matklad** [comment]
This is now possible by using an explicit config. Doing dynamic auto-discovery is on the TODO list, and should be implemented soon:

https://github.com/rust-analyzer/rust-analyzer/issues/2649#issuecomment-640913470

**Comment by serovar** [comment]
Any news about the dynamic auto-discovery?

**Comment by matklad** [comment]
static config seem to work great so far, so there are no longer immediate plans for doing auto-discovery. As usual, PRs are welcome, but this is a challenging task. 

A nice intermediate goal would be to show a warning if a project is not configured propelly, with an auto-fix which sets up workspace config.
