### ISSUE TITLE
Use hashbrown crate?

### ISSUE THREAD

**Issue by mominul** [rust-analyzer/rust-analyzer#180]
[`hashbrown`](https://crates.io/crates/hashbrown) is a very fast hash map crate(uses SIMD). As it's documentation says:
> This crate is a Rust port of Google's high-performance SwissTable hash map, adapted to make it a drop-in replacement for Rust's standard `HashMap` and `HashSet` types.

If we want this, then I can send a PR!

**Comment by matklad** [comment]
Ok, let's switch!

One thing I am unsure about is if we should somehow abstract the hash map we use, to make it possible to switch impls less painfully. I'd lean towards **not** creating abstraction and just replacing rustc_hash with hashbrown everywher manually: it seems unlikely that we'll switch to yet a faster hash map anytime soon :)

**Comment by kjeremy** [comment]
> I'd lean towards not creating abstraction and just replacing rustc_hash with hashbrown everywher manually

Agreed.

I wouldn't mind seeing benchmarks too.

**Comment by matklad** [comment]
Looks like hashbrown is going to end up being `std::HashMap`:  https://github.com/rust-lang/rust/pull/56241/. So let's punt on this! Optimistically closing the issue.
