### ISSUE TITLE
Sublime Text 3 instructions aren't sufficient on Linux

### ISSUE THREAD

**Issue by kvark** [rust-analyzer/rust-analyzer#1811]
Strictly following https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user#sublime-text-3 on Linux, I'm not getting it to work: it simply fails to run `ra_lsp_server` (or `rustup`, or anything) because it's not in `$PATH` for sublime.

What I tried:
  - having `~/.profile` setting the `$PATH`
  - forcing environment for Rust build system as [described on SO](https://forum.sublimetext.com/t/why-doesnt-sublime3-use-global-path-variable-and-how-can-i-force-it-to-use-it/39392/16)
  - modifying the `.desktop` file used to launch ST3 to have the environment

In the end, wasn't able to get it to work yet. It only works when launched from the console.
Sorry if this is off-topic (arguably more of a ST3 issue than rust-analyzer). I think instructions should make the path clear.

**Comment by matklad** [comment]
Yeah, difference in `$PATH` between shell and DE on linux is a reoccurring problem... The worst thing is that, at least as far as I know, there's now single standard place to define PATH which works for both!

I don't think we can provide any better diagnostics for this problem on our side, but the docs need clarification

**Comment by matklad** [comment]
>having ~/.profile setting the $PATH

I think `~/.profile` is what is executed by non-graphical shell and `~/.xprofile` is executed by graphical login manager. I think I had some success in the past by adding `source ./.profile` line to my `~/.xprofile`

**Comment by lnicola** [comment]
You can also try to put `PATH DEFAULT=${PATH}:@{HOME}/.cargo/bin` in `~/.pam_environment`.

**Comment by kvark** [comment]
Thank you for the suggestions!
  - `~/.xprofile` didn't work for me
  - haven't tried the PAM staff because it appears that it's not shipped with Solus

What *did* work in the end though is creating `/etc/profile.d/cargo.sh` with this line:
```sh
export PATH=$HOME/.cargo/bin:$PATH
```

**Comment by lnicola** [comment]
Nb. for anyone from the future there's one issue with the `.pam_environment` approach. On some distros (Arch?), it prevents `/usr/local/bin:/usr/bin` from being added to `PATH`, so non-interactive `ssh` and `scp` stop working.
