### ISSUE TITLE
Missing "Run test" behavior above `#[test]` function

### ISSUE THREAD

**Issue by chessnokov** [rust-analyzer/rust-analyzer#1814]
After today pull, missing "Run test" behavior, and also "Implementation" above struct.

**Comment by matklad** [comment]
Which version of VS Code do you use (`code --version`)? We recently bumped out requirement, this might be the issu

**Comment by chessnokov** [comment]
```bash
$ code --version
1.38.0
3db7e09f3b61f915d03bbfa58e258d6eee843f35
x64
```

**Comment by chessnokov** [comment]
I make little workaround:
the change
```json
"rust-analyzer.cargo-watch.command": "check"
```
to 
```json
"rust-analyzer.cargo-watch.command": "check --all"
```
sometimes break standart behavior, sometimes need to reopen file
