### ISSUE TITLE
Supporting Cargo Features

### ISSUE THREAD

**Issue by sanbox-irl** [rust-analyzer/rust-analyzer#1822]
Hello! 

I have been using gfx_hal (a common crate if doing graphics work in Rust), and make great use of Cargo conditional compilation features.

The Rust analyzer is great, but has no support for them unless I set a default. I can't git ignore my cargo.toml, so I'm forced to constantly have to revert this change on each computer I use, or commit meaningless changes.

Thanks so much for all the hard work! any help would be great :)

**Comment by matklad** [comment]
It’s won’t be completely wrong to say that rust-analyzer ignores features completely at the moment. There are only two small places where we honor features:

1) when calling cargo metadata, we pass —all-features. I don’t think we need anything more here, ideally, as features should be additive
2) default features are picked up by cargo watch command. You can configure this command in the settings.

**Comment by sanboxrunner** [comment]
@matklad 2 is a good temporary substitute, but since it's done extension wide, it's not very useful. Work and hobby project have different features.

Even worse, we don't get an error. Instead, for example, I get this in cargo-watch trace:
```
Fail to parse to json : { SyntaxError: Unexpected token R in JSON at position 1 }Error on cargo-watch : {
error: Package `--v0.1.0 (/Users/--/Documents/Rust/--)` does not have these features: `metal`
}
Fail to parse to json : { SyntaxError: Unexpected token F in JSON at position 1 }
```

So I think a simple `.ra-lsp.toml` is in order to fix this.

**Comment by lnicola** [comment]
You can configure the extension settings for each (Code) workspace with the "Open Workspace Settings" command.

**Comment by sanboxrunner** [comment]
Fair dues for me right now, but I don't think that will work for other

**Comment by eminence** [comment]
I'm checking in on this old issue.   I think this might be solved now:

* rust-analyzer has controls for how the current crate is built (via `rust-analyzer.cargo.features`, `rust-analyzer.cargo.allFeatures`, and `rust-analyzer.cargo.noDefaultFeatures` settings)
* rust-analyzer can parse a Cargo.toml to learn about the features activated for a dependent crate and provide completions accordingly.

Is there anything that's still missing today?

**Comment by matklad** [comment]
Yeah, I think it makes sense to close this!

One thing we might want to do, though, is to automatically propagate settings from `rust-analyzer.cargo` to `rust-analyzer.checkOnSave`, but that needs a new issue

**Comment by sanbox-irl** [comment]
Thank you all! I should have remembered to close, but those new features have made this excellent for me

**Comment by Lucretiel** [comment]
Follow-up: is it possible to configure this on a per-crate basis when working in a cargo workspace? We're running into the problem where we only want certain features enabled by default (so allFeatures is no good) but those features only apply to one of the several crates in the workspace. It's causing errors when trying to build just other crates.

**Comment by bjorn3** [comment]
Does `cratename/featurename` work?

**Comment by Lucretiel** [comment]
> Does `cratename/featurename` work?

Just tried it, no luck.

**Comment by stephanemagnenat** [comment]
Some issue here, is there an issue for enabling features per-crate within a workspace?

**Comment by Veykril** [comment]
https://github.com/rust-analyzer/rust-analyzer/issues/10298 has been opened for that

**Comment by threema-donat** [comment]
> I'm checking in on this old issue. I think this might be solved now:
> 
>     * rust-analyzer has controls for how the current crate is built (via `rust-analyzer.cargo.features`, `rust-analyzer.cargo.allFeatures`, and `rust-analyzer.cargo.noDefaultFeatures` settings)
> 
>     * rust-analyzer can parse a Cargo.toml to learn about the features activated for a dependent crate and provide completions accordingly.
> 
> 
> Is there anything that's still missing today?

I did not find the setting `rust-analyzer.cargo.allFeatures`, although it would be very handy. Was this removed recently or was this mistakenly listed?

**Comment by lnicola** [comment]
`"rust-analyzer.cargo.features": "all"`
