### ISSUE TITLE
When will rust-analyzer be published to crates.io?

### ISSUE THREAD

**Issue by estk** [rust-analyzer/rust-analyzer#1830]
Title says it all.
Additionally it would be nice to have an issue to follow that will track when rust-analyzer will be published to crates.io.

**Comment by sentient-abanchich** [comment]
@matklad You can publish as `alpha` on crates.io. I don't know if publishing there necessarily implies the API is stable.

**Comment by matklad** [comment]
I can't do it easily because we have a git dep on chalk. If you are fine with alpha on crates.io, presumably you'll be fine with just using a git dependency. I've published a dummy package under rust-analyer name
