### ISSUE TITLE
Incompatibility with vscode-vim extension

### ISSUE THREAD

**Issue by estk** [rust-analyzer/rust-analyzer#1831]
I get the following warning when I open vscode:
```
Enhanced typing feature is disabled because of incompatibility with VIM extension
```
It would be good to have an explanation in the warning or a link to docs that explain the problem.

**Comment by osa1** [comment]
Interestingly I don't get any errors (or maybe I'm missing them) but vim plugin simply doesn't work. E.g. it shows "NORMAL" in the mode line, but "j" inserts a character instead of moving down, as in vim normal mode.

**Comment by billyrieger** [comment]
I was having this problem as well, but I noticed in the README it mentions the reason for this error:

>`rust-analyzer.enableEnhancedTyping`: by default, rust-analyzer intercepts Enter key to make it easier to continue comments. Note that it may conflict with VIM emulation plugin.

Setting `"rust-analyzer.enableEnhancedTyping": false` fixed the issue for me.

**Comment by matklad** [comment]
Yeah, adding a like to the docs to the warnings will be good!
