### ISSUE TITLE
Unclear workspace limitations

### ISSUE THREAD

**Issue by kvark** [rust-analyzer/rust-analyzer#1834]
In Sublime Text 3, my workspace contains a few folders which are themselves Cargo workspaces. Is this not a supported case for rust-analyzer? Trying to edit files shows the warning at the bottom: "Rust file outside current workspace is not supported yet"

Related to #1521 and #1798

How do I work with multiple projects in ST3 with rust-analyzer?

**Comment by matklad** [comment]
I think this should just worknow
