### ISSUE TITLE
Syntax highlighting in module not working until module is declared

### ISSUE THREAD

**Issue by Geobert** [rust-analyzer/rust-analyzer#1840]
While working on https://github.com/rust-analyzer/rust-analyzer/issues/1730

I noticed highlight does not fully work on this code:
```rust
use hir::db::HirDatabase;
use ra_syntax::{
    ast,
    ast::{AstNode, AstToken, Literal},
    TextUnit,
};

use crate::{Assist, AssistCtx, AssistId};

pub(crate) fn make_raw_string(mut ctx: AssistCtx<impl HirDatabase>) -> Option<Assist> {
    let string = ctx.node_at_offset::<Literal>()?;
    None // I put that just to be sure that mismatch type was not causing the issue
}
```
![image](https://user-images.githubusercontent.com/72570/64881764-85fb9d80-d653-11e9-8819-c0aceeb3d364.png)

Type and enum variant are not coloured.

**Comment by Geobert** [comment]
It began to be highlighted once the file has been included in `lib.rs`

**Comment by ice1000** [comment]
> It began to be highlighted once the file has been included in lib.rs

Therefore I'd say it's the expected behavior.

**Comment by matklad** [comment]
I think it makes sense to be more resilient about handing modules like this...

**Comment by Geobert** [comment]
I understand what you're saying, but from a UX point of view, I don't think it's pleasant. IMO, this falls in error tolerance category

**Comment by ice1000** [comment]
Ok

**Comment by jonas-schievink** [comment]
This is now diagnosed with a quick fix to add the right `mod` declaration, so closing.
