### ISSUE TITLE
Replace usages of bump_any with bump

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1854]
In the parser, we have two functions to advance the current token:

1. `bump_any()`, which advances over any token
2. `bump(kind: SyntaxKind)` which checks that it actually bumps over specific token.

We should replace almost all usages of `bump_any` with `bump`, like here:

https://github.com/rust-analyzer/rust-analyzer/blob/e2ebb467bdf3ebb7d29260adb95c56594c6db282/crates/ra_parser/src/grammar/type_params.rs#L11-L13

->

```rust
 assert!(p.at(T![<])); 
 let m = p.start(); 
 p.bump(T![<]); 
```
All parser functions live inside the grammar directory. It's OK to not do this in one go, and replace module by module. Note that some usages of `bump_any`  are valid.

**Comment by kjeremy** [comment]
@matklad 

Can the assertion be removed since `bump` asserts? Also I assume you mean `p.bump(T![<]);` above.

**Comment by matklad** [comment]
I'd prefer to leave the asserts at the start of the parsing functions in there
