### ISSUE TITLE
Make sure that each file has at least a placeholder doc comment in the test

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1856]
Short paragraph at the beginning of each module can greatly with understanding rust-analyzer's code. 

We should have a test (in ra_tools package), which crawls the sources of rust-analyzer, and bails on undocumented modules (`!src.starts_with("//!")`), whose name is no tests. There are a lot of such modules at the moment, so we should just add `//! FIXIME: write short doc here` to those.

**Comment by andreevlex** [comment]
I can help with this issue

**Comment by andreevlex** [comment]
Each file == module?

**Comment by matklad** [comment]
Ideally, each module, but that would require parsing rust code, which is looks like its just not worth it. So, it's better to stick with just each file

**Comment by andreevlex** [comment]
Quite often I see the marks module.
It's tests? Exclude this files from check?

**Comment by matklad** [comment]
I'd add `/// See test_utils/src/marks.rs` for those mods

**Comment by andreevlex** [comment]
Can close this issue.
