### ISSUE TITLE
"cargo check" forever in embedded dev

### ISSUE THREAD

**Issue by Geobert** [rust-analyzer/rust-analyzer#1857]
using these instructions to create a new project for an embedded project: https://rust-embedded.github.io/book/start/qemu.html

RA seems to be stuck in "cargo check" (in the status bar)

**Comment by jonas-schievink** [comment]
Same happens when running rust-analyzer on rustc

**Comment by matklad** [comment]
My guess would be that `cargo-check` dies, and we don't report this?

**Comment by matklad** [comment]
@jonas-schievink for rustc specifically, I would imagine it to be wise to disable `cargo check` altogether (`"rust-analyzer.enableCargoWatchOnStartup": "disabled",`): it won't really work on rustc, due to `./x.py` shenanigans, and, even if it worked, it would be much to slow probably.

**Comment by Geobert** [comment]
> 
> 
> My guess would be that `cargo-check` dies, and we don't report this?

How can I verify this?

**Comment by Geobert** [comment]
It seems that indeed, `cargo check` dies, I just noticed today that I have `cmd.exe` in a `Suspended` state and its command is `"cmd.exe" /C "cargo check --all-targets --message-format json  & echo [Finished running. Exit status: %ERRORLEVEL%]"`

**Comment by Geobert** [comment]
How can I trace down what's going wrong? I'd like to solve this :)

**Comment by matklad** [comment]
I'd override the `cargo check` command to something that immediatelly dies, and then launch type script extensions debugger to see what's going on

**Comment by Geobert** [comment]
Gasp, I know nothing about TS :-/ I though it was Rust's side ^^'

**Comment by kiljacken** [comment]
@Geobert Can you replicate this problem when using the new in-server watching?

**Comment by Geobert** [comment]
Unfortunately, I don't have access to the env where I got this error anymore :-/ (changed job, not embedded anymore)

**Comment by kiljacken** [comment]
That completely okay. The in-server cargo check functionality should handle cargo check dying gracefully, should we close this for now?

**Comment by Geobert** [comment]
I agree, I can't verify anyway :)
