### ISSUE TITLE
Question about updates

### ISSUE THREAD

**Issue by Astrantia** [rust-analyzer/rust-analyzer#1864]
I installed rust-analyzer successfully for vscode, following the automated steps in the guide. Is it safe to delete the folder I git cloned now that I've got the extension in vscode? Also will I get updates automatically or should I be git cloning every major release and redoing the steps over again? Thanks for working on RA.

**Comment by bjorn3** [comment]
Updates are not automatically. To speedup updating, you can use `git pull` inside the folder, instead of cloning it again. You can safely delete the folder if you want. The language server itself is found in `.cargo/bin` inside your home dir and the ext is found inside the vscode config dir.

**Comment by Astrantia** [comment]
> Updates are not automatically. To speedup updating, you can use `git pull` inside the folder, instead of cloning it again. You can safely delete the folder if you want. The language server itself is found in `.cargo/bin` inside your home dir and the ext is found inside the vscode config dir.

Thanks!
