### ISSUE TITLE
Error: Can't execute `code --version`. Perhaps it is not in $PATH?

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#1865]
Since #1595 is fixed, I tried to install it again. However, it fails with the error in the title. I'm running the VS Code Insiders build, could that be why? This is on macOS.

**Comment by matklad** [comment]
Yeah, for insiders you need to follow manuall installation process: https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user#vs-code. But this comes up repeatedly, so we should fix it. The binary is called `code-insiders`, right?

**Comment by djc** [comment]
Yup, that's it. (Although previously I had not done the work to actually install it in the PATH. Maybe you could link from the README to https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line as a prerequisite for this to work?)

**Comment by matklad** [comment]
closed by https://github.com/rust-analyzer/rust-analyzer/commit/1e16ac031542b629d7997816592742dbf9f911f6
