### ISSUE TITLE
support `rust-analyzer.enableCargoWatchOnStartup` for emacs

### ISSUE THREAD

**Issue by sentient-abanchich** [rust-analyzer/rust-analyzer#1869]
I see `rust-analyzer.enableCargoWatchOnStartup` in the docs for VS Code users and that Vim has an equivalent. Is there a way to enable compilation error checking like this in Emacs?

**Comment by kiljacken** [comment]
As of #2668 we now have support for running cargo check on save in all editors. This can be closed.
