### ISSUE TITLE
Rust analyzer fails to understand tuple destructured using index

### ISSUE THREAD

**Issue by nbigaouette** [rust-analyzer/rust-analyzer#1870]
I've found a weird pattern that was used in our code base where an enum gets `match`ed using the "index notation" (I don't know how to call this...)

RLS understands that syntax but ra fails. I've created a minimal example to showcase this:

```rust
enum E {
    A(u8),
    B,
    C(u16),
}

fn check(e: E) {
    match e {
        // rust-analyzer fails here
        E::A { 0: 1 } => println!("E::A(1)"),
        // rust-analyzer fails here
        E::A { 0: 2 } => println!("E::A(2)"),
        E::A(3) => println!("E::A(3)"),
        E::A(i) => println!("E::A(i={})", i),
        E::B => println!("B"),
        E::C(4) => println!("E::C(4"),
        // rust-analyzer fails here
        E::C { 0: j } => println!("E::C(j={})", j),
    }
}

fn main() {
    check(E::A(1));
    check(E::A(2));
    check(E::A(3));
    check(E::A(4));
    check(E::B);
    check(E::C(4));
    check(E::C(5));
}
```

![Screen Shot 2019-09-18 at 12 32 42 PM](https://user-images.githubusercontent.com/112988/65167390-f62e6880-da31-11e9-8136-cb29c099dd9f.png)

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b627cf4d95693b560735cbfea4f461fd

I am using rust-analyzer d505ee968b2a99eed65dfe7be27940ad9b2647c1.

**Comment by kjeremy** [comment]
@matklad I want to take a crack at this but am a little unfamiliar with the parsing/syntax part of the code. Can you give some pointers?

**Comment by matklad** [comment]
All the parsing code lives in `ra_parser/src/grammar`, which has a hierarchical strcuture which correponds to the structure of the Rust langauage itself. In particular, parsing of record patterns is handled by `record_field_pat` in `patterns.rs`.

The easiest way to test this during dev is to modify and run `parse_smoke_test`. For real tests, it's best to dump the example to `ra_syntax/test_data/parser/ok`, or to use an inline test in a comment

**Comment by nbigaouette** [comment]
I've updated ra to 7d6c3de890744a143ab2086a79f21fe4ff06008a and it now works. Great job! And thanks a lot!
