### ISSUE TITLE
Move `cargo watch` support from typescript to rust

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1894]
We support showing errors inline in the editor by running `cargo watch` on the client side and processing it's results. This is implemented here:

https://github.com/rust-analyzer/rust-analyzer/blob/468e1d14c1a4b3d646207ae919082dc17753cd31/editors/code/src/commands/cargo_watch.ts

We should move this functionality into the server, to make it available for all clients. The value added here is translating rust specific JSON messages from the compiler to the LSP messages, which are understood by many editors. 

This functionality should be a separate module in the `ra_lsp_server` crate. 
We shouldn't use `cargo-watch` and instead we should manage cargo execution ourselves. 
The execution should be triggered by change notification (similarly to how diagnostics are triggered today). The execution should be propertly debounced: 
* schedule a compilation immediately after any change after a period of quiescence
* don't schedule a compilation more that once in 100 ms
* always eventually schedule a compilation after every change
* denouncing behavior should be tested

We should also clear existing diagnostics after every modification (ideally, we should just shift the ranges, but that can be done later).

It should be possible to disable this functionality. The default should be ON. 

Tests should avoid using real cargo (as that is slow), and instead used recorded traces of cargo execution with `--message-format=json`

**Comment by marcogroppo** [comment]
Mmm what's wrong with `cargo watch`? Correct me if I'm wrong but `cargo check` can only be called after the file has been saved, it can't run after simple in-memory changes. We would basically re-implement `cargo watch` here, with LSP notifications in place of `watchexec`...

**Comment by matklad** [comment]
Yeah, I think it makes sense to re-implemnt `cargo watch` eventually. For example, to be more flexible about notification mechanism and be smarter about which packages in the workspace we are compiling. OTOH, I won't actually mind just calling `cargo watch` as a first approximation.

**Comment by bkchr** [comment]
I think it would also be nice to not use the same `target` folder for this new functionality. I often see that my normal `cargo build/whatever` workflow is interrupted by waiting for `cargo watch` to finish the currently running check.

**Comment by matklad** [comment]
@bkchr that's an interesting consideration! Just using a separate target dir won't be enough: running `cargo test` and `cargo check` at the same time is still suboptimal, b/c there's only so much CPU. The right solution here is to interrupt the `check` if another build command is issued. Interrupting is easy: `cargo` is safe to kill. Detecting if another build is requested would be harder though: we can do this if it comes from code-lens, but if it comes from the command line, there seems to be no good way to detect it?

I think that, for starters, we should just add an ability to configure the env of `watch`ing command, such that the user can set `CARGO_TARGET_DIR` themselves.

**Comment by marcogroppo** [comment]
you could set the cargo watch command in the RA extension settings to `check --target-dir=foo` where `foo` is the target directory

**Comment by bkchr** [comment]
> @bkchr that's an interesting consideration! Just using a separate target dir won't be enough: running `cargo test` and `cargo check` at the same time is still suboptimal, b/c there's only so much CPU. The right solution here is to interrupt the `check` if another build command is issued. Interrupting is easy: `cargo` is safe to kill. Detecting if another build is requested would be harder though: we can do this if it comes from code-lens, but if it comes from the command line, there seems to be no good way to detect it?
> 
> I think that, for starters, we should just add an ability to configure the env of `watch`ing command, such that the user can set `CARGO_TARGET_DIR` themselves.

I think having a different target dir should be enough for the start. You are right that it wastes CPU resources, but I rather waste some CPU resources, instead of waiting for cargo to release the lock to the whole target dir :) 

@marcogroppo ty!

**Comment by lnicola** [comment]
Using separate directories will often waste a lot of disk space. I think using the same destination is a good default.

**Comment by kiljacken** [comment]
You can always go re-save a file in your editor. That should cancel the running check/clippy run and allow your command to progress.

**Comment by kjeremy** [comment]
In thinking about it this might fix the stale diagnostics issue.

**Comment by kiljacken** [comment]
I'd love to give this a go. I have one question up front though: Do we have a smart way to handle a potentially long running task in the lsp-server currently? If not that'll be an interesting challenge as well.

**Comment by matklad** [comment]
In the current impl, we already schedule most tasks asynchronously. We don’t do any progress reporting however.

**Comment by kiljacken** [comment]
It's alive!

![working-output](https://user-images.githubusercontent.com/209321/71426070-bb794380-26a4-11ea-80e3-cddec8297794.png)
