### ISSUE TITLE
Support UTF-8 for the LSP protocol

### ISSUE THREAD

**Issue by XVilka** [rust-analyzer/rust-analyzer#1901]
See the lengthy discussion here: https://github.com/microsoft/language-server-protocol/issues/376

It seems that rust-analyzer is one of a few that uses UTF-16 https://github.com/Avi-D-coder/lsp-range-unit-survey

Would be nice if it will have UTF-8 support as well, at least optionally.

**Comment by matklad** [comment]
We use UTF-16 just because it’s in the spec. We’d gladly drop the code to support UTF-16 in favor of UTF-8 byte offsets, but only if that is specification/extension to the specification.
