### ISSUE TITLE
Assist: Add doc comment

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#1915]
It would be nice if when the cursor was on a `ast::DocCommentsOwner` with no existing comment that we could be prompted to add a new doc comment (probably defaulting to `///`).

**Comment by matklad** [comment]
Not sure if assist would be that valuable: typing `///` is not to hard (in contrast to `#[derive()]`). What would be cool is a quick-fix for `#[deny(missing_docs)]`.

**Comment by sploiselle** [comment]
It would be nice when you're already in a doc comment, entering a carriage return places `///` on the new line. This mirrors the behavior of the default `rls`.

**Comment by lnicola** [comment]
@sploiselle that's already available: https://rust-analyzer.github.io/manual.html#on-enter.

**Comment by sploiselle** [comment]
@lnicola Oh thank you! I was trying to find something about doc comments and didn't think to search for that string.

**Comment by numero-744** [comment]
I think this issue can be closed, or is there still work to do?
