### ISSUE TITLE
Warnings don't show up until `cargo clean` or file change in VSCode

### ISSUE THREAD

**Issue by arsdragonfly** [rust-analyzer/rust-analyzer#1929]
Right now diagnostics depend on the JSON output of `cargo check --all-targets --message-format json`, which won't yield any warnings for files that have already been built. Only after `cargo clean` has been run and/or the file has been saved again will warnings pop up.

**Comment by kiljacken** [comment]
@arsdragonfly This has presumably been fixed upstream at some point, as it seems to work on my end. Can you confirm?

**Comment by bjorn3** [comment]
Cargo caches warnings since https://github.com/rust-lang/cargo/pull/7450.

**Comment by kiljacken** [comment]
Then we can probably close this one too.
