### ISSUE TITLE
Add vscode task provider like rls-vscode

### ISSUE THREAD

**Issue by mwilliammyers** [rust-analyzer/rust-analyzer#1935]
I use this as my daily driver and it is awesome - thanks for providing such a great IDE experience!

Something that I miss from RLS (in Sublime & VSCode) was builtin tasks support.

Any chance of adding support for the [vscode task provider API](https://code.visualstudio.com/api/extension-guides/task-provider) like the official vscode extension has so that `cargo` tasks are automatically detected by vscode? Or is there a reason why [this](https://github.com/rust-lang/rls-vscode/blob/ffe36f31b7a7105c6127f44e407dd828f94d1709/src/tasks.ts) file wasn't cherry picked from [rust-lang/rls-vscode](https://github.com/rust-lang/rls-vscode)?

**Comment by mwilliammyers** [comment]
Ahh, just found [these](https://github.com/rust-analyzer/rust-analyzer/blob/dbdf0e24d51ce425c0066a76a0efc723e41e5071/editors/code/package.json#L156) keybindings etc., but I still think it is worth using the task provider API to be consistent with other languages/build tools using vscode...?

**Comment by matklad** [comment]
The reason why we can't use task provider interface instead of our "run" thing is that task provider is a pretty limited thing. In particular, task providers don't have access to *current* cursor position, open file, etc, so it's impossible to implement something like "run *this* test" using a task provider.

We can provide a task provider *in addition* to "run rust" action.

**Comment by mwilliammyers** [comment]
Ahh, makes sense, yeah I should have said "worth adding" instead of "worth using"- having both would be best. 

I can open a PR, although I am not sure what the protocol is for me ~~stealing~~ copying & pasting the [file](https://github.com/rust-lang/rls-vscode/blob/ffe36f31b7a7105c6127f44e407dd828f94d1709/src/tasks.ts) from the rust-lang repo... :man_shrugging:

**Comment by matklad** [comment]
Just copy&paste it :) Note that we have a pretty strict linting check for rs on CI, so you might need to run `npm run fix` as well.
