### ISSUE TITLE
VSCode extension notification always opens output

### ISSUE THREAD

**Issue by DianaNites** [rust-analyzer/rust-analyzer#1941]
When the VSCode extension has an error, it displays a notification saying a request has failed, and a button to go to the output.

Closing this notification always opens the output tab, instead of when the button is pushed. By clicking the X in the notification or clearing all notifications.

Steps:

1. Trigger an error. A tilde at the end of a line does this nicely.
2. Attempt to close the notification.
3. Focus is forcibly changed to extension output.

**Comment by marcogroppo** [comment]
I think this is the behavior of the VSCode LSP client: https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L2712 
As you can see the first argument of the `then` closure is ignored (it's not declared), this means that the `outputChannel` is shown unconditionally. The `showInformationMessage` function is documented here: https://code.visualstudio.com/api/references/vscode-api

**Comment by matklad** [comment]
Yeah, it seems like an upstream issue to me as well!
