### ISSUE TITLE
Wrong type inference in if and match with return statement

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#1944]
```rust
fn foo(x: Option<i32>) {
    let _x = if let Some(y) = x {
        y
    } else {
        return;
    };
}
```

Here, `_x` is inferred as `()` instead of `i32`. Also works with `if x.is_some() { 3 } else { return; }`.

CC #1505, #1680, @SomeoneToIgnore.

**Comment by flodiebold** [comment]
We need to keep track of whether the code diverges for this. `{ ... some code; }` has type `()`, but if it always diverges, it can also have type `!`... or maybe it always has that type in that case, I'm not sure. Consider examples like `some_function(return)`...

**Comment by lnicola** [comment]
Right, I thought it works for `match` but it doesn't:

```rust
fn foo(x: Option<i32>) {
    let _x = match x {
        Some(y) => y,
        _ => {
            return;
        }
    }; // ()
}

fn bar(x: Option<i32>) {
    let _x = match x {
        Some(y) => y,
        _ => return
    }; // i32
}
```

**Comment by lnicola** [comment]
I think the "simple and obvious" way to do this will break inference in this case:

```rust
fn test(a: u32, b: isize, c: !, d: &str) {
    a;
    b;
    c;
    d;
    1usize;
    1isize;
    "test";
    1.0f32;
}
```

The function returns `()`, but `c;` seems to diverge.

**Comment by flodiebold** [comment]
No, that's fine -- the return type of the function is `()` in any case, and `!` coerces to that anyway. Still, someone needs to look into how rustc handles this before implementing it.
