### ISSUE TITLE
Inline type hints could become too long sometimes

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#1946]
```
commit 31f22d85491d9e7eaadf5fd4f9754c83fc0f3ea6
Merge: ebfba4611 2643ab1d1
Author: bors[bot] <26634292+bors[bot]@users.noreply.github.com>
Date:   Mon Sep 30 19:10:57 2019 +0000
```

tldr:
![type_hint_omg](https://user-images.githubusercontent.com/3784017/66043939-a760f280-e54a-11e9-882d-aa674d197876.png)

Obviously it could be waaay longer than this, but I picked this just as an illustration.

The solution is probably to replace long lines with ellipsis `...`. Or rather, reduce the length by leaving only top-level types, like `Vec<...>` or `Iterator<...>` instead of `Vec<SomeLongAndComplicatedType...>`.

P.S.: Somewhere inside rustc or clippy we already have lints for overcomplicated types with a suggestion to use typedefs instead. Maybe we may use it here as a metric somehow.

**Comment by matklad** [comment]
Yeah, this is an important thing to fix.

We need two lines of defense here:

* first, in the UI layer, we should chop hints to, say, 20 symbols (maybe configurable via an options)
* second, in the logic layer, we should try to make the hints more compact. 

Some of the simple things which we should do are:

* don't show closure types (replace them with `_`)
* don't show default values of type parameters (just omit them)

Some of the more challenging things which we should do:

* use type-aliases if possible
* replace telescopit iterator types with `impl Iterator<Item = >`

**Comment by ice1000** [comment]
In IntelliJ IDEA, inline type hints are folded into `...` when too long, and they can be expanded by clicking the `...`.

**Comment by Swatinem** [comment]
Maybe a bit off-topic, but is it possible to completely remove these inline type hints? I haven’t found anything about it in the docs, and I much rather prefer the code I see to match the things that I write, with additional information available via hover or hotkeys.

**Comment by detrumi** [comment]
> Maybe a bit off-topic, but is it possible to disable these inline type hints? I haven’t found anything about it in the docs, and I much rather prefer the code I see to match the things that I write, with additional information available via hover or hotkeys.

They can be disabled by setting `rust-analyzer.displayInlayHints` to false

**Comment by SomeoneToIgnore** [comment]
I've done a quick research on the `don't show default values of type parameters (just omit them)` proposal.
Currently we use [type_of_pat](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_hir/src/source_binder.rs#L222) method to get the type information, but looks like `InferenceResult` struct holds no info about the default values for the parameters.
Is there a place from where I can get that info?

**Comment by matklad** [comment]
@SomeoneToIgnore the relevant query is `generic_defaults`.

**Comment by kiljacken** [comment]
With both truncation of types in inlay hints and hiding of default types now implemented, this is probably safe to close.

**Comment by coolreader18** [comment]
Would it be possible to have an option to not expand type aliases for inlay hints? I like the hints, but the main purpose of type aliases is to hide a complex type behind a more friendly name, and that also serves as an abstraction over what can be a pretty ugly type definition. I'd bet that for many type definitions, developers don't even necessarily know that it is an alias, or if they do, what the alias actually is for, and therefore expanding the alias to its full form isn't always very helpful.

**Comment by flodiebold** [comment]
It's not that simple. The hints (necessarily) come from type inference, and type aliases are expanded before any type inference happens. There are some plans to model type aliases differently where they would be expanded 'lazily', but that's not trivial to implement.

**Comment by thomwiggers** [comment]
I'm still seeing some very long types, has this issue returned?

![image](https://user-images.githubusercontent.com/974662/106250044-672f8400-6213-11eb-9e47-426d6c1f11ed.png)

**Comment by SomeoneToIgnore** [comment]
Had never got away, long types are always with us in Rust.

This particular one seems to be caused by Chalk reaching its depth limit: at some level of nestedness, Chalk gives up on detecting whether a trait is implemented by a struct or not.
We rely on the trait inference when replacing such constructs with `impl Iterator<T>`

If you could provide a way to reproduce this without extra libs, it would be helpful.

**Comment by flodiebold** [comment]
As mentioned above, you can configure a size limit for your type hints though (`rust-analyzer.inlayHints.maxLength`).

**Comment by thomwiggers** [comment]
the `inlayHints` option does help.

In any case, here's an example program that has complicated "long" types.

```rust
use rayon::prelude::*;

fn main() {
    let once = rayon::iter::once(1);
    let repeat_n = rayon::iter::repeatn(3, 10);
    let iter = once
        .clone()
        .chain(repeat_n.clone())
        .zip(repeat_n.clone().chain(once.clone()))
        .zip(repeat_n.clone().chain(once.clone()))
        .map(|a| a);
    let a = iter.clone().zip(iter);

    std::mem::drop(iter)
}
```
