### ISSUE TITLE
Inner attributes not work

### ISSUE THREAD

**Issue by oxalica** [rust-analyzer/rust-analyzer#1949]
See [this comment](https://github.com/rust-analyzer/rust-analyzer/pull/1928#issuecomment-536495179)

`foo!` is not resolved in this case:
```rust
mod m {
    #![macro_use]
    macro_rules! foo { () => { struct S; }; }
}
foo!();
```

Most of control attributes on items are affected, including #1928

**Comment by lnicola** [comment]
This is working now:

![image](https://user-images.githubusercontent.com/308347/102757373-ea8ac980-4379-11eb-9327-e276cb1997d5.png)
