### ISSUE TITLE
Confusing label ast

### ISSUE THREAD

**Issue by pasa** [rust-analyzer/rust-analyzer#1953]
There are plenty of such test in label parsing tests:
```
LABEL@[31; 34)
    LIFETIME@[31; 33) "\'b"
    COLON@[33; 34) ":"
```
This is confusing. because `'b` is not a lifetime. I guess `IDENT` will fit here much better.

**Comment by bjorn3** [comment]
Rustc's `libsyntax` [internally parses a lifetime and then removes the `'` returning an ident + span](https://doc.rust-lang.org/nightly/nightly-rustc/syntax/parse/parser/struct.Parser.html#method.eat_label). ra_syntax can't remove the `'`, as every single char in the input file must have a node in the concrete syntax tree ra_syntax creates.

**Comment by matklad** [comment]
Are there better names for `'ident` token? It seems like “lifetime” is the best one, although it is confusing if used for labels

**Comment by kiljacken** [comment]
When using it to refer to both lifetimes and labels one could always go with "region", but I'm afraid that might be bit to "theoretical" for some folks.

**Comment by matklad** [comment]
Hm, I must say, I like @kiljacken suggestion in principle, but, in practice, I'd prefer a less jargony lifetime.
