### ISSUE TITLE
rustfmt does not seem to be working on latest nightly.

### ISSUE THREAD

**Issue by bIgBV** [rust-analyzer/rust-analyzer#1955]
Version info:

```
➜ cargo --version
cargo 1.40.0-nightly (8b0561d68 2019-09-30)
➜ rustc --version
rustc 1.40.0-nightly (032a53a06 2019-10-03)
➜ rustfmt --version
rustfmt 1.4.8-nightly (afb1ee1c 2019-09-08)
```

When running format document from within VS code, or invoking the format command through LSP in vim, nothing happens. But when executing `cargo fmt` from the terminal, the files are formatted correctly.

**Comment by davidbarsky** [comment]
Same, I've also been encountering this issue, and I'm not entirely sure _why_ it broke. Could it be a bad interaction with `rustup` + what nightly is set as a default?

**Comment by kanekv** [comment]
I have same with non-recent nightly: `rustc 1.39.0-nightly (eb48d6bde 2019-09-12)`

**Comment by lnicola** [comment]
I suspect this is #4249. Does it still happen?

**Comment by matklad** [comment]
Closing, as it's unclear how to reproduce this.
