### ISSUE TITLE
ra_lsp_server 100% CPU consumption non-stop

### ISSUE THREAD

**Issue by kanekv** [rust-analyzer/rust-analyzer#1958]
I believe this issue was already reported earlier and closed as fixed. I've just installed rust analyzer and found that it uses 100% (and sometimes 200%) of CPU and doesn't dwindle down. Also ra_lsp_server stayed up when I quit vs code. 
I'm on latest master atm
```
commit 7d1bb35fb179b7e55ceb9c5354d9d74bffb8ca63 (HEAD -> master, origin/staging, origin/master, origin/HEAD)
Merge: e1c36759 9638adaa
Author: bors[bot] <26634292+bors[bot]@users.noreply.github.com>
Date:   Thu Oct 3 15:03:29 2019 +0000
```

**Comment by matklad** [comment]
What OS are you using? If you are on Mac, could you try enabling [`rust-analyzer.useClientWatching`](https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/README.md#settings) option?

It would also be useful to get a stack trace from rust-analyzer at 100% CPU.

**Comment by kanekv** [comment]
@matklad Indeed, this option helped, looks like right now it works as expected!

**Comment by matklad** [comment]
Cool! The underlying problem is tracked upstream.
