### ISSUE TITLE
.to_owned shows unknown type

### ISSUE THREAD

**Issue by kanekv** [rust-analyzer/rust-analyzer#1961]
`let s = "test".to_owned()` - shows `unknown` type.

**Comment by ice1000** [comment]
Maybe it's relevant to `trait`'s `Self` type:

```rust
pub trait ToOwned {
    type Owned: Borrow<Self>;
    fn to_owned(&self) -> Self::Owned;
}
```

**Comment by matklad** [comment]
A good first step here would be to write a reproduciable test-case, using our own versions of `Borrow` and `ToOwned`, to `ty/tests.rs`

**Comment by flodiebold** [comment]
I _think_ the problem lies with actually normalizing the projection in Chalk, because of https://github.com/rust-lang/chalk/issues/234. There are sadly still lots of cases where associated types don't work because of this. I might be wrong though, and the problem might be somewhere before that.

**Comment by flodiebold** [comment]
This should be fixed in master.
