### ISSUE TITLE
Support reloading of Cargo workspace

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1968]
Steps:

* transition to lazy VFS model
* figure out how to deal with changing roots
* implement dumb reloading
* implement smart reloading, which tries to keep incremental results fresh (do we really need this? Perhaps we just need rmeta files)

**Comment by matklad** [comment]
I don’t know yet :)

One approach is to indeed to try just re-use the same ids. I feel though that correlating ids might be awkward (or might require another layer of interning?). 

Moreover, I feel that reload, ideally, should work exactly like restarting the server process, to have one code path for both cases, and to make it fast. But that depends on implementing persistence layer...

**Comment by flodiebold** [comment]
Is the "lazy VFS model" #293, or something else?

**Comment by matklad** [comment]
Something else, though more concrete recently. I believe we should more or less re-use https://docs.rs/watchman_client/0.4.0/watchman_client/ API for VFS.
