### ISSUE TITLE
Platform-specific type inference results?

### ISSUE THREAD

**Issue by marcogroppo** [rust-analyzer/rust-analyzer#1971]
Apparently `ra_cli analysis_stats` is returning different results in Windows and in Linux. 

I have two clones of the `rust-analyzer` repository, one in Windows and one in Linux (WSL, actually, but @lnicola was observing different results on "real" Linux, too). They're both at the current HEAD (06a8deae4a29949f438d66c54eed4e016ac35432). 
Running `target/release/ra_cli analysis-stats .` in the workspace's directory returns subtly different type inference stats, while the total number of modules, declarations, functions and expressions is exactly the same.

There is probably an obvious explanation that I'm failing to grasp... however, I had to report this.

This is the output of `ra_cli analysis-stats .` on Windows:

```
Database loaded, 215 roots, 21.7519195s
Crates in this dir: 28
Total modules found: 307
Total declarations: 10525
Total functions: 3697
Item Collection: 8.0334572s, 0b allocated 0b resident
Total expressions: 85589
Expressions of unknown type: 6720 (7%)
Expressions of partially unknown type: 3178 (3%)
Type mismatches: 3862
Inference: 23.7711304s, 0b allocated 0b resident
Total: 31.8049532s, 0b allocated 0b resident
```

And this is the output on Linux:

```
Database loaded, 215 roots, 13.8991603s
Crates in this dir: 28
Total modules found: 307
Total declarations: 10525
Total functions: 3697
Item Collection: 7.264299s, 0b allocated 0b resident
Total expressions: 85589
Expressions of unknown type: 6711 (7%)
Expressions of partially unknown type: 3177 (3%)
Type mismatches: 3859
Inference: 20.2804133s, 0b allocated 0b resident
Total: 27.5450941s, 0b allocated 0b resident
```

**Comment by lnicola** [comment]
Strange, in https://github.com/rust-analyzer/rust-analyzer/issues/1842#issuecomment-538664356 we had a much larger difference. See also #1552.

**Comment by marcogroppo** [comment]
@lnicola yes, that's weird too

**Comment by lnicola** [comment]
And now we get the same numbers:

```
Database loaded, 215 roots, 3.655811662s
Crates in this dir: 28
Total modules found: 307
Total declarations: 10525
Total functions: 3697
Item Collection: 7.111485641s, 0b allocated 0b resident
Total expressions: 85589
Expressions of unknown type: 6711 (7%)
Expressions of partially unknown type: 3177 (3%)
Type mismatches: 3859
Inference: 16.618588081s, 0b allocated 0b resident
Total: 23.730079953s, 0b allocated 0b resident
```

**Comment by matklad** [comment]
We now take cfg into account, and that could explain the difference

**Comment by marcogroppo** [comment]
@matklad shouldn't it affect the number of expressions, too?

**Comment by marcogroppo** [comment]
Ok... this is getting even weirder... I feared that maybe I was compiling without `--locked`, so I ran `cargo clean`, then `cargo build --release --locked` and repeated the experiment. And now I think I have just witnessed #1552 😮 (screenshot) 
![image](https://user-images.githubusercontent.com/2735511/66514117-d0e6c480-eadc-11e9-890a-8ad9047b4ff7.png)

**Comment by lnicola** [comment]
@marcogroppo let's close this as a duplicate of #1552, keeping in mind that `#[cfg]` can also influence the results?

**Comment by marcogroppo** [comment]
@lnicola ok
