### ISSUE TITLE
VSCode button or command to toggle inlay hints

### ISSUE THREAD

**Issue by DrSensor** [rust-analyzer/rust-analyzer#1977]
I notice that changing inlay hints in the settings will directly enable/disable it which reflect on the editor.
![Peek 2019-10-09 20-46](https://user-images.githubusercontent.com/4953069/66486951-bb21d100-ead5-11e9-99d0-2e1c9363802a.gif)

It would be nice if there is a button in the [statusbar](https://code.visualstudio.com/api/extension-capabilities/extending-workbench#status-bar-item) (or at least a [command](https://code.visualstudio.com/api/extension-guides/command#creating-a-user-facing-command)) to toggle Inlay Hints :wink:

**Comment by tigregalis** [comment]
@DrSensor I figured that this idea of changing settings on demand (e.g. from a keybinding) had to have a more general solution, so I did some searching, and I've come up with this workaround to change it via a keybinding*:

1. Install the extension [Settings Cycler by Cody Hoover](https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler)

2. Add the below to your `keybindings.json`:
```js
  {
    "key": "F4", // key to press to activate command
    "command": "settings.cycle", // `settings.cycle` is the command that's actually being run, from the extension `hoovercj.vscode-settings-cycler`
    "when": "editorTextFocus && editorLangId == 'rust'", // this keybinding is only active when (editor is in focus) and (the language is `rust`)
    "args": { // these are the arguments passed to `settings.cycle`
        "id": "rust-toggle-inlay-hints", // must be unique
        "overrideWorkspaceSettings": true,
        "values": [ // Note: use the same settings in each values object
          {
            "rust-analyzer.displayInlayHints": false // sets the inlay hints off
          },
          {
            "rust-analyzer.displayInlayHints": true // sets the inlay hints on
          }
        ]
    }
  },
```

*It doesn't technically give you a statusbar button or a command, but imo a keybinding is even easier than those two.

**Comment by DrSensor** [comment]
Woah, just tested and it works!
Maybe this kind of thing should be documented on `./docs/user/recipes.md` 🤔

**Comment by IcanDivideBy0** [comment]
Rust analyser setting name changed to:
```
rust-analyzer.inlayHints.enable
```

Otherwise, thanks for the tip, works like a charm!

**Comment by matklad** [comment]
Actually, I think it still will be useful to have a "toggle inlay hints" command in rust-analyzer, if just for discoverability.

**Comment by jknight** [comment]
This is great ! I mapped it to `option+f`
 
The copy and paste version from @tigregalis  + @IcanDivideBy0 is

```json
    {
        "key": "alt+f", // **key to press to activate command**
        "command": "settings.cycle", // `settings.cycle` is the command that's actually being run, from the extension `hoovercj.vscode-settings-cycler`
        "when": "editorTextFocus && editorLangId == 'rust'", // this keybinding is only active when (editor is in focus) and (the language is `rust`)
        "args": { // these are the arguments passed to `settings.cycle`
          "id": "rust-toggle-inlay-hints", // must be unique
          "overrideWorkspaceSettings": true,
          "values": [ // Note: use the same settings in each values object
            {
              "**rust-analyzer.inlayHints.enable**": false // sets the inlay hints off
            },
            {
              "r**ust-analyzer.inlayHints.enable"**: true // sets the inlay hints on
            }
          ]
        }
      },
```

**Comment by JennDahm** [comment]
Just for others' awareness, #4601 introduced an official "toggle inlay hints" command that you can bind to a key combination or run in the quick command menu!

(This issue is pretty old, but it was the top result when I was searching for ways to modify when inlay hints are displayed, so I figured I should leave a comment for anyone else stumbling across it in their searches!)
