### ISSUE TITLE
DIscussion forum for rust-analyzer

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#198]
I'd love to have some forum for free-form discussion about rust-analyzer.

However, I also think that rust has a great potential as a language for implementing language servers, so I'd even love to have something more general: a forum for "implementing compilers/lanauge servers in Rust", of which rust-analyzer will be only a subtopic.

cc @DJMcNab @kjeremy @aochagavia @CAD97 @jD91mZM2 @brendanzab @Marwes what do you think about this all?

And what would be the best tool for this?

* Gitter -- it is supper buggy
* Discord -- nice, and that's what rust-lang uses. Not sure how setting up a server works though. Some folks don't like it because it's not open-source. I am fine with that personally.
* Zulp -- that's what we use for salsa. Nice, has topics, but can't open several instances in one tab, and the electron-based desctop app is, well, and electron app.
* Discourse -- I **love** Discourse, due to it timezone friendly and thoughtful feeling. This would be my personal preference.

**Comment by aochagavia** [comment]
I like Discord, but in the end it is more of a chat application than a discussion forum. I think Discourse is a good alternative, though we would have to self-host it somewhere (or pay $100/mo).

**Comment by jD91mZM2** [comment]
I like the idea of a chat more than a forum for having discussions, so I'm in favor for either discord or gitter. If somebody, like myself, is worried about discord not being open source, they can just use the web version which can't touch your system :)

**Comment by DJMcNab** [comment]
I think that we want more of a chat centered experience over a forum, then create issues resulting from the discussion. However, it would be good if we could archive some of the discussions, so we can link to it in the issues created potentially.

Of the options, I have only used discord and gitter. I agree with  @CAD97 that gitter only just works, and I would not wish using it my worst enemy (maybe that's a bit of an hyperbole)! Discord doesn't allow us to have easily segmented discussions, which is important when we seem to be pretty well spread around the globe. I have taken part in one

All in all, although I haven't used it, my vote goes to Zulip, depending on how ergonomic it is and whether we can create permalinks to a discussion

**Comment by jD91mZM2** [comment]
> and whether we can create permalinks to a discussion

I believe discord recently got hyperlinks to messages. Another option would be mattermost (self hosted)

**Comment by aochagavia** [comment]
If we are going for the chat option, I think Discord + GitHub issues may be a easy way to start. Creating a discord server takes less than a minute and we already have GitHub, so... Should we start with this setup and see how it goes?

Regarding segmented discussions, we could have a main room for general discussion and separate channels for particular topics.

**Comment by matklad** [comment]
Ok, let's go with Discord (named it rust-compilers): https://discord.gg/sx3RQZB.

We can always switch the medium later!

**Comment by ChaiTRex** [comment]
@matklad The old link has expired. Does anyone know an updated link?
