### ISSUE TITLE
Extension Tests task fails

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#1982]
I just fired up the extension in vscode and went to debug "Extension Tests" and it fails with

> Error: Error: Cannot find module 'vscode/lib/testrunner'
> 	at t.ExtHostExtensionService._doHandleExtensionTests (c:\Users\jkolb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:670:756)

**Comment by lnicola** [comment]
Does this still apply?

**Comment by matklad** [comment]
Probably not, as we are re-introducin client tests.
