### ISSUE TITLE
Local var rename incorrectly include "mut" in the rename textbox

### ISSUE THREAD

**Issue by alvinhochun** [rust-analyzer/rust-analyzer#1990]
```rust
let mut variable = 42;
```
In vscode, attempting to rename `variable` will cause the rename textbox to show up with the text "mut variable" in it.

(3b4c506f338d03a633419459bb32daf331153d5e)

**Comment by kjeremy** [comment]
When you perform the rename does it replace the `mut`?

**Comment by kjeremy** [comment]
Ok it doesn't. Weirdly enough it looks like we don't set the placeholder text anymore and I'm assuming the range is off since it covers the `mut` but the actual rename operation doesn't alter the `mut`.

**Comment by kjeremy** [comment]
My guess is that the "prepare rename" request is not doing the right thing but the "rename" request is.

**Comment by kjeremy** [comment]
The range returned from `handle_prepare_rename` includes the `mut` which I think is wrong. Maybe `find_all_refs` needs a flag to ignore the binding?

I remember this working at one point.

**Comment by kiljacken** [comment]
This seems to be working, time to close?

**Comment by alvinhochun** [comment]
Yes, it now seems to be working.

**Comment by kjeremy** [comment]
I cna't reproduce it either
