### ISSUE TITLE
Consider vendoring relevant parts of the relative_path_crates

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#1992]
File systems paths are horrible, because they are thoroughly platform specific. We strive to make rust-analyzer as platform-agnostic as possible, and, for this reason, we avoid `std::path::Path` and use `relative_path::RelativePath` instead. 

The difference between the two is that `Path` is cross-platform, because it uses different internal representation on windows (WTF-8) and unix ([u8]), while `RelativePath` uses the same code and repr on both platforms, but is restricted to common subset of paths (`str`).

The problem with `RelativePath` is that `Path <-> RelativePath` conversion is necessary tricky, and there are some edge cases for which there are no obviously good behavior. As this edge cases are important for the meaning of Rust code, processed by rust-analyzer, and as we are using a small subset of `RelativePath` API, I think it makes sense to just "vendor" (or re-implement) some part of it into rust-analyzer. 

I suggest going with `ra_xpath`, `XPath` and `XPathBuf` names. The most important bit which works with relative paths is `mod_resolution` module.

**Comment by kjeremy** [comment]
One issue is that RelativePath 1.0 was just released and `ra_vfs` leaks `RelativePath` from 0.4
