### ISSUE TITLE
VSCode doesn't show new line on comments like Cargo doc does

### ISSUE THREAD

**Issue by jasonwilliams** [rust-analyzer/rust-analyzer#1997]
When i write comments i would like to create a new line.
I've noticed that adding 3 spaces (similar to markdown) on the end creates a new line in the documentation. 

For example this:
https://github.com/jasonwilliams/boa/blob/master/src/lib/realm.rs#L21-L22

generates this:
![image](https://user-images.githubusercontent.com/936006/66662028-f6d8aa00-ec3f-11e9-8ee7-fbc85af8d0bc.png)

But in VSCode its all on 1 line:
![image](https://user-images.githubusercontent.com/936006/66662061-048e2f80-ec40-11e9-815e-83cc2ba4bed8.png)

Can this plugin change that? 
Or have i posted this issue in the wrong place.

**Comment by kjeremy** [comment]
What does RLS do with that comment?

**Comment by jasonwilliams** [comment]
I think with RLS it worked, but can’t confirm

**Comment by marcogroppo** [comment]
rust-analyzer trims all whitespace at the end of the line inside doc comments. I'll file a PR.

**Comment by marcogroppo** [comment]
Sorry @kjeremy I've just seen now that this is related to #1630. The obvious patch (not trimming if there are 3 spaces at the end of the line) would break `test_doc_comment_multi_line_block_strips_suffix` https://github.com/rust-analyzer/rust-analyzer/blob/4ba2c5b2de0d1815007d109b3897ccaf6dda0ab5/crates/ra_syntax/src/ast.rs#L180
but this is not what we want, I suppose 🤔

**Comment by jasonwilliams** [comment]
@marcogroppo could you elaborate what would break and why?

**Comment by matklad** [comment]
I must say that I am sad that we, as an industry, somehow arrived at the markup format where the trailing whitespace is significant :) 

But yeah, we should strip only *leading* whitespace from the docs, not the *trailing*

**Comment by kjeremy** [comment]
Huh... I had no idea that adding spaces to the end would do that in markdown. A quick skim of rls code leads me to believe that they do not trim the end of the line but I still think we need to remove the `*/` in a multiline comment. PR welcome!

**Comment by jasonwilliams** [comment]
@kjeremy how do you mean you need to remove the `*/` in a multiline comment?

**Comment by kjeremy** [comment]
@jasonwilliams 

Yes you would remove the `*/` in multiline comments and make the changes above where we do not strip trailing whitespace. See #1630 for how I originally implemented the removal of the suffix. That's also (`doc_comment_text`) the function you will need to modify.
