### ISSUE TITLE
Project wide references

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#200]
We do pretty well for local references now but `Analysis::find_all_refs` should return project wide references. 

See #197

**Comment by matklad** [comment]
That's a complex feature to implement. The main prerequisite is the proper name resolution, and not our heuristics based approximation. 

It's also interesting that, to avoid analyzing too much code, find all refs in IDEA works by first finding all textual references (which is a fast map-reduce style job), which gives a superset of occurrences, and then filtering this super set by doing a proper resolve.

**Comment by kjeremy** [comment]
Searching through the text first makes a lot of sense and at least if we implement the classic "n references" 
codelens (or upcoming call tree LSP request?) that would probably be a good approach. I'm also assuming we only need to show references from the current project and not say... a dependent crate if trying to find references for something in std or another crate.

**Comment by flodiebold** [comment]
This is mostly implemented, right?

**Comment by matklad** [comment]
Yeah. There's a ton bugs (like, visibility is broken, we don't look into macros, we don't handle field shorthands), but the overall feature is in place. It also may be quite slow, so it's a good way to benchmark stuff!
