### ISSUE TITLE
Annoying error message in workspaces containing non-rust folders

### ISSUE THREAD

**Issue by Timmmm** [rust-analyzer/rust-analyzer#2001]
If you have a workspace containing some rust and some non-rust folders (for example a Rust backend and non-Rust frontend of some sort), then you get this error every time you open the workspace:

> rust-analyzer failed to load workspace: can't find Cargo.toml at /path/to/nonrust/folder

Gets pretty annoying!

**Comment by ruabmbua** [comment]
I think you also get this error, if you open an arbitrary folder with VScode, which contains at least some rust code, but no top level Cargo.toml

**Comment by matklad** [comment]
Yeah... It's unclear what's the best fix here, as it's pretty important to issue this warning if we legitimately fail to find Cargo.toml... 

Perhaps we should allow to suppress this notification on a per-project basis?

**Comment by p-avital** [comment]
I agree that per-project suppression is the way to go.
Maybe using a setting can help, and having a button in the notification to add the suppression setting in workspace preferences? That way people who want to disable it globally can just enable said setting in their global preferences?

**Comment by Timmmm** [comment]
Could you delay starting rust-analyzer until a `.rs` file is opened within each project?

**Comment by TheZoq2** [comment]
> Could you delay starting rust-analyzer until a .rs file is opened within each project?

This seems reasonable to me. Currently, my vim asks if I want to start `cargo watch` when I open any file in a rust folder, even things like commit message edits

**Comment by luser** [comment]
Ideally `rust-analyzer` wouldn't try to operate at all on a workspace that doesn't contain Rust code.  `rls-vscode` [handles this](https://github.com/rust-lang/rls-vscode/blob/26c6e33ef8222fcab5be0b7d5506b15e9906ae91/src/extension.ts#L60) by using `workspace.onDidOpenTextDocument` to watch for Rust source files, finding the matching workspace, and starting a process to handle that workspace if it's not already open.

As a minor band-aid, perhaps the errors could be stored instead of displayed immediately, and then only  display an error if no workspaces were loaded?
https://github.com/rust-analyzer/rust-analyzer/blob/cecf25b72f2af84fc1535cf52d6f3c1b52802565/crates/rust-analyzer/src/main_loop.rs#L106

**Comment by kynrai** [comment]
Just came across this too. as @luser said, a similar approach `rls-vscode` takes might be the better option here. some workspaces can get very large so so scanning each project seems unnecessary

**Comment by davidolrik** [comment]
I get this error when opening workspaces with no rust code at all.

**Comment by jondo2010** [comment]
Just chiming in here, this is a fairly common use-case. Imagine doing some work that entails porting an existing c library to Rust -- I'll have two folders open in the workspace, only one of which is my Rust  project.

**Comment by lnicola** [comment]
@Timmmm, @jondo2010 this somehow seems to work now, can you please test again?

![image](https://user-images.githubusercontent.com/308347/106033451-7363f600-60da-11eb-91a6-d315b6d378fd.png)

![image](https://user-images.githubusercontent.com/308347/106033467-76f77d00-60da-11eb-9a8c-09cdb07f32bf.png)

![image](https://user-images.githubusercontent.com/308347/106033483-7c54c780-60da-11eb-8160-5d762813bf06.png)

(Marking `S-actionable`, if you look at this in the future and the OP hasn't answered, ping me so we can close it.)

**Comment by Timmmm** [comment]
Yeah I don't seem to get that error anymore either. Guess we can close this.
