### ISSUE TITLE
Macro completions suggest private/unstable std macros

### ISSUE THREAD

**Issue by DianaNites** [rust-analyzer/rust-analyzer#2003]
rust-analyzer has gotten really good at resolving macros, perhaps a bit *too* good, because at least for std macros, unstable macros like `format_args_nl` also show up in completions when typing `format`.

![image](https://user-images.githubusercontent.com/5275194/66697716-3f2ab300-eca6-11e9-80b8-19973b8a91b3.png)
![image](https://user-images.githubusercontent.com/5275194/66697785-d7289c80-eca6-11e9-94b8-21b88906d724.png)

----

Using VSCode 1.39.1
Rust-analyzer commit 0896ca04c4e6f88ae268a39472570df4b6d360b0
Rust 1.38.0

**Comment by jonas-schievink** [comment]
We should continue to suggest unstable macros, since you might still want to import them on nightly, but maybe we can give them a lower score

**Comment by DianaNites** [comment]
Maybe they could be ignored if their issue number is 0 and/or their description says internal use only, too? Since those arent meant to be used at all by anyone else.

**Comment by jonas-schievink** [comment]
Hmm, if `format_args_nl` really is just internal, it should probably have `#[doc(hidden)]` on it, then this issue would be fixed as part of https://github.com/rust-analyzer/rust-analyzer/issues/7718

**Comment by jonas-schievink** [comment]
Opened https://github.com/rust-lang/rust/pull/87410 to see what rust-lang/rust thinks
