### ISSUE TITLE
Compile error underlines don't go away/resize

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#2010]
I'm seeing that error or warnings messages from the compiler don't update after I resolve the issue. For example, the span for an unused import will still show the yellow crinkly underline on the same line as before, but the error message will still be for the warning I just removed.

This is with VS Code 1.39.1 and latest master.

**Comment by lnicola** [comment]
This is working as designed. The `cargo check` errors should go away after saving the file.

**Comment by djc** [comment]
I'm pretty sure saving didn't help here, but I'll just close it for now as I haven't seen this in a while.
