### ISSUE TITLE
Error messages in tooltips seem to be compressed

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#2011]
Compared to RLS, error messages as seen in tooltips from rust-analyzer seem to miss all the newlines (and they seem to be wrapped at a shorter line length?). This makes them harder to read compared to the ones from RLS or on the command line.

**Comment by kjeremy** [comment]
Can you post some screen shots?

**Comment by djc** [comment]
<img width="1137" alt="Screen Shot 2019-10-14 at 21 07 27" src="https://user-images.githubusercontent.com/158471/66776475-b2ab0b00-eec6-11e9-99c7-75c65b4dd813.png">

**Comment by lnicola** [comment]
I don't think we control the error hover panel size.

![image](https://user-images.githubusercontent.com/308347/102757849-959b8300-437a-11eb-9ed0-5cf20e1d36c0.png)

**Comment by Veykril** [comment]
The panel size depends on the user, basically you can resize it by dragging the right/bottom border and VSCode will usually memorize this new size.
