### ISSUE TITLE
Publish VSCode extension to marketplace?

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#2013]
Hi, is there a reason I have to clone the git repo and build everything from there instead of the way it works with RLS where I install the extension from inside VSCode and have the language server installed by the extension automatically?

**Comment by matklad** [comment]
Distributing pre-build binaries of the language server is tricky. RLS does this via rustup, but we are not at the stage where we are ready to be officially packaged.

**Comment by jplatte** [comment]
I'm not talking about pre-built binaries, I'm primarily talking about the VSCode extension. I haven't actually looked into how exactly the language server is installed. Would it not be viable to distribute it as a crate?

**Comment by matklad** [comment]
rust-analyzer contains git deps, so it can’t be published to crates.io. I think it should be possible to install it from git via cargo install, but that would make updating painfull (as everything would need to be rebuild from scratch). But yeah, perhaps it makes sense to distribute only the extension, to save one from needing npm to build...

**Comment by TheAifam5** [comment]
Like the idea with only extension published to VSCode :D I'm on Arch and I use AUR package: https://aur.archlinux.org/packages/rust-analyzer-git/
without VSCode extension, because I have my multi-environment setup (for C, C++, JS/TS, Rust).

**Comment by EliSnow** [comment]
Could the extension be self contained as WASM?

**Comment by matklad** [comment]
nope, we need to read files from disk, and there are editors which don't
use V8.

**Comment by EliSnow** [comment]
WASI, then 😉. With the push to have WASM everywhere it would be cool if the rust-analyzer core was a universal WASM which could run on any platform.

**Comment by bjorn3** [comment]
WASM is a bit slower than native. This is unfortunate for a language server, which needs to react very fast. Not sure if the difference is big enough to be noticable though.

**Comment by kanekv** [comment]
@matklad If I build rust-analyzer binary myself - what should be done to manually install it? Is it enough for it just to be in the path?

**Comment by matklad** [comment]
Being in path is enough, yeah. cargo install usually takes care of that.

**Comment by Lokathor** [comment]
Another vote for "please at least put the vs code extension on the vs code marketplace".

**Comment by Extrawurst** [comment]
This would be soooooo needed - the ergonomics of how to set this up manually in VSCode is really bad :(

**Comment by matklad** [comment]
I wouldn't call one-command installation "really bad". Significant effort were put into making the current installation process as easy as it is right now.

I understand that we can do better, but this takes effort.

I would advise against making +1 comments with (even slightly) negative emotional load, as they take everyone's time.

**Comment by lnicola** [comment]
@matklad we can probably close this now?
