### ISSUE TITLE
Type annotations prevent correct typing

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#2015]
See https://dirkjan.ochtman.nl/files/Screen%20Recording%202019-10-15%20at%2011.42.18.mov. It seems the span for the variable name is one character short.

**Comment by lnicola** [comment]
That's kind of a known issue, see the last bullet in https://github.com/rust-analyzer/rust-analyzer/pull/1586#issue-300760697.

**Comment by djc** [comment]
Ah, thanks. Is there a way to disable the type decorators?

**Comment by lnicola** [comment]
`"rust-analyzer.displayInlayHints": false`

**Comment by matklad** [comment]
Yeah, this is a limitation of the client/protocol at the moment, not something we can fix on our side. The workaround is to disable the hints altogether.
