### ISSUE TITLE
compilation error but travis build is passing

### ISSUE THREAD

**Issue by remifontan** [rust-analyzer/rust-analyzer#2019]
I noticed that sometime, even though travis banner is green (build is passing) I get a compilation error when building... it could be my understanding of how travis works that is poor, never used travis before...

example, on commit: e53c916ce2ab7274b68be80b6791afe5b550500f
it seems that it should build fine based on travis.
https://travis-ci.org/rust-analyzer/rust-analyzer/branches

however when following the instruction on the doc:
cargo install --path ./crates/ra_lsp_server/ --force

I get following error:

```
error[E0004]: non-exhaustive patterns: `Dyn(_)` and `Opaque(_)` not covered
  --> crates/ra_hir/src/ty/traits/chalk.rs:80:15
   |
80 |         match chalk {
   |               ^^^^^ patterns `Dyn(_)` and `Opaque(_)` not covered
   |
   = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms

error: aborting due to previous error

For more information about this error, try `rustc --explain E0004`.
error: failed to compile `ra_lsp_server v0.1.0 (/Users/remifontan/Documents/dev/rust-analyzer/crates/ra_lsp_server)`, intermediate artifacts can be found at `/Users/remifontan/Documents/dev/rust-analyzer/target`

```

However if I call `cargo test`, the tests compile and run successfully. Does that mean there is some code that do not go through compilation during test, but is required by the build?

Should the travis job also do a `cargo install --path ./crates/ra_lsp_server/ --force` as well as `cargo test` ?

**Comment by lnicola** [comment]
What if you undo any local changes and add --locked?

**Comment by remifontan** [comment]
I'm not familiar with `install-ra` and got following error:
```
Error: "Invalid flags: --path, ./crates/ra_lsp_server/, --force"
```

however using `--locked` did solve the compilation error. so I guess I'll continue using this flag from now on.

thanks for your help.

**Comment by lnicola** [comment]
> I'm not familiar with install-ra and got following error:

It's `cargo install-ra`, like [here:](https://github.com/rust-analyzer/rust-analyzer/#language-server-quick-start).

Where did you find the `cargo install --path ./crates/ra_lsp_server/ --force` command? [This page](https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user#vs-code) has `--locked`.

**Comment by remifontan** [comment]
I must have copied the instructions several month ago... or missed to copy the `--locked` flag.

**Comment by lnicola** [comment]
Maybe we can close this issue, then?

**Comment by remifontan** [comment]
yes please and thanks again.
