### ISSUE TITLE
Confusing folding of if-else statements

### ISSUE THREAD

**Issue by ztlpn** [rust-analyzer/rust-analyzer#2033]
After folding the `if` branch the `else` keyword disappears and thus visually inverts the meaning of the `else` branch:

```rust
if foo {
    do_a();
} else {
    do_b();
}
```
get folded into
```rust
if foo {...
    do_b();
}
```

Folding probably should not fold the closing `}` and the line it is on.

**Comment by matklad** [comment]
See https://github.com/microsoft/language-server-protocol/issues/827

Basically, we fold only `{ do a() }`, but VS Code client eats `else` as well.  I guess we can implement workaround by folding only the contents of braces, but the proper solution is to make the clients to do the right thing

**Comment by ztlpn** [comment]
Oh, that would be a nice feature! Folding `fn`s into a single line especially makes sense.

> the proper solution is to make the clients to do the right thing

Well at least vscode is honest about the fact that it can't do any fine-grained folding by sending `"lineFoldingOnly": true` in the client capabilities :)

**Comment by matklad** [comment]
Ahhh, if we actually have this capability, I think we can implement a work-around in a pretty clean way. The relevant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/6b9bd7bdd2712a7e85d6bfc70c231dbe36c2e585/crates/ra_lsp_server/src/conv.rs#L230-L248

We should check if client supports `lineFoldingOnly`, and, if that's the case and folding range encompasses curly braces around line endings, we should patch start-end by one

**Comment by ztlpn** [comment]
I'll give implementing it a try.
