### ISSUE TITLE
Rust Analyzer doesn't work in tests directory

### ISSUE THREAD

**Issue by 95th** [rust-analyzer/rust-analyzer#2034]
I have some tests in `tests` directory inside my project dir. When I launch VS Code, RA initially does the analysis correctly. But when I go edit something in test, RA doesn't re-analyze the updated code. For e.g., if it found some errors in the beginning, then even on fixing those, the error markers won't go away. For workaround, I just close and reopen the folder.

Built from commit ID:  6b9bd7bdd2712a7e85d6bfc70c231dbe36c2e585
Rust version: 1.38

Please let me know if you need more information.

**Comment by matklad** [comment]
Are these errors from cargo watch or from the analyzer itself? The easiest way to check would be to disable cargo watch in settings.

**Comment by 95th** [comment]
I tried disabling "cargo watch" and it's still the same.

**Comment by dgabriele** [comment]
The analyzer doesn't consistently apply to files in `tests` or modules therein, like `tests/common`

**Comment by toadslop** [comment]
This is still an issue.
