### ISSUE TITLE
Lack of signatureHelp after function selection

### ISSUE THREAD

**Issue by oblitum** [rust-analyzer/rust-analyzer#2036]
I'm using [coc-rust-analyzer](https://github.com/fannheyward/coc-rust-analyzer) on NeoVim. It works fine but I miss one key part, when I select a function from completion and it expands it with an empty pair of parentheses and moves the cursor inside, it doesn't activate `signatureHelp` at that moment. I use other language servers and `gopls` and `dart`'s `analysis_server` for example, use the same empty pair of parentheses convention, but they do provide signatureHelp when cursor moves inside the pair. So, I'm thinking there's some difference on the server and not particularly an issue in the client.

**Comment by kjeremy** [comment]
There are a number of issues opened on the LSP repo about interaction between signature help and completion and it should probably be solved at that level. I'll see if I can dig up the relevant issues and post here.

**Comment by oblitum** [comment]
FWIW, `signatureHelp` does work when inserting opening parentheses manually.

**Comment by oblitum** [comment]
I think this is a coc.nvim issue, see https://github.com/neoclide/coc.nvim/issues/1441#issuecomment-570637958.

**Comment by oblitum** [comment]
Actually it seems to be a server issue: see https://github.com/neoclide/coc.nvim/issues/1444#issuecomment-570849774.

**Comment by oblitum** [comment]
This looks like to have fixed by itself :D

**Comment by oblitum** [comment]
More than that, it's now expanding with placeholders, not just empty pair of parens.

**Comment by matklad** [comment]
yup, this line is responsible for this working: https://github.com/rust-analyzer/rust-analyzer/blob/fab40db8bdfdac5cde5789f74d1ec28e60a8bb7e/crates/ra_ide/src/completion/presentation.rs#L218
