### ISSUE TITLE
Error during execution of `cargo metadata`: error: --all-features is not allowed

### ISSUE THREAD

**Issue by Matthias247** [rust-analyzer/rust-analyzer#2040]
I just updated rust-analyzer to the latest git revision 6b9bd7bdd271. Here I get the following error message when opening VsCode: 

> rust-analyzer failed to load workspace: cargo metadata failed: Error during execution of `cargo metadata`: error: --all-features is not allowed in the root of a virtual workspace

This didn't happen with the last revision I build (unfortunately I don't have the commit ID, but it should have been roughly 2 weeks old).

Unfortunately I don't have the code online yet, but it's nothing very special. Just a cargo workspace with 3 subprojects in it. One of them specifies features on some dependencies, the others don't deal with features at all.

**Comment by Matthias247** [comment]
Oh, I also updated rustc to the latest nightly version. Maybe that made a difference by bringing in a different cargo revision?

**Comment by Matthias247** [comment]
Seems like intellij-rust has the same issue: https://github.com/intellij-rust/intellij-rust/issues/4541

**Comment by Matthias247** [comment]
I confirmed this is caused by the rustc update. Going back via 

```
rustup install nightly-2019-10-15
rustup default nightly-2019-10-15
rustup component add rust-src
```

fixes the issue.

Feel free to close if you think this is a temporary rustc bug. Or leave open if there had been a rustc output format change that rust-analyzer needs to adopt to.

**Comment by sinkuu** [comment]
This is a temporary cargo bug. https://github.com/rust-lang/cargo/pull/7525

**Comment by Matthias247** [comment]
Good to know! So seems like there is nothing to do for the team.

You might want to consider still leaving this open for a couple of days until nightly is fixed, so that others stumbling over the same issue see it and don't create duplicates.

**Comment by Matthias247** [comment]
This is no longer an issue with newer nightlies
