### ISSUE TITLE
Deprecation for completion items

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2042]
Right now we support deprecation for symbols but not completion items. We should change that by filling in `CompletionItem.deprecated`.

Note that once LSP 3.15 goes live we will also need to add the deprecated tag to the new `CompletionItem.tags`.

**Comment by matklad** [comment]
The relevant code is here: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_ide_api/src/completion/presentation.rs

**Comment by martskins** [comment]
I have a somewhat in progress implementation of this [here](https://github.com/martskins/rust-analyzer/pull/1).

I was expecting to see some kind of warning or text decoration for deprecated completion items though, but deprecated items seem to have the same style as non-deprecated ones both in VSCode and vim (coc.nvim). Am I missing something or is this expected?

**Comment by kjeremy** [comment]
That's correct for vscode. If believe the next version has it.

**Comment by martskins** [comment]
I suppose this is ready for review then. I've opened #2153. Keep in mind that that PR does not address the setting the `tags` field, because there's no such field in the current version of `CompletionItem` in the current version of `lsp-types`.

**Comment by lnicola** [comment]
I think we do now:

```json
    "items": [
        {
            "label": "new()",
            "kind": 3,
            "detail": "fn new() -> Self",
            "deprecated": true,
            "filterText": "new",
            "insertTextFormat": 2,
            "textEdit": {
                "range": {
                    "start": {
                        "line": 10,
                        "character": 7
                    },
                    "end": {
                        "line": 10,
                        "character": 7
                    }
                },
                "newText": "new()$0"
            },
            "additionalTextEdits": [],
            "tags": [
                1
            ]
        }
```
