### ISSUE TITLE
For loop inside parentheses raises error

### ISSUE THREAD

**Issue by nikonthethird** [rust-analyzer/rust-analyzer#2051]
The function `doesnotwork` below is valid but Rust analyzer shows: `Syntax Error: expected SEMI` at the `f` of `for`. The `loop` example works, though.

```rust
fn doesnotwork() -> Option<()> {
    Some(for _ in [1].into_iter() {})
}

fn works() -> Option<()> {
    Some(loop { break })
}
```

**Comment by kjeremy** [comment]
The following works

```
fn this_works() -> Option<()> {
    let o = for _ in [1].into_iter() {};
    Some(o)
}
```

**Comment by kjeremy** [comment]
Syntax tree for `doesnotwork`:

```
```
FN_DEF@[548; 620)
  FN_KW@[548; 550) "fn"
  WHITESPACE@[550; 551) " "
  NAME@[551; 562)
    IDENT@[551; 562) "doesnotwork"
  PARAM_LIST@[562; 564)
    L_PAREN@[562; 563) "("
    R_PAREN@[563; 564) ")"
  WHITESPACE@[564; 565) " "
  RET_TYPE@[565; 578)
    THIN_ARROW@[565; 567) "->"
    WHITESPACE@[567; 568) " "
    PATH_TYPE@[568; 578)
      PATH@[568; 578)
        PATH_SEGMENT@[568; 578)
          NAME_REF@[568; 574)
            IDENT@[568; 574) "Option"
          TYPE_ARG_LIST@[574; 578)
            L_ANGLE@[574; 575) "<"
            TYPE_ARG@[575; 577)
              TUPLE_TYPE@[575; 577)
                L_PAREN@[575; 576) "("
                R_PAREN@[576; 577) ")"
            R_ANGLE@[577; 578) ">"
  WHITESPACE@[578; 579) " "
  BLOCK_EXPR@[579; 620)
    BLOCK@[579; 620)
      L_CURLY@[579; 580) "{"
      WHITESPACE@[580; 585) "\n    "
      EXPR_STMT@[585; 590)
        CALL_EXPR@[585; 590)
          PATH_EXPR@[585; 589)
            PATH@[585; 589)
              PATH_SEGMENT@[585; 589)
                NAME_REF@[585; 589)
                  IDENT@[585; 589) "Some"
          ARG_LIST@[589; 590)
            L_PAREN@[589; 590) "("
      EXPR_STMT@[590; 617)
        FOR_EXPR@[590; 617)
          FOR_KW@[590; 593) "for"
          WHITESPACE@[593; 594) " "
          PLACEHOLDER_PAT@[594; 595)
            UNDERSCORE@[594; 595) "_"
          WHITESPACE@[595; 596) " "
          IN_KW@[596; 598) "in"
          WHITESPACE@[598; 599) " "
          METHOD_CALL_EXPR@[599; 614)
            ARRAY_EXPR@[599; 602)
              L_BRACK@[599; 600) "["
              LITERAL@[600; 601)
                INT_NUMBER@[600; 601) "1"
              R_BRACK@[601; 602) "]"
            DOT@[602; 603) "."
            NAME_REF@[603; 612)
              IDENT@[603; 612) "into_iter"
            ARG_LIST@[612; 614)
              L_PAREN@[612; 613) "("
              R_PAREN@[613; 614) ")"
          WHITESPACE@[614; 615) " "
          BLOCK_EXPR@[615; 617)
            BLOCK@[615; 617)
              L_CURLY@[615; 616) "{"
              R_CURLY@[616; 617) "}"
      ERROR@[617; 618)
        R_PAREN@[617; 618) ")"
      WHITESPACE@[618; 619) "\n"
      R_CURLY@[619; 620) "}"
```
