### ISSUE TITLE
Assist: flip trait bound

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2054]
![image](https://user-images.githubusercontent.com/1711539/67459638-bc104200-f641-11e9-803c-4cd5f6df8b9b.png)

Here, I'd love to see an assists that suggest to flip `'static` and `RefUnwindSafe`.

A similar assist exist here: https://github.com/rust-analyzer/rust-analyzer/blob/31d84bce3c2ae8bf2a8b3dfaf831bd78f99e0d67/crates/ra_assists/src/assists/flip_binexpr.rs

I think, for `+` in trait bounds, we want a completely separate one, as syntax structure is pretty different in this case.

**Comment by rep-nop** [comment]
I think I'd like to give this a try. Is the end goal to move `'static` bounds to the end of the list if they're not?

**Comment by matklad** [comment]
>Is the end goal to move 'static bounds to the end of the list if they're not?

Not really, that should be handled by the formatter. The end goal here is to make sure that we can flip anything that is connected by a plus. We support this for expressions, so it's surprising that it doesn't work in trait bounds

**Comment by rep-nop** [comment]
Ah, okay, thanks for the quick response! :)

**Comment by vlthr** [comment]
@rep-nop just saw your comment - apologies for not commenting on the issue before I started experimenting on it. I wasn't sure if I had time to finish it this weekend and wanted to be conservative.

Were you thinking along similar lines to my implementation? Would love to collaborate if you have any thoughts.

**Comment by rep-nop** [comment]
Is it desirable to keep the behavior of `flip_binops` where it only applies if the cursor is on `+`? I think that's probably the only major difference between my implementation (which isn't quite complete but is passing some of the tests) and yours.

**Comment by matklad** [comment]
Yeah, I think it's good to make this particular assist narrowly-targeted, such that it works only if the cursor is directly on the `+`.

**Comment by rep-nop** [comment]
I'm tidying up my implementation right now and then I'll push it to my fork and see where we want to go from there.

**Comment by vlthr** [comment]
Sounds good! I'm guessing your implementation is going to be a more natural fit since it's designed to target the `+` from the start.

**Comment by rep-nop** [comment]
So I came up with this originally: https://github.com/rep-nop/rust-analyzer/commit/45dddfddf92e36ed27d05a5a1c264bb3d60bfb5c, however @memoryruins pointed out there might be another way of doing it, so I've been trying to figure out a way to use the node siblings, but I'm figuratively bashing my head off of that.

@matklad do you know if that's possible to use here since we have to deal with both tokens (for the `+`) and nodes (so we can get the `TraitBound`)?

**Comment by matklad** [comment]
Does this thing help?
https://github.com/rust-analyzer/rust-analyzer/blob/85984b09e182adca4b03d9f7efab20d48b5b632a/crates/ra_assists/src/assists/flip_comma.rs#L23

**Comment by rep-nop** [comment]
Haha, yes! Perfect. Let me fix this stuff up and I'll rebase with this new code.
