### ISSUE TITLE
Extend seection should extend to `+` in the trait bound list

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2055]
![image](https://user-images.githubusercontent.com/1711539/67460024-a64f4c80-f642-11e9-959d-7888ff904d76.png)

In this situation, the next extend selection should eat a `+`, and not the whole bounds list. Basically, it should work in the same way it deals with commans in lists like this:

```rust
fn foo(x: i32, y: (), z: String)
```

The code and tests for extend selection are here:

https://github.com/rust-analyzer/rust-analyzer/blob/31d84bce3c2ae8bf2a8b3dfaf831bd78f99e0d67/crates/ra_ide_api/src/extend_selection.rs

To figure out the syntax tree structure, **show syntax tree** command in VS Code might be useful. 

While we are at it, it might be a good idea to change the logic for selecting the delimiter. At the moment, we select *previous* delimiter if we can. I suggest that, by default, we should use *next* delimiter. (though this could be split into a separate issue)

**Comment by aee11** [comment]
I'd like to give this a go! One question: In your example, is the expected expanded selection the following?

1. `DeserializeOwned`
2. `DeserializeOwned + `
3. `DeserializeOwned + panic::UnwindSafe + 'static`
4. `R::Params: DeserializeOwned + panic::UnwindSafe + 'static,`

**Comment by matklad** [comment]
The first to steps definitely. 

The third might or might not be there. 

And there should be  `R::Params: DeserializeOwned + panic::UnwindSafe + 'static` (without comma) before the last one
