### ISSUE TITLE
Does ra-emacs-lsp.el cannot support keyword completion?

### ISSUE THREAD

**Issue by ccqpein** [rust-analyzer/rust-analyzer#2064]
I noticed rust-analyzer has keyword-completion.rs, however I cannot get keyword completion when I use my emacs.

emacs version: 27.0.50
rust-analyzer version: newest at 10/24/2019
rust toolchain version: nightly, newest at 10/24/2019

**Comment by matklad** [comment]
The most likely issue is that we support only a couple of cases of keyword completion. Basically, I've implemented only the most annoying bits, and moved towards other things. Specifically, these cases should work:

completing `pub(crate)` on the top-level:

![image](https://user-images.githubusercontent.com/1711539/67549073-11b12100-f70c-11e9-9594-2c9febefe7a8.png)

completing `else` and `else if` after `if`:

![image](https://user-images.githubusercontent.com/1711539/67549126-32797680-f70c-11e9-850d-222827189d73.png)

To further improve the situation, we should either add more special cases like we ones we already have, or we should do what Kotlin does: for each keyword, just try to insert it in the file and see if it parses sucesfully.

**Comment by ccqpein** [comment]
I post this issue because I notice my `struct` and `enum` keywords cannot auto completed. My personally think have those keywords auto completed might be helpful.

**Comment by matklad** [comment]
we've added keyword completion recently
