### ISSUE TITLE
text decorator targets type definitions. 

### ISSUE THREAD

**Issue by seivan** [rust-analyzer/rust-analyzer#2092]
`"ralsp.text": "#000"`

Will make most type definitions black. 
<img width="381" alt="image" src="https://user-images.githubusercontent.com/55424/67635951-01e03b00-f8cc-11e9-871d-164e70e30334.png">

**Comment by lnicola** [comment]
@seivan do you think this is still a problem?

**Comment by seivan** [comment]
@lnicola No it has been fixed. Sorry for the delay!
