### ISSUE TITLE
Can't resolve enum in local function scope

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2098]
```rust
fn foo() {
    enum Blah {
        /// Variant with stuff
        A(i32)
    }

    let _e = Blah::A(0);
}
```

Here `_e` is {unknown} and there are no completions for `Blah`. However if `Blah` is moved out of the function it resolves properly and we get completions and the type is infered.

**Comment by sinkuu** [comment]
Duplication of https://github.com/rust-analyzer/rust-analyzer/issues/1559?

**Comment by kjeremy** [comment]
Yep!
