### ISSUE TITLE
Cannot delete folder / crate on Windows. 

### ISSUE THREAD

**Issue by danylaporte** [rust-analyzer/rust-analyzer#2107]
I cannot delete a sub/child crate (folders) because it is in use by rust-analyzer on windows. 
Also, the issue occurs when using git and changing between different branches. There are folder in locked by rust-analyzer causing issues.

**Comment by matklad** [comment]
Does using `rust-analyzer.useClientWatching: true` in the [settings](https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/README.md#settings) help? I think we only reason we might hold onto the folders is for watching them.

**Comment by danylaporte** [comment]
@matklad I have just tested this `"useClientWatching": true` setting and it works now. Thank you very much!
