### ISSUE TITLE
Macro arguments for signature help

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2118]
Now that #2116 is merged how do I go about figuring out argument for macros?

**Comment by JasperDeSutter** [comment]
Each rule of a macro could probably be represented as a separate signature (like how function overloads work in TypeScript for example)

For `vec!`, this would give us these three:
```rs
vec![$elem:expr; $n:expr]
vec![$($x:expr),*]
vec![$($x:expr,)*]
```
They are a combination of name + ! + rule pattern (with parentheses replaced by preferred bracket kind)

The harder part would probably be to match the correct rule with the combination of tokens that are typed in, and possibly show the resulting type after expansion?

Related: the macro signature help currently only shows when using parentheses, not when using braces or brackets as with `vec!`.

**Comment by kjeremy** [comment]
I like the idea of showing them as overloads.

We only show signature help for call syntax `(...)` we could open it up to braces which would give us a poor man's help for record syntax (with a little more work). That's actually why I implemented the restriction in `FunctionSignature::from_struct` and `FunctionSignature::from_enum_variant`... it was completing `struct S { a: i32 }` if you typed ` let s = S (<|>)`.

**Comment by kjeremy** [comment]
To support this we would have to expand `CallInfo` to return multiple `FunctionSignature` or return multiple `CallInfo` to the LSP layer.

**Comment by matklad** [comment]
Yeah, I think the hard problem here is that a macro signature is not a really well-define thing, as macros specify pattern, against which the input tt is matched, rather than the set of arguments. With the amount of "helper" productions, I also fear that this might create more noise than value, but it might be worth it still to just try it out.

**Comment by kjeremy** [comment]
macro support was recently removed from signature help.
