### ISSUE TITLE
Reject invalid renames

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2121]
Rename operations already fail if you try to rename keywords but we should reject invalid identifiers. For instance I can currently rename `_p` to `*$%*#)#%(*@`. This should be rejected from both https://github.com/rust-analyzer/rust-analyzer/blob/542bc18223fdef60c942d0d6ca0dd9be9de2cd91/crates/ra_lsp_server/src/main_loop/handlers.rs#L445 and https://github.com/rust-analyzer/rust-analyzer/blob/542bc18223fdef60c942d0d6ca0dd9be9de2cd91/crates/ra_lsp_server/src/main_loop/handlers.rs#L466

Both of those call into https://github.com/rust-analyzer/rust-analyzer/blob/542bc18223fdef60c942d0d6ca0dd9be9de2cd91/crates/ra_ide_api/src/references/rename.rs#L16

**Comment by SomeoneToIgnore** [comment]
Should this one be closed?
