### ISSUE TITLE
Autocomplete breaks down structs created with Default trait. 

### ISSUE THREAD

**Issue by seivan** [rust-analyzer/rust-analyzer#2135]
Might be related to https://github.com/rust-analyzer/rust-analyzer/issues/1427

**Comment by flodiebold** [comment]
It would be helpful to provide a code example to explain what you mean exactly here, otherwise we have to guess.

Assuming you mean cases like
```rust
let x = Vec::default();
x.
```
that's because we don't resolve trait methods called through the self type in this way yet. I'm working on it currently though :slightly_smiling_face:

**Comment by seivan** [comment]
Sorry thought it wasn’t ambiguous. Yeah, this also explains why my highlighting broke for the default method. I’ll close this since it’s already a ticket on this. Thanks!
