### ISSUE TITLE
Hover and goto definition for macros in use tree does not work

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2143]
The following fails both hover and goto def.
```rust
use ra_syntax::{
    match_ast<|>
};
```

I think it's because `analyzer.resolve_path` fails to return a path resolution but I'm not too familiar with the resolver code.

**Comment by kjeremy** [comment]
Note that `mach_ast` is a macro.

**Comment by matklad** [comment]
Hm, yeah, `resolve_hir_path` should also call `resolve_path_as_macro`.
