### ISSUE TITLE
Inner comments are attached to the wrong things

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2148]
Currently the following are equivalent:

1.
```rust
//! A comment
mod foo {}
```

and

2. 
```rust
/// A comment
mod foo {}
```

I believe the first example is incorrect and the comment should apply to the parent scope.

The following should be equivalent to 2 above but the comment here is attached to the item list and not the module:

```rust
mod foo {
  //! A comment
}
```

**Comment by kjeremy** [comment]
This is why hover does not display comments on `mod`s if using `//!` syntax.

**Comment by kjeremy** [comment]
I think the solution might involve `n_attached_trivias` also occuring after (during?) `start_node` ? Or maybe doing the `rustc` thing where doc comments are sugared to `#[doc()]`?

**Comment by matklad** [comment]
Oh, n_attached_trivias should absolutelly be fixed to not attach `//!` comments.

**Comment by kjeremy** [comment]
I don't think that helps with inner doc comments though?

**Comment by matklad** [comment]
There are two layers here:

* on the syntactic layer, we should not attach inner doc comments to the following item
* on the semantic layer, we should make a union of inner and outer doc comments

**Comment by kjeremy** [comment]
@matklad I can pull inner doc comments out by skipping over them in `n_attached_trivias` and that associates them with the previous element.

But how do I attach inner doc comments? For instance:

```
//! not-attached-to-foo
// non-docs
mod foo {
    //! attached-to-foo
}
```

becomes

```
COMMENT@[62; 85) "//! not-attached-to-foo"
  WHITESPACE@[85; 86) "\n"
  MODULE@[86; 133)
    COMMENT@[86; 97) "// non-docs"
    WHITESPACE@[97; 98) "\n"
    MOD_KW@[98; 101) "mod"
    WHITESPACE@[101; 102) " "
    NAME@[102; 105)
      IDENT@[102; 105) "foo"
    WHITESPACE@[105; 106) " "
    ITEM_LIST@[106; 133)
      L_CURLY@[106; 107) "{"
      WHITESPACE@[107; 112) "\n    "
      COMMENT@[112; 131) "//! attached-to-foo"
      WHITESPACE@[131; 132) "\n"
      R_CURLY@[132; 133) "}"
```

How do I pull `//! attached-to-foo` out of item list? Does that need to happen in the parser in either `block_expr` or `naked_block`?

**Comment by matklad** [comment]
@kjeremy attaching inner comments to the right element is explicitly out of scope for the parser. Syntactically, `//! attached-to-fo` is nested into `ItemList`, but, semantically, it should be attached to the `MODULE`. The only thing the parser can do here is to avoid attaching inner comments to the wrong element. 

Attaching inner comments should happen in the hir. I think we should handle them by deshugaring then into attributes. See the zulip thread

**Comment by kjeremy** [comment]
Relevant [zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/Avoid.20parsing.20items.20to.20determine.20if.20they.20are.20deprecated)

**Comment by kjeremy** [comment]
@matklad re the zulip thread.

Now that #2179 has been merged how do I sugar (outer) doc comments into attributes? According to https://doc.rust-lang.org/rustdoc/the-doc-attribute.html each `/// a comment` comment becomes a `#[doc = " a comment"]` with leading whitespace preserved though it looks multiple doc comments can be collapsed into one attribute. That makes sense.

You said that I should remove the `hir` documentation so do I create (sugar) new attrs from doc comments in the `attrs_from_ast` itself and then the existing `documentation` filters on the result of the `attrs`? Is that the design you had in mind for outer doc comments?

**Comment by matklad** [comment]
Yes, this sounds about right!

**Comment by kjeremy** [comment]
@matklad I have some code that instantiates once or more `Attr`s via a new method on `Attr`: `fn from_doc_comments_owner(owner: &dyn DocCommentsOwner) -> Option<Arc<[Attr]>>` but I don't think that `attrs_from_ast` is the right place to call it. Does it make more sense to do generate the attributes in in `code_model::docs::documentation_query` and then union that with existing doc attrs? I'm struggling a bit on when to do what and how much of the hir documentation infrastructure you think should be removed.

**Comment by matklad** [comment]
I think `attrs_from_ast` is eaxactly the right place to construct attributes from both doc coments and attributes syntax (in both outer an inner flavor).

The `code_model::docs::documentation_query` should be then removed completely. Instead, there should be a a helper function like

```
fn documentation(attrs: &[Attr]) -> Strig
```

and hir should call into that.

It probably make sense to introduce an wraper type for `Vec<Attrs>`: 

```rust
struct Attrs {
    enttries: Option<Arc<[Attr]>>
}
```

then, all attr-related logic can nicely hang of as methods of this type. So, the IDE would do something like this:

```rust
let def: hir::StructDef = todo!();
let docs = def.attrs(&db).docs();
```

Now that I think about this, introducing an `Attrs` wrapper type is a nice piece of work that can be done as a separate PR.

**Comment by kjeremy** [comment]
@matklad I want to take another stab at this but I feel like I have to create a bunch of duplicate paths. For instance currently everything requires ast::AttrsOwner so I almost need to duplicate all of these functions for ast::AttrsOwner + ast::DocCommentsOwner but this seems like the wrong approach.

**Comment by matklad** [comment]
I do think that we'll need special code for each thing that can have inner doc comments.
