### ISSUE TITLE
rustfmt.toml newline_style problem in Windows 

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#2157]
I just find that the current `rustfmt.toml` `newline_style` is set to `unix`. 

Are there any reasons we have to force it to `unix`? Could we just use `native` here ? Since people using Windows machine will normally config `core.autocrlf=true` in `git`.

**Comment by matklad** [comment]
The problem is that sometimes `\r\n` line endings end up in the repository. Maybe we should check this on CI only? I am not even sure if it works as intended: I *think* I've seen \r\n even after we added this config, which probably means that travis always checks out `\n`?

**Comment by edwin0cheng** [comment]
> I am not even sure if it works as intended: I think I've seen \r\n even after we added this config, which probably means that travis always checks out \n?

Oh... seem you are right :
https://github.community/t5/GitHub-Actions/git-config-core-autocrlf-should-default-to-false/m-p/30729/highlight/true#M532
