### ISSUE TITLE
Avoid parsing items to determine if they are deprecated

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2167]
https://github.com/rust-analyzer/rust-analyzer/pull/2160 added `is_deprecated` field to `CompletionItem`. At the moment, the field is computed by looking at the  syntax tree of the relevant item. This is less then ideal, because it causes us to parse a lot of files to compute comletions. Ideally, `is_deprecated` should be stored in the hir database.

We previously did the same ast -> hir transition for documentation: https://github.com/rust-analyzer/rust-analyzer/pull/1385/commits/2c28f5245dd8ede715d99b55fdad0ceb3de9dbe7

So, what we need here is to add an 

```rust
    fn attrs(&self, def: crate::AttrsDef) -> Option<Arc<[Attr]>>;
```

query, where `AttrsDef` is an enum of all possible defs which can be attributed, and `Attr` is an existing hir-level representation of the attributes (see attr.rs module). 

Then, we should use this query to calculate the `is_deprecated` property of an item during completion.

Tentatively marking it as good-first-issue. It is a rather isolated chunk of work, and the docs PR should give a nice model, but there's still some design to be figured out during implementation.

**Comment by kjeremy** [comment]
I haven't looked at that PR but for deprecated we also need to look up the parent item since you can mark a mod as deprecated and have it apply to child items.
