### ISSUE TITLE
Bogus Type Inference

### ISSUE THREAD

**Issue by sanboxrunner** [rust-analyzer/rust-analyzer#2170]
Hello!

I'm having a strange issue where a complex return type gets parsed *very* incorrectly. 

Here's the method:

```
pub struct GenerationalIndexArray<T>(Vec<Option<ArrayEntry<T>>>);

impl<T> GenerationalIndexArray<T> {
    pub fn iter_mut(&mut self) -> impl Iterator<Item = &mut T> {
        self.0
            .iter_mut()
            .enumerate()
            .flat_map(|opt_ent| Some(&mut opt_ent.1.as_mut()?.value))
    }
}
```

A usage example:

```
let tilemaps: &mut GenerationalIndexArray<Tilemap> = unimplemented!();

for this_tilemap in tilemaps.iter_mut() {
    // issue is here
}
```
In that example, `this_tilemap`'s type is getting parsed as a `Result<JsValue, JsValue>`, which I just have no idea where it's getting that from. Probably `serde-json`, but it's not even in scope in this file, and it doesn't have a crate wide #[macro_use] extern crate serde-json in main, so I've got no idea where it's coming from.

`this_tilemap` *should* be `&mut Tilemap`, which is what Rust gives it in actual usage.

This isn't a huge problem, but I got these bogus autocompletes which are rather confusing. I'd much rather just an unknown for something complex like this.

Thanks guys!

**Comment by flodiebold** [comment]
Hm. Since we can't project associated types from an `impl Trait` yet, I would expect `this_tilemap` to get inferred as `{unknown}` at first. We might later unify that with another type and get something else. I assume there's some code inside the for loop, or does this even occur if the loop is empty?

**Comment by sanboxrunner** [comment]
Happens even if the look is empty!

**Comment by flodiebold** [comment]
Ok then, I can't reproduce this with just the code you posted though. Can you provide the whole code, or try to make a minimal reproduction?

**Comment by sanboxrunner** [comment]
hmm...I tried making a small reproduction of it, but was not successful. It
correctly listed "unknown".

I can give you access to the private repo if you want to look at it? I
understand that you're busy and that's not terrible enjoyable, but I would
thoroughly appreciate it.

**Comment by sanboxrunner** [comment]
To go more into depth here:

It's assigning a type of "Result<JsValue, JsValue>" to each of these loops.
A bizarre type on its own, but the "JsValue" does not come from serde_json
actually -- it appears to come from wasm_bindgen, which somehow this
project has in it (presumably from gfx_hal). When I tried to make a repro
containing my entire cargo.toml I couldn't get the same bug to appear, so I
don't know how helpful this is, but just wanted to give you all the info I
had.

**Comment by bjorn3** [comment]
Maybe you can reduce the full project, instead of creating a new project and adding stuff. You could for example remove as much modules, functions and types as possible. You could then reduce the remaining functions until you have something you can share. The reproducer doesnt have to be minimal.

**Comment by flodiebold** [comment]
Yeah, that's what I'd try: Remove everything that doesn't seem related to it, check that it's still occurring, rinse, repeat. Note that the reproducer also doesn't need to be valid for rustc; e.g. you can probably remove all the method bodies except the one where the `for` loop happens.

I'd be happy to take a look at the private repo if you give me access as well though (but 'try removing stuff and see whether it still happens' would probably be the first thing I'd do anyway).

**Comment by sanboxrunner** [comment]
Smart idea! Also if you've never had the joy of carefully removing 10,000 lines from a project to isolate it down to just a core component, I couldn't recommend it more. Like exfoliation for the file system.

https://github.com/sanboxrunner/ra_type_inference_error

Succesfully reproduces the type inference error right in main.

You'll notice the `gfx_hal` crate (0.3.0 as I'm not in a position to spend the time updating) is in the Cargo.toml. It, and its subcrate, wasm_bindgen, are definitely somehow involved in the problem -- removing them (though they currently have *no* involvement in the project whatsoever) and the type inference will now say `{unknown}`, which is preferable for now.

Thanks for walking me through it guys!

**Comment by flodiebold** [comment]
Interesting, thanks!

Actually, with the dependencies, even
```rust
struct GenerationalIndexArray<T>;
impl<T> GenerationalIndexArray<T> {
    pub fn iter(&self) -> impl Iterator<Item = &T> { }
}

fn main() {
    let list: GenerationalIndexArray<f32> = unimplemented!();
    for this_member in list.iter() {

    }
}
```
is enough to reproduce the problem...

**Comment by sanboxrunner** [comment]
Yup, just reduced it down further to essentially that myself. Thank you for
the help!

**Comment by flodiebold** [comment]
Furthermore, the only needed dependency seems to be
```toml
spirv_cross = "0.15.0"
```

**Comment by flodiebold** [comment]
Ok, I've got it...
Here's a stand-alone (except for std) reproduction:
```rust
struct Right;
struct Wrong;

fn create_iter() -> impl Iterator<Item = Right> { }

trait SomeTrait {}

impl IntoIterator for dyn SomeTrait {
    type Item = Wrong;
}

fn main() {
    for x in create_iter() {

    }
}
```
`js_sys` provides an implementation of `IntoIterator` for `dyn js_sys::Iterator`. We currently pass an `Error` type to Chalk in place of any `dyn` or `impl` type, so Chalk simply thinks that impl applies for `impl Iterator`. So this particular case will get fixed once we can use Chalk's dyn/impl Trait support, though we should also consider making `Error` more special in Chalk so it doesn't unify with itself, or somehow avoiding passing these erroneous impls to Chalk at all :thinking:

**Comment by flodiebold** [comment]
@sanboxrunner I would guess that the bogus inference is gone now (though it will still likely not be able to infer the correct type).

**Comment by sanboxrunner** [comment]
@flodiebold yup, I'm going to close the issue. The actual solution isn't essential but just having this small fix is good enough
