### ISSUE TITLE
`macro_rules` in Impl Block do not resolved correctly

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#2181]
The `_hello` in the following code do not work:

``` rust
fn main() {
    macro_rules! inner {
        () => {"hello"}
    }

    let _hello = inner!();  // _hello not resolved
}
```

I think we didn't handle `macro_rules` in impl block yet ? 
Related code: 
https://github.com/rust-analyzer/rust-analyzer/blob/38f2bd21fbecf1c997a4ab9a8913e8b5487088e3/crates/ra_hir/src/impl_block.rs#L251-L280

**Comment by edwin0cheng** [comment]
Oh, seem like we didn't handle simple struct def in impl_block too :

```

fn main() {
    struct A {}

    let _a = A{};  // a => {unknown}
}
```

**Comment by kjeremy** [comment]
We don't resolve function local defs yet. If you pull the definitions out of main it should with better.
