### ISSUE TITLE
Option to not show box, dbg, if, etc. completion options

### ISSUE THREAD

**Issue by Timmmm** [rust-analyzer/rust-analyzer#2186]
![image](https://user-images.githubusercontent.com/376842/68228646-b45f7e80-ffed-11e9-9168-27f6cba2eeca.png)

These options are a nice idea, but not particularly useful yet (e.g. `.match` doesn't add all the variants) and when rust-analyzer works they are quite noisy:

![image](https://user-images.githubusercontent.com/376842/68228847-0ef8da80-ffee-11e9-809e-605a4eaf92b4.png)

I think they should be disabled for now. They should be re-enabled when they are more useful, and when the entries are sorted so they are always at the end.

**Comment by matklad** [comment]
We definitely should have a configuration option to disable this. Here's how such option should be added:

* add a [feature-flag](https://github.com/rust-analyzer/rust-analyzer/blob/d222608a45d53ca7a1bbc9f0126a092fda48503c/crates/ra_ide_api/src/feature_flags.rs#L57)
* [document](https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/README.md#settings) feature flag (we really should be generating these docs from source)
* disable [postfix completion](https://github.com/rust-analyzer/rust-analyzer/blob/d222608a45d53ca7a1bbc9f0126a092fda48503c/crates/ra_ide_api/src/completion/complete_postfix.rs#L42) if the feature flag is set (`ctx.db.feature_flags`)

I would prefer to keep this feature on by default though!

Ideally, we should also have an option to check for strict match when offering this completions, but binary flag should be enough for the start!

**Comment by lnicola** [comment]
Speaking of which, what's the reasoning behind the feature flags? ISTM there is some duplication between them and the LSP configuration.

**Comment by matklad** [comment]
Feature flags are visible inside rust-analyzer, LSP configuration is not. In other words, LSP config tweaks the LSP-related parts, while feature-flags tweak rust-related parts.

**Comment by lnicola** [comment]
I think it would be more accessible to translate the LSP configuration into the `rust-analyzer` feature flags. For example, in Code I get auto-completion for the LSP settings, but `rust-analyzer.featureFlags` is a JSON blob, so I need need to look over the documentation or code instead.

**Comment by matklad** [comment]
Hm, that's true. That's one more argument for automating this: we should be able to generate the relevant package.json declarations out of `feature_flag.rs`.

**Comment by davidalexanderr** [comment]
I'm new to Rust and new to this repo, but this seems like a good first issue :-) I'd like to take this on

**Comment by davidalexanderr** [comment]
It looks like this has been addressed in https://github.com/rust-analyzer/rust-analyzer/commit/b5349af05fca31af14f8997ed3f18027b1953517 -- can you confirm or deny this @matklad?

**Comment by matklad** [comment]
Nope, that was just s a code cleanupnwihout any changes to functionality

**Comment by davidalexanderr** [comment]
Is the ask to disable all post-fix completion options or just disable the "box, dgb, if, etc." completion options?

**Comment by matklad** [comment]
I think it makes sense to disable all postfix snippets
