### ISSUE TITLE
Expose feature flags to LSP client

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#2189]
The reason behind the `rust-analyzer` feature flags is to separate the LSP configuration (which may be specific to a client) from the `rust-analyzer` settings. This is reasonable, but the user experience could be improved, since the client has no knowledge about the available flags.

We should probably expose LSP settings for the feature flags, and do the translation inside the extension. The `package.json` entries could be generated automatically from the list in `crates/ra_ide_api/src/feature_flags.rs`.

**Comment by matklad** [comment]
Some things to look at:

* here's how we do a similar thing for assists: https://github.com/rust-analyzer/rust-analyzer/blob/d222608a45d53ca7a1bbc9f0126a092fda48503c/xtask/src/codegen/gen_assists_docs.rs

* I think I've seen some sort of `include`-like thing for `package.json`. We should investigate this, to make sure we cleanly separate hand-written part of `package.json` from a generated one.

**Comment by martskins** [comment]
Now that the feature flags are to be exposed to the LSP client, does this still hold?
> Note that we purposefully use run-time checked strings, and not something checked at compile time, to keep things simple and flexible.

I'm also wondering about whether the `FeatureFlags` type still makes sense in this scenario or if we should just add the flags as fields of some other type (`ServerConfig` maybe?)

**Comment by kjeremy** [comment]
@martskins without looking too closely that makes sense to me. We really need to implement the LSP configuration requests.
