### ISSUE TITLE
join-lines should remove block wrapper

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2190]
Before (cursor is `<|>`)

```rust
fn is_bool_or_unknown(ty: Option<Ty>) -> bool {
    match ty {
        Some(ty) => { <|>
            match ty {
                Ty::Apply(at) => match at.ctor {
                    TypeCtor::Bool => true,
                    _ => false,
                },
                Ty::Unknown => true,
                _ => false,
            }
        }
        _ => true,
    }
}
```

Desired "After" after invoking "join lines" command. Note how wrapping `{}` is removed.

```rust
fn is_bool_or_unknown(ty: Option<Ty>) -> bool {
    match ty {
        Some(ty) => match ty {
                Ty::Apply(at) => match at.ctor {
                    TypeCtor::Bool => true,
                    _ => false,
                },
                Ty::Unknown => true,
                _ => false,
            }
        _ => true,
    }
}
```

Code and tests for this feature are here: https://github.com/rust-analyzer/rust-analyzer/blob/d222608a45d53ca7a1bbc9f0126a092fda48503c/crates/ra_ide_api/src/join_lines.rs

**Comment by fkohlgrueber** [comment]
Hi, I'd like to tackle this issue!

This is what I found out after looking at the source:

Rust analyzer already removes blocks around "trivial expressions" when joining lines, but only if these don't contain newlines (see [here](https://github.com/rust-analyzer/rust-analyzer/blob/b7a36b54431ca5b746af53549a1b6e142570c7f4/crates/ra_fmt/src/lib.rs#L41-L43)). The linked function `extract_trivial_expression` is used for joining lines and replacing if-let with matches (see [here](https://github.com/rust-analyzer/rust-analyzer/blob/b7a36b54431ca5b746af53549a1b6e142570c7f4/crates/ra_assists/src/assists/replace_if_let_with_match.rs#L68)).

To get the desired behavior for the example above, one could simply remove the condition that forbids newlines in the input. The open question for me is whether this change should also be applied to "replace if-let with match". For example:

Initial code:

```
if let Some(a) = x {
    println!(
        "Some: {}", 
        a
    )
} else {
    println!("None")
}
```

After using "replace with match" (current rust-analyzer):

```
match x {
    Some(a) => {
        println!(
            "Some: {}", 
            a
        )
    }
    _ => println!("None"),
}
```

Removing the condition that forbids removing the parent block if the expression contains newlines:

```
match x {
    Some(a) => println!(
            "Some: {}", 
            a
        )
    _ => println!("None"),
}
```

I'd argue that the last example might be confusing and that the behavior of "replace with match" shouldn't be changed, but I wanted to get feedback regarding this before opening a PR.

BTW, the tests for "replace with match" do not cover the example above. I'd therefore add a test as part of the PR if that's OK.

Looking forward to your feedback.

**Comment by matklad** [comment]
Good analysis! I think we should *refine* the condition to allow multiline expressions if they are also block-like. That is, for things like `match`, `loop`, `if`, we shouldn't add extra braces. Here's the full list:

https://github.com/rust-analyzer/rust-analyzer/blob/b7a36b54431ca5b746af53549a1b6e142570c7f4/crates/ra_parser/src/grammar/expressions/atom.rs#L136

These are the expressions that don't need `;` to be statements, and which don't require `,` in match arms

**Comment by matklad** [comment]
That is, I think there's no single right answer here, but I think block-like captures user expectations well

**Comment by fkohlgrueber** [comment]
Hmm, I'm currently thinking about the behavior of "replace with match" with long match arms, e.g. refactoring 

```rust
if let MyTypeWithLongName::MyTypeVarian(a) = x {
    if this_condition_variable == foo(x) {
        println!("Yey");
    }
} else {
    println!("None")
}
```

to 

```rust
match x {
    MyTypeWithLongName::MyTypeVarian(a) => if this_condition_variable == foo(x) {
            println!("Yey");
        }
    _ => println!("None")
}
```

might reduce readability (and thereby the utility of the refactoring). I'd argue that removing enclosing blocks in "replace with match" should be very conservative. If the block isn't wanted, it can easily be removed using "join lines".

Wait, I think I'm confusing whether or not there should be an enclosing block and whether or not there should be a newline between the match arm's pattern and the rhs expression. If lines get too long by this refactoring, one can simple insert a newline without introducing another block.

We should probably just change both assists ("join lines" and "replace with match") to remove blocks containing a single *block-like* expression. That's what you were suggesting, right?

**Comment by matklad** [comment]
>That's what you were suggesting, right

Right! Although what you are saying about not messing with blocks too much in "replace if with match" also makes sense. 

A plausible alternative is to retain current heuristic for the assist, but *always* (and not just for block-like expressions) remove a block in join-lines. As join-lines is a more direct action, we can be more aggressive in assume what the user meant. But this would be harder to implement, as it requires two different heuristics, so I'd probably started with a unified *block-like* heuristic.

**Comment by fkohlgrueber** [comment]
I agree that using different heuristics is probably the best way to go, and I think that implementing it shouldn't be that difficult. I'll prepare a PR and ping you if it's ready.
