### ISSUE TITLE
Hover on TupleFieldDef builtin should show the name of the type

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2192]
Hover on:

```rust
struct TS(String, i32<|>);
```

produces:

```rust
pub fn i32() -> IntTy
```

when it should show `i32`. Note that if hovering on `String` it correctly shows the documentation for `String`.

**Comment by kjeremy** [comment]
```
SOURCE_FILE@[0; 23)
  STRUCT_DEF@[0; 23)
    STRUCT_KW@[0; 6) "struct"
    WHITESPACE@[6; 7) " "
    NAME@[7; 9)
      IDENT@[7; 9) "TS"
    TUPLE_FIELD_DEF_LIST@[9; 22)
      L_PAREN@[9; 10) "("
      TUPLE_FIELD_DEF@[10; 16)
        PATH_TYPE@[10; 16)
          PATH@[10; 16)
            PATH_SEGMENT@[10; 16)
              NAME_REF@[10; 16)
                IDENT@[10; 16) "String"
      COMMA@[16; 17) ","
      WHITESPACE@[17; 18) " "
      TUPLE_FIELD_DEF@[18; 21)
        PATH_TYPE@[18; 21)
          PATH@[18; 21)
            PATH_SEGMENT@[18; 21)
              NAME_REF@[18; 21)
                IDENT@[18; 21) "i32"
      R_PAREN@[21; 22) ")"
    SEMI@[22; 23) ";"
```

**Comment by marcogroppo** [comment]
Builtin primitives do not have a definition in `libstd`/`libcore` and usually hovering the mouse over them doesn't return anything (actually there are specific `doc` attributes but I don't think that we're collecting them: https://github.com/rust-lang/rust/blob/6c1b447f2e67f5eae89394344ade698aca3ec7e6/src/libstd/primitive_docs.rs#L804). So this `i32()` function seems pretty weird, maybe it comes from some crate that you've included in the dependencies?
