### ISSUE TITLE
Don't require semicolon after macro definition

### ISSUE THREAD

**Issue by aochagavia** [rust-analyzer/rust-analyzer#220]
The following code generates a syntax error "expected SEMI" at the position of the cursor

```rust
fn test() {
    macro_rules! indent {
        () => {
            for _ in 0..level {
                buf.push_str("  ");
            }
        };
    }<|>
    return;
}
```

**Comment by phansch** [comment]
This looks like a nice starter issue. I would like to see if I can fix it today.

**Comment by aochagavia** [comment]
Feel free to ask for help here if you get stuck

**Comment by phansch** [comment]
I think I jumped the gun a bit early here. Holiday is coming up next week and I want to finish up a compilers course ([this one](https://lagunita.stanford.edu/courses/Engineering/Compilers/Fall2014/info)) so that I start with proper understanding of the basics. I do want to get involved, it may just take a few more weeks =)

If someone else wants to pick this up, feel free!

**Comment by aochagavia** [comment]
It turns out this is not only a problem for macro definitions, but also macro usage. I have created #225 which is more general.

**Comment by DJMcNab** [comment]
But surely macro definition and usages are different constructs entirely. I would argue that this is should be simpler to fix than #225. It might only require a change to <https://github.com/rust-analyzer/rust-analyzer/blob/477de790b0211196256a772befe4f577d1a8ba14/crates/ra_syntax/src/grammar/expressions/mod.rs#L204-L209>

**Comment by aochagavia** [comment]
`macro_rules!` is itself a macro, so macro definition is actually a macro usage, as surprising as it may sound

**Comment by DJMcNab** [comment]
I thought it has different syntax, i.e. `macro_rules! $name: ident {$inner: tt}`, which you cannot define with a regular macro. I'm not certain though

**Comment by aochagavia** [comment]
I think it is true that you can't define own macros with that syntax. Still, the parser currently treats `macro_rules!` as a macro usage (you can test that by displaying the AST in VSCode). We could consider changing that, though I am not sure it is worth it to make a distinction at the parser level.

**Comment by CAD97** [comment]
[This is also the case in the current wg-grammar grammar draft.](https://github.com/rust-lang-nursery/wg-grammar/pull/13/files#diff-8810f7a13a8f9ad79e7163b515c4a9f3R1)
