### ISSUE TITLE
Assist: invert if condition

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2219]
```rust
        if !line.starts_with("//!") { // <- cursor is on this line
            missing_docs.push(f.path().display().to_string());
        } else {

        }
```

->

```rust
        if line.starts_with("//!") {

        } else {
            missing_docs.push(f.path().display().to_string());
        }
```

[Apply De Morgan](https://github.com/rust-analyzer/rust-analyzer/blob/f5e1b0f97c9e46b5186f99d744f4587b2aee397e/crates/ra_assists/src/assists/apply_demorgan.rs) would be a similar assist. Care should be taken to share the expression negation logic between the two!

**Comment by bravomikekilo** [comment]
I would like to try this feature
