### ISSUE TITLE
Usage with Nix/NixOS

### ISSUE THREAD

**Issue by thomasheartman** [rust-analyzer/rust-analyzer#2224]
Hey,

I've been hearing some really positive stuff about Rust Analyzer and wanted to try it out. I use Emacs, so there's some documentation for that already, but I'm also on NixOS and I'm not quite sure what the best way (or any way, really) to install it via Nix is. Would you happen to have a portable setup/nix expression for this?

I know this is a bit of a tangential question to the project itself, but seeing as at least one of the maintainers of the repo uses NixOS (judging from blog posts), I thought it might not be too out there if you had any tips. I'm not sure whether it's worth adding to the docmentation (as it feels like more of a Nix-issue), but it might be useful to others too.

Cheers.

**Comment by matklad** [comment]
AFAIK there’s no ready nix expression yet: https://github.com/rust-analyzer/rust-analyzer/issues/1142

I have npm, vscode and rustup in my configuration.nix (https://github.com/matklad/config/blob/23a1fc73fcae0b0121af7494e5292bb62cfff4d0/configuration.nix#L111) and that should be enough for instructions in the readme to work.

**Comment by oxalica** [comment]
`rust-analyzer` and `vscode-extensions.rust-analyzer` are already included in nixpkgs since https://github.com/NixOS/nixpkgs/pull/77752

**Comment by thomasheartman** [comment]
Ah, this is amazing! Thanks for letting me know. It's been on my todo-list to get around to this and I spent a fair few hours on it, but I never got it to work. Now I don't have to, it seems. Good job, @oxalica! Really appreciate your contribution :heart:

**Comment by matklad** [comment]
Wow!
