### ISSUE TITLE
vscode plugin: propagete --watch arg to cargo-watch

### ISSUE THREAD

**Issue by chessnokov** [rust-analyzer/rust-analyzer#2239]
--ignore arg of cargo-watch does not work fine in some cases:
[Error when containing a non accessable directory](https://github.com/passcod/cargo-watch/issues/135)
but, --watch arg is does

**Comment by kiljacken** [comment]
@chessnokov Are you still having related problems with the new in-server cargo check functionality?

**Comment by chessnokov** [comment]
@kiljacken No, it is work fine!
