### ISSUE TITLE
Rename does not work for local variables bound inside a pattern

### ISSUE THREAD

**Issue by aochagavia** [rust-analyzer/rust-analyzer#224]
To reproduce, write the following code and attempt to rename `a`.

```rust
let (a, b) = (42, 54);
let y = a;
```

**Comment by aochagavia** [comment]
cc @kjeremy

**Comment by matklad** [comment]
Note that this is an interesting problem: in Rust, identifier in a pattern could be either a new name, or a reference to existing constant:

```rust

x: Option<i32> = None;
match x {
    None => (), // reference to `None` constant
    Something => (), // a name binding, equivalent to `_` more or less
}
```

So, this needs some special handling.

**Comment by daboross** [comment]
Note that even without a pattern, identifiers can refer to existing constants:

```
let x = Constant;
// refers to Constant struct
// (does not move 'x' nor trigger 'unused variable' warning)
let Constant = x;
// vs. variable (moves and triggers unused variable warning)
let C = x;
// let z = x; // cannot do due to moving 'x' into 'C'
```

It's pretty niche so I don't expect it needs to be handled if it'd be extra work, but worth noting that this isn't just for special patterns but for all bindings.

**Comment by kiljacken** [comment]
This works on current master. Closing :)
