### ISSUE TITLE
Bugs parsing the try!() macro

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#2241]
This code from serde causes red underlining in VS Code even though rustc is fine with it:

```rust
        match try!(self.next_key_seed(kseed)) {
            Some(key) => {
                let value = try!(self.next_value_seed(vseed));
                Ok(Some((key, value)))
            }
            None => Ok(None),
        }
```

As of 5c3ccc55082838524f695ffe40138fd8e805db70.

**Comment by lnicola** [comment]
So `try!` is deprecated in the 2015 edition, but `serde` uses `#[allow(deprecated)]`. We probably don't take that into account.

**Comment by matklad** [comment]
Yeah, that's tricky. Ideally, we should add editions to the parser, but that requires some design work. In the meantime, I'd be fine with just contextually parsing `try` as a macro if it is followed by `!`, this should be a relatively isolated "fix" to the parser.

**Comment by lnicola** [comment]
I think this is working now:

![image](https://user-images.githubusercontent.com/308347/102768841-7278cf80-438a-11eb-985a-d843b8b9d992.png)
