### ISSUE TITLE
Bugs parsing casts in range expressions

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#2242]
This code causes red underlining in VS Code, even though rustc accepts it:

```rust
&buf[cur.position() as usize..]
```

(`Syntax Error: expected expression`, underlining only from the closing bracket.)

**Comment by matklad** [comment]
@goffrie any change you might want to look into this? Looks like after https://github.com/rust-analyzer/rust-analyzer/commit/b63f260bbcf89a2b40358f534b97f672468294fb cast binds to loosely, and `() as () ..` is not parsed correctly. I wonder if that means we need to add explicit binding power to postfix operators, like the full pratt parsing is supposed to do?

**Comment by matklad** [comment]
(marking as hard, because a long time passed since I've written the pratt parser the last time, and [this loop](https://github.com/rust-analyzer/rust-analyzer/blob/5c3ccc55082838524f695ffe40138fd8e805db70/crates/ra_parser/src/grammar/expressions.rs#L276-L295) again looks like magic to me :( )
