### ISSUE TITLE
Folding multiline comments cuts off suffix

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2247]
Folding the following:

```rust
/*
*
*
*/
let i = ...
```

Shows up like this:

```rust
/*...
let i = ...
```

Which is awkward.

**Comment by matklad** [comment]
I bet that's the same thing as #2033: VS Code only supports full-line folds

**Comment by lnicola** [comment]
I'm not sure what the problem was, but it looks fine now?

![image](https://user-images.githubusercontent.com/308347/102768968-a94ee580-438a-11eb-9e4b-899c4d5260ea.png)
