### ISSUE TITLE
Support declarative macros 2.0

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#2248]
Some source code in `rustc` start to using `decl-macro` : 

https://github.com/rust-lang/rust/blob/82cf3a4486bc882207a09bf0d9e2dea4632781aa/src/libsyntax_ext/lib.rs#L52-L60

It would be nice to support it (at least in parser) or ignore it right now to have a better experince on browsing rustc source code by RA.

**Comment by DJMcNab** [comment]
We also need this for e.g. https://doc.rust-lang.org/std/clone/macro.Clone.html to get proper doc comments for derive macros.

**Comment by edwin0cheng** [comment]
In `ra_parser`, should we add a new `ast::MacroCall2` or reuse `ast::MacroCall` and let hir decided which one to be ?

**Comment by DJMcNab** [comment]
I don't think we should reuse macro call

**Comment by matklad** [comment]
For macro keyword, calls and defs have different syntax, so we should just add a dedicated node for this, `MacroDef`

**Comment by DJMcNab** [comment]
Hold on though - in #2315 I'm already using `MacroDef` to mean macro_rules or procedural macros. We either need a different name for that or a different name for this

**Comment by matklad** [comment]
I don't think ra_syntax should now anything about proc_macros: proc_macros
don't have a syntax-level representation

**Comment by DJMcNab** [comment]
I needed to do that because a lot of stuff used e.g. the `NameOwner` impl of `MacroDefId.ast_id`, and `MacroDef` needed to implement from and To source, which needed a Syntax node implementation for some things

**Comment by jonas-schievink** [comment]
FYI: Rust 1.51.0 will stabilize `core::ptr::{addr_of, addr_of_mut}`, which are "2.0" macros

**Comment by edwin0cheng** [comment]
Since #8212 was merged. Let's close it first and handle related problems (Macro hygiene in macro 2.0) in separate issues.
