### ISSUE TITLE
Extend selection in patterns shold extend to comma

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2250]
In the following code

```rust
let _ = (krate, _crate_def_map, module_id);
let _: (krate, _crate_def_map, module_id) = ();
```

if the cursor is on **first** `_crate_def_map` and we press extend selection twice, we get

![image](https://user-images.githubusercontent.com/1711539/68923288-01cab100-078f-11ea-9f56-631fa1b106fc.png)

Note how comma is selected. In the second case, we get 

![image](https://user-images.githubusercontent.com/1711539/68923325-1c048f00-078f-11ea-83e7-cfe385dc88b1.png)

That is, comma selection step is missing. This should be fixed.

See also a similar recent issue for mentoring instructions: https://github.com/rust-analyzer/rust-analyzer/issues/2055

**Comment by matklad** [comment]
Note, while we are at it, it would be cool to change the implementation to try to select the following comma and whitespace, and on the previous one.

**Comment by gab-umich** [comment]
Hello @matklad, I'd wish to take on this issue. 

I wish to make sure that I we are consistent per your second comment: 

In the case of `let _: (krate, _crate_def_map, module_id) = ();`, by repeatedly pressing the extend selection on `_crate_def_map`, the expansion should follow the following expansion:

`_crate_def_map` -- original
`_crate_def_map, ` -- press once (with white spaces at the end, but not the one at the front)
`, _crate_def_map, ` -- press twice
`(krate, _crate_def_map, module_id) ` -- press three times (with white spaces at the end, but not the one at the front)

Am I interpreting it right?

**Comment by matklad** [comment]
>`, _crate_def_map, ` -- press twice 

This step is extra, once we've selected one list item with a delimiter, we should select the whole list next

**Comment by gab-umich** [comment]
Hello @matklad, thank you for your patience. 
I have fixed the issue (including making sure the delimiter selection prefers the following one instead of previous one). The test I wrote [here](https://github.com/rust-analyzer/rust-analyzer/pull/2523/files#diff-d9767539176796411aa547bb929e009eR454-R521) should verify the behaviour. Please let me know if you like it!
