### ISSUE TITLE
classify_name for MacroCall

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2260]
I saw this
https://github.com/rust-analyzer/rust-analyzer/blob/a599147b4232c0d4f6b071a3a96e86f903f4cf52/crates/ra_ide_api/src/references/classify.rs#L24

and went to implement it. I got stuck implementing `impl FromSource for MacroDef`.

**Comment by matklad** [comment]
MacroDefIds are primaraly created in DefCollector

**Comment by matklad** [comment]
see collect_macro

**Comment by kjeremy** [comment]
I can't figure out how to access the `DefCollector` from there. So far I have something like:

```rust
impl FromSource for MacroDef {
    type Ast = ast::MacroCall;
    fn from_source(db: &(impl DefDatabase + AstDatabase), src: Source<Self::Ast>) -> Option<Self> {
        let ast_id = AstId::new(
            src.file_id,
            db.ast_id_map(src.file_id).ast_id(&src.ast),
        );

        let kind = MacroDefKind::Declarative; // <--- ?
        
        let id: MacroDefId = MacroDefId{
            krate, // <--- ?
            ast_id,
            kind,
        };
        Some(MacroDef { id })
    }
}
```

Where `krate` and `kind` are obviously wrong.

**Comment by matklad** [comment]
`kind` is OK I think, it shouldn't matter much. The best way to get the "correct" crate is to first get a `Module` via `Module::from_definition`, and extract the crate from that. It's OK if this will be wonky, this whole module should be rewritten: #2258

**Comment by kjeremy** [comment]
Thanks I now have that working. The last piece I need to fill is  `NameDefinition::container` in `classify_name`. Is that the same module I found above?

**Comment by matklad** [comment]
yeah!
