### ISSUE TITLE
[Bug] rust-src path in Windows uses forward slashes in VSCode Extension

### ISSUE THREAD

**Issue by DhruvDh** [rust-analyzer/rust-analyzer#2278]
Opening a rust project in vscode gives me the following error -
```
rust-analyzer failed to load workspace: can't load standard library from sysroot "C:\\Users\\dhruv\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib/rustlib/src/rust/src" try running `rustup component add rust-src` or set `RUST_SRC_PATH`
```

**Comment by matklad** [comment]
Have you tried `rustup component add rust-src`?

Could you verify that the directory indeed is missing?

**Comment by DhruvDh** [comment]
Ah, the latest nightly was missing `rust-src`. I just figured it couldn't find `rust-src` because the path string was not well-formed. My bad.
