### ISSUE TITLE
Consider showing GitHub activity on Discord

### ISSUE THREAD

**Issue by aochagavia** [rust-analyzer/rust-analyzer#228]
[This page](https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks) describes how to show GitHub activity on a discord channel. I think it would be nice to show a message on Discord whenever a PR is opened. This will probably require admin rights that only @matklad has

**Comment by matklad** [comment]
SGTM, fixed in https://discordapp.com/channels/509329129070657540/511915505725210634

**Comment by aochagavia** [comment]
What is the current setup? I just created a PR to test it but nothing appeared on the gitupdates channel. Maybe it is configured to show new commits on the master branch?

**Comment by matklad** [comment]
It was set to pushes, changed to everything

**Comment by aochagavia** [comment]
Just saw your comment on the channel. Nice! I'll close this then.

BTW feel free to turn it off if you think it is annoying. And get better soon!
