### ISSUE TITLE
Const generics don't seem to be supported at all

### ISSUE THREAD

**Issue by slightlyoutofphase** [rust-analyzer/rust-analyzer#2281]
VS Code screenshot with an entirely const-generics-based crate of mine open:

![Capture](https://user-images.githubusercontent.com/47403582/68999645-43dc1b80-0891-11ea-966a-b6fe72e859a6.PNG)

On a (possibly) related note, also, is the (obviously incorrect) inference of `val` as being of type `&[u8]` on line 114 in the screenshot just a side effect of it being part of a const generic type, or is that a separate bug I should open an issue for?

**Comment by kjeremy** [comment]
If you remove the const generics is 114 still incorrect? If so I would file a separate issue.

**Comment by slightlyoutofphase** [comment]
I mean, If I "removed the const generics", it would still be... generic in every possible way. Which is to say that it is, in any case, a fully generic implementation of the Extend trait, where `u8` (or more specifically `&[u8]` simply aren't present in any way shape or form.

**Comment by kjeremy** [comment]
What I mean is... does that contribute to the separate issue?

**Comment by flodiebold** [comment]
I would guess that the `&[u8]` type gets inferred from the argument type of the `write` method. You could verify that by checking where it takes you if you goto def on that call.

**Comment by Matthias247** [comment]
Here is an older ticket for const generic parsing: #1574
