### ISSUE TITLE
goto in match_ast! macro doesn't work

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2303]
#2273 doesn't seem to work inside the `match_ast!` macro.

**Comment by kjeremy** [comment]
Let me expand on this: goto def and hover (as of #2307) do not work on things declared inside the macro.

This test passes:

```rust
#[test]
    fn goto_from_macro_local() {
        check_goto(
            "
            //- /lib.rs
            macro_rules! id {
                ($($tt:tt)*) => { $($tt)* }
            }

            id! {
                fn bar() {
                    let i = 0;
                    let j = i<|> + 1;
                }
            }
            ",
            "i BIND_PAT FileId(1) [11; 12) [11; 12)",
        );
    }
```

BUT go to definition either doesn't work or brings you to the beginning of the file so maybe the navigation target is wrong?

**Comment by kjeremy** [comment]
As a datapoint. With the following code in hover.rs:

```rust
if range.is_none() {
        let node = ancestors_at_offset(&file, position.offset).find(|n| {
            ast::Expr::cast(n.clone()).is_some() || ast::Pat::cast(n.clone()).is_some()
        })?;
        let frange = FileRange { file_id: position.file_id, range: node.text_range() };
        eprintln!("frange, {:?}", frange);
        res.extend(type_of(db, frange).map(rust_code_markup));
        eprintln!("res, {:?}", res);
        range = Some(node.text_range());
    };
```

And the following test:

```rust
            //- /lib.rs
            macro_rules! id {
                ($($tt:tt)*) => { $($tt)* }
            }
            
            //id! {
                fn bar() {
                    let i = 0;
                    let j = i<|> + i;
                }
            //}
```

Reports i as:

> frange, FileRange { file_id: FileId(1), range: [111; 112) }
> res, HoverResult { results: ["```rust\ni32\n```"], exact: true }

Uncommenting the macro results in

> frange, FileRange { file_id: FileId(1), range: [53; 123) }
> res, HoverResult { results: [], exact: true }

I'm getting confused between all these exciting types and I suspect that the problem here is in `hover::type_of` where something isn't getting translated correctly.

**Comment by flodiebold** [comment]
Works now as far as I can tell.
