### ISSUE TITLE
lsp infinite loop in chalk

### ISSUE THREAD

**Issue by Speedy37** [rust-analyzer/rust-analyzer#2313]
In my project I always get rust-analyser stuck and have to reload vscode to get it to work again.

By attaching a debugger to the lsp_server, its never getting out of:

```
ra_lsp_server.exe!_ZN155_$LT$chalk_solve..solve..slg..SlgContextOps$LT$TF$GT$$u20$as$u20$chalk_engine..context..ContextOps$LT$chalk_solve..solve..slg..SlgContext$LT$TF$GT$$GT$$GT$21instantiate_ex_clause17hc19f8c48832172ebE
```

**Comment by matklad** [comment]
I think that's https://github.com/rust-lang/chalk/issues/280

**Comment by matklad** [comment]
cc https://github.com/rust-analyzer/rust-analyzer/issues/2052 (we need re-check this once that is fixed)

**Comment by Speedy37** [comment]
I found out the file I should not open that trigger this. I can't share it, but it contains a few methods that looks like the test case made by nikomatsakis.
