### ISSUE TITLE
replace flexi_logger with env_logger

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2335]
We use flexi_logger as a logging facade. Originally, I've chosen it because it allows to easily duplicate logs between stderr and stdout. SInce then, however, we've got a really nice logging on the client side, so I never actually use the "write to file" log. 

I suggest switching to `env_logger` instead, to minize the size of dependencies.

**Comment by lnicola** [comment]
When implementing this, make sure to look at the `env_logger` [features](https://github.com/sebasmagri/env_logger/blob/master/Cargo.toml#L22). My feeling is that we don't need all of them.
