### ISSUE TITLE
Assist for sorting struct/enum field/variants by name

### ISSUE THREAD

**Issue by repnop** [rust-analyzer/rust-analyzer#2364]
As the title suggests, I think it would be nice to have an assist to offer to sort struct fields/enum variants via their names, e.g.
```rust
struct Foo {
    qux: u8,
    bar: i32,
}
```
becomes
```rust
struct Foo {
    bar: i32,
    qux: u8,
}
```

Thoughts?

**Comment by rep-nop** [comment]
One option too would be to prevent the assist from displaying if the struct or enum is `#[repr(C)]` or anything where the ordering effects layout in a specified way

**Comment by Centril** [comment]
N.B. `#[derive(Ord)]` is also something that is sensitive to reordering.

**Comment by rep-nop** [comment]
Ah, good point, didn't think of that :) Probably worth compiling a list of that sort of stuff and see if its reasonable to actually implement this in the first place.

**Comment by matklad** [comment]
Not sure this is really needed: there's "sort lines" action in most editors anyway.

**Comment by matklad** [comment]
In general (but this is subjective of course, your taste might be different) I dislike alphabetic ordering of things, and prefer a semantic based one: put important public things first, put related things 
next to each other, put helper implementation details last
