### ISSUE TITLE
Duplicate diagnostic queries when pressing Enter

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2367]
When I press enter (that is, add a single newline), I often see an output like this in the rust-analyzer tab, if profiling is enabled:

![image](https://user-images.githubusercontent.com/1711539/69475997-19381880-0de5-11ea-9b47-adc168db59b6.png)

Looks like we process change event **twice**. We should figure out why is this happening. The best way to debug this would probably be:

* add `eprintln` in `handlers.rs` for diagnostics, to see dupes even with profiling disabled
* reproduce the effect on a small project
* enable client-side tracing (see `dev/README.md` for instructurions)
* enable logging in `main_loop`

Somewhat orthogonality, we should add some debouncing for diagnostics. Ie, we should avoid producing more than one diagnostic request per `100ms`, but we should immediately trigger request after a period of quiescence, *and* we should schedule a request to happen after 100ms anyway (this last bit might be tricky).

**Comment by michalt** [comment]
This sounds like a fun first issue :) But I can't seem to reproduce this:

```
 216ms - handle_inlay_hints
      161ms - get_inlay_hints
          161ms - SourceAnalyzer::new
                [...]
                0ms - body_with_source_map_query (1 calls)
                3ms - trait_solve_query (2 calls)
               88ms - ???
       19ms - get_inlay_hints
           19ms - SourceAnalyzer::new
                0ms - body_with_source_map_query (1 calls)
                0ms - def_with_body_from_child_node (1 calls)
               18ms - trait_solve_query (15 calls)
       25ms - get_inlay_hints (3728 calls)
  217ms - publish_diagnostics
      217ms - diagnostics
           69ms - Module::from_definition
               69ms - Module::from_file
            1ms - body_with_source_map_query (51 calls)
            7ms - parse_query (1 calls)
           45ms - trait_solve_query (124 calls)
           93ms - ???
   73ms - publish_decorations
       73ms - highlight
           16ms - classify_name (210 calls)
           55ms - classify_name_ref (599 calls)
```

That being said, I find it a bit surprising that we spend ~200ms just for a whitespace change (this is on rust-analyzer itself, which is not that small, but still). Is this expected? I'd imagine that most things should've been already cached.

The idea about limiting how often we recompute things sounds good -- adding something like two spaces will actually compute diagnostics twice (even if both are added within a very short period of time). Perhaps it's an option to introduce some delay, e.g., if the last time we calculated diagnostics was <100ms ago, wait some time, then if no new request has been made, handle the existing one, otherwise, handle the new one instead?

**Comment by matklad** [comment]
Hm, I've actually fixed this recently in https://github.com/rust-analyzer/rust-analyzer/commit/6acef5a7c088bcc1cdf8a64e28b8f20ddf9dcde7#diff-0bb23f5b7637c18cca199c1880823d57

The problem was that we received to events for this modification: first, the edior tells us that it modifed the in-memory buffer. Than, the file is saved to disk (i have aouto-save enabled) and watcher sends a duplicate notification.

>That being said, I find it a bit surprising that we spend ~200ms just for a whitespace change (this is on rust-analyzer itself, which is not that small, but still). Is this expected? I'd imagine that most things should've been already cached.

Yeah, that is excessive, trying to optimize this is a good idea, as relatively few efforts were put into this so far, so some low-handing fruits are to be expected!

>I'd imagine that most things should've been already cached.

We currently [don't really cahce](https://github.com/rust-analyzer/rust-analyzer/blob/d5a1a5e6147ffdcd655ea082161bc63ac2974f2e/crates/ra_hir_ty/src/db.rs#L64-L70) type inference results, and I think we really shouldn't (as all except trivial modificaitions will blow them away). But I think even from-scratch analysis of a single file should maybe be faster than 200ms. It would be great to catch some profiles and see where the time goes.

Also, `93ms - ???` means that there are 93 milliseconds unaccounted for by our profilng infrastructure! It would be cool to figure out where they come from and add approprit `profile` calls. 


So, let's close this, issue, but, if you feel like poking at rust-analyzer with profiler, that would be super sweet!

**Comment by matklad** [comment]
Let's close this, but various profling things can be disucssed in zulip: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0 :)

**Comment by matklad** [comment]
>We currently don't really cahce type inference results

@flodiebold this makes me think... I think it does make sense to cache type-inference on a function granularity: we run syntax highlighting and diagnostics for the whole file, so while you are typing furiously in function `foo`, it makes sense to not re-run type-inference for `bar`.

The problem with this is that `trait_solver_query` is invalidated after every change via an untracked read... What would be the correct caching strategy for caching it?

**Comment by flodiebold** [comment]
> @flodiebold this makes me think... I think it 
> The problem with this is that `trait_solver_query` is invalidated after every change via an untracked read... What would be the correct caching strategy for caching it?

I think we don't need to cache the trait solver at all, as long as we can cache the individual trait queries. If that's prevented by the solver query, maybe we shouldn't use a query for the solver? I think the semantics we want would be that the solver is recreated on every change, but doesn't influence caching of individual queries. I'm not sure what the current semantics are (can't look it up currently)

**Comment by flodiebold** [comment]
> @flodiebold this makes me think... I think it does make sense to cache type-inference on a function granularity: we run syntax highlighting and diagnostics for the whole file, so while you are typing furiously in function `foo`, it makes sense to not re-run type-inference for `bar`.

Don't we even have a test for this? It probably doesn't involve any trait queries though...

**Comment by matklad** [comment]
Nope, we check that `crate_def_map` is not invalidated, and we also check that diagnostics do not block typing. We don't have a test that type-infernece is per-function, as it's not true. Or, we have this test and I don't know about it :D

**Comment by flodiebold** [comment]
We do: https://github.com/rust-analyzer/rust-analyzer/blob/d5a1a5e6147ffdcd655ea082161bc63ac2974f2e/crates/ra_hir_ty/src/tests.rs#L250

**Comment by matklad** [comment]
Hm, fascinating! I do see repeated `trait_solve_query` in profiling output though...

```
129ms - trait_solve_query (127 calls)
```

**Comment by flodiebold** [comment]
Yeah, the test doesn't do any trait queries, I think. And the solver might be the problem (if there indeed is one)

**Comment by matklad** [comment]
Hm, so if I modify the test to be more interesting, it indeed re-runs `trait_solve` query. **However**, it doesn't re-run `infer` query.

That is, salsa re-runs `trat_solve` to validate type inference!

**Comment by matklad** [comment]
Yeah, confirmed that this change

```diff
diff --git a/crates/ra_hir_ty/src/traits.rs b/crates/ra_hir_ty/src/traits.rs
index c4dc857bc..70d15153e 100644
--- a/crates/ra_hir_ty/src/traits.rs
+++ b/crates/ra_hir_ty/src/traits.rs
@@ -68,7 +68,7 @@ pub(crate) fn trait_solver_query(
     db: &(impl HirDatabase + salsa::Database),
     krate: CrateId,
 ) -> TraitSolver {
-    db.salsa_runtime().report_untracked_read();
+    let _ = db.crate_def_map(krate);
     // krate parameter is just so we cache a unique solver per crate
     let solver_choice = chalk_solve::SolverChoice::SLG { max_size: CHALK_SOLVER_MAX_SIZE };
     debug!("Creating new solver for crate {:?}", krate);
```

improved diagnostic performance, to the point where almost all time is in `117ms - ???`.

The question is: is this actually correct?

**Comment by flodiebold** [comment]
Ok, that makes sense because only the trait_solve query directly depends on the solver. Still would probably be good to avoid doing that...

**Comment by flodiebold** [comment]
No, I think depending just on the def map of that create will not be enough. The solver can at least also cache state depending on other crates.

**Comment by flodiebold** [comment]
Can we instead get the solver in an untracked way in the solve query?

**Comment by matklad** [comment]
>Can we instead get the solver in an untracked way in the solve query?

You mean, in `salsa::transparent` way? THat is, to just create a fresh solver for each query? It gives the same improvement for diagnostics, however, `analysis-stats` are predictably twice as slow

**Comment by flodiebold** [comment]
No, I mean basically having the query as it is now, but avoiding the dependency edge from solve to solver. I don't know if that's possible with salsa currently?

**Comment by matklad** [comment]
Ah, that kind of untracked... I don't think salsa has that yet. But would this be correct?

If `trait_solve` looks at the `trait_solver`, but doesn't record a dependecy edge, we might get a query with zero inputs, which will be considered a constant.

**Comment by flodiebold** [comment]
Ah, of course... So we do need the dependency. I guess then the best we can do really is something like depending on all def maps...

**Comment by michalt** [comment]
> Let's close this, but various profling things can be disucssed in zulip: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0 :)

Sounds good -- I'll try to drop by the zulip chat tomorrow! (btw. thanks for all the replies/explanations!)
