### ISSUE TITLE
Resolve `alloc` types

### ISSUE THREAD

**Issue by YetAnotherEmuDev** [rust-analyzer/rust-analyzer#2376]
Even after adding the `alloc` crate as a dependency with `extern crate alloc`, neither completion nor goto definition works for any `alloc` item.
This is especially needed for `#![no_std]` crates depending on allocation features.

**Comment by matklad** [comment]
I think the solution is to add `alloc` as a dependency into the crate graph. See https://github.com/rust-analyzer/rust-analyzer/commit/799903ba16dd0d80ca975a2e0e58e81f71ddc023#diff-1c8e6b45624e6ce512961af52e9a1aa3 and https://github.com/rust-analyzer/rust-analyzer/issues/2199#issuecomment-552140028, which handled the `core` in a similar manner.
