### ISSUE TITLE
can't start on macOS Catalina

### ISSUE THREAD

**Issue by andrewbanchich** [rust-analyzer/rust-analyzer#2395]
I was running macOS Mojave and `rust-analyzer` was working in Emacs. I then upgraded to Catalina and the server wouldn't start.

I did a `git pull` on the master branch of `rust-analyzer` then ran `cargo xtask install --server` again, but it still isn't working.

The `*rust-analyzer::stderr*` buffer in Emacs says:

```
Error: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }
Error: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }

Process rust-analyzer stderr<1> finished

Process rust-analyzer stderr finished
Error: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }
Error: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }

Process rust-analyzer stderr<1> finished

Process rust-analyzer stderr finished
```

macOS isn't prompting me to give `rust-analyzer` any new permissions, and I'm not sure what it is trying to access that macOS is blocking.

**Comment by kiljacken** [comment]
@andrewbanchich Are you still running into this issue on the latest master?

**Comment by andrewbanchich** [comment]
@kiljacken I actually figured it out but forgot to update this. I believe the issue was I needed to give Ruby directory permissions instead of just rust-analyzer.
