### ISSUE TITLE
Questions about Legacy macros pre-name-resolution expansion

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#2423]
When I am working on refactoring some macro related code in nameres to centralize macro expansion, I found this test: https://github.com/rust-analyzer/rust-analyzer/blob/4fd742d6bc23e2f61d0980e15234f09d7e715b76/crates/ra_hir_def/src/nameres/tests/macros.rs#L403-L426

If I remove `#[macro_export]`, this test will fail and the result will be :
```
| crate
| bar: t m
| baz: t v
| foo: t
```

It is because we have some special treatment of legacy macro:
https://github.com/rust-analyzer/rust-analyzer/blob/3206b83a70b4e9140a5f0d9d8454abb7864b543a/crates/ra_hir_def/src/nameres/collector.rs#L771-L780

Bascially it try to expand legacy macros **BEFORE** name resolution. So that's why the previous test works. Seem like there are some bugs which overwrites `PerNs` but I am not so sure.  

So My question is, how current items collecting phase handle this case in general?

**Comment by matklad** [comment]
Heh, the test is indeed surprising, but I think this i how rustc works. Specifically, the following works:

```rust
mod m {
    macro_rules! foo {
        () => ()
    }
    use foo as bar;
    bar!();
}
```

use `self::foo as bar` doesn't though.  https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/using.20.60macro_rules.60.20macros

**Comment by edwin0cheng** [comment]
I found out the the actual reason why the test fail when `#[macro_export]` is removed : 

The current implementation handle all macro name resolution in different path such that it won't update its name to `PerNs`, only if it is marked as `#[macro_export]`. And the test setup used in `type_value_macro_live_in_different_scopes` just dump out data of  `PerNs` contains. So it is okay to fail here.

OTOH, even more surprising is that, our current implementation actually match how rustc behavior:

```rust
#![allow(unused_macros)]
#![allow(unused_imports)]

mod m {
    macro_rules! foo {
        ($id:ident) => {
            pub fn $id() -> u32 {0}
        }
    }
    use foo as bar;
    pub mod inner {
        // It works
        crate::m::bar!(f);
        // It won't works in rustc. 
        // failed to resolve: could not find `foo` in `m`
        crate::m::foo!(g);
    }
}

fn main() {  
    // _a : u32 in RA
    let _a = m::inner::g();
    // _b : {unknown) in RA
    let _b = m::inner::g();
}
```

**Comment by matklad** [comment]
Yes, this is intentional because `macro_rules` are weird. macro_rules are normally *not* added to the namespace proper, such that it's impossible to use macro_rules macros. Instead, they are added to "lexical" macro scope. 

The exception here is `#[macro_export]` macros, whose effect is to mount the macro def at the current crate's root, such that it become `use`able from inside and outside the crate. 

However, the `use _foo as foo` trick actually mounts the macro in the namespace properly, because, in 2018 edition, `use plain` looks for plain in the lexical namespace of the module.
