### ISSUE TITLE
Rainbow highlighting doesn't work

### ISSUE THREAD

**Issue by ice1000** [rust-analyzer/rust-analyzer#2436]
When disabled (`"rust-analyzer.rainbowHighlightingOn": false`), it looks fine:
![image](https://user-images.githubusercontent.com/16398479/69764341-08b5d400-113e-11ea-9c28-c38c3d9b8314.png)

When enabled (set the value to true), it looks like the highlighting is gone instead of rainbowed:
![image](https://user-images.githubusercontent.com/16398479/69764373-208d5800-113e-11ea-83c3-f4a964cf975e.png)

**Comment by mkpankov** [comment]
I think I'm hitting this too

**Comment by cynecx** [comment]
ping? (getting this too)

**Comment by matklad** [comment]
I didn't have capacity to look into this yet. If anyone wants to investigate, here's the rust part:

* https://github.com/rust-analyzer/rust-analyzer/blob/d0b52e5d84b8c371b74d4d5d43f45be91f103d12/crates/ra_ide/src/syntax_highlighting.rs

And here's TypeScript counterpart:

* https://github.com/rust-analyzer/rust-analyzer/blob/d0b52e5d84b8c371b74d4d5d43f45be91f103d12/editors/code/src/highlighting.ts

**Comment by lnicola** [comment]
Our hand-rolled highlighting is no more, and the rainbow highlighting support only remains for the CLI, where it seems to work:

![image](https://user-images.githubusercontent.com/308347/102774323-6fcea800-4393-11eb-9a08-bf5cf91f0075.png)

I propose we close this, and maybe even remove the remaining code since I suspect it's not really used (CC @matklad?).

**Comment by matklad** [comment]
I'd love to keep backend code for this, it isn't that complicated. Maybe someone would want to revive the front-end part of this!

**Comment by matklad** [comment]
but yeah, the issue itself should probably be closed -- the thing it was talking about isn't here anymore!

**Comment by lnicola** [comment]
> Maybe someone would want to revive the front-end part of this!

Using decorations? I feel this would be better handled at LSP level.
