### ISSUE TITLE
Bad intellisense on master

### ISSUE THREAD

**Issue by Matelasse** [rust-analyzer/rust-analyzer#2439]
Using the `master` branch, the following snippet fails to get meaningful completions. I've put '|' symbol to mark the spots where I didn't get the necessary completions. I am not seeing `filter_map`, `for_each`, `path` and `display` function completions. I suspect type inferences are wrong. How can I provide more helpful debugging information? Thanks for all the work.

```rs
use walkdir::WalkDir;

fn main() {
    WalkDir::new("foo")
        .into_iter()
        .|filter_map(|e| e.ok())
        .|for_each(|e| println!("{}", e.|path().|display()))
}
```

**Comment by lnicola** [comment]
There are still some limitations when associated types are involved, see e.g. https://github.com/rust-analyzer/rust-analyzer/issues/832.

**Comment by Matelasse** [comment]
@Inicola this does happen for a `vec<u32>` too. I'm seeing `into_iter` for it, but no `map`

**Comment by Matelasse** [comment]
@matklad Do you know if this is a regression?

**Comment by matklad** [comment]
I don't know off the top of my head. It might be: we did a bunch of big refactorings recently.

**Comment by flodiebold** [comment]
I don't think so, as far as I remember there were always still some problems with iterator chains. Completing iterator chains is kind of a milestone for the type system, I hope I'd have noticed if we got there :)

I think there are still some details missing because of which these Iterator impls don't manage to apply. I haven't looked into the concrete problems recently though.

**Comment by flodiebold** [comment]
Ah no, this is another case of https://github.com/rust-lang/chalk/issues/234, because of which we can't normalize the associated type that is the return type of `into_iter`.

**Comment by flodiebold** [comment]
Every one of these completions works now :slightly_smiling_face:
