### ISSUE TITLE
doesn't work on vscode-remote

### ISSUE THREAD

**Issue by divinerapier** [rust-analyzer/rust-analyzer#2447]
Hi,

"Enter Key" does not work on vscode-remote, I tried restarting it for several times.
And then I found something wrong with `cargo watch`.

``` 
[Running 'cargo check --all-targets --message-format json ']
Fail to parse to json : { SyntaxError: Unexpected token R in JSON at position 1 }{"reason":"compiler-artifact","package_id":"proc-macro2 1.0.6 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["custom-build"],"crate_types":["bin"],"name":"build-script-build","src_path":"/home/my/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.6/build.rs","edition":"2018"},"profile":{"opt_level":"0","debuginfo":2,"debug_assertions":true,"overflow_checks":true,"test":false},"features":["default","proc-macro"],"filenames":["/home/my/project/target/debug/build/proc-macro2-5b88db6c56b02325/build-script-build"],"executable":null,"fresh":true}
```
I don't know if this is the reason.

And it is said that `Cannot read property 'type' of undefined` when restarts by `Command + P; >rust analyzer: restart server`.
Here is my configuration:
``` json
{
    "rust-analyzer.highlightingOn": true,
    "rust-analyzer.displayInlayHints": true,
    "rust-analyzer.trace.server": "verbose",
    "rust-analyzer.lruCapacity": 1000,
}
```

**Comment by lnicola** [comment]
Did you follow the steps [here](https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user#vs-code-remote) and does anything change if you set `"rust-analyzer.enableEnhancedTyping": false`?

**Comment by divinerapier** [comment]
@lnicola Thanks for your reply.
Yes, I'm sure I follow the docs.

The  `cargo check --all-targets --message-format json` works on remote if I run it on a terminal directly. But it is failed on vscode-remote. 

And `rust-analyzer.enableEnhancedTyping` is not override.

I reinstalled the `rustup`,`cargo`, `rust-analyzer` and `vscode` just now.
Unfortunately it doesn't work. Here are the error messages:
```
Rust Analyzer Language server: 
Couldn't start client Rust Analyzer Language Server
```
```
cargo-watch:
cargo-watch started.Error on cargo-watch process : {
spawn cargo ENOENT}
```

**Comment by bjorn3** [comment]
Do you have cargo-watch installed on the remote system?

**Comment by divinerapier** [comment]
@bjorn3 
I have installed it by `cargo install cargo-watch`, maybe I think it is right.

**Comment by Dhs92** [comment]
Disabling enableEnhancedTyping fixed the issue for me, VSC 1.40.2

**Comment by divinerapier** [comment]
Thanks to @Dhs92 , it works after sets `rust-analyzer.enableEnhancedTyping` to `false`.
But the `rust-analyzer` is still not working. 
There is no log message although `"rust-analyzer.trace.server": "verbose"` is set. And the auto completion is not working.
I have reinstalled it for many many times refers to [docs](https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user).

**Comment by Dhs92** [comment]
You're installing it inside of WSL correct? @divinerapier

**Comment by divinerapier** [comment]
@Dhs92 
Local is `MacOS 10.13.4`.   
Remote is `ubuntu 18.04` .  
Version of `rust` is `nightly-2019-11-25`.

**Comment by Dhs92** [comment]
Oh right. Are you installing RA on the remote system, not the host system?
https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user#vs-code-remote

**Comment by divinerapier** [comment]
@Dhs92 Yes...

**Comment by bjorn3** [comment]
@divinerapier Do you still have this issue? It works fine for me now.
