### ISSUE TITLE
fn signatures don't include qualifiers

### ISSUE THREAD

**Issue by JasperDeSutter** [rust-analyzer/rust-analyzer#2450]
Currently, signatures for functions do not include qualifiers like `unsafe`, `const`, `async`... More info here about which qualifiers are allowed: https://doc.rust-lang.org/reference/items/functions.html

It would be helpful to also include this (mainly for hover and completion), as it is currently not possible to tell if a function is async or unsafe without a go-to definition - or seeing rustc compilation errors at call site.
![image](https://user-images.githubusercontent.com/16452324/69878028-07aeaf00-12c4-11ea-9b7e-e7c301939783.png)

Related: `unsafe` is also not shown in signatures for unsafe traits:
![image](https://user-images.githubusercontent.com/16452324/69877926-be5e5f80-12c3-11ea-8b02-5acee473f834.png)

**Comment by matklad** [comment]
Yep, this would be good to fix! The relevant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/c5b322e3df0f3c9d81676bece76bcb76eac6e1ba/crates/ra_ide/src/call_info.rs

Specifically, extending `CallInfo::with_fn` should do the trick here. However, this bit of code might want some bigger refactoring. Specifically, `as_callable_def` doesn't handle closures at the moment, and is in general at the wrong level of abstraction. Ideally, we should extract the call info directly from the callable type (don't have a solid design for this in my head yet).
