### ISSUE TITLE
{unknown} return type when calling simple function.

### ISSUE THREAD

**Issue by FilipAndersson245** [rust-analyzer/rust-analyzer#2452]
![image](https://user-images.githubusercontent.com/17986183/69899558-5b72d400-1368-11ea-8bf6-16b876998008.png)

**Comment by flodiebold** [comment]
IIRC this is because we're not resolving `str` correctly in the module where `as_str` is defined, because that also imports the `str` module and we're not handling the shadowing correctly.

**Comment by flodiebold** [comment]
Ah, we actually already have a report for this: #1905. So I'll close this one.
