### ISSUE TITLE
npm fails on install (windows)

### ISSUE THREAD

**Issue by jasonwilliams** [rust-analyzer/rust-analyzer#2456]
```
will run: cargo install --path crates/ra_lsp_server --locked --force
  Installing ra_lsp_server v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\ra_lsp_server)
    Updating crates.io index
    Finished release [optimized] target(s) in 0.61s
  Installing C:\Users\jasew\.cargo\bin\ra_lsp_server.exe
   Installed package `ra_lsp_server v0.1.0 (C:\Users\jasew\workspace\rust-analyzer\crates\ra_lsp_server)` (executable `ra_lsp_server.exe`)

will run: cmd.exe /c npm --version
6.12.1

will run: cmd.exe /c npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\jasew\workspace\rust-analyzer\editors\code\node_modules\typescript\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\jasew\workspace\rust-analyzer\editors\code\node_modules\typescript\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jasew\AppData\Roaming\npm-cache\_logs\2019-11-30T20_42_18_971Z-debug.log
Error: install client

Caused by:
    `cmd.exe /c npm ci` exited with exit code: 0xfffff026
error: process didn't exit successfully: `target\debug\xtask.exe install` (exit code: 1)
```

Seems like typescript doesn't install before properly.
Looks like its to do with npm ci, when i install manually with npm install its fine.

I think this is only happening on windows

**Comment by matklad** [comment]
Hm, interesting... 

Have no idea what's going on here, really. We use `npm ci` for installation because, as far as I know, it's the only install-like command that actually honors `package-lock.json`.

**Comment by jasonwilliams** [comment]
@matklad both ci and install honor the `package-lock.json` file
https://docs.npmjs.com/cli/install

I think ci will remove the entire `node_modules` folder and start again, plus it will error if a dependency isn't in the package-lock.json file.
https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci

Not sure why this issue happens though, looks like something tries to use typescript before the install is finished? or ci is not re-populating that dep

**Comment by jasonwilliams** [comment]
I have managed to fix some of this by using `npx` before the command so it will use the local node_modules dep instead of looking in the PATH globally.

**Comment by matklad** [comment]
>both ci and install honor the package-lock.json file

Hm, I am pretty sure this wasn't the case a while ago. But yeah, looks like now `install` is OK?  I've change ci back to install in #2462 

>Ive set it to install which gets me further but now its trying to find vsce which doesn't exist

It should pick the one from `node_modules`: https://docs.npmjs.com/misc/scripts#path. I definitelly don't have vsce installed globally, but it works for me

**Comment by jasonwilliams** [comment]
ok interesting, i must have some weird symlink failure going on there.
Will need to investigate

**Comment by kiljacken** [comment]
@jasonwilliams Are you still having problems, or can we close the issue? :)

**Comment by jasonwilliams** [comment]
@kiljacken you can close, i will open a new ticket if it happens again :)

**Comment by kjeremy** [comment]
I just ran into this on my semantic-tokens branch.

**Comment by kjeremy** [comment]
It looks like `cargo xtask install` is changing my `npm` from my local version to the one in `C:\Program Files\nodejs`
