### ISSUE TITLE
Support or-patterns (`pat_0 | ... pat_n`) in nested positions

### ISSUE THREAD

**Issue by Centril** [rust-analyzer/rust-analyzer#2458]
Tracking issue: https://github.com/rust-lang/rust/issues/54883
RFC: https://github.com/rust-lang/rfcs/pull/2535

The implementation history is available in the tracking issue, and I'm available if there are questions.

**Comment by bjorn3** [comment]
```rust
fn foo(x: Option<u8>) {
    match x {
        Some(0 | 1..=255) | None => {}
    }
}
```

parses fine.
