### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by kanekv** [rust-analyzer/rust-analyzer#2482]
In ide meeting notes I've noticed that `complete` feature is marked as `completed`. In my cases it more often doesn't work, I was under impression that it's in very early stage and there are lot of unsolved issues, thus I haven't been reporting a lot of use cases where it did not work for me. What is the status of this feature and what level of stability and coverage is expected?

**Comment by matklad** [comment]
There was a preface whcih I've forgot to copy that all rust-analyze features are assumed to be fast, but with incomlete langauge coverage, and all rls features are assumed to be slow, unless specifically marked otherwise.
