### ISSUE TITLE
Exclusive file locks taken on windows

### ISSUE THREAD

**Issue by Diggsey** [rust-analyzer/rust-analyzer#2488]
Rust-analyzer appears to take exclusive locks on the files it is accessing. This causes problems when eg. switching branches with git.

This is a common problem with NodeJS apps on windows, but I'm not sure if this is exactly the same issue, or if these locks are coming from the Rust code.

To reproduce:
- Open project in VS code
- Try to `git checkout` a branch which is missing a module that rust-analyzer was looking at.

Git will try to remove the files/folders and this conflicts with the exclusive locks held by rust-analyzer. Typically I end up getting permissions errors from both git and inside VS code.

**Comment by lnicola** [comment]
Can you try with the client-side file watcher (`rust-analyzer.useClientWatching`)?

**Comment by kiljacken** [comment]
With client side watching being the default now, we can probably close this issue?

**Comment by matklad** [comment]
I think so!
