### ISSUE TITLE
How to make it basically work?

### ISSUE THREAD

**Issue by gh67uyyghj** [rust-analyzer/rust-analyzer#2496]
Hi all, it seems that this is a very active project compared to buggy RLS and I really need to make it work for me since I've had enough of RLS due to the memory leak in Linux. I just can't run it, I used the instructions in the root README. On VScode startup I see the error message `Couldn't start client Rust Analyzer Language Server`. Please help me identify why it's not running. I am using archlinux if that helps.

**Comment by gh67uyyghj** [comment]
I deeply apologize, I needed to explicitly set the custom path for `ra_lsp_server` in order for the server to run. Probably this is more related to archlinux than rust-analyzer itself.

**Comment by lnicola** [comment]
It's not an Arch issue, but a Linux one. `rustup` adds `~/.cargo/bin` to `PATH` in your shell's configuration file, but if you're using a DE it won't run the shell first. So your `PATH` is only set for terminals.

My workaround was to add `PATH DEFAULT=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:@{HOME}/.cargo/bin:@{HOME}/.local/bin` to `~/.pam_environment`. Another solution would be to move `ra_lsp_server` to `/usr/local/bin`.

**Comment by matklad** [comment]
A PR which adds an appropriate warning message is welcome!
