### ISSUE TITLE
Breakpoint Ignored In Typescript extension while debugging RA itself

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#2509]
Seem like after we are using `rollup.js`, we didn't output corresponding source map for it. On the other hand, we didn't set the correct `outFiles` in `launch.json`:

https://github.com/rust-analyzer/rust-analyzer/blob/a38a3bf2298ceb0bf32cefbc18a427f50caeab84/.vscode/launch.json#L19

Can anyone confirm this bug in other platform (as I'm using Windows) ?

**Comment by lnicola** [comment]
I opened the extension directory, placed a breakpoint and chose "Debug: Select and start debugging", then picked "Extension". The breakpoint remained disabled and the debugger did not stop the new Code instance. The extension did load, however, and even threw an error in `Highlighter.setHighlights`.
