### ISSUE TITLE
Complex macro_rules error

### ISSUE THREAD

**Issue by Speedy37** [rust-analyzer/rust-analyzer#2520]
I've a big (500 lines recursive) macro_rules that generate a strictly typed keyvalue store database types.
Since about a week, using this macro generate a tons of errors (Missing structure fields) with the wrong position in the file. The macro is perfectly working with rustc.

Sadly, I can't share the macro, but I might be able to track down the root cause myself. 

Before spending some time on this, are macro_rules implementation complete and this is a bug, or is there a missing feature that might cause this?

**Comment by edwin0cheng** [comment]
Currently `macro_rules` expansion is not completed, there must be some bugs inside it, especially related to macro name resolution and expansion type (i.e. pat_bind and Ty etc). And the actual expansion part (macro rules matching and expand), except some rare cases, I will say it is okay-ish.

> Sadly, I can't share the macro, but I might be able to track down the root cause myself.

You could try to add a test case in 
https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_mbe/src/tests.rs

For example : something similar to:

https://github.com/rust-analyzer/rust-analyzer/blob/ee904594af174866cfa10474fd8fd3f23580b6af/crates/ra_mbe/src/tests.rs#L1326-L1361

**Comment by Speedy37** [comment]
I managed to build a test case I can share:

```rust
#[test] 
fn test_issue_2520() { 
    let macro_fixture = parse_macro(r#"
        macro_rules! my_macro {
            {
                ( $(
                    $( [] $sname:ident : $stype:ty  )?
                    $( [$expr:expr] $nname:ident : $ntype:ty  )?
                ),* )
            } => {
                Test {
                    $(
                        $( $sname, )?
                    )*
                }
            };
        }
    "#);
    
    macro_fixture.assert_expand_items(
        r#"my_macro ! {
            ([] p0 : u16 ,[] p1 : u32 , [|_| S0K0] s : S0K0 , [] k0 : i32 ,[] k1 : i64)
        }"#, 
        "Test {p0 , p1 , k0 , k1 ,}"
    );
}
```

**Comment by Speedy37** [comment]
For some reason, if I'm using `$( [$nname] )?` after `$( $sname, )?` I get `"Test {p0 , p1 , [s] k0 , k1 ,}` which is the correct result.

So once `[$expr:expr]` is hit, the loop stops if I don't use `$nname`, weird

**Comment by Speedy37** [comment]
This is due to the check in transcriber.rs:159:

```rust
        // if no var expanded in the child, we count it as a fail
        if !ctx.var_expanded {
            break;
        }
```
