### ISSUE TITLE
Function call with attributes on arguments fail to parse

### ISSUE THREAD

**Issue by repnop** [rust-analyzer/rust-analyzer#2521]
I just ran into a problem with r-a not parsing the function call when I have something like this
```rust
fn foo(a: Foo, #[cfg(debug_assertions)] b: Baz) { ... }

// ...

foo(a, #[cfg(debug_assertions)] b);
```
(r-a says it expects an expression, not attribute)

#1661 fixed the attributes when put on parameters, but not when calling functions with attributes on the arguments.

I did a test with adding `AttrsOwner` to `Expr` in the grammar file and that fixed it, but I'm not sure if that's the way to go or not. I could write up a quick PR if its something simple enough that though :)

**Comment by matklad** [comment]
I think this needs some research. The main question is where the arguments are paced: on the expresison, or on the function argument?

Ie, if `foo(#[dummy] x)` is allowed, is `foo((#[dummy] x,))` allowed as well? 

The former case should be easy-ish to fix, the latter might be more involved.

**Comment by repnop** [comment]
The second case does seem to be allowed: [playground link example](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=7b46482e93686158ef7f00bf42b1231a), running in debug/release passes different sized tuples to the function

**Comment by matklad** [comment]
Aha, here's the list where we should allow attributes on the expressions:
https://doc.rust-lang.org/reference/expressions.html#expression-attributes

**Comment by EddieIvan01** [comment]
Any progress?

**Comment by lnicola** [comment]
This is working now:

![image](https://user-images.githubusercontent.com/308347/105728511-e7649980-5f34-11eb-9b28-836cb2b83a1a.png)
