### ISSUE TITLE
no more type annotations displayed

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-analyzer/rust-analyzer#2524]
While working on [cargo-cache](https://github.com/matthiaskrgr/cargo-cache) I noticed that RA stopped displaying any type annotations.

When I start a new cargo project and write `let x = "hello";`, RA correctly displays `let x: &str = "hello";` but inside `cargo-cache`, it no longer does that for some reason.
I tried adding the line to random places without success (type annotations were missing). :/ 

RA @ 5202b0ecbaab2d44e886828f0e30dee67fad0c5c

**Comment by edwin0cheng** [comment]
I think maybe RA handle the `feature` cfg incorrectly in the root crate. In your case, RA seem to be recognized [`ci-autoclean`](https://github.com/matthiaskrgr/cargo-cache/blob/e2e1fa5a9f93391c686fcea2e88d16d219e940e7/Cargo.toml#L18 
) is enabled such that all your modules are disabled. If you remove that line in your toml, all type annotation are coming back.

The current feature `cfg` handling code works as follow: 
1. we insert the package available features in https://github.com/rust-analyzer/rust-analyzer/blob/b0581c2403f49c68738c039065fa2cfc41345738/crates/ra_project_model/src/lib.rs#L228
2. we check if the given feature is inserted before:
https://github.com/rust-analyzer/rust-analyzer/blob/6149ee30ef9a379f642c8a645cea13f32c4f3d84/crates/ra_cfg/src/lib.rs#L32

I think step 1 is not correct, but I'm not too sure..

**Comment by edwin0cheng** [comment]
cc @oxalica

**Comment by oxalica** [comment]
Currently it just simply add mark all features mentioned in `Cargo.toml` as enabled.
Resolving `default` features is not implemented yet.

IMO, negative features is quite counter-intuitive, especially when used with `--all-features`.

**Comment by oxalica** [comment]
I reviewed the code again, enabled features are actually resolved by `cargo metadata`. The command line options are here: https://github.com/rust-analyzer/rust-analyzer/blob/b0581c2403f49c68738c039065fa2cfc41345738/crates/ra_project_model/src/cargo_workspace.rs#L137

Maybe it's better to use `CargoOpt::SomeFeatures(vec!["default".to_owned()])` and/or get features from setting?
