### ISSUE TITLE
Autocomplete doesn't work for newly created targets

### ISSUE THREAD

**Issue by crumblingstatue** [rust-analyzer/rust-analyzer#2529]
1. Create a new cargo project
2. Check if autocompleting any std:: items works (it should).
3. Add a new bin or lib target.
4. In the source code of the new target, try autocompleting any std:: items. It only offers `self` and `super`.
5. Reload the ra-lsp extension. Now completion will also work in the new target.

rust-analyzer: 5202b0ec
Code: 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520)
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.4.2-arch1-1

**Comment by flodiebold** [comment]
This depends on #1968

**Comment by matklad** [comment]
And this one is fixed!
