### ISSUE TITLE
Find Implementations goes to weird places

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2531]
1. Open `handlers.rs` in vscode
2. Click on *Go To Definition* for `lsp::types::{CodeAction ...` which takes you to the definition for `CodeAction` in the lsp-types crate.
3. Above `CodeAction select `3 Implementations` codelense.

Notice how the 3 references are at the top of the lib.rs file in a comment.

**Comment by flodiebold** [comment]
I assume the 3 implementations are the three built-in derives (`Debug, PartialEq, Clone`), and we're not correctly mapping locations from macros for this.

**Comment by mikeyhew** [comment]
Yes, that's what it looks like. In this example, if you remove or add a built-in derive, it changes the number of implementations by one. `Serialize` and `Deserialize` from serde don't change the count though.

![Screen Shot 2019-12-16 at 3 00 31 PM](https://user-images.githubusercontent.com/6751033/70938834-fe884680-2014-11ea-9b0f-7958b3da57a8.png)

The "one implementation" shown above is from the `#[derive(Clone)]`.

**Comment by bjorn3** [comment]
@mikeyhew Proc macro's are not yet supported, so they don't generate implementations.
