### ISSUE TITLE
Documentation on Box<dyn Trait>

### ISSUE THREAD

**Issue by mominul** [rust-analyzer/rust-analyzer#2542]
Hovering on a function of a `Box<dyn Trait>` shows the documentation of the trait's function and its all implementations on the structs even there is no documentation available.

Example:
```rust
trait Animal {
    /// Eat
    fn eat(&self);
}

struct Cat;
struct Bat;

impl Animal for Cat {
    fn eat(&self) {}
}

impl Animal for Bat {
    fn eat(&self) {}
}

fn main() {
    let a: Box<dyn Animal> = Box::new(Cat {});

    a.eat();
}
```

Hovering on `a.e|at()` gives these hints:
![ra_bug_1](https://user-images.githubusercontent.com/9459891/70726298-15cee780-1d28-11ea-964e-02aa4aac4c6d.png)
Is this a intended behaviour?
On the contrary, RLS only gives the documentation of the trait function only.

**Comment by flodiebold** [comment]
No, it's not intended behavior -- multiple items showing up like this is a sign that we couldn't properly resolve the call and fell back to an index-based resolve. I'm actually not sure yet what the problem here is, there's nothing there that we obviously don't support.

**Comment by flodiebold** [comment]
Since this works fine both when we have a `Box<Cat>` and when we have a `&dyn Animal`, it seems there's something going wrong with the autoderef through Chalk. And actually, when I look at `*a`, that results in unknown, so there's definitely something going wrong there.

**Comment by flodiebold** [comment]
Btw, maybe we should mark index-based resolves as such, to make clearer when this is happening :)

**Comment by matklad** [comment]
I wonder if we should remove them completely from anything except goto definition itself: we resolve much more stuff correctly now, so they are less useful. I think index-based resolve for goto def might be useful in perpetuity though (like, if it seriously break your code, you'll get at least something working).  

@kjeremy, what do you think about removing index-based resolve from hover and friends?

**Comment by kjeremy** [comment]
@matklad Yes that sounds like a great idea.

**Comment by kjeremy** [comment]
Huh..... simply commenting out the `index_resolve` block on hover fails `hover_shows_fn_signature`. That's surprising to me.

**Comment by mominul** [comment]
I can confirm that this issue has been fixed! :tada: 
![ra-fixed](https://user-images.githubusercontent.com/9459891/79053517-dfff2880-7c5f-11ea-8cda-4dcfb02d96f2.png)

So, I am closing this issue. :smile: 
Thanks!
