### ISSUE TITLE
Implement Call Hierarchy

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2546]
Let's implement https://github.com/microsoft/vscode-languageserver-node/blob/dbaeumer/moreIntegrationTests/protocol/src/protocol.callHierarchy.proposed.ts#L1

**Comment by matklad** [comment]
I think this should build off the find usages.

**Comment by kjeremy** [comment]
As part of this is I would like to implement `TryConvWith` for `(FileId, RangeInfo<Vec<NavigationTarget>>)` but with an `Output` of `Vec<req::CallHierarchyItem>` which I have defined. However there's already an impl of the `TryConvWith` for `(FileId, RangeInfo<Vec<NavigationTarget>>)`.

**Comment by kjeremy** [comment]
I just made a `to_call_hierarchy_item` and moved on. I have the protocol part done and the prepare request seems to be working.

@matklad Yes find usages will work for the incoming calls. I think the outgoing calls will require traversing the function body and pulling out any function calls.
