### ISSUE TITLE
Find usages for struct "constructors"

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2549]
Given a type like 

```rust
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Path {
    pub kind: PathKind,
    pub segments: Vec<PathSegment>,
    pub generic_args: Vec<Option<Arc<GenericArgs>>>,
}
```

one of the most useful questions is "where `Path` is **constructed**"? That is, "find references", but also filtered by "is this a struct literal?". 

The right way to implement this is to add classification to find usages. That is, find usages should not only return a list of usages, but also a "kind" of usage: struct literal, impl, import, etc. That is, we should change `references: Vec<FileRange>,` to `references: Vec<Reference>,` where

```rust
struct Refrence {
  file_range: FileRange,
  kind: RefrenceKind,
}

enum ReferenceKind {
  Literal
}
```

This code is here: https://github.com/rust-analyzer/rust-analyzer/blob/16cf6bcf4b614a7a1a3a3f3659f7bb3df7cff086/crates/ra_ide/src/references.rs#L38

After that, we need to *somehow* express this via LSP UI. I believe it doesn't have a build-in feature for this, so I suggest the following hack:

* if `find_usages` is invoked exactly at the curly brace (or paren, for tuple structs) of a struct definition, the results should only include struct literals (Kotlin handles a similar problem this way).

**Comment by mikhail-m1** [comment]
Hey, I will look at it.

**Comment by mikhail-m1** [comment]
questions:
1.  Should a search be restricted in this case `Foo<|> {` or/and `Foo <|>{`? Right now `Foo <|>{` doesn’t work, so I would need to change it a little.
2. Do I need to add all references to ReferenceSearchResult and filter them later or just struct literals?
3. Is any way to find struct literals or I need to write a function? If so could you share any examples or recommendations?
4. What other items should be in ReferenceKind enum?

**Comment by matklad** [comment]
1. For `Foo<|> {`  we shouldn't restrict the search, as the cursor is on identifier. For `Foo <|>{` we should. For `Foo<|>{` we can go either way.
2. I think we should always search for  all references, and do filtering later. However, we should *classify* the references during search. That is, the filtering in the second step should be trivial
3. I think some manual code should be added. Specifically, [here](https://github.com/rust-analyzer/rust-analyzer/blob/08c6933104baca84fd4135a76cdc7daf60a0c631/crates/ra_ide/src/references.rs#L141) we can look at the parent of name ref and check if its a `RecordLiteral`. API of syntax trees is described [here](https://github.com/rust-analyzer/rust-analyzer/blob/08c6933104baca84fd4135a76cdc7daf60a0c631/crates/ra_syntax/src/lib.rs#L193).
4. I think it's fine to start with just `RecordLiteral`, and add other when we find a need for them!

**Comment by lnicola** [comment]
This seems to work now.

**Comment by matklad** [comment]
Does it work for tuple structs/enums?

**Comment by lnicola** [comment]
It works for tuple structs (you need to put the cursor before the `(`), but not enums.

**Comment by matklad** [comment]
Specific example from rust-analyzer:

![image](https://user-images.githubusercontent.com/1711539/96142093-f7b2b480-0f01-11eb-8d06-8a1a31b7b1a2.png)

https://github.com/rust-analyzer/rust-analyzer/blob/8090799aa2f2a83746780ebdd7837e0e280c2d2c/crates/ide_db/src/defs.rs#L80-L90

I want this feature so much, I am almost ready to implement it myself :sob:

**Comment by lnicola** [comment]
Are there still cases where this doesn't work?

**Comment by matklad** [comment]
yup, can't get it to work for a simple case. Searching brace doesn't return any referneces, searching name returns all references (not only constructors):


https://user-images.githubusercontent.com/1711539/102789660-b678ce00-43a4-11eb-959f-65e453852887.mp4

**Comment by lnicola** [comment]
CC @sasurau4 ^

**Comment by matklad** [comment]
Another case to test:

![image](https://user-images.githubusercontent.com/1711539/105488141-3f479a00-5cc2-11eb-8999-cf0550c657bd.png)
