### ISSUE TITLE
Build nightly artifacts

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2553]
We are not ready for proper releases yet, but probably can publish nightly builds. I think the best way to publish nightlies is action's [artifacts](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts). We should [schedule](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule) an artifact-producing job to run every day at 4am CET.

We should produce:

* windows build
* mac build
* linux build

Ideally, the binaries should be fully statically linked. I think it's possible on linux with musl, I don't know what are the options for windows and mac.

If anyone more experience with building cross-platform artifacts on actions wants to send a PR or just share pointers to templates we might copy-paste, that would be awesome!

**Comment by bjorn3** [comment]
On Windows and MacOS it is not possible to create statically linked executable's, as the syscall interface is unstable.

**Comment by edwin0cheng** [comment]
For Windows, we could use [`windows-latest` on github-vm](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners) and setting `RUST_FLAGS=-C target-feature=+crt-static` for static linking:

This is the DLL dependencies with RUST_FLAGS:


![with-static-crt](https://user-images.githubusercontent.com/11014119/70844416-bc77cd00-1e7b-11ea-8917-ee0aba99900f.png)

------------------------------------------------

This is the DLL dependencies **without RUST_FLAGS**:
![no-static-crt](https://user-images.githubusercontent.com/11014119/70844424-e03b1300-1e7b-11ea-9f33-900497008c7b.png)

**Comment by ice1000** [comment]
FYI here's an example github-action based artifactory:

https://github.com/owo-lang/narc-rs/blob/0c92e1499df55e1c340648440f36b33adb7cc75f/.github/workflows/rust.yml#L23-L39

To download the artifacts:

https://github.com/actions/upload-artifact#where-does-the-upload-go

**Comment by gilescope** [comment]
We are going to need windows builds so I'll fork and try out some stuff in github actions.
(I'm assuming I'm not going to mess anything up by running those actions?)
Right now it's building for linux but not putting the artifacts anywhere - is that about the current state?

**Comment by kiljacken** [comment]
In #2725 we've got the tests running on macOS and Windows as-well. It has yet to be merged though.

**Comment by gilescope** [comment]
Thanks @kiljacken for that PR. Last step is uploading the results? I can raise a PR for that (but more than happy if someone else wants to do it?)

For the typescript build do we just want to upload everything under the editors dir?
For the OS dependent builds is it just the ra_lsp_server executable that we need?

**Comment by kiljacken** [comment]
@gilescope For the VSCode extension/the typescript build the `ra-lsp-0.0.1.vsix` is the extension package that we might care about. For the OS dependent builds `ra_lsp_server` should be sufficient.

**Comment by gilescope** [comment]
Agreed, though I guess we should try not to be too vscode centric - we don't want to incur the wrath of vim. :-P
Ok will have a try at lunch to get a PR together

**Comment by gilescope** [comment]
So next step is for the extension to be able to download latest server if it doesn’t already have one running or the ra path set.

**Comment by matklad** [comment]
Yeah!

I imagine we need to have an "Update Server" action, which downloads the binary from the appropriate platform from the releases page, and puts it into `~/.cargo/bin` (or maybe in the extension data dir? Not sure which one is better). We also need to make sure that the serve isn't running while we are updating the binary, as windows can't swap a currently executing binary

**Comment by matklad** [comment]
Yeah, looks like python drops the server into the extensions folder, so we should do the same: https://github.com/microsoft/vscode-python/issues/3977

**Comment by matklad** [comment]
We somehow added weekly releases before nightly ones :D 

I'll open a separate issue for nightly releases, as we still want to have them
