### ISSUE TITLE
Extract highlighting tags to an enum

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2563]
We use strings to tag syntax-highlighted tokens: https://github.com/rust-analyzer/rust-analyzer/blob/d6223253b628b279f9ddae8f83f7173d01f6b32c/crates/ra_ide/src/syntax_highlighting.rs#L119

This is less than idea, because there's no single place that lists all the tags. We should fix it by either using an enum, or declaring all the tags as named constants (I lean towards the latter option).

**Comment by matklad** [comment]
cc @omerbenamram, as the person who last touched that code :)

**Comment by omerbenamram** [comment]
@matklad I'll extract those to constants then.

**Comment by ice1000** [comment]
Isn't this issue fixed?
