### ISSUE TITLE
PSA: disable the Rust (rls) extension to avoid duplicate hover output

### ISSUE THREAD

**Issue by mikeyhew** [rust-analyzer/rust-analyzer#2573]
I thought I'd report this issue just so it's there for people to find when they're having the same issue. If you have the Rust (rls) extension installed in VS Code alongside rust-analyzer, you will end up with duplicate hover results like the following:

![screenshot](https://user-images.githubusercontent.com/6751033/70937297-0eeaf200-2012-11ea-80ec-fb924e3e9f41.png)

This isn't a bug, you just need to disable the Rust (rls) extension. It would be good to mention that in the readme somewhere, maybe in a new section about common issues?

**Comment by davyzhang** [comment]
Some of the auto-complete information from ra is not as good as that is rls, I still need two of these to get useful hints.

**Comment by flodiebold** [comment]
Hi @davyzhang, please feel free to report cases where RLS gives better completions as a separate issue.

**Comment by matklad** [comment]
:+1:, having this in an issue tracker is a good idea, but let's close the issue as this is not something we can fix.
