### ISSUE TITLE
One core 100% cpu usage on osx when vscode not running

### ISSUE THREAD

**Issue by gilescope** [rust-analyzer/rust-analyzer#2576]
If you’ve not got any feedback from vscode then ideally there should be little to do. It’s keeping my lap warm for now but this won’t be a feature in the summer!

Needs to figure out how to do dormant better for all our batteries sakes.

**Comment by matklad** [comment]
I *think* this is the long-standing notify bug, I've switched the default to client-side watching on VS Code. https://github.com/rust-analyzer/rust-analyzer/pull/2578

**Comment by gilescope** [comment]
Thanks - that's indeed it. It was killing my batteries, - that's *much* better :-)
