### ISSUE TITLE
Cleanup instructions for vim

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2579]
See discussion in https://github.com/rust-analyzer/rust-analyzer/pull/2370#issuecomment-566283443

Yeah, I think ti's true that vim users are confused by a vast number of available vim client implementations. It would be cool if one adds a paragraph to this section which enumerates the available alternatives explicitely.

The relevant docs are here: https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user#vim-and-neovim

**Comment by oblitum** [comment]
> It would be cool if one adds a paragraph to this section which enumerates the available alternatives explicitely.

I forgot to add this additional paragraph, but, the way it's organized in the pull may render that unnecessary?
