### ISSUE TITLE
Wrong inference for shift operators

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#2602]
```rust
    let _x = 1u32 << 5u8;
```

`_x` gets inferred as `u8`. ~~Probably caused by https://github.com/rust-analyzer/rust-analyzer/pull/451/files#diff-bd22dd45f1f2ee115460eaa92ea6b1c8R555-R556.~~

**Comment by detrumi** [comment]
Currently `binary_op_return_ty` always uses the right-hand type as result type, but this is wrong for `<<`, which uses the left-hand type.

More generally, we should resolve the associated output type like [described here](https://github.com/rust-analyzer/rust-analyzer/blob/3263c7076613bf8c3c32bb2bd5be29f10eb0284c/crates/ra_hir_ty/src/infer/expr.rs#L387:L393).
