### ISSUE TITLE
Highlight interpolation & escape sequences?

### ISSUE THREAD

**Issue by ice1000** [rust-analyzer/rust-analyzer#2604]
Is there a plan for this?

I'm looking for sth like this:
![image](https://user-images.githubusercontent.com/16398479/71205276-13144b00-2270-11ea-8c94-411ee8fc334a.png)

Idk if it's available in intellij-rust yet but there's intellij-rust/intellij-rust#2256

**Comment by matklad** [comment]
Escape sequence highlighting can be implemented right now, it should be mostly straightforward. 

[Here](https://github.com/rust-analyzer/rust-analyzer/blob/08c6933104baca84fd4135a76cdc7daf60a0c631/crates/ra_ide/src/syntax_highlighting.rs#L103), we should tokenize the contents of the string with rustc_lexer. We currently [do this](https://github.com/rust-analyzer/rust-analyzer/blob/08c6933104baca84fd4135a76cdc7daf60a0c631/crates/ra_syntax/src/ast/tokens.rs#L128-L148) to extract the string value, this can be generalized to inform about all escapes in string. 

Highlighting of format arguments is tricky. We need to handle highlighting code inside macro at all first.

**Comment by slyngbaek** [comment]
Is this already implemented? My VS Code seems to highlight them:
![image](https://user-images.githubusercontent.com/1216902/77144884-423f8180-6a44-11ea-960c-fc220126928c.png)
