### ISSUE TITLE
Bright red highlighting of unsafe keyword is excessive

### ISSUE THREAD

**Issue by Farmadupe** [rust-analyzer/rust-analyzer#2605]
When Rainbow Highlighting is activated in vsc preferences, rust-analyzer performs its own syntax highlighting.

The unsafe keyword is highlighted in bright red.

![unsafe_red](https://user-images.githubusercontent.com/2056692/71214372-0bbf6280-22ad-11ea-8e8d-7b452fdf2e4b.png)

I think this is a little excessive (as it is even much brighter than the wiggly error underlines). I realize I can probably change this myself, but I wonder if a nicer default might be to highlight unsafe as a normal keyword?

**Comment by matklad** [comment]
I'm ok with picking a better default color here! I do feel strongly that, by default, unsafe should be colored more conspicuously than other keywords.

**Comment by Farmadupe** [comment]
fwiw, I slightly disagree that unsafe keyword should be more conspicuous  because I think the main purpose of syntax highlighting is to help you navigate your own code. I don't think it is necessary for the syntax highlighter to add any extra 'gravity' to the situation of writing code outside of rust's safety guarantees.  The keyword itself already does that.

Either way, for my part I would be happy as long as the highlighting as less excessive than it is now.

**Comment by p-avital** [comment]
I'm with @Farmadupe on that one, in general, I am against syntax coloring that might be mistaken, even just subconsciously, for error highlighting.

**Comment by gilescope** [comment]
Personally I love the red. I guess there's always going to be two camps on this one, but I think it's great as if I'm looking at someone else's code this always jumps out at me.

**Comment by matklad** [comment]
Actually, I think the issue is not applicable anymore, as we transitions to just using the theme's colors for highlighting. The scope name for `unsafe` is `keyword.other.unsafe`. All present text mate scopes are specified here: https://github.com/rust-analyzer/rust-analyzer/blob/8317efa19159092430c971c9f29e611e448951c3/editors/code/src/highlighting.ts#L222-L249
