### ISSUE TITLE
VSCode setting to specify path to Cargo.toml

### ISSUE THREAD

**Issue by oxalica** [rust-analyzer/rust-analyzer#2649]
Sometimes `Cargo.toml` is not in the workspace root, instead, inside some sub-directory.
Since the project contains non-rust code, it is not good idea to always create `Cargo.toml` workspace file in the root.

Is there any way to specify the directory or path to `Cargo.toml` processed by rust-analyzer?

**Comment by edwin0cheng** [comment]
> Is there any way to specify the directory or path to Cargo.toml processed by rust-analyzer?

If I understand correcly, there is still no way to do that: see #2533

**Comment by matklad** [comment]
Yeah, there's no such setting (yet), it should be not that hard to add.

**Comment by menoude** [comment]
@matklad do you know if this is on the roadmap? I can try to implement it if not (and if it happens to be simple). Sadly this is what keeps our team from using rust-analyzer!

**Comment by matklad** [comment]
Sure, a PR would be welcome!

Here's the current code for determining the set of projects to analyze: 

https://github.com/rust-analyzer/rust-analyzer/blob/61cb87e50629f510c8a1231102ba66ded524bec2/crates/rust-analyzer/src/bin/main.rs#L74-L82

**Comment by matklad** [comment]
Fixed in today's release:

```json
{
    "rust-analyzer.linkedProjects": [
        "/home/matklad/tmp/hello/Cargo.toml"
    ]
}
```

(you can link more than one project)

**Comment by 55Cancri** [comment]
@matklad do I add this setting in vscode's settings.json file? When I do, it says Unknown Configuration Setting.

**Comment by azzamsa** [comment]
> Fixed in today's release:
> 
> ```json
> {
>     "rust-analyzer.linkedProjects": [
>         "/home/matklad/tmp/hello/Cargo.toml"
>     ]
> }
> ```
> 
> (you can link more than one project)

How to achieve the same thing in Emacs? Other than using `rust-project.json`. I don't find it in the [manual](https://github.com/rust-analyzer/rust-analyzer/blob/d58a3a277a1778ec33e492e958b52869510c1239/docs/user/manual.adoc#L347)

**Comment by matklad** [comment]
@azzamsa tbh, I don't know how to pass settings to lang servers via lsp mode. I guess it should be documented somewhere here: https://emacs-lsp.github.io/lsp-mode/. 

A PR to rust-analyzer's manual clarifying this would help!

**Comment by flodiebold** [comment]
There are specific emacs defcustoms for most settings. Probably not for `linkedProjects` though (can't check, not at my computer), and I don't know if it makes sense to handle it that way since it would always have to be defined with dir-locals... Might be worth opening an issue about there.

**Comment by zqyzsj** [comment]
> 

Is this problem solved? I don't know how to specify the root of a non-standard cargo project in emacs.

**Comment by flodiebold** [comment]
That's why you should set it in `.dir-locals.el`, not globally :slightly_smiling_face:

**Comment by zqyzsj** [comment]
> 

Thanks @flodiebold . I'll try it.

**Comment by yhslai** [comment]
How to specify this in emacs? The above comments mentioned `lsp-rust-analyzer-linked-projects`, but what's the equivalent to `eglot`?

**Comment by marcospgp** [comment]
Checking in, is there a way to do this in 2024?

There is a similar option for Python in vscode with the "select python interpreter" command.

**Comment by ChayimFriedman2** [comment]
@marcospgp 

> Checking in, is there a way to do this in 2024?
> 
> There is a similar option for Python in vscode with the "select python interpreter" command.

Yes, the `rust-analyzer.linkedProjects` setting.
