### ISSUE TITLE
Should inlay hints follow the resolve pattern?

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2664]
Inlay hints take a while to resolve. Would it be worth following the LSP `resolve` pattern like rename and actions ?

**Comment by matklad** [comment]
Yeah, I've noticed this as well. I actually think that, first, we should just make the hints itself faster: I did a couple of easy optimizations already, but I still haven't figured out where exactly the time goes (there's some unaccounted-for chunk in profiles). 

After we do this ground-work optimizations, we should add an ability to ask for hints only at a certain view port, and not for the whole file.

**Comment by SomeoneToIgnore** [comment]
Should we close this in favor of https://github.com/rust-analyzer/rust-analyzer/issues/3394?

**Comment by kjeremy** [comment]
Yep! I thought I had made an issue for this. Haha.
