### ISSUE TITLE
No warnings shown in Problems Panel in VSCode (In server cargo watch)

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#2676]
It is very weird that the new `in server cargo watch` seems to not showing any warnings in the `Problems Panel` but it works for error.

**Comment by kiljacken** [comment]
Could you give an example of a warning that you'd expect to show up that currently doesn't? Things like unused import/variable show up just fine on my end

**Comment by edwin0cheng** [comment]
> Could you give an example of a warning that you'd expect to show up that currently doesn't? Things like unused import/variable show up just fine on my end

Even unused variable didn't show up in my end (Windows). But I see that warning when I run `cargo check --message-format=json` in terminal. 

It is more weird that suddenly even errors didn't shown up now while I try to reset the settings of "rust-analyzer.cargo-watch.enable".

**Comment by kiljacken** [comment]
Interesting, it must be doing something platform-incompatible with the paths.

Could you add a `dbg!()` around the clone [here](https://github.com/rust-analyzer/rust-analyzer/blob/523b4cbc602447b14202dd2520f84241bb07c4e2/crates/ra_cargo_watch/src/lib.rs#L269), and share what it looks like?

**Comment by kiljacken** [comment]
Ehh, maybe `eprintln!("{:?}", file_path);` is better on the line after. Output should go to VSCode output console.

**Comment by matklad** [comment]
@edwin0cheng as a sanity check, have you rebuild both the server and the clien?

**Comment by edwin0cheng** [comment]
@matklad `cargo clean` and removed all files in `editor/code/out` and `editor/code/node_modules` and still no ouptut in Problems panel :(

**Comment by edwin0cheng** [comment]
@kiljacken you are right, seem like the uri has subtle differenes in different places:

in https://github.com/rust-analyzer/rust-analyzer/blob/523b4cbc602447b14202dd2520f84241bb07c4e2/crates/ra_lsp_server/src/main_loop/handlers.rs#L860

`url` => "file:///d:/sandbox/temp/src-root/foo/src/main.rs"

in https://github.com/rust-analyzer/rust-analyzer/blob/523b4cbc602447b14202dd2520f84241bb07c4e2/crates/ra_cargo_watch/src/lib.rs#L269

`url` => "file:///D:/sandbox/temp/src-root/foo/src/main.rs"

Note that the D drive part, one is Upper case, One is Lower case.

**Comment by edwin0cheng** [comment]
More information : 

vscode uri will turn all windows drive letter to lower case: 

https://github.com/microsoft/vscode-uri/blob/95e03c06f87d38f25eda1ae3c343fe5b7eec3f52/src/index.ts#L1017

**Comment by matklad** [comment]
This sound eerily familiar: https://github.com/rust-analyzer/rust-analyzer/pull/2565

:unamused:

**Comment by kiljacken** [comment]
It's probably the exact same thing going on. We have a helper `url_from_path_with_drive_lowercasing` in ra_lsp_server, not sure if we want to transform there, or make it accesible without having to depend on ra_lsp_server

**Comment by matklad** [comment]
I'd just put the helper as a `pub fn` into the watch crate. Alternatively, and perhapse more appropriately, we can move all lsp things out of the watch crate. That way, the watch crate is lsp-agnostic, and just returns diagnostics in the format they are produced by `cargo check`. The transformation of those into `lsp-types`  can happen in the `conv` module.

**Comment by kiljacken** [comment]
@edwin0cheng Could you give this branch a try: https://github.com/kiljacken/rust-analyzer/tree/cargo-watch-file-name-casing

**Comment by edwin0cheng** [comment]
@kiljacken It works perfectly 👍
