### ISSUE TITLE
Visualize coercions with hover

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2677]
See: https://github.com/intellij-rust/intellij-rust/pull/4768

https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/Neat.20visualisation.20of.20coecions.20in.20ItelliJ

**Comment by flodiebold** [comment]
Bumping this because I think we have all the necessary information for this now, it just needs some code in the hover implementation. Might add some instructions later.

**Comment by Veykril** [comment]
I can do this, gonna touch some stuff up on hover anyways
