### ISSUE TITLE
Code: visibleRanges support

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#2682]
Split off #1294.

We should only highlight the visible range, not the whole file. See `onDidChangeTextEditorVisibleRanges` under https://code.visualstudio.com/api/references/vscode-api#window.

**Comment by bjorn3** [comment]
We shlould highlight a bit around the visible range to prevent issues when scrolling. Also what about the minimap?

**Comment by lnicola** [comment]
(╯°□°)╯︵ ┻━┻

**Comment by matklad** [comment]
Minimap should probably just use fast highlighter based purely on lexer. This should also follow the relevant developments in VS Code/LSP. Note, in particular, that the existing proposed extension focuses on incremental update for the whole file, which I think is exactly wrong, and that from-scratch update for the visible region of file is more important (but I haven't implemented either, so take this with a grain of salt).

**Comment by matklad** [comment]
obsoleted by semancit tokens
