### ISSUE TITLE
Iterator::map not recognized on Chars

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#2683]
![image](https://user-images.githubusercontent.com/308347/71561669-2dc19d80-2a82-11ea-9d3b-eeb65b5212ab.png)

![image](https://user-images.githubusercontent.com/308347/71561674-3914c900-2a82-11ea-95f9-519cb3f58ed4.png)

Possibly related: `Vec::iter` shows up as `{unknown}`, but `Vec::into_iter` works. `map` works on both (!).

![image](https://user-images.githubusercontent.com/308347/71561680-4df15c80-2a82-11ea-8b33-34b342b1296b.png)

EDIT: Actually no, `into_iter` doesn't give the type either.

**Comment by flodiebold** [comment]
`some_vec.into_iter()` doesn't work because of rust-lang/chalk#234, I'm pretty sure.

`vec![1, 2, 3].iter()` seems to be a macro expansion issue, because
```rust
        let x = vec![1, 2, 3];
        let x = x.iter();
```
actually works :thinking:

**Comment by flodiebold** [comment]
`Chars` is weird, since we detect the type, resolve methods from the `Iterator` impl like `next()`, but still don't show the `Iterator` extension methods :thinking:

**Comment by matklad** [comment]
Yeah, `str` is a builtin type, and so has to go through some shenanigans in name resolution. If anyone wants to look at it, see `BuiltinShadowMode` thing: https://github.com/rust-analyzer/rust-analyzer/blob/010d90202102e4e30ecd670e8500170247ef74a6/crates/ra_hir_def/src/nameres/path_resolution.rs#L104

**Comment by flodiebold** [comment]
I don't think it's clear that this is related to built-in shadowing -- the problem seems to be with the `impl Iterator for Chars` :confused:

**Comment by flodiebold** [comment]
The `vec![].iter()` macro expansion issue is now fixed.
