### ISSUE TITLE
`Vec!` is resolved as type

### ISSUE THREAD

**Issue by MikailBag** [rust-analyzer/rust-analyzer#2686]
Highlighting is incorrect:
![image](https://user-images.githubusercontent.com/11889433/71584143-7466d480-2b22-11ea-8b75-439455f2162c.png)

Documentation is shown for `Vec`.
Go to definition finds Vec definition, etc.
rust-analyzer: 823e9193

**Comment by kiljacken** [comment]
Well, `Vec` is the type, and `vec!` is the macro (note the casing), so it looks like "expected" behavior on otherwise erroneous code.

**Comment by MikailBag** [comment]
Yes, there is `Vec` in scope, but it can't be used as macro. So rust-analyzer should return error ("unknown macro Vec") instead of false-positive.

**Comment by kiljacken** [comment]
Rust-analyzer is still a work in progress, so many things that should be
reported as semantic errors are not implemented yet.

If you use the in-server cargo watch functionality you will get the error
you expect, when you save the file.

**Comment by matklad** [comment]
Yeah, we don't display errors for name resolution at the moment, because there are some false positives. So this is just an instance of a bigger high-level problem, and doesn't need to be tracked as a separate issue.
