### ISSUE TITLE
Does cargo-watch.arguments work in VSCode?

### ISSUE THREAD

**Issue by ondrowan** [rust-analyzer/rust-analyzer#2689]
I have a cargo workspace with multiple crates. For convenience I also have `src` folder in the root directory so I can run `cargo run` for some common tasks. Because of this, I need to run `cargo watch -x "clippy --all"` instead of `cargo watch -x clippy` in VSCode extension. This works well if I try it in terminal, but setting this in RA extension doesn't seem to do anything:

``` 
  "rust-analyzer.cargo-watch.command": "clippy",
  "rust-analyzer.cargo-watch.arguments": [
    "--all"
  ],
```

Clippy is still running only against the crate in `src` folder.

I'm not sure what command is actually running on save and how to debug it in VSCode. Any help would be appreciated.

PS: There's a typo in `editors/code/src/server.ts`. `cargoWatchArgumets` instead of `cargoWatchArguments`. This doesn't seem to have any effect though.

**Comment by kiljacken** [comment]
It was the same place as the typo, the server side variable is just `cargoWatchArgs`. PR is up.

**Comment by ondrowan** [comment]
@kiljacken Wooo, thank was super quick! Thank you!
