### ISSUE TITLE
Prototype validators API

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#27]
Implement a tree visitor which can make additional "syntax-like" checks on the tokens and tree produced by the parser. 

- [] tree visitor
- [] error builder
- [] testing infrastructure

**Comment by aochagavia** [comment]
Is there anything like this already in place? I am asking because the issue is old and sometimes changes are introduced without referring to the issue.

**Comment by matklad** [comment]
Nothing is done yet, though we still need to implement this API.

We have `error` method here, which returns a `Vec<SyntaxError>` precisely to allow to compute errors on the fly:

https://github.com/rust-analyzer/rust-analyzer/blob/bc4de7128f474f75a9eff6591923657025099b74/crates/ra_syntax/src/lib.rs#L98

So, what we need is to add a private `fn validate(file: &File) -> Vec<SyntaxError>` method, and append its results to the errors from the parser. 

Here is the subset of things which should be checked by validate:

- string and char literals have closing quote
- char literals are one symbol long
- `/*` comments have a closing `*/`
- escapes in strings are valid
- doc comments are attached to nodes https://github.com/rust-analyzer/rust-analyzer/issues/166

**Comment by aochagavia** [comment]
Superseded by #223
