### ISSUE TITLE
[server side cargo watch] Warnings only shown for open files

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#2707]

**Comment by kiljacken** [comment]
Is this a request for limiting warning output, or a statement that it currently doesn't show the errors in a way you'd expect?

**Comment by bjorn3** [comment]
Warnings are currently only shown for open files, while I expect it for all files.

**Comment by kiljacken** [comment]
Interesting. What editor do you use? It might be an issue of editor support as this works on my VSCode setup.

**Comment by bjorn3** [comment]
I use VSCode too.

**Comment by kiljacken** [comment]
Interesting. It works on my end: 
![image](https://user-images.githubusercontent.com/209321/71839346-3ede6000-30bb-11ea-85c6-c31b5cc156e3.png)

Anything in the "Rust Analyzer Language Server" output log?

**Comment by bjorn3** [comment]
Can't check for a few days.

**Comment by bjorn3** [comment]
Several other people have reported the same issue.

**Comment by kiljacken** [comment]
Just to get some more variables out on the table: What OS are you using?

**Comment by bjorn3** [comment]
This was on macOS.

**Comment by kiljacken** [comment]
I've added some extra output over on the `watch-debug` branch of [my fork](https://github.com/kiljacken/rust-analyzer/tree/watch-debug). Once you get the opportunity, would you mind giving that a go and sharing the text from the Output tab from "Rust Analyzer Language Server".

**Comment by bjorn3** [comment]
It does show warnings for closed files now.

**Comment by kiljacken** [comment]
Only the debug branch or master as well? If it works on the debug branch
and not master we've got a nasty heisenbug.

**Comment by bjorn3** [comment]
Master at 1327aed7f6289043091aa9179282030c6f13ddbe. This is an older version, but definitely not older than the version I had this problem with.

**Comment by kiljacken** [comment]
Sorry, I'm having trouble following you. Is what you're saying that: You used to have the issue, but it's working now?

**Comment by bjorn3** [comment]
Yes
