### ISSUE TITLE
Find all references is inconsistent on fndef vs call

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2708]
```rust
fn callee() {}
fn caller() {
    call<|>ee();
}
```

Returns two references: `fn callee()` and `callee();`.

```rust
fn call<|>ee() {}
fn caller() {
    callee();
}
```

Only returns `fn callee() {}`

**Comment by kjeremy** [comment]
Actually I think this is a display (vscode?) thing.

**Comment by kjeremy** [comment]
In the following case:

```rust
    fn caller1() {
        caller2();
    }

    fn call<|>er2() {
        caller3();
    }

    fn caller3() {

    }
```

Find references fails to find the call site in `caller1`. This is also affecting call hierarchy.

**Comment by kjeremy** [comment]
Ok weird... my test passes:

```rust
    #[test]
    fn test_find_all_refs_fndef() {
        let code = r#"
        fn call<|>ee() {}
        fn caller() {
            callee();
        }"#;

        let refs = get_all_refs(code);
        eprintln!("refs: {:#?}", refs);
        assert_eq!(refs.len(), 2);
    }
```

That refs printout gives me the correct answer:

```
refs: ReferenceSearchResult {
    declaration: NavigationTarget {
        file_id: FileId(
            1,
        ),
        name: "callee",
        kind: FN_DEF,
        full_range: [9; 23),
        focus_range: Some(
            [12; 18),
        ),
        container_name: None,
        description: Some(
            "fn callee()",
        ),
        docs: None,
    },
    references: [
        FileRange {
            file_id: FileId(
                1,
            ),
            range: [58; 64),
        },
    ],
}
```

However a printout right after https://github.com/rust-analyzer/rust-analyzer/blob/dc48f89581843248660ceb755bb20469ab6ac0c9/crates/ra_lsp_server/src/main_loop/handlers.rs#L526-L530 shows no references.

**Comment by matklad** [comment]
We should ensure that internally we always return both the definition and the list of usages, and don't mix the two. For the VS Code level UI, we should do whatever TypeScript does.

**Comment by kjeremy** [comment]
My plan is to rewrite the tests for `find_all_refs` to do string compares like we do for nav targets and the pending call hierarchy PR.
