### ISSUE TITLE
Prolonged high CPU usage

### ISSUE THREAD

**Issue by jminer** [rust-analyzer/rust-analyzer#2717]
I'm using rust-analyzer with this project at the moment:

https://github.com/jminer/zaffre

and I'm seeing ra_lsp_server maxing out two or more cores on my machine all the time. For example, I just opened up the folder in VS Code, and in vk_util.rs, I did Go to Definition on `ImageLayout` near the end of the file. After that, I switched from VS Code to another program, but ra is keeping two cores maxed out (it's currently been 10 minutes and seems to be indefinite). I wonder if the CPU usage might be related to Ash, as it contains a large 60,000 line generated file (vk.rs) with the Vulkan API.

I'm using the newest rust-analyzer d5a1a5e with default settings and rust-i686-pc-windows-msvc on Windows 10 64-bit. Zaffre probably only builds on Windows at the moment. I have seen ra max out all four cores on my machine for hours when I left VS Code open, but that was with a version of ra from Dec 21 (before I updated today).

**Comment by gilescope** [comment]
try switching to client watching if it's not already - that solved it for me.

**Comment by matklad** [comment]
It would be useful to get a stack trace of rust-analyzer spinning on the CPU.

**Comment by jminer** [comment]
@gilescope I'm using client watching as far as I know. It is the default now, and I haven't changed it.

I recorded a trace with VS Code just sitting open in the background, and I hadn't used it in over 15 minutes. It looks like it is 25 seconds long. I think one thread used 15.7s of CPU time and the other 15.4s during the trace. Here are a couple of call stacks on thread 1:

![thread1-call-stack1](https://user-images.githubusercontent.com/824671/71877020-cd6bd500-30ed-11ea-9e4a-4d56b6401ca5.png)

![thread1-call-stack2](https://user-images.githubusercontent.com/824671/71877031-d066c580-30ed-11ea-945e-53781a5b779b.png)

And here are a couple on thread 2:

![thread2-call-stack1](https://user-images.githubusercontent.com/824671/71877045-d8266a00-30ed-11ea-9f83-6e1e40952b2b.png)

![thread2-call-stack2](https://user-images.githubusercontent.com/824671/71877052-dbb9f100-30ed-11ea-9025-f05bd1057a9d.png)

Are these helpful any?

**Comment by bjorn3** [comment]
@jminer Are you still getting this issue?

**Comment by lnicola** [comment]
I can't seem to reproduce this, but note that `vk.rs` is a 60 600 LOC file.

**Comment by jminer** [comment]
I haven't been working on that project for a while, but I just tried it with the current rust-analyzer and can't reproduce the issue. I can open the project and use go-to-def and rust-analyzer goes to zero CPU after a short time. It must have been fixed at some point.

Thinking back, rust-analyzer has improved a lot in many ways since I opened this issue. Thanks everyone working on it!
