### ISSUE TITLE
snap tests failing on windows

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2720]
> test conv::test::snap_rustc_mismatched_type ... FAILED
> test conv::test::snap_clippy_pass_by_ref ... FAILED
> test conv::test::snap_rustc_incompatible_type_for_trait ... FAILED
> test conv::test::snap_macro_compiler_error ... FAILED
> test conv::test::snap_rustc_unused_variable ... FAILED
> test conv::test::snap_handles_macro_location ... FAILED
> test conv::test::snap_rustc_wrong_number_of_parameters ... FAILED
> 
> failures:
> 
> ---- conv::test::snap_rustc_mismatched_type stdout ----
> thread 'conv::test::snap_rustc_mismatched_type' panicked at 'called `Result::unwrap()` on an `Err` value: "can\'t convert path to url: /test/runtime/compiler_support.rs"', src\libcore\result.rs:1165:5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> 
> ---- conv::test::snap_clippy_pass_by_ref stdout ----
> thread 'conv::test::snap_clippy_pass_by_ref' panicked at 'called `Result::unwrap()` on an `Err` value: "can\'t convert path to url: /test/compiler/mir/tagset.rs"', src\libcore\result.rs:1165:5
> 
> ---- conv::test::snap_rustc_incompatible_type_for_trait stdout ----
> thread 'conv::test::snap_rustc_incompatible_type_for_trait' panicked at 'called `Result::unwrap()` on an `Err` value: "can\'t convert path to url: /test/compiler/ty/list_iter.rs"', src\libcore\result.rs:1165:5
> 
> ---- conv::test::snap_macro_compiler_error stdout ----
> thread 'conv::test::snap_macro_compiler_error' panicked at 'called `Result::unwrap()` on an `Err` value: "can\'t convert path to url: /test/crates/ra_hir_def/src/data.rs"', src\libcore\result.rs:1165:5
> 
> ---- conv::test::snap_rustc_unused_variable stdout ----
> thread 'conv::test::snap_rustc_unused_variable' panicked at 'called `Result::unwrap()` on an `Err` value: "can\'t convert path to url: /test/driver/subcommand/repl.rs"', src\libcore\result.rs:1165:5
> 
> ---- conv::test::snap_handles_macro_location stdout ----
> thread 'conv::test::snap_handles_macro_location' panicked at 'called `Result::unwrap()` on an `Err` value: "can\'t convert path to url: /test/src/main.rs"', src\libcore\result.rs:1165:5
> 
> ---- conv::test::snap_rustc_wrong_number_of_parameters stdout ----
> thread 'conv::test::snap_rustc_wrong_number_of_parameters' panicked at 'called `Result::unwrap()` on an `Err` value: "can\'t convert path to url: /test/compiler/ty/select.rs"', src\libcore\result.rs:1165:5
> 
> 
> failures:
>     conv::test::snap_clippy_pass_by_ref
>     conv::test::snap_handles_macro_location
>     conv::test::snap_macro_compiler_error
>     conv::test::snap_rustc_incompatible_type_for_trait
>     conv::test::snap_rustc_mismatched_type
>     conv::test::snap_rustc_unused_variable
>     conv::test::snap_rustc_wrong_number_of_parameters
> 
> test result: FAILED. 2 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out
> 
> error: test failed, to rerun pass '-p ra_cargo_watch --lib'
>

**Comment by kiljacken** [comment]
I have a hunch what might be going on but no windows machine to test on. Give me 5 and I'll have a branch up with a possible fix.

**Comment by matklad** [comment]
FWIW, with actions it should be easy to add windows to CI... Let's just do
this, if it doesn't increase CI times?

**Comment by kiljacken** [comment]
Hmm this might be a little more hairy than I thought, as `Url::from_file_path` validates that the path is valid for the current platform, so because the example file locations in the cargo output is using unix style paths it will always fail on Windows.
I think, the only great way to fix this while keeping the value of the tests, is to forge the Url's returned from `map_span_to_location_naive` when running on `#[cfg(test)]`. Any other thoughts/suggestions?

@matklad Sounds like a great idea.

I've got a proposed fix open over on #2722
