### ISSUE TITLE
Cargo watch and clippy arguments

### ISSUE THREAD

**Issue by jonathandturner** [rust-analyzer/rust-analyzer#2721]
I'm trying to pass some arguments to clippy.  I notice that this works:

![Screenshot from 2020-01-02 10-56-35](https://user-images.githubusercontent.com/547158/71646505-95ac0880-2d4e-11ea-9a0e-c37331b75337.png)

Where I have: `clippy --all --features=stable`

But, if I try to pass an argument to clippy, it doesn't seem to work:

`clippy --all --features=stable -- -D clippy::option_unwrap_used`

Is there a way to pass arguments to clippy from inside of ra?

**Comment by kiljacken** [comment]
You seem to be running an older version of rust-analyzer and the VSCode extension. You should probably start out by updating :)

The "command" path is only for the `check` vs `clippy` part and the following "arguments" config is where any additional arguments should go. Hope that helps.

**Comment by jonathandturner** [comment]
@kiljacken - I tried the latest rust-analyzer, but I was having trouble with it completing a check. It would hang, and keep the project locked so I couldn't build it manually. If I can get some time, I'll try to file a proper issue.

**Comment by kiljacken** [comment]
In that case, if you want to run a build, you can just re-save the file which restarts the cargo check process which should release the lock for your build to run. It's an inherent issue with depending on cargo check for diagnostics, sadly.

**Comment by matklad** [comment]
>It's an inherent issue with depending on cargo check for diagnostics, sadly.

A (bad) work-around is to set custom target directory for `cargo check`.

**Comment by matklad** [comment]
There's now `rust-analyzer.checkOnSave.overrideCommand` to completely override the command.
