### ISSUE TITLE
[VSCode] - Change bindings for Rust Analyzer: Run

### ISSUE THREAD

**Issue by jasonwilliams** [rust-analyzer/rust-analyzer#2733]
It's not usually good practise to overload common key bindings.
`ctrl + r` is regularly used to change project (File: Open Recent).

Is it possible to change `rust-analyzer.run` to use a different key binding? 
Something less common or unused?

https://github.com/rust-analyzer/rust-analyzer/blob/e4d217074d1f2c922cf8c5a247ca05fa06b0b7ed/editors/code/package.json#L136-L140

**Comment by matklad** [comment]
Yeah, stumping over build-in bindings is pretty impolite. 

What are the guidelines for extension keybindings? Is there a shortcut "namespace" which is considered ok to be occupied by extensions?

I am also fine with just removing this keybinding by default, but I think this is one of the best productivity booster, so having *some* default and nudging the user into trying it feels a right thing to do.

**Comment by jasonwilliams** [comment]
> What are the guidelines for extension keybindings? Is there a shortcut "namespace" which is considered ok to be occupied by extensions?

Thats a good question, im not sure but can find out

**Comment by p-avital** [comment]
Maybe a good compromise would be overriding the default Run action (`F5` on many platforms, I'm not sure if we can have different defaults for Macs on which I believe the default is different) ?
Or using a variant on it, like `Shift/Alt + F5` ?

**Comment by jasonwilliams** [comment]
> What are the guidelines for extension keybindings? Is there a shortcut "namespace" which is considered ok to be occupied by extensions?

Ive looked around i don't think such a thing exists, it seems like most other keybindings are fine except for this one. @matklad are you happy for a PR to remove this keybinding with users adding it back when they need it?

**Comment by matklad** [comment]
yes. We also should update features.md, I think it mentions the default
keybinding
