### ISSUE TITLE
Handle `use Trait as _` properly

### ISSUE THREAD

**Issue by kiljacken** [rust-analyzer/rust-analyzer#2736]
We currently don't handle the `use Trait as _` pattern properly. The following example illustrates the issue:
```rust
use a::Bar as _;
use b::Bar;

pub struct Foo;

fn main() {
    let query = <Bar<Foo>>::query();
}

mod a {
    pub trait Bar {}
}

mod b {
    pub struct Bar<T>(T);

    impl<T> Bar<T> {
        pub fn query() -> usize {
            0
        }
    }
}

```
Rust-analyzer somehow resolves `Bar` in main to `a::Bar` even though the use should discard the name for resolution.

The way this is currently handled in rust-analyzer is that use-items with an alias that is not a `NAME` token will be treated just as if they had no alias. Ideally the use item should be marked in a way where it can be used for method resolution, but not for path resolution.

**Comment by flodiebold** [comment]
Huh. Do we even handle `use Trait as _`? :thinking:

**Comment by kiljacken** [comment]
That seems to be it. We only handle the alias being a `NAME` token, so for cases with underscore they are treated as if they have no alias. That would explain why we are resolving to the wrong item.

**Comment by kiljacken** [comment]
Updated issue text with a better example, and new understanding of the issue.

**Comment by matklad** [comment]
The fix is to add

```rust
unnamed_traits: FxHashSet<TraitId>,
```

here

https://github.com/rust-analyzer/rust-analyzer/blob/010d90202102e4e30ecd670e8500170247ef74a6/crates/ra_hir_def/src/item_scope.rs#L14-L16

and then make sure it is populated accordingly.

**Comment by flodiebold** [comment]
I think it will need to be a `HashMap<TraitId, Visibility>` to handle visibility correctly :slightly_smiling_face: 

Also, to actually use the trait imports, they need to be added to `traits`:
https://github.com/rust-analyzer/rust-analyzer/blob/010d90202102e4e30ecd670e8500170247ef74a6/crates/ra_hir_def/src/item_scope.rs#L107

**Comment by matklad** [comment]
:fearful: how can visibility affect `pub use Foo as _` ? Do glob imports import `_` names, but only if they are appropriately `pub`?

**Comment by kiljacken** [comment]
That seems to be the case: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=256aa48283537c84a5b21da9401a3fc4

**Comment by flodiebold** [comment]
Glob imports do import unnamed traits, yeah (the original issue was such a case, with a 'prelude' module that included unnamed traits) - and since it does that, it would be surprising if it didn't take visibility into account...

**Comment by zombiefungus** [comment]
I would like to work on this
