### ISSUE TITLE
Not all MacroCalls show up as a file symbol

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2774]
Macros like `match_ast!` https://github.com/rust-analyzer/rust-analyzer/blob/d9d99369b2765eaef7f49cd519990769191c3381/crates/ra_syntax/src/lib.rs#L178-L188 do not show up in the outline view in vscode. This is because they are annotated with `macro_export` which fails the following check:

https://github.com/rust-analyzer/rust-analyzer/blob/360f6b7bb32d6280ed787075c4a54f4e5b46fcb6/crates/ra_ide/src/display/structure.rs#L155

In addition when they do show up they are marked as variables. I'm not quite sure what they should show up as (functions?) but the conversion needs to happen here: https://github.com/rust-analyzer/rust-analyzer/blob/2e66bed78296d12f1127ca8cd7cdeafc6c9b78c1/crates/ra_lsp_server/src/conv.rs#L51

**Comment by kjeremy** [comment]
I think this would be a good first issue.

**Comment by ruabmbua** [comment]
Seems like doc comments make this check fail too.
