### ISSUE TITLE
caching problems?

### ISSUE THREAD

**Issue by MarkSwanson** [rust-analyzer/rust-analyzer#2776]
Problem: rust-analyzer seems to take a long time and many uses to get fast.

Reproduce against a new small rust library:
1. vi src/lib.rs
2. wait 30 seconds for ra_lsp-server
3. 'gd' String  -> takes 30 seconds
4. :bd -> buffer delete to get back to src/lib.rs
5. 'gd' String -> takes 15 seconds
6. :bd
7. 'gd' String -> takes 5 seconds
...
5 seconds, 5 seconds, 

After that, 'gd' String is instant.

I sure am grateful for rust-analyzer, but I suspect some caching isn't quite right.
On a slightly larger project it takes 90 seconds to start and it never gets to 'instant speed' - it goes down to about 10 seconds. Perhaps I didn't have enough patience to repeat 'gd' ?

Ubuntu 18, Ryzen 2700, 16GiB, nvme.

If you're trying to save memory by only caching things that you see > n times - please offer an option to just always cache everything :-) I'd happily allocate 8 GiB or more to have a nearly instant rust-analyzer.

Thanks!

**Comment by matklad** [comment]
rust-analyzer doesn't persist anything to disk yet, so the first usage after startup is unfortunately expected to be slow. 

However, after the crate is processed for the first time, subsequent actions after modifications should be instant, modulo bugs.If this doesn't happen for a particular project, it would be lovely to get a reproducible example!

**Comment by MarkSwanson** [comment]
Would you like a minimal neovim or vim config as well?
(maybe you would be testing outside of an editor and wouldn't need them?)

**Comment by matklad** [comment]
It won't hurt, yeah, but I might be able to repro with just vscode?

**Comment by MarkSwanson** [comment]
Ok, the README explains how I did some testing.
https://github.com/MarkSwanson/ratest1

Maybe helpful:  removing wgpu from Cargo.toml speeds things up.

**Comment by MarkSwanson** [comment]
Alright, I've loaded up ratest1 into VSCode.
After a few minutes of playing with VSCode and rust-analyzer I can only say:
FANTASTIC JOB! I'm blown away! I may actually drop vim and switch to VSCode.

Fwiw I spent many hours with different version of vim, neovim, different LSP implementations (editor and server). Only rust-analyzer in VSCode works fast and correct for me.

The only issue I have is that 'cargo  check' warnings do not show up in VSCode. I'll investigate more and open another ticket if I can't solve it.

This issue can be closed - running rust-analyzer in VSCode shows that rust-analyzer is obviously working great. Thanks again for rust-analyzer.

**Comment by lnicola** [comment]
> The only issue I have is that 'cargo check' warnings do not show up in VSCode.

Sounds like #2707.

**Comment by matklad** [comment]
Interesting... Let me cc @norcalli  and @oblitum in case they would find the vim side of this interesting. TL;DR: rust-analyzer can have huge latencies in Vim, but not in VS Code? Not sure what's the problem here, it might very well be some bug on our side.

**Comment by oblitum** [comment]
I think @MarkSwanson is the same user that was having myriad of "software problems" from all sides on coc.nvim channel? And for which I simply suggested VSCode as there was a need for GUI client, etc.

Seriously I just think it's a case there's some shooting yourself in the foot somewhere. I never experienced latency problems with vim/neovim except for the already expected to exist in all editors, it shouldn't be different from VSCode.

**Comment by MarkSwanson** [comment]
I've never participated on the coc.nvim channel.

**Comment by oblitum** [comment]
> I've never participated on the coc.nvim channel.

Well, okay. As a NeoVim user, I simply can't reproduce the issue. go-to-definition is instant after rust-analyzer does its initial load. I think the issue can potentially be editor misconfiguration, as if you don't take care of what you run with autocommands on file load, file loading can get stuck loading.

**Comment by oblitum** [comment]
Also sadly I can't try the provided test as it requires unstable rust, and I just have stable available.

**Comment by oblitum** [comment]
> Also sadly I can't try the provided test as it requires unstable rust, and I just have stable available.

Looks like the tests still work on stable, this is my screencast: 
[screencast.zip](https://github.com/rust-analyzer/rust-analyzer/files/4046256/screencast.zip)
