### ISSUE TITLE
Missing structure fields: - warnings

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#2799]
Not sure how to reproduce, but my code looks like this:

```rust
use std::collections::VecDeque;
use std::fmt;
use thiserror::Error;

use super::{Locatable, Location};
```

Everything from `use std::fmt;` until `use super::{Locatable, Location};` is highlighted in red with the message from the title. I'm not sure what it's trying to tell me, `cargo check` thinks it's fine.

**Comment by Amanieu** [comment]
I'm getting a similar error on `intrusive-collections`.

Steps to reproduce:
- git clone https://github.com/Amanieu/intrusive-rs.git
- Open in vscode
- Open src/linked_list.rs

It will show the following errors, but only if the linked_list.rs file is open:
```
{
	"resource": "/home/amanieu/code/intrusive/src/linked_list.rs",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Missing structure fields:\n- link1\n- link2\n",
	"source": "rust-analyzer",
	"startLineNumber": 1366,
	"startColumn": 21,
	"endLineNumber": 1369,
	"endColumn": 10
}
{
	"resource": "/home/amanieu/code/intrusive/src/linked_list.rs",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "no such field",
	"source": "rust-analyzer",
	"startLineNumber": 1367,
	"startColumn": 13,
	"endLineNumber": 1367,
	"endColumn": 30
}
```
[linked_list.rs](https://github.com/Amanieu/intrusive-rs/blob/master/src/linked_list.rs)

**Comment by kiljacken** [comment]
@jyn514 The best way to help is try to remove as much unrelated code and push a test case that reproduces the issue as a seperate repostory, that way we can debug locally :)

@Amanieu We appear to be resolving the wrong Obj in your case, I'll split it off into another issue and investigate further :)

**Comment by killercup** [comment]
Seeing that issue too right now, will try to make a repro-repo.

FTR, it looks liek this here:

<img width="543" alt="Bildschirmfoto 2020-01-27 um 16 50 10" src="https://user-images.githubusercontent.com/20063/73189717-28a94a00-4125-11ea-80a7-777299156d48.png">

<img width="497" alt="Bildschirmfoto 2020-01-27 um 16 51 11" src="https://user-images.githubusercontent.com/20063/73189776-41196480-4125-11ea-8bec-5ba64a78c0a7.png">

**Comment by killercup** [comment]
Alright, `cargo new ra_missing_struct_fields_wrong_spans` and paste this into `main.rs`:

```rust
fn some() {}
fn items() {}
fn here() {}

fn main() {
    let _x = vec![
        Foo {
            a: 42,
        }
    ];
}

pub struct Foo {
    pub a: i32,
    pub b: i32,
}
```

This highlights these spans on my machine with a build from master right now:

<img width="243" alt="Bildschirmfoto 2020-01-27 um 17 04 44" src="https://user-images.githubusercontent.com/20063/73191024-247e2c00-4127-11ea-8152-608f6746984c.png">

It seems to me like the span offset is releative the somewhere inside of the macro but rendered as absolute in the file?

**Comment by killercup** [comment]
I started working on this FYI but haven yet fixed it.
