### ISSUE TITLE
Publish binary atifacts as GitHub releases

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2802]
We have a workflow for building artifacts: https://github.com/rust-analyzer/rust-analyzer/blob/master/.github/workflows/release.yaml

Now we need to publish those artifacts as a GitHub release.

I think we'll need this action for this: https://github.com/actions/upload-release-asset

**Comment by gilescope** [comment]
I'm guessing the follow up two issues to this will be:

- have the TS extension be able to download the appropriate server package.
- publish the TS extension to the VS code marketplace

(We can look at how codelldb does it for the first item.)

I'm happy doing a PR tomorrow morning for the release action unless anyone's going to beat me to it?

**Comment by yoshuawuyts** [comment]
> publish the TS extension to the VS code marketplace

Related issue: https://github.com/rust-analyzer/rust-analyzer/issues/2013

**Comment by matklad** [comment]
Yeah, I guess we can actually close this!

The next steps would be publishing the extension, and addition the ability to download/upgrade binaries from the editor itself. 

We also should probably review various security-related things before that, I don't feel *super* comfortable just pushing binaries to the Internet.
