### ISSUE TITLE
'3 implementations' but there is only 1

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#2805]
![bad annotation](https://user-images.githubusercontent.com/23638587/72214446-12b64b00-34d0-11ea-9c2a-baa2d22a4e24.png)

This is highlighting some imports as an implementation. I'm not sure where it gets number 3.

**Comment by edwin0cheng** [comment]
My wild guess is, it is coming from the builtin derives (Copy,Clone)  and we didn't handle it to ignore/show in implementations view ?

**Comment by SomeoneToIgnore** [comment]
That is 100% right guess, here's the related issue: https://github.com/rust-analyzer/rust-analyzer/issues/2531

So this one can be clossed, I think.

**Comment by SomeoneToIgnore** [comment]
That is 100% right guess, here's the related issue: https://github.com/rust-analyzer/rust-analyzer/issues/2531

So this one can be clossed, I think.
