### ISSUE TITLE
Add // on ENTER when editing comment

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#2811]
I had this feature in RLS and I really liked it: When I was editing a comment and hit ENTER, it would insert a comment start on the next line.

In RLS:
```rust
// I'm documenting a function and it looks like this:
// fn f() {
```
_hit enter_
```rust
// I'm documenting a function and it looks like this:
// fn f() {
// }
```

It should also respect the type of comment i.e. `///` or `//` or `//!`.

**Comment by edwin0cheng** [comment]
We already had this feature, I think you disabed `enhanced typing`, right ?

**Comment by jyn514** [comment]
Ahh, that's right. I turned it off because it conflicted with vim :/ Is there a plan to support both vim keybindings and enhanced typing?

**Comment by lnicola** [comment]
You can make it work: https://github.com/rust-analyzer/rust-analyzer/issues/4214#issue-609481879.
