### ISSUE TITLE
Thread priorities on Windows

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2835]
So looks like we are hitting some thread priorities problems on windows. Specifically, we run `cargo check` process "in the background", which, in theory, should not block our main loop from processing requests. 

However, it seems like `cargo check` manages to monopolize the CPU, preventing important sync handlers from running: https://github.com/rust-analyzer/rust-analyzer/pull/2825#issuecomment-573988121

I guess the crude fix for this would be to mark `cargo check` process group as low priority. If this is a correct fix, maybe it should even be done in Cargo?

*However*, I would expect windows thread scheduler to be fair, and so I can't actually explain *why* blocking happens here at the first place. Ideally, we should dig into this before rushing through with the fix. I think there might be some bug in how we arrange `cargo check` (like, maybe we really just block on it's output somewhere?) or there indeed might be some subtle OS-level effect.

I ... don't know anything about this part of windows API.

**Comment by matklad** [comment]
We need to revert https://github.com/rust-analyzer/rust-analyzer/pull/2826 after we fix this.

**Comment by matklad** [comment]
While we are at it, I guess we can also speed up the test a bit, by making sure we cancel pending work after typing is done?

**Comment by Speedy37** [comment]
Windows user here. 

On high core count/high load the scheduler is quite garbage. I've to use [processlasso](https://bitsum.com/) to keep things responsive (it automatically lower some process priority, i.e. rustc for me :)).
This problem is not related to rust-analyser to me, it also occur with any heavily threaded build process (rustc, cmake, ...).

**Comment by wycats** [comment]
Sometime soon after this PR, rust-analyzer became useless to me. I think 196b374eb might have been a mistake :wink:

**Comment by matklad** [comment]
I believe windows testing was introduced after the original regression, so it was unfair to block unrelated pr on windows build occasionally failing. The current work around is to disable cargo check altogether, or to revert to the version of rust-analyzer which still has cargo check implemented on the client side.

This will be the next bug I’ll look into once I have a large enough time chunk to actually setup windows dev environment :)

**Comment by matklad** [comment]
Investigating it right now.

Results so far:

* I am unable to reproduce user-visible slowdowns
* I am able to reproduce slowness in "diagnostics don't block typing" tests if I use 
    ```rust
    unsafe {
        let process = winapi::um::processthreadsapi::GetCurrentProcess();
        let mask = 1;
        winapi::um::winbase::SetProcessAffinityMask(process, mask);
    }
    ```
    The event handling taks 800ms in this case (as opposed to 30 ms without setting affinity)
* I've checked hypothesis that this is a regression introduced by moving `cargo check` to the server (by disabling cargo check), and the hypothesis seems wrong: I still get 800 ms

**Comment by matklad** [comment]
I've reverted way back to 442ab3a34dfaf41bc3852acb9db20e0687d20b0c, and still see the same pickture: the test takes 800 ms with and 25ms without affinity. 

That means that reported user-visible regression in performance and the test failing win affinity are independent events. I will continue to investigate the affinity problem (as it seems like it shouldn't be happening). However, I can't investigate user-visible degradation of experience, as I don't see it myself. Would love to get a reproduction!

**Comment by kiljacken** [comment]
@matklad I can give you access to my large work project which is often quite slow with r-a, if that would be useful, with completions often taking several seconds to appear, especially when cargo check is running as well

**Comment by matklad** [comment]
@kiljacken I belive "completion is slow" and "sever perf regression" on windows are different probles. The first one is not regression, and is platform-independent. 

I *think* users are observing big regression on windows, but I have to sift through the recent issues to make sure it is exactly the case.

**Comment by matklad** [comment]
Current depth of the rabbit whole: 

With thread affinity, `std::thread::Thread::unpark` routinelly takes 30-40 milliseconds

**Comment by matklad** [comment]
opened https://internals.rust-lang.org/t/thread-unpark-is-extremely-slow-on-windows/11698

**Comment by edwin0cheng** [comment]
> opened https://internals.rust-lang.org/t/thread-unpark-is-extremely-slow-on-windows/11698

Just curious, are you sure you only measure the processing time on `self.inner.thread.unpark();` and not the IO time of your `printf` ?

**Comment by matklad** [comment]
Pretty sure! And even if we’re measuring prints, it still should be way faster than 40ms

**Comment by matklad** [comment]
So I think there are two things in play here, which affect CI failure:

* first, we fork runtimes **before** we push tasks onto queue. That means that the cancellation has to drain the whole queue, and not only the currently running tasks. This needs to be fixed, but this alone should not help with the second problem
* which is that the windows scheduler seems to be unfair enough, that many background tasks starve the main loop. Specifically, looks like each time the main loop spawns a background job, the scheduler immediatelly switches to this background job (specifically, in the call to the `unpark` method), 

Looks like we'd have to fix 2 anyway, and seems like bumping prioritis is the only reliable way to do so? In other words, analysis by @edwin0cheng on zulip is spot on!


```patch
From 5854cbc2ff480aa900fb47d2f6181404c4a17580 Mon Sep 17 00:00:00 2001
From: Aleksey Kladov <aleksey.kladov@gmail.com>
Date: Sat, 25 Jan 2020 19:06:09 +0000
Subject: [PATCH] bump main thread priority on windows

---
 Cargo.lock                            |  1 +
 crates/ra_lsp_server/Cargo.toml       |  1 +
 crates/ra_lsp_server/src/main_loop.rs | 12 ++++++++++++
 3 files changed, 14 insertions(+)

diff --git a/Cargo.lock b/Cargo.lock
index 07fff9af5..8e320458b 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -1079,6 +1079,7 @@ dependencies = [
  "tempfile 3.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
  "test_utils 0.1.0",
  "threadpool 1.7.1 (registry+https://github.com/rust-lang/crates.io-index)",
+ "winapi 0.3.8 (registry+https://github.com/rust-lang/crates.io-index)",
 ]
 
 [[package]]
diff --git a/crates/ra_lsp_server/Cargo.toml b/crates/ra_lsp_server/Cargo.toml
index 5df0496dd..b31f4c479 100644
--- a/crates/ra_lsp_server/Cargo.toml
+++ b/crates/ra_lsp_server/Cargo.toml
@@ -29,6 +29,7 @@ ra_vfs_glob = { path = "../ra_vfs_glob" }
 env_logger = { version = "0.7.1", default-features = false }
 ra_cargo_watch = { path = "../ra_cargo_watch" }
 either = "1.5"
+winapi = "0.3"
 
 [dev-dependencies]
 tempfile = "3"
diff --git a/crates/ra_lsp_server/src/main_loop.rs b/crates/ra_lsp_server/src/main_loop.rs
index 83adf9711..ccb877ddc 100644
--- a/crates/ra_lsp_server/src/main_loop.rs
+++ b/crates/ra_lsp_server/src/main_loop.rs
@@ -60,6 +60,18 @@ pub fn main_loop(
 ) -> Result<()> {
     log::info!("server_config: {:#?}", config);
 
+    // Looks like windows scheduler is unfair enough to starve out the main loop
+    // if the number of cores is small. So let's bump the main thread priority,
+    // just how MSDN advises us.
+    //
+    // https://docs.microsoft.com/en-us/windows/win32/procthread/scheduling-priorities
+    // https://github.com/rust-analyzer/rust-analyzer/issues/2835
+    #[cfg(windows)]
+    unsafe {
+        let thread = winapi::um::processthreadsapi::GetCurrentThread();
+        winapi::um::processthreadsapi::SetThreadPriority(thread, 1);
+    }
+
     let mut loop_state = LoopState::default();
     let mut world_state = {
         let feature_flags = {
-- 
2.18.0.windows.1
```

**Comment by edwin0cheng** [comment]
> which is that the windows scheduler seems to be unfair enough, that many background tasks starve the main loop. Specifically, looks like each time the main loop spawns a background job, the scheduler immediatelly switches to this background job (specifically, in the call to the unpark method),

I don't know the details about it , but I think it is related: 

https://www.microsoftpressstore.com/articles/article.aspx?p=2233328&seqNum=7

Section : *Boosts After Waiting for Events and Semaphores*
> When a thread that was waiting for an executive event or a semaphore object has its wait satisfied (because of a call to the function SetEvent, PulseEvent, or ReleaseSemaphore), it receives a boost of 1. (See the value for EVENT_ INCREMENT and SEMAPHORE_INCREMENT in the WDK header files.) Threads that wait for events and semaphores warrant a boost for the same reason that threads that wait for I/O operations do—threads that block on events are requesting CPU cycles less frequently than CPU-bound threads. This adjustment helps balance the scales.

And https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-wakeconditionvariable
> The WakeAllConditionVariable wakes all waiting threads while the WakeConditionVariable wakes only a single thread. Waking one thread is similar to setting an auto-reset event, while waking all threads is similar to pulsing a manual reset event but more reliable (see PulseEvent for details).

**Comment by matklad** [comment]
closed by https://github.com/rust-analyzer/rust-analyzer/pull/2906
