### ISSUE TITLE
line! and col! expansion is linear

### ISSUE THREAD

**Issue by MikailBag** [rust-analyzer/rust-analyzer#2842]
# Problem
line!() macro expansion calls `to_line_number`.
Consider this place in this function: 
https://github.com/rust-analyzer/rust-analyzer/blob/e406f2bed66cbe13ef6441a3fb84791a3ca09299/crates/ra_hir_expand/src/builtin_macro.rs#L82
Complexity of this cycle is linear: it looks at each byte before this `line!`

Same with col!: [this](https://github.com/rust-analyzer/rust-analyzer/blob/e406f2bed66cbe13ef6441a3fb84791a3ca09299/crates/ra_hir_expand/src/builtin_macro.rs#L173) cycle iteration count is line size.

That's why it is possible to craft inputs where macro expansion will take quadratic time:
# Test case
(I did not test them locally, because I don't know how to test it using stuff like `analysis-stats`.
But I still believe RA performance on these inputs will be O(input_size**2).)
For line!()
```rust
fn main() {
line!();
line!();
//...
line!();
```

For col!()
```rust
fn main() {
col!();col!();col!();/*...*/;col!();
}
```
# Fix
IMO, the simplest way to address this issue is to use binary search. O(log N) for one macro expansion should be enough.

**Comment by bjorn3** [comment]
`to_col_number` should use `.rfind('\n')` or `rmemchr` instead of a manual loop. That will make it automatically vectorized.

**Comment by edwin0cheng** [comment]
@bjorn3 Indeed, but I think we should change it back to just output a dummy value for now for simplicity.

**Comment by edwin0cheng** [comment]
Submitted #2844 for outputting dummy values.

**Comment by bjorn3** [comment]
#2844 has been merged.

**Comment by kjeremy** [comment]
Wow good catch!
