### ISSUE TITLE
Syntax error on trait fns with destructured args

### ISSUE THREAD

**Issue by tobz1000** [rust-analyzer/rust-analyzer#2847]
Trait functions with destructured arguments do not parse successfully. Some examples:

```rust
struct S { a: usize, b: usize }
struct NewType(usize);

trait T {
    // Syntax Error: expected COMMA/expected type
    fn f1((a, b): (usize, usize)) {}

    // Syntax Error: expected COMMA/expected value parameter/expected R_PAREN...
    fn f2(S { a, b }: S) {}

    // Syntax Error: expected COMMA
    fn f4(NewType(a): NewType) {}

    // Syntax Error: expected COMMA
    fn f3(&&a: &&usize) {}
}
```

These all parse okay as free-standing functions, or in a type impl-block.

The double-deref example is mentioned [here](https://github.com/rust-analyzer/rust-analyzer/issues/597#issuecomment-456480299), so apologies if this is a known issue.

Running in VS Code, built from commit ea0ee8e5bf99bb491875a3539ffdcb39eb0b5397.

**Comment by tobz1000** [comment]
It looks like the problem is within [`params::param_list_opt_patterns`](https://github.com/rust-analyzer/rust-analyzer/blob/1f7a54cfa71a0b81f3f35cde1a529f19f6816a10/crates/ra_parser/src/grammar/params.rs#L101) - because trait functions are parsed as having optional parameter bindings.

The parser looks ahead by 4 tokens for one of the following sequences before parsing a pattern:
- `_:`
- `foo:`
- `mut foo:`
- `&foo:`
- `&mut foo:`

Anything else, and it will just attempt to parse a type.

To detect anything more complex, it looks as though it needs to perform something close to the actual [`pattern::pattern(...)`](https://github.com/rust-analyzer/rust-analyzer/blob/d652e1e67f28c9accc9b98f99085e9509f711d33/crates/ra_parser/src/grammar/patterns.rs#L9) routine, but on encountering an error, backtracking and parsing just as a type instead.

I haven't seen any other examples of backtracking/"retrying" in this fashion, although I'm not too familiar with the project as a whole.

**Comment by matklad** [comment]
Lol, TIL that my first Rust RFC is actually implemented: https://github.com/rust-lang/rfcs/pull/1685

How could I have missed that?

I think the best thing to do would be to support only 2018 edition and always parse patterns in arguments as required, removing the old lookahead special case.

**Comment by tobz1000** [comment]
Okay - does rust-analyzer generally not support 2015, or is it an just an acceptable lack of coverage in this case?

I'd be happy to put up a PR in the next day or so for this.

**Comment by matklad** [comment]
For now, we target 2018, and 2015 where it's not too hard to support. Long
term, of course, we need to support all editions.
