### ISSUE TITLE
Nightly on stable

### ISSUE THREAD

**Issue by DianaNites** [rust-analyzer/rust-analyzer#2848]
Is it, or can it be, possible for rust-analyzer to be told to run the nightly versions of things? In particular cargo fmt and clippy?

In RLS you can explicitly set the channel it uses with `rust-client.channel`, separate from what your project actually uses, but there doesn't seem to be an analogue here?

**Comment by edwin0cheng** [comment]
I think you could do something like this (Haven't tested it though) :

```json
"rust-analyzer.cargo-watch.command": "+nightly clippy"
```

**Comment by DianaNites** [comment]
I actually used to do that, but I don't think it works anymore since cargo watch has been replaced with the in-server thing.

And in any case doesn't address formatting, which is what I really want. `imports_layout` is unstable :(

**Comment by gilescope** [comment]
Maybe the answer is to push for imports_layout to get stabilised?

**Comment by matklad** [comment]
Clippy command is configurable. For `rustfmt`, we literarly do `let mut rustfmt = process::Command::new("rustfmt");` at the moment right now. We should add an option to configure `rustfmt` command.

**Comment by matklad** [comment]
The releveant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/80136367682ced76fb1a74403435c742685620c8/crates/ra_lsp_server/src/main_loop/handlers.rs#L585-L591

**Comment by Arzte** [comment]
Being able to set nightly as the preferred version to run would be helpful, esp with stuff like rustfmt settings that aren't stable yet.

**Comment by DianaNites** [comment]
Fixed by #3181, adding +nightly to the new `rust-analyzer.rustfmtArgs` setting works.

**Comment by DianaNites** [comment]
Wait I made this issue about more than just rustfmt didn't I?

With `+nightly` in the cargo-watch `rust-analyzer.cargo-watch.command` or `rust-analyzer.cargo-watch.arguments` is still broken, no nightly clippy.

**Comment by lnicola** [comment]
You can now override the `cargo check` command:

```
    "rust-analyzer.checkOnSave.overrideCommand": [
        "cargo",
        "+nightly",
        "clippy",
        "--message-format=json"
    ]
```
