### ISSUE TITLE
Bug: ambiguous `+` detection for Trait and lifetime bounds is broken

### ISSUE THREAD

**Issue by ruabmbua** [rust-analyzer/rust-analyzer#285]
**Example:** [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2170f1f5d60327ca5313d5e962673f1f)
**Related:** issue #279 

There are multiple cases, where the ambiguity of `+` is not detected. Note, that the analysis is inside libsyntax (e.g. rustfmt throws the ambiguous `+` error in all cases). This leads to code being able to pass the syntax check, and yielding incorrect results.

List of cases, where additional bounds via `+` are invalid (only the ones I could find / did know):

* shared & mutable reference types
* const and mutable raw pointer types
* Closure return type position (these are handled wrong in libsyntax according to language spec)
* bare function return type position (I think libsyntax got that one right)
* and of course the type cast expression, which is mentioned in issue #279 (the fix should probably be replaced by a more general solution)

This should be solved by properly implementing [TypeNoBounds](https://doc.rust-lang.org/reference/types.html#type-expressions) as a sub parser for all type expressions.

**TypeNoBounds** can then be invoked in all of these 5 cases. Note, that the **allow_bound** mechanism in the **path_()** parser should probably be replaced by something else. E.g. by using **TypeParamBounds** in all the correct places and implementing it correctly.

**Comment by ruabmbua** [comment]
I will try to create a PR, but this might be a little bit over my head.

**Comment by matklad** [comment]
@ruabmbua I think the best way to fix this might be not in the parser itself, but in the [validation](https://github.com/rust-analyzer/rust-analyzer/blob/fd22dbde20179192776a32e40b4f73f2df02c99e/crates/ra_syntax/src/validation.rs) layer. That is, after the parsig is done, you traverse the tree and check that all disambiguating parenthesis are present.

**Comment by ruabmbua** [comment]
A second pass seems like a good idea.

Maybe I can find some time to test this strategy.
