### ISSUE TITLE
Don't require restart for configuration changes

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#2857]
It's frustrating to have to restart RA after each config change. I was talking with @memoryruins and they mentioned that there's a LSP notification on config changes, we'd just have to handle it here:

https://github.com/rust-analyzer/rust-analyzer/blob/c0661ce7444223b0fff1f5d54adb41022ab788cb/crates/ra_lsp_server/src/main_loop.rs#L565

**Comment by SomeoneToIgnore** [comment]
Related: https://github.com/microsoft/language-server-protocol/issues/676

**Comment by matklad** [comment]
I belive we now handle most configs withotu restart
