### ISSUE TITLE
rustup component add rust-src should be run automatically

### ISSUE THREAD

**Issue by gilescope** [rust-analyzer/rust-analyzer#2858]
_Every time_ rust analyzer says can't find rust-src, I have to run rustup component add rust-src (when switching toolchains or computers or getting other people set up).

If rust-analyzer hasn't got the source could it try running `rustup component add rust-src` to see if it fixes things first?
I can't think anyone would not want this? (but if so it could be turned off by a config setting).

**Comment by SomeoneToIgnore** [comment]
Another opportunity can be to adjust the dialogue that pops up when no rust-src is found: we can add buttons with actions there, so we can add one that installs the missing component.

**Comment by matklad** [comment]
Yeah, I think we should just run it without any dialogs.
