### ISSUE TITLE
Changes to `Cargo.toml` don't trigger `cargo check`

### ISSUE THREAD

**Issue by mkpankov** [rust-analyzer/rust-analyzer#2868]
Not sure if it's always the case, I have a workspace and `Cargo.toml` is manifest of subpackage. When I remove a dependency there, compilation errors don't appear until I make a noop edit to any `*.rs` file.

**Comment by flodiebold** [comment]
Related to #1968 (but simpler). I think we don't watch the `Cargo.toml` at all so far.

**Comment by kiljacken** [comment]
This is on me! We just do a naive file extension check against .rs in the
check watcher, should be trivial to add Cargo.toml, or just re-check on all
file updates.
Ideally we'd check if cargo exposes which files trigger a rebuild of what,
but that seems like a lot of complexity.

**Comment by bjorn3** [comment]
Cargo uses the `.d` files emitted by rustc when using `--emit dep-info` to determine which rust source files should trigger a rebuild.

**Comment by gilescope** [comment]
Triggering a check on any save to cargo.toml seems the simplest thing to do at first - that at least makes things less confusing because at the moment you edit cargo.toml and then have to edit and save a .rs file to trigger it currently.

**Comment by matklad** [comment]
That's leave rust-analyzer itself in an inconsistent state though --
completion won't work for new deps, etc.

The minimal useful change here is

* detect that we might need a reload
* show message to the user that a reload is required.

**Comment by gilescope** [comment]
I'm all for that - that's better than me guessing when I should invoke analyzer reload. :-)

**Comment by mkpankov** [comment]
Sorry, is this implemented or closed for other reason? I tried to track commits but couldn't see anything related...

**Comment by matklad** [comment]
this is implemented
