### ISSUE TITLE
"Insert explicit type " assist should trigger only on the binding

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2869]
See this example:

![image](https://user-images.githubusercontent.com/1711539/72620025-cb501480-393e-11ea-94b1-bfd18d10a4d3.png)

Here, the intention will add type to `let ty`. This is clearly not desirable, as `ty` might be off screen. I think we should restrict the intention to only trigger if the cursor is on the `let foo =`, that is, before `=`.

The code for assist is here: https://github.com/rust-analyzer/rust-analyzer/blob/07dca1123dfaec527c6ba3164125309f5c4cc3db/crates/ra_assists/src/assists/add_explicit_type.rs

cc @TomasKralCZ

**Comment by TomasKralCZ** [comment]
Ok, I'll take a look at this.
