### ISSUE TITLE
VS Code Flatpak Support

### ISSUE THREAD

**Issue by mmstick** [rust-analyzer/rust-analyzer#2873]
# Problem
Linux distributions are collectively moving towards Flatpak as a distribution model for third party applications. However, the VS Code extension is currently unsupported within the [VS Code Flatpak](https://flathub.org/apps/details/com.visualstudio.code), due to the way that it tries to spawn `ra_lsp_server` by looking up its path within system paths — paths that won't exist inside of a Flatpak container.

# Solution

The extension could check for the existence of `/usr/bin/flatpak-spawn` to determine if being run within a Flatpak container. If within a Flatpak container, `ra_lsp_server` can be invoked with `flatpak-spawn --host ra_lsp_server`.

**Comment by bjorn3** [comment]
I solved this by telling flatpak to let the PATH env var to include `~/.cargo/bin`, but your solution is much better I think.

**Comment by matklad** [comment]
Hm, looks like this ideally should be some build-in API in the VS Code, similar to how file system is.  But I guess there isn't, and we indeed should do this ourselves :-( 

Also, I cannot help but note that [there's a much better solution for reproducible application packaging](https://nixos.org/) :-)

**Comment by mmstick** [comment]
> I solved this by telling flatpak to let the PATH env var to include `~/.cargo/bin`, but your solution is much better I think.

For anyone wondering how to get this to work:

```sh
flatpak --user override com.visualstudio.code \
    --env=PATH=/app/bin:/usr/bin:/home/$USER/.cargo/bin
```

**Comment by bjorn3** [comment]
The extension now downloads it's own rust-analyzer executable into the extension storage. I am using VSCode inside Flatpak and haven't had any trouble in a long time.

**Comment by dhardy** [comment]
Essentially the same issue occurs with VSCodium in a flatpak:
```
error: could not execute process `rustc -vV` (never executed) Caused by: No such file or directory (os error 2)
```
Solution is as above:
```
flatpak --user override com.vscodium.codium  --env=PATH=/app/bin:/usr/bin:/home/$USER/.cargo/bin
```

**Comment by willswats** [comment]
Could this be reopened? I had to use the `flatpak override` provided by [dhardy](https://github.com/rust-lang/rust-analyzer/issues/2873#issuecomment-1305760775) to get the extension working on the VSCodium flatpak.

**Comment by bjorn3** [comment]
@willswats What do you want rust-analyzer to do? Using `flatpak override` from within a flatpak application is not possible and rust-analyzer doesn't know what to add to `PATH` as you may have installed rustc and cargo anywhere. Rust-analyzer gets the location from `PATH`.

**Comment by willswats** [comment]
@bjorn3 I don't know enough about rust-analyzer or flatpak to come up with a solution, but I wouldn't regard this as solved if the user has to search online for a fix.

**Comment by mmstick** [comment]
You should report the issue to the maintainer of the flathub package.

**Comment by RichardJECooke** [comment]
@mmstick I ran `flatpak --user override com.visualstudio.code --env=PATH=/app/bin:/usr/bin:/home/$USER/.cargo/bin` and nothing happened. I then opened VSCode from the taskbar and rust-analyzer still had the error.

```bash
[ERROR rust_analyzer::main_loop] FetchWorkspaceError:
rust-analyzer failed to load workspace: Failed to load the project at /home/ne/code/rust-actix-web/complete-application/Cargo.toml: Failed to query rust toolchain version at /home/me/code/rust-actix-web/complete-application, is your toolchain setup correctly?: cd "/home/me/code/rust-actix-web/complete-application" && "cargo" "--version" failed: No such file or directory (os error 2)
```

**Comment by euandeas** [comment]
I am having the same issue before and after running the above command.

**Comment by RichardJECooke** [comment]
Yeah I think VSCode under flatpak is just broken. They should remove it rather messing people around.

Rather install it from the site proper -

```sh
curl -L -o vscode.deb "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64" &&
sudo dpkg -i vscode.deb &&
rm vscode.deb;
```

**Comment by krzemyczek** [comment]
> [@mmstick](https://github.com/mmstick) I ran `flatpak --user override com.visualstudio.code --env=PATH=/app/bin:/usr/bin:/home/$USER/.cargo/bin` and nothing happened. I then opened VSCode from the taskbar and rust-analyzer still had the error.

You can always just install rust inside vscodium flatpak.
I went to terminal inside vscodium and pasted:
```sh
 curl https://sh.rustup.rs -sSf | sh
```
But I did it only because I'm on immutable disto
