### ISSUE TITLE
Parameter inlay hint offsetting the argument names

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#2874]
![image](https://user-images.githubusercontent.com/17426603/72661757-91364f80-39de-11ea-8ad8-1f8f6b4f00bb.png)

**Comment by bjorn3** [comment]
The variable `module` is not defined, but I would expect it either not give parameter inlay hints, or show the correct names based on the only function called `declare_data`.

**Comment by lnicola** [comment]
Also, the `linkage` hint is on the wrong argument.

**Comment by bjorn3** [comment]
Yes, also `writable` is the first bool and `tls` is the second bool. I also notice now that `id` should be called `name`, so I guess there is another function which is also called `declare_data`.

**Comment by flodiebold** [comment]
What does 'go to definition' on the method call go to?

**Comment by bjorn3** [comment]
It goes to https://docs.rs/cranelift-module/0.56.0/cranelift_module/trait.Backend.html#tymethod.declare_data instead of the https://docs.rs/cranelift-module/0.56.0/cranelift_module/struct.Module.html#method.declare_data I meant. The former does indeed have `id` has first param, but that method has one more param than the later (it has one too much for this call)

**Comment by flodiebold** [comment]
Method resolution doesn't look at the parameters (except `self`)... I'm wondering why it got the idea that `module` implements this trait though -- is there any kind of blanket impl for it?

**Comment by bjorn3** [comment]
I don't think there is any blanket impl for `Backend`.

**Comment by TomasKralCZ** [comment]
Also, is there a reason why there are no hints on non-literals ?

**Comment by SomeoneToIgnore** [comment]
> Also, is there a reason why there are no hints for non-literals ?

This is the reason, I believe: https://github.com/rust-analyzer/rust-analyzer/issues/1618

**Comment by bjorn3** [comment]
I haven't seen this problem in a long time.
