### ISSUE TITLE
Parameter inlay hint separate from variable type inlay?

### ISSUE THREAD

**Issue by DianaNites** [rust-analyzer/rust-analyzer#2876]
Would it be possible for these to be separate options? I'm not a big fan of the type inlays, I prefer hovering if I need them, but the recently added parameter name inlay is super nice

**Comment by matklad** [comment]
Yes, we should split this into two options

**Comment by Veetaha** [comment]
We should add appropriate option to config in `package.json`
https://github.com/rust-analyzer/rust-analyzer/blob/61fdcc5ded44d4a7300b19cf946acc30367dcbd2/editors/code/package.json#L166
Add getter for it in `config.ts`
https://github.com/rust-analyzer/rust-analyzer/blob/61fdcc5ded44d4a7300b19cf946acc30367dcbd2/editors/code/src/config.ts#L151-L152
And change this `enabled` flag to carry info about which type of inlay hints is enabled.
https://github.com/rust-analyzer/rust-analyzer/blob/61fdcc5ded44d4a7300b19cf946acc30367dcbd2/editors/code/src/inlay_hints.ts#L66

**Comment by SomeoneToIgnore** [comment]
We need to go deeper, to RA level otherwise RA will be computing all types of inlay hints anyway which might be suboptimal.

On a server level, the hints have a kind: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_ide/src/inlay_hints.rs#L15

The setting needs to be passed there, and the logic altered so that the unnecessary kinds of hins are not computed.

**Comment by Veetaha** [comment]
@SomeoneToIgnore does it make sense to separate inlayHints request to inlayTypeHints and inlayParameterHints? Though if both of them are enabled we would need to make two passes or are type and parameter hibts independent anyway?

**Comment by SomeoneToIgnore** [comment]
> we would need to make two passes

Exactly, so I would rather have a single request and a few `if`'s in the `inlay_hints.rs` instead.

**Comment by slyngbaek** [comment]
I'll take a look into this one.

**Comment by Veetaha** [comment]
@matklad #3543 should've closed this
