### ISSUE TITLE
Slow and buggy inline hints and color highlighting

### ISSUE THREAD

**Issue by max-frai** [rust-analyzer/rust-analyzer#2881]
Hello, on big projects after each save I often get broken inline hints and color highlighting.
During this I see checking progress in statusbar and after some time (after check is finished) hints are fixed. It worked okay first time, but after adding "heavy" deps it started lagging :(

Maybe some possible case for the problem: I have ~10 dependencies from private close git repo and ofter it starts checking them.

<img width="466" alt="Screenshot 2020-01-20 at 15 54 39" src="https://user-images.githubusercontent.com/24208746/72731991-7231ec00-3b9d-11ea-98ba-decf46428a52.png">

Also after almost each save it starts to check some random crate from my deps. So after small change (enter) in my local file, checking of `futures_executor` started for some reason.
<img width="202" alt="Screenshot 2020-01-20 at 16 01 27" src="https://user-images.githubusercontent.com/24208746/72732348-2c295800-3b9e-11ea-9948-10e9f18b58b7.png">

**Comment by max-frai** [comment]
Here is example of broken highlighting. It's not fixing even after cargo check so my code looks like this and I can't find the exact way how to fix it.
<img width="599" alt="Screenshot 2020-01-20 at 17 16 18" src="https://user-images.githubusercontent.com/24208746/72737654-a1018f80-3ba8-11ea-9f95-d235f9a110bb.png">

**Comment by bjorn3** [comment]
Is this still an issue? The highlighting has since been replaced with the lsp semantic highlighting interface, which should take care of preventing outdated highlighting.

**Comment by max-frai** [comment]
Yes, it's fixed with new semantic highlighting, thanks.
