### ISSUE TITLE
Autocomplete needs to aggressively listen to new packages in toml

### ISSUE THREAD

**Issue by Matelasse** [rust-analyzer/rust-analyzer#2885]
I noticed a very cool feature in the Jetbrains IDE. They basically watch cargo.toml for any new additions, and once you write something new (without actually downloading the new packages with cargo) you get completions for those new packages. In rust-analyzer, we need to also install the added packages with cargo, before RA is able to provide completions for those packages. Not sure how Jetbrains Rust actually implemented this feature, it doesn't seem trivial to me.

**Comment by matklad** [comment]
Here’s it he initial implementation from IntelliJ Rust: https://github.com/intellij-rust/intellij-rust/commit/8f5434d24db90dc61a9cc6ae8f54f459a119cb0b :D

**Comment by Matelasse** [comment]
> Here’s it he initial implementation from IntelliJ Rust: [intellij-rust/intellij-rust@8f5434d](https://github.com/intellij-rust/intellij-rust/commit/8f5434d24db90dc61a9cc6ae8f54f459a119cb0b) :D

 I was going to mention you in the issue to ask if you had any idea how intellij implemented it... :smile:

**Comment by kjeremy** [comment]
#3414
