### ISSUE TITLE
Can't Activate Features in Cargo Check

### ISSUE THREAD

**Issue by sanbox-irl** [rust-analyzer/rust-analyzer#2897]
Hello!

I updated to the current (as of posting this issue) version of the RA and it appears that the way features work with cargo check has been changed, and it's made all my diagnostics disappear.

Here's what I have as my settings:

```json
{
    "rust-analyzer.cargoFeatures.features": [
        "metal"
    ],
    "rust-analyzer.cargo-watch.arguments": [
        "--features=\"metal\""
    ]
    "rust-analyzer.cargoFeatures.allFeatures": false
}
```

Additionally, just to make it clear, here is the relevant part of my Cargo manifest:
```toml
[features]
metal = ["gfx-backend-metal"]
dx12 = ["gfx-backend-dx12"]
vulkan = ["gfx-backend-vulkan"]
```

I'm sure I'm just formatting something incorrectly, but trying to go through the server log, it doesn't look like the actual command passed to cargo check is listed anywhere explicitly. I see a call out that looks like it's it, but I don't know what the exact command is.

Any help would be very appreciated! Thank you!

**Comment by kiljacken** [comment]
You are missing a `,` in your settings, but that's probably not the issue.

Could you try the `cargo-invocation-log` branch of [kiljacken/rust-analyzer](https://github.com/kiljacken/rust-analyzer) and run it with `RUST_LOG=info`? That should output the exact arguments that gets passed to cargo.

**Comment by sanboxrunner** [comment]
I'm not sure how to run the server myself. My only real interaction with this software is running `cargo xtask install`. However, I did install that branch and everything worked as expected -- only the current release branch is giving me problems

**Comment by kiljacken** [comment]
if you launch VSCode with the environment variable set it should propagate through

**Comment by sanboxrunner** [comment]
Hi there! Sorry to be difficult when you're helping me. I did as asked, and I believe a new output tab called "Cargo Watch Trace" appeared, but it remains blank. I also looked through the other logs, just control+F-ing around for "cargo" or "watch", and none of the results looked like a traced invocation. 

I suspect I'm not doing something exactly right.

Here are the exact steps I did to do this basic task (I feel a little stupid for not doing this correctly!):

Opened up terminal (I happen to be on a mac at this moment),
navigated to project that uses cargo features
and ran `RUST_LOG=info` and then ran `code .`.

**Comment by sinkuu** [comment]
IIUC you have to run `RUST_LOG=info code .` (or `export RUST_LOG=info` and then `code .`).

**Comment by kiljacken** [comment]
@sanboxrunner Don't worry, it's my fault not explaining it as well as I could.

So, the steps I'd like you to take:
* Run `env RUST_LOG=ra_cargo_watch=info,ra_lsp_server=info code .` in your project directory
* Navigate to the `Output` tab on the bottom of VSCode
* On the right side of the `Output` tab there's a drop down. Select `Rust Analyzer Language Server`.
* Share the output here

**Comment by sanboxrunner** [comment]
Hello! Apologies for the wait. Work and what not:

Here's the log.

https://gist.github.com/sanboxrunner/b1a866823ca9dd8fac59b0635c71d48d

**Comment by sanboxrunner** [comment]
I am not getting any diagnostics of any sort right now

**Comment by kiljacken** [comment]
Would you mind sharing the output of running:
`cargo check --message-format=json --manifest-path /Users/jjspira/Documents/Rust/clockwork/Cargo.toml --all-targets --features="metal"`
as well? Just to check that cargo is actually outputting something useful.

**Comment by osa1** [comment]
I think I'm also suffering from the same problem. I don't see any cargo features in the Ctrl+Shift+p menu (no "cargo watch" or anything like that), and I get no errors whatsoever even in a project with dozens of compile errors.

**Comment by sanboxrunner** [comment]
@kiljacken yup, getting output. It's a bit messy of course:
https://gist.github.com/sanboxrunner/cf308c66e00491c87ee374bec0970202

**Comment by sanboxrunner** [comment]
Oh to be clear, that project currently compiles, so there should not have been any errors reported.

Here, I've introduced a few non-syntax errors related to the feature set:

https://gist.github.com/sanboxrunner/a27dce8d313de39095c3e26aeb0f3bde

In the messages, the `B` is a "Backend" trait which is implemented by a struct from the Metal feature.

**Comment by kiljacken** [comment]
I'm not sure if it'll have an impact on this issue, but for just for the sake of it, now that #2959 has landed, could you please retry on latest master?

**Comment by osa1** [comment]
After a `git pull` and installing again I opened a project with build errors and right away I get "problems" window populated with errors, so it seems like things definitely improved since my last message above.

I still don't see a "cargo watch" command in ctrl+shift+p menu though.

**Comment by kiljacken** [comment]
That command doesn't exist (see #2764), so that makes sense.

**Comment by osa1** [comment]
OK. It's not necessary now as the "problems" window is now working. It'd be good to update [the documentation][1] which suggests such a command exists.

[1]: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/features.md

**Comment by sanboxrunner** [comment]
No dice @kiljacken . I've open sourced a snapshot of the repo in question here, so if you want to mess about with it yourself, that's available. 

In the meantime, I've reverted the RA back to commit d652e1e67 which just happens to be what my laptop had, and which happens to still work.

**Comment by sanbox-irl** [comment]
loaded up the current version of the server. things seem to be working. did something et solved? who knows. closing issues is fun tho. let's close it!

**Comment by bjorn3** [comment]
Did you intend to re-open?

**Comment by sanbox-irl** [comment]
(yes, should have typed and then reopened. I'm typing up a whole thing right now and then will delete this message)

**Comment by sanbox-irl** [comment]
Nevermind, closing issues is for losers!

Immediatley after closing the issue, the problem reappeared in current (pulled from master with the key added to VSC to prevent it pull from releases) version...

But I have found an excellent clue to the problem!

I'll walk through the whole thing quickly. I have multiple features in my cargo which related to different graphical backends. Those backends are loaded into cargo conditionally *and* then the features are activated based on what flags are passed in, like normal with `--features=metal` for example.

Here is my original Cargo.toml:

```toml
[dependencies.gfx-backend-vulkan]
version = "0.4"
optional = true

[target.'cfg(target_os = "macos")'.dependencies.gfx-backend-metal]
version = "0.4"
optional = true

[target.'cfg(windows)'.dependencies.gfx-backend-dx12]
version = "0.4"
optional = true
```

With that, the RA would either fail to send any checks or would be unable to detect any of the features loaded. On a hunch, I changed that cargo.toml to this:

```toml
[dependencies.gfx-backend-vulkan]
version = "0.4"
optional = true

[dependencies.gfx-backend-metal]
version = "0.4"
optional = true

[dependencies.gfx-backend-dx12]
version = "0.4"
optional = true
```

And boom, the RA now correctly loads metal on macOS. (To be clear, the entire time this was happening, I was specifying that `features=metal` in VSC settings to the RA). I feel like this has to do with targets for the Rust Analzyer, but I'm not sure beyond a hunch, but I feel like this is a promising lead!

Thanks for all the help so far guys, hope this helps even further

**Comment by bjorn3** [comment]
I believe the `#[cfg]` for the host system are used by rust-analyzer.

**Comment by sanbox-irl** [comment]
Okay, nevermind that nevermind. I'm straight up
![image](https://user-images.githubusercontent.com/31973761/74584398-b939b400-4f86-11ea-899e-7d249847f2f2.png)

**Sometimes** it only loads the correct feature. Other times, it doesn't. I don't have access to exactly what's going on, but when it loads too much, whihc causes it to say certain modules aren't available, which are, it'll say loaded 273 packages. When it has loaded the *correct* modules, then it will only load 250-ish packages.

For now, here's the repo: https://github.com/sanbox-irl/sokoban-chess

Unfortunately, being a game engine, it has an annoying build path. The difficult part is shaderc, whose build instructions you can see here -- https://github.com/google/shaderc-rs

For best results, pull from the `prefabs-robust` branch. I'll leave it here for now

**Comment by sanbox-irl** [comment]
It started working again, I have no idea why, let's call it a day.
