### ISSUE TITLE
ra_syntax: can't parse weird-exprs.rs correctly

### ISSUE THREAD

**Issue by ordian** [rust-analyzer/rust-analyzer#290]
rust-analyzer reports lots of syntax errors on [this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7cf3546d8416fc76e5828481576fe6f9) (extracted [from the compiler](https://github.com/rust-lang/rust/blob/master/src/test/run-pass/weird-exprs.rs) + added ktulhu).

**Comment by matklad** [comment]
Excellent, thank you so much for pointing out this test!
