### ISSUE TITLE
Hover show squashed info

### ISSUE THREAD

**Issue by 95th** [rust-analyzer/rust-analyzer#2902]
Hovering over the `read_to_end` function shows the lifetime and `mut` all squashed together.

![Untitled](https://user-images.githubusercontent.com/22871609/73090331-303ada00-3efe-11ea-820b-340c02f8489d.jpg)

**Comment by flodiebold** [comment]
I'm pretty sure this is another case of #2765; since you didn't include the information where this method comes from, I have to guess it's tokio, which uses a lot of macros.

**Comment by 95th** [comment]
@flodiebold Yes, its Tokio. Sorry I didnt provide additional information. The linked issue looks the same. Thanks
