### ISSUE TITLE
Sanitizing memory-safety issues.

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#2904]
# Rationale

`rust-analyzer` currently uses some `unsafe` code under the hood. This is not good or bad, it has pros, and cons. One of the cons is potential memory corruption. On `Jan 11 2020` we got a message from @leo-lb on zulip ([you can view it here](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/heap.20corruption.2Fdouble.20free.2Finvalid.20pointer.20free.20bug)).
A short summary of that report:

```
free(): invalid next size (fast)
```
> It happened after I removed a dependency from my Cargo.toml
I've been unable to reproduce it (so far)

This means `rust-analyzer` already uses unsound code somewhere in the codebase that caused that memory corruption.

Our current status-quo dictates that we can't more-or-less deterministically react to that issue to find the root cause, because the error message provides somewhere-close-to-zero payload to deduce what happened.

I can only suppose that the faulty code is located somewhere where we use `unsafe` blocks which is [`rowan`](https://github.com/rust-analyzer/rowan) crate and more probably this is [`thin_dst`](https://github.com/CAD97/thin-dst) crate, just according to my intuition.

# Proposal

Integrate sanitizers to run `rust-analyzer` under extensive memory-corruption and leak checks. Unfortunately, I have no experience doing it it `Rust`, so it needs some investigation... Any ideas of tools and setup would be really helpful. I'd propose to use [`valgrind`](https://valgrind.org/) for debug runs of the project just to start with. Then, maybe some sanitizers like [`ubsan`](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) from llvm toolchain.

**Comment by Veetaha** [comment]
It seems that [`miri`](https://github.com/rust-lang/miri) could be a nice tool to integrate, though it doesn't allow for such things as concurrency. Would need to investigate how to deal with it more thoroughly (maybe using it only for specific test runs).

**Comment by lnicola** [comment]
I don't think the sanitizers work too well, e.g. compiling RA with ASAN doesn't work:

```
libchalk_derive-9ce3c3d7acb1e378.so: undefined symbol: __asan_option_detect_stack_use_after_return
```

**Comment by bjorn3** [comment]
Try building with `--target x86_64-unknown-linux-gnu` (modify for local target). This will cause all build scripts and proc macros to be build without the flags from `RUSTFLAGS`.

**Comment by lnicola** [comment]
Unsurprisingly, I can't reproduce the problem mentioned in Zulip.

**Comment by bjorn3** [comment]
Has anyone seen this since?

**Comment by kjeremy** [comment]
I say close it.
