### ISSUE TITLE
Feature request: navigate by ctrl-clicking on inline type hints

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#2905]
```
commit c6dbf406a9bbf1d8df438753c9e1a7c97d0f00e1
Merge: 8a4c248c4 b90ea640e
Author: bors[bot] <26634292+bors[bot]@users.noreply.github.com>
Date:   Fri Jan 24 15:37:11 2020 +0000
```

Inline type hints sometimes could be invaluable, especially they help when navigating through unfamiliar codebase.

Unfortunately, it's not currently possible to use them to navigate into the type. For example in the screenshot below I'd like to be able to Ctrl+click on the grey `Context` word to dig right into its definition.

![image](https://user-images.githubusercontent.com/3784017/73120552-371b2880-3fa2-11ea-9d77-9f431ada3afb.png)

This could be especially handy, since this might be the only place in the code where such type is displayed. Otherwise one would need to find that type manually which is kinda unconvenient.

**Comment by flodiebold** [comment]
Note that there's a "go to type definition" function, which should do this if you use it on `ctx` (I don't know how you trigger that in VS Code). I think this makes sense as well though.

**Comment by 0x7CFE** [comment]
> Note that there's a "go to type definition" function

Indeed, thank you for the hint! 

Of course, there are plenty of ways to find the actual type, for example navigate to `new_context` and examine the return type. Yet, I believe that doing ctrl+click is quite natual thing here.

Also one may want to examine not the type itself, but its part, like `M` in the example above. In that case, ctrl+click seem to be the most convenient way to do it.

**Comment by matklad** [comment]
i don’t there’s api in vscode which allows us to do that.

**Comment by 0x7CFE** [comment]
> i don’t there’s api in vscode which allows us to do that.

Really? Oh, that's a pity. I thought that since the text is displayed in the edit box anyway, it should be possible.

**Comment by kjeremy** [comment]
Go to type definition is your best bet and I think you can have a custom keybinding for it. We could certainly add links in hover but I don't know how useful that would be.

**Comment by 0x7CFE** [comment]
I see, thank you

**Comment by p-avital** [comment]
Since these are built with decorations, which are HTML, we could add an
`onclick` event or make them be links ?

**Comment by matklad** [comment]
I would say this is covered by hover actions now: https://rust-analyzer.github.io/thisweek/2020/06/22/changelog-30.html
