### ISSUE TITLE
analyzer very slow when i write code with actix-rt's macro

### ISSUE THREAD

**Issue by Anehta** [rust-analyzer/rust-analyzer#2912]
![image](https://user-images.githubusercontent.com/6553443/73161609-dff29080-4126-11ea-9363-4b588455aed1.png)
when i typing info. it can work .
![image](https://user-images.githubusercontent.com/6553443/73161666-04e70380-4127-11ea-9a80-7d93dc893177.png)
but i waiting for 10s+
![image](https://user-images.githubusercontent.com/6553443/73161715-25af5900-4127-11ea-8a9c-901e1923eeaf.png)

**Comment by flodiebold** [comment]
Can you try again with the newest master? This might be related to trait solving, in which case we should spend much less time on it now.
