### ISSUE TITLE
Prefer std paths to core/alloc paths in autoimport etc.

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#2915]
Autoimport and path qualification should prefer to use `std` paths before `core` or `alloc`. I think this probably requires a small hack [here](https://github.com/rust-analyzer/rust-analyzer/blob/1916a78c6a31219a8aaa73f2b443282441671539/crates/ra_hir_def/src/find_path.rs#L115) to hardcode this preference; at least I can't think of any principled rule for this.

(Note that this is unrelated to `no_std`; once we have `no_std` support, the path finding algorithm should automatically only find `core` paths in such crates.)

**Comment by SomeoneToIgnore** [comment]
Does it make any sense to add `core` and `alloc` entries here: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_hir_expand/src/name.rs#L142 to be able to compare them as names in the line proposed in the ticket?

**Comment by flodiebold** [comment]
Probably, yeah!
