### ISSUE TITLE
Completion items for missing imports

### ISSUE THREAD

**Issue by Matelasse** [rust-analyzer/rust-analyzer#2919]
Follows up https://github.com/rust-analyzer/rust-analyzer/issues/2918. It would also be nice to have completion suggestions. Typescript LS is a nice example of how good that feature can be.

**Comment by Veetaha** [comment]
Totally agree, I think TypeScript team has achieved the best auto-import experience there in the market.
It provides you with all possible completions even if they are somewhere far from your module.
![ts-completion](https://user-images.githubusercontent.com/36276403/73252770-f13daa80-41c3-11ea-8141-4efdb80f2fea.gif)

**Comment by marcogroppo** [comment]
@Veetaha for what it's worth: OmniSharp (a very good C# language server) only shows completions for the imported namespaces. I like the TS extension approach, but if there are too many symbols completing everything could be too chaotic.

**Comment by SomeoneToIgnore** [comment]
Is this a duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/1062 ?
