### ISSUE TITLE
Array types are formatted in non-standard way in type hints

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#2921]
Thanks for ra! I quickly noticed a very minor thing when trying it out: With this code

```rust
let x = [0.0; 3];
```

I get a type hint like this:

```rust
let x: [f64;_] = [0.0; 3];
```

This is not how rustfmt would format this if there was a type annotation (actually, `_` is not valid in that position, but this is true when using `3` instead in this example). It would add a space after the semicolon:

```rust
let x: [f64; _] = [0.0; 3];
```

**Comment by matklad** [comment]
closed by https://github.com/rust-analyzer/rust-analyzer/pull/2926
