### ISSUE TITLE
"Insert explicit type" suggestion produces invalid code for array

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#2922]
For arrays, ra produces an invalid suggestion to insert `[T;_]`, where `T` is a concrete type, but `_` is literally an underscore, which is not valid in that position.

Example:

```rust
let x = [0.0; 3];
```

produces a suggestion that when applied results in

```rust
let x: [f64;_] = [0.0; 3];
```

which leads to the error message

```
error: expected expression, found reserved identifier `_`
   --> src/file.rs:line:col
    |
col |             let x: [f64;_] = [0.0; 3];
    |                 -       ^ expected expression
    |                 |
    |                 while parsing the type for `x`
```

**Comment by lnicola** [comment]
Wasn't there an RFC to allow underscores for array lengths?

**Comment by jplatte** [comment]
You were a bit faster than I was! ^^

But that RFC hasn't been merged yet, and apparently also hasn't been implemented, considering I get that error message on Nightly.
