### ISSUE TITLE
Trait implementations in external crates are not shown

### ISSUE THREAD

**Issue by SomeoneToIgnore** [rust-analyzer/rust-analyzer#2929]
Consider the `ImportsLocator` trait from the `ra_assists`:

https://github.com/rust-analyzer/rust-analyzer/blob/9be1ab7ff948d89334a8acbc309c8235d4ab374f/crates/ra_assists/src/lib.rs#L86

When I open the project with RA and navigate to it, I get a single implementation shown in a lens:

![image](https://user-images.githubusercontent.com/2690773/73282169-c8380c80-41f9-11ea-824f-8d1c99230d46.png)

This is it, in the same file, in the test module:

https://github.com/rust-analyzer/rust-analyzer/blob/9be1ab7ff948d89334a8acbc309c8235d4ab374f/crates/ra_assists/src/lib.rs#L249

But there's another one, in `ra_ide` crate that is not shown in the lens even after I navigate to that file and back (just to ensure that RA is aware and loaded that file):

https://github.com/rust-analyzer/rust-analyzer/blob/9be1ab7ff948d89334a8acbc309c8235d4ab374f/crates/ra_ide/src/imports_locator.rs#L44

I would expect the lens to show both implementations.

**Comment by matklad** [comment]
Yeah, this is partially an artifact of the fact that this was originally implemented way before generic reference search.

However, I am not sure whether we need to use reference search for this as is... I lean towards building an impl index on top of hir.

**Comment by flodiebold** [comment]
Hm, we already find impls generated by macros, so I think we already use the HIR? I haven't looked at the code...

**Comment by lnicola** [comment]
Triage: `ImportsLocator` is gone, but `trait Diagnostic` is shown as having 0 implementation.

**Comment by jonas-schievink** [comment]
Looks like this was fixed by https://github.com/rust-analyzer/rust-analyzer/pull/8020
