### ISSUE TITLE
Extend VFS to allow dynamic addition of source roots

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#293]
Currently, `VFS` requires the set of roots in its `new`. Ideally, we should allow to dynamically add source roots.

This is tricky, however: an added root can be withing some previously existing root, so we'll need to move files from the old root to the new one. (so, both Remove & Add files in the pending_changes).

Another thing to keep in mind is that we can add a new, nested root when the old root is being scanned! So, we need to account for that as well.

The relevant code is here: https://github.com/rust-analyzer/rust-analyzer/blob/1491fafddbe16bb5851c7ad8f82011e224e469ed/crates/ra_vfs/src/lib.rs#L119

**Comment by pasa** [comment]
I would like to do this. As I understand vfs was moved to the separate repo. Do you have some best practice manage with multiple repo in this project?

**Comment by matklad** [comment]
Vfs is indeed in a separate repo: https://github.com/rust-analyzer/ra_vfs

We publish it to crates.io and use a usual cargo dependency.

For hackig, it's a good idea to add something like

```
ra_vfs = { path = "../ra_vfs" }
```

to the `[patch]` section in the root Cargo.toml.

I am not actually sure it is a best issue to work on right now: there's hope that the new notify (file watching crate we use) will implement an [API](https://github.com/passcod/notify/issues/175) which will make VFS implementation much more straitforward. If that happens, we'll perhaps will need to re-think how code is split between vfs and rust-analyzer.

I'd even say that the best way to move this issue forward is to hack on notify to add 175.

**Comment by pasa** [comment]
Ok. It is pity,  but seems that all another e-mentor issues are taken.  Will try to find something I can cope with.

**Comment by matklad** [comment]
I think is obsoleted, we should re-design VFS API based on https://docs.rs/watchman_client/0.4.0/watchman_client/
