### ISSUE TITLE
Cargo xtask install does not support offline installations

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#2930]
I am currently sitting in the airport with broken wifi and this is annoying me.

**Comment by lnicola** [comment]
Try `cargo build --release --offline && sudo cp target/release/ra_lsp_server ~/.cargo/bin`? Not sure about the Code extension, but I think it's fine to use an older version.

**Comment by kjeremy** [comment]
Thanks! We should pass --offline to xtask in the future.

**Comment by matklad** [comment]
I'd say manual work-around is the right approach here.
