### ISSUE TITLE
Import assist does not trigger on the first character of identifier

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#2932]
![image](https://user-images.githubusercontent.com/1711539/73347502-00862c00-4288-11ea-8c01-1cbef37b42e1.png)

token_at_offset thing should smartly select the right ident near the cursor, not sure why it doesn't work in this case...

cc @SomeoneToIgnore

**Comment by SomeoneToIgnore** [comment]
I'll try to investigate it this week, thanks.
