### ISSUE TITLE
Check watcher hangs on invalid output from cargo check

### ISSUE THREAD

**Issue by kiljacken** [rust-analyzer/rust-analyzer#2935]
Alright, I think I've figured it out!

I was using a proc macro that `println!`ed some debugging info. That debugging info appears in the output used by rust-analyzer, but not in the output when you run `cargo check` from the command line for some reason.

After removing the `println!`s everything is now working as it should.

Not sure how the parsing of `cargo check` works, but maybe it's spinning on reading the same invalid JSON character again and again?

_Originally posted by @Jos635 in https://github.com/rust-analyzer/rust-analyzer/issues/2909#issuecomment-579729371_

**Comment by Jos635** [comment]
Minimal project to reproduce: https://github.com/Jos635/ra-hang-on-invalid-cargo-check-output

Run `code demo` and hit Control+S in `main.rs` if necessary to trigger a `cargo check`, it will then hang forever and make `code` use 1 CPU core and `ra_lsp_server` 1 CPU core.

**Comment by ob** [comment]
I'm not sure this is fixed. I just hit it and can reproduce it easily (see [`rust-sample`](https://github.com/ob/rust-sample)). 

The last comment in #13023 also mentioned `println!()` in a procedural macro. 

Something to note is that the log for the "Rust Analyzer Language Server" prints 
```
Error: Custom { kind: InvalidData, error: Error("unknown variant `ApiVersionCheck`, expected `ListMacros` or `ExpandMacro`", line: 1, column: 18) }
```
which is similar to the error in #14085.

**Comment by lnicola** [comment]
@ob the error is harmless and should be gone in the nightly version, but I don't think you're supposed to use `println!` in a proc macro.

**Comment by Veykril** [comment]
`println!` in proc-macros is discouraged yes (r-a has something to somewhat guard against the use of them though as well I think)

**Comment by ob** [comment]
Still... it shouldn't hang no? Is that a bug in `cargo check` then? If i run `cargo check` by hand, even with the `println!()` in the macro it doesn't hang...

**Comment by lnicola** [comment]
`rustc` runs under different conditions from `rust-analyzer`: it loads the macro, expands the code, then quits. We need to keep running and support proc macros that you change and recompile.

In any case, I can't reproduce the hang:

![image](https://user-images.githubusercontent.com/308347/218247033-e367e4b3-9610-44c8-9fae-2f9f6a7ee2fe.png)

**Comment by ob** [comment]
That is weird! I can repro every time... are you using rust nightly?

**Comment by lnicola** [comment]
Some old beta and a source build from this week, shouldn't matter AFAICT.

**Comment by ob** [comment]
I get the same error:

```
[ERROR proc_macro_api::msg] proc-macro tried to print : input = "Hello, world!"
```

But if I try to edit the `println!()` string in `main.rs` (e.g. put it in one line, or change the spaces between the parenthesis and the quotes) VS Code locks up and I can't input anymore while `cargo check` just keeps spinning on the bottom.

**Comment by lnicola** [comment]
Oh, I think I have check disabled, I'll try again tomorrow.

**Comment by lnicola** [comment]
@ob nope, still can't reproduce it. Feel free to create a new issue.

**Comment by ob** [comment]
Ok, submitted #14136
