### ISSUE TITLE
Better Type Hints for Enum Structs/Tuples

### ISSUE THREAD

**Issue by sanbox-irl** [rust-analyzer/rust-analyzer#2947]
Hello!

This is relatively small, but it might not be something the RA can do yet.

If I have an enum like this:
```rs
pub enum PlayerInputType {
    Start,
    PlayStaffCard(String),
    PickIssue(String),
    BooleanDecision(bool),
    PickPlayer(PlayerName),
    StubbedAction,
    Inaction,
    AdvanceAnIssue {
        issue_name: String,
        staff_card_name: String,
    },
```

Rust-analyzer can be a little strange with autocompletion here for the non-tuple variant (`AdvanceAnIssue`). 

Here is what autocompletion/help looks like for `PlayStaffCard`:
![image](https://user-images.githubusercontent.com/31973761/73394199-054fdd80-4292-11ea-9e69-7051aa5f1645.png)

That's very clear. I know that i should, after hitting tab, type a `(` and then a String, like in the type inlay.

Here's the struct variant on the other hand:
![image](https://user-images.githubusercontent.com/31973761/73394294-2b757d80-4292-11ea-8fa9-438245e4ea02.png)

It shows something similar, representing its data as a tuple! That's fine from a memory standpoint, but it means:
1. I can't trust any tuple autocomplete anymore, since they might be a struct, so I'll have to click in and check
2. I can't know which struct enum variants there are, so I'll need to go to reference for them as well.

I'm not sure what a better enum variant hint here would look like, but i suspect merely changing the type hint to just `{String, String}` as opposed to `(String, String)` would be good enough. Perhaps a real:
```rs
    AdvanceAnIssue {
        issue_name: String,
        staff_card_name: String,
    }
```
popping up would be the best long term solution, along with perhaps an assist in making all the fields if desired, but just the small change would be good enough I think.

Thank you!

**Comment by matklad** [comment]
closed by https://github.com/rust-analyzer/rust-analyzer/pull/3169
