### ISSUE TITLE
Started to incorrectly process source changes since latest release

### ISSUE THREAD

**Issue by mkpankov** [rust-analyzer/rust-analyzer#2950]
Get this code - clone entire repo, start editing this file
https://github.com/whamcloud/integrated-manager-for-lustre/blob/scanner/iml-services/iml-devices/src/db.rs

Edit something so that it should result in compilation error. Save the file. Observe no error. Edit with a no-op (add and remove a space), save the file, observe an error.

While this may sound strange, it's actually easy to spot when working interactively. Looks like mis-compilation in incremental mode, that requires 2 subsequent compilations to actually compile current version of code.

**Comment by kiljacken** [comment]
Sounds like an issue with diagnostics not being cleared properly when cargo
check is run, which wouldn't surprise me too badly. Will investigate
further.

For my own mental note: it's might have to do with cancellation of the
diagnostics update, which could get file clear to get lost. We should
probably explicitly update a file on save as well.

**Comment by flodiebold** [comment]
I'm actually getting this as well, working on RA with emacs. It seems like cargo runs before the file is actually saved, so I was assuming the problem is on the emacs side.

**Comment by SomeoneToIgnore** [comment]
I think there are two separate issues that are very much alike: I experience similar behavior with VSCode on TypeScript projects.

Seems like current VSCode does not instantly save the file after the changes and if you run anything (i.e. compilation) after the editor change fast enough, the old version of the code will be used.

**Comment by SomeoneToIgnore** [comment]
Same happens on Rust projects for me (I don't use cargo watch, just manually run the tasks).

It did not reproduce when I've tried the same in the preview version of the VSCode though so hopefully it fixed with the new release and we will be left with the emacs issue only.

**Comment by mkpankov** [comment]
> Seems like current VSCode does not instantly save the file after the changes 

Hmm, to me it seemed like it started with update of RA, not VSCode... I think I've been using same version of VSCode for quite a while - latest minor is from November I think (1.41) and 1.41.1 patch also seems to be older than this issue.

**Comment by matklad** [comment]
Yeah, I can reproduce it, on that specific file, if I try to safe immediately after modification. Explanation by @kiljacken sounds reasonable.

In general, the current set-up where we compute our native diagnostics when a new cargo-check diagnostic arrives seems quesionable. I think we should do the following instead:

* add `diagnostics: Diagnostics` field to `WorldState`, where
  ```
  struct Diagnostics { native: HashMap<FileId, Diagnostic>, check: HashMap<Field, Diagnostic> }
  ```
* change `handle_diagnostics` to not repy to the cient directly, but instead to send a set of diagnostics to the main loop, just like the check does.
* in the main loop, merge diagnostics form check and handle_diagnostics into a single `Diagnostics` struct, and send it to the client.

**Comment by kiljacken** [comment]
Now that #2959 has landed, could you please retry on latest master?

**Comment by mkpankov** [comment]
Seems to work
