### ISSUE TITLE
rename doesn't see occurences inside macros

### ISSUE THREAD

**Issue by martinpospech** [rust-analyzer/rust-analyzer#2957]
Doing `Rename Symbol/F2` in VS Code doesn't affect `a` in `println!`.

```
fn main() {
    let a = "test";
    println!("b: {}", a)
}
```

**Comment by kjeremy** [comment]
Rename is built on our find references infrastructure which does not currently work in macro calls (though goto def does?).

@edwin0cheng

**Comment by edwin0cheng** [comment]
Yes, `find_all_refs` and [`process_definition`](https://github.com/rust-analyzer/rust-analyzer/blob/5dd8f8e26f2a62f5e7e4da50dcdfde344f6d31b9/crates/ra_ide/src/references.rs#L182) do not work for marco args, It should not be too hard to use [`descend_into_macros`](https://github.com/rust-analyzer/rust-analyzer/blob/1d729033eb70116a8e879b5233065e8fc7290930/crates/ra_ide/src/expand.rs#L72) and use that token to search.

**Comment by gilescope** [comment]
@kjeremy I've just checked today's release and goto def doesn't seem to work for arguments in a macro call. It would be *really* great if it did.

**Comment by edwin0cheng** [comment]
@gilescope I just check in master it works in the following simple case:

```
fn main() {
    let foo = 0;
    println!("{}", fo<|>o);
}
```
Would you mind telling us what code doesn't work?
