### ISSUE TITLE
Signature Parameter offsets

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#296]
Once #294 is merged `ParameterInformation` we will be able to return offsets into the `SignatureInfo.label` instead of a separate string (which is intended to be a substring of `SignatureInfo.label`). This would make the code a little simpler.

See https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp

**Comment by categulario** [comment]
It looks like #294 is merged already. If this is still waiting for someone to do it I'd like to help.

**Comment by categulario** [comment]
This was probably solved in e1e79cf064, consider closing the issue
