### ISSUE TITLE
No errors returned by rust-analyzer

### ISSUE THREAD

**Issue by jonathandturner** [rust-analyzer/rust-analyzer#2968]
I'm seeing a situation (potentially as a follow-on from https://github.com/rust-analyzer/rust-analyzer/issues/2909) where ra will give parser errors but won't give any errors from a cargo check.

The 'cargo check' animation plays, but then no errors are shown.

If I run `cargo check` by hand in the terminal, I see the errors.

This is in Pop! OS, using the latest stable Rust (1.41.0) and the latest ra from master.

**Comment by jonathandturner** [comment]
Just to follow up, I see `cargo check` sometimes return warnings and errors and sometimes not return anything.  I'll try to get a better repro.

**Comment by matklad** [comment]
I think this'll be fixed by https://github.com/rust-analyzer/rust-analyzer/pull/2959

**Comment by kiljacken** [comment]
Now that #2959 has landed, could you please retry on latest master?

**Comment by bjorn3** [comment]
I assume this has since been fixed. If it hasn't, please comment.
