### ISSUE TITLE
ra_cargo_watch: unsigned integer unferflow panic on empty main.rs file

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#2973]
# Reproduction
Tested on the following version (last commit): 12ac379c6c47be389499aa4b37c754cc478945cd
Note: the reproduction was built with debug symbols, i.e. with `debug = 2`:
https://github.com/rust-analyzer/rust-analyzer/blob/3f499489f79d05f8cc31b72055155e91bc78fddc/Cargo.toml#L7

[Link to youtube](https://www.youtube.com/watch?v=O5EC81IUgsg&feature=youtu.be)

# Shallow investigation

Underflow itself happens at this line:
https://github.com/rust-analyzer/rust-analyzer/blob/eba599d9863553d0f7d9d93f4c9050943da171cc/crates/ra_cargo_watch/src/conv.rs#L72

It seems that `cargo check` sends some invalid event data, because `cargo_metadata` docs claim that [`span.line_count` is 1-based](https://github.com/oli-obk/cargo_metadata/blob/master/src/diagnostic.rs#L58-L61):
```rust
    /// 1-based. The line in the file.
    pub line_start: usize,
    /// 1-based. The line in the file.
    pub line_end: usize,
```
Maybe this is their bug, however, I am not entirely sure, because I didn't work with `ra_cargo_watch` crate at all.
@kiljacken, can you take a look, please ?

**Comment by kiljacken** [comment]
I am unable to reproduce. With a completely empty file, I don't get a diagnostic due to `cargo` returning no spans, which makes sense. With a single space in the file, I correctly get a 1-indexed span for the diagnostic.

**Comment by Veetaha** [comment]
On my laptop it continues to reproduce stably on the latest version of `ra`. I'll try to get a repo with the reproduction

**Comment by Veetaha** [comment]
This is very very weird. I entirely copied the project `hello-world` that I opened in extension host to minimize it to the new folder `hello-world-2`, but the problem doesn't appear in it, it appears only in the original forlder `hello-world`

**Comment by Veetaha** [comment]
I see that when I copy the dir `target/.rustc_info.json` file changes when I open a vscode instance

**Comment by kiljacken** [comment]
we can probably just make it a saturating sub and call it good, will do that tomorrow, just to avoid crashes in debug on bad input :)

**Comment by Veetaha** [comment]
Hmm... I see I used 1.42 nightly there ...

**Comment by Veetaha** [comment]
I don't know why when I copy the project and open it in the extension host `target/.rustc_info.json` gets overriden from this
```
{
    "rustc_fingerprint": 3114702442570252495,
    "outputs": {
        "1164083562126845933": ["rustc 1.42.0-nightly (b5a3341f1 2020-01-20)\nbinary: rustc\ncommit-hash: b5a3341f1b8b475990e9d1b071b88d3c280936b4\ncommit-date: 2020-01-20\nhost: x86_64-unknown-linux-gnu\nrelease: 1.42.0-nightly\nLLVM version: 9.0\n", ""],
        "4476964694761187371": ["___\nlib___.rlib\nlib___.so\nlib___.so\nlib___.a\nlib___.so\n/home/veetaha/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu\ndebug_assertions\nproc_macro\ntarget_arch=\"x86_64\"\ntarget_endian=\"little\"\ntarget_env=\"gnu\"\ntarget_family=\"unix\"\ntarget_feature=\"fxsr\"\ntarget_feature=\"mmx\"\ntarget_feature=\"sse\"\ntarget_feature=\"sse2\"\ntarget_has_atomic=\"16\"\ntarget_has_atomic=\"32\"\ntarget_has_atomic=\"64\"\ntarget_has_atomic=\"8\"\ntarget_has_atomic=\"ptr\"\ntarget_has_atomic_load_store=\"16\"\ntarget_has_atomic_load_store=\"32\"\ntarget_has_atomic_load_store=\"64\"\ntarget_has_atomic_load_store=\"8\"\ntarget_has_atomic_load_store=\"ptr\"\ntarget_os=\"linux\"\ntarget_pointer_width=\"64\"\ntarget_thread_local\ntarget_vendor=\"unknown\"\nunix\n", ""],
        "6783195907413256411": ["___\n", ""]
    },
    "successes": {}
}
```
to this
```
{
    "rustc_fingerprint": 9635345540727848879,
    "outputs": {
        "1164083562126845933": ["rustc 1.41.0 (5e1a79984 2020-01-27)\nbinary: rustc\ncommit-hash: 5e1a799842ba6ed4a57e91f7ab9435947482f7d8\ncommit-date: 2020-01-27\nhost: x86_64-unknown-linux-gnu\nrelease: 1.41.0\nLLVM version: 9.0\n", ""],
        "4476964694761187371": ["___\nlib___.rlib\nlib___.so\nlib___.so\nlib___.a\nlib___.so\n/home/veetaha/.rustup/toolchains/stable-x86_64-unknown-linux-gnu\ndebug_assertions\nproc_macro\ntarget_arch=\"x86_64\"\ntarget_endian=\"little\"\ntarget_env=\"gnu\"\ntarget_family=\"unix\"\ntarget_feature=\"fxsr\"\ntarget_feature=\"sse\"\ntarget_feature=\"sse2\"\ntarget_os=\"linux\"\ntarget_pointer_width=\"64\"\ntarget_vendor=\"unknown\"\nunix\n", ""]
    },
    "successes": {}
}
```

**Comment by Veetaha** [comment]
@matklad, do you have any ideas on why `.rustc_info.json` in the original project is not overriden with `1.41` data, but remains the same when I open the extension host?

**Comment by SomeoneToIgnore** [comment]
Can `rustup override` be involved somehow?
Run `rustup override list` to see all of them.

**Comment by Veetaha** [comment]
@SomeoneToIgnore yes, you are right, I see `hello-world` directory in the output of `rustup override list`. So this means that when I open this dir in vscode, it `rust-analyzer` uses nightly cargo, doesn't it?

**Comment by SomeoneToIgnore** [comment]
It means what whatever rust tooling related thing (including cargo) you try to do in that directory, `nightly` toolchain will be forced to be used.
RA uses the same rust tooling hence uses nightly implicitly.

**Comment by Veetaha** [comment]
Okay, I think I should forward this as a regression report to `rustc` team then...

**Comment by Veetaha** [comment]
@kiljacken I think you should not add a saturation here, an `assert!()` at max. I've filed a bug to `cargo` repo [here](https://github.com/rust-lang/cargo/issues/7861)

**Comment by lnicola** [comment]
Beware, I've seen stuff break when renaming a project directory without a follow-up `cargo clean`.

**Comment by Veetaha** [comment]
@lnicola thank you for the precaution. For anyone curious I've created a [repo with the reproduction](https://github.com/Veetaha/cargo-check-regression-1.42-nightly).

**Comment by Veetaha** [comment]
I'll close the issue since this is a regression of `rustc-1.42-nightly`.
