### ISSUE TITLE
Cannot inference certain type.

### ISSUE THREAD

**Issue by crlf0710** [rust-analyzer/rust-analyzer#2984]
Repro repo: 
https://github.com/crlf0710/ra_bug_repo

rustc is able to inference the type of variable `_struct_data`, while ra only shows "{unknown}".

**Comment by flodiebold** [comment]
The `syn::DataStruct` type is generated by a macro; I assume there's something in there we can't handle. I haven't checked in detail though.

**Comment by kiljacken** [comment]
My short analysis is that we can't resolve `into_data_struct()` because it is generated by a procedural macro `easy_ext::ext`. We don't currently support proc macros.

**Comment by flodiebold** [comment]
I don't think that's the problem, since we ignore attribute macros completely, so this just looks like a normal impl.

**Comment by jonas-schievink** [comment]
The `impl syn::Data` doesn't work here, because the crate isn't the one defining `syn::Data`. That means this is just #6029 – it would work if we expanded the attribute macro.
