### ISSUE TITLE
Show secundary spans for errors

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#2996]
Especially for borrowck errors it is very hard to see the problem by just looking at the primary error message and span. For those the secondary error messages and spans (those with `--` instead of `^^`) are often necessary to understand the error.

Another option would be to show the rendered error as computed by rustc.

**Comment by kjeremy** [comment]
Would `DiagnosticRelatedInformation` https://microsoft.github.io/language-server-protocol/specifications/specification-current/#diagnostic help?

**Comment by kiljacken** [comment]
We already provide the related information based on secondary spans from `cargo`, so in editors supporting showing those in a meaningful way that helps.

I'd be open to showing the full error message on hover, if that is possible, but doing it in the problems pane is problematic if the editor is using a non-monospace font.

**Comment by Speedy37** [comment]
Add an option so it can be disabled if needed.
Another way might be to show the cargo check output in a dedicated terminal.

**Comment by bjorn3** [comment]
> Another way might be to show the cargo check output in a dedicated terminal.

Showing the `cargo check` output directly won't work, as we request the output to be formatted as json to be able to parse it much more easily.

**Comment by lnicola** [comment]
It's still not obvious, but we now show these:

![image](https://user-images.githubusercontent.com/308347/105742824-a70d1780-5f44-11eb-9f5e-90190ddb6277.png)

![image](https://user-images.githubusercontent.com/308347/105742837-ab393500-5f44-11eb-9bf3-9c6aae27f4f4.png)
