### ISSUE TITLE
Type hint popup is misplaced in macros

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#3000]
tldr:

![image](https://user-images.githubusercontent.com/3784017/73662906-32a3ed80-46cf-11ea-97bb-b83b88942231.png)

Note the beam cursor is placed on `e` near the end of the line, inside the `format!` macro. Also note the type popup is placed as if I've just hovered the closure's formal parameter `e: Error`.

It gets even weirder if line breaks are present:
![image](https://user-images.githubusercontent.com/3784017/73663133-93332a80-46cf-11ea-8104-be4c4d2759ec.png)

```
commit 856e4ba126ae776753f38c00593c02c4f43be510 (HEAD -> master, origin/staging, origin/master, origin/HEAD)
Merge: 9006cec49 f08297983
Author: bors[bot] <26634292+bors[bot]@users.noreply.github.com>
Date:   Sun Feb 2 14:05:23 2020 +0000

    Merge #2979
```

P.S.: 3000 get! :yum:

**Comment by 0x7CFE** [comment]
Looks like the issue still exist in recent builds (a regression?).

Cursor is placed on `mem` inside `println!` macro, but the type hint popped up waaaay above and to the left (see the second line):
![image](https://user-images.githubusercontent.com/3784017/75094677-228d7880-55c0-11ea-9acd-7f0a8375ffdd.png)

```
commit 2cbe8a4c4be2a69b27c248ab96341c2336f983cd
Merge: 7836720f2 5a6e770f9
Author: bors[bot] <26634292+bors[bot]@users.noreply.github.com>
Date:   Sat Feb 22 12:31:30 2020 +0000

    Merge #3263

```

**Comment by edwin0cheng** [comment]
Um... it is because println! is a recursive macro, and unfortunately the `original_range` function used in #3228 is do not support recursive macro. 

https://github.com/rust-analyzer/rust-analyzer/blob/ff2d77bde6acffc5e4c42878606b3d6d92300e11/crates/ra_ide/src/expand.rs#L37 

I will fix it in these day. Thanks for your report !

**Comment by edwin0cheng** [comment]
Since #3314 is merged, @0x7CFE Would you mind to test it again?

**Comment by 0x7CFE** [comment]
@edwin0cheng, I've just built revision 2dee0779e99 from the repo and it works… kinda :sweat_smile: 

Original issue was fixed, indeed :tada:. However, I found yet another way to break popup placement:

![image](https://user-images.githubusercontent.com/3784017/75355513-3519f180-58e1-11ea-8cde-db96b7909d37.png)

I placed mouse pointer to format literal of the `println!` macro and again, type hint popup is somewhere midway to the stratosphere.

**Comment by edwin0cheng** [comment]
Thanks @0x7CFE, I think I know what happened here, submit a PR to fix it (kinda).

**Comment by 0x7CFE** [comment]
> Thanks @0x7CFE, I think I know what happened here, submit a PR to fix it (kinda).

Unfortunately, as of revision 913cdcee8f0fe4373627d10d756949b970bcf5c2 it still fails. All symptoms remained the same.

**Comment by edwin0cheng** [comment]
Ah... that PR fixed #3135 case, but this one is a little bit complicated.
The problem here seem to be related to `println` used a bulitin macro `format_args_nl`, which currently just a fake implementation which return an empty string and do not support macro token mapping. 

A proper error recovery handling will be needed to fix this bug...

**Comment by edwin0cheng** [comment]
Update: #3350 ignore hover on token inside bulitin macro such that it should be fixed. I tested the following case and it works (no hover popup)

```rust
println("he<|>llo", 1);
```

**Comment by 0x7CFE** [comment]
Yes, it works as expected (no misleading or misplaced popups are shown).

P.S.: I'm not sure, but it seems that this change broke type hint popup for the following case:
`println!("{} bytes:", mem.len()<|>);`

By placing cursor after `()` I expect editor to highlight the whole call expression and pop up it's type. Currently it works only outside of macros.

**Comment by 0x7CFE** [comment]
And I've just found yet another way to break type hint placement:

![image](https://user-images.githubusercontent.com/3784017/75545305-839dcc00-5a58-11ea-8640-1e17039e360f.png)

Mouse was pointed right between `()` of `vec.len()` expression.

**Comment by edwin0cheng** [comment]
> P.S.: I'm not sure, but it seems that this change broke type hint popup for the following case:
println!("{} bytes:", mem.len()<|>);

This is unfortunely a little bit hard to fix until we have a proper token mapping for buitlin macro. (quite a low priority I think). 

> Mouse was pointed right between () of vec.len() expression.
#3366 should fix it

PS: Thank you for the bug reporting !

**Comment by 0x7CFE** [comment]
> #3366 should fix it

Yep, fixed my case. Cheers!

**Comment by edwin0cheng** [comment]
I split the builtin macro bug in other issue and I will close this issue in favor of it. Feel free to reopen this if needed.
