### ISSUE TITLE
How to remove completely from VSCode?

### ISSUE THREAD

**Issue by silvioprog** [rust-analyzer/rust-analyzer#3005]
Hi.

This project is awesome and promising, but still very slow and unstable on my system (Fedora 30 through a AMD Ryzen 7 plus 6 GB RAM and 256 SSD).

So, is there any command to remove/uninstall it completely from VSCode?

TIA

**Comment by lnicola** [comment]
You should be able to uninstall it just like any other Code extension. There's also the LSP server in ~/.cargo/bin, which you might want to remove, but is not harmful on its own.

**Comment by matklad** [comment]
Remove the “rust-analyzer” extension.

**Comment by silvioprog** [comment]
Thank you very much for so quickly help guys! I'm going to back to this extension as soon as it is more stable. Thank you! :-)
