### ISSUE TITLE
Installation guide for prebuilt binaries

### ISSUE THREAD

**Issue by rmanosuthi** [rust-analyzer/rust-analyzer#3007]
Hi,

It's nice that there are prebuilt binaries available now, but I can't seem to find an easily accessible guide on first time setup for specifically that, not "build-from-source".

(I thought [this](https://github.com/rust-analyzer/rust-analyzer/releases/tag/guide-2019-01) might be it but turns out it's not.)

In my opinion this is quite important and should be in the project's README.md itself.

I can help with writing up a "Prebuilt installation" section once I know how to do it!

**Comment by bjorn3** [comment]
I think it should be as easy as putting `ra_lsp_server` in a directory in your PATH (for example `~/.cargo/bin`) and then installing the right extension for your editor.

**Comment by Veetaha** [comment]
Yes, just having `ra_lsp_server` in your $PATH environment variable should be enough.

Related issue about automatic downloading this artifact is #2988

**Comment by Veetaha** [comment]
Documentation on prebuilt binaries for VSCode was updated in #3053, though we still need to document this for non-VSCode editors...

**Comment by Veetaha** [comment]
@matklad, we can close this issue since #3071 has landed
