### ISSUE TITLE
enableEnhancedTyping might be broken, vscode-vim issues

### ISSUE THREAD

**Issue by Cobrand** [rust-analyzer/rust-analyzer#3013]
Hi, I downloaded and installed the master version of rust-analyzer, and it seems to have issues with the vscode vim extension. The issue is that Enter key always creates a newline, regardless of what mode we're in (in NORMAL mode, creates a newline when it shouldn't, as well as INSERT, and well as in commands, for instance :wa<enter> keeps :wa in the command, but just creates a newline where the cursor is, which is a totally different behavior than previously.)

I suspect enableEnhancedTyping is broken, but I might be wrong, regardless, the setting in vscode is greyed, which might indicate that the setting doesn't matter anymore?

![config](https://imgur.com/psM8Zqt.png)

Although disabling and enabling it still shows the hint "changing enhanced typing requires a reload".

I ran a git bisect starting from 912776fd (good) to c9e1aab88 (bad), and I found b70ad7e5f3d5242 is amongst the first to show this behavior, but the previous one, 58c007674b8c746b, doesn't work at all for enter (it does nothing).

It kinda makes sense since they both are related to enhanced typing, and the commits before and after are related to onEnter.

The last one to show the expected behavior is 73c36fdbd2060bd455ff , which I am going to personally use until this issue is fixed (if anyone sees this message with this issue...)

**Comment by bjorn3** [comment]
This is caused by #2981, which was actually supposed to improve interaction of enhancedTyping and the vim extension.

**Comment by Veetaha** [comment]
[I suppose this one could be the cause](https://github.com/rust-analyzer/rust-analyzer/pull/2981/files#diff-0099aced0b5826ac85b37c58f68dcf96L31-L33). We didn't preserve the if around `onEnter` handler.

**Comment by Veetaha** [comment]
@Cobrand I think we removed that `"enableEnhancedTyping"` config option. If you remove `enter` key-binding it should work alright:
![ra-enhanced-typing](https://user-images.githubusercontent.com/36276403/73878276-f4d7ce00-4862-11ea-91fe-ffd985262c89.gif)

A am not sure whether this is the best design, maybe we should better document it? @matklad  what do you think?

**Comment by vitorenesduarte** [comment]
Removing the `enter` key-binding fixed the issue for me.

**Comment by matklad** [comment]
Yep, we need to document that the new way to do this is to disable the keybinding.

**Comment by Cobrand** [comment]
Instead of removing it, changing the condition to `editorTextFocus && !suggestWidgetVisible && !vim.active && editorLangId == 'rust'` works as well, however I'm not sure if it works if the extension is disabled (Enter works then, but I don't know if it's from the default behavior or the onEnter event).

Ideally if there was a way to say "if the vim extension is enabled AND !vim.active" that would be perfect and we could include that directly in the shortcut without changing the doc, but since it doesn't appear to be javascript, I don't really know if it's even possible to test that.

**Comment by Veetaha** [comment]
@Cobrand didn't know about that `!vim.active` thing. Thank you for the idea, I like it! I'll investigate the behavior with disabling `rust-analyzer` once I get to it.

**Comment by jonasbb** [comment]
A better alternative to `!vim.active` would be `vim.mode != 'Insert'`, this way the advanced typing works while typing, but when entering the command mode of vim (`:`) it is disabled.
I tested it with saving (`:w`) and replacing (`:s/a/b/g`) and they work both as expected.

```
editorTextFocus && !suggestWidgetVisible && editorLangId == 'rust' && vim.mode == 'Insert'
```

**Comment by Veetaha** [comment]
@jonasbb, thank you for the hint! Unfortunatelly, this is currently not a high priority, if you managed to achieve the behavior you've just described, we would appreciate accept a PR for this one!

**Comment by Phrohdoh** [comment]
Disabling the keybinding causes the extension host to unexpectedly terminate every single time, without fail so that isn't going to be a working solution.

**Comment by Veetaha** [comment]
@Phrohdoh , **that** is very interesting. Does VSCode terminate right-away without any error report?
I'd like to see a reproduction for this... Might I ask you to describe the steps you follow to see a crash?
Also what is the output of you `VSCode > Help > About` window and might I ask you to send the console output you can find when pressing <kbd>Ctrl+Shift+P</kbd> and executing the command `Toggle Developer Tools` then going to `Console` tab?

**Comment by Phrohdoh** [comment]
After playing with different combinations of extensions this seems to be caused by RA's `onEnter` and _something_  [Tree Sitter] is doing.

[Tree Sitter]: https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-tree-sitter

**Comment by yoshuawuyts** [comment]
@Phrohdoh hit the same issue here too; uninstalling tree-sitter solved the issue for me.

**Comment by Veetaha** [comment]
I'll try to look into this, though I am not a vim user at all...

**Comment by Veetaha** [comment]
@Phrohdoh @yoshuawuyts 
FYI: I guess I've solved the mystery with tree-sitter in https://github.com/rust-analyzer/rust-analyzer/issues/3515#issuecomment-596207493
