### ISSUE TITLE
Hide type hints for constructor return values

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#3022]
It would be nice if rust-analyzer could omit the type hint for infallible constructors, for example

```rust
let mut builder = MyUsefulThingyBuilder::new();
```

and maybe for fallible constructors in conjunction with the `?` operator too:

```rust
let thing = AnotherPrettyLongType::new(arg_a, arg_b)?;
```

as the type hints can cause the actual expression to go off screen and don't add anything in these cases. I'm not entirely certain what would be good criteria for considering something a constructor, but as a conservative approach only functions returning `Self`, `Option<Self>` or `Result<Self, E>` could be considered. Although IMHO it would be nice for conversions to also not receive type hints if invoked like a constructor:

```rust
let x = Type::from(something);
let y = Type::try_from(something)?;
```

**Comment by bjorn3** [comment]
Note for implementation: sometimes the `new` method returns a builder instead of the type itself, so it would be necessary to check for this before ommitting the type hint.

**Comment by kjeremy** [comment]
Is this just a display issue?

**Comment by flodiebold** [comment]
I think it's reasonable to leave out the type hint in any instance of the pattern
```rust
let x = Type::some_method(...arguments...);
```
or the same with `?` if `x` is of type `Type`.

**Comment by Veetaha** [comment]
As a sidenote, see the [configurable heuristics reference of Intelij](https://www.jetbrains.com/help/rider/Inline_Parameter_Name_Hints.html#configuring-parameter-name-hints), where they describe the ways to disable type name hits for certain patterns.
