### ISSUE TITLE
Hide argument name hint for single-element argument lists on fn's with the same name

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#3023]
`anyhow::Context` has a method `context` with an argument named `context`. Having the latter shown by ra doesn't add any value. It would be nice to generally omit the argument name hint for functions like

```rust
fn foo(foo: T);

impl Block {
    // maybe only omit argument name hint if called as a method
    fn foo(self, foo: T);
}
```

**Comment by Veetaha** [comment]
**As a sidenote**
I know that Intelij provides functionality to disable parameter name hints in specific cases.
Their [configurable heuristics reference for that](https://www.jetbrains.com/help/rider/Inline_Parameter_Name_Hints.html#) will be very helpful.

**Comment by kjeremy** [comment]
Are you talking about `SignatureHelp` (the popup you get when calling a function and filling out parameteres) or inline parameter hints?

**Comment by jplatte** [comment]
I'm talking about inline parameter hints.

**Comment by bjorn3** [comment]
This is implemented

![image](https://user-images.githubusercontent.com/17426603/102696617-ece10c80-422f-11eb-8ee6-d61f830b64b2.png)

![image](https://user-images.githubusercontent.com/17426603/102696633-04b89080-4230-11eb-8b10-e71840f32d58.png)

**Comment by jhpratt** [comment]
Could this be improved to be case-insensitive? I have a parameter named `min` with an argument named `MIN_FOO`. The same reasoning applies.

**Comment by SomeoneToIgnore** [comment]
Yes, this should be pretty straightforward, the change can be done here:

https://github.com/rust-analyzer/rust-analyzer/blob/f7a15b5cd1df58e46066bbd27c90cb1ad7f9c316/crates/ide/src/inlay_hints.rs#L346

this + a new example added to tue test should be enough.

**Comment by jhpratt** [comment]
Thanks @SomeoneToIgnore! I just created #7215 for the change itself. Where should the test go? I can add that in another commit (or squash them/amend, I don't really care).

**Comment by SomeoneToIgnore** [comment]
Thanks for the PR 😄 
We have a great `omitted_parameters_hints_heuristics` test that covers all such cases, IMO we can add a few lines inside it.
Does not matter if it's a separate commit or any other type, last time I checked, we did not enforce any particular rule.
