### ISSUE TITLE
Unable to parse `unsafe async fn`

### ISSUE THREAD

**Issue by LucioFranco** [rust-analyzer/rust-analyzer#3025]
I am running into a reproducible bug with ra that says `Syntax Error: expected existential, fn, trait or impl` right in between the `async` and `unsafe`. Running the check manually via `cargo` seems to report no errors.

```rust
struct Foo;

impl Foo {
	pub async unsafe fn bar() {}
}
```

should reproduce it.

Reference sha `d92a15c1637860a669970142abe37d1daf5f2c73`

**Comment by kiljacken** [comment]
If I recall, this is expected, no? The correct syntax is `pub async unsafe fn` (async before unsafe), see rust-lang/rust#61319

**Comment by LucioFranco** [comment]
Thanks for the quick fix!
