### ISSUE TITLE
Cursor position is not right in inlay message when using arrow key to navigate.

### ISSUE THREAD

**Issue by davyzhang** [rust-analyzer/rust-analyzer#3027]
master branch
I can not move cursor behind "b" in this case
![Screen-Recording-2020-02-06-at-3 16 15-PM](https://user-images.githubusercontent.com/576863/73906790-0d43f900-48f4-11ea-84e2-fa4dafa90756.gif)

**Comment by lnicola** [comment]
Duplicate of #1623.
