### ISSUE TITLE
rust-analyzer failed to load workspace

### ISSUE THREAD

**Issue by aodhneine** [rust-analyzer/rust-analyzer#3032]
Using Visual Studio Code Insiders,  version:
```
Version: 1.42.0-insider
Commit: 536757fcc0308b444cbe9ce04f1f013903641ae3
Date: 2020-02-05T16:51:11.916Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.5.2-arch1-1
```

I have no other extensions installed but rust-analyzer.

I installed rust-analyzer following `docs/user/README.md`, but when opening any folder or adding it to workspace, it fails with the following error:
```
rust-analyzer failed to load workspace: No such file or directory (os error 2)
```
and with information:
```
workspace loaded, 0 rust packages
```

This happens with extension and `ra_lsp_server` build from master **and** when downloaded from Github releases.

There's no messages in output.
`Rust Analyzer: Status` shows:
```
no workspaces

analysis:
2 (8kb) files
0 (0b) symbols
1 trees, 1 retained
0 trees, 0 retained (macros)


memory:
0b allocated 0b resident
gc 110 seconds ago

requests:
*   1 textDocument/codeAction             5ms
    2 rust-analyzer/inlayHints            1ms
    4 textDocument/documentSymbol         3ms
    3 rust-analyzer/decorationsRequest    6ms
    5 textDocument/codeLens               3ms
    6 textDocument/hover                  0ms
    7 codeLens/resolve                    0ms
    8 textDocument/hover                  0ms
    9 textDocument/codeAction             0ms
   11 rust-analyzer/inlayHints            1ms
```

I also tried to use latest stable Visual Studio Code, but with no result there either.

I'm using fish-shell, this is my `$PATH`:
```
/home/kyu/bin /home/kyu/sys/bin /home/kyu/sys/local/bin /usr/local/sbin 
 /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl
```
`ra_lsp_server` is located in `/home/kyu/sys/local/bin`
(*Please, don't ask why do I have such a weird folder structutre. I'm ashamed of it myself enough.*)

**Comment by bjorn3** [comment]
Is your crate in a subfolder of the workspace?

**Comment by aodhneine** [comment]
No, it's either the only folder of the workspace or I just `open folder`.

**Comment by aodhneine** [comment]
This is what happens:

![2020-02-06-175745_817x766_scrot](https://user-images.githubusercontent.com/11488344/73964551-4dae7180-490a-11ea-9078-185bf892d4b9.png)
![2020-02-06-175817_817x766_scrot](https://user-images.githubusercontent.com/11488344/73964553-4e470800-490a-11ea-9034-364e9f1f181c.png)

**Comment by bjorn3** [comment]
What does the error message say after `No such file or directory`? (You can click on the `^` that shows when you hover over it to reveal the rest.)

**Comment by aodhneine** [comment]
It shows `rust-analyzer failed to load workspace: No such file or directory (os error 2)`

**Comment by bjorn3** [comment]
One guess: do you have the `rust-src` rustup component installed?

**Comment by aodhneine** [comment]
Yes, I have `rustc`, `rust-src` and `rust-dev`.

**Comment by aodhneine** [comment]
I still didn't have resolved the problem, but it seems like no one cares about this issue anymore.

**Comment by matklad** [comment]
@aodhneine I would advise against leaving comments like "no one cares about this issue anymore". Most people who work on rust-analyzer care a lot about it working great, but at the same time the amount of effort one needs to put in to make this happens far outweighs the available resources.

This in general applies to all open source and closed source problems: inferring that the issue does not get "enough" attention due to the lack of care is not really right (most time the issue is available time) and not really helpful (as it, to put it bluntly, makes the maintainers feel bad).

**Comment by matklad** [comment]
Regardless of this, thank you for the bug report :heart: ! It is helpful.

**Comment by aodhneine** [comment]
Thank you for the response! I was really tired and frustrated after three days of no one responding, but I think that letting my frustration out here was inappropiate, and I'm sorry for that.

Nevertheless, I hope that this bug report will help to improve such an awesome project (I used to use it few months ago without issues) and that it'll be resolved quickly. Feel free to ask if there's something I can help with.

**Comment by Veetaha** [comment]
I wish we could reproduce your bug, otherwise we have ideas of what file is missing. I tried looking over the code and indeed missing sysroot was my only suppositions.
I wish we could have all of your pc on our side ...

**Comment by aodhneine** [comment]
I think I resolved the issue. But I have no idea what happened or how I solved it. I cannot reproduce the bug anymore on my computer.

**Comment by aodhneine** [comment]
I think the issue might be with how I store programs on my computer.

Basically, every program that I install from source or from binary package (like rust) I keep in separate directory and just symlink various files to the places they're expected to be - so in this case I kept `~/.cargo` and `~/.rustup` as symlinks to `~/sys/local/share/cargo` and `~/sys/local/share/rustup`.
And usually this works fine, I have home directory clean of folders and structure I can easily naviagate through and manage.

However it seems like this time something went wrong, and probably `rustup` was keeping location of installed components incorrectly. (But I have no idea how rustup works) 
When I reinstalled rust, I first installed all required components and launched vscode, which (expectedly) was working fine. Then I moved the `.cargo` and `.rustup` into the folders mentioned above, but this didn't break anything.

So... yes, I still have no clue what happened.

**Comment by aodhneine** [comment]
I cannot reproduce the issue anymore, even when doing the same exact steps I did when installed rust and this bug occured.
It seems to be a heisenbug, should I close this issue then, or does it still make any sense to investigate it?

**Comment by matklad** [comment]
I think it might make sense to close. I've opened https://github.com/rust-analyzer/rust-analyzer/issues/3085 to make sure that the next time we have a better error message to work with.

**Comment by aodhneine** [comment]
Okay, thanks everyone for spending your time trying to fix this. :heart:

**Comment by Veetaha** [comment]
@aodhneine , thank you for the report, we do value all of them, I hope we will tackle your bug once we are done with better error loging!

**Comment by sanket1729** [comment]
For reference, I received the same error when I tried running vscode with rust 1.22.0, running vscode again with the stable(1.45) fixed it.

**Comment by Veetaha** [comment]
@sanket1729 I recommend you to open `Output > Rust Analyzer Client` and if present `Output > Rust Analyzer Language Server` (without `Trace`) and send these logs to us next time you see something weird

**Comment by darman96** [comment]
I have a similar error:

```quote
[ERROR rust_analyzer::reload] failed to switch workspaces: rust-analyzer failed to load workspace: "cargo" "--version" failed: No such file or directory (os error 2)
```

I am working inside a dev container, and cargo is installed under "$HOME/.cargo" also present in $PATH.+
I attached the Output of Rust Analyzer Client as well.
[Rust Analyzer Client Output.txt](https://github.com/rust-analyzer/rust-analyzer/files/6580405/Rust.Analyzer.Client.Output.txt)

**Comment by y1rn** [comment]
> I have a similar error:
> 
> ```
> [ERROR rust_analyzer::reload] failed to switch workspaces: rust-analyzer failed to load workspace: "cargo" "--version" failed: No such file or directory (os error 2)
> ```
> 
> I am working inside a dev container, and cargo is installed under "$HOME/.cargo" also present in $PATH.+
> I attached the Output of Rust Analyzer Client as well.
> [Rust Analyzer Client Output.txt](https://github.com/rust-analyzer/rust-analyzer/files/6580405/Rust.Analyzer.Client.Output.txt)

similar issue

**Comment by bjorn3** [comment]
Is rust-analyzer running inside or outside the container? Can you get the environment variables of rust-analyzer to check if `~/.cargo/bin` is indeed in `PATH`. (eg `cat /proc/$pid/environ | tr '\0' '\n'` where pid is the pid of rust-analyzer as seen inside the container if you run it inside the container or as seen outside the container if you run it outside. In the latter case you may need to run it as root.)

**Comment by muozdemir** [comment]
I have a similar issue, too. I have mac as host and linux as remote. using vscode remote.
I tried many options but no luck so far. `~/.cargo/bin` is in the PATH of remote linux machine

`rust-analyzer failed to load workspace: "cargo" "--version" failed: No such file or directory (os error 2)`

[rust-analyzer-cargo-fails.txt](https://github.com/rust-analyzer/rust-analyzer/files/6627400/rust-analyzer-cargo-fails.txt)

**Comment by createyourpersonalaccount** [comment]
When I get this error on Emacs with LSP, it is displayed to the user until an action is taken, but it seems to take care of itself. That is, although the error is displaying, there seems to be some work in the background related to rust-analyzer (I see a count of items processed) and I'm assuming that it's just a dangling error displayed. For what it's worth, at least for my case.

**Comment by rikusen0335** [comment]
Still got the same error:
```
[ERROR rust_analyzer::reload] failed to switch workspaces: rust-analyzer failed to load workspace: "cargo" "--version" failed: No such file or directory (os error 2)
```

I also have Windows 10 as host, and Fedora Linux as remote (for develop machine). Using vscode remote feature.
And I'm using asdf-vm as rust's version control. `which cargo` will show `~/.asdf/shims/cargo` as binary path.

`cargo` can be ran in the zsh shell by `cargo --version`, and it shows `cargo 1.54.0 (5ae8d74b3 2021-06-22)`

Trace log: [rust-analyzer_cargo-not-exists.txt](https://github.com/rust-analyzer/rust-analyzer/files/7036498/rust-analyzer_cargo-not-exists.txt)

**Comment by rikusen0335** [comment]
Idk if this helps since I'm not good at program, but probably:
![image](https://user-images.githubusercontent.com/19174234/130557806-af9b9494-9a53-4c62-a8a3-1e392043e9a6.png)

According to the rust-analyzer source, [THIS CODE](https://github.com/rust-analyzer/rust-analyzer/blob/ce926aebc4461e38535047958c0b6f72b7a0c0ea/xtask/src/install.rs#L141) uses `cmd!()` by xshell, and it uses `bash` to run script, so the original command `cargo --version` may resolved as like `"cargo" "--version" <- is resolved as 'file name'?`

Again I am not much good at program so idk if this helps, but just information...

**Comment by createyourpersonalaccount** [comment]
>1) uses `cmd!()` by xshell, and it uses `bash` to run script, so the original command `cargo --version` may resolved as like `"cargo" "--version" <- is resolved as 'file name'?`

If you believe it attempts to run —version as a program, maybe create such an empty program and place in your binary path and try again. If you get different error, you are right…

**Comment by rikusen0335** [comment]
@createyourpersonalaccount Yeah for now as I edited, it is not right. I was just a fool, nvm xd

**Comment by DrSensor** [comment]
In case someone bumps into similar issues, here is the solution https://github.com/rust-analyzer/rust-analyzer/issues/6849#issuecomment-827585378

**Comment by tijlleenders** [comment]
Thanks DrSensor!
Didn't try this solution but I did reproduce this issue by opening VSCode from Windows OS instead of from WSL2.

Opening Code from WSL2 terminal "code ." avoids the issue. Bottom left corner of VSCode will show if you're connected.
![image](https://user-images.githubusercontent.com/44887755/139729952-9c83dc88-b7a8-4e0b-9a90-abc736d173dc.png)

**Comment by Dequog** [comment]
After trying various things up above, I uninstalled and reinstalled vscode which fixed the problem for me.

**Comment by lizhanhui** [comment]
In case someone got the same issue, here is how I got the problem and the fix.
I am using VSCode Remote with rust-analyzer. For some reason, I have to customize cargo/rust installation path, by way of exporting `CARGO_HOME=/path/to/custom/dir/.cargo` and `RUSTUP_HOME=/path/to/custom/dir/.rustup`.

After reinstallation, cargo works well from the command line, while the rust-analyzer VSCode plugin keeps reporting 
```
rust-analyzer failed to load workspace: "cargo" "--version" failed: No such file or directory (os error 2)
```

`killall node` fixes this issue in the end.

**Comment by mkalvas** [comment]
Rust worked fine for me locally and on remote (mac with remote dev via ssh to a linux machine), but @lizhanhui's hint helped me.

> `killall node` fixes this issue in the end.

I used `pgrep node | xargs ps -fp` to find node processes (on the host machine) and found that some of them were older than the rust installation. So I think that the process was started without the commands present in the env/shell. I killed those older processes, which crashed my ssh remote dev connection on the client, but it restarted on the host automatically and my client reconnected automatically.

This isn't the most reproducible, but this could be why people are seeing this. If they started the vscode remote server process before rust/cargo existed and it needs a reboot to source the env right.

**Comment by rachtsingh** [comment]
I have this issue (even with `CARGO_HOME` set), in my WSL installation. I don't know if it's precisely that setting those environmental variables will fix the issue, since even after setting those variables and running `killall node`, I still have issues on the next time I load VSCode (and I've restarted WSL, my host computer, etc. several times since).

For future searchers, running `code .` in the directory to create the VSCode window instead of using the "Open window" dialog seems to reset it correctly.

**Comment by HemanthDavuluri** [comment]
Upgrade your rust-analyzer extension to the pre-release(v0.4.1525) one. This fixed the issue on my Macbook Pro m1.

**Comment by Oakento** [comment]
I fix it by editing settings.json in the .vscode folder

**Comment by Hangghost** [comment]
> I fix it by editing settings.json in the .vscode folder

Me too. I also met the problem just 5 min ago.
I found the **.vscode** folder record the same path that error messenger is. 
Simply, I just close the VS code window and delete the **.vscode** folder.
(or you could just delete the "rust-analyzer.server.extraEnv")
When I re-opened it is work automatically.

**Comment by strikus** [comment]
juse use command 
cargo new file_name 
in ur terminal and resrart the server by left click on rust analyzer extension downside the vs code

**Comment by gelmodev** [comment]
I encountered the same issue, but I managed to resolve it. Here's how I tackled it:

The directory structure of my worktree is as follows:

```
.vscode
└── settings.json
src
└── challenges
    └── some modules...
    lib.rs
    main.rs
Cargo.lock
Cargo.toml
```

Within the `.vscode` folder, there is a `settings.json` file that contains the following data:

```json
{
  "rust-analyzer.linkedProjects": [
    "./challenges/Cargo.toml"
  ]
}
```

As you can observe, I don't have a `./challenges/Cargo.toml` file because I initially created that folder as a library using `cargo new --lib` and later deleted it. This is why the incorrect path exists.

To resolve the issue, I simply modified the configuration to make rust-analyzer work again:

```json
{
  "rust-analyzer.linkedProjects": [
    "./Cargo.toml"
  ]
}
```

**Comment by groovenectar** [comment]
FYI, in my case (Linux Mint) this was resolved by using the IDE's `.deb` package instead of the Flatpak

Presumably a Flatpak permissions issue on the IDE that could be remedied with Flatseal (I did not try that)
