### ISSUE TITLE
No type inference for slice patterns

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#3043]
Minimal reproduction:

```rust
let xs: &[f64] = &[0.0];
match xs {
    &[x] => {
        x; // {unknown}
    }
    _ => {}
}
```

**Comment by flodiebold** [comment]
We already have a `Pat::SlicePat` variant, so the first step would be implementing lowering from AST to `hir_def::expr::Pat` [here](https://github.com/rust-analyzer/rust-analyzer/blob/5397f05bfe7f3b18229a65040c6685e762b2f9a3/crates/ra_hir_def/src/body/lower.rs#L624). After that, we need to implement the actual inference [here](https://github.com/rust-analyzer/rust-analyzer/blob/5397f05bfe7f3b18229a65040c6685e762b2f9a3/crates/ra_hir_ty/src/infer/pat.rs#L177); basically, check whether the `expected` type is a slice, then recursively call `infer_pat` on the parts (for the prefix and suffix patterns, the expected type should be the element type; for the rest pattern, it'll be the slice type itself.) It's a bit similar to tuple patterns, which are implemented a bit further up:
https://github.com/rust-analyzer/rust-analyzer/blob/5397f05bfe7f3b18229a65040c6685e762b2f9a3/crates/ra_hir_ty/src/infer/pat.rs#L115-L129

**Comment by jplatte** [comment]
Forgot to remove the 'will fix' from the PR. Can't reopen the issue though.
