### ISSUE TITLE
Incorrect inference of `match` expression result

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#3046]
```
commit 5aba5a756a19a54d5c4edd51d8055db36182688b
Merge: a4431e830 56e3fbe58
Author: bors[bot] <26634292+bors[bot]@users.noreply.github.com>
Date:   Thu Feb 6 23:00:07 2020 +0000

    Merge #3042
```

The [following snippet](
https://github.com/bytecodealliance/wasmtime/blob/70345aff31b97df410014da2103bb6e54ca79587/crates/environ/src/compilation.rs#L75-L81) from wasmtime repo is mistakenly inferred as `!` instead of `FrameUnwindKind`:

![image](https://user-images.githubusercontent.com/3784017/74027434-b107d480-49da-11ea-8c6d-a45d2f2ac034.png)

**Update:** aside of [local discussion](https://github.com/rust-analyzer/rust-analyzer/issues/3046#issuecomment-583361328) about known [issue with local imports](https://github.com/rust-analyzer/rust-analyzer/pull/1945), this issue boils down to

```rust
let x = match 0 {
    _ => y,
};
```

…where `x` is inferred as `!` when it probably should be `{unknown}`.

**Comment by lnicola** [comment]
The following works:

```rust
enum E {
    A,
    B,
}

fn foo(e: E) -> E {
    let x = match e {
        E::A => 1,
        _ => {
            return E::B;
        }
    };
    E::A
}
```

Does "go to definition" work for `CallConv` and `FrameUnwindKind`?

**Comment by 0x7CFE** [comment]
Update: if I move [corresponding `use` imports](https://github.com/bytecodealliance/wasmtime/blob/70345aff31b97df410014da2103bb6e54ca79587/crates/environ/src/compilation.rs#L41-L44) to the topmost scope it all starts working as expected:

![image](https://user-images.githubusercontent.com/3784017/74028058-0ee8ec00-49dc-11ea-957c-8dc42ec8f697.png)

**Comment by 0x7CFE** [comment]
> Does "go to definition" work for CallConv and FrameUnwindKind?

Nope, it wasn't working before the import change. As you may see, on the first screenshot `CallConv` and `FrameUnwindKind` are not highlighted as types.

**Comment by lnicola** [comment]
Yeah, `use` in local scopes doesn't work too great: #1165.

**Comment by 0x7CFE** [comment]
> Yeah, `use` in local scopes doesn't work too great: #1165.

Oh, indeed. And @matklad's reply there states that probably this will not be resolved anytime soon. That's unfortunate :(

**Comment by lnicola** [comment]
Still, you could argue that the inference should work better. I think the issue is that `FrameUnwindKind` can't be resolved. The type of `match` should probably be `{unknown}`, not `!`.

It's probably a bug in #1945, but I don't really understand the code :cat:.

**Comment by 0x7CFE** [comment]
> The type of match should probably be `{unknown}`, not `!`.

Agree. It's very strange that type is inferred that way given that analyzer clearly does not have enough information.

**Comment by lnicola** [comment]
```rust
let x = match 0 {
    _ => y,
};
```

`x` gets inferred as `!`.

**Comment by lnicola** [comment]
Maybe you can update the first post with my example above, since it's simpler?

**Comment by flodiebold** [comment]
#3114 fixes the reduced case where there are no match arms that diverge, but if there's a diverging match arm (like in the original case), we'll still fall back to `!`. Interestingly, rustc seems to fall back to `()` in at least [some of these cases](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b95d52683069cc7c421c6f58e4beb8f2). This will require some further thought :thinking:

**Comment by 0x7CFE** [comment]
@flodiebold, as for the `()` issue [recent reddit post](https://www.reddit.com/r/rust/comments/f5nw1o/why_does_rust_infer_when_the_generic_type_cannot/) discusses similar behavior.

**Comment by lnicola** [comment]
Type inference works fine now for:

```
enum E {
    A,
    B,
}

fn foo(e: E) -> E {
    let x = match e {
        E::A => 1,
        _ => {
            return E::B;
        }
    };
    E::A
}
```

I think this can be closed.
