### ISSUE TITLE
ARM linux downloads an x86 plugin that does not work (vscode on Jetson Nano - probably same on Raspbery Pi)

### ISSUE THREAD

**Issue by paulirotta** [rust-analyzer/rust-analyzer#3076]
This worked on ARM devices until recent changes. It is not clear what changed in the build process that it needs to download even when building from source (both Nano and Macos).

Perhaps there is a work around? Macos works but I had to cancel past a retro-frightening "Need to install Java" popup. Java is already on the Nano (Ubuntu).

**Comment by matklad** [comment]
You need to override settings to use the binary in PATH instead of downloading one: https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user#installation-from-sources

**Comment by Veetaha** [comment]
Do we need to filter out x86 arm linux from being proposed to download the prebuilt binary?

**Comment by paulirotta** [comment]
The workaround for ARM is to:

1. Add `"rust-analyzer.raLspServerPath": "ra_lsp_server",` to VS Code settings, otherwise it will use the latest release from GitHub. (and this version is not ARM)

1. clone the repo and `cargo xtask install`

1. `git pull` and repeat step 2 periodically as this tool advances amazingly quickly. (Yay!)

I also like to `whereis code-oss` then `ln -s` in the path to launch it as `code` instead of `code-oss`. Hopefully more official support comes in the future.

**Comment by paulirotta** [comment]
> Do we need to filter out x86 arm linux from being proposed to download the prebuilt binary?

Yes, that would be helpful

**Comment by matklad** [comment]
FWIW, if someone is willing to invest time into setting up cross-compilation to ARM on our CI, I'd be fine with publishing arm artifacts as well.

I think this should be pretty straightforward, as we don't use native dependencies.

**Comment by matklad** [comment]
Also, I am glad to hear that folks use rust-analyzer on Arm and that it, apparently, just works :)
