### ISSUE TITLE
Consistently use `anyhow` in `ra_project_model`

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3085]
`ra_project_model` crate does a lot of interraction with other processes (`cargo` and `rustc`). It is bound to fail in interesting ways, so we need to make sure that the error reporting is top-notch. 

We should switch it to the `anyhow` crate and use `.context` method proacticaly to make sure that all errors are reported with context.

**Comment by matklad** [comment]
cc https://github.com/rust-analyzer/rust-analyzer/issues/3032

**Comment by matklad** [comment]
The crate in question is here:

https://github.com/rust-analyzer/rust-analyzer/blob/29f5e7eebf606c1929d5a77ad66624cd4f3fcf49/crates/ra_project_model/src/lib.rs

**Comment by adamrk** [comment]
I'm willing to take a stab at this.

**Comment by Veetaha** [comment]
Did #3119 close this @matklad  ?
