### ISSUE TITLE
"Play" symbol in "Run Test" code lens is emojified

### ISSUE THREAD

**Issue by TheV360** [rust-analyzer/rust-analyzer#3091]
https://github.com/rust-analyzer/rust-analyzer/blob/a836247de45d7187a3902c2f14034d2817dbfbc3/crates/ra_lsp_server/src/main_loop/handlers.rs#L760
(Introduced in #715)

You can see the issue on the second code lens line in this screenshot. I think it would look better if it blended in with the background, like on the first line here:
![image](https://user-images.githubusercontent.com/25177071/74182846-cb77c300-4c11-11ea-84f1-8da596c4f450.png)

This seems easy to fix, as someone could [attach this character](https://stackoverflow.com/a/38452396/) to the end of the emoji, or maybe use a similar-looking Unicode character.

**Comment by kjeremy** [comment]
I think I'm fine with that. I originally grabbed that character from an example or possibly another extension.

**Comment by Veetaha** [comment]
+1 for not using the emojified version, in vscode it looks very out of style. We can try to appy that fix, proposed by TheV360

**Comment by matklad** [comment]
but why we have two different arrows?

**Comment by TheV360** [comment]
@matklad I edited the top one (with developer tools) to not be emojified. Sorry if my wording was vague, I wrote the initial post in a hurry. They're usually both emojis.

**Comment by Veetaha** [comment]
Did #3126 close this @matklad ?

**Comment by hhiraba** [comment]
"Play" symbol is broken in my environment([gnome-terminal](https://wiki.gnome.org/Apps/Terminal) + [neovim](https://github.com/neovim/neovim) + [coc.nvim](https://github.com/neoclide/coc.nvim)).  

![image](https://user-images.githubusercontent.com/4624806/81504516-be5b9480-9324-11ea-89ce-35eacc68ad8c.png)
(`‣` is drawn by [coc.nvim](https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt#L427-L429))

I think it is not the analyzer's job to decorate with symbols.
So I want the symbol to remove or at least be configurable.
(For example, like [PIPENV_HIDE_EMOJIS](https://pipenv.kennethreitz.org/en/latest/advanced/#pipenv.environments.PIPENV_HIDE_EMOJIS))

**Comment by bjorn3** [comment]
Rust analyzer started using `\u{fe0e}` since #3126 and is still using it. This means that `‣` shouldn't be rendered as emoji.

https://github.com/rust-analyzer/rust-analyzer/blob/409c1a7f069799839a677784685cd184e3551db1/crates/ra_lsp_server/src/main_loop/handlers.rs#L761

**Comment by Veetaha** [comment]
As for me the problem was not fixed, I still see an emoji in vscode:
![image](https://user-images.githubusercontent.com/36276403/81506957-8f342b80-9302-11ea-8d87-9f95524d197b.png)

Should we reopen this issue? Or is there some editor config that influences this that we can specify in our docs?

**Comment by hhiraba** [comment]
@bjorn3 
I'm using latest release 2020-05-04. `rust-analyzer --version` displays 6148a94.  
Probably, some TUIs cannot interpret multiple Unicode variation selectors properly. (I also tried on Kitty and alacritty)  
As shown in my image at L12, gnome-terminal renders `"\u{25b6}\u{fe0f}\u{fe0e}"` as emoji.
(`\u{25b6}\u{fe0f}` is `▶️`)

How about change the symbol from `\u{25b6}\u{fe0f}\u{fe0e}` to `\u{25b6}`?

**Comment by Veetaha** [comment]
Yeah, this `\u{25b6} ` works for me in vscode, I think we should go for it here:
https://github.com/rust-analyzer/rust-analyzer/blob/bfb40a698dab10adcd1284ce4c7a2a10f36ba4e7/crates/rust-analyzer/src/main_loop/handlers.rs#L824-L825

**Comment by hhiraba** [comment]
> Just place a space after the arrow

If without space, does the symbol overlap with `R`? `\u{25b6}` has [ambiguous width](https://www.unicode.org/reports/tr11/tr11-38.html#Ambiguous). So it is rendered in half-width or double-width depending on the renderer regardless of actual font(glyph) width. Probably, analyzer cannot know both renderer behavior and font width. 

For that reason, I think the symbol is preferred to be configurable, like `ra_codelens_test_prefix="\u{25b6} "`. Does `rust-analyzer` already have any per-user config?
(Sorry I'm immature in `rust-analyzer` ... and also Rust itself)

**Comment by Veetaha** [comment]
No, the symbol doesn't overlap, it just touches `Run Test` too tight

**Comment by Veetaha** [comment]
I think letting select the symbol would be an overconfiguration...

**Comment by kjeremy** [comment]
Iirc the play symbol was recommended in a vscode changelog at one point.
