### ISSUE TITLE
Cannot download binary due to api rate limit

### ISSUE THREAD

**Issue by kwonoj** [rust-analyzer/rust-analyzer#3094]
published analyzer in marketplace, clicking download raises 

![image](https://user-images.githubusercontent.com/1210596/74191920-64561080-4c09-11ea-90e6-4e75c75c8998.png)

and manually hitting endpoint reveals it's due to 

![image](https://user-images.githubusercontent.com/1210596/74191954-70da6900-4c09-11ea-8543-2d4ddfc4112b.png)

looks like can gracefully handle non-expected api response & can give retry chances later.

**Comment by Veetaha** [comment]
How many times did you use click "Download now" button today xD ?
Anyway thank you for the report, this was unexpected, but will be fixed!

**Comment by kwonoj** [comment]
I did 2 times, it's api server hitting limit and not caused by individual presses N times.

**Comment by Veetaha** [comment]
We do issue two requests to GitHub. One for retrieving the information about the latest release and the second downloads the binary itself. Do you think this is because two of them are issued in a very short period of time?

**Comment by kwonoj** [comment]
It should be related and I think that also need to be improved. Main crux is total numbers of request in a given timeframe exceeded limit - most likely after plugin is released many ppl try to download binary in a short time frame.

**Comment by kwonoj** [comment]
Per https://developer.github.com/v3/ it's 5000 per hr, each individual fires 2 requests so 2500 download attempt will hit rate limit.

**Comment by bjorn3** [comment]
There is no api key used, so rate-limiting should be done one a per IP basis.

**Comment by Veetaha** [comment]
[Rate limiting](https://developer.github.com/v3/#rate-limiting):
> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

**Comment by kwonoj** [comment]
I am certain I did not make 60 requests per hr, I just installed and tried 2 times only 🤔

**Comment by Veetaha** [comment]
I also doubt that downloading the file counts as an API request ...

**Comment by niderhoff** [comment]
I have the same problem. I got 403 on the first try to download the rust-analyzer.
Then I tried to workaround that by manually installing it and putting it in PATH.
It is found by the extension (seems so?):

```
DEBUG [9/5/2020, 11:03:32 PM]: Checking availability of a binary at rust-analyzer-linux
DEBUG [9/5/2020, 11:03:32 PM]: rust-analyzer-linux --version: {
  status: 0,
  signal: null,
  output: [ null, 'rust-analyzer 0275b08\n', '' ],
  pid: 9585,
  stdout: 'rust-analyzer 0275b08\n',
  stderr: ''
}

```

but I still get the 403 error when tryting to start the server. Why are API request made even if the binary is available?

**Comment by bjorn3** [comment]
You downloaded the nightly version instead of the 2020-08-31 version. The rust-analyzer extension only accepts a rust-analyzer executable that is built from the same git commit.

**Comment by Veetaha** [comment]
Having `"rust-analyzer.serverPath": "rust-analyzer-linux"` should work disregarding any versions.
If you have set the `updates.channel` to `nightly` the extension will always try to poll GitHub API for the new nightly version, even if you have overridden the `serverPath`. Why? This is because nightly release includes `rust-analyzer.vsix` (rust analyzer client extension) to be updated too.

**Comment by niderhoff** [comment]
I reinstalled it using

```
curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux -o ~/.local/bin/rust-analyzer
```

and now it works. My theory as to why is the following: It detected the binary to be of nightly release and consequently polled Github for a new Version even though I did not explicitly set the `updates.channel` to nightly (the setting was on default).

**Comment by lnicola** [comment]
We now support setting a GitHub auth token, and we no longer check GitHub if the LSP binary path is manually set.

Please reopen or file a new issue if you're still having problems.
