### ISSUE TITLE
Download LSP server button doesn't appear

### ISSUE THREAD

**Issue by skeet70** [rust-analyzer/rust-analyzer#3096]
![image](https://user-images.githubusercontent.com/1424117/74192177-35906800-4c12-11ea-8e26-53434e1f5248.png)
![image](https://user-images.githubusercontent.com/1424117/74192192-404afd00-4c12-11ea-92c9-67f0c495937e.png)
```
λ ls ~/.config/Code\ -\ OSS/User/globalStorage/           
state.vscdb  state.vscdb.backup
```
I get the above when freshly installing the extension. I'm on Arch Linux using Code - OSS. Is there something else that needs to be done? Are only some Linux platforms supported?

**Comment by Veetaha** [comment]
Can you please open command palette with <kbd>Ctrl+Shift+P</kbd>, write `Toggle Developer Tools` and press enter to open the Developer Tools, then open Console tab and send its contents here?
Also please give the contents of `Help > About` window in VSCode?

**Comment by Veetaha** [comment]
I suspect @matklad published old version to Marketplace right now

**Comment by skeet70** [comment]
![image](https://user-images.githubusercontent.com/1424117/74192821-85236380-4c13-11ea-8387-129132df651e.png)

```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-20T11:11:01.597Z
Electron: 6.1.7
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.5.2-arch1-1
```

**Comment by Veetaha** [comment]
Yes, I am 90% sure this is the old version of extension right now on Marketplace. Already pinged him...

**Comment by Veetaha** [comment]
@skeet70 How did you install the extension? I suspect that you are using the old version of client extension that you've built from sources.
Can you please try to uninstall the extension and install it from marketplace again?

**Comment by skeet70** [comment]
@Veetaha is there an effective way to uninstall the one I built from source? I've uninstalled -> reloaded -> installed several times now with the same issue.

**Comment by Veetaha** [comment]
@skeet70 The 99% method is `rm -rf ~/.vscode/extensions/matklad.rust-analyzer-0.1.0`

**Comment by Veetaha** [comment]
Glad, it wors now!

**Comment by bjorn3** [comment]
Re-installing without uninstalling also works fine. Only uninstalling without quitting before re-installing keeps the old version cached.
