### ISSUE TITLE
Implement LSIF support

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#3098]
The LSIF 0.4 spec is now available at https://microsoft.github.io/language-server-protocol/specifications/lsif/0.4.0/specification/

**Comment by zoidbergwill** [comment]
I tried to have a look of where I'd need to get started on this, but I'd love to help, though I'm not familiar with this code base yet.

**Comment by namibj** [comment]
This should allow proper cross-repo references for public github code (it seems to maybe require opt-in by generating LSIF data and someone with collaborator access uploading it) on [sourcegraph](https://sourcegraph.com).

I'd not be surprised if they'd at least sponsor generating the LSIF data for the most popular crates, or even more than only those.

**Comment by matklad** [comment]
Hm, I'd say this is explicitly out of scope for the time being, we should do this eventually, but it's not useful to keep the issue open.
