### ISSUE TITLE
VScodevim Keybindings Broken

### ISSUE THREAD

**Issue by andy-crouch** [rust-analyzer/rust-analyzer#3104]
**Environment** - Rust Analyzer running in VS Code (latest available 1.41.1) and Vscodevim 1.12.4. All running on Manjaro Linux.

**Issue** - When I install Rust Analyzer in the above environment the vim keybindings provided by vscodevim start to only work intermittently. The save binding in particular (:w) stops working altogether.

**Comment by Veetaha** [comment]
Hi! Thank you for the report. Can you please provide specific steps to reproduce please?
Also please checkout this issue #3013, we have changed the setup of enhanced typing, that breaks VSCode VIM, the issue to redocument this is #3051

**Comment by zbuc** [comment]
I am also experiencing this issue.

The exact steps to replicate are:

1) Enable VSCode VIM keybindings by installing the VSCode VIM VSCode extension (https://github.com/VSCodeVim/Vim.git)
2) Enable rust-analyzer by installing the VSCode rust-analyzer extension
3) In a source file, press `ESC` to ensure your VSCode VIM is in command mode. Type `:w` and press `ENTER`

This should save the file, however with rust-analyzer enabled it inserts a newline.

**Comment by Veetaha** [comment]
@zbuc, thanks for the input! You just need to remove "Enter" keybinding. In issue #3013 we already stumbled with this. There are ideas to automatically disable the "Enter" keybinding when vim's extension command mode is active, though this is in our todo list, yet...

**Comment by andy-crouch** [comment]
@Veetaha I was just about to share the steps and @zbuc beat me to it.

I can confirm that the fix regarding the Enhanced Enter key behaviour in #3013 worked.  Thanks.
