### ISSUE TITLE
vscode extension constantly prompts for reload after cargo xtask install

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#3105]
If I do a `cargo xtask install` and then start vscode and go into the extension list rust analyzer always has the "reload" button.

**Comment by kjeremy** [comment]
@Veetaha ?

**Comment by Veetaha** [comment]
This should be fine, since `cargo xtask install` runs `code --install-extension rust-analyzer-0.1.0.vsix`. I guess you have to reload the window to load the new client extension you've just installed.

**Comment by kjeremy** [comment]
This is definitely a regression.

vscode is not running when I do a `cargo xtask install` (and it will fail if I try that because it cannot write to the extension which makes sense). The extension appears to be running even though vscode prompts it for a reload.

**Comment by kjeremy** [comment]
This is right after a `cargo xtask install`

![image](https://user-images.githubusercontent.com/4325700/74237122-c7df4d00-4ca0-11ea-95ac-03148061e258.png)

Version: 1.42.0 (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by kjeremy** [comment]
So if I watch the UI while it's loading the "Reload Required" button goes green and says "Update to 2020-someversionorwhatever" and then "Installing" and then the "Reload Required". It's a pretty fast transition.

This shows up in the "Log (Shared)" UI:

> [2020-02-11 07:38:57.534] [sharedprocess] [info] Deleted from disk matklad.rust-analyzer c:\Users\kjere_000\.vscode\extensions\matklad.rust-analyzer-0.1.20200211
> [2020-02-11 07:38:59.140] [sharedprocess] [info] Installing extension: matklad.rust-analyzer
> [2020-02-11 07:38:59.712] [sharedprocess] [info] Downloaded extension: matklad.rust-analyzer c:\Users\KJERE_~1\AppData\Local\Temp\31fd0b4d-d15e-49e5-9a86-b55b956cccea
> [2020-02-11 07:38:59.805] [sharedprocess] [info] Extracted extension to C:\Users\kjere_000\.vscode\extensions\.matklad.rust-analyzer-0.1.20200211: matklad.rust-analyzer
> [2020-02-11 07:38:59.806] [sharedprocess] [info] Renamed to C:\Users\kjere_000\.vscode\extensions\matklad.rust-analyzer-0.1.20200211
> [2020-02-11 07:38:59.817] [sharedprocess] [info] Installation completed. matklad.rust-analyzer
> [2020-02-11 07:38:59.840] [sharedprocess] [info] Extensions installed successfully: matklad.rust-analyzer
> [2020-02-11 07:39:37.280] [sharedprocess] [info] Starting to clean up unused language packs.

**Comment by bjorn3** [comment]
I think it updates from the locally build version to the published version. Maybe using a higher version number like `0.1.0-dev` for the local version would fix this?

**Comment by kjeremy** [comment]
I think for source installs it should never try to download a new extension.

**Comment by kjeremy** [comment]
A workaround for this is to disable automatic extension updates.

**Comment by Veetaha** [comment]
@kjeremy, did #3136 fix this?
