### ISSUE TITLE
VSCode settings displays default value [object Object] for feature flags.

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#3106]
![image](https://user-images.githubusercontent.com/36276403/74236561-296fdd80-4cda-11ea-9118-8d602017c6c6.png)

This is what happens when you stringify an arbitratry object in JavaScript.
I suppose this is a VSCode bug, not sure, needs investigation ...

**Comment by lnicola** [comment]
See #2189.
