### ISSUE TITLE
Source builds should not try to download releases

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#3109]
This would most likely fix #3105 but I think it deserves it's own issue.

**Comment by Veetaha** [comment]
Hmm, correct me if I am wrong, when you do `cargo xtask install` vscode still downloads and installs marketplace frontend extension and you do see `Download now` info message (note that you won't see it if you already installed prebuilt binaries and they are available somewhere in your `AppData\Code\User\globalStorage\matklad.rust-analyzer-<something>`)?

**Comment by kjeremy** [comment]
I'm not sure that I follow. Like I said in the other issue if I `cargo xtask install` it installs everything correctly.

If I pull my ethernet cable and then run vscode the version of the extension is `0.1.0`. Once I plug the cable back in and restart vscode (or reload the workspace) the extension becomes: `0.20200211` which suggests that it downloads.

**Comment by Veetaha** [comment]
@kjeremy, did #3136 fix this?
