### ISSUE TITLE
Link to VSCode marketplace for install instructions

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-analyzer/rust-analyzer#3110]
Got [a question on twitter about this](https://twitter.com/evan_cam_/status/1227235528975757313); would be cool if there was a link to the marketplace (possibly from the readme) to install the extension:
https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer

**Comment by matklad** [comment]
In the process of overhauling the website!

https://rust-analyzer.github.io/

![Uploading image.png…]()

**Comment by Veetaha** [comment]
Should we close this?
