### ISSUE TITLE
Add SemanticTokens to lsp-types crate

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3111]
There's a proposal for proper syntax highlighting in the protocol: 

https://github.com/microsoft/vscode-languageserver-node/blob/8c8981eb4fb6adec27bf1bb5390a0f8f7df2899e/protocol/src/protocol.sematicTokens.proposed.ts

We should switch our bespoke impl to that API. The first step would be to add corresponding rust structs to the lsp-types crate:

https://github.com/gluon-lang/lsp-types

This issue should actually be raised in that repository, but I am raising it here for visibility :-) 

Note that `lsp-types` already contains an alternative extension (see `SemanticHighlightingClientCapability`), which is different from `SemanticTokensClientCapabilities` which is actually proposed for the inclusion into the protocol. 

Note that this is a relatively high-priority task, so help would be appreciated. cc @kjeremy, I think you  might already be doing some work here?

cc https://github.com/rust-analyzer/rust-analyzer/issues/604

**Comment by kjeremy** [comment]
@matklad I have a branch that adds the types to `gluon-lang/lsp-types` but haven't finished it yet due to some tight schedules at work. I raised the issue of the alternate protocol here: https://github.com/gluon-lang/lsp-types/issues/133 

I believe that the md document for `SemanticHighlightingClientCapability` is just an older version and that the proposed ts file is the correct one. The same thing happened with call hierarchy.

**Comment by kjeremy** [comment]
If I don't get to it first I am happy to mentor someone on adding types to the lsp-types crate.

**Comment by kjeremy** [comment]
LSP PR: https://github.com/gluon-lang/lsp-types/pull/137

**Comment by kjeremy** [comment]
So I think my plan of attack now is to start with `textDocument/semanticTokens` and for the predefined types and modifiers.

@matklad I think I'm going to need some guidance on how to go about this in terms of getting the semantic information from the syntax.

**Comment by matklad** [comment]
@kjeremy that's basically what our `highlighting.rs` does? I think you don't even need to change that, just to transform it's results to the format expected by the LSP

**Comment by kjeremy** [comment]
Oh do you mean `syntax_highlighting.rs`? I'm never looked at this. I had to turn highlighting off because things got weird.

**Comment by kjeremy** [comment]
This looks perfect thanks.

**Comment by kjeremy** [comment]
For the bits that are beyond LSP: https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview

**Comment by kjeremy** [comment]
This has been done.
