### ISSUE TITLE
Rust Analyzer does not respect VS Code's "files.exclude" setting

### ISSUE THREAD

**Issue by peterjoel** [rust-analyzer/rust-analyzer#3113]
When I ctrl+click on a definition, I get 100s of matches because Analyzer is looking in my `.history` directory, created by the Local History extension for VS Code.

In my VS Code settings, I have:
```
  "files.exclude": {
    ".history/**": true
  },
```

`files.exclude` is the setting that I'm taken to when I click `Rust Analyzer: Exclude Globs => Edit in settings.json`, so I believe this is the correct setting.

**Comment by Veetaha** [comment]
@peterjoel thank you for the issue! Might I ask you to try to use the following in your `settings.json` instead?
```json
{
    "rust-analyzer.excludeGlobs": [".history/**"]
}
```
I believe VSCode navigated you to the wrong setting... The available settings are described [here](https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user#settings)

**Comment by peterjoel** [comment]
Thanks, this works. I need to work out why VS code is suggesting the wrong setting...

**Comment by lnicola** [comment]
> `Rust Analyzer: Exclude Globs => Edit in settings.json`

Is that a command? I can't find it, can you post a screenshot?

**Comment by Veetaha** [comment]
Some time ago VSCode created a UI for settings (previously all users were forced to edit settings.json). There is an link to jump from UI setting to settings.json file, I guess @peterjoel used it and ended up with the wrong template inserted by VSCode for `excludeGlobs`

**Comment by Veetaha** [comment]
@peterjoel , does vscode still navigate you to files.exclude?

**Comment by lnicola** [comment]
I see this, but it points to the correct key (`rust-analyzer.excludeGlobs`):

![image](https://user-images.githubusercontent.com/308347/74964873-dd7d1100-541c-11ea-8c8c-6e0aba32c8ee.png)

**Comment by Veetaha** [comment]
This might be (~~blame the user~~) human mistake, just want to filter this out

**Comment by peterjoel** [comment]
I don't see the problem any more. I have updated Rust Analyzer in the meantime, so it's hard to know. Previously, when it went to the wrong place, I didn't have the setting set, so my configuration is now different. Still, it doesn't seem to be a problem for me anymore, so I will close it.

**Comment by peterjoel** [comment]
> I see this, but it points to the correct key (`rust-analyzer.excludeGlobs`):
> 
> ![image](https://user-images.githubusercontent.com/308347/74964873-dd7d1100-541c-11ea-8c8c-6e0aba32c8ee.png)

Yep. That's what I see now. Previously there was only a link to edit the JSON. That's why I think this is fixed now.

**Comment by jlennox** [comment]
For those who have arrived here because of google, this has been renamed to `rust-analyzer.files.exclude`

**Comment by chirsz-ever** [comment]
Now it is not possible to disable rust-analyzer on a file with specific suffix (for me it is ".lalrpop")?

**Comment by lnicola** [comment]
> Now it is not possible to disable rust-analyzer on a file with specific suffix (for me it is ".lalrpop")?

Are we trying to parse `.lalrpop` files? We shouldn't and I can't reproduce, can you please file a new issue?

**Comment by chirsz-ever** [comment]
> Are we trying to parse `.lalrpop` files? We shouldn't and I can't reproduce, can you please file a new issue?

Oh, it's my custom setting. I use Rust syntax highlighting for `.lalrpop` files in VS Code, but rust-analyzer also try to resolve these `.lalrpop` files.

I need a way to disable rust-analyzer on `.lalrpop` files. Maybe this associates with #5187.

**Comment by azizur** [comment]
> For those who have arrived here because of google, this has been renamed to ~`rust-analyzer.files.exclude`~ `rust-analyzer.files.excludeDirs` (it keeps changing)

I have been trying below, it still reports issue outside the workspace directory.
```settings.json
"rust-analyzer.files.excludeDirs": [
    "/usr/local/cargo/**/*",
    "/usr/local/cargo/registry/",
    "*/usr/local/cargo/registry/"
  ],
```

**Comment by azizur** [comment]
In my case it was showing problems with files in `/usr/local/cargo/registry/`.

When I looked into the issue, `rust-analyzer` was scanning files in `target/*` directory. So I have updated my config to below. The run `cargo clean`. It seems to be working as expected.

```settings.json
{
"rust-analyzer.files.excludeDirs": [
    "target/debug"
  ]
}
```
