### ISSUE TITLE
How to prevent all tooltips when typing unless specifically asked?

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#3128]
Hi. I'm new to RA so maybe I just don't understand the settings correctly.

I would like to set it so that it never, unless I specifically press the "Trigger Suggest" key (eg: Ctrl+Space by default), opens a tooltip while typing.

Currently I've tried to turn off all the automatic suggestions, and i set the suggestion delay to 99999 ms, but when typing in a method call it pops up a tooltip as you type in the `(` and `)`, suggesting the args types of the call and so forth.

This is extremely distracting, and so I would like to be able to set it for suggestions _only_ when I've specifically pressed the Trigger Suggest key.

**Comment by matklad** [comment]
I think you need this setting, if you are using vs code:
https://github.com/matklad/config/blob/3ae993c6df118501b2aab230f9b03287b9c8192f/vscode/settings.json#L30
.

This is a client side thing, not the server side one.

**Comment by Lokathor** [comment]
Ah ha! solved
