### ISSUE TITLE
[Code] Insert/replace completion behavior

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#3130]
See https://code.visualstudio.com/updates/v1_42#_insert-and-replace-for-completion-items.

**Comment by kjeremy** [comment]
This is the best documentation that I have found on how completion is supposed to work:

https://github.com/microsoft/language-server-protocol/issues/898#issuecomment-593968008

Posting here so we don't lose this link.

**Comment by kjeremy** [comment]
Once https://github.com/gluon-lang/lsp-types/pull/157 is accepted and released we should be able to do this.

See https://github.com/microsoft/language-server-protocol/issues/846 for more details.

**Comment by kjeremy** [comment]
@lnicola  @matklad 

I've merged in the LSP bits so we can do this now.
