### ISSUE TITLE
Simplify server reloading logic

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3164]
https://github.com/microsoft/vscode/issues/45774#issuecomment-373423895 <- seems much neater way then what we are doing

**Comment by Veetaha** [comment]
Yeah, this was [my initial proposal](https://github.com/rust-analyzer/rust-analyzer/pull/3015#discussion_r375194450), though you gave an argument that we don't cancel inflight requests (already scheduled microtasks that hold a reference to terminated language client).
The ideal way to deal with this would be to pass cancellation tokens to our handlers, but this way don't you think this would be too much code that deals with a very rare problem?
Also, see my additional investigation in comments under my initial proposal.

**Comment by Veetaha** [comment]
One way to better employ the solution you referenced here with more confidence is to await for the resolution of all microtasks before restarting the server...

**Comment by Veetaha** [comment]
FYI: as an example of flushing microtasks implementation we can refer to this implementation in jest testing framework that is added in [this PR](https://github.com/testing-library/react-testing-library/pull/440/files)
