### ISSUE TITLE
Feature: show updates notification on extension activation in vscode

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#3166]
The extension shows a pop-up info notification upon its activation if the currently installed version of extension is not the latest one.

The relevant code is here (we need to make use of `fetchArtifactRelease()` and amend our `BinarySource.GithubRelese` to contain `notifyAboutUpdates` boolean flag):
https://github.com/rust-analyzer/rust-analyzer/blob/77d27c67c1dadce4abe7a6a97c0b73eaa3706e60/editors/code/src/installation/server.ts#L45-L48

We add new vscode setting `rust-analyzer.notifyAboutReleases` or `rust-analyzer.notify-about-releases` (or any other wording that is more user-friendly).
@matklad which style do we use for settings? Because we have different casing e.g. `cargo-watch` vs `useClientWatching`:
https://github.com/rust-analyzer/rust-analyzer/blob/77d27c67c1dadce4abe7a6a97c0b73eaa3706e60/editors/code/package.json#L191-L196

**Comment by Veetaha** [comment]
Note: we must not download the latest version of `ra_lsp_server` in this code right away! This is because the extension itself needs to be updated. We just kindly notify the user to press the update button at extension's marketplace page.

**Comment by lnicola** [comment]
Do other popular extensions do their own update checks? And if they do, can we disable them when auto-updates are enabled in Code?

Maybe I'm missing something (I certainly haven't gone through all of the related PRs yet), but this seems better left to Code or the user.

**Comment by Veetaha** [comment]
I know that [`vscode-icons`](https://github.com/vscode-icons/vscode-icons/blob/11a6f06a73e9724cdd1d650c6102de7ded3a43bc/package.json#L150-L154) does that (which has `4.5KK` downloads). I know that @matklad wants the users to be on the latest version of `rust-analyzer`, hence the proposal...

**Comment by lnicola** [comment]
I'm thinking that the auto-update should take care of installing the newest version of the extension. And users who disable automatic updates probably do it for good reasons like preventing Code from connecting to remote servers, so our update checks will likely upset them.

**Comment by lnicola** [comment]
There's also this argument I like: "what if every extension did that?". Cf. https://github.com/vscode-icons/vscode-icons/issues/435#issue-188192871.

**Comment by matklad** [comment]
In the steady state, we definitely should not do http requests without user's explicit consent. For the time being, I would priortize getting something out of the door :) 

I'd like to look at straightening extension lifecycle this week
