### ISSUE TITLE
attribute-style doc comments (`#[doc]`) are not shown in `lsp-ui-sideline`

### ISSUE THREAD

**Issue by japaric** [rust-analyzer/rust-analyzer#3180]
### Steps to reproduce

Start with `cargo new --bin hello` then modify `src/main.rs` to look like this:

``` rust
/// Foo!
struct Foo;

#[doc = "Bar!"]
struct Bar;

fn main() {
    let _ = Foo;
    let _ = Bar;
}
```

Opening the file in emacs-nox and placing the cursor on `Foo` (line 8) shows:

``` text
struct Foo

Foo!
```

on the sideline.

Placing the cursor on `Bar` (line 9) only shows:

``` text
struct Bar
```

Pictures:

![foo](https://user-images.githubusercontent.com/5018213/74637403-d7a7d700-5161-11ea-92b3-cd275d4a83d8.png)

![bar](https://user-images.githubusercontent.com/5018213/74637412-dbd3f480-5161-11ea-8b7b-6e3dcd5be199.png)

### Meta

```
$ cd rust-analyzer
$ git rev-parse HEAD
32fc890de87e25c342b7c141ef98b07cb1471128

$ rustc -V
rustc 1.43.0-nightly (433aae93e 2020-02-14)
```

---

I have a crate that I machine generated using `quote!` and all generated doc comments use `#[doc]` attributes. The multi-line ones look like this:

``` rust
#[doc = "one line description"]
#[doc = ""]
#[doc = "more detailed description"]
pub struct Foo;
```

None of them show up in `lsp-ui-sideline`

**Comment by matklad** [comment]
Should be fixed by #3182 "refactoring", but this would constitute a good test case!
