### ISSUE TITLE
Next steps in assoc item completion

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3183]
https://github.com/rust-analyzer/rust-analyzer/pull/3108 implemented completion for assoc items:

![assoc-completion](https://user-images.githubusercontent.com/1711539/74641596-dc748700-5171-11ea-8069-2386e51453ad.gif)

We should extend it to also work in the following cases:

![image](https://user-images.githubusercontent.com/1711539/74641662-f3b37480-5171-11ea-9e97-8f8477c7cab8.png)

should show the list of available items to override.

![image](https://user-images.githubusercontent.com/1711539/74641733-104fac80-5172-11ea-9f2a-839137a4fb20.png)

should suggest `fold` and `try_fold`.

Implementation wise, these two should be identical: comletion inserts a fake identifier when compuging context.

**Comment by slyngbaek** [comment]
I tried my hand at implementing this #3506 

First pull request, feedback welcome.

**Comment by cata0309** [comment]
Is that JetBrains Mono font the one you are using?

**Comment by matklad** [comment]
yup

**Comment by lnicola** [comment]
It looks like this can be closed?
