### ISSUE TITLE
Trait methods from where clauses on non-parameter types shoule be invisible

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3184]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3936fc7840151d29c938cb4e58376203

```rust
mod a {
    pub trait Foo { fn foo(&self); }
}

fn foo<T>(t: Option<T>) where Option<T>: a::Foo {
    t.foo();
}
```

Here, method `foo` should be invisible and should require explicit import of `a::Foo`. 

This probably is extremely low priority.

**Comment by flodiebold** [comment]
We get these here:
https://github.com/rust-analyzer/rust-analyzer/blob/b2b94cbf71738e7bc372328f22c8dcc8c734b34c/crates/ra_hir_ty/src/method_resolution.rs#L381-L384
So we probably only need to do this if `self_ty.value` is a `Ty::Placeholder`.
