### ISSUE TITLE
Update root README

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#3192]
Root `README.md` mentions only source builds which are now not the primary way to install `rust-analyzer` (i.e. preferred way is to use prebuilt binaries). We should emphasize this so that users are aware of it from the first look at the repo.

**Comment by Veetaha** [comment]
Also what about a nice badge from github actions? 
![image](https://user-images.githubusercontent.com/36276403/74662805-52451680-51a3-11ea-8ada-7f6a7813ac51.png)

**Comment by matklad** [comment]
I'd rather not, for two reasons:

* actions status is already displayed on the repo page
* we adhere to [not-rocket-science](
https://graydon2.dreamwidth.org/1597.html) rule, so a badge for master
branch is superfluous.

**Comment by lnicola** [comment]
This is a bit stale, I suppose.
