### ISSUE TITLE
Add homepage to VSCode extension on maketplace

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#3194]
There is literally nothing on [`rust-analyzer` marketplace homepage](https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer&ssr=false#qna) as of now. 

We need to add some description there. It may be custom or probably just a copy of root `README.md`. I am not sure, but I believe that VSCode looks for `README.md` and places its contents into the homepage. Thus we need to create a `README.md` doc in `editors/code` or copy the root `README.md` to `.vsix` package during the deployment step.

**Comment by bjorn3** [comment]
The description is currently:

# rust-analyzer

Provides support for rust-analyzer: novel LSP server for the Rust programming language.

See https://rust-analyzer.github.io/ for more information.
