### ISSUE TITLE
Inlay hints inherit style of tokens they are attached to

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#3207]
From the following example you can see that `reparsed_len` hint is displayed bold, though other hints are of normal weight.
![image](https://user-images.githubusercontent.com/36276403/74690422-bdb0d780-51e7-11ea-8c9e-4dc76f2a4cc8.png)

This is because the corresponding parameter value is integer literal `3` and I have a custom TextMate rule that makes constants bold, but with this, the parameter hint is also displayed bold.
The fix to this would be to force all hints to have normal font weight on the following lines of code:
https://github.com/rust-analyzer/rust-analyzer/blob/326556b09078a398e641dd221ab870ee0fe47f68/editors/code/src/inlay_hints.ts#L51-L61

There is a dedicated `fontWeight` option you can pass to these functions.
But the issue is a bit more general, users can have arbitrary TextMate rules and inlay hints will inherit them according to the token they are attached to, but I don't see a good general solution here.

**Comment by matklad** [comment]
closed by https://github.com/rust-analyzer/rust-analyzer/pull/3361#issuecomment-592452888
