### ISSUE TITLE
confusing: type errors show up at type declaration

### ISSUE THREAD

**Issue by hoodie** [rust-analyzer/rust-analyzer#3224]
Hi there, I love rust-analyzer!
There is one minute things that has confused me a bit though, sorry if this may be a duplicate.

Errors misusing an type, show up at the type's declaration, e.g. here where I misspelled a variant in lin `128`:

```
error[E0599]: no variant or associated item named `Connect` found for type `Protocol` in the current scope
   --> src/main.rs:128:37
    |
53  | enum Protocol {
    | ------------- variant or associated item `Connect` not found here
...
128 |                 if let Ok(Protocol::Connect(uuid)) = serde_json::from_str(&raw_content) {
    |             
```

..will produce a red squiggly line both in line `53` and `128`. The former one can lead to some confusion though (at least it had me thinking about how I may have miss-declared the enum once or twice before).

Thank you

**Comment by kiljacken** [comment]
What editor are you using? I know that we use the LSP functionality that attaches secondary spans to diagnostics, which might not be handled correctly in your editor. In any case, we can't really control how the

**Comment by hoodie** [comment]
vscodium

**Comment by memoryruins** [comment]
I'm unable to reproduce in VSCodium with a minimal sample.
Does this produce red squiggles for you? and is your extension and server up to date?

```rust
pub enum Enum {
    A(i32),
    B(u8),
}

pub fn b(e: Enum) {
    if let Enum::AA(x) = e {}
}
```
![screenshot 6486](https://user-images.githubusercontent.com/6868531/74800151-94a04d80-52a0-11ea-8a1b-0167eeb17b10.png)

extension: `rust-analyzer 0.1.20200217`
server: `94fb9ad`

```
VSCodium 
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-14T10:21:44.789Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
```

**Comment by hoodie** [comment]
Interesting, I can't reproduce this anymore either. Thanks for checking it out anyway. Perhaps I was on an older version.

**Comment by evbo** [comment]
@hoodie Can we please reopen? I am reproducing this when the `enum` lives in an external dependency via a git repo branch in Cargo.toml. Also, it considers importing FromStr unused, which actually should resolve the error.

![image](https://github.com/rust-lang/rust-analyzer/assets/6313004/a2796587-f5d7-4118-815e-d201b26fe45e)

![image](https://github.com/rust-lang/rust-analyzer/assets/6313004/0df5de43-c18e-419a-9297-d597102645c8)

> no variant or associated item named `from_str` found for enum `schema::Engine` in the current scope
variant or associated item not found in `Engine`



But cargo build finds it no problem of course.

I am on pre-release version of rust-analyzer in VS Code

**Comment by flodiebold** [comment]
@evbo Your screenshot does not show the bug, as far as I can see, and this issue has been closed for years. Can you open a new issue with the full code and describe your actual bug? "cargo build finds it no problem" does not sound to me like the original issue described in this ticket.
