### ISSUE TITLE
Associated types in constraints are not normalized

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#3232]
```rust
trait T {
    type O;
}

impl T for () {
    type O = ();
}

fn f<X, F>(_v: F)
where
    X: T,
    F: FnOnce(&X::O),
{
}

fn main() {
    f::<(), _>(|_z| {}); // _z is inferred as `&<() as T>::O>`
}
```

Possibly unrelated, but inference no longer works if the code is changed to `F: FnOnce(X::O)`. `F: FnOnce(X)` is fine, though.

Split off #3138.

https://github.com/rust-analyzer/rust-analyzer/blob/eb804261dce7f13056566377148a41f460feed28/crates/ra_hir_ty/src/infer.rs#L410 might need to be called on types returned by `chalk`.

**Comment by flodiebold** [comment]
Interestingly, `_z` does get normalized when we use it in an expression :thinking:

**Comment by lnicola** [comment]
@flodiebold should I file a new issue for the `F: FnOnce(X::O)` case :laughing:?

**Comment by flodiebold** [comment]
It looks like that's just another case of rust-lang/chalk#234, though I have no idea why it works with &. We could maybe add it to #2603 and make that the list of cases to check once the Chalk issue is resolved :sweat_smile:
