### ISSUE TITLE
Inspection: unnessary braces in use statement.

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#324]
For code like

```
use ra_db::input::{CrateId};
```

we should suggest removing the `{}`. The first step would be merely detecting such cases and producing a warning. The code for this is here:

https://github.com/rust-analyzer/rust-analyzer/blob/d77520fde3c953968beb09a3da80a0e7b17bbc04/crates/ra_editor/src/lib.rs#L92-L107

To check the file, one should taverse it using `.descendats()` method of the root node and check for a use tree with a single child.  A similar logic was recently implented [here](https://github.com/rust-analyzer/rust-analyzer/commit/67ac0a423f767ce8973348d5188e8baa6979d380)

Then one needs to add a `Severety` type & field to `Diagnostic`, so that we can distinguish between errors and warnings. Currently all diagnostis are errors, but this new one should be a warning. Then, fixing all usages of `Diagnostic` should basically lead to this being supported in the LSP.

**Comment by DJMcNab** [comment]
I think this is related to the TODO for extending `Diagnostic`/`p.error()` to better match the capabilities of rustc.

**Comment by DJMcNab** [comment]
Also, could this check occur in `expand_use_trees` so it works for arbitrary nesting?

**Comment by gfreezy** [comment]
this issue should be closed by #326

**Comment by matklad** [comment]
@gfreezy this currently misses the "fix": an edit which removes the `{}` automatically. Would like to add it as well? See the `fix: Option<SourceChange>` field in the `Diagnostic` in `ra_analysis`: filling it should do the trick.

**Comment by gfreezy** [comment]
Why we have two `Diagnostic` structs in ra_editor and ra_analysis?  `SourceChange` is defined in ra_analysis, but `unnecessary braces diagnostics` is bumped from ra_editor. It's hard to pass the fix from ra_editor to ra_analysis.

**Comment by matklad** [comment]
Answered on DIscord:

>@gfreezy the idea is that ra_editor is a lightweight analysis, which works with a single file only, while ra_analysis is a fully-features analysis which works with the whole crate graph
I am note sure that maintaning this separation is useful, but that's how things work today
One day I'd love to compiler ra_editor (but not ra_analysis) to WASM and add it to rust playground.
For diagnostics, this means that , in ra_analysis, a fix in the diagnostics can affect sevaral files
while in ra_editor the fix can affect a single file only
This is the same reason why SourceChange and LocalEdits are different types

So, we need to add a `fix: Option<LocalEdit>` to the Diagnostics in `ra_editor` and translate it to `SourceChange` in `ra_analysis`.
