### ISSUE TITLE
Language server version 2020-02-11 for rust-analyzer is not installed

### ISSUE THREAD

**Issue by 95th** [rust-analyzer/rust-analyzer#3240]
After today pull and install (commit: 7db7c868812c7289626825988fb6e610ea747eeb), I am getting this error alert.

![Capture](https://user-images.githubusercontent.com/22871609/74854356-3c7f4f00-5365-11ea-9506-70002244d170.PNG)

**Comment by 95th** [comment]
Oh It works by changing
```
"rust-analyzer.raLspServer": "ra_lsp_server",
```
to 
```
"rust-analyzer.serverPath": "ra_lsp_server",
```

**Comment by matklad** [comment]
We've changed the name of the binary to `rust-analyzer`, and renamed the associated setting. To use from-source build, add the following to config:

```
```

yeah, you've got there faster than me :D

**Comment by matklad** [comment]
Oh, you also want 

```
"rust-analyzer.serverPath": "rust-analyzer",
```

**Comment by 95th** [comment]
Oh ok. It means right now I am using older binary. I'll update that. Thanks

**Comment by svanas** [comment]
@matklad I am confused. Do we need this...

`"rust-analyzer.serverPath": "ra_lsp_server"`

...or this, when building from source?

`"rust-analyzer.serverPath": "rust-analyzer"`

**Comment by SomeoneToIgnore** [comment]
Latter, that's due to `ra_lsp_server` renaming into `rust-analyser`

**Comment by alienzj** [comment]
> Latter, that's due to `ra_lsp_server` renaming into `rust-analyser`

`rust-analyzer`
