### ISSUE TITLE
Sysroot error in VS Code when using nightly Rust

### ISSUE THREAD

**Issue by awulkan** [rust-analyzer/rust-analyzer#3245]
I'm a total newbie to Rust, so I hope this isn't a user error. But I thought I'd report it anyway.

After installing the Rust Analyzer extension in VS Code I get this error:
```
rust-analyzer failed to load workspace: Failed to find sysroot for Cargo.toml file 
d:\projects\rust\rocket\Cargo.toml
```

I did some troubleshooting and it seems like it only happens if I use nightly rust. Stable works fine.
This is a problem because it means I can't use the Rocket framework with Rust Analyzer. 

**Steps to reproduce:**
1. Run `rustup default nightly` (nightly-x86_64-pc-windows-msvc unchanged - rustc 1.43.0-nightly (e620d0f33 2020-02-18))
2. Install Rust Analyzer extension in VS Code.
3. Run `cargo init project_name`.
4. Open VS Code in the project folder.

**System:**
Windows 10.

**Comment by lnicola** [comment]
Can you try `rustup component add rust-src --toolchain nightly`?

**Comment by awulkan** [comment]
> Can you try `rustup component add rust-src --toolchain nightly`?

That fixed it, thanks.
I have no idea what that command does though. Care to explain before I close the issue? :)

**Comment by lnicola** [comment]
I'm not sure we should close the issue yet. The `rust-src` component contains the source code of the Rust standard library. `rust-analyzer` uses it to figure out what the `std` types like `String` are. So in order to function correctly, it needs to be installed.

And we actually try to install it, but either that's not available in the Marketplace extension yet, or we install it for the wrong toolchain (stable).

**Comment by awulkan** [comment]
Okey, I'll leave this issue open for further investigation then.

**Comment by lnicola** [comment]
Yeah, that was merged after Monday: https://github.com/rust-analyzer/rust-analyzer/pull/3206.

**Comment by AngelOnFira** [comment]
+1, I had to use `rustup component add rust-src --toolchain nightly-2020-02-06` but it worked :100:

**Comment by lnicola** [comment]
This seems to be working properly now, closing.
