### ISSUE TITLE
Better Autocomplete for Trait Functions

### ISSUE THREAD

**Issue by sanbox-irl** [rust-analyzer/rust-analyzer#3246]
Hello there!

Autocomplete for traits, as introduced in the last release, is sick as heck, but I think it has an issue that caught me a bit offguard: it activates, and writes the parameters, no matter what is there.

Here is it doing it's thing well:

https://imgur.com/a/QbNZ2xl

Here is it doing its thing not so well (autocompleting to something which won't compile):

https://imgur.com/a/npStlTR

I think both situations are actually reasonably common right now in the LSP, as renaming a trait won't rename the implementations (eg, i discovered this by hitting F2 and renaming a function, and then fixing the implementations).

I think a reasonable fix is to show the Parameters in the autocomplete header. Right now, the autocomplete looks like this:

![Screen Shot 2020-02-19 at 9 55 55 PM](https://user-images.githubusercontent.com/31973761/74905289-a4806600-5362-11ea-9ca0-0042c2149a0d.png)

To me, this looks like it's just going to complete the function name (the `()` do give me pause in retrospect, but without the `{}` it's tough to tell how much it's going to autocomplete).

if it instead, looked like this...
![demo_autocomplete](https://user-images.githubusercontent.com/31973761/74905943-6ab05f00-5364-11ea-8364-2faa24fa3c47.png)

Then it would be very clear what *exactly* is about to be autocompleted. 
It'd also be dope if it could be formatted, but that might be a different topic, as that also applies to a lot of the type help popups.

Thank you so much, and thank you for all your hard work!

**Comment by flodiebold** [comment]
The autocompletion should probably just check whether there's already a full function definition following the code being completed.

**Comment by sanbox-irl** [comment]
I think that's a good idea, but I also personally *much* prefer autocomplete to tell me exactly what it's going to auto-complete. Having that and smarter autocompletion would be great

**Comment by flodiebold** [comment]
I think if there's several completion options, showing the complete snippet will take too much room. You should be able to just trust that the completion will do the right thing.

**Comment by sanbox-irl** [comment]
Not to be too pedantic here, but I strongly disagree with `you should be able to just trust that the completion will do the right thing.`

I disagree for three reasons:
1. Auto completion will always be wrong at least sometimes. It might have gotten some type inference incorrect, it may be in a strange state when asked, etc.
2. Correct autocompletion is excellent, but not required. I lived implementing traits before the last update, I could live without it.
3. Incorrect autocompletion is much worse than no autocompletion.

Therefore, to me at least, I want to be the one in control of what gets added to the code when. If the auto completion is incorrect, which it will sometimes be, I can think to myself "hm, that's not right", and move on. Has the tool made a mistake? Sure, but it's no harm no foul. If I clicked ahead anyway and accepted the auto complete, and it was a mistake, then that's my fault.

If I have to accept the auto complete, without knowing beforehand exactly what is going to get autocompleted, then that's the tool's fault, not mine. And that's how you end up getting stuck in this Github thread with me.

This is actually how the Rust analyzer treats everything else it auto completes (and how most Language Servers in most languages do it too, to my knowledge). I'd like that to continue personally, but since I'm basically asking people to do work to make my life easier, I'm not in a very strong arguing position. If the RA team disagrees with me, since it's your tool, I'd understand.

RE: your point above -- VSC, at least, offers two levels of information as per the LSP in a completion item. the RA seems to use those two levels for when a complete snippet takes up a lot of room.

Here's an example of normal function autocomplete (along with other stuff in that module):

https://imgur.com/w6UOAHU

Right now, trait function autocomplete is not doing that:

![Code_aUssCjVrV1](https://user-images.githubusercontent.com/31973761/75088764-82274d80-5506-11ea-83a7-9a326b45f326.png)


I would propose you can keep the current autocomplete for the simple name as above and then add the full docs in the completion resolve request in that lil window thingee.

What do you think?

**Comment by flodiebold** [comment]
Oh, I agree we should show the full signature in the doc tooltip. I also think we should maybe make the label something like `fn serialization_option(..) {}`.

> Incorrect autocompletion is much worse than no autocompletion.

That's exactly why I say autocompletion needs to be trustworthy. If autocompletion inserts something that doesn't make sense, in my opinion that's a bug, and we should fix it by not inserting things that don't make sense, not by saying beforehand that we will insert something that doesn't make sense :slightly_smiling_face: I disagree about this being impossible to do.

**Comment by matklad** [comment]
My rule of thumb is usually do whatever IntelliJ IDEA does:

![image](https://user-images.githubusercontent.com/1711539/75093136-7a57bf80-557f-11ea-9d5f-d5a33d544307.png)

**Comment by sanbox-irl** [comment]
No reason we can't do both @flodiebold !

**Comment by matklad** [comment]
I am going to close this, as I belive having an option here would be, overall, less good than sticking with intelliJ's behavior.
