### ISSUE TITLE
Unknown type deduction when using associated type Self::Type in a trait impl

### ISSUE THREAD

**Issue by x-hgg-x** [rust-analyzer/rust-analyzer#3249]
Rust-analyzer cannot deduce a an associated type in a trait impl when using ```Self::Type```, even if it can when using full syntax ```<Struct as Trait>::Type```.

```rust
trait T {
    type T1;

    fn f(var: Self::T1);
    fn g(var: Self::T1);
}

struct S;

impl T for S {
    type T1 = u32;

    fn f(var: Self::T1) {
        let _a = var;
    }

    fn g(var: <S as T>::T1) {
        let _a = var;
    }
}
```

In this example, variable ```var``` is correctly deduced in the ```g``` function, but not in the ```f``` function.

![screenshot](https://user-images.githubusercontent.com/39058530/74928468-daacfc80-53d9-11ea-8da6-50ae6a89e5ff.png)

I'm using the latest release of rust-analyzer (2020-02-17) with the latest version of the vscode extension.

**Comment by x-hgg-x** [comment]
Another precision: it still works if I put ```<Self as T>::T1``` instead of ```<S as T>::T1```.

**Comment by flodiebold** [comment]
Basically resolving unselected associated types on `Self` in an impl block isn't implemented yet. Writing `T::Type` without specifying the trait deduces the associated type you mean from the where clauses in scope, but it's only allowed for type parameters... and `Self`, which isn't a type parameter in impls. (It is in trait definitions.) It's just an alias for the type being impl'd. So we immediately resolve `Self` to `S` in your example, but while you can write `Self::T1`, you can't write `S::T1`.

Resolving `Self` happens here:
https://github.com/rust-analyzer/rust-analyzer/blob/db1bbb11fbe85a5230452359e80535a2169d0929/crates/ra_hir_ty/src/lower.rs#L291-L300

And selecting an associated type happens a bit later, in `from_type_relative_path` which calls `select_associated_type`. By then, we don't know anymore that the type was written as `Self`. So what we will have to do is add some special handling in the above section that handles `Self::T1` in a similar way to `from_type_relative_path`.
