### ISSUE TITLE
Editing Cargo.toml produces "Rust file outside current workspace is not supported yet."

### ISSUE THREAD

**Issue by pie-flavor** [rust-analyzer/rust-analyzer#3255]
What the title says. If I've got a Rust project open, I can't open Cargo.toml without error spew. Using latest rust-analyzer plugin for VSC.

**Comment by Veetaha** [comment]
Might I ask you to provide the project and `Cargo.toml` that you edited if it is open source?
Anyway, if provide at least `Cargo.toml` and which particular edits you did it would be helpful.

**Comment by Veetaha** [comment]
Also, just to be 100% sure, might I ask you to open the command palette with <kbd>Ctrl+Shift+P</kbd>, write `Toggle Developer Tools` and press enter to open the Developer Tools, then open `Console` tab and send its contents here?

**Comment by lnicola** [comment]
Are you using crates with build scripts that generate code?

**Comment by pie-flavor** [comment]
@lnicola I was, but I tested and it persists when I'm not.
@Veetaha It occurs with this project: https://github.com/pie-flavor/rc_cell
Dev tools output is
```
workbench.desktop.main.js:sourcemap:3628 Error: Rust file outside current workspace is not supported yet.
	at handleResponse (c:\Users\Adam\.vscode\extensions\matklad.rust-analyzer-0.1.20200217\out\main.js:3467:48)
	at processMessageQueue (c:\Users\Adam\.vscode\extensions\matklad.rust-analyzer-0.1.20200217\out\main.js:3294:17)
	at Immediate.<anonymous> (c:\Users\Adam\.vscode\extensions\matklad.rust-analyzer-0.1.20200217\out\main.js:3278:13)
	at processImmediate (internal/timers.js:439:21)
```

**Comment by Veetaha** [comment]
@pie-flavor let me guess, do you use [VSCode workspaces](https://github.com/rust-analyzer/rust-analyzer/issues/3265#issuecomment-590001965)?

**Comment by pie-flavor** [comment]
@Veetaha No, there is only one folder open.
