### ISSUE TITLE
In grouped imports, only one unused warning displays at a time

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#3257]
When I have a group import like `use std::str::{self, FromStr};` and multiple items from the import are unused, rust-analyzer will only highlight the first one with the yellow underline. After I remove it, it will highlight the next one, and so on.

**Comment by bjorn3** [comment]
Rustc emits multiple spans in one warning in this case.

**Comment by kjeremy** [comment]
Can the other spans be expressed in terms of `DiagnosticRelatedInformation`? https://microsoft.github.io/language-server-protocol/specifications/specification-current/#diagnostic
