### ISSUE TITLE
PunkE01: In vscode, types can't be styled differently from their field name

### ISSUE THREAD

**Issue by gilescope** [rust-analyzer/rust-analyzer#3266]
In vscode struct and enum type names have a textmate scope, but field types don't have a different textmate scope and so can't be styled differently from the default 'source.rust' textmate scope. 

This level of styling fidelity is obviously essential for opening up the ability for people to roll their own rusty cyberPunk themes. (btw. mutation being underlined seems _very_ cyberpunk)

I can see there's a mapping from TAG_TO_SCOPES here:
https://github.com/rust-analyzer/rust-analyzer/blob/04dacb994349848873f9b2576d53685630883300/editors/code/src/highlighting.ts

and digging there is a field tag:

https://github.com/rust-analyzer/rust-analyzer/blob/27587f3501168c0522e62bf14923aedbdc08a960/crates/ra_ide/src/syntax_highlighting.rs

but I can't see any sign of the entity.name.field textmate style on any fields (used or defined)? It feels like there should be enough to style fields separately from their types.

Any tips gratefully received!

**Comment by Veetaha** [comment]
Thank you for the proposal! Our current code highlighting setup is quite handcrafted, so instead we would like to invest resources into the development of semantic tokens highlighting API (#3159) that should reach the stable language server protocol release in the nearest future.

**Comment by lnicola** [comment]
This is now solved:

![image](https://user-images.githubusercontent.com/308347/105537700-fa8c2500-5cfa-11eb-9e9a-99a4c9e95003.png)

![image](https://user-images.githubusercontent.com/308347/105537711-feb84280-5cfa-11eb-83b4-aecd7efc800b.png)
