### ISSUE TITLE
Type inference failure in small snippet.

### ISSUE THREAD

**Issue by crlf0710** [rust-analyzer/rust-analyzer#3268]
Currently in this code snippet, ra cannot infer the type of variable v. I'm using ra  commit baf832d6d903afbc39e3a01c752a1aa5218c020e now.
```rust
    let mut action_contexts: Vec<i32> = vec![1, 2, 3];
    for v in action_contexts.iter_mut() {
        dbg!(v);
    }
```

**Comment by flodiebold** [comment]
This is one of many cases where we are not able to normalize associated types because of a Chalk bug. I'm collecting these in #2603.

**Comment by lnicola** [comment]
As seen in https://github.com/rust-analyzer/rust-analyzer/issues/2683#issuecomment-569536866 :smile:.
