### ISSUE TITLE
Spurious cargo recompilations with diesel/libsqlite3-sys

### ISSUE THREAD

**Issue by yuyoyuppe** [rust-analyzer/rust-analyzer#3270]
#### Description
rust-analyzer seems to trigger `libsqlite3-sys` recompilation every time I make a change, and it's really slowing my iteration time.

#### Env
- rustc 1.41.0, stable-x86_64-pc-windows-msvc
- [2020-02-17 rust-analyzer.vsix](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-02-17)

#### Repro steps

- build anything that uses diesel, e.g. https://github.com/diesel-rs/diesel/tree/v1.3.0/examples/postgres/getting_started_step_1
- make any change in the source to trigger background `cargo check`:
![image](https://user-images.githubusercontent.com/1828123/75090164-3958ae80-5571-11ea-988d-31e91e8ed1c7.png)
- build again:
```sh
$ cargo build
    Blocking waiting for file lock on build directory
   Compiling libsqlite3-sys v0.16.0
   Compiling diesel v1.4.3
   Compiling diesel_demo_step_1_sqlite v0.1.0 (S:\Programming\TEMP\getting_started_step_1)
    Finished dev [unoptimized + debuginfo] target(s) in 23.65s
```

#### Workaround
Disable `cargo check` in VSC Settings:
```json
"rust-analyzer.cargo-watch.enable": false
```

**Comment by lnicola** [comment]
This shouldn't generally happen. Do you have any settings that might make `cargo check` work differently when started from the command-line vs. Code? E.g. if you set `RUSTFLAGS` in your terminal, then build the project from Code, it will rebuild everything. But this specific thing is more likely to happen on Linux than Windows.

**Comment by yuyoyuppe** [comment]
@lnicola I don't set any `RUSTFLAGS`. 

The only suspicious thing I see is that I've defined a system-wide environment variable `VCPKGRS_DYNAMIC=1`, because I share some of my vcpkg dependencies between C++ and Rust.

**Comment by bjorn3** [comment]
Is it possible that passing `--all-features` by rust-analyzer, but not when manually compiling causes the problem? To test this you can set `rust-analyzer.cargoFeatures.allFeatures` to false.

**Comment by yuyoyuppe** [comment]
Alright, after some experimenting, I've found that changing `$PATH` in _any_ way, e.g. appending some nonexistent folder `PATH=$PATH:/nonexistent_folder` to it causes `libsqlite3-sys` to recompile. I'll head to its repo to investigate why that happens.

@bjorn3 @lnicola thanks for your helpfulness!

**Comment by lnicola** [comment]
I thought this might be caused by the build script, but I see nothing of sorts in https://github.com/jgallagher/rusqlite/blob/master/libsqlite3-sys/build.rs.

**Comment by yuyoyuppe** [comment]
@lnicola diesel uses `libsqlite3-sys v0.16.0` though 🙂 https://github.com/jgallagher/rusqlite/blob/0.16.0/libsqlite3-sys/build.rs#L126-L127

**Comment by matklad** [comment]
I think we need a `separateTargetDirForCargoCheck` checkbox in the
settings, which sets target for watch commands to `target/rust-analyzer`. I
*think* most folks would like to share the target dirs, but in some cases,
such as this, a separate target dir might be beneficial.

Also, that line form libsqlite3 build script doesn't look exactly right. I
mean, you shouldn't care about PATH env var, you should care about which
binaries exist there?

**Comment by yuyoyuppe** [comment]
I agree, that flag would be really useful in this case. That line is no longer in libsqlite3, so I'll just create a PR which update this dependency.
