### ISSUE TITLE
Show parameter hints for `None`  parameters

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3273]
![image](https://user-images.githubusercontent.com/1711539/75095281-76359d00-5593-11ea-9e2d-c126494471d1.png)

Would be cool to know which `None` means what. Guess we need to just refactor the API, but having a hit would be a useful bandaid. 

I think we literarly should just check for `None`, rather than use a more general rule, like "is this a const item". Though not sure here.

cc @SomeoneToIgnore

**Comment by lnicola** [comment]
Wait, we already have parameter hints, but they don't seem to work on that function even though it does get resolved?

**Comment by matklad** [comment]
it workds with literal parameters:

![image](https://user-images.githubusercontent.com/1711539/75095402-8dc15580-5594-11ea-9649-af0a3cb028e0.png)

**Comment by lnicola** [comment]
Ah. I guess it would be annoying if they were always shown? What does IntelliJ do?

**Comment by SomeoneToIgnore** [comment]
> What does IntelliJ do?

<img width="413" alt="image" src="https://user-images.githubusercontent.com/2690773/75097006-b5291a00-55b6-11ea-9bab-61364b06e8c9.png">

Nothing different from our case.

I think that having an inlay hints for all `None` cases might be a bit verbose.
Should we instead add this info to our hover hints?

**Comment by lnicola** [comment]
> Nothing different from our case.

Um, so it always displays the parameter hints?

**Comment by SomeoneToIgnore** [comment]
Right, that should be formulated as 

> Nothing different from our case for type hints.

**Comment by SomeoneToIgnore** [comment]
For the context, here's the way to simplify the code proposed before: https://github.com/rust-analyzer/rust-analyzer/pull/1606#discussion_r308146363

I've applied the suggestion, but `BindPat::pat` gives me `None` for every inlay hint test I run, currently I'm trying to understand what am I doing wrong.

**Comment by SomeoneToIgnore** [comment]
I've sorted it out.

Old hints:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/2690773/75099207-098cc380-55d0-11ea-856a-c0c7a822d26b.png">


New hints:
<img width="521" alt="image" src="https://user-images.githubusercontent.com/2690773/75099181-bd418380-55cf-11ea-884c-79e50cc46c94.png">

How do you like the results?

**Comment by lnicola** [comment]
It does seem a bit busy when combined with field matching, but I could get used to it. Does it also work for function parameters?

**Comment by SomeoneToIgnore** [comment]
Not yet.

**Comment by SomeoneToIgnore** [comment]
Personally, I'm not sure we should add type hints to the function parameters.
Name hints is another story, here's how it looks like after my changes:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2690773/75099758-74d99400-55d6-11ea-856f-565e130a7e0c.png">

Now we're more or less on par with what intellij-rust displays for the functions/methods.

Imagine adding the type hints there (or, even worse, to a function with its parameters written in one line): IMO, this will be hard to comprehend.

So, should hovers be enough after all?

**Comment by kjeremy** [comment]
> So, should hovers be enough for displaying the function parameters' types after all?

I think so. We should definitely have name hints since that's more important for reading code. If you need type info you can get it through hover or signature help.

**Comment by bjorn3** [comment]
What about something like "if type is Foo and argument name is foo, don't show name inlay hint" and "if expr is something like foo or bar.foo and argument name is foo, don't show name inlay hint"? That omits the name inlay hint in the cases where the arg name is most obvious.

**Comment by SomeoneToIgnore** [comment]
In general, sounds like a good idea to implement, but maybe later, when we collect enough cases, along with the similar type hints ideas from https://github.com/rust-analyzer/rust-analyzer/issues/3022?

I feel like in the end we should come up with a set of toggles for those cases also, similar to what [Rider has](https://www.jetbrains.com/help/rider/Inline_Parameter_Name_Hints.html#configuring-parameter-name-hints)

**Comment by lnicola** [comment]
> Personally, I'm not sure we should add type hints to the function parameters.

Oh, yeah, I was totally talking about name hints for function parameters.

**Comment by SomeoneToIgnore** [comment]
> What about something like "if type is Foo and argument name is foo, don't show name inlay hint" and "if expr is something like foo or bar.foo and argument name is foo, don't show name inlay hint"? That omits the name inlay hint in the cases where the arg name is most obvious.

I've added a few heuristics here: https://github.com/rust-analyzer/rust-analyzer/pull/3279
But it's not over yet, so we'd better come up with a separate ticket to gather the ideas there.

**Comment by 0x7CFE** [comment]
> It does seem a bit busy when combined with field matching, but I could get used to it. Does it also work for function parameters?

Agree. Consider the following example:

![image](https://user-images.githubusercontent.com/3784017/75130249-dba69c80-56ff-11ea-889d-8d2bd97c6e0c.png)

Here we see that inlay hint does not provide any new information... except for a ton of visual noise. Just by looking at match arms I already can infer types, more or less. So I'd rather say that `None` hint would work only in case of a standalone literal without any surrounding context.

Also it could get very noisy in case of several hints per line of code:

![image](https://user-images.githubusercontent.com/3784017/75130369-9e8eda00-5700-11ea-8098-1f02112f1e82.png)

Maybe we should have some heuristics and limit not only the length of a hint, but total length of all hints per line. And then either opt out hints completely, or reduce their complexity by displaying less nested types.

**Comment by SomeoneToIgnore** [comment]
> So I'd rather say that None hint would work only in case of a standalone literal without any surrounding context.

Yes, I agree with you after using the new hints for a while, the PR fixing this is being merged to master right now.

For the other part of your proposal, seems valid, we need to investigate the possible solutions some time later.
I've added the text to the corresponding issue: https://github.com/rust-analyzer/rust-analyzer/issues/3138
