### ISSUE TITLE
Display a progress bar while loading the workspace

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-analyzer/rust-analyzer#3283]
## Current behavior

When opening the editor rust-analyzer will run `cargo-check` and install dependencies. This process can take a while, and currently there are no visual cues indicating how far along the process is. On the command line this process is tracked by displaying a bar at the bottom of the window.

## Proposed behavior

When opening a remote window on WSL, the popup contains a small progress bar tracking the initialization status. It would be great if rust-analyzer could use the same method to track the initialization progress as well.

<img width="402" alt="Screenshot 2020-02-23 16 57 11(2)" src="https://user-images.githubusercontent.com/2467194/75115383-47d0c400-565e-11ea-85dd-4d5914464f12.png">

## Implementation notes (added by @matklad)

This should use the new progress notification of LSP https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workDoneProgress and I think should work without any changes on the client side.

**Comment by yoshuawuyts** [comment]
Related:
- https://github.com/microsoft/vscode/pull/45958
- https://github.com/Microsoft/vscode/issues/44090

**Comment by yoshuawuyts** [comment]
The code for displaying the "workspace loaded" message is here: https://github.com/rust-analyzer/rust-analyzer/blob/f761ed2abb3faa07f9a835e9ba767954ca2e684b/crates/rust-analyzer/src/main_loop.rs#L420-L423

Which creates a new `Notification` that's seemingly part of the LSP protocol. I know little about LSP itself, but https://github.com/microsoft/language-server-protocol/issues/786 gives the impression that there's a notion of "Progress" events available now.

Such event would need to be created, and picked up by the VS Code client side to be translated into the progress API: https://github.com/microsoft/vscode/pull/45958.

**Comment by Veetaha** [comment]
This is an interesting proposal. I never saw language-support extensions to show the bootstrap progress. E.g. TypeScript has none of that (though it's mainly because it manages to become responsive in a few seconds). Also, notice that there do is `cargo check` running status displayed in the bottom status bar:
![image](https://user-images.githubusercontent.com/36276403/75116153-0ea05000-566e-11ea-94a4-ee2d5275276e.png)

**Comment by kjeremy** [comment]
Some language servers display something like "Indexing file (1/2000)". This would definitely be a good place for a progress notification like that.

**Comment by yoshuawuyts** [comment]
@Veetaha I agree with your point that Rust is probably different than TypeScript here.

---

I'm realizing now that I didn't share the *reason* why I opened this issue in the first place.

After a fresh `git clone` of a repo, I opened VS Code, and my CPU suddenly spiked to a 100%. I assumed it was because `rust_analyzer` had started compiling, but I wasn't sure. And more so: I had no idea how long this would go on for. So I opened up my system monitor to check, and waited for it to finish compiling.

The purpose of this flow is so the editor provides visual feedback how far along it is with initializing. Unlike the small spinner at the bottom, the initial compilation needs to complete before people can start working, and so it makes sense to display more prominently on the screen. The spinner serves a different function: for shorter incremental compilations, it shows something is running in the background.

**Comment by kjeremy** [comment]
This has been brought up before in other issues and on zulip. It's a good idea. PRs welcome.

**Comment by Veetaha** [comment]
It needs some investigation to add an API from server side and an appropriate code on TypeScript extension side. If one would wan't to invest time into it, here is our progress API usage for downloading the binary from GitHub: https://github.com/rust-analyzer/rust-analyzer/blob/bd4ea87f7442541123e3bbd7e17bfecdfb3c18c6/editors/code/src/installation/download_artifact.ts#L32-L55

Anyway, I added this into my todo list, but not the first priority...

**Comment by kjeremy** [comment]
Why does this require anything on the client side?

**Comment by Veetaha** [comment]
It would be cool if we could do it solely from the server side via the LSP protocol. I doubt that there is built-in support for such a progress message from VSCode side, but I am **not sure**, an ivestigation is needed.

**Comment by kjeremy** [comment]
If I understand correctly we can do it all from the server side if the
client supports progress notifications and vscode does.

**Comment by kiljacken** [comment]
IIRC we need to get a progress "handle" from VSCode first, to be able to use the progress notfication AFAIK. We use it for the cargo check progress, but you don't get anything without doing something on the client side aswell.

**Comment by Veetaha** [comment]
@kiljacken that status message is not what we want, we handcrafted a progress spinner ourselves, but the proposal is to use the progress info popup as we do for binary download

**Comment by kjeremy** [comment]
@kiljacken: Why isn't it `window/workDoneProgress/create` from server -> client and then use that token for `$/progress` notifications originating from the server? Our typescipt extension should not have to do anything special since the UI is handled by vscode or any other LSP client that supports progress notifications.

**Comment by kiljacken** [comment]
@kjeremy It's been a while so it's a little hazy, but I must've just forgotten to do create first. The API was new and I just lazily converted to using messages that already exsisted and both ends understood. We do a custom progress thingy for check anyways so it didn't matter much.

**Comment by kjeremy** [comment]
@kiljacken It isn't always obvious. Hopefully that's all we have to do but I could be totally wrong too :)

**Comment by edwin0cheng** [comment]
@kiljacken @kjeremy, Some history here:  The reason of using custom progress bar in the old cargo watch (typescript one) was,  at the moment, there was no such "Progress" events in VSCode api, which was my PR in RA around a year ago. :)

**Comment by kjeremy** [comment]
@edwin0cheng Absolutely! Progress support was a heavily requested feature for LSP/vscode and now that we have it we should use it if clients support it :)

**Comment by slyngbaek** [comment]
I'll take a stab at this one

**Comment by yoshuawuyts** [comment]
It seems the box has since been removed, and the spinny indicator in the bottom clearly indicates how far along the workspace is with loading.
