### ISSUE TITLE
Documentation is displayed above diagnostics on hover

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#3284]
![image](https://user-images.githubusercontent.com/308347/75117001-72c71200-5676-11ea-93ca-d8fb51ef5336.png)

![image](https://user-images.githubusercontent.com/308347/75117014-883c3c00-5676-11ea-9ad8-eab98409bdc7.png)

**Comment by lnicola** [comment]
Actually, the error is there, but you have to scroll to the bottom.

**Comment by kjeremy** [comment]
I'm pretty sure this is driven by vscode itself.

**Comment by lnicola** [comment]
![image](https://user-images.githubusercontent.com/308347/75120138-bed38000-5691-11ea-9a79-5b7327b5235a.png)

Yeah, that seems to be the case. Sorry.
