### ISSUE TITLE
Is it possible to set rust-analyzer options to match git-hooks options ?

### ISSUE THREAD

**Issue by flocknetworks** [rust-analyzer/rust-analyzer#3292]
My workspace is in a compilation battle between rust-analyzer and my git-hooks.  Every time I run a git hook it recompiles the binary, I assume because of an options mismatch with rust-analyzer.

An example from my git hook is
RUSTFLAGS="-D warnings" cargo check --tests --features="mock" || exit 1

Can I set the rust-analyzer defaults to be the same and avoid these needless recompilations ?

Thanks,
Nick

**Comment by matklad** [comment]
We should provide an option to do this, but it's not possible at the moment. The current work-arounds are:

* disable rust-analyzer watching (`"rust-analyzer.cargo-watch.enable": false` in config)
* run rust-analyzer with `CARGO_TARGET_DIR` environment set to something like `./target/rust-analyzer`

**Comment by flocknetworks** [comment]
I've turned on the the 'disable rust-analyzer watching' work-around.  That does the trick.

Thanks ( + thanks for rust-analyzer, my cpu has never been so happy....)

**Comment by flocknetworks** [comment]
Hi,

I'm still running with rust-analyzer watching turned off.  Is there an option yet to set the compilation options rust-analyzer will use ?

Thanks,
Nick

**Comment by matklad** [comment]
That's now possible, see the `rust-analyzer.server.extraEnv` config option in VS Code.

**Comment by flocknetworks** [comment]
Adding this to vscode Code>User>settings.json has fixed this problem, Thanks.

  "rust-analyzer.server.extraEnv": {
        "RUSTFLAGS": "-D warnings"
    },
