### ISSUE TITLE
`#![no_std]` can't find crate for `test`

### ISSUE THREAD

**Issue by imjasonmiller** [rust-analyzer/rust-analyzer#3297]
I'm posting this for posterity's sake, as someone else might run into the issue and find it useful.

I kept receiving the following error:

![image](https://user-images.githubusercontent.com/12190184/75187299-16352700-574a-11ea-81ad-9425ed9ffe0f.png)

It seems it's related to the following issues:

* https://github.com/rust-lang/rls-vscode/issues/729
* https://github.com/rust-lang/rls/issues/1524

As `coc.nvim` offers per project based settings, I added the following configuration and relevant [`target`](https://forge.rust-lang.org/release/platform-support.html) to my project, which will make the error go away:

**.vim/coc-settings.json**
```json
{
  "rust.target": "thumbv7em-none-eabihf",
  "rust.all_targets": false
}
```

**System information**
```
nvim v0.5.0-392-gff1730373
coc-rust-analyzer 0.4.3
rustc 1.41.0 (5e1a79984 2020-01-27)
rust-analyzer cba3c99
```

**Comment by stenpeeters** [comment]
I observed the same issue in Eclipse while using the Corrosion plugin with rust-analyzer. For embedded code, with the #![no-std] attribute, Eclipse would always show the "can't find crate for 'test'" error. 

I solved the problem by creating a json file with the following content:
./rls.json

{
  "checkOnSave": {
	"allTargets": false 
	}
}

Then in Eclipse, go to Window-> Preferences --> Rust

and add the file path to the "LS configuration" field. This assumes that the Language server is properly configured.

**Comment by pooladkhay** [comment]
Fix for VSCode:
`{PROJECT_DIR}/.vscode/settings.json`:
```json
{
   "rust-analyzer.checkOnSave.allTargets": false,
}
```

**Comment by tomasApo** [comment]
@pooladkhay this also fixed my issue. I had a `#![no_std]`  test crate issue for months on VSCODE. Thank you

**Comment by mlavacca** [comment]
With the `rust-analyzer` VSCode plugin's latest version (v0.3), the fix is:
```json
{
   "rust-analyzer.check.allTargets": false,
}
```

**Comment by casey-SK** [comment]
The above solutions did not work. However, the following removed the error:

```json
{
    "rust-analyzer.check.allTargets": false,
}
```

**Comment by cf1048596** [comment]
Just a heads up for those using neovim but not coc.nvim but using nvim-lspconfig (I for one as I'm using nvchad) have managed to setup the following workaround for rust-analyzer to find the settings.json and use that.

`local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities
local lspconfig = require("lspconfig")
local util = require "lspconfig/util"

-- Function to load settings from the .nvim/settings.json file
local function load_project_settings()
    local settings_file = util.root_pattern("Cargo.toml")(vim.fn.getcwd()) .. '/.nvim/settings.json'
    print("Loading settings from: " .. settings_file)
    if vim.fn.filereadable(settings_file) == 1 then
        local file = io.open(settings_file, "r")
        local content = file:read("*a")
        file:close()
        local settings = vim.fn.json_decode(content)
        print("Loaded settings: " .. vim.inspect(settings))
        return settings
    else
        print("Settings file not found")
        return nil
    end
end

-- Check if Cargo.toml exists
local cargo_toml_path = util.root_pattern("Cargo.toml")(vim.fn.getcwd())
if cargo_toml_path then
    -- Load project-specific settings
    local project_rust_analyzer_settings = load_project_settings()

    -- Setup rust_analyzer with project-specific settings if available
    local rust_analyzer_settings = {
        ['rust-analyzer'] = {
            cargo = {
                allFeatures = true,
            },
        },
    }

    if project_rust_analyzer_settings then
        if project_rust_analyzer_settings["rust.target"] then
            rust_analyzer_settings['rust-analyzer'].cargo.target = project_rust_analyzer_settings["rust.target"]
        end
        if project_rust_analyzer_settings["rust.all_targets"] ~= nil then
            rust_analyzer_settings['rust-analyzer'].cargo.allTargets = project_rust_analyzer_settings["rust.all_targets"]
        end
    end

    print("Final rust-analyzer settings: " .. vim.inspect(rust_analyzer_settings))

    lspconfig.rust_analyzer.setup({
        on_attach = on_attach,
        capabilities = capabilities,
        filetypes = {"rust"},
        root_dir = util.root_pattern("Cargo.toml"),
        settings = rust_analyzer_settings,
    })

    -- Check and load project-specific configuration for rust_analyzer
    local project_config_path = cargo_toml_path .. '/.nvim/rust_analyzer_config.lua'
    if vim.fn.filereadable(project_config_path) == 1 then
        dofile(project_config_path)
    end
else
    print("Cargo.toml not found, skipping rust-analyzer setup")
end
`

**Comment by cf1048596** [comment]
Just a heads up for those using nvim-lspconfig as opposed to coc.nvim (I for one am, as I'm using nvchad), I came up with the following workaround to allow rust-analyzer to find and utilize a settings.json file if placed in a hidden .nvim folder relative to the root directory/where Cargo.toml exists.

`local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities
local lspconfig = require("lspconfig")
local util = require "lspconfig/util"

-- Function to load settings from the .nvim/settings.json file
local function load_project_settings()
    local settings_file = util.root_pattern("Cargo.toml")(vim.fn.getcwd()) .. '/.nvim/settings.json'
    print("Loading settings from: " .. settings_file)
    if vim.fn.filereadable(settings_file) == 1 then
        local file = io.open(settings_file, "r")
        local content = file:read("*a")
        file:close()
        local settings = vim.fn.json_decode(content)
        print("Loaded settings: " .. vim.inspect(settings))
        return settings
    else
        print("Settings file not found")
        return nil
    end
end

-- Check if Cargo.toml exists
local cargo_toml_path = util.root_pattern("Cargo.toml")(vim.fn.getcwd())
if cargo_toml_path then
    -- Load project-specific settings
    local project_rust_analyzer_settings = load_project_settings()

    -- Setup rust_analyzer with project-specific settings if available
    local rust_analyzer_settings = {
        ['rust-analyzer'] = {
            cargo = {
                allFeatures = true,
            },
        },
    }

    if project_rust_analyzer_settings then
        if project_rust_analyzer_settings["rust.target"] then
            rust_analyzer_settings['rust-analyzer'].cargo.target = project_rust_analyzer_settings["rust.target"]
        end
        if project_rust_analyzer_settings["rust.all_targets"] ~= nil then
            rust_analyzer_settings['rust-analyzer'].cargo.allTargets = project_rust_analyzer_settings["rust.all_targets"]
        end
    end

    print("Final rust-analyzer settings: " .. vim.inspect(rust_analyzer_settings))

    lspconfig.rust_analyzer.setup({
        on_attach = on_attach,
        capabilities = capabilities,
        filetypes = {"rust"},
        root_dir = util.root_pattern("Cargo.toml"),
        settings = rust_analyzer_settings,
    })

    -- Check and load project-specific configuration for rust_analyzer
    local project_config_path = cargo_toml_path .. '/.nvim/rust_analyzer_config.lua'
    if vim.fn.filereadable(project_config_path) == 1 then
        dofile(project_config_path)
    end
else
    print("Cargo.toml not found, skipping rust-analyzer setup")
end`

**Comment by cf1048596** [comment]
Just a heads up for those using nvim-lspconfig instead of coc-nvim, (particularly if you're using something similar to @dreamsofcode on youtube's nvim setup like myself). Here's an example workaround to get neovim to look for a settings.json file in a .nvim subdirectory relative to the root directory/where Cargo.toml lives.

```
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities
local lspconfig = require("lspconfig")
local util = require "lspconfig/util"

-- Function to load settings from the .nvim/settings.json file
local function load_project_settings()
    local settings_file = util.root_pattern("Cargo.toml")(vim.fn.getcwd()) .. '/.nvim/settings.json'
    print("Loading settings from: " .. settings_file)
    if vim.fn.filereadable(settings_file) == 1 then
        local file = io.open(settings_file, "r")
        local content = file:read("*a")
        file:close()
        local settings = vim.fn.json_decode(content)
        print("Loaded settings: " .. vim.inspect(settings))
        return settings
    else
        print("Settings file not found")
        return nil
    end
end

-- Check if Cargo.toml exists
local cargo_toml_path = util.root_pattern("Cargo.toml")(vim.fn.getcwd())
if cargo_toml_path then
    -- Load project-specific settings
    local project_rust_analyzer_settings = load_project_settings()

    -- Setup rust_analyzer with project-specific settings if available
    local rust_analyzer_settings = {
        ['rust-analyzer'] = {
            cargo = {
                allFeatures = true,
            },
        },
    }

    if project_rust_analyzer_settings then
        if project_rust_analyzer_settings["rust.target"] then
            rust_analyzer_settings['rust-analyzer'].cargo.target = project_rust_analyzer_settings["rust.target"]
        end
        if project_rust_analyzer_settings["rust.all_targets"] ~= nil then
            rust_analyzer_settings['rust-analyzer'].cargo.allTargets = project_rust_analyzer_settings["rust.all_targets"]
        end
    end

    print("Final rust-analyzer settings: " .. vim.inspect(rust_analyzer_settings))

    lspconfig.rust_analyzer.setup({
        on_attach = on_attach,
        capabilities = capabilities,
        filetypes = {"rust"},
        root_dir = util.root_pattern("Cargo.toml"),
        settings = rust_analyzer_settings,
    })

    -- Check and load project-specific configuration for rust_analyzer
    local project_config_path = cargo_toml_path .. '/.nvim/rust_analyzer_config.lua'
    if vim.fn.filereadable(project_config_path) == 1 then
        dofile(project_config_path)
    end
else
    print("Cargo.toml not found, skipping rust-analyzer setup")
end
```

**Comment by richy1623** [comment]
Just posting this here in case anyone uses the Zed editor and has the same issue

Include the following in your project `.zed/settings.json`:
```json
"lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "checkOnSave": {
          "allTargets": false,
        },
      },
    },
  },
```

**Comment by Sympatron** [comment]
This seems to have changed. I had to use the following:
```json
"lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "cargo": {
          "allTargets": false,
        },
      },
    },
  },
```

**Comment by ahsanu123** [comment]
in neovim with lazyextra rustaceanvim, you can do 

```shell
// add this in the end of neovim configuration init.lua
vim.o.exrc = true
```

then create `.nvim.lua` in project directory 
```lua
vim.g.rustaceanvim = {
	server = {
		default_settings = {
			["rust-analyzer"] = {
				cargo = {
					allTargets = false,
				},
			},
		},
	},
}
```

when first opening neovim it will detect `.nvim.lua` local config, you need to view then trust it (as described when first open), then  error about test in nostd fixed.
