### ISSUE TITLE
Auto-import should respect std/extern/crate order

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3301]
![image](https://user-images.githubusercontent.com/1711539/75238460-4f5cae00-57c1-11ea-94ef-b220d7dbdf0d.png)

`TraitId` is misplaced, it should have been added to the second group. Before we fix import insertion infra to do this, it maybe make sense to move it to a separate module inside `utils` and in general to refactor code. I think it was introduced *before* we even had the modern make/edit APIs?

cc @SomeoneToIgnore

**Comment by SomeoneToIgnore** [comment]
Does that get fixed by the `cargo fmt`?
I'm noe entirely sure that we need to dive that deep into determining the specific place for an import if it's possible to reformat it after importing.

**Comment by matklad** [comment]
>Does that get fixed by the cargo fmt?

I don't think so. And, anyway, we should eventually subsume rustfmt, so this functionality needs to be implemented anyway ^^

**Comment by flodiebold** [comment]
cargo fmt just reorders imports within groups (i.e. where there's not a blank line in between), and only by ordering alphabetically, as far as I know.

**Comment by matklad** [comment]
I've moved code for inserting uses to the `utils` module.  I haven't refactored it yet. But I've scetched an interface we want in the end:


```rust
pub fn insert_use(where_: SyntaxNode, path: ModPath) -> SyntaxNode {
    let use_item = make::use_item(path);

    let use_scope: UseScope = UseScope::cast(where_).unwrap();
    for existing_use in use_scope.imports() {
        if let Some(merged) = try_merge_two_imports(existing_use, &use_item) {
            return algo::replace_children(where_, existing_use, merged);
        }
    }

    let group: ImportGroup = ImportGroup::new(path);
    let insert_position: InsertPosition<SyntaxElement> = find_insert_position(&use_scope, group);

    algo::insert_children(&where_, insert_position, vec![use_item].into_iter())
}

enum UseScope {
    SourceFile(ast::SourceFile),
    ItemList(ast::ItemList),
}

impl UseScope {
    fn imports(&self) -> AstChildren<ast::UseItem> {
        todo!()
    }
}

fn try_merge_two_imports(lhs: &ast::UseItem, rhs: &ast::UseItem) -> Option<ast::UseItem> {
    todo!()
}

enum ImportGroup {
    Std,
    ExternCrate,
    ThisCrate,
    ThisModule,
    SuperModule,
}

fn find_insert_position(scope: &UseScope, group: ImportGroup) -> InsertPosition<SyntaxElement> {
    todo!()
}
```

`try_merge_two_imports` should also allow us to implement the eponymous assist.

**Comment by matklad** [comment]
>in general to refactor code.

This is super hard actually!

**Comment by SomeoneToIgnore** [comment]
I suspected that :(

**Comment by matklad** [comment]
Some minimal groundwork in https://github.com/rust-analyzer/rust-analyzer/pull/3487

**Comment by Veykril** [comment]
I think this issue can be closed, this was fixed in #5935.

**Comment by asv1** [comment]
Is auto-import order configurable? Can ordering be disabled?

**Comment by Veykril** [comment]
It is currently fixed and cannot be disabled no, though PRs to change this are welcome
