### ISSUE TITLE
fill struct fields: unknown Self?

### ISSUE THREAD

**Issue by Dushistov** [rust-analyzer/rust-analyzer#3306]
If I edit code like this:

```
pub trait Parse: Sized {
    fn parse(input: ParseStream) -> Result<Self>;
}
impl Parse for PackFieldBitflagItemValue {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
	Ok(Self { !!!!!!!!CURSOR HERE!!!!!!!
	    
	})
    }   
}
```

No assistance about "fill struct fields",
but if put cursor to `Self` it reports that `Self` actually `PackFieldBitflagItemValue`.

If I replace `Self` with `PackFieldBitflagItemValue` like this:

```Rust
impl Parse for PackFieldBitflagItemValue {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
	Ok(PackFieldBitflagItemValue {
	    
	})
    }   
}
```

then assist message appear.

Is it possible to add assistant for the first case also?
I use e2a8e891c15fdc3f92a58ac7d98df1a2914e4f7b on Linux/amd64/emacs.

**Comment by JoshMcguigan** [comment]
I believe [validate_record_literal](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_hir_ty/src/expr.rs#L64) is the function responsible for marking a struct literal as having missing fields. Currently, this function returns early when the struct literal is `Self`, when `self.infer.variant_resolution_for_expr(id)` returns `None`. 

It seems resolving this would require resolving the type of `Self` here, but I'm not sure how to do that.

**Comment by matklad** [comment]
In general, such info comes from `InferenceResult`: https://github.com/microsoft/vscode-languageserver-node/issues/576#issuecomment-592557593. I think the type of `Self { }` can be looked up in [this table](https://github.com/rust-analyzer/rust-analyzer/blob/f40ed3fcb037885e0111fc3da6ba5b9eb0bef2b4/crates/ra_hir_ty/src/infer.rs#L131), provided that we resovle `Self` correctly during type inference in the first place. This happens [here](https://github.com/rust-analyzer/rust-analyzer/blob/cf23ca771967d473a2efd0c0b0cf9f285dc3107e/crates/ra_hir_ty/src/infer/expr.rs#L207-L211) and bottoms out [here](https://github.com/rust-analyzer/rust-analyzer/blob/cf23ca771967d473a2efd0c0b0cf9f285dc3107e/crates/ra_hir_def/src/resolver.rs#L173-L177).

**Comment by matklad** [comment]
I.. am not sure where the tests for this functionality are :sweat_smile: I would expect to see them in the same module, but there are none. It might make sense to "break" the functionality, see which test fail, and move them closer to the code (maybe even with [marks](https://github.com/rust-analyzer/rust-analyzer/blob/cf23ca771967d473a2efd0c0b0cf9f285dc3107e/crates/test_utils/src/marks.rs))

**Comment by flodiebold** [comment]
I don't think we actually handle `Self {}` yet at all.

**Comment by matklad** [comment]
Haven't looked into this yet, but I expect 

https://github.com/rust-analyzer/rust-analyzer/blob/cf23ca771967d473a2efd0c0b0cf9f285dc3107e/crates/ra_hir_ty/src/infer/expr.rs#L208

to just work? Ie, it seems that this would be a relatively small fix even if it doesn't fully work yet

**Comment by flodiebold** [comment]
I also haven't really looked, but I think here
https://github.com/rust-analyzer/rust-analyzer/blob/cf23ca771967d473a2efd0c0b0cf9f285dc3107e/crates/ra_hir_ty/src/infer.rs#L428
we'll get `TypeNs::SelfType`, which we currently don't handle.

**Comment by JoshMcguigan** [comment]
> I.. am not sure where the tests for this functionality are sweat_smile I would expect to see them in the same module, but there are none. It might make sense to "break" the functionality, see which test fail, and move them closer to the code (maybe even with [marks](https://github.com/rust-analyzer/rust-analyzer/blob/cf23ca771967d473a2efd0c0b0cf9f285dc3107e/crates/test_utils/src/marks.rs))

I'd be happy to move some tests to get them closer to the code they are testing. Is there any particular file you think would be best to start with?

> I also haven't really looked, but I think here
> 
> https://github.com/rust-analyzer/rust-analyzer/blob/cf23ca771967d473a2efd0c0b0cf9f285dc3107e/crates/ra_hir_ty/src/infer.rs#L428
> 
> we'll get `TypeNs::SelfType`, which we currently don't handle.

I've confirmed that this returns a `TypeNs::SelfType(ImplId(0))`.

**Comment by matklad** [comment]
So, I think we need to move `no_such_field_diagnostics` tests to the file where we produce the diagnostics, and also move some tests for `MissingOkInTailExpr` from `ra_ide/src/diagnositcs.rs` to this `hir/src/expr.rs` as well. Specifically, tests which check the fix itself should remain in IDE, tests that check the condition under which the diangostics is produced should be in hir.
