### ISSUE TITLE
Highlight is not refreshed on insert from clipboard

### ISSUE THREAD

**Issue by max-frai** [rust-analyzer/rust-analyzer#3312]
After inserting code from clipboard, code highlighting is messed up.
<img width="250" alt="Screenshot 2020-02-26 at 02 34 00" src="https://user-images.githubusercontent.com/24208746/75300460-9473f500-5840-11ea-851e-a517120d74b8.png">

**Comment by Veetaha** [comment]
I saw this before, though couldn't find a stable reproduction for this. Guess will need to try with the clipboard, thanks!

**Comment by max-frai** [comment]
Just another tip. I use vim extension so it allows to modify source code not in edit mode on some keybindings. Also we have, for example, `Cmd + /` combination which toggles comment on active line. And this broke code highlighting. So if we comment line with that combination, it becomes grey somewhere but still colored. This works in opposite way. If we uncomment grayed line of code, it stays gray.

**Comment by max-frai** [comment]
Here is how it looks. So I commented three lines with `Cmd + /` and they are colored.
<img width="475" alt="Screenshot 2020-02-29 at 21 46 59" src="https://user-images.githubusercontent.com/24208746/75614043-05ffbc00-5b3d-11ea-9189-521dd8afbee0.png">

**Comment by Veetaha** [comment]
Thanks for the info, already looking into this!

**Comment by matklad** [comment]
Note that we are switching to a new, unrelated highlighting engine in master: https://github.com/rust-analyzer/rust-analyzer/blob/e91320632a9dfee937c3c2ba3ffafd3f5ffb22dc/editors/code/package.json#L170 (it requires code-insiders for the time being).

**Comment by max-frai** [comment]
@matklad I tried new highlighting engine and all my problems wen away. Finally I can work without this disturbing thing :) Thank you
@Veetaha

**Comment by Veetaha** [comment]
Okay, I guess this issue doesn't deserve the effort then...

**Comment by bjorn3** [comment]
I haven't seen any messed up semantic highlighting in a long time.
