### ISSUE TITLE
rust-analyzer seems to slow down vscode after a while, needs restart

### ISSUE THREAD

**Issue by schungx** [rust-analyzer/rust-analyzer#3313]
I believe this was very bad on the previous version, much better on this version, but still happens.

Upon vscode startup, snappy.  Small project.  Windows 10.

Then after a while, becomes sluggish.  CPU goes up constantly to almost 100%.  Keystrokes unresponsive.

Restart vscode... snappy again.

So I believe it has something to do with the integration between vscode and this plugin?

**Comment by edwin0cheng** [comment]
might I ask you to open the command palette with Ctrl+Shift+P, and choose `Rust Analyzer: Status` when it becomes sluggish ? It will show some basic stats about make it slow.

**Comment by schungx** [comment]
~~~
workspaces:
29 packages loaded

analysis:
814 (11mb) files
25070 (2115kb) symbols
473 trees, 128 retained
11556 trees, 128 retained (macros)


memory:
0b allocated 0b resident
gc 1623 seconds ago

requests:
 2612 textDocument/hover                  1ms
*2603 textDocument/formatting             93ms
 2604 textDocument/foldingRange           1ms
 2605 textDocument/codeAction             1ms
 2606 textDocument/documentSymbol         2ms
 2607 textDocument/codeAction             1ms
 2608 textDocument/codeAction             0ms
 2609 textDocument/hover                  0ms
 2610 textDocument/hover                  0ms
 2611 textDocument/definition             1ms
~~~

**Comment by schungx** [comment]
Looks like formatting...

**Comment by edwin0cheng** [comment]
Um, 100ms seem like to reasonable.

**Comment by schungx** [comment]
OK, restarted Vscode and now snappy.  Did the thing again and not much difference.

Probably not with your plugin then...

**Comment by edwin0cheng** [comment]
Close for now, feel free to reopen it if needed.
