### ISSUE TITLE
rust-analyzer/inlayHints request gets sent too often

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#3319]
It looks like switching between the PROBLEMS, OUTPUT, TERMINAL and DEBUG CONSOLE tabs in vscode produces the following if trace is set to messages:

[Trace - 7:59:40 AM] Sending request 'rust-analyzer/inlayHints - (35)'.
[Trace - 7:59:40 AM] Received response 'rust-analyzer/inlayHints - (35)' in 168ms.
[Trace - 7:59:41 AM] Sending request 'rust-analyzer/inlayHints - (36)'.
[Trace - 7:59:41 AM] Received response 'rust-analyzer/inlayHints - (36)' in 175ms.

This implies that inlayHints is running on each tab switch.

**Comment by Veetaha** [comment]
I did think about this lately. We send requests for inlay hints on each character type. I think we should add some heuristics on the client side to prevent unnecessary requests here:
https://github.com/rust-analyzer/rust-analyzer/blob/80f8e474a0c6a1cf477afc2141f9d6182f8b05a3/editors/code/src/inlay_hints.ts#L15-L23
@SomeoneToIgnore  any thoughts on the proper heuristics?
I bet we can skip requests if the user inserted some whitespace in the middle of existing whitespace or added characters inside of string literals etc...

**Comment by kjeremy** [comment]
I wasn't even typing in the case I outlined above. It may be worth seeing how the codeLense and codeAction features are implemented on the vscode side to see if we can draw any inspiration.

**Comment by Veetaha** [comment]
Okay, my wild guess is that this event causes inlay hints refresh here:
https://github.com/rust-analyzer/rust-analyzer/blob/80f8e474a0c6a1cf477afc2141f9d6182f8b05a3/editors/code/src/inlay_hints.ts#L9-L13
