### ISSUE TITLE
VSCode plugin: Add a setting for which subdirectories should be considered Cargo workspaces

### ISSUE THREAD

**Issue by malte-v** [rust-analyzer/rust-analyzer#3326]
Not sure if this is already possible or has been asked before, but how do I handle a project like this?
```
<vscode workspace root>
- my_rust_project/
  - src/
  - Cargo.toml
- some_other_stuff/
  - ...
- Dockerfile
```
Currently, the plugin just complains about not finding a Cargo.toml in the workspace root. I know I could just use multiple VSCode workspaces, but I'm not a big fan of that because it would get quite messy in more complex project layouts.

I would suggest adding a `rust-analyzer.cargoWorkspaces` setting to the VSCode plugin that allows one to specify multiple subdirectories which should be considered Cargo workspaces.

**Comment by lnicola** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/3309 would pretty much fix this.

**Comment by malte-v** [comment]
You're right, sorry for the duplicate.

**Comment by TzviPM** [comment]
In case anyone else runs into this, one solution that works for more deeply nested rust crates is to add a `Cargo.toml` file in the root folder of the project with a `workspace` config that references the nested folders with rust crates.

**Comment by pravic** [comment]
Can we make #3309 configurable how deep to look?
Or can we add a configuration option to specify the path to the main `Cargo.toml`?

Because now it's either a totally manual `rust-project.json` or to open an additional VSCode instance with an inner folder.

**Comment by flodiebold** [comment]
> Because now it's either a totally manual rust-project.json or to open an additional VSCode instance with an inner folder.

It's not; you just have to specify `linkedProjects`.

**Comment by pravic** [comment]
@flodiebold Do you mean that `linkedProjects` can point to `Cargo.toml`?
