### ISSUE TITLE
VS Code wrap viewport width broken with type inlays

### ISSUE THREAD

**Issue by slyngbaek** [rust-analyzer/rust-analyzer#3333]
Probably low-pri, but I noticed that in VS Code the "wrap to viewport width" setting doesn't work when rust-analyzer provides inline typehints.

Wrap to viewport width setting:
![image](https://user-images.githubusercontent.com/1216902/75386708-ffe8b180-5896-11ea-99c6-d938f690374a.png)

No typehints, wrapping to viewport works correctly:
![image](https://user-images.githubusercontent.com/1216902/75387806-b9945200-5898-11ea-9e1d-707e87883cb1.png)

With typehints, wrapping is incorrect:
![image](https://user-images.githubusercontent.com/1216902/75387751-a2556480-5898-11ea-8dda-708c7049bd3b.png)

Potentially related to #3138

**Comment by kjeremy** [comment]
I wonder if we had a really long (or multiple on one line?) code lense if they would wrap.

**Comment by Veetaha** [comment]
Inlay type hints do not contribute to the number of characters in a line which, I think, is used to compute word wrapping. I guess we should file an issue to vscode regarding CSS pseudo-elements width not being considered for word wrapping.

**Comment by lnicola** [comment]
See also https://github.com/microsoft/vscode/issues/16221.

**Comment by trevyn** [comment]
I think this is the relevant vscode issue, I added a comment about the rust-analyzer use case: https://github.com/microsoft/vscode/issues/32856

(Also, they use thumbs-up count on the issue to prioritize, so you know what to do.)

**Comment by Veykril** [comment]
We switched to the native inlay hints which to my knowledge support this.
