### ISSUE TITLE
How can I make subcommand cargo install-code work?

### ISSUE THREAD

**Issue by madmaxio** [rust-analyzer/rust-analyzer#335]
I'm on windows> error: no such subcommand: `install-code`

**Comment by matklad** [comment]
Are you running this command from within rust-analyzer directly? This is the bit of configuration which sets up this command:

https://github.com/rust-analyzer/rust-analyzer/blob/6bd92e66f1e8b828288516fb749b378087f9ab66/.cargo/config#L5

**Comment by madmaxio** [comment]
Ah, what are steps for quick start with language server? From scratch.

**Comment by matklad** [comment]
This should work, although installation on windows is only lightly tested and had problems in the past:

```
$ git clone https://github.com/rust-analyzer/rust-analyzer.git
$ cd rust-analyzer
$ cargo install-code
```

**Comment by madmaxio** [comment]
Thx a lot, will try.

**Comment by madmaxio** [comment]
Finally checked it out, works magnificent even this early stage!
