### ISSUE TITLE
Customize Rainbow Highlighting / Disable Underlining

### ISSUE THREAD

**Issue by JP-Ellis** [rust-analyzer/rust-analyzer#3358]
Is it possible to customize the rainbow highlighting in the VS Code extension?

In particular, I really wish to disable the underlining as I find that to be quite distracting (it makes me think there's an error).  Though I also would like to be able to adjust to colours to be generally more muted as I find them generally too bold.

**Comment by matklad** [comment]
You can disable rainbow highlighting via
`rust-analyzer.rainbowHighlightingOn` setting. Colors are not customizable
as they are generated randomly.

**Comment by JP-Ellis** [comment]
Are the colours *generated* at random, or select at random from a list?  Is it possible to adjust the underlying function?

And in particular, I was hoping to disable the underlining as I find it quite distracting.

**Comment by matklad** [comment]
Here's the code that generates the colors:

https://github.com/rust-analyzer/rust-analyzer/blob/4741ae785257bc894cd9a61c1d5e6479074c69b6/editors/code/src/highlighting.ts#L66

Underlining is different though -- fontStyle, including boldness, itelics
and underline comes from your editor theme. We only set textmate scope:
https://github.com/rust-analyzer/rust-analyzer/blob/4741ae785257bc894cd9a61c1d5e6479074c69b6/editors/code/src/highlighting.ts#L205-L233

Note that we are also transitioning to a new syntax highlighting engine at
the moment, you can try it out with code-insiders by setting
`"rust-analyzer.highlighting.semanticTokens": true,`

**Comment by forrestthewoods** [comment]
> Underlining is different though -- fontStyle, including boldness, itelics
and underline comes from your editor theme. 

There is for sure injection of `underline` on mutable variables. I don't know what "rainbow highlighting" is so maybe I'm mixing features. Either way, I really really really really hate the underline of mutable variables. Is there any way to turn it off?

**Comment by bjorn3** [comment]
Rainbow highlighting was a feature where every identifier would get a diferent color, but identifiers refering to the same get the same color. I think it has since been removed in the transition to the lsp api for semantic highlighting. The underlining should be disableable by customizing the highlighting configuration of vscode itself. I don't know how exactly to do it right now though.

**Comment by dmgk** [comment]
I was annoyed by variable underlining too and was able to disable it with

```
  "editor.semanticTokenColorCustomizations": {
    "[Default Light+]": {
      "rules": {
        "*.mutable": {"underline": false}
      }
    }
  }
```

This is with VS Code OSS 1.46.1 on Linux, and I think `"editor.semanticHighlighting.enabled"` needs to be `true` too for the above to work.

**Comment by chamons** [comment]
I wanted to disable variable underlying as well, and dmgk's [comment](https://github.com/rust-analyzer/rust-analyzer/issues/3358#issuecomment-648530407) was very helpful.

However, I had to change `Default Light` to `Default Dark` for it to work for me.

**Comment by a9udn9u** [comment]
> I wanted to disable variable underlying as well, and dmgk's [comment](https://github.com/rust-analyzer/rust-analyzer/issues/3358#issuecomment-648530407) was very helpful.
> 
> However, I had to change `Default Light` to `Default Dark` for it to work for me.

Or simply remove the theme matcher
```
    "editor.semanticTokenColorCustomizations": {
        "rules": {
            "*.mutable": {
                "underline": false
            }
        }
    }
```
