### ISSUE TITLE
Cyclic dependencies prevent rust-analyzer from running properly

### ISSUE THREAD

**Issue by rakanalh** [rust-analyzer/rust-analyzer#3390]
Follow up to the discussion that happened here:
https://github.com/emacs-lsp/lsp-mode/issues/1467

Emacs lsp-mode was reporting that rust-analyzer was not running although it was. At least, according to the `ps aux | grep rust-analyzer` it was indeed the case. However, rust-analyzer was not providing lsp-mode with the responses it expected.

Running rust-analyzer apparently on a large project such as [substrate](https://github.com/paritytech/substrate), it was noted that the rust-analyzer logs where as follows:

```
[ERROR ra_project_model] cyclic dependency pallet-babe -> substrate-test-runtime
[ERROR ra_project_model] cyclic dependency sc-executor -> substrate-test-runtime
[ERROR ra_project_model] cyclic dependency pallet-transaction-payment -> pallet-balances
[ERROR ra_project_model] cyclic dependency sp-runtime-interface -> sp-io
[ERROR ra_project_model] cyclic dependency sp-runtime-interface -> sp-runtime-interface-test-wasm
[ERROR ra_project_model] cyclic dependency frame-support -> frame-system
[ERROR ra_project_model] cyclic dependency sp-core -> sp-runtime-interface
[ERROR ra_project_model] cyclic dependency node-testing -> node-executor
[ERROR ra_project_model] cyclic dependency substrate-test-runtime-client -> sc-client
[ERROR ra_project_model] cyclic dependency substrate-test-runtime-client -> substrate-test-client
[ERROR ra_project_model] cyclic dependency substrate-test-runtime-client -> substrate-test-runtime
```

Although LSP reported that rust-analyzer was "initialized successfully", no service was provided by lsp mode whether that was goto-definition or autocompletion.

Note: I made sure i compiled and tested the latest master(commit: ea67e2346e64a1a14206e6d0f163c6c2e19d0afb )

**Comment by flodiebold** [comment]
One thing that might be helpful would be to run `rust-analyzer analysis-stats .` on the repository.

**Comment by matklad** [comment]
I think that's a known issue: when we lower `cargo metadata` to crate graph, we don't really make a distinction between a lib with cfg(test) and a lib without, we just forcefully enable test. However, cargo allows a test lib to depend on non-test lib

**Comment by rakanalh** [comment]
`rust-analyzer analysis-stats .` got stuck
```
✗ rust-analyzer analysis-stats .
[ERROR ra_project_model] cyclic dependency node-executor -> node-testing
[ERROR ra_project_model] cyclic dependency frame-system -> frame-support
[ERROR ra_project_model] cyclic dependency sc-executor -> substrate-test-runtime
[ERROR ra_project_model] cyclic dependency pallet-babe -> substrate-test-runtime
[ERROR ra_project_model] cyclic dependency sp-runtime-interface -> sp-core
[ERROR ra_project_model] cyclic dependency sp-runtime-interface -> sp-io
[ERROR ra_project_model] cyclic dependency sp-runtime-interface -> sp-runtime-interface-test-wasm
[ERROR ra_project_model] cyclic dependency sp-state-machine -> sp-core
[ERROR ra_project_model] cyclic dependency sp-state-machine -> sp-trie
[ERROR ra_project_model] cyclic dependency substrate-test-runtime-client -> sc-client
[ERROR ra_project_model] cyclic dependency substrate-test-runtime-client -> substrate-test-client
[ERROR ra_project_model] cyclic dependency substrate-test-runtime-client -> substrate-test-runtime
[ERROR ra_project_model] cyclic dependency pallet-balances -> pallet-transaction-payment
Database loaded, 771 roots, 2.042732236s
Crates in this dir: 213
Total modules found: 945
Total declarations: 19870
Total functions: 11732
Item Collection: 51.508743797s, 0b allocated 0b resident
440/11732 3% processing: tests::rewards_should_work
```

For like 15 minutes, still running.

**Comment by bkchr** [comment]
I'm using `rust-analyzer` with Substrate and it works without any problems. The cylic-dependency can be ignored. It does not prevents anything.

**Comment by rakanalh** [comment]
Compiling the more recent rust-analyzer versions basically resulted in the problem going away for me as well. 
Closing the issue.

**Comment by mimoo** [comment]
I've had lots of problems with rust-analyzer in the last 6 months and I think it's also due to cyclic dependencies

**Comment by peterblockman** [comment]
> When used in VSCode, having the cyclic dev dependency prevents ctrl-clicking to jump to the implementation, but no error shows up.

It still prevents ctrl + click in v0.3.1823. I am using VsCode Version: 1.85.2 (Universal).

**Comment by irvingoujAtDevolution** [comment]
Still have prevents `go to reference` with version v0.4.1952

**Comment by Veykril** [comment]
For people stumbling over this, https://github.com/rust-lang/rust-analyzer/issues/14167 is the tracking issue for this
