### ISSUE TITLE
convert identifier should rename the identifier,not only replace the declaration

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rust-analyzer/rust-analyzer#3391]
now we have the code below
```rust
let aTest = 3;
println!("{}", aTest);
```
![image](https://user-images.githubusercontent.com/17974631/75647213-3fdcd980-5c87-11ea-8682-4c83b5831bb4.png)
after we use the code refactor, the code change to 
```rust
let a_test = 3;
println!("{}", aTest);
```
however what we expect is 
```rust
let a_test = 3;
println!("{}", a_test);
```

**Comment by kiljacken** [comment]
This looks like a diagnostic provided by rustc via cargo check. That means
we don't really control the fix it suggests, and their built-in format for
suggestions is limited to a single edit at a single position, so should
probably be reported upstream as well.

@matklad I assume we could replace the fix in rust-analyzer based on the
diagnostic code. Would we want to attempt that or punt until we
implementation the diagnostic ourselves?

**Comment by matklad** [comment]
I'd rather punt on this, but I'd double check that it's indeed an upstream
issue.

**Comment by lnicola** [comment]
After #7508 we're showing two fixes, the buggy one from `rustc` and ours that works.
