### ISSUE TITLE
Cache cargo-audit on CI

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3399]
We spend five minutes of CPU time on each CI building `cargo audit`.

I think we should:

* enable caching so that we don't rebuild it each time
* install it with `--debug`, so that we don't spend as much time building it
* maybe somehow only trigger it when `Cargo.lock` changes? 

The current setup is here:

https://github.com/rust-analyzer/rust-analyzer/blob/02f761ba4bd356ef2aeae5ed8bdd750c57ade30d/.github/workflows/ci.yaml#L11-L19

**Comment by lnicola** [comment]
Either that, or [set up](https://github.com/RustSec/cargo-audit/issues/66) `cargo-audit`'s CI to build binaries.
