### ISSUE TITLE
Thoughts on homebrew and other package managers?

### ISSUE THREAD

**Issue by simlay** [rust-analyzer/rust-analyzer#3411]
Hi,

First off, I really like rust-analyzer. It's an awesome project.

I've found that y'all publish releases so quickly that I've found it a pain to update. I download the compiled release, I `mv` it to `~/.cargo/bin/rust-analyzer` and then I have to make macOS allow for this downloaded executable. I know, it's a rough life when one of your favorite projects is moving so quickly that you get annoyed with updating.

Anyway, no one else has brought up the topic of package managers. So, I figured I'd bring it up.

**Comment by matklad** [comment]
Which editor do you use? Updating rust-analyzer is the task of the editor plugin. This is implemented in VS Code and vim/coc, not sure about other plugins.

**Comment by simlay** [comment]
Interesting. I didn't know that coc had support for this. I use it with [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim).

**Comment by matklad** [comment]
So I am going to close this, as packaging for distributions is explicitly out of scope for the time being. Anybody is welcome to package rust-analyzer for their system however!
