### ISSUE TITLE
Consider monitoring Cargo.lock for changes

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#3414]
I might be wrong but I don't think we monitor `Cargo.toml` or `Cargo.lock` for changes.

If we added`Cargo.lock` to the `workspace/didChangeWatchedFiles` request and then
responded appropriately to the modification from the `DidChangeWatchedFiles` notification we could reanalyze the workspace.

**Comment by kjeremy** [comment]
@matklad I can sign up for the events but what do I do if I see `Cargo.lock` is modified? Is it enough to `vfs.notify_changed` on the root path?

**Comment by matklad** [comment]
I am afraid that's not that easy: we should re-run `cargo metadata`  and reload everything, and that needs some [re-]design around VFS, which I hope to get to in the next few months, no that watchman has a rust library.

For the time being, I am afraid the best we can do is show the "please reload rust-analyzer" message to the user.
