### ISSUE TITLE
Integration with Emacs eldoc-mode

### ISSUE THREAD

**Issue by eyingxuan** [rust-analyzer/rust-analyzer#3415]
It seems like by default, eldoc-mode will use lsp-hover, which calls textDocument/signaturehelp to display type information in the echo. This however doesn't seem to be working (the echo is blank for all symbols that work with lsp-describe-thing-at-point). I'm not sure if I've made a mistake setting this up and I'm not quite sure how to test this functionality independently.

**Comment by kjeremy** [comment]
In LSP hover is its own request so I'm not quite sure what you mean. SignatureHelp is for displaying function signatures so will only work on function-like calls.

**Comment by eyingxuan** [comment]
From lsp-mode.el, lsp-hover "Display hover info (based on `textDocument/signatureHelp').", and is also the function used for Eldoc to display messages in the echo.

**Comment by kjeremy** [comment]
Do you know what the client capabilities are? Also you're invoking
signature hellp on a function call?

**Comment by eyingxuan** [comment]
I just got into the Emacs ecosystem not long ago, so maybe someone more familiar can chime in, but I think typically eldoc-mode can show type signatures of the identifier (not just functions) at the cursor in the echo. Apparently, they use textdocument/signatureHelp. 

I also tried placing my cursor on a function, but that didn't work either. 

On that note, is there a reason why signatureHelp on works on functions?

**Comment by eyingxuan** [comment]
My mistake - it seems like lsp-hover makes a call to textDocument/hover even though the documentation says textDocument/signatureHelp.

**Comment by alxiong** [comment]
@eyingxuan  I saw that you also use Doom, did you get your eldoc works with rust analyzer? I switch from binding rls to rust-analyzer, and eldoc stops working.

**Comment by eyingxuan** [comment]
By default, placing your cursor on a symbol doesn't show anything in the minibuffer. But, if you set lsp-eldoc-render-all to true, all documentation for the symbol will display. I found that pretty annoying so I turned it off, but it must be that there is a way to structure the textDocument/hover information so that only the symbol information shows up in the minibuffer (with lsp-eldoc-render-all set to nil). Haven't quite figured out how that would work though.

**Comment by alxiong** [comment]
I'm not savvy in lsp, but to decide whether this is language server issue or client issue. I mean apparently lsp-mode.el as a client works perfectly fine with rls as the server, so I would assume it's `rust-analyzer` server that didn't support some of [APIs here](https://github.com/rust-lang/rls/blob/master/clients.md#required-message-support) (e.g. `testDocument/hover` like you suspect).
