### ISSUE TITLE
rename field ignore constructor

### ISSUE THREAD

**Issue by davemilter** [rust-analyzer/rust-analyzer#3431]
Consider such code:

```rust
struct Foo {
    i: i32,
}

impl Foo {
    fn new(i: i32) -> Self {
        Self { i }
    }
}
```

if I put cursor on i field:

```rust
struct Foo {
    i<CURSOR HERE>: i32,
}
```
it renames only i in `struct Foo` definition. But `Self { i }` remains the same,
so this cause error during compilation.

**Comment by matklad** [comment]
I believe this should be fixed somewhere around here: https://github.com/rust-analyzer/rust-analyzer/blob/a5da660bd5953c046db5f0bff854c00d830da9c8/crates/ra_ide/src/references/rename.rs#L125-L129.

We also should tweak the [`Reference`](https://github.com/rust-analyzer/rust-analyzer/blob/a5da660bd5953c046db5f0bff854c00d830da9c8/crates/ra_ide_db/src/search.rs#L24-L29) stuct to allow remember the fact that a particular reference is a field init shorthand and needs special handling. 

The expected result after rename is `Self { i: new_name }`

**Comment by peddermaster2** [comment]
> The expected result after rename is `Self { i: new_name }`

I hope you mean `Self { new_name: i }`
