### ISSUE TITLE
"return expression directly" action removes expression.

### ISSUE THREAD

**Issue by Kibouo** [rust-analyzer/rust-analyzer#3433]
**Description:** RA provides the code action "return expression directly" when having a useless ``let``-binding (variable being returned immediately). Performing the action deletes the actual code (binding + expression) instead of the return statement.

**Reproduce:**
1. [load example code](https://play.integer32.com/?version=stable&mode=debug&edition=2018&code=fn%20foo()%20-%3E%20Vec%3Cusize%3E%0A%7B%0A%20%20%20%20let%20a%20%3D%20(0..10).collect()%3B%0A%20%20%20%20a%0A%7D%0A%0Afn%20main()%20%7B%20foo()%3B%20%7D%0A)
2. place cursor on the line of the return statement (line 4; ``a``)
3. invoke the code action ("return expression directly")

**Expected result:** the binding of the expression, the ``;`` after it, and the line returning the variable are removed. *Not* the binding/expression while keeping the return statement (of a now invalid variable).

**Comment by Kibouo** [comment]
**Version:**
- extension ``rust-analyzer 0.1.20200302`` from VSCode extension market
- ``rust-analyzer --version`` -> ``rust-analyzer f761ed2``

**Comment by matklad** [comment]
cc @kiljacken I believe this is comming from clippy. Could you check if it's a clippy bug, or if we interpret the edit wrongly? 

Our own "inline variable" assist works ok with this case though :)

**Comment by kiljacken** [comment]
In this case, clippy includes a two part replacement, and we seemingly only apply the first part. I'll look into it at some point during the week.
