### ISSUE TITLE
Vscode: Error encountered when viewing previous version from Git history

### ISSUE THREAD

**Issue by schungx** [rust-analyzer/rust-analyzer#3435]
View file content from Git history, starts getting this error.

~~~
[crates\ra_ide\src\syntax_highlighting.rs:218] match element.parent().map(|it| it.kind()) {
    Some(LIFETIME_PARAM) | Some(LABEL) => h | HighlightModifier::Definition,
    _ => h,
} = Highlight {
    tag: Lifetime,
    modifiers: HighlightModifiers(
        0,
    ),
}
~~~

Error will persist even if the history file is closed.

**Comment by matklad** [comment]
I think this is just a stray `dbg!` which was remofed in https://github.com/rust-analyzer/rust-analyzer/commit/8f3677a94a3ff77c9d2d1784b0c8d5f777e46c3b#diff-1a46f1499436ea116d345698c150068a
