### ISSUE TITLE
Assist: replace parameter with self, replace self with parameter

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3439]
I often move free standing functions into methods and vice verse. The annoying mechanical bit of this transformation is changing `&self` into `foo: &Foo` and back. We should have an assist which does this automatically.

![image](https://user-images.githubusercontent.com/1711539/75875794-ae02d700-5e14-11ea-8a69-202a14f1b091.png)

=> 

![image](https://user-images.githubusercontent.com/1711539/75875837-c3780100-5e14-11ea-9a3f-cdac492a6c1a.png)

A good somewhat relevant example of an assist is [inline local variable](https://github.com/rust-analyzer/rust-analyzer/blob/66ec6bdfb0fbb8e99b58f3c184ef5012354e6d92/crates/ra_assists/src/handlers/inline_local_variable.rs). Another bit too look at would be the the [search infra](https://github.com/rust-analyzer/rust-analyzer/blob/66ec6bdfb0fbb8e99b58f3c184ef5012354e6d92/crates/ra_ide/src/references.rs#L110-L114) because, essentially, what we need is to find all usages of `self` and rename them. Perhaps it's even better to literally use `rename` here, instead of a separate assist? Like, we notice if the target name is magical, `self`, and do a slightly different thing in this case. 

The irony is that I need this for refactoring search infrastructure itself :D

**Comment by lnicola** [comment]
@zbsz can this be closed now?

**Comment by zbsz** [comment]
Yes, I think so.
