### ISSUE TITLE
VsCode: generate configuration for debugging

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-analyzer/rust-analyzer#3441]
This is a feature request. VS Code has built-in support for debugging through [CodeLLDB](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb) and [VS Code cpptools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools). These extensions can generate configuration for [launch.json](https://code.visualstudio.com/Docs/editor/debugging) through a menu that looks like this:

![Slice 1](https://user-images.githubusercontent.com/2467194/75876541-2c13ad80-5e16-11ea-8332-88f450090d14.jpg)

Getting the configuration right for Rust projects is a bit of a tricky one, with some nuance on how to properly target binaries, libraries, and tests across all major platforms. Since `rust-analyzer` is providing a premier Rust experience in VS Code, this might be an interesting feature to add.

## References

- I believe [this section](https://code.visualstudio.com/api/extension-guides/debugger-extension#using-a-debugconfigurationprovider) outlines how to add this functionality to VS Code extensions.
- [This post](https://jason-williams.co.uk/debugging-rust-in-vscode) shares a basic debugging setup for VS Code.

**Comment by Veetaha** [comment]
Isn't this the domain of [vscode-lldb](https://github.com/vadimcn/vscode-lldb) extension?

**Comment by matklad** [comment]
nope, to run a test you need to know what a test is, and, with macros, only
rust-analyzer can really know that.

**Comment by vsrs** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/4366 already has the code to generate launch configurations, so I'll start work on this issue.
