### ISSUE TITLE
Completions to not show for function with same name as mod

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#3444]
In the following:

```rust
mod mymod {
    pub fn foo() {}

    pub mod foo {}
}

fn main() {
    mymod::fo<|>
}
```

Completions for the cursor position only show the module `foo` and not the function `foo`.

**Comment by matklad** [comment]
I believe this is a deeper problem with us not always handling namespaces correctly.

**Comment by JoshMcguigan** [comment]
I've opened #3553 in an attempt to fix this. I've got a test which demonstrates this issue, but I'm struggling to pin down where the fix would need to happen.
