### ISSUE TITLE
Flatten highlights

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3447]
The `highlight` function currently returns a `Vec<HighlightedRange>`. However, those highlighting ranges can be nested. I believe that for something like `#[cfg(feature = "foo")]` we produce the range for the whole attribute, and then, separately, a range for a string literal.

It seems like all the clients of syntax highlighting actually want a flat list of highlights. We should refactor `highlight` so that it produces such flat list. One obvious way to do this is to post-process the current return type, but, given that internally we walk the tree in dfs manner, perhaps we can just not produce nested things in the first place? 

The relevant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/a5da660bd5953c046db5f0bff854c00d830da9c8/crates/ra_ide/src/syntax_highlighting.rs#L34-L38

**Comment by ltentrup** [comment]
I have had a look at the specific code and I would like to work on it.
My first idea is to use a stack `Vec<Vec<HighlightedRange>>` mirroring the DFS traversal. When leaving a node, one can implement the flattening.
To implement the flattening itself, one has to clone `HighlightedRange` but it does not implement `Clone`:

https://github.com/rust-analyzer/rust-analyzer/blob/a5da660bd5953c046db5f0bff854c00d830da9c8/crates/ra_ide/src/syntax_highlighting.rs#L27-L32

I am not sure about the semantics of `binding_hash`, can it be cloned or must it be unique?

**Comment by lnicola** [comment]
@matklad do we still want the rainbow stuff after #3820? It's only used in a test.

**Comment by matklad** [comment]
We need to keep it internally, as this is a useful (and somewhat tricky
with respect to shadowing) feature to have. However, the impl should
probably be changed to a separate request, independent of the main
highlighting.

**Comment by kjeremy** [comment]
Did #3826 solve this?
