### ISSUE TITLE
Cross compile all the things. 

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3448]
At the moment, we are building all our releases via actions pipeline in release.yaml. Programming in yaml is not fun though, I would much prefer to call `cargo xtask dist` and have all the binaries for all platforms & arches build into a `./dist` directory. 

The prerequisite here is of course that we need to be able to cross-compile from Linux to Windows and Mac OS. I haven't looked into that, but, ideally, we should *just* use lld, which is a native cross-linker.

If someone with experience of cross-compilation for desktop platforms can chime in here, that would be helpful!

**Comment by bjorn3** [comment]
`lld` for Mach-O is pretty much unmaintained. I believe it also sometimes causes the final executable to SIGSEGV.

**Comment by matklad** [comment]
Yeah, I am not sure what's worse: running three builders, or running docker... Both add a lot of accidental complexity to the process.

**Comment by lnicola** [comment]
I think the current setup works pretty well. Should we still keep this open?

**Comment by matklad** [comment]
I think we still should do this, long term, but I believe this is blocked
in upstream at the moment, so we’d better close this.
