### ISSUE TITLE
Highlighting breaks on delete+undo in rapid succession

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#3452]
tldr:
![wasmtime-1583336074959](https://user-images.githubusercontent.com/3784017/75896003-fea41f80-5e68-11ea-896d-df60886ac0f3.gif)

Revision 66ec6bd.

**Comment by matklad** [comment]
Do you have `"rust-analyzer.highlighting.semanticTokens": true,`? That enabels the new, completely unrelated highlighting implemenation

**Comment by 0x7CFE** [comment]
> Do you have `"rust-analyzer.highlighting.semanticTokens": true,`? That enabels the new, completely unrelated highlighting implemenation

No, I haven't enabled it yet, since it forces me to start RA in a specific way, i.e. simply clicking a tick box in the settings does not work.

By the way, previously types useses in code were highlighted in the same manner as type declarations (cyan-ish green). Now only system types are highlighted that way for me, others remain white. Is this related to refactoring in the highlighting system?

**Comment by 0x7CFE** [comment]
> Probably yeah: some tag names changed, and the old mapping was not updated

I've filed an issue https://github.com/rust-analyzer/rust-analyzer/issues/3455

**Comment by 0x7CFE** [comment]
@matklad, actually I've just enabled new proposed API for semantic highlighting and it still does not highlight types for me. Honestly, I couldn't even say what syntax elements were highlighted by RA and what came just from the color theme (default Dark+ with tweaked `editor` `.background` and `.foreground` colors):

![image](https://user-images.githubusercontent.com/3784017/75969369-702fac80-5f01-11ea-9e89-abcdd91960d5.png)

**Comment by lnicola** [comment]
@0x7CFE the old implementation is gone, and we should have plenty of colors now:

![image](https://user-images.githubusercontent.com/308347/102774901-8b867e00-4394-11eb-9ef7-acc4709fa2bd.png)

Please file a new issue if you still have problems.
