### ISSUE TITLE
Old highlighting system does not highlight types and variable declarations

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#3455]
Based on @matklad's guesss https://github.com/rust-analyzer/rust-analyzer/issues/3452#issuecomment-594628050

![image](https://user-images.githubusercontent.com/3784017/75898743-11b8ee80-5e6d-11ea-9356-9b04b74d80c5.png)

Note that types like `HashMap`, struct fields as well as variable declarations are no longer highlighted properly.

Revision 66ec6bd.

**Comment by 0x7CFE** [comment]
Looks like highlighting does not work for me even with new proposed API enabled.

**Comment by matklad** [comment]
The old highlighting is now completely removed.

**Comment by 0x7CFE** [comment]
@matklad, I've switched to new API but still I do not see highlighting of let bindings and types.  Is this intentional?

![image](https://user-images.githubusercontent.com/3784017/78333282-bedd6e80-75b3-11ea-87dd-a3bc5270fab3.png)

I'm expecting `BitVector` to be highlighted in cyan in the same manner as in popup. Also let bindings are not colored.

**Comment by matklad** [comment]
I think that means that the colors are just not set up in the theme. With Dark+ I get

![image](https://user-images.githubusercontent.com/1711539/78352256-5937b500-75a8-11ea-9e2b-6002304a7539.png)

With Pale fire:

![image](https://user-images.githubusercontent.com/1711539/78352334-78364700-75a8-11ea-9bdc-f5d9ab4f1782.png)


Inspect tokens and scopes is a useful action for troubleshooting:

![image](https://user-images.githubusercontent.com/1711539/78352432-98fe9c80-75a8-11ea-9597-a6c87870b75a.png)

**Comment by SomeoneToIgnore** [comment]
Some additional helpful debugging info can be found here: https://github.com/rust-analyzer/rust-analyzer/issues/3822

**Comment by 0x7CFE** [comment]
> I think that means that the colors are just not set up in the theme. With Dark+ I get

:confused: Maybe I'm missing something but I use the very default Dark+ theme. The only changes I've made are these customizations in `settings.json`:

```json
"workbench.colorCustomizations": {
    "editor.background": "#101010",
    "editor.foreground": "#e0e0e0",
},
```

Could you please elaborate on what do you mean by setting up colors?

**Comment by 0x7CFE** [comment]
I've installed Pale Fire theme and redid your text:

![image](https://user-images.githubusercontent.com/3784017/78356458-cca5ea80-75d9-11ea-84dd-b70af9ef4ba0.png)

P. S.: rust-analyzer version: unreleased (642f3f4)

**Comment by matklad** [comment]
Do you have these settings enabled?

```
{
    "rust-analyzer.highlighting.semanticTokens": true,
    "editor.semanticHighlighting.enabled": true,
}
```

**Comment by 0x7CFE** [comment]
The latter setting wasn't set in my case, but it seems it still does not work even after I added the setting.

**Comment by matklad** [comment]
Hm, I guess my last guess is to try to reload VS Code and check if `Inspect tokens and scopes` shows semantic tokens.... Other than that, genuinely have no idea what might be the problem :(

**Comment by 0x7CFE** [comment]
> Hm, I guess my last guess is to try to reload VS Code and check if `Inspect tokens and scopes` shows semantic tokens.... Other than that, genuinely have no idea what might be the problem :(

![image](https://user-images.githubusercontent.com/3784017/78358347-3d9ad180-75dd-11ea-9a77-730864616f0f.png)

**Comment by Veetaha** [comment]
I think you should run vscode with
```
code-insiders --enable-proposed-api matklad.rust-analyzer
```

**Comment by 0x7CFE** [comment]
> I think you should run vscode with
> 
> ```
> code-insiders --enable-proposed-api matklad.rust-analyzer
> ```

Yep, that fixed the issue :man_facepalming: On a side note, type aliases remain uncolored.

**Comment by Veetaha** [comment]
Unfortunately, the default theme may not support all the textmate scopes that we map our semantic tokens to. If you want, you can setup custom coloring semantic tokens directly.
Here are [my overrides](https://gist.github.com/Veetaha/2120aa0c49c319adc0d29d64a47b010c#file-settings-json-L59-L104) for the most part of available semantic tokens if this helps...

**Comment by SomeoneToIgnore** [comment]
I wonder why do we need `--enable-proposed-api matklad.rust-analyzer` when the tokens are "stable" in the insiders build.
