### ISSUE TITLE
Completion not working with the gl crate

### ISSUE THREAD

**Issue by AkitakiKou** [rust-analyzer/rust-analyzer#3467]
# The problem

I'm recently trying to write OpenGL related code with [the `gl` crate](https://crates.io/crates/gl), and found out that completion doesn't work with it. Typing `gl::` and triggering completion shows nothing.

From [this issue from gl-rs](https://github.com/brendanzab/gl-rs/issues/512), it seems that this is due to the `gl::*` functions being generated by a build script. Is there any workarounds to make completions work with this crate?

# Environment

- version: `rust-analyzer 9090c45`, automatically downloaded by the coc-rust-analyzer plugin for coc.nvim
- OS: Manjaro Linux, kernel 5.4.18
- Editor: vim 8.2

**Comment by edwin0cheng** [comment]
> From this issue from gl-rs, it seems that this is due to the gl::* functions being generated by a build script. Is there any workarounds to make completions work with this crate?
Environment

As i know, there is no easy workarounds for builds script completions yet. However, since https://github.com/rust-lang/cargo/pull/7622 are landed in stable, we are ready to implement all the machinery macros (which are on my high priority task list):

* `include!`
* `concat!`(implemented in #3392) 
* `env!` 

So please stay tuned :)

Closed in flavor of #1964

**Comment by TimVanDyke** [comment]
For a workaround until then, 
https://nercury.github.io/rust/opengl/tutorial/2018/02/12/opengl-in-rust-from-scratch-06-gl-generator.html
See the note at the bottom about autocomplete (It is working for functions but not for enums when you use this workaround)

**Comment by matklad** [comment]
It works in master:

![image](https://user-images.githubusercontent.com/1711539/77040863-1e832980-69b9-11ea-9ea2-1534ef0a64ac.png)

**Comment by TimVanDyke** [comment]
Can you test it with an enum such as ```gl::TEXTURE_2D```? 
https://github.com/rust-analyzer/rust-analyzer/issues/3648

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/77041944-1e842900-69bb-11ea-9428-78475f9cb7c4.png)

**Comment by Mershl** [comment]
As this is the top entry when searching for this issue I'll add my feedback here. With default settings the rust-analyzer plugin for VSCode currently does not show auto completions for `gl`. @matklad Was the necessary optional cargo feature renamed?

**Comment by memoryruins** [comment]
@Mershl the option was renamed to `rust-analyzer.cargo.runBuildScripts`, which is enabled by default these days. Testing the above screenshots works for me after the project is indexed. Double-check that the option is enabled and that completions are working for other crates/modules. Some troubleshooting steps in https://rust-analyzer.github.io/manual.html#troubleshooting

**Comment by flodiebold** [comment]
`rust-analyzer.cargo.buildScripts.enable` is true by default.

**Comment by CodesOtakuYT** [comment]
@flodiebold I just installed windows 11, vscode and rustanalyzer plugin and it wasn't there by default.

**Comment by CodesOtakuYT** [comment]
@flodiebold I just removed it and it still works, but it didn't work before adding the option in the first place.

**Comment by flodiebold** [comment]
There was probably some other temporary error. I can pretty much guarantee that adding that setting does not help, since it's already the default value.

**Comment by Davidos533** [comment]
In my way, `cargo clean` and `cargo build` again solve problem
