### ISSUE TITLE
Failed to download language server

### ISSUE THREAD

**Issue by judehunter** [rust-analyzer/rust-analyzer#3473]
I'm getting the following error after pressing "Download Now":

> Failed to download language server from rust-analyzer GitHub repository: Artifact rust-analyzer-windows.exe was not found in 2020-02-11 release!

I've done a clean installation of rust using rustup-init and a clean clone and install of rust-analyser.

OS: Win10 x64

**Comment by matklad** [comment]
If you are installing from source, you need to do the following:

```
    Installation complete.

    Add `"rust-analyzer.serverPath": "rust-analyzer",` to VS Code settings,
    otherwise it will use the latest release from GitHub.
```

**Comment by lnicola** [comment]
Just to be sure, which Code version are you using?

**Comment by djmcgill** [comment]
I'm getting this error trying to install the vscode extension from the marketplace: 
> Failed to download language server from the rust-analyser GitHub repository: Cannot destructure property `releaseName` of 'undefined' or 'null'
I'm happy to open a separate issue if you prefer.
Windows 10 (10.0.19041), vscode 1.42.1
I'm just going to compile from source so it's not blocking or anything.

**Comment by Veetaha** [comment]
@djmcgill The error you are having to was fixed a couple of releases ago. I guess you still have old `rust-analyzer` extension installed (or one that you built from sources before).

To fix that you should fully remove the extension and reinstall it from the marketplace:
- Open VSCode  
- Open rust-analyzer extension tab
- Click `Uninstall` button:
  ![image](https://user-images.githubusercontent.com/36276403/76264475-9a1f0100-626a-11ea-9166-f5d95560b2d9.png)
- Remove the all the cache that is left on the file-system
  ```bash
  rm -rf ~/.vscode/extensions/matklad.rust-analyzer*
  rm -rf ~/.config/Code/User/globalStorage/matklad.rust-analyzer
  ```
- Reload VSCode
- Install `rust-analyzer` from the marketplace

**Comment by Veetaha** [comment]
@judehunter If you are building from sources you should add the following to `settings.json` (as also referred by matklad):

```json
{
    "rust-analyzer.serverPath": "rust-analyzer"
}
```

**Comment by judehunter** [comment]
Sorry, I was away and couldn't answer. Changing the option in `settings.json` worked!
