### ISSUE TITLE
Find reference for macros defined by macro_rules

### ISSUE THREAD

**Issue by contrun** [rust-analyzer/rust-analyzer#3484]
We are currently able to find definition of macro defined by `macro_rules!`, but not find reference.

**Comment by matklad** [comment]
The relevant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/dd7a11eec7cfc4703214c6278d4023cc372faa90/crates/ra_ide_db/src/search.rs

**Comment by jbalint** [comment]
I started looking into and noticed that there's an incorrect test in references.rs:

```rust
    fn test_find_all_refs_macro_def() {
        let code = r#"
        #[macro_export]
        macro_rules! m1<|> { () => (()) }

        fn foo() {
            m1();
            m1();
        }"#;

        let refs = get_all_refs(code);
        check_result(
            refs,
            "m1 MACRO_CALL FileId(1) 9..63 46..48 Other",
            &["FileId(1) 96..98 StructLiteral", "FileId(1) 114..116 StructLiteral"],
        );
    }
```

First, I'm a bit confused why the function calls would be classified as struct literals. Second, in `find_usage()` what is the role of `classify_name_ref()`? Does it ever not wind up pointing to the exact same Definition instance it's called from?

**Comment by lnicola** [comment]
This seems to be working now:

![image](https://user-images.githubusercontent.com/308347/105537503-b0a33f00-5cfa-11eb-9601-9005075a905a.png)

(although I'm not sure why the code doesn't say `m1!()` and what the `StructLiteral` is supposed to be)
