### ISSUE TITLE
Editing suddenly fails: `command 'rust-analyzer.onEnter' not found`

### ISSUE THREAD

**Issue by xobs** [rust-analyzer/rust-analyzer#3507]
I've been using `rust-analyzer` for a few days now, and in the middle of editing a document vscode gave me this error: `command 'rust-analyzer.onEnter' not found`.  I am no longer able to add newlines to the file.

According to `rust-analyzer.exe --version` I'm running version 6db2da4 which appears to be after some fixes related to the vim plugin.  However, I am not using that plugin.

Reloading the window fixed the problem.

1. Why did it happen while in the middle of editing a file?
2. Why did reloading the window fix the issue?

**Comment by bjorn3** [comment]
Rust analyzer probably crashed. Is there anything on the output panel for "Rust Analyzer Language Server"? Reloading the window restarts rust analyzer, thus fixing the issue.

**Comment by Veetaha** [comment]
Did you build `rust-analyzer`  from source and set the following in your `settings.json` file?
```json
{
    "rust-analyzer.serverPath": "rust-analyzer"
}
```
Otherwise, the extension will use the prebuilt binary. To get the version of `rust-analyzer` for sure you should press <kbd>Ctrl+Shift+P</kbd> and input `> Rust Analyzer: Show RA Version`.

This is very odd that `onEnter` was deregistered in the middle of editing a document. I wish I could see the logs from `Help > Toggle Developer Tools > Console` when this happened.
If that happens again might I ask you to copy them here?

**Comment by xobs** [comment]
I've had it happen twice so far.  I'm using `rust-analyzer` built from source, which is how I got the version number `6db2da4`.

I don't recall seeing the ability to see Rust Analyzer output when it was in that state, however I see the ability to see output now.  I'll post its output next time it happens, or I'll let you know if that terminal window disappears.

**Comment by Veetaha** [comment]
@xobs, might this be related to `vscode-tree-sitter` extension? It appears that [it aborts the extension host](https://github.com/rust-analyzer/rust-analyzer/issues/3515#issuecomment-596207493) on any unhandled promise rejections, that would cause `onEnter` not working...

**Comment by xobs** [comment]
It's entirely possible another extension is doing something like that, but no, I don't have `vscode-tree-sitter` installed.  I do have several others, and I'll start disabling those to see if that improves things.

**Comment by lnicola** [comment]
@xobs are you still seeing this?

Node that we now disable `onEnter` by default.

**Comment by xobs** [comment]
I haven't seen this in a while, so I will close this as it is no longer reproducible. Thanks!
