### ISSUE TITLE
Doc not shown for item if there is a gap between comment and it

### ISSUE THREAD

**Issue by crumblingstatue** [rust-analyzer/rust-analyzer#3510]
![image](https://user-images.githubusercontent.com/1521976/76140967-185b8780-6060-11ea-8968-13f6fb0aa851.png)
![image](https://user-images.githubusercontent.com/1521976/76140981-31643880-6060-11ea-99bb-9d94154c0773.png)

vscode extension ver: 0.1.20200302
(Not sure how to get the version of the server it downloads)

**Comment by edwin0cheng** [comment]
> (Not sure how to get the version of the server it downloads) 

You could press `Shift P` and choose `Show RA Version`

**Comment by Veetaha** [comment]
The version should be the same as the version of the extension, but anyway, who knows :sweat_smile:

**Comment by matklad** [comment]
fixed on master
