### ISSUE TITLE
rust-analyzer can't get data on rustc internals

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-analyzer/rust-analyzer#3517]
When using rust-analyzer on clippy for example, it seems to fail to get a lot of info on functions/types that come from rustc, for example:
````rust
#![feature(rustc_private)]
extern crate rustc_lint;

pub fn register_pre_expansion_lints(_store: &mut rustc_lint::LintStore) {}

fn main() {}
````
Hovering `rustc_lint::LintStore` did not provide any type information.

I tried the same with the clippy submodule inside the rustc-repo hoping that could solve it but to no avail.

**Comment by flodiebold** [comment]
I think `rustc_lint` comes from the sysroot here, right? But it isn't included in the `rust-src` component, so we don't have the source. You could try overriding the dependency in Cargo.toml with a path dependency that points to the source :thinking:

**Comment by bjorn3** [comment]
The `rustc` crate is included in `rust-src`, but many other rustc private crates aren't.

**Comment by matthiaskrgr** [comment]
> You could try overriding the dependency in Cargo.toml with a path dependency that points to the source thinking

````toml
[dependencies]
rustc_lint = { path = "/home/matthias/vcs/github/rust/src/librustc_lint"}
````
makes it work indeed! :+1:

**Comment by montrivo** [comment]
Linking this relevant ticket: https://github.com/intellij-rust/intellij-rust/issues/1618

**Comment by flip1995** [comment]
After https://github.com/rust-lang/rust/pull/76856, this could be done with implementing https://github.com/rust-analyzer/rust-analyzer/blob/96e988fcc3be11acc89dc2c1957bc14e8f39c911/crates/project_model/src/sysroot.rs#L108 for `$(rustc --print sysroot)/lib/rustlib/rustc-src/rust/compiler`, IIUC.
