### ISSUE TITLE
Avoiding analyzing generated source files

### ISSUE THREAD

**Issue by doxxx** [rust-analyzer/rust-analyzer#3522]
I'm using the `peg` crate to generate a parser from a grammar file. The generated source file goes into a path like `c:\Users\Gordon\dev\rust\raytracer\target\debug\build\raytracer-3d13643eb96c3e68\out\sdl_grammar.rs`.

I'm getting errors from `rust-analyzer` about this file:

```
[ERROR rust_analyzer::main_loop] File with cargo diagnostic not found in VFS: c:\Users\Gordon\dev\rust\raytracer\target\debug\build\raytracer-3d13643eb96c3e68\out\sdl_grammar.rs
```

I've tried various ways of excluding this file with the `excludeGlobs` setting:

* `sdl_grammar.rs`
* `target/*/sdl_grammar.rs`
* `target/**/sdl_grammar.rs`
* `target/debug/build/raytracer-3d13643eb96c3e68/out/sdl_grammar.rs`
* `target\\debug\\build\\raytracer-3d13643eb96c3e68\\out\\sdl_grammar.rs`
* `c:\\Users\\Gordon\\dev\\rust\\raytracer\\target\\debug\\build\\raytracer-3d13643eb96c3e68\\out\\sdl_grammar.rs`
* `c:/Users/Gordon/dev/rust/raytracer/target/debug/build/raytracer-3d13643eb96c3e68/out/sdl_grammar.rs`

None of these have worked.

**Comment by doxxx** [comment]
The `target` folder is in my `.gitignore`.

**Comment by kiljacken** [comment]
It's a `cargo check` reported error, so we don't really have a way to ignore it in rust-analyzer. You'll have to figure out how to make cargo ignore it.

**Comment by doxxx** [comment]
I can't reproduce this with the latest version of rust-analyzer.
