### ISSUE TITLE
rename doesn't work for cfg modules

### ISSUE THREAD

**Issue by davemilter** [rust-analyzer/rust-analyzer#3537]
For code like this:

Module one:
```rust
fn myf() {}

#[cfg(test)]
mod tests;
```
Module two:
```rust
use super::*;

#[test]
fn test_myf() {
    myf();
}
```

rename functionality don't rename `myf`, if I ask renaming with cursor on `fn myf() {}`.
But all works fine if I inline module, like this:
```rust
fn myf() {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_myf() {
        myf();
    }
}
```

What is really strange. Because of for example I can "jump  to definition" from `myf();` in "Module two" to "Module one", so rust-analyzer know, that `myf` called from "Module two" is defined in "Module one", but can not rename it.

**Comment by Veykril** [comment]
I can't reproduce this issue anymore so I think this has been accidentally fixed at some point. If I'm wrong feel free to reopen this.
