### ISSUE TITLE
Can not complete after iter().find ?

### ISSUE THREAD

**Issue by davemilter** [rust-analyzer/rust-analyzer#3548]
With code below there are two problems,
but may be this is one problem?

```rust
struct Foo {
    i: i32,
}

fn main() {
    let x = vec![Foo {i: 1}, Foo {i: 2}];
    if let Some(found) = x.iter().find(|x| x.i == 1) {
        found.<CURSOR_HERE>
    }
}
```

rust-analyzer can not figure out that `found` has type `Foo` and so it can not suggest any field for `found` point expression.

It is also not find `find` method. So for `x.` it can find `iter()`, but for `x.iter().` it can not suggest `find` method.

But may be the main problem that it can not figure out that there is `Iterator::find` method, and that's why it can not understand that it returns `Option<&Foo>`?

**Comment by flodiebold** [comment]
Looks to me like another case of rust-lang/chalk#234, so let's close it in favor of #2603.
