### ISSUE TITLE
Option to completely suppress the "workplace loaded: 21 rust packages" info box.

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#3554]
When rust analyzer comes on it pushes a little notification that it's loaded with X many packages. I'm sure this is useful for development purposes, but it's not helpful to an end user, and it doesn't go away on its own after a few sections. You have to manually click the little X to make it go away.

So please make an option to stop that message from appearing.

**Comment by Lokathor** [comment]
Actually, also the "reloading the rust analyzer" notification should be optional. Or maybe put it into the "output" window but not as a notification.

**Comment by edwin0cheng** [comment]
In general we should use a progress bar. :)

#3283

**Comment by Lokathor** [comment]
I would still prefer no info popup boxes ever.

RLS just made a little icon in the info bar at the very bottom of the screen spin around while it was processing. that doesn't cover up parts of my terminal.

**Comment by Veetaha** [comment]
@Lokathor you might want to add the following to your `settings.json`
```json
{
    "rust-analyzer.featureFlags": {
        "notifications.workspace-loaded": false
    }
}
```

**Comment by matklad** [comment]
>I would still prefer no info popup boxes ever.

This is an explicit design decision that we, **by default**, use noisy UI with popus. This is helpful for the new users to learn about available features and troubleshoot problems. 

It is expected that non-novice users explicitly silence more annoying bits of the UI. So, workspace loaded notification is not going away by default. 

But we totally should switch it to https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workDoneProgress, closing in favor of #3283.

**Comment by Lokathor** [comment]
@matklad At no point was I ever suggesting that the default change. I think that I've been quite clear that I want an option, not a change to the default, but apparently I was not clear enough. I find  all the info and popups overwhelming and distracting, giving me a negative experience as a user. Simply switching it to a progress bar would not change that.

@Veetaha Very helpful, thank you. That does appear to fix my problem.

**Comment by matklad** [comment]
@Lokathor yeah, my comment was just to give more context here to elucidate the current design, it wasn't directed at arguing with you :)
