### ISSUE TITLE
Syntax parsing error

### ISSUE THREAD

**Issue by max-frai** [rust-analyzer/rust-analyzer#3560]
```
pub struct Preloader {
    pub browser: Browser,
}

impl Preloader {
    fn create_browser() -> Browser {
        Browser::new(..)
    }

    pub fn new() -> Self {
        browser: create_browser()
    }
}

```
Here is error:
<img width="316" alt="Screenshot 2020-03-11 at 19 21 32" src="https://user-images.githubusercontent.com/24208746/76445080-86d87680-63cd-11ea-8add-bc76ae934059.png">

**Comment by flodiebold** [comment]
That is actually a syntax error. Did you mean to write `Preloader { browser: create_browser() }`?

**Comment by max-frai** [comment]
Sorry, I should sleep more...
I tried to remove this issue, but it's not possible :)
