### ISSUE TITLE
Doc comment spuriously includes non-doc comments

### ISSUE THREAD

**Issue by DJMcNab** [rust-analyzer/rust-analyzer#357]
E.g. in
```rust
/// A documentation comment.
// Not a documentation comment
struct Something;
```
the docs for `Something` are currently given as `A documentation comment.\nNot a documentation comment` (This is rendered by `vscode` without a newline due to markdown rules).
We should really only give them as a `A documentation comment`.

## Mentoring instructions

The current syntax based approximation is defined in:
https://github.com/rust-analyzer/rust-analyzer/blob/1d6dcef5c584d0dffdf5386eec993e41daad0210/crates/ra_syntax/src/ast.rs#L73-L94.

This works by finding all comment nodes owned by the `DocCommentsOwner`, stripping their prefix (no matter what it is) and combining them with `/n`s. A first step is to improve `doc_comment_text` to only allow direct documentation comments (by checking `comment.flavor()` and checking that it is `CommentFlavor::Doc`).

However, we also need to check internal comments prefixed with `//!` (especially in `mod`ules). This requires working out where the `mod`s body is. This should be handled in `ra_analysis`. Ideally, there should be a desugaring of doc comments into `#[doc]` attributes in `ra_hir` (or `ra_analysis`), which should handle cases where `#[doc]` is used manually correctly.

**Comment by csmoe** [comment]
assign to me.

**Comment by DJMcNab** [comment]
It's worth noting that we don't properly handle internal doc comments (`//!`) yet.
