### ISSUE TITLE
rust-analyzer reports errors parsing that are accepted by rustc

### ISSUE THREAD

**Issue by samuela** [rust-analyzer/rust-analyzer#3571]
I have a file (https://github.com/samuela/rustybox/blob/master/procps/ps.rs) that rust-analyzer complains about. Specifically, it's not happy with the ellipsis type here: https://github.com/samuela/rustybox/blob/master/procps/ps.rs#L18:
![Screenshot from 2020-03-12 19-44-14](https://user-images.githubusercontent.com/226872/76584782-e9974400-6499-11ea-8cce-5a62301b942f.png)

However, the file is syntactically correct and the project compiles fine as of all recent rust versions including 
```
  nightly-x86_64-unknown-linux-gnu updated - rustc 1.43.0-nightly (c20d7eecb 2020-03-11) (from rustc 1.43.0-nightly (158127853 2020-03-10))
```

**Comment by matklad** [comment]
oh my, haven't realizes this is actually valid: https://github.com/rust-lang/reference/pull/781
