### ISSUE TITLE
Release action runs for forks

### ISSUE THREAD

**Issue by CAD97** [rust-analyzer/rust-analyzer#3589]
https://github.com/CAD97/rust-analyzer/releases/tag/nightly

It's probably better if the release workflows are only run for [`github.repository`](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context)`== "rust-analyzer/rust-analzyer"` by default, so forks aren't trying to do releases 😛

**Comment by edwin0cheng** [comment]
Agree, but it is nice to have a way to test github action in my owned fork. My solution is I just turned off my fork github actions in my fork repos Settings if I don't want it to run.

**Comment by matklad** [comment]
Yeah, I *think* GitHub actions should just not run by default for forks, as that seems to be a security issue. 

But, as they *do* run, I think we should work-around this by gating release on the repo name.

**Comment by bjorn3** [comment]
Why would it be a security issue? They should run in the context of the fork without access to the secrets of the original repo.

**Comment by matklad** [comment]
*But* they'll have access to fork's secrets. Ie, I might place evil in rust-analyzer, which would publish malicious github pages for forks. That is, it is a security issue for people who fork the repository, not for the upstream.

**Comment by bjorn3** [comment]
I didn't think about that. I was thinking about an security issue for upstream.
