### ISSUE TITLE
Making changes outside editor doesn't invalidate cached state

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#3594]
It seems that VS Code does not update errors etc showing in the editor if I change files outside the editor (for me, usually using the git CLI from some terminal). The compilation state only seems to be updated after reloading the window. (This is with last week's release, and have been seeing it for the past few weeks. It does seem like a regression.)

**Comment by kiljacken** [comment]
At some point we used OS file watching on most platforms, but due to issues on some platforms, client side watching was enabled by default instead. You can try to disable "useClientWatching" in your VSCode settings for rust-analzyer. It works decently on linux, not sure about macos, and quite some issues on windows if I recall.

**Comment by djc** [comment]
I'm surprised that this use case isn't considered an issue, then.

**Comment by kiljacken** [comment]
It is still considered an issue to solve, but gated behind a long needed VFS resign which is sadly just low priority enough that no one has gotten around to it

**Comment by edwin0cheng** [comment]
Yeah, we would like to change vfs to use fb watchman instead, see #1968

**Comment by matklad** [comment]
@kiljacken note that we *do* register file-system watchers with the client: https://github.com/rust-analyzer/rust-analyzer/blob/6616f336b28bcab7d693473c6d9263dff15639ae/crates/rust-analyzer/src/main_loop.rs#L148-L161

So, even if a file is modifed outside of vscode, we still should catch it here: https://github.com/rust-analyzer/rust-analyzer/blob/6616f336b28bcab7d693473c6d9263dff15639ae/crates/rust-analyzer/src/main_loop.rs#L631-L642

**Comment by lnicola** [comment]
Could it be a display problem? I think we had some issues that are fixed in the new implementation.

Do the stale diagnostics show up in the Problems pane?

**Comment by djc** [comment]
I'll check the Problems pane next time this happens.

**Comment by kiljacken** [comment]
Also note that re-running `cargo check` is only triggered on save in the editor right now, that might be the main issue.

**Comment by matklad** [comment]
This is probably fixed with new vfs and auto-relaod
