### ISSUE TITLE
How can a user run more than one cargo watch command?

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#3596]
In `cargo watch` you can use -x for each thing you want it to do, so you could write

```
cargo watch -x build -x clippy
```

And you'd get a build _and_ a clippy run. However, I'm not seeing how to do this in RA.

**Comment by kiljacken** [comment]
This is not currently supported, and I'm uncertain whether we want to support it given the amount of trouble running a single command from the server already causes :)

**Comment by Lokathor** [comment]
Okay then can you add a way to run specifically clippy as well as another command?

**Comment by matklad** [comment]
Note also that long-term, we will remove cargo check execution from rust-analyzer completely, and instead just compute all the diagnostics on the fly, internally. So the long term answer here is that a user needs `cargo watch` external process anyway.

**Comment by Lokathor** [comment]
Well rust-analyzer should have some way of running clippy directly in that case.

**Comment by matklad** [comment]
See 

https://github.com/rust-analyzer/rust-analyzer/issues/5383#issuecomment-658652119

**Comment by Lokathor** [comment]
Wait you gotta document that somewhere in the readme or something.

Just putting a comment at the end of a closed issue is not helping the users.

**Comment by matklad** [comment]
Yeah, I might not forget about this next time I get to updating the manual. But this is mostly build-in vscode feature, so I don’t think we necessary **must** document it ourselves.

**Comment by Lokathor** [comment]
I read the comment though, and I don't even know what it actually means. Like where do I even put that json block? It's completely unclear.

I think that maybe you're *too good* at using VS Code, and you've forgotten that most of us actually have no idea how anything with it works ;P

**Comment by Michael-F-Bryan** [comment]
> Like where do I even put that json block? It's completely unclear.

I [googled *"vs code task"*](https://www.google.com/search?client=firefox-b-d&q=vs+code+task) (keywords mentioned in the original comment) and the first result was [*Integrate with External Tools via Tasks*](https://code.visualstudio.com/docs/editor/tasks) from the official VS Code docs telling me all about how tasks work.

The problem you're always going to have is that rust-analyzer has a lot of features, so even if the relevant information *was* in the manual it'd be hard to discover because not everyone reads to the end. Plus the line is quite blurry between VS Code and the rust-analyzer plugin, so it's hard to know which project is responsible for documenting a particular feature.

**Comment by matklad** [comment]
Yeah, my long-term strategy is to crowd-source documentation for all editors. Doesn't work as good as I would like so far, I've bumped the link to the source:

![image](https://user-images.githubusercontent.com/1711539/87673999-af0a2480-c775-11ea-9f76-c5d48897e6b2.png)

**Comment by lnicola** [comment]
You can also set `cargo clippy` as the `check` command and run `cargo watch` in a terminal. There used to be some problems with warnings reported only once, but I think they work fine now.

**Comment by Lokathor** [comment]
The problem is that I want `cargo build` as my "check" command, and then I can't have clippy for free.

**Comment by lnicola** [comment]
> The problem is that I want `cargo build` as my "check" command

Why? `cargo clippy` will report the same warnings, and you can build the code in the background with `cargo watch`.

**Comment by Lokathor** [comment]
Well however it happens I don't super care I suppose. The point is that in the GUI for the rust-analyzer settings that you get in VS Code you can only input one command to have rust-analyzer's cargo watch do on repeat, and I want more than one command.

Exactly what those "more than one command" actions are seems unimportant, because various users will have their own needs.

Which is why we need this documentation about how to setup an additional automatic `cargo watch`, as provided by the PR that referenced this topic (#5407).
