### ISSUE TITLE
Fix underlining paramter while typing in vim

### ISSUE THREAD

**Issue by phynalle** [rust-analyzer/rust-analyzer#3615]
First, Thanks for creating this great project! 
I'm enjoying to code with rust-analyzer. It is really improved since I've known it. I love It so much. 

In neovim, the first paramter was still underlined while the second is written.
![image](https://user-images.githubusercontent.com/6007810/76793601-a37b1100-6808-11ea-8cd4-47c2494f4ee6.png)

However, A trick seems to underline proper parameter, but I don't like this style.
![image](https://user-images.githubusercontent.com/6007810/76793630-b2fa5a00-6808-11ea-84cf-ea127d780d67.png)

I'm using neovim-0.4.3 with coc plugin + coc-rust-analyzer. And I downloaded the latest release of rust-analyzer (2020-03-16).

In vscode, It works as it is.
![image](https://user-images.githubusercontent.com/6007810/76793659-c4436680-6808-11ea-9755-fb1cb7ae8a7c.png)

**Comment by fannheyward** [comment]
`coc-rust-analyzer` author here, I've reproduced this issue with RA. From server trace log, RA always returns signatureHelp `activeParameter` as 0, coc will underline the first parameter.

**Comment by fannheyward** [comment]
After some tests, I found the different between VSCode and coc.nvim:

In VSCode, params of `textDocument/signatureHelp` request are:

```
{
    "textDocument": {
        "uri": "file:///Users/fannheyward/src/hello-rust/src/main.rs"
    },
    "position": {
        "line": 42,
        "character": 8
    },
    "context": {
        "isRetrigger": false,
        "triggerCharacter": "(",
        "triggerKind": 2
    }
```

In coc, `context` is missing from params. From LSP spec, `SignatureHelpContext` was added in 3.15:

> Additional information about the context in which a signature help request was triggered.

My question is: does `context` is must have for RA to do signatureHelp?

**Comment by matklad** [comment]
@fannheyward  no, we use only TextDocumentPositionParams subset: https://github.com/rust-analyzer/rust-analyzer/blob/57562284abb226b80db463b9ed76deb59057b168/crates/rust-analyzer/src/main_loop/handlers.rs#L468

**Comment by fannheyward** [comment]
@phynalle try to fix this issue on `coc-rust-analyzer`, use `:CocUpdate` to upgrade the extension. Feedback is welcome.

**Comment by phynalle** [comment]
Thanks for trying to fix it, @fannheyward.
It seems that wrong underlining is fixed, but hint window is gone while typing..

Let me show you an example.
When opening parenthesis, it shows up. It's normal.
![image](https://user-images.githubusercontent.com/6007810/76893665-14d1c700-68d0-11ea-8a7f-2aebdee88b7c.png)

But, when parameter is written, it is gone.
![image](https://user-images.githubusercontent.com/6007810/76893724-32069580-68d0-11ea-820f-194d82c017ff.png)

And it shows up again when new parameter is ready to be put
![image](https://user-images.githubusercontent.com/6007810/76893783-48145600-68d0-11ea-8583-fae1ca4162a0.png)

And it is gone again when I try to write something.
![image](https://user-images.githubusercontent.com/6007810/76893828-595d6280-68d0-11ea-833e-340726d2564a.png)

**Comment by fannheyward** [comment]
@phynalle  Fixed in `coc-rust-analyzer` 0.4.11, try `:CocUpdate` and feedback any problem.

**Comment by phynalle** [comment]
wow, I think it's perfect. I don't see any problems. Thanks for your help.

**Comment by fannheyward** [comment]
This issue can be closed. @phynalle @matklad

**Comment by matklad** [comment]
Thanks @fannheyward for looking into this!

**Comment by matklad** [comment]
Hm, actually I wonder if there's off by one error on rust-analyzer side:

![image](https://user-images.githubusercontent.com/1711539/77041666-99007900-69ba-11ea-829a-48f1807e9ea7.png)

![image](https://user-images.githubusercontent.com/1711539/77041696-ac134900-69ba-11ea-82a7-6513ce0065e9.png)

From the screenshots above, it seems like it!

cc @kjeremy would you be interested in looking into this?

**Comment by kjeremy** [comment]
Sure! I still have to go to work sadly but maybe I can get to it this weekend.

**Comment by fannheyward** [comment]
https://github.com/fannheyward/coc-rust-analyzer/issues/321 has revert the fix for this issue.

VSCode will trigger `signatureHelp` after every character input, for example, `func(42,1`, VSCode will send `textDocument/signatureHelp` request after `(` `4` `2` `,` `1`, although RA has declared `triggerCharacters: ["(", ","]` only, RA will return correct activeParameter after `1` .

 coc only trigger when triggerCharacters input, here are `(` `,`.

**Comment by fannheyward** [comment]
This _properly_ is an issue of RA.

Test code with VSCode + RA: 

```rust
fn run(x: u32, y: u32) {
    println!("{}", x + y);
}

fn main() {
}
```

<img width="272" alt="" src="https://user-images.githubusercontent.com/345274/87491603-2909b300-c67b-11ea-92ec-16c113c4fe7d.png">

After input `,`, RA doesn't return correct activeParameter, should be 1.

Request:

```
Sending request 'textDocument/signatureHelp - (166)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/fannheyward/src/hello-rust/src/main.rs"
    },
    "position": {
        "line": 5,
        "character": 10
    },
    "context": {
        "isRetrigger": true,
        "triggerCharacter": ",",
        "triggerKind": 2,
        "activeSignatureHelp": {
            "signatures": [
                {
                    "label": "fn run(x: u32, y: u32)",
                    "parameters": [
                        {
                            "label": "x: u32"
                        },
                        {
                            "label": "y: u32"
                        }
                    ]
                }
            ],
            "activeSignature": 0,
            "activeParameter": 0
        }
    }
}
```

Response:

```
Received response 'textDocument/signatureHelp - (166)' in 3ms.
Result: {
    "activeParameter": 0,
    "activeSignature": 0,
    "signatures": [
        {
            "label": "fn run(x: u32, y: u32)",
            "parameters": [
                {
                    "label": "x: u32"
                },
                {
                    "label": "y: u32"
                }
            ]
        }
    ]
}
```

**Comment by fannheyward** [comment]
Tested with RA fac1b0d, it's fixed!
