### ISSUE TITLE
Unable to open links from help dialogs

### ISSUE THREAD

**Issue by mmahandev** [rust-analyzer/rust-analyzer#3619]
When clicking on links I get this error:

![image](https://user-images.githubusercontent.com/20646367/76805131-05f1f400-67ac-11ea-821e-b96d34a55d03.png)

In the above screenshot I clicked the "format!" link.

**Comment by kjeremy** [comment]
Closing as duplicate of #503.

I think we have two options: we either need to register our own provider for this on the client side for vscode or massage the markdown links before returning from the server.
