### ISSUE TITLE
Partial completions observed in tokio , async-std crates

### ISSUE THREAD

**Issue by prasannakog** [rust-analyzer/rust-analyzer#3621]
This issue is after I observed several instances. RA's provides partial completions . I treid with the following combinations VScode / Emacs with RLS and RA. The issue is , on the below code snippet, the intent is to import TcpStream where as I get only
```
use tokio::net::ToSocketAddrs
```

OTTH, the below code I was expecting completions like read,write etc but got nothing. 

```
 let mut stream = TcpStream::connect("127.0.0.1:6142").unwrap();
stream.<no_completions>
```
Am I missing something here

**Comment by flodiebold** [comment]
Importing `TcpStream` works for me as soon as I enable the `tcp` feature in tokio, which doesn't seem to be enabled by default.

`TcpStream::connect("127.0.0.1:6142").unwrap()` seems wrong; `connect` is an async function, so you'd have to `await` it. If you await it, we still don't infer the type though; I think there we run into #2603 again.

**Comment by lnicola** [comment]
Importing `TcpStream` works:

![image](https://user-images.githubusercontent.com/308347/105535079-1097e680-5cf7-11eb-983d-e4ad5dd1cdbb.png)

And so does the type inference for `TcpStream::connect`:

![image](https://user-images.githubusercontent.com/308347/105535271-5b196300-5cf7-11eb-978c-3fc9d4389c8a.png)
