### ISSUE TITLE
`cargo watch` integration no longer works for workspaces

### ISSUE THREAD

**Issue by mikeyhew** [rust-analyzer/rust-analyzer#3631]
VS Code version: 1.43.0
rust-analyzer version: 0.1.20200316

I just upgraded to the latest version of rust-analyzer, and I'm not getting any error messages or warnings from `cargo watch` in the top-level directory of my workspace anymore. Note that `cargo check` from the top-level directory works fine. I do get error messages if I run vscode from one of the crates inside the workspace.

Here is a git repo I put together demonstrating it not working: https://github.com/mikeyhew/rust-analyzer-broken-cargo-watch

to reproduce:

```
git clone https://github.com/mikeyhew/rust-analyzer-broken-cargo-watch
cd rust-analyzer-broken-cargo-watch
cargo check
```

Notice how `cargo check` outputs an error message, in this case an ICE.

Now open the workspace in VS Code:

```
code .
```

and open the file `yolo/src/main.rs`, and save the file. You should be getting the same error message, but nothing happens.

If you don't like how `break rust` causes an ICE, you can change it to something else, e.g. `does_not_exist()`. It still won't output any error messages.

**Comment by Veetaha** [comment]
Thanks for the repro! I think I know what's the problem.
Here we already have a hardcoded `--workspace` flag:
https://github.com/rust-analyzer/rust-analyzer/blob/2a3543d1953daeb240c214ececd273f1040b0516/crates/ra_cargo_watch/src/lib.rs#L307-L318

But we also specified it in `settings.json` as per the repro:
```json
{
   "rust-analyzer.cargo-watch.arguments": [
     "--workspace"
   ],
   "rust-analyzer.cargo-watch.enable": true
}
```

So at the end of the day, it gets duplicated when passed to `cargo check` and it returns an error:
```
~/junk/rust-analyzer-broken-cargo-watch (master) $ cargo check --workspace --message-format=json --manifest-path /home/veetaha/junk/rust-analyzer-broken-cargo-watch/Catgo.toml --all-targets --workspace
error: The argument '--workspace' was provided more than once, but cannot be used multiple times

USAGE:
    cargo check --all-targets --manifest-path <PATH> --message-format <FMT>... --workspace

For more information try --help
```
So we need to find where we ignore this error and report it instead. Besides that, we might want to deduplicate the `--workspace` flag if it is already passed by the user.

**Comment by mikeyhew** [comment]
Oh great, if I remove the `--workspace` argument, then it works. Thanks!

If the error message had been logged, it certainly would have helped, so I'm glad to see that works has started on that. If this change was documented in the release notes, that would have been helpful too. Do you know when the `--workspace` flag was added?

**Comment by matklad** [comment]
It's documented at the last bullet point in fixes: https://rust-analyzer.github.io/thisweek/2020/03/16/changelog-16.html#fixes

**Comment by mikeyhew** [comment]
Ah I see, thanks! This issue can be closed then, unless you want to keep it open until #3632 is merged.
