### ISSUE TITLE
Macro expansion loops

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3642]
This code give 100% CPU usage:

![image](https://user-images.githubusercontent.com/1711539/76999520-067abe00-6957-11ea-9ab7-30af6f92cf9c.png)

cc @flodiebold, @edwin0cheng, this is quite likely related to #3593

**Comment by edwin0cheng** [comment]
I am investigating this issue now, It seem to be dead on code path of `diagnostic` in an infinite recursive call node resolution.
