### ISSUE TITLE
Notification of nightly version is annoying

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#3653]
The following every time I fire up vscode means I have to click it away every time.

![image](https://user-images.githubusercontent.com/4325700/77073393-98b9ab00-69c5-11ea-930f-c1a7e493037d.png)

It's a source install and I know what I'm doing :)

**Comment by matklad** [comment]
workaround: add `update.channel: "stable"` to settings. But yeah, we should somehow make it better for a from-source install

**Comment by Veetaha** [comment]
Why not just turning of update channels off as we did previously @matklad
https://github.com/rust-analyzer/rust-analyzer/blob/5a0041c5aaeee49be84ce771fb0360ae55cbd8b2/editors/code/src/installation/extension.ts#L18-L19

**Comment by Veetaha** [comment]
@matklad , I'd propose to revert #3663 and add this single

**Comment by matklad** [comment]
The primary goal of #3663 is to make life easier for *users* who install rust-analyzer from source. I think that's the optimal solution
