### ISSUE TITLE
npm warning about installing peer dependencies

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#3657]
I am seeing the following with `cargo xtask install`

> 
> > cmd.exe /c npm --version
> 6.13.7
> > cmd.exe /c npm install
> npm WARN @rollup/plugin-commonjs@11.0.2 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
> npm WARN @rollup/plugin-node-resolve@7.1.1 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
> npm WARN @rollup/pluginutils@3.0.8 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> updated 1 package and audited 422 packages in 2.489s
> 
> 12 packages are looking for funding
>   run `npm fund` for details

**Comment by Veetaha** [comment]
We updated rollup to the new major version in #3637
But its plugins still require the previos major version. We either need to downgrade `rollup` or upgrade the plugins if possible.

**Comment by matklad** [comment]
There's issue on rollup repo saying that its ok, and that the plugins would
be updated next week.
