### ISSUE TITLE
Disable rust-analyzer for a single file.

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-analyzer/rust-analyzer#3660]
Hello, I've started trying out rust analyzer and minor annoyance is that I can't disable RLS on a per file basis. Tokei's codebase actually uses [Rust mixed with handlebars](https://github.com/XAMPPRocky/tokei/blob/2e12cf6faae66eff5187464e5ef140f5e8c19d9b/src/language/language_type.hbs.rs#L25-L36) for code generation, so RLS will never be able to correctly handle this file and I have a lot of errors whenever I'm editing.

It would be nice if I could set a modeline or similar comment or attribute inside the file itself to disable RLS for just that file.

### Proposed Solution
```rust
// rust-analyzer: disable
```

**Comment by Veetaha** [comment]
What about the following setting?

https://github.com/rust-analyzer/rust-analyzer/blob/1ba03c6995015b3143a417ed07437f0c9028a97d/editors/code/package.json#L248

**Comment by XAMPPRocky** [comment]
@Veetaha Thank you, this seems to only configure it for my editor, but I'd like to check in this change in the repository so that it's the same for anyone opening that file, or if I open it from a different machine with a different configuration it is still disabled.

**Comment by lnicola** [comment]
You can check in a Code configuration snippet under `.vscode`. Of course, it won't work for developers who use a different editor.

**Comment by XAMPPRocky** [comment]
Yes, sorry, I should have mentioned I'm using Vim with `coc.nvim`. 😅

**Comment by Veetaha** [comment]
So, should we consider this issue resolved?

**Comment by XAMPPRocky** [comment]
@Veetaha Well not unless this is a wontfix, ideally there would be a way to disable (or configure) that is editor agnostic.

**Comment by Veetaha** [comment]
This do **is** editor agnostic, [coc nvim does provide a way to pass this parameter](https://github.com/fannheyward/coc-rust-analyzer#configurations)

**Comment by lnicola** [comment]
Editor-agnostic configuration is tracked in #6113, let's close this.
