### ISSUE TITLE
Does not analyze main/tests/benches

### ISSUE THREAD

**Issue by dennybritz** [rust-analyzer/rust-analyzer#3667]
I have a library crate, and everything is working fine in my `lib.rs` and in the modules imported there. 

However, I don't get any type hints for my own library (external crates still work) in  `main.rs` `tests/*` or `benches/*`. Hovering over a type shows `{unknown}` or `!`. I'm importing my library with `use my_lib;`. I don't see any errors in the server trace, though I'm not sure if I'm looking at the right logs. I'm using vscode.

My project is a pretty standard setup, nothing special in the `Cargo.toml` file. Is there anything I need to do to get type hints for my own library?

**Comment by Veetaha** [comment]
What if you import your lib with a glob?
```
use my_lib::*;
```

**Comment by dennybritz** [comment]
That doesn't help unfortunately.

**Comment by lnicola** [comment]
This might happen if you add the tests while rust-analyzer is running, but I assume you've restarted it by now. Can you prepare a repository that exhibits this issue?

**Comment by dennybritz** [comment]
Yeah, it has never worked for me (have been using it for 7 days) and I've restarted everything multiple times. I will try to prepare a repo.

**Comment by dennybritz** [comment]
Here's a repo: https://github.com/dennybritz/rust-analyzer-issue3667

Created with `cargo new` and has nothing in it except for a `lib.rs` and `main.rs`. rust-analyzer works fine in `lib.rs` giving me autocompletes and types for standard libraries and my own crate, but it does not work in `main.rs`.

**Comment by Veetaha** [comment]
Hmm, indeed, this is very suspicious... I guess this is due to the renaming. If I comment out it in `Cargo.toml` it works fine (but you need to use the project dir name as the mod name):
```toml
[lib]
# name = "mylib"
path = "src/lib.rs"
```
@matklad, @kiljacken isn't this supported?

**Comment by Veetaha** [comment]
UPD: you don't event need to comment out the thing it `Cargo.toml`, just using the original project dir name as a mod name still gives hints.

**Comment by dennybritz** [comment]
Oh, that's good to know, thanks for looking into it! I've always renamed my libs because they usually had long names with dashes, didn't even think about that. 

I guess this is a missing feature or a bug?

**Comment by edwin0cheng** [comment]
Yeah, It is a bug indeed :

https://github.com/rust-analyzer/rust-analyzer/blob/50c6a315ab2bef493b618742989744fb370a32ca/crates/ra_project_model/src/lib.rs#L374

We should use target name instead of package name for that.

I will submit a PR later.

**Comment by edwin0cheng** [comment]
Thanks @dennybritz for the reporting and the minimal repro.
