### ISSUE TITLE
Assist idea: unwrap to if let (or match?)

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#3669]

**Comment by matklad** [comment]
yep, we should have it. I think we should default to `match`, and have a separate assist to convert match to if-let. 

replace if let with match is a good place to start looking into how this might be implemented: 

https://github.com/rust-analyzer/rust-analyzer/blob/c7a2052e7302a5ff6c05aa2589ef3ff51a9e7c95/crates/ra_assists/src/handlers/replace_if_let_with_match.rs

**Comment by lnicola** [comment]
Do we still want to keep this open?

**Comment by SamB** [comment]
This has regressed due to PR https://github.com/rust-lang/rust-analyzer/pull/3732 :-(
