### ISSUE TITLE
`cargo test cli::generated_assists` fails when assist file open

### ISSUE THREAD

**Issue by JoshMcguigan** [rust-analyzer/rust-analyzer#3670]
This is a meta-issue related to development of assists. 

Running `cargo test cli::generated_assists` fails when any assist files are open. The cause of this issue is that my editor (vim) creates a temp file in the assists directory, which is picked up [here](https://github.com/rust-analyzer/rust-analyzer/blob/master/xtask/src/codegen/gen_assists_docs.rs#L49) and then fails to read as UTF-8 [here](https://github.com/rust-analyzer/rust-analyzer/blob/master/xtask/src/codegen/gen_assists_docs.rs#L60).

Potential fixes:

* Ignore gitignore'd files
  * This seems to be the most appropriate solution, but potentially would involve adding a dependency?
* Ignore files starting with `.`
  * This solves the problem for vim, but I'm not sure about other editors
* Provide a more descriptive error message including the file path that failed to be read as UTF-8
  * This doesn't solve the problem, but would likely provide enough information to allow the user to figure out how to move forward (likely just close the file in their editor)
* Any other options? 

I'd be happy to implement a fix, but I just wanted to discuss the options before making a PR with a particular solution.

**Comment by matklad** [comment]
We should ignore everything with . in front. We already have `is_hidden` function for it somewhere
