### ISSUE TITLE
Auto-import adds multiple types with the same name

### ISSUE THREAD

**Issue by Aloso** [rust-analyzer/rust-analyzer#3676]
The following error is shown when an item such as `HashMap` isn't imported:

> cannot find type `HashMap` in this scope
> not found in this scope rustc(E0412)

It can be imported automatically with a quick fix:

> possible candidates are found in other modules, you can import them into scope

When I click on it, all of them are imported at once, e.g.

```rust
use crate::dummy::HashMap;

use nom::lib::std::collections::HashMap;

use nom::lib::std::collections::hash_map::HashMap;

use std::collections::HashMap;

use std::collections::hash_map::HashMap;
```

It would be better to show a dialog, so we can choose which one we want.

Also, in this case all paths except the first one lead to the same type (nom re-exports `std::collections` for whatever reason). Maybe there's a way to detect this and deduplicate them? Rust-analyzer could just pick the shortest path, so the only suggestions would be `crate::dummy::HashMap` and `std::collections::HashMap`.

**Comment by flodiebold** [comment]
This is not our autoimport, but a suggestion from rustc. It's weird that we apply all of them though. Also, maybe we should just suppress this fix since our autoimport works better :thinking:

**Comment by kiljacken** [comment]
Slightly related to #3633 in that it's because we're applying a suggestion that's not marked machine applicable by rustc. I'll try to squeeze a fix in tomorrow.

**Comment by Aloso** [comment]
> This is not our autoimport, but a suggestion from rustc. It's weird that we apply all of them though. Also, maybe we should just suppress this fix since our autoimport works better 🤔

I kind of missed that, since the light bulb appears only when clicking on the identifier, but the quick fix is shown on hover.

**Comment by lnicola** [comment]
Update: #7508 effectively reverted #3681, but it looks like the suggestions got better here:

```
error[E0433]: failed to resolve: use of undeclared type `HashMap`
 --> src/main.rs:2:15
  |
2 |     let foo = HashMap::new();
  |               ^^^^^^^ not found in this scope
  |
help: consider importing this struct
  |
1 | use std::collections::HashMap;
  |
```

And we also have our own diagnostic for it.
