### ISSUE TITLE
Document ra_syntax::ast API

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#3682]
I wish we had some docs on ast node types, at least an example source code that shows to which kind of symbols the node referes to.
E.g. the difference between `Name` and `NameRef` is not very evident, does `ParenType` pertain to unnamed tuples or tuple structs too and all these kinds of questions arise...

I suppose the ast api is quite stable already so we might want to better document it.
See the reference from [matlkad](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/hover/near/191405667)

**Comment by matklad** [comment]
As the ast is generated, the docs should actually go to https://github.com/rust-analyzer/rust-analyzer/blob/master/xtask/src/ast_src.rs
