### ISSUE TITLE
Editor: Add a option to set Github token to avoid API rate limit

### ISSUE THREAD

**Issue by spacemeowx2** [rust-analyzer/rust-analyzer#3688]
In corporate networks, everyone shares an IP address. Therefore Github often limits unauthenticated API requests.

Request URL:

https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/2020-03-16

Response:

```
{
    message: "API rate limit exceeded for *.*.*.*. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    documentation_url: "https://developer.github.com/v3/#rate-limiting"
}
```

https://github.com/rust-analyzer/rust-analyzer/blob/92b561b5c7da8303473792ba2bacb430614da2d1/editors/code/src/net.ts#L24

**Comment by matklad** [comment]
Is there perhaps some well-known env var which we can use here instead of providing an explicit option?

**Comment by lnicola** [comment]
[hub](https://github.com/github/hub) uses `GITHUB_TOKEN`, but I'm not sure it's the same kind of token.

**Comment by Veetaha** [comment]
There is ``~/.git-credentials`` file which we can make use of :D.

Also, it doesn't look like [`vscode-cpptools` deals with this problem at all](https://github.com/microsoft/vscode-cpptools/blob/5986aee6da20134080fa27347912cb391732cc60/Extension/src/githubAPI.ts#L260-L265) and they check for updates [every hour](https://github.com/microsoft/vscode-cpptools/blob/5986aee6da20134080fa27347912cb391732cc60/Extension/src/LanguageServer/extension.ts#L48) too.

**Comment by spacemeowx2** [comment]
I prefer `GITHUB_TOKEN`. And I think Github has only one kind of [token](https://github.com/settings/tokens).

**Comment by Matthias247** [comment]
Has anyone further looked into this? I'm unfortunately running into the same issue:

```
ERROR [9/19/2020, 12:44:14 AM]: Error fetching artifact release info {
  requestUrl: 'https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/2020-09-14',
  releaseTag: '2020-09-14',
  response: {
    headers: Headers {
      [Symbol(map)]: [Object: null prototype] {
        date: [ 'Sat, 19 Sep 2020 00:44:14 GMT' ],
        server: [ 'Varnish' ],
        'strict-transport-security': [ 'max-age=31536000; includeSubdomains; preload' ],
        'x-content-type-options': [ 'nosniff' ],
        'x-frame-options': [ 'deny' ],
        'x-xss-protection': [ '1; mode=block' ],
        'content-security-policy': [ "default-src 'none'; style-src 'unsafe-inline'" ],
        'access-control-allow-origin': [ '*' ],
        'access-control-expose-headers': [
          'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset'
        ],
        'content-type': [ 'application/json; charset=utf-8' ],
        'referrer-policy': [ 'origin-when-cross-origin, strict-origin-when-cross-origin' ],
        'x-github-media-type': [ 'github.v3; format=json' ],
        'x-ratelimit-limit': [ '60' ],
        'x-ratelimit-remaining': [ '0' ],
        'x-ratelimit-reset': [ '1600477384' ],
        'x-ratelimit-used': [ '60' ],
        'content-length': [ '249' ],
        connection: [ 'close' ],
        'x-github-request-id': [ '7137:1A04:56C6BA:6F476F:5F65545E' ]
      }
    },
    status: 403,
    body: `{"message":"API rate limit exceeded for 205.251.233.51. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}\n`
  }
}
```

**Comment by matklad** [comment]
No, I don't think anyone tried to fix this. But I think it wold be ok to either:

* look for hard-coded `GITHUB_TOKEN` env var
* add an explicit settings for this

**Comment by Matthias247** [comment]
Ok. I will try to give it a shot. Any hints on how to best test this? I don't want to wait a week for the next release 😀
Is there any way to trigger the re-download?

I am slightly leaning towards the explicit settings for the following reasons:
- if one uses the plugin with remote (SSH) development, then they would need to make sure the env var is on all target machines
- vscode can be launched through a variety of ways.  If you launch it non from a shell you might not have the env var

**Comment by lnicola** [comment]
> Is there any way to trigger the re-download?

I think we check (more often?) for updates if the nightly channel is enabled.

> I  am slightly leaning towards the explicit settings

I would prefer to not have this as a preference. A lot of people sync their Code settings either with a dotfiles repository or with the newly-introduced sync feature of Code, and this would mean exposing the GitHub token to other people.

Instead, I'd rather we prompted the user for the token and stored it in `ExtensionContext.globalState`.

**Comment by Matthias247** [comment]
> I would prefer to not have this as a preference. A lot of people sync their Code settings either with a dotfiles repository or with the newly-introduced sync feature of Code, and this would mean exposing the GitHub token to other people.

That's indeed a valid concern

> Instead, I'd rather we prompted the user for the token and stored it in ExtensionContext.globalState.

We need to be careful with hidden settings, because it might lead to surprises if e.g. the token is no longer valid. Then the users might not be able to find where it was originally set, and how to update it.

I guess ideally if a download fails there might be a popup asking the user to enter or update the token. But I guess at least in the first revision it would be something simpler. Maybe an explicit command which allows to enter the token. And making sure the error message when a download fails mentions it and refers to the way of updating it.

**Comment by Matthias247** [comment]
> Instead, I'd rather we prompted the user for the token and stored it in ExtensionContext.globalState.

One more thought on this: I'm not sure how this would work in the remote-extension setup. I guess that state might not be shared between local and remote instance. If one could still set it per instance it might still work. If only the local state is editable then however it wouldn't work.

**Comment by lnicola** [comment]
> I'm not sure how this would work in the remote-extension setup

I think `rust-analyzer` runs remotely -- the local installation doesn't matter, and you can even skip installing it.
