### ISSUE TITLE
Unfortunately we don't ship binaries for your platform yet. 

### ISSUE THREAD

**Issue by tmttknmpfpm** [rust-analyzer/rust-analyzer#3701]
Unfortunately we don't ship binaries for your platform yet. You need to manually clone rust-analyzer repository and run `cargo xtask install --server` to build the language server from sources. If you feel that your platform should be supported, please create an issue about that [here](https://github.com/rust-analyzer/rust-analyzer/issues) and we will consider it.

platform win10

**Comment by lnicola** [comment]
Can you choose "Open Developer Tools" from the Help menu, type `require('os').platform()` and `require('os').arch()` in the console and paste here the output?

**Comment by Veetaha** [comment]
Not sure we should support win10 guys :D

**Comment by lnicola** [comment]
I'm pretty sure it works on Windows 10/x86.

**Comment by vsrs** [comment]
Had the same issue on Windows 10. Fixed by changing my settings.json from
`rust-analyzer.raLspServerPath:"..."`
to
`rust-analyzer.serverPath:"..."`

note the new name.

**Comment by ADyson** [comment]
Im getting this issue also , `require('os').platform() = win32` `require('os').arch() = ia32`.

**Comment by lnicola** [comment]
Ooh, so you're a 32-bit Node. Apparently we should be looking at `process.arch` instead of `os.arch()`, but I can't make that work in Developer Tools (@Veetaha any idea?). I'm also confused regarding `x32` vs. `ia32`.

**Comment by matklad** [comment]
> I'm also confused regarding x32 vs. ia32.

Yeah, I bet this is it. Both os.arch and process.arch return the same thing, and that's why we download x86_64 binaries on x86 node. I guess `ia32` is the right thing to use, and not `x32`. But what is x32 I wonder? the docs are pretty scarce...

**Comment by lnicola** [comment]
`x32` might be [32-bit userspace on a 64-bit kernel](https://en.wikipedia.org/wiki/X32_ABI).

> The return value is equivalent to `process.arch`.

Oh, okay.

Maybe the reporter is really using a 32-bit OS?

**Comment by ADyson** [comment]
I'm on windows 10 x64, ill install the 64-bit vscode, thanks.

**Comment by codermantx** [comment]
I too had this issue, installing 64-bit VsCode worked.

**Comment by lnicola** [comment]
We're now downloading 64-bit `rust-analyzer` on 32-bit Node because I don't think we can easily detect 32-bit Node on a 64-bit OS and using Rust on a 32-bit Windows system seems unlikely.

**Comment by DanteMarshal** [comment]
I was having this same issue, while my `process.arch` was `x64`.
Reinstalling the extension fixed it
