### ISSUE TITLE
Upgraded to 0.2.100, now it doesn't activate

### ISSUE THREAD

**Issue by schungx** [rust-analyzer/rust-analyzer#3702]
Win 10.  Vscode.

Upgraded plugin to 0.2.100 (from 0.1.2020xxxxx).

Now the plugin doesn't seem to activate.  Open a Rust file and the language server doesn't load.

Should I roll back to a previous version?

**Comment by matklad** [comment]
Hm, this obviously isn't intended :)

Rolling back to the previous version should work, but if you can take a look at the client or server logs, that would be helpful!

**Comment by schungx** [comment]
> if you can take a look at the client or server logs, that would be helpful!

OK....  how do I do that?

**Comment by schungx** [comment]
The thing about 0.2.100 is... after installation, it does not even prompt me to download the language server.  When I roll back to the previous version, it does so.

**Comment by Veetaha** [comment]
> OK.... how do I do that?
`VSCode > Help > Toggle Developer Tools > Console`

**Comment by matklad** [comment]
Good question, added some troubleshooting instructions at

https://github.com/rust-analyzer/rust-analyzer/blob/628dc9ff5abcb0e286531d86e8b0054d6c88f201/docs/user/readme.adoc#troubleshooting

**Comment by schungx** [comment]
```
workbench.desktop.main.js:sourcemap:3574
Activating extension 'matklad.rust-analyzer' failed:
Failed to execute c:\Users\schun\AppData\Roaming\Code\User\globalStorage\matklad.rust-analyzer\rust-analyzer-windows.exe --version.
```

**Comment by schungx** [comment]
OK, deleting `rust-analyzer-windows.exe` now causes VScode to prompt to download the language server.  So it is due to left-overs from a previous failed download.

Shouldn't there be checks performed to check the integrity of the language server runtime?

And why does it always prompt to download for 0.1.20xxxx versions, but not for 0.2.100?

**Comment by Veetaha** [comment]
Previously there was a check that if the binary is corrupted, we download it once again. I guess we forgot to add it in #3629

**Comment by Veetaha** [comment]
Also, I wish I could see the entire log, there should've been a message like `Checked binary availability via --version` with the error cause.

**Comment by matklad** [comment]
Hm, I think we should be promprint for the download:

https://github.com/rust-analyzer/rust-analyzer/blob/c23c76eea9990f6e46fac3b92c9652600b2a47e9/editors/code/src/main.ts#L216-L222

@schungx could you have `askBeforeDownload: false` in the settings perchance? 

>Shouldn't there be checks performed to check the integrity of the language server runtime?

The `rust-analyzer-windows.exe --version.` is exactly an integrity check. I wonder why that error doesn't end up being showed by default....

Also we perhaps should change our download logic to first download in a temporary location, and then atomically swap the file, so that we don't get partially-downloaded files in the first place.

**Comment by schungx** [comment]
> The `rust-analyzer-windows.exe --version.` is exactly an integrity check. I wonder why that error doesn't end up being showed by default....

Well, I tried running `rust-analyzer-windows.exe --version` manually, and it failed.  The executable file is corrupted (actually the download was interrupted and it was incomplete).

So you're not gonna get a version back by running it...  Likely you'll be seeing an error.

`askBeforeDownload` is `true`.

**Comment by schungx** [comment]
Hhmmmm.... now I got this:

```
Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api matklad.rust-analyzer
```

**Comment by schungx** [comment]
OK, turning off `semantic tokens` gets rid of this error.  There probably should be a warning somewhere...
