### ISSUE TITLE
rust-analyzer does not suggest extern "C" routines

### ISSUE THREAD

**Issue by AndrewGaspar** [rust-analyzer/rust-analyzer#3711]
Given this code:
```rust
use std::ffi::c_void;

extern "C" {
    fn external_function() -> c_void;
}

fn internal_function() {}

fn main() {
    // type here
}
```

rust-analyzer will suggest `internal_function`, but it will not suggest `external_function`.

**Comment by flodiebold** [comment]
Hmm, do we even collect defs from `extern` blocks? :thinking:

**Comment by edwin0cheng** [comment]
@flodiebold I just checked, we don't have collect defs from extern blocks as you mention in collect defs : 

https://github.com/rust-analyzer/rust-analyzer/blob/ac05571dc9b01dbbb6cf97988190563f1b33ce13/crates/ra_syntax/src/ast/generated.rs#L4125-L4139

And we even don't have the ast node binding for extern blocks either.

**Comment by matklad** [comment]
Yeah, we do nothing with extern blocks at the moment. Although, I suppose it shouldn't be hard to add, at least the first cut.

**Comment by ruabmbua** [comment]
Looks like this is already done, close the ticket?
