### ISSUE TITLE
"Fill match arms" assits is corrupts the match block when it has syntax errors

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#3716]
![bad](https://user-images.githubusercontent.com/36276403/77525426-aec9de80-6e91-11ea-8a09-3e9920dd0421.gif)

**Comment by Veykril** [comment]
For
```rust
match Some(()) {
    Some(())
    None => self
}
```
This currently only appends an extra `None => {}` arm, so it doesn't corrupt the match block anymore.
