### ISSUE TITLE
Pankic on stdio.rsProtocolError

### ISSUE THREAD

**Issue by shirshak55** [rust-analyzer/rust-analyzer#3730]
it works find on my computer but when i use vscode in remote computer i see this error.

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"Error: ', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.3.1/src/stdio.rsProtocolError:(29":13
unexpected message during shutdown: Ok(Response(Response { id: RequestId(U64(1)), result: None, error: None }))")
```

**Comment by matklad** [comment]
Could you try to get the log of messages between client and server? I am not familiar with VS Code remote, but for local vscode it is enabled with `"rust-analyzer.trace.extension": true`

https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/readme.adoc#troubleshooting

**Comment by shirshak55** [comment]
@matklad hmm strange now its working properly after restarting vscode. Should we close this issue?

**Comment by matklad** [comment]
Yeah, I guess it won't be actionable without a way to reproduce/logs. But feel free to reponen if you see this again!
