### ISSUE TITLE
`mod` statement in file included multiple times

### ISSUE THREAD

**Issue by Diggsey** [rust-analyzer/rust-analyzer#3747]
I very much appreciate that this is a niche case, but thought I'd report it anyway 😛 

I have a project which includes a file `common/convert.rs` from two different modules. This file declares a submodule "error" `common/error.rs`.

Rust-analyzer reports a spurious error at a seemingly unrelated line in *one* of the modules that includes `common/convert.rs`:

![image](https://user-images.githubusercontent.com/451321/77782762-b20ac900-704f-11ea-87e5-1869510bbf69.png)

Unfortunately, the project is extremely large and is not public.

**Comment by matklad** [comment]
Yeah, I guess we need to revert the pr which added support for `include!` :D

**Comment by edwin0cheng** [comment]
#8134 should fix this, but I am not sure, @Diggsey could you mind to test it again ?

**Comment by lnicola** [comment]
Ping @Diggsey

**Comment by Diggsey** [comment]
This appears to be fixed 👍
