### ISSUE TITLE
Way to toggle inlay hints without reload

### ISSUE THREAD

**Issue by dbr** [rust-analyzer/rust-analyzer#3751]
I was looking for a way to toggle the the inlay type hints dynamically, as they are often useful, but I find can make code more "dense" and hard to read at times:

<img width="1237" alt="Screen Shot 2020-03-28 at 12 26 41 pm" src="https://user-images.githubusercontent.com/509/77812245-f64da600-70ef-11ea-8ab7-e2dd55a766da.png">

Currently if I alter any of the settings like `rust-analyzer.inlayHints.typeHints` it will only apply after clicking Reload, which is quite disruptive (takes several seconds while the window closes/reopens and reanalyzes the project etc)

Judging from #1977 this setting would apply without reload; is this behaviour possible to restore?

**Comment by SomeoneToIgnore** [comment]
This will be done eventually here: https://github.com/rust-analyzer/rust-analyzer/pull/3666

I'm working on it, but need more time to finish things.

**Comment by dbr** [comment]
Ah that's great. No rush from me, but will be nice to have when it's done. Thanks!
