### ISSUE TITLE
Inferior completion suggesions (and what to do with them?)

### ISSUE THREAD

**Issue by ngortheone** [rust-analyzer/rust-analyzer#3752]
Hi every so often I try use rust-analyzer. Right now my setup is vim with RLS and Clion with Rust plugin and I am really enthusiastic about rust analyzer.

Unfortunately completion suggestions are really poor. I am trying to understand whether there is something wrong with my rust-analyzer setup or completion suggestions are indeed not as good as I wish them to be.

Here is the same snippet of code with completion options on RLS(vim), rust-analyzer (both vscode and vim) and Clion with Rust plugin

### Idea:
![DeepinScreenshot_select-area_20200327225709](https://user-images.githubusercontent.com/18271144/77816282-74428a80-70b9-11ea-9091-6daf6c86b2fd.png)

### RLS(vim)
![DeepinScreenshot_select-area_20200327225802](https://user-images.githubusercontent.com/18271144/77816288-83c1d380-70b9-11ea-9057-e0a9907d4574.png)

### rust-analyzer (both vscode and vim have same completions suggestions)
![DeepinScreenshot_select-area_20200327225734](https://user-images.githubusercontent.com/18271144/77816333-e6b36a80-70b9-11ea-9260-5f900b0666f1.png)

Is there something I can do to get better suggestions? 
Thanks.

**Comment by lnicola** [comment]
There's nothing wrong with your setup. There are limitations regarding associated types: see #2603 and the others that end up pointing to https://github.com/rust-lang/chalk/issues/234. Besides that, the `impl Trait` and `dyn Trait` support has been ripped out and is waiting for pending redesign in `chalk`.

**Comment by ngortheone** [comment]
Thanks for prompt reply @lnicola ! I will be monitoring progress wrt to `chalk`

**Comment by lnicola** [comment]
Let's close this for now and please report back if fixing `chalk` doesn't help.

**Comment by flodiebold** [comment]
> Besides that, the `impl Trait` and `dyn Trait` support has been ripped out and is waiting for pending redesign in `chalk`.

That's incorrect, `dyn Trait` works and `impl Trait` only doesn't work in return position.
