### ISSUE TITLE
Only partial type hints for some iterator types

### ISSUE THREAD

**Issue by eminence** [rust-analyzer/rust-analyzer#3759]
RA (version aaa6961) seems to be a little confused about built-in iterator types like `std::str::Chars`. 

![image](https://user-images.githubusercontent.com/402454/77828123-01a0d180-70f0-11ea-9d10-0c9bcd520672.png)

**Comment by lnicola** [comment]
Probably a duplicate of #3752.

**Comment by flodiebold** [comment]
Yeah, and #2603 and many others...
