### ISSUE TITLE
Arithmetic underflow on project load

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#3760]
thread 'main' panicked at 'attempt to subtract with overflow', crates/rust-analyzer/src/main_loop.rs:720:20

Seen with a debug build on the `rust-analyzer` repository.

**Comment by lnicola** [comment]
```
[crates/rust-analyzer/src/main_loop.rs:719] total = 183
[crates/rust-analyzer/src/main_loop.rs:720] loop_state.roots_scanned_progress = None
[crates/rust-analyzer/src/main_loop.rs:721] world_state.roots_to_scan = 203
```

**Comment by edwin0cheng** [comment]
Yeah, the `total` is defined as : 
```
 let total: usize = world_state.workspaces.iter().map(|it| it.n_packages()).sum();
```

which is out-dated as we have added a lot of different things (e.g. out-dirs) to roots additionally. I would submit a PR to fix it.

**Comment by lnicola** [comment]
I wanted to change it to store the original value of roots_to_scan, but there's already a FIXME there.
