### ISSUE TITLE
Incremental synchronization support

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#3762]
Spawned off #3758.

Some LSP clients (ahem, Gnome Builder) don't respect our choice for full text synchronization, and it wouldn't hurt to reduce the amount of text transferred.

The text change notification comes in [here](https://github.com/rust-analyzer/rust-analyzer/blob/1c2d4135db867efe335a0654d86429bea7bb9caf/crates/rust-analyzer/src/main_loop.rs#L598-L599). `params.content_changes` contains all [changes](https://docs.rs/lsp-types/0.73.0/lsp_types/struct.TextDocumentContentChangeEvent.html), but right now we only process one of them. Before passing the changes to the VFS layer, we need to convert from a line/column to byte offset representation. The latter is implemented as the `TextRange` type, and a conversion method is available [here](https://github.com/rust-analyzer/rust-analyzer/blob/1c2d4135db867efe335a0654d86429bea7bb9caf/crates/rust-analyzer/src/conv.rs#L205).

**Comment by matklad** [comment]
Another potential complication is that we store files with normalized line endings (`\n`), so we need to account for that. I *think*  just normalizing the `text` from `TextDocumentContentChangeEvent` would do the trick, as ranges are ending-agnosic.

**Comment by lnicola** [comment]
> I think just normalizing the text from TextDocumentContentChangeEvent would do the trick, as ranges are ending-agnosic.

But.. their length changes when normalizing the text. This seems harder than I thought :sweat_smile:.
