### ISSUE TITLE
Type inference error that is not one on vscode

### ISSUE THREAD

**Issue by Nimpruda** [rust-analyzer/rust-analyzer#3772]
**IDE :** VSCode 1.43.2
**Rust-analyzer extension version :** 0.2.100

**Issue :** I got the following code : 
```rust
use jsonwebtoken::{Algorithm, EncodingKey, Header};

fn main() {
    let mut header = Header::new(Algorithm::RS256);
    header.kid = Some("stuff".to_owned());
    let encoding_key = match EncodingKey::from_rsa_pem(include_bytes!("stuff")) {
        Ok(k) => k,
        Err(_) => panic!(),
    };
}
```

EncodingKey::from_rsa_pem returns an EncodingKey but rust analyzer infers it to be the never type (!) even thought it shouldn't. Even the k in the match is inferred as a !. Perhaps it's my mistake as I'm relatively new to rust but I think rust-analyzer is the problem.

**Comment by SomeoneToIgnore** [comment]
I believe, this might be related to https://github.com/rust-analyzer/rust-analyzer/issues/3046

**Comment by edwin0cheng** [comment]
I just tested it in master, the above code works at least in Windows machine. Um..

**Comment by bjorn3** [comment]
> **Rust-analyzer extension version :** 0.2.100

I believe this is a very old version of rust-analyzer compiled from source. Try updating to the latest version.

**Comment by lnicola** [comment]
Also works for me on Linux.

**Comment by Nimpruda** [comment]
@bjorn3 That is the version of the vscode extension not rust analyzer. I'll check the version of rust-analyzer later today.

**Comment by Nimpruda** [comment]
It actually does work now. I have no clue why since I have version 9e12b9e (the last one) I rebooted my computer that's about it.
