### ISSUE TITLE
Go to definition does not work (no-op) for functions imported through library that exports pub crate

### ISSUE THREAD

**Issue by nokola** [rust-analyzer/rust-analyzer#3776]
Works with RLS, fails with RustAnalyzer. This issue prevents me from using Rust Analyzer in VS code, since I can't go to definition to resolve parameter types for most of the functions in my code (gl* opengl functions).

To reproduce:
1. Clone https://github.com/nokola/nvg-miniquad/ and open in VS code
2. Open examples/drawaa.rs
3. Ctrl+click on glClearColor(...)

**Expected:** all OK, navigate to definition or show the multiple definitions per platform available

**Actual:** nothing happens, 

**More info:**
nvg-miniquad imports the gl*() functions from miniquad::sapp::* library like so:
```rust
use miniquad::sapp::*;
```
cargo.toml:
```
[dependencies.miniquad]
path = '..\miniquad-nokola'
# same as:
# git = "https://github.com/nokola/miniquad"
# rev = "b980915c62337bf60afbe8708569977adb4c0d74"
```

miniquad has multiple sapp::* implementations
```rust
#[cfg(target_os = "macos")]
pub extern crate sapp_darwin as sapp;
#[cfg(not(any(
    target_os = "linux",
    target_os = "macos",
    target_os = "android",
    target_arch = "wasm32",
    windows
)))]
pub extern crate sapp_dummy as sapp;
#[cfg(target_os = "linux")]
pub extern crate sapp_linux as sapp;
#[cfg(target_arch = "wasm32")]
pub extern crate sapp_wasm as sapp;
#[cfg(windows)]
pub extern crate sapp_windows as sapp;
#[cfg(target_os = "android")]
pub extern crate sapp_android as sapp;
```

**Comment by edwin0cheng** [comment]
Maybe #3711 ?

**Comment by nokola** [comment]
Not #3711 because the same scenario works OK if I try Go To Definition inside the library (nokola/miniquad)
![image](https://user-images.githubusercontent.com/6869225/77949469-d8ad4780-727b-11ea-876d-4cdaccb21083.png)

**Comment by flodiebold** [comment]
I think that's just the index fallback at work.

**Comment by nokola** [comment]
Good point!

**Comment by lnicola** [comment]
@nokola the repo seems broken (even at `1aac09c2639055e99b3fe2c89f2753e0cadd4792`). Since #3711 is now fixed, do you think we can close this? The index fallback was recently removed, too.

(Marking `S-actionable`, if you look at this in the future and the OP hasn't answered, ping me so we can close it).

**Comment by nokola** [comment]
I have the working repository here and checked - all works OK now and the issue is fixed.
Thank you for the note!
