### ISSUE TITLE
I have 600 lexer-stage errors and VS Code/RA cannot keep up

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#3782]
It appears like RA tries to process every edit before re-analyzing, but then takes longer to re-analyze than I need to do the next edit. (Current first error: "Syntax Error: expected COMMA".)

**Comment by kjeremy** [comment]
What's your environment?

**Comment by djc** [comment]
MacBook Pro running macOS 10.15.3 with 2.2 GHz i7 and 32 GB RAM, running stable Rust.

**Comment by kjeremy** [comment]
Vscode, version of rust analyzer?

**Comment by djc** [comment]
Ah, sorry -- I have VS Code 1.43.2 and RA 0.2.108.

**Comment by djc** [comment]
(BTW, the lag introduced on pressing the Enter key is especially annoying in this kind of scenario.)

**Comment by kjeremy** [comment]
Do you have enhanced typing enabled? You may want to disable that and see how it goes. A reproducible project would be great.

**Comment by Veetaha** [comment]
This might be the related case reported in zulip:
https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/Analyzer.20being.20super-slow.20on.20nightly/near/192127028

@djc do you observe the 100% single CPU core load when this happens?

**Comment by djc** [comment]
The code was somewhat similar to this (I've recreated this from what I had originally):

https://github.com/djc/tokio-imap/blob/ra-sloooow/imap-proto/src/parser/rfc3501/mod.rs

I was refactoring nom parsers from macro-style to function-style, starting from a replace of `!(` to `(`. The `do_parse!()` macro in particular has some funky syntax going on.) I'm on a different machine now with a 2,3 GHz 8-Core Intel Core i9, so the performance is much better (not getting 100% CPU on any of this machine's cores), but I'm still seeing similar issues. Would not be surprised if I had 100% CPU on the work laptop.

What is enhanced typing exactly? I can't find it in the settings.

**Comment by kjeremy** [comment]
My mistake. They setting doesn't exist anymore.

**Comment by lnicola** [comment]
[Enhanced typing](https://rust-analyzer.github.io/manual.html#on-enter) is now disabled by default and we limit the number of errors returned to the client.

@djc are you still seeing this?

(Marking `S-actionable`, if you look at this in the future and the OP hasn't answered, ping me so we can close it).

**Comment by djc** [comment]
I did some spot checking against the old branch and it does look like this is fixed. Thanks!
