### ISSUE TITLE
`#![no_std]` can't find crate for `test` in vs code

### ISSUE THREAD

**Issue by ninjasource** [rust-analyzer/rust-analyzer#3801]
Hi,

Same issue as #3297 but the solution there (for vim) does not seem to work for vs code on windows unfortunately.

![Capture](https://user-images.githubusercontent.com/15350484/78115218-5ac37a80-73fa-11ea-96ab-e8e96069ce64.PNG)

Here is my setup:

.cargo\config file:
```
[build]
target = "thumbv7m-none-eabi"
```

.vscode\settings.json file:
```
{
    "rust.target": "thumbv7m-none-eabi",
    "rust.all_targets": false
}
```

src\main.rs file:
```
#![no_std]
#![no_main]

#[entry]
fn main() -> ! {
  loop {}
}
```

rust-analyzer version: 0.2.108
vs code version: 1.43.2
operating system: Windows 10
rustc 1.42.0 (b8cedc004 2020-03-09) stable

**Comment by lnicola** [comment]
I don't know why they're needed, but those settings are spelled `"rust-analyzer.cargo-watch.allTargets": true` and `"rust-analyzer.cargo-watch.arguments": ["--target", "thumbv7m-none-eabi"]`.

**Comment by ninjasource** [comment]
Thank you @lnicola, that worked! 
Here is the required settings file if anyone else comes across this post:

.vscode\settings.json file:
```
{
    "rust-analyzer.cargo-watch.allTargets": false,
    "rust-analyzer.cargo-watch.arguments": [
        "--target",
        "thumbv7m-none-eabi"
    ]
}
```

**Comment by liangyongrui** [comment]
> Thank you @lnicola, that worked!
> Here is the required settings file if anyone else comes across this post:
> 
> .vscode\settings.json file:
> 
> ```
> {
>     "rust-analyzer.cargo-watch.allTargets": false,
>     "rust-analyzer.cargo-watch.arguments": [
>         "--target",
>         "thumbv7m-none-eabi"
>     ]
> }
> ```

The current configuration seems to have changed, can you still work?

**Comment by lnicola** [comment]
```json
{
    "rust-analyzer.checkOnSave.allTargets": false,
    "rust-analyzer.checkOnSave.extraArgs": [
        "--target",
        "thumbv7m-none-eabi"
    ]
}
```

**Comment by Vrixyz** [comment]
Hello, I'm encountering this issue at https://github.com/Vrixyz/button/commit/b1707a9d09d0fe97f75ba050113c5268816e3377

I tried all your options for the .vscode/settings with no success for a full working solution.

Auto-completion works if I restart VSCode.

Source from https://github.com/rust-embedded/discovery was working correctly, so I did setup my source to use a **workspace** to match its structure as much as possible, It worked for a moment 🤷  but then the error came back.

**Comment by ninjasource** [comment]
> 
> 
> ```json
> {
>     "rust-analyzer.checkOnSave.allTargets": false,
>     "rust-analyzer.checkOnSave.extraArgs": [
>         "--target",
>         "thumbv7m-none-eabi"
>     ]
> }
> ```

Thanks for the update. Yes it broke but your new settings work, cheers!

**Comment by ninjasource** [comment]
> 
> 
> Hello, I'm encountering this issue at [Vrixyz/button@b1707a9](https://github.com/Vrixyz/button/commit/b1707a9d09d0fe97f75ba050113c5268816e3377)
> 
> I tried all your options for the .vscode/settings with no success for a full working solution.
> 
> Auto-completion works if I restart VSCode.
> 
> Source from https://github.com/rust-embedded/discovery was working correctly, so I did setup my source to use a **workspace** to match its structure as much as possible, It worked for a moment 🤷 but then the error came back.
> 
> PS: I'm on macOS Catalina

Unfortunately I'm on Windows so I can't say why it's not working for you on a Mac. Make sure you use the new settings @Inicola posted and not my old settings. The settings can be scoped to your Workspace or User. Works for both. Also make sure you have run "rustup update" recently as there has been a new compiler release a few days ago.

**Comment by Vrixyz** [comment]
Thanks ❤️ , `rustup update` fixed it !
It sure feels like a hack though...

**Comment by cdmistman** [comment]
I appear to be running in this bug...

I'm working in a workspace. I'm using a custom target. Here's my `.vscode/settings.json`:
```json
{
    "rust-analyzer.checkOnSave.allTargets": false,
    "rust-analyzer.checkOnSave.overrideCommand": ["cross"],
    "rust-analyzer.checkOnSave.extraArgs": [
        "--target",
        "x86_64-unknown-custom"
    ],
}
```

I also tried without the overrideCommand flag. Any suggestions?

**Comment by ninjasource** [comment]
I haven't had to use but for one project I had to change "check" to "xcheck" like so:
```"rust-analyzer.checkOnSave.command": "xcheck",```

perhaps you could try something like 
```"rust-analyzer.checkOnSave.command": "cross",```
or
```"rust-analyzer.checkOnSave.command": "check cross",```

**Comment by muttering-oldman** [comment]
All of the above didn't work out for me.
I can still see the warning.

Any ideas, guys?

**Comment by brainstorm** [comment]
> Thank you @lnicola, that worked!
> Here is the required settings file if anyone else comes across this post:
> 
> .vscode\settings.json file:
> 
> ```
> {
>     "rust-analyzer.cargo-watch.allTargets": false,
>     "rust-analyzer.cargo-watch.arguments": [
>         "--target",
>         "thumbv7m-none-eabi"
>     ]
> }
> ```

This is either a regression or something else but still seems to be a problem, could anyone reopen it?:

![Skärmavbild 2020-08-27 kl  22 31 33](https://user-images.githubusercontent.com/175587/91442446-31c5e980-e8b5-11ea-815f-6d2d78c3297e.png)

**Comment by lnicola** [comment]
@brainstorm you're using the wrong preferences, see the comments above like https://github.com/rust-analyzer/rust-analyzer/issues/3801#issuecomment-609003603.

**Comment by brainstorm** [comment]
Aah, sweet, thanks @lnicola, works now! :)

**Comment by ninjasource** [comment]
Another gotcha I have come across is opening vs code in the wrong folder. For example, if you open vs code in a folder without a cargo.toml file (maybe your toml file is in a sub folder of this one) then rust-analyzer will not read your settings.json file. A quick sanity check would be to run "cargo check" on the folder you open vs code in and see if it runs ok.

**Comment by dialtone** [comment]
It seems to not be working for me.

```json
{
    "rust-analyzer.checkOnSave.allTargets": false,
    "rust-analyzer.checkOnSave.extraArgs": [
        "--target",
        "thumbv7em-none-eabihf"
    ]
}
```

still results in the test error in vscode.

**Comment by ninjasource** [comment]
@dialtone, Do you have the right target installed?
```
rustup target add thumbv7m-none-eabi
```
Another thing to check is your folder setup. You may be opening your visual studio code in the wrong folder and rust-analyzer is not able to figure things out. Can you run `cargo check` from the folder you open vs code in?

**Comment by dialtone** [comment]
Yeah, code compiles and runs on the embedded device when I `cargo run` in it. And yeah I can run `cargo check` as well. In any case the setup is here: https://github.com/dialtone/airy

**Comment by ninjasource** [comment]
I cloned your repo and got the error message to go away by adding a .vscode/settings.json file in your project root with 

```
{
    "rust-analyzer.checkOnSave.allTargets": false,
    "rust-analyzer.checkOnSave.extraArgs": [
        "--target",
        "thumbv7em-none-eabihf"
    ]
}
```
VS Code needed a restart for rust-analyzer to pick it up.

So the file structure is (I've included the important files):
```
.vscode/settings.json
.cargo/config
src/lib.rs
Cargo.toml
```

**Comment by dialtone** [comment]
Well, that file was simply not checked in, but it just doesn't make the errors go away for me for some reason. Happy to do whatever you want to debug this.

**Comment by ninjasource** [comment]
I think it would be appropriate to check that file into your repo especially since it would be nice to have a known working repo linked in this thread.

**Comment by dialtone** [comment]
done

**Comment by dialtone** [comment]
Just to be clear though, the repository still doesn't work for me, even with the file checked in and having opened the project from the right directory.

**Comment by ninjasource** [comment]
Thanks. Your repo works (without showing the error message) for me on both linux and windows with a fresh checkout. Other than a strangely named `.cargo/config` file (never seen it with a .toml extension but it doesn't seem to make a difference) I can't spot anything wrong. Do a `cargo clean` and maybe reinstall your rust-analyzer plugin and restart vs code. Perhaps this is a caching issue. Check your global vs code settings for conflicting settings. Try your repo on another machine. Other than that I'm all out of ideas, sorry!

**Comment by dialtone** [comment]
Well done all of the above and checked the global settings config and can't spot anything obviously wrong so I'll just keep it broken.

below is my global vscode settings file.
```
{
    "debug.allowBreakpointsEverywhere": true,
    "editor.minimap.enabled": true,
    "editor.formatOnSave": true,
    "editor.wordWrap": "bounded",
    "editor.wordWrapColumn": 120,
    "editor.multiCursorModifier": "alt",
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    },
    "editor.cursorBlinking": "smooth",
    "editor.fontFamily": "FiraCode-Retina",
    "editor.fontLigatures": true,
    "editor.fontSize": 12,
    "editor.formatOnPaste": true,
    "terminal.integrated.shell.osx": "/usr/local/bin/fish",
    "terminal.integrated.fontSize": 12,
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "workbench.iconTheme": "vscode-icons",
    "workbench.editor.enablePreview": false,
    "diffEditor.renderSideBySide": false,
    "vsicons.dontShowNewVersionMessage": true,
    "explorer.confirmDelete": false,
    "window.zoomLevel": 0,
    // markdown
    "markdown-preview-enhanced.mermaidTheme": "forest",
    // git
    "git.inputValidationLength": 120,
    "git.inputValidationSubjectLength": 80,
    // plain text
    "[plaintext]": {
        "editor.wordWrapColumn": 20000,
    },
    // Python
    "python.formatting.provider": "autopep8",
    "python.formatting.autopep8Args": [
        "--ignore",
        "E402"
    ],
    "[python]": {
        "editor.tabSize": 4,
        "editor.insertSpaces": true,
        "editor.formatOnSave": false
    },
    "python.sortImports.path": "nosorting",
    // rust
    "editor.find.addExtraSpaceOnTop": false,
    "[rust]": {
        "editor.defaultFormatter": "rust-lang.rust"
    },
    "rust-client.channel": "nightly", // Use Rust nightly channel
    "rust.clippy_preference": "on", // Always run Clippy lints
    "rust.unstable_features": true, // Conditionally enable range formatting, not enabled by default
    "rust.all_targets": false,
    // go
    "go.useLanguageServer": true,
    "go.autocompleteUnimportedPackages": true,
    "go.goroot": "/usr/local/opt/go/libexec",
    "go.gopath": "/Users/dialtone/dev/go",
    "[go]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.fixAll": true,
        }
    },
    "[go.mod]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
    },
    "gopls": {
        "analyses": {
            "fillreturns": true,
            "undeclarename": true,
            "unusedparams": true,
            "nonewvars": true,
        }
    },
    // other
    "C_Cpp.default.cStandard": "c11",
    "C_Cpp.default.intelliSenseMode": "clang-x64",
    "lldb.showDisassembly": "never",
}
```

**Comment by dialtone** [comment]
I don't have vscode-rust installed. Some of the settings up there, I can remove them all except the defaultFormatter without which rust-analyzer does no formatting of the code. The end result doesn't change.

**Comment by lnicola** [comment]
Do the settings work? If they don't apply, they should have a gray-ish color. You shouldn't need to set the fornatter like that. And I guess vscode-rust is called differently now?

**Comment by dialtone** [comment]
Looks like that may have done it then. Basically the "official" rust extension on VSCode called "rust-lang.rust" should be removed in favor of "matklad.rust-analyzer"?

**Comment by lnicola** [comment]
If you want to use rust-analyzer, yes, don't install both. Some of us prefer it to the official one (and it might replace it in the future), but YMMV.

**Comment by kjeremy** [comment]
We really need to put this in users' faces. For some reason there is a lot
of confusion around this topic.

**Comment by IceSentry** [comment]
Since this is the first result on google I'll leave this here. I had this error and assumed it was caused by rust-analyzer, but it was caused by the cargo extension and not rust-analyzer. Disabling that extension fixed it for me.

**Comment by HTG-YT** [comment]
I just ran into this today. The only problem is that I have multiple crates in my project, and that *one* of them targets `x86_64-unknown-uefi` and the others all target a custom target. Is there a way to... configure the `checkOnSave` arguments for both targets?

**Comment by andrewgazelka** [comment]
I am getting this error again. Is anyone else?

**Comment by eqkessel** [comment]
I was having the same issue and after a little poking around I don't think this is an issue with the rust-analyzer extension, but actually the `panicbit.cargo` extension. It appears to run `cargo check` on its own, which is running into issues with not properly knowing the target (I think), so it complains about not being able to find the `test` crate. If you're having the same problem but the fixes here aren't working, I'd check if that extension is installed, try disabling it, and see if the error persists.

**Comment by iFreilicht** [comment]
@andrewgazelka The problem in your config is that you override the command arguments and add `--all-targets` again, which makes `"rust-analyzer.checkOnSave.allTargets": false,` have no effect.

I tried this today on a new project, and if you specify the target in `.cargo/config.toml` like so:

```toml
[build]
target = "avr-specs/avr-atmega328p.json"
```

Then all you need in your `.vscode/settings.json` is this; 

```toml
{
    "rust-analyzer.checkOnSave.allTargets": false,
}
```

**Comment by MolotovCherry** [comment]
Looks like these keys keep changing. In the latest rust analyzer, it is this one for me
```
"rust-analyzer.check.allTargets": false,
```

**Comment by XGY4n** [comment]
> None of these worked for me. I still have the same errors.

same to me, sad .

**Comment by XGY4n** [comment]
> 
I create dir and file 
xxx
├─.cargo
├─.vscode <- this and add  them jscode  in setting.json  and it works for me
├─src

**Comment by matteoturini** [comment]
Yes, I also did this. It did not work.

**Comment by Brian3647** [comment]
Not working for me either. Config:
```json
{
  "rust-analyzer.cargo.target": "x86_64-unknown-none",
  "rust-analyzer.check.allTargets": false,
  "rust-analyzer.check.extraArgs": ["--target", "x86_64-unknown-none"]
}
```

**Comment by taunusflieger** [comment]
Issue is still there. I got the above error with the following workspace settings:

```yaml
{
    "rust-analyzer.cargo.target": "thumbv6m-none-eabi",
    "rust-analyzer.cargo-watch.allTargets": false,
    "rust-analyzer.cargo-watch.arguments": [
        "--target",
        "thumbv6m-none-eabi"
    ],
    "rust-analyzer.checkOnSave.extraArgs": [
        "--target",
        "thumbv6m-none-eabi"
    ]
}
```

**Comment by Hecatron** [comment]
I'm noticing while developing for the stm32
this does work in so far as suppressing the missing test crate error
```json
  "rust-analyzer.check.allTargets": false,
  "rust-analyzer.check.extraArgs": [
    "--target",
    "thumbv7em-none-eabihf"
  ],
```

But it also seems to have a side effect of preventing errors or warnings showing up of code under examples
I'm only seeing analysis of code under src.

If I set check.allTargets to true then it does check code under examples, but flags that missing test crate error

**Comment by l-0-l** [comment]
Weirdly this issue occurred for me when simply copying a directory with an existing sample project, no issue in the original one but `can't find crate for 'test'` in the new one. Since rust-analyzer changed over the years, and this thread is currently 4 years old, here is a currently working solution (VSCode 1.90, rust-analyzer v0.3.1995) on Linux:
File `.vscode/settings.json`:
```
{
    // The "target" line is optional, can be skipped if you have this in the .cargo/config.toml file:
    // [build]
    // target = "thumbv6m-none-eabi"
    "rust-analyzer.cargo.target": "thumbv6m-none-eabi",
    "rust-analyzer.cargo.allTargets": false
}
```
Generally, when you try this or any other solution in `settings.json`, pay attention that the lines you've pasted aren't grayed out, you can always start typing and follow the auto-completion to check for changed syntax.
This error message appears because by default the extension has `Pass --all-targets to cargo invocation`, and (probably) since we are `#![no_std]` in this case, we must set it to a specific target. This probably could be resolved with a fix in rust-analyzer.

**Comment by K4LCIFER** [comment]
> File `.vscode/settings.json`:
> 
> ```
> {
>     // The "target" line is optional, can be skipped if you have this in the .cargo/config.toml file:
>     // [build]
>     // target = "thumbv6m-none-eabi"
>     "rust-analyzer.cargo.target": "thumbv6m-none-eabi",
>     "rust-analyzer.cargo.allTargets": false
> }
> ```

Your solution still works for me with VSCode v1.03.1 and rust-analyzer v0.3.2577 for an AVR MCU: In `.vscode/settings.json`:
```json
{
    "rust-analyzer.cargo.target": "avr-none",
    "rust-analyzer.cargo.allTargets": false
}
```
