### ISSUE TITLE
Module name on hover should have another newline after it

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#3813]
So that the module and item have a blank line between them.

**Comment by Veetaha** [comment]
Might I ask you to provide a screenshot where you see the issue? Are you talking about hovering over the `mod foo;` declaration or about the module path in symbols on-hover hints? If the latter I don't see any issue with the current impl.

**Comment by kjeremy** [comment]
The latter. It would be nicer if there was some separation.

**Comment by aloucks** [comment]
The RLS vscode extension renders a thin line between the hover tooltip sections (or at least it did; I haven't used it in a long time). I think that would be preferable over empty lines.

**Comment by kjeremy** [comment]
Hm. Try it out and let's see what it looks like.

**Comment by Arthamys** [comment]
With a line separator it renders as:

![after_line_3813](https://user-images.githubusercontent.com/11710698/82682187-2bd5c200-9c4f-11ea-9029-a169929d5eb9.png)
(I can't seem to get a greater separation between the horizontal rule and the signature)

Without the line separator, but only an extra newline:

![after_3813](https://user-images.githubusercontent.com/11710698/82682332-617aab00-9c4f-11ea-9056-20610bafe79f.png)

**Comment by kjeremy** [comment]
OH! that may be because (I may be wrong, this is just a cursory glance) it looks like rls returns multiple marked strings https://github.com/rust-lang/rls/blob/fe46c95c3f01fbdaca36bdf70739d32062c1f53a/rls/src/actions/hover.rs#L482

**Comment by kjeremy** [comment]
As an aside rls is more feature complete with their markdown handling. More PRs are welcome :)

**Comment by Arthamys** [comment]
Yes, it seems the RLS has a more flexible approach to how tooltip information is collected & sent to the client. From what I understand, rust-analyzer only build a String as a response to a HoverRequest.

Modifying the handling of HoverRequests to respond with a broader set of HoverContents variants would probably lead to a less awkward handler for tooltips with multiple sections.

**Comment by aloucks** [comment]
The merged change (#4559) has some negative side effects. The module name is no longer in the correct font (it's not rendering with the code font, i.e. it's not monospace any longer). The line separator is also overlapping the text below it.

**Comment by Veetaha** [comment]
cc #4594

**Comment by chetankhilosiya** [comment]
I verified that, the line separator is working properly. Also the hover popup follows the font size. Attaching the screenshot.
Tested on master branch. Short Commit ID: 740763656.
![rust-hover-fix](https://user-images.githubusercontent.com/1639535/86814798-814f1c80-c09f-11ea-9b34-8698490addcd.png)
