### ISSUE TITLE
Highlight type aliases and attributes by default

### ISSUE THREAD

**Issue by SomeoneToIgnore** [rust-analyzer/rust-analyzer#3822]
With zero additional highlighting-related settings and a standard VSCode dark theme, the code looks like this:

<img width="785" alt="image" src="https://user-images.githubusercontent.com/2690773/78245622-7610b180-74f0-11ea-9143-e18f1128473a.png">

RA does not highlight unresolved entities, such as `TreeRoot` from the screenshot.

It also does not highlight type aliases (`SyntaxNodeRef`, `RefRoot`, `OwnedRoot`, `GreenBuilder`) and annotations (`#derive`) which makes it confusing and does not fit into the general scheme.

**Comment by matklad** [comment]
I think this actually regressed with the recent insiders build. We do set semantic tokens for attrs:

![image](https://user-images.githubusercontent.com/1711539/78247191-bb31e500-74ea-11ea-90f1-3448edd88c7f.png)

Specifically, I think they might have changed the name of the filed in package.json we use map sem tokens to tm scopes.

**Comment by kjeremy** [comment]
The range provider was pushed to vscode a few days ago and it looks like there' some fallout from that and a few other things.

**Comment by matklad** [comment]
fixed by https://github.com/rust-analyzer/rust-analyzer/pull/3827

Relevant docs are https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview

**Comment by SomeoneToIgnore** [comment]
I've installed `rust-analyzer version: unreleased (09b8ee3)` but see no changes.
<img width="648" alt="image" src="https://user-images.githubusercontent.com/2690773/78287008-bccecd80-7529-11ea-971f-4781e80be61d.png">
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/2690773/78287026-bdfffa80-7529-11ea-8b86-382af0362ecf.png">


But thanks for the PR and the docs nontheless, if you won't be able to fix it, I'll check it out some time later.

**Comment by Veetaha** [comment]
The theme you are using doesn't define any coloring for `meta.attribute` Textmate scope. This is quite tricky because there are loads of scopes in the wild and themes cannot support them all.

To solve this we should actually define what *the default* theme is and use only the scopes that it supports.

**Comment by Veetaha** [comment]
I suppose `Dark+ (default dark)` is what vscode uses by default. Here is its [textmate grammar declration file](https://github.com/microsoft/vscode/blob/bc8b6e6324f569ff6024007bf5f3a5b3b12bef5f/extensions/theme-defaults/themes/dark_plus.json#L1).

**Comment by matklad** [comment]
I must say I generally observe weirdness around syntax highlighting... https://github.com/microsoft/vscode/issues/94367 is one specific issue I've tracked down, but there are more, like variables becoming bold in typescript with pale fire for some reason...

**Comment by SomeoneToIgnore** [comment]
Closing this since type aliases are now highlighted in the default theme and for the attributes there's a separate issue.
