### ISSUE TITLE
Cargo check is not disabled

### ISSUE THREAD

**Issue by SomeoneToIgnore** [rust-analyzer/rust-analyzer#3823]
rust-analyzer version: unreleased (98f7842), macOs

`cargo clean` the project, ensure that all watchers are disabled in RA settings, opent the project.
Edit the project.

Expected: no cargo check
Actual: cargo check is run

![Screenshot 2020-04-02 at 14 57 33](https://user-images.githubusercontent.com/2690773/78246856-80cc4600-74f2-11ea-9f66-66b0dd89b3a9.png)

**Comment by SomeoneToIgnore** [comment]
cc @matklad , most probably caused by the recent reafactorings, used to work normally for me during the https://github.com/rust-analyzer/rust-analyzer/pull/3666 implementation

**Comment by matklad** [comment]
Might, or might not get fixed by 3824

**Comment by matklad** [comment]
(the new option is `"rust-analyzer.checkOnSave.enable": false`

**Comment by SomeoneToIgnore** [comment]
Have checked the `rust-analyzer version: unreleased (3c9e9d3)`, it indeed fixes the issue, but now the setting change requires RA restart to apply and does not clean the progress bar, when turned off.
Do you want another issue for that? :)
