### ISSUE TITLE
Auto-import without nested imports

### ISSUE THREAD

**Issue by jminer** [rust-analyzer/rust-analyzer#3831]
I've been using Rust since before 1.0, and I still use the same style of imports as before nested imports were added in Rust 1.25. See the first example here:

https://doc.rust-lang.org/edition-guide/rust-2018/module-system/nested-imports-with-use.html

I prefer

```
use std::fs::File;
use std::io::Read;
use std::path::{Path, PathBuf};
```

instead of

```
use std::{fs::File, io::Read, path::{Path, PathBuf}};
```

I feel like it's not bad to prefer using that style since it's the only style Rust supported ~3 years. However, when you use auto-import, ra will merge the new import with an existing one that it chooses. I would really like to use auto-import, but I don't for this reason. Some projects support an older version of Rust than 1.25, like Serde supporting 1.13, so you also couldn't use auto-import when working on them.

I would like an option to have auto-import not use nested imports.

**Comment by matklad** [comment]
Yup, we definitely need to toggle for this.  But this is currently blocked on rewriting our import-insertion infra to work with syntax trees and not raw text: https://github.com/rust-analyzer/rust-analyzer/issues/3301#issuecomment-592931553

**Comment by PhilipDaniels** [comment]
I'd also like this.

Supporting rationale: when nested imports are used you can end up with a HUGE amount of imports for the current crate and they seem to end up as one long line, which makes finding unused ones tricky.

I don't know if Rust-Analyzer has it yet, but it would be nice if when adding imports it kept the list 'nice':

* Sorted by line
* Sorted by name within the line
* Long lines wrapped appropriately
* Removed unused imports

**Comment by phaazon** [comment]
Please this. A potential workaround would be to make `merge_imports = false` from `rustfmt` actually remove nesting (which I think it should do), but this is currently not the case.

**Comment by lnicola** [comment]
This should already be possible with #5935, but I haven't tested it yet.

**Comment by matklad** [comment]
Yeah, I believe this is fixed now. The relevant config is `"rust-analyzer.assist.importMergeBehaviour": "none",`

**Comment by phaazon** [comment]
It doesn’t seem to work on RA v0.8.0. I have set `none` and it still merges them.

**Comment by phaazon** [comment]
Current behavior:

![img_092120_121335](https://user-images.githubusercontent.com/506592/93755636-f09ace00-fc03-11ea-890d-aea9930d01ff.png)
![img_092120_121347](https://user-images.githubusercontent.com/506592/93755640-f2fd2800-fc03-11ea-8c19-15827b6b1a3e.png)
![img_092120_121351](https://user-images.githubusercontent.com/506592/93755645-f42e5500-fc03-11ea-96fb-2f7f764b0d3f.png)

**Comment by matklad** [comment]
This works on master in VS Code. Could you try rebuildin rust-analyzer from source (or just waiting for a release later today)?

Alternatively, *maaaybe* coc-rust-analyzer needs to be upgraded to learn about the new config option (don't know how config is setup for it)?.

**Comment by phaazon** [comment]
I’m rebuilding it right now and trying in coc-nvim. I’ll let you know when it’s cooked. Thanks for the fast replies.

**Comment by phaazon** [comment]
(and yes I have updated the coc config)

**Comment by phaazon** [comment]
Okay, it indeed works with the latest build; thanks!

**Comment by phaazon** [comment]
Argh, sorry to bother again @matklad but I think I have found a weird… situation. So even though it now works, it also splits things like `std::path::{Path, PathBuf}` on two different lines, which I dislike. Any idea how to fix that?

**Comment by phaazon** [comment]
Yeah but then it would put things like `fs` in `std::{…}`, and then when using something from `fs` only, it would do a `use fs::…`, which I really don’t like. I guess I’ll have to give up on what I want and switch to `full` and have them all nested and stop worrying about it… :(

**Comment by matklad** [comment]
@phaazon could you provide a minimal self-containd example for `fs` issue, with behavior you get with `last`, and behavior you want? This is a fresh feature, there may be bugs!

**Comment by lnicola** [comment]
```rust
use std::fs::{self, File};

fn foo() {
    FileType
}
```

If you import `FileType`, you get:

```rust
use std::fs::{self, File};

use fs::FileType;
```

The empty line looks like a bug to me, but adding a new `use` seems both correct and undesirable.

**Comment by matklad** [comment]
>So I guess the idea here is to not add new imports starting from paths already imported. 

Yeah, I *think* we have a similar issue even with nested imports

**Comment by Veykril** [comment]
This problem is the one thing that was missing from the PR in regards to inserting imports. Ideally the `insert_use` assists should go through the existing imports to check if the start of the path is imported somewhere already and merge that into that tree if it exists instead.

**Comment by matklad** [comment]
@Veykril filed https://github.com/rust-analyzer/rust-analyzer/issues/6071. I *think* the problem here is not that auto-import inserts `fs::File` in the wrong place, but that we tell it to insert `fs::File` (as opposed to `std::fs::File`).
