### ISSUE TITLE
autocomplete traits not working

### ISSUE THREAD

**Issue by zohaad** [rust-analyzer/rust-analyzer#3850]
![traits not showing](https://user-images.githubusercontent.com/10496606/78467320-c021af00-770b-11ea-8e28-a9e56a5ea727.png)

I implemented a trait for a struct in lib.rs, but the method is not showing up as an autocomplete option in main.rs 

This feature does work in RLS however

**Comment by zohaad** [comment]
Here are the files I got the issue with:
[lib.rs](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a6003451eb7c1debb937fd7a6fdfeb0f)
[main.rs](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cfc2f803ff11efad00756a47e742451f)

The issue occurs when trying to autocomplete tweet.summarize() in line 10 of main.rs

**Comment by flodiebold** [comment]
Works for me. Did you restart the language server since you added the `main.rs`?

**Comment by zohaad** [comment]
reloading the extension worked, is there a way to reload the language server without a reload of the extension (and thus a restart of VS code?)

**Comment by lnicola** [comment]
@zohaad there's a "Rust Analyzer: Restart server" command.
