### ISSUE TITLE
Autoimport for types defined in a macro

### ISSUE THREAD

**Issue by TimoFreiberg** [rust-analyzer/rust-analyzer#3851]
I use a macro to generate newtypes in [a sideproject](https://github.com/nt-ca-aqe/skill-manager-cli/blob/master/skill-manager/src/wrapper.rs).
Go to definition works fine for [types defined with that macro](https://github.com/nt-ca-aqe/skill-manager-cli/blob/master/skill-manager/src/employees.rs#L40)
But auto-importing such a type won't work - I have to type the import manually.

Since go to definition works fine, I assume this is possible?

**Comment by edwin0cheng** [comment]
> Since go to definition works fine, I assume this is possible?

One of the reasons auto-import do not works in macro is, currently the [`world_symbol`](https://github.com/rust-analyzer/rust-analyzer/blob/e300e1e8d8f4de273d52fa62762ed14e8a7f96bb/crates/ra_ide_db/src/symbol_index.rs#L113) function does not search for macro expanded code.

**Comment by edwin0cheng** [comment]
And there is a FIXME in: 

https://github.com/rust-analyzer/rust-analyzer/blob/e300e1e8d8f4de273d52fa62762ed14e8a7f96bb/crates/ra_ide_db/src/symbol_index.rs#L108

**Comment by TimoFreiberg** [comment]
Alright, I've been looking at out how `goto_definition` expands macros...
I think we'd need to start collecting all `MacroCall`s in `symbol_index::to_symbol` (which currently ignores all `MacroCalls` that aren't `macro_rules!`).
Then expand them via `ra_hir_expand::db::macro_expand` somehow and then run `symbol_index::file_symbols` on the expanded macro again.

Sounds reasonable?

**Comment by edwin0cheng** [comment]
SGTM, and additionally we should use  [Semantics][1] API instead of calling `db::macro_expand` directly.

[1]: https://github.com/rust-analyzer/rust-analyzer/blob/0c927b458421c488323efbf742ce7017b6da29ab/crates/ra_hir/src/semantics.rs#L43

**Comment by TimoFreiberg** [comment]
Ok and I immediately hit a little roadblock in [`to_symbol`](https://github.com/rust-analyzer/rust-analyzer/blob/baf9fcc38ebd5a52b22fdf115a7475f9002058f6/crates/ra_ide_db/src/symbol_index.rs#L369):
`decl` returns `None` for a macro call like `generate_types!(Foo)` because there's no name in the child-AST.

It looks like the name is used for imports, either for the name of an item or for the path to the item.
So for the import path, we actually want no name and no path segment.
But the logic in `SymbolIndex::new` is based on everything having names.

I think I see why this wasn't implemented yet :)

**Comment by edwin0cheng** [comment]
I could imagine the following steps have to take to implement this feature :

1. Expand the macro call inside [to_symbol][1].
2. Search for the names inside expanded ast node. 
3. Remap the text range from MacroFile to the original file (Same as how goto-def works)

[1]: https://github.com/rust-analyzer/rust-analyzer/blob/baf9fcc38ebd5a52b22fdf115a7475f9002058f6/crates/ra_ide_db/src/symbol_index.rs#L369

**Comment by TimoFreiberg** [comment]
I'm stopping work on this for now, I have a WIP stage [here](https://github.com/TimoFreiberg/rust-analyzer/commit/db852805c805fe698be6762162a040894863fc9e).
I'm stuck at mapping the macroexpanded code to the macro call site.
Matklad and Florian Diebold mentioned in [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/Expanding.20macros.20in.20.60world_symbols.60) that it would make sense to start building the index from the HIR instead of from the AST instead, which would make these changes obsolete.

**Comment by flodiebold** [comment]
This works now, as far as I can see.
