### ISSUE TITLE
rename symbol doesn't work across files in same crate

### ISSUE THREAD

**Issue by ChrisJefferson** [rust-analyzer/rust-analyzer#3869]
Should "rename symbol" and "find all references" work across a crate?

If I try renaming `add` in the following code, it works fine (also renaming the occurrence in `main`. if I put `Q` and it's impl into another file `f.rs` and use `mod f` to include it into main and use `f::Q`, now "rename symbol" doesn't find references to `add` in `main.rs`.

```
pub struct Q {
    i: u64,
}

impl Q {
    pub fn add(&self) -> u64 {
        self.i
    }
}

fn main() {
    let q = Q{i:1};
    q.add();
}
```

**Comment by edwin0cheng** [comment]
Yeah, I remember I added a FIXME in about this bug:

https://github.com/rust-analyzer/rust-analyzer/blob/8a73a8937d67db97072a11a40f0c3ed963e18e1b/crates/ra_ide_db/src/search.rs#L128-L131

I think it is not hard to fix which we could use the module visibility to check whether a sub-module needs to be included.

**Comment by matklad** [comment]
should be fixed now.
