### ISSUE TITLE
"Implement missing members" doesn't handle default generic type parameters

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [rust-analyzer/rust-analyzer#3877]
To reproduce, invoke "Implement missing members" assist on the following program:
```rust
struct S;
impl PartialEq for S {}
```

Actual result:
```rust
impl PartialEq for S {
    fn eq(&self, other: &Rhs) -> std::primitive::bool { unimplemented!() }
}
```
This does not compile: "cannot find type \`Rhs\` in this scope".

Expected result:
```rust
impl PartialEq for S {
    fn eq(&self, other: &Self) -> std::primitive::bool { unimplemented!() }
}
```

Because `PartialEq<Rhs=Self>`.

-------------
rust-analyzer version: 2020-04-06 (c859a64)

**Comment by matklad** [comment]
Relevant bits of code:

* https://github.com/rust-analyzer/rust-analyzer/blob/b7e5d94bda362ffc21174a79aa0be113c3288e1e/crates/ra_assists/src/ast_transform.rs#L34-L38
* https://github.com/rust-analyzer/rust-analyzer/blob/b7e5d94bda362ffc21174a79aa0be113c3288e1e/crates/ra_assists/src/handlers/add_missing_impl_members.rs
