### ISSUE TITLE
Support textDocument/typeDefinition

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#388]
LSP has support for "Goto Type Definition Request" request. It is analogous to <kbd>Ctrl+Shift+B</kbd> shortcut in IntelliJ, and is a different spin on "Goto definition".

In usual "Goto definition", you find an indentifier at the cursor and move to the place where this identifier was defined.

In "Goto type definition", you find an indentifier *expression* at the cursor, figure out its *type*, and navigate to the definition of that *type*

**Comment by kjeremy** [comment]
We've supported this for awhile now. I think we can close.
