### ISSUE TITLE
`Self` span is incorrect

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#3887]
rust-analyzer version: unreleased (d89c189)

Maybe I do not understand something, but to me focusing on `Self` token should highlight it and other occurrences within a document, i.e., not the whole span (which is useless anyway, IMO):

![autogen-1586319620169](https://user-images.githubusercontent.com/3784017/78744347-81019100-798b-11ea-9d19-0bee4fb7c96a.gif)

**Comment by matklad** [comment]
Yup, this is a bug. In general, I'd say our handling of `self` and `Self` with respect to goto definition and friends is more broken than not.

**Comment by lnicola** [comment]
@0x7CFE this seems to work now, can you retest?

![image](https://user-images.githubusercontent.com/308347/105738831-23512c00-5f40-11eb-9aff-c143034e4576.png)

(Marking as `S-actionable`, if you look at this in the future and the OP hasn't answered, ping me so we can close it).

**Comment by 0x7CFE** [comment]
It still works kinda weird. Don't sure if that's the same bug or another one.

![substrate-1611640509810](https://user-images.githubusercontent.com/3784017/105806052-d4ee6c80-5fd5-11eb-9595-9f33f4aafe06.gif)
