### ISSUE TITLE
#[path = "xyz"] is failing

### ISSUE THREAD

**Issue by andre-richter** [rust-analyzer/rust-analyzer#3889]
Hi all,

since the latest update, `unresolved import` errors show up when using the path attribute. This worked before.

![image](https://user-images.githubusercontent.com/4130005/78752271-155ff980-7974-11ea-8401-1cc2a6cf56f9.png)

**Comment by matklad** [comment]
A minimal reproducible example would be of help here, we do have some simple tests for path attributes in the repository, and them seem to work.

**Comment by andre-richter** [comment]
Sure.

Let me know if this works for you:
```bash
git clone git@github.com:rust-embedded/rust-raspberrypi-OS-tutorials.git
cd rust-raspberrypi-OS-tutorials/02_runtime_init
code .
# navigate to src/cpu.rs 
```

**Comment by flodiebold** [comment]
We don't generate `unresolved import` errors, do we? :thinking: So I think these come from rustc?

**Comment by JoshMcguigan** [comment]
Opening the example posted by @andre-richter above, I can confirm this error is coming from rustc. There is a `cfg` item one line above where the original screenshot starts which I think it relevant.

```rust
#[cfg(target_arch = "aarch64")]                                           
#[path = "_arch/aarch64/cpu.rs"]
mod arch_cpu;
pub use arch_cpu::*;
```

I get the same error when running `cargo check` directly (while not on `aarch64`).

```
~/workspace/rust-raspberrypi-OS-tutorials/02_runtime_init master ·
$ cargo check
    Checking kernel v0.1.0 (/home/josh/workspace/rust-raspberrypi-OS-tutorials/02_runtime_init)
error[E0432]: unresolved import `arch_cpu`
  --> src/cpu.rs:10:9
   |
10 | pub use arch_cpu::*;
   |         ^^^^^^^^ use of undeclared type or module `arch_cpu`
```

**Comment by andre-richter** [comment]
I had hoped so. My attempt on it is here:

https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/blob/master/02_runtime_init/.vscode/settings.json

Any errors there? I suspected this works, since it only recently started failing.

**Comment by JoshMcguigan** [comment]
Ah yes, that is it. The settings names changed recently.

I believe you'll want `rust-analyzer.checkOnSave.allTargets` and `rust-analyzer.checkOnSave.extraArgs` now.

**Comment by andre-richter** [comment]
Thanks a lot for all your help!

I tried to rename those, but with the current rust-analyzer stable, it seems to have no effect.
If I update to nightly, the errors go away. But they also go away with the old config values. And even if some are missing. I am a bit confused at the moment.

But seeing that the next release might resolve this, I'll close for now.

In case it persists after next release, I'll reopen.
