### ISSUE TITLE
Semantic highlighting does not show for already opened editors

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#3890]
tldr:
![wasmtime-1586330362087](https://user-images.githubusercontent.com/3784017/78756067-5ec83d00-79a4-11ea-89fd-707b9ea8f1dc.gif)

VS Code was just opened. Newly opened files are highlighted immediately.

rust-analyzer version: unreleased (d89c189)

**Comment by bjorn3** [comment]
I haven't seen any semantic highlighting problems like this one in a long time.

**Comment by woody77** [comment]
Agreed, I'm not sure if it was a VSCode change or a change in the RA plug-in itself, but I haven't seen it recently either (and used to see this daily).
