### ISSUE TITLE
Compilation will fail when the type error is automatically deduced

### ISSUE THREAD

**Issue by YRainbbbb** [rust-analyzer/rust-analyzer#3891]
The example is when I use the gfx-hal library, I encountered the following situation：
```rust
    let (instance, surface, adapter) = {
        let instance = backend::Instance::create(APP_NAME, 1).expect("Backend not supported");
        let surface = unsafe {
            instance
                .create_surface(&window)
                .expect("Failed to create surface for window")
        };
        let adapter = instance.enumerate_adapters().remove(0);

        (instance, surface, adapter)
    };
```
The plugin deduces the type of surfae as ()，And the subsequent calls about the surface all showed errors, even when I directly performed cargo build in the terminal, there was an error.

**Comment by lnicola** [comment]
It's not exactly clear to me how a rust-analyzer type inference bug can cause cargo build to fail when run from a terminal. Can you prepare a repository showing the issue?

**Comment by YRainbbbb** [comment]
I describe it in more detail：
When I write this code on vscode，the first derivation goes like this:
`let surface:() = unsafe {
    instance.create_surface(&window).expect("Failed to create surface for window")
};`
In the subsequent code, there are error prompts for surface calls，But it's not a big deal. It usually runs normally directly on the terminal useing -cargo run- .
But when I use -cargo run- directly this time, the errors I get are consistent with the errors I get from derivation.
It wasn't until I commented out the above code, and then uncommented again, so that the derivation type was deduced correctly after refreshing.

**Comment by flodiebold** [comment]
If you actually write `let surface: ()`, that will of course give type errors. I don't see how that's related to rust-analyzer, though.
