### ISSUE TITLE
[Feature request] Hide obvious parameter name inlay hints

### ISSUE THREAD

**Issue by IceSentry** [rust-analyzer/rust-analyzer#3900]
Sometimes, parameter names are simply called `value`. I don't think it's necessary to show those hints since they don't add anything. 

For example

![image](https://user-images.githubusercontent.com/8348954/78829494-714a7280-79b4-11ea-8218-8f7e96df5b17.png)

Seeing the `value:` on each field really doesn't tell me anything that wasn't already obvious.

I'm wondering if it could be possible to have a list of words that could be removed from parameter names inlay hints. It could be a predefined list of words, but I wouldn't be surprised if a lot of people didn't like that. So having a list of user defined words is probably better.

I'd be interested in making a PR if you want. I might need some guidance to find where this is handled.

**Comment by matklad** [comment]
One specific case where we do similar filtering is here: https://github.com/rust-analyzer/rust-analyzer/blob/779555c1beac90f633c01a773558c4007c99c97f/crates/ra_ide/src/inlay_hints.rs#L248-L251.

It certainly can, and shod be generalized to to more cases.

It also obviously can be generalized to an be configurable, but have a very strong preference to not add config until we exhaust all other ways to detect obvious hints. The reason for that is that configs are the path of least resastance, but have a big accumulating cost.

**Comment by 0x7CFE** [comment]
In this particular case I would say that the following heuristic would probably work. 

Do not show hints if:
- The same method is chained more than once (only for builder pattern)
- Return type of several chained method remains the same (only for builder pattern)
- Several methods from the same `impl` block share the same parameter names and positions, like `checked_add`, `checked_sub`, etc. (Questionable)

**Comment by IceSentry** [comment]
@0x7CFE it's much harder to check if you are in a chained method that has been called multiple time than to just ignore words that are used for obvious parameter name., but I agree that if it's a builder pattern hiding the hints is probably a good heuristic.
