### ISSUE TITLE
Better trait missing items handling in vscode

### ISSUE THREAD

**Issue by cjhopman** [rust-analyzer/rust-analyzer#3904]
When a trait is missing multiple items, the first item in the vscode actions thing should be to add all of the missing items.

**Comment by matklad** [comment]
Just to clarify, you want to swap these two, right:

![image](https://user-images.githubusercontent.com/1711539/78871674-59243300-7a48-11ea-900b-cf4bf72e53c6.png)

? Fixing this now.

**Comment by cjhopman** [comment]
Swapping those two is good. But I had a different issue. I was getting suggestions to implement just one of the missing members at the top (and then the "Implement missing members" at the bottom). I'm not sure what triggered the individual items one and I can't reproduce it with a simple example.

I'll take a screenshot for suggestions like this next time (or if I see this one again)..

**Comment by cjhopman** [comment]
Ah, saw it again.

![Screen Shot 2020-04-09 at 6 58 41 PM](https://user-images.githubusercontent.com/943596/78955489-3c155180-7a94-11ea-965f-60b64010e98a.png)

Here's the trait being implemented:

```
#[async_trait]
pub trait HasBuildContext {
    async fn get_project_filesystem(self: &Arc<Self>) -> Arc<ProjectFilesystem>;

    async fn get_cell_resolver(self: &Arc<Self>) -> CellResolver;

    async fn get_legacy_rules(self: &Arc<Self>) -> Arc<Vec<String>>;

    async fn get_legacy_configs(self: &Arc<Self>) -> Arc<HashMap<CellName, LegacyBuckConfig>>;

    fn set_build_context(self: &Arc<Self>, fs: Arc<ProjectFilesystem>, cell_resolver: CellResolver);
}
```

And the implementation when it showed the error:

```

#[async_trait]
impl HasBuildContext for DiceCtx {
    async fn get_project_filesystem(self: &Arc<Self>) -> Arc<ProjectFilesystem> {
        self.compute(&BuildContextKey()).await.fs
    }

    async fn get_cell_resolver(self: &Arc<Self>) -> CellResolver {
        self.compute(&BuildContextKey()).await.cell_resolver
    }

    fn set_build_context(
        self: &Arc<Self>,
        fs: Arc<ProjectFilesystem>,
        cell_resolver: CellResolver,
    ) {
        self.changed_to(vec![(
            BuildContextKey(),
            BuildContext { fs, cell_resolver },
        )])
    }
}

```

**Comment by cjhopman** [comment]
Also, the first two items don't complete the same way (they use the signature after async_trait expansion), so I guess they're probably coming from some other source than the "implement missing items", in which case it's quite possible the suggestion in #3903 would resolve this, too.

**Comment by cjhopman** [comment]
Here's a simpler case where I hit it:

![Screen Shot 2020-04-10 at 11 54 55 AM](https://user-images.githubusercontent.com/943596/79015730-3e25f180-7b22-11ea-93a6-61699f02f64c.png)

**Comment by cjhopman** [comment]
I do prefer that the single item suggestion fills with `todo!()` rather than `unimplemented!()`
