### ISSUE TITLE
[feature request] Assist for turning a function to return `Result`

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#3907]
After reading the blog post withoutboats's [Ok-Wrapping][1] blog post, I wonder if IDE could help to reduce the typing in this situation. I could imagine we could add an assist that automatically swap a function return type to a `Result` and vice versa. 

[1]: https://boats.gitlab.io/blog/post/why-ok-wrapping/

**Comment by flodiebold** [comment]
Yes, I think a "make this function return `Result`" (/ `Option`) assist would be nice.

Also nice would be an assist that turns
```rust
Ok(match x {
  ... => { y }
})
```
into
```rust
match x {
  ... => { Ok(y) }
})
```
and vice versa (i.e. "pull call into each of the match arms" / "pull call out of match arms"), though ideally it'd be a bit smart about arms that diverge (i.e. return or panic), which we probably can't reliably do yet.

**Comment by matklad** [comment]
>Also nice would be an assist that turns

fwiw, I somewhat moderatly strongly feel that the best soln here is to "extract variable" the `match x {}`, which is already doable today. 

>and vice versa

We should have general "pull upwars" for `if cond { return } else { return }` and friends.

**Comment by bnjjj** [comment]
If it's possible I would like to make a PR to add an assist to swap to return type to Result and vice versa :) it's seems fun to write
