### ISSUE TITLE
[Question] Configure rustfmt using new params

### ISSUE THREAD

**Issue by jatsrt** [rust-analyzer/rust-analyzer#3916]
Previously we were able to add `+nightly` to the format args.  Now there are two new options that change this behavior.  

`rust-analyzer.rustfmt.extraArgs` allows you to add params to the end of the command, and will not allow "nightly"

`rust-analyzer.rustfmt.overrideCommand` allows a full override of the command so in theory you could run it as `rustup run nightly -- rustfmt --`, but I cannot get this to work.  

Any suggestions would be great.

**Comment by jatsrt** [comment]
And I answered my own question, leaving this here for anyone that needs it...

```yaml
"rust-analyzer.rustfmt.overrideCommand": [
        "rustup",
        "run",
        "nightly",
        "--",
        "rustfmt",
        "--edition",
        "2018",
        "--"
    ],
```

**Comment by jhpratt** [comment]
Using `+nightly` as an extra argument works for me.

**Comment by jatsrt** [comment]
@jhpratt interesting, must have been an update to get this working again, it was definitely not working previously

**Comment by jatsrt** [comment]
Looks like it was a bug in `rustfmt` not honoring the `+nightly`

**Comment by willmcpherson2** [comment]
For those using `init.lua`, you can try this:

```lua
lspconfig.rust_analyzer.setup {
    settings = {
        ["rust-analyzer"] = {
            rustfmt = {
                extraArgs = { "+nightly", },
            },
        }
    }
}
```

**Comment by paulrberg** [comment]
For future reference, here's a shorter alternative to @jatsrt's solution:

```json
"rust-analyzer.rustfmt.extraArgs": ["+nightly"],
```
