### ISSUE TITLE
Implement type inference for enum variants

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#392]
We need to handle enum variants in our HIR and type inference. This involves the following steps:
 - add a `DefKind::EnumVariant` and `Def::EnumVariant`
 - in `adt.rs`, add a `EnumVariant` that works similarly to `Struct` and `Enum`, i.e. it's a wrapper around a `DefId` that lets you query the name and `VariantData` for the variant
 - `Module::resolve_path` should resolve enum variants to their `DefId`
 - in `ty.rs`, `resolve_variant` should handle enum variants of the struct flavor, and `type_for_def` should handle unit variants.
 - finally, add a test in `ty/tests.rs` that checks that constructing enum variants works, e.g.
```rust
enum E {
  V1 { field: u32 },
  V2
}
fn test() {
  E::V1 { field: 1 };
  E::V2;
}
```

We don't currently handle tuple structs, so I'd suggest dealing with that and tuple enum variants separately.

Once we've got HIR and path resolution for enum variants, we can also implement handling them in patterns.

**Comment by marcusklaas** [comment]
I'm trying my hand at this issue.
