### ISSUE TITLE
Wrong type analysis when returning function from match or if-else block.

### ISSUE THREAD

**Issue by NichtsVonChaos** [rust-analyzer/rust-analyzer#3929]
Let's write two function:
```rust
fn test1() -> i32 {
    0
}

fn test2() -> i32 {
    1
}
```
Then try to use it as return-value of match block or if-else block:
```rust
let func_ptr = match Some(5) {
    Some(5) => test1,
    _ => test2,
};
```
or
```rust
let func_ptr = if true {
    test1
} else {
    test2
};
```
RA will tell that the type of `func_ptr` is `fn test2() -> i32`, though it is `fn test1() -> i32` actually in both of two cases.

**Comment by flodiebold** [comment]
We now correctly infer this as `fn() -> i32`.
