### ISSUE TITLE
SyntaxNodePtr::to_node leads to accidently quadratic behavior

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3934]
This is a pretty hot operation, but it is linear. So, for example, when we are

* collecting lang items
* and looking at attributes of items
* and looking at sources of items

in a big file, we get O(N^2) behavior. 

Originally I wanted to fix this with using binary search for finding the relevant child. This, however, requires changes to rowan -- specifically, we'd need to remember start offsets of children in green nodes to make binary search work. 

This is not a bad solution, however, I'd like to test something even better in theory -- using paths and not text ranges to represnt SyntaxPtr. I *think* if we use var-length encoding for paths, this might fly without too much extra allocations.

**Comment by kjeremy** [comment]
So to understand... `SyntaxNodePtr::to_mode` itself is O(n) but we use it in such a way (ie multiple times) to create O(n^2) behavior?

**Comment by matklad** [comment]
Yup.

**Comment by matklad** [comment]
Some further thouhtgs:

Looks like there's generally two approaches possible:

* first, we can add some extra info to green nodes to allow for binary search of children by offset/node number. This inflates green nodes, but allows us to keep the SyntaxNodePtr small and `Copy` (potentially even fitting it into a single `u32`)

* second, we can use varint-encoded paths as SyntaxNodePtrs. They are no longer `Copy`, and probably a little larger (but hopefully not too much, if we add some nice compressing scheme on top), but the GreenNodes remain as smoll as they are today, and dereferencing a pointer is faster, as we avoid even the binary search.

**Comment by matklad** [comment]
Also, I've exposed quite a lot of impl details out of current `SyntaxNodePtr`, because "@matklad form the future will deal with it". Not really helpful, @matklad from the past!

**Comment by matklad** [comment]
>but the GreenNodes remain as smoll as they are today

And this unfortunately doesn't work, as, even if we know the child index, we can't use it to compute the offset...

**Comment by Veetaha** [comment]
What about beginning with a `SyntaxNodeIndex` for sysroot and crates.io ?

**Comment by Veetaha** [comment]
Another thing I am thinking of is somehow making use of the syntax node's reference counter `Rc<NodeData>`. Maybe using an enum:
```rust
enum SyntaxNodePtr {
    text_range: TextRange,
    kind: Kind
    cache: Weak<SyntaxNode>
}
```
If I am not mistaken we do not intern red nodes, thus making use of the weak refcount we can reference the node directly and if it was invalidated (i.e. dropped) we proceed with the linear search.

**Comment by matklad** [comment]
Not sure how the Index would work here. Weak references are an interesting
idea, but probably won't help for two reasons:

* the problem is not that we repeatedly lookup the same node
* even if the green tree for a file is in memory, the read nodes are
created and teared down at roughly the function scope, the weaks would
basically be null always

**Comment by matklad** [comment]
Update:

I've made a prototype implementation in rowan. In indeed speeds up the currently ignored test to a linear behavior. The anslysis-stats perf difference is withing the margin of error.

**Comment by Veetaha** [comment]
@matklad show me the code, how did you optimize it?

**Comment by matklad** [comment]
https://github.com/rust-analyzer/rowan/tree/binsearch

**Comment by matklad** [comment]
Another interesting option is to introduce a `TRANSPARENT` `SyntaxKind`, so that a node with many children represented as a node with fewer transparent children. In effect, this is basically using existing tree-structure to turn long lists into trees. 

Interestingly, that's what various fancy incremental algorithms are doing as well. You can't make parsing really incremental if you store `Item *` in an array, which needs linear time for an update. 

I still lean towards just storing offsets though.
