### ISSUE TITLE
Should standard attributes be handled by RA?

### ISSUE THREAD

**Issue by jrvidal** [rust-analyzer/rust-analyzer#3941]
This is sort of an open question/moonshot but I'm not sure whether there is something in the works for this.

By "handling attributes" I mean that the standard compiler attributes are understood by RA and we get:
* Autocompletion when writing an attribute.
* Some form of "Go To Definition" that would take you... to the reference?

**Comment by matklad** [comment]
Yes, they should be supported! Not sure about goto def, but, eg, hover can def link to the docs.
