### ISSUE TITLE
Autoimport adds import to `pub use` items

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#3946]
If there's a fitting import that is `pub`, autoimport will add the new import to that. I think that's surprising and usually not desirable :sweat_smile:

**Comment by matklad** [comment]
hard for the same reason: https://github.com/rust-analyzer/rust-analyzer/issues/3831#issuecomment-608367659

**Comment by Veykril** [comment]
This has also been fixed by #5935.
