### ISSUE TITLE
Tree-based import editing infrastructure

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#3947]
Meta issue for all issues that need to change imports. 

The problem is that our current implementation is text-based, so it's quite hard to extend it with custom logic. The plan is to transition it to tree-based model, but handling nested impls is surprisingly painful. Like, it's not rocket science, you "just" need to write the code to wrestle syntax trees but there's a huge amount of case handling involved (or I am not smart enough to see a simpler solution). 

What we ideally want is something like this:

```rust
pub fn insert_use(where_: SyntaxNode, path: ModPath) -> SyntaxNode {
    let use_item = make::use_item(path);

    let use_scope: UseScope = UseScope::cast(where_).unwrap();
    for existing_use in use_scope.imports() {
        if let Some(merged) = try_merge_two_imports(existing_use, &use_item) {
            return algo::replace_children(where_, existing_use, merged);
        }
    }

    let group: ImportGroup = ImportGroup::new(path);
    let insert_position: InsertPosition<SyntaxElement> = find_insert_position(&use_scope, group);

    algo::insert_children(&where_, insert_position, vec![use_item].into_iter())
}

enum UseScope {
    SourceFile(ast::SourceFile),
    ItemList(ast::ItemList),
}

impl UseScope {
    fn imports(&self) -> AstChildren<ast::UseItem> {
        todo!()
    }
}

fn try_merge_two_imports(lhs: &ast::UseItem, rhs: &ast::UseItem) -> Option<ast::UseItem> {
    todo!()
}

enum ImportGroup {
    Std,
    ExternCrate,
    ThisCrate,
    ThisModule,
    SuperModule,
}

fn find_insert_position(scope: &UseScope, group: ImportGroup) -> InsertPosition<SyntaxElement> {
    todo!()
}
```

in `assists/utils/insert_use.rs`. My current crack at this is [here](https://github.com/matklad/rust-analyzer/commit/9335f0935023f9525f389e6e36181cd5678db1c1), but it is incomplete, and it's unlikely that I'll get back to it soon. SOme useful code can also be salvaged from the `merge_imports` assist. 

The list of issues depending on this:

- [ ] https://github.com/rust-analyzer/rust-analyzer/issues/3301
- [ ] https://github.com/rust-analyzer/rust-analyzer/issues/3831
- [ ] https://github.com/rust-analyzer/rust-analyzer/issues/3946
- [ ] #5795 
- [ ] I've noticed that, when importing `ast::Foo`, we get `use ra_syntax::{ast, ..}; use ast::Foo` and not `use ra_syntax::{ast::{self, Foo}, ...}`.

This is a somewhat good first issue, as the API surface here is small, and the desired interface is more or less clear, it's "only" the implementation that is tricky.

**Comment by matklad** [comment]
A good first step here is to take a look at what IntelliJ is doing :-)

**Comment by Veykril** [comment]
I'd like to have a try at this in the upcoming days 😄

**Comment by matklad** [comment]
@Veykril go for it!

**Comment by matklad** [comment]
@Veykril this is completed, right? Or are there some more things you want to tackle here?

**Comment by Veykril** [comment]
The last point in the checklist
>  I've noticed that, when importing ast::Foo, we get use ra_syntax::{ast, ..}; use ast::Foo and not use ra_syntax::{ast::{self, Foo}, ...}.
is technically not done yet. This would require to go through the entire import trees to search for the module If I'm not mistaken, will probably take a look at that sometime later. Otherwise everything from that list should be done.

**Comment by matklad** [comment]
Aha, then I think we should keep this closed!
