### ISSUE TITLE
Use statement conflates module and function with the same name

### ISSUE THREAD

**Issue by goffrie** [rust-analyzer/rust-analyzer#3970]
![image](https://user-images.githubusercontent.com/1240398/79172725-590a9700-7daa-11ea-912c-03deb8eb0d27.png)
Here `warp::reply` refers to both a function and a module. It is being used as a module in this case but hovering/semantic highlighting think that it is the function.

**Comment by goffrie** [comment]
It seems that the problem is that `SourceAnalyzer::resolve_path` just forwards to `resolve_hir_path`, which does not know the namespace of the path that it is trying to resolve and so preferentially takes the function (from `resolve_path_in_value_ns_fully`), over the module (from `resolve_module_path_in_items`). The opposite problem happens too:

```
enum foo {}
fn foo() {}
fn test() {
    foo();
}
```
renders as 
![image](https://user-images.githubusercontent.com/1240398/79176446-15695a80-7db5-11ea-9b8f-7e47262b0006.png)

indicating that the resolution of `foo` is taking the enum (resolved via `resolve_path_in_type_ns_fully`) over the function.

**Comment by goffrie** [comment]
I can imagine fixing this by making `SourceAnalyzer::resolve_path` infer the namespace of the path from the AST node (by looking at its parent), but I'm not sure if that's too "magical."

**Comment by matklad** [comment]
I think this is an instance of https://github.com/rust-analyzer/rust-analyzer/issues/3407 which is a rather big philosophical problem. 

In this particular instance, I think the function which is buggy is `Semantics::resolve_path(path: &ast::Path)`. It receives an `ast::Path`, so it knows that it is a part of use item and should be resolved as such. 

Fixing it by looking at the parent seems like the right approach at the moment.
