### ISSUE TITLE
Incorrectly shows an error for matching an enum without variants

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#3974]
hyper contains a type `enum Never {}`. When this is matched against, RA (0.2.135) shows an error:

![Screen Shot 2020-04-14 at 09 32 37](https://user-images.githubusercontent.com/158471/79197912-e2fe4280-7e32-11ea-9bbc-e308ede5fc36.png)

In contrast, rustc does not show an error.

**Comment by JoshMcguigan** [comment]
Thanks for the report, I'll take a look at this.
