### ISSUE TITLE
Builtin primitive types are not abbreviated in, say, "Implement missing members" assist

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [rust-analyzer/rust-analyzer#3977]
rust-analyzer version: 2020-04-13 (c388130)
To reproduce, invoke "Implement missing members" assist on the following program:
```rust
trait Foo {
    fn f(x: u32);
}
struct S;
impl Foo for S {}
```

Expected result:
```rust
impl Foo for S {
    fn f(x: u32) { todo!() }
}
```

Actual result:
```rust
impl Foo for S {
    fn f(x: std::primitive::u32) { todo!() }
}
```

If I explicitly add the `use std::primitive::u32` use declaration, the assist will work as expected. But this use declaration is already implied, so it should work without it too.

**Comment by flodiebold** [comment]
Huh, is that in nightly? I can't see `std::primitive` on stable...

**Comment by Vlad-Shcherbina** [comment]
Yes.
```
> rustc --version --verbose
rustc 1.44.0-nightly (b543afca9 2020-04-05)
binary: rustc
commit-hash: b543afca9b90ad6e4689b6d613ab51f9d3ba15e7
commit-date: 2020-04-05
host: x86_64-pc-windows-msvc
release: 1.44.0-nightly
LLVM version: 9.0
```

**Comment by matklad** [comment]
I think this is actually in Beta already.

**Comment by flodiebold** [comment]
I think we need to teach `find_path` that the builtin types are always in scope :thinking:
