### ISSUE TITLE
Invalid renames should say why they failed

### ISSUE THREAD

**Issue by DianaNites** [rust-analyzer/rust-analyzer#3981]
Invalid renames are already rejected, but if possible they should say why, too.

Currently, for VSCode at least, an info box saying "No result." pops up, and thats it. I was unintentionally trying to rename something to a keyword, but it took a few minutes to figure out that I was doing something wrong, not rust-analyzer.

**Comment by matklad** [comment]
Don't know off hand how this should be handled according to the protocol, but the entry point into this functionality is here:

https://github.com/rust-analyzer/rust-analyzer/blob/b495e56b0d3f7a72494d002a69440563e8394574/crates/rust-analyzer/src/main_loop/handlers.rs#L496-L536
