### ISSUE TITLE
Macro expand doesn't show documentation

### ISSUE THREAD

**Issue by DianaNites** [rust-analyzer/rust-analyzer#3984]
Rust-analyzer is able to recognize and highlight the function `$name`, but not it's documentation.

```rust
macro_rules! example {
    ($name:ident) => {
        /// Doesn't show
        fn $name() {}
    };
}

example! {amazing}
```

**Comment by edwin0cheng** [comment]
We still don’t support goto def in call site

**Comment by DianaNites** [comment]
Not sure what that means, but goto definition on `amazing()` will jump to `example! {amazing}`?

**Comment by edwin0cheng** [comment]
Okay, I understand what happen now.

It is because when we expand doc-comment (i.e. `/// Doesn't show`), we sugared it to `#[doc = " Doesn't show"]` , however, we still do not support attribute-style doc comments (#3180).

**Comment by edwin0cheng** [comment]
Related: #3182 describes how to resolve this bug if you are interested.
