### ISSUE TITLE
Incorrect implementation of type shadowing

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#3988]
I'm getting an incorrect error from RA (0.2.135). The relevant code is here:

https://github.com/djc/quinn/blob/92123dc0c54690cf805fb58d1c4204ab9a03fa83/quinn-proto/src/connection.rs#L1129

The issue appears to be that the `use` statement just before the match brings a variant (`Datagram`) in scope that is the same as a [module-level imported](https://github.com/djc/quinn/blob/92123dc0c54690cf805fb58d1c4204ab9a03fa83/quinn-proto/src/connection.rs#L20) type `Datagram`. In this case, clearly rustc has the local import shadowing the global one, whereas RA apparently does not.

![Screen Shot 2020-04-16 at 11 45 47](https://user-images.githubusercontent.com/158471/79441682-d404c500-7fd7-11ea-8ea5-393babcd9114.png)

**Comment by flodiebold** [comment]
It's not so much a problem with shadowing as [local imports just not being supported yet](1165).

**Comment by djc** [comment]
Ah, I suppose this can be closed as a duplicate, then.
