### ISSUE TITLE
Snippet completion deletes preceding characters (LanguageClient-neovim, neosnippet)

### ISSUE THREAD

**Issue by justinas** [rust-analyzer/rust-analyzer#3991]
Hi!

I am not sure whether this is a problem with rust-analyzer or other parts of my setup, but I could not reproduce this issue with `rls` or other language servers (e.g. `pyls`) even though they use snippets.

After completing the method/function snippet, rust-analyzer seems to delete several preceding characters on the same line. Please see the following asciinema recording for a demonstration.

[![asciicast](https://asciinema.org/a/v9vGCIrsz4h0sOknPGGcFP0rm.svg)](https://asciinema.org/a/v9vGCIrsz4h0sOknPGGcFP0rm)

Minimized .vimrc:

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
set clipboard=unnamedplus

filetype off
call plug#begin('~/.vim/plugged')
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    Plug 'autozimu/LanguageClient-neovim', { 'branch': 'next', 'do': 'bash install.sh' }
    Plug 'Shougo/neosnippet.vim'
call plug#end()
filetype plugin indent on
syntax on

" Cycle on TAB
inoremap <silent><expr> <S-TAB> pumvisible() ? "\<C-p>" : "\<TAB>"
imap <silent><expr> <TAB>
     \ pumvisible()
     \ ? "\<C-n>"
     \ : neosnippet#jumpable()
     \ ? "\<Plug>(neosnippet_jump)"
     \ : "\<TAB>"

" Complete on CR
imap <silent><expr> <CR>
     \ pumvisible()
     \ ? "\<C-y>"
     \ : "\<CR>"

let g:deoplete#enable_at_startup = 1

let g:LanguageClient_serverCommands = {
    "\ 'rust': ['rustup', 'run', 'stable', 'rls'],
    \ 'rust': ['rustup', 'run', 'stable', 'rust-analyzer'],
    \ }
let g:LanguageClient_signatureHelpOnCompleteDone = 0 " does not work well yet

let g:neosnippet#disable_runtime_snippets = {
    \ '_' : 1
    \ }
let g:neosnippet#enable_complete_done = 1
```

Stack:
```
neovim 0.5.0+ubuntu1+git202004152112-e8269a3-00e710e-fc1b10a~ubuntu18.04.1
rust-analyzer c82e769
```

Newest vim plugin versions.

Would be very thankful for any help as I have been trying to debug this for days.

**Comment by justinas** [comment]
By the way, here is what happens if there are non-whitespace characters, e.g. another statement on the same line.

[![asciicast](https://asciinema.org/a/vclCQtLDM3AFVYHymKym6qSSd.svg)](https://asciinema.org/a/vclCQtLDM3AFVYHymKym6qSSd)

**Comment by justinas** [comment]
So I had the time to dig a bit into `neosnippet`. [This seems to be the code](https://github.com/Shougo/neosnippet.vim/blob/9f108b30a35e47f2705ffcb92967cfed51464455/autoload/neosnippet/view.vim#L89) that replaces the entire current line (!) with the snippet.

Using `rls`, echoing `snippet_lines[0]` snippet gives:
```
    _foo.bar(<`1:baz: i32`>, <`2:quux: usize`>)
```
That is the snippet, including everything that comes before it on the same line, as well as leading indentation. `pyls` acts the same way, as does `clangd`.

`rust-analyzer`, however, echoes only this:

```
bar(<`1:baz`>, <`2:quux`>)<`0`>
```

Will try to dig deeper to find where `snippet_lines` comes from.

**Comment by justinas** [comment]
Ah yes of course!
```
let snippet_lines[0] = a:cur_text . snippet_lines[0]
```

[The snippet line is prepended with the current text](https://github.com/Shougo/neosnippet.vim/blob/9f108b30a35e47f2705ffcb92967cfed51464455/autoload/neosnippet/view.vim#L71). So `a:cur_text` is empty when `rust-analyzer` is used for some reason.

**Comment by justinas** [comment]
Now investigating [`get_user_data`](https://github.com/Shougo/neosnippet.vim/blob/9f108b30a35e47f2705ffcb92967cfed51464455/autoload/neosnippet/mappings.vim#L178)

Substituting
```viml
    let cur_text = cur_text[: -1-len(snippet_trigger)]
```
with
```viml
    echom 'Original cur_text: ' . cur_text
    echom 'Snippet trigger: ' . snippet_trigger
    let cur_text = cur_text[: -1-len(snippet_trigger)]
    echom 'cur_text after slicing: ' . cur_text
```

Gives me for RLS:
```
Original cur_text:     _foo.bar(${1:baz: i32}, ${2:quux: usize})
Snippet trigger: bar(${1:baz: i32}, ${2:quux: usize})
cur_text after slicing:     _foo.
```

and for rust-analyzer:
```
Original cur_text:     _foo.bar(…)
Snippet trigger: bar(${1:baz}, ${2:quux})$0
cur_text after slicing:
```

I suspect the mismatch where cur_text is completed with the ellipsis inside instead of the entire snippet. This is the behavior demonstrated in my original recordings: cycling to the desired suggestion will first insert the placeholder `.bar(…)` and then only on a commit character (Enter, semicolon, etc.) will expand the snippet.

**Comment by justinas** [comment]
https://github.com/Shougo/neosnippet.vim/blob/3c84bf6969df5b0ee7c53d62313dd3fa2cfb3622/autoload/neosnippet/mappings.vim#L188-L194

Here RA takes the first branch, i.e. one where `textEdit` is used. RLS takes the second one. There is even an issue that introduced this code and it mentions RA https://github.com/Shougo/neosnippet.vim/issues/487

So my current understanding of the issue boils down to: LanguageClient-neovim / deoplete insert the short version of the snippet (with the ellipsis), but neosnippet then tries to delete as many characters as the full snippet, thus deleting too much.

---

As an aside, when I turn off the snippet support (i.e. `let g:neosnippet#enable_complete_done = 0`), what is autocompleted is still the ellipsized form: `_foo.bar(…);`. Not terribly useful, as you have to go back into the parentheses, delete the ellipsis and replace that with your arguments. Would this be considered a bug?

In this case (no snippet support in editor) clangd gives zero shits and inserts the snippet anyway, meanwhile `pyls` will only complete the function name, but not the parentheses or the argument list in any way.

**Comment by justinas** [comment]
I messed around some more with vim completion and neosnippet and produced a PR for neosnippet that seems to fix the issue. Let's see what Shougo thinks. https://github.com/Shougo/neosnippet.vim/pull/490

**Comment by Shougo** [comment]
It seems not rust-analyzer's issue.

**Comment by justinas** [comment]
As the fix has been merged to neosnippet, I am closing this. Thanks everyone.
