### ISSUE TITLE
Type inference analysis confused by use in scope

### ISSUE THREAD

**Issue by CAD97** [rust-analyzer/rust-analyzer#3997]
(Sorry for the not-super-minimized rerpo, I ran into this while following the [gfx-hal intro](https://www.falseidolfactory.com/2020/04/01/intro-to-gfx-hal-part-1-drawing-a-triangle.html).)

### Cargo.toml

```toml
[package]
name = "gfx-hal-tutorials"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
winit = "0.22.0"
```

### main.rs (`use` at root scope)

```rust
use winit::dpi::{LogicalSize, PhysicalSize};
const WINDOW_SIZE: [u32; 2] = [512, 512];

fn main() {
    let event_loop = winit::event_loop::EventLoop::new();

    let (logical_window_size, physical_window_size) = {
        let dpi = event_loop.primary_monitor().scale_factor();
        let logical: LogicalSize<u32> = WINDOW_SIZE.into();
        let physical: PhysicalSize<u32> = logical.to_physical(dpi);

        (logical, physical)
    };
}
```

![image](https://user-images.githubusercontent.com/5992217/79506612-4b504e00-8004-11ea-871c-c487ddc5f506.png)

### main.rs (scoped `use`)

```rust
const WINDOW_SIZE: [u32; 2] = [512, 512];

fn main() {
    use winit::dpi::{LogicalSize, PhysicalSize};
    let event_loop = winit::event_loop::EventLoop::new();

    let (logical_window_size, physical_window_size) = {
        let dpi = event_loop.primary_monitor().scale_factor();
        let logical: LogicalSize<u32> = WINDOW_SIZE.into();
        let physical: PhysicalSize<u32> = logical.to_physical(dpi);

        (logical, physical)
    };
}
```

![image](https://user-images.githubusercontent.com/5992217/79506672-64f19580-8004-11ea-9cba-662b958968cf.png)

This second form infers the _wrong_ type for `logical_window_size`, and no type for `physical_window_size`.

**Comment by edwin0cheng** [comment]
[local imports is still not being supported yet] ( local imports just not being supported yet.)

**Comment by CAD97** [comment]
An interesting side-effect is r-a pulling what appears to be a completely random type that satisfies `[u32; 2] as Into<$0>` for `logical_window_size` here.

**Comment by flodiebold** [comment]
I think that may be related to a bug where Chalk nondeterministically returns a definite result when it shouldn't. Does it still happen in latest RA?

**Comment by lnicola** [comment]
![image](https://user-images.githubusercontent.com/308347/79549498-ba2eb500-809f-11ea-866d-626006ec660f.png)

They show up as unknown for me.

**Comment by flodiebold** [comment]
Let's close this since we have #1165 for local imports and the weird inference is fixed.
