### ISSUE TITLE
Correct identifier lexing

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#4]
Rust uses `_` and XID_Start, XID_Continue to define identifiers. We need to add lexer test for some edge cases with these classes.

**Comment by mystor** [comment]
Let's just depend on https://crates.io/crates/unicode-xid for now - that makes sure we don't get it wrong.

**Comment by matklad** [comment]
@mystor we already do that: https://github.com/matklad/libsyntax2/blob/master/Cargo.toml#L8, however, we don’t have thorough tests for this. While I am pretty sure that the crate is correct, I think it is still important to have independent tests for this :)

**Comment by theotherphil** [comment]
Is this still required now that this crate is using the rustc lexer?

(Sorry if all the 'is this done'/'this is done' comments on old issues are annoying - I'm looking through open issues to try and find something easy to work on.)

**Comment by lnicola** [comment]
@theotherphil maybe you want to try https://github.com/rust-analyzer/rust-analyzer/issues/1592?

**Comment by theotherphil** [comment]
Thanks for the suggestion - I’ve started work on another couple of issues, but I’ll have a look at that one if it’s still open by the time I’m done with these.

**Comment by matklad** [comment]
yeah, this can be just closed now!
