### ISSUE TITLE
"Missing Match arm" error caused by empty match on empty enum

### ISSUE THREAD

**Issue by mikeyhew** [rust-analyzer/rust-analyzer#4000]
This is a common pattern, matching on an empty enum to show the compiler that the code is unreachable, and rust-analyzer is reporting an error unnecessarily.

![Screen Shot 2020-04-17 at 1 14 44 AM](https://user-images.githubusercontent.com/6751033/79534551-e10dcc80-8048-11ea-9930-322b54522741.png)

**Comment by edwin0cheng** [comment]
It should be fixed in master by #3979

**Comment by mikeyhew** [comment]
Thanks! I don't know why, but that one didn't come up when I did a search for existing issues. Closing since this is both a duplicate and has been fixed.
