### ISSUE TITLE
"Expand macros" command for custom derives

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#4005]

**Comment by matklad** [comment]
Yes please!

**Comment by 0x7CFE** [comment]
I can imagine two options here:

- expand macro in the active editor
- peek expansion in a popup editor

**Comment by TheAifam5** [comment]
What about use cargo-expand ?

**Comment by mexus** [comment]
Seems like the feature has been already implemented, hasn't it?

That's what I've got when expanded an invocation of a procedural macro

![image](https://user-images.githubusercontent.com/3609357/103227814-5b188400-4940-11eb-8c29-154a1d41482f.png)

Seems like a perfect expansion, or am I missing something? :)

**Comment by lnicola** [comment]
@mexus cool!

It still doesn't work for custom derives, though, maybe it's worth opening a different issue.
