### ISSUE TITLE
Ignore leading underscores when deciding whether to show inlay hints

### ISSUE THREAD

**Issue by Diggsey** [rust-analyzer/rust-analyzer#4017]
![image](https://user-images.githubusercontent.com/451321/79590796-7c498500-80cf-11ea-90bc-28446af4ce29.png)

**Comment by matklad** [comment]
This should be fixed here: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_ide/src/inlay_hints.rs#L256-L259
