### ISSUE TITLE
Implement async blocks

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#4018]
We don't currently handle async blocks correctly:
```rust
let x = async { 1 }.await;
```
Basically, we just ignore the `async` modifier at the moment. We need to:
 - add the information whether the block is `async` to [`Expr::Block`](https://github.com/rust-analyzer/rust-analyzer/blob/690a0b249eee6537953350be28a0ca11fa96b12a/crates/ra_hir_def/src/expr.rs#L52-L55) and set this during [lowering](https://github.com/rust-analyzer/rust-analyzer/blob/690a0b249eee6537953350be28a0ca11fa96b12a/crates/ra_hir_def/src/body/lower.rs#L467) (this might need some adaptation to ast_src.rs and maybe even the parser to get the async token)
 - adapt [`infer_block`](https://github.com/rust-analyzer/rust-analyzer/blob/690a0b249eee6537953350be28a0ca11fa96b12a/crates/ra_hir_ty/src/infer/expr.rs#L521) to wrap the result in an `impl Future` if the block is async. This requires impl trait support, which we don't have at the moment but should be ready in Chalk soon.

**Comment by bnjjj** [comment]
Is the integration of Chalk is ready now ? Then is it possible to go ahead with this issue ? If so I will be happy to contribute to this issue :)

**Comment by flodiebold** [comment]
No, I was still waiting for https://github.com/rust-lang/chalk/pull/402 to do that.

**Comment by sluongng** [comment]
https://github.com/rust-lang/chalk/pull/464 has been merged, which replaced https://github.com/rust-lang/chalk/pull/402

**Comment by Veetaha** [comment]
Small update:
the issue comment is a bit outdated, `async` keyword token  is already available in `ast` with `EffectBlock`
https://github.com/rust-analyzer/rust-analyzer/blob/7ddc3b468acc82192a665cdaa5b237167524f834/crates/ra_syntax/src/ast/generated/nodes.rs#L902-L927

**Comment by flodiebold** [comment]
Actually after thinking about this I'm not sure whether we should use impl Trait for this; the actually correct way would be introducing generator types... I wouldn't want to implement the full desugaring to generators, but maybe using a generator type as the type of the async block would work nonetheless :thinking:

**Comment by sluongng** [comment]
@flodiebold could you please clarify a bit more on what is the path forward/blockers for this?

**Comment by detrumi** [comment]
> Actually after thinking about this I'm not sure whether we should use impl Trait for this; the actually correct way would be introducing generator types... I wouldn't want to implement the full desugaring to generators, but maybe using a generator type as the type of the async block would work nonetheless thinking

Note that generators [aren't implemented yet](https://rust-lang.github.io/chalk/book/clauses/well_known_traits.html#current-state) in chalk, so it would probably still be blocked

**Comment by flodiebold** [comment]
We don't really need Chalk to implement them, presumably Chalk wouldn't provide the `Future` implementation anyway. On the other hand I do want to get rid of our builtin impls...

**Comment by FilipAndersson245** [comment]
Any updates on this issue?
