### ISSUE TITLE
Extend selection inside a string literal should select a word first

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#402]
See https://github.com/rust-analyzer/rust-analyzer/issues/88 (fixed in See https://github.com/rust-analyzer/rust-analyzer/pull/94) which is exactly the same issue, but for comments. 

In other words,for

`let x = "foo bar b<cursor is here>az quxx"`

we select an entire string literal with extend selection. We should start with just baz.

The relevant code and tests are here:

https://github.com/rust-analyzer/rust-analyzer/blob/e4ffd7b31780b1f2ac6dcb731566b583bf562647/crates/ra_analysis/src/extend_selection.rs

**Comment by gfreezy** [comment]
i will look at it

**Comment by gfreezy** [comment]
expand selection works fine for string literal

**Comment by matklad** [comment]
Hm, does not work for me as expected:

![image](https://user-images.githubusercontent.com/1711539/50597250-dbbe5a00-0eb7-11e9-896d-64d9cc80aae7.png)

![image](https://user-images.githubusercontent.com/1711539/50597255-e4af2b80-0eb7-11e9-840d-5123b727f192.png)

![image](https://user-images.githubusercontent.com/1711539/50597267-ee389380-0eb7-11e9-84c9-47dee3cc1509.png)


It should select only `bar`, not the entire string literal.
