### ISSUE TITLE
VS Code and Rust (rls) and rust-analyzer ?

### ISSUE THREAD

**Issue by yuribudilov** [rust-analyzer/rust-analyzer#4024]
Hello everyone. 
I was certain this has been asked before but unable to find it. 
Apologies if I missed anything.
This is from Dec 2019: PSA: disable the Rust (rls) extension to avoid duplicate hover output #2573

I am using VS Code (current version, 1.44.2 March 2020) and using most recent Rust (rls) and rust-analyzer extensions for VS Code.

Should I disable or even uninstall the Rust(rls) VS-Code extension when I am using rust-analyzer extension or should I have both of them enabled concurrently in VS Code? 

Do they interfere with each other or complementary ? What features would be missing if I disabled Rust(rls) extension?

If this is documented, please provide a link.

Thank you very much.

**Comment by kjeremy** [comment]
I think it's in the readme somewhere. Just disable or uninstall RLS in vscode.
