### ISSUE TITLE
Ambiguity for the module path with the same name as a function declaration

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#4030]
Reproduction:
```rust
mod foo {
    pub(crate) fn bar() {}
}

fn foo() {}

fn main() {
    // foo symbol is analyzed as a function here
    foo::bar();
}
```
![Screenshot from 2020-04-18 15-43-26](https://user-images.githubusercontent.com/36276403/79637962-ae202180-818b-11ea-984a-57b4083c2c4b.png)

**Comment by flodiebold** [comment]
The same or closely related as #3970.

**Comment by lnicola** [comment]
Seems fixed now:

![image](https://user-images.githubusercontent.com/308347/105736965-0e739900-5f3e-11eb-9c52-e33a12b86757.png)
