### ISSUE TITLE
Code completeion does not work inside yew html macro

### ISSUE THREAD

**Issue by RyanBluth** [rust-analyzer/rust-analyzer#4031]
Here is an example of the macro in use https://github.com/yewstack/yew/blob/19b6d11aed6c7bd68f9716ced4fb619edaa58b18/examples/showcase/src/main.rs#L99

**Comment by jplatte** [comment]
This is older than #5265 which AFAICT tracks the same thing, but has less info, so should probably be closed in favor of that?
