### ISSUE TITLE
Display the value of consts on mouseover

### ISSUE THREAD

**Issue by crumblingstatue** [rust-analyzer/rust-analyzer#4051]
This is the definition of my const: `const DAYBOX_SIZE: u8 = 24;`

When I hover over a usage of it, rust-analyzer displays
![image](https://user-images.githubusercontent.com/1521976/79743263-90c29300-8304-11ea-9944-7aeaca78a983.png)

It would be nice if it also displayed the value, so I don't have to go to the definition site to see it.

**Comment by matklad** [comment]
Relevant code is here: https://github.com/rust-analyzer/rust-analyzer/blob/5ca7cd960b908944a2f3f66a1d0ee5df98b78959/crates/ra_ide/src/hover.rs#L77

**Comment by crumblingstatue** [comment]
Did you mean to close this issue? Is it already implemented?

**Comment by matklad** [comment]
oups, nope, didn't mean to close

**Comment by petr-tik** [comment]
if my pr for fixing remove_dbg is merged, I will probably pick this up next. 

Can someone please assign this to me?
