### ISSUE TITLE
"Enter" key doesn't work at all with latest build

### ISSUE THREAD

**Issue by Diggsey** [rust-analyzer/rust-analyzer#4052]
The only way I can type newlines is with shift+enter...

There's no output from rust-analyzer otehr than a couple of:
```
[ERROR rust_analyzer::main_loop] overly long loop turn: 1.6885598s
[ERROR rust_analyzer::main_loop] overly long loop turn: 2.7851657s
```

But they seem to be unrelated? This is on 64-bit windows.

**Comment by flodiebold** [comment]
Probably a similar issue to #4050

**Comment by flodiebold** [comment]
You can unbind the `rust-analyzer.onEnter` keybinding, by the way.

**Comment by Zooce** [comment]
@flodiebold is `rust-analyzer.onEnter` the only way to get the automatic comment continuation to work? (like when I'm writing documentation and pressing Enter adds `///` to the next line for me)

**Comment by lnicola** [comment]
You can add back the key binding.

There's an alternative, see https://github.com/rust-lang/rls-vscode/blob/ffe36f31b7a7105c6127f44e407dd828f94d1709/src/extension.ts#L500-L541.

**Comment by lnicola** [comment]
I think we can close this since `onEnter` is disabled by default and there's nothing actionable in the original report.
