### ISSUE TITLE
[Feature] Live unit testing

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#4059]
One thing that would be helpful, is to have an indicator along the status bar which shows just a count of passed tests out of total tests, eg `cargo-test: 12/12`, or something like that. Green if you've got 100% passed and red if there were failures.

Then RA can just rerun all tests on every save and re-display the value. Lets you keep track as soon you poked something out of alignment.

Clicking the indicator could perhaps even open up a terminal tab with the last set of cargo-test output so that you can check on any error messages.

**Comment by matklad** [comment]
closing in favor of #8420
