### ISSUE TITLE
Setting for which toolchain to use

### ISSUE THREAD

**Issue by smmalis37** [rust-analyzer/rust-analyzer#4064]
It would be nice to have a vscode extension setting for which installed rust toolchain should be used for all commands (stable, beta, nightly, a specific nightly, etc). Currently I have one project I'm working on that requires nightly for unstable features, but all of my others don't and I would prefer them to be on stable. It would be nice to have a setting for this so i could set it globally to stable and then override it to nightly in just that one project.

**Comment by matklad** [comment]
This is handled by rustup override command

**Comment by xobs** [comment]
I wasn't aware of this feature of rustup. That's cool!

This is the only place I read about it, and I feel it should be documented somewhere. Could this information be added to the manual?

**Comment by lnicola** [comment]
@xobs https://rust-lang.github.io/rustup/overrides.html

**Comment by xobs** [comment]
@lnicola Yes, that's why I tried adding this to my config file:
```json
    "rust-analyzer.runnables.cargoExtraArgs": [
        "+beta-msvc"
    ]
```

I also tried this:
```json
   "rust-analyzer.runnables.overrideCargo": "cargo +beta-msvc"
```

However, when I tried that `rust-analyzer` gave me an error that indicated that this setting didn't take effect, leading me to assume that wasn't possible.

It's good to know that `rustup` can affect the `cargo` command on a per-directory basis, and I think it would be good to call it out here.

**Comment by lnicola** [comment]
> It's good to know that rustup can affect the cargo command on a per-directory basis, and I think it would be good to call it out here.

But that's described on the same page (https://rust-lang.github.io/rustup/overrides.html#directory-overrides). Anyway, I guess we could take a PR with a mention of this, even though it's out-of-scope for RA.
