### ISSUE TITLE
Show Syntax Tree's highlighting gets confused on CRLF files

### ISSUE THREAD

**Issue by CAD97** [rust-analyzer/rust-analyzer#4067]
Example:

![image](https://user-images.githubusercontent.com/5992217/79813565-01d86980-834a-11ea-9958-2cb1fec03d93.png)

Here I'm hovering `ATTR@[47; 63)` and it tells me that the text is

```rust
]
#[derive(Logo
```

instead of the correct

```rust
#[derive(Logos)]
```

due to the fact it's using offsets into an LF view of the file, but the file is actually using CRLF.

**Comment by CAD97** [comment]
Completely unrelated side note: either semantic highlighting isn't turned on for stable yet, or it's gone really weird here. I checked the syntax tree to see if it was messed up, but it's definitely correct, so it's whatever highlighting engine that's being used that's messing up in this image.

**Comment by lnicola** [comment]
See also #4048.

**Comment by edwin0cheng** [comment]
cc @Veetaha :)

**Comment by Veetaha** [comment]
Hmm, right RA converts everything to `\n` internally that's why the offsets of syntax nodes don't match the editors' offsets. This needs for a shitty workaround)

**Comment by CAD97** [comment]
(FWIW @Veetaha I only had a CRLF file because I hadn't told that project to create files in LF mode yet.)

**Comment by Veetaha** [comment]
Nevermind, I stumbled with this problem too when opening external crates code, crlf is pervasive...
