### ISSUE TITLE
Integer type variable gets lost during trait solving

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#4072]
![2020-04-21-132741_1013x192_scrot](https://user-images.githubusercontent.com/906069/79860968-e6b23c00-83d3-11ea-9fa6-50cc9a00b88a.png)

Somehow in the first case, the type variable seems to get 'disconnected' in the chain, whereas it works for a concrete type or a normal type variable :thinking:

**Comment by adamrk** [comment]
I'm not seeing the this issue, but I do see the one from https://github.com/rust-analyzer/rust-analyzer/issues/4132 (on commit https://github.com/rust-analyzer/rust-analyzer/commit/9230ae5492bbfd73483d7f30918c1f686ebe46e9):
![image](https://user-images.githubusercontent.com/16367467/80809810-c13ae480-8bc2-11ea-8504-9a0ae1ee5159.png)

**Comment by flodiebold** [comment]
The original problem indeed seems to have fixed itself, which is interesting -- I have no idea what might have done that.

The problem with ranges is a variation of rust-lang/chalk#327, I think: Since we haven't fallen back to `i32` yet when we're checking the `from_iter` call, we basically ask Chalk "does `Range<?0>` implement `Iterator`, and what's the type of `Iterator::Item`?" The problem is, `Range<T>` only implements `Iterator` for `T: Step`. So the answer from Chalk is "maybe, but no idea what the item type is", because it doesn't know that the impl applies. Whereas rustc can see here that because `?0` has to be some kind of integer, regardless of which one it is, it'll implement `Step` and so the `impl<A: Step> Iterator for Range<A>` applies. At least, I think that's how rustc figures it out.

**Comment by JohnWall2016** [comment]
There're some same problems about the range literals:
<img width="960" alt="屏幕快照 2020-05-03 下午3 08 34" src="https://user-images.githubusercontent.com/19472887/80908428-502a3700-8d52-11ea-93c6-1b8023ae587a.png">
