### ISSUE TITLE
We've reached semi-official status, we need a status bar

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#4074]
VS Code provides API for a status bar:

https://code.visualstudio.com/api/references/vscode-api#StatusBarItem

we should implement status bar for rust-analyzer, for the following purposes:

* clearly indicating when rust-anlayzer is enabled
* clearly indicating when rust-analyzer needs a reload. Our current strategy of showing a notification on every keypress in the config is pretty obnoxious, we really should just change the color of the status bar
* indicate the "loading" state of rust-analyzer (?)
* indicate presence of updates for nightly (?)
* provide one-click troubleshooting options (?)

**Comment by matklad** [comment]
cc @Veetaha this seems like something you might be interested in, as it touches on many systems you've helped to improve already!

**Comment by Veetaha** [comment]
@matklad what do you mean by a notification on every keypress? This shouldn't happen on each keypress, if it does then this is a bug, but it does clearly work as intended for me now, i.e. you get the notification when the config value if modified once and never thereafter until you touch it again

**Comment by Veetaha** [comment]
Besides that, I am used to having a blue color of the status bar and orange when in debugging mode, I am not sure we should abuse this power to add new states to the status bar

**Comment by Veetaha** [comment]
3d we do indicate the loading of packages as a progress notification, could you elaborate on this item more?

**Comment by Veetaha** [comment]
5th which troubleshooting options are you implying? Please elaborate...

**Comment by eminence** [comment]
RA already uses the status bar in some places.  Just to be clear if we're talking about the same thing...  When first loading a workspace, the initial analysis status is shown:

![image](https://user-images.githubusercontent.com/402454/80041165-bd73d780-84c9-11ea-9a7d-970255e98a4b.png)

And if running cargo-check-on-save is enabled, a StatusBarItem is shown also:

![image](https://user-images.githubusercontent.com/402454/80041205-d3819800-84c9-11ea-9002-48bd391da5d8.png)


Is the proposal to have a new permanent StatusBarItem that is always visible?  (Similar to the github status bar item, which is always visible when I've opened a project that's hosted on github)

**Comment by matklad** [comment]
>what do you mean by a notification on every keypress? 

![Peek 2020-04-23 11-44](https://user-images.githubusercontent.com/1711539/80084933-d9be5580-8557-11ea-91b4-2db6208ce068.gif)

**Comment by Veetaha** [comment]
@matklad Do you have `files.autoSave`, enabled?

**Comment by matklad** [comment]
Ah, that explains it! Still, the fundamental issue remains that "you need
to relaoad" is a status, and not an event.

**Comment by Veetaha** [comment]
@matklad, could you elaborate on [this](https://github.com/rust-analyzer/rust-analyzer/issues/4074#issuecomment-618065824) and [this](https://github.com/rust-analyzer/rust-analyzer/issues/4074#issuecomment-618066598)

**Comment by eminence** [comment]
Here's another use-case for a status bar -- after RA has loaded, it does a `prime_caches` step.  This can take a while, and until this is done, semantic highlighting will be missing.  Yet there's no hint (other than high cpu usage) that RA is doing anything.  So a notification in the status bar would be useful here!

**Comment by bjorn3** [comment]
What is missing after #5188?

**Comment by matklad** [comment]
Nothing, the "one step troubleshooting" unforunately has to go, as status bar icons don't support context menu
