### ISSUE TITLE
clippy lints show instead of compile errors

### ISSUE THREAD

**Issue by jeffsmith82** [rust-analyzer/rust-analyzer#4085]
Was going through the K&R exercises and have this. Clippy is unhappy that there is brackets around the while condition. When I compile it actually errors as I need to have "upper as f32" in that condition. Should the compiler errors get priority over lints.

```
fn main() {
    let (mut fahr, mut celcius): (f32, f32);

    let lower = 0;
    let upper = 300;
    let step = 20;

    println!("  F      C");
    fahr = lower as f32;
    while (fahr <= upper) {
        celcius = (5.0 / 9.0) * (fahr - 32.0);
        println!("{:3.0} {:6.1}", fahr, celcius);
        fahr = fahr + step as f32;
    }
}
```
 I'm using rust-analyzer 0.2.143 in vscode on Linux.

**Comment by JoshMcguigan** [comment]
I'm wondering if this is a UX issue within VS Code, or perhaps just a general UX challenge when reporting two issues with overlapping spans. In `coc.nvim` if I have the cursor on `upper` I see both the error and the clippy lint listed. If I have the cursor on `fahr` I see only the clippy lint listed (as expected). I also see both the error and the clippy lint in the error list.

Can you perhaps attach a screenshot of what you are seeing?

**Comment by jeffsmith82** [comment]
looking really closely I can see the red squiggle for the error underneath the yellow one but its really hard to see.

![image](https://user-images.githubusercontent.com/1884943/79986873-9a82fc80-84a4-11ea-989f-30adc3ea833c.png)

**Comment by matklad** [comment]
I'd say it's a problem with the client which fails to convey which of the two problems is more significant.
