### ISSUE TITLE
clone on PathBuf is unknown

### ISSUE THREAD

**Issue by mich101mich** [rust-analyzer/rust-analyzer#4087]
In the following Code:
```rust
use std::path::PathBuf;

fn main() {
    let p = PathBuf::new();
    let p2 = p.clone();
}
```
Hovering on `clone` or `p2` gives `{unknown}`, even though `p` is indicated as `PathBuf` which implements `Clone`.

`clone` is also not shown in autocompletion:
![image](https://user-images.githubusercontent.com/23530209/79955513-31d55900-847f-11ea-844c-752820e178e1.png)

System Info:
rust-analyzer version: 2020-04-20
vscode version 1.44.2
Rust version 1.42.0

**Comment by edwin0cheng** [comment]
Okay, this bug is tricky (I spent a few hours to trace in debugger..) , its only happened in a struct which inside std and use `#[derive(Clone)]' builtin derive macro.

The root cause of this bug is very simple, as we expand above macro as :
```rust
impl std::clone::Clone for PathBuf {}
```

Note that `std` module is not imported inside `std` module (?!), such that the name resolution failed to find it inside `std`.

**Comment by flodiebold** [comment]
> Note that std module is not imported inside std module

**Comment by bjorn3** [comment]
> Or core::clone::Clone, but that really just moves the problem...

That would make `#[derive(Clone)]` work for `#![no_std]` crates.

**Comment by flodiebold** [comment]
Actually the proper way might be just `$crate::clone::Clone`, but it might not work yet because we don't use the `Clone` macro defined in core, right @edwin0cheng ?

**Comment by flodiebold** [comment]
> That would make `#[derive(Clone)]` work for `#![no_std]` crates.

Well, currently that works anyway because we don't honor `no_std` in name resolution :wink:

**Comment by bjorn3** [comment]
`Clone` **is** defined in core: https://github.com/rust-lang/rust/blob/46ec74e60f238f694b46c976d6217e7cf8d4cf1a/src/libcore/clone.rs#L140. It just has the `#[rustc_builtin_macro]` annotation to make it special cased by rustc.

**Comment by flodiebold** [comment]
That's what I meant -- we currently don't use that definition, because we don't support `macro` syntax. (We do use the builtin macro definitions for non-derive builtins like `format_args`.)

**Comment by edwin0cheng** [comment]
> Actually the proper way might be just $crate::clone::Clone, but it might not work yet because we don't use the Clone macro defined in core, right @edwin0cheng ?

Um.. for `Clone` I think it is okay, (I need to check first), but how about some builtin trait ? (e.g. Copy)

**Comment by flodiebold** [comment]
> Um.. for Clone I think it is okay, (I need to check first), but how about some builtin trait ? (e.g. Copy)

Copy is also defined in core, and the derive for it as well, so I don't see the difference.
