### ISSUE TITLE
No way to determine what "semantic token" to use in VSCode config

### ISSUE THREAD

**Issue by CleanCut** [rust-analyzer/rust-analyzer#4097]
I discovered through educated guesses and trial-and-error that `variable.immutable` and `variable.mutable` and `variable.constant` are the tokens to use in VSCode settings for the corresponding variable and constant types. Honestly, I don't know if this is an issue with VSCode or rust-analyzer, but I'll start here.

From what I can tell from [this doc](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#token-styling) and [this doc](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector) I should be able to use the semantic token information in the Scope Inspector to determine the name of the setting. This works for some things like Traits, etc. where the semantic token type (`interface`) is really the setting, but you most definitely cannot in the case of some of the most common settings.

Here are some variable settings I discovered by trial-and-error, none of which are listed in any documents I can find nor show up as such on the scope inspector.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/5838512/80053935-52330100-84db-11ea-8bca-2693a7994ad4.png">

Setting: `variable.immutable` -- Scope inspector says: `variable` (and doesn't have `immutable` anywhere at all)

<img width="745" alt="image" src="https://user-images.githubusercontent.com/5838512/80053817-05e7c100-84db-11ea-9ca5-9d0474a0bbb3.png">

Setting: `variable.mutable` -- Scope inspector says: `variable`, though it does note `mutable` under "modifiers"

<img width="722" alt="image" src="https://user-images.githubusercontent.com/5838512/80054027-84446300-84db-11ea-9cca-7e555fe63922.png">

Setting: `variable.constant` -- Scope inspector says: `variable`, though it does note `constant` under "modifiers"
<img width="505" alt="image" src="https://user-images.githubusercontent.com/5838512/80054141-bce43c80-84db-11ea-8bc3-08a9d065a96c.png">

### How do I determine what setting to use?

I'm not going to be able to guess the setting name in all cases. How can I determine what the settings are without resorting to guessing?  Is this something under rust-analyzer's control?

**Comment by Veetaha** [comment]
Here are the declarations of our semantic tokens:
https://github.com/rust-analyzer/rust-analyzer/blob/ad3f1da2eae62c81ac317364171e18b1e546f095/editors/code/package.json#L497-L572
Unfortunately, they don't show up in the ui of the extension contributions...
![image](https://user-images.githubusercontent.com/36276403/80070102-1768b180-854b-11ea-9061-f53022376bef.png)
A side-note: there is no immutable modifier, you can detect immutability by the absence of `mutable` token modifier.

Anyway maybe we should document this somewhere in `docs/user/`...

**Comment by matklad** [comment]
Hm, from the screenshot, `semantic token type` and `modifiers` fields seem to specify exactly what you need?  The `immutable` isn't there because we don't make use of such modifier.

**Comment by CleanCut** [comment]
> Here are the declarations of our semantic tokens:

That's exactly what I needed!

> Hm, from the screenshot, `semantic token type` and `modifiers` fields seem to specify exactly what you need? The `immutable` isn't there because we don't make use of such modifier.

Ah!  The theme already had white variables, which masked the fact that `variables.immutable` _wasn't_ actually working.  The correct usage for immutable variables was just `variables`.

Now everything is starting to make sense.  With those two pieces of information I was able to verify that the general way to specify the "key" in the setting is:

```
semantic_token_type[.modifier1][.modifier2][...]
```

Where the most specific key specified wins.  The order of the modifiers doesn't appear to matter.

For example, this config:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/5838512/80121591-bd1b2100-8549-11ea-95a5-842ff0834435.png">
results in this:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/5838512/80121623-c7d5b600-8549-11ea-9a03-51eb9e516f99.png">
While this config:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/5838512/80121760-f2277380-8549-11ea-8612-b2915424bddd.png">
results in this:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/5838512/80121808-f9e71800-8549-11ea-8dae-785dd1e70ef9.png">

# My Feature Request

> Anyway, maybe we should document this somewhere in docs/user/...

I'll double down on that!  My official request is: **Make it easy to find that list of `semantic token types` and `modifiers`.**

#

On a related note, it appears that VSCode's handling of `fontStyle` itself is buggy (you can't replace a theme's non-blank `fontStyle` with another `fontStyle`, only clear the `fontStyle` entirely or add additional styling to it), which I [reported to VSCode](https://github.com/microsoft/vscode/issues/95932).

**Comment by matklad** [comment]
>Make it easy to find that list of semantic token types and modifiers.

I think this should be handled by the editor. They are correctly specified in package.json and VS Code already provides completion for them:

![image](https://user-images.githubusercontent.com/1711539/80125116-84069f00-8591-11ea-9be7-690ab6509eb6.png)
