### ISSUE TITLE
[feature] Option to always run the nightly rustfmt even if the default channel is not nightly.

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#4109]
If this option were enabled, then whenever RA formats the code it would format with the `+nightly` flag and you'd get the nightly formatter.

I'd like to use stable rust more often for peace of mind, and it's actually rustfmt rather than langauge features that are keeping me on nightly.

**Comment by matklad** [comment]
This should be possible using these config options:

https://github.com/rust-analyzer/rust-analyzer/blob/189ac4abbf6037419cb195c0a36a179544496ced/editors/code/package.json#L240-L259

probably just `extraArgs: ["+nightly"]` would work, but the overrideCommand should work for sure. 

Optimistically closing this, feel free to reopen if this doesn't solve your issue.

**Comment by Lokathor** [comment]
ah excellent!
