### ISSUE TITLE
Manual - Installation - does NOT explain installation

### ISSUE THREAD

**Issue by zoechi** [rust-analyzer/rust-analyzer#4120]
https://rust-analyzer.github.io/manual.html#installation does not explain how to install rust-analyzer,
and to me it is all but obvious how it should be installed.

After 1/2h of searching the web I found https://gitter.im/emacs-lsp/lsp-mode?at=5e9dd8b05706b414e1e30012
but that also does not explain anything, but it hints that there is no installation, but only a downloadable executable. 

If this is the case it would be VERY helpful to put that into the Installation section of the docs or just delete the section to not cause more harm then good.

**Comment by lnicola** [comment]
Does this help? https://rust-analyzer.github.io/manual.html#emacs

**Comment by zoechi** [comment]
Thanks for your response.
Sadly it does not help because

> Does this help? 

is about configuration, not installation.

> Binary releases are available here.

I don't understand why you seem to think that this does not need a VERY prominent mention.
I'm using Rust since a few months and so far everything was installable using `rustup` or `cargo`. Because `rust-analzer` deviates from what is common it, should be mentioned in the docs so that there is no doubt left.

Another issue is that there is no straight-forward way to automate installation. There are some hacks to download releases using wget/curl, but the suggestions look brittle.

**Comment by flodiebold** [comment]
See [here](https://rust-analyzer.github.io/manual.html#language-server-binary):
> Other editors generally require rust-analyzer binary to be in $PATH. You can download the pre-built binary from releases page, or you can install it from source using the following command:

Improvements to the wording and organization of the manual are of course welcome.

**Comment by zoechi** [comment]
Thanks, it's clear now. I'll make an attempt to improve.

**Comment by zoechi** [comment]
the mentioned `cargo xtask ...` does not work for me.

```
cargo xtask
error: no such subcommand: `xtask`

	Did you mean `test`?
```
Just `xtask ...` works though.

I don't know `cargo` well enough to know if this is because there is some configuration missing. This means that there needs to be instructions about how to install xtask or the rust-analyzer install docs need to be adjusted.

**Comment by flodiebold** [comment]
Are you running it from the rust-analyzer source? (The description could be clearer about this.)

**Comment by lnicola** [comment]
`cargo xtask install` is the command you need to run when building from source. There's no need to do that if you're using a pre-compiled binary from GitHub.

If you do want to build from source, you need to check out the repository (or download the code), then run `cargo xtask install` from that directory. This way it will work, without you needing to install anything else. You certainly don't have to run `cargo install xtask`.

**Comment by zoechi** [comment]
@lnicola ok, I didn't expect the command to fail as "no such subcommand" if run in the wrong directory. I just tried to verify if installing xtask worked.

I created #4158 and https://github.com/matklad/cargo-xtask/pull/9

**Comment by flodiebold** [comment]
You don't need to install cargo-xtask. Just running `cargo xtask install` will work when run within the rust-analyzer source.

**Comment by lnicola** [comment]
Can we close this?

**Comment by zoechi** [comment]
Changes are merged
