### ISSUE TITLE
rust-analyzer is broken when $RUST_LOG is set

### ISSUE THREAD

**Issue by phynalle** [rust-analyzer/rust-analyzer#4123]
**environment**
neovim-0.4.3 & coc-rust-analyzer.

**symton**
When I set RUST_LOG with `direnv`, rust-analyzer doesn't work and even node (maybe plugin) is crashed due to out of memory' 
I think logging would give effect on responses made by rust-analyzer.

**Comment by flodiebold** [comment]
If you just set RUST_LOG globally, RA will log *a lot*, which will also slow down everything. The OOM crash is probably the plugin trying to store logs in memory.

**Comment by matklad** [comment]
we changed the magic var to RA_LOG
