### ISSUE TITLE
Support progress reporting from the LSP if the client supports it

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#4140]
That might at least inform the user that something is going on during long requests (first goto def, call hierarchy etc.).

https://github.com/rust-analyzer/rust-analyzer/issues/1650

**Comment by kjeremy** [comment]
We support this on window events now but not individual operations like goto def.

**Comment by matklad** [comment]
I think we have progress for long-running ops like indexing. Having progress for individual operations feels much harder, and not that useful, so closing for now
