### ISSUE TITLE
Add CodeActionKinds to assists and return them from server caps if the client supports it

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#4147]
@matklad I think I wrote the following... but do you remember why we went this route instead of having an `AssistKind` that gets converted to a `String` or `CodeActionKind` in `conv.rs`? 

https://github.com/rust-analyzer/rust-analyzer/blob/45832b990c7f291abe578dff3c460f4a1232f024/crates/rust-analyzer/src/main_loop/handlers.rs#L699-L703

**Comment by matklad** [comment]
I don’t :-)

Seems better to add a kind field to assist, though, unless we are going to add different kinds to most assists, the current soln seems ok enough
