### ISSUE TITLE
Defining a default target to support cross-compilation targets

### ISSUE THREAD

**Issue by simlay** [rust-analyzer/rust-analyzer#4163]
Configuring a default target for rust-analyzer would be pretty nice for projects that have different conditional compilation such as [winit](https://github.com/rust-windowing/winit), [cpal](https://github.com/rustaudio/cpal) and many more.

Myself and @FuriouZz have asked about this in Zulip so I figure it's worth making an issue for tracking and discussion purposes.

Normally, one configures (or at least that's what I've been doing) a default target in their workspace or even host by adding something like:
```
[build]
target = "wasm32-unknown-unknown"
```
in one of the [cargo configuration files](https://doc.rust-lang.org/cargo/reference/config.html).

Based on some talk in Zulip from @matklad, it looks like the relevant commands are hardcoded:
* https://github.com/rust-analyzer/rust-analyzer/blob/fc57358efda7c028cbe8a438446cce5f540f48ca/crates/ra_project_model/src/lib.rs#L561-L564
* https://github.com/rust-analyzer/rust-analyzer/blob/fc57358efda7c028cbe8a438446cce5f540f48ca/crates/ra_project_model/src/cargo_workspace.rs#L149

Also, it seems that the configuration steps use `rustc` bypassing `cargo` which means the cargo configs aren't used. I'm not familiar with some of the rational behind this but if it's too burdensome to make use of the cargo configs, I think supporting this feature via the `settings.json` config with something like `{ "rust-analyzer.defaultTarget": "wasm32-unknown-unknown" }` would be okay but not ideal.

**Comment by FuriouZz** [comment]
@simlay Pull request merged
