### ISSUE TITLE
rust-analyzer seems to continue running after I quit VS Code

### ISSUE THREAD

**Issue by szunami** [rust-analyzer/rust-analyzer#4168]
Sorry if this is a duplicate issue, love this project!

Sometimes several minutes after I quit VS Code, I can still find a `rust-analyzer` process running. Is this a known issue?

**Comment by eminence** [comment]
What OS are you on (Windows/linux/macos/etc) ?    Would you be able to capture a process-tree listing that includes "rust-analyzer" when this happens?

**Comment by szunami** [comment]
I'm on macos; I quit VS Code about 5 minutes ago.

```
ps aux | grep rust-analyzer
sam              15957 100.0 35.4  9428272 2972884   ??  R    10:00PM  10:07.68 /Users/sam/Library/Application Support/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-mac

pstree 15957
--- 15957 sam /Users/sam/Library/Application Support/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-mac
```

**Comment by matklad** [comment]
It would be useful to get a stacktrace next time this happens

**Comment by szunami** [comment]
Sound great, will do.

**Comment by lnicola** [comment]
@szunami are you still seeing this?

**Comment by szunami** [comment]
I have not seen this in the past couple months. I will keep my eyes out for it in the future. Feel free to close this.

Thanks for this excellent tool 😍
