### ISSUE TITLE
Auto-completion doesn't find suggestions with trait-heavy code (e.g. gtk-rs)

### ISSUE THREAD

**Issue by sdroege** [rust-analyzer/rust-analyzer#4176]
For example when taking the example directly from https://gtk-rs.org and typing `window.set` in the `connect_activate()` closure, only the functions that are already used in scope (`set_title()`, `set_default_size()`) are suggested.

However `gtk::ApplicationWindow` impls `glib::IsA<gtk::Widget>` (and various others), via which it is covered by the `impl<T: IsA<gtk::Widget>> gtk::WidgetExt for T { ... }` blanket impl, which provides [lots](https://gtk-rs.org/docs/gtk/trait.GtkWindowExt.html) of other `set_...` functions.

Maybe the indirection via the `IsA` trait and the blanket impl is the problem here?

**Comment by sdroege** [comment]
Thanks for the fast response. If there's anything I could help with this, please let me know :)

**Comment by sdroege** [comment]
Not sure if that's the same problem, but together with macros (for code generation) something similar happens with code only involving the `Deref` trait.

If you have a value of type `gstreamer::Message` as defined [here](https://gstreamer.pages.freedesktop.org/gstreamer-rs/gstreamer/message/struct.Message.html), then this derefs to `gstreamer::GstRc<gstreamer::MessageRef>`. This `Deref` impl (and the whole type) is macro generated. rust-analyzer does not seem to be able to see e.g. the `is_writable()` function on `GstRc`.

Or to take it one level further: `GstRc<T>` impls `Deref<Target=T>`. The functions on `T` are also not visible, both if you have a `Message` (which is somewhat expected) as well as if you have a `GstRc<MessageRef>`. If you have a `&MessageRef` they're visible as expected.

On the other hand if having a simple case of `struct Foo(String)` and `Deref` on that, all string functions are visible to rust-analyzer.

**Comment by flodiebold** [comment]
It's possible that both are caused by not being able to expand those glib macros. It would be interesting to try to create a minimal reproduction by copying the macro code and application to a single file.

**Comment by edwin0cheng** [comment]
Would you mind to tell us where is the call site of the `gst_define_mini_object_wrapper!` macro of the `gstreamer::MessageRef` ? And could you mind to use the "Expand macro recursively" feature to check if it is expanded successfully ?

**Comment by sdroege** [comment]
> Would you mind to tell us where is the call site of the `gst_define_mini_object_wrapper!` macro of the `gstreamer::MessageRef` ?

That's [here](https://gstreamer.pages.freedesktop.org/gstreamer-rs/src/gstreamer/message.rs.html#33-35)

> And could you mind to use the "Expand macro recursively" feature to check if it is expanded successfully ?

Yes that works fine. Works for both `gst_define_mini_object_wrapper!` and the `glib_wrapper!` macros.

Still leaves `$crate::` etc around but I assume that's expected. Or might that cause problems if the macro is defined in a different crate (e.g. `glib_wrapper!` is defined in the glib crate, but is used from e.g. the gtk crate... and there `$crate` should've become `glib::`).

In both cases the whole thing is not formatted nicely but that also shouldn't matter I assume? E.g.

```rust
#[doc(hidden)]impl AsRef<$crate::object::Object>for Element {
  fn as_ref(&self) ->  &$crate::object::Object {
    $crate::object::Cast::upcast_ref(self)
  }
}#[doc(hidden)]unsafe impl $crate::object::IsA<$crate::object::Object>for Element{}
```

**Comment by sdroege** [comment]
Hmm it seems to be the `$crate` that causes confusion here. If I change `gst_define_mini_object_wrapper!` to not use it (which of course only works inside the same crate then), then rust-analyzer can follow the derefs correctly.

Maybe that's also the problem with `glib_wrapper!`.

**Comment by sdroege** [comment]
> Maybe that's also the problem with `glib_wrapper!`.

Should be part of the problem but it's not solved when removing usage of `$crate` there. There the remaining problem seems to be resolution of the traits.

**Comment by edwin0cheng** [comment]
> Still leaves $crate:: etc around but I assume that's expected.

Thanks for the information! Yes, it is expected. RA should translate it to def-site crate name in lowering. However, it seem like there is some bug around path in associate type, here is a minimal reproducible example : 

```rust
struct MessageRef;
struct Message1(MessageRef);
struct Message2(MessageRef);

macro_rules! foo {
    () => {
        impl ::std::ops::Deref for Message1 {
            type Target = $crate::MessageRef;
            fn deref(&self) ->  &Self::Target {
                &self.0
            }
        }

        impl ::std::ops::Deref for Message2 {
            type Target = crate::MessageRef;
            fn deref(&self) ->  &Self::Target {
                &self.0
            }
        }
    }
}

foo!();

fn main() {        
    let msg1 = Message1(MessageRef);
    let msg2= Message2(MessageRef);
    
    let _a = &*msg1;     // _a is &{unknown}
    let _a = &*msg2;     // _a is &MessageRef
}
```

**Comment by sdroege** [comment]
I guess, for the glib `IsA<_>` problem, let's take another look after this first part about `$crate` is solved.

**Comment by edwin0cheng** [comment]
Would you mind to give me some pointer how `IsA<_>` is generated by macro ? I am not familiar with gtk-rs code base .. :)

**Comment by sdroege** [comment]
Sure, but that macro is a bit more complicated :D
1. `glib_wrapper!` is defined [here](https://github.com/gtk-rs/glib/blob/master/src/wrapper.rs#L329) . These and the cases below are the ones used for actual objects with `IsA`. They map to `glib_object_wrapper!`
2. That one comes from [here](https://github.com/gtk-rs/glib/blob/master/src/object.rs#L698) and is rather complicated, involving some recursion. In there you will find the `IsA` impls. There will be one for each parent type and interface that is implemented by a type (e.g. `gtk::Button` inherits among other things from `gtk::Widget` and `glib::Object` so there would be `IsA<gtk::Widget>` and `IsA<glib::Object>` impls).
3. An example usage inside glib can be found [here](https://github.com/gtk-rs/glib/blob/master/src/gobject/auto/binding.rs#L12)
4. The `IsA` trait is defined [here](https://github.com/gtk-rs/glib/blob/master/src/object.rs#L76) and has various super traits that also all come from the same file
5. The most important usage of it is in blanket trait impls like [here](https://github.com/gtk-rs/glib/blob/master/src/object.rs#L1337). That one actually uses `T: ObjectType` instead of `T: IsA<Object>` for reasons I can't remember, but usually that would be `T: IsA<Object>`. See for example [here](https://github.com/gtk-rs/gtk/blob/master/src/auto/button.rs#L562) for `gtk::Button`. That's how methods of parent types are automatically available on sub types, i.e. how one part of OOP inheritance is modeled here.

If you have more questions please just ask :)

**Comment by edwin0cheng** [comment]
After #4220 , `is_writable()` is visible for `Message` now. 

And I just checked, for the case of `window` :

![gtk-screen-shot](https://user-images.githubusercontent.com/11014119/80864924-89ae6400-8cb8-11ea-8868-d8c39a79c492.png)

So I think this issue could be closed ?

**Comment by sdroege** [comment]
Indeed, this works now. It just takes a considerable amount of time to give the auto completion suggestions (2-3s), it's much faster for other types :)

But let's close this then, thanks a lot!

**Comment by matklad** [comment]
>It just takes a considerable amount of time to give the auto completion suggestions (2-3s)

For me, it's pretty fast (200ms), though for me bulid.rs failed to run (NixOS...) so that might be the cause. Still, even 200ms seems like way to slow, hope we'll get to optimizing this stuff some day
