### ISSUE TITLE
rust-analyzer and real-time linting

### ISSUE THREAD

**Issue by sbromberger** [rust-analyzer/rust-analyzer#4185]
Sorry if this is a stupid question, but I've been hearing that rust-analyzer is a "drop-in replacement" for rls. However, I can't seem to get the same behavior in between rls and rust-analyzer in vim. I've tried two different LSP clients: ALE and coc.nvim, and both of them show this crucial difference:

With rls, linting is "real-time"- that is, with ALE, I configure it to show me new errors whenever I exit insert mode. I type something, hit <ESC>, and boom - if there's an error, I see it. I fix the problem, and the error notification goes away.

With rust-analyzer, I have to explicitly save the file before anything is linted. I then fix the problem, and have to save the file again for the error notification to disappear. (In the meantime, if I've removed or added a line, the highlight is now on a completely different line that has no error.)

Is this expected behavior, or am I configuring something incorrectly?

**Comment by matklad** [comment]
This is expected behavior. The full explanation can be found here: https://rust-analyzer.github.io/blog/2020/04/20/first-release.html#drawbacks.

We'll fix it eventually, by switching to as-you-type linting, but that's pretty far in the future. At the moment the work-around is to enable auto-save in the editor.

**Comment by sbromberger** [comment]
Thanks for the confirmation. Auto-save in the editor is not a great option, since I don't necessarily want regular writes to disk / remote network mounts.

I would agree that this is a pretty significant drawback, and one that would preclude use of rust-analyzer as a general LSP server until it's fixed. I'm glad to see that it's on the roadmap, though, but a bit concerned by the statement that it's pretty far in the future. Hopefully rls will still be supported until such time as this is implemented.

Appreciate the quick response!

**Comment by flodiebold** [comment]
> I would agree that this is a pretty significant drawback, and one that would preclude use of rust-analyzer as a general LSP server until it's fixed.

**Comment by oblitum** [comment]
@sbromberger you can have both running at the same time, but it's not light on memory: https://github.com/rust-analyzer/rust-analyzer/issues/1710#issuecomment-528944872. I don't use that anymore, but it worked, coc.nvim with analyzer for anything LSP, but diagnostics (you can leave it enabled too), ALE for diagnostics (I think you may also use coc.nvim here too, just set one extension to not have diagnostics).

**Comment by nikitavoloboev** [comment]
Is this possible to achieve in VSCode Rust Analyser? I read this thread and still confused.

**Comment by minhbear** [comment]
Hi guys, right now I had face that issue, the rust-analyzer does not check linting in realtime, when I run command cargo check it throw error and warning, eventhough I had config rust-analyze.linkedProject and enable autocheckonsave but it not work
