### ISSUE TITLE
Plugin Installation failing

### ISSUE THREAD

**Issue by 95th** [rust-analyzer/rust-analyzer#4187]
I am getting below error about renaming while trying install latest RA plugin from source:

![image](https://user-images.githubusercontent.com/22871609/80481742-abce7c00-8970-11ea-99dd-6ddf10496998.png)

But there is no such folder:

![image](https://user-images.githubusercontent.com/22871609/80481793-c6085a00-8970-11ea-9e63-f79fbee4486d.png)

At commit da1f316b0246ce41d7cb8560181e294089f06ef3

VS code details:
```
1.44.2
ff915844119ce9485abfe8aa9076ec76b5300ddd
x64
```

**Comment by lnicola** [comment]
Try `ls -al` instead. Is that a remote or WSL installation?

**Comment by 95th** [comment]
WSL

![image](https://user-images.githubusercontent.com/22871609/80482323-a9205680-8971-11ea-97cd-3391e5fcca16.png)

**Comment by 95th** [comment]
if I manually create that directory and attempt install, the directory gets deleted but I still get the same error.

**Comment by 95th** [comment]
It worked automatically yesterday. Closing. Thanks
