### ISSUE TITLE
Debugging in VS Code

### ISSUE THREAD

**Issue by vmsh0** [rust-analyzer/rust-analyzer#4191]
Hi,

I'm trying to set up debugging in VS Code.

I'm running a remote setup with Windows client and Linux server. rust-analyzer works fine. I installed the CodeLLDB extension as required, as well as lldb6. However, when I click on the "Debug" link above the main function, everything gets stuck on "Launching: /home/random/elo/target/debug/elo".

**Comment by vmsh0** [comment]
Some further information that might be useful.

This is the output from the LLDB channel:
```Running `cargo build --package elo --bin elo --message-format=json`...
[2020-04-28T15:23:57Z ERROR codelldb::debug_session] Stream::poll after shutdown
Debug adapter exit code=0, signal=null.
    Finished dev [unoptimized + debuginfo] target(s) in 3.17s
Raw artifacts:
{
  fileName: '/home/random/elo/target/debug/elo',
  name: 'elo',
  kind: 'bin'
}
configuration: {
  type: 'lldb',
  request: 'launch',
  name: 'run binary',
  args: [],
  cwd: '/home/random/elo',
  relativePathBase: '/home/random/elo',
  program: '/home/random/elo/target/debug/elo',
  sourceLanguages: [ 'rust' ]
}
Listening on port 29442
[2020-04-28T15:30:22Z ERROR codelldb::debug_session] Stream::poll after shutdown
Debug adapter exit code=0, signal=null.```

**Comment by eminence** [comment]
FWIW, remote debugging seems to work fine for me (Also using a Windows client, connecting to a remote debian system).  The only difference I can see so far is that I'm using LLDB-7 and you're using LLDB-6.  If it is easy for you, can you try LLDB-7?


It also may be worth trying to run lldb directly from the command line to see if that works.  It should look something like this:

```
achin@bigbox:/nas/achin/devel/procdump$ lldb ./target/debug/procdump
(lldb) target create "./target/debug/procdump"
Current executable set to './target/debug/procdump' (x86_64).
(lldb) b main.rs:550
Breakpoint 1: where = procdump`procdump::main::h995549b091c6baf2 + 13 at main.rs:550, address = 0x000000000003469d
(lldb) run
Process 9512 launched: '/nas/achin/devel/procdump/target/debug/procdump' (x86_64)
Process 9512 stopped
* thread #1, name = 'procdump', stop reason = breakpoint 1.1
    frame #0: 0x000055555558869d procdump`procdump::main::h995549b091c6baf2 at main.rs:550
   547  }
   548
   549  fn main() -> anyhow::Result<()> {
-> 550      let args: Vec<_> = std::env::args().collect();
   551
   552      if args.iter().any(|a| a == "--keytest") {
   553          return run_keyboard_input_test();
(lldb) q
Quitting LLDB will kill one or more processes. Do you really want to proceed: [Y/n] y
```

**Comment by matklad** [comment]
I haven't followed all the details here, but looks like this should be closed as upstream bug :)
