### ISSUE TITLE
Setting an illegal the "cargo check" command doesn't report an error anywhere.

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#4197]
I set the "check" command to be `clippy`, but I also temporarily have my target as `stable-i686-pc-windows-msvc` and I don't have clippy installed for that, so running `cargo check` just fails with an error message.

It would be nice if RA had some way to tell me if my "check" command was just totally failing to run.

**Comment by lnicola** [comment]
Probably a duplicate of #3155.

**Comment by Lokathor** [comment]
Ah! apparently so, i searched for the keyword "check".

Closing
