### ISSUE TITLE
Request: Make creating new mod easier

### ISSUE THREAD

**Issue by KSXGitHub** [rust-analyzer/rust-analyzer#4200]
## Problem

Currently, in order to create a new `mod` in Rust in VS Code, I have to do 2 actions:
  1. Create a new file named `dir/my_mod.rs` or `dir/my_mod/mod.rs` using Explorer tree.
  2. Open `dir/mod.rs` and add `mod my_mod.rs;`.

If I skip step (2), then there would be no IDE support for my new file.

## Proposal

1. When user creates a file named `dir/my_mod.rs` or `dir/my_mod/mod.rs`, rust-analyzer should automatically add `mod my_mod;` or `pub mod my_mod;` (depending on context and user preference) to `dir/mod.rs` and save it (optionally, format the code before save).
2. When user adds `mod my_mod;` or `pub mod my_mod;` to `dir/mod.rs`, rust-analyzer should create `dir/my_mod.rs` or `dir/my_mod/mod.rs` depending on context and user preference.

**Comment by matklad** [comment]
You don't need step 1:

https://rust-analyzer.github.io/assets/blog/first-release/new-mod.webm

**Comment by KSXGitHub** [comment]
@matklad How do I make that menu appear?

**Comment by bjorn3** [comment]
Which editor do you use?

**Comment by KSXGitHub** [comment]
@bjorn3 VS Code.

**Comment by matklad** [comment]
The default keybinding is <kbd>ctrl + .</kbd>, you can also click on the yellow lightbulb symbol

**Comment by KSXGitHub** [comment]
@matklad Thanks.

However, I do still think that it would be an improvement if rust-analyzer can just create new file automatically for me without that context menu.

**Comment by matklad** [comment]
I think I disagree here -- it's unclear when the user finished typing the name of the module. More generally, I think that such non-local changes need explicit user's ack. 

As usual, we can revisit this if many folks feel otherwise, but, from experience in IntelliJ, lightbulb works nicely here.
