### ISSUE TITLE
Please make onEnter work

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#4214]
@matklad onEnter is broken yet another time. Users cannot just set the keybinding to `Enter` via simple VSCode GUI (it's just impossible to input Enter as a key), otherwise, they should edit `keybindings.json` file.
Besides that even having edited that file you get inconsistent behavior because the command must be invoked only when the editor has focus and other conditions apply (those conditions that were in keybinding contribution point we removed)

```
editorTextFocus && !suggestWidgetVisible && editorLangId == rust && !vim.active || vim.mode == 'Insert' && editorTextFocus && !suggestWidgetVisible && editorLangId == rust
```
Of course I as a user can add this ugly condition to my keybinding definition, but what if we would like to change this condition and... you see where it gets...

For the last month at least there were no complaints about this feature and it seems we applied all the available fixes to workaround all the rough edges.
I don't see any reasons to disable it since this one is a must-have, manually writing doc comments prefix drives me crazy...

Please consider reverting this commit

cc #4107

**Comment by bjorn3** [comment]
> For the last month at least there were no complaints about this feature

https://github.com/rust-analyzer/rust-analyzer/issues/4052

**Comment by Lokathor** [comment]
I also had a similar problem at one point, but the solution certainly isn't to rip away the functionality entirely.

**Comment by matklad** [comment]
Don't have time to write down my complete thoughts exactly, but I stand by what I've said in the RFC discussion:

>To that end, we should make sure that all our disrupting extensions to the protocol are opt in.

PRs with docs are welcome.

> isn't to rip away the functionality entirely.

The funcionality is there, you just need to opt-into it by defning a config.

**Comment by jonas-schievink** [comment]
Alternatively, we could provide the key binding by default, but gate the actual functionality on a config checkbox that users can enable more easily

**Comment by matklad** [comment]
Yeah, adding a keybinding on config change also seems fine to do!

**Comment by lnicola** [comment]
> Alternatively, we could provide the key binding by default, but gate the actual functionality on a config checkbox that users can enable more easily

I'm not sure, see https://github.com/rust-analyzer/rust-analyzer/issues/2331#issuecomment-556993009. The problem is that adding an `onEnter` handler requires Code to synchronously call into the extension host, which may or may not be free, since it can be running code from whatever other extensions the user has installed.
