### ISSUE TITLE
Types from scrap crate don't resolve

### ISSUE THREAD

**Issue by DuckerMan** [rust-analyzer/rust-analyzer#4238]
![image](https://user-images.githubusercontent.com/23637939/80798943-394adf80-8bae-11ea-9607-c0fa1a8fd093.png)
In case of RLS - it shows `scrape::Capturer`

**Comment by flodiebold** [comment]
Please provide the code example, or at least which crates you're using. Two lines of code are not enough to tell what the problem is.

**Comment by DuckerMan** [comment]
Hi, thanks for you reply!

[Code](https://gist.github.com/DuckerMan/263be981bb08dd6879046279ab7f0c19#file-test-rs-L72)

Crate is `scrap`

**Comment by bjorn3** [comment]
Could you share the `Cargo.toml`?

**Comment by DuckerMan** [comment]
``` [package]
name = "stream"
version = "0.1.0"
authors = ["Sergey Duck"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scrap = {git="https://github.com/quadrupleslap/scrap/"}
crossbeam = "*"
brotli = "*"
[profile.release]
lto = true ```

**Comment by flodiebold** [comment]
The scrap crate sets a cfg in [build.rs](https://github.com/quadrupleslap/scrap/blob/master/build.rs), and doesn't have any [fallback](https://github.com/quadrupleslap/scrap/blob/de3cd4cd8610f1cac7f80e29f59dbdb93ffefc6d/src/common/mod.rs#L12) if it's not set. I think we don't get cfgs from running build.rs yet, though you could check whether you have `rust-analyzer.cargo.loadOutDirsFromCheck` active.

**Comment by DuckerMan** [comment]
Thanks for explanation. Should I close the issue?

**Comment by flodiebold** [comment]
No, I think we should keep it open as long as it doesn't work.

**Comment by leecannon** [comment]
I was experiencing the same issue with the `xcb` crate, which uses build.rs to generate code depending on features.

Setting `rust-analyzer.cargo.loadOutDirsFromCheck` to true allowed type resolution to work.

**Comment by matklad** [comment]
The relevant bit of code to get cfgs out of build.rs is here:

https://github.com/rust-analyzer/rust-analyzer/blob/4d33cdcfb2e06088c8bccc57565224f8a377d899/crates/ra_project_model/src/cargo_workspace.rs#L304.

They then need to be feed into crate graph, which shoudl happen here:

https://github.com/rust-analyzer/rust-analyzer/blob/4d33cdcfb2e06088c8bccc57565224f8a377d899/crates/ra_project_model/src/lib.rs#L399-L415
