### ISSUE TITLE
[FR] Add "qualify symbol" quick fix

### ISSUE THREAD

**Issue by moxian** [rust-analyzer/rust-analyzer#4239]
Consider the following code:

```rust
mod submod {
    pub struct S;
    impl S {
        pub fn new() -> S{
            S
        }
    }
}

fn main(){
    let s = S::new(); // <- use of undeclared symbol or module `S`
}
```
It fails to  compile since the `S` is not declared in the main scope.
RA/VSCode helpfully suggests an option to import `submod::S` to fix the problem 
![Code-20200501-103056](https://user-images.githubusercontent.com/7831163/80799624-def25480-8b96-11ea-8fc4-8a41b290fb3e.png)

That works, and gives us:
```rust
use submod::S;

mod submod {
    pub struct S;
    impl S {
        pub fn new() -> S{
            S
        }
    }
}

fn main(){
    let s = S::new();
}
```

However, personally, I dislike excessive `use`s, especially for rarely used symbols, and much prefer fully qualifying them instead. I.e. I would rather fix code by changing the problematic line to `let s = submod::S::new();` with the final result of
```rust
mod submod {
    pub struct S;
    impl S {
        pub fn new() -> S{
            S
        }
    }
}

fn main(){
    let s = submod::S::new();
}
```

This issue is a feature request to make "fully qualify `submod::S`" available in the same "show fixes" list as "import `submod::S`"

#4124 feature request is related, but IMO sufficiently different to warrant a separate issue.

**Comment by flodiebold** [comment]
I don't see the difference to #4124, could you elaborate?

**Comment by moxian** [comment]
My reading of #4124 is it's asking for autocomplete, happening roughly as one types.
I want to see the fix specifically in the lightbulb menu on the left.

It might very well be that I'm totally mistaken and "assist" indeed means the "show fixes" menu - I'm not very familiar with VS Code terminology.

**Comment by flodiebold** [comment]
Yes, "assist" is that menu, so this is a duplicate :slightly_smiling_face:
