### ISSUE TITLE
Make clippy URLs in popup clickable

### ISSUE THREAD

**Issue by tmcguire** [rust-analyzer/rust-analyzer#4250]
When hovering over a clippy problem popup in vscode, I get something like the following screenshot:
![Screenshot_20200501_213556](https://user-images.githubusercontent.com/1164876/80835786-c1070d00-8bf3-11ea-8a90-4a98b7337dd3.png)

It would be great if the URL, in this case https://rust-lang.github.io/rust-clippy/master/index.html#write_with_newline, was clickable, and clicking it would open it in a browser window. That would save time compared to the current workflow, which is to manually select the link with the mouse, copy it to the clipboard, open a browser and paste the URL into the browser.

(Thanks for implementing the applying the clippy suggestion as a quick fix, that's very useful!)

**Comment by kiljacken** [comment]
We can only show plain text in diagnostics currently. See also #4077

**Comment by Veykril** [comment]
This was implemented in https://github.com/rust-analyzer/rust-analyzer/pull/6585, the `write_with_newline` part in `clippy(write_with_newline)` is clickable since.
