### ISSUE TITLE
Install-from-source does not work on unsupported platforms (VScode remote)

### ISSUE THREAD

**Issue by stabler** [rust-analyzer/rust-analyzer#4251]
I'm developing a rust application for a remote linux-aarch64 target (Nvidia Xavier). 

When I attempt to load the rust-analyzer extension on the remote (aarch64) target, I see the prompt to install from source using: `cargo xtask install --server`. However, after running that command I continue to see the same error message/prompt.

As far as I can tell, the issue is in the `async function getServer(config, state)` (main.js line 16218)

```
    let binaryName = undefined;
    if (process.arch === "x64" || process.arch === "ia32") {
        if (process.platform === "linux")
            binaryName = "rust-analyzer-linux";
        if (process.platform === "darwin")
            binaryName = "rust-analyzer-mac";
        if (process.platform === "win32")
            binaryName = "rust-analyzer-windows.exe";
    }
    if (binaryName === undefined) {
```

If I `return "rust-analyzer";` above the check for process.arch and reboot VScode, rust-analyzer works correctly.

It appears that I can also set config.serverPath, however I'm developing for multiple targets so I don't want to hardcode the path in those cases. I don't fully understand the other logic in getServer, so it's possible there's a mechanism that's supposed to be resolving the binary path that I'm not seeing.

At minimum, propose updating the error message ("Unfortunately we don't ship binaries for your platform yet...") to indicate that there's an additional step (beyond `cargo xtask install --server`) to configure on unsupported architectures.

**Comment by lnicola** [comment]
I suggest adding the binary to `PATH` on all of your remote targets so that you don't need to hardcode anything.

**Comment by stabler** [comment]
Hi Laurențiu, thanks for taking a look!

Actually, the binary /is/ in PATH, the issue is that (because the platform is aarch64 and not x64 or ia32) the getServer logic drops out to ‘undefined’ rather than ‘rust-analyzer’, and therefore doesn’t check path.

https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/src/main.ts#L292

When I short circuit the code to return ‘rust-analyzer’ as described above, it’s able to find the binary on path and start correctly.

At least, that’s my understanding of the issue!

**Comment by lnicola** [comment]
But if you set `"rust-analyzer.serverPath": "rust-analyzer"`, it doesn't go through that code because of this check: https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/src/main.ts#L268.

**Comment by stabler** [comment]
Hi,

Yes, got it.

My original post may not have been very clear. When you try and run rust-analyzer on an unsupported platform it gives you the error message "Unfortunately we don't ship binaries for your platform yet..." with instructions to build on the target. I follow those instructions, and I get the described error. There is no hint that adding the config variable "rust-analyzer.serverPath" is necessary (although as you pointed out, that does solve the problem- I actually describe that in my original post).

I was simply suggesting to update the error message ("Unfortunately we don't ship binaries for your platform yet...") to indicate that there's an additional step (beyond cargo xtask install --server) to configure on unsupported architectures. This will make it so other people can discover this issue.

Closing this post
