### ISSUE TITLE
Run action says `test -p {package}`, actually does `test -p {package} --lib`

### ISSUE THREAD

**Issue by CAD97** [rust-analyzer/rust-analyzer#4255]
...which is a very different command, in that it only runs unit tests (reachable from `lib.rs`) and not integration tests (in the `tests` directory).

This caused me to submit [a PR](https://github.com/ron-rs/ron/pull/222) thinking it passed tests when it didn't.

**Comment by CAD97** [comment]
Unrelated side note: give me the option to just `cargo test` or `cargo check` without any `-p` or `--lib` or other narrowing, please.

This wouldn't be too much of an issue if I could just do my own cargo invocation in the `Run` menu, but I can only select from the options given.

**Comment by matklad** [comment]
Yeah, I think for blanket `test -p package`, we shouldn't add `--lib` or other target-selection args. 

>Unrelated side note: give me the option to just cargo test or cargo check without any -p or --lib or other narrowing, please.

Give me IntelliJ's **Run Cargo command** UI in VS Code  :D 

I think such context-less configs are better handled by native tasks (and I think we provide those?).
