### ISSUE TITLE
Features don't always enable themselves as they should

### ISSUE THREAD

**Issue by nox** [rust-analyzer/rust-analyzer#4260]
When working on [`tranche`](https://github.com/nox/tranche) with the top directory opened in Code, I expect `rust-analyzer` to do its job with the `std` feature enabled, given this `.vscode/settings.json`:

```json
{
    "rust-analyzer.cargo.features": [
        "std"
    ]
}
```

Yet, even if I add a syntax error in `tranche/src/std.rs`, `rust-analyzer` reports no errors.

Am I missing something obvious here?

**Comment by matklad** [comment]
This is a known bug: `cargo check` (what shows the majority of erros) and the rest of rust-analyzer are sort-of two completely separate codepaths, and the organically grew separate ways to tweak features, which is not yet unified in the UI ([unification plan](https://github.com/rust-analyzer/rust-analyzer/issues/3897#issuecomment-611393318)).

The current work-around is to specify feature for the check command separately:

```rust
"rust-analyzer.checkOnSave.extraArgs": ["--features", "std"],
```

**Comment by nox** [comment]
Oh thanks! I kept finding references to that non-unified `cargo check`/`rust-analyzer` behaviour but those were mentioned an older version of this setting, where people passed `"--features \"std\""` instead so it wasn't working. I'll try that.

**Comment by nox** [comment]
Duplicate of #3897.
