### ISSUE TITLE
Incremental text sync panics

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#4263]
```
            0ms - infer:wait (319 calls)
            2ms - parse_macro_query (64 calls)
thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)', /home/matklad/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/macros/mod.rs:34:9
stack backtrace:
   21ms - handle_inlay_hints
       20ms - inlay_hints
            6ms - Semantics::analyze2 (307 calls)
            0ms - crate_def_map:wait (42 calls)
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic
             at src/libcore/panicking.rs:54
  14: alloc::string::String::replace_range
  15: rust_analyzer::main_loop::apply_document_changes
  16: ra_vfs::Vfs::change_file_overlay
```

cc @lnicola, not sure how to repro this, but I've seen this a couple of times.

**Comment by lnicola** [comment]
Oof :-(. Were you using multiple cursors or doing anything fancy?

**Comment by matklad** [comment]
Yeah, not sure what was the problem. I delibiratelly tried doing weird things, but no, I can't repro :(

**Comment by lnicola** [comment]
I might have found a repro:

```rust
enum Enum {
    A,
    B,
}

struct Foo {
    f: Option<Enum>,
}

fn f(foo: &Foo) {
    match foo.f {
        None => (),
        Some(En) => (),
    }
}

<|>fn main() {}
```

Press Ctrl-Home and cut.

**Comment by lnicola** [comment]
Actually, it sometimes crashes in a different place:

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 2 but the index is 12', crates/ra_ide_db/src/line_index.rs:88:9
  14: ra_ide_db::line_index::LineIndex::offset
  15: rust_analyzer::main_loop::handlers::handle_code_action
  16: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

It might be caused by a bad incremental edit, but I think I've also seen it on the first edit after restarting the server.

I wonder if we might be using a stale line index for diagnostics.

**Comment by matklad** [comment]
Seems like there might be just two independent crashes? I also thought that this is some runaway assist, but there's `rust_analyzer::main_loop::apply_document_changes` in my stack trace.

**Comment by lnicola** [comment]
I still can't reproduce this reliably, but it seems to happen when using undo and redo.

**Comment by lnicola** [comment]
It might be a different issue, but I have a repro. Type a letter here:

```rust
// <|>ț
fn main() {}
```

It seems to be caused by the non-ASCII character, so maybe again we have two different issues.

**Comment by lnicola** [comment]
It looks like this:

```
[crates/rust-analyzer/src/main_loop.rs:670] &old_text = "// ț\n"
[crates/rust-analyzer/src/main_loop.rs:671] &content_changes = [
    TextDocumentContentChangeEvent {
        range: Some(
            Range {
                start: Position {
                    line: 0,
                    character: 3,
                },
                end: Position {
                    line: 0,
                    character: 3,
                },
            },
        ),
        range_length: Some(
            0,
        ),
        text: "a",
    },
]
[crates/rust-analyzer/src/main_loop.rs:699] &line_index = LineIndex {
    newlines: [
        0,
        6,
    ],
    utf16_lines: {
        0: [
            Utf16Char {
                start: 3,
                end: 5,
            },
        ],
    },
}
[crates/rust-analyzer/src/main_loop.rs:701] &range = 4..4
thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)'
```

We're inserting the new character right in the middle of that "ț". I'm not sure yet what `utf16_lines` is supposed to contain, maybe there's a bug in `LineIndex`?

**Comment by lnicola** [comment]
Filed #4276, but if you didn't run into this while editing comments in Cyrillic or with emojis, there might still be other bugs around.

**Comment by matklad** [comment]
> but if you didn't run into this while editing comments in Cyrillic or with emojis, there might still be other bugs around.

I actually realized why it might be hard to reproduce -- the point at which we get a panic might not be the point where we hit the bug. Rather, we can apply a change successfully, but wrongly, and it'll blow-up down the line during unrelated edit. 

>, but if you didn't run into this while editing comments in Cyrillic or with emojis, there might still be other bugs around.

Yeah, I think I don't actually have non-ascii text in the code I was working with... So looks like `is_char_boundary(n)` is actually `n > text.len()`

**Comment by matklad** [comment]
... which means that #4276 can't be a fix here? Urgh, non-constructive proofs of bugs' existence are the worst =/

**Comment by lnicola** [comment]
Do you want to disable incremental sync until this is fixed? But I'm afraid it will never get fixed if we do that :stuck_out_tongue:.

**Comment by matklad** [comment]
>Do you want to disable incremental sync until this is fixed?

Maybe disable it unless an env-var (maybe RA_PROFILE) is set? 

>Maybe we should catch the panic and log the original text and list of changes, just in case.

Yeah, seems like a good idea. Maybe even add a non-panicking API?

**Comment by lnicola** [comment]
> Maybe disable it unless an env-var (maybe RA_PROFILE) is set?

But we can't configure it at run-time with the current LSP API.

**Comment by matklad** [comment]
```rust
pub fn server_capabilities() -> ServerCapabilities {
    ServerCapabilities {
        text_document_sync: Some(TextDocumentSyncCapability::Options(TextDocumentSyncOptions {
            open_close: Some(true),
            change: Some(if std::env::var("RA_PROFILE").is_ok() { TextDocumentSyncKind::Incremental } else { TextDocumentSyncKind::Full }),
            will_save: None,
            will_save_wait_until: None,
            save: Some(SaveOptions::default()),
        })),
```

**Comment by lnicola** [comment]
Just wondering, have you seen any more panics after the last couple of fixes?

**Comment by matklad** [comment]
I think it should be fine to remove the debug code now. 

@lnicola could you remind how do we handle dos vs unix line endings here? I don't see any special handing of those, but it seems like there should be some?

**Comment by matklad** [comment]
Oh, I assume that is hidden in the VFS... Basically, we get a string with `\n` from VFS, then we might insert some `\r\n` into it, but it'll get normalized to `\n` in VFS again.

**Comment by matklad** [comment]
(might be good to leave a comment about this, I think I've re-traced this chain of thought couple of times already )

**Comment by jonas-schievink** [comment]
I'm still seeing this (and due to auto-format, this actually corrupts the editor contents, which is a bit scary)

**Comment by lnicola** [comment]
@jonas-schievink are you sure it's not https://github.com/rust-analyzer/rust-analyzer/issues/4266?

**Comment by jonas-schievink** [comment]
Hmm, that's also possible. But the panic message I got was for `is_char_boundary`, like in this issue.

**Comment by lnicola** [comment]
CC #5742

**Comment by bkchr** [comment]
Hey, I still get this when modifying the following line:

`info!("💔 New peer with known bad best block {} ({}).", best_hash, best_number);`

(After adding something behind the emoticon)

```
thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)', /rustc/c5eae562935922f712edec56a45591bc2f8ded1c/library/alloc/src/string.rs:1557:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c5eae562935922f712edec56a45591bc2f8ded1c/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/c5eae562935922f712edec56a45591bc2f8ded1c/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/c5eae562935922f712edec56a45591bc2f8ded1c/library/core/src/panicking.rs:50:5
   3: alloc::string::String::replace_range
   4: rust_analyzer::lsp_utils::apply_document_changes
   5: core::ops::function::FnOnce::call_once
   6: rust_analyzer::dispatch::NotificationDispatcher::on
   7: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
   8: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
   9: rust_analyzer::main_loop::main_loop
  10: rust_analyzer::main
```

**Comment by lnicola** [comment]
I can't reproduce this easily:

```rust
fn main() {
    println!(
        "x x💔xxxxxx xxxxx New peer with known bad best block {} ({}).",
        42, 42
    );
}
```

By "adding behind" do you mean "to the right of"?

**Comment by matklad** [comment]
@bkchr which editor is that?

**Comment by bkchr** [comment]
@matklad emacs

@lnicola yes. I assume it also autosaves in between.

**Comment by matklad** [comment]
Reproduced in Emacs! I would guess an LSP-mode issue then? cc @yyoncho VS Code and Emacs seem to disagree about offsets in incremental sync. This still could be our issue though...

**Comment by matklad** [comment]
For typing `x` after `// 💔` in `💔` I get

```
[DEBUG lsp_server::msg] < {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///home/matklad/tmp/hello/src/main.rs","version":1},"contentChanges":[{"range":{"start":{"line":0,"character":4},"end":{"line":0,"character":4}},"rangeLength":0,"text":"x"}]}}
```

VS Code gives

```
[DEBUG lsp_server::msg] < {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///home/matklad/tmp/hello/src/main.rs","version":2},"contentChanges":[{"range":{"start":{"line":0,"character":5},"end":{"line":0,"character":5}},"rangeLength":0,"text":"x"}]}}
```

I think Emacs sends codepoints coordinates and vscode uses utf16? Feels like a bug in Emacs to me :)

I wish we can just respond with an error to the editor in this case, but, well, LSP uses notifications... Note to self: never design RPC mechanism with one-way messages.

**Comment by matklad** [comment]
https://github.com/emacs-lsp/lsp-mode/issues/2080

**Comment by bkchr** [comment]
Ty @matklad :)

**Comment by matklad** [comment]
@bkchr fyi, theres' a workaround: https://github.com/rust-analyzer/rust-analyzer/blob/42e00032c6ba07eaf2f7d5886c60133c65d84cf5/crates/rust-analyzer/src/caps.rs#L24-L28
