### ISSUE TITLE
`default` specialization keyword not supported for associated constants

### ISSUE THREAD

**Issue by aloucks** [rust-analyzer/rust-analyzer#4264]
The following compiles on nightly with `specialization` enabled, but rust-analyzer flags the `default` keyword as an error.

```rust
#![cfg(feature(min_specialization)]
#![cfg(feature(specialization)]

trait Foo {
    const BAR: i32;
}

impl Foo for () {
    default const BAR: i32 = 1;
}
```

Related:

https://github.com/rust-analyzer/rust-analyzer/issues/1402
https://github.com/rust-analyzer/rust-analyzer/pull/1415

**Comment by matklad** [comment]
fixed some time ago
