### ISSUE TITLE
RA picking stable v nightly errors in dependencies

### ISSUE THREAD

**Issue by kubkon** [rust-analyzer/rust-analyzer#4271]
Apologies if this is a duplicate, but I couldn't find a matching issue.

## Description:
I'm not sure whether this is as intended, but I'm currently seeing a lot of errors of this type:

```
/Users/kubkon/.cargo/registry/src/github.com-1ecc6299db9ec823/dynasm-0.5.2/src/lib.rs:1:1 Error [rustc E0554] `#![feature]` may not be used on the stable release channel
```

For the record, with RLS I've actually never experienced this problem.

## Setup:
Some setup info:
* NeoVim + neoclide
* RA with nightly updates

Oh, and here's the repo I've experienced this in: [wasmtime](https://github.com/bytecodealliance/wasmtime).

cc @bjorn3 are you seeing this as well by any chance?

**Comment by kubkon** [comment]
Oh, and I should probably add that often these are the only errors I see, which hide other, actual errors in the crate(s).

**Comment by bjorn3** [comment]
I haven't ever seen this. How did you switch to the nightly channel? Did you use `rustup override`, the `rust-toolchain` file or something else? I currently use `rust-toolchain`, but back when I used `rustup override`, I don't think I have seen it either.

**Comment by kubkon** [comment]
That's the thing, I'm working exclusively on stable channel.

**Comment by bjorn3** [comment]
Did you enable `allFeatures`? The `lightbeam` feature of wasmtime requires nightly.

**Comment by kubkon** [comment]
Ah, `lightbeam`, of course! So turning `allFeatures` off almost did it, thanks! I'm still seeing the same error for `staticvec` though, which is weird given that it should only be pulled by `lightbeam`. 🤷

**Comment by matklad** [comment]
Not sure what's the exact issue here, but it looks like something activates all/default features, which seems unrelated to rust-analyzer.

**Comment by bjorn3** [comment]
I think this is because of the `--workspace` that rust analyzer automatically passes. It worked fine with `"rust-analyzer.checkOnSave.overrideCommand": ["cargo", "check", "--message-format=json", "-p", "wasmtime"]`.

**Comment by kubkon** [comment]
I can confirm that @bjorn3's suggested solution worked. @matklad question though, is that then the intended behaviour?

**Comment by matklad** [comment]
That's intended behavior from rust-analyzer side, but it can be considered a bug ("the" bug) in Cargo. It's being worked on in https://github.com/rust-lang/cargo/pull/7820

**Comment by kubkon** [comment]
Ah cool, makes sense! Thanks for the link!
