### ISSUE TITLE
Request: Detect and transform URL text to actual hyperlink (VS Code)

### ISSUE THREAD

**Issue by KSXGitHub** [rust-analyzer/rust-analyzer#4275]
I use `clippy` as my `checkOnSave.command`, it often displays a URL to further explain linting rule. It would be convenient if I can just click on that URL.

![screenshot](https://user-images.githubusercontent.com/11488886/80897694-d1b7a000-8d25-11ea-9514-ee159bd7673b.png)

**Comment by edwin0cheng** [comment]
possibly duplicated of #503 , but your link is not a clickable link .

**Comment by KSXGitHub** [comment]
@edwin0cheng That link is from a stdout, it won't even be clickable.

**Comment by eminence** [comment]
Dup of #4250 ?

**Comment by edwin0cheng** [comment]
@eminence , I think so !
