### ISSUE TITLE
Pressing Enter while writing a triple slash doc comment doesn't insert the three slashes on the new line

### ISSUE THREAD

**Issue by kotauskas** [rust-analyzer/rust-analyzer#4277]
The official RLS extension for VSCode inserts three slashes when pressing Enter automatically if the line at which the cursor currently is starts with three slashes. This is the main reason why I used triple slash doc comments everywhere. Now that I'm moving from RLS to rust-analyzer, it really is hard to get used to typing out the slashes on every line. It should be trivial to get the same functionality into rust-analyzer though.

**Comment by bjorn3** [comment]
This does exists, but has been disabled by default since https://github.com/rust-analyzer/rust-analyzer/pull/4107. To enable it, you need to go to "Preferences: Open Keyboard Shortcuts (JSON)" and add the following to between the `[]`:

```json
{
    "command": "rust-analyzer.onEnter",
    "key": "enter",
    "when": "editorTextFocus && !suggestWidgetVisible && editorLangId == rust && !vim.active || vim.mode == 'Insert' && editorTextFocus && !suggestWidgetVisible && editorLangId == rust"
}
```

**Comment by edwin0cheng** [comment]
Dup of #4214

**Comment by Veetaha** [comment]
This is awful, users will hardcode our workaround with the keybindings, I am not sure what is more disruptive, having enabled by default (but controlled by us) or this.

**Comment by kotauskas** [comment]
Why don't we just use an entry in the Settings menu? That's the first place where I tried to search, and likely is for anyone trying to enable this.

**Comment by jhpratt** [comment]
Seconding the suggestion for an option in settings. It's something small, but can be _really_ useful.

**Comment by Veetaha** [comment]
Sorry guys, but vscode does give us a hard time on this one. There api vscode proposes for implementing this feature doesn't fit us. We used a workaround with a keybinding by default, and before that there was other workaround with hooking into `\n` character inputs.

There is no vscode api to dynamically add a keybinding (maybe I am wrong and I just failed to find one, if you know one please ping), so this by itself requires some more workarounds which would be much uglier. Also, I guess we switched from `\n` character input listening for a reason, so this is not an option.

I'd be grateful if @matklad could do some research on this ;D

**Comment by Veetaha** [comment]
P.S. it seems to me that vscode guys decided not to include this feature into the LSP protocol because they wanted to avoid doing blocking lsp requests (btw TypeScript by itself doesn't allow you to synchronously resolve a Promise which is a huge blocker for implementing this in vscode itself), that's why they came up with an editor-side regex approach...
