### ISSUE TITLE
fn item output type is not normalized

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#4281]
```rust
    let file: Option<PathBuf> = None.unwrap();
    let dst =
        file.as_ref().and_then(|it| it.file_name()).map(Path::new).unwrap_or(Path::new("main"));
```

![image](https://user-images.githubusercontent.com/1711539/80911800-ee110800-8d38-11ea-8709-8120b78152d2.png)

The hint is not wrong, but this would be better (wrapping`Path::new` into lambda):

![image](https://user-images.githubusercontent.com/1711539/80911823-0e40c700-8d39-11ea-8205-d50396777ee7.png)

**Comment by flodiebold** [comment]
That's the missing built-in impl of `FnOnce` for function types, I'm pretty sure.

**Comment by flodiebold** [comment]
I think this probably just needs a Chalk update (and some tests) now.
