### ISSUE TITLE
HTML links fail in VS Code pop-ups

### ISSUE THREAD

**Issue by jcd-g00** [rust-analyzer/rust-analyzer#4289]
I installed VS Code 1.44.2 with rust-analyzer 0.2.151 and Rust on my macOS system. I have zero previous experience with either VS Code or Rust.

I opened a sample Rust main.rs including a "println!". Mouse-hover over "println!" produced a pop-up including clickable HTML links.

I don't know what is the formal term for this type of pop-up in VS Code; e.g., "parameter hint", or something else.

When I clicked on the link for "format!", it unsuccessfully tried to open a VS Code editor with the file "/std/macro.format.html". Hovering over the link shows "../std/macro.format.html".

I looked for this HTML file on my local filesystem, and found that rustup had installed it under "~/.rustup".

As a test, I created the file "/std/macro.format.html", and then clicking the link in the pop-up successfully opened this file in text mode in a VS Code editor.

I assume that the intent is to instead open a web-browser tab with the HTML doc file.

I don't know whether or not this problem is actually in rust-analyzer, but without the rust-analyzer extension installed, I don't get the pop-up when mouse-hover over "println!" in my example Rust main.rs.

**Comment by matklad** [comment]
On the one hand, this works as expected, as we just render the docstring on the `println!` macro, which contains the `../std/macro.format.html` links. 

On the other hand, we obviously should fix this. I think the fix would be to change the link format from raw html link to a semantic rustdoc link. But relevant RFC is in progress: https://github.com/rust-lang/rust/issues/43466.

So, let's close this as won't fix until https://github.com/rust-lang/rust/issues/43466 is implemented.
