### ISSUE TITLE
Refactor rename infrastructure

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#4290]
Renaming infra needs some design/refactorigns cleanups. The core issue is that `rename` calls [`find_all_refs`](https://github.com/rust-analyzer/rust-analyzer/blob/3b1d98308596e43299b1c7435a395b0a4d1db425/crates/ra_ide/src/references/rename.rs#L132), which is just at the wrong level of abstraction. It returns [`Declaration`](https://github.com/rust-analyzer/rust-analyzer/blob/3b1d98308596e43299b1c7435a395b0a4d1db425/crates/ra_ide/src/references.rs#L40), which should *only* be used for literal goto definition, it is unsuitable and imprecise for rename. 

In particular, handling of renaming to/from field init shorthand is iffy -- it works on strings, while it probably should have access to AST.

**Comment by bnjjj** [comment]
I think we can link this issue here right ? #4237
