### ISSUE TITLE
Cannot debug unit tests

### ISSUE THREAD

**Issue by agentsim** [rust-analyzer/rust-analyzer#4302]
Using Rust stable (1.43 as of this writing) on MacOS 10.15.4.

The two lenses, `Run Test` and `Debug` appear properly. `Run Test` works correctly, both for individual tests and at the module level, but `Debug` does not.

First, `Debug` fails to stop on any breakpoints, and second, clicking through the stack trace when it stops on a panic results in disassembly for all frames, including the ones for my own code.

My project is pretty simple, I think. The only thing I can think of that might be tripping it up is the use of a workspace with multiple binary targets.

**Comment by vsrs** [comment]
@agentsim,

looks like you have a panic in the code above the breakpoint:

```rust
#[test]
fn it_works() {
    panic!("ups");

    assert_eq!(2+2,4);   // bp on this line
}
```

gives exactly this behavior.  
Is there any chance that debug\run code flow is different?

**Comment by agentsim** [comment]
Nope, that's not what's happening. I'm resorting to `println!`-ing  to debug and even when setting the breakpoint between `println!` commands that I see in the output this problem manifests.

**Comment by vsrs** [comment]
You see the stack trace and all the rest. It means that the debug session was started successfully (it is the only thing that Debug Lens does). So, it might be the CodeLLDB issue. Perhaps https://github.com/vadimcn/vscode-lldb/issues/249 ?

If you have a repro I can take a look.

**Comment by agentsim** [comment]
I can reproduce it at will. Let me know what info you need.

**Comment by vsrs** [comment]
What do you have in the Output->LLDB pane? Should be something like: 
```
Runnting `cargo build....`
Raw artifacts: {
...
}
configuration: {
  type: 'lldb'
  ...
}
```
You can copy-paste this `configuration` to your launch.json and try to start a debug session.

**Comment by agentsim** [comment]
Sorry for the delayed reply, this is my Output->LLDB pane.

```
configuration: {
  type: 'lldb',
  request: 'launch',
  name: 'test dsf::io::tests::write_basic_dsf_file',
  program: '/Users/me/work/dsd-rs/target/debug/dsd-1237ba07d9a3ddac',
  args: [ 'dsf::io::tests::write_basic_dsf_file', '--exact', '--nocapture' ],
  cwd: '/Users/me/work/dsd-rs',
  sourceMap: {},
  sourceLanguages: [ 'rust' ],
  relativePathBase: '/Users/me/work/dsd-rs'
}
Listening on port 49656
```
I entered this configuration into `launch.json` and get the same result.

**Comment by vsrs** [comment]
Thanks for the feedback.

> I entered this configuration into launch.json and **get the same result**.

Then it's definitely CodeLLDB problem and you would better ask in [here](https://github.com/vadimcn/vscode-lldb).

Btw, you can try another debug engine: [MS C++ tools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools). It works on Mac too if you have gdb installed and signed [^1]. Just install the extension and set `"rust-analyzer.debug.engine": "ms-vscode.cpptools"`. Hope this helps.

[^1] [GDB Installation on Mac OS X](https://www.ics.uci.edu/~pattis/common/handouts/macmingweclipse/allexperimental/mac-gdb-install.html)

**Comment by vsrs** [comment]
Just realised that with the latest rust-analyser you can try the MS C++ tools even without GDB.

This settings.json
```jsonc
{
    "debug.allowBreakpointsEverywhere": true,
    "rust-analyzer.debug.engine": "ms-vscode.cpptools",
    "rust-analyzer.debug.sourceFileMap": { // required
        "/rustc/4fb7144ed159f94491249e86d5bbd033b5d60550": "${env:HOME}/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust"
    },
    "rust-analyzer.debug.engineSettings": {
        "cppdbg": {
            "stopAtEntry": false,
            "MIMode": "lldb" // required
        }
    }
}
```
works for me. Though, there are some unexpected breakpoint hits in the rustlib internals, but finally the debugger stops where expected.

**Comment by agentsim** [comment]
Thanks, I gave it a go with MS C++ tools with both llvm and GDB.

With llvm there wasn't much difference. The biggest change was that most of the stack frames would prompt me for a missing source file from `rust-src` which I have installed. Some files it could find, and for those they loaded properly. The test executes properly and my breakpoint doesn't get hit.
Similarly with GDB, I had problems with it not being able to find source files. It also seemed to pause on a panic in the rust internals that somehow gets swallowed in normal execution. After click through those, it still didn't hit my breakpoint. Furthermore, from what I can tell the test never actually finished (like the debugger killed it before completing the test.)

Thanks for your help, I'll ask my question over in the CodeLLDB repo.

**Comment by indolering** [comment]
Could be related to #304.

**Comment by indolering** [comment]
Might be related to [VSCode-lldb #304](https://github.com/vadimcn/vscode-lldb/issues/304).

**Comment by lnicola** [comment]
@agentsim this seems to work for me with CodeLLDB:

![image](https://user-images.githubusercontent.com/308347/106035334-ad35fc00-60dc-11eb-8fa0-bd5e0154cd5c.png)

(it also works for a test in `src/main.rs`)

Can you please test again?

(Marking `S-actionable`, if you look at this in the future and the OP hasn't answered, ping me so we can close it.)

**Comment by agentsim** [comment]
I just checked this again, and now it works for me.
