### ISSUE TITLE
when hovering the mouse, is it possible to enhance the type prompt

### ISSUE THREAD

**Issue by wtklbm** [rust-analyzer/rust-analyzer#4311]
current:
![2020-05-05_11 11 00](https://user-images.githubusercontent.com/26459487/81032334-fa749c80-8ec1-11ea-9150-e486a91e7019.png)

expected:
![2020-05-05_11 13 49](https://user-images.githubusercontent.com/26459487/81032340-fea0ba00-8ec1-11ea-9b00-2ca102e0814c.png)

**Comment by flodiebold** [comment]
The shortening of the closure parameter list is intentional, since the types of the closure parameters are visible on the closure. Showing it as an `fn` type would be wrong, since that's a different type.

**Comment by matklad** [comment]
It might still be a good idea to not shorten stuff for hover. The relevant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/87af7c9bd71892028ac91c4e514c548a66e4e8a8/crates/ra_ide/src/hover.rs#L163

**Comment by bnjjj** [comment]
I take the point :)
