### ISSUE TITLE
rustfmt/analysis not running on examples

### ISSUE THREAD

**Issue by starkat99** [rust-analyzer/rust-analyzer#4312]
While extension seems to run cargo check with --all-targets properly when configured and uses results, it doesn't run rustfmt or analysis on examples. I'm also guessing it doesn't work on other targets such as tests either.

**Comment by matklad** [comment]
We definitelly do work for all targets. 

The most common cause for this symptom is that example is added *after* rust-analyzer is started. We currently do not support dynamic reconfiguration of workspace. 

If the thing still doesn't work after restart, a minimal reproducible example would be helpful.

**Comment by starkat99** [comment]
yup, you're right, as soon as I restarted it, everything works. Oops.
