### ISSUE TITLE
RA is broken for #[actix_rt::main] with proc macros enabled

### ISSUE THREAD

**Issue by SomeoneToIgnore** [rust-analyzer/rust-analyzer#4315]
Cargo.toml:
```toml
[package]
name = "zzz"
version = "0.0.1"
edition = "2018"

[dependencies]
actix-rt = "1.1"
actix-web = "2.0"
```

main.rs:
```rust
#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    let test = test();
    dbg!(test);
    println!("Hello, world!");
    Ok(())
}

#[derive(Debug)]
struct Test {
    test: i32,
}

fn test() -> Test {
    Test { test: 2 }
}
```

Enable proc macro and `loadOutDirsFromCheck` settings.

Expected: inlay hints present, highlighting works, completions proposed
Actual: very few RA features such as code lens are present, the rest is not working **across the whole project**

Here's how it looks with disabled proc macros:
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/2690773/81055811-21d36580-8ed2-11ea-8641-5fa42f030c0f.png">

Notice the hint and the highlighting.
When I toggle the proc macro checkbox and reload the server, I get this:
<img width="1237" alt="Screenshot 2020-05-05 at 13 09 06" src="https://user-images.githubusercontent.com/2690773/81055860-39aae980-8ed2-11ea-981f-945c92598334.png">

This happens in the code of a whole project, not only in the `main.rs`, making RA pretty useless.
Another interesting thing to notice that RA works fine with tokio:
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/2690773/81056137-b047e700-8ed2-11ea-8b74-5a5c2808649d.png">

**Comment by edwin0cheng** [comment]
Aiya, after some investigation, I ended confirming the root cause of this bug:

There is a panic in `actix_rt` case: 
```
thread '<unnamed>' panicked at 'can't resolve local ptr to SyntaxNode: SyntaxNodePtr { range: 160..329, kind: IMPL_DEF }', crates\ra_syntax\src\ptr.rs:30:28
```

It is caused by some proc-macro generated are inconsistent. I added some `dbg!` and here are two expansions expanded by the same struct. (by `#[derive(derive_more::From)]`)

```
impl::core::convert::From<(h2::Error)>forConnectError{#[allow(unused_variables)]#[inline]fnfrom(original:(h2::Error))->ConnectError{ConnectError::H2(original)}}impl::core::convert::From<(SslError)>forConnectError{#[allow(unused_variables)]#[inline]fnfrom(original:(SslError))->ConnectError{ConnectError::SslError(original)}}impl::core::convert::From<(String)>forConnectError{#[allow(unused_variables)]#[inline]fnfrom(original:(String))->ConnectError{ConnectError::SslHandshakeError(original)}}impl::core::convert::From<(io::Error)>forConnectError{#[allow(unused_variables)]#[inline]fnfrom(original:(io::Error))->ConnectError{ConnectError::Io(original)}}impl::core::convert::From<(ResolveError)>forConnectError{#[allow(unused_variables)]#[inline]fnfrom(original:(ResolveError))->ConnectError{ConnectError::Resolver(original)}}

impl::core::convert::From<(ResolveError)>forConnectError{#[allow(unused_variables)]#[inline]fnfrom(original:(ResolveError))->ConnectError{ConnectError::Resolver(original)}}impl::core::convert::From<(String)>forConnectError{#[allow(unused_variables)]#[inline]fnfrom(original:(String))->ConnectError{ConnectError::SslHandshakeError(original)}}impl::core::convert::From<(SslError)>forConnectError{#[allow(unused_variables)]#[inline]fnfrom(original:(SslError))->ConnectError{ConnectError::SslError(original)}}impl::core::convert::From<(h2::Error)>forConnectError{#[allow(unused_variables)]#[inline]fnfrom(original:(h2::Error))->ConnectError{ConnectError::H2(original)}}impl::core::convert::From<(io::Error)>forConnectError{#[allow(unused_variables)]#[inline]fnfrom(original:(io::Error))->ConnectError{ConnectError::Io(original)}}
```

Noted that the orders of tokens are different, and `derive-more` crate is using [`HashMap`][1] such that this order is non-deterministic. 

And we had some [discussion][2] for the general solution of this problem and I will start to study and implement a solution soon.

[1]: https://github.com/JelteF/derive_more/blob/0f899f1e29ac1c3ede0cbf1c41ad50c3bf23f680/src/from.rs#L97
[2]: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/indeterministic.20proc-macro

**Comment by bjorn3** [comment]
Even if there is a solution to this problem, `derive-more` should still be fixed to be deterministic. Otherwise crates using it have non reproducible builds.

**Comment by edwin0cheng** [comment]
Yeah, I will submit an issue to them.

**Comment by SomeoneToIgnore** [comment]
Seems that there's exactly 3 usages of `HashMap` in thir code: https://github.com/JelteF/derive_more/search?q=HashMap&unscoped_q=HashMap

hopefully, the PR to fix it will be small.

**Comment by edwin0cheng** [comment]
Upstream issue submitted, and if someone could write a blog post to call out people please don't use `Hashmap` in proc-macro, I will buy them a beer :)

**Comment by rayanmargham** [comment]
![image](https://user-images.githubusercontent.com/69608259/175834529-41257355-03f6-4b65-ab08-3f479f32ff0f.png)
It is still happening on my machine, please reopen the issue

**Comment by Veykril** [comment]
What is the error you are getting, what rustc version and what rust-analzer version are you using?

**Comment by rayanmargham** [comment]
never mind I've fixed it
