### ISSUE TITLE
**Run** should run doctests

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#4317]
Relevant code:

* https://github.com/rust-analyzer/rust-analyzer/blob/d1c1c01309cff76f6ba60c845500f67a1ca6cec6/crates/ra_ide/src/runnables.rs#L43 -- here we decide if there's a test under cursor
* https://github.com/rust-analyzer/rust-analyzer/blob/d1c1c01309cff76f6ba60c845500f67a1ca6cec6/crates/rust-analyzer/src/main_loop/handlers.rs#L377 -- here we convert "test under cursor" into json we send to LSP client
*  https://github.com/rust-analyzer/rust-analyzer/blob/d1c1c01309cff76f6ba60c845500f67a1ca6cec6/editors/code/src/commands/runnables.ts#L9 -- here we run the actual tests

**Comment by bnjjj** [comment]
Hmm seems not so easy, in fact regarding these issues on cargo https://github.com/rust-lang/cargo/issues/6424 and https://github.com/rust-lang/cargo/issues/6669 the `--all-targets` seems to not test all targets :( 

Then a proposal should be to add a new command suggest to just launch doc test with `--doc` flag. What do you think ?

**Comment by matklad** [comment]
I think the linked cargo issues are irrelevant here? We should just generate `cargo test --doc -- name::of::the::test` command (ie, just adding `--doc` to what we do already).

**Comment by bnjjj** [comment]
Maybe I didn't understood the issue but your linked source code seems to be linked to `cargo test --package my_package_name` (https://github.com/rust-analyzer/rust-analyzer/blob/d1c1c01309cff76f6ba60c845500f67a1ca6cec6/crates/rust-analyzer/src/main_loop/handlers.rs#L403) and then if we add `--doc` it won't test unit tests anymore.

**Comment by edwin0cheng** [comment]
One of the disadvantages to using `cargo test --doc --name::of::the::test` is it only support [library target][1]:
```
--doc
    Test only the library’s documentation. This cannot be mixed with other target options.
```

Maybe we could use `rustdoc --test --test-args="name::of::the::test" src/main.rs` ?

[1]: https://doc.rust-lang.org/cargo/commands/cargo-test.html

**Comment by matklad** [comment]
I think doc tests outside of the `--lib` are a niche use-case to begin with, so I'd start with only supporting `--doc` and doing something custom only when we get a bug report.

**Comment by matklad** [comment]
@bnjjj this is about running a *single* test, which goes via [this](https://github.com/rust-analyzer/rust-analyzer/blob/d1c1c01309cff76f6ba60c845500f67a1ca6cec6/crates/rust-analyzer/src/main_loop/handlers.rs#L393) code path.

**Comment by edwin0cheng** [comment]
`--bin` is common use case too :) , But of course I think starting from simplest is right.

**Comment by bjorn3** [comment]
According to that same page doc tests are only tested for lib targets, which is not true. This is probably outdated documentation.

> When no target selection options are given, cargo test will build the following targets of the selected packages:
> [...]
> * doc tests for the **lib** target

**Comment by matklad** [comment]
Hm, but doc tests just don't work in `--bin`?

https://github.com/rust-lang/rust/issues/50784

**Comment by bjorn3** [comment]
I assumed they worked.
