### ISSUE TITLE
Relases tag the wrong commit

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#4319]
Originally reported on reddit. Our relese process works by pushing the nightly tag to the `release` branch, which is then build and uploaded to GH releases and marketplace. In the process, we create a release tag (`date --iso`). Unfortunatelly, it seems like we shomehow tag the current state of `master`, and not of `release`. 

Here's the commit sha we use for release:

https://github.com/rust-analyzer/rust-analyzer/blob/d1c1c01309cff76f6ba60c845500f67a1ca6cec6/.github/actions/github-release/main.js#L19

And here's how we kick the release process:

https://github.com/rust-analyzer/rust-analyzer/blob/d1c1c01309cff76f6ba60c845500f67a1ca6cec6/.github/workflows/release.yaml#L105-L110

I have no idea why it picks master rather than relase, would apreciate help with debugging this one.

**Comment by bjorn3** [comment]
I think the cron job runs in the context of the latest commit on master.

**Comment by matklad** [comment]
That's for nightly. The weekly release runs on push to `release` branch, but still uses master tag (it might be a good idea to verify if all `tag/commit` pairs in our changelogs mismatch) .
