### ISSUE TITLE
Rust analyzer stop working when the vim/vscode idles for a long time

### ISSUE THREAD

**Issue by YYTVicky** [rust-analyzer/rust-analyzer#4324]
Hi,

Currently, I use RA in a large project. Due to a long time waiting for the initialization (include the definition jumping), I prefer not to close vim/vscode. But recently I found that the RA will stop working if vim/vscode idle for a long time. 

The RA is nightly build version.

**Comment by bjorn3** [comment]
Is the rust-analyzer process still running?

**Comment by w93163red** [comment]
I don’t think so, since the status line shows nothing.

bjorn3 <notifications@github.com>于2020年5月5日 周二13:10写道：

**Comment by bjorn3** [comment]
Can you try `ps aux | grep rust-analyzer`?

**Comment by w93163red** [comment]
> Can you try `ps aux | grep rust-analyzer`?

![image](https://user-images.githubusercontent.com/7308728/81358714-4469a800-90a5-11ea-91f3-ee5d5758a866.png)
I think it related to this setting.

**Comment by matklad** [comment]
Haven't seen this myself, not sure how to reproduce, closing as unactionable.
