### ISSUE TITLE
Extend VFS to watch files

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#433]
Currently, VFS reads files once at startup, and then only uses text-editor notifications to change the state of files. 

This works surprisingly well in practice, but we do miss some file system changes (when, for example, switching branches in git). We should add file-system watching to vfs.

This is tricky in itself, and it is not made easier by the fact that the main filesystem-watching library, https://github.com/passcod/notify/, is transitioning from v4  (which is frozen) to v5 (which is not released yet). v5 does not seem like it would be done in the nearish term, so we should perhaps rely on v4 for the time being.

The code for vfs is here:

https://github.com/rust-analyzer/rust-analyzer/blob/53ffa2a030be52ad6ddcf3c038f08c337894fbe7/crates/ra_vfs/src/lib.rs

**Comment by flodiebold** [comment]
Shouldn't we use the [LSP capabilities](https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeWatchedFiles) for that? The LSP spec says
> Servers are allowed to run their own file watching mechanism and not rely on clients to provide file events. However this is not recommended due to the following reasons:

**Comment by vemoo** [comment]
After reading your reasons I agree.

Also there's at least another issue https://code.visualstudio.com/api/references/vscode-api#2261:
> Note that only files within the current workspace folders can be watched.

so it wouldn't be possible to watch `~/.cargo/registry` with vscode.

But since it didn't look too difficult I implemented it here https://github.com/vemoo/rust-analyzer/tree/lsp-file-system.
Let me know if it's worth merging.

**Comment by matklad** [comment]
@vemoo I'd still prefer to start with `notify`: the bare-bones implementation shouldn't be too hard either I think?

**Comment by vemoo** [comment]
Ok, I will start working on a bare-bones impl with `notify`

**Comment by vemoo** [comment]
It's mostly implemented here https://github.com/vemoo/rust-analyzer/tree/vfs-watch.

- I've created a `Watcher` struct similar to how `thread_worker` is structured but with a `mpsc::channel` as input and a `crossbeam_channel` as output
- I've added a new event (https://github.com/vemoo/rust-analyzer/blob/b4f06b05ab51a1cd6a2e883fe0d5c0b63cd8a3b6/crates/ra_lsp_server/src/main_loop.rs#L115) to the `main_loop`
- I've modified `[add|change]_file_overlay` methods in `Vfs` to make the `text` parameter an `Option` and read it from the file system if none is passed to be able to reuse the on `Watcher` changes

There's still something that's not quite working.
https://github.com/vemoo/rust-analyzer/blob/b4f06b05ab51a1cd6a2e883fe0d5c0b63cd8a3b6/crates/ra_vfs/src/watcher.rs#L79-L90
I thought that `drop`ing the watcher would cause the `Reciever` to recieve with error and terminate the thread, but the thread never terminates.

I will investigate further, maybe I'm missing something.

**Comment by vemoo** [comment]
> Interesting! I wonder if it is possible to make both scanner and watcher to use the same channel to output events. That is, I originally envisioned that [`TaskResult`](https://github.com/vemoo/rust-analyzer/blob/b4f06b05ab51a1cd6a2e883fe0d5c0b63cd8a3b6/crates/ra_vfs/src/io.rs#L19-L22) becomes an enum, and that all watching is handled entirely inside vfs.

I will try to implement that.

>  The `overlay` functions are not for watched files, they are specifically for "file contents in editor differs from contents on disk".

I figured something like that, because of how [`remove_file_overlay`](https://github.com/vemoo/rust-analyzer/blob/291d578938d7dc9b1f9bbd1174e444cc831531d9/crates/ra_vfs/src/lib.rs#L245-L262) was implemented, but I wasn't sure how the watcher events should interact with that. Now I have some questions:

- After thinking about it I see another flaw with the current watcher impl. All the blocking io operations happen on the main loop. To fix that [`WatcherChange`](https://github.com/vemoo/rust-analyzer/blob/b4f06b05ab51a1cd6a2e883fe0d5c0b63cd8a3b6/crates/ra_vfs/src/watcher.rs#L20-L25) should include the file contents. But that means that the watcher must know about ignored files to avoid reading them, maybe [`has_rs_extension`](https://github.com/vemoo/rust-analyzer/blob/b4f06b05ab51a1cd6a2e883fe0d5c0b63cd8a3b6/crates/ra_vfs/src/lib.rs#L63) is enough for now?

- Should [`VfsFileData`](https://github.com/vemoo/rust-analyzer/blob/b4f06b05ab51a1cd6a2e883fe0d5c0b63cd8a3b6/crates/ra_vfs/src/lib.rs#L75-L79) include something like `overlay_text: Option<Arc<String>>`? That way when a watcher event happens we won't overwrite it. Also we would avoid the blocking io operation on [`remove_file_overlay`](https://github.com/vemoo/rust-analyzer/blob/291d578938d7dc9b1f9bbd1174e444cc831531d9/crates/ra_vfs/src/lib.rs#L251) that's happening on the main loop now

- What should happen if there's a `WatcherChange` event but there's an overlay, should we update the `VfsFileData` but not generate a `VfsChange`?

**Comment by vemoo** [comment]
I've started looking at what's needed to use the same channel for scanner and watcher events and I think I have an idea of how it can be done.

- `Task` also needs to become an enum, with a variant for the current scanner task and a new variant for the watcher events. Something like:
```rust
enum Task {
  AddRoot(...),
  WatcherChange(...)
}
```

- `TaskResult` becomes an enum and the variant for the watcher includes the file contents, that way all the blocking io is performed on the io thread worker

This way we can send `Task::AddRoot` or `Task::WatcherChange` to the same channel and `Vfs::handle_task` would handle both cases

**Comment by matklad** [comment]
>But that means that the watcher must know about ignored files to avoid reading them, maybe has_rs_extension is enough for now?

The `Task` includes `pub(crate) filter: Box<Fn(&DirEntry) -> bool + Send>`, this should be used by both scanner and watcher. We might want to change `Fn` to some trait here, to allow filtering to work with both walkdir and notify APIs. But the filtering logic should be the same. In general, I'd prefer to think about this as a single operation: "bulk-scan the source root and then send notifications about updates". 

> Should VfsFileData include something like overlay_text: Option<Arc<String>>?

Yep, that would be the ideal solution. The simple solution would be to store `is_overlayed: bool` field, and just re-scan the text in `remove_overlay`. This approach has the nice property that we gurantee to read the text *after* overlay was disabled, so we neccessary got what was written to disk. I wouldn't worry to much about reading a single file synchronously in the main loop.

>What should happen if there's a WatcherChange event but there's an overlay, should we update the VfsFileData but not generate a VfsChange?

`VfsChange` should not be generated. As for update, `is_overlayed: bool` means that the event is just ignored, while `overaly_text: Arc<String>` will record the text in the *other* field. 

>I have an idea of how it can be done.

Yes, that's precisely the intention. We probably could do watching in the `io` module as well (or in a submodule of the io module.)

**Comment by vemoo** [comment]
I've made some progress [here](https://github.com/vemoo/rust-analyzer/tree/vfs-watch).

To be able to filter watcher events I've turned [`Task`](https://github.com/vemoo/rust-analyzer/blob/ea7667c226b373dcf98735d18fd1319b0ae15453/crates/ra_vfs/src/io.rs#L12-L19) into an enum:
```rust
pub(crate) enum Task {
    AddRoot {
        root: VfsRoot,
        path: PathBuf,
        filter: Box<Fn(&DirEntry) -> bool + Send>,
    },
    LoadChange(crate::watcher::WatcherChange),
}
```

And added another case [`TaskResult`](https://github.com/vemoo/rust-analyzer/blob/ea7667c226b373dcf98735d18fd1319b0ae15453/crates/ra_vfs/src/io.rs#L34-L38):
```rust
pub enum TaskResult {
    AddRoot(AddRootResult),
    HandleChange(WatcherChange),
    LoadChange(Option<WatcherChangeData>),
}
```

That way on `Vfs::handle_task` we can first filter: https://github.com/vemoo/rust-analyzer/blob/ea7667c226b373dcf98735d18fd1319b0ae15453/crates/ra_vfs/src/lib.rs#L219 and send the task back to the io to load the file contents, and the we load the data: https://github.com/vemoo/rust-analyzer/blob/ea7667c226b373dcf98735d18fd1319b0ae15453/crates/ra_vfs/src/lib.rs#L232.

There's another `notify` event that I didn't initially handle [`DebouncedEvent::Rescan`](https://docs.rs/notify/4.0.6/notify/enum.DebouncedEvent.html#variant.Rescan), but I think we should. It says:
> `Rescan` is emitted immediately after a problem has been detected that makes it necessary to re-scan the watched directories.

But unless we keep separate watchers per root we will have to reload all the roots. We could remove all files (except ones with overlay) and then send `Task::AddRoot` for each root.

I also figured out why the watcher thread wasn't shutting down. It was a bug in `notify`. I created a PR to fix it here: https://github.com/passcod/notify/pull/170

**Comment by matklad** [comment]
I've looked through the changes and they look good to me! I think it's OK to not handle `Rescan` to start with: given that nothing works at all at the moment, even without rescan this will be a huge improvement. I don't think we should send `Task::AddRoot` on `Rescan`. At least, we defeneltey should not emit `VfsChange::AddRoot` for the second time for a root.

>I also figured out why the watcher thread wasn't shutting down. It was a bug in notify

Awesome! I bet it was tricky to debug that! And it's cool that we actually hit that bug: this means that we do put some effort on our side to cleanup the threads properly. I think it's ok to just let that thread hang for the time being.

**Comment by vemoo** [comment]
The problem is that the `Watcher`s thread has a `Sender` for the `Worker`s channel, and since that `Sender` is not dropped the channel doesn't close so the worker also doesn't terminate. And that causes a bunch of tests to fail.

**Comment by passcod** [comment]
Note that Notify is more "passively maintained" than "frozen". If you need changes/features (or fixes, as you've seen!) and can contribute an impl I'll be more than happy to merge, even for breaking changes (with a higher threshold, tho). I'm just not going to spend lots of time on it.

Current estimation is that I won't release v5 before async/await is in stable rust, but that could change.

**Comment by matklad** [comment]
Awesome! Thanks for chiming in, @passcod !

**Comment by matklad** [comment]
Fixed!
