### ISSUE TITLE
Is there a setting to change the color of inlay hints?

### ISSUE THREAD

**Issue by schungx** [rust-analyzer/rust-analyzer#4334]
The current color is too similar to the code text, making code harder to read.  I'd prefer a much lighter color - you only need to read it when you want to know the type.

**Comment by SomeoneToIgnore** [comment]
Currently there's a way to change the text color using the `rust_analyzer.inlayHint` color setting:
https://github.com/rust-analyzer/rust-analyzer/blob/30eb458b4fa8adcecd8cbf731bd1cfa9a7a8b88b/editors/code/package.json#L504

There's a way to tweak hints' colors more, here are all possible options: https://vshaxe.github.io/vscode-extern/vscode/ThemableDecorationAttachmentRenderOptions.html , but this requires the code changes in here: https://github.com/rust-analyzer/rust-analyzer/blob/30eb458b4fa8adcecd8cbf731bd1cfa9a7a8b88b/editors/code/src/inlay_hints.ts#L46

**Comment by schungx** [comment]
Worked beautifully.  Thanks.

Add the following to `settings.json`:

```json
"workbench.colorCustomizations": {
    "rust_analyzer.inlayHint": "#bbbbbb"
},
```

Of course, change `#bbbbbb` to whatever color you fancy.

**Comment by dbsxdbsx** [comment]
@schungx , just update that the way you mentioned is no longer valid,  new way to figure this out is like this:
```
        "rust_analyzer.inlayHints.foreground": "#2E8B57",
        "rust_analyzer.inlayHints.background": "#3d3d3d48",
        // Overrides for specific kinds of inlay hints
        // "rust_analyzer.inlayHints.foreground.typeHints": "#fdb6fdf0",
        // // "rust_analyzer.inlayHints.foreground.paramHints": "#fdb6fdf0",
        // "rust_analyzer.inlayHints.background.chainingHints": "#6b0c0c81",
```
referring to : https://rust-analyzer.github.io/manual.html.

**Comment by schungx** [comment]
Somehow the new say is not working...  The old way with `workbench.colorCustomizations` works...  I suppose it'll be there for the up-coming version?

**Comment by Veykril** [comment]
Make sure your rust-analyzer is up to date, this change should be a bit older no already I believe.

**Comment by schungx** [comment]
It is the latest version already.

And it doesn't work, the setting is grayed out...  see screenshot:

![image](https://user-images.githubusercontent.com/661318/124911345-3869d500-e01f-11eb-9843-b50e7c3ef1a0.png)

**Comment by Veykril** [comment]
Ah, it should say `rust-analyzer.inlayHints.forground` instead of `rust_analyzer.inlayHints.forground`(note the `_` vs `-`).

**Comment by schungx** [comment]
Nope... changed it and still not working.  Still grayed out.

I think the setting is still not correct...

**Comment by lnicola** [comment]
That preference doesn't exist, it needs to be set in `workbench.colorCustomizations`, see https://rust-analyzer.github.io/manual.html#color-configurations.

**Comment by schungx** [comment]
> What do you mean by "the old way"?

The old way is the `workbencch.colorCustomizations` way...

**Comment by sgon00** [comment]
![Screenshot_20220320_013436](https://user-images.githubusercontent.com/1555508/159131965-bf948145-9c7d-4ed1-b2ff-8e9142886ff8.png)

Hi, I am running the latest version and copy the setup jsonc code from manuall. It just does NOT work at all. What's the problem?

I have no ideas why this bug is opened and closed several times and nobody really mentioned what the cause is and how to fix it.

**Comment by Plasmatium** [comment]
> That preference doesn't exist, it needs to be set in `workbench.colorCustomizations`, see https://rust-analyzer.github.io/manual.html#color-configurations. What do you mean by "the old way"?

This works for me
```js
{
  "workbench.colorTheme": "rustdoc dark",
  //   "editor.inlayHints.fontSize": 11,
  "editor.inlayHints.fontFamily": "Courier New",
  "workbench.colorCustomizations": {
    // Name of the theme you are currently using
    "[rustdoc dark]": {
      "editorInlayHint.foreground": "#888a",
      "editorInlayHint.background": "#0000"
      // Overrides for specific kinds of inlay hints
      // "editorInlayHint.typeForeground": "#fdb6fdf0",
      // "editorInlayHint.parameterForeground": "#fdb6fdf0",
    }
  }
}
```
<img width="936" alt="image" src="https://user-images.githubusercontent.com/13704796/198040644-53f0f2dc-4952-45cb-9a55-183c8d0b5a6b.png">

**Comment by yuhongyu879** [comment]
> > That preference doesn't exist, it needs to be set in `workbench.colorCustomizations`, see https://rust-analyzer.github.io/manual.html#color-configurations. What do you mean by "the old way"?
> 
> This works for me
> 
> ```js
> {
>   "workbench.colorTheme": "rustdoc dark",
>   //   "editor.inlayHints.fontSize": 11,
>   "editor.inlayHints.fontFamily": "Courier New",
>   "workbench.colorCustomizations": {
>     // Name of the theme you are currently using
>     "[rustdoc dark]": {
>       "editorInlayHint.foreground": "#888a",
>       "editorInlayHint.background": "#0000"
>       // Overrides for specific kinds of inlay hints
>       // "editorInlayHint.typeForeground": "#fdb6fdf0",
>       // "editorInlayHint.parameterForeground": "#fdb6fdf0",
>     }
>   }
> }
> ```
> 
> <img alt="image" width="936" src="https://user-images.githubusercontent.com/13704796/198040644-53f0f2dc-4952-45cb-9a55-183c8d0b5a6b.png">

hi @Plasmatium what theme and font do you use? its looks nice.

**Comment by Plasmatium** [comment]
Hi @yuhongyu879 please refer to the settings below. I remove the `[rustdoc dark]` block to make all themes affected 
```json
{
    "editor.fontFamily": "Cascadia Code PL",
    "editor.fontLigatures": true,
    "editor.fontSize": 14,
    "workbench.colorTheme": "Mariana Pro (Gray)",
    "editor.inlayHints.fontFamily": "Courier New",
    "workbench.colorCustomizations": {
        "editorInlayHint.foreground": "#888a",
        "editorInlayHint.background": "#0000",
    },
    "editor.tokenColorCustomizations": {
        "keywords": {
            "fontStyle": "bold"
        }
    },
}
```

**Comment by yoniamir** [comment]
@Plasmatium This worked for me. Thanks!

**Comment by mark-pictor-csec** [comment]
I tried to add @Plasmatium's `editorInlayHint` lines to a folder's `settings.js`. They had no effect, and when I moused over the settings I got an incredibly cryptic error, presented as a tooltip:

> This setting cannot be applied in this workspace. It will be applied when you open the containing workspace folder directly.

In retrospect, I probably should have interpreted this as meaning to put the settings in the workspace file, as I eventually tried that and it worked.

```jsonc
// workspace file
{
        // ...
	"settings": {
		"workbench.colorCustomizations": {
			"editorInlayHint.foreground":"#bc0a",
			"editorInlayHint.background":"#0000"
		}
	}
}
```

**Comment by piavgh** [comment]
> That preference doesn't exist, it needs to be set in `workbench.colorCustomizations`, see https://rust-analyzer.github.io/manual.html#color-configurations. What do you mean by "the old way"?

This works in 2023
