### ISSUE TITLE
Semantic colors don't match other languages

### ISSUE THREAD

**Issue by georgewfraser** [rust-analyzer/rust-analyzer#4335]
Semantic coloring is a huge improvement over the built-in textmate colors, especially for a tricky-to-color language like rust. But, the colors that are applied by rust-analyzer seem to contradict the color theme. Here is VSCode syntax coloring with semantic coloring off:

<img width="674" alt="Screen Shot 2020-05-05 at 10 19 52 PM" src="https://user-images.githubusercontent.com/1369240/81140630-f0cd5200-8f1e-11ea-8be1-23d78fea7ca8.png">

Here it is with semantic coloring on:

<img width="619" alt="Screen Shot 2020-05-05 at 10 18 14 PM" src="https://user-images.githubusercontent.com/1369240/81140644-fb87e700-8f1e-11ea-9ea5-1e15b88e694e.png">

We can see a couple of issues. First, all keywords are purple. This contradicts other VSCode languages, like typescript, where only some keywords (for example `if`) are purple, and most keywords are blue. Type names, which are all green in other languages, are inconsistent: struct names are blue (the color of keywords in other languages) but enum names are green (as expected).

I'd be happy to work on changing the implementation to better match the coloring of other languages, but first I'd like to understand if this is intended behavior.

**Comment by matklad** [comment]
For keywords, see https://github.com/microsoft/vscode/issues/94367. For enums and structs, we emit specific tags for types: `enum` for enum, `struct` for struct, etc. It's up to the color theme to color or not color them.

Other language "work" because they rely on regex-based  based textmate scopes much more than rust. 

Closing, as I belive this should be fixed in the color theme and not on our side.

**Comment by matklad** [comment]
Though, re-reading 94367, it seems like we can do better for keywords: https://github.com/rust-analyzer/rust-analyzer/pull/4353

**Comment by georgewfraser** [comment]
Help me understand---is it your view that, in the default Dark+ color theme, coloring struct type names like keywords is correct behavior? Or that it's a bug on the VSCode side? Or something else?

**Comment by georgewfraser** [comment]
This contradicts the behavior of, for example, the C++ extension, which colors struct type names like other type names:

<img width="186" alt="Screen Shot 2020-05-06 at 10 12 11 AM" src="https://user-images.githubusercontent.com/1369240/81207326-438c2580-8f82-11ea-9d21-9662db7dfd04.png">

**Comment by matklad** [comment]
>This contradicts the behavior of, for example, the C++ extension

What semantic token type does C++ give for structs?

I believe we correctly flag it as struct and declaration:

![image](https://user-images.githubusercontent.com/1711539/81207800-6d6b3980-8fce-11ea-8fd7-877d6548c33a.png)

**Comment by georgewfraser** [comment]
The VSCode C++ extension implemented "enhanced colorization" before VSCode defined a colorization API. It bypasses the colorization API and directly colors the tokens. So, it doesn't specify a semantic token type. However, it colors struct names the same as other type names:

<img width="186" alt="Screen Shot 2020-05-06 at 10 12 11 AM" src="https://user-images.githubusercontent.com/1369240/81317922-52d2a800-9042-11ea-8450-0134069306c9.png">

Having dug into this more, it's clear to me that this is a mistake in VSCode's default mappings for semantic tokens: https://github.com/microsoft/vscode/issues/97162

If they don't fix it, the solution is to simply define a rust-specific mapping from the semantic token type `struct` to the textmate scope `entity.name.type.struct`. The default mapping they currently have in place, `storage.type.struct`, is clearly intended for the struct *keyword*, not struct *type names*: https://macromates.com/manual/en/language_grammars

**Comment by matklad** [comment]
Oh, thanks for digging this up, fascinating find! I guess, we can paper over this by overriding the name on our side, let me cook up a PR... done, #4365.

**Comment by georgewfraser** [comment]
Syntax coloring is a small obsession of mine 😄 There are a couple other optimizations that could be done to improve client-side performance and user-experience of semantic coloring. I'm working on a PR.

**Comment by georgewfraser** [comment]
Here it is: #4383
