### ISSUE TITLE
if let Some / if let Ok postfix completions for Option<_> / Result<_>?

### ISSUE THREAD

**Issue by YaLTeR** [rust-analyzer/rust-analyzer#4348]
When an expression has a type of `Option<_>` or `Result<_>` it would be useful to have a quick way to turn that into an
```rust
if let Some($1) = expr {
    $2
}$3
```
or `if let Ok` respectively.

**Comment by matklad** [comment]
Yup, I think we should add `ifl` postfix completion. At the moment, one can do this:

![ifl](https://user-images.githubusercontent.com/1711539/81204861-267b4500-8fca-11ea-819a-7f1b4a5e7f81.gif)

**Comment by bnjjj** [comment]
Will try to resolve it this week

**Comment by bnjjj** [comment]
Example: 

![iflet](https://user-images.githubusercontent.com/5719034/81278447-fa0d0a80-9055-11ea-9c60-6095aface473.gif)
