### ISSUE TITLE
"Waiting for code actions" takes forever

### ISSUE THREAD

**Issue by Ten0** [rust-analyzer/rust-analyzer#4352]
Regularly when I'm trying to save a file, it freezes for a long time before actually saving the file.
VSCode ends up saying "Waiting for code actions", with an option to cancel. That is such a loss of time...
Recently, it has started doing that for longer than I had the patience to wait, so I have to click "Cancel" everytime I save a file, effectively making rust-analyzer unusable.

Also, cancelling seems to fire up a new rust-analyzer process without closing the previous one, eventually eating up all my RAM.

**Comment by matklad** [comment]
Hm, this sounds like we maybe crash or get stuck somewhere? Are there any stacktraces or run-away processes of rust-analyzer? A minimal repro would help!

**Comment by Ten0** [comment]
Unfortunately I can't provide the projects this triggers on and I do not recall hitting this issue on smaller projects (though "Waiting for code actions" still blocks saving file for some time there as well).
I was thinking if that was a recently introduced bug this issue would help fixing it regardless :/

**Comment by Ten0** [comment]
This is still a huge bother, though if I wait long enough it eventually saves.
Additionally though, I now have this error before the freeze triggers on the largest projects:

```
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'overflow depth reached', <::std::macros::panic macros>:2:4
stack backtrace:
   0: <unknown>
   1: core::fmt::write
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: std::panicking::rust_panic_with_hook
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <unknown>
  42: <unknown>
  43: <unknown>
  44: <unknown>
  45: <unknown>
  46: <unknown>
  47: <unknown>
  48: <unknown>
  49: <unknown>
  50: <unknown>
  51: <unknown>
  52: <unknown>
  53: <unknown>
  54: <unknown>
  55: <unknown>
  56: <unknown>
  57: <unknown>
  58: <unknown>
  59: <unknown>
  60: <unknown>
  61: <unknown>
  62: <unknown>
  63: <unknown>
  64: <unknown>
  65: <unknown>
  66: <unknown>
  67: <unknown>
  68: <unknown>
  69: <unknown>
  70: <unknown>
  71: <unknown>
  72: <unknown>
  73: <unknown>
  74: <unknown>
  75: <unknown>
  76: <unknown>
  77: <unknown>
  78: <unknown>
  79: <unknown>
  80: <unknown>
  81: <unknown>
  82: <unknown>
  83: <unknown>
  84: <unknown>
  85: <unknown>
  86: <unknown>
  87: <unknown>
  88: <unknown>
  89: <unknown>
  90: <unknown>
  91: <unknown>
  92: <unknown>
  93: <unknown>
  94: <unknown>
  95: <unknown>
  96: <unknown>
  97: <unknown>
  98: <unknown>
  99: <unknown>
 100: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
```

**Comment by JustDerb** [comment]
I'm getting the exact same stack trace, but at a file/line number:

```
thread '<unnamed>' panicked at 'overflow depth reached', /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/macros.rs:13:23
```

*(Note including stack trace, as it's the same one @Ten0 submitted)*

Looks to be just too much recursion...

**Comment by matklad** [comment]
Seems unactionable without minimal reproducible example/stacktrace with symbols.
