### ISSUE TITLE
Please also release fully statically linked executables

### ISSUE THREAD

**Issue by kuznero** [rust-analyzer/rust-analyzer#4354]
In NixOS for example it is necessary to `patchelf --set-interpreter` on each executable that is dynamically linked. And taking into account the way different editor plugins/extensions download updates it would be wise to ensure that it can run without additional steps to remedy problems like this.

An example of how it is possible to produce fully statically linked binaries in Rust can be found in the blog post [Building statically linked binaries in Rust](https://kuznero.com/post/rust/building-statically-linked-binaries/).

If it is going to be an accepted approach going forward, I can volunteer to craft a PR to produce such binary and make it part of the release flow if necessary.

**Comment by kiljacken** [comment]
We do know how to produce statically linked executables, and we did do it for a while. It does have one glaring issue for us right now: statically linked musl cannot `dlopen` which hinders support for proc macros.

Ideally we'll reach a point in rustc's lifecycle where all proc macros are sandboxed wasm, but that's still quite far out in the future.

We could possibly provide a static build as well, and force disable proc macro support in that build, but that seems like a lot of special casing. Maybe we can add a workaround for NixOS instead and call patchelf on the downloaded executable ourselves?

**Comment by kuznero** [comment]
Please have a look at the PR #4369 - this is a working example

**Comment by kuznero** [comment]
Closing, more explanation can be found in the first linked and closed pr.
