### ISSUE TITLE
Read bytesize of `Sized` types on hover.

### ISSUE THREAD

**Issue by iago-lito** [rust-analyzer/rust-analyzer#4355]
Since we can statically tell the type of a variable under cursor, and since the `sizeof` `Sized` types is also statically known,
would it be possible to read not only the type, but also the size on hover information?

(previously posted at [rls](https://github.com/rust-lang/rls/issues/1606) with no success)

**Comment by lnicola** [comment]
Duplicate of #4091. This is actually easier to implement in RLS right now.
