### ISSUE TITLE
VSCode gives "run" and "debug" options for a "main" method that's not in a binary

### ISSUE THREAD

**Issue by sazzer** [rust-analyzer/rust-analyzer#4356]
I've got my application set up so that there is a `main.rs` with a `fn main()` to run the application, but this almost immediately delegates to an `fn main()` inside `lib.rs`. This lets me write integration tests against the library crate, but still build an executable crate at the end.

This works great, with only one tiny detail. 

rust-analyzer in VSCode is giving me the "run" and "debug" actions for the main function inside `lib.rs` as well as inside `main.rs`, but obviously you can't actually do those.

<img width="402" alt="image" src="https://user-images.githubusercontent.com/66072/81265261-ac36d900-903a-11ea-8eca-9b893adf5be1.png">

Clicking on this "run" action then gives me:
```
> Executing task in folder service: cargo run --package xxx --lib -- <

error: Found argument '--lib' which wasn't expected, or isn't valid in this context

USAGE:
    cargo run --package <SPEC>

For more information try --help
The terminal process terminated with exit code: 1
```

**Comment by bnjjj** [comment]
Yes we have to check if we are in a lib or not. If we are in a lib I think rust-analyzer should not display Run | Debug. I will fix this
