### ISSUE TITLE
rust-analyzer cannot infer type from Vec.get

### ISSUE THREAD

**Issue by chuling** [rust-analyzer/rust-analyzer#4357]
I got the type information as `Option<&{unknown}>` from `v.get(idx)`'s result (v is a Vec).

[rust-lang/rls](https://github.com/rust-lang/rls) can infer type information from `Vec<T>.get` or `&v[some_idx]`(v is a Vec), while rust-analyzer seems not.

**Comment by flodiebold** [comment]
Duplicate of #2534 (`get` uses the same trait machinery).
