### ISSUE TITLE
Unwrap block on else blcok should not remove then block

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#4361]
Before:

```rust
fn add_body(fn_def: ast::FnDef) -> ast::FnDef {
    if fn_def.body().is_some() {
        return fn_def;
    } else {<|> 
        let body = make::block_expr(None, Some(make::expr_todo()));
        let body = IndentLevel(1).increase_indent(body);
        fn_def.with_body(body)
    }
}
```

After <kbd>ctrl+.</kbd> unwrap block :

```rust
fn add_body(fn_def: ast::FnDef) -> ast::FnDef {
    let body = make::block_expr(None, Some(make::expr_todo()));
    let body = IndentLevel(1).increase_indent(body);
    fn_def.with_body(body)
}
```

What is expected instead:

```rust
fn add_body(fn_def: ast::FnDef) -> ast::FnDef {
    if fn_def.body().is_some() {
        return fn_def;
    }
    let body = make::block_expr(None, Some(make::expr_todo()));
    let body = IndentLevel(1).increase_indent(body);
    fn_def.with_body(body)
}
```

cc @bnjjj

**Comment by bnjjj** [comment]
Ok got it ! What about the case for `else if` block ?

**Comment by matklad** [comment]
IntelliJ's approach is not directly applicable to us, as it, unlike VS Code, can show a nice UI for what is removed and what is kept. Not sure whats the expected behavior for `else if` block. Maybe just spliting the if-else chain into two?

```rust
if c1 {
  e1
} else if c2 {<|>
  e2
} else {
  e3
}
```

->

```
if c1 {
  e1
} 
e2
if c1 && !c2 {
  e3
}
```

though this is somewhat too fancy, so I am not sure it's worth doing.

**Comment by bnjjj** [comment]
Ok I will resolve this issue this weekend. By the way I have another suggestion about ˋelse if` block.  We can have the same behavior and just unwrap else if block and just drop the next blocks ? 

``ˋ

if c1 {
  e1
} else if c2 {<|>
  e2
} else {
  e3
}
ˋ``


`ˋ`

if c1 {
  e1
}
 e2


`ˋ`

Let me know what do you think about this behavior ?

**Comment by matklad** [comment]
>Let me know what do you think about this behavior ?

Dropping the other block feels somewhat wrong to me, but it's hard to say for sure without using the feature

**Comment by bnjjj** [comment]
IMHO making something like this `if !c1 && !c2 {` don’t worth and add complexity. 

I suggest to do my last proposal and wait for feedbacks if needed, or just don’t show the assist for `else if` blocks
