### ISSUE TITLE
Confusing error for match expr on a enum *self

### ISSUE THREAD

**Issue by zonyitoo** [rust-analyzer/rust-analyzer#4391]
Running on VSCode, rust-analyzer version: 2020-05-04 (6a48a94) .

Could be reproduce on Project's master branch:

https://github.com/shadowsocks/shadowsocks-rust/blob/master/src/relay/tcprelay/http_local.rs#L159

![image](https://user-images.githubusercontent.com/1067951/81476025-29806a80-9242-11ea-9b3e-d8337780de5a.png)

Can't reproduce by `cargo check` and `cargo build` works fine.

**Comment by flodiebold** [comment]
That's probably a duplicate of #4279, can you check the nightly?

**Comment by zonyitoo** [comment]
Oh, that seems related. Let me try with the nightly.
