### ISSUE TITLE
Semantic Highlighting: Self should semantically be a type alias

### ISSUE THREAD

**Issue by CryZe** [rust-analyzer/rust-analyzer#4398]
The semantic highlighting currently considers Self a type parameter, not a type alias.

This is likely caused by this line: https://github.com/rust-analyzer/rust-analyzer/blob/30eb458b4fa8adcecd8cbf731bd1cfa9a7a8b88b/crates/rust-analyzer/src/conv.rs#L59

**Comment by matklad** [comment]
Tricky! `Self` **is** a type parameter in traits, but it is a type alias in impls.

**Comment by lnicola** [comment]
Triage: now it's a type parameter in traits:

![image](https://user-images.githubusercontent.com/308347/105527023-d83edb00-5ceb-11eb-8c00-d542842fbd3e.png)

But a type in impls:

![image](https://user-images.githubusercontent.com/308347/105527058-e2f97000-5ceb-11eb-8cea-2bd42afa846d.png)

**Comment by flodiebold** [comment]
Isn't that correct?

**Comment by lnicola** [comment]
matklad said it should be a type alias in impls.

**Comment by flodiebold** [comment]
Ok, I wasn't sure whether there's a difference between type and type alias in semantic tokens.
