### ISSUE TITLE
Semantic Highlighting: Methods should be methods, fields should be fields

### ISSUE THREAD

**Issue by CryZe** [rust-analyzer/rust-analyzer#4399]
Methods are currently considered functions and fields are currently considered members. It would be better to categorize them as methods and fields as that more accurately describes what they are.

It seems like many extensions are super inconsistent in what they do here. So for example, member, which is currently being used for fields in rust-analyzer, is used for methods in TypeScript. This makes it impossible to properly create a theme at all that works across both TypeScript and Rust (and others).

**Comment by matklad** [comment]
I *think* this is covered by #4397 ? we now use property for fields and member for metods

**Comment by CryZe** [comment]
Yeah I think this is done.
