### ISSUE TITLE
Create Module quick action not present in integration tests

### ISSUE THREAD

**Issue by sazzer** [rust-analyzer/rust-analyzer#4401]
Within the `src` directory, I've been making great use of the quick action to create a new module - via the lightbulb menu.

Within the `tests` directory, I don't get this option. I only get this:
<img width="315" alt="image" src="https://user-images.githubusercontent.com/66072/81484487-a2c98e80-923d-11ea-9154-dac2d44ca28e.png">

Even though hovering the same line gives this:
<img width="659" alt="image" src="https://user-images.githubusercontent.com/66072/81484494-b1b04100-923d-11ea-8493-876fef27be93.png">

**Comment by matklad** [comment]
Minimal reproducible example is needed, quick testing shows that it works for me.

**Comment by sazzer** [comment]
I'm actually noticing quite a few things that aren't working correctly in
the tests directory, so it's probably something I've done.
I'll see if I can get you a minimal example.

Cheers
