### ISSUE TITLE
Cannot jump to symbols used with derive macro

### ISSUE THREAD

**Issue by anirudh-chhangani** [rust-analyzer/rust-analyzer#4413]
I am trying to setup sublime text 3 with rust-analyzer and LSP package on windows with rust msvc toolchain 1.43.0 stable, for the most part the project is indexed properly but I cannot jump to symbols used with derive macro,  is this expected behaviour?

![Screen_Recording_2020-05-09_at_12 05 22_PM(1)](https://user-images.githubusercontent.com/2513446/81502443-a3c0f580-92fb-11ea-8c7f-0f41a62b1c01.gif)

**Comment by edwin0cheng** [comment]
Yes, currently got-definition for derive is not implemented yet.
