### ISSUE TITLE
Cannot jump to symbols from inside of dependencies.

### ISSUE THREAD

**Issue by anirudh-chhangani** [rust-analyzer/rust-analyzer#4415]
I am trying to setup sublime text 3 with rust-analyzer and LSP package on windows with rust msvc toolchain 1.43.0 stable, I am able to jump to symbols from the project but cannot jump once I reach the symbol defined in one of the crates, probably the dependencies are not getting indexed properly? Is this expected behavior?

![Screen Recording 2020-05-10 at 8 44 51 PM(1)](https://user-images.githubusercontent.com/2513446/81503329-a8d47380-9300-11ea-9676-29a86707895c.gif)

**Comment by rsignavong** [comment]
+1

I've got the same error on vim with coc-rust-analyzer.

The Goto jump definition doesn't work anymore on the lastest release.

**Comment by bjorn3** [comment]
I did guess that for some reason sublime text thinks that the rust-analyzer instance for your project doesn't apply to the source files of the dependency. In vs code you can always click on Go to Definition. Even when rust-analyzer doesn't know what the definition is. Rust-analyzer doesn't tell if it knows the definition of a symbol to the editor, until it is asked to return them.

**Comment by rsignavong** [comment]
But I got the same error on vim, I still work on the same project for several months.
The goto definition worked fine until I upgrade to the lastest release (rust-analyzer 6a48a94)

**Comment by anirudh-chhangani** [comment]
Seems like a editor issue https://github.com/sublimelsp/LSP/issues/997, please feel free to close. Thanks.
