### ISSUE TITLE
Using `cross`

### ISSUE THREAD

**Issue by fenollp** [rust-analyzer/rust-analyzer#4425]
Is there any way to tell RA to use `cross` instead of cargo/rustc?

Building for `armv7-unknown-linux-musleabihf` is easiest when done with `cross` however RA doesn't seem to pick up on that (and I'm not sure how it would since there's no mention of this in Cargo.toml).

The build cache seems to get thrashed every time I switch from RA to my `cross` calls.

**Comment by bjorn3** [comment]
You can use the `rust-analyzer.checkOnSave.overrideCommand` config option. Note: it must contain `--message-format=json`.
