### ISSUE TITLE
`GLIBC_2.18' not found -- required by rust-analyzer-linux

### ISSUE THREAD

**Issue by rdfriese** [rust-analyzer/rust-analyzer#4426]
I'm using VSCode Remote-ssh, the plugin and server install fine, unfortunately my system has an older version of glibc (updating this system is not easily possible). Compiling myself isn't a big deal, but would it be possible for the released binaries to be compiled on a system with an older version of glibc? I'm lazy and being able to use the auto update feature is quite nice!

**Comment by bjorn3** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/4157#issuecomment-623971837

> no, no specific plans -- the current assumption is that for most users the binaries we publish are fine. SO, I don't think it makes sense to make our current CI more complicated to get the long tail. Once we ship via rustup, that should be fixed.

**Comment by matklad** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/4427 might, or might not fix it. I think I'll close this issue as:

* I don't think it makes sense for us to make CI more complicated to handle the long tail
* the point would become moot once we ship via rustup

**Comment by rdfriese** [comment]
Understandable, figured I would ask, thanks for the quick response and great work!

**Comment by lnicola** [comment]
If you're on CentOS, that PR won't help, unfortunately.
