### ISSUE TITLE
Diagnose and prohibit the use #[doc(hidden)] symbols of external crates

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#4433]
`#[doc(hidden)]` 99% of the time is used as a hack to export private symbols for various reasons like macro generated code that needs access to them. Unfortunately, no existing tool like `clippy` provides a diagnostic for this one and this is not immediately evident that you are using private symbols.
It can accidentally happen so that you just follow the completions for the needed public symbol and find hints for private modules (which are in fact `#[doc(hidden)]`) or (**I haven't checked**) auto-import instrumentation may violate this convention for you.

The feature:
- `#[doc(hidden)]` symbols either should not appear as completion items or (maybe this can be configured by a feature flag) should be outlined in the completion list so that they stand out.
- All usages of `#[doc(hidden)]` symbols from external crates are underlined with a warning diagnostic

**Comment by matklad** [comment]
> this is not immediately evident that you are using private symbols.

Not sure about this, I think a convention is to use `__names` for doc hidden symbols, so it is pretty clear that something's off.

**Comment by Veetaha** [comment]
This is not always the case. And I often see people not following this convention.

**Comment by Lokathor** [comment]
As a data point, my GL bindings generator generates hundreds of items, and to keep the rustdoc clear I mark most of it as `doc(hidden)` and just expect that "power users" of the crate will just call the hidden stuff.

So hidden doesn't always mean private, sometimes it's just genuinely "most people don't care, don't show this to them".

**Comment by matklad** [comment]
Yeah, I guess we should just take that into account while sorting completions, once we implement that
