### ISSUE TITLE
Proposal: compare binary version by release

### ISSUE THREAD

**Issue by dotSlashLu** [rust-analyzer/rust-analyzer#4437]
Hi, right now it seems every time the Code plugin is upgraded, the rust-analyzer binary has to be downloaded again.

I don't know nothing about vs code plugin API, but this seems to be comparing the last saved version(state.serverVersion?) with the current plugin version, which is irrelevant of the binary version, resulting re-download of rust-analyzer every time:
https://github.com/rust-analyzer/rust-analyzer/blob/8295a9340c1fbda805497035054ead0b10c0d88e/editors/code/src/main.ts#L222

Is it possible to match `rust-analyzer --version` with Code plugin version so that if the plugin doesn't need a newer rust-analyzer we don't have to download the same binary again?

Thanks!

**Comment by matklad** [comment]
We upgrade binary and vs code plugin in lockstep. Every time there's a new plugin version, there's a new server binary.

**Comment by Veetaha** [comment]
The server binary is updated way more often than the plugin and it **always** needs to be redownloaded on an update.
To ease the routine of approving the downloading you can add this to your `settings.json`:
```json
{
    "rust-analyzer.updates.askBeforeDownload": false
}
```

**Comment by dotSlashLu** [comment]
Ok I understand. There're some network issues with my PC running VSCode, so i always get the stable binary from the github release page. Some times when the plugin is updated and requested to download a newer binary but I saw no new release.
