### ISSUE TITLE
Recursive calls of a local function are not resolved

### ISSUE THREAD

**Issue by sanbox-irl** [rust-analyzer/rust-analyzer#4438]
Hello!

The following is working as intended:

![image](https://user-images.githubusercontent.com/31973761/81741919-21981480-9454-11ea-98c4-997dd3eb91fa.png)

But when we try to call the function inside itself: 
![image](https://user-images.githubusercontent.com/31973761/81741948-2d83d680-9454-11ea-956d-d614c1b535cd.png)

We do not get the appropriate autocomplete option.

Not uber essential, but just wanted to put the issue up so it's known

**Comment by bnjjj** [comment]
Maybe I'm wrong but as far as I know for now in rust-analyzer declaring `function` or `trait` or `impl` inside a function body is not already supported.

**Comment by lnicola** [comment]
I thought so, but apparently it's better supported now than it used to be. Notice that the function is resolved properly in the first screenshot.

**Comment by sanbox-irl** [comment]
Yes -- Rust analyzer now supports local functions in some manner! I actually think it used to support this thing, but not positive....

**Comment by lnicola** [comment]
Blocked on #1559.

**Comment by pksunkara** [comment]
@lnicola This should be actionable now.

**Comment by jonas-schievink** [comment]
This is fixed, I've added a test in https://github.com/rust-analyzer/rust-analyzer/pull/8076

**Comment by sanbox-irl** [comment]
thank you all!
