### ISSUE TITLE
Also underline trait bounds for current argument in tooltip

### ISSUE THREAD

**Issue by tmcguire** [rust-analyzer/rust-analyzer#4442]
The tooltip that is shown when calling a function underlines the current argument, which is really useful. Screenshot:
![Screenshot_20200513_002414](https://user-images.githubusercontent.com/1164876/81751919-b6306000-94b0-11ea-8a43-764751ed38c0.png)

It would be useful if the trait bound for the current argument is also underlined. In the case of the screenshot, it would underline `Into<Event>`, and on the next argument, `cb`, it would underline `FnMut(&mut Cursive) + static`.

Not sure if this can be generalized for more complex argument types and trait bounds though.

**Comment by matklad** [comment]
I belie this is not possible to do with the current LSP API, so closing this as a wont fix.
