### ISSUE TITLE
Run doctest does not work in impl trait blocks

### ISSUE THREAD

**Issue by fehrnah** [rust-analyzer/rust-analyzer#4449]
On VScode, the Run doctest does not work if the doctest is in a trait impl block.

Cargo test is called on `Struct::function` instead of `Struct::Trait::function`

**Comment by matklad** [comment]
cc @bnjjj 

-

**Comment by bnjjj** [comment]
Ok will fix it this weekend. @fehrnah can you provide a minimal example to help me reproduce ?

**Comment by Woyten** [comment]
In fact, any documented function that is not a module-level function can't work. The fix seems straight-forward but I believe that there are some tricky cases like generics and impls of the same trait for different structs in the same module.
