### ISSUE TITLE
Environment variables when running tests

### ISSUE THREAD

**Issue by sazzer** [rust-analyzer/rust-analyzer#4450]
Rust Analyzer makes it really easy to run tests as you're authoring them in the editor - just using the "run test" action above the test name.

However, it would be really useful to be able to specify some environment variables when doing this - in particular, the RUST_LOG environment variable would allow for me to see logging output direct in VSCode when running these tests, whereas right now I need to go and run them in a terminal manually.

Cheers

**Comment by vsrs** [comment]
Implemented in #4448 via a test specific launch.json configuration.

**Comment by daxpedda** [comment]
As far as I understand there is no way to set environment variables for all tests?

**Comment by vsrs** [comment]
> As far as I understand there is no way to set environment variables for all tests?

Not at the moment. I'll push relevant PR this week.

**Comment by daxpedda** [comment]
Oh wow, thank you!
Should we re-open this issue until then, or should I file a seperate one?

**Comment by vsrs** [comment]
Either would be fine with me.

**Comment by daxpedda** [comment]
Let's re-open than, we need a member to do that: @matklad?
