### ISSUE TITLE
code action kind set to empty string

### ISSUE THREAD

**Issue by tspiteri** [rust-analyzer/rust-analyzer#4458]
Code actions can have a kind which is an empty string.
```
Received response 'textDocument/codeAction - (283)' in 5ms.
Result: [
  {
    "title": "Change visibility to pub(crate)",
    "kind": "",
    ...
```

I think if the kind is not known it should not be set. For example emacs lsp-ui will by default filter code actions, and it will ignore kind nil, but will filter out kind `""` (https://github.com/emacs-lsp/lsp-ui/issues/443).

**Comment by tspiteri** [comment]
Hmm, looking at https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction shows an empty kind
```
/**
 * A set of predefined code action kinds.
 */
export namespace CodeActionKind {

	/**
	 * Empty kind.
	 */
	export const Empty: CodeActionKind = '';
```
So I was probably wrong and I'm thinking this is not a rust-analyzer bug (though I really don't know anything about the LSP protocol).

**Comment by matklad** [comment]
Yeah, I think this works as intended
