### ISSUE TITLE
Rust Analyzer spawns a lot of instances when working on Firefox 

### ISSUE THREAD

**Issue by djrenren** [rust-analyzer/rust-analyzer#4459]
(I couldn't fit all of them in this screenshot but hopefully it gets the point across)
![image](https://user-images.githubusercontent.com/634666/81981009-a6726200-95fd-11ea-840e-87c9375d4ef0.png)

I'm not sure why this is, but it seems excessive. Plus the fact that they're all taking almost the exact same amount of RAM seems to indicate that they're redundant instances.

Is this somehow to do with the workspace structure? Because this happens even when I open a small crate in the hierarchy.

**Comment by bjorn3** [comment]
You are using htop, right? I think you didn't disable the option to show every thread of a process separately.

https://unix.stackexchange.com/questions/10362/why-does-htop-show-more-process-than-ps

**Comment by lnicola** [comment]
Those are threads, you can usually recognize them by the green foreground.

**Comment by matklad** [comment]
Though, we probably shoudn't spawn that many threads either....

I think we currently spawn:

* num_cpu threads for our threadpool
* num_cpu threads for rayon thread pool
* main_loop thread
* couple of threads for VFS
* couple of threads for LSP communication
* couple of threads for `cargo check`

We probably should find a way to collapse two threadpools....

**Comment by djrenren** [comment]
Sorry for the bogus bug. But yeah num_cpus is probably overkill when working on servers. My  server at work reports 96 cores so that's a lot of threads. Maybe we should have a default sensible limit with a config option to override?
