### ISSUE TITLE
Assist idea: extract enum variant to struct

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#4468]
(and back)

**Comment by matklad** [comment]
Yup, we should totally steal this from IntelliJ :D

**Comment by mcrakhman** [comment]
I will look into that :-)

**Comment by mcrakhman** [comment]
Created a PR for that: https://github.com/rust-analyzer/rust-analyzer/pull/4576

**Comment by matklad** [comment]
Status: this works for tuple variants, but is still not implemented for record variants.

**Comment by pksunkara** [comment]
I think this can be closed, right?
