### ISSUE TITLE
Pattern match with match ergonomics in lambda arguments leads to {unknown} type

### ISSUE THREAD

**Issue by rkuhn** [rust-analyzer/rust-analyzer#4476]
Code is in [this gist](https://gist.github.com/rkuhn/1f48b322ed16ecf046a40ae1bd45c5c0).

This works:
![image](https://user-images.githubusercontent.com/470469/82115173-78a62e00-9761-11ea-82fd-9786af4def80.png)

This does not:
![image](https://user-images.githubusercontent.com/470469/82115151-59a79c00-9761-11ea-8485-12b872edb093.png)

**Comment by flodiebold** [comment]
Yeah, currently we 1. go through the patterns to establish their types and then 2. unify with the closure type; but to make match ergonomics work I think we have to 1. go through the parameters just to get any explicitly annotated types, 2. unify with the closure type and 3. go through the patterns, using the parameters from the now-unified closure type as expected types...

**Comment by rkuhn** [comment]
Meta-question: rustc must already do this, can this not be reused? And if not (due to incremental analysis), would it make sense that rustc uses the rust-analyzer code at some point in the future? It feels weird to have this code duplication, which in my experience (e.g. with Scala) always leads to inconsistencies in the IDE.

**Comment by flodiebold** [comment]
That's a long-term goal (librarification), but for type inference it's still far off.

**Comment by rkuhn** [comment]
That’s awesome!
