### ISSUE TITLE
Wrong "Syntax Error: attributes are not allowed on IF_EXPR"

### ISSUE THREAD

**Issue by DustinByfuglien** [rust-analyzer/rust-analyzer#4478]
RA displays error "Syntax Error: attributes are not allowed on IF_EXPR" when no error is with cargo check.

![screen](https://user-images.githubusercontent.com/18250092/82116261-2ff67100-9771-11ea-9ccb-e0edf2bbefb2.png)

**Comment by bjorn3** [comment]
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4386.

**Comment by DustinByfuglien** [comment]
oh sorry.
