### ISSUE TITLE
Some tests fixtures do not support metadata

### ISSUE THREAD

**Issue by svitalij** [rust-analyzer/rust-analyzer#4480]
Such a test if you add it to `crates\ra_ide\src\call_hierarchy.rs` does not pass. 
```rust
#[test]
fn test_call_hierarchy_in_tests_mod() {
    check_hierarchy(
        r#"
        //- /lib.rs cfg:test
        fn callee() {}
        fn caller1() {
            call<|>ee();
        }

        #[cfg(test)]
        mod tests {
            use super::*;

            #[test]
            fn test_caller() {
                callee();
            }
        }
        "#,
        "callee FN_DEF FileId(1) 0..14 3..9",
        &[
            "caller1 FN_DEF FileId(1) 15..45 18..25 : [34..40]",
            "test_caller FN_DEF FileId(1) 93..147 108..119 : [132..138]",
        ],
        &[],
    );
}
```

<details><summary>Run log</summary><pre>
thread 'call_hierarchy::tests::test_call_hierarchy_in_tests_mod' panicked at 'called `Option::unwrap()` on a `None` value', crates\ra_ide\src\call_hierarchy.rs:161:30
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\fmt\mod.rs:1063
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\io\mod.rs:1426
   5: std::sys_common::backtrace::_print
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:204
   8: std::panicking::default_hook
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:224
   9: std::panicking::rust_panic_with_hook
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:470
  10: std::panicking::begin_panic_handler
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:378
  11: core::panicking::panic_fmt
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\panicking.rs:85
  12: core::panicking::panic
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\panicking.rs:52
  13: core::option::Option<alloc::vec::Vec<ra_ide::call_hierarchy::CallItem>>::unwrap<alloc::vec::Vec<ra_ide::call_hierarchy::CallItem>>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\macros\mod.rs:10
  14: ra_ide::call_hierarchy::tests::check_hierarchy
             at .\src\call_hierarchy.rs:161
  15: ra_ide::call_hierarchy::tests::test_call_hierarchy_in_tests_mod
             at .\src\call_hierarchy.rs:271
  16: ra_ide::call_hierarchy::tests::test_call_hierarchy_in_tests_mod::{{closure}}
             at .\src\call_hierarchy.rs:270
  17: core::ops::function::FnOnce::call_once<closure-0,()>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\ops\function.rs:232
  18: alloc::boxed::{{impl}}::call_once<(),FnOnce<()>>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\liballoc\boxed.rs:1017
  19: panic_unwind::__rust_maybe_catch_panic
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libpanic_unwind\lib.rs:86
  20: std::panicking::try
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panicking.rs:281
  21: std::panic::catch_unwind
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libstd\panic.rs:394
  22: test::run_test_in_process
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libtest\lib.rs:542
  23: test::run_test::run_test_inner::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libtest\lib.rs:451
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test call_hierarchy::tests::test_call_hierarchy_in_tests_mod ... FAILED
</pre></details>

Note the **cfg:test** metadata. At the same time fixtures with metadata work great in the tests from other crates:
https://github.com/rust-analyzer/rust-analyzer/blob/9322790066fe86056965332078bed74ff7f77293/crates/ra_hir_def/src/find_path.rs#L510-L513

https://github.com/rust-analyzer/rust-analyzer/blob/9322790066fe86056965332078bed74ff7f77293/crates/ra_assists/src/handlers/auto_import.rs#L482-L486

**Comment by vsrs** [comment]
Ups, mixed up the account.

To my mind, the root of the problem is that [ra_ide::MockAnalysis](
https://github.com/rust-analyzer/rust-analyzer/blob/9322790066fe86056965332078bed74ff7f77293/crates/ra_ide/src/mock_analysis.rs#L21) does not use fixture metadata at all, treating [FixtureEntry::meta field](https://github.com/rust-analyzer/rust-analyzer/blob/c5c07c2a0a1b4809c5aacef3c8e90034d00c3b03/crates/test_utils/src/lib.rs#L160) just like a path.

I tried to reuse existing logic from https://github.com/rust-analyzer/rust-analyzer/blob/c5c07c2a0a1b4809c5aacef3c8e90034d00c3b03/crates/ra_db/src/fixture.rs#L248 
and looks like it works. All tests passed, including above-mentioned one. You can see my solution here: https://github.com/rust-analyzer/rust-analyzer/compare/master...vsrs:fixture_meta.

Should I submit it as a pull request or is some one already working on a better solution?
