### ISSUE TITLE
Custom `rustfmt` commands cannot use relative executable paths

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-analyzer/rust-analyzer#4486]
While trying to make `rust-analyzer` use the bootstrap version of `rustfmt` inside `rustc`, @jonas-schievink discovered that using a relative path to `rustfmt` won't work:

> Ah, looks like it adjusts the working dir dynamically, so it can't find the command with a relative path

https://github.com/rust-analyzer/rust-analyzer/blob/d51c1f62178c383363a2d95e865131d9a7b969d0/crates/rust-analyzer/src/main_loop/handlers.rs#L651-L655

As a workaround, you can specify an absolute path, but I was thinking we could canonicalize the first "shell word" if it looks like a path (e.g., `./rustfmt` or `build/rustfmt` but not `rustfmt2`). This would require some sort of library that can do shell word-splitting, however. Perhaps there is a better way?

The [`which` crate](https://docs.rs/which/3.1.1/which/) would be helpful for part of this.

**Comment by RalfJung** [comment]
Curiously, relative paths *do* work for `rust-analyzer.checkOnSave.overrideCommand`, so it is somewhat surprising that they do not work for other overrides.

**Comment by ecstatic-morse** [comment]
I assume it's because `checkOnSave` doesn't change the `current_dir` like `rustfmt` does.

**Comment by oxalica** [comment]
According to [the doc](https://doc.rust-lang.org/stable/std/process/struct.Command.html#method.current_dir), `current_dir` **may** effect the resolution of relative program name. It's better to canonicalize the relative command path first.

But why do we need to set `current_dir` for rustfmt here?

**Comment by matklad** [comment]
>But why do we need to set current_dir for rustfmt here?

Not sure there's a super-grand design here, but we do want rustfmt to pick up rustfmt.toml. Hm, is tihs right at all though? Like if I run `rustfmt foo/bar/barz/qux.toml`, will it pick the `rustfmt.toml` at `foo/bar/rustfmt.toml`? I think it should, so this current_dir patching could be removed....

Separately, I feel that semantics of relative paths in config should be independent of the cwd of the language server.

**Comment by lnicola** [comment]
@ecstatic-morse Can you test this again? The `chdir` was removed at some point and added back in #6973, but only for the default (non-overridden) case.

(Marking `S-actionable`, if you look at this in the future and the OP hasn't answered, ping me so we can close it.)

**Comment by RalfJung** [comment]
I now set the rustfmt command to `./build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt` and that seems to work here. :)

**Comment by mrchantey** [comment]
Is it the expected behavior that this vs code setting should not work?
```json
{
"rust-analyzer.rustfmt.extraArgs": [
  "--config-path",
  "./config",
  ]
}
```
If so, what is the workaround for a file in `./config/rustfmt.toml`? At the moment I'm using an absolute path in workspace settings but thats not portable:
```json
{
"rust-analyzer.rustfmt.extraArgs": [
  "--config-path",
  "C:/Users/Example/Project/config",
  ]
}
```
