### ISSUE TITLE
rust-analyzer shows the wrong inferred generic type parameter

### ISSUE THREAD

**Issue by RalfJung** [rust-analyzer/rust-analyzer#4487]
I tried using rust-analyzer on the rustc workspace for the first time and was extremely impressed that it actually "just works"! That's really awesome.

But I found one thing that is curious: when I open `src/librustc_mir/interpret/place.rs` and go to the `ref_to_mplace` functions and hover `let mplace` to show its inferred type, it shows `MemPlace<()>`. That is not correct, it should be `MemPlace<Tag>` or `MemPlace<M::PointerTag>`. This seems to affect most of the Miri engine, not just this specific example.

Maybe this is expected because using rust-analyzer on rustc itself is kind of stretching things a bit, but I figured I'd let you know regardless. :)

**Comment by flodiebold** [comment]
Hm, interesting. There's a lot of places where the type parameter defaults to `()` there, so it's likely that in some location there, we wrongly use the default instead of inferring the type.

**Comment by RalfJung** [comment]
`()` is indeed the default parameter for `MemPlace`, yes.

**Comment by flodiebold** [comment]
@RalfJung please try with the new release (which I hope includes #4765), this may be fixed now.

**Comment by RalfJung** [comment]
@flodiebold is there a way I can trigger the client to update? Do I need to switch to RA nightly for this?

**Comment by flodiebold** [comment]
AFAIK the way it works with the VSCode plugin is that you should get a plugin update and the updated plugin will download the updated binary. I think it should be in the weekly version released today.

**Comment by RalfJung** [comment]
It says all extensions are up-to-date, but didn't update today yet. My RA extension version is 0.2.199.

**Comment by RalfJung** [comment]
Oh, it did update, it just didn't tell me... strange.

**Comment by RalfJung** [comment]
Yes, it now says `MPlace<Tag>`, amazing. :)
