### ISSUE TITLE
Semantic Highlighting: give different colors to structs, generics, and traits

### ISSUE THREAD

**Issue by StevenDoesStuffs** [rust-analyzer/rust-analyzer#4507]
First, thanks for all the work on rust-analyzer; it really is amazing!

Anyhow, currently, structs, generics, and traits all have the same color, producing syntax highlightings like this: 
![Screenshot_20200518_195655](https://user-images.githubusercontent.com/13265529/82273064-080a3780-9942-11ea-8ecc-c8eaa747a61b.png)

At the same time, the same colors are also used for modules
![Screenshot_20200518_202624](https://user-images.githubusercontent.com/13265529/82274477-dc894c00-9945-11ea-897f-93207ffc3174.png)

**Comment by matklad** [comment]
Note that we already produce different semantic tags for these entities, it's up to the color scheme to color them differently. I don't think we can do anything on our side here, but cc @georgewfraser

**Comment by georgewfraser** [comment]
It's quite easy to change this in your `settings.json`. At some point, we should make a rust-specific color theme and distribute it through the VSCode marketplace.

**Comment by StevenDoesStuffs** [comment]
Actually that's exactly what I just did (well, the settings,json part, not the rust-specific color theme part). I used colors from material-darker. One issue is, you can't really mess with the syntax highlighting for only rust using settings,json, at least not for everything.
