### ISSUE TITLE
Strip underscores from function arguments for completion

### ISSUE THREAD

**Issue by YaLTeR** [rust-analyzer/rust-analyzer#4510]
```rust
fn innermost(_marker: i32) {

}

fn intermediate(marker: i32) {
    innermost<complete here>
}

fn main() {
    let marker = 0;
    intermediate(marker);
}
```
![изображение](https://user-images.githubusercontent.com/1794388/82291180-33783b00-99b1-11ea-9ff6-3d912973502b.png)

I'm using this pattern for statically enforcing "being on the main thread"—the marker is a special struct that's unsafely instantiated at known points "on the main thread" and then passed down as arguments to functions that must only be called from the main thread. Naturally, the inner-most functions accept the marker with an underscore as they don't actually use it (all they need is the fact that the caller has one). However, this means that when completing these innermost functions I get a `_marker` completion instead of `marker` and have to fix it manually.

**Comment by kuy** [comment]
I'm new to rust-analyzer. I'd like to try this issue as first contribute!
