### ISSUE TITLE
"ETXTBSY text file is busy" preventing extension from working

### ISSUE THREAD

**Issue by phiresky** [rust-analyzer/rust-analyzer#4511]
An older version of the extension apparently started the `~/.config/Code - OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux` binary a few days ago, and it is still running on my computer (probably a different bug).

Now, the prompt "Language server version xyz not found. Download?" is shown, but on pressing Download the prompt just disappears and nothing happens, causing the extension not to work at all.

I only found the cause by opening developer tools, which shows the error "ETXTBSY text file is busy". This error means that a process is trying to modify a binary that is currently running, which is not allowed by POSIX (i think). It can easily be fixed by instead of changing the existing binary just removing it (which is fine even if it is running) and then writing a new file to the same location. [example](https://stackoverflow.com/questions/1893235/etxtbsy-and-how-to-override-it)

This is not fixed by uninstalling and reinstalling the VSCode extension, nor by manually removing ~/.vscode-oss/extensions/matklad.rust-analyzer*, since the binary in in the globalStorage directory.

I fixed it for myself using `rm ~/.config/Code - OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux'`, but it would be good if at least that error was shown or the method of unlinking was used.

**Comment by lnicola** [comment]
See also https://github.com/rust-analyzer/rust-analyzer/issues/4469.

Anyway, do you still have that instance running? It's perfectly fine to kill it.

**Comment by matklad** [comment]
I think we recently added work-around for this on the client side.
