### ISSUE TITLE
Reverse index for auto-import

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#4515]
For many functions in rust-analyzer, we need an ability to find a path to a certain item, that can be used in an import statement. At the moment, we are doing this in a rather naïve way, by iterating literarly every module and every item, and checking "can we import from here":

https://github.com/rust-analyzer/rust-analyzer/blob/5c1c23ecc7c94fae0948abe8af7a700e42e20921/crates/ra_hir_def/src/find_path.rs#L225-L226

Naturally, if we we do this for many names, we get quadratic behavior and #4498. 

I think we should solve this by pre-computing an *index*, which allows finding import paths quickly. I imagine a query like this:

```rust
fn import_map(crate: Crate) -> Arc<FxHashMap<ModuleDefId, ModPath>>
```

This query should walk the `crate_def_map` and collect all items and reexport, computing the best importing path for each item. Note that the query should only consider `pub` items and re-exports. Ie, this idex would only be usable when importing an item from external crate. 

For imports within a crate, I think we can avoid an index and just use the current "iterate all module" strategy, or even something simpler like "compute path to root, and look at the modules along this path".

**Comment by matklad** [comment]
Hm, actually, while we are at it, we might also return an `fst` with names, alongside the `HashMap`, which would allow us to lookup names during completion...

**Comment by matklad** [comment]
cc @jonas-schievink and @SomeoneToIgnore ^^

**Comment by SomeoneToIgnore** [comment]
> `fst`

That would be great to add to reuse in `ImportsLocator` instead of the symbol database search.
Also it looks like `ImportsLocator` and `importable_locations_in_crate` function logic intersects, so I wonder if we can deduplicate it.

Can you provide any coded pointers for `fst`?
I can tackle it on the weekend.

**Comment by matklad** [comment]
Sorry, should have left a code pointer. FST is what we use in `symbol_index.rs` to bulid the search index: https://github.com/rust-analyzer/rust-analyzer/blob/1bc1f28bc58b2dbcf8f8f548c277e2c90e3075cd/crates/ra_ide_db/src/symbol_index.rs#L190-L226

**Comment by jonas-schievink** [comment]
I've started work on an `ImportMap` here: https://github.com/jonas-schievink/rust-analyzer/commit/fd284bb3e879cd2715463ae5b02f3c89eea441bc (I won't finish the find_path integration, so feel free to take this over)

**Comment by jonas-schievink** [comment]
@SomeoneToIgnore Have to started to work on this yet? If not, I can pick this up again.

**Comment by SomeoneToIgnore** [comment]
Nothing significant do be done, so go ahead.
Thank you for pinging.
