### ISSUE TITLE
Lint ›Unnecessary braces in use statement‹ as Option

### ISSUE THREAD

**Issue by sivizius** [rust-analyzer/rust-analyzer#4531]
After updating of ide-rust in atom, it now uses rust-analyzer instead of rls and now I have a lot of these lints and for $Reasons I want to disable them. How can I do that?

**Comment by lnicola** [comment]
That might be a rustc warning, do you have some code that exhibits the problem?

**Comment by flodiebold** [comment]
That's one of our lints. I don't think we currently have an option to disable it. These are 'weak warning' lints though, that should be displayed very unobtrusively by the IDE; they're basically just a hint that there's a code action there. Maybe Atom doesn't do that?

**Comment by sivizius** [comment]
```
use std::{
  io,
  //mem,
};
```

**Comment by flodiebold** [comment]
Hmm, maybe we shouldn't show the lint if there's a comment in the braces, actually :thinking:

**Comment by sivizius** [comment]
> That's one of our lints. I don't think we currently have an option to disable it. These are 'weak warning' lints though, that should be displayed very unobtrusively by the IDE; they're basically just a hint that there's a code action there. Maybe Atom doesn't do that?

They are just info-lints (lowest level), so, yes, I just could ignore/hide them, but I like to have a way to disable them ›the nice way‹.

**Comment by sivizius** [comment]
There is the unused-import-braces-lint, which is allowed by default, which does almost the same.

**Comment by matklad** [comment]
There's a config to disable all diagnostics: `rust-analyzer.diagnostics.enable`. We *should* have fine-grained flags for all diagnostics, but we don't have those yet.

**Comment by stanciuadrian** [comment]
There is a `rust-analyzer.diagnostics.disabled` option since #5796.
