### ISSUE TITLE
VSCode extension stopped working on NixOS

### ISSUE THREAD

**Issue by cab404** [rust-analyzer/rust-analyzer#4542]
**Steps to reproduce:** 
Install any version of extension past 0.2.~143~151, try running any Rust project.

**What I get:**
It doesn't start. When I try to do "Rust Analyzer: Run" (or any other command) it gives me the following message:
![image](https://user-images.githubusercontent.com/6453661/82502817-b22fbe00-9b00-11ea-9a93-4a76b1fde6b8.png)

It worked in Nix up until 0.2.~143~151.

**Comment by cab404** [comment]
Current nightly (b26dbf8) didn't work either.

**Comment by cab404** [comment]
```
[nix-shell:~]$ patchelf --print-needed ral-latest
libdl.so.2
librt.so.1
libpthread.so.0
libgcc_s.so.1
libc.so.6
ld-linux-x86-64.so.2
libm.so.6

[nix-shell:~]$ patchelf --print-needed ral-working
cannot find section .dynamic
```
Looks like the problem lies with compiling the binary. Did you change anything in that regard between 151 and the next version, @matklad? (it's quite hard to git-blame without tags :( )

**Comment by matklad** [comment]
We've switched from `x86_64-unknown-linux-musl ` to `x86_64-unknown-linux-gnu` (as we need dlopen for proc macros), I imagine that is the problem.

**Comment by cab404** [comment]
Is it okay to add conditional patchelf run to make it work on NixOS?

**Comment by matklad** [comment]
Yup, it should be added between these two lines:

https://github.com/rust-analyzer/rust-analyzer/blob/a4e6963a2313971fe7bbec97d03bc67266ef68a9/editors/code/src/main.ts#L239-L240

**Comment by cab404** [comment]
Thanks for the tip, gonna make PR soon)

**Comment by cab404** [comment]
Ready to merge)
