### ISSUE TITLE
Wrong textedit range is returned

### ISSUE THREAD

**Issue by kiennq** [rust-analyzer/rust-analyzer#4545]
I've tried with the latest nightly build of `rust-analyzer` and notice the wrong textEdit range is returned.
Here is the test snippet with `|` is where cursor is.
``` rust
pub fn test() {
    for index in 0..3 {
        let t = in|
    }
}
```

The log:
```
[Trace - 10:59:05 AM] Sending request 'textDocument/completion - (225)'.
Params: {
  "textDocument": {
    "uri": "file:///c%3A/Data/projects/rust/playground/c15/src/lib.rs"
  },
  "position": {
    "line": 2,
    "character": 18
  },
  "context": {
    "triggerKind": 1
  }
}

[Trace - 10:59:05 AM] Received response 'textDocument/completion - (225)' in 36ms.
Result: [
...
  {
    "textEdit": {
      "range": {
        "start": {
          "line": 2,
          "character": 18
        },
        "end": {
          "line": 2,
          "character": 18
        }
      },
      "newText": "index"
    },
    "label": "index",
    "kind": 6,
    "insertTextFormat": 1,
    "filterText": "index",
    "deprecated": null,
    "additionalTextEdits": []
  },
...
]
```
The range should be `start : {line: 2, character: 16}, end: {line:2, character: 18}` instead. With current range, it will just insert `index` right after `in` and we get `inindex` with previous test snippet.

Here is the full log [rust-analyzer.log](https://github.com/rust-analyzer/rust-analyzer/files/4660252/rust-analyzer.log)

**Comment by matklad** [comment]
Yeah, looks like the fact that `in` is keyword confuses us. We probably set these two fields wrong somewhere:

https://github.com/rust-analyzer/rust-analyzer/blob/a4e6963a2313971fe7bbec97d03bc67266ef68a9/crates/ra_ide/src/completion/completion_item.rs#L29-L34

**Comment by bnjjj** [comment]
Will take a look :)

**Comment by bnjjj** [comment]
@kiennq I tried with your example but can't reproduce, neither in rust-analyzer unit tests nor in vscode. Maybe I miss something. I copied/pasted your example without any changes.

**Comment by lnicola** [comment]
@bnjjj I can see it. You need to type `in`, pick `index` from the completion list, then delete `dex` and trigger again the completion using Ctrl-Space.

**Comment by bnjjj** [comment]
If I do your manipulation I just have `let t = inindex;` but I think it's not the issue listed here.

**Comment by lnicola** [comment]
I think it is?

> With current range, it will just insert `index` right after in and we get `inindex` with previous test snippet.

**Comment by bnjjj** [comment]
Ooooh god ! Sorry I misunderstood the issue. In fact I thought the issue was that it will complete the `inindex` in place of the `in` keyword inside the for loop expression. Ok it's more clear for me now ! Thanks @lnicola for your time and sorry haha

**Comment by kiennq** [comment]
I've tried with https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-06-01 and this issue seems still happened.

The log
```
[Trace - 12:14:58 AM] Sending request 'textDocument/completion - (508)'.
Params: {
  "textDocument": {
    "uri": "file:///c%3A/Data/projects/rust/playground/c15/src/main.rs"
  },
  "position": {
    "line": 21,
    "character": 18
  },
  "context": {
    "triggerKind": 1
  }
}

[Trace - 12:14:58 AM] Received response 'textDocument/completion - (508)' in 49ms.
Result: [
  ...
  {
    "textEdit": {
      "range": {
        "start": {
          "line": 21,
          "character": 16
        },
        "end": {
          "line": 21,
          "character": 16
        }
      },
      "newText": "index"
    },
    "label": "index",
    "kind": 6,
    "insertTextFormat": 1,
    "filterText": "index",
    "detail": "i32",
    "deprecated": null,
    "additionalTextEdits": []
  }
  ...
]
```
With the same snippet as before.
The returned range is incorrect since I've already typed `in`.
The range should be `"start":{"line":21, "character":16}, "end":{"line":21, "character":18}`.

With this, `index` will be inserted into before `in` and I get `indexin` as result after `textEdit` is applied.
