### ISSUE TITLE
disable all inlay hints, but still see "implementations"

### ISSUE THREAD

**Issue by LucianoBestia** [rust-analyzer/rust-analyzer#4549]
I would like to disable all inlay hints. They are just distracting me. 
I found the settings
![image](https://user-images.githubusercontent.com/31509965/82543250-ddea8c80-9b70-11ea-8da6-9bb1c87c1f10.png)
and I try both possiblities. I restart VSCode in between.
![image](https://user-images.githubusercontent.com/31509965/82543981-01fa9d80-9b72-11ea-8316-272f701ed63c.png)

The "implementations" inlay hint is always there (distracting me).
ALso the wording in the settings always says `Inlay Hints:Enable`. No matter if I check or uncheck the `Disable all inlay hints`.

![image](https://user-images.githubusercontent.com/31509965/82543375-10948500-9b71-11ea-8f0e-f7c34356b2dc.png)

Can the "disable all inlay hints" apply also to this?

**Comment by lnicola** [comment]
Do you mean the "2 implementations" lens? That's probably `analyzer.lens.enable`.

**Comment by lnicola** [comment]
`"rust-analyzer.inlayHints.enable": false` works fine for me:

![image](https://user-images.githubusercontent.com/308347/82549154-28fea280-9b65-11ea-8434-3c401734d7c3.png)

**Comment by matklad** [comment]
Yup, `codeLens` and `inlayHints` are different features, they are controlled by different flags.

**Comment by LucianoBestia** [comment]
Ok. Thank you. Didnt know about lens.
