### ISSUE TITLE
Should rust-analyzer really be running on remote machine?

### ISSUE THREAD

**Issue by buzmeg** [rust-analyzer/rust-analyzer#4561]
The task that caused this was that I attempted to use VSCode to remotely edit my rust files on a Beaglebone Black (small Linux computer based around ARM A-series).  The system tried to install a rust-analyzer plugin for my architecture which does not exist, and I was going to file a bug about it.

*HOWEVER*, the larger problem is that I really don't want rust-analyzer running on my remote machine *at all*.  Remote machines are, quite often, much smaller than a local development machine and most of the heavy lifting should be done on the local development machine.

I realize that this is so far off the happy path that it's ridiculous, but given that Ferrous specializes in embedded development, it's probably not as outlandish as one would think.

Thanks.

**Comment by lnicola** [comment]
It's a reasonable feature to ask for, but the way it works now also makes sense: you might be writing code for Linux while running Windows.

For embedded cases, it's less common to actually compile on the target. You'll probably be better of in the long run if you set up a cross-compiling workflow.

**Comment by ArtemGr** [comment]
> Remote machines are, quite often, much smaller than a local development machine

My notebooks are usually less powerful than the servers.
And it makes sense: the notebook should prioritize for having a good battery life, being small and quiet, whereas the server can go full speed.
So I'd really like the _option_ of running the rust-analyzer on a server to remain.
Speaking of which, how did you run it? A remote desktop, such as VNC? VSCode Live Share? Something else?

**Comment by buzmeg** [comment]
Fired off the compile with "cargo xtask install --server", let the BBB rattle on it for 18 hours, and, presto, it worked.

I'm quite impressed, actually.

I don't want to take away the ability to run remotely as I can quite easily see situations where my local machine is far less powerful than the remote machine.  However, the reverse is not uncommon either.  We probably need the infrastructure to be able to do both.

**Comment by buzmeg** [comment]
Oh, if you mean remote setup, I'm just using the standard VSCode/ssh stuff from the "Remote Development" pack.

**Comment by matklad** [comment]
I feel at this point this is sort of out of scope. You *can* run rust-anlayzer locally by just developing locally. You *can* run rust-analyzer rempotely using vscode-remote. We surely can make this more polished or what not, but it seems like this should be solved on the editor's side, if at all (as it seems like current workflows cover a lot of use-cases already)
