### ISSUE TITLE
External Libraries/Crate Dependencies

### ISSUE THREAD

**Issue by aclysma** [rust-analyzer/rust-analyzer#4579]
I'm not sure where to suggest this or if it's already suggested, so please don't hesitate to close and ask me to post this somewhere else. :)

One of my most-loved features of CLion is that it's easy to browse and search my project's dependencies.

I'm aware that auto-complete and jump-to-definition to external libraries works in VSCode and other editors, but I specifically want to be able to full-text search and browse the file structure of dependencies. This includes the standard libraries like libcore and libstd.

![image](https://user-images.githubusercontent.com/316070/82713493-fa092f00-9c3f-11ea-9958-1a41530d8938.png)

I would love to see something like this available in other editors like VSCode or emacs. Perhaps it could look like this in VSCode:
https://code.visualstudio.com/updates/v1_13#_custom-views

I'm not sure if this is something rust-analyzer would support directly (i.e. identifying paths and passing them to extensions in VSCode or other editors) or if the data is already available and it's just a matter of the feature being implemented in the VSCode/other editor extensions.

**Comment by matklad** [comment]
Yup, this is tracked at https://github.com/rust-analyzer/rust-analyzer/issues/4284
