### ISSUE TITLE
Debug code lense says "Found argument '--no-run' which wasn't expected"

### ISSUE THREAD

**Issue by jekjektuanakal** [rust-analyzer/rust-analyzer#4582]
I have Manjaro installed with ZSH. I installed Rust by the usual way, using rustup. I updated rust to latest version (1.43). I installed rust-analyzer VSCode extension, and then it installs rust-analyzer server for me.

This is my problem:

I created a new project using "cargo new project-name" and then opened it in VSCode. I am able to run the hello world program by clicking Run code lense on top of main function. However, when I tried to click Debug, it shows an error like this: 

```
error: Found argument '--no-run' which wasn't expected, or isn't valid in this context

USAGE:
    cargo build --bin <NAME>... --message-format <FMT>... --package <SPEC>...
```

I can only debug from Debug tab, clicking Run (Play) button on top left. It is working normally if I launched debug from there.

Is there anything that I did wrong? How can I fix it?

**Comment by lnicola** [comment]
Might have been fixed by #4528.

**Comment by jekjektuanakal** [comment]
Oh, sorry, didn't see that. Thanks! I will wait for it

**Comment by lnicola** [comment]
Tentatively closing this. Please say something of it's still not working on Monday (or in the nightly release).
