### ISSUE TITLE
VSCode Semantic Highlight: Boolean literal semantic highlighted as keywords

### ISSUE THREAD

**Issue by GrayJack** [rust-analyzer/rust-analyzer#4583]
On VSCode extension the boolean literals `true` and `false` are being parsed as keyword.

![image](https://user-images.githubusercontent.com/17973728/82732086-7142cf80-9ce1-11ea-8b9b-e53034bb6010.png)

I tested using 4cc2ff6e390b6d8015ed1d266425459268f6e0b0

I noticed as well that `self` is also highlighted as keyword, I don't known if this in intended, but if is, it's possible to add a modifier to be able to change it's color?

**Comment by bjorn3** [comment]
`true`, `false` and `self` are actually considered keywords: https://github.com/rust-lang/rust/blob/148c125b1bf20674e8d0c55c21b3433a6d465b07/src/librustc_span/symbol.rs#L63

**Comment by GrayJack** [comment]
Wow, learned something new today.

Would it possible to add modifier so one can colorize these specific cases with other colors?

**Comment by GrayJack** [comment]
Just to make clear, when I ask if it's possible, I mean is the project interested in it? And if it is, where do I start to find how to add those to vscode extension

**Comment by lnicola** [comment]
I think it's possible for boolean literals since https://github.com/rust-analyzer/rust-analyzer/pull/4556.

**Comment by GrayJack** [comment]
True, maybe I forgot to reload the VSCode window when I took the screenshot

But I'm still interest in the `self` :smile:
