### ISSUE TITLE
Why isn't rust-analyzer in cargo.io

### ISSUE THREAD

**Issue by iwahbe** [rust-analyzer/rust-analyzer#4588]
If this is answered somewhere, my apologies, but why isn't `rust-analyzer` in `cargo.io`. It seems an obvious place to put it. Thanks for the great lsp-server.

**Comment by matklad** [comment]
The main reason that it is work, which doesn't directly help with making rust IDE story better. 

Anyone is encouraged to publish rust-analyzer crates with custom prefixes.

See https://github.com/rust-analyzer/rust-analyzer/pull/4405#issuecomment-628573805
