### ISSUE TITLE
Module path in on-hover message is no-longer monospace

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#4594]
Non-monospace code makes my eyes unhappy...
cc #4559
![image](https://user-images.githubusercontent.com/36276403/82757672-b0a91300-9dea-11ea-9ae3-313a80db4a6e.png)

rust-analyzer version: nightly (f4f5fca)

**Comment by Veetaha** [comment]
Also, there is no newline after the mod path either...

**Comment by aloucks** [comment]
I've got a fix for this in the works that migrates to using multiple marked strings. Just sorting out the unit tests now.
