### ISSUE TITLE
Highlighting the ? operator

### ISSUE THREAD

**Issue by CryZe** [rust-analyzer/rust-analyzer#4597]
When the ? operator was proposed, people have suggested that highlighting it in the IDE would be a good way of ensuring you don't miss it. So far this hasn't really been done, so it would be great if we could have it be semantically (or syntactically?) highlighted.

**Comment by kiljacken** [comment]
Still need integration in semantic highlighting, #4621 was just a textmate grammar patch.

**Comment by ruabmbua** [comment]
Merge #4654 closes this issue.

**Comment by CryZe** [comment]
Thanks a lot :D
