### ISSUE TITLE
QuickFix: Rename to snake case

### ISSUE THREAD

**Issue by kuy** [rust-analyzer/rust-analyzer#4598]
rust-analyzer shows me a warning but doesn't provide a quick-fix for it.

1. Rename to snake case
2. Rename all references

rust-analyzer
![Screen Shot 2020-05-25 at 2 19 28](https://user-images.githubusercontent.com/151614/82760464-9b55d800-9e2e-11ea-8f25-cad4cf9e3a4f.png)

IntelliJ Rust
![Screen Shot 2020-05-25 at 2 21 18](https://user-images.githubusercontent.com/151614/82760459-985ae780-9e2e-11ea-91fb-18ba97d7f8a7.png)

**Comment by kuy** [comment]
I'm working on this 🚀

**Comment by SomeoneToIgnore** [comment]
Small heads-up: we have a snake case transformer method in stdx: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/stdx/src/lib.rs#L106

If that's not enough for some reason, we can move more from `xtask` module: https://github.com/rust-analyzer/rust-analyzer/blob/9594fe33fabeb2f97afad86c3a5d5ed79e3d54d8/xtask/src/codegen/gen_syntax.rs#L372
