### ISSUE TITLE
Keyboard shortcut to show/hide inlay hints

### ISSUE THREAD

**Issue by mydogisbox** [rust-analyzer/rust-analyzer#4599]
The inlay hints are awesome when I need them and really busy when I don't. It'd be awesome if there was a quick way to turn them on/off so I can see them when I need them but they're hidden when I don't.

**Comment by bjorn3** [comment]
I can remember there being a similar request recently, but I can't find the issue.

**Comment by mydogisbox** [comment]
@bjorn3 were you maybe thinking of https://github.com/rust-analyzer/rust-analyzer/issues/3751 ?
