### ISSUE TITLE
Provide a command to open API document

### ISSUE THREAD

**Issue by EFanZh** [rust-analyzer/rust-analyzer#4609]
Is it possible for Rust Analyzer to provide a command that opens the corresponding API document for the symbol under the cursor?

For example:

- When cursor is on an an `i32` symbol, this command opens <https://doc.rust-lang.org/stable/std/primitive.i32.html>.
- When cursor is on a `random` symbol of the [rand](https://crates.io/crates/rand) crate, this command opens <https://docs.rs/rand/0.7.3/rand/fn.random.html>.
- etc.

**Comment by matklad** [comment]
Yes, it is possible, we'll do this eventually. For the time being, I personally just use "goto definition" and read the docs from the source.

**Comment by matklad** [comment]
Hm, now that we have hover actions, I wonder if we can use them here... cc @vsrs

**Comment by kinnison** [comment]
You may find some success for stdlib documentation using `rustup doc $symbol` for example `rustup doc i32` or `rustup doc std::iter::Iterator`.  rustup has limited capabilities for finding stuff, so generally fully qualified items work better for it, but it can open docs if they're installed locally.  It can't redirect you to docs.r-l.o sadly.

**Comment by matklad** [comment]
This has been implemented a while ago by @zacps 

![image](https://user-images.githubusercontent.com/1711539/103438021-4e957380-4c3f-11eb-9a8b-18e3b35438f0.png)
