### ISSUE TITLE
Change new attribute syntax highlighting color

### ISSUE THREAD

**Issue by cart** [rust-analyzer/rust-analyzer#4613]
I think #4474 is a good change, but im not a huge fan of coloring attributes as functions. I liked that attributes were "distinct" from function calls. My brain now mentally groups attributes and their functions as "the same": 

![image](https://user-images.githubusercontent.com/2694663/82832965-8a7a8600-9e71-11ea-8cd7-93622a27554b.png)

I personally think the old coloring was much clearer.

Ideally it would use a different color that still visually groups with the concept of "attribute". Maybe a slightly lighter or darker version of the attribute color? 

![image](https://user-images.githubusercontent.com/2694663/82833374-a5012f00-9e72-11ea-9eea-dd1a4216f5fe.png)

**Comment by matklad** [comment]
We can't control the color, but we can and probably should produce a dedicated semantic highlighting tag for attribute attr key.

**Comment by ruabmbua** [comment]
You an customize the color yourself:

```json
"editor.semanticTokenColorCustomizations": {
        "[Default Dark+]": {
            "enabled": true,
            "rules": {
                "function.attribute": "#9b9809",
            },
        }
    },
```

**Comment by Veykril** [comment]
I believe we can close this, for `#[inline]` the `inline` is tagged as `function.attribute` and the `#[` and `]` parts are tagged as `attribute.attribute` which should give appropriate coloring options.
