### ISSUE TITLE
Rust analyzer "cargo check" blocks debug builds

### ISSUE THREAD

**Issue by cart** [rust-analyzer/rust-analyzer#4616]
I'm working on a project where iterative compile times are important. If i make a change, save it, and immediately start a debug build then it will almost always get blocked by rust analyzer's invocation of the "cargo check" command. My build then needs to wait until cargo check completes.

Blocking doesn't occur if I run a release build. This creates the weird situation where release builds are actually faster to complete:
```
Finished release [optimized] target(s) in 0.80s
```
vs
```
Finished dev [unoptimized + debuginfo] target(s) in 1.31s
```

This is especially troublesome for initial cargo check runs, which can block builds for minutes at a time.

**Comment by matklad** [comment]
The workarounds are:

* set `"rust-analyzer.checkOnSave.enable": false` (you should still get errors in the editor if you invoke build manually)
* set `"rust-analyzer.checkOnSave.extraArgs": ["--target-dir", "/path/to/proect/target/check"]`

**Comment by cart** [comment]
Brilliant. The second option is exactly what I was looking for. My first instinct was "why isn't this the default?", but then I looked at the target folder doubling in size. The current default behavior seems like the right choice for most people. Then people (like me) who are willing to trade some disk space for non-blocking behavior can do so. Ideally theres a way to avoid duplicate artifacts, have check on save enabled, _and_ avoid blocks, but I understand that such an ask might be outside the bounds of the constraints rust-analyzer operates in. Maybe RA could detect when there is a user-initiated cargo lock contention and force-stop its internal cargo check execution?

Thanks for your help! I consider this issue solved for me.

**Comment by flodiebold** [comment]
I wonder, if you let it share the target folders, does the `cargo build` that runs after check has finished have to rebuild all dependencies? Otherwise you might spend some time waiting for the lock, but it's maybe just time you'd otherwise spend waiting for the dependencies to build?

**Comment by lnicola** [comment]
My impression is that `cargo check` is mostly but not completely a subset of `cargo build`. Running `cargo check` after `cargo build` will do some work, but will still take less than a clean `check`.

**Comment by cart** [comment]
Those numbers are relatively consistent with my rust-analyzer experience as well.  In my project I get ~0.8 seconds for iterative debug builds (release vs debug is nearly indistinguishable) and ~1.3 seconds for iterative debug builds waiting on a rust analyzer cargo check.

Those numbers are definitely workable, but I've worked hard to make the change/build/run/check loop as tight as possible for my project (its a real time app with "hot reloading" in various forms). Every millisecond is valuable to me.

**Comment by lnicola** [comment]
What if you set `cargo build` as your check command?

**Comment by cart** [comment]
Thats a really smart idea. Sadly i just tested it and for some reason thats significantly slower for iterative builds (~1.5 seconds when immediately invoked and hitting a block. ~0.8 seconds when waiting for cargo check to finish). It seems like cargo decides it needs to re-do the work for some reason. Note that i have reverted the "custom target folder" configuration option.

**Comment by lnicola** [comment]
That's without your previous `watchexec` setup, I assume? If it's visibly slower when called from rust-analyzer compared to running it from the command line, it may be worth further investigation.

**Comment by cart** [comment]
Nope no `watchexec` setup (i didnt even know what that was until now)>

To be clear, the "cargo build" initialized by RA runs at the same speed as a command line "cargo build". The approach im using is:
1. save change (RA cargo build triggers)
2. manually run "cargo run" before RA "cargo build" finishes
3. RA "cargo build" finishes in ~0.8 seconds
4. "cargo run" finishes in ~1.5 seconds.

**Comment by cart** [comment]
I have a feeling that using something like watchexec to run the binary whenever RA's cargo build finishes would give me 0.8 second build/runs. But then im running the program every time i save a file (which isn't desirable)

**Comment by lnicola** [comment]
Yeah, I was about to suggest using cargo run instead of build/check. Note that we pass --all-features by default, that might explain why run takes longer.

**Comment by cart** [comment]
I was sure that was going to be it, but sadly passing --all-features to cargo run also didnt change the total build/run time.

**Comment by lnicola** [comment]
Different environment options might also trigger rebuilds. You could try to start Code from a terminal, then use the Code terminal to run cargo run. But it's pretty far-fetched :-).

Still, might be a fun issue to look at.

**Comment by cart** [comment]
Sadly that also had no effect for me. However that might be because my vscode is a "snap", which might change the env variables.

**Comment by matklad** [comment]
I think it's fair to close this: although the probelm is real, I don't think we'll be able to come up with anything better than the current set of work-arounds.

**Comment by dpc** [comment]
Another solution/workaround idea would be for `rust-analyzer` to use normal debug builds for dependencies, so that the `cargo build` can just re-use the work  `rust-analyzer` just did.

**Comment by lnicola** [comment]
> Another solution/workaround idea would be for rust-analyzer to use normal debug builds for dependencies, so that the cargo build can just re-use the work rust-analyzer just did.

It runs `cargo check` by default, which means that the build artifacts are shared between it and a `cargo build`. So normally there's no slowdown from letting RA run `cargo check`.

But there might still be a bug, e.g. if a no-op `cargo check` takes too much time in RA.

**Comment by Ralith** [comment]
This is still a big problem for me as my build relies on `RUSTFLAGS` which, afaict, there's no way to pass to rust-analyzer. Each `check` invocation therefore throws out the entire build cache, meaning I have to start from scratch repeatedly. I have `"rust-analyzer.checkOnSave.extraArgs": ["--target-dir", "target/check"]` in my global settings, but this appears to have silently stopped working about a month ago.

**Comment by lnicola** [comment]
You can set environment variables using `server.extraEnv` or something like that.

**Comment by Ralith** [comment]
Tried that, now it's clobbering my cache every time I try to build instead of every startup :(

**Comment by Ralith** [comment]
This is continuing to be a (very frustrating) problem. It looks like every time RA declares it's "loading metadata", it clobbers my debug compile cache. This happens at least once every time I launch vscode, and often at other times. My environment is set consistently between my terminal and `rust-analyzer.server.extraEnv`; it seems like RA is ignoring the latter for some of its operations.

**Comment by Veykril** [comment]
What do your `RUSTFLAGS`/`analyzer.server.extraEnv` contain? Assuming this is indeed the problem.

Knowing how to reproduce this would be helpful.

cc https://github.com/rust-analyzer/rust-analyzer/issues/5828

**Comment by Ralith** [comment]
Relevant configuration segment:

```
    "terminal.integrated.env.windows": {
        "RUSTFLAGS": "-L${workspaceFolder}\\..\\OpenXR-SDK\\build\\src\\loader\\Release",
        "RUSTC_FORCE_INCREMENTAL": "1"
    },
    "rust-analyzer.server.extraEnv": {
        "RUSTFLAGS": "-L${workspaceFolder}\\..\\OpenXR-SDK\\build\\src\\loader\\Release",
        "RUSTC_FORCE_INCREMENTAL": "1"
    },
```

**Comment by Veykril** [comment]
Good new is I can reproduce this, bad news is I still don't see why this is happening but its certainly `RUSTFLAGS` related ...

Note that you can set the rustflags in the `.cargo/config.toml` which should work fine.

**Comment by Veykril** [comment]
Oh, okay found the problem, `${workspaceFolder}` isnt being substituted when starting the server with the env vars.

**Comment by Veykril** [comment]
So this seems odd, it is caused by setting `RUSTFLAGS` but cargo is invoked with the same `RUSTFLAGS` in both cases.

**Comment by Veykril** [comment]
So `${workspaceFolder}` isnt being substituted in settings, `"terminal.integrated.env.windows"` is special cause its innate to vscode, extensions can't substitute these OTOH.

@Ralith so you have to replace the `${workspaceFolder}` in the RUSTFLAGS, vscode doesnt allow up to substitute this ourselves unfortunately.

**Comment by Veykril** [comment]
Well I suppose we could support the known set ourselves here... cc #9626

**Comment by Ralith** [comment]
Thanks for investigating!

**Comment by mirgee** [comment]
Did anyone found out how to set `rust-analyzer` config with YouCompleteMe? Is it possible to set it via `.ycm_extra_config.py`? I tried different variations of, e.g.:
```
def Settings( **kwargs ):
    return {
        "checkOnSave": {
           "enable": False
        }
    }
```
with no effect.

**Comment by matklad** [comment]
@mirgee note that we log the config we get from the editor. When using vscode, I enable logs like 

```
λ RA_LOG=rust_analyzer=info code .
```

look for `[INFO rust_analyzer::config] updating config from JSON:` line, it might help you to map what you write in Python to what rust-analyzer actually sees.

**Comment by bmitc** [comment]
> The workarounds are:
>
> * set `"rust-analyzer.checkOnSave.extraArgs": ["--target-dir", "/path/to/proect/target/check"]`

How are folks setting this so that it works across all projects? VS Code also warns me that the setting does `extraArgs` does not exist.

----

Why was this closed? It's still an issue, and it's the only language extension I've used that has this problem. Other extensions normally have their own build completely separate from the builds one runs manually at the command line.

**Comment by Veykril** [comment]
The proper fix for this is setting the `rust-analyzer.cargo.targetDir` now

**Comment by bmitc** [comment]
> The proper fix for this is setting the `rust-analyzer.cargo.targetDir` now

Thank you. For others, here is the link to the documentation: https://rust-analyzer.github.io/book/configuration#cargo.targetDir
