### ISSUE TITLE
Highlight punctuation

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#4620]
Currently, bits of punctuation such as `(`, `)`, `{`, `}`, `[` and `]` aren’t highlighted. Additionally, `.` isn’t highlighted, when it should arguably be highlighted as an operator.

**Comment by kjeremy** [comment]
I recommend the bracket pair colorizer 2 extension for the first case.

**Comment by arzg** [comment]
Sorry, what I meant was that those brackets should be given the `punctuation.<whatever>` scope, and that `.` should be given `keyword.operator.<whatever>`.

Thanks for the recommendation though :)

**Comment by matklad** [comment]
Yes, we should send `operator` token type for all puctuators.
