### ISSUE TITLE
Error/syntax highlighting not working with vscode

### ISSUE THREAD

**Issue by v1nsai** [rust-analyzer/rust-analyzer#4627]
I have installed just `rls-vscode` and `rust-analyzer` extensions in VSCode to avoid conflict, and am using all default settings for both extensions, but I still can't get linting or any kind of syntax highlighting to work.  For example the following code shows no errors:

```
fn main() {
    my_macro!(); jkfjdkjfkdjk
}
```

I've checked the Developer Console and didn't see anything I thought was important, full contents below:
```
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.r.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/r/syntaxes/r.tmLanguage.json.
New grammar file: file:///Users/doctor_ew/.vscode/extensions/ikuyadeu.r-1.3.0/syntax/r.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.rust.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/rust/syntaxes/rust.tmLanguage.json.
New grammar file: file:///Users/doctor_ew/.vscode/extensions/matklad.rust-analyzer-0.2.182/rust.tmGrammar.json
register @ TMScopeRegistry.ts:45
console.ts:137 [Extension Host] Using active channel: stable-x86_64-apple-darwin
console.ts:137 [Extension Host] Minetest Tools extension is active.
console.ts:137 [Extension Host] running with rustup: rls
console.ts:137 [Extension Host] will use a rustup-installed RLS; ensuring present
console.ts:137 [Extension Host] ApplicationInsights:CorrelationIdManager Array(1)
t.log @ console.ts:137
console.ts:137 [Extension Host] ApplicationInsights:CorrelationIdManager Array(1)
t.log @ console.ts:137
console.ts:137 [Extension Host] ApplicationInsights:CorrelationIdManager Array(1)
t.log @ console.ts:137
console.ts:137 [Extension Host] Setting sysroot to /Users/doctor_ew/.rustup/toolchains/stable-x86_64-apple-darwin
log.ts:197   ERR content modified: Error: content modified
	at handleResponse (/Users/doctor_ew/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3531:48)
	at processMessageQueue (/Users/doctor_ew/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3356:17)
	at Immediate.<anonymous> (/Users/doctor_ew/.vscode/extensions/matklad.rust-analyzer-0.2.182/out/src/main.js:3340:13)
	at processImmediate (internal/timers.js:439:21)
extensionsViews.ts:286 Error querying extensions gallery Canceled
```

The `Content Modified` error appears to be no big deal [according to a contributor to the project](https://github.com/rust-analyzer/rust-analyzer/issues/4443#issuecomment-633946414).

Interestingly, I just noticed that linting seems to be half working.  These screenshots show it working sometimes but still missing obvious syntax problems:

![image](https://user-images.githubusercontent.com/410443/82946245-01944500-9f6c-11ea-8551-11a111b6e9e7.png)

![image](https://user-images.githubusercontent.com/410443/82946258-0527cc00-9f6c-11ea-8b42-2994de8e5d3e.png)

![image](https://user-images.githubusercontent.com/410443/82946268-0953e980-9f6c-11ea-8d8c-041443170e49.png)

I've gotten identical results from running rust-analyzer in vscode on my MacBook and on vscode on my Linux (Ubuntu) box.

**Comment by schungx** [comment]
I think you're supposed to disable `rls` when using `rust-analyzer`...  They may conflict.

Does `cargo check` run when you save?  Did you turn on `check on save` or something?

**Comment by v1nsai** [comment]
I tried setting `"rust-client.autoStartRls": false` and `"rust-client.engine": "rust-analyzer"` but I'm getting the same weirdly selective linting.  Is there anything else I need to do to disable RLS?

**Comment by schungx** [comment]
> but I'm getting the same weirdly selective linting. I'm not sure how to verify that `cargo check` does not run when I save though

Well if `cargo check` runs...

1)  You get the text `cargo check` in the status bar.

2) The `cargo check` is likely to run for a few seconds for normal-sized projects.  If it only flashes on for a second or so, then it probably terminated due to some error.

**Comment by Veetaha** [comment]
I recommend uninstalling `rls-vscode`, `rust-analyzer` works alright by itself.

**Comment by matklad** [comment]
Not sure what's the specific issue here, but generally stuff works, so the best bet is to follow the troubleshooting guide: https://rust-analyzer.github.io/manual.html#troubleshooting

**Comment by Jeel5000** [comment]
make sure that you have enabled rust-language-basic extension

search "@builtin rust" in extensions. you will see **rust-language-basic** extension. make sure that is enabled.

**Comment by endingman** [comment]
I have the same issue, and have try to reinstall the extension multi times. Have no any suggest comletion and not show any errors when typing code.

**Comment by IceTDrinker** [comment]
resetting the theme of my editor worked for whatever reason
