### ISSUE TITLE
"command 'rust-analyzer.*' not found" in vscode with remote SSH 

### ISSUE THREAD

**Issue by emakryo** [rust-analyzer/rust-analyzer#4634]
I encountered the following error when I used `rust-analyzer` on a remote host.

```
Command 'Rust Analyzer: Status' resulted in an error (command 'rust-analyzer.analyzerStatus' not found)
```
I installed rust-analyzer from vscode marketplace. I tried every command defined in rust-analyzer, but none of them worked and I got the same error popups. Removing caches and reinstalling vscode didn't help. On the local mache, it works as expected.

What's wrong with my installation?

--- 

My environment
- rust-analyzer 0.2.182
- rust 1.43.1 stable
- VSCode 1.45.1
- Remote SSH extension 0.51.0
- local machine: macOS 10.14.6
- remote machine: amazon linux 2018.03

**Comment by bjorn3** [comment]
Have you also installed the extension on the remote machine? I believe that is required.

**Comment by emakryo** [comment]
yes, I installed both remote and local machine.
But I confirmed it works on another host, so I check the difference between them.

**Comment by emakryo** [comment]
The problem is the version of glibc installed on the system.
glibc 2.18 is required by precompiled rust-analyzer binary while there is only glibc 2.17.
I solved the issue by installing it from source.
