### ISSUE TITLE
Disable rls-vscode when installing

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#4635]
Is there a way to do this at least until unification? A lot of issues that pop up are because people don't deactivate the rls extension.

**Comment by kjeremy** [comment]
If this isn't possible maybe we can detect that the extension is running and throw up a big dialog.

**Comment by Veetaha** [comment]
We can detect rls for sure, and we can uninstall it too, there is a [command for this](https://github.com/microsoft/vscode/issues/73309#issuecomment-495558401)

**Comment by matklad** [comment]
I think we should just merge the extenssions already :)
