### ISSUE TITLE
Make public assist adds `pub` in front of `pub(crate)`

### ISSUE THREAD

**Issue by TimoFreiberg** [rust-analyzer/rust-analyzer#4636]
When the "Make public" assist is triggered on a reference to something in another crate that's currently `pub(crate)`, the assist adds `pub ` in front of the `pub(crate)`.
The assist should change the existing visibility modifier by removing the `(crate)`.

**Comment by kjeremy** [comment]
I'm wondering if instead of "Make public" if we should have a "Change visibility" and present the user with the choices using a snippet.

**Comment by TimoFreiberg** [comment]
Well, the assist knows the minimum required visibility to make the current code compile, so that's not necessary. Maybe the UI is different in VS code, but in vim (using coc.nvim), additional prompts from the assist completely block my input, so that doesn't sound very attractive to me right now. If the choices were presented very unobtrusively, I wouldn't mind though.
