### ISSUE TITLE
missing newline on 'missing structure fields' on VSCode

### ISSUE THREAD

**Issue by flipbit03** [rust-analyzer/rust-analyzer#4638]
I'm on VSCode/Windows and I noticed that when I'm missing some fields in a struct, the error message lacks proper newlines.

This is my VSCode App Info from About: 
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

my rust-analyzer extension is **v0.2.182**

![image](https://user-images.githubusercontent.com/5620032/83039854-ffd28c00-a014-11ea-8b96-b7d0550f8e75.png)

If there's anything more I can do to help in this regard, hit me.

**Comment by lnicola** [comment]
See [this](https://github.com/rust-analyzer/rust-analyzer/issues/4115#issuecomment-619933233).

**Comment by flipbit03** [comment]
Yeah, and I've just fixed the test as well.

**Comment by flipbit03** [comment]
#4639
