### ISSUE TITLE
Handle cargo package renames

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#464]
We currently don't handle the case where a package is renamed in the Cargo.toml, e.g. in `ra_analysis` where `ra_hir` is imported as `hir` instead, so the name resolution fails there. I think this needs to be fixed in `from_cargo_metadata` in project_model.rs (the `name` of the `PackageDependency` should be the renamed name), but I'm not sure what's the correct way of getting this information from the cargo metadata.

**Comment by matklad** [comment]
This is fixed in https://github.com/rust-analyzer/rust-analyzer/tree/new-metadata and waits for https://github.com/oli-obk/cargo_metadata/pull/59.

Guess I'll just merge that with the patch

**Comment by flodiebold** [comment]
Ah, great :)
