### ISSUE TITLE
Handle std and prelude in name resolution

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#465]
With the name resolution getting better, it's now more obvious that `std` is missing completely :) I guess we need to get the path to the rustup-installed std source code somehow. Of course that will also mean we have to parse a lot more code.

Once we have `std`, we should also import (basically) `std::prelude::v1::*` in every module.

**Comment by matklad** [comment]
In terms of implementation, I think we need to add `StdPackages` filed to [this datastructure](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_lsp_server/src/project_model.rs#L19-L22). We should populate it by running `rustc --print sysroot`. This should be done next to the place [where we call cargo metadata](https://github.com/rust-analyzer/rust-analyzer/blob/63e3afeb682cb41e0bb00e1d138f962bbb1b1e7b/crates/ra_lsp_server/src/project_model.rs#L101-L107).

Then we should lover both bits of information to the crate graph, [here](https://github.com/rust-analyzer/rust-analyzer/blob/63e3afeb682cb41e0bb00e1d138f962bbb1b1e7b/crates/ra_lsp_server/src/server_world.rs#L38-L96). I think lowering would basically mean adding a dep to std from every crate. 

I *think* prelude is marked with some-kind of lang-item, so we can handle it inside the hir, without changing `CrateGraph` data. Though, if we need this, we certainly can mark some crates as "this comes from sysroot, this is std".

**Comment by flodiebold** [comment]
> marked with some-kind of lang-item

That means we'll need some kind of 'index lang-items' step, right? Which we'll want for a lot of other things as well.

I think this is the item (in libstd/lib.rs):
```rust
// Explicitly import the prelude. The compiler uses this same unstable attribute
// to import the prelude implicitly when building crates that depend on std.
#[prelude_import]
#[allow(unused)]
use prelude::v1::*;
```

**Comment by matklad** [comment]
>That means we'll need some kind of 'index lang-items' step, right? Which we'll want for a lot of other things as well.

yep!

**Comment by DJMcNab** [comment]
We need to handle `#![no_std]` too. This seems like the right time to be thinking about this, as we need to be looking into correctly handling attributes to properly discover lang items.
