### ISSUE TITLE
Smarter newline on return key in comments

### ISSUE THREAD

**Issue by binomial0** [rust-analyzer/rust-analyzer#4656]
I don't know if this is in scope or even possible in VS Code.
I think it would be really useful and convenient if, when the cursor is inside of an inline comment and you press enter, the editor would automatically insert the // or /// sigil on the beginning of the new line.
So, say you have the following code:
```
/// This is a function named `foo`.
fn foo() {}
```
You place the cursor after "function" and press enter, you currently get:
```
/// This is a function
 named `foo`.
fn foo() {}
```
I think you should get:
```
/// This is a function
/// named `foo`.
fn foo() {}
```

**Comment by flodiebold** [comment]
This exists, see e.g. #4277.
