### ISSUE TITLE
Incoherent syntax highlighting in VS Code

### ISSUE THREAD

**Issue by Moxinilian** [rust-analyzer/rust-analyzer#4657]
Hello!

For a couple weeks now I've been observing weird syntax highlighting behaviors in VS Code. See this example (I am using the Monokai default theme):

![image](https://user-images.githubusercontent.com/30992420/83323784-4f0cfc80-a261-11ea-9456-aa44b3c94731.png)

The highlighting is very odd. Firstly, the two use statements have different highlighting, which is surprising. Then, in the structs, types are sometimes green and underlined, sometimes not.
Hence why I believe the syntax highlighting is completely broken on my install. The change happened suddenly and a while ago, and I therefore unfortunately cannot remember if a rust-analyzer update caused it.

Do you know what could be the cause of this?

Thanks in advance.

**Comment by bjorn3** [comment]
It seems that the `stretch` crate is not found. Did you add it to `Cargo.toml` without reloading rust-analyzer afterwards? rust-analyzer doesn't currently handle changes to `Cargo.toml`.

**Comment by Moxinilian** [comment]
That was the problem! Thank you.
A quick follow-up question: is it possible to revert the style back to what it previously was in configs? I interpreted an apparently intended change in how code is highlighted as my bug (notably types getting underlines), as I would much prefer the previous format.
Thanks in advance!

**Comment by aloucks** [comment]
You can disable semantic highlighting per-theme in your settings.json.

```json
    "editor.semanticTokenColorCustomizations": {
        "[Monokai]": {
            "enabled": false,
        }
    },
```

**Comment by Moxinilian** [comment]
Okay, apparently underlining is from the theme and not rust-analyzer.
Thank you!
