### ISSUE TITLE
Labels on breaks ignored for inference

### ISSUE THREAD

**Issue by robojumper** [rust-analyzer/rust-analyzer#4663]
Contrived example:
```rust
fn foo() {
    let _x = || 'outer: loop {
        let inner = 'inner: loop {
            let i = Default::default();
            if (break 'outer i) {
                loop { break 'inner 5i8; };
            } else if true {
                break 'inner 6;
            }
            break 7;
        };
        break inner < 8;
    };
}
```

rust-analyzer currently infers `inner`, `i`, `6`, `7`, and `8` to be of type `i32`. Correct would be `inner`, `6`, `7`: `i8` and `i`: `bool`.

I briefly looked into this and decided it would be necessary to extend the [HIR Expr](https://github.com/rust-analyzer/rust-analyzer/blob/5f7225446e75509ae0d971a6f3e2b9d3e37d6f2a/crates/ra_hir_def/src/expr.rs#L43) with block labels / break/continue targets. The [AST](https://github.com/rust-analyzer/rust-analyzer/blob/5f7225446e75509ae0d971a6f3e2b9d3e37d6f2a/crates/ra_syntax/src/ast/generated/nodes.rs#L1058) currently only offers the pseudo-lifetimes as `SyntaxToken`s. What would be a good type to represent the labels in the HIR?

**Comment by flodiebold** [comment]
I think it makes sense to use `Name`.
