### ISSUE TITLE
RA inserts "&mutself" for trait method stub, and missing space after `:`

### ISSUE THREAD

**Issue by RalfJung** [rust-analyzer/rust-analyzer#4665]
I am working on an implementation of the `mir::visit::Visitor` trait in rustc, and to add a new method I started typing `fn visit_termin<tab>`. That got auto-completed as follows:
```rust
    fn visit_terminator(&mutself, terminator: &Terminator< 'tcx>, location:Location) {
        
    }
```
Notice the missing space in `&mutself`, and the missing space before `Location`.

**Comment by bjorn3** [comment]
I think this has been reported before, but I can't find the issue for it.

**Comment by flodiebold** [comment]
Probably #2765. At least I assume it's the same problem: The function being geerated by a macro, so we don't have valid whitespace and need some formatting infrastructure to put it there.
