### ISSUE TITLE
"Missing structure fields" error in a compiling code

### ISSUE THREAD

**Issue by osa1** [rust-analyzer/rust-analyzer#4681]
rust-analyzer version: 7ae247f (just pulled a few mins ago)
Error line: https://github.com/osa1/tiny/blob/f69c85234a959f5c3a0a894c30d94b0146786956/libtiny_tui/src/lib.rs#L120

Screenshot:

![Screenshot_2020-06-01_09-50-33](https://user-images.githubusercontent.com/448274/83383336-932d0800-a3ed-11ea-8ac4-02d4222fd189.png)

This code builds fine so there shouldn't be any errors. I think the problem is in name resolution. A few lines above the error line I have this

```
use tui::TUIRet::*;
```

and the struct that rust-analyzer complains about is coming from that line (`Input`). There's another struct with same name: `term_input::Input`, but clearly that's not what we're referencing here.

**Comment by osa1** [comment]
Perhaps rust-analyzer doesn't handle overriding existing names after `use` statements. There's an `Input` in scope in the error above, but it's overridden by the `use tui::TUIRet::*;` line.

**Comment by lnicola** [comment]
Local imports (use) are indeed not supported.
