### ISSUE TITLE
Introdce named lifetime does not work if there are already some type parameters

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#4684]
```rust
impl<I> fmt::Display for SepByBuilder<'_/*cursor here*/, I>
where
    I: Iterator,
    I::Item: fmt::Display,
{
```

Source: https://github.com/rust-analyzer/rust-analyzer/blob/b12d4316cc5ddd7f540304420a9cd63ed424173e/crates/ra_assists/src/handlers/introduce_named_lifetime.rs

cc @jbalint

**Comment by jbalint** [comment]
will fix it
