### ISSUE TITLE
[Feature Request]: Homebrew package?

### ISSUE THREAD

**Issue by dalisoft** [rust-analyzer/rust-analyzer#4685]
Hi!

Thanks for best tool which i'm planning to use in future, but would be best to have Homebrew package.
So users can have just do `brew install rust-analyzer` on Mac & Linux machines and can use `rust-analyzer-server` on editors

Thanks

**Comment by lnicola** [comment]
I've never used `brew`, but we have binary releases for MacOS. I imagine a `brew` recipe that downloads them would be reasonably easy to write, unless it's more common to build from source?

Medium-term, the binaries will also be available in `rustup`, so this might not be necessary after all.

**Comment by dalisoft** [comment]
I also like to use binaries. Homebrew also installs binary if available, if it’s possible, would be nice. 

I install rust with brew install cargo. I choose all packages with Homebrew over official because update, maintaining last version easier and less painful. Sometimes we have less time to update from multiple commands, i think Homebrew solves this issue. 

Thanks for reply and best tool.

**Comment by dalisoft** [comment]
Close as it's not required currently, i will look into this issue when i will be free time to learn Rust :)

Anyway, thanks for tool

**Comment by peterkos** [comment]
It appears that there is one?
https://formulae.brew.sh/formula/rust-analyzer

Also, `rustup`'s installation was completely broken for me on macOS+Sublime but installing through Homebrew worked perfectly. I assume it can resolve path issues that `rustup` has trouble with?

**Comment by dalisoft** [comment]
When i searched, i did not found. But i did it via Ansible playbook + get_url with caching
