### ISSUE TITLE
Create module assist

### ISSUE THREAD

**Issue by CGMossa** [rust-analyzer/rust-analyzer#4687]
It would be nice, if there was a create a module assist, that pops out when one tries to `mod new_module;` or similar.

There are two ways to create a module (I believe): One with having a folder the name
the name of the module with a `mod.rs` in it to contain all the sub-files in `mod sub_file01`, etc. And another where the modules are single files.

This assist exists in `intellij-rust`. I tried to find an issue containing this, but couldn't find it.

**Comment by jonas-schievink** [comment]
This already exists

**Comment by CGMossa** [comment]
Hmm.. It says that there is a problem:
```
file not found for module `testing`
to create the module `testing`, create file "src\testing.rs"rustc(E0583)
```
but it doesn't give an option/button to do so. 

Am I misunderstanding something?

**Comment by bjorn3** [comment]
![image](https://user-images.githubusercontent.com/17426603/83429194-fb064180-a433-11ea-8843-39d44abd5140.png)

**Comment by CGMossa** [comment]
I found it. If I click `Ctrl + .` it works, but these things are not appearing as suggestions/quick-fixes in vscode. Maybe they should be. But that's a different issue. Please feel free to close this.

**Comment by jonas-schievink** [comment]
The lightbulb icon provides these assists too.
