### ISSUE TITLE
No error highlighting - but only on certain projects

### ISSUE THREAD

**Issue by 17cupsofcoffee** [rust-analyzer/rust-analyzer#4690]
On newer versions of Rust Analyzer (anything after 0.2.159 on the marketplace), I don't get error reporting (i.e. the red squiggles when I mistype) any more - but only for one project in particular. Other features of the plugin work fine, and other repos can report errors fine, it's just this one project as far as I can tell.

The repository in question is https://github.com/17cupsofcoffee/tetra.

How would I go about narrowing down the cause of this? I know there's various logs/traces I can turn on in RA, but I'm a bit unsure of where to start 😅 I have noticed that the `cargo check` notice seems to stay visible for a lot longer when I hit save than it used to - not sure if I might be running into a timeout or something?

**Comment by lnicola** [comment]
It works for me:

![image](https://user-images.githubusercontent.com/308347/83443348-3f083f00-a452-11ea-8333-3941ed86db77.png)

`rust-analyzer` basically runs `cargo check --all-features --message-format=json` each time you save a file. Does that command work as expected?

See also #4443.

**Comment by 17cupsofcoffee** [comment]
Oh, I see the issue now - `--all-features` is enabling a feature flag in my library which attempts to build SDL2 from source, and that doesn't work because I don't have `cmake` installed on my machine. This also explains why the `cargo check` is taking so long - the build script is doing loads of stuff in the background before it falls over.

That feature flag has never compiled on my machine, and RA has always used `--all-features`, so I'm not sure why this has only suddenly become an issue now. I'll have to have a dig through the changelog and see if something relevant changed (maybe something to do with features or build scripts).

Either way, this isn't an issue in RA itself - I just need to disable `rust-analyzer.checkOnSave.allFeatures` when working on this library by the sounds of it. Thank you for the insight!

**Comment by lnicola** [comment]
I think it would make sense to disable `rust-analyzer.checkOnSave.allFeatures` by default. There's plenty of projects with incompatible features (even though you're not supposed to do that), or where some features don't work because they require a library, compiler or nightly toolchain version.
