### ISSUE TITLE
Semantic highlighting for function exit points

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#4691]
[As seen in IntelliJ](https://intellij-rust.github.io/2020/06/01/changelog-123.html)

**Comment by matklad** [comment]
Yessss I want this a lot. The problem is, I don't see an LSP request we can use for it :0(

Maybe abuse document highlight?

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/88051842-9d4fc500-cb59-11ea-85cd-2e8789344abf.png)

**Comment by matklad** [comment]
https://microsoft.github.io/language-server-protocol/specification#textDocument_documentHighlight

**Comment by kjeremy** [comment]
That takes in a position though. You couldn't do this with semantic highlighting and token modifiers?

**Comment by matklad** [comment]
@kjeremy that's exatcly the UI -- higlights of **all** exit points activates when you are on a single exit point (and probably it makes sense to trigger it on return type as well).

**Comment by matklad** [comment]
For the refrece, IntellijJ impl is here: https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactory.kt

**Comment by kjeremy** [comment]
Ah! I thought it was always active. This would be really nice to have.

**Comment by woody77** [comment]
always active is definitely doable, but it can't be themed as a background change (but could be given bold or other font styling).

In the theme that I'm working on, making the `?` operator extra clear is one of my goals (as well as other subtle, easy-to-miss things).

**Comment by kjeremy** [comment]
I think we could just use `DocumentHIghlightKind::Text` for this
