### ISSUE TITLE
Automatic Comment Expansion on Enter

### ISSUE THREAD

**Issue by kianenigma** [rust-analyzer/rust-analyzer#4693]
I recall that when I used to to use the [RLS](https://github.com/rust-lang/rls-vscode) + [Rust](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust)  extension for rust on of my beloved features was:

```rust
/// casually writing some comment [press-enter-here]
/// [next-line-starts-with-the-///-prefix]
pub fn foo() {..} 
```

which is supported in most other languages as well. 

Soon after switching to RA I realised that this is not working. Is this in the concerns of RA and this repo to be fixed? 

Albeit I have it now again as well by enabling the official rust Rust extension and setting the backend to RA. though, to be fair, I am not super happy about this as it looks more like an overhead to me to have the Rust extension also enabled. I literally only use this feature from it.

**Comment by lnicola** [comment]
See #4656. It's already possible, but you need to add a key binding.
