### ISSUE TITLE
rust-analyzer doesn't seem to actually be running on remote machine

### ISSUE THREAD

**Issue by buzmeg** [rust-analyzer/rust-analyzer#4699]
I compiled up rust-analyzer with ''cargo xtask install --server" (and an 18+ hour compile).  It seems to exist and is on my default path on the remote machine.

```
root@beaglebone:~# uname -a
Linux beaglebone 4.19.94-ti-r42 #1buster SMP PREEMPT Tue Mar 31 19:38:29 UTC 2020 armv7l GNU/Linux
root@beaglebone:~# which rust-analyzer
/root/.cargo/bin/rust-analyzer
root@beaglebone:~# rust-analyzer
^C
```

Yet, VSCode doesn't seem to be recognizing that it is there even though the extension claims to be installed ("Extension is enabled on 'SSH: 192.168.12.150'" and it shows up in the Extensions window as installed).  The Command Palette doesn't seem to be bringing up "Rust Analyzer: Show RA Version", for example.

And I keep getting:
> Unfortunately we don't ship binaries for your platform yet. You need to manually clone rust-analyzer repository and run `cargo xtask install --server` to build the language server from sources. If you feel that your platform should be supported, please create an issue about that here and we will consider it.

Are there further steps that I need to do beyond ''cargo xtask install --server" to get it installed and running on a remote machine?

Thanks.

(I originally thought this was running (See: #4561), but I don't know if I was simply mistaken or if something changed.)

**Comment by buzmeg** [comment]
The bug seems to be in the local plugin in rust-analyzer/editors/code/out/main.js in getServer

For some reason, the code drops through the 

```
    if (config.package.releaseTag === null)
        return "rust-analyzer";
```

And then drops into the binary-specific code which then returns undefined.

Perhaps config.package.releaseTag is being returned for the local plugin instead of the remote server?

**Comment by bjorn3** [comment]
There is a config to define the rust-analyzer binary path. I believe it was called something like `rust-analyzer.serverPath`.

**Comment by buzmeg** [comment]
Ah, that does allow me to override and get around the null.  However, two things:

1) An environment variable with the name "Path" is not supposed to also include the name of the binary executable--I added my path--/root/.cargo/bin and it didn't work.  This should be called "Rust Analyzer--Server Executable".  The only reason I could make this work is that I actually looked at the code.

2) Why not simply try to run with the default "rust-analyzer"?  This code seems like it is trying to be way too clever about detection when "just try it and see if it errors" is far more definitive.  Although, to be fair, it seems like I'm the only person to ever hit this, so it probably wasn't worth worrying about before.

**Comment by buzmeg** [comment]
I can confirm that this is working ... slowly.

I see like 3 node instances along with cargo, rust-analyzer, and random rustc.

That's ... really suboptimal.  Where are all the node instances coming from?

**Comment by bjorn3** [comment]
Those node instances are part of vscode itself. Vscode is made using the electron framework, which uses chromium to display the ui and node for interfacing with the os. Cargo and rustc should only run after saving to check your code for errors.

**Comment by buzmeg** [comment]
serverPath actually does the trick.  But it hoses the local install.  I'll file a different bug.  Thanks.
