### ISSUE TITLE
Std/core name resolution fails on gimli-rs/object

### ISSUE THREAD

**Issue by matprec** [rust-analyzer/rust-analyzer#4702]
When i'm loading a fresh checkout of [gimli-rs/object](https://github.com/gimli-rs/object) in VSCode, all of the std/core name resolution fails. It compiles fine via cargo check/build:

![grafik](https://user-images.githubusercontent.com/20750283/83497255-7dd1df80-a4ba-11ea-922f-27effe77cf42.png)

As far as i can tell, other projects just work fine. Maybe it has to do with their nostd compatibility?

**Comment by flodiebold** [comment]
These are errors from cargo-check. Does `cargo check --all-features` compile?

**Comment by bjorn3** [comment]
Maybe the fact that both `rustc-dep-of-std` and `std` features are enabled.

**Comment by lnicola** [comment]
Let's disable `rust-analyzer.checkOnSave.allFeatures`.

**Comment by matprec** [comment]
No that doesn't compile and throws the same errors. This makes me think it might have to do with their feature setup for rustc ingeratation.

Disabling `--all-targets` within the extension consequently removes all errors. This makes it an issue of `gimli-rs/object`
