### ISSUE TITLE
GLIBC 2.18 requirement

### ISSUE THREAD

**Issue by LukeMauldin** [rust-analyzer/rust-analyzer#4706]
The rust-analyzer binary for Linux has a requirement on GLIBC 2.18.  When I try to run it on RHEL/Centos7 I receive this error: `/lib64/libc.so.6: version `GLIBC_2.18' not found`

I am able to run tools from the standard rust distribution on RHEL/Centos7 because it looks like they are compiled in a docker container based on RHEL5.  Could you update the rust-analzyer binary to be least be compatible with RHEL/Centos7?

**Comment by lnicola** [comment]
I suggest building from source for CentOS/RHEL. The oldest distro available on GitHub Actions is Ubuntu 16.04, but CentOS 7 has an even older glibc.

Short/medium-term, `rust-analyzer` binaries will be available as `rustup` components.

**Comment by LukeMauldin** [comment]
Yes, I have been building from source to make it work. I just wanted to report it as an issue in case others had the same problem. It is good to know that it will be included out of the box in the short/medium term.

**Comment by justintime4tea** [comment]
You may be able to get away with some janky workaround like posted over here:
https://github.com/vadimcn/vscode-lldb/issues/268
