### ISSUE TITLE
improve highlighting for mismatched return types

### ISSUE THREAD

**Issue by EverlastingBugstopper** [rust-analyzer/rust-analyzer#4714]
for example, if i have the following code snippet:

```rust
let location = Some("world");
let disp = if let Some(location) = &location{
  format!("hello {}", location);
} else {
  "hello void".to_string()
};
```

the problem is that i have a `;` at the end of the first call to `format!`. however, `rust-analyzer` will red-squiggly typo underline my `"hello void".to_string()` when that's not the real problem.

I understand it's probably impossible to tell which one the programmer intends to be the correct return type, but if we're doing type inference here, wouldn't it make sense to squiggly underline both of them instead of just the one defined second?

maybe this is a rustc thing and not a rust-analyzer thing - just something i noticed! thanks :)

**Comment by bjorn3** [comment]
This is a rustc error. rust-analyzer doesn't yet report typeck errors, because there are still several cases where it is wrong: https://edwin0cheng.github.io/github-action-usage-test/

**Comment by EverlastingBugstopper** [comment]
Cool! Thanks for the info 😄
