### ISSUE TITLE
Can't resolve type if the type is imported in the same function:

### ISSUE THREAD

**Issue by Aloso** [rust-analyzer/rust-analyzer#4719]
**How to reproduce:**

```rust
fn _foo() {
    use std::borrow::Cow;
    let _ = Cow::Borrowed("?");
}
```

Move your cursor over `Cow::Borrowed`. The tooltip just says `{unknown}`. The same applies to nested functions, e.g.

```rust
fn _foo() {
    use std::borrow::Cow;

    fn _bar() {
        let _ = Cow::Borrowed("?");
    }
}
```

In `impl` blocks within a function I got no type information _at all_, which is a separate issue.

**Comment by bjorn3** [comment]
Duplicate of #1165.
