### ISSUE TITLE
[Feature Request]: Hide methods from suggestions when typing "::"

### ISSUE THREAD

**Issue by rodrigocfd** [rust-analyzer/rust-analyzer#4731]
This idea originated from [this StackOverflow question](https://stackoverflow.com/q/62172979/6923555). The idea is to have an option to hide methods (those which the first parameter is `self`) from the suggestions that are shown after `::`. Only associated functions would appear then.

The rationale is that, although methods _are_ associated functions (thus should be listed), most of the time you want to invoke them only with an object, using the `.` syntax.

In the example below, `calc_num` should _not_ be listed in suggestions:

![Example](https://i.stack.imgur.com/98iTM.gif)

**Comment by flodiebold** [comment]
It's always 'easy' to add options, but I'm not a fan of hiding valid completions. I think we should sort them to the bottom, if possible, and that may be enough?

**Comment by lnicola** [comment]
I don't think we should do this. Any opinion @matklad?

**Comment by SorteKanin** [comment]
I would love if this was reopened. Personally I'd like the option of either sorting the self functions to the bottom or entirely removing them. 99% of the time, I don't want the self methods and the suggestions are just noise then. 

This should definitely be a configuration option though as it could be confusing unless you make the conscious choice to hide those functions.

Are there any specific reasons not to provide such an option? @lnicola why do you think it should not be implemented?

**Comment by rodrigocfd** [comment]
@SorteKanin Personally, I'd like to see the methods sorted by: those belonging to the struct itself, then the traits. And for the trait methods, showing the trait where they come from.

**Comment by SorteKanin** [comment]
@rodrigocfd that sounds like a good idea for some customizable options yea. But this issue is just about hiding the self functions I'd say.
