### ISSUE TITLE
rustAnalyzer/cargoWatcher token missing window/workDoneProgress/create

### ISSUE THREAD

**Issue by rwols** [rust-analyzer/rust-analyzer#4732]
The $/progress notifications with token rustAnalyzer/cargoWatcher are not preceded by a window/workDoneProgress/create request. As a consequence, those progress notifications don't appear in the status bar.

On the other hand, $/progress notifications with token rustAnalyzer/startup *are* preceded by a window/workDoneProgress/create request, so I'm guessing rustAnalyzer/cargoWatcher just needs to be updated to use the same code as from rustAnalyzer/startup.

Editor: Sublime Text
Rust Analyzer version: 7ae247f
Platform: Ubuntu 20.04

**Comment by kjeremy** [comment]
@rwols the request was renamed from the proposed `window/workDoneProgress/create` to `window/workDoneProgressBegin` when officially [released in 3.15](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workDoneProgressBegin). I suspect that that the sublime LSP client needs to be updated.

**Comment by kjeremy** [comment]
@Veetaha Does #4407 fix this?

**Comment by Veetaha** [comment]
Nope, it partially fixes this problem with `rustAnalyzer/startup` (which I suspect happens only in our integration tests and not in real-life scenarios). I have some thoughts on how to fix it, but I just need to find time for playing with this.
