### ISSUE TITLE
JsonProject parsing broken

### ISSUE THREAD

**Issue by Nashenas88** [rust-analyzer/rust-analyzer#4735]
It looks like commit https://github.com/rust-analyzer/rust-analyzer/commit/d4b21476a8f8dc882e2ace78e156da6fcb70a8ff broke RA for json projects.

**Comment by Nashenas88** [comment]
CC @woody77

**Comment by woody77** [comment]
```
[2020-06-03 20:59:20.203] [exthost] [error] [matklad.rust-analyzer] provider FAILED
[2020-06-03 20:59:20.206] [exthost] [error] Error: busy
	at Object.provideDocumentSemanticTokens (/Users/aaronwood/.vscode/extensions/matklad.rust-analyzer-0.4.0-dev/out/src/main.js:14452:27)
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:412:9)
```

**Comment by woody77** [comment]
I should clarify how we've been generating `rust-project.json`, as I think it's likely to be germane:

```
{
  "roots": [],
  "crates": [,
    {
      "crate_id": 0,
      "root_module": "<some_path>/src/rust/src/libcore/lib.rs",
      "edition": "2018",
      "deps": [
      ],
      "cfg": []
    },
<the rest of the stdlib crates>
...
    {
      "crate_id": N,
      "root_module": "<absolute path to some crate's lib.rs or main.rs>",
      "edition": "2018",
      "deps": [
        {
          "crate": 4,
          "name": "std"
        },
       <more deps, all with id's less than this crate's id
      ],
      "cfg": []
    },
 ```

We're not listing any roots, just crates (a couple thousand of them).

And it seems like after #4723, that's not a valid setup.

@matklad - Are we just not using the rust-project.json file in the way it was envisioned?  I'll try to be online early in my time tomorrow, and catch you online.  Either here or on zulip.

**Comment by matklad** [comment]
So, the meta note here is that `rust-project.json` format is not stable, and I want to preserve the freedom of breaking it, until it is "done". So, users of rust-project.json should generally pin a specific version of rust-analyzer to  avoid accidental breakage.

In this specific case, yes, there should be specified the set of roots which covers all the crates. We previously used the set of folders opened in the editor for this, and it worked by accident.

**Comment by woody77** [comment]
I totally get the meta-note.  I'm mostly trying to keep things working for the developers that we have.

What are the ramifications of choosing the roots?  I can easily add one folder, and with some more work, add a more fine-grained set of folders.  What are the trade-offs of one giant root with many non-Rust files vs. multiple smaller roots (up to 1000s) that correspond closely to the crates' source folders?

**Comment by matklad** [comment]
> What are the trade-offs of one giant root with many non-Rust files vs. multiple smaller roots (up to 1000s) that correspond closely to the crates' source folders?

Roots are intended to be fine-grained. rust-analyzer will be slower for bigger roots. We crate one root per Cargo.toml. I also hope to kill roots completely soon....

**Comment by woody77** [comment]
Ok, that would explain the big slowdown I saw when trying to fix it.

Is there a way I can help with making the roots go away?

**Comment by woody77** [comment]
btw, we can close out this issue, now that understand why it broke (and we've worked around it).
