### ISSUE TITLE
Startup (cargo check, maybe other analysis) breaks vscode settings

### ISSUE THREAD

**Issue by cjhopman** [rust-analyzer/rust-analyzer#4742]
Not sure if this is a limitation of vscode or not, but extension settings (not just those of rust-analyzer) don't show up in user settings while it's running `cargo check` at startup. I'd assume that vscode is waiting for a response from the extension but `¯\_(ツ)_/¯`

**Comment by cjhopman** [comment]
This might not be limited to just startup. It might be that current nightly rust analyzer is just breaking vscode settings in general. I switched to stable by editing the settings.json directly.

**Comment by vincentisambart** [comment]
@cjhopman I might have fixed this in #4780 (merged a few hours ago). You might want to try again with a version that include the fix.
