### ISSUE TITLE
Windows installation instruction

### ISSUE THREAD

**Issue by Stargateur** [rust-analyzer/rust-analyzer#4744]
There is no windows instruction to compile the project, only:

> You’ll need Cargo, nodejs and npm for this.

I have installed these but I still run into:

```none
> cmd.exe /c code.cmd --version
'code.cmd' n'est pas reconnu en tant que commande interne
ou externe, un programme ex▒cutable ou un fichier de commandes.
> cmd.exe /c code-insiders.cmd --version
'code-insiders.cmd' n'est pas reconnu en tant que commande interne
ou externe, un programme ex▒cutable ou un fichier de commandes.
> cmd.exe /c codium.cmd --version
'codium.cmd' n'est pas reconnu en tant que commande interne
ou externe, un programme ex▒cutable ou un fichier de commandes.
> cmd.exe /c code-oss.cmd --version
'code-oss.cmd' n'est pas reconnu en tant que commande interne
ou externe, un programme ex▒cutable ou un fichier de commandes.
Error: install client
```

**Comment by lnicola** [comment]
Do you have Code installed? I think there's an option to add it to `%PATH%`.

**Comment by Stargateur** [comment]
I used default installer of node, there is no option to add anything called "Code". What is it ?

**Comment by lnicola** [comment]
What LSP client (editor) are you trying to use `rust-analyzer` with? If it's not Visual Studio Code, you can run `cargo xtask install --server`.

**Comment by Stargateur** [comment]
That look right, I want to install rust analyser for Atom, there is no specific instruction.

So, rust-analyzer look installed but my atom plugin doesn't seem to do anything now... well that another problem.

**Comment by lnicola** [comment]
For Atom I found https://github.com/atom/atom-languageclient. I'm not sure if that's built-in or you have to install it manually. Then, in the LSP client configuration you should be able to either set the server path (which you can set to `rust-analyzer.exe`), or maybe to pick a language like Rust. If it's the latter, it's probably RLS and you should rename `rust-analyzer.exe` to `rls.exe`.

**Comment by lnicola** [comment]
By the way, you don't have to build from source. As https://rust-analyzer.github.io/manual.html#installation mentions, you can grab a binary release from GitHub.

**Comment by lnicola** [comment]
Okay. You can install the `ide-rust` package. On my system it defaults to `rust-analyzer`, so it works out of the box.
