### ISSUE TITLE
arm64 binaries for linux & win

### ISSUE THREAD

**Issue by eldiablolives** [rust-analyzer/rust-analyzer#4746]
I am well aware that we can install from source but it would be nice to include linux & windows arm64 prebuild binaries. 

This question is going to keep on coming with microsoft's commitment to arm64 platform and of course WSL, suddenly devices like surface pro X (and upcoming from other suppliers) have become a good options for developers on the go.

vscode insiders track emitted arm64/win binaries which means it is coming out mainstream imminently

**Comment by Veetaha** [comment]
[There were some efforts to bring cross-compiling for arm quite some time ago](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/ARM.20build.3F/near/191076109).
I wonder what we ended up with. Are there any blockers for this?
cc @qmx

**Comment by eldiablolives** [comment]
I just compiled it on linux arm64/WSL, running it from vscode, works like a charm. I imagine doing the same on win-arm64 would work. To do this automatically you need somewhere win/arm64 instance as well as linux, finding that I think is the major challenge, the rest just works.

Failing that someone could do a manual compile on significant versions, and do a manual push into repo, it wouldn't be as fresh as intel64 but it would get it out there, lower-version is better than no version and compiling manually then fiddling with config is not great

**Comment by matklad** [comment]
rust-analyzer is available through rustup, it might have binaries for more platforms.

**Comment by Alovchin91** [comment]
@matklad When I try to install rust-analyzer via rustup on WSL on my Surface Pro X, I get the following:

```
➜  ~ rustup component add rust-analyzer-preview
error: component 'rust-analyzer-preview' for target 'aarch64-unknown-linux-gnu' is unavailable for download for channel stable
```

Is this because I'm using the stable toolchain? And is there anything that prevents the team from providing Linux ARM64 binaries for VS Code extension to download automatically?

**Comment by lnicola** [comment]
`aarch64-pc-windows-msvc` added in #7148. Filed #7311 for `dist-aarch64-unknown-linux-gnu`.

**Comment by qdm12** [comment]
Would it be possible to have arm64 (aarch64) support for unknown-linux-musl? I'm developing a VScode development container based on Alpine Linux, and would like to support arm64 for native performance on arm64 machines. Let me know if you feel I should create another issue instead though. Thanks!

**Comment by lnicola** [comment]
@qdm12 I suppose we could try that, but you can also install `rust-analyzer-preview` from a nightly toolchain. You don't need to use the nightly compiler, just RA itself.

I won't be able to look into this soon, but the releases are built by https://github.com/rust-analyzer/rust-analyzer/blob/master/.github/workflows/release.yaml.

**Comment by qdm12** [comment]
> also install rust-analyzer-preview from a nightly toolchain. You don't need to use the nightly compiler, just RA itself.

Cool I will try that.

> I won't be able to look into this soon, but the releases are built by

Yes I already tried to toy around with it, replacing x86_64 by aarch64 but I get errors down the line after a few minutes of cross compiling and I have no idea what I'm doing 😄
