### ISSUE TITLE
Support for feature(label_break_value)

### ISSUE THREAD

**Issue by jonhoo** [rust-analyzer/rust-analyzer#4747]
The following code compiles fine on nightly:
```rust
#![feature(label_break_value)]

fn main() {
    'block: {
        break 'block;
    }
}
```
but `rust-analyzer` gives an error at the `break 'block`:
```
[rust-analyzer] [E] break outside of loop
```
This is obviously a nightly feature, so don't know how important it is to support it yet, but the RFC has been approved (tracking issue: https://github.com/rust-lang/rust/issues/48594) so it's probably coming sooner or later.

**Comment by Veykril** [comment]
This was fixed in https://github.com/rust-analyzer/rust-analyzer/pull/6839
