### ISSUE TITLE
Fix "unused function" waring from rustc to only color the name of the function

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#4754]
Currently, unused functions are rendered as:

![image](https://user-images.githubusercontent.com/1711539/83870920-5e8fb800-a72f-11ea-8649-9bea9d9df0b7.png)

That is, rustc uses the span of the whole function for diagnostic. It instead should use only the name of the function. 

Note that this is diagnostic which comes from rustc, so I *think* it should be fixed there (unless we are somehow using the wrong span here). 

cc @estebank, is there some existing issue at rust-lang/rust for this?

**Comment by estebank** [comment]
I don't think there's a ticket for it, but it should be very easy to fix.

**Comment by matklad** [comment]
Yup, fixed, thanks! (missed the edit originally)
