### ISSUE TITLE
Auto-importing `std::fmt` can be very slow

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#4763]
Example: Add this to `item_scope.rs`:

```rust
impl fmt::Display for ItemScope {}
```

Then do `Ctrl+.` over the `fmt`. It will take a pretty long time (~2 seconds), even when all the `CrateDefMap`s are cached, and much longer when not.

This is primarily happening because the `query.limit(40);` doesn't actually limit it to 40 entries. I've seen it return over 1000 entries. Fixing that is easy but breaks the auto import completely, since most of the returned symbols are actually for *functions* called `fmt`. This should probably be filtered in the symbol index query, but I'm not yet sure about the best way to do that.

**Comment by flodiebold** [comment]
This would probably also be fixed by building an index on top of the import maps and using that instead, as mentioned in #4515 :thinking:

**Comment by matklad** [comment]
I think the simplest fix here is to add `is_importable: bool` field to [FileSymbol](https://github.com/rust-analyzer/rust-analyzer/blob/02f7b5d7abbab829c2a0f66cdcbb6678afb412a4/crates/ra_ide_db/src/symbol_index.rs#L333). It should be able to determine this syntactically (look if parent is `impl` / `trait`).

**Comment by SomeoneToIgnore** [comment]
Should we rather follow the https://github.com/rust-analyzer/rust-analyzer/pull/4748 approach in the auto import assist instead of a text search we're doing now?
