### ISSUE TITLE
Unused symbol warnings

### ISSUE THREAD

**Issue by cart** [rust-analyzer/rust-analyzer#4766]
#4721 removes the "warning" status from unused symbols. This means they no longer show up in the "problems" panel. Now in order to identify these problems I need to run cargo build/check manually. Having the warnings show up in an easy-to-navigate panel was a nice productivity booster for me. It would be great if we could optionally re-enable the old behavior.

**Comment by freesig** [comment]
I also loved this feature

**Comment by CryZe** [comment]
This has been very annoying to me the last few days as I now need to use the terminal to find all my unused imports and co. and manually navigate to those places.

**Comment by CryZe** [comment]
Can we possibly revert the PR for tomorrow's release and then figure out what to do after?

**Comment by lnicola** [comment]
Already done in https://github.com/rust-analyzer/rust-analyzer/pull/4862.
