### ISSUE TITLE
No runnables for macro-generated code.

### ISSUE THREAD

**Issue by vsrs** [rust-analyzer/rust-analyzer#4771]
For example:

```rust
macro_rules! gen {
    () => {
        #[test]
        fn foo_test() {
        }
    }
}

#[cfg(test)]
mod tests {
    gen!();
}
```

`mod tests` should have `Run|Debug` lens\actions and be available via `rust-analyzer.run` command.

**Comment by mcrakhman** [comment]
I'll work on it

**Comment by zachChilders** [comment]
The same goes for function-like proc-macros as well.  I tried adding a dummy attribute to help resolve as a runnable, but it didn't work :(  It looks like the Runnable detection is only looking for Fn nodes in the AST.  

Is there a way to either:
- resolve runnables _after_ macro expansion
- expand the Runnable detection to include function-like macro invocations so a dummy attribute will work
?

I'd be happy to contribute!

**Comment by bjorn3** [comment]
Function-like proc-macros are not yet supported at all.

**Comment by bugadani** [comment]
Just a different use case for this issue: the `main` function generated by RTIC's `app` attribute also doesn't get picked up as an entry point.

**Comment by lnicola** [comment]
Triage: still happens.
