### ISSUE TITLE
Auto-completion for new added crates needs to restart the server?

### ISSUE THREAD

**Issue by awh6al** [rust-analyzer/rust-analyzer#4782]
I'm using vscode-1.45 with latest rust-analyzer

in Cargo.toml add `num = "0.2.1"` 
in main.rs add `extern crate num;`
save the file
in main.rs type num:: `// nothing displayed here` 
restart the rust-analyzer server 
 in main.rs type num:: `// works fine`

Is it required or we should treated as an issue?

**Comment by lnicola** [comment]
Known issue, duplicate of #3715.
