### ISSUE TITLE
Clear the build task warnings and errors when running cargo check

### ISSUE THREAD

**Issue by CryZe** [rust-analyzer/rust-analyzer#4783]
There's an ongoing set of livestreams where Jonathan Turner (known for nushell and co.) tries to teach Jason Turner (known for cppweekly and co.) some Rust and rust-analyzer is behaving so badly that it's almost more annoying for them to use it than not using it at all I feel like. They are constantly running into stale warnings and errors that are super confusing. https://www.youtube.com/watch?v=Y5-ZgxfQvpc

The problem stems from the fact that they are using the built in Run / Debug / ... commands. However when you trigger a build task with them, the annotations stay until you rerun that build task. The problem is that in the meantime cargo check / cargo clippy will add its own annotations, so you end up with duplicates, but also those properly clear up while the ones from the build task don't.

This is super confusing for beginners and is probably not what you want anyway, as it leads to duplicate warnings. So to resolve this it may make sense to clear the warnings and errors from the build task when updating the warnings and errors from the cargo check.

**Comment by lnicola** [comment]
See also #4768.

**Comment by matklad** [comment]
I agree this is super annoying, but this is a client issue: https://github.com/microsoft/vscode/issues/66982
