### ISSUE TITLE
Doctest code lens is now mixed with function definition and attributes

### ISSUE THREAD

**Issue by aloucks** [rust-analyzer/rust-analyzer#4785]
The doc test code lens used to be at the top of the documentation block, but is now mixed in between the documentation, attributes, and function definition. Can this be changed back or made configurable?

Old display (expected):
![image](https://user-images.githubusercontent.com/221559/83976209-a432b900-a8c6-11ea-969e-03cf0ea50e9f.png)

New display (unexpected):
![image](https://user-images.githubusercontent.com/221559/83976345-64b89c80-a8c7-11ea-9922-c6104c0819bb.png)

**Comment by matklad** [comment]
Agree that this is a bug, we should always draw the thing before comment.

**Comment by aloucks** [comment]
This still seems to be an issue in latest nightly (with regular tests - not specifically doctests)

![image](https://user-images.githubusercontent.com/221559/85232340-34472700-b3cc-11ea-938f-1d8492bf2143.png)
