### ISSUE TITLE
Feature requests poached from the RLS

### ISSUE THREAD

**Issue by DJMcNab** [rust-analyzer/rust-analyzer#479]
This is more of a meta issue, but there are feature requests from the `rls` that we can take inspiration from. If this shouldn't be an issue, then feel free to close, obviously.

[Rls issue tracker](https://github.com/rust-lang/rls/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen).

For an example, see #480.

**Comment by wycats** [comment]
Not sure if this is an RLS feature request, but similar: auto-fill `match type` with enum variants.

**Comment by matklad** [comment]
@wycats  That is already implemented in the simple case where `match` is empty:

https://youtu.be/jNnvaHbnhK8
