### ISSUE TITLE
No autocompletion for a newly added crates as dep

### ISSUE THREAD

**Issue by TheAifam5** [rust-analyzer/rust-analyzer#4790]
## Environment:
- OS: ArchLinux
- VSCode: 1.45.1
- RA Extension: 0.3.198-nightly
- Cargo: 1.45.0-nightly
- RustC: 1.46.0-nightly

## Problem
Adding new dependencies does not refresh RA auto-completion. Executing `cargo build` or using VSCode build task does not refresh it either.
After restarting RA, autocompletion is visible for newly added crates.

## Reproduce
Add any crate as dependency by editing `Cargo.toml` and save.
To be sure, you can build the project. Then go to the `.rs` file and try to use the crate.

#### RA Extension settings:
```json
"rust-analyzer.updates.channel": "nightly",
"rust-analyzer.cargo.loadOutDirsFromCheck": true,
"rust-analyzer.procMacro.enable": true,
```

**Comment by lnicola** [comment]
Known issue, see #3715.
