### ISSUE TITLE
No syntax highlighting for `unsafe extern "C" fn(...)`

### ISSUE THREAD

**Issue by shekohex** [rust-analyzer/rust-analyzer#4795]
Hi, I'm working with FFI and I noticed something strange about syntax highlighting when I write something like this:

```rust
type FooFn = unsafe extern "C" fn(msg: *mut raw::c_char);
```
![image](https://user-images.githubusercontent.com/14620076/84028290-bc6f0a80-a990-11ea-977b-c17987853d56.png)

> I'm using the stable version of rust-analyzer ext v0.2.191 on VSCode
rust-analyzer version: 2020-06-01 (7ae247f)

> PS: I also noticed that GitHub doesn't syntax highlight it either, is something I'm missing?

**Comment by matklad** [comment]
works on master

![image](https://user-images.githubusercontent.com/1711539/87233092-c38c9c80-c3c4-11ea-853d-c03c807c0fd7.png)
