### ISSUE TITLE
unsafe intrinsics are not recognized as such

### ISSUE THREAD

**Issue by crumblingstatue** [rust-analyzer/rust-analyzer#4798]
Most notably, calls to `transmute` are not being highlighted as unsafe with the new unsafe highlighter.
It's not marked an `unsafe fn`, but it is in an `extern "rust-intrinsic"` block, which implicitly makes it unsafe.

**Comment by bjorn3** [comment]
There are also safe intrinsics: https://github.com/rust-lang/rust/blob/73558160933b2764ed9a84b1b2b647e128eac3f8/src/librustc_typeck/check/intrinsic.rs#L72-L77

**Comment by crumblingstatue** [comment]
Ah, interesting. I guess that makes it more complicated to solve this problem.

**Comment by matklad** [comment]
But those are `rustc_private`, right? If that is the case, I am compelled to close this as "won't fix" :) Maintenance/usefulness ratio doesn't seem to enticing in this case.

**Comment by bjorn3** [comment]
`std::mem::transmute` is a re-export of `std::intrinsics::transmute`. There may be other intrinsics that are stabily re-exported.

**Comment by matklad** [comment]
Lol yes:

![image](https://user-images.githubusercontent.com/1711539/84083507-0a602e80-a9e2-11ea-8305-03e688779f67.png)

I this means that we have to special case *implicit* unsafe here:

https://github.com/rust-analyzer/rust-analyzer/blob/3999bbba1bba45ae9d577506c6414f741e1fe80a/crates/ra_hir_def/src/data.rs#L37

Altenratively, perhaps special casing should be removed from compiler, and the `transmute` intrinsic should be marked as unsafe?

**Comment by crumblingstatue** [comment]
Small update: `transmute` is now highlighted in red. Not sure if it's an RA update or a Rust update, but at least `transmute` works now.
