### ISSUE TITLE
Feature: Show default value for types that implement Default

### ISSUE THREAD

**Issue by almindor** [rust-analyzer/rust-analyzer#4806]
It would be useful to be able to see the default values for any type that implements `Default` on hover-over. This is probably a very low chance feature request but it seemed like a fairly useful thing to have to me.

**Comment by matklad** [comment]
Seems too niche -- showing it in any hover would be actively noisy, having a dedicated shortcult would mean that no one would use it. I'd just **goto type definition** to the see the type, and then **go to impl** to find the Default impl
