### ISSUE TITLE
Release 2020-06-08 doesn't work with workspaces

### ISSUE THREAD

**Issue by mkpankov** [rust-analyzer/rust-analyzer#4808]
```
[ERROR rust_analyzer::main_loop] failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /home/mkpankov/work/integrated-manager-for-lustre/Cargo.toml: Failed to run `cargo metadata --manifest-path /home/mkpankov/work/integrated-manager-for-lustre/Cargo.toml`: Error during execution of `cargo metadata`: error: --features is not allowed in the root of a virtual workspace
    note: while this was previously accepted, it didn't actually do anything
```

Worked fine previously

**Comment by matklad** [comment]
Do you have any cargo features enabled in rust-analyzer's settings? I think we shouldn't be passing `--feature` by default.

**Comment by mkpankov** [comment]
Yes, I have one feature enabled. Disabling it fixes the issue, in the sense `rust-analyzer` can work.

**Comment by hrydgard** [comment]
Also running into this, but we can't reasonably disable all our features.

**Comment by mkpankov** [comment]
Me neither, I need that feature enabled 😄 Will stay at previous release for now.

**Comment by matklad** [comment]
I wonder how that worked before... Like, it's true that its impossible to enable feature for a virtual manfirst...

**Comment by hrydgard** [comment]
For me, as I recall, autocompletion was severely limited before in the additional (much smaller) workspace, but rust-analyzer kept working in other files.

**Comment by flodiebold** [comment]
> Like, it's true that its impossible to enable feature for a virtual manfirst...

So is there a way to get metadata for the workspace with certain features enabled (in certain projects)? :thinking:

**Comment by mkpankov** [comment]
I don't have `linkedProjects` setting - the only non-default is Cargo features.

**Comment by matklad** [comment]
I am still not sure what the problem here was, but I guess it doesn’t matter now that cargo support features in virtual manifests,
