### ISSUE TITLE
Strange highlighting in rdoc

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#4809]
tldr:

![image](https://user-images.githubusercontent.com/3784017/84128217-7be3bf80-aa6a-11ea-92ec-3e0085ba25cc.png)

rust-analyzer version: unreleased (733ef31)
Affected code: https://github.com/paritytech/wasmi/blob/master/src/module.rs#L596

**Comment by matklad** [comment]
cc @ltentrup 

well, at least we highlight something :D

**Comment by ltentrup** [comment]
The non-highlighted identifier were not resolved as the analysis of the documentation is independent of the analysis of the source file. 

I guess one could put the documentation code inside an anonymous module and do an implicit `use super::*`?

**Comment by 0x7CFE** [comment]
Looks like this issue is not dependent on actual source. I see the same issues in stdlib, say, `vec.rs`.

**Comment by matklad** [comment]
But even if we don't resolve idents, we *should* color them based on syntax? IE, if you just copy-paste that code into a file whcih doens't have `wasi` dependency, it still will be colored

**Comment by ltentrup** [comment]
They are probably all highlighted as `unresolved_reference` and thus not visible as they are not colored by default?

**Comment by matklad** [comment]
Right... I think we shouldn't use `UnresolvedRerefence` for injections in this way.

**Comment by ltentrup** [comment]
Alright, but unresolved_reference overwrites the actual type, make it a modifier instead?
Or introduce an option to the analysis whether to use unresolved_reference?
