### ISSUE TITLE
"impl Trait + Trait" is displayed incorrectly

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [rust-analyzer/rust-analyzer#4814]
To reproduce, mouse hover over `_x` in the following program:
```rust
use std::ops::{Deref, DerefMut};

fn f(_x: impl Deref<Target=u8> + DerefMut<Target=u8>) {}
```

### Expected result
`impl Deref<Target = u8> + DerefMut<Target = u8>`

### Actual result
`impl Deref<Target = u8> + DerefMut, Target = u8>`

--------------

rust-analyzer version: 2020-06-08 (d696776)

**Comment by matklad** [comment]
Probaby shouldn't be too hard to debug, the tests should be added here:

https://github.com/matklad/rust-analyzer/blob/00c81f8006926b5a326d4dd11f61ea5ae09aadbd/crates/ra_ide/src/hover.rs#L351
