### ISSUE TITLE
Misplaced light bulb

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#4826]
Note that here, the light bulb is shown one line higher than needed:

![image](https://user-images.githubusercontent.com/3784017/84236336-ae042880-ab21-11ea-9da3-f0689e9af81f.png)

rust-analyzer version: unreleased (c9fc725)

P.S.: Also note that it shows "change return type to `Result`" assist which is redundant here, since return type is `Result` already.

**Comment by matklad** [comment]
cc @bnjjj for `Result`

The placement of lightbulb is I thing fully controlled by the editor.

**Comment by bnjjj** [comment]
Ok I will take it I think I already know how to fix that !
