### ISSUE TITLE
linkedProjects doesn't work with relative paths?

### ISSUE THREAD

**Issue by repi** [rust-analyzer/rust-analyzer#4838]
We have multiple Cargo workspaces in our repo (4 actually, though 2 important ones) so tried using the new `linkedProjects` setting to point out the non-root workspace we have which is located in `modules/Cargo.toml`.

Added this to our repo `.vscode/settings.json`:

```json
   "rust-analyzer.linkedProjects": [
        "modules/Cargo.toml"
    ],
```

But starting VS Code and loading this repo folder just results in:

> rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file modules/Cargo.toml: Failed to run `cargo metadata --manifest-path modules/Cargo.toml`: Error during execution of `cargo metadata`: error: manifest path `modules/Cargo.toml` does not exist

Is maybe non-absolute folders not supported for `linkedProjects`? 

That would be very useful to have as we don't want this with an absolute path in a manual per-user setting, this is really part of our repository and we want Rust Analyzer to pick up all of our Cargo workspaces in our repository/folder, either manually or automatically.

**Comment by matklad** [comment]
We now consistently absolutize all the paths relative to the `rootUri` LSP client sets when initializing the server, so closing. 

I am not sure how vscode sets the `rootUri`, especially in presence of multiple workspace folders though. The best way to debg this would be via `RA_LOG=rust_analyzer=info`, and looking for this printout:

https://github.com/rust-analyzer/rust-analyzer/blob/00c81f8006926b5a326d4dd11f61ea5ae09aadbd/crates/rust-analyzer/src/config.rs#L281

**Comment by repi** [comment]
Thanks, will try out the latest
