### ISSUE TITLE
rustc --target configuration in rust-project.json workspaces

### ISSUE THREAD

**Issue by woody77** [rust-analyzer/rust-analyzer#4840]
_Opening an issue to discuss the comment I made in https://github.com/rust-analyzer/rust-analyzer/pull/4784#issuecomment-640262242_

(background for others):
At the moment, the stdlib syntax highlighting that happens in a Cargo.toml project is based on using the default `rustc --target` configuration (ie. the `target_arch`, `target_os`, and `target_has_atomic=<foo>` and other cfg items).

One of the uses of rust-project.json is being able to lay out a codebase that is being cross-compiled, and therefore the default `rustc` configuration isn't the one that will be used.

Some rust-project.json scenarios will involved a mixed set of targets (e.g. "host and target").  For those doing embedded (i.e. nostd) programming, aimed at something like a Cortex-M0, I think this also applies.

(current issue):
I think what's needed is a way to efficiently convey the compilation target configuration to rust-analyzer.

Providing every cfg flag, for every crate, is not a scalable solution (and isn't how `rustc` itself is interacted with.

So I would like to propose that the rust-project.json instead could take the `--target <triple>` information as part of the crate configuration (perhaps as a new, optional, member of `Crate`, and then use that to internally populate the set of `cfg` items that are used for processing the `#[cfg(<foo>)]` statements in the source code.

Much like how RA calls out to `rustc` for the `default_cfg` in Cargo.Toml projects, the process of setting up the ProjectWorkspace::Json could invoke `rustc` once per triple (`rustc --print cfg --target <triple>`) and then use those results for the setup of the crate.

(yes, this is also a volunteering to work on this)

**Comment by woody77** [comment]
I think so.  We should probably setup an issue to talk about target/config switching, though.

**Comment by lnicola** [comment]
Let's close this since it seems fixed. Configuration switching is #6117.
