### ISSUE TITLE
Issue with coc-rust-analyzer after RA 2020-05-25

### ISSUE THREAD

**Issue by Avi-D-coder** [rust-analyzer/rust-analyzer#4853]
See https://github.com/fannheyward/coc-rust-analyzer/issues/283 for details.
What changed between RA 2020-05-25 works but RA 2020-06-01 that might affect method completion.

**Comment by matklad** [comment]
Hard to tell, we did start using preselect more actively some time ago. As this issue stands, it's not too actionable. What would help is just gathering JSON with completions that rust-analyzer sends to the client, it probably would contain an answer.

**Comment by matklad** [comment]
Closing, I don’t see a way to move forward here.
