### ISSUE TITLE
Long delay before completions begin working with nvim-lsp

### ISSUE THREAD

**Issue by nerosnm** [rust-analyzer/rust-analyzer#4861]
- nvim version: `NVIM v0.5.0-nightly-83-ge78658348`
- rust-analyzer version: `rust-analyzer 36353bb`

Apologies if this should be filed in [neovim](https://github.com/neovim/neovim) instead, but I'm not sure exactly where the issue lies.

I'm using rust-analyzer with the built-in LSP support added in nvim 0.5. A minimal `init.vim` configuration is as follows:

```vim
if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
  silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  au VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.local/share/nvim/plugged')
Plug 'neovim/nvim-lsp'
call plug#end()

set omnifunc=v:lua.vim.lsp.omnifunc

lua << EOF
nvim_lsp = require'nvim_lsp'

nvim_lsp.rust_analyzer.setup{}
EOF

set completeopt=menu
set completeopt+=menuone
```

When I open a file in a Rust project, and trigger a completion (e.g. type `use std::collections::H` and press `<C-x><C-o>`), it takes until sometimes as long as 20-30 seconds after nvim startup before rust-analyzer will actually provide completions. After that point, completions are always instantaneous.

**Comment by lnicola** [comment]
See #1650.
