### ISSUE TITLE
Top level attribtues are completed inside nested attributes

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#4890]
![image](https://user-images.githubusercontent.com/1711539/84637894-8e407c00-aef6-11ea-8ac4-cf67c3b15c6d.png)

![image](https://user-images.githubusercontent.com/1711539/84637915-96002080-aef6-11ea-8f58-355a9bc58977.png)

Also, the label here should probably say `deprecated = "..."`, it's better to give visual clues about what would be inserted. 

The relevant code & tests are here: https://github.com/rust-analyzer/rust-analyzer/blob/672d160b013df82b1729fd3db130ff7b6f9b5b31/crates/ra_ide/src/completion/complete_attribute.rs

**Comment by bnjjj** [comment]
Will solve this :)

**Comment by abreis** [comment]
I'm also seeing top level attributes getting completed inside plain text comments:

<img width="445" alt="toplevel" src="https://user-images.githubusercontent.com/95046/84779735-a68ac680-afdc-11ea-9370-10b80eeb1440.png">

... which is quite annoying. Unsure if related.

**Comment by bnjjj** [comment]
@abreis Hmm I think here you're talking about keywords and not attributes

**Comment by abreis** [comment]
Doh, you're right. Nevermind.
