### ISSUE TITLE
rust-analyzer crashes

### ISSUE THREAD

**Issue by Coder-256** [rust-analyzer/rust-analyzer#4895]
For some reason, `rust-analyzer` crashes from time to time. I cannot seem to reliably reproduce it, but here are [two crash reports](https://gist.github.com/Coder-256/b9927ca1eea9c4169c05c3bf96200c56). I think the first crash was with 2020-06-08 and the second with 2020-06-15.

I also uploaded the extension output from the most recent crash. I hope this helps, let me know if you would like any more information. macOS 10.14.6, VS Code 1.46.0.

**Comment by lnicola** [comment]
> `index out of bounds: the len is 209 but the index is 222', crates/ra_ide_db/src/line_index.rs:102:9`

That one might be related to the incremental text sync...

**Comment by lnicola** [comment]
Do you have any non-ASCII characters in your files?

**Comment by Coder-256** [comment]
No. It is possible I typed one or two by mistake but definitely not enough to make that much of a difference.

**Comment by bkchr** [comment]
I see a similar behavior and the document has utf8 characters like emoticons.

**Comment by lnicola** [comment]
@bkchr if you can find a repro, please file an issue :cold_sweat:.

@matklad not sure if this is about the UTF-16 conversion or the incremental sync, but it might be worth fuzzing a little the UTF-16 conversion.

**Comment by lnicola** [comment]
@Coder-256 @bkchr are you still seeing this except e.g. #4841?

**Comment by Coder-256** [comment]
No, I haven’t seen it for a while now, you can close this there’s nothing you can do.

**Comment by bkchr** [comment]
Yeah, I also think that I don't have seen this for quite some time.
