### ISSUE TITLE
{unknown} type information for url::Url::parse

### ISSUE THREAD

**Issue by drguildo** [rust-analyzer/rust-analyzer#4897]
With version 2.1.1 of the url crate and the following code:

```rs
fn main() {
    use url::Url;
    let issue_list_url =
        Url::parse("https://github.com/rust-lang/rust/issues?labels=E-easy&state=open");
}
```

when I hover over `Url::parse` I get `{unknown}`.

**Comment by flodiebold** [comment]
Does it work if you move the use statement outside the function?

**Comment by drguildo** [comment]
@flodiebold Yes. If I move the use to the top level I get the expected type information and documentation.

**Comment by flodiebold** [comment]
Then this is a duplicate of #1165.
