### ISSUE TITLE
vcruntime.dll missing

### ISSUE THREAD

**Issue by Maan2003** [rust-analyzer/rust-analyzer#4898]
## Cannot start Rust analyzer.
![image](https://user-images.githubusercontent.com/49202620/84700893-9db0db00-af71-11ea-962d-a826b2dd8a70.png)

## when manually starting the server.
![image](https://user-images.githubusercontent.com/49202620/84700666-38f58080-af71-11ea-8ce8-5c36434b968e.png)

### versions
```
stable-x86_64-pc-windows-gnu
rustc 1.44.0 (49cae5576 2020-06-01)
cargo 1.44.0 (05d080faa 2020-05-06)
rustup 1.21.1 (7832b2ebe 2019-12-20)
Windows 10 version 1903 build 19028.1
```

**Comment by aloucks** [comment]
You might need to install the  Visual C++ Redistributable:
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

However -- are you specifically wanting to target the gnu toolchain? If not, you might be better off using `stable-x86_64-pc-windows-msvc` and installing the MSVC build tools (or visual studio community):

https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by Maan2003** [comment]
It worked. Thanks a lot for such a early response
