### ISSUE TITLE
Allow setting a command override for Run similar to Check

### ISSUE THREAD

**Issue by dljsjr** [rust-analyzer/rust-analyzer#4902]
We heavily use `cross` for embedded ARM development and it would be a huge plus to be able to use `cross` to run tests with the Run hover details/lens functionality to get that same tight feedback loop.

It seems like the easiest way to handle that would be to allow specifying a custom command override for Run similar to what is done for Check on Save but this might present other issues that aren't immediately obvious.

**Comment by matklad** [comment]
cc @vsrs this is that "create configuration from template" part of the generic run feature

**Comment by matklad** [comment]
To expand on this, I believe the solution here should be general -- the user should be able to specify a template run configuration, which is then used to generate all specific configs. It is also unclear who is reponsible for this -- client or the server....

**Comment by vsrs** [comment]
@dljsjr 
Perhaps there is a bit hacky workaround at the moment:
You can use `Rust Analyzer: Generate launch configuration` from the vscode Command Palette. Then open `launch.json` and modify generated launch configuration:
```jsonc
    {
      "type": "cppvsdbg", // or "lldb", do not change
      "request": "launch", // do not change
      "name": "test some::full::test::name", // do not change
      "program": "cross",
      "args": [
        "test test some::full::test::name",
        "--exact",
        "--nocapture",
        "--target mips64-unknown-linux-gnuabi64"
      ],
      "cwd": "${workspaceRoot}",
    }
```

Now `Debug` lens will use this configuration (and cross command).

I did not check if it really works, but it should.

**Comment by vsrs** [comment]
> It is also unclear who is reponsible for this -- client or the server....

I believe it should be the client. We can have something like a cargo task template in settings. AFAIK [DartCode](https://github.com/Dart-Code/Dart-Code/) has something very close.

**Comment by matklad** [comment]
>You can use Rust Analyzer: Generate launch configuration from the vscode Command Palette. 

We also should extend this to generating non-debug commands. I'd love to use that to set `RA_LOG` env var.

**Comment by vsrs** [comment]
> We also should extend this to generating non-debug commands. I'd love to use that to set `RA_LOG` env var.

Yeah, had that in my plans. Though I can't decide yet what's more convenient:
1) Lookup `launch.json` for a test configuration and reuse `args`, `cwd`, `env`, etc. This will always keep Run and Debug in sync.

2) Add special settings for Run, something like
```jsonc
    "rust-analyzer.cargoTaskTemplates:[
        {
            namePattern: "test exact::test::name",
            "environment": [
                {
                  "name": "RA_LOG",
                  "value": "1"
                }
            ]
        },
        {
            namePattern: "test *", //
            "environment": [... ]
        },
    ]
```
 For this case it is definitely the second. But I want to have Run and Debug environments in sync...

**Comment by vsrs** [comment]
@matklad 
I came to the mind that the solution with some sort of templates is inflexible. And it would be much better to have all logic in a different vscode extension. Yes, an extension for the extension :)
 
The idea is to delegate shell command building to a special "runner" extension if one is specified. MVP works great to my mind:
![custom_cargo_runner](https://user-images.githubusercontent.com/62505555/85128783-a7b92f00-b23a-11ea-8050-b39edbd7319c.gif)
 
What do you think?
 
@dljsjr could you please share some thoughts on the proposed UI? Or maybe you can try this on some real project? To do this you need to uninstall rust-analyzer, install two vsixs:  
[rust-analyzer-0.4.0-dev-cross.vsix](https://conrlab.com/testbed/rust-analyzer-0.4.0-dev-cross.vsix)  
[cross-rust-analyzer-0.0.1.vsix](https://conrlab.com/testbed/cross-rust-analyzer-0.0.1.vsix)
```
code --install-extension rust-analyzer-0.4.0-dev-cross.vsix --force
code --install-extension cross-rust-analyzer-0.0.1.vsix --force
```
and add `"rust-analyzer.cargoRunner": "cross-rust-analyzer"` to the `settings.json`.

**Comment by dljsjr** [comment]
I've heard tale and legend about the breakneck pace of the development on this project but wow y'all are fast.

It works like a dream, and an extension arch sounds a little more user friendly than a template-based configuration if I'm being honest. This seems pretty reasonable to me.

**Comment by matklad** [comment]
@vsrs how did you manage to make "extension for extension" work? Am I guessing correctly that you just execute a VS Code command, and that command happens to be implemented in another extension? I wonder if we could/should do the same for debuggers?

**Comment by matklad** [comment]
FWIW, I think IntelliJ uses something similar for run configurations (though I am not sure if I ever understood the whole picture):

https://www.jetbrains.org/intellij/sdk/docs/tutorials/run_configurations.html

* There are "Run Configurations", which define a format which is stored on disk, as well as a GUI for editing settings. 
* IDE actions (like a run button) produce run configurations
* There's a [thing](https://github.com/intellij-rust/intellij-rust/blob/167a3c030dc181b6000927ab7f7035ab25c12f31/src/main/kotlin/org/rust/cargo/runconfig/command/CompositeCargoRunConfigurationProducer.kt#L36-L46) which can compare configuration to an existing one (so that you can modify a config for a specific test, but still use play button in the UI)
* There's a special [ConfigurationFactory](https://github.com/intellij-rust/intellij-rust/blob/167a3c030dc181b6000927ab7f7035ab25c12f31/src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfigurationType.kt#L42-L44) which creates config from template, which allows user to specify default env vars and such
* Separately from Run Configurations, there are [Runners](https://github.com/intellij-rust/intellij-rust/blob/167a3c030dc181b6000927ab7f7035ab25c12f31/src/main/kotlin/org/rust/cargo/runconfig/CargoCommandRunner.kt) which can execute specific configuraiton type (so, run, debug and coverage are three different runners for a single config).

I am not sure that the IntelliJ setup is right, it seems overly complicated. But domain model here is indeed quite reach, interested, and has natural extension points.

**Comment by vsrs** [comment]
> @vsrs how did you manage to make "extension for extension" work? Am I guessing correctly that you just execute a VS Code command, and that command happens to be implemented in another extension? I wonder if we could/should do the same for debuggers?

Yes, you are correct. Here are the details: [rust-anayzer part](https://github.com/vsrs/rust-analyzer/blob/7e7ed83314f6492097219b41684ec82c54f70716/editors/code/src/tasks.ts#L79-L98) [cross-rust-analyzer](https://github.com/vsrs/cross-rust-analyzer/blob/70303982063392fcfbf305f300ea0d056e563311/src/extension.ts#L76-L101)

And yes, we could use the same for debuggers, build systems, etc. But! rust-analyzer should have some built-in defaults (support of cargo, basic debuggers, etc). I.e. it should be usable without any sub extension (plugin?) installed.

BTW, using commands is a good starting point and perhaps the simplest way to get something working. However, not the best one and has significant performance penalty. Not a big deal in this particular case (and for debuggers), but in general I would prefer another approach when a plugin exports the implemented plugin interface and rust-analyzer uses it via [vscode.Extension.exports](https://code.visualstudio.com/api/references/vscode-api#Extension%3CT%3E)

**Comment by vsrs** [comment]
> I am not sure that the IntelliJ setup is right, it seems overly complicated. But domain model here is indeed quite reach, interested, and has natural extension points.

Thanks, I'll take a look.

**Comment by vsrs** [comment]
@dljsjr thanks for the feedback :)

**Comment by matklad** [comment]
> when a plugin exports the implemented plugin interface and rust-analyzer uses it via vscode.Extension.exports

Aha, now it clicks! Though, I *think* we should arrange this differently -- rust-analyzer should export an extensions point, and other extensions should use it. Ie, it's important that extenension authors don't need upstream coordination.

**Comment by vsrs** [comment]
> Though, I think we should arrange this differently -- rust-analyzer should export an extensions point, and other extensions should use it.

Perhaps it should work in two ways, as we need somehow activate a plugin at first. Pseudocode:
```ts
interface PluginHost {
  // some methods  to get raw info from rust-analyzer
}

interface Capabilities {
    cargoRunner: bool;
}

interface Plugin {
    setHost(host: PluginHost) : Capabilities ;
}

interface CargoRunner {
   // ...
}
```

somewhere in the rust-analyzer vscode extension:
```ts
const ext = vscode.extensions.getExtension(Id);
ext.activate(context);
let plugin = ext.exports as Plugin;
let caps = plugin.setSite(...);
if( caps.cargoRunner ) {
    let runner = plugin as CargoRunner;
   // register as a runner
}
```

> Ie, it's important that extenension authors don't need upstream coordination.

Absolutely agree. Once the interfaces are stabilized, the plugins will become completely independent from the rust-analyzer code. In fact this is the main reason why I think that this solution is better then configuration-template approach.
