### ISSUE TITLE
Disable syntax highlighting for non Rust doc comment code

### ISSUE THREAD

**Issue by chinedufn** [rust-analyzer/rust-analyzer#4904]
I'll sometimes include non-Rust code blocks in my documentation.

Maybe as an instruction on how to run something like in this screenshot, or an example of interop with another language.

Not sure how easy or hard this is - but would be nice if the syntax highlighting didn't happen for non Rust code.

![image](https://user-images.githubusercontent.com/2099811/84721026-a7284c00-af4d-11ea-93e2-26c3e66d534a.png)

**Comment by ltentrup** [comment]
Seems like we have to parse the list of fence-guards and check whether there is some non-rustdoc token.
Relevant code is here:
https://github.com/rust-analyzer/rust-analyzer/blob/83a16e825da2767aaee1d62447eb94f4d7de8881/crates/ra_ide/src/syntax_highlighting/injection.rs#L78-L84

**Comment by matklad** [comment]
It also looks like we still default to unresolved reference as well, which we probably shouldn't do

**Comment by ltentrup** [comment]
The unresolved references should disappear once #4876 is merged
