### ISSUE TITLE
Changing "rust-analyzer.cargo" requires a reload

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-analyzer/rust-analyzer#4906]
Starting today, I've been getting spurious *Changing "rust-analyzer.cargo" requires a reload* messages from the VS Code `rust-analyzer` plugin. I haven't touched my settings, so it sounds like `rust-analyzer` is changing its own settings.

It's popped up and prompted for a reload 3 or 4 times over the last couple hours and will pop up again regardless of whether you reload the app or dismiss it. 

Do you have any idea what is causing these pop-ups?

Version info:

- rust-analyzer version: 2020-06-15 (017331a)
- plugin: v0.2.207
- host platform: x86_64-pc-windows-msvc

**Comment by matklad** [comment]
Hm, no, seems pretty curious...

**Comment by matklad** [comment]
Could you check if it is still reproducible after mondays' release? We've rewritten a bunch of code in that area, so hopefully we now have a different set of bugs!

**Comment by lnicola** [comment]
@Michael-F-Bryan gentle ping: are you still seeing this?

**Comment by Michael-F-Bryan** [comment]
I've since stopped using that Windows machine for development, but remember seeing it up until October.

There isn't really enough information to do anything here, so I'm going to close the issue.
