### ISSUE TITLE
Top level keywords show up as completions in non-code comments

### ISSUE THREAD

**Issue by abreis** [rust-analyzer/rust-analyzer#4907]
I'm seeing top level keyword completion inside plain text comments:

<img width="445" alt="toplevel" src="https://user-images.githubusercontent.com/95046/84779735-a68ac680-afdc-11ea-9370-10b80eeb1440.png">

... which is quite annoying when you end comments with a full stop.

cc #4566 #4700

**Comment by BGluth** [comment]
Should any auto-completion/highlighting be happening in comments?

**Comment by RalfJung** [comment]
> Should any auto-completion/highlighting be happening in comments?

Not sure, but doing none of it would already be an improvement.

**Comment by BGluth** [comment]
Alright I'll give this one a go.

@flodiebold should any auto-completion be active when we're writing a comment?

**Comment by flodiebold** [comment]
Not sure why you are asking me in particular, but, well, in normal comments there is probably no use for autocompletion, but in doc comments we will want some. But it probably makes sense to disable all current completions in comments right now.

**Comment by BGluth** [comment]
Ah ok.

Yeah sorry about that. Wasn't sure who to ask and I just wanted to get something official before I started anything.
