### ISSUE TITLE
Go to definition of type inlay hint

### ISSUE THREAD

**Issue by chinedufn** [rust-analyzer/rust-analyzer#4910]
Not sure whether or not this is possible in VSCode, but it would be nice if when I `Command + Click` on `&TerrainChunkRenderJob` in this screenshot It took me the the struct definition (there is precedence for this in that it is the current behavior of intellij-rust).

![image](https://user-images.githubusercontent.com/2099811/84804584-00858f00-afd1-11ea-9d18-86ba8cbe9c21.png)

Cheers!

**Comment by chinedufn** [comment]
Right now it takes me to the first place that I used `terrain_job` which I think means that it's possible to decide what to do when the hint is clicked ... ?

**Comment by bjorn3** [comment]
You can right click on `terrain_job` and then choose "Go to Type Definition".

**Comment by BGluth** [comment]
It might be a kind of cool feature if this is easy though. Then if you have something like `Option<Bar>` you could just goto the definition of the inner type.

**Comment by matklad** [comment]
cc #4839

**Comment by matklad** [comment]
Fixed by #4839 essentially
