### ISSUE TITLE
Goto definition on self in impl blocks does not go to implementing type

### ISSUE THREAD

**Issue by BGluth** [rust-analyzer/rust-analyzer#4912]
```rust
struct Foo {}
impl Foo {
    fn bar(self<|>) {}
}
```
At this point it nothing happens (as in it's not going to the wrong location).

I couldn't find an existing issue for this anywhere, but if one already exists feel free to close.

**Comment by lnicola** [comment]
I'd argue that's what "Go to type definition" is for (since `self` is a value), but that doesn't work either.

**Comment by BGluth** [comment]
Yeah... "go to type definition" should definitely go to the struct. I'm probably a bit naive when it comes to what exactly "go to definition" should handle, but since there's nothing else to "goto" in this case, should it also just go to the struct?

**Comment by flodiebold** [comment]
Well, that `self` is a definition itself -- when you 'go to definition' on another instance of `self` inside the method, it should go there. So 'go to definition' on the `self` parameter declaration should go to that same token, which I think would make VSCode trigger 'find references' instead?

**Comment by BGluth** [comment]
Is this likely a simple-ish thing to implement? If it is I'll give it a go.

**Comment by BGluth** [comment]
So I've poked at this for a few hours, and I think I could use some guidance on the rough approach of the implementation.

```rust
let (ty, node) = sema.ancestors_with_macros(token.parent()).find_map(|node| {
    let ty = match_ast! {
        match node {
            ast::Expr(expr) => sema.type_of_expr(&expr)?,
            ast::Pat(pat) => sema.type_of_pat(&pat)?,
            _ => return None,
        }
    };

    Some((ty, node))
})?;
```

So right now in `goto_type_definition`, we only match against `Expr` and `Pat`. `self` is of the type `ast::SelfParam` so we abort at this point and don't go any further. Adding another match arm here for `SelfParam` feels kind of odd to me since `Expr` and `Pat` are very "high level" types that will already match against so many things. I was a also bit surprised that there isn't a variant of `Expr` or `Pat` for `self`.

**Comment by flodiebold** [comment]
`self` in the parameter list is its own thing, it's not a pattern (or expression). It's syntactically different from other parameters, and you can't put it into other patterns. That's why it's separate. So it completely makes sense here to handle `ast::SelfParam` as another case, I think.

In *expressions*, on the other hand, `self` is simply a path expression. So I think our existing cases should handle that.

**Comment by lnicola** [comment]
Filed #7316 for find all references not working on `self`.

Other than that, I think there's no need to do anything else here. `Go to Type Definition` works and `self` is a value, not a type, so there's no reason why `Go To Definition` should do the same thing.
