### ISSUE TITLE
Nice to have: Improve errors when rust file is not associated to a crate

### ISSUE THREAD

**Issue by Nashenas88** [rust-analyzer/rust-analyzer#4917]
When new rust devs try using Rust Analyzer for the first time, some of them will create an isolated `.rs` file and run into a bunch of errors/crashes from the rust analyzer plugin in VS Code. It would be nice to display a more friendly error message, something along the lines of "This file cannot be analyzed as it's not associated to any crates, see (some link) on how to create a crate".

**Comment by lnicola** [comment]
@Nashenas88 in a quick test we're no longer crashing here, are you still seeing this?

**Comment by Nashenas88** [comment]
I'm not seeing crashes anymore, but I still see that items aren't recognized. For example, if I add a new file `sample.rs` and try to `use std::collections::Vec`. The entire chain is highlighted as unresolved. There's no indication that you're editing a file that's not part of any modules. It's easier for me to notice since I've updated my styling to mark unresolved items in red, but to new devs, it's especially confusing because the code looks fine, but none of the goto, find implementations, references, etc. functionality works.

**Comment by Veykril** [comment]
We diagnose files that are unlinked now https://github.com/rust-analyzer/rust-analyzer/pull/7966 so I believe we can close this
