### ISSUE TITLE
Uknown type after adding new crate: Requires restarting VScode

### ISSUE THREAD

**Issue by bergkvist** [rust-analyzer/rust-analyzer#4918]
When I add a new crate, crate types will show as unknown.

To get rust-analyzer to infer the types, I need to restart VSCode.

Would be nice if this was dealt with automatically, without having to restart VSCode after every added crate.

How to reproduce:
1. Start VSCode with rust-analyzer
2. Add a crate to Cargo.toml (like roxmltree = "0.11.0")
3. Import the crate in main.rs (use roxmltree;) and compile once to download/compile the crate.
4. rust-analyzer is not able to infer types of roxmltree (displaying {unknown})
5. Restart VSCode
6. Now, types are correctly inferred

**Comment by bjorn3** [comment]
This is https://github.com/rust-analyzer/rust-analyzer/issues/3715.
