### ISSUE TITLE
Locate errors within macro definition.

### ISSUE THREAD

**Issue by iago-lito** [rust-analyzer/rust-analyzer#4924]
I get the following with `rust-analyzer` on:

![error_on_invocation](https://user-images.githubusercontent.com/10091387/84902960-c211d200-b0ad-11ea-809b-f4e98b7b1305.png)

Whereas `cargo check` yields:

```
error: expected identifier, found keyword `fn`
 --> src/main.rs:3:16
  |
3 |         struct fn async {}
  |                ^^ expected identifier, found keyword
...
7 | test!();
  | -------- in this macro invocation
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Put it simply, the error is displayed at the macro invocation, but not within the macro definition.

I understand that it must be difficult and maybe sometimes ambiguous to locate errors within macro definitions. But since `rustc` seems able to locate the error at `3:16`, could `rust-analyzer` not do the same?

It does not yet, which makes it difficult editing macros with large bodies, because no errors pop up within them like they usually do in regular code.

**Comment by matklad** [comment]
Should be fixed around here: https://github.com/rust-analyzer/rust-analyzer/blob/00c81f8006926b5a326d4dd11f61ea5ae09aadbd/crates/rust-analyzer/src/diagnostics/to_proto.rs#L43-L63
