### ISSUE TITLE
doctest syntax highlighting not overriding comment token type in base case

### ISSUE THREAD

**Issue by CAD97** [rust-analyzer/rust-analyzer#4929]
![image](https://user-images.githubusercontent.com/5992217/84931263-8ae8f400-b0a0-11ea-9431-0df83ce406ef.png)

Partial syntax highlighting but with all "normal" tokens in the comment highlighting is somewhat offputting.

This is with no customization of the Rust TextMate grammar beside what is standard with

> vscode version: 1.46.0
> rust-analyzer version: 2020-06-15

**Comment by ltentrup** [comment]
As far as I know, the semantic highlighting overwrites the TextMate Rust grammar. That means that none-highlighted parts by the semantic highlighting get highlighted according to the TextMate grammar.
I am not sure if feasible, but a solution could be to insert a semantic token type for normal/non-highlighted parts.
