### ISSUE TITLE
v0.2.207 not working in VSCode 1.46.0

### ISSUE THREAD

**Issue by krooq** [rust-analyzer/rust-analyzer#4938]
I've installed the latest rust-analyzer release (v0.2.207) in VSCode (1.46.0) and it doesn't seem to work at all.
VSCode says its installed and enabled via the extensions tab but no commands are appear when I search with ctrl+shift+P, no analysis is performed, no option for rust analyzer in the output tab, no prompt to install language server, it's just as if it isn't there.

I tried 
- switching workspaces/projects
- restarting VSCode
- reinstalling rust-analyzer
- uninstalling all other extensions

I reinstalled the previous rust analyzer version v0.2.199 and it works fine.

My VSCode installation and OS version
```
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by Veetaha** [comment]
Could you please show us the log output of the extension? It is under `Help -> Toggle Developer Tools -> Console`?

**Comment by SPARTAN563** [comment]
I'm seeing the following error in the VSCode Console under similar conditions.

```
Activating extension 'matklad.rust-analyzer' failed: EBUSY: resource busy or locked, open '%AppData%\Code\User\globalStorage\matklad.rust-analyzer\rust-analyzer-windows.exe'.
```

*Note that `%AppData%` is expanded in the log entry, but I've redacted it here.*

**Comment by bjorn3** [comment]
@SPARTAN563 Try closing all vscode windows and ensuring that `rust-analyzer-windows.exe` is no longer running. Then you can open vscode again and the download should succeed.

**Comment by Veetaha** [comment]
Yeah, probably should fixe this issue or at least throw a proper error indication (this should have been done quite much earlier than right now I guess). I'll try to tackle this...

**Comment by krooq** [comment]
@Veetaha, this is the error I'm getting in the console

```
Activating extension 'matklad.rust-analyzer' failed: Cannot find module '<my-user-dir>\.vscode\extensions\matklad.rust-analyzer-0.2.207\out\src\main'
Require stack:
- <my-vscode-install>\resources\app\out\vs\loader.js
- <my-vscode-install>\resources\app\out\bootstrap-amd.js
- <my-vscode-install>\resources\app\out\bootstrap-fork.js.
```

**Comment by Veetaha** [comment]
@krooq that's very weird, try the following strictly in order:
- Click `Uninstall` rust-analyzer extension in vscode
- Close vscode
- Remove `'<my-user-dir>\.vscode\extensions\matklad.rust-analyzer-0.2.207`
- Install `rust-analyzer` once again

**Comment by krooq** [comment]
Ok that worked! cool!
Must have been a messed up install of the RLS which windows/vscode cached somewhere.
Thanks a bunch!

I'll close this ticket as I think this is just an odd case and probably a dodgy Australian internet connection thing.
