### ISSUE TITLE
API design question: should ast nodes implement `Deref<Target=SyntaxNode>`

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#494]
Currently, one needs to explicitelly invoke `.syntax()` method to go from, say `ast::FnDef` to `SyntaxNode`. Should we perhaps just `Defer` from `ast::FnDef` to `SyntaxNode`?

**Comment by flodiebold** [comment]
My intuitive answer is no. I've never experienced it as a problem to invoke `.syntax()`. Also, I feel like the AST nodes are a different level of abstraction, not just a 'smart pointer' to a `SyntaxNode`. I think one shouldn't need to go to the `SyntaxNode` that often, and when one does, it's good that it's explicit.

**Comment by matklad** [comment]
That probably makes sense, yeah!

**Comment by pcpthm** [comment]
This is already closed but here if my argument for having `Deref`.

My reasoning is that each `AstNode` type represents "a set of `SyntaxKind`s". For example, `TupleExpr` represents a singleton set `{TUPLE_EXPR}` and `Expr` is the union of `TupleExpr`, `ArrayExpr`, ... = `{TUPLE_EXPR, ARRAY_EXPR, ...}`, then `SyntaxNode` is union of all such `AstNode`s, or, in other words, represents the ground set.
In this way, `SyntaxNode` and other `AstNode` types are not really have "distinct type" and can be treated uniformly.

More specifically, there should be `Deref<Target=B> for A` if and only if `A`'s `SyntaxKind` set is a subset of `B's` `SyntaxKind` set.

Also, in this logic, traits such as `NameOwner` can be an `AstNode` type with union set of such AST node satisfying.

**Comment by matklad** [comment]
So, to get from `TupleExpr` to `Expr` we'd use `&*expr` instead of `expr.into()`? I think that *would* work, but, given that upcasts seem to be relatively rare, explicit `into` call looks better to me. I also worry that providing several `Deref` with different `Targets` for the same type will make type-inference more surprising.

>Also, in this logic, traits such as NameOwner can be an AstNode type with the union set of such AST node satisfying corresponding condition.

I think we can already do this today. That is, we can easily generate a backing-enum for a trait. An alternative would be to just make `AstNode` (and `NameOwner`) object-safe. This is doable, if we rejuggle trait bounds on `AstNode` a bit, but unfortunately not super useful: to be useful, this must support intersections like `N: NameOwner + TypeAscriptionOwner`, but you can't `dyn +` yet.

**Comment by pcpthm** [comment]
> So, to get from TupleExpr to Expr we'd use &*expr instead of expr.into()?
The convenience is mostly for `SyntaxNode` only and having deref to `Expr` was mostly only for generalization in my reasoning. I'm now not sure such generalization will be a plus.

> I also worry that providing several Deref with different Targets for the same type will make type-inference more surprising.
Oh, having multiple `Deref` declarations for a type is impossible actually. I missed that.
So making deref to `NameOwner` probably won't work because there is some incomparable overlapping traits.

**Comment by matklad** [comment]
>Oh, having multiple Deref declarations for a type is impossible actually.

Ah, riiight, `Output` is associated type....
