### ISSUE TITLE
Better Handling of errors in dirty states

### ISSUE THREAD

**Issue by djrenren** [rust-analyzer/rust-analyzer#4946]
Currently rust analyzer gets very confused about problem locations. It appears the issue is that stale error locations persist even when edits should move them.

![dirty_state](https://user-images.githubusercontent.com/634666/85070192-61ed5f80-b183-11ea-94df-643a54263029.gif)

In an ideal world, we'd shift error locations around if their body remains untouched, and invalidate the error if their span is edited. I've implemented this before for the kythe language server. This could greatly improve the quality of life in cases where you can't just recompile whenever you want.

**Comment by matklad** [comment]
I'd say this is the client-side issue. We *can* work around this by forcefully pushing shifted diagnostics ranges, but I'd say that it makes more sense if the client does the shifting itself. 

See also https://github.com/microsoft/language-server-protocol/issues/510

I'll close this issue as I believe it is not really actionable on our side. 

Though, it would be useful if someone finds the rational *why* VS Code doesn't do range shifting.
