### ISSUE TITLE
Doctest syntax highlighting disabled for macro_rules

### ISSUE THREAD

**Issue by ian-h-chamberlain** [rust-analyzer/rust-analyzer#4949]
The new doctest syntax highlighting is awesome!

I noticed that it seems to be disabled for `macro_rules` definitions:
![Screen Shot 2020-06-19 at 09 24 53](https://user-images.githubusercontent.com/11131775/85137402-27310900-b20f-11ea-8532-0bc6df7a49e2.png)

Strangely enough, by adding some characters I can force the syntax highlighting on, but then of course my code is invalid :)
Example:
![Screen Recording 2020-06-19 at 09 25 20 mov](https://user-images.githubusercontent.com/11131775/85138151-509e6480-b210-11ea-9033-e483889efaa8.gif)

Some output from the inspector when it is off and on:
![Screen Shot 2020-06-19 at 09 25 50](https://user-images.githubusercontent.com/11131775/85138180-5b58f980-b210-11ea-98bf-998f639ef60e.png)
![Screen Shot 2020-06-19 at 09 26 06](https://user-images.githubusercontent.com/11131775/85138181-5b58f980-b210-11ea-8a7c-a70f557d8213.png)

**Comment by ltentrup** [comment]
Good catch :) Turns out there was indeed a problem with comments attached to `macro_rules!`
