### ISSUE TITLE
Encountered panic when using `Self` instead of type name 

### ISSUE THREAD

**Issue by yaahc** [rust-analyzer/rust-analyzer#4954]
when testing the fix for #4800 from https://github.com/rust-analyzer/rust-analyzer/pull/4952 on `zebra-network` I still encountered a panic, though a different one from before.

Here is the code in question:

https://github.com/ZcashFoundation/zebra/blob/main/zebra-network/src/peer/error.rs#L8-L20

And the following change seems to resolve it

```diff
❯ git diff
diff --git a/zebra-network/src/peer/error.rs b/zebra-network/src/peer/error.rs
index 82b2a3e..f8143f2 100644
--- a/zebra-network/src/peer/error.rs
+++ b/zebra-network/src/peer/error.rs
@@ -14,8 +14,8 @@ impl<E> From<E> for SharedPeerError
 where
     PeerError: From<E>,
 {
-    fn from(source: E) -> Self {
-        Self(Arc::new(TracedError::from(PeerError::from(source))))
+    fn from(source: E) -> SharedPeerError {
+        SharedPeerError(Arc::new(TracedError::from(PeerError::from(source))))
     }
 }
```

Seems like there's some sort of bug in how it handles `Self` aliases.

**Comment by Speedy37** [comment]
Same as the one I just opened I think: #4953

**Comment by yaahc** [comment]
:thumbsup: closing this as a duplicate then
