### ISSUE TITLE
Feature request: update imports on file move in VS Code

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-analyzer/rust-analyzer#4977]
Today I manually moved a JavaScript file in VS Code into a new directory through the Explorer view, and was met with the following pop-up:

![Screenshot 2020-06-22 07 45 54](https://user-images.githubusercontent.com/2467194/85252681-a9623d00-b45c-11ea-9777-07969975f2fc.png)

This is quite neat, and something that would be great to have for Rust as well. Thanks!

**Comment by yoshuawuyts** [comment]
It seems that the inverse already works though: using "rename symbol (F2)" on a `mod` import automatically renames the file the `mod` points to.

**Comment by lnicola** [comment]
This was implemented in #7009 and other PRs, at least for simple cases.
