### ISSUE TITLE
LinkedProjects with relative paths use the wrong Current Dir.

### ISSUE THREAD

**Issue by rickvanprim** [rust-analyzer/rust-analyzer#4978]
Attempting to set `rust-analyzer.linkedProjects` for multiple nested Cargo.toml's contained inside of a single root folder doesn't appear to work.

For example:
```
"rust-analyzer.linkedProjects": [
    "Scripts/x/Cargo.toml",
    "Code/Foo/foo/Cargo.toml",
    "Code/Bar/bar/Cargo.toml"
]
```

I think the culprit is this code (https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_project_model/src/cargo_workspace.rs#L161):
```
if let Some(parent) = cargo_toml.parent() {
   meta.current_dir(parent);
}
```

If I'm understanding the code correctly, it seems like it will fail in any scenario where the `Cargo.toml` is a relative path that isn't in the current directory.  It seems like the correct version would be:
```
if let (Some(parent), Some(file_name) = (cargo_toml.parent(), cargo_toml.file_name()) {
    meta.current_dir(parent);
    meta.manifest_path(file_name);
}
```

Though I'm not sure the intent behind changing the current directory here, and for my purposes, I'd just assume the working directory was left as my VSCode workspace root.  That said, this doesn't seem like a big deal, just odd, so I assume I'm overlooking someone else's use case.

**Comment by rickvanprim** [comment]
Related: https://github.com/rust-analyzer/rust-analyzer/issues/2649

**Comment by matklad** [comment]
I think I fixed this last week. Now the paths are absolute relative to the workspace url the server is configured with. https://github.com/rust-analyzer/rust-analyzer/blob/6c2f42260c35689647c30966a6ac8447a91c8871/crates/rust-analyzer/src/config.rs#L287
