### ISSUE TITLE
Suggests "where" autocompletion at the end of a sentence

### ISSUE THREAD

**Issue by RalfJung** [rust-analyzer/rust-analyzer#4979]
I am writing comments, and after typing a text like
```
/// Returns whether the two types are equal up to lifetimes.
```
when I typed the final `.`, a menu suggesting "where" as autocompletion appears, so when I hit enter to start a new line, it instead inserts the text "where" at the end of the previous line. That is quite annoying, I have to hit escape-enter each time I want to start a new line.

Is there a way to make RA not auto-complete when writing comments?

**Comment by RalfJung** [comment]
That was in the rustc codebase. In https://github.com/Gilnaa/memoffset/, it suggests a whole bunch of things, the first being "const", so that is what is inserts on `.<enter>`.

**Comment by lnicola** [comment]
Duplicate of #4907?

**Comment by RalfJung** [comment]
Indeed, thanks.
