### ISSUE TITLE
Auto-comment insertion

### ISSUE THREAD

**Issue by RalfJung** [rust-analyzer/rust-analyzer#4980]
I often write long comments (some doc comments, some not) and I got very used to a feature in Kate where when I press Shift-Enter, it insert comment signs into the next line automatically.

To get the same in RA, I got the advice to add this to my shortcuts:
```
    {
        "command": "rust-analyzer.onEnter",
        "key": "shift+enter",
        "when": "editorTextFocus && !suggestWidgetVisible && editorLangId == rust"
    }
```
Unfortunately, this only works for doc comments, not for normal comments. Is there a way to get this behavior for normal (`//`) comments as well?

**Comment by lnicola** [comment]
See https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_ide/src/typing/on_enter.rs#L33.

**Comment by RalfJung** [comment]
(Btw, I am very happy that RA doesn't do this by default when just pressing "enter". I found that really confusing about the previous Rust vscode plugin. I prefer to explicitly request the magic.)

**Comment by RalfJung** [comment]
@lnicola that says
```
 // Continuing single-line non-doc comments (like this one :) ) is annoying
```
I might agree with this for when the behavior happens every time I press enter, but *being able to* auto-continue non-doc comments is very useful. I often find myself writing such comments that span quite a number of lines, and dearly miss the ability of the editor to be able to support me there.

**Comment by lnicola** [comment]
It was disabled in https://github.com/rust-analyzer/rust-analyzer/pull/3557.

Another workaround is to add a `//` line at the bottom:

```rust
// line1<|>
//
```

If you trigger `onEnter`, you'll get a `//` continuation.

**Comment by bjorn3** [comment]
In vscode shift+enter is the shortcut to insert an enter while bypassing any extensions that may have been bound to the enter key.

**Comment by RalfJung** [comment]
@lnicola hm, that's not great as I have to remove that silly extra line at the end when I am done (and re-add it when I want to do more editing), but it is better than nothing.

@bjorn3 ah, interesting! Seems like a matter of preference whether with or without magic should be the default. (Shift-enter still seems to apply auto completion suggestions though, which is a big thing I would have hoped it to bypass.)

**Comment by kaleidawave** [comment]
This is something that I really miss after switching from vscode-rust to rust-analyzer. Writing long doc comments is a real chore. I think if you are in a doc comment (not single line) and press enter then the new lines should start with a doc comment `/// `. This looks quite simple to implement: https://github.com/rust-lang/vscode-rust/commit/9a7e9058dcdc7f1823d777d26e6007417a03824b

**Comment by lnicola** [comment]
@kaleidawave this should already work, as described in https://rust-analyzer.github.io/manual.html#on-enter.

**Comment by kaleidawave** [comment]
> @kaleidawave this should already work, as described in https://rust-analyzer.github.io/manual.html#on-enter.

Whoa nice!!! Didn't realise. Is there a reason that this is not *enabled* by default. Guessing extensions cannot modify key bindings.

**Comment by lnicola** [comment]
Sure, see https://github.com/rust-analyzer/rust-analyzer/issues/4214#issuecomment-623076203.

**Comment by RalfJung** [comment]
FWIW I am quite opposed to extensions modifying what happens on "enter", so I think putting this on shift-enter is a much better default. :)

**Comment by lnicola** [comment]
I'd also be fine with the Code approach, which isn't perfect, but will work in most cases.

**Comment by kaleidawave** [comment]
^^^^ One of the issues with the vscode keybinding approach. Hopefully this can be solved at the vscode level, else it might be worth looking at another way of solving this issue. I occasionally disable rust-analyzer when I am writing rust and don't need suggestions. It would be nice if I could still use enter in the editor 😆

**Comment by lnicola** [comment]
#10384 ported the `vscode-rust` (regex-based) approach for comment continuation, but you can still enable the custom `onEnter`.

The original request (continuing `//` comments) works as designed if you add a space at the end.
