### ISSUE TITLE
rust-analyzer ignores compiler settings?

### ISSUE THREAD

**Issue by mouse07410** [rust-analyzer/rust-analyzer#4985]
MacOS 10.15.5, current toolchain:
```
nightly-x86_64-apple-darwin (default)
rustc 1.46.0-nightly (a8cf39911 2020-06-21)
```
Using `rust-analyzer` from the Nightly toolchain, rather than downloading a separate copy for the VSCode plugin.

Problem: `rust-analyzer` gives me warnings I explicitly told it to ignore:

![Screen Shot 2020-06-22 at 09 31 04](https://user-images.githubusercontent.com/5923577/85293257-1a105600-b46b-11ea-85f0-22dc6f47cb9c.png)

**Comment by flodiebold** [comment]
Have you tried running the build outside of rust-analyzer? I think your attribute should be `#![allow(unused_mut)]`, note the `!`.

**Comment by mouse07410** [comment]
Thank you! My fault - your suggestion worked/fixed it.
