### ISSUE TITLE
Rust-Analyzer suddenly stopped working

### ISSUE THREAD

**Issue by bdashore3** [rust-analyzer/rust-analyzer#4986]
Environment:
- WSL2 running Ubuntu 20.04
- Vscode 1.46.1
- RA 0.2.215

Hi there, I've been using rust-analyzer for a long time and it suddenly crashed on me after pressing update on vscode. The first thing I did was clean-reinstalling the extension which didn't work. Then, I clean installed vscode itself. Rust-analyzer still wouldn't activate.

After some searching, I found out how to enable logging in settings.json, and here's a picture on what the developer console showed me

![image](https://user-images.githubusercontent.com/8082010/85302981-e4259e80-b477-11ea-835f-c5222d5fef33.png)

I tried running `/home/kingbri/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux --version` 
in my terminal and this was the output: `-bash: /home/kingbri/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux: cannot execute binary file: Exec format error`

What can I do to fix this issue? Thanks in advance for your help

**Comment by lnicola** [comment]
Can you try running `file /home/kingbri/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux`?

**Comment by bdashore3** [comment]
@lnicola here's the output

`/home/kingbri/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux: data`

**Comment by lnicola** [comment]
Sounds like it's corrupted. Can you remove that file and try again?

**Comment by bdashore3** [comment]
Vscode prompted me to download the binary again. Same error still pops up and same output from the `file` command

**Comment by lnicola** [comment]
Can you upload that file somewhere?

CC @Veetaha.

**Comment by bdashore3** [comment]
Here's the file

[Dropbox Link](https://www.dropbox.com/s/w8gwu8243mwyuid/rust-analyzer-linux?dl=0)

**Comment by kyasbal-1994** [comment]
Same problem happen to me. 
If I execute the command `/home/kyasbal/.config/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux --version` directly, I could get an interesting log.

```
/home/kyasbal/.config/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux: 1: Syntax error: ")" unexpected
```

I think this is just a --version for rust-analyzer, so I guess this command won't check syntax error of my code. I suspect this error happened inside of the command.

**Comment by lnicola** [comment]
@bdashore3 weird, you file is indeed not executable. Can you download it manually from here and put it in the same location? https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-06-22

```
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ f7 e1 81 45 79 ab 43 9f ┊ 90 91 bb ce c3 3d 4c ed │×××Ey×C×┊×××××=L×│
│00000010│ 9e 36 a4 cc 2f ca 65 19 ┊ d0 ce ec 27 c0 03 44 ac │×6××/×e•┊×××'×•D×│
│00000020│ 4b 51 74 ab 14 47 64 c2 ┊ 2d 17 ed df ca ce ee 81 │KQt×•Gd×┊-•××××××│
│00000030│ a2 3b 46 83 a8 0d d6 3d ┊ ee 29 9f c7 43 63 16 5e │×;F××_×=┊×)××Cc•^│
│00000040│ 84 4e 66 ca 91 62 8f 19 ┊ 92 e8 18 52 33 3a b0 93 │×Nf××b×•┊××•R3:××│
│00000050│ b1 b6 88 85 22 08 28 d0 ┊ 98 65 38 03 ec 8c e9 43 │××××"•(×┊×e8•×××C│
│00000060│ 7e 9d 10 4e 22 05 f1 1a ┊ 28 f1 22 01 a4 f3 72 b1 │~×•N"•×•┊(×"•××r×│
│00000070│ fb 52 93 39 32 91 e3 ed ┊ 35 19 7d 00 81 5b 45 5f │×R×92×××┊5•}0×[E_│
│00000080│ a1 d9 0f 9e f5 47 56 3e ┊ d3 67 16 6a a2 3d c6 1b │××•××GV>┊×g•j×=×•│
│00000090│ dd 3d 3e 44 26 bf 57 2e ┊ 4b 30 90 75 2d 46 a0 ed │×=>D&×W.┊K0×u-F××│
│000000a0│ 73 82 c0 a1 4c e4 b0 8c ┊ 0e ab 51 28 81 d6 60 0d │s×××L×××┊•×Q(××`_│
│000000b0│ 95 b1 01 c6 ac 24 42 0c ┊ bd 42 2a dc 40 8f 93 d6 │××•××$B_┊×B*×@×××│
│000000c0│ 82 23 ea bf c7 9a 43 d9 ┊ 6b 18 85 1f 33 9a 1c 56 │×#××××C×┊k•×•3×•V│
│000000d0│ 2f bb 84 71 0e 19 1c 30 ┊ 27 89 7d 8d f2 9f 96 07 │/××q•••0┊'×}××××•│
│000000e0│ 93 ed 26 be 06 75 66 98 ┊ 58 0e 0f de 14 69 80 95 │××&×•uf×┊X••×•i××│
│000000f0│ 8a d1 b8 b7 05 85 31 79 ┊ f2 2f 70 24 f1 9c 80 b4 │××××•×1y┊×/p$××××│
│00000100│ a6 db 10 32 8a d8 88 ee ┊ d8 f2 f1 b3 3a a4 62 60 │××•2××××┊××××:×b`│
│00000110│ 74 8e 7a 22 57 2a 82 68 ┊ 67 4f 73 53 46 47 33 ac │t×z"W*×h┊gOsSFG3×│
│00000120│ eb 06 8c 9b 98 09 0c f4 ┊ 56 83 0c 3a c6 3a 1d 36 │×•×××__×┊V×_:×:•6│
│00000130│ a4 4a 34 a5 f7 61 cc 72 ┊ 68 43 d4 bf f5 08 bc 50 │×J4××a×r┊hC×××•×P│
│00000140│ 41 61 c4 11 7c 72 0d c4 ┊ 7e fa 76 2a 54 6a d6 d8 │Aa×•|r_×┊~×v*Tj××│
│00000150│ 48 f7 7e 28 29 fe de 4e ┊ 00 fd 1f 52 91 8c ce 38 │H×~()××N┊0×•R×××8│
│00000160│ 13 7c 4e 28 9b 4c 6e ca ┊ 96 a1 37 39 c2 57 c8 0d │•|N(×Ln×┊××79×W×_│
│00000170│ 52 88 80 35 fe b0 11 1d ┊ dd 16 31 b2 cb d4 32 54 │R××5××••┊×•1×××2T│
│00000180│ 12 c9 6a 30 74 9a 72 d2 ┊ 6f f2 a2 bf 82 09 a3 2e │•×j0t×r×┊o××××_×.│
│00000190│ 1c ff 62 81 d3 f6 e2 19 ┊ 65 b8 da a5 23 b7 4b 2e │•×b××××•┊e×××#×K.│
│000001a0│ 7b 9b 45 92 95 76 35 b9 ┊ b3 fe 56 3d 14 aa 36 b0 │{×E××v5×┊××V=•×6×│
│000001b0│ 61 4b 0e 08 63 f8 c6 dd ┊ e3 4c f7 ad e8 10 8e e6 │aK••c×××┊×L×××•××│
│000001c0│ 8f da 5e c9 7e 51 df 6c ┊ 0a b2 c0 22 ee 96 19 56 │××^×~Q×l┊_××"××•V│
```

It's also 27 949 394 instead of 27 966 344 bytes.

**Comment by bdashore3** [comment]
The vsix package or linux executable?

**Comment by Veetaha** [comment]
The linux exe

**Comment by lnicola** [comment]
@kyasbal-1994 can you run `file` and `ls -l /home/kyasbal/.config/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux` and possibly upload it somewhere if it doesn't show up as `rust-analyzer-linux: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=df68b161b4040e76f637e26e634244c2e2b073d6, stripped`?

@bdashore3 the Linux executable. Make sure to run `chmod +x` on it, though.

**Comment by bdashore3** [comment]
Will do, I'll show the results once I get them

**Comment by kyasbal-1994** [comment]
@lnicola Sure I will do that and report.

rust-analyzer works well if I downgraded to 0.2.207 which is the last version available on visual studio code extension menu. If there are someone just want to run rust-analyzer, you can use following link to downgrade the extension.
https://stackoverflow.com/questions/42626065/vs-code-rollback-extension-install-specific-extension-version

**Comment by Veetaha** [comment]
This might be related to #4963. I am not sure how tmp dir might affect the binary on WSL

**Comment by bdashore3** [comment]
@Inicola `rust-analyzer --version` works perfectly on the linux executable

**Comment by bdashore3** [comment]
@Veetaha Same issue happens on windows as well

**Comment by Veetaha** [comment]
Okay, thanks, I'll need to check this

**Comment by kyasbal-1994** [comment]
This is weird. I downgrade rust-analyzer to previous version and updated again. Then it works with the latest version and rust-analyzer-linux seems to be valid Linux ELF binary.

**Comment by lnicola** [comment]
@kyasbal-1994 should have tried that before :-).

**Comment by bdashore3** [comment]
It still errors out for me when downgrading/upgrading with the same error

**Comment by kyasbal-1994** [comment]
> It still errors out for me when downgrading/upgrading with the same error

Did you download rust-analyzer server after downgrading extension?

**Comment by bdashore3** [comment]
Yes, I did

**Comment by lnicola** [comment]
The file @bdashore3 uploaded is missing the first 16 950 bytes.

**Comment by frainho** [comment]
Downgrading worked for me as well. 

I tried to remove `rust-analyzer-mac` but reinstalling the extension didn't trigger an installation of the binary.

**Comment by Veetaha** [comment]
I found the problem, we need a hotfix. We do skip the first chunks of the file....

**Comment by Veetaha** [comment]
This is very wierd beause on my machine (Ubuntu) it works even now, only in Windows Virtualbox this happens...

**Comment by jsj1027** [comment]
Running VSCode 1.46.1 on PopOs 20.04 which is based on Ubuntu 20.04.
Upgrading to 0.2.215 has basically disabled(?) rust-analyzer. No type hinting, no formatting. This is not only a windows problem.

Some specs here
OS: Pop!_OS 20.04 LTS x86_64 
Kernel: 5.4.0-7634-generic
VSCode: 1.46.1
cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
x64

Please let me know any other ways I can help or other info you need from my machine.

**Comment by bjorn3** [comment]
This has been fixed in #4989. The fix will be published next week.

**Comment by lnicola** [comment]
@jsj1027 this was just fixed. A new release will be available soon(ish) in the Marketplace.

**Comment by Veetaha** [comment]
This won't take a week, we will publish a patch today-or-tomorrow https://github.com/rust-analyzer/rust-analyzer/pull/4989#issuecomment-647668226
