### ISSUE TITLE
Extension not compatible with 1.46.1

### ISSUE THREAD

**Issue by leshow** [rust-analyzer/rust-analyzer#4987]
I installed the rust-analyzer update today and it no longer works:

![rust-analzyer](https://user-images.githubusercontent.com/1128302/85304424-bd686780-b479-11ea-8edd-202bad67ccae.png)

**Comment by lnicola** [comment]
Is there anything in the console? The first error might come from a different extension.

**Comment by leshow** [comment]
You can see "activating extension `matklad.rust-analyzer` fail right there during bootstrap

**Comment by lnicola** [comment]
Oh, right, that's the console :facepalm:.

**Comment by leshow** [comment]
Perhaps there's a config file somewhere that has 1.45.1 as a version number in it and it just needs a bump

**Comment by lnicola** [comment]
There's a dependency on `types/vscode@1.45.0`, but that shouldn't be a problem. Plus, I'm running 1.46.1.

**Comment by leshow** [comment]
It stopped working directly after the update this morning I'm getting an error from this also:
```
	at /home/leshow/.vscode/extensions/matklad.rust-analyzer-0.2.215/out/src/main.js:16808:15
	at async activate (/home/leshow/.vscode/extensions/matklad.rust-analyzer-0.2.215/out/src/main.js:16800:24)
	at async Promise.all (index 0)
```

**Comment by BGluth** [comment]
I'm having the same issue.

**Comment by mouse07410** [comment]
Same

**Comment by lnicola** [comment]
CC #4986 which might explain some issues.

**Comment by lnicola** [comment]
@Veetaha for some reason, GitHub didn't close this with #4989. Let's be optimistic.

**Comment by Veetaha** [comment]
I believe that `Extension is not compatible` message comes from some other extension.

**Comment by leshow** [comment]
Still borked as far as I can tell, I tried the new version @lnicola

**Comment by Veetaha** [comment]
@leshow which version have you tried? We haven't published the hotfix yet

**Comment by leshow** [comment]
Oh, I just assumed since it was closed the hotfix was pushed. vscode said the latest version is an hour old

**Comment by matklad** [comment]
The fix was published moments ago

**Comment by leshow** [comment]
works for me
