### ISSUE TITLE
Methods from NewMac trait in hmac not resolved

### ISSUE THREAD

**Issue by mouse07410** [rust-analyzer/rust-analyzer#4991]
MacOS 10.15.5, VSCode 1.46.1, rust-analyzer .207 (.215 simply doesn't work at all here).

When `rust-analyzer` is enabled (and `rls` is disabled):
![Screen Shot 2020-06-22 at 13 27 56 ](https://user-images.githubusercontent.com/5923577/85317682-cc0c4a00-b48c-11ea-8a93-91c4b63ae6cf.png)

When `rls` is enabled instead:
![Screen Shot 2020-06-22 at 13 29 34 ](https://user-images.githubusercontent.com/5923577/85317725-e21a0a80-b48c-11ea-8f8a-cba84fb0dfb9.png)

**Comment by lnicola** [comment]
Repro, with the `sha2` and `hmac` crates:

```rust
use hmac::{Hmac, NewMac};
use sha2::Sha256;

fn _foo(secret: &[u8], _data: &[u8]) {
    let _mac = Hmac::<Sha256>::new_varkey(secret).expect("boop");
}

fn main() {}
```

It seems that `new_varkey` (from the `NewMac` trait) doesn't get resolved.

**Comment by flodiebold** [comment]
```rust
impl<D> NewMac for Hmac<D>
where
    D: Update + BlockInput + FixedOutput + Reset + Default + Clone,
    D::BlockSize: ArrayLength<u8>,
    D::OutputSize: ArrayLength<u8>,
```
That's a lot of where clauses that could potentially be the problem. Also, `NewMac: Sized`, so maybe we're just still missing the `Sized` impl (that can be checked by just writing `impl<T> Sized for Hmac<T> {}`)

**Comment by matklad** [comment]
Triage: still doesn't resolve.

**Comment by mouse07410** [comment]
Ping...?

**Comment by matklad** [comment]
Triage: still doesn't resolve.

**Comment by flodiebold** [comment]
Works for me on master.
