### ISSUE TITLE
Fix lexing of number literals

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#5]
- [ ] make sure that lexer itself works reasonably (note: it's ok to parse more stuff as numbers)
- [ ] create a validator that converts literals to their values, and which checks that all digits are in range, and that there are not too many digits.
- [ ] bazillion of tests: float literals are hard.

**Comment by mystor** [comment]
We want to keep the original textual representation of all literals: we're going to want it later in the pipeline (e.g. for procedural macros). We probably want to do something similar to string literals and lazily interpret the values when they are requested.

(Again, there is a validator for float literals in proc_macro2 which I believe is correct)

**Comment by bjorn3** [comment]
I believe the same lexer as rustc is now used.

**Comment by matklad** [comment]
Indeed!
