### ISSUE TITLE
Failing to download new server version

### ISSUE THREAD

**Issue by Xymist** [rust-analyzer/rust-analyzer#5009]
This has been reproducible (for me) for a few months; I'm open to the possibility it might be my environment but I don't see similar with other extensions.

Steps (tentative):

- RA self updates in VS Code
- Little popup appears in the bottom right saying a new server version is available
- Click download button
- Bar progresses to 1% and then the popup vanishes
- Observe that server version is not updated

Fix/Workaround:

- Uninstall the extension
- `rm -r ~/.config/Code/User/globalStorage/matklad.rust-analyzer/`
- Reinstall the extension

Details:

```
OS: Ubuntu 18.04
VSCode:
  Version: 1.46.1
  Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
  Date: 2020-06-17T21:13:08.304Z
  Electron: 7.3.1
  Chrome: 78.0.3904.130
  Node.js: 12.8.1
  V8: 7.8.279.23-electron.0
  OS: Linux x64 4.15.0-1081-oem snap
```

I will add a DevTools/Console log to this next time an update comes around, assuming it recurs.

**Comment by Veetaha** [comment]
I recommend turning on rust-analyzer.trace.extension in settings.json

**Comment by MinusGix** [comment]
I have had a similar issue, though it usually gets farther than 1%. Occurs with most recent update, and have had it happen in a previous update.  
Output with trace.extension enabled (this is after it failed to download, and I reloaded vscode):  
```
[Extension Host] Extension version: 0.2.224 using configuration: Object
console.ts:137 [Extension Host] PersistentState:  Object
console.ts:137 [Extension Host] Using server binary at /home/minus/.config/Code - OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux
console.ts:137 [Extension Host] Checking availability of a binary at /home/minus/.config/Code - OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux
console.ts:137 [Extension Host]% Objectoutput: (3) [null, "", ""]pid: 176803signal: "SIGSEGV"status: nullstderr: ""stdout: ""__proto__: Object --version output: [Circular]
console.ts:137 [Extension Host] Bootstrap error Error: Failed to execute /home/minus/.config/Code - OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux --version
	at bootstrapServer (/home/minus/.vscode-oss/extensions/matklad.rust-analyzer-0.2.224/out/src/main.js:16820:15)
	at async bootstrap (/home/minus/.vscode-oss/extensions/matklad.rust-analyzer-0.2.224/out/src/main.js:16767:18)
	at async activate (/home/minus/.vscode-oss/extensions/matklad.rust-analyzer-0.2.224/out/src/main.js:16692:24)
t.log @ console.ts:137
abstractExtensionService.ts:396 Activating extension 'matklad.rust-analyzer' failed: bootstrap error. Open "Help > Toggle Developer Tools > Console" to see the logs (enable verbose logs with "rust-analyzer.trace.extension").
_logMessageInConsole @ abstractExtensionService.ts:396
```
Visual Studio Code info:
```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-17T22:31:53.325Z
Electron: 7.1.14
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.125-1-MANJARO
```
The executable exists at `/home/minus/.config/Code - OSS/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux`, and if it is ran (as the logs say), a Segmentation Fault occurs. I believe this is likely due to it being an incomplete download. (The file is 16mb, with an `md5sum` hash of `b7ae6dbac2c3d66d05c7024d395a8d28`. While the original it's trying to download is about 30mb)
Perhaps some form of hash of the file should be made available, and then the extension checks for it's validity?  
Deleting the binary, and reloading, then letting it download once more worked. A simple(?) temporary solution would be to have an extension command to remove the existing binary so that a new one can be downloaded, that way a user does not need to find where it's located.

**Comment by Veetaha** [comment]
@MinusGix could you expand `Object` on `using configuration:` and `PersistentState` lines?

**Comment by MinusGix** [comment]
@Veetaha, sorry, but I can't due to having gotten it to properly download rust analyzer (and I've closed and restarted visual studio code since then).

**Comment by lnicola** [comment]
> The file is 16mb

Can we detect download errors?

**Comment by Veetaha** [comment]
We should be safe not to face incomplete downloads after #5025 , but checking the hash of the downloaded file I think is much safer than running `--version` with UB-flavour when it is corrupted :d

**Comment by lnicola** [comment]
Not incomplete as in "we downloaded everything but forgot to write some of the data to disk", but rather "the server closed the connection before all data was received".

**Comment by Xymist** [comment]
Just to follow up on this, it did _not_ reoccur for me in the latest release. I'll keep an eye on it, as it's clearly something other people have run into occasionally.

**Comment by xobs** [comment]
I'm experiencing this as well.

A long time ago I installed `rust-analyzer` from source. This included installing `rust-analyzer.exe` from Cargo. I was experiencing oddities from the extension, even though I'm running the latest version.

I discovered that it was using `rust-analyzer.exe` from cargo:

```
> rust-analyzer.exe --version
rust-analyzer 6db2da4
> Get-Command rust-analyzer

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     rust-analyzer.exe                                  0.0.0.0    C:\Users\smcro\.cargo\bin\rust-analyzer.exe
>
```

I removed this in the hopes that the extension would download the correct version, however it is now giving errors saying it can't run `rust-analyzer`:

```
[Extension Host] Bootstrap error Error: Failed to execute rust-analyzer --version
	at bootstrapServer (c:\Users\smcro\.vscode\extensions\matklad.rust-analyzer-0.2.224\out\src\main.js:16820:15)
	at async bootstrap (c:\Users\smcro\.vscode\extensions\matklad.rust-analyzer-0.2.224\out\src\main.js:16767:18)
	at async activate (c:\Users\smcro\.vscode\extensions\matklad.rust-analyzer-0.2.224\out\src\main.js:16692:24)
	at async Promise.all (index 0)
	at async h.$activate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:846:297)
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:265
```

**Comment by Veetaha** [comment]
@xobs do you have this in `settings.json`?
```json
{ "rust-analyzer.serverPath": "rust-analyzer.exe" }
```
If not might I ask you to add
```json
{ "rust-analyzer.trace.extension": true }
```
and send us the logs from `About > Toggle Developer Tools > Console` with all objects expanded?

**Comment by xobs** [comment]
@Veetaha I did not have that in `settings.json`.

And annoyingly, enabling extension tracing fixed the problem -- I saved `settings.json` and exited out of Visual Studio Code, and when I opened it up again it prompted me to download the language server.

**Comment by Veetaha** [comment]
I am glad it works for you. I'll try to improve our logging situation to allow us get the logs much cleaner from the users.

**Comment by xobs** [comment]
Well, I did have it happen again today, though the issue seems more mundane. Also, it's actually attempting to download now:

```
[Extension Host] activating extension
console.ts:137 [Extension Host] starting language server
2console.ts:137 [Extension Host] (node:35352) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
console.ts:137 [Extension Host] Bootstrap error Error: EPERM: operation not permitted, unlink 'c:\Users\smcro\AppData\Roaming\Code\User\globalStorage\matklad.rust-analyzer\rust-analyzer-windows.exe'
t.log @ console.ts:137
notificationsAlerts.ts:40 Cannot activate rust-analyzer: bootstrap error. Open "Help > Toggle Developer Tools > Console" to see the logs (enable verbose logs with "rust-analyzer.trace.extension")
onDidChangeNotification @ notificationsAlerts.ts:40
abstractExtensionService.ts:396 Activating extension 'matklad.rust-analyzer' failed: bootstrap error. Open "Help > Toggle Developer Tools > Console" to see the logs (enable verbose logs with "rust-analyzer.trace.extension").
_logMessageInConsole @ abstractExtensionService.ts:396
log.ts:197   ERR Object has been destroyed: Error: Object has been destroyed
    at WebContents._send (<anonymous>)
    at WebContents../lib/browser/api/web-contents.js.WebContents.send (electron/js2c/browser_init.js:3696:15)
    at IpcMain.<anonymous> (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:528:868)
```

In this case, it's because `rust-analyzer` is running in another vscode window. In order to work around the problem I need to kill `rust-analyzer.exe` five times, then reload the window in question.

Note that this is different from the previous issue, where it didn't appear to even attempt to download anything.

**Comment by Veetaha** [comment]
You should not kill `rust-analyzer.exe`, vscode restarts it automatically, you should close other vscode windows instead

**Comment by paulirotta** [comment]
I'm seeing this for the first time. Windows, production release install in VSCode

![image](https://user-images.githubusercontent.com/3486467/95171864-32f50b00-07bf-11eb-98ee-122f58d7f51c.png)

**Comment by lnicola** [comment]
Do you have two Code (or RA LSP server) instances running?

**Comment by paulirotta** [comment]
No. I did yesterday, but all vscode instances closed before this. Running two vscode instances of which one is a library used by the application and referenced locally with `../libname` may have contributed. It does lead to other issues like failure to reindex as code changes.

**Comment by lnicola** [comment]
@Xymist are you still having issues?

**Comment by Xymist** [comment]
I have seen it since my last comment in this thread, but not in a couple of months and I upgrade whenever the option is available. At this point unless someone else has a replication I think it's safe to consider it either solved or at least not recurring.
