### ISSUE TITLE
vscode extension fails to bootstrap on windows

### ISSUE THREAD

**Issue by dlunch** [rust-analyzer/rust-analyzer#5019]
Extension fails to bootstrap on windows since release 2020-06-22

`await fs.promises.realpath(os.tmpdir());` fails.
![image](https://user-images.githubusercontent.com/1371509/85523573-200c5f80-b642-11ea-8b6b-4e20ea67ceb9.png)

https://github.com/rust-analyzer/rust-analyzer/blob/dceb81856eebc35856081587fac6339374c6e177/editors/code/src/net.ts#L141

**Comment by lnicola** [comment]
Does `os.tmpdir()` work? What kind of drive is `R:`?

**Comment by dlunch** [comment]
`os.tmpdir()` works and returns `R:\Temp`, and `R:` is Ramdisk.

**Comment by lnicola** [comment]
@Veetaha do we even care for `realpath`? I don't think it's needed.

We could also download it in the extension directory instead of `TEMP`.

**Comment by Veetaha** [comment]
Hmm, yup I think we may omit `realpath`.
I thought about downloading into the extension dir, but temp dir is what it exists for, os will take care of removing the garbage if e.g. user closed vscode in the middle of our download

**Comment by lnicola** [comment]
> os will take care of removing the garbage

Actually, it generally doesn't. Disk Cleanup can delete temporary files and there's a pattern of using `O_TMPFILE` (or `unlink`) on Linux, but temporary files often remain there for years.

**Comment by bjorn3** [comment]
On Linux `/tmp` is either a `tmpfs` (ramdisk) or it is cleared on startup.

**Comment by Veetaha** [comment]
That's what I've learnt from [here](https://advancedweb.hu/secure-tempfiles-in-nodejs-without-dependencies/#problem-4-cleanup)

**Comment by lnicola** [comment]
I think we could download it to the extension storage directory and a fixed name. Even if it's aborted, next time we'll overwrite it anyway.
