### ISSUE TITLE
Infinite cargo check and 100% CPU

### ISSUE THREAD

**Issue by max-frai** [rust-analyzer/rust-analyzer#5030]
On latest master when I open some rust project, i get infinite cargo check loading animation in status bar and lots of rustc processes which heats my macbook to 95 degress and 100% cpu.

**Comment by lnicola** [comment]
It will likely finish and be fast next time. You can close your editor and launch `cargo check` from a terminal to watch it, or you can disable `rust-analyzer.checkOnSave.enable`.

**Comment by Veetaha** [comment]
![image](https://user-images.githubusercontent.com/36276403/85565197-98215800-b637-11ea-8c73-058cd18aa467.png)
Rust-analyzer infinetly spawns rustc to the extents all my ram and CPU are used up and I need to poweroff my laptop

**Comment by max-frai** [comment]
@Veetaha yes, that's it. When I kill rustc it spawns again

**Comment by lnicola** [comment]
@Veetaha try `ps auxfwwwwwwwwwww` and look for the subtree rooted under `rust-analyzer`.

**Comment by Veetaha** [comment]
@lnicola 
It do is rooted under `rust-analyzer`, @matklad do you think new vfs could break this?

**Comment by matklad** [comment]
Yup, I'd say it's the VFS refactoring, will try to look into this today

**Comment by lnicola** [comment]
I meant, what are they compiling?

**Comment by max-frai** [comment]
Probably yes, because with rustc and rust-analyzer I also see `fseventsd` process with 300% cpu usage.

**Comment by max-frai** [comment]
Command line of one of the rustc.
```
/Users/frai/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/rustc --crate-name regex_syntax /Users/frai/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-syntax-0.6.12/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata -Cembed-bitcode=no -C debuginfo=2 --cfg feature="unicode-age" --cfg feature="unicode-bool" --cfg feature="unicode-case" --cfg feature="unicode-gencat" --cfg feature="unicode-perl" --cfg feature="unicode-script" --cfg feature="unicode-segment" -C metadata=04af33dbb50d13a5 -C extra-filename=-04af33dbb50d13a5 --out-dir /Users/frai/Workspace/Rust/browser-rs/target/debug/deps -L
```

It looks like it's infinitely recompiles crates from cargo.toml

**Comment by Veetaha** [comment]
It's hard to tell, there are a ton of local crates in my workspace (which is private). Tho it looks like the processes are not right under `rust-analyzer`, but under `systemd`, which is most likely beacuse they are wrapped with `sccache`.

**Comment by bjorn3** [comment]
> Tho it looks like the processes are not right under rust-analyzer, but under systemd,

That almost always means that the parent exited. If a process exits all it's children will get a ppid (parent pid) of 1 (systemd in your case).

**Comment by matklad** [comment]
fixed in https://github.com/rust-analyzer/rust-analyzer/pull/5035/commits/ddc5a3e5679bab2ae574fcfc6b7afcbd31b702bc

Rule of thumb: don't use long common prefixes when naming things, it would be impossible to debug the code:

![image](https://user-images.githubusercontent.com/1711539/85580670-39aaa880-b63c-11ea-8a29-3e3c929957ee.png)

**Comment by lnicola** [comment]
Why isn't that a warning?

**Comment by bjorn3** [comment]
`n_entries_total` is used as argument to `report_progress` below. For the self comparison I would not be surprised if there is a clippy lint for it.

**Comment by matklad** [comment]
That's a clippy warning. It is indeed a case were using clippy would have saved me half an hour. 

But I guess this warning should be moved into rustc proper, it seems unlikely that this'll trigger false positives.
