### ISSUE TITLE
VSCode: Format document not working

### ISSUE THREAD

**Issue by maver1ck** [rust-analyzer/rust-analyzer#5036]
Hi,
I have following problem.
I'm using VS Code on WSL with Rust-analyzer extension.

When trying to use Format Document command I'm getting error:
```
[Error - 5:06:37 PM] Request textDocument/formatting failed.
  Message: No such file or directory (os error 2)
  Code: -32603 
```

cargo fmt is working properly.

**Comment by Rerumu** [comment]
I also have this problem. The error shows up in my Solus VM when the extension is enabled on VSCode and I try to format the code. `rustfmt` is up to date and fine according to `rustup`.

**Comment by matklad** [comment]
The most likely code is that `rustfmt` is not in PATH for the VS Code process. #5087 will fix this issue for majority of cases.

**Comment by maver1ck** [comment]
@matklad 
After this fix will $HOME/.cargo/bin will be in PATH ? 
(this is default place for installing rust binaries in linux)

**Comment by bjorn3** [comment]
No, it will just look for rustfmt in `~/.cargo/bin`, even when that directory is not in `PATH`.

https://github.com/rust-analyzer/rust-analyzer/blob/9617bb4f07f724b25abd4040a960f5ccff97b569/crates/ra_toolchain/src/lib.rs#L27-L35

**Comment by maver1ck** [comment]
Thanks :)

**Comment by djave-co** [comment]
I ran `brew install rustfmt` to fix this.

**Comment by Alan3344** [comment]
It turns out that rust is not installed 🐶

```bash
➜  rs_desktop git:(master) ✗ which rustc         
/opt/homebrew/bin/rustc

➜  rs_desktop git:(master) ✗ which rustfmt   
rustfmt not found

# then

==> Downloading https://formulae.brew.sh/api/formula.jws.json
curl: (28) Operation too slow. Less than 100 bytes/sec transferred the last 5 seconds                                                     
...


➜  rs_desktop git:(master) ✗ which rustfmt
/opt/homebrew/bin/rustfmt

```

**Comment by siddharth1729** [comment]
# For Linux

Tye the command 
```bash
       sudo apt install rustfmt
```

and then in vscode press ctrl+shift+i togather

you are all done,
Happy Rusting
