### ISSUE TITLE
Semantic Highlighting: Emit mutable modifer for `&mut self`?

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#5041]
Title should speak for itself, currently `&mut self` doesn't mark self as mutable, by value as in just `mut self` doesnt either. I feel like this should ideally be the case though, as other variables containing mutable references do get this modifier.

Edit: Most of this has landed with #5345, with the exception of using a mutable self in a readonly access, like a variable read access or a function that takes self by reference.

**Comment by ruabmbua** [comment]
This might be problematic. self is a **selfKeyword**. Would it make sense to apply a mutable modifier to a keyword token type?

**Comment by Veykril** [comment]
I mean the `self` is already handled as a special keyword since it has its own semantic highlighting rule `selfKeyword`. And to my knowledge the `self` keyword/identifier always acts like a (special) variable in methods, which is why imo it would make sense for it to get the mutable modifier if it is a mutable reference(or even a `mut self` by value). Feel free to correct me if im wrong with this tho.

The reason as to how I came to notice this "problem" is that I use sem highlighting to underline mutable variables/identifiers but this unfortunately can't, at least currently, be applied to `self`.

**Comment by matklad** [comment]
Yes, we should apply mutable to self.

Relevant code is here https://github.com/rust-analyzer/rust-analyzer/blob/ba48c6548c4e9a1fa6a4c12372c64d41781c1559/crates/ra_ide/src/syntax_highlighting.rs

**Comment by Veykril** [comment]
Partially solved in #5345, left over part can be tracked in #5461.
