### ISSUE TITLE
Inline module to file refactoring

### ISSUE THREAD

**Issue by theduke** [rust-analyzer/rust-analyzer#5054]
A code action that moves a top level inline module to it's own file would be very handy.

**Comment by matklad** [comment]
Some code pointers:

* fix that creates a new module: https://github.com/rust-analyzer/rust-analyzer/blob/3615347fcebebaa58a5cbf675ae062aae149d9c3/crates/ra_ide/src/diagnostics.rs#L58-L70
* there's no specific assists which feels similar, but, for example, add_function touches more than one file: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_assists/src/handlers/add_function.rs

**Comment by theduke** [comment]
This is implemented now.
