### ISSUE TITLE
ra_ide_db fails to compile on PocketBeagle computer

### ISSUE THREAD

**Issue by buzmeg** [rust-analyzer/rust-analyzer#5067]
"cargo xtask install --server" eventually dies at ra_ide_db because it eventually chews up 512MB of RAM on a PocketBeagle computer and gets out of memory killed.

I had a similar problem with rustup where they had a peak usage that would overflow.  However, they fixed it.  See:
https://github.com/rust-lang/rustup/issues/2340

Quoting:
> This is likely fixed with master which probes for available memory using
the effective-memory crate.

> The memory spike is due to having to hold buffers for incomplete writes.

I will check if swap allows the process to complete.  However, as these systems all have flash-based filesystems, swap is not a good solution.

Thanks.

**Comment by bjorn3** [comment]
Have you tried passing `-j1` to cargo to prevent multiple parallel rustc processes? (edit https://github.com/rust-analyzer/rust-analyzer/blob/3615347fcebebaa58a5cbf675ae062aae149d9c3/xtask/src/install.rs#L134)

**Comment by buzmeg** [comment]
Can confirm adding swap allows compile to complete.  I will try with -j1 to see what happens.

**Comment by buzmeg** [comment]
How do I pass "-j1" to the appropriate commands.  Nothing I do seems to work.  For example:

```
# export RUSTFLAGS="-j1" 
root@beaglebone:~/rust-analyzer-2# time cargo xtask install
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -j1 --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
--- stderr
error: Unrecognized option: 'j'

```

**Comment by bjorn3** [comment]
-j1 is not a rustc argument. It is a cargo argument. You can edit the cargo invocation at https://github.com/rust-analyzer/rust-analyzer/blob/3615347fcebebaa58a5cbf675ae062aae149d9c3/xtask/src/install.rs#L134

**Comment by buzmeg** [comment]
Can confirm that -j1 doesn't change things.  This is not surprising as the chip only has a single A8 core.

```
 # time cargo xtask install
   Compiling xtask v0.1.0 (/root/rust-analyzer-2/xtask)
    Finished dev [unoptimized] target(s) in 22.88s
     Running `target/debug/xtask install`
> cargo --version
cargo 1.44.1 (88ba85757 2020-06-11)
> cargo install -j1 --path crates/rust-analyzer --locked --force 
  Installing rust-analyzer v0.1.0 (/root/rust-analyzer-2/crates/rust-analyzer)
    Updating crates.io index
   Compiling ra_ide_db v0.1.0 (/root/rust-analyzer-2/crates/ra_ide_db)
error: failed to compile `rust-analyzer v0.1.0 (/root/rust-analyzer-2/crates/rust-analyzer)`, intermediate artifacts can be found at `/root/rust-analyzer-2/target`

Caused by:
  could not compile `ra_ide_db`.

Caused by:
  process didn't exit successfully: `rustc --crate-name ra_ide_db --edition=2018 crates/ra_ide_db/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C debuginfo=0 -C metadata=cd6412056c55cbf2 -C extra-filename=-cd6412056c55cbf2 --out-dir /root/rust-analyzer-2/target/release/deps -C incremental=/root/rust-analyzer-2/target/release/incremental -L dependency=/root/rust-analyzer-2/target/release/deps --extern either=/root/rust-analyzer-2/target/release/deps/libeither-dfed31a392aedfea.rmeta --extern fst=/root/rust-analyzer-2/target/release/deps/libfst-59e43af35a29fa04.rmeta --extern log=/root/rust-analyzer-2/target/release/deps/liblog-0e590f17c3c4559d.rmeta --extern once_cell=/root/rust-analyzer-2/target/release/deps/libonce_cell-b7fa5b4adfd48191.rmeta --extern ra_db=/root/rust-analyzer-2/target/release/deps/libra_db-b0d1d62e20cb8249.rmeta --extern hir=/root/rust-analyzer-2/target/release/deps/libra_hir-2575e1cf737ef491.rmeta --extern ra_prof=/root/rust-analyzer-2/target/release/deps/libra_prof-e252edca3f2f32ff.rmeta --extern ra_syntax=/root/rust-analyzer-2/target/release/deps/libra_syntax-a268f1ca8234ab95.rmeta --extern ra_text_edit=/root/rust-analyzer-2/target/release/deps/libra_text_edit-65504f750098197d.rmeta --extern rayon=/root/rust-analyzer-2/target/release/deps/librayon-579d180634971d45.rmeta --extern rustc_hash=/root/rust-analyzer-2/target/release/deps/librustc_hash-5220f8d22a79c07f.rmeta --extern superslice=/root/rust-analyzer-2/target/release/deps/libsuperslice-1b903db085c3acc4.rmeta --extern test_utils=/root/rust-analyzer-2/target/release/deps/libtest_utils-222f80ca0c5efbed.rmeta` (signal: 9, SIGKILL: kill)
Error: install server

Caused by:
    0: process `cargo install -j1 --path crates/rust-analyzer --locked --force ` failed
    1: exit code: 101

real    39m2.673s
user    22m35.302s
sys     1m54.413s

```

**Comment by lnicola** [comment]
Does turning down `codegen-units` to `1` help here? Also, would it be possible to cross-compile it instead?

**Comment by buzmeg** [comment]
I'm willing to try if you tell me how to turn the codegen-units down.

Yes, it's always *possible* to cross compile.  That has its own set of issues and generally winds up producing subtle bugs that are hard to track down.  However, that's a band-aid along the lines of "I can enable swap".

I also would like to know "Why is this particular crate out of all of the 190+ the only one causing a memory hiccup?"

In addition, I don't want to let this drop because this is part-and-parcel of "Rust is painful to compile".

**Comment by bjorn3** [comment]
> I'm willing to try if you tell me how to turn the codegen-units down.

Add the following to the bottom of `Cargo.toml`:

```toml
[profile.release]
codegen-units = 1
```

or set `RUSTFLAGS="-Ccodegen-units=1`.

**Comment by matklad** [comment]
We improved our compile times/separate compilation quite a bit recently, might make sense to retry this now.

**Comment by lnicola** [comment]
We've done a bunch of cross-compilation work in CI lately and the story is pretty reasonable (`rustup target add`, `cargo build --target` and maybe install a target-specific `gcc` and set `CARGO_TARGET_FOO_LINKER`). I disagree that it leads to more bugs -- we already cross-compile some of our release binaries.

We could still build 32-bit binaries on CI, but there's a bunch of ARM targets and I'm not sure which ones people care about. And there's still the option of installing a (pretty outdated) version from `rustup`.

The `rustup` change you mentioned is unrelated: it was probably uncompressing to memory or allocating too much. We don't, however, pass a compiler option saying "try to OOM on this crate".

**Comment by buzmeg** [comment]
I'm going to close this as I'm not driving the PocketBeagle project anymore.  If this pops back up, I'll refile a new bug.

Thanks.
