### ISSUE TITLE
Support quick fix to convert `impl Trait` function arg to named generic

### ISSUE THREAD

**Issue by jackh726** [rust-analyzer/rust-analyzer#5085]
(and back)

Example:
```
trait Foo {}
fn bar(&impl Foo) {}
```
to
```
fn bar<F: Foo>(&F) {}
```

**Comment by matklad** [comment]
The to should also have F: Foo bound

**Comment by jackh726** [comment]
> The to should also have F: Foo bound. An example of similar assist: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_assists/src/handlers/move_bounds.rs

Yeah, sorry. Updated.
