### ISSUE TITLE
Setting rust-analyzer.serverPath silently hoses things up if incorrect

### ISSUE THREAD

**Issue by buzmeg** [rust-analyzer/rust-analyzer#5091]
If you have serverPath set incorrectly, rust-analyzer/VSCode gives no indication of the fact that it can't find the server.  It just quietly fails.

I discovered this when I attempted to use rust-analyzer on my local machine instead of on a remote machine like I had been doing.

I believe that #5045 is a special case of this, so I have closed that bug in favor of this one.

Thanks.

**Comment by Veetaha** [comment]
This is very weird. When testing https://github.com/rust-analyzer/rust-analyzer/pull/4993 I clearly saw an error notification pop up (even made a screenshot of one).
But right now, when trying to synthesize an error there is no popup notification. I remember even hitting such a case where there was no notification about the activation failure before https://github.com/rust-analyzer/rust-analyzer/pull/4993, but for some reason when writing that PR everything worked as intended so I just didn't elaborate on that.
The 100% solution would be just forcing an error notification, but it would be better to find out what is going on...
