### ISSUE TITLE
rust-analyzer.serverPath affects both local and remote instances

### ISSUE THREAD

**Issue by buzmeg** [rust-analyzer/rust-analyzer#5092]
If you set rust-analyzer.serverPath, it takes effect for both local and remote instances.

This is highly unlikely to be correct.  serverPath could conceivably be different for every single remote host.

For starters, a new variable called remoteServerPath probably needs to come into existence.

However, rather than a simple filepath, it probably eventually needs to become a list which keeps (hostname, serverPath) pairs.

Thanks.

**Comment by lnicola** [comment]
> For starters, a new variable called remoteServerPath probably needs to come into existence.

I don't think so. In Code extensions can run locally or on the remote. If you want a remote extension, you'll have to install it there and it will run in a headless Code instance without caring whether you're connecting remotely or not.

If you want different LSP server paths on different computers, you can use a workspace settings file. But I don't see why that's necessary -- you should put the binary somewhere in `PATH` instead.

**Comment by buzmeg** [comment]
> But I don't see why that's necessary -- you should put the binary somewhere in PATH instead.

That's fine, but rust-analyzer needs to not be incorrectly clever when it doesn't recognize the architecture.  Quoting from issue #4699

> The bug seems to be in the local plugin in rust-analyzer/editors/code/out/main.js in getServer
> 
> For some reason, the code drops through the
> 
>     if (config.package.releaseTag === null)
>         return "rust-analyzer";
> 

serverPath was the workaround to this problem.

**Comment by lnicola** [comment]
You can use `"rust-analyzer.serverPath": "rust-analyzer"` and make sure the server is in `PATH`, at the cost of losing auto-updates on the local side.

**Comment by niderhoff** [comment]
I have manually installed the analyzer using cargo:

niid@DESKTOP-9OF9U33:~/projects/rust-book/minigrep$ which rust-analyzer-linux 
/home/niid/.local/bin/rust-analyzer-linux

And I have set "rust-analyzer.serverPath" to "rust-analyzer-linux", but the extension tries to download it anyway and ignores the binary in PATH?

**Comment by mimoo** [comment]
same problem here, now that I have set serverPath I can't use rust-analyzer locally anymore :( 

not sure I understand your solution @lnicola

**Comment by lnicola** [comment]
The overeager arch detection was fixed in https://github.com/rust-analyzer/rust-analyzer/pull/7194. I'm going to close this, but please reopen or file another issue if required.
