### ISSUE TITLE
Name-based IDs

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#510]
One thing I've realized when implementing macros is that ID's can be recursive: IdLoc can contains `parent: Option<Id>` field. And that leads to a more "natural" representation of `ModuleId`:

```rust
enum ModuleLoc {
    Root(CrateId),
    FakeRoot(FileId), // for files which do not belong to any crate
    Child { parent: ModuleId, name: Name }
   // BlockModule { function: FunctionId, block: usize}
}
```

Something similar can be done for other defs:

```rust
struct FunctionLoc {
    parent: ModuleOrImplOrTraitId,
    name: Name,
}
```

This seems to be a more natural and more stable representation then a `SourceItemId` based one, but that means that we won't be able to use a single `DefLoc` for everything. Though, we could define `DefId` as `enum DefId { Module(ModuleId), Enum(EnumId), }` etc. 

Should we do this change? I don't know, but this looks like a reasonable approach.

**Comment by flodiebold** [comment]
Hmm. Maybe something like `enum DefLoc { Module(ModuleLoc), Named { parent: DefId, name: Name } }` could work?

Also wouldn't we still need an index (i.e. 'the nth function with that name') in case someone just writes two functions with the same name?

For the stability, would it maybe be enough to separate the ids by kind (i.e. make the `DefLoc` based on 'the nth item of that `DefKind`' instead of basing it on the name)?

**Comment by matklad** [comment]
Thinking about this more, it seems that index-based IDs for modules make more sense in the end: I *think* we'll have to produce a module tree for a crate in one go anyway, and so packing all the data in one vector will be nice performance & memory usage wise. 

However I still want to get rid of `SourceRoot`s which poison Module (and other) IDs. 

So, something like

```
enum CrateRoot {
    Real(CrateId),
    Fake(FileId),
}

struct ModuleIdx(RawId)

struct ModuleTree {
    crate_root: CrateRoot,
    modules: Arena<ModuleIdx, Module>
}

struct ModuleId(RawId);
struct ModuleLoc {
    crate_root: CrateRoot,
    idx: ModuleIdx.
}
```

I think I'll give this model a try once we remove `Canceled`.

**Comment by matklad** [comment]
Chatted a bit with niko about monotype id vs strongly-typed id:

nikomatsakisToday at 21:20
I have often asked myself this question
one thing i've observed from rustc is that the EntityId thing has often allowed a lot of distinct sorts of things to go through one path in the code
otoh it feels like for all the usual reasons stronger types would be handy
in Lark, we pursued a semi-hybrid approach, that I would kind of like to do more of
wherein we have distinct id types but also an enum like EntityId that can be used to write generic code
I guess one could use traits too
anyway tl;dr I'm not sure but I think it's an interesting question

matkladToday at 21:24
So, enum DefId { Fn(FnId), Struct(StructId) }? I am leaning to this repr as well atm (currently, ra uses monotype, and I want to refactor).

The main argument for me is that different entities can have different interned location: module identified by parent module & name, struct field -- by parent struct & position, function -- by parent (module|impl|trait) & name

nikomatsakisToday at 21:25
more or less that, yes
this is not actually what Lark does for its entities
but we do have other kinds of ids that work this way
e.g., in the HIR, I have a lot of distinct sorts of ids (expression, path, etc) and then a MetaIndex
and I thought in that context it worked out well
so e.g. using that I can have one map like types: MetaIndex -> Ty
that stores all the "things with types" in the HIR
but also where desired draw distinctions
( and of course various Into<MetaIndex> impls and the like for ergonomics )
 
I guess we should try to refactor to `(Fn|Struct|Mod|Trait)Id, enum AnyId {}, impl From<((Fn|Struct|Mod|Trait)Id)> for AnyId`

**Comment by matklad** [comment]
Somewhat implemented. StructFIelds and EnumVariants use relative ids now
