### ISSUE TITLE
Call Hierarchy is broken

### ISSUE THREAD

**Issue by cbarrete** [rust-analyzer/rust-analyzer#5103]
Given the following file:
```rust
fn a() {
    b()
}

fn b() {}

fn main() {
    a()
}
```

`rust-analyzer` reports no incoming calls for `b` and two outgoing calls (one to `a` and one to `b`). For `a`, it also reports one outgoing call to `b` and no incoming calls.

**Comment by kjeremy** [comment]
I wrote a test and can verify that this works correctly at the `call_hierarchy` level at least... will continue investigating.

**Comment by cbarrete** [comment]
Thanks!
