### ISSUE TITLE
Simplify type_at_pos tests?

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#5107]
Today I was reminnded that there's a more intuitive way to write ty tests:

![image](https://user-images.githubusercontent.com/1711539/85945594-3adf1c80-b93f-11ea-8beb-2755cf24cea2.png)

So, I think it makes sense to refactor

```rust
#[test]
fn infer_adt_self() {
    let (db, pos) = TestDB::with_position(
        r#"
//- /main.rs
enum Nat { Succ(Self), Demo(Nat), Zero }

fn test() {
    let foo: Nat = Nat::Zero;
    if let Nat::Succ(x) = foo {
        x<|>
    }
}

"#,
    );
    assert_eq!("Nat", type_at_pos(&db, pos));
}
```

to just

```rust
#[test]
fn infer_adt_self() {
    check(
        r#"
enum Nat { Succ(Self), Demo(Nat), Zero }

fn test() {
    let foo: Nat = Nat::Zero;
    if let Nat::Succ(x) = foo {
        x
    } //^ Nat
}

"#);
}
```

@flodiebold wdyt?

**Comment by matklad** [comment]
Took me almost exactly four years to forget this :-) 

https://github.com/intellij-rust/intellij-rust/commit/4bfce6837cbc0bf04e1dc585acc64fd0d4d9493b

**Comment by flodiebold** [comment]
Seems good to me.

**Comment by flodiebold** [comment]
Done, right?
