### ISSUE TITLE
lint API

### ISSUE THREAD

**Issue by llogiq** [rust-analyzer/rust-analyzer#511]
Since this frontend is going to be used from IDEs, it might be a good idea to have a lint interface to allow quickly marking errors.

**Comment by matklad** [comment]
Currently only purely syntax based lints can be reliable. We have two API for them (unpolished):

* [diagnostics](https://github.com/rust-analyzer/rust-analyzer/blob/40686722ba0762c4af396da120331710edfeabe8/crates/ra_ide_api_light/src/diagnostics.rs) which are classical lints

* [assists](https://github.com/rust-analyzer/rust-analyzer/blob/40686722ba0762c4af396da120331710edfeabe8/crates/ra_ide_api_light/src/assists.rs) (Intentions, code actions): micro-refactorings which are activated depending on the current context.

**Comment by sirgl** [comment]
Are you planning to run linting for whole project? (for example, how it is done in Roslin)
Or just highlight errors for current file?

**Comment by matklad** [comment]
The API should be oriented towards analyzing a single syntax node, so that we can do either way.

I hope that, due to salsa being absolutely awesome, we will be able to pull whole project analysis. But it's important to handle single-file analysis as well, if only to have "low-battery" mode.

**Comment by matklad** [comment]
This is very far in the future, so, in order to avoid ballast issues, closing.
