### ISSUE TITLE
Hovering over a struct field should give info about it not the parent struct

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#512]
```rust
            struct Foo {
                field: i32
            }

            fn main() {
                let foo_test = Foo {
                    fie<|>ld: 1
                };
            }
```

Currently hovering over `field` gives us Foo but it would be nice if it gave us `i32`

**Comment by flodiebold** [comment]
Relatedly, goto def should go to the location of the field.

**Comment by kjeremy** [comment]
The behavior has changed and instead of going to the parent struct we get the `Failed to exactly resolve the symbol. This is probably because rust_analyzer does not yet support glob imports or traits.` message
