### ISSUE TITLE
inline hint improvement

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rust-analyzer/rust-analyzer#5123]
Our current project makes heavy use of `inline hint`, but because of vscode api's limitation, our `inline hint` is worse than intellij's `inline hint`. I have an optimization proposal for the decoration api here, if it is approved We could implement the same inline hint as intellij, but because I don't have enough community attention, I hope you could help me promote it, more than 20 upvotes would pass the proposal, I know I should't  open an issue for something like this, but I really want to make our plugin better!
here is the issue link: 
https://github.com/microsoft/vscode/issues/101085
Thanks again!

**Comment by lnicola** [comment]
> This feature request is now a candidate for our backlog. The community has 60 days to upvote the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it.

Urgh.

Stil, how does it differ from https://github.com/microsoft/vscode/issues/16221?

**Comment by IWANABETHATGUY** [comment]
> > This feature request is now a candidate for our backlog. The community has 60 days to upvote the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it.
> 
> Urgh.
> 
> Stil, how does it differ from [microsoft/vscode#16221](https://github.com/microsoft/vscode/issues/16221) which has been on backlog for three years?

because our `inline hint` implementation limited by vscode decoration api, it's worse than intellij , if your cursor move nearby the `inline hint`, it's reduce your edit experience, you could see my issue illustration, your cursor became very wide 。
and also that issue has been closed , and my issue give a more clear feature proposal

**Comment by lnicola** [comment]
> cursor around hints

Yeah, that's very annoying. Still, https://github.com/microsoft/vscode/issues/16221 is a request for the same feature and is still open (just locked, not closed).

**Comment by IWANABETHATGUY** [comment]
locked because the disscussion under that issue just said that they want the feature like intellij, but did't give the feature discuription, this what my feature proposal did.

**Comment by matklad** [comment]
closing in favor of the issue in the vscode repo.

**Comment by jrieken** [comment]
@matklad fyi - we have an initial proposal for inline hints and I would love to get some feedback from you folks. 

https://github.com/microsoft/vscode/blob/971190e4d0ff4878f1bf5e09501bb7dcf1c55afc/src/vs/vscode.proposed.d.ts#L1948-L2023

**Comment by jrieken** [comment]
e.g the snippet below gives you this

<img width="657" alt="Screenshot 2021-01-19 at 17 18 30" src="https://user-images.githubusercontent.com/1794099/105061964-60b64500-5a7a-11eb-9fe9-7b51549b86a3.png">


```js
    vscode.languages.registerInlineHintsProvider('fooLang', new class implements vscode.InlineHintsProvider {
        // onDidChangeInlineHints?: vscode.Event<void> | undefined;
        provideInlineHints(doc: vscode.TextDocument, range: vscode.Range, _token: vscode.CancellationToken) {
            const result: vscode.InlineHint[] = [];

            let end = doc.offsetAt(range.end);
            let pos = doc.offsetAt(range.start);
            let text = doc.getText();
            while (pos < end) {
                const idx = text.indexOf('bar', pos)
                if (idx < 0) {
                    break;
                }
                pos = idx + 4;
                const start = doc.positionAt(idx);
                result.push(new vscode.InlineHint('foo', new vscode.Range(start, start), 'FOObar Inline Hint Hover!'))
            }
            return result;
        }
    })
```

**Comment by SomeoneToIgnore** [comment]
@jrieken amazing, thanks for bringing this up!

I'm will go through the proposal closer to midnight today, I have a few ideas like styling and inlay hint kinds that seem to be absent in the proposal but appreciated by our users.

**Comment by matklad** [comment]
Took a quick look (but `@SomeoneToIgnore` is the relevant expert here):

* semantics of whitespaceBefor / whitespaceAfter is unclear, it needs better docs. How does it compare with having trailing/leading ws in the `text` itself?
* I am somewhat hesitant about `description`. For a hint like `: Foo<Bar>`, we ideally want different tooltips for `Foo` and `Bar` parts.
* We also want ctrl+click to go to definition of `Foo` and `Bar` (but this can easily be added later)
* On the LSP layer, we definitely need kinds, to allow, eg, sending *only* typehints or only parameter hints. But this isn't necessary needed in the editor API

**Comment by SomeoneToIgnore** [comment]
Well, turns out @matklad nailed the core of it, I've elaborated on those more and added some examples.
Let's move the discussion to the currently open issue related to the upstreaming, I've added a comment there: https://github.com/rust-analyzer/rust-analyzer/issues/2797#issuecomment-763153354
