### ISSUE TITLE
Crashes every time in a specific project (VSCode)

### ISSUE THREAD

**Issue by Dzejkop** [rust-analyzer/rust-analyzer#5125]
Every single time rust-analyzer starts for this project it displays the notification
```
The Rust Analyzer Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

and in the logs there appear a bunch of entries like this one:
```
thread 'main' panicked at 'expected absolute path, got ', crates/paths/src/lib.rs:63:36
stack backtrace:
   0: <unknown>
   1: core::fmt::write
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: <unknown>
   9: paths::AbsPathBuf::assert
  10: ra_project_model::cargo_workspace::CargoWorkspace::from_cargo_metadata
  11: ra_project_model::ProjectWorkspace::load
  12: <unknown>
  13: <unknown>
  14: rust_analyzer::main_loop::main_loop
  15: <unknown>
  16: <unknown>
  17: std::rt::lang_start_internal
  18: <unknown>
  19: __libc_start_main
  20: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 4:56:35 PM] Connection to server got closed. Server will not be restarted.
```

Funny enough thisonly seems to affect one specific project.

**Comment by lnicola** [comment]
Do you have any path dependencies in `Cargo.toml`?

**Comment by Dzejkop** [comment]
Yes

**Comment by lnicola** [comment]
Crashes around https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_project_model/src/cargo_workspace.rs#L248 with the assertion that the workspace has an absolute path.

**Comment by matklad** [comment]
Would be useful to get output of `cargo metadata` command

**Comment by Dzejkop** [comment]
I can't really give you the `cargo metadata` there's some work related stuff there :frowning: 

Any specific entries I could provide?

**Comment by lnicola** [comment]
`workspace_root` would be interesting. It's at the end.

**Comment by Dzejkop** [comment]
```
    "target_directory": "/home/user_name/Projects/abcd3/abcd3/target",
    "version": 1,
    "workspace_root": "/home/user_name/Projects/abcd3/abcd3"
}
```

**Comment by matklad** [comment]
Hm, not sure what’s going on here.... Do you have out_dir or proc macro support enabled in the settings?

**Comment by Dzejkop** [comment]
Ok, I fiddled with user settings I had this entry for some reason

```
"rust-analyzer.cargo.loadOutDirsFromCheck": true,
```

after removing, everything works fine

**Comment by matklad** [comment]
@Dzejkop could you run `cargo check --message-format=json` and check the value of `out_dir` from "build script executed" messages? It seems like there might be some bug in cargo?

**Comment by matklad** [comment]
Ah, I guess, you might be using rust older than 1.41,and that causes cargo metadata to use default path here.

**Comment by Dzejkop** [comment]
Yup, I'm using Rust 1.40, thanks for looking into this
