### ISSUE TITLE
`Remove dbg!` assist removes more text than it should.

### ISSUE THREAD

**Issue by et342** [rust-analyzer/rust-analyzer#5129]
Applied to a code like `dbg!(a + b).foo()`, turns it into `a + b.foo()`.

**Comment by flodiebold** [comment]
Also, I think I've seen it remove comments preceding the dbg.

**Comment by matklad** [comment]
relevant code&tests: https://github.com/rust-analyzer/rust-analyzer/blob/33ebfa8dcc66f3b3be7da48be48257802f251088/crates/ra_assists/src/handlers/remove_dbg.rs

**Comment by petr-tik** [comment]
If no one has started working on this - I would like to take it. 

Can someone please assign the issue to me?

**Comment by petr-tik** [comment]
> Also, I think I've seen it remove comments preceding the dbg.

I have tried putting a comment line above the dbg! and after on the same line and I cannot reproduce this. I found another bug though. 

If you have one, please share a repro.
