### ISSUE TITLE
incorrect tracking of identifiers in rainbow highlighting

### ISSUE THREAD

**Issue by Licenser** [rust-analyzer/rust-analyzer#5140]
![image](https://user-images.githubusercontent.com/119093/86131167-964b0f00-bae5-11ea-8708-b251d3d87ac8.png)

Looking at `event` in the code above the mention in line 132 is being mistaken as the event introduced in 131 while it is the event from line 122.

Expected:

event#1: 122, 132
event#2: 131, 138, 140

Actual:
event#1: 122
event#2: 131,  132, 138, 140

A synthetic example:
![image](https://user-images.githubusercontent.com/119093/86131702-43258c00-bae6-11ea-8392-33358270082d.png)

```
fn main() {
    let number = 1;
    let number = number + 1;
    let number = number + 1;
    let number = number + 1;
    let number = number + 1;
    let number = number + 1;
    println!("{}", number);
}
```

**Comment by Licenser** [comment]
This is what I would expect it to look like (with naming variables differently to enforce color change).

![image](https://user-images.githubusercontent.com/119093/86131966-98619d80-bae6-11ea-87e4-d4756e275693.png)

Side note: changing this in the file in VSCode didn't update the colors until I reloaded the window but I think that's a separate issue.

**Comment by bjorn3** [comment]
Which version of rust-analyzer are you using? As far as I know rainbow highlighting has been removed months ago.

**Comment by lnicola** [comment]
I think it's still available for HTML highlighting.

**Comment by Licenser** [comment]
Ohh that's a good point bjorn :joy: I had a super old one 202dev or something installed 🤦
