### ISSUE TITLE
Implement trait members assist only works on whole block

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#5144]
```rust
struct S;

impl Iterator for S // need to add {}
```

**Comment by matklad** [comment]
code&tests here: https://github.com/rust-analyzer/rust-analyzer/blob/33ebfa8dcc66f3b3be7da48be48257802f251088/crates/ra_assists/src/handlers/add_missing_impl_members.rs

**Comment by M-J-Hooper** [comment]
Was giving this one a quick go but I'm not getting anywhere... without braces there is not even an `Impl` in the tree. Not really sure how to get to anything useful from just the `AssistContext`. Advice on how to proceed appreciated!

**Comment by lnicola** [comment]
> without braces there is not even an Impl in the tree

Are you sure? I seem to get one:

```
SOURCE_FILE@0..49
  STRUCT@0..9
    STRUCT_KW@0..6 "struct"
    WHITESPACE@6..7 " "
    NAME@7..8
      IDENT@7..8 "S"
    SEMICOLON@8..9 ";"
  WHITESPACE@9..11 "\n\n"
  IMPL@11..30
    IMPL_KW@11..15 "impl"
    WHITESPACE@15..16 " "
    PATH_TYPE@16..24
      PATH@16..24
        PATH_SEGMENT@16..24
          NAME_REF@16..24
            IDENT@16..24 "Iterator"
    WHITESPACE@24..25 " "
    FOR_KW@25..28 "for"
    WHITESPACE@28..29 " "
    PATH_TYPE@29..30
      PATH@29..30
        PATH_SEGMENT@29..30
          NAME_REF@29..30
            IDENT@29..30 "S"
  WHITESPACE@30..31 " "
  COMMENT@31..48 "// need to add {}"
  WHITESPACE@48..49 "\n"
```

What's missing is the `ASSOC_ITEM_LIST`.

**Comment by M-J-Hooper** [comment]
@lnicola Do you mind posting the code you used to get that tree out of interest? I will give it another go now, might be missing something obvious 😄

**Comment by lnicola** [comment]
@M-J-Hooper of you're using Code, there's a Show syntax tree command.

**Comment by M-J-Hooper** [comment]
@lnicola turns out there is an `Impl` but not a `AssocItemList` on which this assist was depending. Take a look at the PR. Thanks for your help!

**Comment by M-J-Hooper** [comment]
@matklad @lnicola Something that I did not really get a grasp on (so just kind of ignored it) is the use of `SemanticScope`s and `AstTransform` in this assist. Do you mind giving a quick explanation of what's going on there?

**Comment by matklad** [comment]
Filed https://github.com/rust-analyzer/rust-analyzer/pull/6048
