### ISSUE TITLE
Clear existing progress notifications when restarting the language server

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#5165]
If you restart the language server while a progress notification is being shown, that progress notification will exist permanently.

**Comment by Veetaha** [comment]
In addition, when rust-analyzers fails to discover the workspace, the progress resource is not freed too, it shows `roots scanned: 0/0` indefinitely

**Comment by matklad** [comment]
>In addition, when rust-analyzers fails to discover the workspace, the progress resource is not freed too, it shows roots scanned: 0/0 indefinitely.

Fixed on master

>If you restart the language server while a progress notification is being shown, that progress notification will exist permanently.

Seems to be a bug in the client library? Ie, I expect that it should dispose all the resources during shutdown. I wonder why `lc.LanguageClient` is not disposable even...
