### ISSUE TITLE
Adding imports / other fixes not advertised as "quickfix"?

### ISSUE THREAD

**Issue by antifuchs** [rust-analyzer/rust-analyzer#5172]
I recently upgraded lsp-mode in emacs, and it appears there's a new setting, `lsp-ui-sideline-actions-kind-regex`, which defaults to showing only quickfix and refactor-type assists. There are several bug-removal assists that rust-analyzer offers that present as the `""` type, including adding missing imports. The lsp-mode issue&work-around for this is https://github.com/emacs-lsp/lsp-ui/issues/455

My intuition is that rust-analyzer is not sending the correct type for those assists & that they should be `quickfix`es; do you agree?

**Comment by bjorn3** [comment]
https://github.com/rust-analyzer/rust-analyzer/issues/5115#issuecomment-651035162

> The suggestion is marked as MaybeIncorrect: https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/method/suggest.rs#L870

**Comment by kjeremy** [comment]
We don't categorize all assists yet but it will be in soon: #5116

**Comment by kjeremy** [comment]
@antifuchs assists are now categorized.

**Comment by antifuchs** [comment]
Great news! I'll try this asap & report back (:

**Comment by matklad** [comment]
optimistically closing

**Comment by antifuchs** [comment]
Belated confirmation that the quick fixes I have tried all seem to be properly classified. Thanks!
