### ISSUE TITLE
bug: directory parsing

### ISSUE THREAD

**Issue by TomGoodacre** [rust-analyzer/rust-analyzer#5194]
Switched to rust-analyzer by changing "rust-client.engine" : "rust-analyzer" in vscode settings.

Navigated to Rust project.

Got the error message: "The Rust Analyzer server crashed 5 times in the last 3 minutes. The server will not be restarted."

Checked ra Logs. Log message: "'C:\Users\Tom' is not recognized as an internal or external command, operable program or batch file."

The full username is "Tom Goodacre" with a space. So a command in some script somewhere is having trouble with directory strings containing spaces.

Tried placing project in a directory without spaces. Same issue. So maybe a script looking at rustup home?

rustup show output:
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Tom Goodacre\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.46.0-nightly (f781babf8 2020-07-01)

rust-analyzer is the nightly version, in vscode setings.

If more information is required, instruct me and I shall provide it if I am able.

**Comment by bjorn3** [comment]
The "Rust" extension is at https://github.com/rust-lang/rls-vscode/, please file an issue there. You may want to switch to the "rust-analyzer" extension, which is developed specifically for rust-analyzer and supports all rust-analyzer features.

**Comment by TomGoodacre** [comment]
Ok, I switched to the "rust-analyzer" extension. Thank you for your prompt reply!
