### ISSUE TITLE
Still getting a popup before each nightly update

### ISSUE THREAD

**Issue by Geobert** [rust-analyzer/rust-analyzer#5196]
Hi,

I have `"rust-analyzer.updates.askBeforeDownload": false` in my settings, but I still have a popup asking me to update every nightly version.

I think the setting only works for downloading the lang server bin, but maybe it shoult also turn off this one? Or it is bad practice because a reload is needed?

**Comment by Veetaha** [comment]
Yup, the nightly update requires the reload of the window, either way, we should ask before doing it otherwise it may lead to sudden unwanted side effects.

**Comment by Geobert** [comment]
Understood :)
