### ISSUE TITLE
Bad hints and pop-up for `for` loops

### ISSUE THREAD

**Issue by mcarton** [rust-analyzer/rust-analyzer#5206]
It looks like the `for` loop could get some love:

Here is an example with VS Code:

1. First, a useless hint appears:
   ![image](https://user-images.githubusercontent.com/3751788/86477458-c80fe000-bd48-11ea-8651-f514664bec5f.png)

2. When I type space, my cursor is teleported:
   ![image](https://user-images.githubusercontent.com/3751788/86477468-cb0ad080-bd48-11ea-9384-f53b28615d63.png)

3. After I type `i`, it's teleported back, and the hint is replaced by an equally useless pop-up:
   ![image](https://user-images.githubusercontent.com/3751788/86477469-ccd49400-bd48-11ea-9672-28aa117bb035.png)

4. After I type `n`, the hint is back teleporting the cursor again, and the pop-up is slightly different:
![image](https://user-images.githubusercontent.com/3751788/86477471-ce05c100-bd48-11ea-8cf5-ebfd82c6924f.png)

5. Another space and the pop-up disappears:
   ![image](https://user-images.githubusercontent.com/3751788/86477475-cfcf8480-bd48-11ea-94b0-c1e653eea0d7.png)

The constant back and forth of the cursor and the dialogs is rather annoying. Neither the hint nor the dialog seem very useful in this case.

(I couldn't find a similar issue, GitHub's search isn't really good with common keywords such as "for" and "hint". Sorry if this was already reported.)

**Comment by matklad** [comment]
The relevant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/6c1546c3a495785cf293dbbfb7f65ea124602528/editors/code/src/inlay_hints.ts

We probably should just disable the hints in these common cases (or, more generally, check that the parent expressions doesn't contiain sytnax errros shallowly).
