### ISSUE TITLE
handle `extern crate` in name resolution

### ISSUE THREAD

**Issue by killercup** [rust-analyzer/rust-analyzer#523]
Currently, `std::sync::Arc` cannot be resolved.

In <https://github.com/rust-analyzer/rust-analyzer/pull/522#issuecomment-453826759>, @flodiebold speculates:

> std::sync gets properly resolved, but it reexports Arc from alloc_crate, which is an extern crate rename: extern crate alloc as alloc_crate. I guess that's the problem.

- - -

Here's a simple test case:

```diff
diff --git a/crates/ra_ide_api/src/hover.rs b/crates/ra_ide_api/src/hover.rs
index 2968b807..2ca1d6d9 100644
--- a/crates/ra_ide_api/src/hover.rs
+++ b/crates/ra_ide_api/src/hover.rs
@@ -230,6 +230,20 @@ mod tests {
         assert_eq!("u32", &type_name);
     }
 
+    #[test]
+    fn test_type_of_arc() {
+        let (analysis, position) = single_file_with_position(
+            r"
+            use std::sync::A<|>rc;
+
+            fn main() {}
+            ",
+        );
+
+        let hover = analysis.hover(position).unwrap().unwrap();
+        assert!(!hover.info.contains("Failed to exactly resolve"));
+    }
+
     // FIXME: improve type_of to make this work
     #[test]
     fn test_type_of_for_expr_1() {
```

**Comment by flodiebold** [comment]
Hm, you're right, it just works for `extern crate` apparently. But `extern crate foo as bar` doesn't just rename the crate in the extern prelude, because 1. it only has an effect if it's in the crate root or the current module, and 2. the original name is still usable. Back to reading rustc, I guess...

**Comment by flodiebold** [comment]
I think `extern crate`s in the crate root are special-cased to insert entries in the extern prelude, if I read this correctly:
https://github.com/rust-lang/rust/blob/master/src/librustc_resolve/build_reduced_graph.rs#L390-L408

**Comment by bjorn3** [comment]
Yup, https://github.com/rust-lang/rust/pull/54658

**Comment by flodiebold** [comment]
Though `std` isn't actually a case of this, since it's still edition 2015, but I guess if we implemented it that way we could still avoid implementing 2015 name resolution...
