### ISSUE TITLE
Enums variants with struct-style values do not register when constructed with Self.

### ISSUE THREAD

**Issue by geeklint** [rust-analyzer/rust-analyzer#5230]
The test case below generates the following warning:
``variant is never constructed: `B`  note: `#[warn(dead_code)]` on by default [dead_code]``

The struct-style variant `Test::B` is constructed in the function `make_b` using `Self::B`
The warning does not appear if the variant is enum style (`B(u32)`) or if `Test::B` is used to construct it instead of `Self::B`.

Tested using rust-analyzer via YouCompleteMe in vim (version: rust-analyzer ca31b1d)

```rust
enum Test {
    A,
    B { value: u32 },
}

impl Test {
    fn make_b(&mut self) {
        *self = Self::B { value: 10 };
    }
}

pub struct Opaque(Test);

impl Opaque {
    pub fn new() -> Self {
        Self(Test::A)
    }
    pub fn make_b(&mut self) {
        self.0.make_b();
    }
}
```

**Comment by flodiebold** [comment]
That's a rustc error, not a rust-analyzer error. Also, I can't reproduce it. Is it possible you were just seeing an outdated error?

**Comment by geeklint** [comment]
I don't see it when I `cargo check/build/clippy`, which is why I believed it was related to rust-analyzer.  I just tried re-downloading releases/latest/download/rust-analyzer-linux to make sure, and I still see it. I'll try building rust-analyzer from master.

**Comment by flodiebold** [comment]
Do you see this error in a fresh project with no other code? You could also try running `cargo check --all-targets` in your project, which is what rust-analyzer runs by default.

**Comment by geeklint** [comment]
Ah, looks like it was actually YCM not respecting rust-analyzer over RLS.

Perhaps it would be a good idea to copy this line from lsp-examples:
> If you previously built YCM with `--rust-completer`, then you need to remove the directory `</path/to/>/YouCompleteMe/third_party/ycmd/third_party/rls`.

To the [YCM section in the manual](https://rust-analyzer.github.io/manual.html#youcompleteme)?  It's right there in the linked page, but I must have missed it somehow.

Still curious why RLS had that behavior when `cargo check` did not.
