### ISSUE TITLE
`ignore` attribute autocompletion is incorrect

### ISSUE THREAD

**Issue by alvinhochun** [rust-analyzer/rust-analyzer#5232]
The [`ignore` attribute](https://doc.rust-lang.org/reference/attributes/testing.html#the-ignore-attribute) is used for marking ignored test so it should autocomplete as `ignore = "reason"`, but instead rust-analyzer gives the completion `ignore(lint)`.

**Comment by matklad** [comment]
Code&Tests: https://github.com/rust-analyzer/rust-analyzer/blob/41feb816c98894d48df97193eb085738e405a3c2/crates/ra_ide/src/completion/complete_attribute.rs#L88

**Comment by darkmtr** [comment]
can i give this a try?

**Comment by alvinhochun** [comment]
> 
> 
> can i give this a try?

As far as I see it's just two lines of changes so I suppose you could just make a pull request quickly without asking.
