### ISSUE TITLE
Import suggestions not provided for code within examples folder

### ISSUE THREAD

**Issue by mbartelsm** [rust-analyzer/rust-analyzer#5237]
As the title states, rust-analyzer fails to provide import suggestions when working in a code example.

To reproduce:

* Create a new project
* Set up some dependency and some example in the cargo manifest
* Create the example file
* Use a feature of the dependency within the example without importing it
* No suggestions will be made

**Comment by lnicola** [comment]
Does it work after you restart the server?

**Comment by mbartelsm** [comment]
It didn't, but reinstalling the extension worked.
