### ISSUE TITLE
Dependency on crate in subdirectory breaking workspace handling

### ISSUE THREAD

**Issue by vincentisambart** [rust-analyzer/rust-analyzer#5246]
When my crate depends to a subcrate in a subdirectory, [Workspace Symbol](https://rust-analyzer.github.io/manual.html#workspace-symbol) or going to a type definition in an other file stops working properly.

To reproduce:

```command
$ cargo new --lib myproblem
$ cd myproblem
$ cargo new --lib mysubcrate
```

Add the following declaration to src/lib.rs:
```rust
pub struct Foo;
```

In the main Cargo.toml's `[dependencies]` section, add:
```toml
mysubcrate = { path = "mysubcrate" }
```

Then open the current directory in VSCode and wait for rust-analyzer to load. Opening the Workspace Symbols list doesn't show `Foo`. If you remove that dependency in Cargo.toml, it seems to work properly though.

**Comment by extrawurst** [comment]
I am seeing the same issue, interestingly the symbols of the subcrate popup in there though
