### ISSUE TITLE
implement postfix completion

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#525]
```
foo > bar.if

=>

if foo > bar {
   cursor
}
```

```
res.match 

=>

match res {
    _ => (),
}
```

```
work.is_empty().not

=>

!work.is_empty().while

=>

while !work.is_empty() {
}
```

This I think should be implemented as a new module here: https://github.com/rust-analyzer/rust-analyzer/blob/c46e0300e6cebf78c78c28ca91e45b57e4e40954/crates/ra_ide_api/src/completion.rs

**Comment by gfreezy** [comment]
how to remove the old text?

**Comment by matklad** [comment]
@gfreezy that needs some investigation, but I think [specification](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion) allows that.

Specifically, I think we can use `textEdit` to replace the `.if` with `if {\n    $0}`, and `additionalTextEdits` to insert the `if` before the expression.
