### ISSUE TITLE
rust-analyzer doesn't cooperate with single file cargo-script scripts

### ISSUE THREAD

**Issue by grandopener** [rust-analyzer/rust-analyzer#5251]
https://github.com/DanielKeep/cargo-script provides a neat system for self-contained Rust "scripts," potentially with dependencies, defined in single files.

Currently working on such a file in VS Code spams errors with the message "Rust file outside current workspace is not supported yet."  I would guess this means the issue is known and possibly even planned, but I didn't see an issue for it.  (Apologies if I missed one.)

It would be really awesome if rust-analyzer could handle this use case.

**Comment by matklad** [comment]
>Currently working on such a file in VS Code spams errors with the message "Rust file outside current workspace is not supported yet."

It seems like you are using an outdated version of rust-analyzer, we removed this error quite some time ago.

**Comment by grandopener** [comment]
Oops!  I had kept the extension up to date but I did indeed have a separately installed version of rust-analyzer from ages ago that I had forgotten about.  Sorry for the false alarm!
