### ISSUE TITLE
Rust-analyzer not works when switching workspaces in Vscode

### ISSUE THREAD

**Issue by Edu4rdSHL** [rust-analyzer/rust-analyzer#5254]
I have two different folders from different projects added to the workspace, when I works on the first one added RA works without problems but switching to the another project it just stop reporting problems. See #4894 for the actual behavior of RA when switching project folder.

In short, rust-analyzer doesn't show errors regarding to nonexistent or wrong typed variables, bad number of function parameters and more.

**Comment by matklad** [comment]
Relevant fixme: https://github.com/rust-analyzer/rust-analyzer/blob/6c1546c3a495785cf293dbbfb7f65ea124602528/crates/rust-analyzer/src/reload.rs#L234-L248

**Comment by Edu4rdSHL** [comment]
Thanks, as workaround you can change the order of the folders and put in first place the one where you want to work, then restart vscode.

**Comment by jonas-schievink** [comment]
This is now fixed, we spawn one flycheck instance per client workspace
