### ISSUE TITLE
Add an option to disable the documentation popup

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#5260]
Editor: VSCodium

I wasn't able to find a way to stop the documentation popup from appearing while typing. It can be stopped from appearing on mouse hover by setting `"editor.hover.enabled"`, optionally scoped to just `"[rust]"` files, but no matter what I've tried, I couldn't stop it from appearing while typing. The most annoying part of this is that when writing a macro invocation and dismissing the popup after writing the opening parenthesis, it re-appears after every typed comma (even within string literals!).

In my case, I'm writing lots of `sqlx::query_as!` invocations. `query_as!` has more than enough docs to expand the popup to its maximum size, which makes it overlay lots of surrounding things in the code that I often want to see.

**Comment by matklad** [comment]
Perhaps you are looking for `callInfo`?

https://github.com/matklad/config/blob/e34228fad6dacf51959ffb6fb6da63d75cb31759/home/.config/Code/User/settings.json#L118

**Comment by jplatte** [comment]
Why did I not find this before ._.

Thanks so much for the extremely fast response! For some reason, a tiny empty popup remains after setting `"rust-analyzer.callInfo.full": false`, but this largely solves my issue, without fully removing the (otherwise very useful) popup!

**Comment by matklad** [comment]
>For some reason, a tiny empty popup remains

That's strage, a minimal reproducing example would be helpful!

**Comment by jplatte** [comment]
@matklad I can reproduce this by just opening a fresh `cargo init`ed project with `"rust-analyzer.callInfo.full": false` by adding a comma before the closing parenthesis in `println!("Hello, World!");`, or by typing `main(` inside main.

![Screenshot_2020-07-08_114151](https://user-images.githubusercontent.com/951129/86904044-6e286500-c110-11ea-9b46-2586edeeb1c3.png)

**Comment by jplatte** [comment]
Just noticed my version of RA is a bit outdated, will try to fix..

**Comment by jplatte** [comment]
Okay, so I can still reproduce the empty popup with rust-analyzer 2020-07-06 (8b0983e). Will open a separate issue about publishing the extension on Open VSX.

**Comment by matklad** [comment]
>I see there already was one.

Yeah... but it seems more popular than I've expected. I wonder if some form of automatic sync can be setup betwen the two repositories -- I am still not thrilled about managing two sets of access tokens...

**Comment by matklad** [comment]
I can't reproduce the issue locally (which is strange), but I think the fix would be to say `if consice && has_zero_params { return None}` somewhere around here: https://github.com/rust-analyzer/rust-analyzer/blob/41feb816c98894d48df97193eb085738e405a3c2/crates/rust-analyzer/src/handlers.rs#L560

The problem is that the data types for expressing call info are a bit of a mess right now, so it wont be trivial to fix.

**Comment by jplatte** [comment]
> > I see there already was one.
> 
> Yeah... but it seems more popular than I've expected. I wonder if some form of automatic sync can be setup betwen the two repositories -- I am still not thrilled about managing two sets of access tokens...

AFAIK Open VSX has some form of automation for this – their Registry is pretty filled with packages "Packaged by Open VSX". AFAICT, the reason rust-analyzer isn't published on there by them is https://github.com/open-vsx/publish-extensions/issues/41. You may not have to manage publishing yourself at all if that can be fixed.

> The problem is that the data types for expressing call info are a bit of a mess right now, so it wont be trivial to fix.

Should I open a separate issue about this then?
