### ISSUE TITLE
Migrating a client from rls to rust-analyzer

### ISSUE THREAD

**Issue by bstaletic** [rust-analyzer/rust-analyzer#5261]
Hi. I saw today that rust-analyzer is available through rustup, but under the component name "rust-analyzer-preview". The good news is that it took me about 3 minutes to migrate YCM to RA, at least locally. Now I have some, hopefully simple, questions.

1. Should I be concerned about the "-preview" part in the component name?
2. How to get verbose logging from RA? Right now YCM [uses these env variables](https://github.com/ycm-core/ycmd/blob/master/ycmd/completers/rust/rust_completer.py#L97-L98) to make rls as verbose as possible, but the same did nothing for RA.
3. Does RA respect `RUSTC` environment variable to know which `rustc` executable should be used?

Other than these questions I have, RA worked perfectly after just pointing YCM at a different executable.

**Comment by matklad** [comment]
The general note is that, while rust-analyzer is available via rustup, it's still very much provisional. So, expect things to be rough around the ages for some time still. 

>Should I be concerned about the "-preview" part in the component name?

Not really -- we'll be in `-preview` state for a long time 

>How to get verbose logging from RA?

You can set `RA_LOG=rust_analyzer=trace` env variable. We generally don't enable logs by default, so there might be cases where we accidently log gigabytes of data or something like that (this would definitelly happen if you use blanket `RA_LOG=trace`).

> Does RA respect RUSTC environment variable to know which rustc executable should be used?

Yes: https://github.com/rust-analyzer/rust-analyzer/blob/a622a8e109e0f41f1b7cf869acb955eab8c95b43/crates/ra_toolchain/src/lib.rs#L28-L35

**Comment by bstaletic** [comment]
Thanks for answering.

> You can set RA_LOG=rust_analyzer=trace env variable. We generally don't enable logs by default

YCM does enable some logging by default, but it's useful to tell users "flip this one switch and post all logs available" when debugging.
