### ISSUE TITLE
Autocomplete for deref doesn't work for structs defined inside a function

### ISSUE THREAD

**Issue by cbrewster** [rust-analyzer/rust-analyzer#5269]
Example:
```rust
use std::rc::Rc;

fn main() {
    struct Foo {
        a: i32,
        b: String,
    }

    let foo = Rc::new(Foo {
        a: 1,
        b: "Hello!".into(),
    });

    foo.<|>
}
```
Expected:
The autocomplete at `foo.<|>` should show options for fields `a` and `b`.

Actual:
The autocomplete options do not include any of the fields from `Foo`.

**Comment by flodiebold** [comment]
Duplicate of #1559, I don't think this has anything to do with the deref.
