### ISSUE TITLE
Ability to hide less relevant (ie. "ready") information from the status message

### ISSUE THREAD

**Issue by Rantanen** [rust-analyzer/rust-analyzer#5275]
Once the rust-analyzer has loaded, it keeps reporting "rust-analyzer ready" as part of the status message. Reports for rust-analyzer loading/reload needed/etc. are just fine, as those should be somewhat temporary states, but seeing "rust-analyzer ready" constantly in the status bar is somewhat useless.

This becomes an issue when the status bar is needed for displaying other information - further exacerbated by editors (such as Vim) that have individual status bars for different split windows:
![image](https://user-images.githubusercontent.com/385385/86984882-74faba80-c198-11ea-9087-5491203e35bc.png)

(At least I'm under the impression the "rust-analyzer ready" message comes from rust-analyzer itself. I tried figuring out where rust-analyzer stops and coc-rust-analyzer starts, but it wasn't entirely clear to me.)

**Comment by fannheyward** [comment]
`loading/ready` status is from RA, and `rust-analyzer ready` is displayed by `coc-rust-analyzer`.

In RA VSCode extension, this status message be displayed with an icon + `rust-analyzer` text. In vim, just display text message on status line.

It maybe a noise, do you have any suggestions for the status message?

**Comment by fannheyward** [comment]
Can you close this issue here and open a new issue https://github.com/fannheyward/coc-rust-analyzer/issues?
