### ISSUE TITLE
Unable to infer type for union fields

### ISSUE THREAD

**Issue by nicomem** [rust-analyzer/rust-analyzer#5277]
rust-analyser is unable to infer type for union fields

```rust
union MyUnion {
    foo: u32,
    bar: f32,
}

unsafe fn baz(u: MyUnion) {
    let inner = u.foo;
    // inner is {unknown}
    // expected: u32
}
```

**Comment by flodiebold** [comment]
The relevant code is here:
https://github.com/rust-analyzer/rust-analyzer/blob/5a195001d79995a6336988e18a2b78052917a02e/crates/ra_hir_ty/src/infer/expr.rs#L408-L409
It should be pretty straightforward to implement -- basically the same as for structs (in fact, it would be nice to handle structs and unions with mostly the same code there). A test should be added [here](https://github.com/rust-analyzer/rust-analyzer/blob/5a195001d79995a6336988e18a2b78052917a02e/crates/ra_hir_ty/src/tests/simple.rs#L267).
