### ISSUE TITLE
"introduce match" action

### ISSUE THREAD

**Issue by killercup** [rust-analyzer/rust-analyzer#528]
Similar to "introduce variable", an "introduce match" action would replace the `x` under cursor here

```rust
fn maybe() -> Option<i32> { Some(42) }

fn foo() {
    let x = maybe();
    x<|>
}
```

with this:

```rust
    match x {
        _ => (),
    }
```

Assuming knowledge of the type of `x`, we could later on add special cases, e.g. for booleans (use `if`) or enums with two variants (use `if let`).

This is similar to #525 but maybe a bit more user-discoverable ;) Feel free to close this issue if you feel like #525 is a better approach.

**Comment by matklad** [comment]
Good idea, I think we need both this and #525 !

**Comment by flodiebold** [comment]
Also, with a code action the user can select the expression to match on -- with a completion we have to guess it.

**Comment by zacps** [comment]
Similarly it'd be nice to be able to convert an `if let` to a `match`.

**Comment by matklad** [comment]
@zacps this already works for iflets with else: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_assists/src/handlers/replace_if_let_with_match.rs

Should be straightforward to extend to plain iflets

**Comment by matklad** [comment]
Hm, now that I think about it, just using prefix/postfix completions for this seems to be a better idea in terms of cost/benefit.
