### ISSUE TITLE
No Completion after awating a future

### ISSUE THREAD

**Issue by xsoheilalizadeh** [rust-analyzer/rust-analyzer#5287]
Issue Type: <b>Bug</b>

There is no completion when after `.await` 

```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let urls = [
        "http://google.com",
        "http://bing.com",
        "http://twitter.com",
        "http://stackoverflow.com/",
    ];

    let requests = urls.iter().map(|url| get_redirect_url(url).boxed());

    let result = futures::future::select_ok(requests).await.unwrap(); // .await.no_compeltion

    Ok(())
}

async fn get_redirect_url(gateway_uri: &'static str) -> Result<&'static str, ()> {
    let url = &hyper::http::Uri::from_static(gateway_uri);

    let client = hyper::Client::new();

    println!("GET {}", url);

    let response = client.get(url.clone()).await.unwrap();

    println!("< {} - {}", url, response.status());

    Ok(gateway_uri)
}
```

Extension version: 0.2.232
VS Code version: Code - Insiders 1.47.0-insider (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-08T10:52:52.439Z)
OS version: Windows_NT x64 10.0.19628

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.37GB free)|
|Process Argv|--folder-uri file:///c%3A/Code/hub-rs|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by SomeoneToIgnore** [comment]
This is most probably caused by this issue:

https://github.com/rust-analyzer/rust-analyzer/issues/1791

With no types known, no proper completion can be provided.

**Comment by lnicola** [comment]
Another test case from #5435:

```rust
use async_std::fs::OpenOptions;
use crossbeam_channel::{bounded, Receiver, Sender};


async fn access_log_process<T:AsRef<Path>>(path:T, recv: Receiver<String>) -> io::Result<()> {
    let mut file = OpenOptions::new()
        .create(true)
        .append(true)
        .open(path)
        .await.expect("open failed");

    let interval = 5;
    loop {
        if let Ok(s) = recv.try_recv() {
            file.write(s.as_bytes()).await. // complete not working. as std::fs::File::write
        } else {
            task::sleep(Duration::from_secs(interval)).await;
        }
    }
}
```

**Comment by flodiebold** [comment]
The example from 5435 works for me (once I import all necessary traits). In the original example, the `<SelectOk<Pin<Box<dyn Future<Output = Result<&str, ()>> + Send>>> as Future>::Output` still doesn't get normalized for some reason.

**Comment by lnicola** [comment]
This works now:

![image](https://user-images.githubusercontent.com/308347/113908183-ec6c8180-97de-11eb-94e5-c4af734aca8c.png)

![image](https://user-images.githubusercontent.com/308347/113908243-fb533400-97de-11eb-86c2-e0c94e2fedc8.png)

And the return type in the second example is also normalized:

![image](https://user-images.githubusercontent.com/308347/113908736-8c2a0f80-97df-11eb-9a86-959023a4c852.png)
