### ISSUE TITLE
Assertion failed: We don't expect to receive commands in CodeActions

### ISSUE THREAD

**Issue by rijenkii** [rust-analyzer/rust-analyzer#5308]
Extension version: `0.3.237-nightly`
/usr/bin/rust-analyzer --version: `rust-analyzer 90f8378`

While editing files, "Rust Analyzer Client" "output" tab pops up and the following error message gets printed:
```
ERROR [11/07/2020, 14:03:35]: Assertion failed: We don't expect to receive commands in CodeActions
```
Complete "output" tab contents: https://gist.github.com/rijenkii/93ee3194a1755074346a886241cf1616

**Comment by matklad** [comment]
I think you are using old version of rust-analyzer binary with a new version of typescript extension, as we indeed are not producing commands now. Filed https://github.com/rust-analyzer/rust-analyzer/pull/5309/files to be dead sure that we don't.

**Comment by rijenkii** [comment]
Oh, indeed, I have used externally installed rust-analyzer binary
After clearing the "rust-analyzer.serverPath", issue disappeared
Thanks for the hint!
