### ISSUE TITLE
Auto reload isn't working when Cargo.toml or Cargo.lock are changed outside of editor

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#5333]
When switching between `master` and `kjeremy:mark-fixes-as-preferred` things are not reloaded (it is enabled in the settings). There are changes to `Cargo.toml` and `Cargo.lock` so I would expect it to reload. The status bar does not change from "Ready".

**Comment by matklad** [comment]
Right, we probably should move the Cargo.toml stuff from `OnDidSave` to file-system watcher. Maybe we should just add `Cargo.toml` an `Cargo.lock` to the VFS, but I am hesitant to do that, admittedly for no real reason.

**Comment by crumblingstatue** [comment]
I'm not sure if this is the right issue for this, but rust-analyzer isn't picking up changes for Cargo.toml from cargo-edit either.
If you add a dependency with cargo-add, it won't be processed until you manually save Cargo.toml.

**Comment by crumblingstatue** [comment]
Another time when rust-analyzer doesn't pickup changes: `cargo update`
Fixing this would involve watching Cargo.lock for changes, I think.

**Comment by woody77** [comment]
I think this applies to `rust-project.json` as well.

**Comment by yohan-pg** [comment]
This is super annoying is there any way I can help getting this fixed?

**Comment by matklad** [comment]
Sending a PR would help! I think what we need here is to just treat cargo.tomls and locks exactly as .rs files. There are a bunch of places for that:

* https://github.com/rust-analyzer/rust-analyzer/blob/7d363755a27f3bc89a5c7f5d15c8664299436bb4/crates/vfs/src/loader.rs#L39
* https://github.com/rust-analyzer/rust-analyzer/blob/7d363755a27f3bc89a5c7f5d15c8664299436bb4/crates/rust-analyzer/src/reload.rs#L73
* https://github.com/rust-analyzer/rust-analyzer/blob/7d363755a27f3bc89a5c7f5d15c8664299436bb4/crates/rust-analyzer/src/main_loop.rs#L116

Maybe something else as well. 

Sadly, this is a bit of code where fast&robust&high assuarance automated tests are hard, so we only test manually.

**Comment by damccull** [comment]
This is also something I find inconvenient, but I'm not in a position where I can spend the time to fix it. If I get that way in the future, and this isn't done, I'll try to work up a PR. Until then, maybe someone else will be able to :)

**Comment by lnicola** [comment]
I put up a tentative fix in #9426, but I'm not sure it's correct.
