### ISSUE TITLE
Feature request: plugin for rust-analyzer

### ISSUE THREAD

**Issue by abdulla-tuychi** [rust-analyzer/rust-analyzer#5334]
I would like to add custom code visualyser.
Is there any way to add external plugin to rust-analyzer? Something like a handler on the server side and a command on client side.
Can this be achieved from external code without changing core rust-analyzer?
Is this possible right now, or will this feature(plugin system) be added? Are there any docs?
Thanks

**Comment by matklad** [comment]
There's no way extend the core of rust-analyzer. One day, we'll have WASM api probably, but this is very far in the future, and is explicit non-goal at *this* moment.

You can extend VS Code extension though, and, if the functionality you want can be built on top of existing LSP requests, than you should be able to do that. See https://github.com/rust-analyzer/rust-analyzer/issues/4902#issuecomment-646965402 and associated PR
