### ISSUE TITLE
inlay hints cannot be shown just after openning project, edit is necessary to trigger the generation

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#5349]
Inlay hints isn't shown directly, I always need to do some modifications to make it works, the first `fetchHints` is always empty array as you can see from the following screenshot:

https://user-images.githubusercontent.com/33961674/87353897-f5853680-c55d-11ea-9fa4-cc8edc5eb664.png

I tested coc-rust-analyzer & vscode, they both have this issue

I believe it's because the analysis hasn't finished? Because after adding a sleep(30) in `fetchHints`, it can be correctly rendered.

So the first `fetchHints` has been called too early and RA just returned empty hints:

https://user-images.githubusercontent.com/33961674/87353897-f5853680-c55d-11ea-9fa4-cc8edc5eb664.png

**Comment by GopherJ** [comment]
See also: https://github.com/fannheyward/coc-rust-analyzer/issues/317

**Comment by GopherJ** [comment]
If it's hard to detect when the analysis really finishes, maybe we can just return back an error? So that client can retry...

**Comment by Veetaha** [comment]
We can wait until workspace loaded progress end notification on the frontend, but in fact this indeed looks like a race condition in current impl such that it returns empty arrays from time to time.
@matklad do you think we can alleviate this race condition on the server side?

**Comment by matklad** [comment]
Yup, this is the same problem as with semantic tokens, pure pull model does not work here. I think I still believe that Dart's subscriptions are fundamentally better here than what LSP is trying to do:

https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#request_analysis.setSubscriptions
