### ISSUE TITLE
GoTo Definition for reference_definition succeeds but hover fails to find it

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#535]
Hovering on https://github.com/rust-analyzer/rust-analyzer/blob/a901cb4f342b0a784e716e29934999cc036dc835/crates/ra_ide_api/src/hover.rs#L20 says that it cannot resolve the symbol but go to definition brings us the the correct place.

**Comment by DJMcNab** [comment]
Hover currently uses the Query fallback, but does give the definition of `reference_definition` for me.

It is worth noting that this is expected currently, as we do not yet support function local items, including imports from `use`s.

**Comment by vipentti** [comment]
This seems to work now for me at least.
