### ISSUE TITLE
disable the default triangle of runnable?

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#5360]
Can the default triangle be disabled because it should be client's side's work, with this triangle I need to disable `coc.nvim`'s default small seperator otherwise it looks like:

![image](https://user-images.githubusercontent.com/33961674/87406549-221e6a00-c5c1-11ea-8838-c5c3bdc981e5.png)

And It looks strange when we call codeLensAction.

![image](https://user-images.githubusercontent.com/33961674/87406302-d370d000-c5c0-11ea-8a0a-d5f712dfdbba.png)

**Comment by matklad** [comment]
No, play button is intentionally part of the text label for **running** code lens.
