### ISSUE TITLE
Add `:` automatically when completing field names inside record literals

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#5365]
This would function similarly to how the `=` is added to the suggestion when completing associated types in trait definitions:

<img width="191" alt="Screen Shot 2020-07-14 at 8 45 44 pm" src="https://user-images.githubusercontent.com/31783266/87417079-fe840f80-c612-11ea-89ff-4525f2c3ae63.png">

**Comment by bjorn3** [comment]
You may have wanted to write `Struct { field }`. In case of `type` inside an impl block the `=` is required for it to be valid syntax. For struct literals it not the case that the `:` is required because of the shorthand initialization syntax.

**Comment by arzg** [comment]
I hadn’t considered the shorthand. I personally find that any kind of ‘smartness’ that you then have to undo yourself because it’s wrong is _really bad._ Would it be possible to replace the `:` with `,` if a `,` is typed afterwards? That isn’t very discoverable, though.

**Comment by matklad** [comment]
Yeah, I think we should just not add `:`. We can look at the scope, but, still, it might be that the user intended to first write the shorthand, and than introduce the local.
