### ISSUE TITLE
Failing to handle varargs in C functions (regression)

### ISSUE THREAD

**Issue by ndemonner** [rust-analyzer/rust-analyzer#5374]
After upgrading RA to `2020-07-13 (5ca7cd9)`, I get the following error:

![image](https://user-images.githubusercontent.com/1157/87441280-c85d7600-c5a7-11ea-9e1c-fe152ae3fc24.png)

**Comment by jonas-schievink** [comment]
We never handled varargs, we just didn't report this error before. I'll take a look at threading the varargs flag through.
