### ISSUE TITLE
Can't specify features for individual crates in a virtual workspace

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-analyzer/rust-analyzer#5383]
When you have a workspace containing multiple crates in subdirectories and those crates have their own feature flags, it's not possible to specify which feature flags to use when checking/navigating that project. 

Setting `rust-analyzer.cargo.features` doesn't work because cargo errors with `"error: --features is not allowed in the root of a virtual workspace`", same as if I ran `cargo check --features foo` from the workspace root.

This becomes particularly evident if you are continuously recompiling and running tests in a background terminal (e.g. `cd sub-crate && cargo watch -x "check --features foo"`). Rust Analyzer ends up compiling the crate/workspace without the feature and `cargo watch` compiles with it. That means you'll constantly be rebuilding the entire crate... Which can be quite expensive when the feature flag enables several transitive dependencies (e.g. `tokio` and a HTTP server).

**Comment by matklad** [comment]
If you are running cargo watch anyway, you should set rust-analyzer.checkOnSave.enable: false. Cargo watch should still provide you with inline error markers, via the problem matcher.

**Comment by Michael-F-Bryan** [comment]
> Cargo watch should still provide you with inline error markers, via the problem matcher

Does the problem matcher need `cargo watch` to be running inside a VS Code terminal? I run `cargo watch` completely separately from VS Code, and when I disabled `checkOnSave` and restarted VS Code it didn't show me any inline error messages.

**Comment by matklad** [comment]
You need to run it as a vscode task, the following definition should work

```json
    {
      "label": "Watch",
      "group": "build",
      "type": "shell",
      "command": "cargo watch --package rust-analyzer",
      "problemMatcher": "$rustc-watch",
      "isBackground": true
    },
```

**Comment by jonas-schievink** [comment]
This is a Cargo limitation that will be addressed by https://github.com/rust-lang/rfcs/pull/2957.

**Comment by matklad** [comment]
I belive this was fixed on the cargo side with the introduction of resolver=2
