### ISSUE TITLE
Vscode documentation? - Apply type annotations

### ISSUE THREAD

**Issue by UebelAndre** [rust-analyzer/rust-analyzer#5384]
I'm having a hard time finding documentation on the vscode extension in terms of what it's expected to do and what (if any) key-shortcuts I have available to me. 

The thing I'm trying to do is apply type annotations that are auto generated by the extension. Is there a way to do that?

**Comment by matklad** [comment]
Alll features are documented here: https://rust-analyzer.github.io/manual.html#assists-code-actions


You want add explicit type assist (the second one in the list)

**Comment by UebelAndre** [comment]
@matklad sorry, this may be a newb question but how do I update vscode to actually write the type annotations to my source code?

**Comment by Veetaha** [comment]
@UebelAndre 
`Alt+Enter` on the symbol definition:
![demo](https://user-images.githubusercontent.com/36276403/87588739-d1a42b00-c6ec-11ea-9cd0-97142cbb5491.gif)

**Comment by UebelAndre** [comment]
Is there documentation for these keyboard shortcuts?

**Comment by Veetaha** [comment]
@UebelAndre that's a general vscode shortcut, I recommend visiting their docs https://code.visualstudio.com/docs/getstarted/keybindings
Rust-analyzer doesn't generally add keybindings automatically, I recommend reading up on `keybindings.json` via the link I pasted in this comment and assigning shortcuts to commands rust-analyzer provides (Ia m not sure there are docs for vscode commands, but here: https://github.com/rust-analyzer/rust-analyzer/blob/6824cf4f8a94dc9d0bd049efcf99e18651c71831/editors/code/package.json#L100)

**Comment by UebelAndre** [comment]
Ah! I see! Thank you!

For anyone who finds this in the future, the feature is called `Quick Fix...` and you can look for it in your Keyboard Shortcuts menu.
<img width="537" alt="Screen Shot 2020-07-16 at 8 55 43 AM" src="https://user-images.githubusercontent.com/26427366/87693749-3178f100-c742-11ea-882e-e0314082529e.png">
