### ISSUE TITLE
Validators should return value on success

### ISSUE THREAD

**Issue by marcusklaas** [rust-analyzer/rust-analyzer#540]
Validators currently only generate errors on bad input and never return the actual values on proper input. Since validation involves parsing the input already, we may just as well return the result so that we don't have to do this at a later point.

**Comment by kiljacken** [comment]
It is not clear to me how this fits with the way the syntax tree works currently. Validators are currently run as a last step after parsing a file is completed, so while it's a prime spot to annotate the tree with useful information, I'm not quite sure how to go about storing it.

The simplest approach would be to store the value in the `ast::Literal` along side its `SyntaxNode`. This would require mutable access during validation, which shouldn't have any issues at the point where we run validations, but has a habit of spreading if we ever need to use the validation machinery outside `SourceFile::parse`.

Anybody got some thoughts?

**Comment by matklad** [comment]
We don't need to *store* thing, it's almost always cheaper to recompute. I think this mostly happens already (see, for example, various `::value` methods in `token.rs`), but we might want to make sure that it happens consistently and has a nice API (in particular, seems like we want a `trait Value` which we implement for literals?).

**Comment by matklad** [comment]
This should be solve on case-by-case basis, strings already work thatn way.
