### ISSUE TITLE
All punctuation has exactly the same color

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#5406]
Before:
![image](https://user-images.githubusercontent.com/36276403/87668419-b4b33a80-c774-11ea-9df5-5f12b59fd15d.png)
Now:
![image](https://user-images.githubusercontent.com/36276403/87670391-4ec8b200-c778-11ea-9338-c1bf05ec10c8.png)

Notice how `::` and `&` lost color.

I recommend creating separate semmantic token types or modifiers for each kind of punctuation (reference, curly brace, parens, bracket, etc.)
cc @ltentrup

**Comment by ltentrup** [comment]
This is indeed a regression caused by adding the punctuation highlight tag. Does it make sense to add all those as separate tags or is there a way to have hierarchical tags, like `punctuation.brace`? I know that there are highlight modifier but I am not sure if they can be used in this way.

**Comment by Veetaha** [comment]
Semantic tokens map to Textmate scopes, so even though there is no way to define hierarchical tags for semantic tokens (you can at most add a modifier and that's it), we can still have a flat definition of punctuation semantic tokens but nested textmate scopes they map to

**Comment by ltentrup** [comment]
I didn't know that but this is pretty handy. In this case, it is pretty easy to fix this regression. I’ll try to open a PR soon.
