### ISSUE TITLE
[feature-request] Extract method/function

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#5409]
It looks this [has been done in VS Code](https://code.visualstudio.com/docs/editor/refactoring) before in the form of a Code Action, which makes me think that it does not rely on any nonstandard extensions to LSP.

**Comment by matklad** [comment]
We have `generate_function`, which is somewhat close in the implementation: https://github.com/rust-analyzer/rust-analyzer/blob/10e3a9879c8714320f9a0729d647da7877f0a753/crates/assists/src/handlers/generate_function.rs

**Comment by arzg** [comment]
Thank you @cpud36, that looks amazing! ❤️
