### ISSUE TITLE
[REQUEST] Mark VSCode only features in the changelog

### ISSUE THREAD

**Issue by Elinvynia** [rust-analyzer/rust-analyzer#5410]
Hello, as many users are not using VSCode but enjoy reading the changelog, it can be quite disappointing to try out the mentioned newly added features and most of them not working, the ideal solution would be supporting more editors, but that's something for the far future, for now I would suggest marking non-LSP specific stuff with a VSCode tag or similar in the changelog.

**Comment by flodiebold** [comment]
Hm. Can you give an example what you would consider "VSCode only"? Because most of our features are using standard LSP or documented LSP extensions, which can and are being implemented by other editors.

**Comment by lnicola** [comment]
Yeah, sorry, we can still do a better job at mentioning which features are protocol extensions.
