### ISSUE TITLE
Handle patterns in type inference

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#542]
We currently don't handle any patterns except simple bind patterns in let. Here are some examples we should be able to handle:
```
let (a, b) = (1, "x");
```
```
enum E { A { x: usize }, B }

let e = E::A { x: 3 };
if let E::A { x: x } = e {
    x
};
match e {
    E::A { x } => x,
    E::B => 1,
};
```
```
let x = &1;
let &y = x;
let ref xx = y;
```

To do this, we need to extend `ra_hir::expr::Pat` to include all these kinds of patterns, and then handle them during type inference by walking down the pattern, writing the pattern type with `write_pat_ty` and passing down the expected type so that `Bind` patterns know which type they are. See also the implementation in rustc: 
https://github.com/rust-lang/rust/blob/03acbd71c977cd63ce5f39ba9b6fe9ffd578785a/src/librustc_typeck/check/_match.rs#L40
(We'll want to handle 'binding modes' as well sooner or later, but a first implementation probably doesn't need to include them.)

**Comment by marcusklaas** [comment]
I'd love to work on this!
