### ISSUE TITLE
MBE: templates are parsed on each invocation

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#5426]
The code [here](https://github.com/rust-analyzer/rust-analyzer/blob/19f891250647b9c08cf9d5f23433ec7380a85010/crates/ra_mbe/src/mbe_expander.rs#L17) goes through each rule to see if it applies. For that, it [parses](https://github.com/rust-analyzer/rust-analyzer/blob/19f891250647b9c08cf9d5f23433ec7380a85010/crates/ra_mbe/src/mbe_expander/transcriber.rs#L85) its definition. Keeping the parsed version on hand might speed up MBE a little.

**Comment by flodiebold** [comment]
@lnicola why did you immediately close this? Seems like an issue we should address at some point.

**Comment by lnicola** [comment]
It was a bit wrong (I wanted `matcher::match_`, the code I linked to is called by `transcribe` IIRC) and the code pretty much expects the current structure (an iterator over references to subtrees). I tried to pre-parse it into a `Vec` but it got too slow (or never finished).

And while MBE is a rather slow (about 45% of the `analysis-stats` parsing time in the RA repo), I have no proof that this repeated parsing of the templates is the problem, so it seemed more wise to close it :-).

**Comment by flodiebold** [comment]
Even regardless of performance, it seems a bit iffy design-wise to me as well.

**Comment by edwin0cheng** [comment]
Since #7083 is landed , could we close this ?

**Comment by lnicola** [comment]
Yes.
