### ISSUE TITLE
[VSCODE] "Add derive" and "Add impl" don't move editor to new cursor position

### ISSUE THREAD

**Issue by DJMcNab** [rust-analyzer/rust-analyzer#543]
This can make for a jarring user experience in large structs/enums, e.g. at https://github.com/rust-analyzer/rust-analyzer/blob/e8e82ce032f8678929b015e6f70ac060bb2cf94c/crates/ra_syntax/src/parser_impl/event.rs#L71, it can be unclear that we actually have added an impl.

This is an issue which we should investigate how to handle using the vscode API. It is not an issue in ra_lsp_server necessarily.

**Comment by kjeremy** [comment]
Note: this works for small structs/enums. It appears to be a problem with larger ones.
