### ISSUE TITLE
Wrong semantic highlighting?

### ISSUE THREAD

**Issue by sheepycoder** [rust-analyzer/rust-analyzer#5445]
![image](https://user-images.githubusercontent.com/67375302/87913826-53011200-ca8d-11ea-81b0-5c9a23869654.png)

I would expect Debug and PartialEq to be of same color.

**Comment by bjorn3** [comment]
Is `Debug` imported? Can you give a minimal reproducing example?

**Comment by sheepycoder** [comment]
```
use std::fmt::Debug;

fn foo<T>(x: T)
where
    T: Debug + PartialEq,
{
    println!("{:?}", x);
}

fn main() {
    foo(1);
}
```
![image](https://user-images.githubusercontent.com/67375302/87921773-aaf14600-ca98-11ea-9011-47a580b3190b.png)

**Comment by lnicola** [comment]
![image](https://user-images.githubusercontent.com/308347/87922009-095ff980-ca84-11ea-9dd6-f70bff694c9b.png)

![image](https://user-images.githubusercontent.com/308347/87922023-0f55da80-ca84-11ea-9c9b-04d68970fbc7.png)

I don't see any difference here.

**Comment by Veetaha** [comment]
Works for me, I think you don't have semantic tokens enabled, you should run `vscode-insiders --enable-proposed-api matklad.rust-analyzer`

**Comment by sheepycoder** [comment]
Nvm, I think the vscode theme I am using has this bug. Works fine with other themes.

**Comment by lnicola** [comment]
> Works for me, I think you don't have semantic tokens enabled, you should run vscode-insiders --enable-proposed-api matklad.rust-analyzer

No, they should work on non-Insiders, too.
