### ISSUE TITLE
Error shown even after deleting all code

### ISSUE THREAD

**Issue by ghost** [rust-analyzer/rust-analyzer#5446]
![image](https://user-images.githubusercontent.com/67375302/87917451-a3c73980-ca92-11ea-9d7d-0a2b877ac272.png)

I am on latest nightly ra in vscode. The errors do not reset even after deleting the code. As you can see the code contains only an empty main function and nothing else, still vscode shows an error. I have to `Reload Window` every few seconds/minutes to get proper errors to be shown.

**Comment by bjorn3** [comment]
Have you saved after changing the code? `cargo check` only runs when you save the code, as otherwise rustc is can't read the changed files.

**Comment by sheepycoder** [comment]
Yup, I have saved after changing the code. New errors (if any) do show up after saving, however most of the times the older ones do not get removed (even if the offending code is removed/fixed).

**Comment by bjorn3** [comment]
Do you use the run task?

**Comment by sheepycoder** [comment]
I run from the lens on top of main().

**Comment by bjorn3** [comment]
VSCode doesn't provide an api to clear the errors for problem matchers I think.

**Comment by sheepycoder** [comment]
Same as https://github.com/rust-analyzer/rust-analyzer/issues/4783

**Comment by kjeremy** [comment]
I've seen this as well. I think that for some reason the LSP layer isn't sending up an empty array to clear the diagnostics.

**Comment by matklad** [comment]
seems to be upstream issue
