### ISSUE TITLE
Automatically insert reference during completion if there's a matching variable

### ISSUE THREAD

**Issue by YaLTeR** [rust-analyzer/rust-analyzer#5449]
This pattern comes up a lot when using e.g. [ash](docs.rs/ash).
```rust
struct CreateInfo {
    /* ... */
}

fn main() {
    let create_info = CreateInfo { /* ... */ };
    foo<complete>
}

fn foo(create_info: &CreateInfo) {
    /* ... */
}
```
Current:
![image](https://user-images.githubusercontent.com/1794388/87934016-f4d92c80-ca96-11ea-9876-2916c7e4a312.png)

Desirable:
![image](https://user-images.githubusercontent.com/1794388/87934090-0faba100-ca97-11ea-9d9c-70ba8f1700c2.png)

**Comment by JoshMcguigan** [comment]
Thanks for the suggestion! This was added in #5846, so I'm going to go ahead and close this issue.
