### ISSUE TITLE
Wrong type deduction [involving type-level macro]

### ISSUE THREAD

**Issue by almindor** [rust-analyzer/rust-analyzer#5455]
NOTE: using this as a re-opening of #5444 as the `use` part is NOT required for this error, see below.

The following code causes Rust Analyzer to "deduce" the type of `obj` to be a form of Iterator instead of the `Object` type and shows the error `Expected 1 argument, found 0` on line 33 by the `.position()` method call. Hovering over the error in the editor (VSCode) is pointing to `core::iter::traits::iterator::Iterator`. I suspect it's related to how `*pos` is deduced on the left side.

The code compiles fine legion = "0.2.4" is required as a dependency.

```rust
use legion::prelude::*;

#[derive(Clone, Default, Copy, Debug, PartialEq)]
struct Position {
    x: f32,
    y: f32,
}

#[derive(Clone, Default, Copy, Debug, PartialEq)]
struct Object {
    pos: Position,
}

impl Object {
    pub fn position(&self) -> &Position {
        &self.pos
    }
}

fn main() {
    // Create a world to store our entities
    let universe = Universe::new();
    let mut world = universe.create_world();

    // Create entities with `Position` and `Velocity` data
    world.insert((), std::iter::once((Position::default(), Object::default(),)));

    // Create a query which finds all `Position` and `Velocity` components
    let query = <(Write<Position>, Read<Object>)>::query();

    // Iterate through all entities that match the query in the world
    for (mut pos, obj) in query.iter_mut(&mut world) {
        *pos = *obj.position(); // RA error here
        println!("X: {:?}", pos);
    }
}
```

**Comment by flodiebold** [comment]
Looks like the `Iterator` impl for `query.iter_mut()` can't be solved, so we don't know the types of `pos` and `obj`. Needs a look in the Chalk logs (and/or the use of the new Chalk file writer, cc @detrumi).

**Comment by detrumi** [comment]
Looks like it's caused by the `{error}` here:
```
#[upstream]
impl<_1_0, _1_1, _1_2> Filter<_1_0> for Adt_9<(_1_1, _1_2)>
where
  _1_0: Copy,
  _1_1: Filter<_1_0>,
  _1_2: Filter<_1_0>
{
  type Assoc_5221 = {error};
}
```
Which is [this impl](https://docs.rs/legion/0.2.4/legion/filter/trait.Filter.html#impl-Filter%3CChunksetFilterData%3C%27a%3E%3E-for-(A%2C%20B)):
```
impl<'a, A, B> Filter<ChunksetFilterData<'a>> for (A, B) where A: Tag, B: Tag {
    type Iter = Zip<(Iter<'a, A>, Iter<'a, B>)>;
}
```
([with `Zip` from `legion_core`](https://github.com/TomGillen/legion/blob/80a3d15c2dbb293052f10d196fdfb656cbb54f68/legion_core/src/zip.rs#L45))

**Comment by flodiebold** [comment]
Ah, that's defined by a type-position macro, which we don't expand yet.

**Comment by lnicola** [comment]
This seems to work now:

![image](https://user-images.githubusercontent.com/308347/106022930-00a14d80-60cf-11eb-969d-e5ee326a87e6.png)

Please reopen if you still notice it.
