### ISSUE TITLE
Semantic Highlighting: Mutability of mut self is not always propagated

### ISSUE THREAD

**Issue by CryZe** [rust-analyzer/rust-analyzer#5461]
If the parameter is `fn(mut self, ...)` as opposed to `fn(&mut self, ...)` then the usage of self is not marked as mutable as it would for other variables.

Correct propagation on `&mut self`:

![https://i.imgur.com/FG5iBqS.png](https://i.imgur.com/FG5iBqS.png)

Incorrect propagation on `mut self`:

![https://i.imgur.com/M8PU72v.png](https://i.imgur.com/M8PU72v.png)

**Comment by Veykril** [comment]
This is the part my pr https://github.com/rust-analyzer/rust-analyzer/pull/5345 didn't implement yet unfortunately as it wasn't trivial to do it seems(unless I missed something). It seems like the self `local` is cast down to a shared reference/immutable value if it is being used as such in the db.
