### ISSUE TITLE
Failure to resolve name collision in local item

### ISSUE THREAD

**Issue by ammkrn** [rust-analyzer/rust-analyzer#5468]
rust-analyzer version: 2020-07-20 (c9c518e)
rustc 1.45.0 (5c1f21c3b 2020-07-13)
vscode 1.47.2 (darwin)

The following code is accepted by rustc, but is rejected as a hard error by RA, since RA believes `Box` to be `std::Box`. If I move `Box` outside of the function block, it both compiles and is accepted by RA.

```
struct X;

impl X {
    pub fn mk_box() -> impl std::fmt::Debug {

        #[derive(Debug)]
        struct Box {
            height : u64,
            width : u64,
        }

        impl Box {
            pub fn new(height : u64, width : u64) -> Box {
                Box { height, width }
            }
        }

        Box::new(1, 2)
    }
}

fn main() {
    let _x = X::mk_box();
    println!("x : {:#?}\n", _x);
}
```

Hovering on the error shows the docs for std::Box, with the message:
```
Expected 1 argument, found 2
```

**Comment by cynecx** [comment]
This is a duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/1559 I'd say.

**Comment by ammkrn** [comment]
> This is a duplicate of #1559 I'd say.

Thanks, I guess I just didn't look hard enough.
