### ISSUE TITLE
VSCode `rustc` problem matcher should use fileLocation autoDetect

### ISSUE THREAD

**Issue by rickvanprim** [rust-analyzer/rust-analyzer#5482]
Per https://github.com/microsoft/vscode/issues/449 and https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher , problem matchers can now be defined that support both relative and absolute paths.  I propose that https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/package.json#L602-L634 be updated to specify `"fileLocation": "autoDetect"`.  Cargo seems to compiles path based dependencies with absolute paths when they are not located inside of the current crate/workspace root (https://github.com/rust-lang/cargo/issues/8506#issuecomment-662037683), and presently the problem matcher that ships with `rust-analyzer` attempts to treat those paths as relative.

Current workaround is to specify inside of `tasks.json`:
```
"problemMatcher": [
    {
        "base": "$rustc",
        "fileLocation": "autoDetect"
    }
]
```

**Comment by kjeremy** [comment]
Do you have an easily reproducible test case for this? PRs welcome!

**Comment by rickvanprim** [comment]
Here's a zip file of a basic workspace with two crates, `executable` and `library`.  If you run `cargo build` inside of `executable` (or specify it from the root with `--manifest-path executable/Cargo.toml`), you'll notice that the compile error inside of `library` prints an absolute path.
[RustAnalyzer_5482.zip](https://github.com/rust-analyzer/rust-analyzer/files/4963716/RustAnalyzer_5482.zip)
