### ISSUE TITLE
Memory leak? 

### ISSUE THREAD

**Issue by ashneverdawn** [rust-analyzer/rust-analyzer#5485]
<img width="608" alt="Screen Shot 2020-07-22 at 12 57 38 AM" src="https://user-images.githubusercontent.com/8341280/88136111-960ad480-cbb6-11ea-8504-d5defd432c09.png">

VSCode isn't even running.

macOS 10.15.6 / VScode 1.47.2 / rustc 1.44.1

**Comment by kjeremy** [comment]
There's not enough information about this but my guess is that those are stale processes. We currently don't watch the parent process id but we probably should.

**Comment by kjeremy** [comment]
If these are stale rust-analyzer processes (there's no client around) can you attach a debugger and get stack traces?

**Comment by Veykril** [comment]
Closing for now as the info is insufficient, if it happens again feel free to reopen.
