### ISSUE TITLE
VSCode Font ligature broken in macros

### ISSUE THREAD

**Issue by Prunoideae** [rust-analyzer/rust-analyzer#5486]
![image](https://user-images.githubusercontent.com/24620047/88141184-aefe9e80-cc25-11ea-95d2-4d66ce0dd9e7.png)

Using rust-analyzer cloned, complied and installed from GitHub on 2020.7.21.
And Fira Code Retina with font ligature on.

**Comment by Prunoideae** [comment]
Also it's strange that why the second println! behaves normally, a guess is that the string literal was processed as a 'whole', while bool operators are broke into single characters in macro processing.

**Comment by lnicola** [comment]
Thing is, I don't think we do anything that's likely to affect ligatures. The editor is in charge of rendering the text and we can't really change it (the inlay type hints being an exception).

Also, for some reasons ligatures no longer seem to work for me -- at all:

![image](https://user-images.githubusercontent.com/308347/88142365-10ab1280-cbfe-11ea-81b1-0f86710b8d95.png)

**Comment by Prunoideae** [comment]
![image](https://user-images.githubusercontent.com/24620047/88142373-fe45ce80-cc27-11ea-9f0f-d6700b76472b.png)

Switching back to rls does solve this issue, so there may be something strange in rust-analyzer?

**Comment by lnicola** [comment]
Looks like turning off `editor.semanticHighlighting.enabled` fixes it. Maybe it's something about the way we set the spans that breaks ligatures?

**Comment by Prunoideae** [comment]
Yes it does get fixed. 
I don't know the analyzer much so there's not much thing I can talk on it, sorry.

**Comment by lnicola** [comment]
It does work fine with the TypeScript extension, though:

![image](https://user-images.githubusercontent.com/308347/88143014-308f0600-cbff-11ea-9da9-2b51cea3b33e.png)

**Comment by Nufflee** [comment]
any updates on this???????

**Comment by Veykril** [comment]
This seems to be working fine for me now
![image](https://user-images.githubusercontent.com/3757771/120889572-218a2a00-c5fe-11eb-96a7-d980b2f63234.png)
