### ISSUE TITLE
Server should monitor the client process id and die if it goes away

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#5496]
The client can send down an optional process id in the `InitializeParams`. If present we should watch it (maybe using the `sysinfo` crate so it's cross-platform?) on a timer. If the process goes away the server should kill itself. This should prevent bugs like #5485. This is also what the node based language servers do.

**Comment by jonas-schievink** [comment]
Do language servers communicate with the editor via stdin/stdout? If so, why can't rust-analyzer exit if stdin is closed? If I'm not mistaken that should happen automatically when the parent exits.

**Comment by matklad** [comment]
yup, we should just exit when stdin is closed.

Might make sense to check if we actually do that, I think sometimes we fail to do that.

**Comment by kjeremy** [comment]
There are occasionally stale processes left so I don't think we always catch it.

**Comment by lnicola** [comment]
Maybe we're stuck processing a request? We do get stuck in chalk from time to time.

**Comment by kjeremy** [comment]
I'm going to close this for now
