### ISSUE TITLE
Push tags for vscode extension versions

### ISSUE THREAD

**Issue by mattburgess** [rust-analyzer/rust-analyzer#5509]
I use VSCodium, which since v1.46.0 doesn't use the Microsoft Marketplace for extensions, but instead uses https://open-vsx.org/.
The rust-analyzer extension is being published to that MarketPlace by the code at https://github.com/open-vsx/publish-extensions/blob/1542b6ec2a98eb5fc153995866888744b5557b12/extensions.json#L486-L491.

It would be nice if rust-analyzer/rust-analyzer would publish tags with the same version number as the extension is published with to the MS Marketplace. That way, a simple PR to the open-vsx repo above will have the same version made available there as well.

At the moment, openvsx has a `0.4.0-dev` version available which doesn't correspond to any upstream versioning scheme at all. That makes it really unclear as to how recent it is, what features it should have, etc.

**Comment by jonas-schievink** [comment]
The plan is to use https://github.com/rust-lang/vscode-rust/ instead of the extension in this repo, so maybe ask there?

**Comment by mattburgess** [comment]
Ah, that's great. And it turns out they already push tags and version numbers correctly, such that https://open-vsx.org/extension/rust-lang/rust is already there. Thanks!
