### ISSUE TITLE
[Chore Feature Request]: Release binary file structure change?

### ISSUE THREAD

**Issue by dalisoft** [rust-analyzer/rust-analyzer#5530]
Hi @rust-analyzer and contributors. 

Can you please change release binary archive files/folder structure?

Current behaviour: `rust-analyzer-linux`  after extracting archive
Excepted behaviour: `rust-analyzer` after extracting archive

This makes automation to installation makes easier and much native-like for extracting directly to `/usr/local/bin`

Thanks

**Comment by bjorn3** [comment]
`rust-analyzer-linux.gz` is not an archive. It is a compressed file. It doesn't contain a filename for the extracted file. Insteas the decompressor just strips the `.gz` extension by default. If you want a different name, you will have to tell the decompressor about this.

**Comment by dalisoft** [comment]
Sorry then, i just got understand. Thanks a lot for help and tip. Issue solved
