### ISSUE TITLE
dbg postfix doesn't automatically close with semicolon

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#5535]
when we type:

```
msg.dbg|
```

we would like it turns into:
```
dbg!(msg);
```

instead of
```
dbg!(msg)
```

because we will need to type `;` to fix compiling, I'm not sure if there are other postfixes which need this

**Comment by bjorn3** [comment]
You may have wanted to continue the statment to something like `dbg!(msg).unwrap();`.

**Comment by GopherJ** [comment]
@bjorn3 so in this case maybe what we can turn:

```
msg.dbg|
```

```
dbg!(msg)|;
```

will it be better to fit two cases?

**Comment by bnjjj** [comment]
It's already the case for me. Do you have an example to reproduce ?

**Comment by GopherJ** [comment]
@bnjjj Hi, with currentl version it's:

```
dbg!(msg)|
```
instead of 

```
dbg!(msg)|;
```

**Comment by CryZe** [comment]
Why would you want a semi colon though? In a lot of cases the dbg! macro is used as an expression, not a statement.

**Comment by GopherJ** [comment]
@CryZe actually that's my question, I use `dbg!` more as a statement, if most of the developers think they use `dbg!` as an expression, definitly we should close this issue.

**Comment by GopherJ** [comment]
Hi, I finally think this should be closed because I also started to use `dbg` as expression~ Thanks!
