### ISSUE TITLE
Unable to resolve `${workspaceRoot}` in multi folder workspace

### ISSUE THREAD

**Issue by mburszley** [rust-analyzer/rust-analyzer#5536]
I have a project where I have multiple crates in a single repository split by directory and am using the multi-root workspace feature of vscode so the extension doesn't break (it doesn't like seeing multiple `Cargo.toml` files in a single workspace).

![image](https://user-images.githubusercontent.com/25436433/88469119-84c60e80-cebb-11ea-89c8-1982af2d8ebd.png)

When I'm trying to debug a test (through WSL2 Ubuntu-20.04 via Remote - WSL using the CodeLLDB extension and rust-analyzer nightly on stable toolchain), it's telling me I need to scope the variable which led me to [this piece of documentation](https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder).  In my generated `launch.json`, I see the following config:

```json
        {
            "type": "lldb",
            "request": "launch",
            "name": "Debug unit tests in library 'aoc-1'",
            "cargo": {
                "args": [
                    "test",
                    "--no-run",
                    "--lib",
                    "--package=aoc-1"
                ],
                "filter": {
                    "name": "aoc-1",
                    "kind": "lib"
                }
            },
            "args": [],
            "cwd": "${workspaceFolder}"
        },
```

I changed the variable reference to include the folder name where the workspace root is (`"${workspaceFolder:1}"`) and I tried changing it to `"."`, but it's still getting a reference to `${workspaceFolder}` from *somewhere*.

Here's a sample of what I'm doing:

```
root/
|-- 1/
|   |-- .vscode/
|   |   |-- launch.json
|   |-- src/
|   |   |-- lib.rs
|   |-- Cargo.toml
|-- .gitignore
|-- aoc.code-workspace
```

The only configuration difference in `Cargo.toml` is changing the `name` to `aoc-1`.

Here is my workspace file:

```json
{
	"folders": [
		{
			"name": "root",
			"path": "."
		},
		{
			"name": "day-1",
			"path": "1"
		}
	],
	"remoteAuthority": "wsl+Ubuntu-20.04",
	"settings": {}
}
```

and `lib`:

```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn assert_instruction() {
        let instr = Instruction::new("R83");
        assert_eq!(instr, Instruction { count: 83, direction: Direction::Right });
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
struct Instruction {
    count: i16,
    direction: Direction,
}

impl Instruction {
    pub fn new(s: &str) -> Self {
        let (direction, count) = s.split_at(1);
        let direction: Direction = direction.parse().unwrap();
        let count: i16 = count.parse().unwrap();

        Instruction {
            count,
            direction,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
enum Direction {
    Up,
    Right,
    Down,
    Left,
}

impl std::str::FromStr for Direction {
    type Err = &'static str;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "U" => Ok(Direction::Up),
            "R" => Ok(Direction::Right),
            "D" => Ok(Direction::Down),
            "L" => Ok(Direction::Left),
            _ => Err("Failed to parse direction!"),
        }
    }
}
```

**Comment by flodiebold** [comment]
Should be fixed by #5513.
