### ISSUE TITLE
Wrong type deduction #2

### ISSUE THREAD

**Issue by ferreus** [rust-analyzer/rust-analyzer#5544]
```rust
use std::ops;

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Vec3 {
    v: [f64;3]
}
impl Vec3 {
    pub fn new(e0: f64, e1: f64, e2: f64) -> Vec3 {
        Vec3 {v: [e0, e1, e2]}
    }
}
impl ops::Mul<f64> for Vec3 {
    type Output = Vec3;
    fn mul(self, t: f64) -> Self::Output {
        Vec3::new(self.v[0]*t, self.v[1]*t, self.v[2]*t)
    }
}

#[cfg(test)]
mod tests {
    use super::Vec3;

    #[test]
    pub fn length() {
        let v = Vec3::new(1.0,1.0,1.0);
        let v2 = v * 2.0; //v2 type is Vec3, but rust analyzer shows f64
        assert!(v2.v[0] > v.v[0]);
    }
}
```

![bug_png](https://user-images.githubusercontent.com/206508/88523085-0626b980-d000-11ea-98bb-0507c0ab83df.png)
Rust-analyzer: 0.2.248

**Comment by ruabmbua** [comment]
Does ra already handle core::ops::*;?

If not, that is probably the issue.

**Comment by kiljacken** [comment]
If I recall correctly we only support custom unary operations, not the
binary ones yet

**Comment by flodiebold** [comment]
Yeah, that's correct:

https://github.com/rust-analyzer/rust-analyzer/blob/f1d507270c7d915ef0177feca7b6745d95169ac8/crates/ra_hir_ty/src/infer/expr.rs#L527-L533

**Comment by ruabmbua** [comment]
I don`t think it is very difficult to implement it. 

Looking at the handler for ops::Index there is already everything we need. Resolving associated type of lang item trait with generic parameters.

**Comment by ruabmbua** [comment]
Does anyone know a good project, in which we can run analysis-stats pre / post fixing this? I imagine a game with e.g. the cgmath crate would be a good start.

**Comment by lnicola** [comment]
I think we have some overloaded operators from the text-size crate, so we should at least see an improvement. As a larger test, maybe euclid, cgmath or nalgebra?

**Comment by ruabmbua** [comment]
I managed to implement it, but I am hitting a problem.

Impls for operations, which use the Self type alias in the parameters can not be resolved correctly.

E.g.

```ruststruct A;

impl std::ops::Sub for A {
    type Output = bool;
    fn sub(self, rhs: Self) -> Self::Output {
        true
    }

}

```

**Comment by ruabmbua** [comment]
Never mind. I think it is a problem with default trait parameters.

```rust
// Works:
impl std::ops::Sub<Self> for A {
    type Output = bool;
    fn sub(self, rhs: Self) -> Self::Output {
        true
    }

}

// Does not work:
impl std::ops::Sub for A {
    type Output = bool;
    fn sub(self, rhs: Self) -> Self::Output {
        true
    }

}
```

**Comment by ruabmbua** [comment]
Currently blocked by: https://github.com/rust-analyzer/rust-analyzer/issues/5685

**Comment by flodiebold** [comment]
Does it really block this though? I think you should still be able to write tests for this and even try it out in real code, it just won't work with some existing impls, right?

**Comment by ruabmbua** [comment]
It does not work on the impls from the standard  library for integers u.s.w.

**Comment by ruabmbua** [comment]
If the default type param stuff would work, we do not even need special cases for primitive types.

**Comment by flodiebold** [comment]
We might still want to keep the special cases for primitive types for performance anyway.

**Comment by ruabmbua** [comment]
Yeah you may be right. I must admit, I was just a little bit intrigued by the fact, that we may not need to handle built in types at all.

**Comment by flodiebold** [comment]
We can still decide to do that later :wink:
