### ISSUE TITLE
Can't hide Hover Actions. Settings appear to be ignored.

### ISSUE THREAD

**Issue by LeCyberDucky** [rust-analyzer/rust-analyzer#5545]
Hi, 

I'm trying to get rid of these "run" and "implementations" lines as seen here: 

![image](https://user-images.githubusercontent.com/19520383/88529669-9c5adf80-d000-11ea-9eb2-7fee8afc8308.png)
![image](https://user-images.githubusercontent.com/19520383/88529708-aaa8fb80-d000-11ea-8864-c7577c8106df.png)

I assume that's what these settings are responsible for: 

![image](https://user-images.githubusercontent.com/19520383/88529774-bf858f00-d000-11ea-8f20-4021caaa521b.png)

But I simply can't get rid of them. I've disabled them both under "user" and "workspace", but they're still there. I have this in my settings.json: 

![image](https://user-images.githubusercontent.com/19520383/88530013-0ecbbf80-d001-11ea-88d8-aa8c98dd138f.png)

Am I missing something, or is this broken?

Edit: I forgot to mention that I have just tried reinstalling the extension, but that didn't help. Is there something else I should do? I'm happy to provide more information if something is needed.

**Comment by lnicola** [comment]
Hover actions are panes that show up when you hover a symbol with the mouse cursor. You want `rust-analyzer.lens.enable`.

**Comment by LeCyberDucky** [comment]
I see. I'm sorry about the confusion. Thank you!
