### ISSUE TITLE
vscode links in the documentation pop-up do not work

### ISSUE THREAD

**Issue by ompadu** [rust-analyzer/rust-analyzer#5546]
Windows, latest vscode and rust versions:

`rustc 1.45.0 (5c1f21c3b 2020-07-13)`

![3](https://user-images.githubusercontent.com/6009271/88537232-dd112380-d015-11ea-8089-6b0685411b9f.PNG)

Clicking on links to local documentation:

![Capture](https://user-images.githubusercontent.com/6009271/88537335-0f228580-d016-11ea-8eb6-a53f5e599c55.PNG)

Links that open in the browser show this:

![2](https://user-images.githubusercontent.com/6009271/88537354-1d70a180-d016-11ea-9d6d-96a37ab04987.PNG)

**Comment by lnicola** [comment]
Triage: still happens.

![image](https://user-images.githubusercontent.com/308347/103008248-8153b380-453d-11eb-8a29-f1ddb443a8ad.png)
