### ISSUE TITLE
Support cfg_attr

### ISSUE THREAD

**Issue by mehmooda** [rust-analyzer/rust-analyzer#5548]
It seems the following is currently not supported:

```rust
#[cfg_attr(target_os = "windows", path = "os_windows.rs)]
mod os;
```
I've had to do the following:

```rust
#[cfg(target_os = "windows")]
mod os_windows;
#[cfg(target_os = "windows")]
use os_windows as os;
```

**Comment by crumblingstatue** [comment]
The following is not highlighted as code in the doc string

```Rust
    #[cfg_attr(feature = "ci-headless", doc = "```no_run")]
    #[cfg_attr(not(feature = "ci-headless"), doc = "```")]
    /// Code goes here...
    /// ```
```

Not sure if only because of the missing cfg_attr support, or if there are other factors too.

**Comment by jonas-schievink** [comment]
I've now added `cfg_attr` support. The code in the original report should now work fine, but there are still some parts of r-a that use syntactical attributes, so they don't handle `cfg_attr`.

**Comment by c410-f3r** [comment]
cc #5016

**Comment by jonas-schievink** [comment]
Doc comments don't work with `#[doc]` attributes at all, so this isn't due to `cfg_attr` (though this is fixed by https://github.com/rust-analyzer/rust-analyzer/pull/8059).

Closing this issue. For any other `cfg_attr` related problems, new issues should be filed.
