### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#5551]
Some users seem to be worried about the privacy implications of running rust-analyzer, especially in the context of loaded terms such as "metrics" and "diagnostics".

We could have a section in the user manual mentioning any privacy caveats. Currently, the only one is the Code extension update check: ~~in the default configuration~~ when configured to use nightly builds (~~unless~~ and if `rust-analyzer.serverPath` is not set), it queries the GitHub API to find if any LSP server updates are available. The file itself is not downloaded unless `rust-analyzer.updates.askBeforeDownload` was disabled by the user.

**Comment by matklad** [comment]
> Currently, the only one is the Code extension update check: in the default configuration (unless rust-analyzer.serverPath is set), it queries the GitHub API to find if any LSP server updates are available.

Only on nightly — I think stable doesn’t do any http.

**Comment by lnicola** [comment]
Oh right, this happens here: https://github.com/rust-analyzer/rust-analyzer/blob/48f9a05692e509c3bfd7df5b1088fe2863617714/editors/code/src/main.ts#L154.
