### ISSUE TITLE
Ruquest failed on improper code

### ISSUE THREAD

**Issue by saveriomiroddi** [rust-analyzer/rust-analyzer#5552]
If I write and save the following (invalid) code:

```rust
enum Command {
    Publish(&' str),
    Message,
}
```

I get an error from VSC (popup on the bottom right); in the console, this is the output:

```rust
error: unterminated character literal
 --> <stdin>:6:14
  |
6 |     Publish(&' str),
  |              ^^^^^^^

[Error - 10:02:09 PM] Request textDocument/formatting failed.
  Message: rustfmt exited with:
                           Status: exit code: 101
                           stdout: 
  Code: -32900 
```

I'm not a Rust/VSC expert; apologies if this is not a rust-analyzer issue :slightly_smiling_face:

**Comment by lnicola** [comment]
I don't think that's an issue. We try to format the code using rustfmt when you save a file. If it's invalid, you'll get an error like that, but it should work fine after you fix it.
