### ISSUE TITLE
Fill in SymbolInformation container_name from workspace/symbol query

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#559]
It would be nice to fill this in for the UI.

**Comment by matklad** [comment]
Will need to add additional info to `FileSymbol` struct:

https://github.com/rust-analyzer/rust-analyzer/blob/0974e6abeb9c3f047e21c3e23769b93c9e7dcaf3/crates/ra_hir/src/db.rs#L80

And we should add more context to the `to_symbol` function such that it actually knows the parent:

https://github.com/rust-analyzer/rust-analyzer/blob/0974e6abeb9c3f047e21c3e23769b93c9e7dcaf3/crates/ra_ide_api/src/symbol_index.rs#L215-L231
