### ISSUE TITLE
Cargo check runs forever, huge delays in displaying errors and slow autocomplete

### ISSUE THREAD

**Issue by bugproof** [rust-analyzer/rust-analyzer#5617]
It seems like `cargo check` runs forever :(. Completely stops me from doing anything serious.

![image](https://user-images.githubusercontent.com/3116731/88981287-e6c0b280-d2c5-11ea-9ce0-f00558edae31.png)

Also there are huge delays in displaying errors, e.g. it wants me to wrap call in unsafe block, when I wrap it I have to wait 20 seconds before the error disappears. 

Also, there seems to be a problem with autocomplete. Takes 6-10 seconds to show up: 
![image](https://user-images.githubusercontent.com/3116731/88981657-bd545680-d2c6-11ea-96cb-05e8ac2dc2a0.png)

Any reason why it happens? I have 100K LOC bindings file generated from bindgen. Maybe that is the issue?

CPU: Ryzen 3700x
OS: windows 10 x64

**Comment by bugproof** [comment]
OK it seems like huge file (100k loc) was the problem. I whitelisted only what I need and it's fine now.

**Comment by vaikzs** [comment]
@bugproof how did you whitelist the files that cargo has to check. Can you provide the attribute in settings.json?

**Comment by bugproof** [comment]
> @bugproof how did you whitelist the files that cargo has to check. Can you provide the attribute in settings.json?

I didn't whitelist the files that cargo has to check. I whitelisted what I want generated with bindgen so instead of generating 100K LOC in generated 1-10K. The problem with huge files still exists.

**Comment by vaikzs** [comment]
Thanks @bugproof. 

I'm using VSCode + rust analyzer. Rust analyzer checkOnSave is extremely slow even for small changes. All I'm expecting is a syntax highlighting.

**Comment by vaikzs** [comment]
@bjorn3 which I did but it defeats the purpose. I need compiler syntax highlighting. any suggestions?

**Comment by Veykril** [comment]
with syntax highlighting do you mean diagnostics (errors, warnings, etc.) or coloring the tokens in your editor?

**Comment by vaikzs** [comment]
@Veykril yes.

**Comment by mageowl** [comment]
`cargo clean` can sometimes help with this.

**Comment by ValorZard** [comment]
yeah im still getting this issue ughhh

**Comment by ChayimFriedman2** [comment]
There is basically nothing we can do on our side to improve the situation here. If you have a big project, checking it will take a long time, that's a rustc issue. Try enabling incremental compilation and see if it helps.

One thing to be aware of is that if the command-line `cargo check` and rust-analyzer differ in their flags/rustflags etc., each will clear each other and start from scratch, which can lead to very slow checking. In that case, either make the flags the same or use a different target directory for rust-analyzer check (`rust-analyzer.cargo.targetDir`).
