### ISSUE TITLE
Go-to-definition doesn't work through VS Code Live Share

### ISSUE THREAD

**Issue by daboross** [rust-analyzer/rust-analyzer#5644]
Hi,

I've been using rust-analyzer with VS Code Live Share for a while now, and sometime within the last few months, go to definition stopped working. I'm not sure if this is a problem with VS Code or the Live Share plugin, but I figured I'd file it here. I'm looking for help debugging this, finding the root cause, and/or fixing the issue.

To reproduce:
- install rust-analyzer and Live Share (https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare)
- get rust-analyzer working on a small rust project
- start live share
- on a separate computer (and separate github account to login to live share with), connect to the liveshare instance
- try "go to definition" on any symbol on the second computer.

As far as I can tell, go to definition _never_ works. It just doesn't do anything for the guest. I've tried this with a Linux x86_64 host and Windows 10 guest, and vice-versa.

Throughout the testing, go-to-definition _has_ worked on the Host. Just not on the guest.

Doing this same procedure with a few different VS code plugins works. Tested:
- [python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) - go-to-definition just works
- [go](https://marketplace.visualstudio.com/items?itemName=golang.Go) - go-to-definition just works
- [Rust](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust) plugin with RLS - go-to-definition just works
- typescript - go-to-definition causes explicit error - https://github.com/MicrosoftDocs/live-share/issues/3570
- rust-analyzer - go-to-definition silently fails

Notably, it seems like both rust-analyzer [go plugin](https://github.com/golang/vscode-go/) go directly through the language server - at least, it's confirmed via debugger that neither use `vscode.DefinitionProvider`, and both do register language servers. Not sure what's different that lets go work, but not rust-analyzer.

Separate from this, there are a few other things broken for Live Share guests that it'd be nice to fix. But not having go-to-definition is the biggest issue. Other things not working include semantic highlighting, and code actions/running tests (though code actions / running tests not working is a [known live share issue](https://github.com/MicrosoftDocs/live-share/issues/3121)).

**Comment by daboross** [comment]
I think I've reduced this to a live share issue, where it doesn't support `LocationLink`-type results: https://github.com/MicrosoftDocs/live-share/issues/3781

**Comment by aletsdelarosa** [comment]
@daboross yes, that is correct, We are not supporting `LocationLink` as a result for `Definition` we are working on a fix.

**Comment by aletsdelarosa** [comment]
@daboross  I will update [issue #3570](https://github.com/MicrosoftDocs/live-share/issues/3570) on Live Share repo. I think you can close this issue.
