### ISSUE TITLE
Type checking doesn't work when `rocket` library is a dependency

### ISSUE THREAD

**Issue by brundonsmith** [rust-analyzer/rust-analyzer#5646]
To reproduce:
1. Create a new Rust bin project via cargo
2. Paste this into `main.rs`:
```rust
fn main() {
    let foo:&str = 12;
}
```
3. Add this to `Cargo.toml`:
```toml
[dependencies]
rocket = "0.4.5"
```
4. Note that there's no type error in `main.rs`
5. Removing the dependency brings the error back

Things to note:
- Syntax errors and parameter names still show up, so rust-analyzer is functioning in some capacity
- Rocket does a lot of fancy macro stuff (though it doesn't have to be used for this to happen); could that be relevant?

**Comment by bjorn3** [comment]
Are you using nightly?

```
error: failed to run custom build command for `rocket v0.4.5`

Caused by:
  process didn't exit successfully: `/home/bjorn/test_project/target/debug/build/rocket-f9eb5b1b9f1891f5/build-script-build` (exit code: 101)
--- stderr
Error: Rocket (core) requires a 'dev' or 'nightly' version of rustc.
Installed version: 1.44.1 (2020-06-17)
Minimum required:  1.35.0-nightly (2019-04-05)
See the getting started guide (https://rocket.rs/v0.5/guide/getting-started/) for more information.
thread 'main' panicked at 'Aborting compilation due to incompatible compiler.', /home/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.5/build.rs:29:13
```

Version `0.4.5` of rocket still requires a nightly compiler. Only starting from the not yet released version `0.5.0` does rocket support a stable compiler.

**Comment by brundonsmith** [comment]
I'm using nightly from my cargo commands; I'm not sure how to specify it for rust-analyzer

**Comment by SomeoneToIgnore** [comment]
Afaik, RA does not have a native diagnostics to check the types yet. 
This meand that the error comes from the `cargo check` output that is used by RA internally and by default is run after every change in the project.

`cargo check` for a project with no dependencies happens instantly, while `rocket` brings a significant dependency footprint into the project hence initial `cargo check` might be very slow.
Try running `cargo check` manually after adding `rocket` and try editing the file after the successul run.

**Comment by brundonsmith** [comment]
`cargo +nightly check` runs instantly for the above case and doesn't have an effect on what the editor shows

It makes sense that there's no way rust-analyzer would know it needs to be performing the check in nightly, I'm just not sure how to tell it to do that. I couldn't find a relevant option in the settings.

**Comment by bjorn3** [comment]
Run `rustup override set nightly` in the project dir. This makes all commands in that dir use nightly by default.

**Comment by bjorn3** [comment]
You can also create a file called `rust-toolchain` in the project dir with the text `nightly`. That way everyone cloning your project will use nightly by default.

**Comment by brundonsmith** [comment]
That worked, thanks. It would be good if rust-analyzer could provide a pop-up notification or something in the future, rather than silently failing

**Comment by bjorn3** [comment]
That is https://github.com/rust-analyzer/rust-analyzer/issues/3155

**Comment by brundonsmith** [comment]
Perfect, thank you!
