### ISSUE TITLE
Shutdown request causes a crash

### ISSUE THREAD

**Issue by DanielChabrowski** [rust-analyzer/rust-analyzer#5647]
Hey,
I started using rust-analyzer with emacs yesterday and there's a crash happening during shutdown request. Which is particularly annoying because lsp-mode asks me to restart the lsp and doesn't close the app till I answer.

Output from lsp-mode:
```
LSP :: rust-analyzer:723118 initialized successfully
LSP :: rust-analyzer has exited (exited abnormally with code 101)
LSP :: Sending to process failed with the following error: Process rust-analyzer not running
```

rust-analyzer bt indicating that it crashes in lsp-server:
```
thread 'main' panicked at 'Invalid request
Method: shutdown
 error: invalid type: map, expected unit', /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/macros.rs:16:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:342
  13: lsp_server::msg::Request::extract::{{closure}}
  14: lsp_server::msg::Request::extract
  15: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::on_request
  16: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
  17: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
  18: rust_analyzer::main_loop::main_loop
  19: rust_analyzer::main
  20: std::rt::lang_start::{{closure}}
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  23: std::panicking::try
             at src/libstd/panicking.rs:274
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  26: main
  27: __libc_start_main
  28: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process rust-analyzer stderr finished
```

Request that I assume crashed it:
```
[Trace - 06:19:30 ] Sending request 'shutdown - (4)'.
Params: {}
```

Happens with both latest release and `e96bfd8`.

It seems that the issue comes from the fact that lsp-mode sends `Params: {}` in shutdown request. Similar issue was documented in rls (https://github.com/rust-lang/rls/blob/master/rls/src/server/mod.rs#L532).

**Comment by DanielChabrowski** [comment]
I did some more digging, apparently they send {} instead of null for reasons stated here: https://github.com/emacs-lsp/lsp-mode/pull/1074 while https://www.jsonrpc.org/specification proposes that `params` may be omitted instead.

I fixed this by changing the definition in lsp-types to:
```rust
impl Request for Shutdown {
    type Params = Option<serde_json::Map<String, serde_json::Value>>;
    type Result = ();
    const METHOD: &'static str = "shutdown";
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_shutdown_deserialize() {
        use serde_json::json;

        serde_json::from_value::<<Shutdown as Request>::Params>(json!(null))
            .expect("Expected success");

        serde_json::from_value::<<Shutdown as Request>::Params>(json!({}))
            .expect("Expected success");
    }
}
```
I have not tried a client that sends a null so my above representation may be incorrect.

If this solution is acceptable, I can make a PR to lsp-types and then bump the version here.

**Comment by kjeremy** [comment]
The LSP spec says that it should be `void` which i think means "not present". See: https://microsoft.github.io/language-server-protocol/specification#shutdown

You may want to raise the issue in the language-server-protocol repo.

**Comment by vsrs** [comment]
@kjeremy "not present" does not work for RA too. Please see https://github.com/rust-analyzer/lsp-server/pull/17

**Comment by alxiong** [comment]
same issue here, exactly the same error (after updating my `lsp-mode` ...)

thanks @DanielChabrowski for submitting this issue!

**Comment by flodiebold** [comment]
I can't reproduce this in my Emacs. @DanielChabrowski is this still happening?

**Comment by joncol** [comment]
I just started experiencing something very similar to this, but not specifically during shutdown.

When opening any `.rs` file, I get: `LSP :: rust-analyzer has exited (exited abnormally with code 101)` (in the `*Messages*` buffer).

`rust-analyzer` version: 20201221-1 (on Arch Linux).
I've got the latest versions of Rust installed via `rustup update` as of today:
```
stable-x86_64-unknown-linux-gnu - Up to date : 1.48.0 (7eac88abb 2020-11-16)
nightly-x86_64-unknown-linux-gnu - Up to date : 1.50.0-nightly (11c94a197 2020-12-21)
```

Not much else to go on.

**Comment by pabloariasal** [comment]
@joncol having the same issue on Arch Linux after upgrading to `rust-analyzer - 20201221-1`.
If you still have the old package in your cache (`/var/cache/pacman/pkg/`) you can downgrade to version `20201214-1`, which works just fine.

**Comment by joncol** [comment]
> @joncol having the same issue on Arch Linux after upgrading to `rust-analyzer` version `20201221-1`.
> If you still have the old package in your cache (`/var/cache/pacman/pkg/`) you can downgrade to version `20201214-1`, which works just fine.

I'll do just that, thanks for the tip. Do you think a new issue should be opened, or?

**Comment by flodiebold** [comment]
That's probably #6979.
