### ISSUE TITLE
Rust analyzer reports arity error wrong when there is attributes on the function definition

### ISSUE THREAD

**Issue by GrayJack** [rust-analyzer/rust-analyzer#5649]
Rust analyzer reports arity error wrong when there is attributes on the function definition

### Example
```rust
fn foo(#[cfg(unix)] x: i64, #[cfg(not(unix))] x: i32) {
    todo!()
}

fn main() {
    let _ = foo(x);
}
```

The code above will show an error `Expected 2 arguments, found 1`

**Comment by lnicola** [comment]
You can make those go away using `rust-analyzer.diagnostics.enableExperimental`.

**Comment by GrayJack** [comment]
I personally don't mind, I just wanted to report the error.

But it's good to know that can be disabled :smile:

**Comment by jonas-schievink** [comment]
Presumably the fix is to check for `#[cfg]` attributes when lowering function parameters here:

https://github.com/rust-analyzer/rust-analyzer/blob/af6e9a7eb3c321ea43d3ac14c2b05f8c58e1abac/crates/ra_hir_def/src/item_tree/lower.rs#L307-L310

**Comment by jcdickinson** [comment]
Comment for search engines: `#[derive(SystemDesc)]` from Amethyst triggers `Expected 2 arguments, found 1`.

**Comment by jonas-schievink** [comment]
Okay so this is a deeper-than-expected rabbit hole, since `#[cfg]` can be put on `&self`, and even on the tailing varargs `...` parameter. I don't think we have a nice way of handling that at the moment. Maybe `ItemTree` should already perform cfg-stripping, but I feel like there must be a reason it doesn't.

I'm assuming the Amethyst issue is unrelated except that the numbers happen to match? Not sure why it would use `#[cfg]` on parameters.

**Comment by djc** [comment]
I just ran into this as well on trust-dns, which defines some associated functions with an optional extra argument depending on a Cargo feature. The extra errors confused me for a while.

**Comment by Tamschi** [comment]
This issue also affects parameter lists:

```rust
struct C(#[cfg(FALSE)] ());
impl C {
    fn new() -> Self {
        Self(
            #[cfg(FALSE)]
            (),
        )
    }
}
```

This code compiles fine, but reports:

```json
{
	"resource": "[…]/src/main.rs",
	"owner": "rustc",
	"code": {
		"value": "mismatched-arg-count",
		"target": {
			"$mid": 1,
			"external": "https://rust-analyzer.github.io/manual.html#mismatched-arg-count",
			"path": "/manual.html",
			"scheme": "https",
			"authority": "rust-analyzer.github.io",
			"fragment": "mismatched-arg-count"
		}
	},
	"severity": 8,
	"message": "Expected 0 arguments, found 1",
	"source": "rust-analyzer",
	"startLineNumber": 4,
	"startColumn": 9,
	"endLineNumber": 7,
	"endColumn": 10
}
```
(`[…]` mine.)

**Comment by jonas-schievink** [comment]
> ```rust
> struct C(#[cfg(FALSE)] ());
> impl C {
>     fn new() -> Self {
>         Self(
>             #[cfg(FALSE)]
>             (),
>         )
>     }
> }
> ```

Huh, this is interesting, the field gets removed correctly, and the `()` argument also gets the "code is inactive due to `#[cfg]`" diagnostic, but the arity error is still there

**Comment by jonas-schievink** [comment]
That specific issue is now fixed. Unfortunately I can't look into the Amethyst bug because I can't find the `SystemDesc` derive.

**Comment by jonas-schievink** [comment]
Fixed the remaining issues in https://github.com/rust-analyzer/rust-analyzer/pull/8068.

If the Amethyst issue persists, please open a new issue.
