### ISSUE TITLE
Design & implement diagnostics API

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#565]
We don't report any errors (besides syntax) currently, but we probably should :sweat_smile: 

To do this, we'll need a diagnostics API.

Here are some rough thoughts about it:

* diagnostics are a "cold path": we expect to not emit diagnostics for most of the code, and, if we do, it's ok if it is somewhat slow. 
* diagnostics need text offsets
* the previous two points imply that diagnostics should be a part of syntax mapping
* while diagnostics are provided by the guts of the compiler, the fixes should be provided by an IDE, and they should be diagnostics specific. This implies some kind of any map setup?
* in the compiler, it would be conventient to have a mutable sink-style API for diagnostics: instead of returning a set of diagnostics explicitly, record them as a side-effect of computation
* with the lazy setup, it's unclear how to collect diagnostics from all of the queries.

**Comment by lnicola** [comment]
We have a couple of diagnostics, can we close this?

**Comment by matklad** [comment]
We have diagnostics, and they are even somewhat designed, but I don’t like the design yet :)

**Comment by matklad** [comment]
Ok, I think our current state is not disgustingly horrible, so let's close this. Still could use some improvement though!
