### ISSUE TITLE
Code folding doesnt work with traits

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#5652]
![demo](https://user-images.githubusercontent.com/36276403/89182991-40afc980-d59f-11ea-9d06-5f2d7205d4c9.gif)

**Comment by Veetaha** [comment]
@lnicola than's for the quick PR.
I'd also report that impl blocks are not collapsible too...:
![image](https://user-images.githubusercontent.com/36276403/89187827-74422200-d5a6-11ea-89c8-d73bbedddb30.png)

**Comment by lnicola** [comment]
Nah, they work with the PR.

**Comment by Veetaha** [comment]
Wow, so cool!
