### ISSUE TITLE
Code folding doesn't work for traits

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#5654]
![demo](https://user-images.githubusercontent.com/36276403/89182991-40afc980-d59f-11ea-9d06-5f2d7205d4c9.gif)

**Comment by Veetaha** [comment]
Whoops

**Comment by Veetaha** [comment]
This is the duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/5652

**Comment by lnicola** [comment]
Oh, cool.
