### ISSUE TITLE
Document Symbols listed in reverse order within each scope

### ISSUE THREAD

**Issue by pubfnbar** [rust-analyzer/rust-analyzer#5655]
Using:
* [Sublime Text 3.2.2, Build 3211](https://www.sublimetext.com/3)
* [LSP 0.11.4](https://github.com/sublimelsp/LSP) (with only rust-analyzer client enabled)
* [Rust Enhanced 2.22.0](https://github.com/rust-lang/rust-enhanced)
* [rust-analyzer-mac e96bfd8](https://github.com/rust-analyzer/rust-analyzer/releases/download/2020-08-03/rust-analyzer-mac)

When you have a Rust Enhanced document open in Sublime Text, and you choose **Tools > Command Palette**, type _LSP: Document Symbols_ and hit Enter, the symbols are listed in reverse order within each scope like this:
![LSP Document Symbols - rust-analyzer](https://user-images.githubusercontent.com/66903996/89188803-d0597600-d5a7-11ea-83bb-074354409a31.png)

**Comment by lnicola** [comment]
Surprisingly, in Code they're in a different order:

![image](https://user-images.githubusercontent.com/308347/89190547-4bbc2700-d5aa-11ea-93fe-9eb487537a17.png)

**Comment by lnicola** [comment]
Document symbols are computed here: https://github.com/rust-analyzer/rust-analyzer/blob/be49547b446cba240f8f2a9592284e77d4a6896f/crates/rust-analyzer/src/handlers.rs#L245. The result of `file_structure` looks fine, but the conversion at https://github.com/rust-analyzer/rust-analyzer/blob/be49547b446cba240f8f2a9592284e77d4a6896f/crates/rust-analyzer/src/handlers.rs#L275 changes the ordering.

My guess is that it's worse in Sublime because it doesn't support hierarchical symbols and we take a different path at https://github.com/rust-analyzer/rust-analyzer/blob/be49547b446cba240f8f2a9592284e77d4a6896f/crates/rust-analyzer/src/handlers.rs#L288.

**Comment by magurotuna** [comment]
So helpful instructions. Though I'm new to this repo, can I work on it?

**Comment by lnicola** [comment]
Sure!

**Comment by kjeremy** [comment]
The display order should not depend on the server. I think this is a client-side sorting issue.

**Comment by lnicola** [comment]
I guess the clients could sort by range, but if two different ones don't do that, it's probably a common issue.

**Comment by kjeremy** [comment]
In vscode you have the option of position, name or category:

![Untitled](https://user-images.githubusercontent.com/4325700/89412471-2982f000-d6f5-11ea-9da5-1278dab82960.png)

**Comment by kjeremy** [comment]
I don't see anything about sorting the response in the [sublime lsp repo](https://github.com/sublimelsp/LSP/blob/bf7dcf79bbf7a21646348d17c0b81d2f8dbe85c7/plugin/symbols.py#L126-L161)

**Comment by magurotuna** [comment]
I've looked into it as well.

Firstly, it seems that language server protocol doesn't say about the order in responses of `DocumentSymbols`.
[Here is LSP Specification](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol)

Actually, rust-analyzer's server returns a response like this:

<details>
<summary>click here to see the full json response</summary>
<pre>
<code>
```json
[
    {
        "deprecated": false,
        "detail": "fn()",
        "kind": 12,
        "name": "main",
        "range": {
            "end": {
                "character": 1,
                "line": 16
            },
            "start": {
                "character": 0,
                "line": 14
            }
        },
        "selectionRange": {
            "end": {
                "character": 7,
                "line": 14
            },
            "start": {
                "character": 3,
                "line": 14
            }
        },
        "tags": []
    },
    {
        "children": [
            {
                "deprecated": false,
                "detail": "fn()",
                "kind": 12,
                "name": "b4",
                "range": {
                    "end": {
                        "character": 14,
                        "line": 11
                    },
                    "start": {
                        "character": 4,
                        "line": 11
                    }
                },
                "selectionRange": {
                    "end": {
                        "character": 9,
                        "line": 11
                    },
                    "start": {
                        "character": 7,
                        "line": 11
                    }
                },
                "tags": []
            },
            {
                "deprecated": false,
                "detail": "fn()",
                "kind": 12,
                "name": "b3",
                "range": {
                    "end": {
                        "character": 14,
                        "line": 10
                    },
                    "start": {
                        "character": 4,
                        "line": 10
                    }
                },
                "selectionRange": {
                    "end": {
                        "character": 9,
                        "line": 10
                    },
                    "start": {
                        "character": 7,
                        "line": 10
                    }
                },
                "tags": []
            },
            {
                "deprecated": false,
                "detail": "u8",
                "kind": 14,
                "name": "B2",
                "range": {
                    "end": {
                        "character": 21,
                        "line": 8
                    },
                    "start": {
                        "character": 4,
                        "line": 8
                    }
                },
                "selectionRange": {
                    "end": {
                        "character": 12,
                        "line": 8
                    },
                    "start": {
                        "character": 10,
                        "line": 8
                    }
                },
                "tags": []
            }
        ],
        "deprecated": false,
        "kind": 19,
        "name": "impl B",
        "range": {
            "end": {
                "character": 1,
                "line": 12
            },
            "start": {
                "character": 0,
                "line": 7
            }
        },
        "selectionRange": {
            "end": {
                "character": 6,
                "line": 7
            },
            "start": {
                "character": 5,
                "line": 7
            }
        },
        "tags": []
    },
    {
        "deprecated": false,
        "kind": 23,
        "name": "B",
        "range": {
            "end": {
                "character": 9,
                "line": 5
            },
            "start": {
                "character": 0,
                "line": 5
            }
        },
        "selectionRange": {
            "end": {
                "character": 8,
                "line": 5
            },
            "start": {
                "character": 7,
                "line": 5
            }
        },
        "tags": []
    },
    {
        "children": [
            {
                "deprecated": false,
                "kind": 23,
                "name": "A2",
                "range": {
                    "end": {
                        "character": 14,
                        "line": 2
                    },
                    "start": {
                        "character": 4,
                        "line": 2
                    }
                },
                "selectionRange": {
                    "end": {
                        "character": 13,
                        "line": 2
                    },
                    "start": {
                        "character": 11,
                        "line": 2
                    }
                },
                "tags": []
            },
            {
                "deprecated": false,
                "kind": 23,
                "name": "A1",
                "range": {
                    "end": {
                        "character": 14,
                        "line": 1
                    },
                    "start": {
                        "character": 4,
                        "line": 1
                    }
                },
                "selectionRange": {
                    "end": {
                        "character": 13,
                        "line": 1
                    },
                    "start": {
                        "character": 11,
                        "line": 1
                    }
                },
                "tags": []
            }
        ],
        "deprecated": false,
        "kind": 2,
        "name": "a",
        "range": {
            "end": {
                "character": 1,
                "line": 3
            },
            "start": {
                "character": 0,
                "line": 0
            }
        },
        "selectionRange": {
            "end": {
                "character": 5,
                "line": 0
            },
            "start": {
                "character": 4,
                "line": 0
            }
        },
        "tags": []
    }
]
```

</code>
</pre>
</details>

This response has the symbols in the reverse order.

And as @kjeremy is pointing out, sublime lsp plugin does nothing about re-ordering symbols. So sublime's LSP outputs them in the same order as the response given by rust-analyzer.
On the other hand, VSCode gives us options to sort symbols in various ways (the default is `sort by category` in my environment).

I think there are  two ways:

1. Fix rust-analyzer to return `DocumentSymbols` in reverse order, although the protocol doesn't require that.
2. Create a new issue to the sublime's lsp repo, saying that sorting options are needed.

Which way should be taken? Or any other way?

**Comment by lnicola** [comment]
I think we should try to return the symbols in a reasonable order, probably by position. But note that for clients with hierarchical symbols support it's not enough to reverse the results.

**Comment by pubfnbar** [comment]
If you use the Sublime Text's native _Goto Symbol_ feature via its menu bar item **Goto > Goto Symbol...** you get the document symbols listed in the following order:
![Goto Symbol - Sublime Text](https://user-images.githubusercontent.com/66903996/89418318-9370b900-d738-11ea-8fd3-8acd1c6051d0.png)

**Comment by magurotuna** [comment]
@lnicola 
Thanks for the advice!
OK, I'll try to fix rust-analyzer to return the symbols sorted by position.

**Comment by kjeremy** [comment]
I guess we can sort them ourselves if we really want to but @Inicola is right wrt hierarchical symbols (and sublime's lsp client supports hierarchical symbols) so you'll still have a problem.

Either way I think an issue should be filed against the LSP client since this is a client-side issue and the server is returning correct results.

**Comment by magurotuna** [comment]
Hmm..... I'm kind of confused.

Simplified current response from rust-analyzer looks like:

```json
[
  {
    "detail": "fn()",
    "kind": 12,
    "name": "main"
  },
  {
    "kind": 23,
    "name": "B"
  },
  {
    "children": [
      {
        "detail": "fn()",
        "kind": 12,
        "name": "b4"
      },
      {
        "detail": "fn()",
        "kind": 12,
        "name": "b3"
      },
      {
        "detail": "u8",
        "kind": 14,
        "name": "B2"
      }
    ],
    "kind": 19,
    "name": "impl B"
  },
  {
    "children": [
      {
        "kind": 23,
        "name": "A2"
      },
      {
        "kind": 23,
        "name": "A1"
      }
    ],
    "kind": 2,
    "name": "a"
  }
]
```

This order corresponds to the shown results in sublime.
Now I will try to sort them in a reasonable order. For example, if we reverse them for each hierarchy, then the result will be like:

```json
[
  {
    "kind": 2,
    "name": "a",
    "children": [
      {
        "kind": 23,
        "name": "A1"
      },
      {
        "kind": 23,
        "name": "A2"
      }
    ]
  },
  {
    "kind": 23,
    "name": "B"
  },
  {
    "kind": 19,
    "name": "impl B",
    "children": [
      {
        "kind": 14,
        "name": "B2",
        "detail": "u8"
      },
      {
        "kind": 12,
        "name": "b3",
        "detail": "fn()"
      },
      {
        "kind": 12,
        "name": "b4",
        "detail": "fn()"
      }
    ]
  },
  {
    "detail": "fn()",
    "kind": 12,
    "name": "main"
  }
]
```

It matches well with the actual code. So it could be said as  "reasonable" order, I guess.

Are my understanding and idea right?
