### ISSUE TITLE
Feature idea: Macro expansion preview

### ISSUE THREAD

**Issue by brundonsmith** [rust-analyzer/rust-analyzer#5665]
Hi! I offer this as just a suggestion. It may not be worth the level of effort required and I'm sure y'all have plenty of other stuff on your plates, but it would be pretty awesome.

I recently found this CLI tool that previews what your code will look like after macros have been expanded: https://github.com/dtolnay/cargo-expand

It seems like it would be incredibly useful when developing a macro to be able to see this in-editor somehow. Maybe macro invocations expose a little button like tests do, and you can just "unfold" that bit of code into the code it would generate. Perhaps the abovementioned crate could even be used, to minimize how much effort would be required on the RA side.

Either way, thanks for the great work!

**Comment by kjeremy** [comment]
Does this fit your need? https://rust-analyzer.github.io/manual.html#expand-macro-recursively

**Comment by brundonsmith** [comment]
I didn't know about that, that's perfect! Sorry for wasting your time 🙂

**Comment by kjeremy** [comment]
No worries. Perfect!
