### ISSUE TITLE
media assets

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#567]
Secret issue to host documentation assets, like images, gifs and videos.

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/51383996-0bae6400-1b2c-11e9-82ed-495efd21f93d.png)

**Comment by matklad** [comment]
![rls_debug](https://user-images.githubusercontent.com/1711539/51384036-254fab80-1b2c-11e9-824d-95f9a6e9cf4f.gif)

**Comment by matklad** [comment]
![ferrous-logo](https://user-images.githubusercontent.com/1711539/58105231-cf306900-7bee-11e9-83d8-9f1102e59d29.png)

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/60521147-60672500-9cef-11e9-9c0b-4b757d2e4ef7.png)

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/60546857-e5b9fc00-9d26-11e9-8709-3d2d77915e50.png)

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/60578228-86410800-9d89-11e9-83b5-aed7a8c9bce5.png)

**Comment by matklad** [comment]
![logo min](https://user-images.githubusercontent.com/1711539/72442551-07537000-37ad-11ea-8ee3-7c5f0913a3f5.png)

**Comment by matklad** [comment]
![logo-small](https://user-images.githubusercontent.com/1711539/72442624-20f4b780-37ad-11ea-9585-9d9fced1b417.png)

**Comment by matklad** [comment]
https://gist.github.com/matklad/49c01e8f48a984f3f3be4f525267892d

**Comment by Veetaha** [comment]
![download-now-info-message](https://user-images.githubusercontent.com/36276403/74103174-a40df100-4b52-11ea-81f4-372c70797924.png)

**Comment by Veetaha** [comment]
![image](https://user-images.githubusercontent.com/36276403/74108225-c0c11d80-4b80-11ea-9b2a-0a43f09e29af.png)

**Comment by Veetaha** [comment]
![image](https://user-images.githubusercontent.com/36276403/74611090-92ec5380-5101-11ea-8a41-598f51f3f3e3.png)

**Comment by Veetaha** [comment]
![image](https://user-images.githubusercontent.com/36276403/78043783-7425e180-737c-11ea-8653-b02b773c5aa1.png)

**Comment by Veetaha** [comment]
![image](https://user-images.githubusercontent.com/36276403/78225773-6636a480-74d3-11ea-9d9f-1c9d42da03b0.png)
