### ISSUE TITLE
Suppress inlay hints on lines with syntax errors

### ISSUE THREAD

**Issue by eminence** [rust-analyzer/rust-analyzer#5670]
Starting with code like this:

```rust
use std::sync::mpsc::{Sender, channel};

fn main() {
    
    let (tx, rx) = channel();

}
```

Which I see in VSCode as this:

![image](https://user-images.githubusercontent.com/402454/89442404-cad16c80-d71c-11ea-84df-4336bb616adb.png)

Most of the time, I can provide enough type hints in other parts of the code to let rust figure out this unknown type, but not always.  If I need to explicitly annotate the types, I often the mistake of writing code like this:

```rust
    let (tx: Sender<u8>, rx) = channel();
```

This is a syntax error, but rust-analyzer still gives inlay type hints to VSCode to display:

![image](https://user-images.githubusercontent.com/402454/89442871-872b3280-d71d-11ea-986b-53f600cc91ef.png)

The result is quite hard to read and parse (for my human brain).  Do you think it would make sense for rust-analyzer to suppress inlay type hints on lines with syntax errors?

**Comment by Veykril** [comment]
I don't think we can do much here, surpressing the hints for lines with syntax errors is gonna be quite difficult and I don't really see a feasible way for us to implement this without degrading general user experience in other places.
