### ISSUE TITLE
AtomicU32 completions are squished

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#5673]
I'm seeing things like this today:
![image](https://user-images.githubusercontent.com/4325700/89479697-6b498000-d761-11ea-9996-5574e6af63a1.png)

**Comment by lnicola** [comment]
Same as https://github.com/rust-analyzer/rust-analyzer/issues/4665?

**Comment by kjeremy** [comment]
Go-to definition for `fetch_add` also brings me to a bogus location which implies that the function is generated via a macro so it could be the same.

**Comment by lnicola** [comment]
It is: https://doc.rust-lang.org/src/core/sync/atomic.rs.html#1229-1231.
