### ISSUE TITLE
Sometimes RA is detecting clone as unsafe

### ISSUE THREAD

**Issue by nomad010** [rust-analyzer/rust-analyzer#5677]
Every so often, Rust Analyzer detects clone as need an unsafe function or block. The problematic clones are always in a test, or at least I haven't seen them outside a test. The items that I'm cloning are u64s but I'm not sure if that has any bearing to the issue. Saving the document so RA runs again does not cause the error to go away, but doing a cargo clean and reopening VS Code does fix it.

This has been repro'ing for at least a few months I think.

**Comment by ruabmbua** [comment]
Can you create a minimal reproducible example? This sounds interesting, I have never seen anything like that.

**Comment by matklad** [comment]
closing, it's impossible to move forward without a way to reproduce.
