### ISSUE TITLE
Analysis doesn't work in build.rs

### ISSUE THREAD

**Issue by bugproof** [rust-analyzer/rust-analyzer#5683]
Rust-analyzer version: v0.2.266
VSCode version: 1.47.3
OS: Windows 10 x64
-

![image](https://user-images.githubusercontent.com/3116731/89646682-84b30f00-d8bc-11ea-9f87-18f7b9665eac.png)
![image](https://user-images.githubusercontent.com/3116731/89646696-8b418680-d8bc-11ea-9335-e51a8019df07.png)

In comparison with IntelliJ Rust
-
![image](https://user-images.githubusercontent.com/3116731/89646837-ccd23180-d8bc-11ea-8f6b-76dd073c348e.png)

As you can see on the screenshots above it's a pretty drastic difference in developer experience.

**Comment by flodiebold** [comment]
I'm guessing that's in a `build.rs` file? We don't have support for that yet.

**Comment by matklad** [comment]
Hm, not sure what's going on here: we **do** have support for build.rs:

![image](https://user-images.githubusercontent.com/1711539/90012765-4f376880-dca4-11ea-84b8-452cde714f9d.png)

let me check if we listen to *creation* of build.rs...

**Comment by matklad** [comment]
yup, we also re-query cargo metadata when adding a build.rs. @bugproof do you have any idea what might be a way to reproduce this? Does it happen for all your projects?

**Comment by bugproof** [comment]
@matklad I'm on windows. Created basic rust library with `cargo new --lib`, added `build = "build.rs"` to cargo.toml, added `build.rs`.

Happens for all projects.

**Comment by flodiebold** [comment]
Seems this is fixed.
