### ISSUE TITLE
Type inference not working when default type parameter is used in trait

### ISSUE THREAD

**Issue by ruabmbua** [rust-analyzer/rust-analyzer#5685]
Example:

```rust
struct A;

trait Op<RHS=Self> {
    type Output;

    fn do_op(self, rhs: RHS) -> Self::Output;
}

impl Op for A {
    type Output = bool;

    fn do_op(self, rhs: Self) -> Self::Output {
        true
    }
}

impl std::ops::Sub for A {
    type Output = bool;
    fn sub(self, rhs: Self) -> Self::Output {
        true
    }
}

fn test() {
    let x = A;
    let y = A;
    let r = x.do_op(y);

    let x = A;
    let y = A;
    let r = x - y;
}

```

In both cases the type for variable r is not inferred correctly. It resolves to e.g. *Op::Output<A, A>*.

As soon as the impl block specifies the RHS type parameter, everything works just fine:

```rust
struct A;

trait Op<RHS=Self> {
    type Output;

    fn do_op(self, rhs: RHS) -> Self::Output;
}

impl Op<Self> for A {
    type Output = bool;

    fn do_op(self, rhs: Self) -> Self::Output {
        true
    }
}

impl std::ops::Sub<Self> for A {
    type Output = bool;
    fn sub(self, rhs: Self) -> Self::Output {
        true
    }
}

fn test() {
    let x = A;
    let y = A;
    let r = x.do_op(y);

    let x = A;
    let y = A;
    let r = x - y;
}

```

Both cases infer r to be of type bool.

Edit:

Type inference for overloaded operators in *std::ops* does not actually work in RA. I have a branch for that, which is currently pretty useless. If we can fix the default type parameter problem in traits, it will work just fine (I guess).

**Comment by lnicola** [comment]
Triage: this still happens.

**Comment by ruabmbua** [comment]
Is anyone aware, if this is an issue with chalk? If that is the case, should we create an issue in the chalk repository?

**Comment by flodiebold** [comment]
No, if this is indeed related to type parameter defaults then it has nothing to do with Chalk. I haven't looked into it in detail so far though.
