### ISSUE TITLE
Some generated docs include non-AsciiDoc-compatible content

### ISSUE THREAD

**Issue by mkantor** [rust-analyzer/rust-analyzer#5702]
The pipelines for codegen extract text from Rust doc comments and inject it into AsciiDoc contexts (at least [assists](https://github.com/rust-analyzer/rust-analyzer/blob/2020-08-10/xtask/src/codegen/gen_assists_docs.rs#L107) and [features](https://github.com/rust-analyzer/rust-analyzer/blob/2020-08-10/xtask/src/codegen/gen_feature_docs.rs#L73) do this, maybe others too).

These Rust doc comments are written in Markdown (unsurprisingly). Markdown is similar to AsciiDoc but isn't a strict subset of it (even assuming [AsciiDoctor's syntax extensions](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#markdown-compatibility)).

The result is some funky output in the manual when the doc comments contain non-AsciiDoc syntax. For example, the link to De Morgan’s law in [the assists section of the manual](https://rust-analyzer.github.io/manual.html#assists-code-actions) doesn't become nice HTML:

![Messed up link](https://user-images.githubusercontent.com/35091/89812243-ac8cb780-daf4-11ea-8cef-0c117ef722ed.png)

**Comment by mkantor** [comment]
Some ways this could be addressed:

1. **Update the codegen pipelines to explicitly convert from Markdown => AsciiDoc syntax.**

   I could't find any Rust libraries that can do this after a brief search. Something like [Pandoc](https://pandoc.org/) or [kramdown-asciidoc](https://github.com/asciidoctor/kramdown-asciidoc) could work if shelling out is okay. If not, it wouldn't be too hard to write a Rust function that can handle basic cases like links.

1. **Replace AsciiDoc with Markdown (in the codegen output).**

   Probably a lot of effort, and I assume there are legit reasons AsciiDoc was chosen in the first place. This would require changes in [the rust-analyzer.github.io repository](https://github.com/rust-analyzer/rust-analyzer.github.io) as well.

1. **Use AsciiDoc syntax in these doc comments.**

   But then they'll look weird in rustdoc, IDE tooltips, etc.

1. **Restrict these doc comments to the common subset of Markdown and AsciiDoc.**

   Easy to do but hard to maintain over time. Also implies that the manual can never include links and such in these sections, which is a bummer.

None of those are obvious winners to me, otherwise I'd send a pull request. :wink:

**Comment by matklad** [comment]
That's a bug in the comment -- comments should use AsciiDoc, filed #5720
