### ISSUE TITLE
import sorting should use a natural sort

### ISSUE THREAD

**Issue by jgarvin** [rust-analyzer/rust-analyzer#5714]
Current behavior if you ask analyzer to add uses for each type for you:

`use std::num::{NonZeroU16, NonZeroU8, NonZeroU32, NonZeroU64};`

This would be slightly nicer:

`use std::num::{NonZeroU8, NonZeroU16, NonZeroU32, NonZeroU64};`

**Comment by bjorn3** [comment]
Rust-analyzer should use the same order as rustfmt in my opinion. This means alphabetic instead of natural.

**Comment by iago-lito** [comment]
Agreed. In any case, if Rust-analyzer outputs something different than rustfmt, then rustfmt wipes the difference anyway on the next fist pass. So maybe this is a feature to ask at [`rustfmt`](https://github.com/rust-lang/rustfmt) instead?

**Comment by lnicola** [comment]
I think this is out of scope for now, but you can file this as a `rustfmt` feature request.

**Comment by jgarvin** [comment]
Filed w/ rustfmt: https://github.com/rust-lang/rustfmt/issues/4381
