### ISSUE TITLE
Fold consecutive lines of `mod …;`

### ISSUE THREAD

**Issue by killercup** [rust-analyzer/rust-analyzer#572]
Given a source file that starts like this:

https://github.com/rust-analyzer/rust-analyzer/blob/7e84440e25e19529e4ff8a66e521d1b06349c6ec/crates/ra_syntax/src/lib.rs#L20-L39

I would like to fold the `mod` block and ideally only see the `pub mod` items.

**Comment by kjeremy** [comment]
This would be a good first issue for someone to pick up.
