### ISSUE TITLE
[Feature Request] Install from crates.io

### ISSUE THREAD

**Issue by adrianisuru** [rust-analyzer/rust-analyzer#5736]
I think it would be great if rust-analyzer could be installed from crates.io via a 
```
$ cargo install rust-analyzer
``` 
There is something [here](https://crates.io/crates/rust-analyzer) but it is vastly outdated.

@matklad your thoughts on this?

**Comment by matklad** [comment]
We won't implement this: between `rustup component add rust-analyzer-previrew`, getting binary release from GitHub and `cargo install --git https://github.com/rust-analyzer/rust-analyzer`, the cost-benefit ratio of publishing to crates.io is bad.
