### ISSUE TITLE
VSCode Plugin: Rust Analyzer + Main?

### ISSUE THREAD

**Issue by indo-dev-0** [rust-analyzer/rust-analyzer#5764]
As a new user. it is not clear how the Rust Analyzer extension interacts with the main VSCode Rust extension.  I went looking in the Rust VSCode extension and found a setting to use Rust Analyzer, so I enabled it assuming that Rust Analyzer was a beta feature.  Both plugins should probably be updated to reflect this.

**Comment by bjorn3** [comment]
We are currently merging the rust-analyzer extension into the Rust extension. For now the rust-analyzer extension works better.

**Comment by flodiebold** [comment]
It's not recommended to run both extensions. We're now showing a warning message about this.
