### ISSUE TITLE
Is possible to set a output dir?

### ISSUE THREAD

**Issue by AurevoirXavier** [rust-analyzer/rust-analyzer#5767]
Pass the `CARGO_OUTPUT_DIR` to rust-analyzer in vscode.

**Comment by bjorn3** [comment]
You could start vscode with that env var set.

**Comment by AurevoirXavier** [comment]
Does it work in remote ssh?

**Comment by bjorn3** [comment]
The remote ssh extension doesn't seem to have an option to set env vars.

**Comment by lnicola** [comment]
You can use the `SetEnv` SSH option on the client side, but it might already run one of the shell config files on the remote side.
