### ISSUE TITLE
Hover details show unexpected crate name/path

### ISSUE THREAD

**Issue by samhedin** [rust-analyzer/rust-analyzer#5771]
Hey! I hope that this hasn't been posted before. I searched and could not find anything.

I expect the first line of the hover details to show `std::collections::HashMap`. Instead, it shows `std::collections::hash::map`. 
![pic](https://i.imgur.com/YJ1AUbZ.png)

**Comment by bjorn3** [comment]
`std::collections::hash::map::HashMap` is the full path of `HashMap`. `std::collections::HashMap` is just a re-export.

https://github.com/rust-lang/rust/blob/de32266a1780aa4ef748ce7f6200a1554fad0aca/library/std/src/collections/hash/map.rs#L200

https://github.com/rust-lang/rust/blob/de32266a1780aa4ef748ce7f6200a1554fad0aca/library/std/src/collections/mod.rs#L425

**Comment by samhedin** [comment]
I see - I figured that something like this would be the case. Is there a way to get the re-exported path instead?

**Comment by bjorn3** [comment]
Rustc has the same problem with error messages: https://github.com/rust-lang/rust/issues/21934

**Comment by samhedin** [comment]
I see. I understand that this isn't a priority for my people. I'll keep an eye on it though. Thank you :100:
