### ISSUE TITLE
In-project vs external semantic highlighting

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#5772]
Xcode has a feature where it can highlight symbols from inside the current project differently to those from outside of it. The default colour schemes highlight all in-project symbols in teal, while external symbols get purple. I found this interesting, because, although Xcode has the ability to highlight e.g. variables and types differently, instead it was decided to make ‘where is this symbol from?’ more visible than ‘is this a function call, variable, or type?’.

I once read an article (I tried to find it, but failed) where the author says they find this useful, because when they find something wrong with their code, they know whether it’s more likely that their usage of an API is wrong, or if the actual implementation is incorrect. I don’t remember the specifics of the argument, but this sounds interesting to me. I’ve never used Xcode myself, though.

**Comment by arzg** [comment]
I’d be interested in trying to implement this. Could anyone give me any pointers as to how I could approach this? Here’s what I was thinking of:

I was been digging through `crates/hir/src/lib.rs` to see if anything there might help me, and had the idea of adding a `HasCrate` trait for `hir::Struct`, `hir::Function`, etc that returns a `hir::Crate`. Then this can be accessed from `ide::syntax_highlighting` and be compared with the crate of the file being highlighted. How can I figure out what crate the file being highlighted is in?

**Comment by Veykril** [comment]
The simplest way is probably to just construct a `SemanticsScope` with `Semantics::scope` of the syntaxnode thats being highlight and then calling `SemanticsScope::crate` on it to get the crate.
