### ISSUE TITLE
Parameterized std types like Option, Vec, Result inferred to be "{unknown}"

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [rust-analyzer/rust-analyzer#5779]
To reproduce, hover over "_o" in the following snippet:
```rust
fn main() {
    let _o: Option<i8> = None;
}
```

Expected result: `Option<i8>`
Actual result: `{unknown}`

rust-analyzer version: 2020-08-10 (7a03f05)

**Comment by kjeremy** [comment]
I can't reproduce.

**Comment by flodiebold** [comment]
Do any standard library types work? Probably the standard library source isn't being found.

**Comment by Vlad-Shcherbina** [comment]
Indeed, it seems the standard library is not picked up at all. For instance, competions for `std::` don't work.

How do I troubleshoot this sort of stuff?

I have recent nightly installed with `rustup`, with the `rust-src` component. Just in case it was messed up in one of the releases, I tried updating to the most recent nightly (rustc 1.47.0-nightly (7e6d6e5f5 2020-08-16)), still have the same problem.

**Comment by bjorn3** [comment]
Do you have nightly set as default for the project? `rustup override set nightly`

**Comment by Vlad-Shcherbina** [comment]
Nightly is the only toolchain I have installed.
```
> rustup override set nightly                                                                             
info: using existing install for 'nightly-x86_64-pc-windows-msvc'
info: override toolchain for 'C:\temp\rust_playground\hello_world' set to 'nightly-x86_64-pc-windows-msvc'

  nightly-x86_64-pc-windows-msvc unchanged - rustc 1.47.0-nightly (7e6d6e5f5 2020-08-16)
```

The problem persists.

**Comment by lnicola** [comment]
Do you have environment variables like `RUST_SRC_PATH` set?

**Comment by Vlad-Shcherbina** [comment]
Thank you all for the leading questions!

The value of `RUST_SRC_PATH` was
```
C:\Users\username\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src
```

This path was invalid. The actual directory structure was like this:
```
C:\Users\username\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\
  Cargo.lock
  library\
    alloc\
    backtrace\
    core\
    ...
```

`rustup uninstall` didn't remove this environment variable.
It didn't occur to me to try removing it manually without reinstalling rust.

Then I removed the variable and installed rust.
`RUST_SRC_PATH` was not set and everything worked as supposed.

I don't know exactly what happened, but probably something
(rustup, some other tool, or me following some ancient instructions)
set this variable, and it was not updated to keep up with the
https://github.com/rust-lang/rust/commit/2c31b45ae878b821975c4ebd94cc1e49f6073fd0 .

**Comment by kjeremy** [comment]
Do we print that out anywhere? If not maybe we should...

**Comment by flodiebold** [comment]
I think we do log an error message about it?
