### ISSUE TITLE
Server crashes when receiving a negative number for textDocument/hover

### ISSUE THREAD

**Issue by w0rp** [rust-analyzer/rust-analyzer#5789]
I found this issue while fixing an issue in ALE, where ALE was sometimes sending `-1` for the column index. I've fixed the bug in ALE, and it's worth reporting the issue which crashed the server here. A log with the message that triggered the error can be found here: https://github.com/dense-analysis/ale/issues/3294#issuecomment-675161271

A snippet of the output from the logs is as follows.

```
thread 'main' panicked at 'Invalid request
Method: textDocument/hover
 error: invalid value: integer `-1`, expected u64', /home/rick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
stack backtrace:
```

This is the message that caused that problem.

```
{"method":"textDocument/hover","jsonrpc":"2.0","id":2,"params":{"textDocument":{"uri":"file:///home/rick/Projects/nushell/crates/nu-cli/src/commands/str_/pad.rs"},"position":{"character":-1,"line":1}}}
```

The server should either return an error and handle numbers possibly being negative gracefully, or disregard negative numbers and treat them as `0`.

**Comment by flodiebold** [comment]
In my opinion, there's not much use in guarding against misbehaving clients.

**Comment by matklad** [comment]
Yup, this is expected behavior -- we intentionally hard-crash for misbehaving clients.

**Comment by matklad** [comment]
To be clear, in theory this *might* be the bug where we misinterpret the spec, but I think in this case it's pretty clear that the column number shouldn't be negative.

**Comment by w0rp** [comment]
It's worth returning an error in response. It's the same as returning a 4xx error in an HTTP response, instead of 500.

**Comment by matklad** [comment]
I disagree, I think in the context of LSP hard-crash is a better behavior. Unlike the web, this is a closed system (the same operator is in control of both the server and the client). Hard crashing forces one to actually fix client and server.
