### ISSUE TITLE
cannot jump to code generated by tonic grpc

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#5799]
Hi, I found it's impossible to jump to code generated by tonic, is it unimplemented ?

**Comment by bjorn3** [comment]
Did you enable `rust-analyzer.cargo.loadOutDirsFromCheck`?

**Comment by GopherJ** [comment]
hi @bjorn3 I just enabled it but it still doesn't work, I'm using coc-rust-analyzer + coc.nvim + rust-analyzer

**Comment by Ameobea** [comment]
Fwiw enabling `rust-analyzer.cargo.loadOutDirsFromCheck` fixed this issue for me in VS Code

**Comment by lnicola** [comment]
Are you using nightly? If so, can you try with a new rust-analyzer?

**Comment by Ameobea** [comment]
@lnicola -

> Are you using nightly?

Yes, I'm currently using `rustc 1.49.0-nightly (a1dfd2490 2020-10-05)`

> If so, can you try with a new rust-analyzer?

I'm using the latest master, built fresh a couple of hours ago with `cargo xtask install`

> Also, how did you enable the setting?

I just added this line to my VS Code `settings.json`:

```json
"rust-analyzer.cargo.loadOutDirsFromCheck": true,
```

**Comment by lnicola** [comment]
Sorry, I was asking @GopherJ  since for you it already works.

**Comment by GopherJ** [comment]
Hi all, thanks for your replies, I confirm that I'm using nightly but I'm not using VSCode, I use vim + coc.nvim + coc-rust-analyzer

**Comment by lnicola** [comment]
It's hard to tell, but if you're using proc macros with a nightly `rustc` newer than 1.45, you'll need a `rust-analyzer` that includes #5651, otherwise it will crash.

It's unlikely, but it could also be a `coc-rust-analyzer` issue.

**Comment by matklad** [comment]
needs a minimal reproducible examble to become actionable. THe action would be to check with vs code if i works.

**Comment by GopherJ** [comment]
Hi @matklad thanks for your reply, I should have done it :) sorry.

I confirm it's more a pb on coc.nvim + coc-rust-analyzer because it works perfectly in Vscode but not with coc.nvim + coc-rust-analyzer

**Comment by lnicola** [comment]
Closing for now, we can reopen or file a new bug if we're doing anything wrong.

**Comment by lnicola** [comment]
CC https://github.com/rust-analyzer/rust-analyzer/issues/3767 -- I think?

**Comment by lgln** [comment]
I have the same issuse, is there some progress?

**Comment by flodiebold** [comment]
@lgln can you give a minimal reproduction of the issue?

**Comment by lgln** [comment]
`
use hello_world::greeter_client::GreeterClient;
use hello_world::HelloRequest;

pub mod hello_world {
    tonic::include_proto!("helloworld");
}
`
i want to find definition of "GreeterClient" in line 1, the cursor just jump to "tonic::include_proto!(" in line 5

my rust-analyzer is v0.2.583, my config in settings.json:

`
"rust-analyzer.cargo.runBuildScripts": true,
"rust-analyzer.lruCapacity": 1024,
"rust-analyzer.procMacro.enable": true,
`

**Comment by lgln** [comment]
```
use hello_world::greeter_client::GreeterClient;
use hello_world::HelloRequest;

pub mod hello_world {
tonic::include_proto!("helloworld");
}
```

i want to find definition of "GreeterClient" in line 1, the cursor just jump to "tonic::include_proto!(" in line 5

my rust-analyzer is v0.2.583, my config in settings.json:

```
"rust-analyzer.cargo.runBuildScripts": true, 
"rust-analyzer.lruCapacity": 1024, 
"rust-analyzer.procMacro.enable": true,
```

**Comment by shikhar** [comment]
It is easy to repro with https://github.com/shikhar/bazel-tonic/tree/4a27fbf7fe15a26804a3eb5eb3f7b62dafa9fba4

Generated code is included in `lib.rs`, and symbols from generated code are used in `client.rs` and `server.rs`. Trying to jump to definition from those symbols takes you to the include in `lib.rs`, instead of the generated source file.

P.S. This is with the `2021-07-19` release, with the latest `2021-07-26` release it's more broken, opening a separate issue for that and will link here

**Comment by flodiebold** [comment]
This seems like a duplicate of #3767.
