### ISSUE TITLE
rust-analyzer-preview from rustup nightly is out of date

### ISSUE THREAD

**Issue by bstaletic** [rust-analyzer/rust-analyzer#5802]
Today I tried to upgrade to nightly-2020-08-18 and, while it "worked", rustup installed rust-analyzer with `c9c518e` as the latest one, which corresponds to tag 2020-07-20. From there I have encountered two problems, compared to nightly-2020-07-08.

1. https://github.com/rust-analyzer/rust-analyzer/pull/5467 is missing
2. YCM is installing all rustup components with `third_party/rust-analyzer/` as the root. On the latest nightly, rust-analyzer doesn't find rust-src even though it is installed in the same root. This, however, works on today's HEAD (d21d5e4).

To be fair, I am not sure how rustup nightlies are updated, so I might be complaining to the wrong people.

**Comment by bjorn3** [comment]
https://github.com/rust-lang/rust/pull/75631 updated rust-analyzer. It will be available with the next nightly.

**Comment by matklad** [comment]
Yup, the version in rust-up are not fully up-to-date yet, the recommended way to get ra is still from GitHub release. Hopefully, things will be better since today, as (:crossed_fingers:) we fixed the last couple of build-related bugs.

**Comment by bstaletic** [comment]
Thanks for the update!
