### ISSUE TITLE
Document "*.mutable" trick in manual.adoc

### ISSUE THREAD

**Issue by sploders101** [rust-analyzer/rust-analyzer#5803]
I love the level of information rust-analyzer presents up-front, but it can also be a little overwhelming. I've found configuration options to turn most of them off, but I can't seem to find one for turning off variable links. It's extremely distracting and makes my code a lot harder to read when every variable in the file is underlined. I would *really* appreciate an option to turn this off, because it's kind of a dealbreaker for me. This one thing makes my code **harder** to read *with* rust-analyzer than without it.

Apart from that though, I wanted to say you guys have done a **phenomenal** job. It's just a shame that I have to disable *all* of it due to that one gripe.

If this option gets added, I will most certainly start using it again, because every other aspect I've seen is great! Thanks for all your hard work!

**Comment by bjorn3** [comment]
The underlining of variables is only for mutable variables. You can use the following to disable it:

```jsonc
{
    "editor.semanticTokenColorCustomizations": {
        "rules": {
            "*.mutable": {
                "fontStyle": "", // underline is the default
            },
        }
    },
}

**Comment by sploders101** [comment]
Thank you! I still think this should be addressed in rust-analyzer's preferences, since that's where anyone encountering the issue is likely to look first, but this workaround works great, thanks!

**Comment by matklad** [comment]
I don' think this should be a preference, but documenting in in the manual.adoc might be useful!
