### ISSUE TITLE
When a crate has `src` in its path, rust-analyzer panics

### ISSUE THREAD

**Issue by msalib** [rust-analyzer/rust-analyzer#5833]
For example, if I have a crate called `foo` and I place it in `/home/msalib/src/bar/foo` with files likes ``/home/msalib/src/bar/foo/Cargo.toml` and ``/home/msalib/src/bar/foo/src/lib.rs`, rust-analyzer will panic.

**Comment by bjorn3** [comment]
What is the panic message?

**Comment by lnicola** [comment]
Triage: can't reproduce.

@msalib does this still happen?

**Comment by lnicola** [comment]
Closing for now. Feel free to reopen if you run into this again.
