### ISSUE TITLE
Add CodeLens for references

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#5836]
Currently, the only CodeLenses that rust-analyzer shows are `Run` above `fn main()`, `Run Test | Debug` above tests, and `n implementations` above struct, enum, union and trait definitions. A useful addition to this would be a CodeLens of the form `n references` above definitions where this makes sense. When clicked, this CodeLens would show all the references to the symbol the definition defines.

Here’s a list of some possible definitions above which the references CodeLens could be shown:

- structs
- enums
- unions
- traits
- free functions
- functions in impl blocks
- functions in trait definitions

It _might_ be a good idea to show the CodeLens above enum variant definitions as well as struct and union field definitions, but that might be a bit much.

**Comment by vsrs** [comment]
I'm working on it.
