### ISSUE TITLE
Feature: When a type can't be found, assume only type with the same name 

### ISSUE THREAD

**Issue by jgarvin** [rust-analyzer/rust-analyzer#5844]
I'm working on a project with several crates in a shared workspace. Some of these crates contain proc macros with code like:

```
let output = quote! {
    let world = crate::world::World::new();
    // ....
}
```

Without some kind of fuzzy matching, I don't believe analyzer will ever be able to find the definition of `World`, even if it perfectly implemented every language feature and replaced the `rustc` parser, because what it precisely refers to depends on the crate the macro is invoked in. When a type can't be found, I suggest the following search order:

1. Current crate.
2. Other crates in the same workspace.
3. Dependencies of current crate.
4. Dependencies of other crates in the same workspace.

While imperfect, in practice most type names are actually fairly unique. Without some sort of feature like this, in these kinds of cases ironically the experience using analyzer isn't as good as a traditional tags program would be. Rust analyzer is _too_ smart :)

In the case there are multiple possibilities, tag programs typically return all of them and let the user choose. I don't know if this is possible with LSP but it would be nice.

To be clear this would only be the behavior if a precise lookup fails. Precise lookups when possible are still always preferred.

**Comment by flodiebold** [comment]
I don't think this is possible to do in a reasonable way. The situations where it would actually be useful are very few, and I suspect the situations where it would lead to bad behavior would be much more frequent. It's also worth noting that we analyze the expanded macro and provide completions based on that, when it expands to actual code; we would have to somehow detect when the macro argument can somehow be meaningfully interpreted as code instead.
