### ISSUE TITLE
Feature request: rust-analyzer.onEnter should strip out trailing white-spaces before go to next line 

### ISSUE THREAD

**Issue by crlf0710** [rust-analyzer/rust-analyzer#5848]

**Comment by matklad** [comment]
I do think that we also should do this ourselves as well.

The relevant code&tests are here:

https://github.com/rust-analyzer/rust-analyzer/blob/ed09bd3cc6a37d7d22038adf7ff815f0188a9949/crates/ide/src/typing/on_enter.rs

**Comment by repnop** [comment]
Would this include non-comment end-of-line whitespace as well? The title makes it sound like it should apply to all scenarios (and in that case, does this get called inside strings/are strings an issue?), but currently `on_enter.rs` only concerns itself with comments at the moment. If it does include non-comments, any tips for refactoring the method to account for that? :)

**Comment by matklad** [comment]
No, this should include only comments.

**Comment by OrangeTux** [comment]
Aren't trailing white spaces already trimmed? [This tests](https://github.com/rust-analyzer/rust-analyzer/blob/ed09bd3cc6a37d7d22038adf7ff815f0188a9949/crates/ide/src/typing/on_enter.rs#L237-L256) covers that, right?

**Comment by repnop** [comment]
@OrangeTux it removes a single space, not all of the trailing whitespace
