### ISSUE TITLE
Feature request: rustfmt current block.

### ISSUE THREAD

**Issue by crlf0710** [rust-analyzer/rust-analyzer#5849]
Currently `rustfmt` does nothing to code within MBE. Before fully solving this problem. It would be nice if there's a workaround command that we can recognize the current block syntax the cursor is within, and reformat the code within the block with some recognized indentation.

**Comment by kjeremy** [comment]
There is a range version of the format request for LSP but we do not implement it since rustfmt is unreliable for document ranges.

**Comment by matklad** [comment]
This is a desirable feature, but it'll mostly fall out naturally after shaving this two large yaks: #4182, #1665
