### ISSUE TITLE
Add a tests that forbids merge commits

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#5854]
We use `rebase` workflow in rust-analyzer. That is, if master branch moves forward from under your PR, you should rebase the PR on top of master (rewriting the history), rather than merge master into your PR branch. 

We should add a test to enforce this. The test should go here:

https://github.com/rust-analyzer/rust-analyzer/blob/master/xtask/tests/tidy.rs

It should run `git` (using `not_bash`), find the last 50 commits or so, and and check that all the merges are from bors.

**Comment by Jesse-Bakker** [comment]
The branch point for the current branch can be found using `git merge-base HEAD master`. Merges not made by bors since branching can be found using `git rev-list --merges --invert-grep --author 'bors\[bot\]' $(git merge-base HEAD master)..`

**Comment by dragfire** [comment]
Let me give this a shot!

**Comment by dragfire** [comment]
#5862 failed because CI checks out repository with no commit history. Since this repo does not have a `pre-push` git hook to ensure that `cargo test` is executed. What is the correct flow we are looking for here?

**Comment by matklad** [comment]
I guess specifying depth to be 50 in the appropriate YML
