### ISSUE TITLE
Add Option to download unpacked binary when updating

### ISSUE THREAD

**Issue by fnafnio** [rust-analyzer/rust-analyzer#5857]
When updating rust-analyzer it automatically downloads the gzipped variant from releases.
Our IT department at $WORK blocks all .gz files automatically (creating a whole host of other problems), but .exe files can be downloaded without problem and when copied to the correct path work without any issues.

Adding the option to always download the unpacked binary would drastically improve the update process for my coworkers and myself.
The discussions with the IT department have been ongoing for quite some time and it should be their problem to solve, but we would really appreciate a pragmatic solution to this issue

**Comment by matklad** [comment]
I'd say this is out of scope. We *could* add a toggle for this, but I really would prefer to keep the release infra as simple as possible.  We are also likely to change distribution strategy in the near future anyway (with movement to a unified rls/rust-analyzer extension).

In practical terms, I'd advice to either:

* use rust-analyzer from rustup
* build rust-analyzer from source (it doesn't require anything beyond stable cargo)
