### ISSUE TITLE
incorrect linting happens frequently recently

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#5864]
First I need to claim that I had never this issue two weeks ago, recently I always see some lint errors, sometimes it's even warning that half of the code in current file is incorrect.

I then exit and open the file again, errors disappear.

For example, the following lint:

![image](https://user-images.githubusercontent.com/33961674/91155174-c4526700-e6c2-11ea-95c8-b8067f675a3e.png)

is suggesting:

![image](https://user-images.githubusercontent.com/33961674/91155225-d8966400-e6c2-11ea-8f8e-35ef2f3f0b18.png)

## Environments

1. coc-rust-analyzer 0.7.15
2. nvim 0.4.4
5. rust-analyzer ef9cea9

**Comment by GopherJ** [comment]
If I exit and re-open, the errors gone.

**Comment by GopherJ** [comment]
![image](https://user-images.githubusercontent.com/33961674/91166869-51052100-e6d3-11ea-8fc3-2efb4dae237b.png)

If I exit and re-open, the errors gone

**Comment by flodiebold** [comment]
This looks like the client getting out of sync with the server. This might be a problem with the client, since I don't think we have any reports of this with VSCode. If you can reproduce this in a simple case (like with a file from scratch), can you record a log of the LSP messages?

**Comment by GopherJ** [comment]
@flodiebold Hi, I'll try to reproduce it on vscode

Just got another strange thing:

![image](https://user-images.githubusercontent.com/33961674/91308288-5cc61580-e7af-11ea-9e39-10e9bd23a0b2.png)

**Comment by lnicola** [comment]
Does this still happen?

**Comment by GopherJ** [comment]
Hi @lnicola I confirm that it has been much better now. I kept upgrading to latest rust-analyzer.  I'll need some time to confirm it's resolved by testing for a few days.

**Comment by lnicola** [comment]
Ping @GopherJ

**Comment by GopherJ** [comment]
@lnicola Hi, since I'm not able to reproduce it, I'll close it, thanks for all of your support
