### ISSUE TITLE
Goto file for include!(...)

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#5871]
This is a feature request. I think it should not be hard to get a goto-file (maybe just via goto-definition lsp functionality) for `include!(...) expressions and items`.
This might work by invoking the goto-definition request on the path string literal expression in `include!(<here>)`. This will greatly simplify navigating to code which resides in `OUT_DIR`.

As a second step it might be super-awesome if goto-definition requests for symbols defined in `include!()`ed files navigated the users exactly to the included files source instead of `include!(...) expression`

**Comment by kjeremy** [comment]
I just ran into this messing with `capnproto` `include!(concat!(env!("OUT_DIR"), "/test_capnp.rs"));`

**Comment by xuqihang** [comment]
Now when I tried Ctrl+Click the items defined in the `include!()`ed files the cursor only jumped to the end of the current file.
Expecting the exciting feature.

**Comment by flodiebold** [comment]
I've opened #6992 for go to definition on items defined in an included file; let's keep this about going to the file by clicking on the path itself.

**Comment by theotherphil** [comment]
I’ll give this a go if no-one else is already working on it.

**Comment by jiacai2050** [comment]
It seems this feature doesn't work any more.

```rust
mod prometheus {
    include!(concat!(env!("OUT_DIR"), "/prometheus.rs"));
}
pub use prometheus::*;
```

Snippet above include prost-build output file, when invoke `find definition` on type defined in `promtheus` module, it will go to `include!`, not actual generated `prometheus.rs`

```
rust-analyzer --version
rust-analyzer 0.3.1369-standalone (ff4d55e48 2023-01-15)
```

**Comment by Veetaha** [comment]
I don't think this feature worked with expressions other than the are string literal like this `include!("...")`
