### ISSUE TITLE
Feature request: Showing of mangled functions names for use in bpftrace

### ISSUE THREAD

**Issue by adaszko** [rust-analyzer/rust-analyzer#5872]
Hi,

Is it feasible (and not too out of scope) to extend rust-analyzer so that it can show raw function symbol names after mangling?  The primary application of this would be to set a [uprobe](https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#3-uprobeuretprobe-dynamic-tracing-user-level) on a particular function within bpftrace.  What currently works but is too coarse-grained is setting a wildcard uprobe, i.e. something like `sudo bpftrace -e 'uprobe:/home/adaszko/.cargo/bin/lighthouse:*process_block* { printf("%p\n", arg0); }'`.  The specific, mangled symbol looks something like `sudo bpftrace -e 'uprobe:/home/adaszko/.cargo/bin/lighthouse:"_ZN12beacon_chain12beacon_chain20BeaconChain$LT$T$GT$13process_block17h86f7a13feab01da8E" { printf("foo\n"); }'`.  What I'm asking for is for rust-analyzer to spit out that `_ZN12beacon_chain12beacon_chain20BeaconChain$LT$T$GT$13process_block17h86f7a13feab01da8E` when I hover over function name or a similar mechanism so that I can copy and paste a mangled name for a specific parameterized types and use within bpftrace.

TIA!

**Comment by lnicola** [comment]
Can you use `llvm-nm` to get a symbol list? This does seem a little out of scope for rust-analyzer.

**Comment by bjorn3** [comment]
This would require compiling the program, listing all symbols defined in the compiled program and then filtering the ones that couldn't have been from the current function away. The exact symbol name depends on the rustc version and the symbol hash has too many inputs that it is infeasible to re-implement in rust-analyzer. A single function can also be responsible for multiple symbols due to generics.

**Comment by adaszko** [comment]
> Can you use `llvm-nm` (or an equivalnt `nm` from the BPF toolchain) to get a symbol list? This does seem a little out of scope for rust-analyzer.

Sure, and it works, what I have problem with, is that matching a particular mangled name with a particular monomorphised function is hard.  It requires understanding of the mangling algorithm and that's what I'm trying to avoid.  Working out the right symbol name is (I presume) complicated and error prone.  Bpftrace is usually used while you're debugging other problems, so it would be very helpful if guessing the right symbol name for tracing would be a problem in itself.

> This would require compiling the program, listing all symbols defined in the compiled program and then filtering the ones that couldn't have been from the current function away. The exact symbol name depends on the rustc version and the symbol hash has too many inputs that it is infeasible to re-implement in rust-analyzer. A single function can also be responsible for multiple symbols due to generics.

I assumed it's the generics that introduce the most variability in mangled symbol names.  That sounds complicated indeed.

**Comment by adaszko** [comment]
Thanks for the feedback, guys.  It doesn't sound feasible.
