### ISSUE TITLE
The return of `.await` is not typed as the `Output` of a BoxFuture, but as a `Future::Output<...>`

### ISSUE THREAD

**Issue by woody77** [rust-analyzer/rust-analyzer#5886]
I have a fn that returns a `BoxFuture<'static, String>`, which RA is telling me expands out to:

![Screen Shot 2020-08-25 at 6 01 35 PM](https://user-images.githubusercontent.com/17480512/91242757-157f4c80-e6fd-11ea-8644-3fe26fd32adb.png)

After calling await:  `let bar = foo.await;`, I'm seeing:

`Future::Output<Pin<Box<dyn Future<Output = String> + Send>>>`
![Screen Shot 2020-08-25 at 6 01 47 PM](https://user-images.githubusercontent.com/17480512/91242767-1e701e00-e6fd-11ea-987d-4c66eb9c6c33.png)

Instead of just `String`.

sample playground that uses the compiler for inspecting the type before/after the await:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=68afe0b35861d41fc9286cce1529276d

**Comment by woody77** [comment]
async functions (without BoxFuture) work as expected:

![Screen Shot 2020-08-25 at 6 05 01 PM](https://user-images.githubusercontent.com/17480512/91242922-83c40f00-e6fd-11ea-9f34-bef71489affc.png)

**Comment by Nashenas88** [comment]
Related to https://github.com/rust-analyzer/rust-analyzer/issues/5003#issuecomment-653777545

**Comment by flodiebold** [comment]
@woody77 are you still encountering this?

**Comment by woody77** [comment]
Yes.

From the current nightly:

![Screen Shot 2020-12-21 at 5 43 12 PM](https://user-images.githubusercontent.com/17480512/102838890-1dea4a00-43b4-11eb-90db-bf6676ba5591.png)

It's not _wrong_, but it's not ideal, since it is showing the correct underlying type:
`pub type BoxFuture<'a, T> = Pin<alloc::boxed::Box<dyn Future<Output = T> + Send + 'a>>;`

But both `baz` and `result` should just be `String`, and if I force a compilation error, that's what `rustc` still reports:

![Screen Shot 2020-12-21 at 5 48 40 PM](https://user-images.githubusercontent.com/17480512/102839216-d6b08900-43b4-11eb-82fd-be30a993bbd8.png)

**Comment by Dessix** [comment]
I've setup some repros that I was going to file as another issue, but this seems to be more appropriate. The repros are available on Gist:
https://gist.github.com/Dessix/2d06becd23ff9291d8fab4015d17975b#file-lib-rs-L44

This also occurs on [BoxStream](https://docs.rs/futures/0.3.13/futures/stream/type.BoxStream.html) and [tracing::Instrumented](https://docs.rs/tracing/0.1.25/tracing/instrument/struct.Instrumented.html).

This issue makes working with trait futures almost unmanageable.

**Comment by jonas-schievink** [comment]
I believe this is partially related to the use of associated type bounds in the `Future` impl for `Pin`:

```rust
impl<P> Future for Pin<P>
where
    P: Unpin + ops::DerefMut<Target: Future>,
```

Here, the `Target` type is actually defined on `ops::Deref`, not `DerefMut`, which would be invalid if the bound was written out in full (`where <P as ops::DerefMut>::Target: Future`). Desugaring that bound to `<P as ops::Deref>::Target: Future` resolves the `{unknown}` types, but still does not normalize the associated types.

**Comment by jonas-schievink** [comment]
Oh, no, it's a problem with path resolution or something? This is broken (infers `{unknown}`):

```rust
use std::{
    future::Future,
    ops,
};

pub struct NotPin<P>(P);

impl<P> Future for NotPin<P>
where
    P: Unpin + ops::DerefMut<Target: Future>,
{
    type Output = <<P as ops::Deref>::Target as Future>::Output;
}

fn box_future() -> NotPin<Box<dyn Future<Output = ()> + 'a + Send>> {
    loop {}
}

async fn broken() {
    let boxed = box_future();
    let output = boxed.await;  // infers `<<{unknown} as Deref>::Target as Future>::Output`
}
```

...but when you replace `ops::Deref{Mut}` with just `Deref{Mut}` and import them, it works:

```rust
use std::{
    future::Future,
    ops::*,
};

pub struct NotPin<P>(P);

impl<P> Future for NotPin<P>
where
    P: Unpin + DerefMut<Target: Future>,
{
    type Output = <<P as Deref>::Target as Future>::Output;
}

fn box_future() -> NotPin<Box<dyn Future<Output = ()> + 'a + Send>> {
    loop {}
}

async fn broken() {
    let boxed = box_future();
    let output = boxed.await; // infers `()`
}
```

Seems pretty weird.

**Comment by Veykril** [comment]
Qualifying the `DerefMut` usage seems fine, but it breaks when qualifying the `Deref` in `type Output = <<P as Deref>::Target as Future>::Output;`, it also fails when qualifying the `Future` trait there.

Seems like we don't lower qualifed `as` target paths properly?

**Comment by flodiebold** [comment]
That does indeed seem weird...

**Comment by Veykril** [comment]
![image](https://user-images.githubusercontent.com/3757771/113046452-68901500-91a0-11eb-9cbb-8ffcdb19e704.png)
Looks like that was it
