### ISSUE TITLE
Switching to "nightly" in code-server causes update loop

### ISSUE THREAD

**Issue by hjfreyer** [rust-analyzer/rust-analyzer#5892]
# To Reproduce

1. Use `code-server`.
2. Install rust-analyzer via extensions.
3. Change channel setting to "nightly".
4. Reload.
5. A toast pops up saying "New version of rust-analyzer (nightly) is available (requires reload)."
6. Press "update".

# Expected result

`code-server` webpage reloads and rust-analyzer is on the nightly channel.

# Actual result

Another toast pops up saying "New version of rust-analyzer (nightly) is available (requires reload)." Rinse and repeat as many times as you'd like. 

It seems like in this state the rust-analyzer extension isn't actually functional. I'm not getting any errors highlighted.

**Comment by bjorn3** [comment]
I don't know how code-server works. Is it possible that code-server forgets the extension globalstorage when reloading? Or that it can't download the language server due to missing internet access?

**Comment by Veetaha** [comment]
I've submitted a bug report to code-server, I guess it's their fault :P
https://github.com/cdr/code-server/issues/2021

**Comment by Veetaha** [comment]
Should have been closed cdr/code-server#2049
