### ISSUE TITLE
RA reports syntax error on if inside let 

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-analyzer/rust-analyzer#5901]
````rust
fn main() {
    const A: bool = true;

    let b: i32 = {
        if A {
            4 
        } else {
            10
        }
    };

    println!("{}", b);
}
````
this is valid rust code but rust analyzer reported several syntax errors
![ra_syntax_error](https://user-images.githubusercontent.com/476013/91497077-908f6100-e8bd-11ea-91f3-fb4c7bb90b61.png)

`rust-analyzer f5a4a4b`

**Comment by bjorn3** [comment]
The language server state got out of sync with the editor state. You can see this by the fact that semantic highlighting is highlighting parts of identifiers differently.

**Comment by lnicola** [comment]
@matthiaskrgr have you seen this lately?

**Comment by lnicola** [comment]
If it's a synchronization issue, this is pretty much untestable (and unactionable) without a LSP trace taken from the beginning.
