### ISSUE TITLE
`checkOnSave.enable` default discrepancy

### ISSUE THREAD

**Issue by euclio** [rust-analyzer/rust-analyzer#5905]
I noticed that the `checkOnSave.enable` setting defaults to `true` in the VS code extension, but `false` in the server itself. I use vim, so while trying to enable clippy I was confused to find that none of my `checkOnSave` configuration changes were taking effect.

Is this intentional? If not, I'm happy to make a PR to change the default setting to `true` in both places.

**Comment by Veetaha** [comment]
Yes, this is definitely a bug. The inconvenience is that we have two sources of truth for default configurations.
This:
https://github.com/rust-analyzer/rust-analyzer/blob/7f79dbc84f5d69ec6f48fa8d67bdfa0525c5dd34/crates/rust-analyzer/src/config.rs#L394-L452

and this should be identical:
https://github.com/rust-analyzer/rust-analyzer/blob/7f79dbc84f5d69ec6f48fa8d67bdfa0525c5dd34/editors/code/package.json#L199-L631
