### ISSUE TITLE
Power Intensive CPU util

### ISSUE THREAD

**Issue by jon-chuang** [rust-analyzer/rust-analyzer#5919]
Rust analyzer has very poor impact on laptop battery life. 

There needs to be work done to reduce its CPU util when idle. 

My battery util with rust analyzer turned on v.s. without is 45W v.s. 10-15W. That is truly a battery life killer.

 Are there any suggestions on how this might be done? Or is this something that has to be managed at the end-user level, for instance, the way that Atom is utilising it?

**Comment by staninprague** [comment]
Do you have any diesel ORM code in your project? Can this be related to: #5344 - Continuous high CPU usage of rust-analyzer-mac triggered by something in vscode?

**Comment by matklad** [comment]
ther's nothing specific in this issue we can act upon.
