### ISSUE TITLE
a missing semicolon can mess up the whole diagnostics

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#5924]
The following example has a missing semicolon, this semicolon has broken the whole diagnostic, The Butterfly Effect makes it hard to understand what's exactly happening and give a really bad develop experience.

Code:
```rust
use std::sync::{Arc, RwLock};

async fn test(data: Arc<RwLock<usize>>) -> usize {
    *data.write().unwrap() += 2;
    *data.write().unwrap()
}

#[async_std::main]
async fn main() -> Result<(), ()> {
    let data = Arc::new(RwLock::new(1)) // missing semicolon :)
    println!("{}", test(data).await);
    println!("Hello, world!");
    Ok(())
}
```

What's showing as diagnostics:

1. 
![image](https://user-images.githubusercontent.com/33961674/91833123-929f4a00-ec46-11ea-8344-44d303af3e6b.png)

2.
![image](https://user-images.githubusercontent.com/33961674/91833050-769ba880-ec46-11ea-98d9-94dd548ee07e.png)

3. 
![image](https://user-images.githubusercontent.com/33961674/91833163-9f23a280-ec46-11ea-93a7-06d82c732b48.png)

**Comment by bjorn3** [comment]
The `main` function not found are coming from rustc. They are caused by the fact that `#[async_std::main]` can't be expanded due to the syntax error, which means that rustc will just completely ignore the function.

**Comment by GopherJ** [comment]
@bjorn3 great thanks on your quick reply~ I'm wondering what can be done on this? As an user it's frustrating to see this kind of meaningless information

**Comment by bjorn3** [comment]
As an heuristic if a function is called `main` and couldn't be parsed, then a dummy `fn main() {}` could be inserted by rustc without any attributes.

**Comment by jonas-schievink** [comment]
Also rustc's "main not found" diagnostic encompasses the entire source file for some reason

**Comment by lnicola** [comment]
I think this is an upstream issue and we shouldn't try to do anything about it.

I filed https://github.com/rust-lang/rust/issues/77968 upstream (maybe someone can add the `A-diagnostics` label).
