### ISSUE TITLE
`let =` typing assist doesn’t have any effect

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#5925]
In case it’s helpful, I’m using VS Code version 1.48.2 and rust-analyzer version 2020-08-31.

---

I’m not sure if I’ve understood [the part of the manual on the subject](https://rust-analyzer.github.io/manual.html#on-typing-assists) correctly, but typing `let =` in front of an existing expression is meant to insert a semicolon. For me, it doesn’t. [Here](https://streamable.com/vie2p7)’s a video showing what I mean.

**Comment by flodiebold** [comment]
Random guess -- do you use a vim extension or something similar?

**Comment by arzg** [comment]
Nope. If you’d like I can try disabling all my extensions and config to see if the issue is with rust-analyzer.

**Comment by matklad** [comment]
Do you have `"editor.formatOnType": true,` in the settings?

**Comment by arzg** [comment]
No. Is that setting required for typing assists to work?

**Comment by arzg** [comment]
Update: I have tried enabling `editor.formatOnType`, and typing assists work now. Do you think this would be worth mentioning in the docs?

**Comment by matklad** [comment]
Yeah, most of the assists are implemented as the onTypeFormatting

**Comment by matklad** [comment]
Yup, PR to the docs would help. I think the source for docs is the comment
in typing.rs
