### ISSUE TITLE
[feature] "generate getter/setter" source action for VS Code

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-analyzer/rust-analyzer#5943]
_This issue is a sibling of #5944 and #5946._

VS Code provides a ["generate getter/setter" source action for Java](https://code.visualstudio.com/docs/java/java-refactoring#_generate-getters-and-setters).

![advancedgettersetter (2)](https://user-images.githubusercontent.com/2467194/92120396-49dbc280-edf9-11ea-8516-69279a887fb9.gif)

This flow seems like it could translate quite well to Rust: just like Java we don't have a `get` or `set` keyword, but instead expose methods to access fields. Typing these out by hand, however, is not a great experience, and we could probably benefit a lot from being able to automatically generate getters and setters.

## Which methods should be generated?

One difference with Java is that we track borrows, and that there's a difference between `field_name`, `field_name_mut` and `set_field_name`. For builders, variants that return `self` exist as well -- however I think builders are a code action category onto themselves.

Given a translation of the earlier Java code:

```rust
struct Person {
    name: String,
    address: String,
}

impl Person {
    pub fn name(&self) -> &String {
        &self.name
    }
}
```

The following suggestions should be shown:

```txt
[ ] Select the fields to generate getters and setters. (1 selected) [ OK ]
---------------------------------------------------------------------------
[x] name mut getter, setter
[ ] address getter, mut getter, setter
```

And if the `name` options is selected, the following code should be generated:

```rust
struct Person {
    name: String,
    address: String,
}

impl Person {
    pub fn name(&self) -> &String {
        &self.name
    }

    pub fn name_mut(&mut self) -> &mut String {
        &mut self.name
    }

    pub fn set_name(&mut self, name: String) {
        self.name = name;
    }
}
```

Even though it's unlikely anyone would want to expose all getter/setter methods for any given field, it's far easier to have them be generated by the IDE and delete the unused methods, than it is to write the methods by hand.

**Comment by Veetaha** [comment]
`&String` type is useless because it doesn't have more methods than `&str`. Same for `&Vec<T>`, where having `Vec<T>` I wouldn't even like the getter to return `&[T]`, but better `impl Iterator<Item = T>` to constrain it more. I wonder if we can somehow make a special case for these.

Related: [getset](https://github.com/Hoverbear/getset)

**Comment by yoshuawuyts** [comment]
[IntelliJ Rust recently added support for this](https://intellij-rust.github.io/2020/09/07/changelog-130.html) too. Though the flow seems slightly different than VS Code Java:

![generate_getter_setter](https://user-images.githubusercontent.com/2467194/93456435-fc258680-f8dd-11ea-83ce-22901199a2e6.gif)

**Comment by matklad** [comment]
We actually have this now, thanks @yoshuawuyts !
