### ISSUE TITLE
[feature] "generate delegate methods" source action for VS Code

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-analyzer/rust-analyzer#5944]
_This issue is a sibling of #5943 and #5946._

VS Code provides a ["generate delegate methods" source action for Java](https://code.visualstudio.com/docs/java/java-refactoring#_generate-delegate-methods).

![generate-delegate-methods](https://user-images.githubusercontent.com/2467194/92124898-a392bb80-edfe-11ea-8363-1a15ba3bcab0.gif)

Propagating functionality from internal structs to the outside world is not uncommon. If _all_ methods of an internal struct need to be forwarded as-is, the [`Deref`](https://doc.rust-lang.org/std/ops/trait.Deref.html) and [`DerefMut`](https://doc.rust-lang.org/std/ops/trait.DerefMut.html) traits enable that at the type level.

But it's not uncommon to want to provide extra guards on methods, or expose only _some_ methods of an internal struct. In which case it's the solution in Rust is to use the delegation pattern.

## What code should be generated?

Practically there exist three kinds of delegation:
- concrete method -> concrete method
- trait method -> concrete method
- trait method -> trait method

### concrete method -> concrete method

I would suggest any initial implementation of this feature to be scoped to concrete method -> concrete method. The way that would look is like this:

```rust
struct Rectangle {
    height: u32,
    width: u32,
}

impl Rectangle {
    pub fn new(height: u32, width: u32) -> Self {
        Self { height, width }
    }

    pub fn area(&self) -> u32 {
        self.height * self.width
    }
}

struct Square {
    rectangle: Rectangle,
}

impl Square {
    pub fn new(a: u32) -> Self {
        Self {
            rectangle: Rectangle::new(a, a),
        }
    }
}
```
The following suggestions would be shown for `Square`:
```txt
[ ] Select methods to generate delegates for. (1 selected) [ OK ]
---------------------------------------------------------------------------
[x] rectangle.area
```
And if the `rectangle.area` option was selected, the following code would be generated:

```rust
// ... collapsed the Rectangle impl

struct Square {
    rectangle: Rectangle,
}

impl Square {
    pub fn new(a: u32) -> Self {
        Self {
            rectangle: Rectangle::new(a, a),
        }
    }

    pub fn area(&self) -> u32 {
        self.rectangle.area()
    }
}
```

### trait method -> concrete method

Being able to create concrete delegates for trait methods would be great to have as well, but can probably be done as a follow-up as it seems more complicated and less common than concrete method delegation. The way I would envision this to work is like this:

```rust
trait Sound{
    fn sound(&self);
}

struct Dog;

impl Sound for Dog {
    fn sound(&self) {
        println!("bark");
    }
}

pub struct House<T: Sound> {
    inner: T
}
```

The following suggestions would be shown for `House`:
```txt
[ ] Select methods to generate delegates for. (1 selected) [ OK ]
---------------------------------------------------------------------------
[x] inner.sound Sound
```

The dialog should show where the trait originates from in relation to the file. For example `Hash` would show up as `std::hash::Hash`. This in turn generates the following code:

```rust
// ... collapsed Sound and Dog

pub struct House<T: Sound> {
    inner: T
}

impl<T: Sound> House<T> {
    fn sound(&self) {
        self.inner.sound();
    }
}
```

### trait method -> trait method

It's not uncommon to want to implement a trait in terms an internal type that already implements that trait. For example delegating a `Hash` impl to some inner type. Forwarding these implementations is often simple-but-tedious work, and being able to automatically generate this would be incredibly useful. Take for example the following code:

```rust
#[derive(Debug)]
struct Inner;

struct Outer {
    inner: Inner
}
```

If we'd want to delegate the `Debug` impl to the inner type, it'd be possible by generating the following code:

```rust
#[derive(Debug)]
struct Inner;

struct Outer {
    inner: Inner,
}

impl std::fmt::Debug for Outer {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.inner.fmt(f)
    }
}
```

This feels different than creating a concrete method. I'm not sure if it should fit in the same flow as concrete method delegation. This seems like a question that needs design work before implementing.

Also not all methods can be delegated as-is. For example traits that have `self: Pin<&mut Self>` in the signature require more complex delegation patterns. Therefor initially there may need to be limitations on which traits can be delegated -- for example by excluding traits with deviating self types at first.

**Comment by gfreezy** [comment]
how about generate like this crate? https://docs.rs/delegate/0.6.1/delegate/
