### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by caemor** [rust-analyzer/rust-analyzer#5945]
Rust analyzer crashed in a unexpected way: https://gist.github.com/caemor/2d0b3a427574f257062fcd092137b7d2
I am not sure if that output is even helpful in any way.

After restarting vs code the crash didn't happen anymore. 

Version was rust-analyzer-0.2.297

**Comment by lnicola** [comment]
> `thread '<unnamed>' panicked at 'Failed to make ast node `syntax::ast::generated::nodes::Name` from text mod ::from_reader;', crates/syntax/src/ast/make.rs:325:13`

Can you share a project where this happens? The crash is in the `generate_function` assist.

**Comment by caemor** [comment]
It only happened once and sadly the project where it happened is private.

**Comment by caemor** [comment]
Closing because I don't think the crashlog is helping and the other above called reasons
