### ISSUE TITLE
[feature] "generate PartialEq" source action for VS Code

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-analyzer/rust-analyzer#5946]
_This issue is a sibling of #5943 and #5944._

VS Code provides a ["generate hashcode and equals" source action for Java](https://code.visualstudio.com/docs/java/java-refactoring#_generate-hashcode-and-equals). This enables implementing equality comparisons between the current class and other types.

![generate-hashcode-equals](https://user-images.githubusercontent.com/2467194/92138233-69311a80-ee0e-11ea-9e10-435b0b09b547.gif)

In Rust the way to implement equality between two instances of the same type is usually to use `#[derive(PartialEq, Eq)]`. If all fields on the struct implement `PartialEq + Eq` then deriving _just works_.

However when you want to compare two different types, `PartialEq` needs to be implemented manually. When using a newtype, it's not uncommon to provide equality comparisons with an inner type. This is a fairly mechanical operation, but tedious to type out. Which is where an IDE could be immensely helpful.

## What code should be generated?

The most tedious part to generate is `PartialEq` implementations that perform equality with an inner type. `Eq` by comparison is far less tedious. Given the following code:

```rust
#[derive(PartialEq, Eq)]
struct Inner(String);

struct Outer {
    inner: Inner,
    counter: u8,
}
```

The following `"Generate equality"` suggestions should be shown for `Outer`:
```txt
[ ] Select the fields to generate PartialEq for. (1 selected) [ OK ]
---------------------------------------------------------------------------
[x] inner Inner
[ ] counter u8
```

And if the "inner" option is selected, the following code should be generated:

```rust
#[derive(PartialEq, Eq)]
struct Inner(String);

struct Outer {
    inner: Inner,
    counter: u8,
}

impl std::cmp::PartialEq<Inner> for Outer {
    fn eq(&self, other: &Inner) -> bool {
        self.inner == other
    }
}
```

## Comparing owned and borrowed values

It's quite common to want to compare owned values with borrowed values. For example equality comparisons exist between `&str` and `String`, making them a lot easier to use. The question is whether we'd want to generate these too, especially since the implementations are not intuitive to get right:

```rust
impl std::cmp::PartialEq<&Inner> for Outer {
    fn eq(&self, other: &&Inner) -> bool {
        &&self.inner == other
    }
}
```

One approach would be to use a dialog similar to "generate getters / setters" https://github.com/rust-analyzer/rust-analyzer/issues/5943 and show which implementations already exist in the dropdown, so that it becomes clear which implementations already exist and which will be generated:

```txt
[ ] Select the fields to generate PartialEq for. (1 selected) [ OK ]
---------------------------------------------------------------------------
[x] inner PartialEq<Inner>, PartialEq<&Inner>
[ ] counter PartialEq<u8>, PartialEq<&u8>
```

There's a question whether borrowed equality for `Copy` types is useful, but I'm sure that can be refined. Personally I'm leaning towards slightly over-generating implementations, and trusting people delete what they don't want. That seems like a faster workflow than in some cases need to implement equality from scratch (and remember the exact incantation for that).

## Delegating equality checks

String types tend to have a lot of different equality implementations. For example `str` has `PartialEq` implementations for `str`, `Cow<'a, str>`, `OsStr`, `OsString`, and `String`. A `str` wrapper may want to implement some of these equality checks as well.

https://github.com/rust-analyzer/rust-analyzer/issues/5944 proposes a "generate delegate methods" source action which could be leveraged here. In particular the `trait method -> trait method` implementation. It seems that if that feature was implemented, then forwarding member `PartialEq` implementations would be possible.

## Ord and PartialOrd

It seems that the same constraints and designs laid out in this issue would apply to `Ord` and `PartialOrd` as well. Perhaps it would be possible to share the implementation between the two sets of traits.

**Comment by matklad** [comment]
The fix would be to extend an existing assist to do that:

https://github.com/rust-analyzer/rust-analyzer/blob/eb08a27f1bd31cc15db4893dded60663effaf3f9/crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs#L21

**Comment by yoshuawuyts** [comment]
This should be easier now that we have #9863. The logic needs to be extended to be able to compare with types other than `Self`, and to not hard-code the variable name of `other`.
