### ISSUE TITLE
Type becomes unknown when put into tuple?

### ISSUE THREAD

**Issue by NickNick** [rust-analyzer/rust-analyzer#5947]
I am using version 0.2.297

I have a snippet of code, where the types are known throughout (yay) but then are lost in the last step:

![image](https://user-images.githubusercontent.com/239522/92160606-93df9b00-ee2f-11ea-8165-b5baee466bcd.png)

On line 3143 they are known, but on line 3132 they are gone. I think they are somehow lost after .map(). I checked this by adding another .map after that, and it couldn't deduce the types anymore.

Let me know if this is enough for an issue report, or if there's more needed. Thanks!

**Comment by bjorn3** [comment]
Are you refering to the ...? These are to prevent the type hints from getting too long. There should be an option to change the limit before it kicks in.

**Comment by NickNick** [comment]
> Are you refering to the ...? These are to prevent the type hints from getting too long. There should be an option to change the limit before it kicks in.

I was referring to line 3132, and clarified in the first message too.

**Comment by bjorn3** [comment]
Where is `collect_vec` defined (which trait of which crate)? Did you put the `use` for it's trait inside the function body or at the top of the file?

**Comment by NickNick** [comment]
That refers to https://docs.rs/itertools/0.9.0/itertools/trait.Itertools.html#method.collect_vec, it's `use` is with `use itertools::Itertools;`.

**Comment by bjorn3** [comment]
Where did you place the `use itertools::Itertools`? Is in at the top of the file or inside the function body.

**Comment by NickNick** [comment]
Top of the file.

**Comment by bjorn3** [comment]
cc @flodiebold

**Comment by flodiebold** [comment]
Does `.collect::<Vec<_>>` instead of `collect_vec` work?

**Comment by NickNick** [comment]
No, same result.

**Comment by flodiebold** [comment]
Can you see the full type of the result of `map` some way? E.g. assign it to a variable. I think it might just be hitting the type size limit, which is set quite low currently.

**Comment by cynecx** [comment]
It's not minimal, but I can reproduce this with this:

```rust

use itertools::Itertools;

struct Foo;

struct Bar;

fn ISSUE_5947() {
    let name = &Foo;
    let amount = &&Bar;
    let data = vec![(name, amount)];
    let res = data
        .iter()
        .cloned()
        .filter_map(|(a, b)| Some((a, b)))
        .map(|(a, b)| (a, b))
        .collect_vec();
}
```

![Screenshot from 2020-09-04 13-49-12](https://user-images.githubusercontent.com/5961244/92236358-92f14c80-eeb5-11ea-801a-81aa7334db2d.png)

**Comment by cynecx** [comment]
Not sure if this is the same issue but Item type of the Vec is also unknown:

```rust
use itertools::Itertools;

#[derive(Debug)]
struct Foo;

#[derive(Debug)]
struct Bar;

fn ISSUE_5947() {
    let name = &Foo;
    let amount = &&Bar;
    let data = vec![(name, amount)];
    let res = data
        .iter()
        .cloned()
        .filter_map(|(a, b)| Some((a, b)))
        .map(|(a, b)| (a, b, a))
        .collect_vec();
    println!("{:?}", res);
}
```

![Screenshot from 2020-09-04 13-56-53](https://user-images.githubusercontent.com/5961244/92236855-920cea80-eeb6-11ea-8e82-d7d5509c4926.png)

**Comment by NickNick** [comment]
> Can you see the full type of the result of `map` some way? E.g. assign it to a variable. I think it might just be hitting the type size limit, which is set quite low currently.

Can I increase this limit to test this? I think this may be true. Since yesterday evening I split the expression and that fixes it.

When I'm splitting it up, it seems to know the type right until the .collect():

![image](https://user-images.githubusercontent.com/239522/92252050-01420900-eece-11ea-8a8d-d6572f329a67.png)

I think @cynecx has a nice reproduction there actually, thanks a lot! :+1:

**Comment by flodiebold** [comment]
> Can I increase this limit to test this? I think this may be true.

It's currently hard-coded pretty deeply in Chalk [here](https://github.com/rust-lang/chalk/blob/46344c8074f2a8b9a377a1281021bf879ff5cc60/chalk-recursive/src/fulfill.rs#L237) and [here](https://github.com/rust-lang/chalk/blob/46344c8074f2a8b9a377a1281021bf879ff5cc60/chalk-recursive/src/fulfill.rs#L247) :disappointed:

**Comment by cynecx** [comment]
Setting the limits to e.g. 100 seems to have fixed this:

![Screenshot from 2020-09-04 18-05-37](https://user-images.githubusercontent.com/5961244/92261784-5d128f00-eeda-11ea-81b8-cb7c5cb722eb.png)

**Comment by NickNick** [comment]
So increasing fixes the issue, but still what I don't understand is why the bindings do still get type information, but their .map() does not. I'd expect the depth to be too shallow in both cases, no?

Regardless, thanks for the help so far.

**Comment by flodiebold** [comment]
It depends on whether the type can be directly constructed without help from Chalk (e.g. all the return values of the intermediate iterators), or not (calculating the item type of the iterator means normalizing the associated type, which requires Chalk).

**Comment by flodiebold** [comment]
@NickNick are you still seeing this? You can also increase the type size limit by setting the `CHALK_MAX_SIZE` env variable (default is 30).

**Comment by NickNick** [comment]
Quickly browsing through my code now I can't seem to find any missing types anymore, so for me this issue is fixed, thanks. If I run into it again I will first increase the size with that env variable. Feel free to close this issue.
