### ISSUE TITLE
ra_syntax: errors on a type cast + comparison

### ISSUE THREAD

**Issue by ordian** [rust-analyzer/rust-analyzer#595]
```rust
fn is_empty<T: ?Sized>(ptr: *const T) -> bool {
    return ptr as *const usize as usize <= 256;
    //                                   ^^^   
    // ra_syntax expects a type, COMMA, R_ANGLE or SEMI 
}
```

**Comment by DJMcNab** [comment]
The relevant code in `libsyntax` starts here - @matklad, I'm not sure how to make this work in our infra?

**Comment by matklad** [comment]
@DJMcNab missing link to linsyntax source?

**Comment by DJMcNab** [comment]
Oops. I'm on mobile so can't link now, but it's a line about creating a Snapshot and reloading it on syntax errors in the parsed trait bound

**Comment by matklad** [comment]
I think that logic exists solely for the purpose of better error message. it should be possible to parse this without lookahead. See https://github.com/rust-lang/rust/pull/42578 and the state of the code *before* that PR for how this should be done.

We'll add backtracking later, of course, but for the start it's better to keep things simple.

**Comment by matklad** [comment]
Specifically, the following is still error in rustc:

```
return ptr as *const usize as usize < 256;
```

**Comment by kiljacken** [comment]
This is working now, so issue can be closed.
