### ISSUE TITLE
Missing `fill struct fields` quick-fix when `missing structure fields` problem is present

### ISSUE THREAD

**Issue by avrong** [rust-analyzer/rust-analyzer#5950]
The problem is suggesting a quick-fix for the issue, except there is no actual fix to resolve the problem.
But it will suggest the right quick-fix inside of the struct instantiation description.

<img width="400" src="https://user-images.githubusercontent.com/6342851/92283250-2bb0b800-ef08-11ea-9608-1ba6f76a86b1.png">
<img width="400" src="https://user-images.githubusercontent.com/6342851/92283515-b7c2df80-ef08-11ea-91af-034e413ece60.png">
<img width="400" src="https://user-images.githubusercontent.com/6342851/92283394-75999e00-ef08-11ea-9fac-0381dbe466d9.png">

**Comment by bnjjj** [comment]
I had the same issue, will take a look to fix it :)

**Comment by FH0** [comment]
![image](https://user-images.githubusercontent.com/32861476/101623623-ae8b6680-3a53-11eb-9eec-13805c84fa4d.png)
```rust
s! {
    pub struct in6_addr {
        pub s6_addr: [u8; 16],
        __align: [u32; 0],
    }
}
```
Is it the same problem?

**Comment by Veykril** [comment]
That should be the same problem, the quickfix trigger range currently only covers the inner parts of the struct expression. #6775 fixes that.

**Comment by gluax** [comment]
This seems to be broken again :c. I tried uninstalling and reinstalling as well.

![image](https://user-images.githubusercontent.com/16431709/210414067-46e16751-af14-4d39-87d1-81f5b25f2006.png)


![image](https://user-images.githubusercontent.com/16431709/210413979-1c93db55-380e-4c77-b6bc-b9b3c5865bca.png)

**Comment by Veykril** [comment]
Given the async function I presume this happens in  an `#[async_trait]` item which is known to not always work currently

**Comment by gluax** [comment]
Ah got it. Thanks for that information!
