### ISSUE TITLE
Cannot add breakpoints in VSCode without debug.allowBreakpointsEverywhere

### ISSUE THREAD

**Issue by saschanaz** [rust-analyzer/rust-analyzer#5952]
It seems the VSCode extension does not explicitly enable breakpoints and instead depends on debug.allowBreakpointsEverywhere behavior. Enabling the flag correctly allows adding breakpoints.

On VSCode 1.48.2 and rust-analyzer extension 0.2.297.

**Comment by bjorn3** [comment]
I think it is the responsibility of the debugging plugin to do this and not rust-analyzer. Rust-analyzer has no idea where breakpoints could be placed.

**Comment by saschanaz** [comment]
But there is no "debugging plugin", right?

**Comment by bjorn3** [comment]
The debugging plugin is codelldb, native debug or something like that. Whichever one you use to invoke the debugger.

**Comment by saschanaz** [comment]
Ah, I have ms-vscode.cpptools installed and that enabled Rust debugging (but not breakpoints, https://github.com/microsoft/vscode-cpptools/issues/75).

But still, it seems enabling breakpoints does not require understanding how to map them but simply indicates the file type is debuggable. And since rust-analyzer is a language service extension I think it might be more proper to indicate it here.

**Comment by bjorn3** [comment]
Rust files are not debuggable without a debugger plugin, which ms-vscode.cpptools is. Rust-analyzer is not a debugger, and as such it doesn't make sense for rust-analyzer to say that rust files are debuggable. in my opinion.

**Comment by saschanaz** [comment]
Well yes, [the documentation](https://code.visualstudio.com/api/references/contribution-points#contributes.breakpoints) also says it's for debuggers. Closing as such.

I still think it doesn't really make sense to let debuggers mark every language as debuggable, though.

**Comment by Elias-Graf** [comment]
@saschanaz Hey, How exactly do I fix this? I don't really understand what you guys were talking about (I'm relatively new to rust). I'm simply pressing the "Debug" link on my test and it runs it. I didn't install anything specific, although I did some cpp a while ago (no Idea if that involved a debugger [I failed horribly at cpp]).

I understand that `debug.allowBreakpointsEverywhere` is obviously not the way to go, but what is?

Kind regards :)

**Comment by bjorn3** [comment]
Are you using a vscode variant other than the official from microsoft. Microsoft only allows certain of it's extensions to be used with the official vscode version.

**Comment by Elias-Graf** [comment]
@bjorn3 I'm using the insider branch but it is certainly the official one. Why, do I have something installed that I shouldn't have?

**Comment by bjorn3** [comment]
A C/C++ debugger extension is what you need for rust debugging. They are not actually C/C++ specific, but work for all languages that compile to native executables.

**Comment by Zingam** [comment]
On Windows Microsoft's C++ Tools doesn't work. CodeLLDB worked for me.
