### ISSUE TITLE
Feature request: assist to surrond an expression with `dbg!` or just parens `(...)`

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#5960]
When debugging rust code one quite often needs to add/remove `dbg!` macros. Coupled with RA's ability to select expressions it can be very convenient.

**Comment by kiljacken** [comment]
The `dbg!` part already exists as a postfix completion.

**Comment by flodiebold** [comment]
I'm sure there's already a way to surround the selection with parens in VSCode?

**Comment by lnicola** [comment]
> I'm sure there's already a way to surround the selection with parens in VSCode?

Select the expression, press `(`, press right arrow twice.

**Comment by 0x7CFE** [comment]
Thanks for the feedback, guys!
