### ISSUE TITLE
Cargo crash for template

### ISSUE THREAD

**Issue by mehmetcansahin** [rust-analyzer/rust-analyzer#5961]
Hello,

I'm preparing a boilerplate for warp server framework. However, due to the Cargo.toml file, rust-analyzer crashes constantly. The reason is that I'm using "name =" {{project-name}} "" and "authors = [" {{authors}} "]".

```
rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file Cargo.toml, cargo 1.45.1 (f242df6ed 2020-07-22): Failed to run `cargo metadata --manifest-path Cargo.toml`: Error during execution of `cargo metadata`: error: failed to parse manifest at `Cargo.toml` Caused by: invalid character `{` in package name: `{{project-name}}`, the first character must be a Unicode XID start character (most letters or `_`)
```

```Cargo.toml
[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.2"
tokio = { version = "0.2", features = ["full"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
```

**Comment by bjorn3** [comment]
> error: failed to parse manifest at `Cargo.toml` Caused by: invalid character `{` in package name: `{{project-name}}`, the first character must be a Unicode XID start character (most letters or `_`)

`{{project-name}}` is not a valid crate name. It is meant to be replaced with your real crate name.

**Comment by mehmetcansahin** [comment]
I understand, but in the case of creating a template, I have to rename it before publishing. This situation is not programatic for me and it is used in many libraries. What can I do to avoid getting an error? For example https://github.com/rustwasm/wasm-pack-template

**Comment by bjorn3** [comment]
You could completely disable rust-analyzer or use `rust-analyzer.linkedProjects`. Rust-analyzer uses `cargo metadata` to find all the dependencies and files of your project. If `cargo metadata` fails, you will have to manually specify which files are the roots of your project and what dependency has which source.

**Comment by mehmetcansahin** [comment]
Thank you.
I looked at cargo metadata but couldn't see a parameter to bypass these properties.
