### ISSUE TITLE
Type inference makes mistakes.

### ISSUE THREAD

**Issue by Lepuroid** [rust-analyzer/rust-analyzer#5963]
Here are some examples of bad type inference in a comparison with the "Rust" VSC expansion. The upper hints are from "Rust" and are correct and the lower hints are from "rust-analyzer".
<a href="https://imgbb.com/"><img src="https://i.ibb.co/myHBWJM/1.png" alt="1" border="0"></a>
<a href="https://ibb.co/b6FkJZz"><img src="https://i.ibb.co/rQ3VsS4/2.png" alt="2" border="0"></a>
The next one isn't really wrong, but in other cases it hints with the `pub struct String`, not just `String`.
<a href="https://ibb.co/KFFgLTs"><img src="https://i.ibb.co/Fgg10RY/3.png" alt="3" border="0"></a>
The next one refers to the return type of the `unwrap()` method.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/jJjbm7h/4.png" alt="4" border="0"></a>

**Comment by kiljacken** [comment]
Is the project open source? It's almost impossible to discover what is wrong without source code.

But from the third image, this might be a case of #1165. Your `use crate::*` inside the function isn't supported yet, if you move it out of the function everything "should" work correctly.

**Comment by Lepuroid** [comment]
Yes, [it](https://github.com/Lepuroid/libmagma.git) is open source.
Moving `use crate::*` out of function fixes all mistakes but 3. It is still `String`.

**Comment by kiljacken** [comment]
3 is correct as I see it, the String type is std::string::String (but `use`d in the prelude), unless you are saying that you've defined your own String type.

**Comment by Lepuroid** [comment]
It seems you are right and I was confused about variables' types hints and hints for the return types of functions in their definitions. Thank you.
