### ISSUE TITLE
VSC hoverAction.enable and inlayHints.enable configurations not working

### ISSUE THREAD

**Issue by diliop** [rust-analyzer/rust-analyzer#5964]
Currently running:
- `v0.2.305` for the `rust-analyzer` extension
- `0275b08` for the `rust-analyzer` binary
- VSC with
   ```
   Version: 1.48.2
   Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
   Date: 2020-08-25T10:09:08.021Z (1 wk ago)
   Electron: 7.3.2
   Chrome: 78.0.3904.130
   Node.js: 12.8.1
   V8: 7.8.279.23-electron.0
   OS: Darwin x64 19.6.0
   ```

In my `settings.json` I have the following configurations:

```
    "rust-analyzer.hoverActions.enable": false,
    "rust-analyzer.inlayHints.enable": false,
```
and the expected behavior would be for both the [Hover](https://rust-analyzer.github.io/manual.html#hover) and [Inlay Hints](https://rust-analyzer.github.io/manual.html#inlay-hints) to be disabled which does not appear to be the case:

![Screen Shot 2020-09-08 at 1 37 49 AM](https://user-images.githubusercontent.com/1054180/92453394-0f18b800-f174-11ea-9168-46384b452c80.png)

I have also tried:
- disabling all configurations associated with `hoverAction` and `inlayHints`
- using the `nightly` build for both `rust-analyzer` VSC extension and binary 

but the observed behavior is the same. I might be missing something here but would love any feedback.

**Comment by lnicola** [comment]
This is a hover action (the Run/Debug links):

![image](https://user-images.githubusercontent.com/308347/92454121-d8b95800-f1c8-11ea-9687-7e288205fe3b.png)

This is an inlay hint (`: Receiver<CentralEvent>`):

![image](https://user-images.githubusercontent.com/308347/92454158-e40c8380-f1c8-11ea-9318-112c976051f2.png)

As you can see, they don't show up for you, so changing the setting worked.

If you want to disable the hover pane, you can configure that using `editor.hover.enabled`.

**Comment by diliop** [comment]
Oh I see! I thought the yellow bulb in the picture above was what the `inlayHints` controls. Using your suggestion and `editor.hover.enabled` I can get the hover to disappear so thats good. In case you know, is there a way to make this 
 behavior context/language specific i.e. only disable the hovers for `.rs` files. Also, is there a way to also disable the yellow bulbs?

**Comment by lnicola** [comment]
> In case you know, is there a way to make this behavior context/language specific i.e. only disable the hovers for `.rs` files.

```json
    "[rust]": {
        "editor.hover.enabled": false,
    },
```
> Also, is there a way to also disable the yellow bulbs/Code Actions?

```json
    "editor.lightbulb.enabled: false
```

**Comment by diliop** [comment]
@lnicola you are a god among men! Thanks you so much for the tips and the help 💯
