### ISSUE TITLE
Seemingly random underscores from syntax highlighting

### ISSUE THREAD

**Issue by awulkan** [rust-analyzer/rust-analyzer#5966]
Hey, I just got started with Rust, and decided to install RA, so maybe this isn't a bug, but instead something I don't understand.

I have copied a bit of code from an Actix-Web example, and I'm getting random underscores in the code once the syntax highlighting sets in. I'm using the default VS Code theme on Windows 10.

![Image](https://i.imgur.com/nGUFAIk.png)

**Comment by bjorn3** [comment]
These indicate when a variable is mutable, or a method takes self by mutable reference instead of by immutable reference.

**Comment by awulkan** [comment]
> These indicate when a variable is mutable, or a method takes self by mutable reference instead of by immutable reference.

Alright, thanks. I'll close this issue then. :)

**Comment by Hadron67** [comment]
Is there any way to turn it off?
