### ISSUE TITLE
[flycheck] Allow disabling the `--workspace` argument through config

### ISSUE THREAD

**Issue by phil-opp** [rust-analyzer/rust-analyzer#5967]
The check command for `flycheck` currently hardcodes the `--workpace` argument:

https://github.com/rust-analyzer/rust-analyzer/blob/60c8941097f3674ed4b583925603b5ec43833f0c/crates/flycheck/src/lib.rs#L198

This is problematic for workspaces whose crates require different targets. For example, a workspace for an embedded program might consist of crates that should be compiled for some ARM target and crates that should be compiled for the host architecture (e.g. cargo `runner` crates or [xtasks](https://github.com/matklad/cargo-xtask/)).

For such workspaces, it is not possible to build all workspace crates for the same target, so there should be an option to disable the `--workspace` argument. This would make it possible to at least check one half of the crates configuring a default target and passing explicit `--package` arguments.

Ideally, there should be some way to specify target requirements at the crate/binary level, so that we could check everything in multiple passes (one for each target), but this seems like a larger task.

**Comment by bjorn3** [comment]
You can use `"rust-analyzer.checkOnSave.overrideCommand": ["cargo", "check", "--message-format=json"]`.

**Comment by phil-opp** [comment]
Ah great, thanks a lot!
