### ISSUE TITLE
Code completion & Highlighting inside macro calls

### ISSUE THREAD

**Issue by pksunkara** [rust-analyzer/rust-analyzer#5972]
From zulip discussion,

> when declaring macro_rules (not talking about proc_macros), you are generally given token hints like ident, expr etc.. Since we read the macro_rules def, can we use those hints to resolve the tokens inside macro call?

> More generally, we should make compleiton and goto definition work for $meta_vars, then highlighting

**Comment by flodiebold** [comment]
We have completion/highlighting inside macro calls; I think this is more about macro_rules definitions?

**Comment by pksunkara** [comment]
Basically it's both. Because resolving one of them resolves the other.

**Comment by flodiebold** [comment]
Can you give some specific examples then? It's not completely clear to me what the scope of this is.

**Comment by pksunkara** [comment]
If you look at the macro defined [here](https://github.com/clap-rs/clap/blob/8e676b59e47a19ab8ec87610bf8d59db5ca75c44/src/macros.rs#L163), when I use it

```
app_from_crate!().|
```

I expect the completion values from `clap::App` since this macro resolves to `clap::App`. We can understand that it resolves to that by looking at the syntax inside macro.

**Comment by flodiebold** [comment]
But that's not completion _inside_ a macro, is it? It's just expanding a macro call. I don't see any reason why this shouldn't already work right now, if it doesn't for you could you maybe report a separate bug with a full reproduction?
