### ISSUE TITLE
Unknown Request in Multi-Project setup

### ISSUE THREAD

**Issue by peter-subscale** [rust-analyzer/rust-analyzer#5973]
Getting a very annoying error message as I am typing:

```
[ERROR rust_analyzer::dispatch] unknown request: Request { id: RequestId(U64(110)), method: "textDocument/semanticTokens/full", params: Object({"textDocument": Object({"uri": String("<file_location>")})}) }
[Error - 10:42:39 am] Request textDocument/semanticTokens/full failed.
  Message: unknown request
  Code: -32601 
```

**Comment by kjeremy** [comment]
What's your server/client information? This is due to the recent changes to update the LSP protocol.

**Comment by peter-subscale** [comment]
Appears to be resolved using VSCode `1.48.2` with the latest rust analyzer extension, `0.2.305`

**Comment by owen-hope** [comment]
This seems to be broken using VSCode `1.49` with the latest rust analyzer extension, `0.2.305`

**Comment by lnicola** [comment]
@owen-hope are you still getting this error?
