### ISSUE TITLE
Unresolved associated type (Just highlighting?)

### ISSUE THREAD

**Issue by cynecx** [rust-analyzer/rust-analyzer#5978]
```rust
struct Foo;

trait Bar {
    type Foo;

    // Go to definition shows Bar's `type Foo`, Foo's `type Foo = usize` and `struct Foo`
    // which is implies that rust-analzer doesn't actually know what `Self::Foo` refers to.
    // Go to type definition doesn't work.
    fn b(a: Self::Foo); // Foo is colored as 'unresolvedReference'
}

impl Bar for Foo {
    type Foo = usize;

    // hovering over `a` shows `usize` but `Foo` is also colored as 'unresolvedReference'
    fn b(a: Self::Foo) {
    }
}

```

![image](https://user-images.githubusercontent.com/5961244/92950885-c146cd00-f45d-11ea-88bf-c47ae9bb4889.png)

rust-analyzer: fab7543290573081484c99aa7ca4585bc4d45747

**Comment by cynecx** [comment]
I think something is wrong (or missing) about the path resolution of the Self type inside trait impls.

This also affects auto-completion:

```rust
trait Foo {
    type Bar: Default + Clone;

    fn bo(&self) {
        let a = Self::Bar::<|>; // not completion results
        let b = <Self::Bar as Default>::<|>; // correctly shows `default()`
    }
}
```

**Comment by flodiebold** [comment]
Hmm. The type hints for
```rust
        let x = Self::Bar::default();
```
show that it does get resolved. I think this might need some additional handling in the completion code.

**Comment by cynecx** [comment]
@flodiebold Hmm, however highlighting seems to be affected as well.

**Comment by lnicola** [comment]
Looks similar to https://github.com/rust-analyzer/rust-analyzer/issues/5003.

**Comment by cynecx** [comment]
@lnicola I need to step up my "properly searching gh issues" game.
