### ISSUE TITLE
Rust-analyzer detects iterator cmp function instead of correct member function

### ISSUE THREAD

**Issue by Mikastiv** [rust-analyzer/rust-analyzer#5979]
I have a struct with a member function cmp.

`impl Foo {
    fn cmp(&mut self) -> bool {
        todo!()
    }
}`

I am using a function pointer to this function in a closure in another function.

`fn bar(foo: fn(&mut Foo) -> bool) {
    todo!()
}`

In my code when I call the function using a closure, rust-analyzer picks it up as the generic cmp function to compare with an iterator. It generates an error, but the code compiles fine.

`bar(|foo| foo.cmp());` _Squiggly line here_

rust-analyzer says: Expected 1 argument, found 0

**Comment by izderadicka** [comment]
I do have similar problem with `take` function  for Option enum.  
Analyzer complains that take function is missing argument.
Below is extract from my code to demonstrate the problem:
```rust
use structopt::StructOpt;
use std::path::PathBuf;

#[derive(Debug, StructOpt)]
pub struct Args {
   

    #[structopt(short, long)]
    pub config_dir: Option<PathBuf>,

    
}
pub fn parse_args() -> Result<Args, ()> {
    let mut args = Args::from_args(); // problem relates to creation of args by this derived associated method and type inference

    // because this eliminates problem:
    // let mut args: Args = Args::from_args();

    // Anf this too
    // let mut args = Args {config_dir: Some(PathBuf::new())};

    let _cfg = args.config_dir.take(); // Got error: Expected 1 argument, found 0 rust-analyzer
    // let cfg = args.config_dir.take(0); // This is also error: this function takes 0 arguments but 1 argument was supplied expected 0 argumentsrustc(E0061)
    let _cfg = Option::take(&mut args.config_dir); // This works
    Ok(args)
}
```

rust-analyzer version: 2020-09-07 (0275b08) in VS Code

**Comment by bjorn3** [comment]
Do you have proc macros enabled? `"rust-analyzer.procMacro.enable": true` and `"rust-analyzer.cargo.loadOutDirsFromCheck": true`

**Comment by Mikastiv** [comment]
This worked for me. So is it supposed to work this way?

**Comment by bjorn3** [comment]
Yes, `#[derive(StructOpt)]` doesn't do anything when proc macros are disabled. This means that `Args::from_args` is not found and rust-analyzer takes a guess at the return type. In this case incorrectly.

**Comment by Mikastiv** [comment]
Well thanks for the solution!

**Comment by izderadicka** [comment]
Works for me as well, thanks.  Just question why proc macro option is disabled by default (plus outdir), as they are quite common - serde, .... Are there any performance implication?  For me as normal user it was not possible to realize that I need to change settings.

**Comment by bjorn3** [comment]
Proc macro support used to be buggy. I think most bugs are fix now though. The proc macro support also only works for one specific rustc version as it depends on an implementation detail of the proc macro support in rustc. For example nightly rustc is not compatible right now. There is a PR to fix this, but it won't be merged until the change lands on stable, because landing it right now will break support for the latest stable.

**Comment by izderadicka** [comment]
@bjorn3 thanks for explanation.  Actually I was using nightly it worked there fine.
