### ISSUE TITLE
[VSCode] Option to check only on save

### ISSUE THREAD

**Issue by viveksjain** [rust-analyzer/rust-analyzer#5984]
Currently the rust-analyzer VS Code extension shows errors as you type each character. Personally I find this distracting and unhelpful. Is there a way to get it to update/check _only_ on saved content? (I see there is a Check On Save option but that seems to control whether it runs `cargo check` on save, in _addition_ to existing check-on-every-keystroke behavior.)

**Comment by bjorn3** [comment]
No, rust-analyzer recomputes errors every time your editor requests them, just like pretty much every other language server. All editors I know of ask for the errors after every keystroke. (often with a small debounce delay) I don't think vscode has any way to configure this.

**Comment by viveksjain** [comment]
Thanks for the quick response! This should be controllable from the vscode extension itself right? The original rust extension offers this: https://github.com/rust-lang/vscode-rust/search?q=build_on_save&unscoped_q=build_on_save, although I don't know enough about vscode extensions to understand how that is plumbed through (there's only 2 matches?). Will see if I can figure it out later.

**Comment by viveksjain** [comment]
Ah looks like it's just propagated to rls https://github.com/rust-lang/rls/pull/422/files, although I don't know if same approach makes sense for rust-analyzer as well.

**Comment by bjorn3** [comment]
The RLS extension supports this only because RLS is much slower with getting errors. Rust-analyzer gives the results almost instantly while RLS needs to invoke rustc.

> The original rust extension offers this: https://github.com/rust-lang/vscode-rust/search?q=build_on_save&unscoped_q=build_on_save, although I don't know enough about vscode extensions to understand how that is plumbed through (there's only 2 matches?).

It is in RLS itself. Basically it prevents running rustc when the editor tells RLS about a changed file. It still record the new file contents in the vfs. https://github.com/rust-lang/rls/blob/7b0a20bf13b7061b1eb31a058117ac5517ff8cc9/rls/src/actions/notifications.rs#L115-L117 In rust-analyzer this is not as simple, as simply changing the vfs directly causes everything that has read from the file to be invalidated. There is no way around this.

**Comment by viveksjain** [comment]
I managed to get the behavior I want by simply tracking unsaved files on the server and suppressing PublishDiagnostics notifications for those files until the file is saved. Not sure if that would cause any issues but it's working well for me. Let me know if you would be interested in a PR, otherwise I'm fine closing this issue.

**Comment by lnicola** [comment]
@matklad any opinions here? I don't think we necessarily want this, though.

**Comment by matklad** [comment]
I think this can be emulated closely enough with 

```json
"rust-analyzer.diagnostics.enable": false,
"rust-analyzer.checkOnSave.enable": true
```

I don't think this feature will be a of end game (inline diagnostics should just work perfectly, which, admitedly, is very much not the case today), so I suggest closing this as having a work-around.

**Comment by viveksjain** [comment]
Ah thanks, that combination of options is a much simpler way to get the behavior I want.
