### ISSUE TITLE
Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by liuhangyu** [rust-analyzer/rust-analyzer#5986]
./rust-analyzer-linux --version
rust-analyzer 0275b08

code --version
1.49.0
e790b931385d72cf5669fcefc51cdf65990efa5d
x64

Failed to deserialize InitializeParams: missing field `requests`; {"capabilities":{"textDocument":{"callHierarchy":{"dynamicRegistration":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dynamicRegistration":true,"isPreferredSupport":true},"codeLens":{"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true},"completion":{"completionItem":{"commitCharactersSupport":true,"deprecatedSupport":true,"documentationFormat":["markdown","plaintext"],"preselectSupport":true,"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"contextSupport":true,"dynamicRegistration":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"documentHighlight":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"documentSymbol":{"dynamicRegistration":true,"hierarchicalDocumentSymbolSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"foldingRange":{"dynamicRegistration":true,"lineFoldingOnly":true,"rangeLimit":5000},"formatting":{"dynamicRegistration":true},"hover":{"contentFormat":["markdown","plaintext"],"dynamicRegistration":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"onTypeFormatting":{"dynamicRegistration":true},"publishDiagnostics":{"relatedInformation":true,"tagSupport":{"valueSet":[1,2]},"versionSupport":false},"rangeFormatting":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"selectionRange":{"dynamicRegistration":true},"semanticTokens":{"dynamicRegistration":true,"tokenModifiers":["declaration","documentation","static","abstract","deprecated","async","readonly"],"tokenTypes":["comment","keyword","number","regexp","operator","namespace","type","struct","class","interface","enum","typeParameter","function","member","macro","variable","parameter","property","label"]},"signatureHelp":{"contextSupport":true,"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true,"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true}},"window":{"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"documentChanges":true,"failureHandling":"textOnlyTransactional","resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"vscode","version":"1.49.0"},"initializationOptions":{"path":null,"releaseTag":"nightly"},"processId":18683,"rootPath":"/home/liuhy/learning/r-test/alg","rootUri":"file:///home/liuhy/learning/r-test/alg","trace":"verbose","workspaceFolders":[{"name":"alg","uri":"file:///home/liuhy/learning/r-test/alg"}]}
[Error - 20:42:56] Connection to server got closed. Server will not be restarted.

**Comment by liuhangyu** [comment]
vscode settings.json

	"rust.all_features": true,
	"rust-client.engine": "rust-analyzer",
	"rust-client.revealOutputChannelOn": "info",
	"rust-client.rustupPath": "$HOME/.cargo/bin/rustup",
	"rust-client.trace.server": "verbose",
	"rust-client.logToFile": false,
	"rust-client.autoStartRls": true,
	"rust-client.disableRustup": true,
	"rust-client.updateOnStartup": false,
	"rust.rustfmt_path": "$HOME/.cargo/bin/rustfmt",
	"rust.rust-analyzer.path": "$HOME/.local/bin/rust-analyzer-linux",
	"rust.rust-analyzer.releaseTag": "nightly",
	"rust.rust-analyzer": {}

**Comment by bjorn3** [comment]
Does it work with the latest version?

**Comment by ohmyarch** [comment]
Same, reinstalling is a workaround.

**Comment by mleonhard** [comment]
@ohmyarch Would you please explain clearly?  What did you reinstall and then rust-analyzer began working?

**Comment by mleonhard** [comment]
rust-analyzer release 2020-08-31 is working for me.  Newer versions have this crash.

**Comment by jonas-schievink** [comment]
I recommend using the official rust-analyzer plugin until we complete transition to rust-lang/vscode-rust.

**Comment by matklad** [comment]
I *think* this is fixed by updating the version of the rust-analyzer VS Code plugin. I *think* this is an upstream issue, but I haven't investigated this further: https://github.com/microsoft/language-server-protocol/commit/bdf50a1ae6fd06c4b1fbe142ac3e2c84fdccc4c5#r43152883.

**Comment by matklad** [comment]
SOmeone reported this being fixed by an update, so closing

**Comment by nathanshelly** [comment]
@matklad in what version is this supposed to be fixed? currently seeing the same issue on macOS with `rust-analyzer` extension version 0.2.297 and `rust-analyzer` binary version 2020-09-21.

Is there supposed to be an official release of the extension with this fixed or do I need to install from master somehow?
