### ISSUE TITLE
[VSCode] Support collapsing/folding block comments

### ISSUE THREAD

**Issue by rlabrecque** [rust-analyzer/rust-analyzer#5991]
After some investigation it seems like this may fall on rust-analyzer to hint to VSCode.

In the following screenshot I would only expect a single code folding arrow on line 45 and for this whole block to be collapsed from 45~61
![image](https://user-images.githubusercontent.com/2047188/93005513-8a78c180-f506-11ea-8b89-f2922632c852.png)

An alternative currently is to use the Explicit Folding, and set /* */ for rust.
https://marketplace.visualstudio.com/items?itemName=zokugun.explicit-folding

**Comment by matklad** [comment]
The relevant code and tests are here: https://github.com/rust-analyzer/rust-analyzer/blob/7dd09a7b34d7c9cc2739a1106b3e383b7d9044ff/crates/ide/src/folding_ranges.rs#L28

**Comment by Anthuang** [comment]
Has something changed recently to address this? I can't seem to reproduce this issue.

**Comment by lnicola** [comment]
Not really, but it does seem to work:

![image](https://user-images.githubusercontent.com/308347/97079076-b86b1e80-15f9-11eb-9547-38dd063becff.png)

@rlabrecque can you please test again?

**Comment by rlabrecque** [comment]
This does seem to be resolved when using v0.2.352!

I wish I documented what version I reported this issue with.

Any idea which change resolved it?

**Comment by lnicola** [comment]
I think the last change to that file was https://github.com/rust-analyzer/rust-analyzer/pull/5653, which seems unrelated.

**Comment by kjeremy** [comment]
I wonder how this broke in the first place. Fun fact: the initial implementation was my second PR and first feature contribution https://github.com/rust-analyzer/rust-analyzer/pull/79 to RA.

**Comment by matklad** [comment]
Wow, it's bean a while :-)
