### ISSUE TITLE
Two similar quick fixes on `variable does not need to be mutable` problem

### ISSUE THREAD

**Issue by avrong** [rust-analyzer/rust-analyzer#5994]
When a problem is present, quick fix on the related code shows two (identical, I guess) quick-fixes: `remove this mut` from rustc and `Remove mut keyword` from rust-analyzer.

<img width="300" src="https://user-images.githubusercontent.com/6342851/93013993-d9316480-f5b5-11ea-88ba-955386447f1d.png">

```rust
fn main() {
    let mut s = String::new();
    println!("{}", s);
}
```

**Comment by matklad** [comment]
Yeah, this is sort-of how the things work today. We intentionally dont' try to be smart when merging native and  cargo check diagnostics. Long term, this'll be fixed by subsuming cargo check.
