### ISSUE TITLE
Incorrect "operation requires unsafe block"

### ISSUE THREAD

**Issue by RalfJung** [rust-analyzer/rust-analyzer#5996]
When using rust-analyzer with the standard library, it shows an error for this code in `sore/src/ptr/const_ptr.rs`:
```rust
    pub const fn guaranteed_eq(self, other: *const T) -> bool
    where
        T: Sized,
    {
        intrinsics::ptr_guaranteed_eq(self, other)
    }
```
It says this needs an unsafe block, but it evidently does not as the code compiles fine. Indeed, `ptr_guaranteed_eq` is a safe intrinsic.

**Comment by bjorn3** [comment]
rust-analyzer doesn't have a list of safe intrinsics. It just assumes that all are unsafe.

**Comment by RalfJung** [comment]
Yeah, I figured. That assumption is incorrect, though.

**Comment by matklad** [comment]
We need to figure out how rustc distinguish between safe and unsafe intrinsics and do the same.

**Comment by RalfJung** [comment]
rustc essentially has a whitelist of safe intrinsics, the rest is unsafe:

https://github.com/rust-lang/rust/blob/c6e4db620a7d2f569f11dcab627430921ea8aacf/compiler/rustc_typeck/src/check/intrinsic.rs#L68

**Comment by matklad** [comment]
Ok, I think we need then to hack this around here:

https://github.com/rust-analyzer/rust-analyzer/blob/7dd09a7b34d7c9cc2739a1106b3e383b7d9044ff/crates/hir_def/src/item_tree/lower.rs#L558

We need to check that we are in `extern "rust-intrinsics"` block syntatically, and then look at he names

**Comment by Rudxain** [comment]
`std::env::set_var` is detected as `unsafe` by RA 1.80.0 (0514789 2024-07-21)

**Comment by RalfJung** [comment]
That is a true fact. Not sure why you are stating that fact in this long-closed issue, though. If you think something is wrong, please open a new issue and explain why you think something is wrong. (However, `set_var` being declared unsafe is not a bug, it is a feature. if you are confused about why it is unsafe, I suggest asking on [IRLO](https://internals.rust-lang.org/) or Zulip.)

**Comment by Rudxain** [comment]
Wait, then why does this compile?:
https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/blob/413634eca8a76f71801a8b4ec9d94d6bfd426791/src/gui/views/list.rs#L846

The call isn't wrapped in `unsafe`, and the `async` function isn't `unsafe` either.

This seems like an unsound compiler bug

**Comment by Lazerbeak12345** [comment]
> If you think something is wrong, please open a new issue and explain why you think something is wrong

**Comment by RalfJung** [comment]
In this case, better to ask on Zulip/IRLO as nothing is wrong here. But please stop the off topic posting in this issue.
