### ISSUE TITLE
[VSCode] Distracting text in bottom bar when typing

### ISSUE THREAD

**Issue by adroitwhiz** [rust-analyzer/rust-analyzer#6000]
This is semi-related to https://github.com/rust-analyzer/rust-analyzer/issues/5984, but is more specific.

Running rust-analyzer "live" (as you type) is fine in my opinion, but every time it runs, it indicates it along the bottom of the window, meaning that text there rapidly flickers whenever you type anything:
![Peek 2020-09-14 09-48](https://user-images.githubusercontent.com/25993062/93094219-9f249900-f66f-11ea-85fd-eb865139d770.gif)
This is extremely distracting.

**Comment by kiljacken** [comment]
You wouldn't happen to be running with autosave enabled in VSCode? I believe this is a bad interaction between our cargo check (flycheck) running on save, and autosave triggering each time you write something.

**Comment by adroitwhiz** [comment]
Autosave is disabled:
![image](https://user-images.githubusercontent.com/25993062/93108546-ec5d3680-f680-11ea-8617-c8f0f2cff812.png)

**Comment by kiljacken** [comment]
Hmm, the `Rust: ` status item that is producing the noisy output is not part of rust-analyzer. Are you running any other rust related VSCode extensions?

**Comment by adroitwhiz** [comment]
Looks like this is an issue with https://github.com/rust-lang/vscode-rust/

**Comment by kiljacken** [comment]
Okay, please report it there then :) Glad we could narrow it down.
