### ISSUE TITLE
Function completion description includes whitespace between arguments

### ISSUE THREAD

**Issue by YaLTeR** [rust-analyzer/rust-analyzer#6002]
rust-analyzer 0d03fe6

LanguageClient-neovim:

![image](https://user-images.githubusercontent.com/1794388/93097123-d6b23600-f6ad-11ea-8cd3-6bf7c34cb0a9.png)

VSCode:

![image](https://user-images.githubusercontent.com/1794388/93097194-edf12380-f6ad-11ea-9298-2f5cebc00705.png)

Test code:
```rust
fn foo(
    a: i32,
    b: i32,
) {
}

fn main() {
    
}
```

**Comment by bnjjj** [comment]
Will fix it this week
