### ISSUE TITLE
Massive Performance Degradation With Nightly

### ISSUE THREAD

**Issue by hammypants** [rust-analyzer/rust-analyzer#6004]
Windows 10. v1809.

`rust-analyzer version: nightly (7ba578a)`

```
$ code --version
1.49.0
e790b931385d72cf5669fcefc51cdf65990efa5d
x64
```

```
  "[rust]": {
    "editor.defaultFormatter": "matklad.rust-analyzer"
  },
  "rust-analyzer.trace.extension": true,
  "rust-analyzer.trace.server": "verbose",
  "rust-analyzer.updates.channel": "nightly",
  "rust-analyzer.checkOnSave.command": "clippy",
```

Was not present in the nightly from Sept 13th.

Virtually all `textDocument/semanticTokens/{*}` and `textDocument/codeAction`:

```
[Trace - 12:20:58 AM] Received response 'textDocument/codeAction - (15)' in 6422ms. Request failed: canceled by client (-32800).
[Trace - 12:20:58 AM] Received response 'textDocument/semanticTokens/range - (12)' in 10520ms. Request failed: canceled by client (-32800).
[Trace - 12:20:58 AM] Received response 'textDocument/semanticTokens/range - (13)' in 10045ms. Request failed: canceled by client (-32800).
[Trace - 12:20:58 AM] Received response 'textDocument/semanticTokens/range - (14)' in 9754ms. Request failed: canceled by client (-32800).
[Trace - 12:20:58 AM] Received response 'textDocument/semanticTokens/range - (16)' in 6163ms. Request failed: canceled by client (-32800).
...
...
[Trace - 12:22:24 AM] Received response 'textDocument/semanticTokens/full - (6)' in 103737ms.
```

When doing... basically anything. The above was from typing `.` before the debounce. Startup is also impacted.

EDIT: Also had `RA_LOG=info` set.

**Comment by lnicola** [comment]
Is it still slow if you disable the tracing settings?

**Comment by hammypants** [comment]
Disabled everything:
```
 "rust-analyzer.trace.extension": false,
  "rust-analyzer.trace.server": "off",
  "rust-analyzer.updates.channel": "nightly",
  "rust-analyzer.checkOnSave.command": "clippy",
```
and unset `RA_LOG`... nadda.

**Comment by jonas-schievink** [comment]
I can't measure any perf regression in startup or type inference time between fda6937d7f91dc723229d1045d9a57b22a846dc7 and current master (7ba578ab1413505e960dda305cc322a29bc00ab3). Are you sure that startup is impacted?

I could imagine https://github.com/rust-analyzer/rust-analyzer/pull/5976 causing perf problems when completing items, so I've opened a revert at https://github.com/rust-analyzer/rust-analyzer/pull/6005. Would be great if you could test that.

**Comment by hammypants** [comment]
#6010 brought performance back to Earth. Thanks again. Closing.
