### ISSUE TITLE
[FEATURE REQUEST] Option to suppress adding URLs to hover document

### ISSUE THREAD

**Issue by flw-cn** [rust-analyzer/rust-analyzer#6014]
In vim, the URL in the hover document given by RA is actually unclickable because the popup window does not capture focus. However, the presence of these URLs can affect the sentence flow of the document text.

I know there's a feature in vim called conceal that hides them, but since URLs are usually long, actually hiding them leaves a huge black hole, like this:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5546718/93285021-85698a00-f806-11ea-911d-e77fea4a47f0.png">

I looked at the source code for these modules and found that the original documentation comments did not contain URLs, so they should have been added actively by rust-analyzer.

I know that some GUI editors like vscode have this feature that is very useful, as they often have an integrated browser that can easily display what the link is pointing to. But in other term-based editors, actually opening the URL is not very convenient and breaks the train of thought.

So is it possible to request an option to turn this feature off?

**Comment by bjorn3** [comment]
The documentation does contain urls. For example ``[`String`]`` turns into a link because there is a ``[`String`]: <the url>`` at the bottom.

**Comment by flw-cn** [comment]
So, since it is at the bottom of the document, is it possible to still keep it at the bottom? Just add an option to give those who need it a choice.

**Comment by flw-cn** [comment]
I tried to make a few small changes myself and things look much better now. If my suggestions are accepted, I'll improve it so that it can be merged in via PR.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5546718/93297751-7f82a180-f824-11ea-9d09-0f5f437dd489.png">

**Comment by flodiebold** [comment]
This seems like an editor issue to me, unless we're sending these links in a non-markdown context?

**Comment by bjorn3** [comment]
When rewriting links I think the markdown is canonicalized to always use `[text](link)` instead of `[text]` and `[text]: link`

https://github.com/rust-analyzer/rust-analyzer/blob/e7da5816d67fadc056ee43310f9d04164c2617d9/crates/ide/src/link_rewrite.rs#L41-L46

**Comment by bjorn3** [comment]
`pulldown-cmark` doesn't distinguish between the two ways of writing a link. It always uses `Tag::Link` with a mandatory url: https://docs.rs/pulldown-cmark/0.8.0/pulldown_cmark/enum.Tag.html#variant.Link `pulldown-cmark-to-cmark` then emits `[text](link)`: https://docs.rs/pulldown-cmark-to-cmark/5.0.0/src/pulldown_cmark_to_cmark/lib.rs.html#325-331

**Comment by kjeremy** [comment]
FYI we only ever send markdown back (we do not honor the client caps here). We should probably have different behavior if sending back text. See #4326

**Comment by flw-cn** [comment]
It just works now. I cordially invite @bjorn3, @flodiebold, and @kjeremy to review my changes and hope to merge them with your help.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5546718/94332256-2e359780-0006-11eb-9724-1aed14130d0d.png">

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/5546718/94332275-558c6480-0006-11eb-8117-e94e2158c9d0.png">
