### ISSUE TITLE
[VSCode]: When I debug a unit testcase with Hahsmap.insert lines, error thrown when using the Debug button

### ISSUE THREAD

**Issue by selvavm** [rust-analyzer/rust-analyzer#6015]
Hi All,

I am new to unit testing in Rust and I have written couple of unit tests. I am able to debug by clicking on the debug button at the top of the test function except one test. This test function contains Hashmap.insert and below is the error thrown by VSCode

![image](https://user-images.githubusercontent.com/16543422/93291119-e3df3a00-f7ff-11ea-87a7-b4bd65e0a175.png)

The error is strange because I am not stepping into the insert command and infact, I have set the breakpoint after this command.

I am using cppvsdbg

**Comment by selvavm** [comment]
Update: This happens only with cppvsdbg and not with lldb

**Comment by matklad** [comment]
Unclear whats' going on here. But, if this happens only with one backend, might it be an upstream issue?

**Comment by matklad** [comment]
Closing: I don’t see any next steps here, and it seems that the error comes out from the debugger, not rust-analyzer itself? rust-analyzer doesn’t do debugging at the moment, it just forwards to debugger extension
