### ISSUE TITLE
Incorrect renaming if multiple identifiers appear on the same line

### ISSUE THREAD

**Issue by kneasle** [rust-analyzer/rust-analyzer#6039]
Suppose that we have an identifier that is used multiple times on the same line, as in the following file (`x` will be renamed):
```rust
fn main() {
    let x = 0;
    let longer_variable = 1;
    println!("{} {} {} {} {}", x, longer_variable, x, longer_variable, x);
}
```
and we rename that identifier to something that changes the length (in this case we rename it to `YYYYYYY`) we get the following file:
```rust
fn main() {
    let YYYYYY = 0;
    let longer_variable = 1;
    println!("{} {} {} {} {}", YYYYYY, longer_variaYYYYYYle, x, longer_YYYYYYariable, x);
}
```

The renaming function has clearly found the instances of `x` (correctly), but it has has replaced them _by index_ from left to right.  Therefore, it has missed the 2nd instance of `x` by 5 chars and the second instance of `x` by 10 chars and replaced the corresponding parts of the text.  This means that whenever this occurs you have to fix these instances by hand, which usually takes longer than doing a basic text substitution.

This would be fixed if the substrings were replaced in _reverse_ (right to left) order, since then the indices would still be valid.

I'm quite happy to make a PR for this myself (if someone points me in the right direction code-wise), but I have exams in a few weeks and need to revise :cry: so I won't be able to sink lots of time into it.

P.S. Loving rust-analyzer - it's so much better than every other language server I've seen `:)`.

P.P.S. I'm using latest `rust-analyzer` with `coc` and `neovim` on Linux Mint - I can get exact versions when I get back to my laptop.

**Comment by kneasle** [comment]
Thinking about it, this might not be a problem with `rust-analyzer` - I don't have any other (decent) language servers installed so I can't test if others do the same thing.

**Comment by lnicola** [comment]
I can't reproduce this in Code.

**Comment by kneasle** [comment]
OK that kinda makes sense - thinking about it, I find it unlikely that language servers would be responsible for editing text directly, so this is more likely a problem of `CoC` or `neovim`.  I'll do some more digging... thanks for checking this out though!

**Comment by lnicola** [comment]
For the record, we seem to return this:

```
[Trace - 22:41:18] Received response 'textDocument/rename - (197)' in 2ms.
Result: {
    "documentChanges": [
        {
            "edits": [
                {
                    "newText": "yyyy",
                    "range": {
                        "end": {
                            "character": 9,
                            "line": 1
                        },
                        "start": {
                            "character": 8,
                            "line": 1
                        }
                    }
                }
            ],
            "textDocument": {
                "uri": "file:///home/me/Projects/hello/src/main.rs",
                "version": 26
            }
        },
        {
            "edits": [
                {
                    "newText": "yyyy",
                    "range": {
                        "end": {
                            "character": 32,
                            "line": 4
                        },
                        "start": {
                            "character": 31,
                            "line": 4
                        }
                    }
                }
            ],
            "textDocument": {
                "uri": "file:///home/me/Projects/hello/src/main.rs",
                "version": 26
            }
        },
        {
            "edits": [
                {
                    "newText": "yyyy",
                    "range": {
                        "end": {
                            "character": 52,
                            "line": 4
                        },
                        "start": {
                            "character": 51,
                            "line": 4
                        }
                    }
                }
            ],
            "textDocument": {
                "uri": "file:///home/me/Projects/hello/src/main.rs",
                "version": 26
            }
        },
        {
            "edits": [
                {
                    "newText": "yyyy",
                    "range": {
                        "end": {
                            "character": 72,
                            "line": 4
                        },
                        "start": {
                            "character": 71,
                            "line": 4
                        }
                    }
                }
            ],
            "textDocument": {
                "uri": "file:///home/me/Projects/hello/src/main.rs",
                "version": 26
            }
        }
    ]
}
```

I'm not sure how returning multiple changes is different from returning multiple edits.

**Comment by kneasle** [comment]
OK so this tracks down the problem to be that of CoC.  CoC is treating the individual changes as atomic actions and applying them one after another (causing the ranges of later edits to become invalid) whereas Code is merging them and assuming that the ranges refer to the original document.  According to the LSP specification Code's implementation is correct and CoC's is wrong, so no changes are required here.
