### ISSUE TITLE
Autofix Missing Module Does Not Work On Vim With Coc

### ISSUE THREAD

**Issue by brunoczim** [rust-analyzer/rust-analyzer#6040]
Steps to reproduce:

1. Create a rust project `cargo new  --lib mytest`.
2. Put this in `src/lib.rs`:
```rust
mod child;
```
3. Put this in `src/child.rs`:
```rust
mod grandchild;
```
4. Put the cursor over `mod grandchild;` and execute (inside Vim) `:execute ":normal \<Plug>(coc-fix-current)"`.
5. Confirm.
6. This is going to happen:
![image](https://user-images.githubusercontent.com/18701450/93690651-4b6fe080-fab1-11ea-9119-dc6cc2a2ad7c.png)

**Comment by bjorn3** [comment]
rust-analyzer tells coc to create `src/child/grandson.rs` this requires creating `src/child` first, which coc doesn't do I think. The lsp spec doesn't seem to specify if you must first create a directory or that directories are automatically created for you as necessary. https://microsoft.github.io/language-server-protocol/specifications/specification-current/#resourceChanges

**Comment by matklad** [comment]
Closing as upstream issue!
