### ISSUE TITLE
wrong formatting of generated rust-doc inline text block

### ISSUE THREAD

**Issue by extrawurst** [rust-analyzer/rust-analyzer#6045]
we recently added a ton of inline documentation in [godot-rust](https://github.com/godot-rust/godot-rust) for example:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/776816/93739979-e075f500-fbe9-11ea-9dc3-d26082995853.png">

these are compile time generated using proc-macros. unfortunately for the time being all these have to be wrapped into ` ```text ` blocks but rust-analyzer then shows `text` in the beginning of each of these:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/776816/93740066-0b604900-fbea-11ea-804e-8c10efe5113e.png">

oddly enough this does only happen for `#[doc = #doc_comment]` generated comments of this sort

**Comment by matklad** [comment]
The relevant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/3a38554f86e5e1b41b111ed8ccc688e84a9d5ae4/crates/ide/src/hover.rs

**Comment by Veykril** [comment]
`#[doc = "```text\nfoo\n```"]` shows `foo` for me on hover so I think this got fixed when we moved doc handling to the HIR
