### ISSUE TITLE
Rename fails weirdly

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#6046]
```rust
fn main() {
    let yyyy = 2;
    let yyyy = 1;
    let longer_variable = 1;
    println!("{}", yyyy);
}
```

If I try to rename the `yyyy` to `x`, it fails. But it works if I remove the `longer_variable` line or the second definition of `yyyy`.

**Comment by JoshMcguigan** [comment]
I am not able to re-create this on the latest stable release of rust-analyzer. Using the example provided above, if I rename the first `yyyy` rust-analyzer renames only that single usage as I'd expect. Renaming the second `yyyy` renames both the declaration and the usage in the `println`. I don't see a failure in either case.

@lnicola are you still able to recreate this issue?

**Comment by lnicola** [comment]
Yeah, it seems to work now. I wonder what fixed this. Thanks for testing again.
