### ISSUE TITLE
Format on save fails quietly if rustfmt is not installed for the current toolchain

### ISSUE THREAD

**Issue by Skasselbard** [rust-analyzer/rust-analyzer#6052]
System: Ubuntu 18.04 with VS-Code
**Observed**: format on save does not work when rustfmt is not installed for the current toolchain
**Expected**: Either some kind of (additional) feedback that formatting failed (e.g. a pop up in vs-code) or an automatically triggered installation of rustfmt

Actually the log of the language server already prints a message that rustfmt is not installed for the current toolchain. But I would argue that an additional pop-up would be a better solution, since the first impulse (meaning my first impulse^^) is to check the settings (followed by confusion and resignation) instead of checking the log.

**Comment by stanciuadrian** [comment]
The current "master" already shows a popup: "A request has failed. See the output for more information. Source: rust-analyzer (Extension). [Go to output button]".

L735 is failing when rustfmt is not installed (thanks @matklad !). I could try to add some error handing to override that generic message.

**Comment by matklad** [comment]
I *think* "A request has failed" is a low-level error from the protocol. There might be some way to render an error in a nicer way here, but I am not sure.
