### ISSUE TITLE
Unresolved import for declarative macros 2.0

### ISSUE THREAD

**Issue by fmease** [rust-analyzer/rust-analyzer#6059]
Since #6016. Importing a [declarative macro 2.0](https://github.com/rust-lang/rust/issues/39412) (an experimental feature) is falsely flagged as unresolved.

Minimal example to reproduce:

```rust
#![feature(decl_macro)]

use foo as _; // error: unresolved import
macro foo() {}

fn main() {}
```

If I am not mistaken, RA itself already handles declarative macros 2.0 in some places and it is in fact not _rustc_ which resolves them:

```rust
#![feature(decl_macro)]

foo!(); // RA's name resolver can handle this
macro foo() {}

fn main() {}
```

**Comment by fmease** [comment]
This is probably low priority for most people but I can try to give it a go in a week, once I have spare time, unless someone else would like to fix this.

**Comment by jonas-schievink** [comment]
Yeah we don't support them at the moment. We have some hacks in place so that builtin macros from the standard library still work.

**Comment by fmease** [comment]
If I may ask, do you think there is enough information in the code base already that improving support is relatively easy? Is it even acceptable to implement for RA given it's an unstable/experimental feature?

At first glance, it seems like [`ModCollector::collect`](https://github.com/rust-analyzer/rust-analyzer/blob/4ddb8124b01a04adcc7d42444f7ca8d377bb60ae/crates/hir_def/src/nameres/collector.rs#L848) is the place to start, am I correct? Extending it to handle a new `ModItem::Macro` and going from there.

**Comment by jonas-schievink** [comment]
Yeah it should be fine to add support for them

**Comment by fmease** [comment]
FYI, the overarching issue is #2248. However in my opinion, this issue (#6059) should not be closed in favor of the other one since it is specifically about error messages which should not be reported and which weren't reported before. Further, a fix of this issue would not necessarily mean declarative macros 2.0 would then be "fully" supported by rust analyzer.

**Comment by matklad** [comment]
works on master
