### ISSUE TITLE
Rust analyzer causes vim to freeze after a `rustup update`

### ISSUE THREAD

**Issue by vext01** [rust-analyzer/rust-analyzer#6066]
Hi,

I'm working on a [fork of rust](https://github.com/softdevteam/ykrustc) and I use Neovim with vim-lsp set up to use rust-analyzer. I thought I'd be able to set `RUST_SRC_PATH` to the `library` directory of my fork and carry on as usual. However, opening certain files causes vim to freeze for 40 seconds at a time, during which time neovim uses 100% CPU.

[At first I thought it was vim-lsp's fault](https://github.com/prabirshrestha/vim-lsp/issues/909), but having done some debugging, it actually looks like rust-analyzer is swamping neovim with a large stream of errors which it is attempting to read via a pipe (see the link for examples of the kinds of error I see). There's a vimscript loop in vim-lsp which does this, and it appears to be the cause of the freezes.

If I edit the same problematic files on a fresh clone of upstream rust-lang, then there are no freezes.

So I guess this is a problem to do with analyzing incompatible (with the default toolchain) forks of Rust?

I don't have the rust-src component installed. I wasn't expecting to need it as I'd be setting `RUST_SRC_PATH`.

My fork makes no syntactic changes to Rust, but it does contain a modified codegen and has different lang items etc. This must be the source of the errors.

Many thanks!

**Comment by vext01** [comment]
(Happy to provide a full vim-lsp log if that would help)

**Comment by bjorn3** [comment]
https://rustc-dev-guide.rust-lang.org/building/suggested.html

You may want to use the following config:

```jsonc
{
    "rust-analyzer.checkOnSave.overrideCommand": [
        "./x.py",
        "check",
        "--json-output"
    ],
    "rust-analyzer.rustfmt.overrideCommand": [
      "./build/TARGET_TRIPLE/stage0/bin/rustfmt"
    ],
}
```

**Comment by vext01** [comment]
That goes in `<source-dir>/.vscode/settings.json`, right?

I've tried putting that there and also in $HOME, but the result is the same.

Is `TARGET_TRIPLE` literal, or do I replace it with the system's triple?

**Comment by bjorn3** [comment]
You need to replace `TARGET_TRIPLE` it with the system's triple. That config is only relevant if you want the format file command to work. For `vim-lsp`  it seems that you need to put it in `'config'` when calling `lsp#register_server`. https://github.com/mattn/vim-lsp-settings/blob/6366cc52ad97f96bce5e544afa7e2b8f9359edd9/settings/rust-analyzer.vim#L10

**Comment by vext01** [comment]
For whatever reason, blasting away `~/.rustup` and reinstalling it seems to have solved the problem. I didn't need to provide a vscode config either (does rust-analyzer look for `x.py` automatically now, I wonder).

Odd...

**Comment by vext01** [comment]
So, I did a `rustup update` on my rust nightly yesterday, and now the freeze ups are back.

Is rust-analyzer caching something which is incompatible with newer versions of rust or something?

**Comment by vext01** [comment]
Again, nuking `~/.rustup` and reinstalling fixes it.

**Comment by vext01** [comment]
Is there a way I can invoke rust-analyzer outside of vim to try an narrow down the problem?

`RUST_SRC_PATH` is set to the `library` sub-directory of my compiler clone.

In `.vscode/settings.json` I have:
```
{
    "rust-analyzer.checkOnSave.overrideCommand": [                                                        
        "./x.py",
        "check",
        "--json-output"
    ],
    "rust-analyzer.rustfmt.overrideCommand": [
        "./build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt"
    ],
    "editor.formatOnSave": true
}
```

I'm using rust-analyzer master branch as of today, and neovim master branch as of yesterday.

**Comment by bjorn3** [comment]
You can try `rust-analyzer-linux analysis-stats .`

**Comment by vext01** [comment]
Thanks Bjorn.

Here's what happens:
```
$ rust-analyzer analysis-stats .
[ERROR project_model] cyclic dependency cargo-test-support -> cargo
[ERROR project_model] cyclic dependency rustc-std-workspace-core -> core
[ERROR project_model] cyclic dependency wasi -> rustc-std-workspace-alloc
Database loaded 546.67ms, 798mi

Crates in this dir: 151
Total modules found: 2340
Total declarations: 42359
Total functions: 32639
Item Collection: 29.19s, 219099mi
5241/32639 16% processing: build::expr::as_constant::expr_as_constant
```

It does that for a while and then eventually gives this:
```
22999/32639 70% processing: string::test_drain_end_overflowthread 'main' panicked at 'var_universe invoked on bound variable', /home/vext01/.cargo/registry/src/github.com-1ecc6299db9ec823/chalk-solve-0.33.0/src/infer.rs:157:41
stack backtrace:
   0: std::panicking::begin_panic
   1: chalk_solve::infer::unify::Unifier<I>::unify_ty_ty
   2: <chalk_ir::Substitution<I> as chalk_ir::zip::Zip<I>>::zip_with
   3: chalk_ir::_DERIVE_chalk_ir_zip_Zip_I_FOR_WhereClause::<impl chalk_ir::zip::Zip<I> for chalk_ir::WhereClause<I>>::zip_with                                                                                    
   4: chalk_solve::infer::unify::<impl chalk_solve::infer::InferenceTable<I>>::unify
   5: chalk_recursive::fulfill::Fulfill<I,Solver,Infer>::new_with_clause
   6: chalk_recursive::recursive::Solver<I>::solve_new_subgoal
   7: <chalk_recursive::recursive::Solver<I> as chalk_recursive::solve::SolveDatabase<I>>::solve_goal
   8: <chalk_recursive::recursive::RecursiveSolver<I> as chalk_solve::solve::Solver<I>>::solve_limited
   9: hir_ty::traits::trait_solve_query
  10: salsa::runtime::Runtime::execute_query_implementation
  11: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  12: salsa::derived::slot::Slot<Q,MP>::read
  13: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  14: <DB as hir_ty::db::HirDatabase>::trait_solve::__shim
  15: <DB as hir_ty::db::HirDatabase>::trait_solve
  16: hir_ty::infer::InferenceContext::resolve_ty_as_possible
  17: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  18: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
  19: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_method_call
  20: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  21: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  22: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  23: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  24: hir_ty::infer::infer_query
  25: salsa::runtime::Runtime::execute_query_implementation
  26: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  27: salsa::derived::slot::Slot<Q,MP>::read
  28: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  29: <DB as hir_ty::db::HirDatabase>::infer_query::__shim
  30: hir_ty::db::infer_wait
  31: rust_analyzer::cli::analysis_stats::AnalysisStatsCmd::run
  32: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

It takes a minute or so to get that far. Is that the expected behaviour?

**Comment by vext01** [comment]
That was in the root of my rust fork. I tried in the `library` subdir too and got the same.

**Comment by bjorn3** [comment]
This is a chalk bug

cc @flodiebold

**Comment by flodiebold** [comment]
Is this with current rust-analyzer master?

**Comment by vext01** [comment]
> Is this with current rust-analyzer master?

Yes, as of today. I did `git pull && cargo clean && cargo xtask install`.

Is this likely to be the same issue as the freeze I'm seeing in nvim?

**Comment by flodiebold** [comment]
I don't know, you should see the same stacktrace in the rust-analyzer logs from running nvim if that's the case.
