### ISSUE TITLE
Renaming only works for item under cursor

### ISSUE THREAD

**Issue by sharksforarms** [rust-analyzer/rust-analyzer#6067]
Using neovim and built-in LSP.

It seems like renaming only works once in the file?

![Peek 2020-09-23 13-57](https://user-images.githubusercontent.com/10912917/94053943-f4b42080-fda8-11ea-9d95-99c1de5e9648.gif)

neovim lsp log: https://gist.github.com/sharksforarms/04d9eb956465d03b6f492420254a1239

**Comment by lnicola** [comment]
Works for me in Code:

![image](https://user-images.githubusercontent.com/308347/94054165-f222ec80-fde3-11ea-9cce-0799f6ee4d45.png)

**Comment by lnicola** [comment]
Could this be an instance of https://github.com/rust-analyzer/rust-analyzer/issues/6039?

**Comment by sharksforarms** [comment]
Actually it looks like it could be neovim? 

[It's printing this log message out](https://github.com/neovim/neovim/blob/f34eeba2d85b4382d7504e1f3e12a7afb0788c1d/runtime/lua/vim/lsp/util.lua#L220), which returns before applying the text. If I comment it out, it works...

**Comment by chisade** [comment]
I have the exact same problem. 
https://github.com/rust-analyzer/rust-analyzer/blob/bcdedbb3d5a45ea974cc5f8e9068e9604c43a757/crates/rust-analyzer/src/handlers.rs#L617
and 
https://github.com/rust-analyzer/rust-analyzer/blob/bcdedbb3d5a45ea974cc5f8e9068e9604c43a757/crates/rust-analyzer/src/handlers.rs#L635
are probably entry points for this issue, right?

**Comment by chisade** [comment]
> Actually it looks like it could be neovim?
> 
> [It's printing this log message out](https://github.com/neovim/neovim/blob/f34eeba2d85b4382d7504e1f3e12a7afb0788c1d/runtime/lua/vim/lsp/util.lua#L220), which returns before applying the text. If I comment it out, it works...
> 
> [neovim/neovim#12970](https://github.com/neovim/neovim/issues/12970)

I can confirm this. Seems to be the only thing that is keeping the replacement from working.

**Comment by lnicola** [comment]
@chisade they are, but I'd start by tracing the communication at the LSP level. If RA sends the wrong document version, it should be visible in the trace.

**Comment by sharksforarms** [comment]
> @chisade they are, but I'd start by tracing the communication at the LSP level. If RA sends the wrong document version, it should be visible in the trace.

LSP logs included in gist, is this what you mean?

**Comment by lnicola** [comment]
Yes, sorry, I didn't look at the linked issue.

**Comment by sharksforarms** [comment]
```
[ DEBUG ] 2020-09-23T14:22:40-0400 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:361 ]	"rpc.send.payload"

{
   id = 5,
   "jsonrpc =""2.0",
   "result ="{
      "documentChanges ="{
         {
            "edits ="{
               {
                  "newText =""my_var",
                  "range ="{
                     "end ="{
                        character = 9,
                        line = 1
                     },
                     "start ="{
                        character = 8,
                        line = 1
                     }
                  }
               }
            },
            "textDocument ="{
               "uri =""file:///tmp/tester/src/main.rs",
               version = 0
            }
         },
         {
            "edits ="{
               {
                  "newText =""my_var",
                  "range ="{
                     "end ="{
                        character = 13,
                        line = 3
                     },
                     "start ="{
                        character = 12,
                        line = 3
                     }
                  }
               }
            },
            "textDocument ="{
               "uri =""file:///tmp/tester/src/main.rs",
               version = 0
            }
         }
      }
   }
}
```

Note: I'm not at all familiar with LSP, are the version numbers suppose to be increasing?

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#versionedTextDocumentIdentifier

Both `version` are set to `0` is this correct?

**Comment by kjeremy** [comment]
This is most likely a dup of #4901

**Comment by matklad** [comment]
Yeah, pretty sure that this duplicates #4901
