### ISSUE TITLE
`/` isn't being linked to `Div<>` implementation (for `std::time::Duration`)

### ISSUE THREAD

**Issue by woody77** [rust-analyzer/rust-analyzer#6069]
RA isn't finding the `impl Div<u32> for Duration` implementation for the `/` operator.  Directly calling `div(...)`  works, if it's brought into the scope with `use std::ops::Div`.

In the examples below, `update_check_start_time` is an `Instant`:

<img width="537" alt="Screen Shot 2020-09-23 at 2 38 33 PM" src="https://user-images.githubusercontent.com/17480512/94072639-ebc44e80-fdaa-11ea-8f07-80791a0dc9b2.png">

**Comment by kiljacken** [comment]
Please see #2454
