### ISSUE TITLE
Don't needlessly unnnest imports

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#6071]
If we auto-import `File`  in this code

```rust
use std::{fs::{self}};

fn main()  {
    let _: File = todo!();
}
```
we get

```rust
use std::{fs::{self}};
use fs::File;
```

Instead, we should get `use std::{fs::{self, File}};`

I think the bug is in this function:

https://github.com/rust-analyzer/rust-analyzer/blob/4ddb8124b01a04adcc7d42444f7ca8d377bb60ae/crates/hir_def/src/find_path.rs#L19-L23

It returns (but this needs to be double checked) `fs::File` for the above example, rather than `std::fs::File`

**Comment by flodiebold** [comment]
Hmm. I think the behavior from `find_path` is correct, when we want to qualify paths we do want to use already-imported modules.

**Comment by matklad** [comment]
Hm, yeah, that is also true... Should it return a pair of path and an index?

**Comment by flodiebold** [comment]
I feel like `find_path` is the wrong level to fix this at. This seems like a consideration specific to auto-import to me. I don't understand your suggestion yet though, what would the index be?

**Comment by matklad** [comment]
>I don't understand your suggestion yet though, what would the index be?

So, `find_path` will return both the full path, as well as path prefix. 

>This seems like a consideration specific to auto-import to me.

I am not entirely sure, for two reasons:

* First, it seems like auto-import would need to re-derive some info? When we are looking for `File`, we get `std::fs::File` path first, and then shorten it in `find_import`. Auto-import would then need to effectively lengthen it to `std::fs::File` back
* There are case like

```rust
use std::fs; // module
use lol::fs; // a macro or a const
```

Auto-import would need to decide which `fs` to append to... Although the latter problem might be there even with the my suggested setup?
