### ISSUE TITLE
rust-analyzer failed to discover workspace (vsCode)

### ISSUE THREAD

**Issue by causticroot** [rust-analyzer/rust-analyzer#6079]
(rust beginner) After installing the rust-analyzer, I get this output from vscode:

`rust-analyzer failed to discover workspace`

My versions:
```
rustup 1.22.1 (b01adbbc3 2020-07-08)
cargo 1.46.0 (149022b1d 2020-07-17)
```
output of `rustup default` :
`stable-x86_64-unknown-linux-gnu (default)`

output of `rustup --print sysroot` :
`/home/causticroot/.rustup/toolchains/stable-x86_64-unknown-linux-gnu`

Ive run `rustup comonent add rust-src`, output:
`info: component 'rust-src' is up to date`

output of `ls` on  `(rustc --print sysroot)/lib/rustlib/src/rust/src`
`build_helper  liballoc  libcore  libpanic_abort  libpanic_unwind  libproc_macro  libprofiler_builtins  libstd  libterm  libtest  libunwind  stdarch  tools`
```
~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src> cd $(rustc --print sysroot)/lib/rustlib/src/rust
~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust> ls
Cargo.lock  src
```

output of `>Rust Analyzer:Status`: 
`Command 'Rust Analyzer: Status' resulted in an error (cannot open rust-analyzer-status://status. Detail: Rust Analyzer is still loading...)`

output of `>Rust Analyzer:Show RA Version`
`rust-analyzer version: 2020-09-21 (e70cf70)`

Please flag me if information is missing or if any information is wrong, I'm new to rust and I really want to understand and help solve the bug

**Comment by bjorn3** [comment]
What is the workspace layout? Where are there `Cargo.toml` files?

**Comment by causticroot** [comment]
![image](https://user-images.githubusercontent.com/66440299/94331298-bafa3a00-ffa1-11ea-99b5-88cd13c29140.png)

home/

**Comment by bjorn3** [comment]
There must be a `Cargo.toml` in the project for autodetection to work. You can set the `rust-analyzer.linkedProjects` config option to a list of paths to `Cargo.toml` files.

**Comment by causticroot** [comment]
Where do I set this up? sorry...

![image](https://user-images.githubusercontent.com/66440299/94331551-b59def00-ffa3-11ea-86cd-a08068169b9b.png)

**Comment by causticroot** [comment]
I managed to do so ... thank you very much !!! Is there no other way for the analyzer to recognize my "`Cargo.toml`" files, without having to specify the path one by one in my `setting.json`?


![image](https://user-images.githubusercontent.com/66440299/94332107-8ccc2880-ffa8-11ea-99c7-d491286bb85a.png)

**Comment by spamegg1** [comment]
I ran into the same problem. 

If we take the project folders out of the outer-most folders, then it works. So there can only be one level of folder-nesting until a `Cargo.toml` file is reached. Two or more deep, doesn't work.

This is very sad. If we try to follow the book's natural structure with our folders, this problem happens, and they don't do anything about it.

The Rust book is so poorly organized in terms of following along with the code. It should have its own repository with all of the code in perfect working condition, instead of disorganized snippets.
