### ISSUE TITLE
Fuzzy tests

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#61]
There are several things that parser self-checks for during parsing:

* it might get stuck during error recovery [code](https://github.com/matklad/libsyntax2/blob/44334f6f56bd99635f650796af0db8047e4c21c4/crates/libsyntax2/src/parser_impl/mod.rs#L100)
* Marker might be dropped without completing or abandoning [code](https://github.com/matklad/libsyntax2/blob/44334f6f56bd99635f650796af0db8047e4c21c4/crates/libsyntax2/src/parser_api.rs#L137)
* It might produce a tree with invalid block structure [code](https://github.com/matklad/libsyntax2/blob/44334f6f56bd99635f650796af0db8047e4c21c4/crates/libsyntax2/src/lib.rs#L119)

We need to fuzz/property test the parser to verify that this does not happen in practice.

To that end, we need to implement:

* fuzzing with arbitrary &str inputs: will be most useful for lexer probably?
* fuzzing with arbitrary (invalid) Rust code. Arb Rust code might be acquired by taking a sample of real Rust code and applying random edits to it.

**Comment by killercup** [comment]
Made a small PR with the most trivial fuzzer: #63. With the rs files from the libsyntax2 crate as corpus it quickly goes up to a coverage of 20199 (probably code paths but I don't know libfuzzer well enough; it's a high number compared to other fuzz targets, though).

Aaaaan it even found a crash! https://gist.github.com/killercup/a0be6701333a635de9dec6cffc89aedb

**Comment by killercup** [comment]
Two other interesting approaches: https://github.com/vegard/prog-fuzz/commit/c80b1a750c030f0e67bf556989ffb39dc092cf9c and creating edits from commits

**Comment by matklad** [comment]
>Aaaaan it even found a crash!

That's a good sign! Today I've made sure that parser deals with rust-lang/rust, with fail-tests and all, so this failure must be non-trivial. 

I'll write a fix shortly with a description of how to fix these things: I expect this won't be the sole fuzzing error :) 

>With the rs files from the libsyntax2 crate as corpus it quickly goes up to a coverage of 20199 

As a bonus objective, I think it makes sense to add `cargo gen-fuzz-corpus path-to-dir-with-sources` command to [tools](https://github.com/matklad/libsyntax2/blob/df05c5c3e20cfdfccd0165dd3370fed7c3676cd0/crates/tools/src/main.rs), so that we can easily generate a corpus on CI using libsynax sources.

**Comment by killercup** [comment]
Oh yes it most definitely is a non-trivial failure, it took the fuzzer almost 3 minutes to find – compared to most other projects where the first failures show up after 3 seconds! ;)

This is just the very first stab at things! I think I'll have a few hours to kill waiting at an airport tomorrow and might just integrate this with you tools crate and also throw other fuzzers at it. I've been meaning to make fuzzer definitions more generic anyway. And maybe after I've understood how to use libsyntax2 I can also use it to write a tool to auto-generate fuzzers for all functions that take a `&[u8]` or `&str` as input!

**Comment by matklad** [comment]
Ah, the delicious taste of dog food: I've copy-pasted your example as a test, and of course the plugin is now half-broken, because the indexing thread panics :D

**Comment by matklad** [comment]
Added a fix with a long explanation of what actually is going on: https://github.com/matklad/libsyntax2/pull/64/commits/a5c333c3ed98d539fcadcc723e992f5295d22d5c.

If you fuzzers find more errors like these, you now know how to fix 'em!

**Comment by killercup** [comment]
Wow, a5c333c3ed98d539fcadcc723e992f5295d22d5c has a beautiful commit message!

I have indeed found another crash ([output](https://gist.github.com/killercup/254c98a31d921972ecc88e2c3c35ecad)). I'll see if I can fix it later this afternoon!

**Comment by killercup** [comment]
> is it running the parser with debug-assertions on?

Totally forgot to answer this one! Yes:

```
     Running `fuzz/target/x86_64-apple-darwin/debug/parser -artifact_prefix=/Users/pascal/Projekte/tools/libsyntax2/crates/libsyntax2/fuzz/artifacts/parser/ fuzz/artifacts/parser/`
```

And good point. I'll also run it in release to see if there is a unknown dependency on this somewhere (or a things that fails differently without overflow checks)!

**Comment by matklad** [comment]
>. I'll also run it in release to see if there is a unknown dependency on this somewhere (or a things that fails differently without overflow checks)!

I've refactored code a bit, so that for fuzzing we always do that block check, even in release mode:
https://github.com/matklad/libsyntax2/commit/ba4a697d8cb577c03c84c0c91a25ecbeaa9c68e6

**Comment by killercup** [comment]
Cool! When using `cargo fuzz`, it'll also pass `--cfg fuzzing` FYI

**Comment by matklad** [comment]
>I have indeed found another crash 

BTW, I am seeing the same `match_arm_list` in the trace (https://gist.github.com/killercup/254c98a31d921972ecc88e2c3c35ecad#file-gistfile1-txt-L28), so I suspect it might be the same crash.

**Comment by YaLTeR** [comment]
Ran the fuzzer and found this: https://gist.github.com/YaLTeR/2d0c734a0cca830e136a59af3891f0b2
```
==26789== ERROR: libFuzzer: deadly signal
    #0 0x55fdaa499c47 in __sanitizer_print_stack_trace /checkout/src/libcompiler_builtins/compiler-rt/lib/asan/asan_stack.cc:38:3
    #1 0x55fdaa8128fb in fuzzer::PrintStackTrace() /home/yalter/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/libfuzzer/FuzzerUtil.cpp:206:38
    #2 0x55fdaa82516c in fuzzer::Fuzzer::CrashCallback() /home/yalter/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/libfuzzer/FuzzerLoop.cpp:237:18
    #3 0x55fdaa825021 in fuzzer::Fuzzer::StaticCrashSignalCallback() /home/yalter/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/libfuzzer/FuzzerLoop.cpp:209:19
    #4 0x55fdaa8114a1 in fuzzer::CrashHandler(int, siginfo_t*, void*) /home/yalter/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/libfuzzer/FuzzerUtilPosix.cpp:36:36
    #5 0x7f9a4cc833bf  (/usr/lib/libpthread.so.0+0x123bf)
    #6 0x7f9a4cac8d7e in __GI_raise (/usr/lib/libc.so.6+0x37d7e)
    #7 0x7f9a4cab3671 in __GI_abort (/usr/lib/libc.so.6+0x22671)
    #8 0x55fdaa857ba5 in std::sys::unix::abort_internal::h2d5bbe49e1ed7a4d /checkout/src/libstd/sys/unix/mod.rs:166:4
    #9 0x55fdaa848c95 in std::process::abort::h725e682b8e29a1d1 /checkout/src/libstd/process.rs:1465:13
    #10 0x55fdaa7faae7 in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::h68f0b4fc004e84a1 /home/yalter/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/src/lib.rs:32:12
    #11 0x55fdaa849c83 in std::panicking::rust_panic_with_hook::h07c16741eebef2bd /checkout/src/libstd/panicking.rs:481:16
    #12 0x55fdaa7eaf48 in std::panicking::begin_panic::hb29aa991448d2272 /checkout/src/libstd/panicking.rs:411:4
    #13 0x55fdaa53a7cf in libsyntax2::parser_impl::ParserImpl::nth::h351e8643c2e8eb8b /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/parser_impl/mod.rs:100:12
    #14 0x55fdaa53310b in libsyntax2::parser_api::Parser::nth::h798f4523564ef2d4 /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/parser_api.rs:30:8
    #15 0x55fdaa5330ad in libsyntax2::parser_api::Parser::current::h13defb764e36f541 /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/parser_api.rs:24:8
    #16 0x55fdaa5fe7fb in libsyntax2::grammar::paths::is_path_start::hbf340d0210784a21 /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/paths.rs:7:10
    #17 0x55fdaa69dfa6 in libsyntax2::grammar::patterns::atom_pat::h1b6d742a3e02101e /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/patterns.rs:40:7
    #18 0x55fdaa69cb78 in libsyntax2::grammar::patterns::pattern_r::h408b6fb3ff622b49 /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/patterns.rs:15:23
    #19 0x55fdaa69c8f5 in libsyntax2::grammar::patterns::pattern::h605052eb8e5df494 /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/patterns.rs:11:4
    #20 0x55fdaa6a1f5c in libsyntax2::grammar::patterns::slice_pat::he5c575af740d02cf /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/patterns.rs:200:17
    #21 0x55fdaa69f8d8 in libsyntax2::grammar::patterns::atom_pat::h1b6d742a3e02101e /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/patterns.rs:61:19
    #22 0x55fdaa69cb78 in libsyntax2::grammar::patterns::pattern_r::h408b6fb3ff622b49 /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/patterns.rs:15:23
    #23 0x55fdaa69c8f5 in libsyntax2::grammar::patterns::pattern::h605052eb8e5df494 /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/patterns.rs:11:4
    #24 0x55fdaa678294 in libsyntax2::grammar::params::value_parameter::h0e900604f3e84ed9 /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/params.rs:75:12
    #25 0x55fdaa677d96 in libsyntax2::grammar::params::list_::hab31290f6033dff7 /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/params.rs:55:8
    #26 0x55fdaa677173 in libsyntax2::grammar::params::param_list::heccf9816986b6b2b /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/params.rs:9:4
    #27 0x55fdaa4f6bae in libsyntax2::grammar::items::fn_def::hcf4625e05adef906 /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/items/mod.rs:252:16
    #28 0x55fdaa4f571e in libsyntax2::grammar::items::maybe_item::h1414516c96095486 /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/items/mod.rs:127:12
    #29 0x55fdaa4f3f2b in libsyntax2::grammar::items::item_or_macro::hd33c3b05c327d3d9 /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/items/mod.rs:38:10
    #30 0x55fdaa4f3c22 in libsyntax2::grammar::items::mod_contents::hfd59d2b708b80dc1 /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/items/mod.rs:24:8
    #31 0x55fdaa51a4d9 in libsyntax2::grammar::root::h3563db47730a26de /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/grammar/mod.rs:60:4
    #32 0x55fdaa5fe440 in libsyntax2::parser_impl::parse_with::h87e0153dc9ff950f /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/parser_impl/mod.rs:40:8
    #33 0x55fdaa4bba62 in libsyntax2::File::parse::hb3d2ab4a56a501be /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/lib.rs:76:30
    #34 0x55fdaa4b7d3e in libsyntax2::utils::check_fuzz_invariants::h6fdcbfd07d84fa53 /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/src/utils.rs:50:15
    #35 0x55fdaa3fc3d5 in rust_fuzzer_test_input /home/yalter/Source/rust/libsyntax2/crates/libsyntax2/fuzz/fuzz_targets/parser.rs:7:8
    #36 0x55fdaa7fa77d in libfuzzer_sys::test_input_wrap::_$u7b$$u7b$closure$u7d$$u7d$::ha9609b37de696f3e /home/yalter/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/src/lib.rs:11:8
    #37 0x55fdaa83d28b in std::panicking::try::do_call::ha2f5fd7b918e763a /checkout/src/libstd/panicking.rs:310:39
    #38 0x55fdaa860688 in __rust_maybe_catch_panic /checkout/src/libpanic_abort/lib.rs:41:4
```

**Comment by matklad** [comment]
Thanks! First one fixed in https://github.com/matklad/libsyntax2/commit/b6f8037a6f8fbcb4f127e1d2b518279650b1f5ea. Letme take a look at the second one...

**Comment by DJMcNab** [comment]
I think the current action on this is just to run these every few weeks for a little bit to see if there's any code which can trigger a panic. I wonder if there's any neat way to remind us of this automatically - any ideas?

**Comment by matklad** [comment]
>I wonder if there's any neat way to remind us of this automatically - any ideas?

A travis cron job?

**Comment by matklad** [comment]
So yeah, there are two bits I want to add to the current setup to close the issue

* add a  `cargo fuzz-tests` task (which should trick me to finally run this on my machine :) )
* add an automated way to run fuzzing on CI. A daily cron job to run fuzzing for half an hour seems ideal.


A further improvement would be a high-level fuzzing, on the `ra_analysis` level: creating an (in-memory) rust project and running random diagnostics, completions and edits on it, but that is definitelly a separate issue.

**Comment by memoryruins** [comment]
Left it running overnight; no crashes yet :)
```
#6248625        REDUCE cov: 28690 ft: 163494 corp: 4204/91Kb lim: 110 exec/s: 234 rss: 605Mb L: 9/108 MS: 1 EraseBytes-
#6251047        REDUCE cov: 28690 ft: 163494 corp: 4204/91Kb lim: 110 exec/s: 234 rss: 605Mb L: 67/108 MS: 2 ShuffleBytes-EraseBytes-
#6251189        REDUCE cov: 28690 ft: 163494 corp: 4204/91Kb lim: 110 exec/s: 234 rss: 605Mb L: 37/108 MS: 2 ChangeBinInt-EraseBytes-
#6251406        NEW    cov: 28690 ft: 163503 corp: 4205/91Kb lim: 110 exec/s: 234 rss: 605Mb L: 109/109 MS: 2 InsertByte-CopyPart-
#6253052        REDUCE cov: 28690 ft: 163503 corp: 4205/91Kb lim: 110 exec/s: 234 rss: 605Mb L: 28/109 MS: 1 EraseBytes- 
```

**Comment by skade** [comment]
Hm, travis cron jobs are not really meant for long-running tasks. Is there a maximum time we want to run this?

**Comment by matklad** [comment]
>Is there a maximum time we want to run this?

Yeah, that's what I had in mind: limit fuzzing time by, say, five minutes every nigh.  We've recently added [some extra time consuming checks](https://github.com/rust-analyzer/rust-analyzer/blob/b495e56b0d3f7a72494d002a69440563e8394574/.github/workflows/release.yaml#L63-L65) on nightly.

>We'd need to apply, though.

My gut feeling is that, at this stage, fuzzing would add relatively little benefit. So I'd rather avoid integrating with services besides the ones we already have.

**Comment by matklad** [comment]
we have some fuzzing tests set up, we don't have automated fuzzing on CI, but, given the number of *known* bugs, I don't think it's worthwhile to invest time into this at this point.

**Comment by matthiaskrgr** [comment]
Just for the record, I have fed rust-lang/glacier and rust-lang/rust +  around 30% of random files contained in the history of rust-lang/rust  into `rust-analyzer highlight`, and filtered out a couple of crashes:

https://github.com/rust-lang/rust-analyzer/issues/16288
https://github.com/rust-lang/rust-analyzer/issues/16287
https://github.com/rust-lang/rust-analyzer/issues/16286
https://github.com/rust-lang/rust-analyzer/issues/16284
https://github.com/rust-lang/rust-analyzer/issues/16283
https://github.com/rust-lang/rust-analyzer/issues/16282
https://github.com/rust-lang/rust-analyzer/issues/16281
https://github.com/rust-lang/rust-analyzer/issues/16280
https://github.com/rust-lang/rust-analyzer/issues/16278

I can do mutation-based fuzzing based on randomly mutated (using tree-splicer) rust files using https://github.com/matthiaskrgr/icemaker/ if anyone is interested :)
