### ISSUE TITLE
Freezes at Go to Definition

### ISSUE THREAD

**Issue by alexs-sh** [rust-analyzer/rust-analyzer#6103]
```rust
pub fn magic_func<C>(mut callback: C)
where
    C: FnMut(&str)
        + std::marker::Sized
        + std::marker::Sync
        + std::marker::Send
        + std::clone::Clone
        + 'static,
{
    callback("dummy");
}

fn main() {
    magic_func(move |_| {})
}
```
Jumping to the definition of **magic_func** causes an editor to freeze.
**ps** command shows that I have 1 rust-analyzer process in state S, and it uses 0% CPU.  
**killall rust-analyzer** returns editor to its normal state.

System Info:
rust-analyzer 20200928 (from ArchLinux repo)
nvim 0.4.4 (from ArchLinux repo)
coc.nvim 0.0.79-6cb5c6cd2d

Please let me know if additional info will be needed.

Thank you for your time

**Comment by kjeremy** [comment]
I can't reproduce this with vscode

**Comment by alexs-sh** [comment]
Yes, with VSCode works fine. So, it looks like a coc/nvim issue. Thanks!

**Comment by alexs-sh** [comment]
Different rust-analyzer versions could explain the different behavior of vscode and nvim.

vscode uses rust-analyzer 277488b
nvim uses rust-analyzer from ArchLinux repo. 

```
/usr/bin/rust-analyzer --version
rust-analyzer ???????
```
The freeze has gone away after switching to 277488b for nvim.
