### ISSUE TITLE
rust-analyzer on WSL cannot find sysroot, VSCode 1.49.2

### ISSUE THREAD

**Issue by ChronosWS** [rust-analyzer/rust-analyzer#6106]
VSCode: 1.49.2
Rust-Analyzer plugin: 0.2.328

Expected: Language server loads and operates correctly (as it did yesterday before today's VSCode update)

Actual: Language server fails to load, all language features unavailable in VSCode

Error (from extension toast):
```
rust-analyzer failed to load workspace: Failed to find sysroot for Cargo.toml file /home/cliff/<redacted>/Cargo.toml. Is rust-src installed?: can't load standard library from sysroot /usr/local (discovered via `rustc --print sysroot`) try running `rustup component add rust-src` or set `RUST_SRC_PATH`
```

Diagnostics:
From the VSCode Bash shell:
```
$ rustc --print sysroot
/home/cliff/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
$ rustup component add rust-src
info: component 'rust-src' is up to date
```
From Rust Analyzer Language Server diagnostics window:
```
[ERROR rust_analyzer::reload] failed to load workspace: Failed to find sysroot for Cargo.toml file /home/cliff/<redacted>/Cargo.toml. Is rust-src installed?: can't load standard library from sysroot
/usr/local
(discovered via `rustc --print sysroot`)
try running `rustup component add rust-src` or set `RUST_SRC_PATH`
```

From Rust Analyzer Client diagnostics window:
```
INFO [9/30/2020, 12:21:44 PM]: Extension version: 0.2.328
INFO [9/30/2020, 12:21:44 PM]: Using configuration {
  lruCapacity: null,
  files: { watcher: 'client', exclude: [] },
  notifications: { cargoTomlNotFound: true },
  cargo: {
    autoreload: true,
    noDefaultFeatures: false,
    allFeatures: false,
    features: [],
    loadOutDirsFromCheck: false,
    target: null
  },
  rustfmt: { extraArgs: [], overrideCommand: null },
  checkOnSave: {
    enable: true,
    extraArgs: [],
    command: 'check',
    overrideCommand: null,
    allTargets: true,
    noDefaultFeatures: null,
    allFeatures: null,
    features: null,
    target: null
  },
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    typeHints: true,
    chainingHints: true,
    parameterHints: true,
    maxLength: 20
  },
  completion: {
    addCallParenthesis: true,
    addCallArgumentSnippets: true,
    postfix: { enable: true }
  },
  callInfo: { full: true },
  updates: { channel: 'stable', askBeforeDownload: true },
  serverPath: null,
  trace: { server: 'off', extension: false },
  procMacro: { enable: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  lens: { enable: true, run: true, debug: true, implementations: true },
  hoverActions: {
    enable: true,
    implementations: true,
    run: true,
    debug: true,
    gotoTypeDef: true
  },
  linkedProjects: null,
  withSysroot: true,
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [],
    warningsAsInfo: [],
    warningsAsHint: []
  },
  assist: { importMergeBehaviour: 'full' }
}
INFO [9/30/2020, 12:21:44 PM]: PersistentState: {
  lastCheck: undefined,
  releaseId: undefined,
  serverVersion: '0.2.328'
}
INFO [9/30/2020, 12:21:44 PM]: Using server binary at /home/cliff/.vscode-server/data/User/globalStorage/matklad.rust-analyzer/rust-analyzer-linux
WARN [9/30/2020, 12:22:39 PM]: LSP request timed out {
  method: 'rust-analyzer/inlayHints',
  param: {
    textDocument: {
      uri: 'file:///home/cliff/<redacted>/src/main.rs'
    }
  },
  error: [ResponseError: Rust Analyzer is still loading...
  	at handleResponse (/home/cliff/.vscode-server/extensions/matklad.rust-analyzer-0.2.328/out/src/main.js:3779:48)
  	at processMessageQueue (/home/cliff/.vscode-server/extensions/matklad.rust-analyzer-0.2.328/out/src/main.js:3594:17)
  	at Immediate.<anonymous> (/home/cliff/.vscode-server/extensions/matklad.rust-analyzer-0.2.328/out/src/main.js:3578:13)
  	at processImmediate (internal/timers.js:439:21)] {
    code: -32801,
    data: undefined
  }
}
```

**Comment by bjorn3** [comment]
> can't load standard library from sysroot /usr/local (discovered via `rustc --print sysroot`)

Is it possible that `~/.cargo/bin` is not in your PATH for vscode? Did you set the PATH in `~/.profile` or `~/.bashrc`/`~/.zshrc`?

**Comment by ChronosWS** [comment]
> 
> > can't load standard library from sysroot /usr/local (discovered via `rustc --print sysroot`)
> 
> Is it possible that `~/.cargo/bin` is not in your PATH for vscode? Did you set the PATH in `~/.profile` or `~/.bashrc`/`~/.zshrc`?
```
$ echo $PATH
/home/cliff/.cargo/bin;...
$ which cargo
/home/cliff/.cargo/bin/cargo
```

Is there some way besides that which VSCode might require for the path to be recognized?

**Comment by bjorn3** [comment]
You are printing the PATH for your shell. This is not necessarily identical to the PATH for graphical applications. For example `~/.profile` is runned when logging in, meaning that it applies for all programs. `~/.bashrc` only runs when you open a shell, meaning that it only applies to that shell session and not for example vscode, unless you ran vscode from the terminal.

**Comment by ChronosWS** [comment]
> 
> 
> You are printing the PATH for your shell. This is not necessarily identical to the PATH for graphical applications. For example `~/.profile` is runned when logging in, meaning that it applies for all programs. `~/.bashrc` only runs when you open a shell, meaning that it only applies to that shell session and not for example vscode, unless you ran vscode from the terminal.

Yes, I always run `code` from the WSL terminal - I don't do a post-hoc connection to Remote WSL

**Comment by ChronosWS** [comment]
Though in any case, I see in `.profile` the following:
```
export PATH="$HOME/.cargo/bin:$PATH"
```

**Comment by ChronosWS** [comment]
If there are any additional diagnostics I can enable to help debug this please let me know :)

**Comment by matklad** [comment]
Have no idea what's going on here. Added some more logging in #6230.

**Comment by lnicola** [comment]
@ChronosWS are you still seeing this?

**Comment by patbecich** [comment]
I experienced a similar issue. If I open an individual Rust file in VSCode (i.e. `cd src; code main.rs`), rust-analyzer shows an unresolved import error. `Cargo.toml` exists in the project root, but it seems rust-analyzer does not find it.
If I open the project directory in VSCode, and then open the Rust file, rust-analyzer works as expected. 
I'm not sure if my issue is this: https://github.com/rust-analyzer/rust-analyzer/issues/6038

**Comment by Veykril** [comment]
@patbecich r-a requires the cargo workspace to be fully opened for it to work, single files do not work properly(we have some stuff now that allows them to work in some fashion but very very limited).

Closing as OP hasn't replied and doesn't seem to be active currently anymore.
