### ISSUE TITLE
Add quick fix to sort methods

### ISSUE THREAD

**Issue by Timmmm** [rust-analyzer/rust-analyzer#6110]
It would be nice to add a quick fix to sort methods in an `impl`. It should support both:

1. Sort methods alphabetically, and
2. Sort methods in the same order as trait declaration.

The second one would match the order of the methods to the order they are declared in in the trait, when doing `impl Trait for Type`.

**Comment by matklad** [comment]
we already have something like this for struct literals:

https://github.com/rust-analyzer/rust-analyzer/blob/f7144dcd52c663cefc789445fe561771d935fbf0/crates/assists/src/handlers/reorder_fields.rs#L10-L28

**Comment by fisherdarling** [comment]
I'd be interested in taking this on. This would be my first contribution, but I think I can figure it out with enough questions :P

I'm going to essentially copy the implementation for reorder_fields and start by first simply sorting them. Then I'll look into adding ordering by trait definition. I'll try and find all of the machinery that I need to hook up by looking at how `reorder_fields` is added.

**Comment by matklad** [comment]
@fisherdarling sounds like the right approach here!

**Comment by fisherdarling** [comment]
Alright, I think #6809 is ready for a review / comments!
