### ISSUE TITLE
Generate editor-independent documentation for configuration

### ISSUE THREAD

**Issue by cuviper** [rust-analyzer/rust-analyzer#6112]
Would it be possible to document the configuration options in the user manual?

The only descriptions I've found are in `editors/code/package.json`. I suppose that will be rendered nicely in the settings interface for vscode users, but it's little help to poor Vim users like myself. :slightly_smiling_face:

**Comment by lnicola** [comment]
If we add that, some documentation about configuring the various Vim clients would be really nice, because it comes up very often.

**Comment by matklad** [comment]
Yeah, this is a long-standing issue. We should add doc comments here:

https://github.com/rust-analyzer/rust-analyzer/blob/f7144dcd52c663cefc789445fe561771d935fbf0/crates/rust-analyzer/src/config.rs#L452-L519

And then add a codegen task here:

https://github.com/rust-analyzer/rust-analyzer/blob/f7144dcd52c663cefc789445fe561771d935fbf0/xtask/src/codegen.rs#L8-L13

to generate this:

https://github.com/rust-analyzer/rust-analyzer/blob/f7144dcd52c663cefc789445fe561771d935fbf0/editors/code/package.json#L209-L692

and also to generate a section in the manual. 

It is not clear to me how exactly we'd do all that, specifically, how we'd map rust types to json schema. Perhaps as the first step we should just write the json part by hand?

**Comment by vorner** [comment]
It's very far from complete solution, but it feels a bit related. I wanted to have documentation for configuration options a program can take, generated from doc comments and I've created this crate: https://crates.io/crates/structdoc. It's definitely not good enough quality for RA right now, but it is able to generate kind of abstract tree of the options with descriptions and types.

If there was interest, I would be open to discussions extending this.

**Comment by cuviper** [comment]
Should this be closed by #6776? I think so, but the published manual isn't updated yet...

**Comment by lnicola** [comment]
Yes. We close issues after fixing them, but releases are weekly. The new manual should be published next Monday.
