### ISSUE TITLE
VSC unused warnings are painful to look at

### ISSUE THREAD

**Issue by AaronKutch** [rust-analyzer/rust-analyzer#6126]
Here is a screenshot of what I have to look at for extended periods when I am working on code that isn't being used yet by the interface or main function:
![image](https://user-images.githubusercontent.com/32419308/94973078-64748a80-04d0-11eb-9011-64fb097af746.png)
(the quality is just as bad for dark themes)
There are a few things happening here:
 - The unused code text is being shaded a very light color by the extension
 - An ugly yellow squiggle is being applied across the entire function or file
 - I have the error lens extension that applies a little more shading on top of that

To begin with, I don't think the light color shading should be applied to the font ever, considering that all Rust codebases I have worked with only had unused code during the writing of code. I think that all squiggles should never extend beyond the line that they originate, which will fix similar problems I have when an error extends across an entire function.

I have had a good experience with the Error lens extension for VScode, and I wonder if some parts of it should be included in the `rust-analyzer` extension. For example:
![image](https://user-images.githubusercontent.com/32419308/94974448-3bee8f80-04d4-11eb-9942-70338debf998.png)
The only use for the squiggles is when the inline error message does not give enough information to pinpoint something inside a line:
![image](https://user-images.githubusercontent.com/32419308/94974642-c8994d80-04d4-11eb-91c6-b952d03281ba.png)
I would disable squiggles entirely for warnings, and only use them for error messages that point to something within a line (if an entire line or more is included by the error bounds, then just use light highlighting and no squiggles). The error lens extension often picks up what is most important about the error, and I rarely have to open the errors tab to see more specifics about the error, but I think the `rust-analyzer` extension can do even better if it implemented its own inline messages and highlighting.

**Comment by kiljacken** [comment]
You shouldn't hold your breath for a custom inline error message implementation in the rust-analyzer vscode extension. It's simply out of scope. We depend on your editor and it's understanding of the language server protocol to handle errors in an editor independent way.

I believe the extra squiggles on top of the fade of unused code is due to how we map diagnostics from cargo check, and could probably be improved for the unused code warnings. That might be worth looking into.

As for not shading unused code, there should be a VSCode configuration option for that, although I do not know it off the top of my head.

**Comment by AaronKutch** [comment]
I found the configuration `"editor.showUnused": false` which improves contrast greatly. The squiggles look like they are controlled from `rust-analyzer`s side. Is it possible to reduce the amount of page covered by squiggles in general, say if squiggles from errors or warnings cover a whole function, they are reduced to just covering the signature?

**Comment by bjorn3** [comment]
![image](https://user-images.githubusercontent.com/17426603/94996596-e387c280-05a5-11eb-9a09-e2a2106f036a.png)

As you can see this specific warning comes from rustc, not rust-analyzer. Rust-analyzer just passes the warning through to the editor. If you want to reduce the part covered by a warning, you should open an issue for rust. For functions this has already been done.

**Comment by AaronKutch** [comment]
It has been a few weeks since I have programmed in Rust, and I was messing with macros and assumed the same was true for functions (maybe this was a recent change, I can't remember). I guess the problem is solved for most users already.

**Comment by tgross35** [comment]
Does anybody have a good way to turn off the squiggles only? I'm glad things are better than the current example, but prefer only the lightened text alone over that plus a yellow squiggle.

**Comment by tgross35** [comment]
@bjorn3 that's excellent. Thank you for the tip!
