### ISSUE TITLE
References from match ergonomics are missing for field pattern shorthands

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [rust-analyzer/rust-analyzer#6146]
rust-analyzer version: 2020-10-05 (e5f252a)

To reproduce, mouse hover over the last occurrence of `f` in the following program:
```rust
struct S {
    f: i32,
}

fn main() {
    let s = S { f: 0 };
    let S { f /* <- hover here */ } = &s;
}
```

Expected result: `f: &i32`.
Actual result: `f: i32`.

For comparison, in
```rust
let S { f: x } = &s;
```
hovering over `f` gives `f: i32` and over`x` `x: &i32`. This sort of makes sense, because `f` is a field of type `i32` and `x` is a local binding of type `&i32`.

In case of field pattern shorthands, `f` plays both roles, and these perspectives are at odds.
I feel "`f` is a local binding of type `&i32`" is more useful.
If one really cares about `f` as a field one could go to the definition of `S` and hover there.

**Comment by matklad** [comment]
Have no idea what's the probelm here, but I'd start with writing a test for this:

https://github.com/rust-analyzer/rust-analyzer/blob/f7144dcd52c663cefc789445fe561771d935fbf0/crates/ide/src/hover.rs#L386-L388

and then following the call graph to spot the problem
