### ISSUE TITLE
Add semantic token modifiers for punctuation

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#6152]
I used to have different colors for curly braces, operators, parens, brackets and other punctuation in TypeScript.

<details>
<summary>Take this colorization as an example:</summary>

![image](https://user-images.githubusercontent.com/36276403/95221885-95bac680-0800-11eb-9a3a-7e5ae2809eab.png)
</details>

It is not possible to achieve this amount of color diversity for punctuation in rust-analyzer for now, so I propose to add more specific semantic token modifiers for punctuation: `punctuation.curlyBrace`, `punctuation.bracket`, `punctuation.paren` ... so that it is possible to control the style of each individual punctuation symbol kind.

I am not insisting on implementing this via semantic token modifiers, this is just the first thing that comes to my head.

**Comment by Veykril** [comment]
I believe that textmate scopes for these would be a better fit, since punctuations don't really have any semantic meaning in this case and you can use textmate scopes just fine with semantic highlighting enabled, as it falls back in those cases where it isn't used for tokens.

**Comment by Veetaha** [comment]
TextMate might work too, but our textmate doesn't produce scopes for different punctuation symbols:
![image](https://user-images.githubusercontent.com/36276403/95315320-02829f00-089b-11eb-93af-18b7b4780666.png)

cc #6137

**Comment by Veykril** [comment]
Yes those would have to be split up into multiple categories, would go well with that open PR right now I guess 😄

**Comment by dustypomerleau** [comment]
Some semantic highlighting approaches ignore punctuation, which allows the underlying TextMate scopes to shine through. But this is not the case with RA, so with semantic highlighting enabled, the color of all bracket types will be whatever color the theme sets for `punctuation:rust`. There is a separate semantic token type for `operator:rust`, but that would be the only distinction. If you are willing to disable semantic highlighting, then yes, my open PR would allow you to theme all of those things separately.

**Comment by Veykril** [comment]
Oh interesting, now that you say it there is a `punctuation` semantic rule. I guess I missed that when i checked earlier probably cause i was putting my cursor at the wrong position. Then yes textmate scopes wouldn't necessarily be helpful here.

**Comment by matklad** [comment]
Agree we should do this. Perfect rust-analyzer client wouldn't have text mate scopes at all, and would rely solely on semantic tokens.
