### ISSUE TITLE
Incorrect placement of filled struct fields

### ISSUE THREAD

**Issue by andrewgAB** [rust-analyzer/rust-analyzer#6156]
Clicking "Fill struct fields" when a struct is inside a `vec!` macro, will fill the fields in the wrong place.

## Steps to reproduce:

```rust
struct Person {
    pub name: String,
    pub age: u8,
}

fn main() {
    let person = vec![Person {}];
}
```
1. place the cursor inside the `Person {}` braces.
2. Fill struct fields

## Expected result:
```rust
struct Person {
    pub name: String,
    pub age: u8,
}

fn main() {
    let person = vec![Person { name: (), age: ()}];
}
```

## Actual result:
```rust
struct Person {
    pub na{ name: (), age: ()}: String,
    pub age: u8,
}

fn main() {
    let person = vec![Person {}];
}
```

**Comment by Veykril** [comment]
Duplicate of #4314.

**Comment by andrewgAB** [comment]
Closing as duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4314
