### ISSUE TITLE
Autocompletion formatting problem

### ISSUE THREAD

**Issue by Aescetic** [rust-analyzer/rust-analyzer#6162]
Firstly — very fine project. Someday I will fully comprehend its contours but for now I know that it is pretty stupendous work. In particular, it is dramatically superior to what I have been able to coax out of RLS.

However, we are here, in this issue, and here is a screenshot:

![](https://i.postimg.cc/JzgKHtDJ/beyond.jpg)

As you can see, there is a vector and a selection of signatures of methods on this vector, courtesy of Rust Analyzer. There is just one problem: those weirdly placed question marks and the occasional vast and highly irregular space between some words and others.

It is probably tempting to say that this is a problem with my specific configuration of Emacs, and that is a reasonable thing to say, but everything looks normal and good when instead of Rust Analyzer I use RLS.

Thoughts?

**Comment by bjorn3** [comment]
i think the `?` are a replacement for newlines by emacs.

**Comment by Aescetic** [comment]
Okay, @bjorn3, that makes sense. The highly irregular space, then, is likely a rendered tab character.

What command should I use to obtain the autocompletion list on the command line?

**Comment by Aescetic** [comment]
And, more generally, do you think that Rust Analyzer, like RLS, should be responsible for stripping such newline and tab characters, or that the burden should fall elsewhere?

**Comment by bjorn3** [comment]
The LSP specification says nothing about if the server must support newlines in `CompletionItem.label`. It also doesn't provide a way for the client and server to negotiate support for it. What do you think @matklad?

**Comment by matklad** [comment]
There shouldn’t be any newlines in label, it’s a bug on owner side (and we need to add an assert there)

**Comment by matklad** [comment]
We've added assert a while ago
