### ISSUE TITLE
Add a command to cancel active `cargo check`

### ISSUE THREAD

**Issue by 0x7CFE** [rust-analyzer/rust-analyzer#6163]
I'm working on a huge Rust project that takes ages even to do cargo check (not to mention release build). Obviously, it's not practical to disable check on save entirely, since it's very useful to have quick feedback on recent changes in the code right in the editor.

However, if everything was checked successfully then sometimes I'd like to do some real compile & run pass, for example to run the tests which I usually do from a separate terminal.

Unfortunately, that would be impossible, since lock would be held by an active cargo check that still checks dependencies of a recently changed module.

Anyway, it would be cool to have a way to cancel active check (like a command or something like a × button next to check progress) and proceed with external tests.

**Comment by Veetaha** [comment]
This has been working perfectly for me so far: https://github.com/rust-analyzer/rust-analyzer/issues/4828#issuecomment-642203720

**Comment by matklad** [comment]
duplicates  https://github.com/rust-analyzer/rust-analyzer/issues/4828

For my personal workflow, I just don't use `checkOnSave`. Using https://rust-analyzer.github.io/manual.html#run works better for me.
