### ISSUE TITLE
CodeActions add_impl_default_members add_impl_missing_members not enabling

### ISSUE THREAD

**Issue by StevenJPx2** [rust-analyzer/rust-analyzer#6164]
Hi! Thanks for your awesome support for this plugin. 

## Background
I'm making a web server using `Actix`, `Juniper`, and `juniper_from_schema`. 

So this is where the problem arises:
```rust
pub struct User {
    id: ID,
    user_name: String,
    full_name: String,
    desc: HTML,
    password_hash: i32,
    articles: i32,
    drafts: i32,
}

impl UserFields for User {}
// Error: E0046: not all trait items implemented, missing: `field_id`, `field_user_name`,  
// `field_full_name`, `field_desc`, `field_password_hash`, `field_articles`, `field_drafts` in implementation
```

## Issue
So, one of the best solutions for this is to utilise `rust-analyser`'s `codeAction`: `add_impl_missing_members ` to automagically fill in all of the functions with a default return value as well. 

This is how it is supposed to work: 
###### Before:
```rust
trait Trait<T> {
    Type X;
    fn foo(&self) -> T;
    fn bar(&self) {}
}

impl Trait<u32> for () {┃

}
```
###### After:
```rust
trait Trait<T> {
    Type X;
    fn foo(&self) -> T;
    fn bar(&self) {}
}

impl Trait<u32> for () {
    fn foo(&self) -> u32 {
        ${0:todo!()}
    }
}
```

However, doing this in my case shows no code actions available. It works for the above example if I try, so I'm assuming that it doesn't work globally, but only for locally defined traits.

## Solution
I don't exactly know what a good way to fix this might be, but if I'm wrong and it is actually possible, please let me know!

**Comment by matklad** [comment]
To debug this, I'd:

* put a print somewhere around [here](https://github.com/rust-analyzer/rust-analyzer/blob/f7144dcd52c663cefc789445fe561771d935fbf0/crates/assists/src/handlers/add_missing_impl_members.rs#L112-L124), rebuild rust-analyze from source and tried to see where it returns None
* tried to make a smaller example which doesn't depend on many external crates.

**Comment by StevenJPx2** [comment]
# An update
The problem arises most probably because I was loading GraphQL from a schema file, which is then loaded onto the Rust file via the macro `graphql_schema_from_file!` from `juniper_from_schema`. The compiler/LSP was able to detect the missing members, however, `rust-analyser` wasn't. 


`src/schema.graphql`
```graphql
type User {
   id: ID!
   userName: String!
   fullName: String!
   desc: HTML!
   passwordHash: String!
   articles: [Post!]!
   drafts: [Post!]!
 }
```

`src/graphql.rs`
```rust
graphql_schema_from_file!("src/schema.graphql")

pub struct User {
     id: ID,
     user_name: String,
     full_name: String,
     desc: Html,
     password_hash: String,
     articles: Vec<Post>,
     drafts: Vec<Post>,
 }

 impl UserFields for User {}
```

So, what I imagine is happening is that the macro is generating the trait `UserFields` based on `schema.graphql`.

## Issue
The `codeactions` ` add_impl_default_members` and `add_impl_missing_members` do not work for the macro generated traits despite the compiler/LSP detecting it.

**Comment by brandondong** [comment]
I have a project that calls `graphql_schema_from_file`. I didn't have proc macro support enabled until [v69](https://rust-analyzer.github.io/thisweek/2021/03/22/changelog-69.html) which changed the defaults but when it did, the proc macro call would intermittently result in "proc macro server crashed" macro errors.

This would result in the above scenario where the code action was missing as well as those traits not being present during autocompletion. However, with [v70](https://rust-analyzer.github.io/thisweek/2021/03/29/changelog-70.html), this issue appears to have been fixed for me.
