### ISSUE TITLE
Add support for intra-doc links

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/rust-analyzer#6168]
Intra-doc links rustdoc feature is soon to be shipped with the stable rust toolchain: https://github.com/rust-lang/rust/issues/43466

I propose to add a feature for their support in ide.
The simplest and useful thing that I miss is the ability to navigate to the linked symbol definition in the source code.
Suppose we have the following:

```rust
/// Blah, .. [`foo`]
pub fn bar() { }

/// You might want to see [`std::fs::read()`] too.
pub fn foo() { }
```

I suggest that when we hover over ``[`foo`]`` symbol in the doc comment we can use `goto-declaration/definition` and the editor should open the file and the line where the referenced symbol is located, in this case it should be the same file, function `foo`.
The link in `pub fn foo()` documentation should also be actionable and direct us to the source code of `std::fs::read` function.
We might also want to highlight (via semantic tokens) that the given link is an intra-doc link (maybe even preserving the information about the symbol kind (function/variable/struct/trait...)).

The initial implementation of this feature might just use the current path resolving instrumentation of rust-analyzer and this will already be very useful, after that we might also support [path disambiguation syntax of intra-doc links](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md#path-ambiguities), maybe even suggest completions?

**Comment by matklad** [comment]
Relevant code: 
* https://github.com/rust-analyzer/rust-analyzer/blob/f7144dcd52c663cefc789445fe561771d935fbf0/crates/ide/src/goto_definition.rs#L27-L31
* https://github.com/rust-analyzer/rust-analyzer/blob/f7144dcd52c663cefc789445fe561771d935fbf0/crates/ide/src/doc_links.rs#L1

**Comment by kjeremy** [comment]
I think [textDocument/documentLink](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_documentLink) might be a good alternate approach to this.

**Comment by sasurau4** [comment]
I'll try it.

**Comment by matklad** [comment]
I think we have the basic support for this already? There are bugs, and the code needs to be refactored for a proper doc pipeline, but that merits separate tracking.
