### ISSUE TITLE
Module from path not recognized properly

### ISSUE THREAD

**Issue by cisaacson** [rust-analyzer/rust-analyzer#6170]
We are using modules defined with a path, and the path is code-generated code. The code is generated from a `build.rs` build script. `rust-analyzer` worked fine with this until a couple of days ago (not sure which version exactly).

Here is an example of the `mod` definition.

```
#[path = "../../target/to/my/path/generated_code.rs"]
pub mod generated_code;
```

In any module that imports this module now shows as an error. `cargo check` works fine and the code builds fine. Seems like a regression.

**Comment by cisaacson** [comment]
Verified that the Sept 28th 2020 release works fine, I rolled back to this one for now.

**Comment by cisaacson** [comment]
Using VS Code I downgraded to version `0.2.336` and it works fine for this use case. Hope that helps to find it.

**Comment by Veykril** [comment]
RA does not currently(and maybe never will from what I remember) resolve `#[path = ...]` attributes.

**Comment by cisaacson** [comment]
@Veykril I see, but it used to work? And actually my earlier comment about it working with the earlier version was incorrect. I don't understand why I am seeing it now, and not before the last few days. We may switch to a proc_macro to get around this.

**Comment by flodiebold** [comment]
I'm pretty sure we do resolve path attributes, as long as they stay within the project workspace.

**Comment by cisaacson** [comment]
> I'm pretty sure we do resolve path attributes, as long as they stay within the project workspace.

Our path is to the `target` dir. Can you define what qualifies as `within the project workspace`?

**Comment by cisaacson** [comment]
The issue was the `target` dir, we changed it to another path in the `src` dir and it works fine. Closing the issue, thanks for the quick help.
