### ISSUE TITLE
Small change in rustup rust-src component breaks rust-analyzer

### ISSUE THREAD

**Issue by ddboline** [rust-analyzer/rust-analyzer#6178]
After upgrading rust to 1.47.0 via rustup I get the following error from rust-analyzer:
```
rust-analyzer failed to load workspace: Failed to find sysroot for Cargo.toml file /home/ddboline/setup_files/build/garmin_rust/Cargo.toml. Is rust-src installed?: could not find libcore in sysroot path `/home/ddboline/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/`
```
This appears to be the result of ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src being renamed to ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library, creating a symlink from library to src serves as a workaround.

**Comment by bjorn3** [comment]
Which version of rust-analyzer are you using? This should have been fixed a while ago.

**Comment by ddboline** [comment]
I'm using it through the rust-analyzer VSCode extension, which is v0.2.336.

**Comment by jonas-schievink** [comment]
I can't reproduce this locally

**Comment by robatipoor** [comment]
after update rust 1.47 stable version I got the same error message in linux
rustup component add rust-src --toolchain stable info: component 'rust-src' is up to date
ls $(rustc --print sysroot)/lib/rustlib/src/rust/src liballoc libcore libstd
rust-analyzer --version rust-analyzer e5f252a

**Comment by julientregoat** [comment]
same for me after updating to 1.47

**Comment by lnicola** [comment]
Do you have `RUST_SRC_PATH` set?

**Comment by robatipoor** [comment]
> Do you have `RUST_SRC_PATH` set?

yes 
`echo $RUST_SRC_PATH`
/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src

**Comment by lnicola** [comment]
That path has recently changed, as @ddboline has noticed. You should unset the variable or fix it.

**Comment by ddboline** [comment]
@lnicola Yep, that was the problem, a forgotten RUST_SRC_PATH entry in ~/.bash_profile, I'm gonna go ahead and close this issue.

**Comment by flodiebold** [comment]
Maybe we could try `$RUST_SRC_PATH/../library` if `$RUST_SRC_PATH` doesn't work :thinking:

**Comment by SomeoneToIgnore** [comment]
If I got the idea right, we recommend unsetting this variable to use RA, don't we?
Can we detect it on startup and show a warning pop-up or similar?

**Comment by lnicola** [comment]
There's already a fixme comment to drop support for the old path in 1.47, though we could wait for one more release.

**Comment by flodiebold** [comment]
I don't think there's a big cost to these workarounds, so I don't really see a reason to eagerly remove support for the old path. I do think RUST_SRC_PATH often causes problems, so it makes sense to warn users about it, but if we can just keep functioning in more situations, I don't see a reason not to. Or in other words, I don't see the sense in breaking people's setups just because some other people's similar setups are already broken.

**Comment by flodiebold** [comment]
But also, while we recommend not using RUST_SRC_PATH, I think there are setups where it's needed (otherwise we should just remove the support). So I don't think we can just show a warning on every startup.

**Comment by lnicola** [comment]
We _could_ warn if the path doesn't exist, but the "old" path still exists in the new directory structure IIRC. Or we could warn if we couldn't load the sysroot and the variable was set.

**Comment by bjorn3** [comment]
What about making it a preference instead of env var? That makes it much more visible.

**Comment by jonas-schievink** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/6185 adds an extra note to the error when `RUST_SRC_PATH` is set

**Comment by LU15W1R7H** [comment]
@jonas-schievink thanks! That fixed it for me.
