### ISSUE TITLE
Unable to download from github in VSCode (response 401)

### ISSUE THREAD

**Issue by Rasmus-Pontoppidan** [rust-analyzer/rust-analyzer#6182]
When installing rust-analyzer, I get the error message
"Failed to download: Got response 401 when trying to fetch release info for 2020-10-05 release".

I use Windows, but the error happens in the Windows version of VS Code, as well as WSL.

The entire fail message in the terminal is: 
ERROR [10/9/2020, 10:38:25 AM]: Error fetching artifact release info {
  requestUrl: 'https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/2020-10-05',
  releaseTag: '2020-10-05',
  response: {
    headers: Headers {
      [Symbol(map)]: [Object: null prototype] {
        date: [ 'Fri, 09 Oct 2020 08:38:26 GMT' ],
        'content-type': [ 'application/json; charset=utf-8' ],
        'content-length': [ '80' ],
        connection: [ 'close' ],
        server: [ 'GitHub.com' ],
        status: [ '401 Unauthorized' ],
        'x-github-media-type': [ 'github.v3; format=json' ],
        'x-ratelimit-limit': [ '60' ],
        'x-ratelimit-remaining': [ '53' ],
        'x-ratelimit-reset': [ '1602235424' ],
        'x-ratelimit-used': [ '7' ],
        'access-control-expose-headers': [
          'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset'
        ],
        'access-control-allow-origin': [ '*' ],
        'strict-transport-security': [ 'max-age=31536000; includeSubdomains; preload' ],
        'x-frame-options': [ 'deny' ],
        'x-content-type-options': [ 'nosniff' ],
        'x-xss-protection': [ '1; mode=block' ],
        'referrer-policy': [ 'origin-when-cross-origin, strict-origin-when-cross-origin' ],
        'content-security-policy': [ "default-src 'none'" ],
        vary: [ 'Accept-Encoding, Accept, X-Requested-With' ],
        'x-github-request-id': [ 'C522:F31B:58E81BE:68E4E2D:5F802182' ]
      }
    },
    status: 401,
    body: '{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}'
  }
}

**Comment by mstallmo** [comment]
Just hit this issue on my windows machine today as well. Any ideas on what the cause of the error might be?

**Comment by edwin0cheng** [comment]
What's the fail message shown ? Could you download the link directly ?

**Comment by Rasmus-Pontoppidan** [comment]
I actually solved this :) I created a new GitHub Token using the suggested URL when I chose "Create new GitHub Auth Token" (or something like that). I copied that token into the bar that popped up. Had no issues since.

**Comment by edwin0cheng** [comment]
Nice, close it now and feel free to reopen it needed.

**Comment by lnicola** [comment]
@mstallmo if it's a 401 from GitHub, your IP address is rate-limited, so either add a token or download it manually.

**Comment by mstallmo** [comment]
I was able to fix this as well with the new token, thanks! I thought I had a valid github token already entered but 🤷
