### ISSUE TITLE
derive_more imports not found

### ISSUE THREAD

**Issue by Timmmm** [rust-analyzer/rust-analyzer#6183]
In `Cargo.toml` dependencies:

    derive_more = "0.99.10"

In code:

    use derive_more::{From, Into, Add, AddAssign, Sum};

Using the VSCode extension it highlights all of the imports (`From`, `Into`, etc.) as `unresolved import`.

**Comment by bjorn3** [comment]
You can enable proc-macro support using

```jsonc
{
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
}
```

**Comment by Timmmm** [comment]
Ooo thanks, presumably there's some downside that explains why this isn't enabled by default?

**Comment by lnicola** [comment]
https://github.com/rust-analyzer/rust-analyzer/issues/6053#issuecomment-699030244

**Comment by Timmmm** [comment]
Ah, slower. Got it.
