### ISSUE TITLE
macro rename failed

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rust-analyzer/rust-analyzer#6184]
![image](https://user-images.githubusercontent.com/17974631/95584492-6c07d680-0a70-11eb-8442-e62face59bac.png)
after i rename the macro, the macro definition has been renamed, but all the reference not change.
![image](https://user-images.githubusercontent.com/17974631/95584537-7b871f80-0a70-11eb-9175-6c95456c4b85.png)

**Comment by IWANABETHATGUY** [comment]
![Uploading image.png…]()

**Comment by matklad** [comment]
needs minimal example to be actionable.

**Comment by IWANABETHATGUY** [comment]
https://github.com/IWANABETHATGUY/RSLint/blob/c51753b7e4737dc2489dfbad2506f054ebf81b75/crates/rslint_lexer/src/labels.rs#L385, here
