### ISSUE TITLE
strange behavior: swap files for not opened files in neovim, annoying to edit those files back.

### ISSUE THREAD

**Issue by dash2507** [rust-analyzer/rust-analyzer#6186]
While working with a rust project in Neovim, rust_analyzer checks all files in the project and creates swap files for the files with errors. with neovim, if the swap is already created for the file then to opening the file will ask first to recover from the swap. 

i.e.:
- src
   - a.rs   _<- This file has error._
   - lib.rs 

Opening lib.rs in neovim, rust_analyzer created two swap files one for lib.rs and another for a.rs because it has errors. If I try to open a.rs neovim tells me to recover the a.rs file based on swap file. 

If I disable the rust_analyzer with lsp, then it will only create single swap file. How to get rid of this behaviour.

**Comment by bjorn3** [comment]
https://github.com/neovim/neovim/blob/569e75799d7015b15631c80cee1feec561f29df7/runtime/lua/vim/lsp/callbacks.lua#L85

The LSP server in neovim should already filter away diagnostics for closed files.

**Comment by dash2507** [comment]
Thanks! I got it working by disabling the swap files completely.

**Comment by lnicola** [comment]
Closing for now.
