### ISSUE TITLE
can't infer rayon par_iter()

### ISSUE THREAD

**Issue by Silentdoer** [rust-analyzer/rust-analyzer#6192]
like title

**Comment by jonas-schievink** [comment]
This works for me:

```rust
use rayon::prelude::*;

fn f() {
    let x = [0, 1, 2].par_iter();
}
```

Please provide more info needed to reproduce this

**Comment by Silentdoer** [comment]
i m use vscode

**Comment by Silentdoer** [comment]
this is vscode rust analyzer plugin bug？

**Comment by lnicola** [comment]
It works in Code. Can you paste a snippet that shows the problem? If you had a local import (use) in a function, it's a known issue. Same if you had a very complex expression, e.g. if we can't decide a type used in the return expression of the lambda, we won't be able to tell what map returns.
