### ISSUE TITLE
Rust-analyzer error with rust-src

### ISSUE THREAD

**Issue by arijit79** [rust-analyzer/rust-analyzer#6193]
Today I encountered an error when I was using rust-analyzer inside VSCode

```
rust-analyzer failed to load workspace: Failed to find sysroot for Cargo.toml file /home/[PATH TO MY CARGO.TOML]. Is rust-src installed?: could not find libcore in sysroot path `/home/[USER]/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src`
```

I thought it was some issue with rust-src so I reinstalled it for a couple of times. Lastly I tried reinstalling my entire toolchain and installing rust-src but no lunk

Rust version 4.47.0
Rustup version 1.22.1
rust-analyzer e5f252a

**Comment by lnicola** [comment]
You should unset RUST_SRC_PATH if you have it set. The path changed in 1.47, and you might have the old one configured.

**Comment by arijit79** [comment]
Thanks. It fixed my issue. Closing off the issue
