### ISSUE TITLE
Workspace and enabled crate features break cargo metadata run

### ISSUE THREAD

**Issue by andre-richter** [rust-analyzer/rust-analyzer#6197]
Hi,

I am currently in the following situation. I have a workspace with a couple of members:
```
workspace_root/
    - Crate A (no features)
    - Crate B (features X and Y)
    - Crate C (no features)
    - .vscode/settings.json
```

`Crate B` has two features X and Y, which are mutually exclusive, but you need one of the two enabled (choice of feature decides whether one or another file is conditionally imported with a use-statement. For reasons of being explicit in what a feature enables, I'd like to leave the default feature blank and use distinct feature names).

To get auto-completion and all the other goodness, I want to enable feature `X` or `Y` for rust-analyzer. However, putting `"rust-analyzer.cargo.features": ["X"]` results in breakage, because the run of `cargo metdata` fails upfront (since you cant have features in workspace roots (without -Zpackage-features, which isn't set for the metadata invocation it seems).

I am also not sure if it would break something while processing the other crates that don't have this feature, but it seems it doesn't even get there because of the failed `metadata` run.

It seems I can't override the `cargo metadata` command. Any other workarounds? Or would this need some code changes to rust-analyzer?

Thanks a lot,
Andre

**Comment by matklad** [comment]
Yeah, I don't think there's any work-around here besides `-Zpackage-features`. Fundamentally, we need upstream `cargo metadata` support here. 

I guess, opening individual crates as separate projects might also work.

**Comment by matklad** [comment]
I think this became possible recently with the new feature resolver. Specifically, this now works:

> However, putting "rust-analyzer.cargo.features": ["X"] results in breakage, because the run of cargo metdata fails upfront (since you cant have features in workspace roots (without -Zpackage-features, which isn't set for the metadata invocation it seems).

**Comment by andre-richter** [comment]
Indeed, it works now. Thanks for noticing! :+1:

**Comment by daprilik** [comment]
It seems this issue still crops up in cases where you have multiple workspace roots (e.g: via `linkedProjects). If different workspaces have different feature sets, the exact same manifest error as in OP occurs.
