### ISSUE TITLE
Adapt Salsa (red-green) algorithm to IDE use-case

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#62]
rustc uses the red-green algorithm to implement on-demand and incremental compilation: https://rust-lang-nursery.github.io/rustc-guide/incremental-compilation.html, and it looks like the perfect basis for Code Analyzer support as well.

However, there's a fundamental difference between how rustc does red-green, and how Code Analyzer works.

Command-line compiler operates in a sequence of invocations, so there are distinctly separate phases of updating the root data and calculating queries. 

In Code Analyzer, query evaluation and data modification can happen concurrently. Consider the following sequence of events

* user types something in `foo.rs`
* we start a job to do reparsing and basic syntax-based highlighting
* re parsing finishes
* we start a job to infer types inside `foo.rs` and present errors
* user types something in other file, `bar.rs`.

That is, we have an in-progress query on our hands, and a set of changes to apply. What we want is

* to apply changes as fast as possible
* preferably, not to loose reparsing info for `foo.rs`
* preferably, cleanly cancel an in-flight request.

Here are some options to deal with the problem

* we can wrap QueryEngine in an `RwLock`, so that all all request acquire and hold read lock for the duration of the request, modifying the root facts requires acquiring a write lock. When we receive an update request, we cancel all pending requests, wait for them to finish and apply updates. This is the approach used in IntelliJ. It should be very efficient in the total amount of work done, but can cause slow response if cancellation is not threaded throughout all of the requests.

* we can wrap QueryEngine in an `Arc` and use `Arc::make_mut` to apply updates. This requires QueryEngine to be cheaply clone (so, `im::HashMap` instead of `std::HashMap`), and needs an intricate operation of cloning the database as queries are storing new results into it.

* we can implement the first solution by making use of existing interior mutability in QueryEngine. Specifically, we can store an atomic timestamp, which is incremented before we apply changes. When we execute queries, we check the current timestamp and auto-cancel the request, if it is greater than the request-start time.

It's interesting that these solutions are not optimal in a sense that if the current query deals exclusively with `foo.rs` file, and modifications apply only to `bar.rs` file, we loos the results of the query, although they are not affected by modification.

**Comment by matklad** [comment]
One interesting midnight thought:
 
If I understand correctly, the model in rustc is purely push-based: to check up-to-dateness of the query, you re-ask all dependent queries. 

I think there is a class of queries with large fan-in, for whom a push-based model might make more sense. 


Consider, for example, the following query:

> The set of items declared by all modules of the crate

This seems to be an important query: because only the bodies of items are typically edited, the results of this query should be stable, and they determine the module structure, imports, and results of name resolution for paths outside of item bodies: quite useful things. 

Now, using a pull-based model works badly for this query: to check if it is up-to-date, we need to iterate all the files in the crate, which is mostly useless work, because most of them are not changed!

Push-based model works better: in theory, after a file edit, we can verify, that the set of declared items in a file is not changed and avoid recomputing the rest.

I think this also fits into Salsa in a general way: 

* we designate specific nodes as push-based
* when constructing such nodes, we travers the dep graph along reversed edges and mark all edges as push-based.
* when changing the ground facts, we follow each push-edge and mark it as potentially changed. 
* when evaluating query for a push-based node, we check only only maked edges, instead of all of them


Note that we still only recompute queries on demand! however, we have a better insight into which parts might actually change (which we pay for by an additional work during modification).

**Comment by aochagavia** [comment]
Should this be moved to https://github.com/salsa-rs/salsa now we have finally migrated to it?

**Comment by matklad** [comment]
Yeah, I think this could be closed. The only bit we *might* need, but which is missing from salsa, is https://github.com/salsa-rs/salsa/issues/41
