### ISSUE TITLE
Implemnt **find all impls** function

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#620]
Looks like we have all the pieces in play to do **find all impls** query. Not sure what's the best way to expose it via LSP API.

**Comment by kjeremy** [comment]
Maybe a codelens?

**Comment by matklad** [comment]
Yeah, code lens might be a good choice!

**Comment by kjeremy** [comment]
Depending on the performance (since I'm thinking by "find all impls" you mean implementations of traits?)we may need to implement `codelens/resolve`

**Comment by kjeremy** [comment]
What are the steps involved in this on the analysis side?

**Comment by kjeremy** [comment]
So I think the steps for "find impls of trait" would be:

1. find all `ast::TraitDef` in a file
2. For each module in the workspace (?) find all impl blocks that correspond to that trait
3. For each impl block find the struct that it is for and file/pos
4. Return list of file/pos to the LSP

Does that sound right?

**Comment by matklad** [comment]
yep!

1. Here we should also look for structs and enums. I'd even start with structs and enums, and added traits later.
2, 3 should be handled by https://github.com/rust-analyzer/rust-analyzer/blob/0974e6abeb9c3f047e21c3e23769b93c9e7dcaf3/crates/ra_hir/src/db.rs#L80

**Comment by kjeremy** [comment]
Ok I think I misunderstood. For traits I was assuming it would resolve the locations of structs that implemented those traits. But for structs and enums it would return the location of the impl blocks correct (which is also probably textDocument/implementation)?

**Comment by kjeremy** [comment]
In going from a ast `StructDef` to a `hir::Struct` does it make sense to add a `struct_from_source` to `source_binder`? Ince I have the `Struct` (or I guess `Enum`) how do I resolve that to a `Ty`? I guess my larger question is: how to go from something in `code_model_api` to a `Ty` without making the type_for_* fn's public?

**Comment by matklad** [comment]
>In going from a ast StructDef to a hir::Struct does it make sense to add a struct_from_source to source_binder?

Yes.

>how do I resolve that to a Ty?

I think we should add a `fn ty(&self, db: &impl HirDatabase) -> Ty` methods to `Struct` and `Enum`.

**Comment by kjeremy** [comment]
So to get back a source location for the block I can iterate through the `ImplItem`s and pick out their source and then find the parent ast node but that probably won't work with an empty block.

**Comment by kjeremy** [comment]
@matklad Let's talk about impls of traits. Do I need to extend `TyFingerprint` to also include a variant for `Trait(code_model_api::Trait)` and handle that in `collect_recursive`? I think if I did that I could then create a lookup function like `CrateImplBlocks::lookup_impl_blocks` but for traits.

**Comment by flodiebold** [comment]
@kjeremy The `impls` in `CrateImplBlocks` are supposed to be indexed by target type, not trait; and `TyFingerprint` is supposed to be a simplified form of `Ty`. I think there should be a separate index of impls by implemented trait.

**Comment by kjeremy** [comment]
@flodiebold so basically something like `CrateImplBlocks { ... impls_by_trait: FxHashMap<TraitId, Vec(ModuleId, ImpId)> }`?

**Comment by flodiebold** [comment]
Seems reasonable.
