### ISSUE TITLE
Fails to load on Arch W/ Doom Emacs.

### ISSUE THREAD

**Issue by ergpopler** [rust-analyzer/rust-analyzer#6201]
installed via these instructions: 

    Run the following commands:

    rm -rf ~/.emacs.d ~/.doom.d
    git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
    ~/.emacs.d/bin/doom install

    Open ~/.doom.d/init.el in an editor. Emacs, vim -- wherever.

    Scroll down to ;rust under :lang and replace it with (rust +lsp)

    Scroll up to ;lsp under :tools and remove the semicolon in front of it.

    Install rustup by running this shell command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

    Install rls with rustup component add rls rust-analysis rust-src

    Run ~/.emacs.d/bin/doom env

    Run ~/.emacs.d/bin/doom sync

    Start Emacs

I then installed Rust analyzer via various methods, reinstalled arch and tried again and still to no avail.

"Error from the Language Server: Rust-analyzer is still loading... (Unknown Error) then never loads..."

Following those instructions nigh exactly the same on Ubuntu 20.04 results in a functional emacs with Rust-analyzer.

**Comment by matklad** [comment]
Hm, no idea what might be wrong here. Might be useful to get some logs out of emacs! What LSP messages are exchanged, what is printed by rust-analyzer to stderr, etc.

**Comment by lnicola** [comment]
Can you confirm that it still works, despite the error message?

![image](https://user-images.githubusercontent.com/308347/96002128-7398f800-0e41-11eb-8d9f-5024cc6e8845.png)

**Comment by lnicola** [comment]
The "is still loading" error is actually a response from the LSP server for requests that come from the client before the project was loaded.

**Comment by ebroto** [comment]
I was having the same problem, the "still loading" message was never going away and code was not being highlighted. In my case the log showed this:
```
[ERROR rust_analyzer::reload] failed to load workspace: Failed to find sysroot for Cargo.toml file /home/ebroto/src/ebroto-clippy/clippy_lints/Cargo.toml. Is rust-src installed?: could not find libcore in sysroot path `/home/ebroto/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src` (`RUST_SRC_PATH` might be incorrect, try unsetting it)
```
I had `RUST_SRC_PATH` set to a different channel than the one the project was actually using. Unsetting that variable solved the problem for me. Not sure why it started manifesting today because I think I set that variable months ago and forgot about it :)

**Comment by zeroclock** [comment]
It may be valueable to ensure `cargo check` finish correctly.

I got same problem when switched Mac to Linux.
In my case, it seemed to be permission related error and executing commands below worked for me :)

```shell
$ cd your project root
$ cargo check # some permission errors occurred
$ sudo rm -rf ~/.cargo/git/checkouts/*
$ sudo rm -rf ./target
$ cargo check # again
```

**Comment by matklad** [comment]
Closing: I don’t this this issue is specific enough to be fixable. Recently, we somewhat improved out error reporting during project load.

in particular, the clients can implement this extension: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#server-status
