### ISSUE TITLE
Completing field starting with _ gives double _

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#6203]
```rust
struct A {
    _marker: PhantomPinned,
}

fn a() {
    A {
        _<|>
    }
}
```

will result in

```rust
struct A {
    _marker: PhantomPinned,
}

fn a() {
    A {
        __marker
    }
}
```

**Comment by fmease** [comment]
Noted, I am going to take a look and also check if it happens in other cases like function parameters.

**Comment by fmease** [comment]
I cannot reproduce this at all. I tried rust-analyzer version 0.2.344 (2020-10-12 (b7596d2)) and master (unreleased (93de491)). Can anybody reproduce this with their setup?

**Comment by lnicola** [comment]
I can't.

**Comment by bjorn3** [comment]
I still got last weeks version. With this weeks version it works fine.
