### ISSUE TITLE
Auto-import: invalid type: null, expected struct CodeActionParams

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#6204]
```rust
struct A {
    _marker: PhantomPinned, // try to auto-import this, server crashes
}

fn main() {

}
```

```
thread 'main' panicked at 'Invalid request
Method: experimental/resolveCodeAction
 error: invalid type: null, expected struct CodeActionParams'
```

**Comment by SomeoneToIgnore** [comment]
Works for me for today's nightly: `rust-analyzer version: nightly (b7596d2)`

![out](https://user-images.githubusercontent.com/2690773/95766952-b2517580-0cbc-11eb-860f-b66ae18d2b8c.gif)

**Comment by lnicola** [comment]
Tested at 518f6d772482c7c58e59081f340947087a9b4800.

**Comment by SomeoneToIgnore** [comment]
Can confirm that almost any auto import fails now on the fresh nightly.

**Comment by lnicola** [comment]
Probably #6200 CC @kjeremy.

**Comment by lnicola** [comment]
b7596d248382aa88b81da4dd6c7598993bc4b787 also fails for me.

**Comment by max-frai** [comment]
Confirm that almost each auto import fails.

**Comment by hammypants** [comment]
This is also happening for `Implement missing members` code action for traits.

**Comment by lnicola** [comment]
Looks like we're sending an invalid message:

```
[Trace - 12:26:34] Sending request 'experimental/resolveCodeAction - (54)'.
Params: [
    null
]
```

**Comment by lnicola** [comment]
Filed https://github.com/rust-analyzer/rust-analyzer/pull/6213 for it.

**Comment by kjeremy** [comment]
Good find! Interestingly enough LSP 3.16 will have a `codeAction/resolve` request.

**Comment by matklad** [comment]
Yeah, we should switch to codeAction/resolve not sure if it'll square with our groups support though....
