### ISSUE TITLE
Request: Completion/Intellisense for struct names in destructured variable initialization

### ISSUE THREAD

**Issue by KSXGitHub** [rust-analyzer/rust-analyzer#6210]
I often do this:

```rust
let TypeName { foo, bar } = expr();
```

I wish the completion menu shows me `TypeName` when I first type `T` after `let`.

**Comment by matklad** [comment]
I think the relevant code & tests are here:

https://github.com/rust-analyzer/rust-analyzer/blob/3e450cf89f9fcb7356a12487ccac7f8e21811095/crates/ide/src/completion/complete_unqualified_path.rs#L9
