### ISSUE TITLE
nightly (3d13939): local use highlight issue + merge import panic

### ISSUE THREAD

**Issue by Geobert** [rust-analyzer/rust-analyzer#6212]
Multiple things with nightly (3d13939):
- local use doesn't seems to be manage for semantic highlighting:
```rust
fn my_fn() {
    use picky::x509::name::NameAttr;

let attr = match attr {
            "cn" => NameAttr::CommonName,
            "c" => NameAttr::CountryName,
            _ => unreachable!(),
        };
}
```

"NameAttr::CommonName" showed "unresolvedReference" as semantic token type

and if I move the use outside the function, it becomes "enumMember"

Then I moved the use at the top of the file, and wanted to use the merge import:
```
thread 'main' panicked at 'Invalid request
Method: experimental/resolveCodeAction
 error: invalid type: null, expected struct CodeActionParams', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\lsp-server-0.3.4\src\msg.rs:163:17
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Info  - 09:13:17] Connection to server got closed. Server will restart.
```

**Comment by lnicola** [comment]
Local imports don't work: https://github.com/rust-analyzer/rust-analyzer/issues/1165

Merge panic is https://github.com/rust-analyzer/rust-analyzer/issues/6204.

**Comment by Geobert** [comment]
> Local imports don't work: #1165.

Oh, I didn't know it was here for a long time, noticed it this morning because of the string coloration. 

Thanks for the answer and sorry for the disturbance :)
