### ISSUE TITLE
Document rust-analyzer diagnostics

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#6215]
We should document all our diagnostics in the manual (probably don't need a lot of text, just the diagnostic code and maybe an example message). We could probably generate this similarly to the assist documentation.

**Comment by matklad** [comment]
Here's the relevant code:

https://github.com/rust-analyzer/rust-analyzer/blob/3e450cf89f9fcb7356a12487ccac7f8e21811095/xtask/src/codegen/gen_feature_docs.rs#L10-L18

To find existing diagnostics, look for impls of this trait:

https://github.com/rust-analyzer/rust-analyzer/blob/3e450cf89f9fcb7356a12487ccac7f8e21811095/crates/hir_expand/src/diagnostics.rs#L32-L42
