### ISSUE TITLE
Document auto-import

### ISSUE THREAD

**Issue by ndmitchell** [rust-analyzer/rust-analyzer#6225]
In my project we prefer to use `use crate::foo::bar`, even if `use super::bar` would work. Rust Analyzer always suggests `super` imports if it can. It would be great to:

* Have an action to turn `super` into `create` where possible.
* Have an option to insert `crate` references in preference to `super`.

**Comment by lnicola** [comment]
Does `rust-analyzer.assist.importPrefix` help here?

**Comment by ndmitchell** [comment]
Thanks @lnicola - that's exactly what I was after.

I note there aren't a huge amount of docs for that option, I searched the manual etc first - is it worth having some more docs on the options and what they do - perhaps even auto-generated from the .json file?

**Comment by lnicola** [comment]
More docs are always welcome :+1:.

**Comment by matklad** [comment]
Yeah, I think we should add a `Feature:` block in addition to the standard `Assist` one here:

https://github.com/rust-analyzer/rust-analyzer/blob/3e450cf89f9fcb7356a12487ccac7f8e21811095/crates/assists/src/handlers/auto_import.rs#L8

there, we should document that auto-import is triggered by assist, and explain the available options. 

auto-improt is big enough that it merits its own top-level feature section!

See the `source` link here: https://rust-analyzer.github.io/manual.html#magic-completions

**Comment by lnicola** [comment]
> See the source link here: https://rust-analyzer.github.io/manual.html#magic-completions

Uh-oh...
