### ISSUE TITLE
Wrong color of ? operator in face of hints

### ISSUE THREAD

**Issue by schungx** [rust-analyzer/rust-analyzer#6235]
Not sure if anybody raised this before...

When chaining, and one of the parts ends with an `?` operator, the hint's color bleeds into the `?`, like the following:

![image](https://user-images.githubusercontent.com/661318/96062534-7d197300-0ec8-11eb-9928-0d2776276f43.png)

Don't worry about the actual color (which is a faint grey) because I just set it this way.

In this example, the `?` at the end of the chaining line should be colored regular, instead of as a hint.

**Comment by lnicola** [comment]
Does it still happen if you disable ligatures? Or at least the ?: one, which doesn't make sense as Rust syntax.

**Comment by schungx** [comment]
You're right!  The problem is font ligatures!

Not sure whether I can selectively disable `?:`  in VS code, but true enough, disabling font ligatures solves the problem!

**Comment by lnicola** [comment]
I think you can, the Fira Code readmee describes how each of them is called.

**Comment by lnicola** [comment]
Sorry, I was thinking of https://github.com/tonsky/FiraCode/blob/master/extras/stylistic_sets.png, but there seems to be no alternative for that one.

**Comment by schungx** [comment]
Putting a space in front of the colon (or omit it completely if the colors are different enough from text) is a possible solution...  I am not sure how many different ligatures end with `:`, so this may be worth considering.

**Comment by lnicola** [comment]
I filed https://github.com/tonsky/FiraCode/issues/1140 just in case, but I think a space or ZWNJ will work. Even if it's implemented, we should do that to support other fonts.

**Comment by lnicola** [comment]
Strangely, I don't see the same effect:

![image](https://user-images.githubusercontent.com/308347/96087028-e51d8880-0ecb-11eb-8445-c4b29d3740c9.png)

**Comment by schungx** [comment]
Are you using a font without ligatures support?

**Comment by schungx** [comment]
That's weird... perhaps you're using a font without `?:` ligature?  I believe `?:` is not very common...

**Comment by lnicola** [comment]
No, it's Fira Code 5.2.

**Comment by schungx** [comment]
I have a really old version of Fira Code, version 1.204.  Let me install the latest version to check...

**Comment by lnicola** [comment]
It was removed in https://github.com/tonsky/FiraCode/blob/master/CHANGELOG.md#30-april-9-2020, I don't know why I couldn't find it before.

**Comment by schungx** [comment]
OK, confirmed.  The latest version of Fira Code no longer has this problem!  Good catch!!!

Unfortunately, `JetBrains Mono` still has it...

**Comment by lnicola** [comment]
Can you test #6236?

**Comment by schungx** [comment]
Hhhmmm... don't know how to install a custom build of ra... I just load it from the the official extensions.

My suggestion is to add the `JetBrains Mono` font.  The latest version should still have `?:`.

`Source Code Pro` also doesn't have `?:`, so right now the only recent version popular font that has it will be `JetBrains Mono`...

**Comment by lnicola** [comment]
> My suggestion is to add the `JetBrains Mono` font.

I find building the extension easier than installing fonts on Linux :sweat_smile:.

Does this work?

![image](https://user-images.githubusercontent.com/308347/96094087-92e16500-0ed5-11eb-841a-9edbdbfda44b.png)

**Comment by schungx** [comment]
> I find building the extension easier than installing fonts on Linux 😅.

That's why you're DA MAN!

> Does this work?

Your picture looks just fine!

**Comment by schungx** [comment]
Just for future reference, `?:` also seems to conflict with TypeScript:

https://github.com/tonsky/FiraCode/issues/970
