### ISSUE TITLE
Refactor for `field init shorthand`

### ISSUE THREAD

**Issue by ShuiRuTian** [rust-analyzer/rust-analyzer#6237]
``` rust
struct User {
    username: String,
    email: String,
}

fn build_user(email: String, username: String) -> User {
    User {
        email: email, // here, it could refactor to "email", just like "username" in the next line!
        username,
    }
}
```

**Comment by matklad** [comment]
This is aready implemented:

![image](https://user-images.githubusercontent.com/1711539/96118837-61c05f00-0eec-11eb-80f5-e76b1fa4512a.png)

**Comment by ShuiRuTian** [comment]
Oops, sorry for the mistake.
I come from eslint, which would mark the whole "email: email" with underline, rather than "..." under the start place.
Sorry for reporting this issue mistakenly again.

**Comment by matklad** [comment]
It’s the display issue: we flag the whole thing with a hint severity, it’s VS Code that truncates hints to the first character.

ES Lint probably uses warn severity, but this is not something we want to do.
