### ISSUE TITLE
Automatically prefix `///` when adding newlines in doc comments

### ISSUE THREAD

**Issue by zicklag** [rust-analyzer/rust-analyzer#6254]
In RLS in VSCode it would automatically add the `/// ` prefix while I'm inside of a doc comment and I add a newline. This was rather convenient and it would be cool to have Rust Analyzer do this as well.

**Comment by bjorn3** [comment]
You need to explicitly enable it: https://github.com/rust-analyzer/rust-analyzer/blob/bf1043cac2f3cc2264d9fcda242f63616f4efa1b/crates/ide/src/typing/on_enter.rs#L22

**Comment by zicklag** [comment]
Oh, nice, that works. Ah, that is in the docs, too. Would it be possible to make that a setting, or is that not how VSCode works?

**Comment by lnicola** [comment]
I think we can toggle preferences at run-time, but can't add keybindings, so not really.

**Comment by zicklag** [comment]
Bummer. Oh, well. Thanks for the help! :)

**Comment by HKalbasi** [comment]
Does it really needs LSP extension and manual shortcut? All languages ​​have some kind of comments that should be extended on enter, but I don't think they do it this way. We can't do what RLS does?

**Comment by lnicola** [comment]
We can, but matklad isn't fond of the idea because it's reimplementing part of the Rust syntax in regexes, instead of using the proper parser in RA.

In practice there might be some corner cases where the regexes don't work, but IMO it's still better than sluggish Enter.

**Comment by HKalbasi** [comment]
Apart from speed, default-ness is also an important issue IMO.

Is the reimplementing regex something like `\s*\/\/[\/,!].*`? Or it is not that easy?

**Comment by lnicola** [comment]
See https://code.visualstudio.com/api/language-extensions/language-configuration-guide#on-enter-rules.

Does this already work in `vscode-rust`? It doesn't seem to be configured in https://github.com/rust-lang/vscode-rust/blob/master/language-configuration.json.

**Comment by HKalbasi** [comment]
> Does this already work in vscode-rust?

Yes it works. It is here: https://github.com/rust-lang/vscode-rust/blob/master/src/extension.ts#L287

Any argument against copying it as is in RA? People that need LSP based behavior still can add a shortcut I think?
