### ISSUE TITLE
Unable to find modules generated by proc_macro

### ISSUE THREAD

**Issue by dodomorandi** [rust-analyzer/rust-analyzer#6258]
I feel slightly bad for posting this, because I really suspect this can be a PITA.

Crates like `graphql_client` creates a pretty good amount of modules, structs and impls based on graphql files an a few derives. Unfortunately rust-analyzer does not like the situation: it is unable to deduce most of the things, and, even worse, it is unable to detect the modules automatically generated, leaving annoying errors around.

I crated a small dummy repository based on the _official_ [github example](https://github.com/graphql-rust/graphql-client/tree/master/examples/github) in order to make testing easier, you can find it [here](https://github.com/dodomorandi/break-rust-analyzer).

Please don't hate me for this matklad and others, I am really a huge fan of your work -- it took me more than two weeks to finally think "I just need to let them know"...

**Comment by bjorn3** [comment]
You can enable proc-macro support using

```jsonc
{
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
}
```

**Comment by bjorn3** [comment]
I just tested your reproduction repo. I get the same problems with proc macros enabled. @matklad Is it possible that modules defined by proc macros are ignored?

**Comment by matklad** [comment]
Possible, but not intended.

**Comment by jplatte** [comment]
In [ruma](https://github.com/ruma/ruma), lots of (probably all) proc-macro-generated types are also not found (both generated by a derive macro and a function-like macro). Both should work, right?

**Comment by edwin0cheng** [comment]
@dodomorandi I just checked that in current master it works, would you like to test it again ?

![Screenshot 2020-12-28 223819](https://user-images.githubusercontent.com/11014119/103221422-8b225000-495d-11eb-8f1c-57a1e43148da.png)

**Comment by dodomorandi** [comment]
@edwin0cheng Thank you for the check! The situation is much better, you are right. I am not sure the completion engine is able to handle things from the modules generated with proc-macro, but I am with NeoVim + CoC, it could also be a different issue.

@jplatte are you seeing the same improvements developing ruma? In that case I think we can close this issue :blush:

**Comment by jplatte** [comment]
Yeah, no issues here anymore 🙂
