### ISSUE TITLE
Doesn't handle Rust 1.47+ rust-src paths

### ISSUE THREAD

**Issue by sdroege** [rust-analyzer/rust-analyzer#6264]
```
Failed to find sysroot for Cargo.toml file Cargo.toml. Is rust-src installed?: could
not find libcore in sysroot path `~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src`
```

The new path seems to be `~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library`

**Comment by lnicola** [comment]
Do you have RUST_SRC_PATH set?

**Comment by sdroege** [comment]
I actually did. For some reason I thought this was autodetected. Sorry for the noise, should've had my coffee first :)

**Comment by lnicola** [comment]
It is autodetected, but not if the variable is set. You can probably remove it.

**Comment by DouglasLivingstone** [comment]
I'm seeing a similar issue with Rust 1.47.0:

> rust-analyzer failed to load workspace: Failed to find sysroot for Cargo.toml file /home/ubuntu/.../Cargo.toml. Is rust-src installed?: can't load standard library from sysroot /home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src (discovered via `rustc --print sysroot`) try running `rustup component add rust-src` or set `RUST_SRC_PATH`

`rustc --print sysroot` prints:

```
/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
```

`rustup component add rust-src` prints:

```
info: component 'rust-src' is up to date
```

and `RUST_SRC_PATH` is not set.

Like @sdroege, I do have source files under `.../stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library` but not `stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src`

**Comment by flodiebold** [comment]
@DouglasLivingstone is your rust-analyzer up to date? How have you installed it?

**Comment by DouglasLivingstone** [comment]
Hi @flodiebold, yes, I think it is up to date. Locally it works fine, I'm running it in VS Code 1.50.1 on Windows 10, but when I try to use it over a remote SSH connection it fails to load. The version number reported in the Rust Analyzer Client output window is:

```
INFO [10/23/2020, 1:34:42 PM]: Extension version: 0.2.352
```

Thanks for any help!

**Comment by flodiebold** [comment]
What version does the `Rust Analyzer: Show RA Version` command report?

**Comment by DouglasLivingstone** [comment]
Interesting, the output is:
```
rust-analyzer version: 2020-10-19 (c9c518e)
```
but `c9c518e` is tagged as the `2020-07-20` release. What would I need to do to force it to update?

**Comment by flodiebold** [comment]
Yeah, that's a 3 months old commit. Maybe you compiled it yourself? Do you have `serverPath` explicitly set? Otherwise I'd try deleting the `rust-analyzer-windows` binary and seeing if it downloads it again.

**Comment by DouglasLivingstone** [comment]
Brilliant, thanks, deleting `~/.vscode-server/extensions/matklad.rust-analyzer-0.2.352/` fixed it for me
