### ISSUE TITLE
rust-analyzer error hint in visual studio code

### ISSUE THREAD

**Issue by Vensence** [rust-analyzer/rust-analyzer#6269]
I got an extension error hint after I update rust and rust-analyzer extension in vscode;
the hint content is right here blow:
![image](https://user-images.githubusercontent.com/22963992/96348648-e83b9300-10dc-11eb-86ea-ae690cef5a30.png)
It said that I miss the source directory , I check the directory and it didn't exist indeed.
But I NEVER set the RUST_SRC_PATH before, so how can I solve this problem?
Thanks for any answer

**Comment by lnicola** [comment]
Try `rustup component add rust-src`.

**Comment by Vensence** [comment]
I've already add it before, and I just remove & add it again, but the hint still occurs

**Comment by lnicola** [comment]
The message is a bit misleading, it first looks in `C:\Users\Vensence\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\src\rust\library`, then in the path in the screenshot. I'm not sure what's wrong, but you could use https://docs.microsoft.com/en-us/sysinternals/downloads/procmon to see which paths the server is looking into.

**Comment by flodiebold** [comment]
The "`RUST_SRC_PATH` might be incorrect, try unsetting it" warning only happens if `RUST_SRC_PATH` is actually set, so there is something setting it.

**Comment by Vensence** [comment]
I check the environment settings there IS an environment variable named: "RUST_SRC_PATH", and I delete & reboot, problem solved!~
Thank you for all your support!!!~
