### ISSUE TITLE
"unresolved import" 

### ISSUE THREAD

**Issue by tigregalis** [rust-analyzer/rust-analyzer#6278]
I'm using Windows 10 Home version 1903, and Visual Studio Code 1.50.0, and rust-analyzer VS code extension version 0.2.344. I wasn't able to work out how to find the version of ra_lsp_server that's running.

I've seen this problem in a clone of the bevy repo at https://github.com/bevyengine/bevy . I'm seeing the below error in my "Problems" pane, but the project compiles fine (and using `cargo check` in the terminal doesn't warn us about anything).

![image](https://user-images.githubusercontent.com/38416468/96416210-4a51e080-1222-11eb-8a8b-1450b19bfdd6.png)

`bevy_math::Vec4` is ultimately a re-export of `glam::f32::Vec4`, but it sits alongside `bevy_math::Vec3` which is ultimately a re-export of `glam::f32::Vec3` which it doesn't have a problem resolving.

I've tried:

* restarting VS code - doesn't fix it
* tried changing the order of the `use` lines to trigger a re-check - doesn't fix it, which means it doesn't look like these are "stale" as per #4073, but that `cargo check` is finding a problem in rust-analyzer, but not in the terminal
* tried changing the order of `Vec4` vs `Vec3` to trigger a re-check - rust-analyzer continues to point to `Vec4` being unresolved, now in its new position, confirming this isn't "stale"
* I also tried "Restart Window" from the command palette in vain hopes (following on from #4073)
* cloning a fresh copy of https://github.com/bevyengine/bevy - I changed any line in `crates\bevy_render\color.rs` and saved it, which reproduced this behaviour

Having opened my local copy of the `glam` source in my `.cargo`, I'm now seeing the behaviour there.

Other issues that may or may not be related: #6258, #6063, #6038

I was able to trivially reproduce this - see repo https://github.com/tigregalis/glam-breaks-ra:  
![image](https://user-images.githubusercontent.com/38416468/96421414-54c3a880-1229-11eb-919f-9aed460fdf24.png)  
![image](https://user-images.githubusercontent.com/38416468/96421252-234add00-1229-11eb-93b2-d4e2c8182b1f.png)  
![image](https://user-images.githubusercontent.com/38416468/96421353-41b0d880-1229-11eb-8ab8-3c14ab568b9a.png)  
![image](https://user-images.githubusercontent.com/38416468/96421289-2e057200-1229-11eb-8ec5-d1a31c021bc6.png)

**Comment by Veykril** [comment]
Looks like `glam`'s `Vec4` uses `cfg` attributes to determine the definition of the struct: https://github.com/bitshifter/glam-rs/blob/121cfaaa56494993d1666468039b2da663fd9a06/src/f32/vec4.rs#L21-L42
But it doesn't do that for `Vec3`: https://github.com/bitshifter/glam-rs/blob/121cfaaa56494993d1666468039b2da663fd9a06/src/f32/vec3.rs#L10-L13
So I imagine that is the problem.

**Comment by bjorn3** [comment]
https://github.com/bitshifter/glam-rs/blob/d1b83da533c5ddb161f2da4d76faa33607d59c67/build.rs#L16

That `cfg` is set by the build script. I don't think rust-analyzer has support for this.

**Comment by lnicola** [comment]
Shouldn't they work by https://github.com/rust-analyzer/rust-analyzer/blob/1b3b8c7/crates/project_model/src/cargo_workspace.rs#L314-L326 (if `rust-analyzer.cargo.loadOutDirsFromCheck` is set)?

**Comment by lnicola** [comment]
@tigregalis can you try enabling `rust-analyzer.cargo.loadOutDirsFromCheck`? This seems to work for me.

**Comment by tigregalis** [comment]
@lnicola That's solved it, thanks. What is this option doing?

**Comment by lnicola** [comment]
It enables build script support, which makes those `#[cfg]`s work -- and also code generated at build-time, like other projects have.

**Comment by tigregalis** [comment]
Ok, thanks. I'll close the issue. It could be worth documenting though.

**Comment by a74731248** [comment]
> @tigregalis can you try enabling `rust-analyzer.cargo.loadOutDirsFromCheck`? This seems to work for me.

Could you please tell me how to enable this？

**Comment by flodiebold** [comment]
It's called `rust-analyzer.cargo.buildScripts.enable` nowadays and enabled by default.
