### ISSUE TITLE
Path to enabling build script and proc macro support by default

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#6279]
We've had a couple issue reports that turned out to be fixed by enabling build script and/or proc macro support. I think the reason these are off by default is that they can slow down the first load of a project by a lot. On the other hand, it's clear that they are needed to provide a good IDE experience.

So I think we'll want to turn them on in the future. The question, then, is when we should do that. We could:

 - enable them right now
 - wait for better proc macro support (to offset the loading cost with even better IDE support)
 - wait for a sandboxing story (which won't happen on a reasonable timeline)
 - anything else?

**Comment by bjorn3** [comment]
Another option would be to add a diagnostic for `env!("OUT_DIR")` and `#[derive(SomeProcMacroDerive)]` when the respective features are disabled to enable them. This won't help for dependencies, but it could for the current crate without the drawbacks associated with always enabling them.

**Comment by lnicola** [comment]
Closing in favor of #6448.
