### ISSUE TITLE
Line comment in multi-line comment causes textmate scopes to mark the entire rest of the file as a comment

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#6281]
Just putting this 
`/* // */`
line into a rust file will cause all subsequent lines to be marked as a `comment.block.rust`. This is on current nightly.
![image](https://user-images.githubusercontent.com/3757771/96450308-5172f180-1216-11eb-9700-dec224b4f019.png)

**Comment by Kimundi** [comment]
Can comfirm:

![grafik](https://user-images.githubusercontent.com/2903206/96705932-34652c80-1396-11eb-8571-9217d842078c.png)

For reference, without the `//`:

![grafik](https://user-images.githubusercontent.com/2903206/96706312-b6555580-1396-11eb-9001-5618b218d7d7.png)
It seems to style the entire document as a comment, and the only saving grace are the semantic informations that override the grammar later on.

**Comment by lnicola** [comment]
CC @dustypomerleau if you haven't seen this.

**Comment by dustypomerleau** [comment]
Yes I'll have a look - appears that the line comment is commenting out the block comment terminator when they are on the same line.
