### ISSUE TITLE
Opening Documentation for module opens parent module

### ISSUE THREAD

**Issue by CryZe** [rust-analyzer/rust-analyzer#6286]
If you try to open the documentation for a module, it directs you to the parent module instead.

Steps to reproduce:

1. Write something like this `use std::mem::swap;`
2. Put the cursor on `mem`
3. Run `Rust Analyzer: Open docs under cursor`
4. The documentation for `std` itself and not the `mem` module opens.

**Comment by matklad** [comment]
cc @zacps

**Comment by zacps** [comment]
Cheers for the report, I'll try to take a look at it sometime this week.
