### ISSUE TITLE
Autoindent is incorrect when typing '.'

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#629]
In complete_dot.rs:

```rust
match def_id.resolve(ctx.db) {
                    Def::Struct(s) => {
                        for field in s.fields(ctx.db) {
                            CompletionItem::new(
                                CompletionKind::Reference,
                                ctx.source_range(),
                                field.name().to_string(),
                            )
                            .kind(CompletionItemKind::Field)
                            .set_detail(field.ty(ctx.db).map(|ty| ty.subst(substs).to_string())) // HERE
                            .add_to(acc);
```

Typing Enter plus '.' indents the next line past the column that .set_detail and .add_to are at.

**Comment by gfreezy** [comment]
autoident doesn't work on my computer.

**Comment by academician** [comment]
Looks like this should be closed, if #653 fixed it?

**Comment by matklad** [comment]
Still reproduces on master

**Comment by adamrk** [comment]
@matklad, seems like this was resolved at some point? I'm not seeing it on master now.

**Comment by matklad** [comment]
![d](https://user-images.githubusercontent.com/1711539/85800011-811a5d00-b740-11ea-9bab-eeae7998f6d9.gif)

still repros for me

**Comment by adamrk** [comment]
Oh interesting, maybe there's some setting I'm missing? I do use the vim vscode extension, so maybe that messes something up.

![out](https://user-images.githubusercontent.com/16367467/85814091-65757d80-b765-11ea-8790-a1a6c4699b6d.gif)

**Comment by matklad** [comment]
Your code is is just different :)

**Comment by alexfertel** [comment]
Is this one still happening? I can't reproduce it 🤔 and the code that handles it seems different (and actually looks like the correct way to do this).

```rust
let prev_indent = IndentLevel::from_node(&parent);
let target_indent = format!("    {}", prev_indent);
```
