### ISSUE TITLE
profile using coz

### ISSUE THREAD

**Issue by benmkw** [rust-analyzer/rust-analyzer#6296]
https://github.com/plasma-umass/coz

Actually I want to try this myself but cause I did not do it for several weeks now and am usually not on linux I think I may post it here incase someone already did that and found it to be not working or wants to try it :)

**Comment by bjorn3** [comment]
Rust-analyzer doesn't really use multithreading as far as I know. This makes coz not very useful. Coz is designed to profile multithreaded programs.

**Comment by benmkw** [comment]
I think they found some stuff in sqlite which was also not directly related to multithreading as only multiple clients accessed the database at the same time but the database itself is single threaded but it also seems to me that if RA does not use multithreading in its dependencies then this might be of limited use.
So this could be analogous to the LSP client making multiple requests more or less at the same time. Not sure if that happens/ is actually a similar case, basically thinking out loud here.

**Comment by matklad** [comment]
Folks are welcome and encouraged to profile rust-analyzer in whichever way they find useful, and to contributed profile-based improvements. 

However, it doesn't makes sense for us to focus on code profilng at the moment, so I am closing this issue to reduce the overal amount of open issue.s
