### ISSUE TITLE
Add quick fix for return type mismatch: "Change return type of a function to the type inferred from the returned variable"

### ISSUE THREAD

**Issue by avkonst** [rust-analyzer/rust-analyzer#6303]
It is feature request. I find I need it very frequently when rapidly develop new code:

Here is the error I see:
![image](https://user-images.githubusercontent.com/3971413/96668104-f0ceea80-13b6-11eb-9f40-863762117060.png)

And I would like to have a quick fix provided by VS code, which would add (or change to) correct return type annotation to the function automatically:
![image](https://user-images.githubusercontent.com/3971413/96668192-1c51d500-13b7-11eb-9f17-cb5fe6be4605.png)

**Comment by flodiebold** [comment]
We can't provide quick fixes for rustc diagnostics, and we currently don't report type mismatches from our own type checker (because it would probably still lead to many false positives), which makes this currently not so easy.

**Comment by Veykril** [comment]
Would it maybe make sense to offer an assist instead. which is enabled for functions that don't have a return type set to add one inferred from the function body?

**Comment by flodiebold** [comment]
Hm yeah if we restrict it to functions that don't have a return type set we could probably handle it similarly to the existing "wrap return type in Ok" diagnostic/assist.

**Comment by avkonst** [comment]
> Would it maybe make sense to offer an assist instead, which is enabled for functions that don't have a return type set to add one inferred from the function body?

Yes, I meant assist action. I do not see why limiting it to functions with no return type makes it easier, but it would be a good start for sure.

**Comment by flodiebold** [comment]
Closing since the assist exists now.
