### ISSUE TITLE
New grammar changes seem to not handle comments correctly

### ISSUE THREAD

**Issue by Kimundi** [rust-analyzer/rust-analyzer#6309]
If you have a opening and closing block comment, then it seems to get confused by the presence of interior `//` (See the attributes):

![grafik](https://user-images.githubusercontent.com/2903206/96705932-34652c80-1396-11eb-8571-9217d842078c.png)

For reference, without the `//`:

![grafik](https://user-images.githubusercontent.com/2903206/96706312-b6555580-1396-11eb-9001-5618b218d7d7.png)

Additionally, it also seems to sometimes think that a block comment is not terminated at all (might be the same root cause as above), and style the _entire_ file as a comment.

**Comment by lnicola** [comment]
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6281?

**Comment by Kimundi** [comment]
Ah indeed, must have missed that one.
