### ISSUE TITLE
Syntax highlighting consider __ident as a comment inside macro arguments

### ISSUE THREAD

**Issue by bnjjj** [rust-analyzer/rust-analyzer#6311]
I have this bug since the last release on monday 19th

Maybe I'm the only one with this current behavior

![bug_ra_syntax](https://user-images.githubusercontent.com/5719034/96724000-98481f00-13af-11eb-9ca8-85d81354a3df.png)

**Comment by lnicola** [comment]
Do you have semantic highlighting disabled?

CC @dustypomerleau

**Comment by bnjjj** [comment]
![rust_analyzer_bug_hl](https://user-images.githubusercontent.com/5719034/96731302-6470f780-13b7-11eb-9563-a509e63cf18e.png)

no I also have same behavior in a macro_rules! bloc
