### ISSUE TITLE
Maybe avoid duplication for clone()d parameter name inlay hints?

### ISSUE THREAD

**Issue by shish** [rust-analyzer/rust-analyzer#6315]
I don't know if this is a VSCode thing, a VSCode-rust thing, a rust-analyzer thing, or something else, so apologies if this is in the wrong place :)

It seems that the parameter name inlay hints are smart enough that when I pass a variable named `cache` or `args.cache` into the function's `cache` parameter, it doesn't duplicate the parameter name there. But if I pass `name.clone()` to the `name` parameter, it treats that as a different thing, even though I as a (admittedly non-expert) user would say that that's redundant - should the parameter names be hidden here?

<img width="300" alt="Screenshot 2020-10-21 at 20 05 30" src="https://user-images.githubusercontent.com/40659/96771059-166ceb80-13d9-11eb-90eb-7c9f0c0074bb.png">

**Comment by SomeoneToIgnore** [comment]
Than makes perfect sense!

We have a set of geuristics here: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/inlay_hints.rs#L324

we can add one more there.

Those heuristics tend to bloat though, so some time later we need to come up with a refactoring there.
