### ISSUE TITLE
Error: Syntax Highlighing in strings after lines starting with '>' in VSCode is incorrect

### ISSUE THREAD

**Issue by h-bex** [rust-analyzer/rust-analyzer#6323]
Environment:

- VSCode: 1.50.1 (Windows 10 Version)
- rust-analyzer Extension: v0.2.352
- rust-analyzer version: 2020-10-19 (3ca97b0)

The code shown below has been formatted inside VSCode
The single `>` in line 13 results in the wrong highlighting of the string in line 17.
The code was formatted using VSCode with the rust-analyzer extension.
Just open the code as rust file in VSCode:

```rust
use std::collections;

fn main() {
    let dbg_message = "This is an intersting break message"; // Correct highlighting
    println!("Works");
}

type this_is_a_really_long_type_that_goes_for_a_long_column = i32;

thread_local!(
    static x: collections::VecDeque<
        this_is_a_really_long_type_that_goes_for_a_long_column,
    > = Default::default();
);

fn works() -> &'static collections::VecDeque<i32> {
    let dbg_message = "This is an intersting break message"; // Wrong highlighting
    todo!();
}
```

Look especially for the variable `dbg_message`, which occurs two times in the code.  See how it is displayed the first time (All letters in green) and in the second place (different colors, but no one in green).

After joining the line defining the x to

```rust
    // ...
    static x: collections::VecDeque<
        this_is_a_really_long_type_that_goes_for_a_long_column,> = Default::default();
    // ...
```
The syntax highlighting of the second string is correct again.

NOTE: This does not only happen for a line starting with `>` in a thread_local block, but seem to also happen with functions returning long return-types, so the the format breaks a single `>` to a new line. However I did not find an easy example breaking the syntax highlighting.
It is also not necessary to have a line-break before the `>`; a simple space seem to be sufficient to show the same wrong behaviour.

**Comment by dustypomerleau** [comment]
This happens even with RA disabled. It's related to the fact that whitespace around the `>` classifies it as a comparison operator (greater than), rather than punctuation (angle bracket). I will hack on it a bit.

**Comment by aloucks** [comment]
It's not just strings. I see strange behavior as well with the new grammar. Disabling RA results in correct highlighting. 

Everything after the `_` is broken for many lines. It seems to think that the underscore means the next character should be "disabled".


```rust
let mut normal_image: image::ImageBuffer<image::Rgba<u8>, _> = image::ImageBuffer::from_raw(width, height, normal_buffer_data).unwrap();
```
