### ISSUE TITLE
`extern` functions considered safe even though they are not `"rust-intrinsic"`

### ISSUE THREAD

**Issue by frazar** [rust-analyzer/rust-analyzer#6334]
After PR #6307, *all* functions coming from `extern` blocks are considered safe if their name is found in [this list](https://github.com/frazar/rust-analyzer/blob/aff04d81ba6a334c1ba20ea4e6e04ffc88221aee/crates/hir_def/src/item_tree/lower.rs#L719). However, only functions defined in `extern "rust-instrinsic"` blocks should get this treatment.

Expected outcome:
```Rust
extern "rust-intrinsic" {
    pub fn likely(b: bool) -> bool; // <- Safe to call since it comes from rust-intrinsic
}

extern "foo" {
    pub fn bitreverse(x: u32) -> u32; // <- Unsafe to call as it doesn't come from rust-intrinsic
}

fn main() {
    let _ = likely(true);
    let _ = bitreverse(12);
          //^^^^^^^^^^^^^^ This operation is unsafe and requires an unsafe function or block
}
```

As discussed in the comments to PR #6307, this should be simply a matter of checking the `ABI` node of the extern block.

Possible solution strategy:
1. Solve #6308
2. Add a way to access the name of the `ABI` node
```
SOURCE_FILE@0..395
  EXTERN_BLOCK@0..117
    ABI@0..23
      EXTERN_KW@0..6 "extern"
      WHITESPACE@6..7 " "
      STRING@7..23 "\"rust-intrinsic\""
```
3. Modify [this line](https://github.com/frazar/rust-analyzer/blob/aff04d81ba6a334c1ba20ea4e6e04ffc88221aee/crates/hir_def/src/item_tree/lower.rs#L558) so that functions are marked as safe if they come from an `extern "rust-intrinsic"` blocks AND their name matches [the whitelist](https://github.com/frazar/rust-analyzer/blob/aff04d81ba6a334c1ba20ea4e6e04ffc88221aee/crates/hir_def/src/item_tree/lower.rs#L719)

**Comment by matklad** [comment]
Fixed, see

https://github.com/rust-analyzer/rust-analyzer/blob/eb08a27f1bd31cc15db4893dded60663effaf3f9/crates/hir_def/src/item_tree/lower.rs#L841-L882
