### ISSUE TITLE
Lambdas are rendering weird

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#6340]
The handler parameter should be `|_,_| ()` but it is rendering as `|_,_/ ()` see:

![image](https://user-images.githubusercontent.com/4325700/97054328-9cf90880-1552-11eb-95c6-c1d70c8ec00b.png)

**Comment by aloucks** [comment]
I think it's the underscore that's causing the problem. I now see a similar issue too after the [grammar update](https://github.com/rust-analyzer/rust-analyzer/issues/6323#issuecomment-715637282).

**Comment by dustypomerleau** [comment]
The goal was to give comment scope to ignored params, but it's catching a lot of other cases. I'll have to either scope only word characters or just remove that scope completely.

**Comment by aloucks** [comment]
I don't think comment scope is the right choice in either case.

**Comment by kjeremy** [comment]
Ignored params probably shouldn't have comment scope.

**Comment by cdmistman** [comment]
I'm also seeing this bug in a match pattern (I've only noticed it today)

![image](https://user-images.githubusercontent.com/23486351/97066339-95515800-1582-11eb-8211-68fb64cfbc4c.png)

**Comment by dustypomerleau** [comment]
#6330 will fix, @cdmistman.
