### ISSUE TITLE
IncorrectCase diagnostic thinks lazy_static refs should be camel cased

### ISSUE THREAD

**Issue by ArifRoktim** [rust-analyzer/rust-analyzer#6348]
The following:
```rust
use lazy_static::lazy_static;
lazy_static! {
    static ref HELLO_WORLD: String = "hi!".into();
}
```
produces
```
[rust-analyzer] [H] Structure `HELLO_WORLD` should have CamelCase name, e.g. `HelloWorld`
```

**Comment by ArifRoktim** [comment]
CC @GopherJ

**Comment by bjorn3** [comment]
`lazy_static!` creates a type named the same as the static. It uses `#[allow(non_camel_case_types)]` to suppress the warning for rustc, but rust-analyzer doesn't have support for this.

**Comment by popzxc** [comment]
Is this issue still actual after #6350? I'm unable to reproduce it on the most recent nightly.

**Comment by ArifRoktim** [comment]
I can still reproduce it. Maybe you're unable to reproduce because in something like
```rust
static ref HELLO: String = "hi!".into();
```
the `HELLO` now counts as camel case. Change it to `HELLO_WORLD` and the issue shows itself.

**Comment by popzxc** [comment]
Ah, indeed.
