### ISSUE TITLE
Failed to inference return type of closure.

### ISSUE THREAD

**Issue by 12101111** [rust-analyzer/rust-analyzer#6352]
The code is https://github.com/rust-lang/rust/blob/master/src/bootstrap/config.rs#L560

![image](https://user-images.githubusercontent.com/8438475/97102688-94373c80-16e2-11eb-8ebb-187e9e915c2e.png)

The type of closure `get_toml`, `toml` and `included_toml` is inferenced to `()`, but it should be `TomlConfig`.

Even with a type annotation, the return type of `get_toml` is still `()`
![image](https://user-images.githubusercontent.com/8438475/97102751-0c056700-16e3-11eb-936e-b00e38ce9e93.png)

**Comment by flodiebold** [comment]
What happens if you move the local `use std::process` outside of the function?

**Comment by 12101111** [comment]
use `std::process` outside of the function:
![image](https://user-images.githubusercontent.com/8438475/97104088-08c2a900-16ec-11eb-9428-a3d892cf8a46.png)
use `std::process:exit`:
![image](https://user-images.githubusercontent.com/8438475/97104095-1bd57900-16ec-11eb-9084-239d06fc46f0.png)

**Comment by flodiebold** [comment]
So this is just a case of #1165; because the `process::exit` call isn't resolved when you're using a local import, we don't know that the error case diverges, so it gets typed as `()`, and since the type of `table` can be anything at that point, it'll get unified to `()` as well.
