### ISSUE TITLE
"Run Doctest" lens only available for functions

### ISSUE THREAD

**Issue by Woyten** [rust-analyzer/rust-analyzer#6356]
Sometimes it makes sense to write a doctest for a [struct](https://docs.rs/tune/0.18.0/src/tune/ratio.rs.html#10-43) or [trait impl](https://docs.rs/tune/0.18.0/src/tune/tuning.rs.html#18-31).

Unfortunately, for those positions no "Run Doctest" lens is shown. It would be great it was available for any possible doctest position! :smiley:

**Comment by bnjjj** [comment]
Will check to enable this for struct and impl

**Comment by matklad** [comment]
Minimal example:

```rust
trait T {}

/// ```
/// assert_eq!(2 + 2, 4)
/// ```
impl () for T  {
}
```

**Comment by bnjjj** [comment]
I'm on it :)
