### ISSUE TITLE
Weird highlighted closing brackets and parens

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#6364]
I'm seeing some highlighted closing brackets and parenthesis and I don't know why they're highlighted. They look like errors in my editor and they are not. It also doesn't happen consistently.

For instance:

[this is red](https://github.com/rust-analyzer/rust-analyzer/blob/bf84e4958ee31c59e5b78f60059d69a73ef659bb/crates/rust-analyzer/src/main_loop.rs#L613)

![image](https://user-images.githubusercontent.com/4325700/97184788-add59400-1775-11eb-9aee-78c6898dbb79.png)

![image](https://user-images.githubusercontent.com/4325700/97184508-5fc09080-1775-11eb-831f-f5717af4cbfa.png)

**Comment by dustypomerleau** [comment]
I can't reproduce with that particular file (with or without semantic highlighting). I get red with `semantic token type` of `unresolvedReference`, but never for punctuation. Does it show a corresponding error in the Problems tab?

**Comment by kjeremy** [comment]
It does not. I'll try a different theme tomorrow and see if it's theme
related.

**Comment by kjeremy** [comment]
This seems to have disappeared for now.
