### ISSUE TITLE
Wrong parameter hint when using `std::cmp::max` and `std::fs::rename` together

### ISSUE THREAD

**Issue by oxalica** [rust-analyzer/rust-analyzer#6373]
Here's a minimal reproduction on vscode 1.50.1 with rust-analyzer 2020-10-26.
When toggling comment for `std::cmp::max`, we need to **close and reopen the file** to see the hint change.
```rust
fn main() {
    std::cmp::max(1, 2); // comment this line to fix
    let (v1, to) = ("bar", "bar");
    std::fs::rename("foo", "bar")?;
    std::fs::rename("foo", to)?;
    std::fs::rename("foo", v1)?;
}
```

Wrong hint: (the second parameter of `rename` is `to`, not `v1`)
<img width="317" alt="image" src="https://user-images.githubusercontent.com/14816024/97195971-e1043b80-17e6-11eb-9587-28da994f0f63.png">

Corrent hint:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/14816024/97195995-e82b4980-17e6-11eb-973d-6a616d449394.png">

Note that the hint is off when the argument itself is `to` instead of `v1` in wrong case. Maybe a bug on extension side?

**Comment by Veykril** [comment]
Interesting, I cannot seem to reproduce via test cases in `inlay_hints`. A snippet that doesn't rely on std that causes this issue: 
```rs
pub fn foo(v1: usize, v2: usize) {}
pub fn bar(to: &str) {}

fn main() {
    foo(1, 2); // comment this line to fix
    let (v1, to) = ("bar", "bar");
    bar("bar");
    bar(to);
    bar(v1);
}
```
![image](https://user-images.githubusercontent.com/3757771/97231867-7fd76a80-17dc-11eb-97a2-ce958d07f8d7.png)

**Comment by Veykril** [comment]
Took a look at this and I believe this might be a vscode decorations bug as the decorations contain the correct strings.

I dumped the inlayhint data before and after they were turned into decorations and the strings for them are correct:

<details>
    <summary>Spoiler warning</summary>

    // InlayHints directly from the language server
    [
    {
        kind: 'ParameterHint',
        label: 'v1',
        range: {
        end: { character: 9, line: 4 },
        start: { character: 8, line: 4 }
        }
    },
    {
        kind: 'ParameterHint',
        label: 'v2',
        range: {
        end: { character: 12, line: 4 },
        start: { character: 11, line: 4 }
        }
    },
    {
        kind: 'TypeHint',
        label: '&str',
        range: {
        end: { character: 11, line: 5 },
        start: { character: 9, line: 5 }
        }
    },
    {
        kind: 'TypeHint',
        label: '&str',
        range: {
        end: { character: 15, line: 5 },
        start: { character: 13, line: 5 }
        }
    },
    {
        kind: 'ParameterHint',
        label: 'to',
        range: {
        end: { character: 13, line: 6 },
        start: { character: 8, line: 6 }
        }
    },
    {
        kind: 'ParameterHint',
        label: 'to',
        range: {
        end: { character: 10, line: 8 },
        start: { character: 8, line: 8 }
        }
    }
    ]
    // InlaysDecorations, which are directly sent through the vscode api
    {
    type: [
        {
        range: b {
            _start: _ { _line: 5, _character: 9 },
            _end: _ { _line: 5, _character: 11 }
        },
        renderOptions: { after: { contentText: '‌: &str' } }
        },
        {
        range: b {
            _start: _ { _line: 5, _character: 13 },
            _end: _ { _line: 5, _character: 15 }
        },
        renderOptions: { after: { contentText: '‌: &str' } }
        }
    ],
    param: [
        {
        range: b {
            _start: _ { _line: 4, _character: 8 },
            _end: _ { _line: 4, _character: 9 }
        },
        renderOptions: { before: { contentText: 'v1: ' } }
        },
        {
        range: b {
            _start: _ { _line: 4, _character: 11 },
            _end: _ { _line: 4, _character: 12 }
        },
        renderOptions: { before: { contentText: 'v2: ' } }
        },
        {
        range: b {
            _start: _ { _line: 6, _character: 8 },
            _end: _ { _line: 6, _character: 13 }
        },
        renderOptions: { before: { contentText: 'to: ' } } // as you can see, this is the correct string here with the correct range
        },
        {
        range: b {
            _start: _ { _line: 8, _character: 8 },
            _end: _ { _line: 8, _character: 10 }
        },
        renderOptions: { before: { contentText: 'to: ' } } // as you can see, this is the correct string here with the correct range
        }
    ],
    chaining: []
    }
</details>

**Comment by flodiebold** [comment]
I guess this requires a minimal reproduction in VSCode and then a VSCode bug report then.

**Comment by bjorn3** [comment]
triage: The reproducer in the issue description is still producing this bug.

**Comment by Veykril** [comment]
This is no longer happening now that we switched to native hints.
