### ISSUE TITLE
Semantic Highlighting: impl Iterator is considered callable

### ISSUE THREAD

**Issue by CryZe** [rust-analyzer/rust-analyzer#6375]
The newly introduced callable modifier (which I've used to mark variables the same color as functions) is for some reason being applied to impl Iterator here:

![https://i.imgur.com/MBzbqGK.png](https://i.imgur.com/MBzbqGK.png)

**Comment by lnicola** [comment]
CC @GrayJack

**Comment by GrayJack** [comment]
Hey @CryZe , can you give a code that this happens or point me to a code base where it happens?

**Comment by bjorn3** [comment]
The `Callable` modifier comes from https://github.com/rust-analyzer/rust-analyzer/blob/35ed3d2c005fdb0ec9ab78a52b31758bd7de298e/crates/ide/src/syntax_highlighting.rs#L773-L775

**Comment by bjorn3** [comment]
I think what happens is because of the `+ {error}` the question if it implements `FnOnce` results in an ambiguous solution. This will then cause `impls_fnonce` to return true, as `solution.is_some()` is true.

**Comment by CryZe** [comment]
This replicates the issue:
```rust
fn look_up<'txt>(word: &'txt str) -> Option<impl Iterator<Item = char> + Clone + 'txt> {
    Some(word.chars())
}

fn foo() {
    if let Some(bar) = look_up("hi") {}
}
```

**Comment by CryZe** [comment]
It also seems to replicate with:
```rust
fn look_up(word: &str) -> Option<impl Iterator<Item = char>> {
    Some("".chars())
}

fn foo() {
    if let Some(bar) = look_up("hi") {}
}
```
which doesn't have the `+ {error}` which apparently correlates with the lifetime.

**Comment by GrayJack** [comment]
@bjorn3 If inside `method_resolution::implements_trait` the function returns false when solution is `Solution::Ambig`, would solve the problem right?

I think a more appropriate question would be:
Is it best to change `method_resolution::implements_trait` implementation or create a new function that only returns true when the solution is `Solution::Unique`?

**Comment by flodiebold** [comment]
It's worth investigating why `impl Clone: Fn` would return ambiguous though :thinking:
