### ISSUE TITLE
Diagnose files that aren't in the crate hierarchy

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#6377]
As of recently, we diagnose `mod m;` with a `#[cfg]` that is currently inactive. We do not emit a diagnostic for the contents of `m.rs` though, which can be pretty confusing, since it just shows up as "IDE is not working" while editing m.rs.

**Comment by flodiebold** [comment]
It'd also be really great to have a big warning when editing a file that isn't in the module tree at all.

**Comment by Kimundi** [comment]
According to the Rust discord, warnign about this is also apparently a feature in jetbrains. Would also address issues like this: https://github.com/rust-analyzer/rust-analyzer/issues/7345

**Comment by JDuchniewicz** [comment]
Can we force rust-analyzer to include the file in the tree?

**Comment by jonas-schievink** [comment]
I'm planning to add a quickfix that treats files like this as standalone crates instead. Blindly injecting them into the module hierarchy doesn't seem like the best idea.

**Comment by JDuchniewicz** [comment]
This is probably the best idea, most of the time when you are writing a standalone file, you only need standard completion and features. Unless other people have different experiences.

**Comment by jonas-schievink** [comment]
> I'm planning to add a quickfix that treats files like this as standalone crates instead.

I added a quickfix that adds the appropriate `mod name;` item instead
