### ISSUE TITLE
Inlay hints acquire font styling from the character that follows them

### ISSUE THREAD

**Issue by dfoxfranke** [rust-analyzer/rust-analyzer#6380]
I have VSCode theme that puts operators in bold. A closure in my code written as `|chunk|` has an inferred argument type of `Result<Bytes, Error>`, rendered in my editor as an inlay hint. Correct behavior would be to render the **`|`**'s in bold but not anything in between them. Instead, I get a (correctly) regularly-styled `chunk` but a  bold **`: Result<Bytes, Error>|`** following it.

The type renders correctly (i.e. not in bold) if I write it out explicitly rather than having it filled in as an inlay hint. So this seems to be an issue particular to inlays, and not a problem with any of the patterns in `rust.tmGrammar.json`.

**Comment by bjorn3** [comment]
This is a limitation of the lsp/vscode Inlay hints can only be attaches before or after a character, not in between two characters.

**Comment by lnicola** [comment]
@dfoxfranke does #6382 do anything for you?

**Comment by dfoxfranke** [comment]
@lnicola Confirmed, this fixes it for me. You probably also want `textDecoration: "none"`, to remove underlines.

**Comment by kjeremy** [comment]
@dfoxfranke what theme are you using? I'd like to be able to reproduce this to make sure that #6394 didn't regress.

**Comment by dfoxfranke** [comment]
@kjeremy It's a theme I'm developing and it's not released yet, but it will be soon, probably this weekend; after then look for "Lunaria" on the extension marketplace. By the looks of the diff, it won't regress on my theme (which puts operators in bold) but will regress on any theme that underlines operator (I don't know of any that do this).

Regardless, I have to say I really dislike this change. I designed the theme I'm working on specifically with rust-analyzer inlay hints in mind, and it arranges colors in such a way that the inlay hints are already readable and clearly distinct from the surrounding text. Varying the font size will make them less legible and distracting, and if you're going to do this I wish you'd provide a toggle for it.

**Comment by kjeremy** [comment]
Thanks for the response.

Please file an issue if you want the size change to be customizable so we
don't lose track of it.
