### ISSUE TITLE
`cfg` highlighting is inconsistent

### ISSUE THREAD

**Issue by schungx** [rust-analyzer/rust-analyzer#6381]
The newest version has `cfg` highlighting, essentially graying out the code shielded by an inactive feature gate.

This is a great feature, except that I find it inconsistent.

First I'd load a file, and it would color fine.  Then I'll switch to another file, and it won't color at all.  Then I switch back to the original file, and it'll lose the coloring.

Sometimes it'll suddenly come back after a while, sometimes it won't.

Usually when I restart Visual Studio Code, it'll work fine the first time.  Then not afterwards.

**Comment by schungx** [comment]
I did some more experiments and it seems to work for any document window already open when I start VS Code.  Any window I open afterwards, or closing the original one and reopening, will cause it not to color.

**Comment by jonas-schievink** [comment]
This is a general problem with diagnostics. I'm not sure why it happens though, it might be a VS Code bug.

**Comment by jonas-schievink** [comment]
Found the issue, and opened a PR that should fix it in https://github.com/rust-analyzer/rust-analyzer/pull/6637
