### ISSUE TITLE
Static variable should have UPPER_SNAKE_CASE name

### ISSUE THREAD

**Issue by iulianR** [rust-analyzer/rust-analyzer#6386]
Hello, I get the following error with every uppercase static variable with the version released on 2020-10-26:

```Static variable `TEST` should have UPPER_SNAKE_CASE name, e.g. `T_E_S_T` rust-analyzer```
![image](https://user-images.githubusercontent.com/6775259/97315268-3553fd80-1871-11eb-8f80-258b8bb12528.png)

**Comment by bjorn3** [comment]
This should have been fixed by #6350, which was merged after version 2020-10-26 had been released.

**Comment by iulianR** [comment]
I double checked the version in a new project, after `Rust Analyzer: Restart Server` in VSCode.
![image](https://user-images.githubusercontent.com/6775259/97318544-a6e17b00-1874-11eb-8d6f-aa720a5c0039.png)

**Comment by lnicola** [comment]
It will be available in the next release (or you could switch to the nightly versions).

**Comment by iulianR** [comment]
Seems OK with nightly. Good to know it's fixed. Thanks!
