### ISSUE TITLE
Renaming `test` function named `test` renames macro `test`

### ISSUE THREAD

**Issue by sanbox-irl** [rust-analyzer/rust-analyzer#6389]
start with:

```
#[cfg(test)]
mod tests {
   #[test]
   fn test() {}
}
```
hit F2 or Rename on the `test` after `fn` (so, line 3 there, not the proc macro i'm saying), and rename it to anything, such as, `wow_test`, and end up with:

```
#[cfg(test)]
mod tests {
   #[wow_test]
   fn wow_test() {}
}
```

pretty funky! testing on Windows 10, most recent version, VSCode

**Comment by sanbox-irl** [comment]
ONLY happens when the fn is named `test` just to be clear -- doesn't happen otherwise

**Comment by Veykril** [comment]
Looks like it in general renames attributes that share the same name as the function.
```rust
#[foo]
fn foo() {}
```
becomes
```rust
#[bar]
fn bar() {}
```
on rename with `bar` for `foo`.
