### ISSUE TITLE
Code completion not working in Neovim

### ISSUE THREAD

**Issue by AdaShoelace** [rust-analyzer/rust-analyzer#6395]
Since the latest update of rust code completion using rust-analyzer has stopped working in both Neovim and vscode.
This holds true for both rust nightly and stable.

Completion for my own code and extern crates works but not for std.

in init.vim:
```
let g:LanguageClient_autoStart = 1
let g:LanguageClient_serverCommands = {
			\ 'rust': ['rust-analyzer'],
			\ 'dart': ['dart_language_server'],
			\ 'python': ['/usr/bin/pyls'],
			\ 'cpp': ['clangd'],
			\ 'c': ['clangd'],
			\ 'crystal': ['/home/user/Programming/crystal/scry'],
			\}
```
Print out from `pacman -Q rust-analyzer-git`: `rust-analyzer-git 1:0.0.0.13202.g85cda15b6-1`
RUST_SRC_PATH: `/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu`

I've also tried to extend the RUST_SRC_PATH with `/lib/rustlib/src` to no avail...

If the problem is my config feel free to tell me and perhaps help me in the right direction because I don't know how to fix it.

**Comment by flodiebold** [comment]
Are you getting an error message saying something like "could not find libcore in sysroot path"? Not sure where it would show up in Neovim, but in VSCode it should be hard to miss.

I think both `RUST_SRC_PATH` values you tried are wrong; you'd need to extend it with `lib/rustlib/src/rust/library`, but you shouldn't need `RUST_SRC_PATH` at all if rust-analyzer can run `rustc` to find it. Try unsetting it completely.

**Comment by AdaShoelace** [comment]
> Are you getting an error message saying something like "could not find libcore in sysroot path"? Not sure where it would show up in Neovim, but in VSCode it should be hard to miss.
> 
> I think both `RUST_SRC_PATH` values you tried are wrong; you'd need to extend it with `lib/rustlib/src/rust/library`, but you shouldn't need `RUST_SRC_PATH` at all if rust-analyzer can run `rustc` to find it. Try unsetting it completely.

I checked VScode again and it prompted me to update the rust-analyzer extension which fixed the problem there. Neovim still doesn't work though.

I also tried to both include `lib/rustlib/src/rust/library` in `RUST_SRC_PATH` and to unset it for both nightly and stable, neither worked.

**Comment by AdaShoelace** [comment]
Now Neovim gives me this error: 
```
Error:analyzer: rust-analyzer failed to load workspace: Failed to find sysroot for Cargo.toml file /home/ada/Programming/rust/hobby/lox/Cargo.toml. Is rust-src installed?: can't load standard library from sysroot

/home/ada/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
(discovered via `rustc --print sysroot`)
try running `rustup component add rust-src` or set `RUST_SRC_PATH`
```

**Comment by flodiebold** [comment]
This is confusing. What does `rustc --print sysroot` print? Also, running rust-analyzer with `RA_LOG=project_model=debug` could help if you can see the logs in Neovim.

**Comment by AdaShoelace** [comment]
> This is confusing. What does `rustc --print sysroot` print? Also, running rust-analyzer with `RA_LOG=project_model=debug` could help if you can see the logs in Neovim.

`rustc --print sysroot` prints: `/home/ada/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu`
How do I run rust-analyzer with `RA_LOG=project_model=debug`?

**Comment by flodiebold** [comment]
> rustc --print sysroot prints: /home/ada/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu

Then it's very confusing that we're looking in `/home/ada/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src` :thinking: Did you run the command in the project directory?

> How do I run rust-analyzer with RA_LOG=project_model=debug?

That depends on the editor, so I can't tell you how to do it with Neovim (or even VSCode) :grimacing:

**Comment by lnicola** [comment]
Is it possible that you have an older `rust-analyzer` in `~/.cargo/bin`?

**Comment by flodiebold** [comment]
Oh yeah, this log message is actually only explainable with an old rust-analyzer.

**Comment by AdaShoelace** [comment]
I can't see any other installation. However, after uninstalling `rust-analyzer-git` using pacman vscode still has completion and neovim is unchanged o.O

**Comment by lnicola** [comment]
Code can use a bundled LSP binary. Does `which rust-analyzer` print anything?

**Comment by AdaShoelace** [comment]
Yes it did! And once I removed it and installed the latest version everything worked!
Thanks for all the help even though this wasn't a bug.

**Comment by lnicola** [comment]
I wonder if we can do anything to make debugging these easier. Print out the server path in the logs? But those will probably be hard to read in other editors, and it's less of a problem in Code.
