### ISSUE TITLE
RustAnalayzer mistakenly gives error on a.max(b)

### ISSUE THREAD

**Issue by Ten0** [rust-analyzer/rust-analyzer#6409]
It seems to beleive `max` in `a.max(b)` is about [`Iterator::max`](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.max), whereas it's about [`Ord::max`](https://doc.rust-lang.org/stable/std/cmp/trait.Ord.html#method.max), and as a consequence gives the error: `expected 0 arguments, found 1` (and also when hovering with the mouse, doc points to `core::iter::traits::iterator::Iterator`). Using std::cmp::max(a, b) makes the error disappear.

Note that the feature that writes inferred types in light gray mentions `&{unknown}` instead of `&Something` (despite the type I'm iterating on being explicitly `Vec<Something>`), I suspect that is linked.

**Comment by Veykril** [comment]
It would be helpful to see a more complete snippet. Are you using any local imports(as in `use` statements that are inside of functions or expressions)? Because those are currently being ignored by RA which could lead to this problem.

**Comment by Ten0** [comment]
> Are you using any local imports(as in `use` statements that are inside of functions or expressions)?

I'm not using `use` statements inside the function, however the `Something` I'm iterating on is declared in the function, just above, as it's a local structure used only to deserialize the result of a specific database query made there. Could that also be it?

> Because those are currently being ignored by RA which could lead to this problem.

Why is that? :o

**Comment by Ten0** [comment]
> Why is that? :o

Nvm, I found the answer.

https://github.com/rust-analyzer/rust-analyzer/issues/1165#issuecomment-696560892

Looks like this issue is the long-standing-much-duplicated #1165 / #1559.

**Comment by Ten0** [comment]
Hmmm that being said, it looks like we could still improve the method inference when the type is `{unknown}`, by at least picking functions that have the proper number arguments/the right return type.

**Comment by flodiebold** [comment]
I don't know about that, but we should avoid giving follow-up errors when we have unknown types.

**Comment by flodiebold** [comment]
Closing in favour of #6975.
