### ISSUE TITLE
Incorrect unresolved import of external crate Type Definitions

### ISSUE THREAD

**Issue by IsaacTru** [rust-analyzer/rust-analyzer#6410]
When importing a Type Definition from an external crate, RA produces the unresolved import problem even though rustc is able to compile the code just fine. Rust Analyzer v0.2.360

Cargo.toml:
```
[package]
name = "ra_mwe"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typenum = "1.12"
```

main.rs:
```rust
use typenum::P2;

fn main() {
    let power = P2::new();
    let pow = typenum::P2::new();
}
```

**Comment by flodiebold** [comment]
Those constants are generated by a build script, so you'll need to turn on `loadOutDirsFromCheck`.

**Comment by IsaacTru** [comment]
Thanks for the suggestion. I am currently using VSCode 1.50.1 for Linux and had that setting checked in my User profile:
![image](https://user-images.githubusercontent.com/37151395/97711271-1f655900-1a7a-11eb-9373-8f248c55755c.png)
but _not_ in the Workspace profile. When I checked it in the Workspace all was fixed! Closing issue.

**Comment by IsaacTru** [comment]
Apparently I am mistaken. The problem reappeared a few minutes later, after RA had finished running `cargo check`. I now have the settings checked in both the User and Workspace profile.

**Comment by IsaacTru** [comment]
I can see the generated files by typenum in the target directory in a mod called `consts`. Importing `typenum::consts::P1` does not work either.
I'm also noticing that `cargo check` runs after RA has finished indexing all the crates (per the taskbar at the bottom of VSCode), could this be causing the `OUT_DIR`s value to be incorrectly set when RA attempts to index?

**Comment by Veykril** [comment]
Can't reproduce this on current nightly so I believe this has been solved.
