### ISSUE TITLE
Bad code highlighting

### ISSUE THREAD

**Issue by c410-f3r** [rust-analyzer/rust-analyzer#6419]
```rust
fn stuff() {
    let foo = vec![1, 2];
    #[
        // Won't do much
        allow(clippy::indexing_slicing)
    ]
    let _ = foo[0];
}

struct MoreStuff {
    a: i32,
    b: i32,
    c: i32
}
```

The `'` of `Won't` messes with sub-sequence code highlight. Funny enough, the same behavior doesn't happen when the comment is outside of the macro scope.

**Comment by dustypomerleau** [comment]
Comments should be allowed in attributes. I will push a fix.

**Comment by c410-f3r** [comment]
@dustypomerleau Thanks!
