### ISSUE TITLE
VSCode mishighlights format!("{:x?}", a)

### ISSUE THREAD

**Issue by lf-** [rust-analyzer/rust-analyzer#6427]
![image](https://user-images.githubusercontent.com/6652840/97796114-66af2f00-1bcb-11eb-8658-9b450b5742db.png)

This is probably related to the aging grammar being used for highlighting, but I've seen that there's been work on putting a better grammar into the rust-analyzer extension, so I think this belongs here?

rust-analyzer version: 2020-10-26 (eae54b5); VSCode extension 0.2.360; VSCode 1.50.1

**Comment by dustypomerleau** [comment]
Hi @lf-,

Could you clarify:

1. Is this happening with Rust Analyzer enabled, or with the built-in VS Code grammar?
2. Is semantic highlighting enabled or disabled?
3. Could you post a larger code snippet, rather than a screenshot?

**Comment by lf-** [comment]
Sorry about the tiny screenshot! It was in semi-closed code so I was uncomfortable revealing much code, but I have reproduced it in the below snippet:

```rust
#[derive(Debug)]
struct Thingy(u8);

fn main() {
    let thingy = Thingy(17);
    let mut n2 = 0;
    n2 += 1;
    println!("{:x?} {} ", thingy, n2);
}
```

Here's a screenshot of it happening in this smol snippet:

![image](https://user-images.githubusercontent.com/6652840/97851993-fe377f00-1caa-11eb-8738-d2e6a6e6a42a.png)

1. I *think* I have the rust analyzer grammar since rust analyzer is doing its magic.

2. Semantic highlighting is enabled, if that's what makes mut variable uses get underlined.

3. :)

**Comment by CryZe** [comment]
Seems to reproduce for me:
![https://i.imgur.com/m0FPgdb.png](https://i.imgur.com/m0FPgdb.png)
