### ISSUE TITLE
Custom derive unresolvable!

### ISSUE THREAD

**Issue by junknet** [rust-analyzer/rust-analyzer#6429]
This is a project I'm learning about .[url](https://github.com/ajeetdsouza/zoxide)
![1](https://user-images.githubusercontent.com/55597646/97798262-711b0880-1c5f-11eb-9ed1-5ea1f2efbd38.png)
parse() function cannot be parsed by rust-analyzer,but rls can parse it.
I don't kown why.

**Comment by bjorn3** [comment]
You can enable proc-macro support using

```jsonc
{
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
}
```

**Comment by junknet** [comment]
Wow. Thank you very much

**Comment by junknet** [comment]
![2](https://user-images.githubusercontent.com/55597646/97802377-dd0c6980-1c7d-11eb-8c4b-82c11b3baa5e.png)
Well, the problem doesn't seem to have been solved completely
