### ISSUE TITLE
How to remove RA's underline diagnostics

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#6444]
![image](https://user-images.githubusercontent.com/33961674/97900716-5d44d480-1d3b-11eb-9725-cf6b8e0c5c49.png)

It's hard to know what's really happening while RA makes all lines emphasized... Is there a configuration for this? Or it's coc.nvim/coc-rust-analyzer's issue?

**Comment by jonas-schievink** [comment]
The issue in coc is that it highlights diagnostics marked as "Unnecessary". VS Code just makes the text gray instead of underlining everything.

You can disable the `inactive-code` diagnostic by setting `"rust-analyzer.diagnostics.disabled": ["inactive-code"]`.

**Comment by GopherJ** [comment]
@jonas-schievink awesome it worked! Thanks!

**Comment by lit0ne** [comment]
Hi, where should I put these setting please ?

**Comment by 0x501D** [comment]
> Hi, where should I put these setting please ?

It depends on the IDE.
For example, in my bundle vim + coc + rust-analyzer I wrote a parameter to the file:

```sh
$ grep inactive ~/.vim/coc-settings.json
  "rust-analyzer.diagnostics.disabled": ["inactive-code"],
```
