### ISSUE TITLE
Wrong textmate scopes on functions/methods with turbofish

### ISSUE THREAD

**Issue by aloucks** [rust-analyzer/rust-analyzer#6446]
It's missing `meta.function.call.rust` and `entity.name.function.rust`. 

![image](https://user-images.githubusercontent.com/221559/97938168-b5d19d00-1d4e-11eb-8be1-1c94ee1b64da.png)

**Comment by dustypomerleau** [comment]
Thanks @aloucks. I'll need to define a special case for this.
