### ISSUE TITLE
Incorrect "unresolved import" in std

### ISSUE THREAD

**Issue by hghwng** [rust-analyzer/rust-analyzer#6449]
To reproduce the bug, just enter the following code under Linux:

```rust
use std::os::unix::io::AsRawFd;
fn main() {}
```

 RA emits the error of "unresolved import". Since the block is conditionally compiled with `cfg_if` (see [the source of std]), I suspect that the guard is not handled correctly.

[the source of std]: https://github.com/rust-lang/rust/blob/d662f808550acadc5980969e1826a653ec35b408/library/std/src/os/mod.rs#L6

Enabling `loadOutDirsFromCheck` and `procMacro` does not solve the problem.

**Comment by bjorn3** [comment]
Duplicate of #6038
