### ISSUE TITLE
Document semantic highlighting

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#6457]
I would imagine it to be a nice addition to the [manual](https://rust-analyzer.github.io/manual.html) being able to check what semantic tokens RA emits, possibly with a small description to what each token and modifier roughly applies to?

**Comment by matklad** [comment]
Uhu. The question is, how do we make sure that the docs don't diverge from code? My prefernece, as usual, would be for some kind of code-gen/doctest based solution,but I might be overthinking this.

**Comment by matklad** [comment]
Should be docced here: https://github.com/rust-analyzer/rust-analyzer/blob/6cd669e8809d9e19b2169d04b99f33258848b814/crates/ide/src/syntax_highlighting.rs#L42-L54
