### ISSUE TITLE
Add "Open Cargo.toml" action

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#6462]
Invoking it should open Cargo.toml for the current file. 

This should be implemented at the `rust-analyzer` layer (ie, not in the IDE layer). 

This needs custom protocol extension. 

See https://github.com/rust-analyzer/rust-analyzer/commit/c9f878962a7c9d1c33d5834a1dce2106c9286699#diff-4bec6bfceb4323ffd0d2ff1ad25070234f084f31ddd5577bbdb510de878a3811 for an example which adds custom extension

**Comment by p3achyjr** [comment]
I can take this up if no one else is working on it. This would open the Cargo.toml of the current crate, right?

**Comment by lnicola** [comment]
Yes, but there might be some corner cases:

 - the project is not Cargo-based
 - the file is generated by a build script
 - the file is included in multiple crates

**Comment by matklad** [comment]
>This would open the Cargo.toml of the current crate, right?

Right! i suggest looking at `handle_runnables` for the logic of discovering the current crate/package

**Comment by p3achyjr** [comment]
Thanks @matklad, @lnicola. This might not be the right place to ask this, but how can I actually go about testing this? It seems like this would involves changes to both client + server, and looking at ./docs/dev.md, it just says that there is no specific workflow for this case.

**Comment by matklad** [comment]
We just don't such features -- there's relatively few bugs on the interesection between client and server, and conventinal testing is not too efficient here.

**Comment by p3achyjr** [comment]
ah, got it 👍. What about manually verifying it works? Like installing a dev build and running that in vscode?

**Comment by lnicola** [comment]
@p3achyjr you can uninstall the store extension, run `cargo xtask install` in a clone of the repository, and maybe update `rust-analyzer.serverPath` to point to the executable in `~/cargo/bin`.
