### ISSUE TITLE
When loading VS Code extension, show a warning if rust-lang.rust is also installed

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#6463]

**Comment by matklad** [comment]
See https://github.com/rust-analyzer/rust-analyzer/issues/6461

**Comment by lnicola** [comment]
Detecting installed extensions might be possible using https://code.visualstudio.com/api/references/vscode-api#extensions (it might be worth checking that the current extension is matklad.rust-analyzer, though). We could display a message suggesting the user to uninstall one of them.

**Comment by xFrednet** [comment]
Hey I was looking at this issue to figure out how difficult it would be to implement it. (For me as new comer).

I'm pretty sure that the suggested solution by @lnicola would work but it would be vscode specific from what I can see. Is there maybe a way to implement it with the pure [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/)? (I couldn't find one). If it's not possible would it be worth to suggest such a feature for the LSP specification in addition to implementing it with the vs code specific way?

**Comment by lnicola** [comment]
Both extensions mentioned here are Code-specific (unless you count coc.nvim, but that kind express the Code API and a fork of this extension), and there's no idea of an extension in LSP -- why would there be?

There are LSP clients that don't support extensions, and for those that do, there's no extension to be in conflict with.

**Comment by xFrednet** [comment]
Okay, it seems like I've misunderstood a part of the LSP. Thank you very much for clarifying!

**Comment by extremegf** [comment]
I've create a pull requests that adds this warning. I kindly requets comments.

This is my first pull request for RA, so forgive me if I missed something.

![Screenshot from 2020-12-18 18-33-02](https://user-images.githubusercontent.com/1788593/102644346-f0599280-4160-11eb-896c-7c550c403e70.png)
