### ISSUE TITLE
Warn if rust-lang.rust is installed

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#6464]
The two extensions often conflict with each other (#6461 is a recent example) and it doesn't make sense to run both.

Detecting installed extensions might be possible using https://code.visualstudio.com/api/references/vscode-api#extensions (it might be worth checking that the current extension is `matklad.rust-analyzer`, though). We could display a message suggesting the user to uninstall one of them.

**Comment by lnicola** [comment]
Closing in favor of #6463

**Comment by matklad** [comment]
Rust protects from data races they said....

**Comment by lnicola** [comment]
But not from race conditions!
