### ISSUE TITLE
Smarter logging of semanticTokens messages

### ISSUE THREAD

**Issue by Timmmm** [rust-analyzer/rust-analyzer#6469]
Bug #6402 happened for me again, and I have verbose logging enabled, but unfortunately it is pretty impossible to read because of messages like this:

```
[Trace - 3:45:47 PM] Received response 'textDocument/semanticTokens/full/delta - (15638)' in 34ms.
Result: {
    "data": [
        0,
        0,
        3,
        1,
... Followed by 100k lines of data ...
```

I doubt anyone is going to read that - you might want a custom `Debug` impl. I folded a few of those away and the next biggest causer of spam is progress messages (I got about 1500 of them in just a few seconds).

```
[Trace - 3:45:47 PM] Received notification '$/progress'.
Params: {
    "token": "rustAnalyzer/indexing",
    "value": {
        "kind": "report",
        "message": "47/770 (term)",
        "percentage": 6.103896103896104
    }
}
```

**Comment by lnicola** [comment]
Those are printed by Code, not `rust-analyzer`. As a workaround, you can disable semantic highlighting (or post-process the trace).

**Comment by Timmmm** [comment]
Oh ok, never mind then!
