### ISSUE TITLE
Unresolved import for a re-exported macro

### ISSUE THREAD

**Issue by hulloitskai** [rust-analyzer/rust-analyzer#6478]
Hi, `rust-analyzer` appears to be giving me `unresolved import` when importing `tokio::main`:

```rust
use anyhow::Result;
use tokio::main as wrapper; // unresolved import

#[wrapper]
async fn main() → Result<()> {
  // ...
}
```

> I do know that directly using `#[tokio::main]` instead of `use`-aliasing it will avoid the complaints from `rust-analyzer`; however, I believe this error points to a deeper issue with specific imports that should be addressed.

However, the code compiles properly. Upon closer inspection of the source containing the `tokio::main` macro, I see that it is embedded with several layers of macros to handle `cfg` (to only export the macro when certain `tokio` features are enabled):

```rust
cfg_macros! {
    /// Implementation detail of the `select!` macro. This macro is **not**
    /// intended to be used as part of the public API and is permitted to
    /// change.
    #[doc(hidden)]
    pub use tokio_macros::select_priv_declare_output_enum;

    cfg_rt! {
        cfg_rt_multi_thread! {
            // This is the docs.rs case (with all features) so make sure macros
            // is included in doc(cfg).

            #[cfg(not(test))] // Work around for rust-lang/rust#62127
            #[cfg_attr(docsrs, doc(cfg(feature = "macros")))]
            pub use tokio_macros::main;

            #[cfg_attr(docsrs, doc(cfg(feature = "macros")))]
            pub use tokio_macros::test;
        }

        cfg_not_rt_multi_thread! {
            #[cfg(not(test))] // Work around for rust-lang/rust#62127
            pub use tokio_macros::main_rt as main;
            pub use tokio_macros::test_rt as test;
        }
    }

    // Always fail if rt is not enabled.
    cfg_not_rt! {
        #[cfg(not(test))]
        pub use tokio_macros::main_fail as main;
        pub use tokio_macros::test_fail as test;
    }
}
```
Perhaps it is the expansion of these macros, or the `#[cfg(not(test))]`, that is tripping up `rust-analyzer`?

**Comment by ArifRoktim** [comment]
Does adding
```json
    "rust-analyzer.procMacro.enable": true,
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
```
to your configuration fix the issue? Proc Macro support is disabled by default.

**Comment by stevenxie** [comment]
I already had those options enabled when I reported this issue. But good call, should have included that info in the report!

**Comment by jonas-schievink** [comment]
> Perhaps it is the expansion of these macros, or the `#[cfg(not(test))]`, that is tripping up `rust-analyzer`?

It is the `#[cfg(not(test))]`. rust-analyzer always enables the `test` cfg.

However it seems that the Rust issue this is working around, https://github.com/rust-lang/rust/issues/62127, has been fixed, so the workaround in tokio can probably be removed now.

**Comment by jonas-schievink** [comment]
Ah nevermind it was closed as wontfix.

**Comment by Veykril** [comment]
This can be worked around by adding `tokio-macros` to the `rust-analyzer.cargo.unsetTest` setting now.
