### ISSUE TITLE
Constant `ZERO` should have UPPER_SNAKE_CASE name, e.g. `Z_E_R_O`

### ISSUE THREAD

**Issue by kawogi** [rust-analyzer/rust-analyzer#6487]
For the following code
```rust
pub const ZERO: Millis = Millis(0);
```
Visual Studio Code reports (attributed to `rust-analyzer`)
```
Constant `ZERO` should have UPPER_SNAKE_CASE name, e.g. `Z_E_R_O`
```
Using a quick fix results in 
```rust
pub const Z_E_R_O: Millis = Millis(0);
```
which is consistent with the error message but very likely not the expected convention.

Offering
```rust
pub const Zero: Millis = Millis(0);
```
Correctly results in
```
Constant `Zero` should have UPPER_SNAKE_CASE name, e.g. `ZERO`
```
(which gives the above follow-up problem)

I expected `ZERO` to be the correct convention and rust-analyzer to not complain. Looks like some PascalCase parser went rogue.

**Comment by Veykril** [comment]
This should've been fixed in https://github.com/rust-analyzer/rust-analyzer/pull/6350, are you on the latest stable plugin version?

**Comment by kawogi** [comment]
Wild guess: this looks like a probable cause. "URL" might be both: `UPPER_SNAKE_CASE` or an abbreviation in "UpperCamelCase".

https://github.com/rust-analyzer/rust-analyzer/commit/854b1331810b503e266be96708ed753db2677865#diff-f29185bc15c9578d498a392c122f4077942cc2fa20ade33f9213c510a5f2ae4cR37

**Comment by kawogi** [comment]
Totally fixed - the extension required a reload for the changes to become active.

Sorry for the noise and thanks for the quick reply!
