### ISSUE TITLE
Suggestion: `..Default::default()` for remaining struct fields in a constructor

### ISSUE THREAD

**Issue by tigregalis** [rust-analyzer/rust-analyzer#6492]
IntelliSense to suggest `..Default::default()` when after the last comma of a struct constructor if it has public fields and a `Default` impl.

Currently I just use a snippet in VS Code:
```javascript
	"..Default::default()": {
		"prefix": [
			"..Default::default()"
		],
		"body": [
			"..Default::default()"
		],
		"description": "Fill remaining fields with default values"
	}
```

![image](https://user-images.githubusercontent.com/38416468/98442268-a2537700-213e-11eb-8207-cea1f6a58a4b.png)

**Comment by matklad** [comment]
Should probably go somewhere around here: https://github.com/rust-analyzer/rust-analyzer/blob/2fd29d04708a19ef30af67bf5e231293d2deaf93/crates/completion/src/completions/record.rs

**Comment by bnjjj** [comment]
I will implement this
