### ISSUE TITLE
Syntax highlighting is incorrect after /**/

### ISSUE THREAD

**Issue by twanvl** [rust-analyzer/rust-analyzer#6493]
An empty block comment causes the VS code syntax highlighting for all normal tokens after it to look like a comment

For example
```
const looks_ok:u32 = (1);
/**/
const looks_bad:u32 = (1);
```

It sees to only occur with exactly `/**/`, putting anything inside the comment doesn't cause this issue.

**Comment by dustypomerleau** [comment]
This is a result of having separate scope definitions for block comments (`/*...*/`) and block doc comments (`/**...*/`). `/**/` is treated as an unclosed block doc comment containing `/`. If distinguishing the two comment types is not important, then I can simply remove the separate scope for block doc comments.

**Comment by bjorn3** [comment]
Is there any project using block doc comments at all?

**Comment by dustypomerleau** [comment]
> Is there any project using block doc comments at all?

I don't know. I provided the separate scope because they are essentially attributes, so I thought some users might want to color them as attributes. If they aren't being used then it's an easy decision to take them out—if you did happen to use them they would just get block comment scope.

**Comment by kjeremy** [comment]
lsp-types might still have some but I converted most of them to standard
doc comments.

**Comment by matklad** [comment]
`/**/` needs to be handled as a special case: https://github.com/rust-analyzer/rust-analyzer/blob/2fd29d04708a19ef30af67bf5e231293d2deaf93/crates/syntax/src/ast/token_ext.rs#L72-L74
