### ISSUE TITLE
Semantic Highlighting: Why is "::" considered an operator but "." punction?

### ISSUE THREAD

**Issue by Greatness7** [rust-analyzer/rust-analyzer#6498]
The `::` character maps to the scope `keyword.operator.namespace` and the semantic token type `operator`.
The `.` character maps to the scope `keyword.operator.access.dot` and the semantic token type `punctuation`.

It feels intuitive to me that these two work in a similar manner and should share syntax coloring.

**Comment by GrayJack** [comment]
I would argue that both should be punctuation on TextMate grammar and semantic token, neither are defined as a symbol in the [operator expression](https://doc.rust-lang.org/reference/expressions/operator-expr.html) in the reference. The same way I think the `:` should be parsed a punctuation on textmate grammar  (I think it is currently scoped as `keyword.operator.key-value`).
