### ISSUE TITLE
First shell within terminal crashes while the rust analyzer extension is initializing under windows vs code

### ISSUE THREAD

**Issue by Nevsden** [rust-analyzer/rust-analyzer#6503]
Updating to the new vs code version `1.50.1` the rust-analyzer extension seems to create a problem while it is initializing. Everytime I start vs-code on a `rust` workspace, there seems to be a problem with rust-analyzer, which renders the first git shell that is initialized unusable. I then have to remove the shell, wait for rust-analyzer to finish initializing and create a new terminal.

Did that happen to anyone else? Is this more a vs-code problem?

**Comment by lnicola** [comment]
That sounds like a weird issue. What do you mean by "renders the first git shell that is initialized unusable"?

**Comment by Nevsden** [comment]
I think it has nothing to do with rust-analyzer. It also happens, if I open VS Code on a non-rustian workspace. Sorry for opening the issue.

However the problem is, that on startup my terminal opens up with a new git bash shell, but the shell is inactive and I have to open a new shell, which then works fine.

**Comment by bjorn3** [comment]
What do you mean by inactive?

**Comment by Nevsden** [comment]
It means, I somehow cannot interact with the git shell that has opened within the terminal. Clicking into the shell to activate typing into it does not work and the underscore character also does not appear, which usually indicates activity in the shell.

I then have to close the terminal interface using the close symbol and open it up again. Only then, after vs code opens a new shell, the shell can be interacted with.

**Comment by matklad** [comment]
It seems theres' nothing in this issue we can act upon.
