### ISSUE TITLE
New Assist: To/From Block Comments

### ISSUE THREAD

**Issue by brigand** [rust-analyzer/rust-analyzer#6515]
I would like an assist on converting `///` <-> `/**`, and `//!` <-> `/*!` comments to toggle an entire section of comments between the line and block styles. For example, a series of `///` lines documenting a struct could be converted to a single `/** … */` block, and then back again.

I don't see committing code in the block style to be the main use here, but rather this would allow switching to block comments for *easier editing*, and then switching back to line comments when done.

By converting to a block comment temporarily, you're easily able to copy a code example to the clipboard without manually removing the `///<space>` from each line, or to paste a code example from another source into the doc comment. It would also be helpful when updating word wrapping or code example formatting. When done, it only requires a couple keystrokes to switch back.

I would likely author new medium-length doc comments in the block form if it were easy to switch to line comments after.

## Examples

```rust
/// This is the first line of the comment.
///
/// # Example
/// ```
/// let a = 1;
/// let b = 2;
/// let n = if a < b {
///     // Space indented
///     a + b
/// } else {
///     // Tab indented
/// 	b - a
/// };
/// ```
/// Etc...
pub struct S;
```

would convert to/from the following, any number of times...

```rust
/**
This is the first line of the comment.

# Example
`​``
let a = 1;
let b = 2;
let n = if a < b {
    // Space indented
    a + b
} else {
    // Tab indented
	b - a
};
`​``
Etc...
*/
pub struct S;
```

## Additional Details

The above examples are actually imperfect. Each of the line comments likely has a space after the `///`, but isn't required, and that decision isn't represented in the block comment. This allows easier editing at the cost of being potentially but rarely lossy.

I would suggest that relative indentation is preserved, i.e. the least amount of whitespace after the `///` or `//!` on any line being transformed (except if the rest of the line is blank) be trimmed when converting to a block comment, and one space of separation be entered when converting back to line comments. It seems like it would be unusual for this to be an issue, but it would in theory be possible to resolve if people disagree (say, starting the comment with `/** <!-- indent: none -->`).

I'm unsure whether or not line comments that are themselves indented should preserve the whitespace before the `///` when converted to block comments. Either way, you can use the least indented non-blank line when converting back to line comments, and indent it appropriately for the context.

It might also make sense to do this for the non-documentation `//` <-> `/*` comments, for completeness.

I think this would be a generally useful assist to have available, especially when writing or editing library documentation.

**Comment by matklad** [comment]
Yup, we should have this

**Comment by bnjjj** [comment]
Will try to implement this :)

**Comment by Purpzie** [comment]
Just bumping this, I was thinking of suggesting the same thing but found this request first.
