### ISSUE TITLE
RFC: Textmate scopes for tuple structs and enum members

### ISSUE THREAD

**Issue by dustypomerleau** [rust-analyzer/rust-analyzer#6520]
I'd like to improve the highlighting of tuple structs and enum members, which are currently getting function scope when they wrap values in round brackets, and type scope when there are no round brackets.

The default fallback scopes for VS Code are:

| Semantic Token Selector | Fallback Textmate Scope     |
| ----------------------- | -----------------------     |
| type                    | `entity.name.type`          |
| struct                  | `storage.type.struct`       |
| enum                    | `entity.name.type.enum`     |
| enumMember              | `variable.other.enummember` |

Unique scopes are easy at declaration, because we have a keyword to capture (`enum`, `struct`, `trait`, `type`), but I think it may not be possible to distinguish enum members from tuple structs at other locations in the code. I need to pick a sensible scope to distinguish these from function calls. At the moment, I am tempted to use `variable.other.enummember`, but this is less generic than `entity.name.type`, and might feel wrong in the case of tuple structs. Using `variable` scope provides a little more visual distinction, because it would scope enum members differently from the parent enum, which is already getting `entity.name.type`.

Given the fallback scopes, if you were choosing one scope for the following tokens:

```rust
struct Point(i32, i32);
let p = Point(10, 11);
//      ^^^^^ here

enum Animal {
    Dog(String, f64),
//  ^^^ here
    Cat { name: String, weight: f64 },
//  ^^^ here
}

let mut a: Animal = Animal::Dog("Cocoa".to_string(), 37.2);
//                          ^^^ here
a = Animal::Cat { name: "Spotty".to_string(), weight: 2.7 };
//          ^^^ here
```

which scope would you prefer?

**Comment by dustypomerleau** [comment]
I think a reasonable compromise for adding some distinctions would be to use the following patterns (happy for feedback as always):

```rust
// nonspecific - no distinction can be made
Type
namespace::Type

// likely enum
Enum::Member
Enum::Member()
Enum::Member {}

// likely struct
Struct {}
namespace::Struct()

// inside enum declarations, favor member:
enum Enum {
    Member(),
    Member
}

// outside enum declarations, favor Struct
Struct()

// leverage impl
impl Struct {}
impl Trait for Struct {}
```

There are issues navigating interspersed type parameters and such, but I think I can negotiate those with lookarounds.

(also relevant to #6528)

**Comment by HTG-YT** [comment]
In Rust there is also a thing as `trait`. So I guess `storage.type.trait` might also be added

**Comment by dustypomerleau** [comment]
We currently capture traits at declaration as `entity.name.type.trait`, but the issue is that (outside of `impl` blocks) traits don't offer a unique target for the regex, so they can't be separated from other capitalized words (types, enums). There are many partial workarounds, such as grabbing calls to `derive()` in attributes, and hard-coding trait names provided by the standard library, but these half measures will result in traits being highlighted inconsistently. 

At the moment, my plan is to use `entity.name.type.trait` at declaration and in `impl`, and `entity.name.type` elsewhere. This at least reduces the chances of highlighting non-traits as traits. 

The Textmate grammar can only go so far. It's designed to give newcomers to the language a good experience out of the box, and to provide reasonable highlighting if semantic scopes need to be disabled for some reason. I would like to get it to a reasonably stable 1.0 for that purpose, but I don't expect we can match the precision of semantic highlighting.

**Comment by matklad** [comment]
@dustypomerleau you probably want to cc @georgewfraser on these issues. You two are way more knowledgeable then most other folks on this area :-)

**Comment by dustypomerleau** [comment]
I ran into a snag at the intersection of trying to implement these patterns along with tests (https://github.com/microsoft/vscode-textmate/issues/142). Seems that my method of catching the patterns with lookbehinds essentially makes the grammar untestable (with default tooling). I think I'll close this for now - I should be able to refactor to get a similar result, at which point it will be easier for people to give feedback.
