### ISSUE TITLE
Separate the Rust structs, traits, enumerates and enumerate members into 4 different TextMate rules.

### ISSUE THREAD

**Issue by HTG-YT** [rust-analyzer/rust-analyzer#6528]
I personally want to have separate colours for `struct`, `trait`, `enum` and `enum` members when customizing the VSCode syntax highlighting of themes. However due to some restrictions, all those I mentioned above can only have 1 colour.

Would it be possible to make some changes to te `rust.tmLanguage.json` such that they can be separated from one another?

**Comment by lnicola** [comment]
I'm not sure how expressive the TextMate rules are, but one thing we try to do is highlight references to items in the same way as the items. So in:

```rust
struct S;

let s = S;
```

The two `S`es and `s` should have the same color. TextMate rules might be able to do that for `S` and `S`, but not `s`.

My point is that this should be supported with semantic highlighting. Is there a reason why you're not using it? If you are, you can define different colors for the three item types.

**Comment by dustypomerleau** [comment]
I'm afraid Textmate is not up to this particular challenge. I am working on some improvements in this space, and making progress, but this is precisely the problem semantic highlighting was designed to solve.

**Comment by HTG-YT** [comment]
I mean the declaration works... but yeah, those in `use` statements, which is what I wanted to fix. They are unified as `type`s

**Comment by lnicola** [comment]
Did you disable semantic highlighting?

**Comment by HTG-YT** [comment]
I don't think so

**Comment by HTG-YT** [comment]
> Did you disable semantic highlighting?

What did you mean?

**Comment by HTG-YT** [comment]
Nevermind I enabled it and it works like a charm

**Comment by lnicola** [comment]
Not sure what the issue was, but let's close this to keep things tidy.
