### ISSUE TITLE
expected two arugments, found 1

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#6535]
![image](https://user-images.githubusercontent.com/33961674/98935377-bc48dd00-24e3-11eb-8e54-23afc06fb62b.png)

**Comment by GopherJ** [comment]
rust-analyzer: `b7bd0bb`

**Comment by GopherJ** [comment]
#6390  #5502 is it the same thing?

**Comment by flodiebold** [comment]
@GopherJ can you provide a minimal example?

**Comment by GopherJ** [comment]
@flodiebold let me try it, I had this pb some time ago, I'll find the old code to see if it's still possible to reproduce

**Comment by GopherJ** [comment]
@flodiebold I cannot reproduce it anymore
