### ISSUE TITLE
Issues regarding `Self` & `self` (in patterns)

### ISSUE THREAD

**Issue by pksunkara** [rust-analyzer/rust-analyzer#6549]
I have talked with @lnicola and decided that it's better to create an issue for this. Both of them are working fine for structs but they have a few issues for enums.

### ~~Variant not being auto completed~~

<img width="561" alt="lib_rs_—_reign" src="https://user-images.githubusercontent.com/174703/99147507-d0c2dc00-2681-11eb-9a88-cb81b0fe76ec.png">

~~Here, I wanted to do `Self::Foo` but as you can see `Foo` is missing from the list~~

~~Related #4650 (solves some of the issues in it if this is solved)~~

Fixed in #6960

### Self not found in match

<img width="563" alt="lib_rs_—_reign" src="https://user-images.githubusercontent.com/174703/99147538-27301a80-2682-11eb-94de-5d6aeb397262.png">

Here, `self` resolves to `&A` and if I try to type `Self`, I don't get any completions at all. (Also weirdly I get `Some` which should not because `self` does not resolve to an option)

Ideally, I want to see both `Self` and `Self::Foo` in the completion list. (Because if we type `A`, we get both `A` and `A::Foo`)

Related #6404
Related #6550 (Fixing that should solve a part of this, but not fully)

**Comment by ice1000** [comment]
I guess it also has something to do with #1908
