### ISSUE TITLE
Variants auto completion when enums are references

### ISSUE THREAD

**Issue by pksunkara** [rust-analyzer/rust-analyzer#6550]
<img width="407" alt="lib_rs_—_reign" src="https://user-images.githubusercontent.com/174703/99147979-56945680-2685-11eb-92bf-d0b29d2714ae.png">

If `a` is of type `A`:

* When I type `A`, I get `A` and `A::Foo`
* When I type `F`, I get `A::Foo`

But as you can see from above image, if `a` is of type `&A` (same issue with `&mut A`):

* When I type `A`, I get `A`
* When I type `F`, I get neither

**Comment by Veykril** [comment]
Relevant code should be here https://github.com/rust-analyzer/rust-analyzer/blob/e8c803937ce23a6cf74583ad03f9868869c7eea1/crates/completion/src/completions/unqualified_path.rs#L42-L44

The problem is that the call to `as_adt` will fail if the expected type is behind a reference.
