### ISSUE TITLE
Unresolved import for SIMD types (CARGO_CFG_TARGET_FEATURE not evaluated?)

### ISSUE THREAD

**Issue by hrydgard** [rust-analyzer/rust-analyzer#6556]
This builds and runs, but rust-analyzer is unhappy with the vec4 type:

![ra-repro](https://user-images.githubusercontent.com/130929/99182131-4dfa5980-2733-11eb-9d46-47806e35addf.png)

Here's the (rather trivial) repro:

https://github.com/hrydgard/ra-vec4-repro

glam::Vec4 is a SIMD type:

```
/// A 4-dimensional vector.
///
/// This type is 16 byte aligned.
#[cfg(vec4_sse2)]
#[derive(Clone, Copy)]
#[repr(C)]
pub struct Vec4(pub(crate) __m128);
```

So my suspicion is that the `vec4_sse2` option is not set, hiding the type.

The [build.rs](https://github.com/bitshifter/glam-rs/blob/825a75a2c1ccdb225d50ede37a6b6382f5a6997e/build.rs) is what sets this option based on CARGO_CFG_TARGET_FEATURE.

What's the best way to deal with this as a user of glam-rs (or as the library author, to make rust-analyzer do the most sensible thing?)

I guess this is somewhat similar to #6038 ?

**Comment by bjorn3** [comment]
It should work if you enable `loadOutDirsFromCheck`.

```jsonc
{
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
}
```

> I guess this is somewhat similar to #6038 ?

No, that is the `cfg_if` dependency of libstd being ignored.

**Comment by hrydgard** [comment]
Ah thanks, that does indeed take care of it. Though https://github.com/rust-analyzer/rust-analyzer/issues/6448 discusses the insecurity of the option (although when developing something with a build.rs, you'll end up running it whether you use rust-analyzer or not.. so not that big a difference)...

Wonder if glam-rs could somehow do this check without relying on a build.rs, but I'll take that issue over there.
