### ISSUE TITLE
Add readonly modifier for semantic highlighting in vscode

### ISSUE THREAD

**Issue by TimDiekmann** [rust-analyzer/rust-analyzer#6564]
The [Semantic token scope map](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-scope-map) has the selectors `variable` and `variable.readonly`. RA marks mutables as `*.mutable`. Other languages uses the provided selectors (like typescript). It would be nice, if non-mutable variables would receive the `*.readonly` modifier so one can match them, too. The same applies to `property`.

**Comment by matklad** [comment]
I am not sure about this one... `readonly` makes sense for languages which default mutable, but in rust it's immutable by default. 

For the purposes of styling, it makese more sense to apply additional modification (like underlining) if the thing is mutable, rather than apply it by default and remove for readonly things. But I guess we can set both readonly and mutable?

**Comment by TimDiekmann** [comment]
I'd prefer to apply underlining for `*.mutable`, but as far as I can see, it's not possible to get the same style for e.g. Rust and Typescript. For Rust I simply put 
```json
"*.mutable": { "underline": true }
```
but for Typescript I need
```json
"variable": { "underline": true },
"*.readonly": { "underline": false }
```
and this is not compatible. 

> But I guess we can set both readonly and mutable?

I think the more modifiers are included, the better the style can be adjusted. :slightly_smiling_face:

**Comment by Veykril** [comment]
Note that you can add a `:rust` suffix to the rules to make them only apply to a specific language, like `"*.mutablerust": { "underline": true }`

So I think this issue can be closed?

**Comment by Veykril** [comment]
Going to close this, as rust assumes immutability by default, readonly does not make too much sense. And as a second point this can be worked around by special casing the mutability highlighting rules for rust by appending `:rust` to the specifier like `"*.mutable:rust": { "underline": true }`.
