### ISSUE TITLE
Report diagnostic codes from RA in "problems" pane

### ISSUE THREAD

**Issue by Diggsey** [rust-analyzer/rust-analyzer#6580]
Often I'll get spurious errors from RA and I want to disable that specific diagnostic, but it's not easy to find out the name to disable.

I end up having to grep the RA source to find where the message is formatted, which is not ideal. It would be simpler if the diagnostic codes were visible directly, or at least present in the JSON when you copy the error.

**Comment by kjeremy** [comment]
We do not currently fill in the diagnostic code: https://github.com/rust-analyzer/rust-analyzer/blob/0a658c4a973d934d622957a6fb03916271496385/crates/rust-analyzer/src/handlers.rs#L1131
