### ISSUE TITLE
LSP 3.16: Support annotations (edit previews)

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#6583]
Resource operations, code actions, completion and rename now optionally support returning an `AnnotatedTextEdit` which allows previewing a change with optional confirmation (this corresponds to the vscode's ` WorkspaceEditEntryMetadata` api). We should take advantage of this where it makes sense and also extend our `SnippetWorkspaceEdit` to support this capability if the client advertises support.

**Comment by kjeremy** [comment]
This also applies to resource operations like create/rename/delete file.

**Comment by matklad** [comment]
I think we now do this/
