### ISSUE TITLE
Feature request: Hover Actions: Method References

### ISSUE THREAD

**Issue by strohel** [rust-analyzer/rust-analyzer#6590]
rust-analyzer in VSCode currently offers:
- [x] Lens: Implementations
- [x] Lens: Method References
- [x] Hover Actions: Implementations
- [ ] Hover Actions: Method References

I find the `Method References` feature rather handy (i.e. one sees the usage count without invoking references search), but I find Lenses rather intrusive. Would it be possible to add `Method References` under `Hover Actions` as well?

I'm using rust-analyzer v0.2.384 from [open-vsx.org](https://open-vsx.org/extension/matklad/rust-analyzer) + VSCodium 1.51.1.

**Comment by vsrs** [comment]
Working on it.
