### ISSUE TITLE
Failed to load mio/url during reload

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#6596]
I started rust-analyzer and noticed the following in the log:

```
[ERROR rust_analyzer::reload] failed to load C:\Users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.6.22\test/mod.rs
[ERROR rust_analyzer::reload] failed to load C:\Users\jkolb\.cargo\registry\src\github.com-1ecc6299db9ec823\url-2.2.0\benches/parse_url.rs
```

**Comment by jonas-schievink** [comment]
This happens because those files are not included in the Cargo package (because the crates use `include`), but the files are still referenced in Cargo.toml, so it's a benign error (maybe it should be a warning instead?).
