### ISSUE TITLE
Crash on a missing `version` field

### ISSUE THREAD

**Issue by poliorcetics** [rust-analyzer/rust-analyzer#6603]
### Logs

Excerpt from the neovim logs:

```
"rust-analyzer" "stderr"    "thread 'main' panicked at 'Invalid notification
Method: textDocument/didSave
error: missing field `version`', /Users/alexis/.config/rust/cargo/registry/src/github.com-1ecc6299db9ec823/lsp-server-0.5.0/src/msg.rs:192:17
stack backtrace:
"
"rust-analyzer" "stderr"    "   0: _rust_begin_unwind
1: std::panicking::begin_panic_fmt
2: lsp_server::msg::Notification::extract::{{closure}}
3: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::on_notification
4: rust_analyzer::main_loop::"
"rust-analyzer" "stderr"    "<impl rust_analyzer::global_state::GlobalState>::handle_event
5: rust_analyzer::main_loop::main_loop
6: rust_analyzer::run_server
7: rust_analyzer::try_main
8: rust_analyzer::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
"
```

### Version

- `rust-analyzer cadf0e9`
- macOS 10.15.7

### Tested with

- [`zoxide`](https://github.com/ajeetdsouza/zoxide)
- [`cargo-intraconv`](https://github.com/poliorcetics/cargo-intraconv)

Both those crates have a valid `version` field.

### More infos:

[Relevant neovim issue in which I discovered the bug](https://github.com/neovim/neovim/issues/13344)

**Comment by bjorn3** [comment]
The panic message shows that the error comes from lsp-server. It must be neovim not sending the version fields in an lsp request.

**Comment by poliorcetics** [comment]
Could this be worked around via a PR to `lsp-server` ? Panicking, regardless of the message sent, seems like a bad thing

**Comment by poliorcetics** [comment]
I made a PR to `lsp-server` to change the current behaviour. It is a breaking change so fixing this crash will have to wait for a new version of `lsp-server` to be published to crates.io and updated in the `Cargo.toml` for RA before anything else is done here. I'll try to maintain a patch on the side which uses my locally modified `lsp-server` to see how it behaves in practice.

**Comment by flodiebold** [comment]
Looks to me like [this](https://github.com/gluon-lang/lsp-types/blob/207766153e54a56f33a1fbaab71837277638fdec/src/lib.rs#L1959) line in lsp-types is wrong, according to https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didSave. Not sure why that only seems to be a problem with neovim, though.

**Comment by flodiebold** [comment]
(CC @kjeremy )

**Comment by kjeremy** [comment]
I'll check it out when I get to a computer. What does it look like compared
with 3.16?

**Comment by poliorcetics** [comment]
> Looks to me like [this](https://github.com/gluon-lang/lsp-types/blob/207766153e54a56f33a1fbaab71837277638fdec/src/lib.rs#L1959) line in lsp-types is wrong, according to https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didSave. Not sure why that only seems to be a problem with neovim, though.

Isn't this example the one that is correctly followed by lsp-types:

```typescript
interface DidSaveTextDocumentParams {
	/**
	 * The document that was saved.
	 */
	textDocument: TextDocumentIdentifier;

	/**
	 * Optional the content when saved. Depends on the includeText value
	 * when the save notification was requested.
	 */
	text?: string;
}
```

If yes, it seems to me lsp-types is correct and it's neovim that fails to send the correct information, causing the crash ?

**Comment by flodiebold** [comment]
> EDIT: oh, I see the VersionedTextDocumentIdentifier vs TextDocumentIdentifier is the thing you are pointing out as wrong ?

Yes, the former has the `version` field, the latter doesn't.

> I'll check it out when I get to a computer. What does it look like compared
with 3.16?

Ah, indeed, 3.16 has `VersionedTextDocumentIdentifier` there. Is that a breaking change in the protocol? :thinking:

**Comment by poliorcetics** [comment]
So this happens because neovim is not yet up to date with the changes to the spec ?

(I don't know much about the LSP spec and its versions)

**Comment by kjeremy** [comment]
It's a clarification of the existing spec and should not be a breaking
change.

**Comment by flodiebold** [comment]
Going from `TextDocumentIdentifier` (which doesn't have `version`) to `VersionedTextDocumentIdentifier` (which does, and it's not optional) seems to be a breaking change though? It might have been the intention to make it `OptionalVersionedTextDocumentIdentifier` instead?

**Comment by kjeremy** [comment]
@dbaeumer is this intended?

**Comment by poliorcetics** [comment]
Opened an issue to properly ask about it and give it more visibility. 😄

**Comment by dbaeumer** [comment]
Will have a look. I think that was a mistake.
