### ISSUE TITLE
thread '<unnamed>' panicked at 'no value set for FileTextQuery(FileId(1))'

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#6622]
I used the "memory usage" command a few moments earlier. I have `rust-analyzer.rustcSource` set since today.

```
thread '<unnamed>' panicked at 'no value set for FileTextQuery(FileId(1))', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.0/src/input.rs:104:32
stack backtrace:
Panic context:
> request: textDocument/foldingRange FoldingRangeParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            host: None,
            port: None,
            path: "/home/bjorn/Documenten/cg_clif3/src/abi/pass_mode.rs",
            query: None,
            fragment: None,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
}
```

**Comment by kjeremy** [comment]
I can reproduce this on windows

**Comment by kjeremy** [comment]
In fact it messes every other LSP request up after.

**Comment by d00z3l** [comment]
Similar issue for me on Windows after I upgraded, it crashes and then stops. Use v0.2.400 extension in VS Code.

 ```
thread '<unnamed>' panicked at 'no value set for FileTextQuery(FileId(0))', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.16.0\src\input.rs:104:32
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 3:42:28 pm] Registering progress handler for token rustAnalyzer/indexing failed.
Error: Progress handler for token rustAnalyzer/indexing already registered
	at Object.onProgress (c:\Users\tryan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:4302:23)
	at LanguageClient.onProgress (c:\Users\tryan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:11915:45)
	at new ProgressPart (c:\Users\tryan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:9950:41)
	at createHandler (c:\Users\tryan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:13237:34)
	at handleRequest (c:\Users\tryan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:3832:41)
	at processMessageQueue (c:\Users\tryan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:3713:17)
	at Immediate._onImmediate (c:\Users\tryan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:3703:13)
	at processImmediate (internal/timers.js:439:21)
```

**Comment by Nashenas88** [comment]
I'm seeing this as well:
```
thread '<unnamed>' panicked at 'no value set for FileTextQuery(FileId(0))', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.0/src/input.rs:104:32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   2: <salsa::input::InputStorage<Q> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch::{{closure}}
   3: <salsa::input::InputStorage<Q> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   4: <DB as base_db::SourceDatabaseExt>::file_text::__shim
   5: salsa::runtime::Runtime::execute_query_implementation
   6: salsa::derived::slot::Slot<Q,MP>::read_upgrade
   7: salsa::derived::slot::Slot<Q,MP>::read
   8: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
   9: <DB as ide_db::LineIndexDatabase>::line_index::__shim
  10: ide::Analysis::file_line_index
  11: rust_analyzer::handlers::publish_diagnostics
  12: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  13: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  14: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by kjeremy** [comment]
> 
> 
> Similar issue for me on Windows after I upgraded, it crashes and then stops. Use v0.2.400 extension in VS Code.
> 
> ```
> thread '<unnamed>' panicked at 'no value set for FileTextQuery(FileId(0))', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\salsa-0.16.0\src\input.rs:104:32
> stack backtrace:
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> [Error - 3:42:28 pm] Registering progress handler for token rustAnalyzer/indexing failed.
> Error: Progress handler for token rustAnalyzer/indexing already registered
>    at Object.onProgress (c:\Users\tryan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:4302:23)
>    at LanguageClient.onProgress (c:\Users\tryan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:11915:45)
>    at new ProgressPart (c:\Users\tryan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:9950:41)
>    at createHandler (c:\Users\tryan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:13237:34)
>    at handleRequest (c:\Users\tryan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:3832:41)
>    at processMessageQueue (c:\Users\tryan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:3713:17)
>    at Immediate._onImmediate (c:\Users\tryan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:3703:13)
>    at processImmediate (internal/timers.js:439:21)
> ```

I believe @jonas-schievink fixed this particular one with #6701

**Comment by kjeremy** [comment]
@Nashenas88 I see this too just loading the rust-analyzer project.

**Comment by d00z3l** [comment]
Any chance there is a new release soon? I have to restart VS Code to get the analyzer up and running after it crashes. It has been working perfectly for months 👍  This is an awesome project.

**Comment by kjeremy** [comment]
Every Monday there is a new stable release. Or there are nightlies... or build from source is easy with a `cargo xtask install` command.

**Comment by d00z3l** [comment]
Thanks, I will update!

**Comment by Nashenas88** [comment]
@d00z3l it should also be possible to downgrade to a previous release to get stability back. See https://code.visualstudio.com/updates/v1_30#_install-previous-versions

**Comment by d00z3l** [comment]
Thanks @Nashenas88, that is even easier!

**Comment by thomcc** [comment]
Yes, this causes frequent r-a crashes for me (on macOS), after which sometimes vscode becomes fully unresponsive intermittently (arguably their bug, admittedly — there shouldn't be anything r-a can do that causes that IMO). Surprised there aren't more reports, but maybe it's some idiosyncrasy of my config or something.

Still, very frustrating. `cargo xtask install` on master caused bootstrap failures, and restarting the issue to reappear (it's unclear to me if it was using the master-installed version at that point or the other one)

Reverting to the version released 9 days ago works fine, though.

**Comment by Nashenas88** [comment]
This is already fixed, right? CC @jonas-schievink

**Comment by jonas-schievink** [comment]
> Error: Progress handler for token rustAnalyzer/indexing already registered

This ^ should be fixed. Not sure about the "no value set" thing.
