### ISSUE TITLE
Don't prefix full path specification when changing & to &mut.

### ISSUE THREAD

**Issue by iago-lito** [rust-analyzer/rust-analyzer#6626]
With the following code:
```rust
fn f(vec: &Vec<usize>) {
    vec.push(5);
}
```
I get a suggestion to "change this to a mutable reference", but if I do, I get:
```rust
fn f(vec: &mut std::vec::Vec<usize>) {
    vec.push(5);
}
```

That's a bit overkill, right? I would rather expect
```rust
fn f(vec: &mut Vec<usize>) {
    vec.push(5);
}
```

It actually becomes worse. I've decided to file this bug report after my argument:
```rust
shells: &LocatedShells,
```
was changed to
```rust
shells: &mut topology::located_slice::LocatedBoxedSlice<std::collections::HashMap<usize, shell::Shell, std::hash::BuildHasherDefault<fnv::FnvHasher>>>,
```
instead of just
```rust
shells: &mut LocatedShells,
```

That's definitely overkill, so I end up changing the `&` to `&mut` by hand.
Is this something expected? Or something I can configure not to happen?

**Comment by bjorn3** [comment]
I think those quick fixes are generated by rustc, not rust-analyzer.

**Comment by iago-lito** [comment]
@bjorn3 Oh, should I move the issue to [`rust`](https://github.com/rust-lang/rust) then?

**Comment by bjorn3** [comment]
Yes
