### ISSUE TITLE
Type inference fails on simple example involving i32 fallback and closures.

### ISSUE THREAD

**Issue by umanwizard** [rust-analyzer/rust-analyzer#6628]
Edit: See my most recent comment for a simpler example.

**Comment by umanwizard** [comment]
I don't think the issue is the same as the one discussed in https://github.com/rust-analyzer/rust-analyzer/issues/6338 , since I've manually bumped up the parameter discussed there to 1000.

**Comment by umanwizard** [comment]
Minimal example, with no dependencies:

```
use std::marker::PhantomData;

struct S<T>(PhantomData<T>);
fn f<T>() -> S<T> {
    S(PhantomData)
}
impl<T> S<T> {
    fn f(&self, _t: T) {}
    fn g<F: FnOnce(&T)>(&self, _f: F) {}
}
fn main() {
    let s = (|| {
        let s = f();
        s.g(|_x| {});
        s
    })();
    s.f(10);
}
```

The type of `_x` is not inferred.

**Comment by umanwizard** [comment]
Even more minimal example:

```
use std::marker::PhantomData;

struct S<T>(PhantomData<T>);
fn f<T>() -> S<T> {
    S(PhantomData)
}
impl<T> S<T> {
    fn f(&self, _t: T) {}
    fn g<F: FnOnce(&T)>(&self, _f: F) {}
}
fn main() {
    let s = f();
    s.g(|_x| {});
    s.f(10);
}
```

**Comment by umanwizard** [comment]
Actually, maybe this is a chalk regression? It repros with https://github.com/rust-analyzer/rust-analyzer/issues/6338 (even if I also patch chalk to latest master), but not with rust-analyzer latest master.

**Comment by umanwizard** [comment]
`git bisect` (in chalk) points to https://github.com/rust-lang/chalk/commit/b5cd4d3c956071a1daab3988fd1c4ee678081f11 .

@jackh726 FYI

**Comment by flodiebold** [comment]
I think this is a problem in how we're handling lifetime variables in Chalk solutions (which we didn't get before).
