### ISSUE TITLE
Disabling autosuggest does not work

### ISSUE THREAD

**Issue by sivadeilra** [rust-analyzer/rust-analyzer#6629]
I'm using the Rust Analyzer extension. When I'm typing Rust code, VS Code constantly raises pop-ups for function arguments and other things, and it's extremely distracting. I can't even see the code I'm writing because the pop-ups cover the editor so much.

I contacted the team that provides Rust Analyzer, and they said that this is controlled by VS Code itself, not by Rust Analyzer. I have tried every parameter I can find to disable autosuggestions in VS Code, and none of them actually seem to have any effect.

I have used these settings:

```
"editor.quickSuggestions": false,
"editor.suggestOnTriggerCharacters": false,
"editor.quickSuggestionsDelay": 1000000
```

Please help. Editing has become so frustrating that I'm on the verge of abandoning VS Code.

**Comment by SomeoneToIgnore** [comment]
There are various "Editor Show" settings in VSCode:

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/2690773/100200706-a7b70c80-2f07-11eb-9f73-7f1fd3e38995.png">

Disabling them all turned off the completion suggestions for me, please try it out.

**Comment by SomeoneToIgnore** [comment]
Also to note: for me, `"editor.quickSuggestions": false,` had turned off the completions while I type too.
They do appear on Ctrl + Space though.

**Comment by lnicola** [comment]
Also `editor.hover.enabled` and `editor.codeLens`.

**Comment by lnicola** [comment]
@sivadeilra closing this for now, but feel free to ask more questions if you're still having trouble with the IDE configuration.
