### ISSUE TITLE
include! macro not being expanded

### ISSUE THREAD

**Issue by djmarcin** [rust-analyzer/rust-analyzer#6636]
I'm trying to use `rust-project.json` and I have proc macros mostly working, except that the `include!` macro does not seem to be being expanded properly. I'm using the `sysroot_src` parameter, so maybe it's something to do with `librustc_macros.so` not being loaded properly? Is it expected to be at a specific location relative to sysroot_src or even the rust toolchain?

The exact way I'm testing this is by using tonic to generate a proto definition, and then using `include!("/absolute/path/to/file.rs")`, but the types are not resolved in other files (e.g. `{unknown}` on hover). When I manually replace the `include!` with the actual contents of the generated file the types are all resolved as expected, so it seems to be the `include!` macro.

**Comment by bjorn3** [comment]
`librustc_macros.so` is a set of proc macros used during compilation of rustc itself. That it can be found in `lib/` is just an artifact of the way the build system works. `include!` is directly implemented in rustc cq rust-analyzer.

**Comment by flodiebold** [comment]
If you're using an absolute path, that's probably it. We don't support including files outside the workspace, and I *think* we just don't support including absolute paths in general.

**Comment by djmarcin** [comment]
Yes, I'm using an absolute path, and reading over the code it does look like it include_expand [only deals with relative paths](https://github.com/rust-analyzer/rust-analyzer/blob/7f12a1f225c7d3397f27964ce039b55d680772d3/crates/hir_expand/src/builtin_macro.rs#L329). This makes me curious if `include!(concat!(env!("OUT_DIR"), "/foo.rs"))` works since OUT_DIR appears to me to be 1) an absolute path and 2) not required to be inside the workspace (e.g. when passing --target-dir).

Are there technical reasons for the limitation to relative paths and requiring files to be inside the workspace?

**Comment by flodiebold** [comment]
Actually, now I think absolute paths should work as long as they are in the workspace. The file just needs to be inside the same source root as the including file. I'm not 100% sure how the rust-project.json paths map to source roots, but probably both paths should be inside the same path defined using `include` inside the same `Crate`, and the included path should not be `exclude`d.

**Comment by bjorn3** [comment]
> Are there technical reasons for the limitation to relative paths and requiring files to be inside the workspace?

Rust-analyzer simply doesn't know about files outside the workspace. All files are added to the VFS in advance before parsing any single file using `set_file_text`. Due to the query architecture it is not possible to read arbitrary files without completely avoiding the query architecture. Avoiding it would prevent any changes to the read file to be propagated to the analysis results.

**Comment by djmarcin** [comment]
Thanks! These were the hints I needed to get it working. I had to set _both_ the normal crate root as well as the `OUT_DIR` in the `include` array of the project config. With that set up, the VFS knows about the files and can resolve them from absolute paths.
