### ISSUE TITLE
Manual cargo check trigger

### ISSUE THREAD

**Issue by kianenigma** [rust-analyzer/rust-analyzer#6642]
I have an override of the cargo check command to run it remotele: 

```
"rust-analyzer.checkOnSave.overrideCommand": [
		"cargo",
		"remote",
		"check",
		"--",
		"--tests",
		"--message-format",
		"json",
	],
```

at the same time, running this on every save is still too much. If check on save is off: 

```
"rust-analyzer.checkOnSave.enable": false,
```

Is there a middle ground where the check command can be triggered manually?

**Comment by bjorn3** [comment]
You can use "Run Task" I think.

**Comment by lnicola** [comment]
Code also supports a remote workflow.

Closing for now, since there are a couple of workarounds.

**Comment by gilescope** [comment]
Is there a "Rust Analyser: Run Check" command? I tried to find it but couldn't. There's 100s of rust analyser commands I can run but the one useful one does seem to be missing. I would settle for a wrapper to cargo that when I run cargo in the terminal updated the problems. At the moment check is turned off on save leads to poor UX. At least `clear && ograc check` helps a little. But would be nice to have an IDE being integrated - working for big projects is exactly where Rust Analyzer should shine..

**Comment by lnicola** [comment]
Yeah, maybe this isn't such a bad feature to have.

**Comment by matklad** [comment]
I still don't quite understand why **Run** isnt' sufficien here: 


https://user-images.githubusercontent.com/1711539/135474455-ee8df973-a51b-4700-ae3c-b717cabd7d6d.mp4


The big benefit of `Run` is that it's the client who is in charge of running the actual cargo command, which is the right separation of concerns. Rust-analyzer shouldn't be an extra middleman betwen the programer and the `cargo check`.

**Comment by lnicola** [comment]
I think the solution proposed by matklad is good enough. It's easy to add a shortcut for it and it even updates the diagnostics.

Closing this and the associated #10302.
