### ISSUE TITLE
Support for multiple windows?

### ISSUE THREAD

**Issue by itmuckel** [rust-analyzer/rust-analyzer#6647]
Hey, great work so far!

I noticed that when I have two windows/instances of VSCode opened with different rust projects, then two instances of rust-analyzer run. Isn't the idea of LSP that multiple projects can use the same server simultaneously?

Don't know if this is possible, but it would be great if the vscode plugin could recognize that an instance of rust-analyzer is already running and connect to it. Currently IntelliJ uses less memory. 😄 

![grafik](https://user-images.githubusercontent.com/18561536/100391166-e4cbed80-3032-11eb-89a1-99e2d86d5c5b.png)

**Comment by bjorn3** [comment]
Every time you open a new window in vscode, effectively a new instance is created. All extensions run once for each window and all files are not synced between windows. This is a property of vscode, not rust-analyzer. Sharing the same rust-analyzer instance between two windows is likely very complex, as different vscode windows may provide conflicting information when for example the same file is changed in two windows in different ways.

> Isn't the idea of LSP that multiple projects can use the same server simultaneously?

The idea is that the same executable can be used by different editors. For example rust-analyzer works fine with vscode, (neo)vim, emacs, etc. LSP is a single common interface for communication between language servers and editors.

**Comment by lnicola** [comment]
Note that if your projects are related, you can use a Cargo workspace and open a single editor instance.

**Comment by lnicola** [comment]
Let's close this, since (while we'd like to use less memory), sharing server instances is probably one of the worse ways.
