### ISSUE TITLE
Quick fix to remove unused parameter leaves unwanted whitespace

### ISSUE THREAD

**Issue by rherrmann** [rust-analyzer/rust-analyzer#6663]
The quick fix _Remove unused parameter_ leaves a whitespace behind, if there are further parameters.

Before:
```rust
fn foo(<|>unused: u8, used: u8) -> u8 {
  return used;
}
```

After:
```rust
fn foo( used: u8) -> u8 {
  return used;
}
```
Note the whitespace before `used`.

**Comment by Veykril** [comment]
Relevant code that determines the text range to be deleted is here: https://github.com/rust-analyzer/rust-analyzer/blob/a6f26ded0037a3efb5625ac3482a2f4ec9eb01a3/crates/assists/src/handlers/remove_unused_param.rs#L88-L96
