### ISSUE TITLE
[Question] Find types that implement given trait

### ISSUE THREAD

**Issue by ngortheone** [rust-analyzer/rust-analyzer#6671]
Hi guys. Thanks for rust-analyzer, it is awesome!

Is it possible to show all types that implement a trait(when a cursor is located on a trait)?

I found this, but it is not clear whether this is implemented or not. 
https://github.com/rust-analyzer/rust-analyzer/issues/620

Thanks

**Comment by lnicola** [comment]
I think there's no way to do this with the current `chalk` API. This might be tracked elsewhere, but I can't find an issue for it.

**Comment by flodiebold** [comment]
I think the only reasonable interpretation of this is to find all impl blocks for a given trait, which already exists as a code lens.

Listing all actual *types* implementing a trait is not possible, as this set can easily be infinite.
