### ISSUE TITLE
Analysis stops before finishing files

### ISSUE THREAD

**Issue by noxabellus** [rust-analyzer/rust-analyzer#6672]
In the latest stable release of the extension, I am getting some failures of analysis. The analysis appears to stop before processing all of the items in some files. As shown here, a function at the bottom of my file has no information available, while the same types and information are available for the function right above it.
![rust-analyzer-fail](https://user-images.githubusercontent.com/13547335/100552754-c17d8a00-324e-11eb-88ee-ca677f4577b0.gif)

Edit: Removed "random" from op and title because it is consistently the same items in the same files that fail, though the files do not seem noticeably different in content than any other. Arbitrary might be a better term

**Comment by noxabellus** [comment]
I have just tried rolling my version back up to a few months ago and it doesn't resolve the issue, though I wasn't having this problem last week. I'm guessing this is something to do with updating rust itself and not the extension/server

**Comment by noxabellus** [comment]
This error only seems to happen when my toolchain is set to the nightly branch. On stable, there is no issue. So I rolled back my nightly rust version night by night until I found a version where this error did not appear. The last working version for me is `nightly-2020-10-26-x86_64-unknown-linux-gnu - rustc 1.49.0-nightly (4760b8fb8 2020-10-25)`

**Comment by jonas-schievink** [comment]
This should now be fixed thanks to https://github.com/rust-analyzer/rust-analyzer/pull/6723
