### ISSUE TITLE
Disable inlay type hints by default or at least for when skipping rustfmt?

### ISSUE THREAD

**Issue by huntc** [rust-analyzer/rust-analyzer#6674]
Would it be reasonable to see the inlay type hints disabled by default? I find that the same information is provided when hovering over a variable.

Also, for my particular use-case, I use `#[rustfmt::skip]` for some code sections and the inlay type hints destroy the desired formatting. If disabling by default is unpalatable, not having inlay type hints for where formatting has been disabled would be great.

**EDIT**: Here's an example of my code that (hopefully) benefits from block formatting:

```rust
#[rustfmt::skip]
pub fn command_handler(state: &State, command: Command) -> Effect {
    match (state, command) {
        (State::Idle { observations }, Command::GetObservations)                                         => handle_get_observations(observations),
        (State::Idle { observations }, Command::ProcessAccelerometer { time, ref samples, samples_len }) => handle_process_accelerometer(observations, time, &samples[0..samples_len]),
        (State::Idle { .. },           Command::SetInsideMovement { time })                              => handle_set_inside_movement(time),
        (State::Idle { .. },           Command::SetOutsideMovement { time })                             => handle_set_outside_movement(time),
        (State::Idle { .. },           Command::Timeout)                                                 => Effect::None,
```

This is what it looks like with inlay types enabled:

![image](https://user-images.githubusercontent.com/694893/100672677-65ce1080-33b6-11eb-8fe1-9c6e4ce9be6d.png)

Thanks for any consideration.

Refs:
* https://rust-analyzer.github.io/manual.html#inlay-hints
* https://github.com/rust-analyzer/rust-analyzer/issues/3138

**Comment by flodiebold** [comment]
In general, we want all features enabled by default, because otherwise you might never know they exist.

I don't know about disabling inlay hints because of a rustfmt annotation, that seems like it would be rather surprising as well :thinking:

**Comment by huntc** [comment]
> I don't know about disabling inlay hints because of a rustfmt annotation, that seems like it would be rather surprising as well

What was surprising was to see my careful formatting was compromised visually having just switched to Rust Analyzer.

Is there a way I can save this setting’s value against my project so that others who open it, and who use Rust Analyzer, won’t be surprised?

**Comment by flodiebold** [comment]
There are editor-specific ways to save settings local to the workspace, for example in [VS Code](https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations).

**Comment by lnicola** [comment]
Speaking as an occasional contributor to other projects (as opposed to a `rust-analyzer` developer), I wouldn't be keen on losing IDE features for the sake of some `#[rustfmt::skip]` sections. Depending on your code, you might be able to format it a little differently (e.g. by inserting newlines) so that the hints don't make it look weird.

For ["novelty" code](http://ioccc.org/2019/mills/prog.c) I'd recommend the viewer to disable hints if they want it to look right.

**Comment by huntc** [comment]
Thanks for the dialogue on this topic. I've edited the original description to include an example of the code I'm formatting, and a screenshot to show what happens with inlay type hints enabled. I'm certainly open to feedback on how others may go about formatting for my use-case.

I'd also like to point out that this issue has nothing to do with novelty code. Thanks.

**Comment by lnicola** [comment]
Yeah, that's fair code. For me, this would probably be "good enough":

```rust
#[rustfmt::skip]
pub fn command_handler(state: &State, command: Command) -> Effect {
    match (state, command) {
        (State::Idle { observations }, Command::GetObservations)
            => handle_get_observations(observations),
        (State::Idle { observations }, Command::ProcessAccelerometer { time, ref samples, samples_len })
            => handle_process_accelerometer(observations, time, &samples[0..samples_len]),
        (State::Idle { .. }, Command::SetInsideMovement { time })
            => handle_set_inside_movement(time),
        (State::Idle { .. },Command::SetOutsideMovement { time })
            => handle_set_outside_movement(time),
        (State::Idle { .. }, Command::Timeout)
            => Effect::None,
    }
}
```

but I have a very high threshold for disabling `rustfmt`.

In this case I'd probably split the match and move the handling of each `State` into a different function.

**Comment by Veykril** [comment]
This would probably make more sense to think about as a r-a specific tool attribute cc https://github.com/rust-analyzer/rust-analyzer/issues/7449
