### ISSUE TITLE
Unable to run individual parameterized tests - e.g. with test_case

### ISSUE THREAD

**Issue by sazzer** [rust-analyzer/rust-analyzer#6687]
Using crates for parameterized testing doesn't allow me to run the individual tests using the "Run Test" action. I can run the entire set of tests in the module, but not a single method.

The reason for this is because the tests are run with `--exact` but the name provided is *not* the exact test name, since the exact test name is ultimately generated.

For example, given the test:
```
    #[test_case("", ParseUserIDError::Malformed ; "Blank")]
    fn failed_parse(input: &str, expected: ParseUserIDError) {
        let parsed: Result<UserID, ParseUserIDError> = input.parse();
        let_assert!(Err(err) = parsed);
        check!(err == expected);
    }
```

Running this will execute: 
```
cargo test --package universe --lib -- users::model::user_id::tests::failed_parse --exact --nocapture <
```

Whilst the exact test name is `users::model::user_id::tests::failed_parse::blank` (And an additional test function for each occurrence of `test_case`)

If I use the "Run Test" action on the module as a whole, it executes without the `--exact` flag and thus works.

**Comment by bjorn3** [comment]
Without `--exact` if there would be a test called `foo` and `foobar`, trying to run `foo` would run both. It would be better to keep passing `--exact`, but implement expansion of attribute proc macros.
