### ISSUE TITLE
Add an option to reload rust-analyzer to vscode ext

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#669]

**Comment by jrvidal** [comment]
Does this mean restarting the server? I could look into that.

**Comment by matklad** [comment]
@jrvidal yeah, I imagine a VS Code command “Rust Analyzer: restart server”

**Comment by jrvidal** [comment]
Fixed in https://github.com/rust-analyzer/rust-analyzer/pull/1153

**Comment by bjorn3** [comment]
Thanks
