### ISSUE TITLE
Feature request: Make Run & Debug button more pronounced

### ISSUE THREAD

**Issue by havish10** [rust-analyzer/rust-analyzer#6691]
Right now the run and debug buttons are quite small, and they are only at the main method so you have to scroll all the way up to run your code. Something like the Code Runner extension would be very usefull, or a keyboard shortcut to run the file.

**Comment by bjorn3** [comment]
You can use ctrl-shift-p > run task.

**Comment by havish10** [comment]
a more concise shortcut would be better

**Comment by bjorn3** [comment]
You can assign "Tasks: Rerun Last Task" a keybinding yourself. There doesn't seem to be a way to assign a keybinding to "Tasks: Run Task".

**Comment by lnicola** [comment]
Yeah, I don't think we can do anything else here. Closing for now.
