### ISSUE TITLE
Workspaces fail to properly analyze with certain dependencies

### ISSUE THREAD

**Issue by jkelleyrtp** [rust-analyzer/rust-analyzer#6693]
I've been trying to find a web-server library that works for a crate in a workspace and can't find anything. It seems that tokio and async_std or the crates themselves (actix, gotham, warp, tide, etc) break all symbol inference when added as a dependency to a crate in a workspace. I have these flags setup:

```
  "rust-analyzer.procMacro.enable": true,
  "rust-analyzer.cargo.loadOutDirsFromCheck": true,
```

For now, I'm just building each crate on its own (no workspace), but this does lead to the issue described in the docs:

> If each crate had its own target directory, each crate would have to recompile each of the other crates in the workspace to have the artifacts in its own target directory. By sharing one target directory, the crates can avoid unnecessary rebuilding.

I'm scratching my head because I don't know what other debug information I can provide, other than "I don't see any errors highlighted when my crate is in a workspace."

**Comment by flodiebold** [comment]
Can you provide an example workspace that reproduces the problem?

**Comment by lnicola** [comment]
@jkelleyrtp are you still having this issue?

**Comment by jkelleyrtp** [comment]
The issue still persists, but I think Rust Analyzer is running into unrecoverable errors from Rustc.

This is the underlying issue:
https://github.com/rust-lang/rust/issues/79946

I'll close this issue.
