### ISSUE TITLE
How to *actually* use rust's source as `RUST_SRC_PATH`

### ISSUE THREAD

**Issue by maisiliym** [rust-analyzer/rust-analyzer#6695]
Using rust's git source results in missing Cargo files which seem to be from other repos, which are registered as submodules.
Obviously, checking out all of the submodules should work, but that would mean keeping duplicate copies of each one of those, which are already present in their own 'github paths'. Is there a more elegant way?
```
LSP[rust_analyzer] rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /git/github.com/rust-lang/rust/library/std/Cargo.toml, cargo
 1.49.0-nightly (becb4c282 2020-10-28): Failed to run `cargo metadata --manifest-path /git/github.com/rust-lang/rust/library/std/Cargo.toml`: Error during execution of `c
argo metadata`: error: failed to read `/git/github.com/rust-lang/rust/src/tools/rust-installer/Cargo.toml`
Caused by:
  No such file or directory (os error 2)
```

**Comment by bjorn3** [comment]
You could remove the `Cargo.toml` in the root of the rust checkout. This is the file that references some of the submodules.

**Comment by maisiliym** [comment]
https://github.com/rust-lang/rust/pull/81778
