### ISSUE TITLE
Error on proc macro

### ISSUE THREAD

**Issue by AurevoirXavier** [rust-analyzer/rust-analyzer#6696]
It can work 2 days ago.

But today I update it on vscode.

And the proc macro report error. Looks so noisy.

![2020-12-02_13-52](https://user-images.githubusercontent.com/16152305/100833899-d2740880-34a5-11eb-8d5d-0bab625fee5f.png)

**Comment by AurevoirXavier** [comment]
This macro is from crate frame-support.

```
frame-support = { version = "2.0.0" }

use frame_support::decl_storage;
```

**Comment by bjorn3** [comment]
It expects `CARGO_PKG_NAME` to be set: https://github.com/paritytech/substrate/blob/918313f9bea2766bddcef8ea5b5a454486f3acfe/frame/support/procedural/tools/src/lib.rs#L41

**Comment by AurevoirXavier** [comment]
> It expects `CARGO_PKG_NAME` to be set: https://github.com/paritytech/substrate/blob/918313f9bea2766bddcef8ea5b5a454486f3acfe/frame/support/procedural/tools/src/lib.rs#L41

Any quick fix can I do?

Seems there's a env setting in rust-analyzer.

**Comment by flodiebold** [comment]
The `macro-error` diagnostic is new; this was probably already not working before you updated, you just didn't see the error. You can disable the `macro-error` diagnostic using the `rust-analyzer.diagnostics.disable` setting to go back to not seeing it ;)

Setting `CARGO_PKG_NAME` would probably have to be done programmatically by RA, since it depends on the crate we're "compiling", I guess? I wonder if that's intended/supported usage though...

**Comment by AurevoirXavier** [comment]
> The `macro-error` diagnostic is new; this was probably already not working before you updated, you just didn't see the error. You can disable the `macro-error` diagnostic using the `rust-analyzer.diagnostics.disable` setting to go back to not seeing it ;)
> 
> Setting `CARGO_PKG_NAME` would probably have to be done programmatically by RA, since it depends on the crate we're "compiling", I guess? I wonder if that's intended/supported usage though...

Seems this setting not exist.

**Comment by tomjakubowski** [comment]
@AurevoirXavier I used this:

```
"rust-analyzer.diagnostics.disabled": [
  "macro-error"
]
```

Setting what you did disables all of rust-analyzer's diagnostics, probably not what we want.

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier I used this:
> 
> ```
> "rust-analyzer.diagnostics.disabled": [
>   "macro-error"
> ]
> ```
> 
> Setting what you did disables all of rust-analyzer's diagnostics, probably not what we want.

Thanks.

**Comment by Diiaablo95** [comment]
The same is happening again, on Mac Silicon with Rust Analyzer version 0.2.853 and VSCode version Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3, for the frame macro [frame_support::pallet](https://github.com/paritytech/substrate/blob/master/frame/support/procedural/src/lib.rs#L404). Anyone else with the same issue and, more importantly, anyone with a fix? 😂
