### ISSUE TITLE
proc-macro: don't respawn server process on crash

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#6707]
Currently we'll respawn the proc-macro server every time it crashes:

https://github.com/rust-analyzer/rust-analyzer/blob/731b38fa3c1694648e6c8e60f61820f9783343eb/crates/proc_macro_api/src/process.rs#L128-L131

This has caused issues in the past, where this behavior would make the process crash in a loop, leading to a constantly growing number of coredumps on the user's system. The server should only crash when something is seriously wrong, so a better behavior would be to disable proc macros and let the user know that something went wrong.

**Comment by kjeremy** [comment]
This sounds like a good plan. An alternate approach would be to have a back
off strategy but I like the idea of being upfront with the user.
