### ISSUE TITLE
Completion stopped working for single file in project

### ISSUE THREAD

**Issue by ndarilek** [rust-analyzer/rust-analyzer#6717]
There's probably a simple fix for this but I can't find it. All identifier-based autocompletion has stopped working in a single file in my VSCode project. Even something like `std` doesn't provide completions, though `trait` and other keywords work fine. I see the following in my output logs:

```
WARN [12/3/2020, 9:02:50 PM]: LSP request timed out {
  method: 'rust-analyzer/inlayHints',
  param: {
    textDocument: { uri: 'file:///c%3A/Users/Nolan/projects/escape/src/GAME.RS' }
  },
  error: ResponseError: Rust Analyzer is still loading...
      at handleResponse (c:\Users\Nolan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:3904:48)
      at processMessageQueue (c:\Users\Nolan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:3719:17)
      at Immediate.<anonymous> (c:\Users\Nolan\.vscode\extensions\matklad.rust-analyzer-0.2.400\out\src\main.js:3703:13)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23) {
    code: -32801,
    data: undefined
  }
```

I notice it thinks the file I'm editing is GAME.RS. I did accidentally quickly type GAME.RS without realizing capslock was set when creating the file. I then closed the file, renamed it to game.rs, confirmed under WSL that the filename is lower-case (I'm on Windows, obviously.), cloned the git repo to a separate directory and confirmed that Windows is creating the file cased correctly, restarted rust-analyzer, restarted VSCode, removed target/ multiple times... Short of uninstalling and reinstalling everything or taking a blowtorch to the system and getting a new one, I'm not sure what to do here. :) Clearly there's a cache somewhere, but it isn't in target/, it isn't obvious how to clear it, and rust-analyzer isn't smart enough to fix this.

How do I fix my stupid mistake? Thanks for your help.

**Comment by ndarilek** [comment]
OK, I fixed this, but it was ugly and probably harder than it needed to be. I changed to %appdata%\code, grepped for every occurrence of GAME.RS, and deleted every directory I found. The one that seemed to fix it was a reference in workspaceStorage.

In the meantime, I also tried running the "reload workspace" command. I also tried the "memory usage (clears database)" command for no other reason than it suggested clearing a database. The only way to get rid of this reference was to grep through the binary data on the filesystem and remove the specific directory.

I hope I don't make this mistake again, but while I do think Windows' case insensitivity leaves something to be desired, at least something I tried probably should have wiped all relevant filename keys in the workspace and regenerated--"reload workspace" for instance. Not sure what to title this issue for tracking that, or if another already exists and I just don't know what to search for, but I hope this can be repurposed to finding a solution.

Thanks!

**Comment by xsoheilalizadeh** [comment]
Related #6141

**Comment by lnicola** [comment]
@ndarilek Unfortunately, `rust-analyzer` doesn't have any persistent caching, so it starts up from scratch every time. My theory is that you left the file open in Code, with the old name/URL. By removing that `workspaceStorage` folder, you've effectively nuked eveything Code knew about your project.

Closing since this is not our bug.

@xsoheilalizadeh `.package-cache` sounds like an emacs thing and your error almost looks as if it's trying to source (`.`) a shell script using the `sh` syntax. Do you have anything Unix-specific in your emacs config? Again, probably unrelated.
