### ISSUE TITLE
A problem of function bracket completion

### ISSUE THREAD

**Issue by junknet** [rust-analyzer/rust-analyzer#6720]
![123](https://user-images.githubusercontent.com/55597646/101177858-3e5f9800-3683-11eb-88d9-c848892afabc.png)
![11](https://user-images.githubusercontent.com/55597646/101177892-461f3c80-3683-11eb-90e2-01fb502f3b0c.png)
In the case of the second picture, I press the completion key, and I cannot complete the function brackets and function parameters.
version:nigthly

**Comment by Veykril** [comment]
I can't reproduce this on current master so I think this got fixed
