### ISSUE TITLE
How to set which files to watch or ignore?

### ISSUE THREAD

**Issue by pakanek** [rust-analyzer/rust-analyzer#6729]
How do I tell rust-analyzer which files to watch or ignore?

When I start Emacs it tells me there are more than 3000 files to watch.

**Comment by flodiebold** [comment]
As far as I understand it, this is a client issue -- emacs-lsp has a configuration that allows you to ignore files for watching, and otherwise it'll watch everything. See [the emacs-lsp documentation](https://emacs-lsp.github.io/lsp-mode/page/performance/#ignore-watch-foldersfiles).
