### ISSUE TITLE
RA reports incorrect-ident-case on extern C fn declarations

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#6736]
RA will report that functions in an `extern "C"` block should have a camel case name. Eg: that you should rename `SDL_Init` to `s_d_l_init`.

Clearly this is just a completely wrong thing to suggest.

**Comment by bjorn3** [comment]
Rust-analyzer doesn't yet fully support `#[allow]`.

**Comment by Lokathor** [comment]
This isn't an issue of allow. This should not generate a message even with no allows at all.

Changing the name of the function in the extern block changes what external function is searched for and linked against. You'd just get link errors for trying to link against functions that don't exist. It's just plain an incorrect suggestion for RA to make at all.
