### ISSUE TITLE
Auto-import suggests hidden (pub in priv module) items

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#6738]
![image](https://user-images.githubusercontent.com/1711539/101330997-9fe65900-3873-11eb-9090-a93ac6f756d6.png)

**Comment by matklad** [comment]
cc @jonas-schievink

**Comment by jonas-schievink** [comment]
hmm, it looks public: https://doc.rust-lang.org/core/unicode/fn.White_Space.html

**Comment by matklad** [comment]
Hm.... I wonder if thouse should be doc(hidden) or something?

**Comment by jonas-schievink** [comment]
Maybe? Certainly seems weird that the entire `unicode` module is missing in `std`

**Comment by matklad** [comment]
submited a fix upstream: https://github.com/rust-lang/rust/pull/79795
