### ISSUE TITLE
Multi-line doc in macro expands to multiple paragraphs, instead of concatenating the lines

### ISSUE THREAD

**Issue by rodrigocfd** [rust-analyzer/rust-analyzer#6742]
I'm using stable versions:
* rust-analyzer v0.2.408
* Rust 1.48.0
* VSCode 1.51.1
* Windows 10 x64

This is the minimal reproducible code:

```rust
/// Long
/// line.
pub struct Normal {}

macro_rules! gen_struct {
    (
        $(#[$attr: meta])*
        $name:ident
    ) => {
        $(#[$attr])*
        pub struct $name {}
    }
}

gen_struct! {
    /// Long
    /// line.
    Generated
}

fn main() {
    let n = Normal{};
    let g = Generated{};
}
```

The `Normal` struct doc is displayed correctly:

![normal](https://user-images.githubusercontent.com/1283868/101360736-d5dc0b00-387c-11eb-9327-df53b3e5688f.png)

But the `Generated` struct shows like this:

![generated](https://user-images.githubusercontent.com/1283868/101361245-7a5e4d00-387d-11eb-83d9-314f3ae8f376.png)

Actually I thought I was using the wrong syntax, and I asked this [on StackOverflow](https://stackoverflow.com/q/65112749/6923555). But, as the answer says, `rust doc` generates the correct output, so it seems to be an issue with rust-analyzer.

**Comment by Veykril** [comment]
The problem here are doc attributes which the macro creates, for those we push a blank line in between their texts when collecting them instead of just a newline. Is that intended? https://github.com/rust-analyzer/rust-analyzer/blob/403ed489ff51e4b1d9b1bbde1ddb6f765ebcbd1f/crates/hir_def/src/docs.rs#L106-L121
