### ISSUE TITLE
Error when running derive macros from the parse-display crate

### ISSUE THREAD

**Issue by JoNil** [rust-analyzer/rust-analyzer#6744]
In this code: https://github.com/JoNil/aoc2020/blob/master/src/bin/2_a.rs

I get the error: "proc macro returned error: Cannot perform expansion for Display: error String("internal error: entered unreachable code: valid raw ident fails to parse") rust-analyzer(macro-error)"

Emanating form the ParseDisplay macro.

I have enabled ust-analyzer.cargo.loadOutDirsFromCheck and rust-analyzer.procMacro.enable.

**Comment by jonas-schievink** [comment]
I've patched quote to include more information:

```
proc macro returned error: Cannot perform expansion for FromStr: error String("internal error: entered unreachable code: valid raw ident fails to parse: (Some(Group { delimiter: None, stream: TokenStream [Ident { ident: \"r#a\", span: 4294967295 }], span: 4294967295 }), None)")
```

This happens because rust-analyzer's `TokenStream`s wrap all of their contents in a group without delimiters, and quote isn't expecting that group. We should get rid of that group, or at least make sure iteration skips it.

**Comment by jonas-schievink** [comment]
Ah, nevermind, we already skip the group. For some reason the `FromStr` impl nested the group inside another one.
