### ISSUE TITLE
some code actions are broken

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#6753]
See: https://github.com/fannheyward/coc-rust-analyzer/issues/492

**Comment by GopherJ** [comment]
any one with the same issue?  Some important actions stopped working recently like quickfix

**Comment by hammypants** [comment]
Yup. Implementing traits and a bunch of other stuff are broken on `nightly`.

**Comment by IWANABETHATGUY** [comment]
![image](https://user-images.githubusercontent.com/17974631/101490936-06679600-399e-11eb-90fc-2a4e29d3585a.png)
the Same problem, duplicate codeAction

**Comment by bjorn3** [comment]
One comes from rust-analyzer itself, while the other likely comes from a rustc warning.

**Comment by flodiebold** [comment]
I don't think we have a "remove these parentheses" code action. The duplicate might be caused by #6734? I'm not sure that's related to the original issue though.

@hammypants @GopherJ Could you describe the concrete issue and give an example?

**Comment by IWANABETHATGUY** [comment]
> I don't think we have a "remove these parentheses" code action. The duplicate might be caused by #6734? I'm not sure that's related to the original issue though.
> 
> @hammypants @GopherJ Could you describe the concrete issue and give an example?

I am pretty sure , this `remove parentheses` codeAction is offered by the `rust-analyzer`, if i disabled the `rust-analyzer`, this 
codeAction disappear

**Comment by flodiebold** [comment]
Yes, the question is whether the code action comes from our own analysis or from a rustc diagnostic.

**Comment by Veykril** [comment]
I think this might be on #6734 duplicating the rustc lint, therefore duplicating the quickfix
![image](https://user-images.githubusercontent.com/3757771/101497447-482b1900-396b-11eb-8da2-897efeb878cf.png)

**Comment by GopherJ** [comment]
> I don't think we have a "remove these parentheses" code action. The duplicate might be caused by #6734? I'm not sure that's related to the original issue though.
> 
> @hammypants @GopherJ Could you describe the concrete issue and give an example?

![Peek 2020-12-08 22-27](https://user-images.githubusercontent.com/33961674/101543685-da034800-39a4-11eb-83f5-69403b77a83e.gif)

are you able to reproduce this?

**Comment by flodiebold** [comment]
I can't reproduce it from Emacs, with current RA master.

**Comment by GopherJ** [comment]
most of the people are not on master I believe,  I'm using b988c6f

**Comment by flodiebold** [comment]
Can you try master to see whether your problem still exists there?

**Comment by GopherJ** [comment]
@flodiebold I can still reproduce it, strange...

**Comment by flodiebold** [comment]
It seems like a client issue to me, to be honest.

**Comment by GopherJ** [comment]
@fannheyward I can even reproduce the issue using rust-analyzer@2020-10-12

**Comment by flodiebold** [comment]
It would be helpful to get a trace of the LSP communication between the client and server.

**Comment by GopherJ** [comment]
@fannheyward I tried to use coc-rust-analyzer@0.8, things go back to normal

**Comment by GopherJ** [comment]
@
