### ISSUE TITLE
Procedural macro attributes are not supported

### ISSUE THREAD

**Issue by whaqzhzd** [rust-analyzer/rust-analyzer#6758]
rust can be compiled, but ra says these fields don't exist.

This is the smallest demo 
[proc_attributes_bug.zip](https://github.com/rust-analyzer/rust-analyzer/files/5657046/proc_attributes_bug.zip)

**Comment by bjorn3** [comment]
Proc macro attributes are not yet supported.

**Comment by whaqzhzd** [comment]
Thank you for taking your valuable time to answer this question ~ is there any way to temporarily block the rust-analyzer error messages in vscode until rust-analyzer is supported.

**Comment by lnicola** [comment]
You can only selectively disable them:

```json
    "rust-analyzer.diagnostics.disabled": [
        "no-such-field"
    ]
```

**Comment by whaqzhzd** [comment]
Thank you

**Comment by lnicola** [comment]
Duplicate of #6029
