### ISSUE TITLE
No completion for impl blocks on dyn traits

### ISSUE THREAD

**Issue by MaikKlein** [rust-analyzer/rust-analyzer#6777]
```rust
trait Foo {
    fn foo_dyn(&self, s: &str);
}

impl dyn Foo {
    pub fn foo<T: AsRef<str>>(&self, s: T) {
        self.foo_dyn(s.as_ref())
    }
}

impl Foo for u32 {
    fn foo_dyn(&self, s: &str) {
        println!("{} {}", self, s);
    }
}

fn main() {

    let f: Box<dyn Foo> = Box::new(42);
    // No completion for `f.foo`
    f.foo("Hello");
}
```

There are no completions for functions inside an `impl dyn Trait { }` block. It is often nice to add generics on top of your trait objects.

Tested in vim and vscode 

``` 
Language server version 0.2.408 for rust-analyzer
```

**Comment by flodiebold** [comment]
I believe the problem may be in this code:

https://github.com/rust-analyzer/rust-analyzer/blob/ef989880fff36f10b7e166647497779bacc1c47f/crates/hir_ty/src/method_resolution.rs#L248-L276

which determines the crates in which inherent impls for a type may be found. Note that it currently doesn't handle `Ty::Dyn` at all; it probably needs to look at the first trait and take its definition crate.

We probably also need to add a variant to `TyFingerprint`:

https://github.com/rust-analyzer/rust-analyzer/blob/ef989880fff36f10b7e166647497779bacc1c47f/crates/hir_ty/src/method_resolution.rs#L30-L32

It would probably look something like `Dyn(TraitId)`.

**Comment by fisherdarling** [comment]
I'll try and take this one on!
