### ISSUE TITLE
"could not resolve macro `$crate::format_args`" when passing more than two arguments to `assert_eq!(left, right, "there was an error {}, {}", x, y)`

### ISSUE THREAD

**Issue by jrop** [rust-analyzer/rust-analyzer#6791]
Now, before I complain 😄 I want to give the obligatory resounding THANK YOU for creating such an amazing tool.  I rely on rust-analyzer almost every day, and it is simply an invaluable aid to my job.  Now for the bug:

The most recent version of rust-analyzer fails when passing messages + formatting args to `assert_eq!(..)`:

```
❯ rust-analyzer --version
rust-analyzer a0fa522
```

```rust
// main.rs
fn main() {
    let x = 1;
    let y = 3;
    assert_eq!(1, 3, "The values are not equal: {} != {}", x, y);
}
```

The error message given is: ``[rust-analyzer macro-error] [E] could not resolve macro `$crate::format_args` ``.  Now `$crate::format_args` is in the `assert_eq!` definition for more than two arguments:

```rust
macro_rules! assert_eq {
    ($left:expr, $right:expr) => ({
        // .. snip ..
    });
    ($left:expr, $right:expr,) => ({
        $crate::assert_eq!($left, $right)
    });
    ($left:expr, $right:expr, $($arg:tt)+) => ({
        match (&($left), &($right)) {
            (left_val, right_val) => {
                if !(*left_val == *right_val) {
                    // The reborrows below are intentional. Without them, the stack slot for the
                    // borrow is initialized even before the values are compared, leading to a
                    // noticeable slow down.
                    panic!(r#"assertion failed: `(left == right)`
  left: `{:?}`,
 right: `{:?}`: {}"#, &*left_val, &*right_val,
                           $crate::format_args!($($arg)+))
                }
            }
        }
    });
}
```

Here's a screenshot of the error message in context with the code (below).  It seems that the spans for the error message are wonky as well:

![image](https://user-images.githubusercontent.com/1404053/101694388-47a88600-3a30-11eb-8ba8-8fbe1f08fee8.png)

**Comment by jrop** [comment]
It's worth noting that when I upgrade rust-analyzer to the nightly (e4c6c70), I do not see this error. 👍

**Comment by jrop** [comment]
Possibly related #6788

**Comment by lnicola** [comment]
Right, see https://github.com/rust-analyzer/rust-analyzer/issues/6716.

This should be fixed now, please reopen if it still happens on nightly.
