### ISSUE TITLE
Can't format inside tokio select macro.

### ISSUE THREAD

**Issue by FH0** [rust-analyzer/rust-analyzer#6792]
I try to add some instructions, but I found it easy to understand.

https://docs.rs/tokio/0.3.5/tokio/macro.select.html

**Comment by lnicola** [comment]
Does `cargo fmt` work for that code?

**Comment by bjorn3** [comment]
Rustfmt doesn't format code inside macros as it only sees opaque token trees. It doesn't know if those token trees should be interpreted as item, statement, expression or anything else.

**Comment by jonas-schievink** [comment]
Not our bug, then
