### ISSUE TITLE
Broken syntax highlighting after any local macro 

### ISSUE THREAD

**Issue by grunweg** [rust-analyzer/rust-analyzer#6794]
Follow-up to #6793. This is probably a duplicate of #1559; feel free to close in that case.
(Filing this also so I can reference this bug with the itertools crate.)

After any occurrence of the `itertools::iproduct!` macro, there is no more syntax highlighting for remainder of the file.
Tested with the 2020-12-07 release, but probably happens on any version after https://github.com/rust-analyzer/rust-analyzer/commit/be50908a5031fee45fcbba97bc0c96187324ea54.

**Example code**
```
// add itertools="0.9.0" to the Cargo.toml file
// main.rs has this
use itertools::iproduct;
fn main() {
    let t = ["toast", "bread"];
    for (a, b) in itertools::iproduct!(t.iter(), t.iter()) {
        println!("{}, {}", a, b);
    }
}
```

**Expected**
Syntax highlighting works normally for the whole file.

**Actual**
No syntax highlighting after line 3.

Thanks for your time!

**Comment by grunweg** [comment]
Never mind; I figured out how to resolve this myself: replacing the call to ``itertools::iproduct!`` by ``iproduct!`` restores syntax highlighting.

**Comment by lnicola** [comment]
I can't reproduce this on `master`:

![image](https://user-images.githubusercontent.com/308347/101772042-86534480-3af3-11eb-9372-0c554443c621.png)

Do you have any errors in Atom LSP logs? Does Atom even support semantic highlighting? If not, it's probably an Atom issue.

**Comment by grunweg** [comment]
How do I enable Atom LSP logs?

**Comment by lnicola** [comment]
No idea. Does it still happen if you disable `rust-analyzer`?
