### ISSUE TITLE
 rust-analyzer freezes vim and vscode-neovim

### ISSUE THREAD

**Issue by extremegf** [rust-analyzer/rust-analyzer#6803]
I've noticed that at RA v0.2.408 vim support seems broken.

This applies to both vscodevim.vim v1.18.4 and asvetliakov.vscode-neovim v0.0.63. 

The vim plugin does not accept any input while rust analizer is processing current file / module (I'm not sure of the scope).

Simplest reproduction is to edit the file and hold j. The cursor movement is jerky until processing finishes. Removing vim plugin and doing the same experiment holding arrow down show no jerky movement.

Does anyone see similar behavior?

**Comment by lnicola** [comment]
For me it's relatively smooth. I'm using NeoVim 0.4.4 and LanguageClient-neovim.

**Comment by extremegf** [comment]
Im

**Comment by lnicola** [comment]
Oh, I just noticed what those plugins were. So you're running Neovim in VS Code. I haven't tried that, but maybe you could try to test with fewer pieces in the equation, either a console neovim or a Code without any Vim plugins.

**Comment by extremegf** [comment]
I disabled all my plugins and then re-enabled rust-analizer and vscodevim.vim. 

That fixed the stutter and lag.

This must have been some interaction with other plugins.
