### ISSUE TITLE
Memory metrics stopped working

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#6808]
I think we're no longer reporting memory usage since https://github.com/rust-analyzer/rust-analyzer/pull/5581.

_Originally posted by @lnicola in https://github.com/rust-analyzer/rust-analyzer/issues/6597#issuecomment-742731892_

**Comment by jonas-schievink** [comment]
They're back, and went down quite a bit :tada: https://rust-analyzer.github.io/metrics/
