### ISSUE TITLE
"Failed to parse macro invocation" when using puffin (regression)

### ISSUE THREAD

**Issue by hrydgard** [rust-analyzer/rust-analyzer#6811]
Puffin is a nice little instrumented profiling library by @emilk .

It used to work well with rust-analyzer, but doesn't anymore since 0.2.408 or a very nearby version. 

![image](https://user-images.githubusercontent.com/130929/101881631-f7970400-3b94-11eb-8ed3-a6b58606ce3e.png)

## Complete repro

cargo.toml:
```toml
[package]
name = "repro"
[dependencies]
puffin = "0.3.1"
```

main.rs
```rust
fn main() {
    puffin::profile_function!();
}
```

The offending macro looks like this:
```rust
#[macro_export]
macro_rules! profile_function {
    () => {
        let _profiler_scope = if $crate::are_scopes_on() {
            Some($crate::ProfilerScope::new(
                $crate::current_function_name!(),
                $crate::current_file_name!(),
                "",
            ))
        } else {
            None
        };
    };
}
```

which doesn't look all that complicated but does call other macros from the macro - related to #6788 ? (EDIT: no, doesn't seem to be)

**Comment by emilk** [comment]
Direct link to all the macros in `puffin`: https://github.com/EmbarkStudios/puffin/blob/main/puffin/src/lib.rs#L364

**Comment by edwin0cheng** [comment]
Reproduction :

```
macro_rules! profile_function {
    () => {
        let _a = if true {
            Some(1)
        } else {
            None
        };
    };
}

fn main() {
    profile_function!();
}
```

**Comment by edwin0cheng** [comment]
The simplest form : 

```rust
macro_rules! profile_function {
    () => {
        let _a = 1;
    };
}

fn main() {
    profile_function!();
    // ^^ failed to parse macro invocation
}
```

It seem to be related to this line:

https://github.com/rust-analyzer/rust-analyzer/blob/41321d96789ed918eebda02ada76758765d19d16/crates/hir_expand/src/db.rs#L398

And because it is a statement (```let _a = 1;```) and then parser reject it as expr.

**Comment by edwin0cheng** [comment]
@flodiebold I just checked that FIXME was written by you but I forget what it was meant. Could you shed some light about it ?

**Comment by flodiebold** [comment]
IIRC the problem is that during body expansion, we need to detect whether the macro call is in a statement position, and then let it expand to statements instead of an expression and handle that case.

**Comment by flodiebold** [comment]
Basically here we are already in an expression context, so we can't just expand to statements:
https://github.com/rust-analyzer/rust-analyzer/blob/41321d96789ed918eebda02ada76758765d19d16/crates/hir_def/src/body/lower.rs#L550

So I guess we'd actually need to add a special case [here](https://github.com/rust-analyzer/rust-analyzer/blob/41321d96789ed918eebda02ada76758765d19d16/crates/hir_def/src/body/lower.rs#L660) to see if this is a top-level macro call, so we can let it expand to statements.
