### ISSUE TITLE
VS Code hover over comment creates large disruptive visual 'flicker'

### ISSUE THREAD

**Issue by Voultapher** [rust-analyzer/rust-analyzer#6815]
When I hover over a comment inside a function it highlights the whole body and gives me the function expression:

no hover:
![no-hover](https://user-images.githubusercontent.com/6864584/101896962-18b61f80-3baa-11eb-9f22-39d4cb8e79ec.png)

hover:
![hover](https://user-images.githubusercontent.com/6864584/101896969-1bb11000-3baa-11eb-8bf8-fddfd904f9c3.png)

I find this behavior very disruptive and annoying. Any chance to get this changed so it only triggers when I actually select the last expression item like closing brace etc. or at least give us an option to disable this. Right now this creates large amounts of visual distracting noise when moving the mouse.

**Comment by lnicola** [comment]
That looks like a type hint that gets triggered when hovering over the attached comment.

**Comment by lnicola** [comment]
```
[Trace - 13:18:20] Sending request 'textDocument/hover - (13514)'.
Params: {
    "textDocument": {
        "uri": "file:///home/me/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/mod.rs"
    },
    "position": {
        "line": 2271,
        "character": 66
    }
}


[Trace - 13:18:20] Received response 'textDocument/hover - (13514)' in 1ms.
Result: {
    "contents": {
        "kind": "markdown",
        "value": "```rust\n()\n```"
    },
    "range": {
        "start": {
            "line": 2270,
            "character": 43
        },
        "end": {
            "line": 2274,
            "character": 5
        }
    }
}
```
