### ISSUE TITLE
Port item up down movers from IntelliJ

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#6823]
Intellij Rust has this bunch of code: 

https://github.com/intellij-rust/intellij-rust/tree/25f37175094192ba88f345f03b2a4b5b941dd395/src/main/kotlin/org/rust/ide/actions/mover

this is for moving items, statements and mactch arms up and down. rust-analyzer should have this as well, although I don't think that this is exposed in the procol. Rough steps:

* design appropriate LSP protocl extensions (see `lsp-extensions.md`)
* implement in the `ide` crate. This only needs access to `syntax`, so should be rather trivial.
* add a bunch  of tests

**Comment by kjeremy** [comment]
Alternatively could we do this with a command?

**Comment by matklad** [comment]
Yeah, that would need to be a command in VS Code, and a request-response in LSP. The user can then bind the command to ctrl+shift+up/down or whatever

**Comment by kjeremy** [comment]
I think the LSP side could be a command as well to avoid another custom request/response.

**Comment by matklad** [comment]
Ah, sorry, I've misunderstood. Your idea is that the client will send `workspace/executeCommand`, and the server would use `workspace/applyEdit`?  

If that's right, I'd rather do a custom extension still, for two reasons:

* I am not a fan of server-side initiated `applyEdit`, as that loses causality
* THis will still require custom per editor code to surface the command in the UI.

**Comment by kjeremy** [comment]
Yes that was the idea. You would still need custom code to surface the command of course but the benefit to other clients is that they wouldn't have to write as much.
