### ISSUE TITLE
format string completion doesn't work for format postfix

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#6843]
https://rust-analyzer.github.io/manual.html#format-string-completion
in the doc, it says:

```
"Result {result} is {2 + 2}".format 
```

will be converted into:

```rust
format!("Result {} is {}", result, 2+2)
```

but it didn't work for VScode and coc,nvim

**Comment by Veykril** [comment]
Looks like the docs or the source is wrong. The docs should either read `fmt → format!(…​)` or the code should check for `format` instead of `fmt`.
We could also have both `fmt` and `format` work here maybe? `fmt` is nice cause its short to type but `format` is more inline with the other additions in that they are fully typed out in regards of their macro counterpart.

https://github.com/rust-analyzer/rust-analyzer/blob/479d1f7eec22c3564867223e2093f14774092528/crates/completion/src/completions/postfix/format_like.rs#L24-L26

**Comment by GopherJ** [comment]
I think we just need one to make things easier, I would think `format` is better even `fmt` is shorter, because users still need to remember to use `fmt` instead of just typing `format` like `panic`

**Comment by GopherJ** [comment]
BTW,

```rust
fn main() {
    let a = "cfg";
    let b = "certificates";
    "{strsim::jaro_winkle(a)}".println!
}
```

produces:

```rust
fn main() {
    let a = "cfg";
    let b = "certificates";
    println!("{::jaro_winkle(a)}", strsim)
}
```

**Comment by Veykril** [comment]
How is your snippet incorrect? Please correct me if I'm wrong but the text between the curly brackets in your snippet isn't a valid format specifier is it? What would be the expected outcome here?

**Comment by lnicola** [comment]
Presumably `println!("{}", strsim::jaro_winkle(a));`.

**Comment by GopherJ** [comment]
@Veykril there are two issues:

1. "{1 + 1}".format doesn't work, it's ok I can use `fmt` but the doc may needs to be updated
2. error with module '::'

```
fn main() {
    let a = "cfg";
    let b = "certificates";
    "{strsim::jaro_winkle(a)}".println!
```

should produce:

```
fn main() {
    let a = "cfg";
    let b = "certificates";
    .println!("{}", strsim::jaro_winkle(a));
}
```

**Comment by Veykril** [comment]
I see, I misunderstood how the postfix is meant to work, thanks!

**Comment by lnicola** [comment]
I still hope that (format) string interpolation will be added to the language.

**Comment by lnicola** [comment]
So this is fixed after #7075 and #7076, right?

**Comment by Veykril** [comment]
Yep should be

**Comment by stuser88** [comment]
Even if I type like the explanatory animation below, 
it does not reproduce in the same way on VSCode 1.73.1, rust-analyzer v0.3.1566.
Is this animation wrong after all? Or is it a bug in the source code?
[https://rust-analyzer.github.io/manual.html#format-string-completion](https://rust-analyzer.github.io/manual.html#format-string-completion)

"Result {result} is {2 + 2}".prin
→println!("Result {result} is {}", 2 + 2)

The animation finally shows println!("Result {} is {}", result, 2 + 2)
but on my VSCode result doesn't move outside of std::fmt syntax.
