### ISSUE TITLE
VSCode "problems" menu entries are too eager to disappear

### ISSUE THREAD

**Issue by SomeoneToIgnore** [rust-analyzer/rust-analyzer#6850]
rust-analyzer version: nightly (4998807)

I don't use the cargo check on save, preferring to run it manually from time to time.

My expected workflow: run `cargo check` RA runnable, get problems menu filled, go over each and fix the issues one by one, sometimes navigating other code or switching between issues without any changes.

My current workflow: same, but with the direct `cargo check` cli output, because problems disappear for me even if I simply navigate between them.

Reproduction on `rust-analyzer` repo: 
spoil the name of the trait
https://github.com/rust-analyzer/rust-analyzer/blob/479d1f7eec22c3564867223e2093f14774092528/crates/hir_ty/src/db.rs#L21

and run the `cargo check -p hir_ty --all-targets` runnable via rust-analyzer, to get the problems populated.
Then, click a few different ones and notice the number of problems displayed.

Here's how it works for me:
<details>
  <summary>gif</summary>
  
  ![gonegonegone](https://user-images.githubusercontent.com/2690773/101995952-cc1c3280-3cd6-11eb-8132-0b6f8bfc33dd.gif)
  
</details>

**Comment by jonas-schievink** [comment]
I believe this is caused by this code

https://github.com/rust-analyzer/rust-analyzer/blob/6f3a3bdde4e526d880b9d8d9c613d2cef50a5f3b/crates/rust-analyzer/src/main_loop.rs#L650-L659
