### ISSUE TITLE
rename trait member symbol doesn't rename for implementor

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#6854]
Reproduce:

1. git clone https://github.com/GopherJ/lttb-rs
2. cd lttb-rs
3. go to line 62
4. call rename symbol action
5. line 67 wasn't updated automatically

![Peek 2020-12-13 14-14](https://user-images.githubusercontent.com/33961674/102012999-a120f580-3d4d-11eb-8390-09c33aa0f118.gif)

**Comment by GopherJ** [comment]
I can reproduce it in `coc.nvim` and `VScode`

**Comment by theotherphil** [comment]
This issue duplicates https://github.com/rust-analyzer/rust-analyzer/issues/2977

**Comment by GopherJ** [comment]
@theotherphil which one shall we focus? because there is also #4201
