### ISSUE TITLE
Feature Request: Derive Default from Enum Variant

### ISSUE THREAD

**Issue by mitsuhiko** [rust-analyzer/rust-analyzer#6860]
A relatively common situation for me is an enum that has one variant that should become the default. It would be nice if one could select the variant that should become the default and be able to automatically derive a `Default` for it:

```rust
enum Variant {
    Undefined, // hover and "derive Default for this variant"
    Minor,
    Major,
}
```

Would then produce this:

```rust
impl Default for Variant {
    fn default() -> Variant {
        Variant::Undefined
    }
}
```

**Comment by bnjjj** [comment]
Will implement this ! I also have this kind of issue
