### ISSUE TITLE
Specifying test target for no_std projects

### ISSUE THREAD

**Issue by MabezDev** [rust-analyzer/rust-analyzer#6869]
I am using ra in a no_std arm project, which works great in terms of auto complete and linting with the following settings:

```json
"rust-analyzer.checkOnSave.allTargets": false,
"rust-analyzer.checkOnSave.extraArgs": [
    "--target",
    "thumbv7m-none-eabi"
]
```
However, when it comes to running my projects tests, they are run on the host platform (typically `x86_64-unknown-linux-gnu`). Is there anyway to tell ra to pass `--target x86_64-unknown-linux-gnu` only when running singular tests?

**Comment by bjorn3** [comment]
You can use the `rust-analyzer.runnables.cargoExtraArgs` config I think.

**Comment by MabezDev** [comment]
Perfect! Not sure how I missed that before! Thank you.

**Comment by Anton-4** [comment]
For future readers; `rust-analyzer.runnables.cargoExtraArgs` has changed to `rust-analyzer.runnables.extraArgs`.
