### ISSUE TITLE
VSCode: Rust highlighting is not performed for block doc comments

### ISSUE THREAD

**Issue by lf-** [rust-analyzer/rust-analyzer#6873]
Hi! Recently I've been taking to using the [block documentation comments](https://doc.rust-lang.org/reference/comments.html) as I find them easier to work with and read. However, the RA extension in VSCode doesn't appear to highlight Rust blocks inside of them.

Versions:
* rust-analyzer extension: 0.2.408
* VSCode: 1.51.1, running on remote on WSL

I appear to have semantic highlighting on, as I have the underlines on mutable variables.

![image](https://user-images.githubusercontent.com/6652840/102089764-82fcd900-3dd1-11eb-8cca-6f9a83b0a297.png)

Sample code from the screenshot:

```rust
/// ```rust
/// println!("blah!!")
/// ```
mod rabug {
    /**
    ```rust
    println!("blah!!")
    ```
    */
    const BLAH: u8 = 0;
    fn blah() {
        //! ```rust
        //! println!("blah!!")
        //! ```
    }
    fn blah2() {
        /*!
        ```rust
        println!("blah!!")
        ```
        */
    }
}
```

**Comment by lf-** [comment]
I just found another bug related to this one:

Actual result: the doc comment gets entirely syntax highlighted as if it is code when it is shown in the mouse over
![image](https://user-images.githubusercontent.com/6652840/103205056-8aca7c00-48ad-11eb-9c26-44e312203802.png)

Expected result: only the code parts are syntax highlighted
![image](https://user-images.githubusercontent.com/6652840/103205084-9c138880-48ad-11eb-8ba9-bf0d199e5321.png)

Repro is to mouse over `blah` (ok) compared to `blah2` (broken) from the sample above. I've added another line `some stuff that's not code` as a text sample for clarity.

**Comment by Veykril** [comment]
I think the problem here is that for block-style comments we do not strip the leading whitespace properly, so when the code checks for the triple backtick prefix it sees whitespace instead making it believe that the comment isn't a code block.
