### ISSUE TITLE
Add common issues to the changelog

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#6877]
It may be useful to put common issues in the change log. We're getting a lot of duplicates.

**Comment by lnicola** [comment]
To be (un)fair, some of them are in the issue template and we're getting duplicates.

**Comment by flodiebold** [comment]
It might also be helpful to add a note saying "this is a new diagnostic, you might see false positives, you can disable it using this setting" whenever we add a new diagnostic, to avoid the "there's a regression in RA, it's showing errors where it didn't before, I'm going back to an older version" reactions.

**Comment by matklad** [comment]
I think this is mostly handled by issue templates now!
