### ISSUE TITLE
proc macro server dies too easily and loses panic messages

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#6880]
I was playing with the example in https://github.com/rust-analyzer/rust-analyzer/issues/6868#issuecomment-744461482 and it seems really easy to make it crash:

![image](https://user-images.githubusercontent.com/308347/102115148-d1e35680-3e43-11eb-87a5-78e0013f61e9.png)

![image](https://user-images.githubusercontent.com/308347/102115160-d7d93780-3e43-11eb-975a-7b67fae07d07.png)

**Comment by jonas-schievink** [comment]
I've noticed this too, the loss of backtraces is due to the macro-side `proc_macro` crate turning them off intentionally. Not sure if we can do much about that.

I don't know why the double panic happens, but that would be great to fix as it tears down the whole process.

**Comment by lnicola** [comment]
Another example: the server is crashing on the `rust-analyzer` repository.

**Comment by edwin0cheng** [comment]
I just checked that the code mentioned do not crash now ?! 

![Screenshot 2020-12-20 134041](https://user-images.githubusercontent.com/11014119/102706023-23b73100-42c9-11eb-83d4-a7d1f7189814.png)

**Comment by lnicola** [comment]
I'm not sure how exactly I've made it crash -- are you getting no errors in the RA output channel?

It should also crash on its own in three RA repo.

**Comment by edwin0cheng** [comment]
> I'm not sure how exactly I've made it crash -- are you getting no errors in the RA output channel?

Yes, no errors.

**Comment by lnicola** [comment]
I'm using a nightly Rust, maybe that's why?

https://user-images.githubusercontent.com/308347/102706904-a5459980-429e-11eb-9034-2cbbcad87ad0.mp4
