### ISSUE TITLE
proc macros are highlighted as functions

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#6881]
E.g. on the code in https://github.com/rust-analyzer/rust-analyzer/issues/6868#issuecomment-744461482:

![image](https://user-images.githubusercontent.com/308347/102115541-6057d800-3e44-11eb-9e66-41a14600abad.png)

`say` is `function` and `!` is `macro`.

**Comment by jonas-schievink** [comment]
This is now fixed, since name resolution has a better understanding of proc. macros now
