### ISSUE TITLE
Pattern fragment not matching if followed by |

### ISSUE THREAD

**Issue by RReverser** [rust-analyzer/rust-analyzer#6882]
Minimal example:

```rust
macro_rules! try_for_each {
    ($expr:expr, |$pat:pat| $body:block) => {{
        let mut expr = $expr;
        while let Some($pat) = expr.next()? $body
    }};
}

fn main() {
    struct S;
    impl S {
        fn next(&mut self) -> Result<Option<u32>> {
            Ok(None)
        }
    }
    try_for_each!(S, |x| {
        println!("{}", x);
    });
}
```

After the recent update to `rust-analyzer a0fa522` it started highlighting usage of `try_for_each!(...)` with an error "expected Pattern rust-analyzer macro-error", even though it's perfectly valid and compiles with Rust.

**Comment by flodiebold** [comment]
This is enough to reproduce:
```
macro_rules! try_for_each {
    ($pat:pat |) => {{ }};
}

fn main() {
    try_for_each!(x |);
}
```

**Comment by RReverser** [comment]
> This isn't really a regression; the diagnostic just didn't exist before.

Well, it accepted the code before, but now started erroring out, so from UX perspective it's a regression.
