### ISSUE TITLE
[VSCode] Feature request: allow modifyable font size for type hints

### ISSUE THREAD

**Issue by SKyletoft** [rust-analyzer/rust-analyzer#6883]
Currently type hints/annotations are in a slightly smaller size than regular text. The setting for this is seemingly fixed at 2 (?) sizes smaller than the Editor: Font Size (editor.fontSize) setting in VSC settings. This leads to the following text being slightly offset from lines above and below, as can be seen in the screenshot. Please let us detach the sizes or have an option for how different they can be.

![image](https://user-images.githubusercontent.com/45131343/102142895-69a46d00-3e63-11eb-8e26-87b0c5818f40.png)

**Comment by kjeremy** [comment]
The reason it is smaller is that it stands out more from the surrounding text to give the user the hint that it has been placed there by the editor. This is a convention in both IntelliJ and Visual Studio.

That said if you would like to change it the relevant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/39aae835fd70d06092c1be1add6eef3984439529/editors/code/src/inlay_hints.ts#L64

**Comment by SKyletoft** [comment]
But IntelliJ adds padding so that it still conforms to the spacing of the normal font, does it not?

**Comment by kjeremy** [comment]
Ahh... Maybe! PRs welcome!

**Comment by atombender** [comment]
Is there a workaround to fix the font sizes (e.g. some local CSS change I can make to VSCode) until the extension has been corrected?
