### ISSUE TITLE
[Feature Request] println postfix enhancement

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rust-analyzer/rust-analyzer#6891]
current `println` postfix , only trigger after a string literal
for example
![image](https://user-images.githubusercontent.com/17974631/102208692-aecfaa00-3f0a-11eb-94d3-a59890782375.png)
such a scenario is rarely to use.
However, we often use `println` when we want to print some `CallExpression`  and `Identifier`, 
for example:
![image](https://user-images.githubusercontent.com/17974631/102209086-3ae1d180-3f0b-11eb-9b2c-6bfffd8fbca9.png)
Thanks.

**Comment by GopherJ** [comment]
@IWANABETHATGUY it supports also format string https://rust-analyzer.github.io/manual.html#format-string-completion

**Comment by IWANABETHATGUY** [comment]
> @IWANABETHATGUY it supports also format string https://rust-analyzer.github.io/manual.html#format-string-completion, you can also use dbg postfix for structs

I know, but directly println the callExpression is also a common use case, 
like
```rust
test().println;
```
convert to 
```rust
println!("{:?}", test());
```
It's pretty convinent.
For now, you need wrap it with brace then wrap it with with quote, 
```rust
"{test()}".println
```

**Comment by lukechu10** [comment]
Is this something we want to implement or should it be closed?

**Comment by IWANABETHATGUY** [comment]
With the latest snippet completion, we could easy implement this by adding config below  to `setting.json`
```json
"rust-analyzer.completion.snippets": {
    "println!": {
      "postfix": "println",
      "body": [
        "println!(\"$0\", ${receiver});"
      ],
      "description": "println!()",
      "scope": "expr"
    }
  }
```
