### ISSUE TITLE
Provide .rpm and .deb packages in a repository 

### ISSUE THREAD

**Issue by jeschkies** [rust-analyzer/rust-analyzer#6902]
Hi,

I've noticed that the GitHub release download is very slow. It would be nice to have RedHat and Debian packages of the analyzer in a package repository.

**Comment by bjorn3** [comment]
Where would the repository be hosted? And who is going to pay for it? Also what is the benefit of a full `.rpm`/`.deb` package? The language server is just a single executable and the vscode extension can't be in a package anyway as it has to be installed through vscode itself for everyone that wants to use it.

**Comment by jeschkies** [comment]
> Also what is the benefit of a full .rpm/.deb package?

One gets all the benefits of a proper package manager such as security features and updates. It makes things easier.

> Where would the repository be hosted? And who is going to pay for it?
I was hoping there were repositories for OSS projects. However, after a quick search I actually had to find that the application process is more evolved.

**Comment by bjorn3** [comment]
Security is not very relevant for rust-analyzer. It is trivial to execute arbitrary code by adding a `build.rs` file. Regular updates are already done through both the vscode extension, which automatically downloads the corresponding language server version, and through rustup as optional component for the nightly channel.

**Comment by jeschkies** [comment]
> Security is not very relevant for rust-analyzer.
I have a hard time following that argument. How is e.g. vscode verifying the download? Is the binary signed and is the checksum compared?

> Regular updates are already done through both the vscode extension, which automatically downloads the corresponding language server version
Which is the reason I created this ticket since the download did not work from my side. The manual download worked in the end.

I understand if one says the extra effort is not worth it. However, system package managers went through all the trouble so that we don't need custom solutions.

**Comment by lnicola** [comment]
rust-analyzer is also available via rustup, but that version tends to be outdated.

**Comment by flodiebold** [comment]
In the future, the main distribution channel for rust-analyzer will be rustup. It's unlikely we'll have the capacity or expertise to maintain system packages, but distributions can of course package it, and I'd expect they will once we're out of the 'experimental' phase, just like the compiler itself.

I think it's very unlikely we'll ever do this ourselves, so I'll close this issue.
