### ISSUE TITLE
Can't infer `Impl Into<T>` types

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#6903]
```rust
fn foo(x: impl Into<i32>) {
    let x = x.into(); // no type hint here
    x.abs(); // unresolved method here
}
```

THis works with rustc though. 

@flodiebold  is this a dupe of some super-complicated issue? From the look of it, the example seems pretty obvious...

**Comment by flodiebold** [comment]
I think that's rust-lang/chalk#584.

**Comment by matklad** [comment]
indeed! dupe of https://github.com/rust-analyzer/rust-analyzer/issues/5514
