### ISSUE TITLE
Only use metadata for current target

### ISSUE THREAD

**Issue by jonhoo** [rust-analyzer/rust-analyzer#6908]
Unlike most other cargo tools, `cargo metadata` counter-intuitively defaults to including _all_ targets. This means that with the current logic, `rust-analyzer` ends up processing all targets _unless_ one a custom target is specified:
https://github.com/rust-analyzer/rust-analyzer/blob/41321d96789ed918eebda02ada76758765d19d16/crates/project_model/src/cargo_workspace.rs#L169-L171

I think `rust-analyzer` should probably _always_ specify `--filter-platform`, and just specify the host platform if `target` is not specified. Cargo finds the host platform by running `rustc -Vv` and extracing the `host:` line, which `rust-analyzer` could probably also do pretty easily:
https://github.com/rust-lang/cargo/blob/fde8ee3ba0cba4eef75f197d42586ef4664f057b/src/cargo/util/rustc.rs#L48-L68

There's also precedent for relying on `rustc` to determine these kinds of things, such as using it to find the sysroot:
https://github.com/rust-analyzer/rust-analyzer/blob/48802e54d1669c68fd27b007533dd6aa5221d089/crates/project_model/src/sysroot.rs#L126-L127

One way to make this nicer would be if `cargo metadata` supported a "special" value for `--filter-platform` called `host`. I'll look at submitting that as a PR upstream, but the more immediate fix (and also one that would continue to work for older compiler releases) would be to just use `rustc -Vv`.

**Comment by steveyko** [comment]
I am using Rust toolchain 1.37.0 due to some LLVM compatibility issues with other codebases. In that version, cargo doesn't have ```--filter-platform```. I use ```coc.nvim``` with ```rust-analyzer```, and my ```nvim``` always complains that ```cargo metadata``` wasn't expecting ```--filter-platform```. I thought I'd report this in case people here are interested in backward compatibility.

**Comment by chorman0773** [comment]
I'm going to second the backcompat issue. I'm currently using 1,38 in a program to ensure it can be built directly from mrustc and get the same issue. Maybe an opt-out would be useful?
