### ISSUE TITLE
Don't offer auto-importing completion unless at least 3 characters are already typed

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#6917]
With only two idents, we usually have a whole bunch of potential candidates, which noticeable slows down completion. 

MOre generally, I feel we might want to play with thresholds here somewhat? 

cc @SomeoneToIgnore

**Comment by matklad** [comment]
cc https://github.com/microsoft/language-server-protocol/issues/1101

**Comment by branpk** [comment]
(Consider making an exception for `Rc`)

**Comment by flodiebold** [comment]
We could probably make an exception for all exact matches?

**Comment by BlackCrowned** [comment]
This seems to be already implemented in matklad.rust-analyzer-0.2.694

See capture from vscode:
![auto_complete](https://user-images.githubusercontent.com/1255584/128599861-983142d5-e2e3-42ea-843d-3817bae650d8.gif)
