### ISSUE TITLE
VSCode: Rust-analyzer not working with Bracket Pair Colorizer 2

### ISSUE THREAD

**Issue by F0rsaken** [rust-analyzer/rust-analyzer#6923]
Having both `rust-analyzer` and `Bracket Pair Colorizer 2` installed in VSCode, disables `Bracket Colorizer` in Rust files.

With both enabled:
![image](https://user-images.githubusercontent.com/21238469/102545122-18d88280-40b6-11eb-8667-30d9cb26c0c0.png)

Without `rust-analyzer`:
![image](https://user-images.githubusercontent.com/21238469/102545172-30b00680-40b6-11eb-98b2-1f6eef8f8e5f.png)

Link to the extension:
https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2

**Comment by bjorn3** [comment]
I also use that kind of extension. I think the same extension as you, but I can't check right now. It works fine for me.

**Comment by F0rsaken** [comment]
There is [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) and [Bracket Pair Colorizer 2](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2).

Turns out, v1 works fine :/

**Comment by bjorn3** [comment]
Turns out I am using "Rainbow Brackets" (2gua.rainbow-brackets)

**Comment by bryangingechen** [comment]
I had this issue too with Bracket Colorizer 2 and after investigating I was able to fix the underlying issue in #6885.

Bracket Colorizer 2 currently works for me with a recent nightly version of the extension, and presumably will also begin working in the marketplace version after the usual weekly release in a few hours.

**Comment by bryangingechen** [comment]
Bracket Colorizer 2 works fine for me with today's release.
