### ISSUE TITLE
Auto-importing puts import into a feature-gated import block.

### ISSUE THREAD

**Issue by jcdyer** [rust-analyzer/rust-analyzer#6925]
The following code depends on `bson = {version = "1.1", features = ["decimal128"]}`.

```rust
#[cfg(feature = "decimal128")]
use bson::decimal128::Decimal128;

use bson::{
    doc,
    Bson,
};

fn demonstrator() -> Vec<u8> {
    let js = Bson::JavaScriptCodeWithScope(JavaScriptCodeWithScope {
        code: String::from("console.log('a bug?', x);"),
        scope: doc! {"x": 42},
    });
    let doc = doc!{ "js": js };
    let mut out = Vec::new();
    doc.to_writer(&mut out);
    out
}
```
The identifier "JavaScriptCodeWithScope" can be `use`d as `bson::JavaScriptCodeWithScope`, but when I do ctrl-., and opt to perform the import, it places the import within the feature-gated import block.  In theory that could be the correct action, and I'm not sure how smart RA could be about this, but I think importing into the non-cfg-gated block is a better choice in the absence of a specific reason to choose one or the other.

**Comment by Veykril** [comment]
It certainly shouldn't merge the import into feature gated ones I feel, similar to how we prevent it from inserting imports into `pub` visible ones.

Relevant code should be here:
https://github.com/rust-analyzer/rust-analyzer/blob/37e5f19373d6e4d639d0ee1125741f7b5c5c5b1a/crates/ide_db/src/helpers/insert_use.rs#L183-L196

**Comment by SomeoneToIgnore** [comment]
To note, we don't respect the opposite operation either: adding an import from the cfg'ed code section won't place it into the corresponding section or create it.
