### ISSUE TITLE
Feature Request: Recommend disabling one of the plugins if rust-lang.rust and matklad.rust-analyzer are both active

### ISSUE THREAD

**Issue by extremegf** [rust-analyzer/rust-analyzer#6928]
On first reading this sound silly - especially for seasoned RA devs. But hear me out.

For a long time I had rust-lang.rust and matklad.rust-analyzer installed at the same time. I assumed (incorrectly) that rust-lang.rust will use rls + racer by default and if I install matklad.rust-analyzer it will switch to that instead. 

I was very wrong. While reporting a bug for RA I noticed the warning that these plugins are incompatible and cause problems.
I removed rust-lang.rust and it made a huge difference in my experiance. Many features were broken when both plugins were enabled. The whole experiance was buggy and glitchy.

I imagine that many other devs may be making the same mistake, not realizing how awful it is when both plugins are installed. Moreover they might conclude that RA itself is buggy and unusable - which is the wrong impression - after I disabled rust-lang.rust **RA works beautifly**. I got really productive.

So here's the idea. Display a popup warning -  if RA detects that rust-lang.rust is also active tell the user that this might cause problems and they should disable one of the rust plugins.

**Comment by Veykril** [comment]
Definitely not a silly idea, as this idea already came up before in #6463 😄
