### ISSUE TITLE
Imports inserted via Auto-import should inherit Cfg-Attributes

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#6939]
As mentioned in https://github.com/rust-analyzer/rust-analyzer/issues/6925#issuecomment-748097069
> 
> 
> To note, we don't respect the opposite operation either: adding an import from the cfg'ed code section won't place it into the corresponding use section or create it first.

Given something like
```rust
#[cfg(debug_assertions)]
fn foo() {
    let foo = HashMap::new();
}
```
triggering an auto-import(or a import insertion from a completion) should ideally give us an import that considers the cfg attribute like:
```rust
#[cfg(debug_assertions)]
use std::collections::HashMap;

#[cfg(debug_assertions)]
fn foo() {
    let foo = HashMap::new();
}
```
As in the import inherits the cfg attributes of the ancestor items(up to the module that will receive the import) of the import triggering node.

**Comment by matklad** [comment]
Alternatively, we might place this import into the function?
