### ISSUE TITLE
Shifted type annotations in tuple when a type macro is used

### ISSUE THREAD

**Issue by Tamschi** [rust-analyzer/rust-analyzer#6940]
I'm seeing some issues with tuples (likely only free-standing, definitely not if it's an enum variant) when one of the items is typed via macro:

![see code block below](https://i.imgur.com/qZZ3KtQ.png)

Aside from the wrong type annotations on the pattern variables, the hover annotation on `test` also just shows `(usize, usize)` as type, so it's a more general problem with tuples.

Text version:

```rust
use syn::Token;

type Shifted = (usize, Token![=>], usize);

fn main() {
    let test: Shifted = (0, Default::default(), 0);
    #[allow(clippy::match_single_binding)]
    match test {
        (_a, _b, _c) => (),
        // The previous line is shown as `(_a: usize, _b: usize, _c) => (),` in Code.
    }
}
```

- - -

Versions:
rust-analyzer: `0.3.420-nightly`
`syn = "1.0.54"` (in case it's relevant)
OS: Windows

**Comment by Tamschi** [comment]
Almost forgot: Both `Cargo: Load Out Dirs From Check` and (likely irrelevantly) `Proc Macro: Enable` are enabled in my user settings.

**Comment by flodiebold** [comment]
Yeah, I think we just don't expand type macros yet.

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/119142902-ac402600-ba4f-11eb-87b1-e41596489e00.png)


works now
