### ISSUE TITLE
Auto-import imports the wrong thing when module clashes with extern crate

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#6941]
Assuming an extern crate named `c`, the following code inserts the wrong use item:

```rust
mod c {}

c::module<|>::thing_in_crate!();
```

Results in this import:
```rust
use c::module;
```

This resolves to the module, not the crate. Instead the import should look like this:

```rust
use ::c::module;
```

**Comment by SomeoneToIgnore** [comment]
Closed via https://github.com/rust-analyzer/rust-analyzer/pull/8820
