### ISSUE TITLE
organizeImports doesn't remove unused import in vscode

### ISSUE THREAD

**Issue by zhiqiangxu** [rust-analyzer/rust-analyzer#6952]
Here's the settings.json snippet:

```
 "editor.codeActionsOnSave": {
        "source.organizeImports": true
    }
```

It's supposed to remove unused import when save, but it doesn't happen.

It works great for other languages such as golang.

**Comment by GopherJ** [comment]
dup to: https://github.com/rust-analyzer/rust-analyzer/issues/5131
