### ISSUE TITLE
Cannot build on windows: jemalloc does not support windows

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#696]
>  RUST_BACKTRACE=1 cargo check
>    Compiling jemalloc-sys v0.1.8
> error: failed to run custom build command for `jemalloc-sys v0.1.8`
> process didn't exit successfully: `C:\projects\rust-analyzer\target\debug\build\jemalloc-sys-14688d2d99717e81\build-script-build` (exit code: 101)
> --- stdout
> TARGET=x86_64-pc-windows-msvc
> HOST=x86_64-pc-windows-msvc
> NUM_JOBS=8
> OUT_DIR="C:\\projects\\rust-analyzer\\target\\debug\\build\\jemalloc-sys-ee448feb5c02c141\\out"
> BUILD_DIR="C:\\projects\\rust-analyzer\\target\\debug\\build\\jemalloc-sys-ee448feb5c02c141\\out\\build"
> SRC_DIR="C:\\Users\\kjere_000\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\jemalloc-sys-0.1.8"
> 
> --- stderr
> thread 'main' panicked at 'jemalloc does not support target: x86_64-pc-windows-msvc', C:\Users\kjere_000\.cargo\registry\src\github.com-1ecc6299db9ec823\jemalloc-sys-0.1.8\build.rs:58:13
>

**Comment by DJMcNab** [comment]
Fixed by #697? Also, should we give make cargo install-lsp use jemalloc by default (on Linux)

**Comment by matklad** [comment]
I'd rather use system allocator by default: jemalloc is a c library, so, even on linux, building it might be a hassle.

**Comment by WB-Expert5007** [comment]
Hi, So you mean, we can't install "jemalloc" package on Win 10 ???

**Comment by matklad** [comment]
Yes, as far as I know, jemalloc does not support windows.

**Comment by WB-Expert5007** [comment]
> 
Thanks for your reply.
So then Can I install "jemalloc" on Win 10 using MSYS2?
Do you have any experience in MSYS2?
Please check https://www.msys2.org/.

**Comment by matklad** [comment]
@WB-Expert5007 it seems that your questions are unrelated to rust-analyzer per-se. I don't know what would be the right place to ask about jemalloc.
