### ISSUE TITLE
Rename on variable use in macro! call doesn't do anything

### ISSUE THREAD

**Issue by stanciuadrian** [rust-analyzer/rust-analyzer#6976]
I'm trying to rename a variable. 

If I try to rename the place a variable is used/referenced, then nothing happens:

![image](https://user-images.githubusercontent.com/2334569/102781327-2d5f9800-43a0-11eb-8f44-82caf3137c62.png)

If I try to rename the variable binding, it works:

![image](https://user-images.githubusercontent.com/2334569/102781365-39e3f080-43a0-11eb-88fb-e17387edd9cb.png)

Renaming `a` in the binding of `b` works fine:

![image](https://user-images.githubusercontent.com/2334569/102781896-166d7580-43a1-11eb-9cc9-a3688bdf41b1.png)

The `textDocument/prepare` response is received but there is no `textDocument/rename` request after it.

**Comment by lnicola** [comment]
```rust
fn main() {
    let ab = 4;
    println!("{}", ab);
}
```

Notice the weird range that we're returning:

```
[Trace - 16:17:04] Sending request 'textDocument/prepareRename - (203)'.
Params: {
    "textDocument": {
        "uri": "file:///home/grayshade/Projects/hello/src/main.rs"
    },
    "position": {
        "line": 2,
        "character": 20
    }
}


[Trace - 16:17:04] Received response 'textDocument/prepareRename - (203)' in 1ms.
Result: {
    "start": {
        "line": 4,
        "character": 9
    },
    "end": {
        "line": 4,
        "character": 11
    }
}
```

(lines are 0-based, 2:30 is correct)
