### ISSUE TITLE
[A-vscode] Conflict with GitLens's "Current Line Blame"

### ISSUE THREAD

**Issue by fanninpm** [rust-analyzer/rust-analyzer#6994]
Type annotations at the _end_ of a line don't behave nicely with the "Current Line Blame" from the GitLens extension.

Example of "Current Line Blame" in action:
<img width="690" alt="Screen Shot 2020-12-21 at 8 56 34 PM" src="https://user-images.githubusercontent.com/27117322/102839659-04a2c700-43cf-11eb-9380-266fa30182bb.png">

Example of feature conflict:
<img width="704" alt="Screen Shot 2020-12-21 at 8 57 10 PM" src="https://user-images.githubusercontent.com/27117322/102839701-197f5a80-43cf-11eb-8d83-2ad6e11fa22a.png">

**Comment by lnicola** [comment]
Type hints are pretty much a hack, as they are not supported natively by Code. I don't think there's anything we can do here.

Maybe we should hide the chaining hint on the line with the cursor, but I'm not sure that's much better.

**Comment by matklad** [comment]
I don’t think we can do anything specific on hour side here, let’s just wait for upstream hints.
