### ISSUE TITLE
Associated types are not resolved

### ISSUE THREAD

**Issue by junknet** [rust-analyzer/rust-analyzer#6995]
![1608625014(1)](https://user-images.githubusercontent.com/55597646/102865693-1ccb2280-4471-11eb-9950-1fcc2e2ec993.jpg)

**Comment by lnicola** [comment]
Does it work with `Progress::Message`?

**Comment by junknet** [comment]
> 
> 
> Does it work with `Progress::Message`?

No

**Comment by lnicola** [comment]
Can you show the definition of `Progress` and `Sandbox`?

**Comment by lnicola** [comment]
https://github.com/hecrj/iced/blob/master/examples/progress_bar/src/main.rs

**Comment by junknet** [comment]
Well, I used auto insert Default members.

**Comment by lnicola** [comment]
Repro:

```rust
trait Foo {
    type Bar;

    fn foo(_: Self::Bar);
}

struct S;

impl Foo for S {
    type Bar = i32;

    fn foo(_: Self::Bar) {
        todo!()
    }
}
```

![image](https://user-images.githubusercontent.com/308347/102867255-2dfc3b00-4441-11eb-860f-8c74f1c5d41c.png)

I'm actually surprised that this doesn't work.

**Comment by flodiebold** [comment]
Duplicate of #5003, I think.

**Comment by lnicola** [comment]
I thought so, but this one is simpler.

**Comment by flodiebold** [comment]
I think they are all actually working in the type system, the information just isn't surfaced.
