### ISSUE TITLE
Stop producing uncompressed release artifacts

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#6996]
The uncompressed artifacts are much larger and I suspect everyone will be happy to download them instead. After implementing uncompression support in the Code extension we left them for compatibility with users who haven't upgraded yet, but forgot to remove this.

Unfortunately, there's at least one LSP client which downloads the uncompressed binaries (GNOME Builder), so we need to coordinate with them.

Filed https://gitlab.gnome.org/GNOME/gnome-builder/-/issues/1369 specifically for GNOME Builder.

**Comment by matklad** [comment]
We can do this now.
