### ISSUE TITLE
Failed to deserialize InitializeParams: missing field `prepareSupportDefaultBehavior`

### ISSUE THREAD

**Issue by runiq** [rust-analyzer/rust-analyzer#6997]
With 5e2935e ([release 2020-12-21](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-12-21)) and neovim's builtin LSP client.

**Comment by lnicola** [comment]
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6979.

You should stay on the older release until neovim's LSP client gets updated or we work around this.

**Comment by runiq** [comment]
Ah, thanks! The different field name threw me off.
