### ISSUE TITLE
Version 2020-12-21 cannot be built in offline mode

### ISSUE THREAD

**Issue by leonardohn** [rust-analyzer/rust-analyzer#7023]
I've been maintaining _rust-analyzer_ package in my overlay for Gentoo Linux, however the compilation doesn't work since version 2020-12-21 due to a Git-related dependency named _lsp-types_. Gentoo has a strict policy to build packages on a sandbox which remains disconnected from internet during the build phase, so `--offline` flag is necessary; Another limitation is that no packages can be downloaded from third party repositories except from [crates.io](crates.io). Here is the detailed log:

```
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for dependency `lsp-types`

Caused by:
  Unable to update https://github.com/matklad/lsp-types/?branch=code151#87219c33

Caused by:
  can't checkout from 'https://github.com/matklad/lsp-types/': you are in the offline mode (--offline)
```

Are there any plans to return to the old configuration?

**Comment by jonas-schievink** [comment]
This will be fixed in the next release, but note that this is not an officially supported configuration.
