### ISSUE TITLE
.arc / .rc / .pin, similar to .box?

### ISSUE THREAD

**Issue by fasterthanlime** [rust-analyzer/rust-analyzer#7033]
I find myself writing `Arc::new(expr)`, `Rc::new(expr)` or `Box::pin(expr)` quite often - I'd love to write `expr.arc` then Ctrl-Space to get rust-analyzer to insert those for me.

It could even *gasp* auto-import Arc/Rc in those cases?

**Comment by Maan2003** [comment]
I demand Rc<RefCell<\_>>> and Arc<Mutex<\_>> then :smile:

**Comment by lnicola** [comment]
CC https://github.com/rust-analyzer/rust-analyzer/issues/1431

**Comment by Veykril** [comment]
With https://github.com/rust-analyzer/rust-analyzer/pull/10458 merged, starting tomorrow(on nightly) or next week(on stable) this can be done by adding:
```json
        "Arc::new": {
            "postfix": "arc",
            "body": [
                "Arc::new(${receiver})",
            ],
            "requires": "std::sync::Arc",
            "scope": "expr",
        },
        "Rc::new": {
            "postfix": "rc",
            "body": [
                "Rc::new(${receiver})",
            ],
            "requires": "std::rc::Rc",
            "scope": "expr",
        },
        "Box::pin": {
            "postfix": "boxpin",
            "body": [
                "Box::pin(${receiver})",
            ],
            "requires": "std::boxed::Box", // Technically not really needed due to the prelude
            "scope": "expr",
        },
```
to your `rust-analyzer.completion.snippets` settings.

**Comment by SomeoneToIgnore** [comment]
I wonder, would it make sense to add some defaults (similar to the json above) into package.json at least?

People who find them annoying, can override the settings.
