### ISSUE TITLE
Implement missing members for trait impl and fill match arms adds $0

### ISSUE THREAD

**Issue by veber-alex** [rust-analyzer/rust-analyzer#7037]
Steps to reproduce:
1. `impl Iterator for Foo {}` 
2. Try to apply "Implement missing members"

```rust
struct Foo;

impl Iterator for Foo {
    $0type Item;

    fn next(&mut self) -> Option<Self::Item> {
        todo!()
    }
}
```

RA version: 0.3.428-nightly

**Comment by bjorn3** [comment]
Which editor are you using? $0 should be interpreted as I think the new position of the cursor.

**Comment by veber-alex** [comment]
> Which editor are you using? $0 should be interpreted as I think the new position of the cursor.

VSCode 1.52.1

**Comment by veber-alex** [comment]
Similar thing also with "Fill match arms"
```rust
let x = Some(10);
match x {
    Some(${0:_}) => {}
    None => {}
}
```

**Comment by GopherJ** [comment]
I also had this issue in neovim + coc-rust-analyzer

**Comment by Veykril** [comment]
This seems to happen with all assists that put cursor positions, but only with assists, cursor setting completions work fine still.

**Comment by nmraz** [comment]
I also just hit this with today's release (2020-12-28) on VSCode 1.52.1.  Reverting to the previous version of the extension fixes the issue, so it feels like at least something must have regressed on the RA side.

**Comment by JosephTLyons** [comment]
> I also just hit this with today's release (2020-12-28) on VSCode 1.52.1. Reverting to the previous version of the extension fixes the issue, so it feels like at least something must have regressed on the RA side.

I think this is what I experienced.  Last night, it was working correctly.  It only broke after I downloaded the newest RA.

**Comment by Veykril** [comment]
I believe the problematic change is this one https://github.com/rust-analyzer/rust-analyzer/commit/23ed33a3a6b92064ae711bac305ac163f1fda4f5#diff-9d0d5bb068560b621fd1e980e53c9edaaf9966629337a02732fb4724ce1b108e
