### ISSUE TITLE
false positive diagnostic

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rust-analyzer/rust-analyzer#7041]
https://user-images.githubusercontent.com/17974631/103144790-66b25200-476a-11eb-9568-c010a2bc2ac7.mp4
i wrote a proc-macro to add two field to  struct, rustc compile successfully , but rust-analyzer report a diagnostic "no such field"

**Comment by bjorn3** [comment]
Proc macro attributes are not yet expanded.

**Comment by lnicola** [comment]
Closing as duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/6029.
