### ISSUE TITLE
Lifetime elision error not displayed

### ISSUE THREAD

**Issue by branpk** [rust-analyzer/rust-analyzer#7053]
```rust
fn foo(a: &i32, b: &i32) -> &i32 {}

fn main() {}
```

rust-analyzer shows no inline errors for the above code. Manually running `cargo check` works correctly:
```
error[E0106]: missing lifetime specifier                                                 
 --> src\main.rs:1:29
  |
1 | fn foo(a: &i32, b: &i32) -> &i32 {}
  |           ----     ----     ^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but the signature does not say whether it is borrowed from `a` or `b`
help: consider introducing a named lifetime parameter
  |
1 | fn foo<'a>(a: &'a i32, b: &'a i32) -> &'a i32 {}
  |       ^^^^    ^^^^^^^     ^^^^^^^     ^^^
```
but rust-analyzer shows no inline error message.

Other check-on-save errors are shown correctly, so I don't think it's an issue with my setup.

Windows 10, VS Code, Rust 1.50.0 nightly, rust-analyzer v0.2.424

**Comment by jonas-schievink** [comment]
Please try with a nightly build of r-a

**Comment by branpk** [comment]
Thanks!

**Comment by owtotwo** [comment]
I have the same thing.

The reason I speculate is something wrong in **cargo's build cache**. (Refer: rust-lang/cargo#9971)

_Clicking `Run` button on `fn main() {}` to force rebuild_, and the lifetime error will show correctly temporarily.

But it will be hidden again when the next Check-on-Save.

Development Environment:
 - Windows 10 19044.1889
 - Visual Studio Code 1.70.2
 - rustc 1.63.0 (4b91a6ea7 2022-08-08)
 - rust-analyzer version: 0.3.1178-standalone (a670ff888 2022-08-21)
 - **And** rust-analyzer version: 0.4.1179-standalone (6711ded5c 2022-08-22)
