### ISSUE TITLE
`_` gets greedily consumed in macro pattern matching repetitions

### ISSUE THREAD

**Issue by DropDemBits** [rust-analyzer/rust-analyzer#7056]
In a repetition of a rule  (e.g. `expr`, `ident`) that can cover `_`, and matching a `_` directly, the `_` is matched by the repetition causing the `_` rule to fail and produces an `` expected leaf: `_` `` error.

`rustc` on the latest stable and nightly matches these macro invocations without any errors.

Minimal reproducible examples:

[Example 1](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f53ae9a7fb2f4674b9d6cf02d04b8b51)
```rust
macro_rules! seq1 {
    ($($a:ident)* _) => {};
}

// `_` overlaps with `$a:ident` but rustc matches it under the `_` token
seq1![a b c d _]; // expected leaf: `_`
```

[Example 2](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a9063abb5ef749c93284521f6cf73844)
```rust
macro_rules! seq2 {
    ($($a:expr => $b:ident)* _ => $c:expr) => {};
}

// `_ => ou` overlaps with `$a:expr => $b:ident` but rustc matches it under `_ => $c:expr`
seq2![a => b c => d _ => ou]; // expected leaf: `_`
```

**Comment by edwin0cheng** [comment]
Um... TIL 

However, this is not working in rustc : ('error: local ambiguity: multiple parsing options: built-in NTs ident ('a') or 1 other option.')

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0bdc4c65a67b36b541400548c7c0b6a7)

```rust
macro_rules! seq1 {
    ($($a:ident)* e) => {};
}

seq1![a b c d e];
```

So underscore `_` is special cased ? sadface
