### ISSUE TITLE
Custom derives don't show up in import completions (thiserror::Error)

### ISSUE THREAD

**Issue by Silentdoer** [rust-analyzer/rust-analyzer#7072]
like title

**Comment by bjorn3** [comment]
Did you enable proc-macro support?

```jsonc
{
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
}
```

**Comment by Silentdoer** [comment]
> Did you enable proc-macro support?
> 
> ```jsonc
> {
>     "rust-analyzer.cargo.loadOutDirsFromCheck": true,
>     "rust-analyzer.procMacro.enable": true,
> }
> ```

I have write these config, but can not infer also, need more config or component?

**Comment by lnicola** [comment]
Can you show a code sample?

**Comment by lnicola** [comment]
This seems to work for me:

![image](https://user-images.githubusercontent.com/308347/103273152-4cc17b00-49c7-11eb-94a6-f6da841d657f.png)

```rust
use std::io;

use thiserror::Error;

#[derive(Error, Debug)]
pub enum DataStoreError {
    #[error("data store disconnected")]
    Disconnect(#[from] io::Error),
    #[error("the data for key `{0}` is not available")]
    Redaction(String),
    #[error("invalid header (expected {expected:?}, found {found:?})")]
    InvalidHeader { expected: String, found: String },
    #[error("unknown data store error")]
    Unknown,
}

fn foo() -> Result<(), DataStoreError> {
    Err(DataStoreError::Unknown)
}

fn main() {
    let _x = foo().unwrap_err();
}
```

**Comment by Silentdoer** [comment]
![IMG_20201229_171935](https://user-images.githubusercontent.com/30740234/103274000-9461fa00-49fb-11eb-9539-fbd3ebdf7b86.jpg)

**Comment by lnicola** [comment]
Got it. I think we don't return derive macros in autocompletion results for imports.

**Comment by Silentdoer** [comment]
![IMG_20201229_173747__01](https://user-images.githubusercontent.com/30740234/103274668-2c141800-49fd-11eb-9688-2e83e3e9c357.jpg)

**Comment by Silentdoer** [comment]
like this:
![image](https://img2020.cnblogs.com/blog/784440/202012/784440-20201229174259664-1277916520.jpg)

**Comment by Silentdoer** [comment]
like this:
https://github.com/Silentdoer/silentdoer/blob/master/IMG_20201229_171935.jpg

**Comment by Silentdoer** [comment]
> Got it. I think we don't return derive macros in autocompletion results for imports.

OK, thank you for you attension

**Comment by lnicola** [comment]
Since you've removed the screenshots, the problem is that we don't suggest `Error` in `use thiserror::Error`.

**Comment by GopherJ** [comment]
I just had the same issue

**Comment by Veykril** [comment]
![image](https://user-images.githubusercontent.com/3757771/119985847-78bb4980-bfc3-11eb-9f6f-fabdd73fe875.png)
This seems to work now

**Comment by flodiebold** [comment]
A bit weird that we label it `Error!` though, isn't it?

**Comment by Veykril** [comment]
Hm ye, we shouldn't show the bang here I suppose
