### ISSUE TITLE
Incorrect associated type when implementing an Iterator trait

### ISSUE THREAD

**Issue by zyrikby** [rust-analyzer/rust-analyzer#7089]
It seems that there is somewhere an error in a template that produces an incorrect associated type when you use rust-analyzer to implement a trait with associated type (at least I have checked this with Iterator). For instance, when I create a structure `Simple`, and then use rust-analyzer code action to implement missing members, I obtain the following code:

```Rust
struct Simple(i32);

impl Iterator for Simple {
    $0type Item;

    fn next(&mut self) -> Option<Self::Item> {
        todo!()
    }
}
```   

You can see that there is an error in the definition of the associated type, it should be `type Item = i32;`

**Comment by Veykril** [comment]
Fixed in #7070, should be in the next stable release, or current nightly.
