### ISSUE TITLE
Provide an option to pin version

### ISSUE THREAD

**Issue by kdy1** [rust-analyzer/rust-analyzer#7093]
Currently both of stable and nightly crashes due to https://github.com/rust-analyzer/rust-analyzer/issues/6956.
I think option to pin version, just like `rust-toolchain`, will be super useful.

**Comment by bjorn3** [comment]
You can disable auto-updating of all vscode extensions. Vscode doesn't seem to have a way to disable it for just a single extension.

**Comment by Michael-F-Bryan** [comment]
@kdy1, you can also use the instructions from https://github.com/microsoft/vscode/issues/12764#issuecomment-442370545 to install a particular version of an extension.

**Comment by iitalics** [comment]
what about non-vscode users?

**Comment by bjorn3** [comment]
For them, it depends on how exactly respective editor extension gets rust-analyzer. For example getting it as rustup component is common option, in which case not updating the nightly rustc toolchain should keep the rust-analyzer version the same I think.

**Comment by lnicola** [comment]
The only two integrations we know of that download the extension automatically are Code and GNOME Builder. Only the Code extension is implemented here, and automatic updates for it are provided by Code itself, not by us (the extension never updates the LSP server).

So there's nothing we can do here.
