### ISSUE TITLE
proc_macro_derive panics, even though it compiles with cargo run

### ISSUE THREAD

**Issue by OleStrohm** [rust-analyzer/rust-analyzer#7100]
I have a proc_macro crate inside a binary crate, and the proc_macro crate has a proc_macro_derive. With coc-rust-analyzer for coc.nvim this gives the following error on the derive for struct T:
```
proc macro returned error: proc-macro panicked: called `Result::unwrap()` on an `Err` value: "failed to parse derive input: \"structT{}\""
[rust-analyzer: macro-error]
```
This is an issue with the parsing in the first line of the function in lib.rs, it seems syn can't parse the token stream.
Cargo run does not give any errors, so it should be valid, and I therefore made it panic with the token stream's debug print, and here is what rust-analyzer's invocation receives:
```
TokenStream [
    Ident {
        ident: "struct",
        span: 4294967295,
    },
    Ident {
        ident: "T",
        span: 4294967295,
    },
    Group {
        delimiter: Brace,
        stream: TokenStream [],
        span: 7,
    },
]
```
And here is what `cargo run` prints:
```
TokenStream [
  Ident {
      ident: "struct",
      span: #0 bytes(60..66),
  },
  Ident {
      ident: "T",
      span: #0 bytes(67..68),
  },
  Group {
      delimiter: Brace,
      stream: TokenStream [],
      span: #0 bytes(69..73),
  },
]
```

Here is the code that reproduces this, the toml files are standard for the given dependencies:

src/main.rs:
```
#[macro_use] extern crate min_derive;

#[derive(MinDerive)]
struct T {

}

fn main() {
    println!("Hello, world!");
}
```
min_derive/src/lib.rs:
```
#![recursion_limit = "128"]

extern crate proc_macro;
extern crate syn;
#[macro_use]
extern crate quote;

#[proc_macro_derive(MinDerive, attributes(att))]
pub fn vertex_attrib_pointers_derive(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    //    panic!("text = {:#?}", input.to_string());
    let _ast = syn::parse_derive_input(&input.to_string()).unwrap();

    (quote! {
        impl T {}
    })
    .parse()
    .unwrap()
}
```

**Comment by OleStrohm** [comment]
I just remembered I should add the version of the programs I'm using, so here goes:
rustc: 1.48.0 (stable)
cargo: 1.48.0
nvim: v0.4.4
coc.nvim: 0.0.80-7642d233d6
coc-rust-analyzer: 0.25.0 (Which is the 28-12-20 version of rust-analyzer)

**Comment by OleStrohm** [comment]
In an attempt to find the cause of this problem I pulled the latest version of rust-analyzer and pointed coc at the new executable, and the issue was gone. It seems that coc-rust-analyzer is just behind whatever commit fixed this issue.

Closing this since the issue is already fixed.

**Comment by OleStrohm** [comment]
Never mind. The debug build was just too slow to respond, so I didn't get the error until a while later. This issue still exists on the latest commit.

**Comment by edwin0cheng** [comment]
@OleStrohm  What syn crate and quote crate version you are using ?

**Comment by edwin0cheng** [comment]
Okay, I found that it is because we didn't handle well about the spacing between token in proc-macro. #7101 should fix it.

**Comment by Animeshz** [comment]
Same error, 
![image](https://user-images.githubusercontent.com/26714676/121534849-3d873480-ca1f-11eb-9239-9c370f728efd.png)

It happens when using `serde::{Serialize, Deserialize}` macros on any struct.

**Comment by bjorn3** [comment]
That is not the same error message. Can you open a new issue?

**Comment by Grimmp** [comment]
Having exactly the same error as @Animeshz.
