### ISSUE TITLE
Proc macro server crashed after add sqlx as depedency

### ISSUE THREAD

**Issue by neo-clon** [rust-analyzer/rust-analyzer#7103]
Hello guys

I have a problem in my projects with the last 3 versions of rust analyzer

Every time I add them as a sqlx dependency, it marks an error in the structures that use the derive Serialize or Deserialize macros

![image](https://user-images.githubusercontent.com/12282168/103398587-f9ecde00-4b02-11eb-8932-eece5eb4b34b.png)

![image](https://user-images.githubusercontent.com/12282168/103398603-08d39080-4b03-11eb-8eff-65f36bfd5133.png)

My dev enviroment is:
arch linux x64
NVIM: 0.4.4
rustc 1.48.0
coc.nvim version: 0.0.80-cf0e8400a4
coc-rust-analyzer 0.25.0
rust-analyzer 1d53075 (stable channel)
CocConfig:
  rust-analyzer.procMacro.enable: true
  rust-analyzer.cargo.loadOutDirsFromCheck: true

**Comment by bjorn3** [comment]
Which rustc version are you using?

**Comment by ssankko** [comment]
@bjorn3 `rustc 1.45.2 (d3fb005a3 2020-07-31)`
Should i try use newer versions?
I am stuck at 1.45 because of nasty rustc bug that drastically slows compilation time if nested async functions are used.

**Comment by ssankko** [comment]
Update to `rustc 1.49.0 (e1884a8e3 2020-12-29)` seems to fix this behavior.

**Comment by bjorn3** [comment]
Rust-analyzer only supports proc macros compiled with the latest stable version of rustc or sometimes versions a bit newer or older. Rust-analyzer depends on the specific abi between the proc-macro and rustc. This is an implementation detail and occasionally changes.

**Comment by pauldorehill** [comment]
Hello, I came across this issue while tinkering with one of my own macros. It seems the use of a `println()` in a derive macro causes it to happen:

```rust
#[proc_macro_derive(Hello)]
pub fn hello(_: proc_macro::TokenStream) -> proc_macro::TokenStream {
    println!("fail"); // This will cause the error
    proc_macro::TokenStream::new()
}
