### ISSUE TITLE
Regression: Filling match arms inserts format string as code

### ISSUE THREAD

**Issue by camden-smallwood** [rust-analyzer/rust-analyzer#7109]
On latest stable rust-analyzer (as of Dec. 31), if I use Ctrl+. in VSCode in order to fill out the match arms, the first entry includes a format string. This happens with both stable rust (1.48.0) and nightly.

Code before insertion (I-beam inside match statement braces):
```Rust
fn main() {
    match std::fs::File::open("asdf.txt") {
        
    }
}
```

Code after insertion:
```Rust
fn main() {
    match std::fs::File::open("asdf.txt") {
        Ok(${0:_}) => {}
        Err(_) => {}
    }
}
```

Expected result - There should be a binding name inserted, and it should be highlighted:
```Rust
fn main() {
    match std::fs::File::open("asdf.txt") {
        Ok(result) => {}
        Err(_) => {}
    }
}
```

**Comment by Veykril** [comment]
Already fixed in #7070, will be on next weeks stable. Otherwise you can use the current nightly builds.
