### ISSUE TITLE
Unresolved import until open mod.rs file

### ISSUE THREAD

**Issue by mrazorvin** [rust-analyzer/rust-analyzer#7142]
Hello, I can't found info/solution for this problem, if I clone and open https://github.com/dimforge/ncollide in VS code, rust-analyzer mark each import as `unresolved module` until I manually open unresolved mod.rs, then sometimes everything starts work as expected.

I tried both OSS-code + stable rust-analyzer & VS Code insider preview + rust analyzer nightly, I also tried with enabled proc macros and out dir

In Clion (JetBrains IDE) everything is working as expected. 
Also my own projects fully work with OSS + stable rust analyzer.

Stable RA version

```
rust-analyzer version: 2020-12-07 (a0fa522)
```

Stable OSS version

``` SysInfo
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-12T10:54:25.653Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.11-3-MANJARO
```

UPD: rust-analyzer-server logs shows `[ERROR rust_analyzer::main_loop] File with cargo diagnostic not found in VFS: file not found: /home/mikhailr/Projects/ncollide/src/utils/triangle.rs` for each unresolved import (but this path actually exists)

**Comment by mrazorvin** [comment]
OK, since I'm rust beginner I didn't notice that ncollide contains different Cargo.toml files in build folder. If I change content for root Cargo.toml with one from build directory, rust-analyzer could resolve all imports, and everything is working as expected. 

So I think this issue could be closed. 

P.S I still slightly confused because rust-analyzer somehow could resolve modules only after opening related files for following Cargo.toml (maybe some kind warn or info message will be helpful for such situations)

```
[workspace]
members = [ "build/ncollide2d", "build/ncollide3d" ]

[patch.crates-io]
ncollide2d = { path = "./build/ncollide2d" }
ncollide3d = { path = "./build/ncollide3d" }
```

**Comment by lnicola** [comment]
I think we have an issue tracking the detection of files outside of the project, which might help here. Let's close this.
