### ISSUE TITLE
"version ????????"

### ISSUE THREAD

**Issue by iitalics** [rust-analyzer/rust-analyzer#7143]
I recently upgraded rust-analyzer via `rustup update`, and now when i ask the command for its version `rust-analyzer --version` i get:
```
rust-analyzer ???????
```
this is unacceptable since i need to have version information in order to diagnose other problems occurring as a result of this recent upgrade.

**Comment by bjorn3** [comment]
`git rev-parse HEAD` must be giving an error when compiling rust-analyzer on the rust CI. You can get the rust-analyzer commit by getting the commit from `rustc -v` and then looking at the commit of the `src/tools/rust-analyzer` submodule on the main rust repo as of that commit `rustc -v` reports.

**Comment by jonas-schievink** [comment]
Note that the version shipped by rustup is frequently outdated, so the other issues you are seeing might already be fixed. I suggest using the version shipped through the VS Code extension instead.

**Comment by matklad** [comment]
I think we fixed our versioning awhile ago.

**Comment by lnicola** [comment]
Confirmed, this works with the `rustup` version:

    rust-analyzer fd109fb 2021-05-11 dev
