### ISSUE TITLE
Unresolved import for gdnative::api

### ISSUE THREAD

**Issue by Kreyren** [rust-analyzer/rust-analyzer#7146]
See https://github.com/RXT0147/unnamedGame/pull/1/files#diff-e1cec28f123335e7874fd650acab37adf149e0878763e6b7ad700aeb493f0102R4

![image](https://user-images.githubusercontent.com/11302521/103522457-512bdf00-4e72-11eb-9f31-58421fa2a1bd.png)

Seems like rust-analyzer misinterpreting unresolved import to me?

Rust analyzer v0.2.432
rustc 1.49.0 (e1884a8e3 2020-12-29)
cargo 1.49.0 (d00d64df9 2020-12-05)

**Comment by edwin0cheng** [comment]
Have you tried to enabled in your settings : 

```
rust-analyzer.cargo.allFeatures : true
```

**Comment by Kreyren** [comment]
@edwin0cheng Configuration is set with same result.

![image](https://user-images.githubusercontent.com/11302521/103593237-30549f80-4eed-11eb-9d2c-d90665d5e7ec.png)

FWIW the configuration of vscode is managed from https://github.com/RXT0147/RXT0147 that has the repository in question as a submodule in `projects/unnamedGame`, but i've tried to move `.vscode` to `unnamedGame` and open that directory directly with same result.

**Comment by edwin0cheng** [comment]
It is weird , without any special settings :

![Screenshot from 2021-01-05 10-53-27](https://user-images.githubusercontent.com/11014119/103601313-55283180-4f44-11eb-8259-74aa5ce371fb.png)

So any error shown in Output Panel?

**Comment by Kreyren** [comment]
Just following:

<details>
<summary>Rust Analyzer Client Output</summary>

```
INFO [1/6/2021, 1:31:40 AM]: Extension version: 0.2.441
INFO [1/6/2021, 1:31:40 AM]: Using configuration {
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    chainingHints: true,
    maxLength: null,
    parameterHints: true,
    typeHints: true
  },
  updates: { channel: 'stable', askBeforeDownload: true },
  serverPath: null,
  server: { extraEnv: null },
  trace: { server: 'off', extension: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  assist: { importMergeBehaviour: 'full', importPrefix: 'plain' },
  callInfo: { full: true },
  cargo: {
    autoreload: true,
    allFeatures: true,
    features: [],
    loadOutDirsFromCheck: false,
    noDefaultFeatures: false,
    target: null,
    noSysroot: false
  },
  checkOnSave: {
    enable: true,
    allFeatures: null,
    allTargets: true,
    command: 'check',
    noDefaultFeatures: null,
    target: null,
    extraArgs: [],
    features: null,
    overrideCommand: null
  },
  completion: {
    addCallArgumentSnippets: true,
    addCallParenthesis: true,
    postfix: { enable: true },
    autoimport: { enable: true }
  },
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [],
    warningsAsHint: [],
    warningsAsInfo: []
  },
  files: { watcher: 'client' },
  hoverActions: {
    debug: true,
    enable: true,
    gotoTypeDef: true,
    implementations: true,
    run: true,
    linksInHover: true
  },
  lens: {
    debug: true,
    enable: true,
    implementations: true,
    run: true,
    methodReferences: false
  },
  linkedProjects: [],
  lruCapacity: null,
  notifications: { cargoTomlNotFound: true },
  procMacro: { enable: false },
  runnables: { overrideCargo: null, cargoExtraArgs: [] },
  rustcSource: null,
  rustfmt: { extraArgs: [], overrideCommand: null }
}
INFO [1/6/2021, 1:31:40 AM]: PersistentState: {
  lastCheck: undefined,
  releaseId: undefined,
  serverVersion: '0.2.441'
}
INFO [1/6/2021, 1:31:40 AM]: Using server binary at /home/kreyren/.config/VSCodium/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu
```

</details>

**Comment by edwin0cheng** [comment]
Oh , have you enabled proc-macro supported ?
```
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
```

**Comment by Kreyren** [comment]
@edwin0cheng Seems to work now O.o

![image](https://user-images.githubusercontent.com/11302521/104030973-143e5000-51c4-11eb-945f-399a16f5fc13.png)

**Comment by edwin0cheng** [comment]
Great !

**Comment by Kreyren** [comment]
@edwin0cheng Can you elaborate why is procMacro important? Would like to add a note to the code about why it fixed it O.o

**Comment by edwin0cheng** [comment]
Sure!

It is not quite related to proc-macro, but to support `include!()` macro, RA needed to know where is the `OUTDIR` of that crate. This information is only possible (at least for now) by parsing from `cargo check`. 

```
"rust-analyzer.cargo.loadOutDirsFromCheck" : true
```

The flags above enabled RA to run `cargo check` command at the initialization phase. For more details , see #6448.
