### ISSUE TITLE
Operator overloading type inference Error

### ISSUE THREAD

**Issue by MATRIXKOO** [rust-analyzer/rust-analyzer#7150]
```rust
use std::ops::Add;

struct wrapper_f64{test: f64}
impl Add<usize> for wrapper_f64{
    type Output = Self;
    fn add(self , rhs : usize)-> wrapper_f64{
        wrapper_f64{test: self.test + rhs as f64}
    }
}
fn main(){
    let f64_in = wrapper_f64{test: 1.0};
    let usize_num : usize = 2;
    let res = f64_in + usize_num;

}
```
when I run those codes on
**rustc:** stable-x86_64-unknown-linux-gnu - rustc 1.49.0
**OS: window wsl**
**RA** is update-to-date
RA type inference like
![img](https://user-images.githubusercontent.com/42641719/103534786-86fcb200-4eca-11eb-87ee-cccd53b6ccf0.png)
And the real type of **res** should be **wrapper_f64**

**Comment by ruabmbua** [comment]
The code, which does type inference in expressions has a explicit path for primitive types (probably for speedup), which handles this kind of inference wrong.

If you remove the explicit handling of primitive types, this specific example resolves the type correctly.

Even if we get rid of the explicit built-in type handling, there are cases where types are resolved incorrectly for operator overloads: https://github.com/rust-analyzer/rust-analyzer/issues/5685.

This is (I think) an issue with chalk.

**Comment by flodiebold** [comment]
I'd still like to keep the built-in handling, and rather fix it so it doesn't apply in those wrong cases.

**Comment by paulrberg** [comment]
I am encountering a similar issue called by an overloaded `call` method:

```rust
multicall.call().await?;
```

`rust-analyzer` finds this error even if the code compiles fine:

<img width="774" alt="Capture d’écran 2021-01-15 à 10 41 28" src="https://user-images.githubusercontent.com/8782666/104702216-587aa480-571e-11eb-91ed-b433497a1963.png">

The defintion of the `call` function:

```rust
pub async fn call<D: Detokenize>(&self) -> Result<D, ContractError<M>> {
    ....
}
```

The catch is that the `Multicall` struct also implements `Middleware`:

```rust
async fn call(
    &self,
    tx: &TransactionRequest,
    block: Option<BlockNumber>,
) -> Result<Bytes, Self::Error> {
    ...
}
```

These types are from [ethers-rs](https://github.com/gakonst/ethers-rs/tree/fc4b3e4ce49f67a9d0f8155902a4e750411e1174).

**Comment by flodiebold** [comment]
That's not the same issue. Can you make a separate report please?

**Comment by paulrberg** [comment]
Oh, sorry @flodiebold. Will do.
