### ISSUE TITLE
Get return type of `hir::Function`

### ISSUE THREAD

**Issue by arnaudgolfouse** [rust-analyzer/rust-analyzer#7158]
Hello !

I am trying to use rust-analyzer as a library, mainly the `ra_ap_hir` crate.
I noticed that the structure `ra_ap_hir::Function` implement various methods to retrieve its parameters (like `assoc_fn_params`) ; however, no method exists to get the return type. Is that normal, and is there a workaround ?

Thank you !

**Comment by flodiebold** [comment]
The hir API only contains what someone needed for the IDE parts so far, so there's bound to be gaps :)

**Comment by arnaudgolfouse** [comment]
PR #7160 has been merged, so I am closing this
