### ISSUE TITLE
add dbg postfix completion

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#716]
It should turn `self.current().dbg` into `dbg!(self.curren())`.

See https://github.com/rust-analyzer/rust-analyzer/issues/525 and https://github.com/rust-analyzer/rust-analyzer/pull/582 for instructions

cc @gfreezy  :)

**Comment by DJMcNab** [comment]
Looks good - can you open a PR?

The completions include other types to allow the editor to select which suggestions to show, using its own fuzzy algorithm. I'm not sure about insta.
