### ISSUE TITLE
failed to run health check for "nvim" plugin

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#7165]
Hi, I got this after upgrading neovim

![image](https://user-images.githubusercontent.com/33961674/103634179-029c4480-4f47-11eb-9b75-ab98a4ca8e01.png)

**Comment by flodiebold** [comment]
That looks like an NVim issue? I'd suggest reporting it there.

**Comment by lnicola** [comment]
We don't have a neovim plugin.

**Comment by GopherJ** [comment]
@lnicola @flodiebold sorry... I'm silly to open an issue in bad place...
