### ISSUE TITLE
Native newline style rustfmt configuration breaks formatting on Windows

### ISSUE THREAD

**Issue by EFanZh** [rust-analyzer/rust-analyzer#7166]
Steps to reproduce:

1. Use `cargo new` to create a new project on Windows.
2. Create a `.rustfmt.toml` file with `newline_style = "Native"` inside.
3. Open project directory with Visual Studio Code with Rust Analyzer extension installed.
4. Format `src/main.rs` with Rust Analyzer.
5. Observe the document. There are extra newlines inserted between each line, like this:

   ```rust
   fn main() {

       println!("Hello, world!");

   }
   ```

   Notice the empty lines between each text line.

**Comment by Jesse-Bakker** [comment]
This is caused by #7106 not normalizing line endings
