### ISSUE TITLE
Attribute completion shoud not insert optional args

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#7167]
![Peek 2021-01-05 15-21](https://user-images.githubusercontent.com/1711539/103645962-e8c02900-4f69-11eb-9a8c-befdee5f675c.gif)

This is wrong, the user should never erase things inserted by completion, we must not insert `= ""`.

**Comment by Jesse-Bakker** [comment]
The completion could also be changed to give the user a choice, e.g.:

`deprecated ${1:= "${2:reason}"}`, where the user can hit backspace from tabstop $1 to not use the optional argument, or
`deprecated ${1|,"${2:reason}"|}, using explicit choice syntax to choose between having the argument or not

**Comment by matklad** [comment]
This is a rarely invoked completion, so I'd probably prefer just `deprecated`.

**Comment by matklad** [comment]
That is, it takes `n` times to learn each snippet tab stops, which works for frequent snippets.

**Comment by FlowerBOII** [comment]
I can work on this.
Do you know if there are other attributes that should not have the optional args ? 
Or is it only the ```deprecated``` one ?

**Comment by Veykril** [comment]
`must_use` and `should_panic` suffer from the same problem I think.

**Comment by Veykril** [comment]
Fixed in #7176

**Comment by matklad** [comment]
the same still happens for at least `inline`

**Comment by matklad** [comment]
![image](https://user-images.githubusercontent.com/1711539/104769449-606b3080-5780-11eb-8efa-253f6628dc1a.png)
