### ISSUE TITLE
with rust-analyzer extension enabled, rust code can not do folding in vscode

### ISSUE THREAD

**Issue by E834159672** [rust-analyzer/rust-analyzer#7175]
## env
 * VSCode Version:1.52.1
 * OS Version:fedora 33 kernel 5.10.4
 * rust-analyzer version: v0.2.441

##  Steps to Reproduce:

 * create new file name main.rs
 * open it with vscode
 * write code like this :
```
// #region mytest

fn test(){

}

// #endregion
```
* it can not fold the mytest region.

## Does this issue occur when all extensions are disabled?: Yes/No
No. but when enable rust-analyzer extension ,it occur.

**Comment by E834159672** [comment]
same issue in the rust-analyzer repo : [issue link](https://github.com/microsoft/vscode/issues/113879)

**Comment by Veykril** [comment]
Not sure if this counts as a dupe but I would imagine so https://github.com/rust-analyzer/rust-analyzer/issues/4217

**Comment by flodiebold** [comment]
Yeah, I'm pretty sure this is a duplicate.
