### ISSUE TITLE
No status or progress bar displayed when cargo check for load_out_dirs_from_check

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#7188]
When `load_out_dirs_from_check` is enabled , rust-analyzer will run `cargo check` internally. However, currently we don't display any information to user indicating the checking is running. For a large project (e.g. substrate) it looks like it is hang. 

And I think we face the same problem when RA fetches the meta-data from `cargo-metadata`.. ?

**Comment by lnicola** [comment]
> And I think we face the same problem when RA fetches the meta-data from cargo-metadata.. ?

That's #3300.
