### ISSUE TITLE
Implement `macro_rules` macros

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#720]
See https://github.com/rust-analyzer/rust-analyzer/pull/719 which adds a bare-bones, incomplete and buggy implementation. 

There's [a comment](https://github.com/rust-analyzer/rust-analyzer/blob/0c04e55ca23790d853986544f84fe5e53c61d3d6/crates/ra_mbe/src/lib.rs#L112-L117) explaining where to get a test suite from. It would also be cool to add a better error handling (currently we return Options everywhere, but we should use results) and the ability to match non-terminals like `$e:expr` (this is tricky, I think for starters we should just use string parsing for this, and adapt parser to token trees later). 

I would also love to point out [this comment](https://github.com/rust-analyzer/rust-analyzer/blob/0c04e55ca23790d853986544f84fe5e53c61d3d6/crates/ra_mbe/src/mbe_expander.rs#L19-L63) which explains one of the most interesting bits of the expansion process!

The relevant IntelliJ Rust code is here:

https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt

The relevant rustc code is here:

https://github.com/rust-lang/rust/tree/63505b84a6fb0fdb6a2f2a2a884556aeca2326d4/src/libsyntax/ext/tt

**Comment by csmoe** [comment]
interesting issue, I'll work on this.

**Comment by detrumi** [comment]
Assuming this isn't being worked on at the moment, I'll take a stab at it.

And errors seem way better than guessing where the unwrap panic came from. I'm already wondering how you ever got it to work without it :smile:

Aside from the error handling, I'll start with expressions. I also noticed that whitespace differences can be a problem for some of the `intellij-rust` test cases, haven't looked at that yet.

**Comment by TheSirC** [comment]
Isn't that issue be resolved?

**Comment by matklad** [comment]
@TheSirC we have a better error handling now, yeah, but the overall handling of macro by example is super-incomplete! 

This is something that we'll need pretty soon, so I'll try to split this up into more issues and in general specify more precisely what do we need here. That said, I am not too familiar with this part of the Rust language, so if anyone want to "lead" macros by example, that would be awesome!

**Comment by matklad** [comment]
actually, now support covers a pretty large chunk of real-world macros, thanks to the awesome work by @edwin0cheng , so this can be closed!
