### ISSUE TITLE
Failure to find ndarray s! macro

### ISSUE THREAD

**Issue by nitsky** [rust-analyzer/rust-analyzer#7204]
RA reports the error "Fail to find macro definition rust-analyzer (macro-error)" when I attempt to use the [`s!` macro](https://docs.rs/ndarray/0.14.0/ndarray/macro.s.html) from the [`ndarray` crate](https://docs.rs/ndarray). Other macros from this crate and other crates work fine.

## Steps to reproduce

Create a new crate, add `ndarray` as a dependency, add the statement `ndarray::s![..];` to a function in `lib.rs` and observe the error. Add the statement `ndarray::array[1];` and observe it works fine.

**Comment by edwin0cheng** [comment]
Minimal reproducible example :

```rust
macro_rules! s(
    ($crate) => {};
    () => {0};
);

fn main() {
    let _a = s!();       // <-  Fail to find macro definition
}
```

**Comment by nitsky** [comment]
Thank you @edwin0cheng for the fix! :+1:
