### ISSUE TITLE
Extract module is broken on windows

### ISSUE THREAD

**Issue by CGMossa** [rust-analyzer/rust-analyzer#7208]
I hesitate to put this issue out, but I'm sure it is not just me that caused this:
I'm on Windows 10, vscode (latest version), and also latest version of rust-analyzer.
I'm writing a module in a `main.rs`-file, and I wanted to `Ctrl+.` and then extract module to file.
However, I get this error message:

```
cannot open file:///c%3A/Users/tpb398/Documents/GitHub/todo-cli/src/todo.rs.
Detail: Unable to read file 'c:\Users\tpb398\Documents\GitHub\todo-cli\src\todo.rs' 
(Error: Unable to resolve non-existing file 'c:\Users\tpb398\Documents\GitHub\todo-cli\src\todo.rs')
```

Note, this file `todo.rs` doesn't exist, but isn't it supposed to be created here?
Maybe it is a windows thing and the `c%3A` is the problem.

**Comment by yoshuawuyts** [comment]
Can confirm this also happens on my Windows machine:

```text
cannot open file:///c%3A/Users/yoshu/Code/prisma-engines/libs/user-facing-errors/src/user_facing_error.rs.
Detail: Unable to read file 'c:\Users\yoshu\Code\prisma-engines\libs\user-facing-errors\src\user_facing_error.rs'
(Error: Unable to resolve non-existing file 'c:\Users\yoshu\Code\prisma-engines\libs\user-facing-errors\src\user_facing_error.rs')
```

To me this seems like the filesystem fails to create the file, or perhaps opens the file with the wrong permissions, and then tries writing into it, which fails.

**Comment by Kiiyya** [comment]
I have the same issue. It's not very serious, just very inconvenient for now.

**Comment by Veykril** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/7576 fixes this, turns out we did indeed try to fill the new module with source before actually creating its file.
