### ISSUE TITLE
rustfmt config file is not picked up in vs code when the project is in a subdirectory

### ISSUE THREAD

**Issue by AlexAegis** [rust-analyzer/rust-analyzer#7227]
Consider a freshly `cargo init`-ed project with an added `.rustfmt.toml`

```sh
.
├── .rustfmt.toml
├── Cargo.toml
└── src
    └── main.rs
```

In this case the format config is picked up as usual and when formatting `main.rs` is formatted according to the configuration file.

Now consider a project where this rust project lives in a subdirectory

```sh
.
└── project
    ├── .rustfmt.toml
    ├── Cargo.toml
    ├── LICENSE
    └── src
        └── main.rs
```

In this case the configuration file is not picked up, and I have to symlink it to the root as a workaround or open it separately so that `project` is the root. I suggest calling `rustfmt` from the directory of the formatted `.rs` file instead of the project root.

**Comment by matklad** [comment]
I think we’ve fixed that at some point: https://github.com/rust-analyzer/rust-analyzer/blob/a99de65573d59d6398f472b0d42daabe9e8a5410/crates/rust-analyzer/src/handlers.rs#L959
