### ISSUE TITLE
`ifl` postfix doesn't work on expressions with type `&Option<_>`

### ISSUE THREAD

**Issue by Maan2003** [rust-analyzer/rust-analyzer#7230]

**Comment by Veykril** [comment]
The `receiver_ty` arg here needs its references stripped before being passed to the `TryEnum` constructors here: https://github.com/rust-analyzer/rust-analyzer/blob/dcbb77cb6c75db9b300abe0fe6ed4668e2ef1193/crates/completion/src/completions/postfix.rs#L42
Relevant method: https://github.com/rust-analyzer/rust-analyzer/blob/dcbb77cb6c75db9b300abe0fe6ed4668e2ef1193/crates/hir/src/code_model.rs#L1528

**Comment by Maan2003** [comment]
I will submit PR soon.
