### ISSUE TITLE
False "unresolved import" error for "use chrono_tz::Tz"

### ISSUE THREAD

**Issue by Count-Count** [rust-analyzer/rust-analyzer#7233]
I get an incorrect "unresolved import" on the `use chrono_tz::Tz;` line in
```rust
// Cargo.toml dependency: chrono-tz = "0.5"
use chrono_tz::Tz;

fn main() {
    let _tz = &Tz::Zulu;
}
```
with VS Code, latest automatically installed rust-analyzer. `cargo check` returns no errors.

**Comment by edwin0cheng** [comment]
You need to enable proc-macro support using 

```
{
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
}
```

**Comment by Count-Count** [comment]
Doh, I should have checked that, thanks. Can I just close this issue?

**Comment by lnicola** [comment]
Yes :-)
