### ISSUE TITLE
Feature request: Automatic import for trait methods

### ISSUE THREAD

**Issue by havish10** [rust-analyzer/rust-analyzer#7248]
Using IntelliJ Rust, we can type
```rs
v.iter().tu
```
and be prompted with `tuple_combinations` from the itertools crate.
![image](https://user-images.githubusercontent.com/26846302/104194811-cefe6600-53ef-11eb-9e8c-beba2efe9315.png)

With rust-analyzer, we do not get prompted with `tuple_combinations`.
![image](https://user-images.githubusercontent.com/26846302/104194836-d58cdd80-53ef-11eb-9692-3e269abdf075.png)

**Comment by hf29h8sh321** [comment]
This would be a great feature !

**Comment by bjorn3** [comment]
Rust-analyzer should already support this, but it doesn't seem to be working here for some reason.

**Comment by Veykril** [comment]
Note the completion does work if the trait is in scope, we don't seem to complete trait methods in general if the corresponding trait isn't in scope.
![image](https://user-images.githubusercontent.com/3757771/104197046-d2f8ab00-5424-11eb-82dc-ce4f89b63ca4.png)

**Comment by flodiebold** [comment]
See also #7140, @SomeoneToIgnore is working on this; I'd have assumed we already have a ticket for it, but couldn't find one.

**Comment by SomeoneToIgnore** [comment]
Yes, I have some drafts in https://github.com/SomeoneToIgnore/rust-analyzer/tree/actual-trait-fuzzy-imports and plan to wrap it up somewhere in the near future, but no exact time estimates.
