### ISSUE TITLE
Diagnostics doesn't see the `test` crate

### ISSUE THREAD

**Issue by fzzr-** [rust-analyzer/rust-analyzer#7252]
Diagnostics for benches partially broken, error:
- unresolved extern crate
- unresolved import

Steps to reproduce:
1. new crate
2. crate/benches/mybench.rs with source:
```
#![cfg(test)]
#![feature(test)]
extern crate test;                     // unresolved extern crate
use self::test::{Bencher, black_box};  // unresolved import
```

<img width="664" alt="Screenshot 2021-01-12 at 10 33 34" src="https://user-images.githubusercontent.com/888526/104283483-a2b31a00-54c1-11eb-9e78-35e0177f260f.png">

**Comment by Zageron** [comment]
Well I dug into the code, and also tried writing a test but I couldn't get it to pass or fail as I expected.
There doesn't seem to be a way to assert that there are _no_ problems with a diagnostic check, so I tried to fail something. But the result I get back is just empty. So yeah, not sure how to approach this.

```rust

#[test]
fn unresolved_extern_crate_test() {
    mark::check!(unresolved_extern_crate_test);
    check_diagnostics(
        r"
        #![cfg(test)]
        #![feature(test)]
        extern crate test;
          extern crate doesnotexist;
        //^^^^^^^^^^^^^^^^^^^^^^^^^^ unresolved extern crate
        ",
    )
}
```

```
running 2 tests
test nameres::tests::diagnostics::unresolved_extern_crate_test ... FAILED
test nameres::tests::diagnostics::unresolved_extern_crate ... ok

failures:

---- nameres::tests::diagnostics::unresolved_extern_crate_test stdout ----
thread 'nameres::tests::diagnostics::unresolved_extern_crate_test' panicked at 'assertion failed: `(left == right)`
  left: `{FileId(0): [(53..79, "unresolved extern crate")]}`,
 right: `{}`', crates\hir_def\src\test_db.rs:180:9
```

**Comment by Zageron** [comment]
#6714 same issue
