### ISSUE TITLE
Inlay hints not working for stm32 hals

### ISSUE THREAD

**Issue by seanybaggins** [rust-analyzer/rust-analyzer#7258]
rust-analyzer does not provide inlay hints when working with `stm32xx hals`. Very similar to issue #6504. Perhaps the token limit needs to be bumped again? I provide more detail for what my issue is in #6029. I think my comment may have been misplaced which is why I am opening up this issue.

**Comment by edwin0cheng** [comment]
Cannot reproduce :

rust-analyzer version: 2021-01-11 (60c501f)

![screen](https://user-images.githubusercontent.com/11014119/104376336-d3499100-555f-11eb-8676-4237fad54248.png)

Have you enabled proc-macro ?
```
    "rust-analyzer.procMacro.enable": true,    
    "rust-analyzer.cargo.loadOutDirsFromCheck": true
```

**Comment by bjorn3** [comment]
Off topic, but what plugin do you use for showing those warning and error messages inline?

**Comment by edwin0cheng** [comment]
@bjorn3 Error Lens: https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens

**Comment by bjorn3** [comment]
Thanks!

**Comment by seanybaggins** [comment]
Enabling proc macros did the trick. Thanks :)
