### ISSUE TITLE
Split out arena crate

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#7267]
I’ve recently needed a simple arena, and have found that the implementations of crates like typed-arena, vec-arena, id-arena, slab, compact-arena and trove are all more complex than the simple `Vec<T>` in rust-analyzer’s arena. Although this complexity provides more features, these features are not ones that I need. Is splitting out the arena crate into a separate repository and crates.io package something that you would consider?

**Comment by lnicola** [comment]
I think we could, but there's not much code in the anyway.

I should probably take a look at the other crates that you mentioned, now I'm curious what they do differently

**Comment by arzg** [comment]
I would just write the implementation myself since it’s so simple, but I thought it might be better to split it out from here instead to avoid duplication.

**Comment by matklad** [comment]
couldn't resist another Borges pun: https://github.com/rust-analyzer/rust-analyzer/pull/7271. But I also wanted to experiment with the `/lib` dir forever.

@arzg could you send a PR which fills-out Cargo.toml metadata and provides basic docs?

**Comment by arzg** [comment]
Could someone please publish a new version of la-arena that incorporates the recent changes? I think it might be a good idea to move the crate to a separate repository to avoid changes being made without new versions being published.

Thank you for getting this done so quickly!

**Comment by matklad** [comment]
published 0.2

**Comment by lnicola** [comment]
Let's close this. The crate is published, even though the question of having a separate repository is still pending.
