### ISSUE TITLE
vscode: allow spawning r-a inside a container

### ISSUE THREAD

**Issue by bilelmoussaoui** [rust-analyzer/rust-analyzer#7303]
Currently, the vscode extension offers a setting to set the binary path of the server with `rust-analyzer.server.path` configuration. In the case of Flatpak or any container based apps workflow, running rust-analyzer on the host side doesn't make much sense as the dependencies are often not available outside the container (this is especially the case when working with crates that are mostly bindings of a C/C++ library)

In order to spawn rust-analayzer in the current Flatpak container of a specific project, the command to run depends on the manifest used to setup the container itself, which makes adding such functionality to automatically detect the manifest, parse it and all not a possibility of rust-analyzer. The command looks normally +/- like this 
`flatpak build --with-appdir --allow=devel --bind-mount=/run/user/1000/doc=/run/user/1000/doc/by-app/com.belmoussaoui.Decoder.Devel --share=ipc --socket=fallback-x11 --socket=wayland --socket=pulseaudio --device=all --talk-name=org.a11y.Bus --env=RUST_LOG=decoder=debug --env=G_MESSAGES_DEBUG=none --env=GST_PLUGIN_SYSTEM_PATH=/app/lib/gstreamer-1.0 --talk-name='org.freedesktop.portal.*' --talk-name=org.a11y.Bus --env=PATH=$PATH:/usr/lib/sdk/rust-stable/bin /home/bilelmoussaoui/Projects/qrscanner/.flatpak/repo rust-analyzer`

So my idea was to have a different setting that would allow to set which VSCode command the r-a extension should use to spawn a specific command like `rust-analyzer`, extensions that wish to integrate with r-a can then use it to properly spawn r-a inside a container.

I'm interested in writing a patch if that's something you're interested in. I'm also not super happy by this approach so I'm very open to any possible alternatives

**Comment by lnicola** [comment]
I would write a shell script wrapper (though we do an self-exec trick for proc macro support).

Also if you're using Docker containers with Code, you can use the remote connection feature and install the extension in your dev container.

**Comment by bilelmoussaoui** [comment]
> I would write a shell script wrapper (though we do an self-exec trick for proc macro support, so you'd need to test that they're still working).

So your idea is to make the `flatpak-vscode` extension write a shell script somewhere and set it as a `server.path` ? 

> Also if you're using Docker containers with Code, you can use the remote connection feature and install the extension in your dev container. Can you SSH into Flatpak?

You could but I don't think you would want to run your GUI over SSH. I already tried going that road but it has it own issues and sadly VSCode offers an integration with only Docker without a way to support anything else.

**Comment by lnicola** [comment]
> So your idea is to make the flatpak-vscode extension write a shell script somewhere and set it as a server.path ?

I'm not familiar with `flatpak-vscode`, but yeah, something like that (assuming you can't write the script manually -- your `flatpak` invocation seems pretty tailored for your usecase).

> You could but I don't think you would want to run your GUI over SSH.

There's no need to: https://code.visualstudio.com/docs/remote/ssh

**Comment by bilelmoussaoui** [comment]
> I'm not familiar with `flatpak-vscode`, but yeah, something like that (assuming you can't write the script manually -- your `flatpak` invocation seems pretty tailored for your usecase).

Okay, thanks for the suggestion. I will give it a try. The thing with Flatpak is that the command depends fairly on what the application developer defined in `finish-args` which are a set of permissions the application have.

> There's no need to: https://code.visualstudio.com/docs/remote/ssh

Sure, I have had a look at this already and it fails miserably because that means the user has to configure a ton of things to make it work fine instead of just opening a project that has a Flatpak manifest on it and be able to directly build it/run it. 

Anyway, I will do some testing and report back. Thanks for the super fast answers, really appreciate it :)

**Comment by lnicola** [comment]
@bilelmoussaoui just to make sure, did you file this as a Flatpak extension developer, or as a `rust-analyzer` user working on a Rust project that needs Flatpak?

**Comment by bilelmoussaoui** [comment]
As the former actually. I have been doing a bunch of work lately to make the GNOME libraries usable from Rust and I'm doing the extra step to make Code plays fairly nicely with Rust projects that uses Flatpak

**Comment by bilelmoussaoui** [comment]
> > I'm not familiar with `flatpak-vscode`, but yeah, something like that (assuming you can't write the script manually -- your `flatpak` invocation seems pretty tailored for your usecase).
> 

Nice, it seems to work fine; so I guess this can be closed. Thanks a lot for the help here. I noticed there's a setting to override cargo/rustfmt as well 
```
  runnables: { overrideCargo: null, cargoExtraArgs: [] },
  rustfmt: { extraArgs: [], overrideCommand: null }
```
I suppose those have to be overridden as well ?

**Comment by lnicola** [comment]
I suppose so -- if your toolchain is inside Flatpak.

Also, I mentioned the proc macro server. It runs as `rust-analyzer proc-macro` (or something like that), so your wrapper script should at least forward the arguments (`$@`? I could never remember).

**Comment by bilelmoussaoui** [comment]
> I suppose so -- if your toolchain is inside Flatpak.

Perfect then :) 

> Also, I mentioned the proc macro server. It runs as `rust-analyzer proc-macro` (or something like that), so your wrapper script should at least forward the arguments (`$@`? I could never remember).

Yeah all good from that side. 

Thanks for your work on rust-analyzer btw! super awesome job :100:
