### ISSUE TITLE
Renaming "mod.rs" also renames mod and use statements

### ISSUE THREAD

**Issue by Systemcluster** [rust-analyzer/rust-analyzer#7307]
When renaming a `mod.rs` file with Visual Studio Code, corresponding `mod` and `use` statements are erroneously also renamed.

Reproduction steps:

* Create a `mod.rs`, for example `src/foo/mod.rs`
* Refer to it with `mod` or `use` statements:
  * `mod foo;` in `lib.rs` or `main.rs`
  * `use foo;` in any file
* Rename `mod.rs` in the explorer sidebar, e.g. to `mod-bar.rs`

Doing so results in references to that mod being updated:

* `mod foo;` will be changed to `mod mod-bar;`
* `use foo;` will be changed to `use mod-bar;`

**Comment by bjorn3** [comment]
This is a feature introduced by https://github.com/rust-analyzer/rust-analyzer/pull/7009.

**Comment by lnicola** [comment]
> `mod foo;` will be changed to `mod mod-bar;`

Well, that seems wrong.

**Comment by bjorn3** [comment]
Ah, I get the bug now. My bad.

**Comment by Systemcluster** [comment]
After renaming `foo/mod.rs` to `foo/mod-bar.rs`, there are no valid modules left: neither `foo` nor `foo::mod-bar` are valid modules, and `mod-bar` as it happens currently makes the least sense. The simplest course of action would be to ignore `mod.rs` renames from updating references.

**Comment by Veykril** [comment]
Yes I think there are two bugs here, first we don't check if the new name is a valid identifier and second as said just now when `mod.rs` is being renamed it renames references which just breaks references.

I'll self assign this as I'm currently working on rename-infra anyways.

**Comment by ShuiRuTian** [comment]
Hi, folks. Do we still have this behavior in master branch? I think this PR https://github.com/rust-analyzer/rust-analyzer/pull/7220 should have fixed this issue.

It does two things
1. not rename when `from file` or `to file` is "mod.rs"
2. support same level folder rename by imitate change mod.rs

But the implement is a little tricky. We need a really rename-files function to support more complicated situations.

**Comment by Veykril** [comment]
I just tested this out again and I can't seem to reproduce it anymore.
When renaming a mod.rs file it has no effect on anything thanks to #7220, renaming ordinary modules/folders to something that is not a valid identifier also seems to not update references anymore, and renaming through an lsp request to an invalid identifier returns an error now.
I'll close this, if there is something that I missed feel free to reopen.
