### ISSUE TITLE
Make sure `core` library from sysroot is handled correctly

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#731]
```rust
use std::time::Duration;

fn main() {
    Duration::<|>
}
```

The completion doesn't work in this case. Also, the tooltip says "Failed to exactly resolve the symbol".

**Comment by matklad** [comment]
most likely https://github.com/rust-analyzer/rust-analyzer/issues/523 or https://github.com/rust-analyzer/rust-analyzer/issues/231 (specifically, glob import support).

**Comment by lnicola** [comment]
I don't think glob imports are involved, but `std::time::Duration` is a re-export from `core::time`. Do you think it's #523?

**Comment by matklad** [comment]
Yep, looks like it!

**Comment by flodiebold** [comment]
Completion or resolution of associated method calls is simply not implemented yet.

**Comment by lnicola** [comment]
The associated method limitation seems pretty big, should we open an issue for it?
