### ISSUE TITLE
feature(const_trait_impl) is treated as syntax error

### ISSUE THREAD

**Issue by andre-richter** [rust-analyzer/rust-analyzer#7313]
Hi,

experimental feature `const_trait_impl` is treated as a syntax error by rust-analyzer. For example, on nightly, the following compiles, but rust-analyzer would complain about the `impl const` and even erase the const on saving.

```rust
#![allow(incomplete_features)]
#![feature(const_trait_impl)]

struct X(u32);

impl const core::ops::Add<u32> for X {
    type Output = u32;
    
    fn add(self, other: u32) -> u32 {
        self.0 + other
    }
}

fn main(){
    let y = X(2);

    println!("{}", y + 1u32);
}
```

**Comment by Veykril** [comment]
`impl const` parsing isn't implemented yet.

> and even erase the const on saving.

This shouldn't be caused by RA, at least it seems suprising to me. I wonder if this is `rustfmt` eating that up for some reason, assuming you have format on save enabled 🤔

**Comment by flodiebold** [comment]
> That seems to be a rustfmt issue

Yeah, it's reproducible on playground as well.

**Comment by andre-richter** [comment]
Ah yeah, sorry for getting that part wrong.

**Comment by andre-richter** [comment]
Raised https://github.com/rust-lang/rustfmt/issues/4650 for the rustfmt part.
