### ISSUE TITLE
Per struct counters

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#7363]
We do a good job tracking runtime performance using hprof. We should have analagous infra for tracking space. I don't think we can easily count bytes, but we can count number of instances. Here's the API I want:

```rust
struct DefMap { 
  _c: profile::Count<Self>,
  ...
}
```

The `Count` thing internally should use `TypeId / type_name` to get a key and add a count to a global hasmap. 

It should be possible to get a specific count with `get::<DefMap>`, `get_by_name("DefMap")`, and to iterate all counts. There should be a vscode command to dump all counts.

See

* https://github.com/sorbet/sorbet/blob/e19a41d7bf526102e27a85c0c0c3be060e73670a/common/Counters_impl.h
* https://github.com/sorbet/sorbet/blob/e19a41d7bf526102e27a85c0c0c3be060e73670a/common/Counters.h
* https://github.com/sorbet/sorbet/blob/e19a41d7bf526102e27a85c0c0c3be060e73670a/common/Counters.cc

**Comment by matklad** [comment]
will implement a simple version myself, as I need that right now...

**Comment by kjeremy** [comment]
As an aside that sorbet logo makes me really hungry.

**Comment by matklad** [comment]
>will implement a simple version myself, as I need that right now...

Unsurprisingly, I now know that my new advanced caching in rowan wasn't actually caching a thing. Never underestimate the power of tools
