### ISSUE TITLE
Is a Visual Studio extension planned?

### ISSUE THREAD

**Issue by deeprobin** [rust-analyzer/rust-analyzer#7369]
I do not mean Visual Studio Code but Visual Studio Community/Professional/Enterprise
(see https://github.com/rust-lang/rfcs/issues/3056)

**Comment by lnicola** [comment]
> Language Server Protocol is available in-box starting with Visual Studio 15.8 Preview 3

I think it has native support, more or less.

**Comment by lnicola** [comment]
Or maybe not? https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension?view=vs-2019

**Comment by deeprobin** [comment]
I will read up on this and develop a VSIX extension if necessary.

**Comment by flodiebold** [comment]
Yeah, "support for LSP" doesn't mean "all LSP servers work out of the box". Same as in VS Code.

I think the answer to the original question is that we only provide the VSCode extension, basically as a reference implementation and to prototype client features. All other editor support is developed by other teams.

**Comment by flodiebold** [comment]
In that vein, let's close this issue.
