### ISSUE TITLE
build.rs cache compability

### ISSUE THREAD

**Issue by davemilter** [rust-analyzer/rust-analyzer#737]
`rls` has fundamental flaw (https://github.com/rust-lang/rls/issues/753).
It has no integrated with `rustc`/`cargo`, so for example if your crate is wrapper around some
huge C/C++ library, and `build.rs` build this library from scratch `rls` will build it again.
So if your crate uses huge C/C++ library, for example skia.org , `rls` becomes resource pig,
it eats CPU it eats disk space by gigabytes, while it can just use already existing
result of running `cargo check` / `cargo build`.

Is rust-analyzer somehow address this issue, can it reuse result of running `build.rs` via `cargo build`?

**Comment by matklad** [comment]
rust-analyzer does not run `build.rs` itself. If `build.rs` does something like code-generating Rust code, you'll need to run it yourself, (by using `cargo build`). 

By-design, rust-analyzer does not care about native dependencies at all. 

So I think we are covered here? :)

**Comment by davemilter** [comment]
@matklad 

> rust-analyzer does not run build.rs itsel

This is great.

> So I think we are covered here? 

Thus, if module contains:

```Rust
include!(concat!(env!("OUT_DIR"), "/skia_c_header.rs"));
```

and this module was generated via `cargo check` / `cargo build` call,
`rust-analyzer` can find `skia_c_header.rs` in `target` directory?

For example my current `target` directory contains:

```
target/release/build/our_skia_sys-d325086a50832cbd/out/skia_c_header.rs
target/release/build/our_skia_sys-e4466b4e7eae6d94/out/skia_c_header.rs
target/arm-linux-androideabi/release/build/our_skia_sys-d5d081c93d07be27/out/skia_c_header.rs
target/arm-linux-androideabi/release/build/our_skia_sys-51c56fe5ee958917/out/skia_c_header.rs
target/arm-linux-androideabi/release/build/our_skia_sys-a271c24af5b5e654/out/skia_c_header.rs
target/arm-linux-androideabi/debug/build/our_skia_sys-61b0f62623005351/out/skia_c_header.rs
```

Can `rust-analyzer` find suitable `skia_c_header.rs` for proper handling of `include!`?

**Comment by davemilter** [comment]
`include!(concat!(env!("OUT_DIR"),` is recomded way to handle generated code in cargo book.

**Comment by matklad** [comment]
>`rust-analyzer` can find `skia_c_header.rs` in `target` directory?

It currently can't simply because we ignore `target` directory completely. We also don't handle neither of `include!`, `concat!` and `env!` macros at the moment. But there's no fundamental reason why we can't do this, it just needs implementation. `env!` would be slightly problematic in general, but, for env-vars which are set by Cargo, we should be 100% correct.

**Comment by metajack** [comment]
Is there another bug for working with generated rust code? This one was closed, but this seems like an important feature that rust-analyzer needs.

**Comment by matklad** [comment]
@metajack there are two bits for this feature:

* running `build.rs` to generate the code
* properly integrated generated code (that is, supporting `include!(concat!(env!("OUT_DIR"), "/my_file.rs"))`)

The first one is explicitly out of scope. I've created https://github.com/rust-analyzer/rust-analyzer/issues/1964 for the second one. It seems doable with moderate effort. Should we prioritize this?

**Comment by metajack** [comment]
To be clear I was concerned about the second one. Thanks for opening an issue. I'll continue discussion there.
