### ISSUE TITLE
Highlight ‘let’ in ‘if let’ as control flow

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#7385]
In my opinion, `if let` is sufficiently often referred to as a single entity that `if` and `let` should have the same colour. Then again, the `let` itself is not affecting control flow – it’s just binding the pattern.

<img width="312" alt="Screen Shot 2021-01-22 at 11 45 46 am" src="https://user-images.githubusercontent.com/31783266/105430338-5f1d9480-5ca7-11eb-966b-8d7727c70c89.png">

**Comment by arzg** [comment]
@lnicola [mentioned on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Highlighting.20of.20.60let.60.20in.20.60if.20let.60/near/255733081) that they view the `let` as doing pattern matching, but not the actual control flow, so I’m closing this issue.

**Comment by HKalbasi** [comment]
Also this is in alignment with `if-let-chain` proposal.
