### ISSUE TITLE
Can Rust Analyzer Not Handle Build.rs Generated Source Files?

### ISSUE THREAD

**Issue by zicklag** [rust-analyzer/rust-analyzer#7400]
I have a [crate](https://github.com/katharostech/LDtk-rs) that generates a Rust src file in the `build.rs` and then `include!`'s it in the lib.rs file. This works great for `cargo build`, but the rust analyzer seems to not be able to get the auto-complete for it correctly:

It gets the Project, top level type which is hard-coded into the struct:

![image](https://user-images.githubusercontent.com/25393315/105524768-bae71e00-5ca5-11eb-896b-8e88f06d73a9.png)

But it can't get any of it's fields figured out:

![image](https://user-images.githubusercontent.com/25393315/105524738-aa36a800-5ca5-11eb-926c-861e9019fd41.png)

I'm guessing that using a proc macro to generate the code instead of `include!`-ing the source file would probably fix it, and I'm going to try that out, but I wanted to make sure you guys didn't have any pointers first. Thanks!

**Comment by lnicola** [comment]
Did you enable `rust-analyzer.cargo.loadOutDirsFromCheck`?

**Comment by zicklag** [comment]
Ah, that fixed it! Thanks for the quick response. I always wondered what that setting was actually for. Would you be open to me adding some more description such as "Needed for autocomplete for some crates that generate source files in the cargo `OUT_DIR`"?

Am I right in my understanding that it would work fine if I used a proc macro? I might just do that if it helps users not having to be aware of this edge case.

**Comment by lnicola** [comment]
Proc macros are also off by default, so no. And a build script seems like the better solution here.

The plan is to enable both by default in #7328 and that will probably include cleaning up the config name and description. A PR for that would be appreciated, of course.

Let's close this in the meantime, though.

**Comment by zicklag** [comment]
Sounds great! I'll update the option description, and I'm happy that I can just use a build script for my crate. :slightly_smiling_face: Thanks again for the help!
