### ISSUE TITLE
Chokes on type with nested `impl Trait`s

### ISSUE THREAD

**Issue by davidpdrsn** [rust-analyzer/rust-analyzer#7403]
I'm using [tower](https://github.com/tower-rs/tower) and building a type consisting of several nested `impl Trait<impl Trait<impl Trait<...>>>`s. It seems at around 10 levels rust-analyzer never finishes type checking, at least its a very long time. `cargo check` on the command-line finishes very quickly however.

I've made a reproduction script here https://github.com/davidpdrsn/tower-ra-slow

I noticed that `cargo build` also takes a very long time, not sure if thats related somehow. Do you think I should file a bug for rust as well?

**Comment by detrumi** [comment]
I tried the repro, and could not reproduce the slowness. Up to 3 layers it shows the type of `_svc` instantly, adding another layer turns it into an `{unknown}`, which I'm assuming is from a type length limit.

**Comment by davidpdrsn** [comment]
How about 10?

**Comment by detrumi** [comment]
10 layers does the same thing as 4 layers: it instantly switches to `{unknown}`, and doesn't cause high cpu%

**Comment by davidpdrsn** [comment]
Maybe [coc-rust-analyzer](https://github.com/fannheyward/coc-rust-analyzer) does something funky them 🤷

**Comment by flodiebold** [comment]
You can increase the type size limit by setting the `CHALK_SOLVER_MAX_SIZE` env variable. Maybe that's necessary to reproduce it?

**Comment by davidpdrsn** [comment]
fwiw it also takes forever when you do `cargo build` so the bug might be in rustc itself?

**Comment by detrumi** [comment]
Same results with coc-rust-analyzer. Setting CHALK_SOLVER_MAX_SIZE/CHALK_OVERFLOW_DEPTH to a high value doesn't reproduce it either. So I think your editor setup just calls rustc somewhere instead?

rustc does indeed take a very long time to build, but that doesn't influence rust-analyzer.

**Comment by davidpdrsn** [comment]
> So I think your editor setup just calls cargo/rustc somewhere instead?

Could that be caused by setting this `"rust-analyzer.checkOnSave.enable": true`?

**Comment by flodiebold** [comment]
Maybe it's the `cargo clippy`?

What did you actually mean by "rust-analyzer never finishes type checking"? How does this show in the editor?

**Comment by davidpdrsn** [comment]
When I save it says `cargo check` in my status bar. Thats the one that never finished. Not quite sure what exactly runs because `cargo check` on the command line does finish 🤔 

https://user-images.githubusercontent.com/718941/106510003-9d4c5c80-64ce-11eb-90b0-ca3ad026fc60.mov

**Comment by flodiebold** [comment]
According to your configuration, it should run `cargo clippy --all-features --all-targets --target-dir /Users/david.pedersen/rust-analyzer-check`.

**Comment by davidpdrsn** [comment]
Yep that reproduces it. Guess its not an issue with RA then?

**Comment by flodiebold** [comment]
Yeah, seems like the problem might be in Clippy.

**Comment by davidpdrsn** [comment]
Cool. I'll close this and file a clippy issue. Thanks for your help 😊
