### ISSUE TITLE
For vscode pulgin , it seems only works in main.rs and lib.rs .

### ISSUE THREAD

**Issue by UnknownHp** [rust-analyzer/rust-analyzer#7407]
No auto-completition, no problem hint outside main.rs and lib.rs. 
I appreciate it if you tell me what went wrong.

**Comment by bjorn3** [comment]
Which project is this on? Are there any errors reported by the extension? (output pane and then one of the rust analyzer output streams)

**Comment by flodiebold** [comment]
Also, are the other files added to the module tree using `mod` statements? Are you getting compilation errors reported by `cargo check`?

**Comment by UnknownHp** [comment]
I didn't understanding the module concepts, and it worked after I declare the mod. Thank you all ！

> Also, are the other files added to the module tree using `mod` statements? Are you getting compilation errors reported by `cargo check`?
