### ISSUE TITLE
Support in band lifetimes

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#7416]
This happened trying to rename `'me` on https://github.com/jyn514/rust/blob/8edda7e0fb9ae313e47f9f43a07e719b9f0fe9d0/compiler/rustc_infer/src/infer/nll_relate/mod.rs#L818.

```
thread '<unnamed>' panicked at 'assertion failed: self.hl_range.range.contains_range(hl_range.range)', crates/ide/src/syntax_highlighting/highlights.rs:42:9
stack backtrace:
   0: std::panicking::begin_panic
   1: ide::syntax_highlighting::highlights::Node::add
   2: ide::syntax_highlighting::traverse
   3: ide::syntax_highlighting::highlight
   4: ide::Analysis::highlight_range
   5: rust_analyzer::handlers::handle_semantic_tokens_range
   6: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic context:
> request: textDocument/semanticTokens/range SemanticTokensRangeParams {
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            host: None,
            port: None,
            path: "/home/joshua/rustc2/compiler/rustc_infer/src/infer/combine.rs",
            query: None,
            fragment: None,
        },
    },
    range: Range {
        start: Position {
            line: 239,
            character: 0,
        },
        end: Position {
            line: 360,
            character: 66,
        },
    },
}
```

**Comment by jyn514** [comment]
>             path: "/home/joshua/rustc2/compiler/rustc_infer/src/infer/combine.rs",

Hmm, that seems wrong.

**Comment by jyn514** [comment]
Actually that might have been an early panic. The error from renaming `'me` is

```
[Error - 3:56:52 PM] Request textDocument/prepareRename failed.
  Message: No references found at position
  Code: -32603 
```

**Comment by Veykril** [comment]
Reference search fails there because those lifetimes don't have a definition place. As in they aren't listed in the impls generic param list where we currently expect them to be.
So the problem here is in band lifetimes not being supported yet for reference searching(or rather at all I imagine) as those lifetimes therefor have no definition.

**Comment by jhpratt** [comment]
In-band lifetimes appear quite likely to be removed from the compiler at this point. Something to keep an eye out for with regard to closing this issue.

**Comment by Veykril** [comment]
This feature is getting removed, so we can close this 
https://github.com/rust-lang/rust/issues/91867
