### ISSUE TITLE
Unresolved import while processing `build.rs` from dependency

### ISSUE THREAD

**Issue by saruman9** [rust-analyzer/rust-analyzer#7417]
## MWE

`Cargo.toml`:

```toml
...
[dependencies]
k8s-cri = "0.2.0" // Dependency have `build.rs`
```

`main.rs`:

```rust
use k8s_cri::v1alpha2::ContainerStatus; // Unresolved import

fn main() {
}
```

`cargo check` reports that everything is ok:

```shell
$ cargo check 2>/dev/null && echo $?
0
```

`rust-analyzer` with `rust-analyzer.cargo.loadOutDirsFromCheck` and `rust-analyzer.procMacro.enable` options enabled reports about "unresolved import" error:

```shell
$ rust-analyzer diagnostics --load-output-dirs --with-proc-macro ./
...
Diagnostic { message: "unresolved import", range: 4..38, severity: Error, fix: None, unused: false, code: Some(DiagnosticCode("unresolved-import")) }
...
```

## Versions

- Rust version: `1.49.0 (e1884a8e3 2020-12-29)` (stable).
- rust-analyzer version: 3ab8d7a.

**Comment by lnicola** [comment]
Does it work outside of build.rs?

**Comment by saruman9** [comment]
Thank you for fast response!

> Does it work outside of build.rs?

What do you mean? I use dependency crate in `main.rs`, not in `build.rs`. In `build.rs` of `k8s-cri` (dependency) used macro and `build.rs` writes code to `OUT_DIR`.

> And shouldn't that be a dev-dependency?

In my case it should be main dependency.

**Comment by lnicola** [comment]
Sorry, please ignore my question. I misread your description.

**Comment by lnicola** [comment]
Looks like we lose a letter from the output file name?

```
[INFO hir_expand::builtin_macro] include!(/home/me/Projects/hello/target/debug/build/k8s-cri-3b8ef8545172af0b/out/untime.v1alpha2.rs)
```

**Comment by lnicola** [comment]
The `k8s-cri` code does:

```rust
pub mod v1alpha2 {
    tonic::include_proto!("runtime.v1alpha2");
}

#[macro_export]
macro_rules! include_proto {
    ($package: tt) => {
        include!(concat!(env!("OUT_DIR"), concat!("/", $package, ".rs")));
    };
}
```

It's this bit here: https://github.com/rust-analyzer/rust-analyzer/blob/1cd5a6cd411a5a71db46a7904aa152123b58f30f/crates/hir_expand/src/builtin_macro.rs#L326-L341

We're try to trim the quotes from raw strings, and `runtime` gets unlucky here.

**Comment by saruman9** [comment]
Nice catch!
