### ISSUE TITLE
Non-proc macro attributes are looked up as proc macros?

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#7420]
Set `RA_LOG=hir_expand` and load the RA repo with proc macro support disabled. I see about 1000 warnings like:

```
[WARN hir_expand::db] fail on macro_parse: (reason: UnresolvedProcMacro macro_call: #[derive(Debug, PartialEq, Eq, Deserialize)]
struct TestPackageMetadata {
    some_field: bool,
    other_field: String,
}) parents: 
```

Same with `#[doc]`.

**Comment by lnicola** [comment]
Not sure if this is actually an issue, though, maybe we're just too eager to report errors.

**Comment by jonas-schievink** [comment]
That looks like it's trying to look up `Deserialize`, the `#[doc]` case seems more interesting, do you have logs of that?

**Comment by lnicola** [comment]
```
[WARN hir_expand::db] fail on macro_parse: (reason: UnresolvedProcMacro macro_call: #[doc=" The protocol compiler can output a FileDescriptorSet containing the .proto"]#[doc=" files it parses."]#[derive(Clone,PartialEq, ::prost::Message)]pubstructFileDescriptorSet{#[prost(message,repeated,tag="1")]pubfile: ::std::vec::Vec<FileDescriptorProto>,}) parents: include!("protobuf.rs");
```

Note that this happens only with `"rust-analyzer.procMacro.enable": false`.

**Comment by jonas-schievink** [comment]
That one looks like it's looking up `::prost::Message`

**Comment by lnicola** [comment]
Ugh, I missed that.

Indeed, all of these seem to be for derive macros, as expected.

**Comment by jonas-schievink** [comment]
Yeah, we should probably tone down those warnings though
