### ISSUE TITLE
Merge lens.methodReferences and lens.references settings

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#7435]
IMO these perform a similar function, and I think it would be unusual to want one but not the other. The config could be simplified by removing `lens.methodReferences` in favour of having a single `lens.references` setting that determines whether to show the references CodeLens for all items.

**Comment by vsrs** [comment]
I would prefer to keep both. Method references are heavier, and it's worth having an option to disable them, leaving data type refs, IMO.

**Comment by arzg** [comment]
Fair enough :)
