### ISSUE TITLE
cargo xtask install fails

### ISSUE THREAD

**Issue by jpremler** [rust-analyzer/rust-analyzer#7440]
Fails with
```
error: failed to read 'git/rust-analyzer/lib/README.md/Cargo.toml'

Caused by:
  Not a directory (os error 20)
```

Deleting `lib/README.md` works around the issue.

**Comment by kjeremy** [comment]
Are you on the latest stable cargo? I had the same problem when running
"cargo outdated" but bumping the cargo crate fixed the issue. I suspect you
have something outdated in your toolchain.

**Comment by jpremler** [comment]
You're right. `rustup update` solves the issue. My bad.
