### ISSUE TITLE
How to use LanguageService for custom syntax in positional proc macros?

### ISSUE THREAD

**Issue by jkelleyrtp** [rust-analyzer/rust-analyzer#7441]
I'm making a DSL for a library and would like to ship a LanguageService (+VSCode Ext) that provides highlighting/autocomplete while also allowing Rust in some positions. Something like:

```rust
html! {
<Button onclick=|click| {/* perform rust-completions here */} />
}
```

Right now, forwarding the request to the RA service doesn't provide any help because RA doesn't know how to process the proc macro. What strategy would you take to enable this sort of RA-powered assists in custom macros?

It's my first time in VScode extensions, so bear with me 🙂.

**Comment by Veykril** [comment]
I think what you are interested in is what is being proposed in this issue here, https://github.com/rust-analyzer/rust-analyzer/issues/5389 This is still an open problem.

**Comment by flodiebold** [comment]
I'm not sure what you're going for. Is this just a proc macro inside other Rust code? In that case, if the proc macro just passes through the code inside the `{}`, completions inside it should just work with rust-analyzer (as long as you enable proc-macro support). See also #7402 for some more information.
