### ISSUE TITLE
Add "Update later" button in VS Code update prompt

### ISSUE THREAD

**Issue by eugene-babichenko** [rust-analyzer/rust-analyzer#7442]
When an update is found for `rust-analyzer` server the VS Code extension suggest to download it. It is completely unclear that you should just close the notification to proceed and there should a separate "Update later" button.

![image](https://user-images.githubusercontent.com/15912853/105815088-503a2900-5faa-11eb-98f4-9a0b67de702b.png)

**Comment by bjorn3** [comment]
An "update later" button would imply that it is possible to keep running an older version, which isn't the case. There is an exact correspondence between vscode extension and rust-analyzer binary versions. Any mismatch could cause either side to crash due to changes in the interface between them.

**Comment by lnicola** [comment]
If you ignore the notification, you'll either have a mismatched server binary or no server at all. And we can't delay extension updates until the server is available, since Code updates it automatically.

I don't think there's anything we can do here specifically, so I'm inclined to close this.
