### ISSUE TITLE
if completion leaves not operator behind

### ISSUE THREAD

**Issue by pandaman64** [rust-analyzer/rust-analyzer#7448]
https://user-images.githubusercontent.com/1788628/105843316-e148e880-601a-11eb-8f3a-5630350c02ff.mp4

Sorry for posting a large video. I couldn't find a way to crop it easily😂

rust-analyzer version: 2021-01-18 (fde4a86)

**Comment by lnicola** [comment]
This one is a little ambiguous. `!if true { ... } else { ... }` can be valid (if not very useful) Rust code. On the other hand, `(!true).if` isn't handled well either (it gets turned into `if (!true)`).
