### ISSUE TITLE
Hover docs should go through hir::Document infrastructure

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#745]
So that we get proper markdown formatting.

**Comment by tomjakubowski** [comment]
I'd be interested in working on this, if this issue is still valid (it doesn't seem to've been triaged).

**Comment by kjeremy** [comment]
Go for it!

**Comment by kjeremy** [comment]
This would mean that for most things `hover` would go through the `hir` infra instead of syntax.

**Comment by matklad** [comment]
@tomjakubowski specifically, [this call](https://github.com/rust-analyzer/rust-analyzer/blob/11742e33716cd9fdce08bf5501afcb793fcc59ac/crates/ra_ide_api/src/hover.rs#L77) to `reference_definition` should be replaced by the hir-based resolve. And the `reference_definition` should be made private after that.

**Comment by tomjakubowski** [comment]
Thanks for the pointer! I've gotten as far as constructing a `SourceAnalyzer`, constructing an `hir::Path` from the `ast::NameRef`, and calling `resolve_hir_path()` on the analyzer. This gets me an `PerNs<hir::Resolution>`. Should I expect to get either (or both of) types or values from `resolve_hir_path()`? I think this function can only handle types (a let binding, say, can't really have a doc comment, can it?).

Judging by the Resolution type, I'll next need to tackle the FIXME on `doc_text_for`:

```
// FIXME: this should not really use navigation target. Rather, approximately
// resolved symbol should return a `DefId`.
pub(crate) fn doc_text_for(db: &RootDatabase, nav: NavigationTarget) -> Option<String> {
```

And have that function take either a `ModuleDef`, or maybe a `Resolution` straight up. I can then pattern match on the `ModuleDef` to get values of various types which implement `Docs`, which I'll return. Does that sound about right?

I'm also not sure how to handle the case when the analyzer returns a `Resolution` that's anything but a `Resolution::Module`.

**Comment by matklad** [comment]
>I think this function can only handle types (a let binding, say, can't really have a doc comment, can it?).

Functions can have doc comments though. 

>And have that function take either a ModuleDef, or maybe a Resolution straight up. I can then pattern match on the ModuleDef to get values of various types which implement Docs, which I'll return. Does that sound about right?

Yeah, that sounds about right! Another important point is that `docs` should just become a field on `NavigationTarget`, instead of being just a method. 

>I'm also not sure how to handle the case when the analyzer returns a Resolution that's anything but a Resolution::Def.

Just provide empty docs. In general, we don't need to be 100% precise, yet.

**Comment by tomjakubowski** [comment]
I was going to rebase my WIP branch, saw conflicts, and it looks to me like this work has already been completed! HIR-based lookup here: 
https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_ide_api/src/hover.rs#L96
