### ISSUE TITLE
Implement utf-8 offsets extension from clangd

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#7453]
https://clangd.llvm.org/extensions.html#utf-8-offsets

we should totally support this.

**Comment by matklad** [comment]
@bkchr would you be willing to submit a patch for this?

I thing you need to:

* rename `LineCol` and associated methods to `LineColUtf16`
* add `LineCol` (uft8 version) to the LineIndex
* Add `utf8_offsets: bool` capability in the `config.rs`
* change to_proto/from_proto modules to respect it.

**Comment by bkchr** [comment]
Yeah, I will try to find some time for it :) 

Actually doing it in Rust should be way faster than touch lisp :D

**Comment by kjeremy** [comment]
CC https://github.com/microsoft/language-server-protocol/issues/376

**Comment by matklad** [comment]
@bkchr did you get the chance to look into this? If not, I might look into this this weekend (but no promises :D )

**Comment by bkchr** [comment]
@matklad Not yet :( Do you have seen this https://github.com/emacs-lsp/lsp-mode/issues/2080#issuecomment-770346696 ?
