### ISSUE TITLE
"Extend selection" should be called "expand"

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#7454]
See https://rust-analyzer.github.io/manual.html#extend-selection.

In Code, the commands are called `editor.action.smartSelect.expand`, `editor.action.smartSelect.grow` and `editor.action.smartSelect.shrink`. In the UI they're called `Expand Selection` and `Shrink Selection` -- I couldn't find `grow`.

**Comment by lnicola** [comment]
This is actually a bit more complex:

 - we don't actually have an "extend selection" command, just a comment block for it?
 - "expand selection" in Code doesn't actually call "extend selection", but `textDocument/selectionRange` (`handle_selection_range` on our side)
 - "shrink selection" in Code also uses `textDocument/selectionRange` IIRC (it returns a list of nested selection ranges)

It sounds like this was a custom command that was replaced by the standard `textDocument/selectionRange`. We should remove that comment block.

**Comment by kjeremy** [comment]
Yeah originally this was specific to us but @matklad submitted got it
upstreamed in an earlier LSP version.

**Comment by matklad** [comment]
To give more context: I don't think we necessary should follow vs code terminology, I like inlay hints rather more than inline hints, the same goes to code actions vs assits or lenses vs annotations. As per our architecture invaruant, we design for a hypothetical ideal client, not VS Code. 

That being send, extend/shrink does fit better that expand/contract.
