### ISSUE TITLE
CARGO environment variable not set when `cargo check` runs through ra

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#7462]
When trying to use one of [SQLx]'es query macros (using the master branch), this error currently happens in VSCodium when ra runs `cargo check`:

[SQLx]: https://github.com/launchbadge/sqlx

```
proc macro returned error: proc-macro panicked: `CARGO` must be set
proc macro returned error: proc-macro panicked: Lazy instance has previously been poisoned
proc macro returned error: proc-macro panicked: Lazy instance has previously been poisoned
... (one poisoned error for every but the first query macro invocation)
```

The error comes from here: https://github.com/launchbadge/sqlx/blob/df393128f8b07e3b858e65446b2a508a73bf5135/sqlx-macros/src/query/mod.rs#L33

Since cargo there is only used to run `cargo metadata`, it would most likely be fine for 99% of the cases to fall back to `cargo`, but it would be nice if it just worked as-is.

**Comment by flodiebold** [comment]
It's kind of scary to me that proc macros are depending on this :confused: (Are these env variables at least documented for proc macros?)

On the other hand, why complain about this with a proc macro that also makes an actual database connection...

**Comment by jplatte** [comment]
Yes, this is documented: https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates

Of course ideally proc-macros wouldn't rely on cargo-specific things since some users might want to use a different build system. The most prominent cargo-specific thing a lot of proc-macros do is probably using [proc-macro-crate](https://crates.io/crates/proc-macro-crate), although I guess most uses of it use a fallback instead of erroring when `proc_macro_crate::crate_name` fails.
