### ISSUE TITLE
RA could not complete Angle brackets after today's update

### ISSUE THREAD

**Issue by junknet** [rust-analyzer/rust-analyzer#7495]
**env:win10+nightly**

![L08U2}7QQLK0KPTRX9%AL60](https://user-images.githubusercontent.com/55597646/106352778-c5965880-6320-11eb-91ca-fea83f2e0b2d.png)

**Comment by bjorn3** [comment]
Where should those angle brackets be completed? I don't see anything wrong.

**Comment by junknet** [comment]
> 
> 
> Where should those angle brackets be completed? I don't see anything wrong.

The completion list of yesterday's version will prompt Option<... >

**Comment by flodiebold** [comment]
It still does, when it's correct. In an expression, for example in your screenshot, completing angle brackets would be wrong, so it doesn't. Usually you'll want to write `Option::something` in that situation, and even if you wanted to give type arguments, you'd have to write them as `Option::<u32>::something`.
