### ISSUE TITLE
Implement default members mentions crate instead of self

### ISSUE THREAD

**Issue by detrumi** [rust-analyzer/rust-analyzer#7499]
When using the `Implement default members` assist, the generated code contains `crate` where it should mention `self`.

Example:
```
struct Wrapper<T>(T);

trait T {
    fn f(self) -> Wrapper<Self>
    where
        Self: Sized,
    {
        Wrapper(self)
    }
}

impl T for () {
    <|>
}
```
When triggering the assist with the cursor at `<|>`, this fills in the following:
```
    fn f(self) -> Wrapper<Self>
    where
        Self: Sized,
    {
        Wrapper(crate)
    }
```
Notice the `Wrapper(crate)`, which should be `Wrapper(self)` instead

**Comment by flodiebold** [comment]
I suspect that's the path qualification logic being a bit overeager...
