### ISSUE TITLE
tooltip for types aliases should say what the equivalent is

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#7511]
In the tooltip for a type it will say something like `pub type c_ulong`. However, it would be a lot more helpful if it said `= ...` and showed the type being aliased.

**Comment by Veykril** [comment]
Relevant code: https://github.com/rust-analyzer/rust-analyzer/blob/379b6775598659f66aa8b438cdb3d19aa322a2f4/crates/ide/src/display/short_label.rs#L62-L66
