### ISSUE TITLE
Rename ide related crates

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#7526]
We should do the following renames: 

```
assists -> ide_assists
completions -> ide_completions
ssr -> ide_ssr
```

@jonas-schievink wdyt? This'll make the structure more obvious I think.

**Comment by jonas-schievink** [comment]
Yeah, seems fine!

**Comment by 96RadhikaJadhav** [comment]
@matklad  Can I work on the issue?

**Comment by matklad** [comment]
Sure, go ahead!

**Comment by chetankhilosiya** [comment]
The renaming for assists -> ide_assists and ssr -> ide_ssr is done by this merge https://github.com/rust-analyzer/rust-analyzer/pull/7759. and completion crate is already renamed to ide_completion.
