### ISSUE TITLE
Hiding very long type annotations

### ISSUE THREAD

**Issue by arturoc** [rust-analyzer/rust-analyzer#7527]
I find that sometimes types generated from macros and similar get too long for the type annotations. For example:

![image](https://user-images.githubusercontent.com/48240/106647652-84f04680-658f-11eb-8bf6-c994cb16b5dd.png)

Rather than help they make the code less readable and since they are so long they are not immediately useful as a short type that is very easily readable would be. 

Perhaps there should be a limit of characters to show. Since you can always see the type by hovering the mouse over the declaration I think it would help uncluttering the view in certain types of code. 

If a certain type is longer than a number of characters it would be completely hidden or perhaps abbreviated to that number of characters plus ...

**Comment by Veykril** [comment]
There already is such a feature, the config is `rust-analyzer.inlayHints.maxLength`. The default value for this is unlimited(`null`). This config causes type hints to get truncated after reaching the number of characters by replacing any other nested hints with `..`.

**Comment by SomeoneToIgnore** [comment]
We also have https://github.com/rust-analyzer/rust-analyzer/issues/3138 and https://github.com/rust-analyzer/rust-analyzer/issues/4151 that cover the same issue, I think we can close this one.

**Comment by arturoc** [comment]
Thanks!
