### ISSUE TITLE
Add a separate semantic token type for character literals

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#7530]
Currently, both character literals and string literals use the `string` semantic token type. It would be nice to have the ability to differentiate between the two.

**Comment by Veykril** [comment]
We already internally handle char literals differently for highlighting, we merely need to map it differently than string literals here https://github.com/rust-analyzer/rust-analyzer/blob/85e1f0905aae762b8d64b52e76bbc6aa5915894b/crates/rust-analyzer/src/to_proto.rs#L429

**Comment by petr-tik** [comment]
hey, can you please assign this to me, i would like to take a stab at this?

**Comment by petr-tik** [comment]
looking at the semantic token types spec, it doesn't look like LSP recognises character literals. what about representing them as the number tokentype with a static modifier? 

https://microsoft.github.io/language-server-protocol/specification#textDocument_semanticTokens

**Comment by petr-tik** [comment]
i suppose I could add an additional TokenType here for a CharacterLiteral

https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/rust-analyzer/src/semantic_tokens.rs#L10-L38

**Comment by Veykril** [comment]
You want to define it here https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/rust-analyzer/src/semantic_tokens.rs#L40-L63 as you said it doesnt exist in the standard lsp spec
