### ISSUE TITLE
Support local trait impls for non-local types for unnamed free constants

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#7550]
In following code: 

```rust
trait Foo {}
struct A {}

const _ : () = {
    impl crate::Foo for crate::A {}  <---  (1)
};
```

(1) is local trait impls for non-local types. Currently we do not support it due to the fact that we do not want to look at the bodies of all functions and blocks. But is it possible to support this case solely, as an escape hatch for proc-macro author to workaround of lacking of proc-macro hygiene at the moment  ?

What do you think about it @jonas-schievink  ?

**Comment by jonas-schievink** [comment]
Yeah, I think this is a good idea!

**Comment by jonas-schievink** [comment]
If there's any `use` items in the initializer, then this might need better support for inner items first.

Then we have to stop ignoring unnamed consts here and record them as part of the containing `DefMap`, like we do for other items:

https://github.com/rust-analyzer/rust-analyzer/blob/700a3d5d75cdc1b8b7049d35af335c638e079c5c/crates/hir_def/src/nameres/collector.rs#L986

Finally, we have to change the `trait_impls_in_crate` query to inspect the body of all anonymous consts to look for blocks containing impls (this might need further changes to body lowering first):

https://github.com/rust-analyzer/rust-analyzer/blob/6bde542a39fe63298a31b838e59705797ed8a2cf/crates/ra_hir_ty/src/method_resolution.rs#L49

It is possible that there's a more optimal way of doing this though, but this should be a start.

**Comment by flodiebold** [comment]
Maybe we should even restrict it to unnamed consts of unit type?

**Comment by jonas-schievink** [comment]
We can check for a literal `()` type, ignoring type aliases and associated types. Not sure if that's worth it though, anonymous consts might be used rarely enough where it doesn't matter if we always do it.

**Comment by flodiebold** [comment]
Actually, thinking about it, I can't think of any reason to make an anonymous const with a different type, so it probably wouldn't help anyway.
