### ISSUE TITLE
No longer automatically receiving nightly updates in VS Code

### ISSUE THREAD

**Issue by DazWilkin** [rust-analyzer/rust-analyzer#7556]
Until ~recently (this year!?), I received the nightly updates each morning when restarting VS Code; this no longer appears to happen and I've resorted to deleting `${HOME}/.config/Code/User/globalStorage/matklad.rust-analyzer` most days and restarting VS Code to force the reinstall.

I'm running VS Code in a Snap on Ubutnu:

```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-62-generic snap
```
And I don't recall changing VS Code settings beside adding the comment to remind me where to delete the extension (full settings [here](https://gist.github.com/DazWilkin/dfe9b9dc4f685e0bf54e238801d7d2ef):

```JSON
// ${HOME}/.config/Code/User/globalStorage/matklad.rust-analyzer
"rust-analyzer.cargo.loadOutDirsFromCheck": true,
"rust-analyzer.diagnostics.disabled": [
    "macro-error"
],
"rust-analyzer.updates.askBeforeDownload": true,
"rust-analyzer.updates.channel": "nightly",
```

Prior to today's reinstall, the RA was [95e03ec](https://github.com/rust-analyzer/rust-analyzer/commit/95e03ec499a93af9825c5a496ec05b18e6d74cbd). It is now current [74a223f](https://github.com/rust-analyzer/rust-analyzer/commit/74a223faa33156be1b8b1a6880f9b63463027946).

I'm unclear what I've done that's broken this and would appreciate your guidance.

I find this to be a valuable tool and appreciate your hard work; I made a small financial contribution to the project.

**Comment by lnicola** [comment]
Do you have anything in the logs that might be related to the extension update?

The update happens around here: https://github.com/rust-analyzer/rust-analyzer/blob/471795b019d800dca65e2a400fbdb166e6f821cd/editors/code/src/main.ts#L160. We check for a new version of the extension, prompt the user to download it, install it, then reload the workspace.

Since you have `rust-analyzer.updates.askBeforeDownload` enabled, note that some users find the extension notifications in Code too easy to miss.

**Comment by kjeremy** [comment]
Maybe vscode version makes a difference? You need to be on at least latest
stable.

**Comment by DazWilkin** [comment]
Thanks for the replies!

I'm running `1.53.2` which is the latest version.

I had previously set `"rust-analyzer.updates.askBeforeDownload": false` but, when the downloads appeared to stop occurring, I changed this to ensure that I received the prompt; I don't.

Where would I find the logs?

In VS Code, there are `Rust Analyzer Client` logs:

```
INFO [2/20/2021, 12:01:20 PM]: Extension version: 0.3.448-nightly
INFO [2/20/2021, 12:01:20 PM]: Using configuration {
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: true,
    chainingHints: true,
    maxLength: null,
    parameterHints: true,
    typeHints: true
  },
  updates: { channel: 'nightly', askBeforeDownload: true },
  server: { path: null, extraEnv: null },
  trace: { server: 'off', extension: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  assist: { importMergeBehavior: 'full', importPrefix: 'plain' },
  callInfo: { full: true },
  cargo: {
    autoreload: true,
    allFeatures: false,
    features: [],
    loadOutDirsFromCheck: true,
    noDefaultFeatures: false,
    target: null,
    noSysroot: false
  },
  checkOnSave: {
    enable: true,
    allFeatures: null,
    allTargets: true,
    command: 'check',
    noDefaultFeatures: null,
    target: null,
    extraArgs: [],
    features: null,
    overrideCommand: null
  },
  completion: {
    addCallArgumentSnippets: true,
    addCallParenthesis: true,
    postfix: { enable: true },
    autoimport: { enable: true }
  },
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [ 'macro-error' ],
    warningsAsHint: [],
    warningsAsInfo: []
  },
  files: { watcher: 'client' },
  hoverActions: {
    debug: true,
    enable: true,
    gotoTypeDef: true,
    implementations: true,
    run: true,
    linksInHover: true
  },
  lens: {
    debug: true,
    enable: true,
    implementations: true,
    run: true,
    methodReferences: false
  },
  linkedProjects: [],
  lruCapacity: null,
  notifications: { cargoTomlNotFound: true },
  procMacro: { enable: false, server: null },
  runnables: { overrideCargo: null, cargoExtraArgs: [] },
  rustcSource: null,
  rustfmt: { extraArgs: [], overrideCommand: null }
}
INFO [2/20/2021, 12:01:20 PM]: PersistentState: {
  lastCheck: 1610388093331,
  releaseId: 36205655,
  serverVersion: '0.3.448-nightly'
}
INFO [2/20/2021, 12:01:20 PM]: Using server binary at /home/dazwilkin/.config/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu
```

The `Rust Analyzer Language Server Trace` is empty

As of now, the nightly is `20a911f` but my `Show RA Version` is `7435b93` from 2021-02-15 (the last time I deleted and let it reinstall).

**Comment by Veykril** [comment]
We had a PR https://github.com/rust-analyzer/rust-analyzer/pull/7194 that broke auto updating due to a small mistake, which got introduced on the 7th of january. I'm pretty sure that locked everyone into the nightly version they were using indefinitely until reinstalling so I feel like this seems related. Similar thing happened to the person in this issue whose nightly version is 2 days younger https://github.com/rust-analyzer/rust-analyzer/issues/7968

it is very weird though that deleting only now fixed it for you as this was fixed some weeks ago 🤔

**Comment by DazWilkin** [comment]
Thanks for the update!

It is curious as I've been manually deleting `${HOME}/.config/Code/User/globalStorage/matklad.rust-analyzer` almost every day too.

But, I noticed that the entry in the logs did not change:

```console
PersistentState: { lastCheck: 1615309621817, releaseId: 39478902, serverVersion: '0.3.448-nightly' }
```
