### ISSUE TITLE
Support `type` declarations in type inference

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#756]
We currently don't handle `type`s at all in type inference, e.g.:
```rust
struct A<X> { x: X };
type Foo = A<u32>;
type Bar<T> = A<T>;
fn test(x: Foo, y: Bar<u128>) {
    x.x;
    y.x;
}
```

**Comment by mjkillough** [comment]
It looks like rust-analyzer/rust-analyzer#892 added support for this. Is there still more to do, or should this be closed?

**Comment by flodiebold** [comment]
You're right, this can be closed.
