### ISSUE TITLE
Hovering over items with link that starts with "mod" in their doc does not show the "mod"

### ISSUE THREAD

**Issue by ChayimFriedman2** [rust-analyzer/rust-analyzer#7563]
While reviewing `std::any::Any`, I read the documentation of the struct and hovered over it. There was a link there to `[module-level documentation][mod]` (where `[mod]: crate::any`). But while I hovered over the struct to show the tooltip, I suddenly noticed that the link text is `ule-level documentation`!

So I started researching this bug. It turns out that:

 - If a link text in an item's doc comment starts with `mod`, the link is shown but strips the `mod` in the start.
 - This only happen to items that are not defined in the root module.

Example:
![image](https://user-images.githubusercontent.com/24700207/106995620-f4c92180-6787-11eb-8c7b-3417b576fa7c.png)

rust-analyzer version: 2021-02-01 (1a59f75)

I'd like to work on this issue myself.

**Comment by Veykril** [comment]
Hovering is implemented here https://github.com/rust-analyzer/rust-analyzer/blob/ac5958485e5e77b020b3ebe0c100df5a5fe6ca08/crates/ide/src/hover.rs, link rewriting in docs should happen somewhere around here https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/doc_links.rs

**Comment by ChayimFriedman2** [comment]
Thanks. Found that already, although CodeLLDB made my life harder in trying to debug the server 😉

**Comment by ChayimFriedman2** [comment]
The rewriting happens in this function:
https://github.com/rust-analyzer/rust-analyzer/blob/d7c99931d05e3723d878bea5dc26766791fa4e69/crates/ide/src/doc_links.rs#L333-L348
It sounds like a feature, so I'm not sure what to do.

This was inserted in this commit: 6bba415. Prior to that, there shall be a space or at sign (`@`) after the keyword to be stripped.

I think the best is to check what rustdoc does and follow that, as it's the "formal" consumer of doc comments.

What do you think?

**Comment by Veykril** [comment]
Fixed in #8178
