### ISSUE TITLE
Assist to remove `dbg!` calls

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#758]
For expression like `dbg!( 1 + 1)` suggest removing `dbg!()` to get `1 + 1`.

To add a new assist, you need to create a new module and add it to the `all_assists` here:

https://github.com/rust-analyzer/rust-analyzer/blob/d0fd05142f45fb69a9dc64bfd55d2453b1927b9c/crates/ra_assists/src/lib.rs#L68-L87

For assist itself, you should check if the current node is `ast::MacroCall` for `dbg!`, and suggest replacing it with argument. See, for example, this particular assist:

https://github.com/rust-analyzer/rust-analyzer/blob/d0fd05142f45fb69a9dc64bfd55d2453b1927b9c/crates/ra_assists/src/change_visibility.rs#L10-L15

see also: https://github.com/rust-analyzer/rust-analyzer/pull/728

**Comment by nakulcg** [comment]
I'd like to take this
