### ISSUE TITLE
[Feature Request] format range support

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#7580]
![image](https://user-images.githubusercontent.com/33961674/107122031-817ef700-68d0-11eb-9c94-e35fedf61907.png)

I keep getting this error messages recently. It seems RA will send `formatSelected` notification when the width of current line becomes greater than `rustfmt.toml` 's `max_width`.

And in this case coc.nvim throw out an error that RA doesn't support range formatting.

![Peek 2021-02-06 22-58](https://user-images.githubusercontent.com/33961674/107122052-8fcd1300-68d0-11eb-87b9-189fe9e0ec30.gif)

I'm wondering if it's possible to support range formatting in RA? Or shall I consider this as a coc.nvim's UX issue?

**Comment by flodiebold** [comment]
I'd consider it a UX issue or misconfiguration in coc.nvim that it tries to do this when it's not supported.

That said, in principle I think range formatting is something we should support; I'm not sure what the status of that in rustfmt is though. If it's supported by rustfmt by now, it shouldn't be too hard to implement. Otherwise it will have to wait for our own formatting infrastructure (#1665 / #4182).

**Comment by bjorn3** [comment]
Rustfmt has experimental support for range formatting on the nightly channel:

````
$ rustfmt +nightly --help=file-lines
If you want to restrict reformatting to specific sets of lines, you can
use the `--file-lines` option. Its argument is a JSON array of objects
with `file` and `range` properties, where `file` is a file name, and
`range` is an array representing a range of lines like `[7,13]`. Ranges
are 1-based and inclusive of both end points. Specifying an empty array
will result in no files being formatted. For example,

```
rustfmt --file-lines '[
    {"file":"src/lib.rs","range":[7,13]},
    {"file":"src/lib.rs","range":[21,29]},
    {"file":"src/foo.rs","range":[10,11]},
    {"file":"src/foo.rs","range":[15,15]}]'
```

would format lines `7-13` and `21-29` of `src/lib.rs`, and lines `10-11`,
and `15` of `src/foo.rs`. No other files would be formatted, even if they
are included as out of line modules from `src/lib.rs`.
````

**Comment by Jesse-Bakker** [comment]
I wonder if it would be possible to do some processing on selected syntax to make it valid rust syntax and then run it through rustfmt as if it was a file and at the end strip off the added syntax. At first glance, the processing needed would be to expand or shrink the selection to a valid `AstNode` and then wrap it in a function. For example:

```rust
let a=2;
```
With `=2` selected. First, expand the selection to `a=2`, then 
->

```rust
fn fmt_dummy_name() {
a=2
}
``` 
-> rustfmt

```rust
fn fmt_dummy_name() {
    a = 2
}
```

-> 

```rust
a = 2
```

This may be a bit hacky, but at least it works on stable :grin:
