### ISSUE TITLE
ARCHITECTURE.md does not look nice in dark mode

### ISSUE THREAD

**Issue by melodicstream** [rust-analyzer/rust-analyzer#7581]
![image](https://user-images.githubusercontent.com/14367750/107128006-1108b380-6899-11eb-9704-3a2ddee57272.png)

The lack of a background color to the text and the balloons make it so that it's really hard to read the image when using Github's dark theme.

Proposed solutions are to either add a background to the image as a whole, or to fill out the balloon and add a white outline to the text.

**Comment by tovVAar** [comment]
Created [PR](https://github.com/rust-analyzer/rust-analyzer/pull/7582) with edited image:


![50114578-e8a34280-0255-11e9-902c-7cfc70747966](https://user-images.githubusercontent.com/4789492/107129398-0ab70f00-687a-11eb-9bfc-d4eb023aec06.png)
