### ISSUE TITLE
$/progress impacting perf in vim while typing

### ISSUE THREAD

**Issue by prabirshrestha** [rust-analyzer/rust-analyzer#7590]
editor: vim
plugin: https://github.com/prabirshrestha/vim-lsp

rust-analyzer is sending too many `$/progress` notifications.

I do prefer the initial notifications when the server is starting. But once it booted and I start typing and vim-lsp sends didChangeNotification or completion notification I get bombarded with `$/progress` notification making the typing very slow and is unbearable. If I disable workdone progress `let g:lsp_work_done_progress_enabled = 0` it seems to be responsive again. Is there some way to control this?

Few things to note about vim and vimscript in general. It is a single threaded and vimscript is notoriously very slow (one of the slowest languages). This requries to json parse and run vimscript. Would it be possible to throttle/debounce this `$/progress` notification on the server instead or some way to even disable this notifications after the initial warming up notifications?

Log was to long to paste here so you can find the vim-lsp log at https://gist.github.com/prabirshrestha/93efe102437180132438a715a64dd7e9

**Comment by prabirshrestha** [comment]
Curious if there has been any update on this? This is making vim very slow and I'm currently disabling the work done progress but since rust servers take time to start up I'm getting blanked out before starting anything.

**Comment by vatosarmat** [comment]
Maybe that's because `textDocument/didChange` notifications to LS and debouncing them(which neovim builtin LSP seems to allow) could help

**Comment by krobelus** [comment]
We're facing a similar issue with Kakoune/kak-lsp
This [log excerpt](https://github.com/kak-lsp/kak-lsp/pull/545#issuecomment-963481599) shows that on startup, `rust-analyzer` sends one `$/progress` notification per *millisecond*.
We're probably gonna implement some kind of throttling.
But I think rate-limiting on the `rust-analyzer` side would also make sense. AFAICT "report" requests can be dropped without harm. Maybe we should send at most one per 50 milliseconds, I think users won't know the difference.

**Comment by lnicola** [comment]
There's been some improvements here:

 - we only prime caches on workspace load, and not while typing: #10088
 - we exclude test and example crates from priming: #10743
 - we exclude transitive dependencies: #10978
 - there is an option to disable cache priming: #10810

On rust-analyzer itself, these changes reduced the number of processed crates from about 677 to about 105, which take about 7 seconds. Most of the others were smaller ones, so the remaining reports should be more "consistent" at about 67 ms / crate. That seems reasonable enough and I don't think we need to implement any server-side progress throttling.

I'll close this now, but please post a comment if it's still too bad or you have newer measurements.

**Comment by lnicola** [comment]
@krobelus ah, right, that's the project loading phase, not the cache priming discussed in the original post. I don't know -- I personally feel these don't bring much. We should probably add an option to disable them.
