### ISSUE TITLE
Match arms with `Self::Foo(something)` are not resolved

### ISSUE THREAD

**Issue by SomeoneToIgnore** [rust-analyzer/rust-analyzer#7594]
When an enum variant has some data in it and matched with `Self::` prefix, rust-analyzer does not properly infer the corresponding match arm and does not allow such things as "go to definition":

<img width="741" alt="image" src="https://user-images.githubusercontent.com/2690773/107190828-fd259480-69f3-11eb-85b2-58f7ad12de92.png">

```rust
pub(crate) enum TestEnum {
    A,
    Unresolved(i32),
}

impl std::fmt::Display for TestEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let _resolved = Self::Unresolved(2);
        let _resolved_too = TestEnum::Unresolved(2);

        let _take_one = match self {
            Self::A => write!(f, "A"),
            // unresolved
            Self::Unresolved(_) => write!(f, "unresolved: Try go to definition on this match arm"),
        };

        let take_two = match self {
            TestEnum::A => write!(f, "A"),
            TestEnum::Unresolved(_) => write!(f, "resolved"),
        };

        take_two
    }
}
```

**Comment by lnicola** [comment]
I think this might be a dupe, but I can't find the issue I'm thinking of.

**Comment by lnicola** [comment]
https://github.com/rust-analyzer/rust-analyzer/issues/6549

**Comment by SomeoneToIgnore** [comment]
Looks very related, although in my case some of the `Self::` variants are actually resolved.

**Comment by SomeoneToIgnore** [comment]
Still happens on `rust-analyzer version: nightly (36465b3)` even after https://github.com/rust-analyzer/rust-analyzer/issues/6549 is fixed.
