### ISSUE TITLE
Easy Language Server features?

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#76]
Are there any easyish language server features (low hanging fruit) that could be implemented?

**Comment by matklad** [comment]
[Folding ranges](https://microsoft.github.io/language-server-protocol/specification#textDocument_foldingRange) should be doable.

Wanna give it a shot?

**Comment by matklad** [comment]
And I think there are a ton of code-actions which could be just implemented as well. Like, for example, a code action that filps between match arm guard and and if expr

```
match foo {
    bar if barz => {
        stuff
    }
}
```

<=>

```
match foo {
    bar => {
        if barz  { stuff } 
    }
}
```

**Comment by kjeremy** [comment]
It doesn't look like `languageserver-types` supports folding ranges yet but I can take a crack at the code actions. Is there a blueprint to follow? It looks like I should add an action into `AnalysisImpl::assists` right?

**Comment by matklad** [comment]
>It doesn't look like languageserver-types supports folding ranges yet

It might be a good idea to send a PR to languageserver-types then :) 

>Is there a blueprint to follow?

Yep, `code_actions.rs` contains several examples together with the tests:

https://github.com/matklad/rust-analyzer/blob/5901e9811636f0a5c5f73ef99ee574da83888a68/crates/ra_editor/src/code_actions.rs

I suggest to start with `move guard inside action` (the `=>` direction from the previous update). I think that to do that, you'll need to add accessor to `MatchGuard` to get an expression. That is, you need to modify `grammar.ron`, and then run `cargo gen-kinds` to update generated code.

See https://github.com/matklad/rust-analyzer/commit/23303cd0f8298c2d7b082fcb04919454c1c306ab#diff-e1e05a48de544b7b334e42793e36541d which did smth similar (note that `generated.rs` files is generaed with `cargo gen`). Sorry for not having documented this workflow properly yet: brushing up contributing md is on my todo list :)

**Comment by kjeremy** [comment]
> It might be a good idea to send a PR to languageserver-types then :)

I'm submitting PRs. Once that's done I'll work on folding ranges.

**Comment by kjeremy** [comment]
@matklad I'm working against my branch until the language-server PR is pulled in and released. I have a:

```rust
pub fn handle_folding_range(
    world: ServerWorld,
    params: TextDocumentIdentifier,
    _token: JobToken,
) -> Result<Option<Vec<FoldingRange>>> {
    let file_id = params.try_conv_with(&world)?;
    let line_index = world.analysis().file_line_index(file_id);
/// ...
}
```

I think to start I want to detect contiguous lines of comments and `use` statements. That should be simpler than dealing with start/end columns. Is there a rough outline for that?

Also: what's the easiest way to test the language server?

**Comment by matklad** [comment]
>I think to start I want to detect contiguous lines of comments and use statements.

Seems reasonable!

> Is there a rough outline for that?

Yep! [This code](https://github.com/matklad/rust-analyzer/blob/f5808b21a423235037a487d877e23deb3e602f37/crates/ra_editor/src/extend_selection.rs#L86-L96) in fact detects a contiguous run of comments.

>Also: what's the easiest way to test the language server?

For testing the code, I prefer to keep most of the tests separate from the language server. See, for example, how [extend selection](https://github.com/matklad/rust-analyzer/blob/f5808b21a423235037a487d877e23deb3e602f37/crates/ra_editor/src/extend_selection.rs) is tested. I think the same pattern should work for folding regions. 

There are full-blown server tests [here](https://github.com/matklad/rust-analyzer/blob/f5808b21a423235037a487d877e23deb3e602f37/crates/ra_lsp_server/tests/heavy_tests/main.rs), but I think they should be used only for high-level integration testing.


So, besides unit-tests, I think it's OK to just manually verify that VS Code can interoperate with the server. See instructions [here](https://github.com/matklad/rust-analyzer/tree/f5808b21a423235037a487d877e23deb3e602f37/editors) on how to actually use the language server. 


Note that there's [some logging](https://github.com/matklad/rust-analyzer/blob/f5808b21a423235037a487d877e23deb3e602f37/crates/ra_lsp_server/src/main.rs#L15) which should help with troubleshooting.

**Comment by kjeremy** [comment]
@matklad Is there an easy way to debug the traffic between client and server?

**Comment by matklad** [comment]
running with `RUST_LOG=gen_lsp_server=debug` should enable [these logs](https://github.com/matklad/rust-analyzer/blob/c2ab6ad73d2a7cd9a54dd8ee9f96dab25ec89600/crates/gen_lsp_server/src/msg.rs#L187-L192).

They can be seen in the output tab of running VSCode and in the `log` folder. 

So, `RUST_LOG=gen_lsp_server=debug code .` should be the setup.

**Comment by kjeremy** [comment]
Great. I have some terrible code that works for comments: https://gist.github.com/kjeremy/d8a551ec1eb156ae8407577a38378e0c

It's a pretty rough cut. A few questions:
1. I'm sure I'm not traversing the syntax tree correctly (as evidenced by that terrible vector check). Is there a better way to do it?

2. What belongs in ra_analysis?

**Comment by matklad** [comment]
>I'm sure I'm not traversing the syntax tree correctly (as evidenced by that terrible vector check). Is there a better way to do it?

A simple solution is perhaps to remember all processed comments in a block in a HashSet (`SyntaxNodeRef` is Copy & Hash) and `continue` based on that.

I think that using `walk::walk` directly you'll be able to implement are more "direct" solution by keeping track of the current run of comments explicitly, but that's a lot of code for small benefit. 

>What belongs in ra_analysis?

In general, it is concerned about things that span multiple files, which is not the case for this feature.

However, I choose to dupplicate ra_editor API in ra_analysis (by just forwarding it), to make it so that there's only one API for clients.

So, functionality and tests should live in ra_editor, ra_analysis should just forward that (see how it's done for extend selection). This forwarding is probably unfortunate, so, if you don't like how the current API surface look like, feel free to try to improve it :)

**Comment by DJMcNab** [comment]
Code actions could inlude switching between `use` styles as discussed in #127.

This would include the options of:
1) a single `use {}` (except for `#[cfg(...)]`
2) a single `use <crate>::{}` for each crate
3) ```rust
   use fully::qualified::path
   ```
   for each item.

The latter could use a heustic such as only a single level of `{}` is used, e.g. 
```rust
use first::second::{third, fourth, fifth::sixth}
```
would be allowed, but
```rust
use first::second::{third, fourth, fifth::{sixth, seventh}}
```
would be converted to 
```rust
use first::second::{third, fourth};
use first::second::fifth::{sixth, seventh};
```

**Comment by matklad** [comment]
@DJMcNab I'd **love** that!
