### ISSUE TITLE
VSCode extension does not recognise installed binary

### ISSUE THREAD

**Issue by coxackie** [rust-analyzer/rust-analyzer#7603]
I have system-installed the binary of rust-analyzer (Arch Linux package), but the VSCode extension does not seem to identify it is installed it and still asks to download a binary (related to the extension version). Should it not be possible to work with the installed binary? I am using the system binary with neovim lsp, and I do not see the purpose of duplicate installation.

**Comment by bjorn3** [comment]
You need to set the `rust-analyzer.serverPath` config.

**Comment by coxackie** [comment]
@bjorn3 Thanks a lot. For some reason, I could not easily find this documented. Closing.
