### ISSUE TITLE
Assist proposal: generate a as_variant() method for enum

### ISSUE THREAD

**Issue by bnjjj** [rust-analyzer/rust-analyzer#7604]
Inspired by this assist https://github.com/rust-analyzer/rust-analyzer/pull/7562 I would like add an assist to generate method `as_variant_name()` a pattern I often use to quickly extract a variant from an enum.
Example:
```rust
enum Number {
    I64(i64),
    F64(f64),
}
```

output:
```rust
enum Number {
    I64(i64),
    F64(f64),
}

impl Number {
    pub fn as_i64(&self) -> Option<&i64> {
        // ....
    }
}
```

If you think it could be useful for developers let me know I would be happy to implement this.

**Comment by Veykril** [comment]
Sounds like a good addition to me as it is closely related to the `is_` version, and pretty useful to have in general in my opinion. Reminds me that I still wish there was a `matches!` like macro in std that does exactly this 😄 Could probably live in the same module as well?

**Comment by numero-744** [comment]
> Sounds like a good addition to me as it is closely related to the `is_` version, and pretty useful to have in general in my opinion. Reminds me that I still wish there was a `matches!` like macro in std that does exactly this smile Could probably live in the same module as well?

This is discussed here: https://github.com/rust-lang/rfcs/issues/2960
