### ISSUE TITLE
Prioritize T::new() over T::ne() in completions.

### ISSUE THREAD

**Issue by extremegf** [rust-analyzer/rust-analyzer#7606]
Implementation might end up hacky but this would be a large quality-of-life improovement.

T::new() pattern is very common.
T::ne() (not-equal) is very rarely used, because you would rather write p != q which is equivalent to p.ne(q).
Yet the first completion after typing p.ne$0 is T::ne().

Actually we might deprioritize all variants: eq, ne, lt, gt, le, ge.

Let me know what you think. Also if someone from the team would give me some hints on how this might be done I could possibly implement a PR.

**Comment by flodiebold** [comment]
I think this is covered by #4544.

**Comment by SomeoneToIgnore** [comment]
Yes, let's close that in favor to that one.

@extremegf
I've added some instructions in https://github.com/rust-analyzer/rust-analyzer/issues/4544#issuecomment-775876826 , ask away if something's unclear.

**Comment by crumblingstatue** [comment]
This still happens, it looks like #7935 is the issue to track now.
