### ISSUE TITLE
Tests which return Result are not run correctly

### ISSUE THREAD

**Issue by ChrisJefferson** [rust-analyzer/rust-analyzer#7624]
I hope I am submitting this to the correct repository, if not, apologises.

Consider the following test:

```
    #[test]
    fn basic_test() -> Result<(),()> {
        assert_eq!(false, true);
        Ok(())
    }
```

if I click on the "Run tests" button in vscode (that appears just above the tests), this test (along with my other tests) is run. If I click the "Run test" just for this test, no tests are run, I see output like:

```
> Executing task: cargo test --package rust-peal --lib -- vole::partition_stack::tests::basic_test --exact --nocapture <

   Compiling rust-peal v0.1.0 (/home/caj/files/reps/rusty-groups/rust-peal)
    Finished test [unoptimized + debuginfo] target(s) in 2.47s
     Running target/debug/deps/rust_peal-afb549c45843f2ca

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 35 filtered out


Terminal will be reused by tasks, press any key to close it.
```

I think the problem is the "Result" means the tests get wrapped, when running all tests the line is the following (notice the final f)

`test vole::partition_stack::tests::basic_test::f ... FAILED`

**Comment by lnicola** [comment]
Sounds like that might be a `cargo` issue? The `cargo test --package rust-peal --lib -- vole::partition_stack::tests::basic_test --exact --nocapture` invocation looks correct.

Can you share a project where this happens? You can remove most of the other code.

**Comment by ChrisJefferson** [comment]
Apologies, this is being caused by a package I was using ( https://github.com/d-e-s-o/test-env-log ), which redefines `#[test]`. It is also fixed in the most recent version of the package!

Should have tried for a minimal test case before submission.
