### ISSUE TITLE
Type of match expr on the output of str::parse is wrongly assumed to be `!`

### ISSUE THREAD

**Issue by booleancoercion** [rust-analyzer/rust-analyzer#7626]
When typing the following function in VS Code:
```rust
fn test() -> i32 {
    let a = match "1".parse() {
        Ok(val) => val,
        Err(_) => return 0,
    };

    a
}
```
Everything compiles correctly, but RA wrongly interprets the type of `a` to be `!` when it is actually `i32`.

**Comment by cynecx** [comment]
Perhaps something is wrong with the coercion logic? We are trying to merge the never type with a type variable here (from the two match arms):

https://github.com/rust-analyzer/rust-analyzer/blob/8638bcbfe79a19f3c2a75bd35054e90a245af3af/crates/hir_ty/src/infer/expr.rs#L330

which then calls (with `ty1=TypeVar`, `ty2=Never`):

https://github.com/rust-analyzer/rust-analyzer/blob/8638bcbfe79a19f3c2a75bd35054e90a245af3af/crates/hir_ty/src/infer/coerce.rs#L31

This does not branch as `self.coerce(ty1, ty2)` returns true. This seems wrong to me?

@flodiebold ?

**Comment by flodiebold** [comment]
No, I don't think that's the right fix. I think the compiler handles diverging expressions a bit differently from us, and we need to investigate why exactly this works in rustc.

**Comment by cynecx** [comment]
I am not even sure of those link are relevant here but still dumping them here so I or others might take a look later:

https://github.com/rust-lang/rust/blob/master/compiler/rustc_typeck/src/check/_match.rs (eg. `check_match`)
https://github.com/rust-lang/rust/blob/master/compiler/rustc_typeck/src/check/coercion.rs (eg. `CoerceMany`)
