### ISSUE TITLE
Sort assists by the range of the affected element

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#763]
Assists are micro-refactorings whose availability depends on the position of the cursor (eg, if cursor is on if, you can replace it with match). Usually, there's a number of the assists available, so it would be cool to sort the most relevant assists first (currently, the order is arbitrary). 

To do this, assists should have an optional `target: Option<TextRange>` which points to the area where assist is available (a better name for "region of code where assists is available" is welcome!). For example in 

```rust
struct Foo {
    <|>bar: u32
}
```

there should be two assists available: "add derive", which is active for the whole struct, and "make pub(crate)" which is active for `bar` ident.

The `target` field should be added to this struct:

https://github.com/rust-analyzer/rust-analyzer/blob/7e3776ca56a7f042a6a07f7cc2a4b27feb652516/crates/ra_assists/src/lib.rs#L18-L21

We should also have a `fn target(&mut self, target: TextRange)` method on `AssistBuilder` to optionally set the target:

https://github.com/rust-analyzer/rust-analyzer/blob/7e3776ca56a7f042a6a07f7cc2a4b27feb652516/crates/ra_assists/src/assist_ctx.rs#L118-L154

With this setup, we should sort the assists by the length of `target` here (the smaller the target the more specific assist is):

https://github.com/rust-analyzer/rust-analyzer/blob/7e3776ca56a7f042a6a07f7cc2a4b27feb652516/crates/ra_assists/src/lib.rs#L57-L64

assists with no target set should be sorted last. 

It might also be a good idea to look through existing assists and set target if appropriate. 

To test this feature, we should add a test to [lib.rs](https://github.com/rust-analyzer/rust-analyzer/blob/7e3776ca56a7f042a6a07f7cc2a4b27feb652516/crates/ra_assists/src/lib.rs) which basically asks for assists for the `struct Foo` example above.

**Comment by kjeremy** [comment]
Somewhat related: the next version of the protocol (I believe it's in the insiders build already) is that code actions will have an `is_preferred: bool` field that can be used to auto-fix assists either with a key-stroke or on file save. I don't know if that will matter for sort order but we should keep it in mind.
