### ISSUE TITLE
Support impls inside item bodies for types defined in the same body

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#7633]
This currently ignores the `impl`, which disables all IDE functionality inside it and also makes `f` not show up in completion:

```rust
fn f() {
    struct S;

    impl S {
        fn f(&self) {}
    }
}
```

**Comment by lnicola** [comment]
The highlight range (how is it called?) for these is a bit weird, too:

![image](https://user-images.githubusercontent.com/308347/108845018-91dbe500-75e5-11eb-9fbe-7b4ab44a5318.png)

**Comment by Veykril** [comment]
That's because when `Name{Ref}Class` classification fails for the token that's being hovered we try to find an enclosing expression and just highlight that + showing the type of said expression if possible.

**Comment by Veykril** [comment]
This seems to almost work now? Only thing that doesn't is completions, when typing `S.f$0` we don't get a completion for the `S::f` function.

**Comment by jonas-schievink** [comment]
This fully works now, including completions :tada:
