### ISSUE TITLE
no auto-completion for associated constants/functions on primitive types

### ISSUE THREAD

**Issue by japaric** [rust-analyzer/rust-analyzer#7642]
the auto-completion list for this case with a primitive type is empty:

``` rust
let x = i16::_;
```

the auto-completion list for this other case with a user-defined type does list the associated constants and functions:

``` rust
struct S;
impl S {
    const A: u8 = 0;
    const B: u8 = 0;
    fn foo() {}
}
let x = S::_; // [A, B, foo]
```

**Comment by jonas-schievink** [comment]
We don't complete functions either
