### ISSUE TITLE
Could not resolve macro when macro is defined in recursive macro expansion

### ISSUE THREAD

**Issue by SrTobi** [rust-analyzer/rust-analyzer#7645]
```rust
macro_rules! import_helper_macros {
    () => {
        import_helper_macros!($)
    };

    ($x:tt) => {
        #[allow(unused_macros)]
        macro_rules! blub { () => {  }; }
        
    };
}


fn main() {
    import_helper_macros!();
    blub!(); // <- error here
}
```

rust-analyzer shows `could not resolve macro 'blub'`, but rustc will compile just fine.
Error goes away if `import_helper_macros!($)` is used in the main.

**Comment by nox** [comment]
Is rust-analyzer choking on [this](https://github.com/hyperium/hyper/blob/bdb5e5d6946f4e3f8115a6b1683aff6a04df73de/src/cfg.rs#L26-L62) the same issue?

**Comment by edwin0cheng** [comment]
@nox I dunno think so, OP's problem is related to inner item `macro_rules!` , but not normal macro expansion.
