### ISSUE TITLE
Errors due to specialization + async_trait

### ISSUE THREAD

**Issue by vorot93** [rust-analyzer/rust-analyzer#7669]
```
#![feature(min_specialization)]

use async_trait::async_trait;

#[async_trait]
pub trait Trait {
    async fn a() {}
}

pub struct A1;

#[async_trait]
impl Trait for A1 {
    default async fn a() {}
}
```

Errors at `default` keyword:
```
Syntax Error: expected BANG
Syntax Error: expected `{`, `[`, `(`
Syntax Error: expected SEMICOLON
```

**Comment by Veykril** [comment]
The ungrammar has default already specified for the corresponding items, so the parsing has to be implemented only. Relevant code is here https://github.com/rust-analyzer/rust-analyzer/blob/84c9970db5056738995b0979cda8249c2314c6ee/crates/parser/src/grammar/items.rs#L86-L155
