### ISSUE TITLE
Support excluding certain auto-completion names such as PartialOrd::le()

### ISSUE THREAD

**Issue by kennytm** [rust-analyzer/rust-analyzer#7675]
**Issue**: when typing `str_var.le` most of the time we want it to call its `len()` method. But it will always pick `PartialOrd::le()` since it is a perfect match 🤷.

> ![1-fs8](https://user-images.githubusercontent.com/103023/107881908-65f39c00-6f21-11eb-8703-ca1a1feda6ed.png)

**Feature request**: There should be a way to exclude `PartialOrd::{le, ge}` and `PartialEq::ne` from appearing in the auto-completion e.g. by configurating an exclusion list (blacklist). Or if we must keep them in the completion, make them have a very low priority that even if the user entered a perfect match it is still not chosen as the default candidate.

> rust-analyzer version: 2021-02-08 (336909b)

**Comment by lnicola** [comment]
We should probably show inherent methods before those from traits in the prelude.

**Comment by flodiebold** [comment]
It's a similar topic to #4544, in that for both we need to have some completion sorting infrastructure. I disagree about sorting inherent methods before traits from prelude in general though; I'd just sort the operator overloading traits down.

**Comment by kennytm** [comment]
Closing in favor of #4544 and #7606.
