### ISSUE TITLE
Assist to convert `for` loop to `Iterator::for_each`

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#7681]
For example:

```rust
// Before
for (pixel_mut_ref, pixel_value) in pixels
    .get_frame()
    .iter_mut()
    .zip(screen_pixel_buf.subpixels())
{
    *pixel_mut_ref = pixel_value;
}

// After
pixels
    .get_frame()
    .iter_mut()
    .zip(screen_pixel_buf.subpixels())
    .for_each(|(pixel_mut_ref, pixel_value)| *pixel_mut_ref = pixel_value);
```

It might also be useful to have an assist that goes the other way.

**Comment by arzg** [comment]
Since #7741 has been merged, should this issue be closed and a new one be created for ‘`for_each` to `for`’, or should we keep this one and repurpose it?

**Comment by bjorn3** [comment]
I did say it should be a new issue.

**Comment by arzg** [comment]
> I did say it should be a new issue.

Oops, sorry, I must’ve missed it.
