### ISSUE TITLE
Completion suggests a lot of useless things

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#7686]
![image](https://user-images.githubusercontent.com/4325700/107973442-37a6a880-6f83-11eb-8a27-49bb1ed0d93a.png)

**Comment by lnicola** [comment]
I think we shouldn't do fuzzy suggestions across path segments.

**Comment by flodiebold** [comment]
I don't think we do anymore, that's just VSCode highlighting them that way? These are all matches on the last segment.

**Comment by lnicola** [comment]
We could also have a "smart case" thing where we do a case-sensitive search if the input has an upper-case letter. This would exclude 7 of the results in this example. And `Some` is duplicated for some reason.

**Comment by SomeoneToIgnore** [comment]
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/2690773/116937378-cfa65b00-ac71-11eb-9b21-1a6eb99071ea.png">

Hello from 2021: 
* no double `Some`
* "smart case" implemented
* despite some funny highlighting, we actually don't search in path segments

Should we close this?

**Comment by jhpratt** [comment]
I'd still prefer the aforementioned prefix matching (on any particular path segment). Having `So` match `lsp_types::SymbolKindCapability` seems excessive imo.

**Comment by Veykril** [comment]
Closing in favor of #10922 to better track the one aspect that hasn't been covered here yet.
