### ISSUE TITLE
Latest stable release on vscode seems to not auto update errors until I close the file and re-open it

### ISSUE THREAD

**Issue by dtzxporter** [rust-analyzer/rust-analyzer#7689]
After automatically upgrading to (v0.2.481) and downloading the language server, errors seem to be sticky even after fixed unless I make substantial changes to a line OR close the file and re-open it.

Like for instance, removing a semi colon and saving, then fixing it and saving, error persists.

This was not the case in the previous version.

See: https://i.imgur.com/1aTIFnW.mp4

**Comment by Veykril** [comment]
Hmm, that's a weird one I can't seem to reproduce. Worst question to ask but have you tried reinstalling the plugin? Do you have any specific rust-analyzer settings set or vscode autosaving after delay set?

I'm also a bit confused on the error you are getting, it says `expected SEMICOLON` after typing one there which just doesn't seem like the correct error at all 😕 There shouldn't be any parsing error there.

**Comment by dtzxporter** [comment]
Hey, I recorded the inverse example of what I said, sorry, there shouldn't be one there (initially, correct parse) then I place one, and it bugs out, then removed it and it stays there...

```
    "rust-analyzer.inlayHints.enable": false,
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.diagnostics.disabled": ["macro-error"]
```

^ Config

**Comment by dtzxporter** [comment]
Welp, launched today and was presented with an update (v0.2.489) and it seems to be working properly again (Reports the correct error and resolves it once I fix the issue & save)... Looks good to close.
