### ISSUE TITLE
Vim editor support

### ISSUE THREAD

**Issue by JeanMertz** [rust-analyzer/rust-analyzer#769]
I've been moving from vscode to Vim, and one of the extensions I miss, is (of course) rust-analyzer.

The moment I started using RLS in Vim, I noticed my fans regularly spinning up again, and as someone who dislikes spinning fans, that's a problem! 😝

Now I know that RA uses extensions that only work in vscode, but I came acros this project, that looks like it might work nicely with RA:

https://github.com/neoclide/coc.nvim

> Coc is an intellisense engine for vim8 & neovim. It only works on vim >= 8.1 and neovim >= 0.3.1
> 
> It's a completion framework, language server client which support extension features of VSCode.

There's first-party RLS extension support:

https://github.com/neoclide/coc-rls

> It's fork of rls-vscode.
> 
> Adds language support for Rust to coc.nvim. Supports:
> 
> * code completion
> * jump to definition, peek definition, find all references, symbol search
> * types and documentation on hover
> * code formatting
> * refactoring (rename, deglob)
> * error squiggles and apply suggestions from errors
> * snippets

Given that it's a fork of rls-vscode, I wonder how far we can get porting the current ra vscode plugin to coc.

I don't have the time _right now_ to work on this, but I wanted to put this here, in case anyone else is interested. If I find some time in the near future, I will take a stab at this.

**Comment by matklad** [comment]
Most of the features should work out of the box with 
https://github.com/autozimu/LanguageClient-neovim

**Comment by kjeremy** [comment]
@JeanMertz Take note that we do not really do anything with client capabilities yet so if you may see some weird things that could explain the behavior.

**Comment by JeanMertz** [comment]
> Most of the features should work out of the box with
> [autozimu/LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim)

I've been giving this a go, but it seems like autocompletion is behaving weirdly.

Say I have this:

```rust
let string = String::new|
```

If I hit tab, I end up with

```rust
let string = String::new()$0|
```

Similarly, `drop|` ends up as `drop($0)|`

Now I realise that `$0` is supposed to be the final position of the cursor after autocompletion (similar to how you make snippets in vscode).

Is this because of what @kjeremy said, that RA is supposed to not do cursor positioning when the client does not support this, but does so anyway right now?

**Comment by matklad** [comment]
Yeah, vim does not support snippets in completion IIRC, but we only provide completion with snippets. I'd say that the really proper solution here would be to fix vim, but we probably can provide simpler completions on our side as well.

**Comment by DJMcNab** [comment]
I would guess that the language client does not support snippet syntax. I imagine there is a link, but I'm on mobile so can't check.

**Comment by kjeremy** [comment]
That's my guess as well. We could store the client caps and check against them in the handlers (or the `conv` functions even if we support a request but not all the capabilities) but we've only cared about supporting the latest protocol additions so far.

**Comment by JeanMertz** [comment]
Alright, for those finding this thread, I managed to get this working using the following:

* install the latest [`LanguageClient-neovim`](https://github.com/autozimu/LanguageClient-neovim) for LSP support
* install [`deoplete.vim`](https://github.com/Shougo/deoplete.nvim) for autcomplete support
* install [`neosnippet.vim`](https://github.com/Shougo/neosnippet.vim) for snippet expansion support (see [here](https://github.com/autozimu/LanguageClient-neovim/commit/657ad707d8732fc5a2139224cb00132880455904) why)

Those three combined with this config:

```rust
let g:deoplete#enable_at_startup = 1
let g:neosnippet#enable_complete_done = 1
let g:LanguageClient_serverCommands = {
    \ 'rust': ['~/.cargo/bin/ra_lsp_server'],
    \ }
```

should do the trick:

![recording](https://user-images.githubusercontent.com/383250/52770625-e5e58380-3033-11e9-8765-458d7647868b.gif)

**Comment by matklad** [comment]
Wow, that's a cool GIF :heart: ! 

Could you send a PR to add it to readme?

After "See these instructions for VS Code setup and the list of features (some of which are VS Code specific)." we could say "It works with other editors as well", and add a gif below. 

We shouldn't add gifs directly to the repo, instead, upload it in a comment to [this issue](https://github.com/rust-analyzer/rust-analyzer/issues/567)

**Comment by lnicola** [comment]
For what it's worth, it's also working with `w0rp/ale`. You need:

```viml
let g:ale_rust_rls_executable = 'ra_lsp_server'
let g:ale_rust_rls_toolchain = ''
```

**Comment by Avi-D-coder** [comment]
For anyone using [Coc.nvim](https://github.com/neoclide/coc.nvim/) I forked the code extension and started porting it to the Coc api at [coc-rust-analyzer](https://github.com/Avi-D-coder/coc-rust-analyzer). It's about a month old, but it's a start.

**Comment by oblitum** [comment]
I have a question. I'm using rust-analyzer in coc.nvim (not the coc-rust-analyzer extension, I've just setup the server) and it works but I noticed snippets for function signatures don't work. Are they expected to work? I've noticed in the [gif above](https://github.com/rust-analyzer/rust-analyzer/issues/769#issuecomment-463524385) that they also not working for another [neo]vim LSP client, just an empty argument list. signatureHelp is working fine, when it works, but I miss snippet support.

**Comment by oblitum** [comment]
coc.nvim supports snippet expansion, I use it with other servers. So it's not an issue of it not supporting that. [Example](https://oblitum-public.s3-us-west-2.amazonaws.com/screencast-neovim-coc.mp4).

**Comment by matklad** [comment]
We don't add placeholder parameter values to the function call, only the `()`.

**Comment by oblitum** [comment]
@matklad but I guess that's not the aim, just momentarily lacking right?

**Comment by matklad** [comment]
I don't know, to me personally parameter snippets seem like a poor substitution for parameter info & completion. But it won't be hard to add them in any case, and hiding them behind a feature flag should be uncontroversial.

**Comment by oblitum** [comment]
ok. I don't see the need for a feature flag though, as you can see in the video, expansion is optional, it's not substitute.

**Comment by oblitum** [comment]
> I don't know, to me personally parameter snippets seem like a poor substitution for parameter info & completion. But it won't be hard to add them in any case, and hiding them behind a feature flag should be uncontroversial.

Parameter snippets placeholders are provided by default now. Was a feature flag added?

**Comment by matklad** [comment]
Yup, https://rust-analyzer.github.io/thisweek/2020/03/09/changelog-15.html#new-features

The relevant flags are:

`call-info.full`, `completion.insertion.add-argument-snippets`, `completion.insertion.add-call-parenthesis`. The docs still are more or less missing though :-(

**Comment by oblitum** [comment]
Nice!

**Comment by thorlucas** [comment]
I'm using @JeanMertz's exact configuration, and when inserting the same snippet (or any snippet for that matter), I get an odd thing at the end:

``` rust
let string = String::with_capacity(capacity)<`0`>
```

Anybody know what this could be?
