### ISSUE TITLE
Flip comma breaks in macros

### ISSUE THREAD

**Issue by bugadani** [rust-analyzer/rust-analyzer#7693]
I tried to run "Flip comma" assist on this piece of code:
```rust
fn foo() {
    bar!(a.b, c);
}
```

Instead of the expected `bar!(c, a.b);`, the assist result is `bar!(a.c, b)`. I think it could be argued this is as valid as anything else since macros can do whatever they want, but if keeping `a.b` together isn't an acceptable solution, "Flip comma" probably shouldn't be offered in macro calls.

**Comment by Veykril** [comment]
The assist only considers siblings, which for macro input are just mere tokens so it swaps the `b` and `c` tokens https://github.com/rust-analyzer/rust-analyzer/blob/00d5a9563af9c84cdea9d029a9583be0513cc459/crates/assists/src/handlers/flip_comma.rs#L21-L23
I don't think descending the macro here is an option so disabling it when inside macros is probably best. To check we would have to iterate all ancestors of the token and see if any of them is a `ast::MacroCall`.

**Comment by greenhat** [comment]
I'd like to work on it.

**Comment by Veykril** [comment]
Go ahead. Also you could try looking into whether its possible to just take all tokens on the left and right side(up until the end of the macrocall or a next comma) of the comma and swap them. If that doesn't work out disabling is still also fine.
