### ISSUE TITLE
Assist: generate an `is_empty` method from a `len` method

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-analyzer/rust-analyzer#7709]
_Sibling issue: https://github.com/rust-analyzer/rust-analyzer/issues/7708_

Clippy's ["len without is_empty"](https://rust-lang.github.io/rust-clippy/master/index.html#len_without_is_empty) lint warns if you have a `len` method but no `is_empty` method. An assist could make this trivial to generate. I'd be happy to implement this; feel free to assign me to it!

## Examples

**before**
```rust
impl MyStruct {
    p|ub fn len(&self) -> usize {
        self.data.len()
    }
}
```

**after**
```rust
impl MyStruct {
    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}
```

**Comment by lnicola** [comment]
Implemented in #8037.
