### ISSUE TITLE
extract module into file changed module visibility

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#7712]
![Peek 2021-02-18 12-00](https://user-images.githubusercontent.com/33961674/108303592-2a86f500-71e1-11eb-93bf-c5cddbb1b9d3.gif)

**Comment by Veykril** [comment]
Relevant code that discards the visibility https://github.com/rust-analyzer/rust-analyzer/blob/20a911f3cc2beb0409ab71cc1560648374745f7f/crates/assists/src/handlers/move_module_to_file.rs#L62
