### ISSUE TITLE
unresolved-module in rapier repository

### ISSUE THREAD

**Issue by emilk** [rust-analyzer/rust-analyzer#7715]
Hi, and thanks for an amazing tool!

I'm using rust-analyzer in VS code and am currently doing some work on this project: <https://github.com/dimforge/rapier/>

The problem is that rust-analyzer doesn't seem to work at all for that repository. I get no type annotations, and things like rename doesn't work.

rust-analyzer reports the problem `unresolved-module` for these lines: https://github.com/dimforge/rapier/blob/12c5dd4caa6af5750b682ba17229601e3a418155/src/lib.rs#L131:L136 despite the modules seemingly being in the normal place (e.g. https://github.com/dimforge/rapier/blob/12c5dd4caa6af5750b682ba17229601e3a418155/src/data/mod.rs).

Hopefully reproducing this problem will be as easy as checking out the above repository (not exactly a minimal reproduce though).

**Comment by Veykril** [comment]
Looks like we are having trouble resolving paths correctly due to rapier's "interesting" workspace structure, https://github.com/dimforge/rapier/tree/master/build. All of these crates direct their lib path to `../../lib.rs`. Everything resolves fine if one replaces the top level workspace toml with one of the ones in the build directory and removing the explicit lib path.

**Comment by flodiebold** [comment]
That's a really weird structure... but in theory we should be fine with it. Are we getting the current path from lib.rs mixed up somehow?

**Comment by Veykril** [comment]
Commenting out all but one of the members in the workspace.members entry in the top level Cargo.toml also fixes unresolved module errors so I guess there is some mixup/collision happening

**Comment by bjorn3** [comment]
Is it possible that the fact that the same `src/lib.rs` file is used by two crates be the problem here?

**Comment by flodiebold** [comment]
It shouldn't be, but maybe it is. Although I'd certainly expect it to lead to errors being reported multiple times etc.

**Comment by rezural** [comment]
I just noticed that if you navigate to each of the modules that cannot be found in the file explorer, then rust-analyzer can now find that file.

**Comment by rezural** [comment]
Symlinking to /src/ in each of the build directories, and removing the path works:

[lib]
name = "rapier2d_f64"
#path = "../../src/lib.rs"
required-features = [ "dim2", "f64" ]

**Comment by rezural** [comment]
Any pointers on where the code is that should pick up path would be appreciated.

I assume it is in the rust-analyzer server that this is not being picked up properly.

**Comment by lnicola** [comment]
See also https://github.com/rust-analyzer/rust-analyzer/issues/9173, but I think the path isn't outside of the workspace in this issue.

**Comment by lnicola** [comment]
I think you can look into the project_model (we have two, look for the cargo one) and vfs crates. It works once you open the file because we load it into the VFS, but we miss it during the initial project load.

This is probably a bit different from the other issue because the path is available in Cargo.toml, and we don't need to parse an attribute to find it.

**Comment by rezural** [comment]
Ive found the project_model, and I'm pretty sure that at least doesnt support path. Not sure where the code currently generates the path from though.

**Comment by flodiebold** [comment]
It does:
https://github.com/rust-analyzer/rust-analyzer/blob/9d60d75e1400ba82ae8d41496d8a0fb9a8edec0c/crates/project_model/src/cargo_workspace.rs#L162-L163
which goes into the crate graph here:
https://github.com/rust-analyzer/rust-analyzer/blob/9d60d75e1400ba82ae8d41496d8a0fb9a8edec0c/crates/project_model/src/workspace.rs#L431-L440
There's nothing special about `path`; we just get the crate root file from Cargo in all cases.

**Comment by rezural** [comment]
Minimal Repro here:
https://github.com/rezural/rust-analyzer-rapier-repro.git

**Comment by rezural** [comment]
It looks like when vfs-notify code registers a workspace, it uses the project root (which in the repro is build/biccies), which contains no entries. We need to pass (probably via root.include) to this code here:

https://github.com/rust-analyzer/rust-analyzer/blob/9fdb8f90376c02ec2a267cf9eb3bdb7b6027e1e6/crates/rust-analyzer/src/reload.rs#L461

probably in here:

https://github.com/rust-analyzer/rust-analyzer/blob/80b840df79e3fddbc3fa13e65c39b42a4195a480/crates/project_model/src/workspace.rs#L220

I'll hopefully have a PR soon.

**Comment by rezural** [comment]
@emilk, FYI

Just put up this PR. 0 errors now in rapier master. looks beautiful :smile:

**Comment by emilk** [comment]
Thank you @rezural !

**Comment by rezural** [comment]
Please test this in nightly.

Works for me, probably can close this.

@emilk
