### ISSUE TITLE
Don't compute block_def_map when there are only macros in expression position

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#7717]
Currently we cannot distinguish between macro calls in item/statement vs. expression position, leading to unnecessary block_def_map computations. For example, in this code there's no need to compute block_def_map for the function block:

```rust
fn f() {
    let x: mac![] = e!();
}
```

This is a very minor issue and is unlikely to impact performance or memory usage much.

**Comment by lnicola** [comment]
Do we still want to do this? Not that I think either way, but we're lagging on `ungrammar`.

**Comment by jonas-schievink** [comment]
Crap, I shouldn't have published that so eagerly, I ran into some issues while updating r-a

**Comment by jonas-schievink** [comment]
I reverted the ungrammar changes since I came up with a simpler way to achieve this: We "just" compute per-block ItemTrees and skip `block_def_map` computation when that ItemTree has no top-level items.
