### ISSUE TITLE
Apple Silicon: Wrong binary auto downloaded under VSCode's rust-analyzer plugin

### ISSUE THREAD

**Issue by miranquil** [rust-analyzer/rust-analyzer#7720]
I found that under VSCode insider edition which supports Apple Silicon, every time I installed rust-analyzer plugin there would be a pop-up asking me to download rust-analyzer binary. **Even ra was already existed in $PATH.**

This is not the worst. If I let it download automatically and start coding in Rust, the editor will get soooooo laggy when typing. But if I ignore that pop-up and configure the existing binary path under config of plugin, it works well.

I guess the auto-downloading downloads an Intel version in fact?

**Comment by bjorn3** [comment]
Rust-analyzer should be installed for AArch64 on M1 macs since https://github.com/rust-analyzer/rust-analyzer/pull/7001.

**Comment by lnicola** [comment]
> But if I ignore that pop-up and configure the existing binary path under config of plugin, it works well.

That's normal. The extension will download the binary from GitHub unless you configure it there. We don't look in `PATH` first.

> If I let it download automatically and start coding in Rust, the editor will get soooooo laggy when typing.

That's not really normal, although I've never seen an M1 Mac. Can you let the extension download the server, then look under `~/Library/Application\ Support/Code/User/globalStorage/matklad.rust-analyzer` and see what version is there? You can run it with `--version`, then run `md5sum` against it, or something similar.

Also, are you running a native M1 Code build?

**Comment by miranquil** [comment]
Well maybe I've created an outdated issue because I've uninstalled the extension for several days without testing again.

The server downloaded by the extension works well now.

All in all, here's the stuff you need.

```bash
./rust-analyzer-aarch64-apple-darwin --version
rust-analyzer 7435b9e
```

And here is the one existing already:

```bash
~/.cargo/bin/rust-analyzer --version
rust-analyzer 876c451
```

Thanks for helping!

**Comment by lnicola** [comment]
If it happens again, please make sure that the downloaded version is identical to the one you except. E.g. maybe Code compiled for x86 downloads the x86 version because the platform isn't detected correctly. Or try to download an x86 binary, put in under `serverPath` and see if matches the slowness you've noticed before.

**Comment by max-sixty** [comment]
FYI I had this issue — uninstalling the extension, restarting VSCode, and installing it again — worked
