### ISSUE TITLE
Completion suggestion only shows public traits and members

### ISSUE THREAD

**Issue by villem** [rust-analyzer/rust-analyzer#7728]
Environment: mac osx 10.15.7, VSCode 1.53.2, 
Latest nightly Rust Analyzer
```
INFO [2/20/2021, 6:07:47 PM]: PersistentState: {
  lastCheck: 1613807019781,
  releaseId: 38343369,
  serverVersion: '0.3.494-nightly'
}
```

I don't know if this has been always the case?
We got simple struct and some traits.
```rust
#[derive(Debug, Default)]
struct Foo {
    pub name: Option<String>,
}
struct Template2 {
    pub foo: Foo,
}

impl Template2 {
    pub fn faa(&self) {
        let a: Foo = Foo {..Default::default()};
        
    }
    fn priv2(&self) {

    }
    pub fn bar(&self) -> () {
        let a: Foo = Foo { ..Default::default() };
        println!("foo {}", a.name);
        self.<*>

    }
}
fn baz() {
    let goo: Template2 = Template2{ foo: Foo{ name: None }};
    println!("goo {}", goo.faa())
}
```
`goo.<*>` get fn bar completion if bar is pub.
also bar's `self.<*>` find priv() only if it is pub.

Has rust analyser always followed visibility rules? I think it would be really nice if we could turn this of and let compiler fail when private part is tried to use.

**Comment by lnicola** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/308347/108605667-4b587180-73be-11eb-8829-f3b2a554bbe9.png)

Your original code had `fn priv()` without `&self`, does it still happen with the updated version?

**Comment by villem** [comment]
I don't get completion even after adding &self to priv2. I also added the empty main. Strange enough if get priv2 suggestion when from `baz()` with `goo.pri`

**Comment by villem** [comment]
With latest nigthly Feb 21. Things seems working better. I get priv2 within `bar` but also with `goo.pri`.

**Comment by lnicola** [comment]
I don't recall this any recent changes that could have affected this, but it's good to hear that it works. Can we close it, then?

**Comment by villem** [comment]
After playing bit more, I get still inconsistent suggestions. It seems that only reliable way to get member and trait suggestions is to mark everything pub.

**Comment by flodiebold** [comment]
Can you provide a concrete example where you're missing suggestions?

**Comment by villem** [comment]
The attached video shows how trait method `bar` only get suggestions `faa and priv2()` if they are pub. The `goo` variable get suggestion `faa and priv2()` whether they are pub or not.



https://user-images.githubusercontent.com/123159/108628561-654c8f80-7464-11eb-83b4-97acf557517d.mp4

**Comment by flodiebold** [comment]
Huh, there seems to be something weird going on with macroexpansion here.
```rust
mod foo {
    #[derive(Debug, Default)]
    struct Template2 {}

    impl Template2 {
        fn private(&self) {}
    }
    fn baz() {
        let goo: Template2 = Template2 {};
        // goo.<|> -> here it works
        println!("goo");
        // goo.<|> -> here it doesn't work
    }
}
```
It seems like we detect the wrong module after the macro call. Note that this only fails if it's in a submodule; putting the code into the crate root makes it work.

**Comment by edwin0cheng** [comment]
Um.. an empty macro is not working either: 

```rust
macro_rules! empty {
    () => {};
}

mod foo {
    #[derive(Debug, Default)]
    struct Template2 {}

    impl Template2 {
        fn private(&self) {}
    }
    fn baz() {
        let goo: Template2 = Template2 {};
         // goo.<|> -> here it works
         empty!();
        // goo.<|> -> here it doesn't work        
    }
}
```

**Comment by villem** [comment]
Latest working great. Thank you!
