### ISSUE TITLE
Extension doesn't do anything

### ISSUE THREAD

**Issue by willparsons** [rust-analyzer/rust-analyzer#7740]
I've tried using the rust-analyzer extension on its own and it is literally not doing anything. It's like no extensions for Rust are installed at all

**Comment by bjorn3** [comment]
Did you get a notification at the bottom right of the vscode window asking to update the rust-analyzer binary? After a while this notification will be moved into the notification pane by vscode, so it can be easy to miss.

**Comment by lnicola** [comment]
And which Code version are you using?

**Comment by willparsons** [comment]
@bjorn3 Yes, and I allowed it to install the binary

@lnicola 
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Hope this info helps

**Comment by lnicola** [comment]
Is there anything in the output window, in the RA channels? Did you try to restart Code after installing the binary?

**Comment by willparsons** [comment]
Ok, this is very weird but today it's working :P

Sorry for wasting everyone's time. 

If it helps I just removed all extensions relating to rust. Restarted VSCode and installed the rust-analyzer. Weird because I have done this multiple times before.

**Comment by lnicola** [comment]
Did you have any others? We warn about running at the same time with vscode-rust (the official extension).

**Comment by willparsons** [comment]
> Did you have any others? We warn about running at the same time with vscode-rust (the official extension).

So I had tried this before with the vscode-rust extension completely removed and it didn't work. Honestly, no clue why but today it just requested to install the binary again, and now it's ok. I guess some sort of error with the binary that was downloaded prior.
