### ISSUE TITLE
tooltips render type signatures using private type aliases

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#7745]
If a function in another crate has a type alias in its signature that's private to the declaring crate, the tooltip rendering for the function will show that private type alias, rather than showing the type that you'd use from within the current crate.

**Comment by flodiebold** [comment]
I guess we currently show the definition as written. We could instead display the actual types, but I'm not actually sure that would be a better default. It'd mean we show no type aliases at all, for example.

**Comment by Lokathor** [comment]
rustdoc shows the types based on what users outside of the crate see, which seems to work very well and is a minimal complication while still showing most aliases.

**Comment by camelid** [comment]
Is this a duplicate of #1666?

**Comment by Lokathor** [comment]
uh, probably
