### ISSUE TITLE
Unable to jump to between {}

### ISSUE THREAD

**Issue by tami5** [rust-analyzer/rust-analyzer#7746]
Hey everyone, thanks for all the work and amazing innovation you are all doning here.

I used rust-analyzer with neovim and I have this issue of not being able to jump to snippets. Basically the server returns 

```
{
  'label': 'impl', 
  'textEdit': {
     'range': {
        'end': {'character': 3, 'line': 5}, 
        'start': {'character': 0, 'line': 5}
     }, 
     'newText': 'impl $0 {}'
   }, 
...
}
```

which doesn't allow jumping to between `{}`, 

expected `impl $1 { $0 }`

Thanks 

https://github.com/hrsh7th/nvim-compe/issues/188

**Comment by tim-hilt** [comment]
This is true for all of the built-in snippets, as far as I checked them. It works as expected with postfix-snippets though.

I also tested it with VS-Code: Same thing. Must be related to `rust-analyzer`.

**Comment by tami5** [comment]
Any plans to solve this. or add $1/$0 to the snippet to improve experience

**Comment by tim-hilt** [comment]
Was this resolved?

**Comment by tami5** [comment]
> Was this resolved?

Yes, I no longer experience it, not sure if if the plugin I'm using for completion provided a hack or this was resolved somehow here.

**Comment by tim-hilt** [comment]
That's great news! May I ask which editor and plugin you're using? I don't normally code Rust. I tried that out with VS Code and the rust-analyzer extension.

**Comment by tami5** [comment]
@tim-hilt I use neovim + nvim-cmp which the best experience out there 😆 add me on discord if you need help setting up neovim tami5#1560

**Comment by lnicola** [comment]
Isn't `ms-jpq/coq_nvim` the best thing now? :rofl:

**Comment by tim-hilt** [comment]
@lnicola I wouldn't want a Python-dependency for an nvim-package!
