### ISSUE TITLE
Uniform line separator handling

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#775]
Linux and mac use \n for line endings, Windows uses \r\n, and we need to deal with it somehow.

Just using both wouldn’t work too well: we need to create edits to the documents, and worrying about line separators when editing code is too much of a hassle.

So we should use \n everywhere, and convert to \r\n at the boundary. Specifically, in the `paerse` query we should do the conversion in the “in” direction, and we should transform edits on the “out” direction.

**Comment by vipentti** [comment]
This will probably require some state regarding the newlines that are being used. Meaning we can always transform all newlines to`\n` but doing the reverse transformation should know whether to keep the `\n` or transform them back to `\r\n`. I think ideally we would maintain original line endings with all edits, even if the file has mixed line endings.

**Comment by c410-f3r** [comment]
Shouldn't the EOL conversion be handled inside ra_vfs? At least for the `Editor` -> `Analyzer` flow.

**Comment by matklad** [comment]
Fixed this a while ago.
