### ISSUE TITLE
Autocomplete doesn't show items from current crate

### ISSUE THREAD

**Issue by redain** [rust-analyzer/rust-analyzer#7750]
Usually autocomplete helps me to find needed item and automatically import it when selected.
However, recently i encountered a problem when autocomplete doesn't show me items from the crate that I'm working on now currently, but instead showing me only items from external crates.
For example I have an `AttachmentImage` pub struct in my crate, but autocomplete doesn't show me this item, but only shows items with similar names from external crate `ash`. This struct is just an example, all other items from my crate doesn't appear in autocomplete suggestions either.
![Screenshot 2021-02-22 183724](https://user-images.githubusercontent.com/52823087/108705583-1a07af00-7540-11eb-8915-db645611b8db.png)

Ctrl + . assist for importing such items doesn't work too (No code actions available) when cursor is over item.
However i have another assist at the top of source file (it works only at line 1, col 1) that is able to import such an item (and it seems this assist appears only after `cargo check`):
![Screenshot 2021-02-22 201715](https://user-images.githubusercontent.com/52823087/108713563-fac24f00-754a-11eb-96ac-111e6a6c1234.png)

rust-analyzer version: 2021-02-22 (14de9e5)
I'm using VS Code.

**Comment by lnicola** [comment]
Did you perhaps forgot a `mod` declaration? Can you share a subset of your project where this still happens?

**Comment by redain** [comment]
Mod declaration exists for both imported item and current source file.
I'm not sure how to share a subset of a project, but I can share access to entire repository for your account.
Also i noticed that for function parameters ctrl + . assist with suggested import is working but no autocomplete suggestion though.
![Screenshot 2021-02-22 230650](https://user-images.githubusercontent.com/52823087/108735067-adea7280-7562-11eb-867b-125b653127e7.png)

**Comment by redain** [comment]
Seems like having macros in struct method body breaks autocompletion, i was able to reproduce it in a fresh new test crate.
With macros format!:
![Screenshot 2021-02-24 135549](https://user-images.githubusercontent.com/52823087/108960242-2c9cf800-76a8-11eb-8c8f-f0b35bb949ce.png)
Without macros:
![Screenshot 2021-02-24 135606](https://user-images.githubusercontent.com/52823087/108960264-36bef680-76a8-11eb-85ba-bae3dc161284.png)
In my original example there was todo! macros in struct method body

**Comment by lnicola** [comment]
> i was able to reproduce it in a fresh new test crate

But your original example had no macro call, strange. Can you put the code up somewhere?

**Comment by redain** [comment]
> 
> 
> > i was able to reproduce it in a fresh new test crate
> 
> But your original example had no macro call, strange. Can you put the code up somewhere?

In my original example there was todo! macro. I will upload example repository

**Comment by redain** [comment]
https://github.com/redain/rust-analyzer-issue-example/blob/main/src/mod_2/src_1.rs - here is an example

**Comment by lnicola** [comment]
I can confirm, this is such a weird bug.

**Comment by flodiebold** [comment]
If it's related to macros in function bodies, cc @jonas-schievink

**Comment by SomeoneToIgnore** [comment]
Afaik, we do current crate lookup via the symbol search ([here](https://github.com/rust-analyzer/rust-analyzer/blob/68626e4ef5acfea05812b68f41efa2bcd5bea448/crates/ide_db/src/imports_locator.rs#L112)), so don't really support any macros at all in this case.

**Comment by jonas-schievink** [comment]
Using a macro in a function body causes it to get a block_def_map, so this can surface bugs around inner item handling
