### ISSUE TITLE
proc-macro panicked: not implemented: unknown args for typed_integer: n 0, kind isize

### ISSUE THREAD

**Issue by jonasbb** [rust-analyzer/rust-analyzer#7751]
In a derive macro crate I see this error message:
```
proc macro returned error: proc-macro panicked: not implemented: unknown args for typed_integer: n 0, kind isize
```

It is sufficient to open the `tests/basic.rs` file of this repository (<https://github.com/jonasbb/serde-indexed>) in VS Code to see the error message.

rust-analyzer Version: 0.2.497 (but also happened with last week's version).  
VS Code: 1.53.2

The error message seems to originate from here, which is missing `isize` in the list of suffixed integers.
https://github.com/rust-analyzer/rust-analyzer/blob/94f56ebccf2e558c178d2d73161fe78803b6f3e2/crates/proc_macro_srv/src/rustc_server.rs#L494-L513

**Comment by lnicola** [comment]
That code is from `rustc`, does the test compile?

**Comment by jonasbb** [comment]
Yes the crate and tests compile with `rustc 1.50.0 (cb75ad5db 2021-02-10)` and `rustc 1.52.0-nightly (9b471a3f5 2021-02-19)`.

@lnicola I cannot find the code in the rust-lang/rust repository. Are you sure the code is from there? I only see this implementation:
https://github.com/rust-lang/rust/blob/c8915eebeaaef9f7cc1cff6ffd97f578b03c2ac9/compiler/rustc_expand/src/proc_macro_server.rs#L538-L540

**Comment by lnicola** [comment]
Ah, sorry, I searched for it in the Rust repository, but actually got a result from the `rust-analyzer` submodule.
