### ISSUE TITLE
Incorrect syntax highlighting for use memchr::{memchr, memchr2}

### ISSUE THREAD

**Issue by Count-Count** [rust-analyzer/rust-analyzer#7763]
In this use statements for of the memchr crate the crate is incorrectly highlighted as a function, see screenshot:
```rust
use memchr::{memchr, memchr2};

fn main() {
    let _x1 = memchr(b'x', b"abcx");
    let _x2 = memchr2(b'x', b'y', b"abcx");
}
```
Hovering over the crate also incorrectly show the function documentation instead of the crate documentation.

It is correctly highlighted for a single import like this:
```rust
use memchr::memchr;
use memchr::memchr2;

fn main() {
    let _x1 = memchr(b'x', b"abcx");
    let _x2 = memchr2(b'x', b'y', b"abcx");
}
```
![memchr-broken](https://user-images.githubusercontent.com/51271955/108820627-bcfe0e80-75bc-11eb-8cca-0fc562c961da.png)
![memchr-ok](https://user-images.githubusercontent.com/51271955/108820636-c1c2c280-75bc-11eb-86d3-218514a8b0d3.png)

Repo w/ testcase: https://github.com/Count-Count/rust-analyzer-syntax-highlighting-bug

**Comment by lnicola** [comment]
Ugh. We color `memchr` as `memchr::memchr`.

**Comment by lnicola** [comment]
![image](https://user-images.githubusercontent.com/308347/108820908-84aefe00-75c5-11eb-85be-eac99c98b67e.png)
