### ISSUE TITLE
Type hints and drill downs do not work with wasm-bindgen/web-sys

### ISSUE THREAD

**Issue by mplsgrant** [rust-analyzer/rust-analyzer#7767]
**My Goal & Problem**
I want to see type hints, hover hints, and use drill-downs to see underlying source code while I program using the wasm-bindgen suite of crates. However, most inline and hover hints do not show up, and "ctrl-clicking" does not drill down to the underlying source code as I expect it would.

**My Software**
* Visual Studio Code version 1.53.2
* rust-analyzer

rust-analyzer settings:

    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
    "rust-analyzer.lens.references": true,
    "rust-analyzer.lens.methodReferences": true,
    "rust-analyzer.updates.channel": "nightly",
    "rust-analyzer.diagnostics.disabled": [
        "missing-unsafe"
    ],

**Additional Details**
* The software I wrote compiles successfully and runs as I expect it to.
* When I use the old(?) Rust extension with the rls backend, drill-downs and hover hints do work, but inline-hints do not show up.

Here is a screenshot which shows the lack of type hints:

![web-sys](https://user-images.githubusercontent.com/58152638/108876343-bf179b80-75c3-11eb-8356-acb006a83cb1.png)

**Comment by jonas-schievink** [comment]
this is https://github.com/rust-analyzer/rust-analyzer/issues/6029

**Comment by lnicola** [comment]
@jonas-schievink do you want to keep an open issue for `web_sys`? We've closed most other issues caused by the lack of attribute proc macro support.

**Comment by jonas-schievink** [comment]
Doesn't really seem necessary
