### ISSUE TITLE
Usage of constants in patterns not listed in references

### ISSUE THREAD

**Issue by Alabaster** [rust-analyzer/rust-analyzer#7771]
It seems that the usage of constants in patterns is not listed when finding references of that constant. For example in the code:
```Rust
const A: i32 = 42;

fn main() {
    let mut b = 24;
    match b {
        // This usage of A is not found.
        A => println!("Hello"),
        _ => {}
    }

    // This usage of A is not found.
    if let A = b {
        println!("World");
    }

    // Only this usage is found.
    b = A;
}
```
only the last usage of `A` is listed in the references while I would have expected all three usages to appear in the list. "Goto definition" works fine on all usages. I tested this with a build of rust-analyzer from the current master branch (commit 27ed1ebf8997cea55fb446ce249b390607b84105).

**Comment by Veykril** [comment]
Fixed in #7772
