### ISSUE TITLE
Postfix vec completion

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#7773]
Wraps an expression in `vec![]`

Before:

```rust
fn foo(n: i32) -> Vec<i32> {
    n.vec$0
}
```

After:

```rust
fn foo(n: i32) -> Vec<i32> {
    vec![n]$0
}
```

**Comment by lukechu10** [comment]
I would like to try and implement this.

**Comment by flodiebold** [comment]
I'm not convinced we should add this. `[x].vec` isn't shorter to type than `vec![x]`, and I think it's unlikely that you'll want to wrap some expression in a vector after the fact...

**Comment by Veykril** [comment]
Wouldn't it be `x.vec` -> `vec![x]`? But ye it might not pull its weight...

**Comment by lnicola** [comment]
These come up so often it might be worth adding support for custom replacements.

**Comment by lukechu10** [comment]
I think this is related to https://github.com/rust-analyzer/rust-analyzer/issues/1431

**Comment by flodiebold** [comment]
I could see adding more of them if we can only show them in situations where they're likely to be useful. So for example, I think the `vec` postfix might be acceptable if we only show it if we have a `T` and are expecting a `Vec<T>`.

**Comment by lukechu10** [comment]
> I could see adding more of them if we can only show them in situations where they're likely to be useful. So for example, I think the `vec` postfix might be acceptable if we only show it if we have a `T` and are expecting a `Vec<T>`.
> 
One problem with this approach is that is that some users might expect these postfix completions to be available in certain situations e.g.
```rust
let my_vec = x.vec<|>
```
but discover they are not.

**Comment by lukechu10** [comment]
Maybe this could be special cased for variable definitions?

**Comment by Veykril** [comment]
That wouldn't really counteract the main problem as the main use of postfix completions are for variables. I think we should ideally support custom postfix completion definitions so that people can just create the completions they want themselves.

**Comment by Veykril** [comment]
With https://github.com/rust-analyzer/rust-analyzer/pull/10458 merged, starting tomorrow(on nightly) or next week(on stable) this can be done by adding:
```json
        "vec!": {
            "postfix": "vec",
            "body": [
                "vec![${receiver}]",
            ],
            "description": "vec![]",
            "scope": "expr",
        },
```
to your `rust-analyzer.completion.snippets` settings.
