### ISSUE TITLE
Block doc comments are not recognized properly

### ISSUE THREAD

**Issue by Purpzie** [rust-analyzer/rust-analyzer#7774]
This is related to #6873, but I've decided to post a new issue instead of a comment, since that only addresses syntax highlighting. I played around with it a bit, and it seems like block doc comments straight up aren't recognized properly.

![Capture](https://user-images.githubusercontent.com/25022704/108947962-274b9900-7627-11eb-9157-519ff7a210c2.PNG)

Also, indented block comments don't render correctly in tooltips.

![Capture](https://user-images.githubusercontent.com/25022704/108948006-3d595980-7627-11eb-8daa-462dbb688827.PNG)

**Comment by Veykril** [comment]
Well, technically they are recognized. Its just that we don't strip leading whitespace properly in them which causes codeblocks to not be recognized and tooltips to render incorrectly. But you are right in that this is potentially a different problem than highlighting iirc.

**Comment by Veykril** [comment]
The stripping of leading whitespace for such comments has to happen here https://github.com/rust-analyzer/rust-analyzer/blob/0537510aef4059d5f79146a8dc2734ffdb27dc74/crates/syntax/src/ast/token_ext.rs#L36-L56
