### ISSUE TITLE
Support #![feature(extended_key_value_attributes)]

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#7779]
Tracking issue: https://github.com/rust-lang/rust/issues/78835. I hope to replace `doc(include)` with this, and it would be nice for it to have IDE support.

![image](https://user-images.githubusercontent.com/23638587/109107863-7dd8d600-7700-11eb-87dd-f896956a826d.png)

**Comment by jyn514** [comment]
Tangentially related: this has pretty bad error recovery in the parser, maybe it could be improved somehow? 
![image](https://user-images.githubusercontent.com/23638587/109110052-60a60680-7704-11eb-8c94-6f43bc6b0931.png)

**Comment by Veykril** [comment]
Parsing implemented in #8097, given #8092 I think this can be closed
