### ISSUE TITLE
Chinese characters are shown as Unicode other than glyph when the doc comment included in a macro.

### ISSUE THREAD

**Issue by sanfusu** [rust-analyzer/rust-analyzer#7781]
Chinese characters are shown as Unicode other than glyph when the doc comment included in a macro.
![image](https://user-images.githubusercontent.com/34563541/109142808-4880c680-779a-11eb-9f75-caade9b71265.png)

But English doc comment will be OK.
![image](https://user-images.githubusercontent.com/34563541/109142949-6ea66680-779a-11eb-89df-445a9fca9ace.png)

The file's encoding is UTF-8.

**Comment by lnicola** [comment]
This seems to happen for any non-Latin character.
