### ISSUE TITLE
`convert_for_to_iter_for_each` shouldn't be applicable everywhere in a for loop

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#7784]
Currently no matter where the cursor is in a for loop node we show the assist. I feel like this is a bit too much.
It would probably be better to only show it when in the cursor is on the iterable itself.

**Comment by matklad** [comment]
closed by https://github.com/rust-analyzer/rust-analyzer/pull/7812#issuecomment-787496450
