### ISSUE TITLE
Support `pub use x as y;`

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#7788]
![image](https://user-images.githubusercontent.com/23638587/109187592-09ce1a80-7760-11eb-8501-fe4c0a0e13e4.png)

**Comment by Veykril** [comment]
I can't reproduce this 😕
![image](https://user-images.githubusercontent.com/3757771/109193911-26d30f80-7799-11eb-92ec-822e218fe14a.png)

**Comment by flodiebold** [comment]
Yeah, we support `pub use as`. Either there's some other thing going on in the code there, or this is an incremental update bug.

**Comment by lnicola** [comment]
Do you have any panics in the Output window?

**Comment by jyn514** [comment]
This was fixed by closing the tab and reopening it. I don't see any panics - maybe VSCode was caching the errors after I already fixed them?

**Comment by Veykril** [comment]
This was probably a desync issue/diagnostics not clearing properly.
