### ISSUE TITLE
`generated-foo` markers left in `package.json`

### ISSUE THREAD

**Issue by pojntfx** [rust-analyzer/rust-analyzer#7789]
## Symptoms

I tried to install the VSCode extension from Open-VSX on code-server, which runs into the following issue:

![Screenshot from 2021-02-25 19-06-17](https://user-images.githubusercontent.com/28832235/109196896-9696c980-779c-11eb-8c24-a738b6fe137e.png)

The extensions works flawlessly, despite the error.

## Reproduction

Occurs on a clean installation of Debian 10 (Docker container) plus the following additional commands:

```shell
apt update
apt install -y curl
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
. ~/.cargo/env
curl -fsSL https://code-server.dev/install.sh | sh
code-server --install-extension 'matklad.rust-analyzer' # From Open-VSX
code-server
```

Now visit [http://localhost:8080/](http://localhost:8080/). The message shows up whether a Rust project is open or not.

**Comment by lnicola** [comment]
I can't actually reproduce this (on Arch):

![image](https://user-images.githubusercontent.com/308347/109393803-654d0380-792c-11eb-90fa-4bc5642281c5.png)

**Comment by lnicola** [comment]
I actually manage to reproduce the error, but there's no stack trace. There's only one error:

[2021-02-27 18:52:23.785] [exthost] [error] [matklad.rust-analyzer] provider FAILED
[2021-02-27 18:52:23.785] [exthost] [error] Error: busy at semanticHighlightingWorkaround

So.. yeah, I'm not sure.

**Comment by iliakonnov** [comment]
Same issue when using remote connection over ssh. I've saved the log from DevTools, in case if it can help: https://gist.github.com/a7ce86f1799210139247f136aac45495

**Comment by lnicola** [comment]
This seems to come from https://github.com/microsoft/vscode/blob/a699ffaee62010c4634d301da2bbdb7646b8d1da/src/vs/workbench/api/common/configurationExtensionPoint.ts#L216.

Are we missing something from `package.json`?

**Comment by lnicola** [comment]
Argh. We have a couple of markers in `package.json`, `$generated-start` and `$generated-end`. They're left in when we package the extension, even in the Marketplace version.
