### ISSUE TITLE
No codelens on #[actix_rt::main] but has codelens on main

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#7790]
I opened an [issue](https://github.com/neoclide/coc.nvim/issues/2923) on coc.nvim side because it didn't retry after `textDocument/codeLens` failling like:

![image](https://user-images.githubusercontent.com/33961674/109243130-57f22500-7817-11eb-90a4-b1a49824bd58.png)

but today I find another interesting point which is:

1. it's hard to reproduce this on normal main function, I always have codelens run
```rust
fn main() {}
```

2. it's easy to reproduce this on main function which is generated by macro, like:
```rust
#[actix_rt::main]
async fn main() -> anyhow::Result<()> {}
```
it gives me `No codelens found` error. I can easily reproduce this behavior on medium sized project.

**Comment by flodiebold** [comment]
Attribute proc macros aren't supported yet: #6029
