### ISSUE TITLE
Type inferrence for Deref types ignores member visibility

### ISSUE THREAD

**Issue by ExoticMatter** [rust-analyzer/rust-analyzer#7841]
```rust
fn main() {
    let b = Box::new((Some(0),));
    let _ = b.0.as_ref();
}
```
Because `Box<_, _>.0` is private, `b.0` refers to the field of the boxed tuple. However, RA still infers `b.0` as `Unique<_>`, resulting in incorrect autocomplete as well as RA mistaking `Option::as_ref` for the unsafe `Unique::as_ref`.

The above code compiles, but RA suggests otherwise.

This appears to happen with any `Deref` type; the following code reproduces the issue with a custom type.

```rust
mod a {
    pub struct Foo(pub char);
    #[derive(Default)]
    pub struct Bar(i32);

    impl std::ops::Deref for Bar {
        type Target = Foo;

        fn deref(&self) -> &Foo {
            &Foo('z')
        }
    }
}

mod b {
    fn foo() {
        let x = super::a::Bar::default().0;
    }
}
```
RA shows the type hint `i32` for `x` instead of `char`.

rust-analyzer version: nightly (5df3ee8)
vscodium version: 1.53.2

**Comment by flodiebold** [comment]
I think this affects both fields and method resolution.
