### ISSUE TITLE
Function signatures are missing in auto-complete documentation tooltips

### ISSUE THREAD

**Issue by aloucks** [rust-analyzer/rust-analyzer#7842]
The function signature and it's arguments are missing from the doc tooltips. Only the return type is displayed.

![image](https://user-images.githubusercontent.com/221559/109567589-9a379280-7ab3-11eb-88a8-6d2dff15393f.png)

**Comment by kjeremy** [comment]
Weird... is this a recent regression?

**Comment by Veykril** [comment]
This change was deliberate by matklad if I recall correctly. But VSCode showed the `details` inline to the right of the name before I believe where this change made a lot of sense since then it was the `function signature` followed by the return type directly inline.
