### ISSUE TITLE
"proc macro process is closed" from `rust-analyzer diagnostics` CLI

### ISSUE THREAD

**Issue by kevinmehall** [rust-analyzer/rust-analyzer#7843]
I was trying to use the CLI instead of the language server to debug an issue with proc-macro expansion. With `rust-analyzer diagnostics . --load-output-dirs --with-proc-macro`, though, I'm seeing proc-macro expansion always fail with:

```
Diagnostic { message: "proc macro process is closed", range: 1..89, severity: Error, fix: None, unused: false, code: Some(DiagnosticCode("macro-error")) }
```

This turns out to be a different error than the one I was originally trying to debug. (I'll report that one once I can minimize the test case).

This error is emitted in `proc_macro_api::process::ProcMacroProcessSrv::send_task` because the `Arc::weak` to `sender` is already dropped. The strong reference is owned by `ProcMacroProcessThread`, which is owned by `ProcMacroClient`, which is kept in a local variable in `load_workspace` and was dropped when that function returned.

Cargo.toml:
```
[dependencies]
peg = "0.6"
```

main.rs:
```
peg::parser!(pub grammar foo() for str { });
fn main() {}
```

I thought I'd open an issue for anyone else seeing this message while trying to debug something else, but it's not much of a problem since it doesn't seem to happen in normal usage with the language server.

**Comment by edwin0cheng** [comment]
Thank you for the detailed report, it should be fixed in #7844.
