### ISSUE TITLE
regression on 2021-03-01release?

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#7855]
I use rust-analyzer together with coc-rust-analyzer, and recently I upgraded rust-analyzer from 2021-01-25 to 2021-03-01 release, then I start to notice some strange issues.

1. when I run codelens run, I started to have `0 references`, what is it for and how should I use it? 
![image](https://user-images.githubusercontent.com/33961674/109737724-7aae8000-7c01-11eb-9123-1241280b65ec.png)

2. some autoimports missing, I cannot reproduce it by using 2021-01-25 release
  ![image](https://user-images.githubusercontent.com/33961674/109737944-e4c72500-7c01-11eb-996f-01ae38165ddd.png)
  here `AggregatorCmd` is not imported but I don't have the suggest item for importing it. I used to have it in 2021-01-25 release
    ![image](https://user-images.githubusercontent.com/33961674/109738256-75056a00-7c02-11eb-8c8c-8e079a9c81dc.png)

**Comment by lnicola** [comment]
> when I run codelens run, I started to have 0 references, what is it for and how should I use it?

It's a code lens showing the number of references to the function. Invoking it should call "find all references". It can be disabled.

> some autoimports missing

Does that happen in functions with macro calls?

**Comment by GopherJ** [comment]
@lnicola no it's not with macro calls

**Comment by GopherJ** [comment]
BTW, after upgrading to 2021-03-08, I also started to have zoombie errors as described here: https://github.com/fannheyward/coc-rust-analyzer/issues/658

**Comment by GopherJ** [comment]
any help on this? I would like to use latest release but it seems something btoken

**Comment by lnicola** [comment]
If would help if you could prepare a small example showing the problem.

**Comment by GopherJ** [comment]
@lnicola Hi, I've tried `2021-03-22` since the last friday and it was working perfectly, so I'll close this issue as it may be just an issue of `2021-03-01`
