### ISSUE TITLE
[feature request] Make auto-import order configurable

### ISSUE THREAD

**Issue by asv1** [rust-analyzer/rust-analyzer#7885]
I think it be nice to have option in config to turn off ordering during auto-import.

**Comment by Veykril** [comment]
Relevant code is here https://github.com/rust-analyzer/rust-analyzer/blob/3d662e320b97fdc50d8cc1721983661900da22d3/crates/ide_db/src/helpers/insert_use.rs#L538-L598

**Comment by SomeoneToIgnore** [comment]
Or could that be that you've meant the order of the completion items, suggested during the completion?

We have https://github.com/rust-analyzer/rust-analyzer/issues/4922 and https://github.com/rust-analyzer/rust-analyzer/issues/4544 to track this.

**Comment by Veykril** [comment]
In this case they mean import insertion as they asked here earlier https://github.com/rust-analyzer/rust-analyzer/issues/3301#issuecomment-790851507

**Comment by asv1** [comment]
@SomeoneToIgnore 
No, i am about auto import order not completion.

**Comment by asv1** [comment]
Fixed by #7889
