### ISSUE TITLE
autocomplete options does not appear

### ISSUE THREAD

**Issue by patrickelectric** [rust-analyzer/rust-analyzer#7897]
I did a simple repository if someone wants to replicate the problem: 
https://github.com/patrickelectric/vscode-autocomplete-problem/blob/master/src/main.rs#L7

In 3 different computers I was unable to make rust-analyzer to work with it.
I'm using rust-analyzer (v0.2.497) directly from vscodium (1.53.2).

![image](https://user-images.githubusercontent.com/1215497/110221482-5249ae80-7eab-11eb-8000-6044023e9048.png)
![image](https://user-images.githubusercontent.com/1215497/110221558-a0f74880-7eab-11eb-8d10-07b80b9f9ce9.png)

**Comment by jonas-schievink** [comment]
Does it work if you enable "load out dirs from check"?

**Comment by patrickelectric** [comment]
I did try both `rust-analyzer.cargo.loadOutDirsFromCheck` and `rust-analyzer.procMacro.enable` without success

**Comment by lnicola** [comment]
Confirmed. Looks like some `include!` shenanigans might be going on.

**Comment by lnicola** [comment]
That's actually `rust-analyzer.cargo.runBuildScripts` (I thought it was enabled by default). But no, it doesn't help.

**Comment by patrickelectric** [comment]
Reading the sourcing code and doing some debug from rust-analyzer, it appears that cargo environment variables are not supported at all.
https://github.com/rust-analyzer/rust-analyzer/blob/30402beeb200fe85bd7595a6a8e6efdb81ede2b5/crates/hir_expand/src/builtin_macro.rs#L434-L448

Taking a closer look on:
https://github.com/rust-analyzer/rust-analyzer/blob/30402beeb200fe85bd7595a6a8e6efdb81ede2b5/crates/hir_expand/src/builtin_macro.rs#L418-L421

My debug showed that it was always empty and there was nothing in `db.crate_graph()[krate].env`.

Doing research over cargo, it appears that cargo OUT_DIR variable may not be possible at all to get:
https://github.com/rust-lang/cargo/issues/7546

For you that is reading this in the future, if you are generated stuff under `OUT_DIR`, it may be a good alternative to generated under a path such as `src/generated`, and with that you can do `include!` without using `OUT_DIR`.

**Comment by jonas-schievink** [comment]
mavlink does not seem to be using `OUT_DIR`

**Comment by jonas-schievink** [comment]
Ah, this might be due to https://github.com/rust-analyzer/rust-analyzer/issues/7846

**Comment by patrickelectric** [comment]
> mavlink does not seem to be using `OUT_DIR`

[I just changed it](https://github.com/mavlink/rust-mavlink/commit/7ccf8963dd53b9a4f524b61b004403a56d7d7956#diff-c293c79035ce2e3cc1c1eb67a02c2b9875d12eb8ddf7760e0154f5d79a4db064).

Though, projects that depends of rust-mavlink are still not working with that change, but inside the project the autocomplete now works. 

rust-mavlink master branch:
![image](https://user-images.githubusercontent.com/1215497/110243609-e7938400-7f39-11eb-92f1-610e40881792.png)
> It is still inconsistent, some time works and sometimes doesn't


example vscode-autocomplete-problem:
![image](https://user-images.githubusercontent.com/1215497/110243438-18bf8480-7f39-11eb-8b0d-cca044a0b24e.png)

**Comment by flodiebold** [comment]
@patrickelectric `OUT_DIR` should work fine as long as you've enabled `rust-analyzer.cargo.loadOutDirsFromCheck` (hence the name) or the new `rust-analyzer.cargo.runBuildScripts`.

**Comment by patrickelectric** [comment]
It's enabled and not working:
![image](https://user-images.githubusercontent.com/1215497/110243823-cbdcad80-7f3a-11eb-96a1-22cb4f94d280.png)

`rust-analyzer.cargo.runBuildScripts` does not show here for me, I'm using the latest 0.2.487. Is that available somewhere to test ?

**Comment by bjorn3** [comment]
`rust-analyzer.cargo.loadOutDirsFromCheck` is what it is called on the stable weekly builds. It has been renamed to `rust-analyzer.cargo.runBuildScripts` on nightly with the old name being accepted as alias.

**Comment by flodiebold** [comment]
@patrickelectric what does `cargo check --message-format=json | grep build-script-executed` say?

**Comment by patrickelectric** [comment]
> @patrickelectric what does `cargo check --message-format=json | grep build-script-executed` say?

<details>
{"reason":"build-script-executed","package_id":"libc 0.2.88 (registry+https://github.com/rust-lang/crates.io-index)","linked_libs":[],"linked_paths":[],"cfgs":["freebsd11","libc_priv_mod_use","libc_union","libc_const_size_of","libc_align","libc_core_cvoid","libc_packedN","libc_cfg_target_vendor"],"env":[],"out_dir":"/home/patrick/git/patrick/vscode-autocomplete-problem/target/debug/build/libc-cf127cddf224d515/out"}
{"reason":"build-script-executed","package_id":"proc-macro2 1.0.24 (registry+https://github.com/rust-lang/crates.io-index)","linked_libs":[],"linked_paths":[],"cfgs":["lexerror_display","hygiene","use_proc_macro","wrap_proc_macro"],"env":[],"out_dir":"/home/patrick/git/patrick/vscode-autocomplete-problem/target/debug/build/proc-macro2-3498c16925406714/out"}
{"reason":"build-script-executed","package_id":"syn 1.0.62 (registry+https://github.com/rust-lang/crates.io-index)","linked_libs":[],"linked_paths":[],"cfgs":["syn_disable_nightly_tests"],"env":[],"out_dir":"/home/patrick/git/patrick/vscode-autocomplete-problem/target/debug/build/syn-e4255a1c653518e2/out"}
{"reason":"build-script-executed","package_id":"serde_derive 1.0.124 (registry+https://github.com/rust-lang/crates.io-index)","linked_libs":[],"linked_paths":[],"cfgs":["underscore_consts"],"env":[],"out_dir":"/home/patrick/git/patrick/vscode-autocomplete-problem/target/debug/build/serde_derive-50d3257b96e1e96e/out"}
{"reason":"build-script-executed","package_id":"serde 1.0.124 (registry+https://github.com/rust-lang/crates.io-index)","linked_libs":[],"linked_paths":[],"cfgs":["ops_bound","core_reverse","de_boxed_c_str","de_boxed_path","de_rc_dst","core_duration","integer128","range_inclusive","num_nonzero","serde_derive","core_try_from","num_nonzero_signed","systemtime_checked_add","std_atomic64","std_atomic"],"env":[],"out_dir":"/home/patrick/git/patrick/vscode-autocomplete-problem/target/debug/build/serde-73ca5304cca9ae09/out"}
{"reason":"build-script-executed","package_id":"bitflags 1.2.1 (registry+https://github.com/rust-lang/crates.io-index)","linked_libs":[],"linked_paths":[],"cfgs":["bitflags_const_fn"],"env":[],"out_dir":"/home/patrick/git/patrick/vscode-autocomplete-problem/target/debug/build/bitflags-f9113967e336fcbe/out"}
{"reason":"build-script-executed","package_id":"num-traits 0.2.14 (registry+https://github.com/rust-lang/crates.io-index)","linked_libs":[],"linked_paths":[],"cfgs":["has_i128","has_to_int_unchecked"],"env":[],"out_dir":"/home/patrick/git/patrick/vscode-autocomplete-problem/target/debug/build/num-traits-9247bc1ce3fdb48a/out"}
{"reason":"build-script-executed","package_id":"mavlink 0.8.6 (registry+https://github.com/rust-lang/crates.io-index)","linked_libs":[],"linked_paths":[],"cfgs":[],"env":[],"out_dir":"/home/patrick/git/patrick/vscode-autocomplete-problem/target/debug/build/mavlink-2f7d07fb4a9be9fc/out"}

</details>

**Comment by jonas-schievink** [comment]
`OUT_DIR` is not the problem here, I suspect what's happening is that all `include!`s in `src/generated/mod.rs` fail to resolve due to https://github.com/rust-analyzer/rust-analyzer/issues/7846. This also explains why all submodules show up but are empty, since they're declared inline and use `include!` to pull in their content (`mod` should work just as well here though?).

**Comment by patrickelectric** [comment]
> `mod` should work just as well here though?

Yep, thanks for the feedback.
But it did not work, autocomplete is still not working:
https://github.com/patrickelectric/rust-mavlink/commit/2a2a908459ad5fd258e662ffe564deb5b67ba014

**Comment by jonas-schievink** [comment]
Yes, the only way to work around this bug is to only generate a single file. Once #7846 is fixed, what you have now should start working as-is.

**Comment by edwin0cheng** [comment]
#7846 is fixed, and I tested in `rust-mavlink` project from master and it seem to work now. @patrickelectric could you test it again ?

**Comment by patrickelectric** [comment]
Yep, I can confirm that it works, just downloaded https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-03-22 with:
```json
  "rust-analyzer.cargo.runBuildScripts": true,
  "rust-analyzer.lruCapacity": 1024,
  "rust-analyzer.procMacro.enable": true,
  "rust-analyzer.cargo.allFeatures": true,
```
![image](https://user-images.githubusercontent.com/1215497/112021120-b3aa8800-8b0f-11eb-807b-f1d48affb744.png)

**Comment by patrickelectric** [comment]
Thank you everybody for your patience and time!

**Comment by lnicola** [comment]
Heads-up: build scripts and proc macros are now enabled by default.
