### ISSUE TITLE
Renames from renaming modules gets applied twice

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#7916]
https://user-images.githubusercontent.com/308347/110324810-2bac8480-801f-11eb-8b57-4770d4e2e5a5.mp4

**Comment by lnicola** [comment]
https://user-images.githubusercontent.com/308347/110325009-74643d80-801f-11eb-99ab-7b8d51fbd83b.mp4

**Comment by Veykril** [comment]
I don't think the problem is the underscore, but the fact that the rename turns the name into a longer string. This feels like we are doing a double replacement somewhere. Renaming something to something shorter also drops the semicolon as shown in your second mp4.

**Comment by Veykril** [comment]
The vscode preview doesn't show the erroneous renames though so I feel like this happens on our typescript side(its also most likely my fault)

**Comment by Veykril** [comment]
Hm, actually no renames don't even seem to go through `resolveCodeAction` or `applySnippetWorkspaceEditCommand` 😕

**Comment by Veykril** [comment]
Found the culprit, when renaming a module(at least in vscode) the client sends a rename request but also a `WillRenameFiles` request for the renamed files for which we reply to with a second set of renames which both get applied.

**Comment by Veykril** [comment]
@kjeremy maybe you have an idea, im not sure how this is supposed to be handled or whether this is a bug in vscode. My only idea would be to drop source renames from rename requests for modules when the client suppose `WillRenameFiles`?

**Comment by kjeremy** [comment]
This sounds like a bug. I thought that `WillRenameFiles` only triggered if one was ie renaming files in the explorer view of vscode and not executing a `textDocument/rename` request.

Specifically that's how I interpret "The will rename files request is sent from the client to the server before files are actually renamed as long as the rename is triggered from within the client."

See: https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#workspace_willRenameFiles

**Comment by Veykril** [comment]
Opened an issue for clarification https://github.com/microsoft/vscode-languageserver-node/issues/752

**Comment by dbaeumer** [comment]
As comment in microsoft/vscode-languageserver-node#752 this is expected (that you get the event on a workspace edit). Otherwise another extension / server couldn't react to a rename trigger via a workspace edit.
