### ISSUE TITLE
`use foo::bar` is overridden by dependency named `bar`

### ISSUE THREAD

**Issue by Diggsey** [rust-analyzer/rust-analyzer#7919]
One of my files has an import with the same name as one of my dependencies:
```rust
use permissions::jwt;
```
(dependency named `jwt`)

The following code is shown as an error by RA:
```rust
let claims = jwt::Claims { ... };
```

Because it thinks `Claims` is coming from the `jwt` crate, when in fact it should come from the `permissions::jwt` module. Rustc compiles the code without any warnings or errors.

This is using the current nightly version of RA (2021-03-08)

**Comment by jonas-schievink** [comment]
Reproduction:

```rust
//- /lib.rs crate:lib deps:jwt
mod permissions;

use permissions::jwt;

fn f() {
    fn inner() {}
    jwt::Claims {};
}

//- /permissions.rs

pub mod jwt  {
    pub struct Claims {}
}

//- /jwt/lib.rs crate:jwt
pub struct Claims {
    field: u8,
}
```

**Comment by Diggsey** [comment]
Thanks!
