### ISSUE TITLE
No completion on new file unless linked to the main.rs

### ISSUE THREAD

**Issue by JDuchniewicz** [rust-analyzer/rust-analyzer#7937]
I have no completion on a new `.rs` file unless I add a `mod foo;` to `main.rs.` I am running multiple buffers in vim and I open a new file with `:e foo.rs` and then save it.

**Comment by SaiintBrisson** [comment]
This happens because rust-analyzer does not know where the file belongs if it is not specified in an existing module, and the file isn't necessarily used in the package. I don't think this is an issue, could be wrong though.

**Comment by bjorn3** [comment]
I believe there is an existing issue about improving this case, but I can't find it.

**Comment by SaiintBrisson** [comment]
> I believe there is an existing issue about improving this case, but I can't find it.

https://github.com/rust-analyzer/rust-analyzer/issues/6377#issue-729861893 probably this one

**Comment by flodiebold** [comment]
Yes, #6377 plus also #6388 would help.

**Comment by JDuchniewicz** [comment]
Sorry could not find it. Thanks for linking that though!
