### ISSUE TITLE
CompletionItem Builder should use `&mut` methods

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#7946]
We should change these methods from `self -> Self` to `&mut self -> &mut Self`:

https://github.com/rust-analyzer/rust-analyzer/blob/c45ac6effe37562daa97e6675c54963252f65664/crates/ide_completion/src/item.rs#L368-L439

I think its better to do a PR for method.

**Comment by yonip23** [comment]
Hi, I would like to take over this issue :smiley: 
I'm not sure I understand what is the change that you want, is it something like that?
```rust
 pub(crate) fn lookup_by(&mut self, lookup: impl Into<String>) -> &mut Self {
        self.lookup = Some(lookup.into());
        self
    }
```

**Comment by Veykril** [comment]
Yep, that's what this issue wants 👍 
And as asked, its best to do one PR per method changed, to keep the diff smaller.

**Comment by SomeoneToIgnore** [comment]
we don't enforce zero clippy warnings, more info can be fond here: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/style.md#clippy and around, do check them out for more info on the development process.

`cargo test` should be enough given that you write some tests on your functionality 😄 
You can always build from your sources and install the server locally to test it yourself, see https://rust-analyzer.github.io/manual.html#manual-installation and the next item for building from source.

**Comment by yonip23** [comment]
Hi @Veykril @SomeoneToIgnore @matklad or anyone else,
I started changing `lookup_by` and I think that it would be better to change all of these methods together, because changing only one of them leads to an unnecessary `&mut` prefixes, like so:
![image](https://user-images.githubusercontent.com/67855609/110777443-cac4bc80-8269-11eb-8644-3d9d7e6443c8.png)

Thoughts?

**Comment by Veykril** [comment]
That's a good point, I guess doing them at once might be better after all.

**Comment by SomeoneToIgnore** [comment]
Closed in https://github.com/rust-analyzer/rust-analyzer/pull/7974
