### ISSUE TITLE
RA crash when calling println! in proc-macro

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#7954]
Hello, I came across this issue while tinkering with one of my own macros. It seems the use of a `println!()` in a derive macro causes it to happen:

```rust
#[proc_macro_derive(Hello)]
pub fn hello(_: proc_macro::TokenStream) -> proc_macro::TokenStream {
    println!("fail"); // This will cause the error
    proc_macro::TokenStream::new()
}
```
I'm using rustc 1.5.0 & RA v0.2.513

_Originally posted by @pauldorehill in https://github.com/rust-analyzer/rust-analyzer/issues/7103#issuecomment-794577271_

**Comment by jonas-schievink** [comment]
Haha, is the output just going straight through the IPC interface?

**Comment by edwin0cheng** [comment]
I think so !! :)

**Comment by flodiebold** [comment]
Is this something we can or want to fix? It seems to me that proc macros printing on stdout are a bad idea in general (e.g. this would also be bad for anything that makes rustc output JSON and tries to parse that).

**Comment by pauldorehill** [comment]
Using `println!` / `eprintln!` is useful for debugging macros that don't work: getting a message that the macro server crashed can be at bit misleading... it can make you think that some of the code you changed has caused something to go very wrong even if the macro is working 🙃 

As an aside if you use `eprintln!` the console prints all the vscode error json `fail{"message":"struct is never constructed: ...}`

**Comment by flodiebold** [comment]
Yes, eprintln is fine, println isn't.

**Comment by flodiebold** [comment]
> I believe it ignores any lines that don't start with {.

That's something we could do as well, isn't it? (We could even collect those lines and show them somewhere...)
