### ISSUE TITLE
VS code extension doesn't work

### ISSUE THREAD

**Issue by suhr** [rust-analyzer/rust-analyzer#796]
On the `run` command I get this error:

> `Cannot read property 'code2ProtocolConverter' of undefined`

On `status` I get this error:

> `cannot open rust-analyzer-status://status. Detail: Cannot read property 'sendRequest' of undefined`

VS Code version: 1.30.2

**Comment by DJMcNab** [comment]
Are there any other error messages in the output channel. This is probably my fault - sorry!

**Comment by matklad** [comment]
This means that something on the typescript side dies. I think running the extension under debug should show a useful stacktrace. 

I *think* we might be using some stuff from VS Code 1.31.0 so updating VS Code might be a good idea as well.

**Comment by kjeremy** [comment]
I don't think we explicitly use any new features but I did update some of the dependencies for node 10 which is what shipped with 1.31. That may be causing the problem. It also looks like we're using a beta of the `vscode-languageclient` package but that should only be additive to the feature set. Definitely try updating to 1.31.

**Comment by suhr** [comment]
Updating to 1.31 indeed helps.

**Comment by matklad** [comment]
Glad to head that! Will add "needs the most recent version of VS Code" to the readme!
