### ISSUE TITLE
Import disambiguation regression

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#7962]
I got this popup when using the "Import `Weak`" assist on a `Weak` identifier:

![screenshot-2021-03-10-17:41:15](https://user-images.githubusercontent.com/1786438/110664652-e37c9600-81c7-11eb-8651-a77961f0c095.png)

The first one here refers to `std::rc::Weak`, the second to `std::sync::Weak`, but for some reason only the name, not the full path, is shown.

**Comment by SomeoneToIgnore** [comment]
Should be fixed in https://github.com/rust-analyzer/rust-analyzer/pull/7957 , could you confirm?

**Comment by jonas-schievink** [comment]
Yup, that fixes it. Thanks!
