### ISSUE TITLE
Inline quick fix for importing types within a crate is not working for "no more mod.rs" Rust 2018 modules - regression.

### ISSUE THREAD

**Issue by staninprague** [rust-analyzer/rust-analyzer#7963]
Thank you for the great tool! I'm facing rather a strange problem. I believe that rust-analyzer was capable of offering an inline Quick-Fix for importing a type from the crate (adding use and merging it nicely with other uses).

I now updated to the latest version of rust-analyzer and meanwhile vscode got updated to the February update as well.

Now the import quick fix for the std types works as it used to:

![rust-analyzer-import](https://user-images.githubusercontent.com/3834343/110668436-9a2e4580-81cb-11eb-8ebd-37f9f64a2e4f.jpg)

Or for example, here is the quick-fix from the problems panel:

![import-quick-fix-in-problems](https://user-images.githubusercontent.com/3834343/110669153-58ea6580-81cc-11eb-8fdf-a9eedbddae06.jpg)

But here is the inline quick fix for the **type from the same crate**:

![import-own-type](https://user-images.githubusercontent.com/3834343/110670457-b337f600-81cd-11eb-89ee-6a983aa05c3e.jpg)

For my own/crate types inline Quick-fix is not offered. For the problems panel, it works differently from what it used to be:

![import-own-file](https://user-images.githubusercontent.com/3834343/110669501-aebf0d80-81cc-11eb-8430-7cf0417c86c1.jpg)

"Consider importing this struct" is the last suggestion and tapping on this line actually works in a way that cursor goes to the top of the screen, blue quick fix hint is shown, tapping on it shows "consider importing this struct", tapping on the suggestion adds line with a "use" to the top of the file.

But it used to work for the crate types in the same way as it was working for the std types?

I re-installed vscode, rust-analyzer, tried several weeks old rust-analyzer version, tried older version of vscode, but I can't get rust-analyzer to help me import types from my own crate.

I should have messed with the settings somehow, but now I'm having the fresh settings after re-installing everything and still there is no nice auto-import and inline quick fix for the types from the same crate.

What I can be missing?

**Comment by flodiebold** [comment]
The "a struct with a similar name exists" comes from rustc. We should hide rustc's suggestion if we have a better one, similar to the case in #7936.

That said, the question is if we do have an autoimport for `PointCollectionSyncRecord`. In general the autoimport code action should still work as before, also for types in the same crate. Do you have a simple example repo where the suggestion doesn't show up?

**Comment by staninprague** [comment]
Looks like really depends on many factors, here is for example how I think it would work before. It would recognize that type can be imported, plus offer all others suggestions:

![another-one-import](https://user-images.githubusercontent.com/3834343/110673857-94d3f980-81d1-11eb-9e89-18cfc28db72b.jpg)

Now, when inside a method, inline quick fix is not recognizing that the own crate type can be imported.

**Comment by flodiebold** [comment]
Do you happen to have a macro call in your method where it doesn't work? Can you try it in an empty method?

**Comment by staninprague** [comment]
I think I'm getting closer to the root cause of the problem. Based on your suggestion I tried some github projects and they seem to work ok for the auto-import and inline import quick-fix.
I tried to look for what is different and here is what I think the problem is:

If modules are setup in the "no more mod.rs", Rust 2018, way: https://doc.rust-lang.org/nightly/edition-guide/rust-2018/module-system/path-clarity.html#no-more-modrs:

![no-more-mod](https://user-images.githubusercontent.com/3834343/110677489-82f45580-81d5-11eb-912d-fd337077750c.jpg)

Then there is a problem with inline import quick-fix for own crate types.

This is not how it used to work before. I actually used rust-analyzer with a great joy to move to that "no more mod.rs" in a few places.

If modules follow the mod.rs conventions inline import quick-fix is working alright. If modules follow "no more mod.rs" convention - inline import quick fix is lost inside the methods. I tried in several places to confirm.

To clarify:

Module following "no more mod.rs" convention can't use rust analyzer to import crates that are located in the same crate. Quick-fix import is not working in such a "no more mod.rs" modules.

Should I better create a bug?

**Comment by flodiebold** [comment]
That's surprising to me; rust-analyzer itself uses this convention everywhere. Just to make sure, you're still declaring `bar` in `foo.rs` with `mod bar`, right? Can you reproduce this with a minimal setup?

**Comment by staninprague** [comment]
> Just to make sure, you're still declaring bar in foo.rs with mod bar, right?

True. It looks like this:

![no-more-mod-1](https://user-images.githubusercontent.com/3834343/110681962-aec60a00-81da-11eb-9aec-4e5046c5f0ab.jpg)

Quick fix import is not working inside methods of add.rs and pull.rs. Interestingly enough it is working outside of methods in these files!

Inline/Problems import quick-fix used to work as I was using rust-analyzer 3 weeks ago to re-organize a few places into "no more mod.rs" and re-factoring exactly these places with import quick-fix. Now all of these "no more mod.rs" modules are not showing import quick fixes. Actually they do, but not for the types from the crate, std types continue to invoke import quick fix.

I'll try to isolate the problem by having an empty project, but can't tell when I'd get to this.

**Comment by staninprague** [comment]
I tested in more places and I have only one place when the issue holds true. Importing hints work alright in other places with the "no more mod.rs" structure.  I'll try to experiment more to find what is the difference in the folders/modules that is causing the problem.

**Comment by lnicola** [comment]
Probably fixed in #10872. Tested with the code in https://github.com/rust-analyzer/rust-analyzer/issues/7963#issuecomment-953567521.
