### ISSUE TITLE
Rename symbol skips naked enum variants in match arms

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#7968]
In this code:

```rust
fn foo() {
    use Foo::{Bar, Baz};

    let foo = Bar;
    match foo {
        Bar => println!("bar"),
        Baz => println!("baz"),
    }
}

enum Foo {
    Bar,
    Baz,
}
```

If I try to rename the `Foo::Bar` enum variant, the `Bar` in the match arm doesn't change with it. Pretty sure it should?

(Tested with currently nightly in VS Code, using the "Rename Symbol" context menu item.)

**Comment by Veykril** [comment]
This seems to work fine for me on current nightly :confused: 
![mRxuBq6a8O](https://user-images.githubusercontent.com/3757771/110694986-9e695b80-81e9-11eb-824a-e063d410309e.gif)

**Comment by djc** [comment]
Hmm, that's weird. Can you try renaming `RSA` in https://github.com/ctz/rustls/blob/main/rustls/src/msgs/enums.rs#L45?

**Comment by djc** [comment]
Similarly, I tried to rename `TLSError` to `TlsError` in https://github.com/ctz/rustls/blob/main/rustls/src/error.rs#L161 and it changes the import on line 161 but failed to change any of the variants in 176-189.

**Comment by djc** [comment]
Just to check, I'm currently running v0.3.446-nightly.

**Comment by Veykril** [comment]
Ah, current nightly is 0.3.515. I think you might have to reinstall the plugin if I recall correctly we had a problem with autoupdating which might got you stuck on that version 😅

**Comment by Veykril** [comment]
I did test renaming `RSA` though, in the macro the rename doesnt do anything(it doesnt even send the request interestingly), renaming a usage works though and it seems to catch all usages in the crate so updating should fix this for you I imagine.

**Comment by Veykril** [comment]
Alright, also managed to find and fix another bug thanks to this 😄
