### ISSUE TITLE
Add type ascription should add a semicolon

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#7971]
![semi](https://user-images.githubusercontent.com/1711539/110772441-aae2c800-826c-11eb-8fe7-89fc1ce399d2.gif)

I think adding `;` would be a nice touch here

cc https://github.com/rust-analyzer/rust-analyzer/pull/7824, @conradludgate

**Comment by conradludgate** [comment]
Good catch. I'll get a PR and some tests for that later today
