### ISSUE TITLE
Can't make a newline with `Enter` when ra-lsp is enabled

### ISSUE THREAD

**Issue by suhr** [rust-analyzer/rust-analyzer#798]
<kbd>Ctrl</kbd><kbd>Enter</kbd> works but it's annoying.

**Comment by matklad** [comment]
I think this is the symptom of https://github.com/rust-analyzer/rust-analyzer/issues/796

Otherwise, there's a `rust-analyzer.enableEnhancedTyping` setting that controls this behavior.
