### ISSUE TITLE
Performance regression in #7813

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#7983]
This looks like it might have regressed the analysis performance (from 48 to 75 seconds):

![image](https://user-images.githubusercontent.com/308347/109501299-1627df80-7aa0-11eb-8d86-d546a181ea30.png)

_Originally posted by @lnicola in https://github.com/rust-analyzer/rust-analyzer/issues/7813#issuecomment-787936638_

**Comment by matklad** [comment]
@flodiebold do you think we might close this? As far as I know, the status is:

* we don't exactly know why the regression happened
* but we clawed back most of the perf anyway

**Comment by flodiebold** [comment]
Yes, let's close it.
