### ISSUE TITLE
rust-analyzer hangs when using crate proptest

### ISSUE THREAD

**Issue by soenkehahn** [rust-analyzer/rust-analyzer#7987]
I'm using rust-analyzer from within vscode through the `rust-analyzer` extension. I ran into an issue where it hangs when using the crate [proptest](https://crates.io/crates/proptest). Here's a minimal example:

https://github.com/soenkehahn/ra-bug

Opening `src/main.rs` in vscode makes the rust-analyzer extension hang. Also, the process `~/.config/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu` keeps using one cpu afterwards, even when quitting vscode. I have to manually kill it to get rid of it.

Here's what I'm using:
ubuntu 20.10
vscode 1.54.2
matklad.rust-analyzer 0.2.513
rust-analyzer d54e115

Please, let me know if I can provide more information! Thanks a lot for working on rust-analyzer!!! :)

**Comment by jhpratt** [comment]
Related? #7953

**Comment by soenkehahn** [comment]
@jhpratt: Maybe. It sounds similar. In my case indexing often works fine. I.e. I have a bigger project where I'm also using the `proptest` crate, and -- if I'm not working on those tests -- rust-analyzer usually works fine. Just when touching the `proptest` related code, it often starts hanging. #7953 sounds like it always hangs, and never works. Still might be related of course.

**Comment by edwin0cheng** [comment]
In OP case, it is because we are not handling some ill-form macro properly, which cased a infinite-loop.

#8005 should fix it.

**Comment by soenkehahn** [comment]
Hi @edwin0cheng! Can confirm, this seems to be fixed. Just tested with current master (commit af8440b84). Thanks a lot!
