### ISSUE TITLE
Feature Requests: add function "test function at cursor" 

### ISSUE THREAD

**Issue by davyzhang** [rust-analyzer/rust-analyzer#799]
Go extension has this fine feature that will run the test for the function where the cursor is placed.
The test functions are bind by name conventions:
fn foo(){}
fn test_foo(){}

I also think a command that can run an arbitrary test by name would be nice, it will save time jumping from and to test will doing a quick modification.

**Comment by matklad** [comment]
That already exists! Command is **Rust Analyzer: Run`.

**Comment by matklad** [comment]
>it will save time jumping from and to test will doing a quick modification.

**Run Analyzer: Run** allows you to run "previous" test, so this should be covered as well. In general, **Run** should work directly from "worksapce symbols" pane, but I think this is impossible to do atm, given existing VSCode API.

**Comment by davyzhang** [comment]
Thanks so much for your work!
