### ISSUE TITLE
What's up with attributes?

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#8]
I have no idea how the attribute grammar should look like. Is it still key-value pairs, or have we gone full token-trees? The letter would be unfortunate: token trees means zero support from IDEs: no extend selection for cases like `#[foo= 1 + 2 + 3]`, because we don't know that 1 + 2 + 3 is an exression.

**Comment by mystor** [comment]
The answer is that an attribute can contain arbitrary token trees (though that's behind a feature flag right now). That being said, most attributes take the form of a "Meta". (e.g. in syn: https://docs.rs/syn/0.12.3/syn/enum.Meta.html). I imagine that we could add support, like in `syn`, a mechanism for interpreting the token trees as an `Option<Meta>`. IDEs could then take advantage of meta-like attributes to provide good support.

**Comment by matklad** [comment]
Great! Is there any RFC for this? I know about RFC for meta(and this is what currently suppported here) but token trees in the source code were a surprise for me.

Pinning down structure of attributes to meta is very useful, because you actually can show syntax errors...

**Comment by mystor** [comment]
It's part of the procedural macros work. See https://github.com/rust-lang/rust/pull/40346 for the commentary on the PR to rustc.

**Comment by matklad** [comment]
Excellent, thanks a lot @mystor for this and for other comments as well, they are really helpful! :heart:
