### ISSUE TITLE
Can not complete nested Vec with structs

### ISSUE THREAD

**Issue by davyzhang** [rust-analyzer/rust-analyzer#800]
rustc --version
rustc 1.32.0 (9fda7c223 2019-01-16)

![image](https://user-images.githubusercontent.com/576863/52617776-e23cea00-2ed7-11e9-9b0b-eda257eccaaf.png)

**Comment by matklad** [comment]
I think those completions come from RLS, not from rust-analyzer: we don't handle that much of type inference yet to suggest `to_vec` :laughing:

**Comment by davyzhang** [comment]
Yep, that is from rls, which is not correct also. Right now I have to install two of these extensions to try my luck on code completion 😉

**Comment by davyzhang** [comment]
Why is this issue closed? I've tested the latest extension, there's no proper completion for this test case

**Comment by matklad** [comment]
It’s a not too actionable issue: we are aware that significant chunks of compiler smarts (like trait solving) are completely missing at the moment, and that manifests itself, for example, as missing completion variants.

**Comment by davyzhang** [comment]
Understood, thanks so much for your efforts.
