### ISSUE TITLE
Add semantic token modifier for items from traits

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#8024]
I think it’s helpful that rust-analyzer currently allows differentiating the highlighting of traits, as they are ‘special’ and often deserve more attention than the rest of the code. Continuing this, I think it would be even more helpful to highlight items that originate from traits, too. For example:

```rust
struct Cat;

trait Animal {
    const SOUND: &'static str; // ‘SOUND’ is given modifier

    fn make_sound(&self) { // ‘make_sound’ is given modifier
        println!("{}", Self::SOUND); // ‘SOUND’ is given modifier
    }
}

impl Animal for Cat {
    const SOUND: &'static str = "Meow!"; // ‘SOUND’ is given modifier
}

fn main() {
    let cat = Cat;
    cat.make_sound(); // ‘make_sound’ is given modifier
    let _sound = Cat::SOUND; // ‘SOUND’ is given modifier
}
```

The same would apply to associated types that come from traits.

Maybe the semantic token modifier `abstract` could be used? This terminology isn’t used in Rust, though, so that’s definitely up for debate.

**Comment by Veykril** [comment]
`abstract` are usually things that requires the implementor to give an implementation in other languages right? I don't think that fits too well in this case then. Technically we could reuse `trait` as a modifier I think? We do that with `attribute` as well.

**Comment by arzg** [comment]
- [x] Methods (#8024)
- [ ] Associated constants
- [ ] Associated types

**Comment by chetankhilosiya** [comment]
Associated constants is also done with (#8240).
Associated types is remaining.

**Comment by arzg** [comment]
Thank you so much @chetankhilosiya for your work on this issue :)

I’m happy to report that the example from earlier is working on the nightly channel (everything in `#ff0000` is from a trait):

<img alt="Screen Shot 2021-04-09 at 1 20 42 pm" src="https://user-images.githubusercontent.com/31783266/114123788-65322180-9936-11eb-8246-40b984e06396.png">
