### ISSUE TITLE
Add benchmark suite hash to the metrics JSON

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#8031]
We should add this hash to JSON we publish to the metrics repo, so that it's easy to see when we update the test suite.

_Originally posted by @matklad in https://github.com/rust-analyzer/rust-analyzer/pull/8030#discussion_r594412711_

**Comment by d2weber** [comment]
I took the opportunity to start with this issue and submitted a pull request.

**Comment by lnicola** [comment]
Yes, sorry for the delay.

**Comment by d2weber** [comment]
> Yes, sorry for the delay.

No worries, thanks for reviewing.
