### ISSUE TITLE
Can't get the version information

### ISSUE THREAD

**Issue by azzamsa** [rust-analyzer/rust-analyzer#8043]
Hi.

After a change request (https://github.com/rust-analyzer/rust-analyzer/issues/7854) and a change, https://github.com/rust-analyzer/rust-analyzer/pull/7984 merged. 
The output of rust-analyzer **should be**:

```
❯ ./rust-analyzer-2021-03-15 --version
rust-analyzer 2021-03-15


❯ ./rust-analyzer-nightly --version
rust-analyzer-2021-03-15-gc0a2b4e
```

But, after downloading the [c0a2b4e nightly release](https://github.com/rust-analyzer/rust-analyzer/releases/tag/nightly) and the [2021-03-15 latest release](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-03-15). This is **what I get**:.

```
❯ ./rust-analyzer-2021-03-15 --version
rust-analyzer


❯ ./rust-analyzer-nightly --version
rust-analyzer
```

Am I missing something?

Thanks for rust-analyzer.

**Comment by lnicola** [comment]
Looks like #8049 didn't help here.

**Comment by lnicola** [comment]
If I clone the repository using `git clone --depth 200 https://github.com/rust-analyzer/rust-analyzer` and build it with `cargo xtask dist`, the resulting binary shows the version:

```
rust-analyzer nightly-4-g5ac0290f
```

So I'm not sure what's up.

**Comment by SomeoneToIgnore** [comment]
Can confirm the same: locally built version does show the correct string, the nightly version does not.
Could it be that the CI has no `.git` directory when building? (I've experienced such behavior with TeamCity before)

**Comment by lnicola** [comment]
Maybe, see https://github.com/rust-analyzer/rust-analyzer/pull/8121#issuecomment-803531187. But the action does have an option for the fetch depth, so why would that exist if there's no `.git`?

I guess we can revert #7984.

**Comment by SomeoneToIgnore** [comment]
I like the information improvement in general, so maybe we can leave it and fall back to less descriptive version string instead?
This also leaves an opportunity to debug and fix the CI issue for somebody.

**Comment by flodiebold** [comment]
It looks like the action does the fetch with `--no-tags`. We could probably fetch tags ourselves, or maybe there's an option to disable that.

**Comment by flodiebold** [comment]
Apparently setting `fetch-depth` to `0` will make it fetch tags as well. It somewhat makes sense, since `git fetch --tags` would also fetch the whole repository. Do we _need_ the shallow checkout for the release action?

**Comment by lnicola** [comment]
Let's see if #8194 fixes this.

**Comment by lnicola** [comment]
Looks like it worked:

    rust-analyzer nightly-9-g4cb3ecce3
