### ISSUE TITLE
Completion is cutting off function signature

### ISSUE THREAD

**Issue by ruffson** [rust-analyzer/rust-analyzer#8047]
Hello, 

I am using neovim `v0.5.0-dev+1133-g0869cbd55` with its native lsp client and the [compe](https://github.com/hrsh7th/nvim-compe) completion plugin. Everything works fine except that when I auto-complete, the doc preview is cutting off the documentation right under the signature, showing only the return type.

![Screenshot from 2021-03-14 20-41-09](https://user-images.githubusercontent.com/1185812/111278095-73dc3000-8639-11eb-806d-a715d76bca98.png)

A minimal init vim would be [here](https://github.com/sharksforarms/vim-rust/blob/master/neovim-init-lsp-compe.vim).

When I use another completion plugin, `completion-nvim` I do get the correct docs, ([minimal config](https://github.com/sharksforarms/vim-rust/blob/master/neovim-init-lsp.vim)):
![Screenshot from 2021-03-16 09-00-51](https://user-images.githubusercontent.com/1185812/111278190-90786800-8639-11eb-92a9-90184ce5ddb6.png)

I first raised an [issue](https://github.com/hrsh7th/nvim-compe/issues/257) over at that plugin but it seems to be that the issue is that the compe plugin correctly uses the `textDocument/completion` lsp functionality whereas the other plugin uses the `textDocument/hover` even for completion.

Just to show the compe plugin's `hover` on the same function:
![Screenshot from 2021-03-14 20-46-19](https://user-images.githubusercontent.com/1185812/111278399-c6b5e780-8639-11eb-8fe1-859832ec3672.png)

I just updated my `rust-analyzer` but `--version` does not return anything (anymore)...

So my question is: Does whatever falls out of `textDocument/completion` cut off the function signature? Is this a known issue?

**Comment by flodiebold** [comment]
This should be fixed by #7900, I think.

**Comment by ruffson** [comment]
Oh wow that looks like what I'm experiencing, thank you for pointing me in the right direction. Will eagerly await the next release!
