### ISSUE TITLE
Formatting: put opening braces in new line

### ISSUE THREAD

**Issue by Atrate** [rust-analyzer/rust-analyzer#8064]
First of all: Sorry if this is not the repo to ask, I'm mostly new to VSCode and Rust programming, so I may be missing some (a lot of) things.

I just installed `rust-analyzer` for programming in Rust and I really like the syntax highlighting and formatting functions it provides with one exception:

Is it somehow possible to make `ra` put opening braces in functions and conditionals in new lines? So, instead of formatting like this:

```
fn a() {
    ...
}
```
It would do this:
```
fn a() 
{
    ...
}
```

I'm asking as I haven't found such a setting in the documentation. If such a setting does not exist, would it be possible to implement it? Seems simple enough (at least for someone who knows how to write VSCode plugins, that is, not me).

If not, is there another VSCode Rust formatting plugin that would do what I outlined here?

Thanks,
Atrate

**Comment by lnicola** [comment]
We currently use `rustfmt` for document formatting, and you can configure that by adding a `rustfmt.toml` file to your project, or under your configuration directory. The setting you want is https://rust-lang.github.io/rustfmt/?version=v1.4.36&search=#brace_style.

**Comment by Atrate** [comment]
Thank you for the quick answer! That solves it beautifully.
