### ISSUE TITLE
"Convert to guard return" fails on mutable variables

### ISSUE THREAD

**Issue by ThomasK33** [rust-analyzer/rust-analyzer#8074]
When running the "Convert to guard return" function, the rust analyzer language server panics, when determining the name of a mutable variable.

![image](https://user-images.githubusercontent.com/2198487/111537753-1dbbd980-876c-11eb-80b8-4d350af0ee83.png)

Reproducible example:
```rust
fn main() {
    let variable_name: Result<u8, Box<dyn std::error::Error>> = Ok(1);

    if let Ok(mut variable_name) = variable_name {
        variable_name = variable_name + 1;
        println!("{}", variable_name);
    }
}

```

Language server panic:
```none
thread '<unnamed>' panicked at 'Failed to make ast node `syntax::ast::generated::nodes::Name` from text mod mut variable_name;', crates/syntax/src/ast/make.rs:518:13
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: syntax::ast::make::name
   3: ide_assists::assist_context::Assists::add
   4: ide_assists::handlers::early_return::convert_to_guarded_return
   5: ide_assists::Assist::get
   6: base_db::CheckCanceled::catch_canceled
   7: ide::Analysis::assists
   8: rust_analyzer::handlers::handle_code_action_resolve
   9: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Veykril** [comment]
The problem is this line https://github.com/rust-analyzer/rust-analyzer/blob/9d691530d556bdc40262585383a1b18d3a1de07e/crates/ide_assists/src/handlers/early_return.rs#L147
The ident pattern is being turned into a name here, this includes `ref` and `mut` tokens which shouldn't be part of the name.

**Comment by hi-rustin** [comment]
I am working on this.
