### ISSUE TITLE
ref (&) completion is broken for fiels

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#8090]
![image](https://user-images.githubusercontent.com/1711539/111656958-0dfbce00-881c-11eb-9495-9fbf76441d0e.png)

![image](https://user-images.githubusercontent.com/1711539/111656984-148a4580-881c-11eb-92a0-d7f3d9566722.png)

:disappointed:

**Comment by flodiebold** [comment]
Duplicate of #8058.

**Comment by JoshMcguigan** [comment]
Just noting I've implemented a potential workaround for this in #8142.
