### ISSUE TITLE
Fold consecutive `const` items as `use` statements in VSCode

### ISSUE THREAD

**Issue by Loptall** [rust-analyzer/rust-analyzer#8114]
In latest rust-analyzer extension of VSCode. It is possible to make `use` statements folded as below.

<img width="362" alt="Screen Shot 2021-03-20 at 18 11 52" src="https://user-images.githubusercontent.com/60812655/111865035-e89bcb00-89a7-11eb-9730-1a2969dfee56.png">
<img width="350" alt="Screen Shot 2021-03-20 at 18 12 01" src="https://user-images.githubusercontent.com/60812655/111865038-ec2f5200-89a7-11eb-8ff4-3eb26990aa21.png">

I think `const`(and `static`) items should have the same behavior.

**Comment by Veykril** [comment]
Implemented in #8231
