### ISSUE TITLE
Allow the usage of block attributes

### ISSUE THREAD

**Issue by c410-f3r** [rust-analyzer/rust-analyzer#8126]
`rustc` compiles

```rust
const _LEN: usize = {
  #[allow(unused_mut)]
  let mut len = 0;
  #[cfg(windows)]
  { len += 1; }
  len
};

fn _foo() -> [i32; _LEN] {
  [
    #[cfg(windows)]
    { 1 }
  ]
}
```

but `rust-analyzer` shows `Syntax Error: A block in this position cannot accept inner attributes`. The error goes away when removing brackets.

Feel free to close this PR if it is a duplicated of https://github.com/rust-analyzer/rust-analyzer/issues/919.

**Comment by Veykril** [comment]
Quoting the reference:
```
Block expressions accept outer and inner attributes, but only when they are the outer expression of an expression statement or the final expression of another block expression
```
We currently validate the following which is therefor incorrect: 
https://github.com/rust-analyzer/rust-analyzer/blob/090e013161ab5b1679554ddd53683e81e3fe845a/crates/syntax/src/validation/block.rs#L1-L22

**Comment by c410-f3r** [comment]
Fixed by https://github.com/rust-analyzer/rust-analyzer/pull/8578
