### ISSUE TITLE
Variable name same as function name is highlighted as function.

### ISSUE THREAD

**Issue by chetankhilosiya** [rust-analyzer/rust-analyzer#8152]
When the variable used in function has same name as function name then it is highlighted as function.
The function semantic tag is given to that variable name.
Example:
```rust
fn example() {
    let example = 10; // here the example is highlighted as function
}
```
fix: The field symbol highlighting should be given.

**Comment by Veykril** [comment]
That example is not quite right to trigger it. The cause are macros which aren't included here.

```rust
fn example(example: i32) {
    assert!(true);
    let _ = example; // example here resolves to the function
}
```
vs
```rust
fn example(example: i32) {
    // assert!(true);
    let _ = example; // example here resolves to the parameter
}
```

https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/Cross.20crate.20find.20usages.20seems.20to.20be.20broken.3F/near/229489409

**Comment by chetankhilosiya** [comment]
the issue occures for standalone function but not in method function.
```rust
impl Example {
    fn example(example: i32) {
        assert!(true);
        let _ = example; // example here resolves to the parameter
    }
}
```
