### ISSUE TITLE
unresolved-macro-call on futures_util::join!

### ISSUE THREAD

**Issue by Follpvosten** [rust-analyzer/rust-analyzer#8163]
With the latest stable and nightly versions, in a new project just depending on tokio and future_util, with this code in main.rs:
```rust
#[tokio::main]
async fn main() {
    let bla = async { 1 };
    let blub = async { 2 };
    let (bla, blub) = futures_util::join!(bla, blub);
}
```
I get this error on the futures_util::join! line:
![Screenshot_20210323_124253](https://user-images.githubusercontent.com/22855787/112141274-61cc3580-8bd5-11eb-8964-5caf77751ed8.png)
despite it obviously finding the macro, as the documentation is shown. This did not happen with the stable release before this one.
More info: vscode 1.54.3 (OSS build), Linux 5.10.24, rustup 1.23.1, cargo/rustc 1.50.0

**Comment by jonas-schievink** [comment]
The macro invokes `join_internal!`, which is reexported like this:

```rust
#[proc_macro_hack(support_nested, only_hack_old_rustc)]
pub use futures_macro::join_internal;
```

**Comment by Follpvosten** [comment]
Oh so this really is #6478?

**Comment by jonas-schievink** [comment]
No, it might be the fact that we don't support attribute macros like `#[proc_macro_hack]`, but if it only appeared recently it might be something else.

**Comment by lnicola** [comment]
It's also https://github.com/rust-analyzer/rust-analyzer/issues/6835 and also #6029.

**Comment by jonas-schievink** [comment]
https://github.com/rust-analyzer/rust-analyzer/issues/6835 looks like a direct duplicate, so closing in favor of that
