### ISSUE TITLE
Change `thread_worker` library to propagate panics by default

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#817]
We have a small [thread_worker](https://github.com/rust-analyzer/rust-analyzer/blob/74d03d57e77b791b6973497f17a35136ddc295ab/crates/thread_worker/src/lib.rs) for spawning background threads. It's main purpose is to force clean thread shutdown: if you don't join the thread, it might be forcefully terminated when the process exists, skipping destructors. Leaving threads unjoined is also bad for reliable unit-testing, and in general bad for overall architecture of the system. 

A slight problem with this library is that it turns a thread's `panic` into `Result` by forcing you to use the [shutdown](https://github.com/rust-analyzer/rust-analyzer/blob/74d03d57e77b791b6973497f17a35136ddc295ab/crates/thread_worker/src/lib.rs#L55) method. I now think this is a bad idea: it's usually best to escalate the panic instead of catching it, even on the thread boundary. We need to switch "panic, if child thread panicked" behavior. 

To do this, we need the following changes:

* introduce a wrapper around `thread::spawn` and `thread::JoinHandler` which joins the thread automatically in Drop, propagating the panic from the child thread if the parent thread is not panicking itself. We should use this wrapper in cases where we spawn bare threads, [like here](https://github.com/rust-analyzer/rust-analyzer/blob/74d03d57e77b791b6973497f17a35136ddc295ab/crates/ra_vfs/src/io.rs#L81-L85)
* Remove [`WorkerHandle`](https://github.com/rust-analyzer/rust-analyzer/blob/74d03d57e77b791b6973497f17a35136ddc295ab/crates/ra_vfs/src/io.rs#L81-L85) struct (which exists solely to join the thread) and instead add our `JoinHandler` (what's a good name here? `ScopedThread`, `ThreadGuard`?) to the `Worker`
* Change `Worker`'s shutdown method to return a pair of `(ScopedThread, Receiver)`
* update  usages of `thead_worker` to the new API, paying close attention to possible deadlocks. Specifically, channel senders should be dropped **before** `ScopedThread`, *even* in case of a panic.

**Comment by matklad** [comment]
cc @stjepang, this is very related to https://github.com/rust-lang/rust/pull/48830 and shows an interesting interaction between channels and threads (drop sender prior to joining).

**Comment by matklad** [comment]
Slightly tangential, but, if you are interested in threads and clean cancellation, there's an interesting discussion over here: https://trio.discourse.group/t/structured-concurrency-in-rust/73

**Comment by matklad** [comment]
>drop sender prior to joining

Hm, this seems fun indeed, looks like the pattern we want is

```rust
let (sender, receiver) = channel();
let thread = spawn(move || {
    for event in receiver {
        ...
    }
})

// subtle, force sender to be dropped *before* thread, avoiding deadlock
let sender = sender;
```

That's a super uncomfortable level of subtlety, can we do better?

**Comment by DJMcNab** [comment]
We could just use std::mem::drop manually.

**Comment by matklad** [comment]
That works for the happy case, but not for the panics, a panic will cause a deadlock
