### ISSUE TITLE
Shorten automatic type annotations when type is too long

### ISSUE THREAD

**Issue by Cobrand** [rust-analyzer/rust-analyzer#8172]
I'm using the `fixed` crate, for fixed-point numbers and there are type hacks to have generic fixed-point number types.

In this crate, you would usually import aliases, such as https://docs.rs/fixed/1.6.0/fixed/types/type.I8F8.html (which is equivalent to `FixedI16<UInt<UInt<UInt<UInt<UTerm, B1>, B0>, B0>, B0>>`). The problem is that because of #1666 , type aliases in rust-analyzer are see-through and you always get the original type displayed, no matter the amount of aliases.

The end result is something like that ![code image](https://imgur.com/hGrhoe4.png), which absolutely destroys the reading of the code when using such types. When you use such a type everywhere in your code, it gets really annoying. You could add some annotations from time like `let a: I8F8` when you can even though it's annoying, but in this case (pattern matching), it's not even possible to do that.

So until the issue with type aliases is fixed, I propose that we simply shorten the generic types if they are too long. For instance, if a generic type has a name length more than 20 characters, we could replace it with "...". In the example, that would result here in `Vector2D<FixedI64<...>>` or `Vector2D<...>`. This would be about 40~50 characters saved, which would make a huge difference.

You could always hover over the type to see the full type if you would like (at least in vscode), so shortening shouldn't be a problem.

This is really a big problem for me, so if no one is up for it, I can take care of it myself, you just need to tell me where are implemented type annotations in the repo and I'll give it a try.

**Comment by jonas-schievink** [comment]
You can set `rust-analyzer.inlayHints.maxLength` to limit them

**Comment by Cobrand** [comment]
@jonas-schievink you're a lifesaver. I'm closing this.

Still, I see that the default is unlimited, perhaps a more sane default would be advisable? I doubt the amount of people wanting type annotations unlimited in length are in the majority, I think a saner default would be about 20~30~40 characters.

**Comment by Veykril** [comment]
I'm certainly in favor of setting a default. Unlimited seems like something that general user wouldn't ever want to have imo.

**Comment by jonas-schievink** [comment]
Yeah, seems reasonable to set a default limit here. We should choose it so that all common hints are still fully rendered though.

**Comment by SomeoneToIgnore** [comment]
I've filed https://github.com/rust-analyzer/rust-analyzer/pull/8177 with 20 picked as an arbitrary number.

I'm not sure how to determine the common hints in general due to a few cases: 

* If `JavaLikeLongNaming` is used in the project, it can be a common thing and hint in the project, but will still be too long to fully render
* If you have enough chained iterator methods, chalk bails and starts to show real combined nested iterator types, which are also pretty common and very bloated at the same time
