### ISSUE TITLE
vscode errors from cargo check don't stay in place while the buffer is edited.

### ISSUE THREAD

**Issue by umanwizard** [rust-analyzer/rust-analyzer#8180]
I'm not sure if this is a vscode issue, or a rust-analyzer issue, and I'm not sure whether it is even possible to fix. So please feel free to close this if it's not actionable.

When a set of files is saved, I have rust-analyzer configured to run `cargo check`, and the errors are reported to vscode and become red squiggles. The issue is that these squiggles are tied to a _line number_ (and range of columns), rather than a line's identity.

Thus if an error occurred on line 10, and then I insert another line, say at line 5, the squiggle will _still be on line 10_, instead of following the line it is attached to, which is now at line 11.

**Comment by lnicola** [comment]
I think this is a known Code issue, but I can't find a reference. @matklad might know.

**Comment by matklad** [comment]
https://github.com/microsoft/vscode/issues/103953 

I think that's a bug on vscode side, and server-side work-around would be too complicated, so closing. 

That said, this is the one of the most annoying things indeed, :hugs:
