### ISSUE TITLE
Huge memory leak with 2021-03-22

### ISSUE THREAD

**Issue by rnd-ash** [rust-analyzer/rust-analyzer#8181]
Noticed this after leaving my IDE (vscode) open all day:
![image](https://user-images.githubusercontent.com/14551965/112214373-03c04200-8c17-11eb-9a73-a53e4518b39e.png)

Memory usage by rust analyzer doesn't account for hardly any of the usage being reported by the system:

Per-query memory usage:
   307mb FileItemTreeQuery
    80mb HygieneFrameQuery
    66mb MacroArgTextQuery
    63mb CrateDefMapQueryQuery
    51mb FileTextQuery (purge)
    32mb InternEagerExpansionQuery
    24mb GenericParamsQuery
    23mb ImplDatumQuery
    21mb ParseQuery
    18mb TraitSolveQuery (deps)
    15mb GenericParamsQuery (purge)
    15mb AttrsQuery
    13mb ImplTraitQuery (purge)
    12mb TraitSolveQuery (purge)
    11mb ImplSelfTyQuery (purge)
    11mb ImplDataQuery (purge)
    11mb AstIdMapQuery
    11mb MacroDefQuery
    10mb BodyQuery
     9mb BodyWithSourceMapQuery
     9mb TraitImplsInDepsQuery
     8mb ParseMacroExpansionQuery (purge)
     8mb AstIdMapQuery (purge)
     8mb InternFunctionQuery
     8mb FileItemTreeQuery (purge)
     8mb GenericPredicatesQuery (purge)
     8mb MacroExpandQuery (purge)
     8mb ImplTraitQuery
     8mb ImplDataQuery (deps)
     7mb InternMacroQuery
     7mb InferQueryQuery
     7mb InternMacroQuery (purge)
     7mb ImplDatumQuery (purge)
     6mb MacroArgTextQuery (purge)
     6mb AttrsQuery (purge)
     6mb InternFunctionQuery (purge)
     5mb FunctionDataQuery
     5mb ImplTraitQuery (deps)
     5mb ImplSelfTyQuery (deps)
     5mb InternImplQuery (purge)
     4mb TraitImplsInCrateQuery
     4mb InternImplQuery
     4mb CrateGraphQuery (purge)
     4mb BlockDefMapQuery
     4mb FileItemTreeQuery (deps)
  3882kb GenericParamsQuery (deps)
  3548kb ImplDatumQuery (deps)
  3495kb ImportMapQuery
  3197kb TypeAliasDataQuery
  2924kb GenericPredicatesQuery
  2633kb ParseMacroExpansionQuery (deps)
  2417kb TyQuery (purge)
  2350kb GenericPredicatesQuery (deps)
  2304kb MacroExpandQuery (deps)
  2130kb GenericDefaultsQuery (purge)
  2067kb HygieneFrameQuery (purge)
  1978kb InternConstQuery
  1968kb ExprScopesQuery
  1967kb MacroArgTextQuery (deps)
  1892kb LineIndexQuery
  1802kb CrateDefMapQueryQuery (deps)
  1766kb InferQueryQuery (deps)
  1696kb InternConstQuery (purge)
  1633kb SourceRootQuery (purge)
  1549kb TyQuery
  1426kb AstIdMapQuery (deps)
  1304kb InternTypeAliasQuery
  1192kb AssociatedTyValueQuery
  1188kb StructDataQuery
  1119kb TypeAliasDataQuery (purge)
  1046kb AttrsQuery (deps)
   967kb TraitImplsInCrateQuery (deps)
   958kb CallableItemSignatureQuery
   940kb HygieneFrameQuery (deps)
   872kb ImplSelfTyQuery
   848kb InternTypeAliasQuery (purge)
   834kb BlockDefMapQuery (purge)
   784kb InternStructQuery (purge)
   709kb GenericDefaultsQuery
   670kb TyQuery (deps)
   663kb EnumDataQuery
   658kb InternStructQuery
   571kb FunctionDataQuery (purge)
   556kb ParseQuery (purge)
   538kb ParseMacroExpansionQuery
   525kb FileSourceRootQuery (purge)
   525kb AssociatedTyValueQuery (purge)
   520kb GenericDefaultsQuery (deps)
   473kb CallableItemSignatureQuery (purge)
   471kb FileSymbolsQuery
   470kb FnDefDatumQuery
   350kb BlockDefMapQuery (deps)
   331kb TypeAliasDataQuery (deps)
   320kb ConstDataQuery
   310kb InternTypeParamIdQuery (purge)
   308kb TraitSolveQuery
   290kb ValueTyQuery (purge)
   276kb MacroExpandQuery
   231kb CallableItemSignatureQuery (deps)
   229kb ConstDataQuery (purge)
   218kb GenericPredicatesForParamQuery (purge)
   214kb FunctionDataQuery (deps)
   213kb BodyWithSourceMapQuery (deps)
   203kb BodyQuery (purge)
   202kb AssociatedTyValueQuery (deps)
   202kb BodyWithSourceMapQuery (purge)
   201kb InferQueryQuery (purge)
   200kb ExprScopesQuery (purge)
   197kb GenericPredicatesForParamQuery
   179kb MacroDefQuery (purge)
   178kb TraitImplsInCrateQuery (purge)
   177kb CrateDefMapQueryQuery (purge)
   175kb TraitDataQuery
   168kb ValueTyQuery
   164kb InternEnumQuery (purge)
   145kb InternEnumQuery
   143kb FieldTypesQuery
   133kb CrateLangItemsQuery (deps)
   126kb TraitDatumQuery
   119kb StructDataQuery (purge)
   109kb ParseQuery (deps)
    98kb StructDatumQuery
    98kb InternTraitQuery (purge)
    95kb InherentImplsInCrateQuery (deps)
    94kb FnDefDatumQuery (purge)
    92kb LineIndexQuery (purge)
    90kb InternTraitQuery
    88kb InternCallableDefQuery (purge)
    83kb ValueTyQuery (deps)
    81kb StructDatumQuery (purge)
    79kb GenericPredicatesForParamQuery (deps)
    68kb InternStaticQuery
    64kb ConstDataQuery (deps)
    60kb TraitDatumQuery (purge)
    59kb InherentImplsInCrateQuery
    58kb FieldTypesQuery (purge)
    52kb TraitDataQuery (purge)
    52kb InternEagerExpansionQuery (purge)
    51kb EnumDataQuery (purge)
    49kb InternStaticQuery (purge)
    44kb SourceRootCratesQuery (deps)
    38kb AssociatedTyDataQuery
    38kb BodyQuery (deps)
    35kb ExprScopesQuery (deps)
    35kb MacroDefQuery (deps)
    34kb FnDefDatumQuery (deps)
    34kb StructDataQuery (deps)
    33kb FieldTypesQuery (deps)
    31kb TraitDataQuery (deps)
    22kb TraitDatumQuery (deps)
    22kb InternTypeParamIdQuery
    21kb InternCallableDefQuery
    21kb StructDatumQuery (deps)
    17kb LangItemQuery (purge)
    17kb InternClosureQuery (purge)
    15kb LineIndexQuery (deps)
    13kb EnumDataQuery (deps)
    13kb AssociatedTyDataQuery (purge)
    10kb InternClosureQuery
     7kb AssociatedTyDataQuery (deps)
     6kb FileSymbolsQuery (purge)
     5kb CrateLangItemsQuery
   3840b ImportMapQuery (deps)
   3696b ImportMapQuery (purge)
   3456b TraitImplsInDepsQuery (deps)
   3088b LangItemQuery (deps)
   2848b LibraryRootsQuery (purge)
   2336b InherentImplsInCrateQuery (purge)
   2304b StaticDataQuery
   2256b InternUnionQuery
   1808b CrateLangItemsQuery (purge)
   1808b TraitImplsInDepsQuery (purge)
   1696b StaticDataQuery (purge)
   1616b InternUnionQuery (purge)
   1392b UnionDataQuery
   1216b FileSymbolsQuery (deps)
   1040b SourceRootCratesQuery (purge)
    672b SourceRootCratesQuery
    432b StaticDataQuery (deps)
    352b InternImplTraitIdQuery (purge)
    304b LocalRootsQuery (purge)
    272b UnionDataQuery (purge)
     80b InternImplTraitIdQuery
     48b UnionDataQuery (deps)
      0b CrateGraphQuery
      0b CrateGraphQuery (deps)
      0b FileTextQuery
      0b FileTextQuery (deps)
      0b FileSourceRootQuery
      0b FileSourceRootQuery (deps)
      0b SourceRootQuery
      0b SourceRootQuery (deps)
      0b LangItemQuery
      0b AssociatedTyDataQuery
      0b AssociatedTyDataQuery (deps)
      0b AssociatedTyDataQuery (purge)
      0b ReturnTypeImplTraitsQuery
      0b ReturnTypeImplTraitsQuery (deps)
      0b ReturnTypeImplTraitsQuery (purge)
      0b InternCallableDefQuery (deps)
      0b InternTypeParamIdQuery (deps)
      0b InternImplTraitIdQuery (deps)
      0b InternClosureQuery (deps)
      0b LibrarySymbolsQuery
      0b LibrarySymbolsQuery (deps)
      0b LibrarySymbolsQuery (purge)
      0b LocalRootsQuery
      0b LocalRootsQuery (deps)
      0b LibraryRootsQuery
      0b LibraryRootsQuery (deps)
      0b InternMacroQuery (deps)
      0b InternEagerExpansionQuery (deps)
      0b InternFunctionQuery (deps)
      0b InternStructQuery (deps)
      0b InternUnionQuery (deps)
      0b InternEnumQuery (deps)
      0b InternConstQuery (deps)
      0b InternStaticQuery (deps)
      0b InternTraitQuery (deps)
      0b InternTypeAliasQuery (deps)
      0b InternImplQuery (deps)
      0b InternTypeParamIdQuery
      0b InternTypeParamIdQuery (deps)
      0b InternTypeParamIdQuery (purge)
 -4058mb ImplDataQuery

**Comment by rnd-ash** [comment]
After resetting my PC and re-launching VSCode, I can see the memory usage or rust analyzer increasing at a rate of about 1GB/hr, whilst just having the project open, without any editing.

**Comment by Veykril** [comment]
Is this happening for you for just a specific project?

**Comment by rnd-ash** [comment]
I've noticed this on 2 separate instances (2-4GB used by 1 instance of rust analyzer), however this project seems to have the worst memory leak by far (Open Vscode in the app_rust folder)

https://github.com/rnd-ash/OpenVehicleDiag

**Comment by Veykril** [comment]
Hm, looks like this is linux specific, I've kept the project open on my windows machine for 30 minutes now with no change in memory usage in vscode 😕

**Comment by jonas-schievink** [comment]
Yeah, something's off even on https://github.com/rust-analyzer/rust-analyzer/commit/858ad554374a8b1ad67692558a0878391abfdd86. r-a is using 11 GB of RAM on itself.

**Comment by jonas-schievink** [comment]
`analysis-stats` on r-a shows "448mb Unaccounted", which seems too much, while using a total of 4783mb

**Comment by jonas-schievink** [comment]
`analysis-stats` shows nothing interesting on OpenVehicleDiag though

**Comment by jonas-schievink** [comment]
> SUMMARY: LeakSanitizer: 37249679 byte(s) leaked in 5702966 allocation(s).

@matklad the leaks all come from here: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/syntax/src/ast/node_ext.rs#L36-L40

**Comment by matklad** [comment]
:unamused: :palm_tree: 

That really is missing a TODO.

**Comment by matklad** [comment]
We should make analysis stats panic if there's too much memory after main, that would've caught this on nightly.

**Comment by jonas-schievink** [comment]
Not terribly slow, but sanitizers are still nightly-only and can break from time to time

**Comment by Veykril** [comment]
#8191 fixed this so we can close this right?
