### ISSUE TITLE
Grayed out code and unlinked-file not documented

### ISSUE THREAD

**Issue by MichaelMcDonnell** [rust-analyzer/rust-analyzer#8188]
I was working on a feature in the Rust standard library and upgraded rust-analyzer from v0.2.521 to 0.2.529. After upgrading the code in library/core/src/fmt/mod.rs is all grayed out and I get a message about the file being unlinked. I followed the link to the [documentation](https://rust-analyzer.github.io/manual.html#unlinked-file) but unlinked-file is not documented. It worked again after downgrading. Do anyone know what is going on?

Steps to reproduce:

1. Clone the Rust repo at https://github.com/rust-lang/rust
2. Open the folder in VS Code
3. Open the file library/core/src/fmt/mod.rs
4. Notice the code is grayed out and there is a message about unlinked-file
5. Click to open the online documentation
6. Notice that the documentation does not contain any information about unlinked-file.

**Comment by bjorn3** [comment]
A wild guess, but this could have regressed in https://github.com/rust-analyzer/rust-analyzer/pull/8108. This PR would make the `#![cfg(not(test))]` used multiple times inside libcore actually work. Rust-analyzer always sets `cfg(test)` to be able to analyze unit tests.

**Comment by jonas-schievink** [comment]
I think the `#![cfg(not(test))]` on libcore's `lib.rs` has always been a problem (we've been respecting crate-level `#![cfg]` for a while), just the diagnostic is new. I've documented it in #8189, but it'll take until the next release until the docs get updated.

**Comment by MichaelMcDonnell** [comment]
Thanks for the quick responses!

Is there another way rust-analyzer could analyze unit tests without setting cfg(test)? Or is there some other way this could be fixed?

Alternatively, can this behavior be disabled?

**Comment by jonas-schievink** [comment]
Diagnostics can be disabled as described here: https://rust-analyzer.github.io/manual.html#diagnostics

**Comment by MichaelMcDonnell** [comment]
Thanks! I ended up adding a workspace setting with just unlinked-file disabled:

```json
{
    "rust-analyzer.diagnostics.disabled": [
        "unlinked-file"
    ]
}
```

That at least makes the code not grayed out.
