### ISSUE TITLE
Run | Debug code lenses incorrectly placed

### ISSUE THREAD

**Issue by ceronman** [rust-analyzer/rust-analyzer#8195]
Rust Analyzer puts `Run | Debug` code lenses on `main` functions. This works well for the entry point of an application, which is the `main.rs` file. However, you can have other functions called `main` in other modules. These are not entry points. When this happens, Rust Analyzer still puts a `Run | Debug` code lens on those functions. If you click them, Rust will execute the main entry point of the application (`main` in `main.rs`), not the one where the code less is on. This is confusing and misleading. The expected behaviour is that RA should only put these lenses on the main entry point and not on any function called `main`.

**Comment by ivan770** [comment]
We might need to check if `main` function lies in root module in `runnables.rs`. Currently code just checks if function name is `main`. https://github.com/rust-analyzer/rust-analyzer/blob/f6f582dec4c0d2e9ad22d5a753ba92192dec9d31/crates/ide/src/runnables.rs#L229-L231

**Comment by Veykril** [comment]
That alone won't suffice I think since one can have multiple binaries in a crate, and those do not lie at the root module.

**Comment by flodiebold** [comment]
Those binaries would be their own crates in the cargo metadata, with their own root modules.
