### ISSUE TITLE
Debugging on Apple Silicon?

### ISSUE THREAD

**Issue by XiNiHa** [rust-analyzer/rust-analyzer#8199]
I have tried debugging on my M1 Mac and got these messages:
```
Running the contributed command: 'rust-analyzer.debugSingle' failed.
This platform (arm64-darwin) is not supported.
```

Is there any plan to support debugging on Apple Silicon?

**Comment by lnicola** [comment]
`rust-analyzer` only starts the debug session, which is implemented by another extension (C/C++, LLDB VSCode, Native Debug etc.). Check which one you are using and follow up with them.
