### ISSUE TITLE
lsp start fail

### ISSUE THREAD

**Issue by matianhe3** [rust-analyzer/rust-analyzer#8203]
```
Suspicious state from syntax checker rust: Flycheck checker rust returned 1, but its output contained no errors: error: no override and no default toolchain set
Try installing a more recent version of rust, and please open a bug report if the issue persists in the latest release.  Thanks!
LSP :: Error from the Language Server: Rust Analyzer is still loading... (Unknown error) [16 times]
Company: An error occurred in auto-begin
Company: backend (company-capf :with company-yasnippet) error "Rust Analyzer is still loading..." with args (candidates l)
LSP :: Error from the Language Server: Rust Analyzer is still loading... (Unknown error) [2 times]
Company: An error occurred in auto-begin
Company: backend (company-capf :with company-yasnippet) error "Rust Analyzer is still loading..." with args (candidates le)
LSP :: Error from the Language Server: Rust Analyzer is still loading... (Unknown error) [2 times]
Company: An error occurred in auto-begin
Company: backend (company-capf :with company-yasnippet) error "Rust Analyzer is still loading..." with args (candidates let)
LSP :: Error from the Language Server: Rust Analyzer is still loading... (Unknown error) [4 times]
Saving file /Users/matianhe/rust/src/main.rs...
Wrote /Users/matianhe/rust/src/main.rs
Suspicious state from syntax checker rust: Flycheck checker rust returned 1, but its output contained no errors: error: no override and no default toolchain set
```

**Comment by lnicola** [comment]
Does `cargo check` work? What does `rustup toolchain list` print, if you installed Rust that way?

The "still loading" errors should not be a problem.

**Comment by matianhe3** [comment]
``` 
cargo check
    Checking rust v0.1.0 (/Users/matianhe/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 0.71s
```
```
 rustup toolchain list
stable-x86_64-apple-darwin (default)
```

**Comment by flodiebold** [comment]
There's nothing in those messages that indicates that rust-analyzer is actually failing to start (in fact, it's responding and indicating that it's loading). It may just take a few moments to be ready, depending on the size of the project.

That said, you don't want to use the `rust` flycheck checker when you're using lsp. You should make sure `lsp` is enabled instead.

**Comment by matianhe3** [comment]
> There's nothing in those messages that indicates that rust-analyzer is actually failing to start (in fact, it's responding and indicating that it's loading). It may just take a few moments to be ready, depending on the size of the project.
> 
> That said, you don't want to use the `rust` flycheck checker when you're using lsp. You should make sure `lsp` is enabled instead.

![image](https://user-images.githubusercontent.com/24929062/112625724-46c62380-8e6a-11eb-9d87-c13823fb4e59.png)

config: 
```
(use-package rustic
  :config
  (setq rustic-format-on-save t))

(use-package lsp-mode
  :commands lsp
  :custom
  (lsp-auto-guess-root t)
  (lsp-keymap-prefix "M-m l")
  (lsp-modeline-diagnostics-enable nil)
  (lsp-keep-workspace-alive nil)
  (lsp-auto-execute-action nil)
  (lsp-before-save-edits nil)
  (lsp-eldoc-enable-hover nil)
  (lsp-diagnostic-package :none)
  (lsp-completion-provider :none)
  (lsp-file-watch-threshold 1500)
  (lsp-enable-links)
  :custom-face
  (lsp-face-highlight-read ((t (:underline t :background nil :foreground nil))))
  (lsp-face-highlight-write ((t (:underline t :background nil :foreground nil))))
  (lsp-face-highlight-textual ((t (:underline t :background nil :foreground nil))))
  :hook
  (lsp-mode . lsp-enable-which-key-integration))

```
In `Message`:
```
helm-posframe is enabled.
.config/emacs/straight/build/rustic/rustic-flycheck.el: Warning: (lambda nil \.\.\.) quoted with ' rather than with #'
Loading /Users/matianhe/.config/emacs/recentf...done
Cleaning up the recentf list...done (0 removed)
For information about GNU Emacs and the GNU system, type C-h C-a.
[yas] Prepared just-in-time loading of snippets successfully.
Package dash-functional is obsolete; use dash 2.18.0 instead
main.rs has auto save data; consider M-x recover-this-file
LSP :: Connected to [rust-analyzer:56382/starting].
LSP :: rust-analyzer:56382 initialized successfully
LSP :: rust-analyzer failed to load workspace: "cargo" "--version" failed, exit code: 1
stderr:
error: no override and no default toolchain set

LSP :: Error from the Language Server: Rust Analyzer is still loading... (Unknown error) [3 times]
Mark set
```

IN `lsp-log`:
```
Command "rls" is present on the path.
Command "/Users/matianhe/.config/cargo/bin/rust-analyzer" is present on the path.
Command "rls" is present on the path.
Command "/Users/matianhe/.config/cargo/bin/rust-analyzer" is present on the path.
Found the following clients for /Users/matianhe/rust/src/main.rs: (server-id rls, priority -1), (server-id rust-analyzer, priority 1)
The following clients were selected based on priority: (server-id rust-analyzer, priority 1)
```

IN `rust-analyzer::stderr`:
```
[ERROR rust_analyzer::reload] failed to load workspace: "cargo" "--version" failed, exit code: 1
stderr:
error: no override and no default toolchain set
```

```
cargo check
    Checking rust v0.1.0 (/Users/matianhe/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 0.75s
cargo --version
    cargo 1.51.0 (43b129a20 2021-03-16)
```

**Comment by flodiebold** [comment]
That seems like a path issue then. What happens if you run `cargo --version` within Emacs from the project root using `shell-command`?

**Comment by matianhe3** [comment]
> That seems like a path issue then. What happens if you run `cargo --version` within Emacs from the project root using `shell-command`?

 cargo --version
cargo 1.51.0 (43b129a20 2021-03-16)

**Comment by flodiebold** [comment]
Does running `rust-analyzer analysis-stats .` in your project directory from the terminal work?

**Comment by matianhe3** [comment]
> Does running `rust-analyzer analysis-stats .` in your project directory from the terminal work?
> 
> Also, what does `rust-analyzer --version` say?

```
~/rust ❯❯❯ rust-analyzer analysis-stats .
Database loaded:     607.31ms
  crates: 1, mods: 1, decls: 1, fns: 1
Item Collection:     3.12s
  exprs: 10, ??ty: 0 (0%), ?ty: 0 (0%), !ty: 0
Inference:           1.67s
Total:               4.80s

~/rust ❯❯❯ rust-analyzer --version
rust-analyzer 
```

**Comment by flodiebold** [comment]
OK, so this is some issue with the environment in Emacs, or maybe rustic is passing some additional environment variables that are causing this. Does running `rust-analyzer analysis-stats .` from within Emacs using `shell-command` work?

**Comment by matianhe3** [comment]
> OK, so this is some issue with the environment in Emacs, or maybe rustic is passing some additional environment variables that are causing this. Does running `rust-analyzer analysis-stats .` from within Emacs using `shell-command` work?

yes

**Comment by flodiebold** [comment]
Does the problem persist with `lsp-start-plain.el` (from [lsp-mode](https://github.com/emacs-lsp/lsp-mode/blob/master/.github/ISSUE_TEMPLATE/bug_report.md))?

**Comment by matianhe3** [comment]
> Does the problem persist with `lsp-start-plain.el` (from [lsp-mode](https://github.com/emacs-lsp/lsp-mode/blob/master/.github/ISSUE_TEMPLATE/bug_report.md))?

yes

**Comment by matianhe3** [comment]
![image](https://user-images.githubusercontent.com/24929062/113401490-00c30f80-93d6-11eb-864c-f0af3c636654.png)

**Comment by flodiebold** [comment]
That's `cargo metadata` failing when called by rustic, and then RLS failing to start. I don't see anything about rust-analyzer there. I suggest asking on the rustic-mode repo about this.
