### ISSUE TITLE
Compiler assist name capitalization

### ISSUE THREAD

**Issue by ivan770** [rust-analyzer/rust-analyzer#8204]
(almost) all assists, that rustc returns to RA start with lowercase letter, thus distinguishing it from native RA assists.
Should RA capitalize names before passing assists back to LSP client?
![image](https://user-images.githubusercontent.com/14003886/112621262-342ff800-8e32-11eb-95d4-d7af198980fe.png)

**Comment by flodiebold** [comment]
IMO no, it wouldn't really do much. "A struct with a similar name exists" is still just as weird compared to our assists. In general, showing rustc errors is only a temporary thing anyway (though rather long-term temporary). We should try to hide them when we have our own, better versions.

**Comment by ivan770** [comment]
Sounds reasonable

**Comment by flodiebold** [comment]
Maybe we could append ` [rustc]` or something like that though :thinking:

**Comment by Veykril** [comment]
That sounds like a good idea I think, would probably get rid of the confusion when one sees two similar assist popups for now, like wrong capitalization does currently
