### ISSUE TITLE
rustc test files have broken syntax highlighting: font is very light and hard to read

### ISSUE THREAD

**Issue by RalfJung** [rust-analyzer/rust-analyzer#8215]
Since recently, syntax highlighting in test files in the rustc repo is broken: the entire file is rendered in a very light font on white background, making it very hard to read. The code looks like code that is inside a `#[cfg(false)]`.

To reproduce, open e.g. `src/test/ui/closures/2229_closure_analysis/diagnostics/repr_packed.rs` -- but this seems to affect all test files that I tried so far.

This makes it rather hard to work in these files since I can barely see the code I am trying to edit...

"Rust Analyzer: Show RA Version" shows an empty version number, no idea what's up with that... "Rust Analyzer: Status" says
```
workspaces:
493 packages loaded

analysis:
11941 (104mb) files
0 (0b) index symbols
7715 trees, 128 retained
45484 trees, 128 retained (macros)
1602mb total

counts:
all counts are zero


requests:
   49 textDocument/codeLens               16326ms
   33 textDocument/semanticTokens/full    20902ms
   50 textDocument/codeLens               0ms
   51 textDocument/codeLens               0ms
   52 textDocument/codeLens               0ms
   53 textDocument/codeLens               0ms
   56 textDocument/codeLens               0ms
*  46 textDocument/codeAction             16631ms
   47 textDocument/documentSymbol         16625ms
   48 textDocument/foldingRange           16523ms
```

**Comment by RalfJung** [comment]
Hovering over the code in that file shows a popup saying

> file not included in module treerust-analyzerunlinked-file

That's fair, but that is no reason to make the code so hard to read!
I searched for a way to disable "make code hard to read when it is `cfg`d out", but found nothing. (I'd probably use that even if this bug was fixed, as chances are I should actually care about that code since it might very well be active for other people compiling this same code.)

**Comment by Veykril** [comment]
I'm not sure what decides the highlighting when cfg'ed out but you can at least surpress the `unlinked-file` warning from RA which gets rid of the highlighting as the warning doesn't get emitted.
You can do that by adding it to the disabled diagnostics(in vscode it looks like the following in the settings.json):
```json
    "rust-analyzer.diagnostics.disabled": [
        "unlinked-file"
    ],
```

**Comment by RalfJung** [comment]
> You can do that by adding it to the disabled diagnostics(in vscode it looks like the following in the settings.json):

Thanks a lot, now the test files are readable again. :)

**Comment by Veykril** [comment]
After a bit of digging you can turn the fading out in vscode with `"editor.showUnused": false`.

Basically the diagnostic has an extra flag whether its unused code or not which allows the client to do things with it then like vscode fading it out. Might be good idea to add this bit of info to the manual as well, as tests/examples tend to have this unlinked file diagnostic.

**Comment by flodiebold** [comment]
IMO marking the whole file as unused is indeed too much. It'd be nice if we could e.g. show a warning banner instead.

**Comment by lnicola** [comment]
Or we could put the diagnostic on the first line, I suppose.

**Comment by jonas-schievink** [comment]
We can also stop marking the diagnostic as unused, I think that way VS Code will only underline the first 2 characters or so. Not sure about other clients though.
