### ISSUE TITLE
"Show RA version" in vscode shows empty string

### ISSUE THREAD

**Issue by crumblingstatue** [rust-analyzer/rust-analyzer#8224]
In the ctrl+shift+p menu, I select "Rust Analyzer: Show RA version", and it shows this 
![image](https://user-images.githubusercontent.com/1521976/112749266-85222680-8fc1-11eb-81b2-452d0062eb9f.png)

Extension version is v0.2.529, and vscode version is 
```
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-24T18:27:15.725Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.10-arch1-1
```
I'm running the OSS version, and installed RA through the .vsix file in the github releases page.

**Comment by Veykril** [comment]
This is fixed in the next stable release 👍

**Comment by crumblingstatue** [comment]
Just to make it clear: Is it only supposed to show "nightly" if I have the latest version installed through the official github releases .vsix?

**Comment by Veykril** [comment]
It should show nightly + commit-hash 🤔 
![image](https://user-images.githubusercontent.com/3757771/112869038-01e5fb00-90bd-11eb-9c47-ff848ada576e.png)

**Comment by crumblingstatue** [comment]
![image](https://user-images.githubusercontent.com/1521976/112872179-5b9bf480-90c0-11eb-88aa-6b955806e7d8.png)
It only shows this to me.
Should I open an issue about this?

**Comment by crumblingstatue** [comment]
The reason I'm so interested in this is version info for bug reports. This *is* the recommended way to get the version info for bug reports, right? Or is there a more recommended way?

**Comment by Veykril** [comment]
This certainly is the way(that or client logs which should show the same output I'm pretty sure). Are you on the stable extension(judging from the issue logs from earlier you are right)?

**Comment by crumblingstatue** [comment]
I installed the extension through the `.vsix` file contained on this release page: https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-03-29
Looking at rust-analyzer output, it says `INFO [3/29/2021, 6:16:49 PM]: Extension version: 0.2.538`

**Comment by crumblingstatue** [comment]
I think for the time being I'll try to remember to use the rust-analyzer client log to get the version info, but we can reopen this issue, or I can open a new issue, and I want to help to get to the bottom of this.

**Comment by Veykril** [comment]
That is rather weird, you are using the stable client while it shows you just a `nightly` string, it should show the release tag instead I think 🤔 For the time being yes please open a new issue if you wouldn't mind. This sounds certainly wrong.
