### ISSUE TITLE
Enter key doesn't work in *.rs files

### ISSUE THREAD

**Issue by Aloso** [rust-analyzer/rust-analyzer#823]
I installed rust-analyzer ~ 10 min ago.

When I press **Enter** or **Shift+Enter**, nothing happens. Only **Ctrl+Enter** works. Only rust files are affected.

VS Code: 1.31.1
OS: Manjaro (Linux 4.19) with KDE Plasma
Keyboard: German

**Comment by matklad** [comment]
That probably means rust analyzer is not actually working. Does the "Rust Analyzer: Status" command works?

**Comment by Aloso** [comment]
No, it doesn't. Can I fix it?

**Comment by matklad** [comment]
Probably, but we need to figure out what's wrong in the first place :) 

Is there "rust-analyzer" section in the "Output" tab of the vs code panel?

**Comment by Aloso** [comment]
The tab is empty.

**Comment by Aloso** [comment]
I'm confused, because when I hover over a struct or trait name, the definition is shown. Doesn't this mean that ra is working?

**Comment by Aloso** [comment]
I just re-installed it. Now the output says:

```
[Error - 21:23:15] Request textDocument/hover failed.
  Message: content modified
  Code: -32801 
[Error - 21:23:16] Request textDocument/hover failed.
  Message: content modified
  Code: -32801
ERROR [ra_lsp_server::main_loop] unknown request: RawRequest { id: 26, method: "m/decorationsRequest", params: Object({"uri": String("file:///home/ludwig/Develop/glutin_2018/src/lib.rs")}) }
```

**Comment by Aloso** [comment]
When I press Enter, this is printed to the output:

```
ERROR [ra_lsp_server::main_loop] unknown request: RawRequest { id: 113, method: "m/onEnter", params: Object({"position": Object({"character": Number(0), "line": Number(39)}), "textDocument": Object({"uri": String("file:///home/ludwig/Develop/glutin_2018/src/tests.rs")})}) }
```

**Comment by matklad** [comment]
>ERROR [ra_lsp_server::main_loop] unknown request: RawRequest { id: 26, method: "m/decorationsRequest", params: Object({"uri": String("file:///home/ludwig/Develop/glutin_2018/src/lib.rs")}) }

That means that you use a severely outdated version of the VS Code extension. Have you installed the analyzer from the master branch using `cargo install-code` command?

**Comment by Aloso** [comment]
Yes, I did. However, I just did a `git pull`, then `cargo install-lsp``and `cargo install-code`, and now Enter works.

**Comment by Aloso** [comment]
Before I did `git pull`, the last commit was `65266c6`. It seems like merge #816 fixed it.

**Comment by matklad** [comment]
Note that we could have renamed the plugin itself (probably? I don't remember), so it might be a good idea to check vscode extensions list for a stale one.

**Comment by Aloso** [comment]
No, there's only one plugin. But it's possible that forgot `cargo install-lsp` the first time, so an outdated version was used. Thanks anyway for the help ;)

**Comment by DJMcNab** [comment]
We have renamed the plugin I think.
