### ISSUE TITLE
Automatically download the language server

### ISSUE THREAD

**Issue by Timmmm** [rust-analyzer/rust-analyzer#8230]
The VSCode extension asks me every week if I want to download the updated language server. It would be nice if there was an "Always yes" option so it didn't keep asking.

**Comment by lnicola** [comment]
Try `"rust-analyzer.updates.askBeforeDownload": false`.

**Comment by Timmmm** [comment]
Ooo nice! It would be good to have a way of disabling that option from the notification message. Or I guess just mentioning that it exists would be decent.

**Comment by opeik** [comment]
> Try `"rust-analyzer.updates.askBeforeDownload": false`.

I have this option enabled, but rust-analyzer is still asking to install the update.

**Comment by lnicola** [comment]
@opeik what do you mean by enabled? And can you post a screenshot?

**Comment by opeik** [comment]
> @opeik what do you mean by enabled? And can you post a screenshot?

As in I've explicitly set `"rust-analyzer.updates.askBeforeDownload": false`. I'll post a screenshot
 tomorrow once it pops up again. 
 
 ![Screen Shot 2021-08-08 at 16 46 04](https://user-images.githubusercontent.com/11566773/128626442-8bd21507-a74d-4db0-a243-1efcdd98aa0a.png)

**Comment by opeik** [comment]
As promised.

![Screen Shot 2021-08-09 at 11 21 37](https://user-images.githubusercontent.com/11566773/128657226-dbf9f796-eb09-4517-9919-67abee5669e3.png)

**Comment by SomeoneToIgnore** [comment]
There actually are two separate prompts currently:

* for downloading the server binary, which is suppressed by the settings discussed above:
https://github.com/rust-analyzer/rust-analyzer/blob/ac50e35325231c5ac72541f3e96c4e119b2e2566/editors/code/src/main.ts#L349-L355

 * for downloading the VSCode client update, which is not anyhow currently suppressed:
https://github.com/rust-analyzer/rust-analyzer/blob/ac50e35325231c5ac72541f3e96c4e119b2e2566/editors/code/src/main.ts#L215-L219

-----------

The documentation for the setting mentions the server part here:
https://github.com/rust-analyzer/rust-analyzer/blob/cb13e4a2ca6d2f4c19b6a9959288142dffc4c32c/docs/user/manual.adoc#vs-code

and mentions no download proposals with askBeforeDownload = false
https://github.com/rust-analyzer/rust-analyzer/blob/cb13e4a2ca6d2f4c19b6a9959288142dffc4c32c/docs/user/manual.adoc#nightly

> If you don’t want to be asked for Download now every day when the new nightly version is released add the following to your settings.json:

Also in the VSCode settings description, we mention generic files downloading for this toggle:
https://github.com/rust-analyzer/rust-analyzer/blob/93433364ab7c2bf7a4b91b73245e7b7f3f8e1e76/editors/code/package.json#L319-L323

-----------

So, looks like if we wrap another prompt in `if (config.askBeforeDownload)` check, it won't contradict the documentation at least (which we can also update, to explain it more transparent in all 3 places what exactly the flag does after all the changes).

**Comment by bjorn3** [comment]
> for downloading the VSCode client update, which is not anyhow currently suppressed:

That one IMHO shouldn't be suppressed as it causes the editor window to reload to load the updated extension. This can result in lost work and is otherwise just annoying when happening without an explicit user action.

**Comment by opeik** [comment]
An option would be nice anyhow.

**Comment by lnicola** [comment]
The server binary is now bundled with the extension and we rely on the Marketplace to update the latter.
