### ISSUE TITLE
Extract function assist should create mutable reference where necessary

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#8234]
Example:

```rust
fn foo() {
    let mut x = 5;
    for _ in 0..10 {
        x += 1; // extract this
    }
}
```

Extracting the loop body into a function generates `fn fun_name(mut x: i32)` rather than `fn fun_name(x: &mut i32)`, changing semantics.

If a `&mut self` method is called on a non-`Copy` type in the code being extracted, the same thing happens – except then it results in a compilation error rather than changed semantics.

Not sure whether this is strictly related, but if a local variable is already of type `&mut T` and is made part of the argument list by the assist, ra generated `mut x: &mut T`, even if `x` is never re-assigned. (should I open a separate issue about this?)

**Comment by Veykril** [comment]
So the issue here is that the assist tries to be too smart. Basically it checks whether the binding is used after the extraction range or not. If it isn't, like in this case, it moves the binding even though thats invalid here due to the loop.
