### ISSUE TITLE
Can't move item command in some circumstances

### ISSUE THREAD

**Issue by redactedscribe** [rust-analyzer/rust-analyzer#8236]
[Move item command](https://github.com/rust-analyzer/rust-analyzer/pull/8054) was recently added to rust-analyzer.

```rust
|#[derive(Debug)]
enum FooBar {
    Foo,
    Bar,
}
```

If the cursor is on the left side of the `#` symbol, the move item action cannot be performed. Same goes for the keywords `fn` or `impl` (or an `enum` without an attribute above it).

```rust
|const FOO: &str = "Bar";
```

With the cursor on the left side of a `const` however, the move action works without needing to "be inside" it (i.e. cursor to the right side of `c`).

```rust
fn foobar() {
    // ...
}|
```

Interestingly, if the cursor is on the right side of the ending curly brace of a function (what could be considered "not inside" the function), the move action still succeeds.

I don't know if this all expected behavior, but I thought I'd mention it as it seems inconsistent.

Thanks.

rust-analyzer nightly https://github.com/rust-analyzer/rust-analyzer/commit/01dc53a31c39fe754c7228646c456325e49e8d09 (2021-03-29)

**Comment by ivan770** [comment]
Movability of some nodes (like attributes) can be added by adding its node to this list https://github.com/rust-analyzer/rust-analyzer/blob/5dd6b931388dac00d272a41a139c4f0cc3c449dc/crates/ide/src/move_item.rs#L44-L70
About putting cursor at the start or end of some nodes - yeah, that seems to be a problem. Current algorithm relies simply on getting first token/node that is under cursor, checking if it's eligible for moving, and if it can be moved, we move it. If item under cursor is not movable - we expand selection for next node ancestor, and so on, until we find a movable node.

**Comment by ivan770** [comment]
I can work on that, though it would be awesome if someone collected a list of some common movability inconsistencies.

**Comment by Veykril** [comment]
I think you can check if the selection range is empty and in that case take a biased(biased towards non whitespace) token, via `file.token_at_offset(position.offset)`, like hover does for example https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/hover.rs#L93. That should fix most problems with no selection, I think?

**Comment by ivan770** [comment]
> I think you can check if the selection range is empty and in that case take a biased(biased towards non whitespace) token, via `file.token_at_offset(position.offset)`, like hover does for example https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/hover.rs#L93. That should fix most problems with no selection, I think?

I'll take a look at it, thanks!
