### ISSUE TITLE
Intra-doc info: Support URL fragment specifiers

### ISSUE THREAD

**Issue by crumblingstatue** [rust-analyzer/rust-analyzer#8238]
```Rust
pub mod theitem {
    /// This is the item. Cool!
    pub struct TheItem;
}

/// Gives you a [`TheItem`].
///
/// [`TheItem`]: theitem::TheItem
pub fn gimme() -> theitem::TheItem {
    theitem::TheItem
}
```

This does not resolve currently.
rust-sfml [uses these kind of intra-doc links extensively](https://github.com/jeremyletang/rust-sfml/blob/master/src/graphics/render_states.rs#L50-L52).

[Description of this feature for reference](https://doc.rust-lang.org/rustdoc/linking-to-items-by-name.html)

**Comment by Veykril** [comment]
I assume this is meant in regards to hover/highlighting? For link rewriting we should be supporting these already

**Comment by Veykril** [comment]
Heh this is tricky, the reason this doesn't work is that hover and goto impl work on the `ast::Comment` which doesn't contain the entire markdown text so most links are actually broken. So the problem at hand is to figure out how to map the cursor pos into the entire item's hir doc string.

**Comment by crumblingstatue** [comment]
> I assume this is meant in regards to hover/highlighting? For link rewriting we should be supporting these already

Yeah, it's for the new link hover/hightlighting support
