### ISSUE TITLE
Incorrect version string in "Show RA Version" output

### ISSUE THREAD

**Issue by crumblingstatue** [rust-analyzer/rust-analyzer#8239]
Using the latest rust-analyzer release (installed through .vsix, see Background), the "Show RA Version" command simply shows `nightly`, with no further details.

Background:
I'm using the OSS version of VSCode, which does not support the official marketplace. The alternate marketplace always gets the RA updates late, so I always use [the `.vsix` file](https://github.com/rust-analyzer/rust-analyzer/releases/download/2021-03-29/rust-analyzer.vsix) on the GitHub Releases page to install the latest version of rust-analyzer when it comes out.

VSCode OSS version info:
```
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-24T18:27:15.725Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.10-arch1-1
```
Rust-analyzer version (according to Rust Analyzer Client log): `INFO [3/29/2021, 6:16:49 PM]: Extension version: 0.2.538`

See https://github.com/rust-analyzer/rust-analyzer/issues/8224 for the discussion leading up to this issue.

**Comment by Veykril** [comment]
What do the client logs say about the server version?

**Comment by crumblingstatue** [comment]
> What do the client logs say about the server version?

The only information I can find regarding server version is
```
INFO [3/29/2021, 6:16:49 PM]: PersistentState: {
  lastCheck: undefined,
  releaseId: undefined,
  serverVersion: '0.2.538'
}
```
It's the same as the extension version. Is it supposed to be?

**Comment by Veykril** [comment]
It is supposed to be the same yes and I think I know the problem. I imagine if you run the server with the `--version` flag yourself you will get the proper stable tag but we slice it too much in the vscode plugin so it disappears.

**Comment by crumblingstatue** [comment]
See #8495 for some additional information. It seems that the distributed RA executable simply reports "nightly" with the --version flag
