### ISSUE TITLE
Incorrect "Missing match arm" error in tooltip

### ISSUE THREAD

**Issue by imranmaj** [rust-analyzer/rust-analyzer#8249]
The following code compiles correctly using cargo/rustc with no warnings or errors:

```rust
use std::cmp::Ordering::*;

#[allow(dead_code)]
fn foo(a: u32, b: u32, c: u32) {
    match (a.cmp(&b), a.cmp(&c), b.cmp(&c)) {
        (Less | Equal, Greater, _) => (),
        (Greater, Less | Equal, _) => (),
        (Greater, Greater, Less) => (),
        (Greater, Greater, Greater) => (),
        (Less | Equal, Less | Equal, Less) => (),
        (Less | Equal, Less | Equal, Greater) => (),
        (_, _, Equal) => (),
    }
}
```

but rust-analyzer continues to show the red underline indicating an error (even after file save, language server restart, VSCode window reload, and VSCode editor restart). Hovering over the underline shows this tooltip:

![image](https://user-images.githubusercontent.com/49664304/112913565-bfb5bd00-90ae-11eb-8b20-b53eb5749789.png)

which states that rust-analyzer believes there is a missing match arm, despite all possible cases being covered.

Rust Analyzer version: `v0.2.538`
VSCode version information:
```
Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```
Rust version: `rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)`
Rust toolchain: `nightly-x86_64-pc-windows-msvc`
Compilation target triple: `x86_64-pc-windows-msvc`

**Comment by Jesse-Bakker** [comment]
The problem seems to be with `or_patterns`:

```rust
enum Either {A, B}

fn main() {
    match (Either::A, Either::B) {
        //^^^^^^^^^^^^^^^^^^^^^^ Missing match arm
        (Either::A | Either::B, _) => (),
    }
}
```

**Comment by Veykril** [comment]
Ye most likely those aren't really implemented at all yet in our usefulness checks I think. I got interested in checking that part out recently actually as I read through the paper it (and rustc's check) is based on.

**Comment by Jesse-Bakker** [comment]
It was actually a subtle bug in the specialization of OR-patterns:

When specializing `(A | B, _)`, the intended matrix looks like `Matrix( [PatStack([A,  _]), [PatStack([B, _])])`, but would instead become `Matrix( [PatStack([A]), PatStack([B])] )`, dropping the tail of tuple patterns. These are of course not covered by [PatStack([_, _])], causing the bug.
