### ISSUE TITLE
Weird letters

### ISSUE THREAD

**Issue by fautioT** [rust-analyzer/rust-analyzer#8264]
Hello, here is the problem I have I don't know how to fix it. Could you help me?
![Capture d’écran (285)](https://user-images.githubusercontent.com/65911636/113010160-ea6c4800-9178-11eb-9497-92ec4ade2f3a.png)

**Comment by lnicola** [comment]
That's not a problem. Your debugger is helpfully interpreting binary data as UTF-8 strings. And of course, you must have gotten the wrong repository.
