### ISSUE TITLE
remap-path-prefix breaks links to dependencies

### ISSUE THREAD

**Issue by Systemcluster** [rust-analyzer/rust-analyzer#8277]
When the `--remap-path-prefix` rustflag is set, links to dependencies in tooltips try to access the remapped path, which doesn't exist.

![image](https://user-images.githubusercontent.com/2847328/113208005-9b560e00-9271-11eb-870d-9e43f879b594.png)

My `rustflags` contain these lines:

```
"--remap-path-prefix=C:/Users/Username/=/",
"--remap-path-prefix=C:\\Users\\Username\\=\\"
```

**Comment by jonas-schievink** [comment]
This looks like an issue on the rustc side, since we just use what it outputs in its diagnostics. It might be expected behavior of `--remap-path-prefix`, even.

**Comment by flodiebold** [comment]
Yeah, I don't think there's anything we can do in rust-analyzer about this.
