### ISSUE TITLE
Aliased std type shows incorrect documentation

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#8281]
In my code I regularly import `smartstring::alias::String`. However, I just noticed that RA is now showing documentation from `alloc::String` if I hover over the `String` type instead of the documentation from smartstring:

<img width="288" alt="Screen Shot 2021-04-01 at 13 37 53" src="https://user-images.githubusercontent.com/158471/113288606-799b6c00-92ef-11eb-8e74-3ccb4657a5c1.png">

<img width="470" alt="Screen Shot 2021-04-01 at 13 38 13" src="https://user-images.githubusercontent.com/158471/113288631-84560100-92ef-11eb-9a32-f0910b53e68b.png">

(I'm pretty sure this is a regression from the past few weeks, or I would have noticed it.)

**Comment by Veykril** [comment]
I can't seem to reproduce this 😕

**Comment by Veykril** [comment]
Oh nevermind I can, it's macros causing problems with nameres/nameclassification again 😅 Hover works correctly if no macros are in the body, adding a macro call to the body causes this.

**Comment by djc** [comment]
Thanks for the quick fix!
