### ISSUE TITLE
In nvim normal mode， the virtual  hint always twinkle

### ISSUE THREAD

**Issue by cloud-mist** [rust-analyzer/rust-analyzer#8289]
1. my environment:
    - nvim
    - coc-rust-analyzer
2. question:
    - I am in normal mode.When I move the cursor, then the places  I marked twinkle. Move once, twinkle once.<br>
This problem makes me mad.How to solve it?
    - `Run debug`, how I use this button? I can't click and move on it. Or how I conceal it?
<img src=https://user-images.githubusercontent.com/49445212/113380729-8da6a280-93af-11eb-953c-6f302bfcbd24.png width=60%>

**Comment by lf-** [comment]
The flickering might be a bug in Coc or the editor integration, for what it's worth, although I think I've also seen it in VSCode to some extent. Have you seen it show up on other languages?

To use these code lenses, you have to define a mapping for `<Plug>(coc-codelens-action)` in your `init.vim` (see `:h n_coc-codelens-action`)

Re: how to disable these, they're code lenses: the config key `rust-analyzer.lens.enable` should do it. This is also enabled globally with the coc config item `codeLens.enable` (see `:h coc-config-codelens`).

**Comment by lnicola** [comment]
`coc-rust-analyzer` is independent from the Code extension in this repo: https://github.com/fannheyward/coc-rust-analyzer/.

**Comment by cloud-mist** [comment]
> The flickering might be a bug in Coc or the editor integration, for what it's worth, although I think I've also seen it in VSCode to some extent. Have you seen it show up on other languages?
@lf- I have never seen this on other languages.Because I also have never seen the virtual hint text on other languages.<cr>
 I learned a lot from your words. Now I have changed `codelens.enable`'s  status to `false`.And my problem is solved.  :smile: 
Thank you very much. :+1:
