### ISSUE TITLE
Rust analyzer incorrectly reports missing  `#[allow(unused)]`

### ISSUE THREAD

**Issue by Raz-Hemo** [rust-analyzer/rust-analyzer#8296]
I have a struct that uses the `rental` crate's macro for self referencing. Even though my code builds, rust analyzer outputs the following error in VS code:
```
proc macro returned error: proc-macro panicked: expected prefix "#[allow(unused)]" not found in "# [allow (unused)] enum ProceduralMasqueradeDummyType {Input = (0 , stringify ! (use super ::*;# [rental] pub struct ResolutionDependents {fbos : Box < Fbos >, framebuffer : (MultiOutputFrameBuffer < \'fbos >, & \'fbos Fbos) ,})) . 0}"
```

My guess is that it trips on extra whitepsace (i.e. `# [allow (unused)]` instead of `#[allow(unused)]`), though the internal `rental` macro seems to not have that whitespace:
```
			#[allow(unused)]
			#[derive(__rental_structs_and_impls)]
			enum ProceduralMasqueradeDummyType {
				Input = (0, stringify!($($body)*)).0
			}
```

This is my own code:
```
rental! {
    mod rentals {
        use super::*;

        #[rental]
        pub struct ResolutionDependents {
            fbos: Box<Fbos>,
            framebuffer: (MultiOutputFrameBuffer<'fbos>, &'fbos Fbos),
        }
    }
}
```

This happened after I updated to the latest rust analyzer, but I haven't used it for several months so can't remember what the old version was.

![image](https://user-images.githubusercontent.com/21125918/113434791-44277900-93ea-11eb-9ad3-75b857a6f57f.png)

**Comment by bjorn3** [comment]
This is a bug in rental. It doesn't handle extra white space in the proc macro input. Rustc doesn't make any guarantee that it doesn't add extra white space. It just happens to not do so at the moment, but it is allowed to change this, which would break rental completely.

By the way rental is no longer maintained.

**Comment by Raz-Hemo** [comment]
Gotcha, thanks.
