### ISSUE TITLE
Incorrect method resolution with Deref + const generics

### ISSUE THREAD

**Issue by dalcde** [rust-analyzer/rust-analyzer#8308]
The following code is correct but rust-analyzer marks it as invalid at the location marked with `<--`
```rust
pub struct Inner();

impl Inner {
    pub fn foo(&self) {}
}

pub struct Outer<const N: usize> {
    inner: Inner,
}

impl<const N: usize> std::ops::Deref for Outer<N> {
    type Target = Inner;
    fn deref(&self) -> &Inner {
        &self.inner
    }
}

impl Outer<0> {
    pub fn foo(&self, _: i32) {}
}

impl Outer<1> {
    pub fn bar(&self) {
        self.foo() // <--
    }
}
```

The `self.foo` in `Outer::<1>::bar` should resolve to `Inner::foo` under `Deref`. However, `rust-analyzer` thinks it resolves to `Outer::<0>::foo` and thinks that it has the wrong number of arguments.

**Comment by flodiebold** [comment]
We don't support const generics at all yet.

**Comment by flodiebold** [comment]
This is fixed.
