### ISSUE TITLE
Faint code in VSCode extension

### ISSUE THREAD

**Issue by Heinenen** [rust-analyzer/rust-analyzer#8311]
Hi I'm just getting started with Rust and tried using the rust-analyzer extension for VSCode. I noticed that the code faints after the extension finishes indexing the project (see screenshots). This happens for me with versions 0.2.538 and 0.2.529, but not with older ones.
I tried the extension on both my computer with Linux Mint (20.1), with VSCode version 1.54.3 and my notebook with Manjaro with the same results.

Older version (0.2.521)
![without](https://user-images.githubusercontent.com/37484430/113483822-a72a1600-94a5-11eb-9f69-f26468d6707b.png)
Newest version (0.2.539)
![with](https://user-images.githubusercontent.com/37484430/113483828-ac876080-94a5-11eb-9552-8cf7ac6299b5.png)
![unlinked](https://user-images.githubusercontent.com/37484430/113483831-aee9ba80-94a5-11eb-92cd-003c5749d1e7.png)

**Comment by jonas-schievink** [comment]
This is fixed in git, you need to wait for the next release or build from git.
