### ISSUE TITLE
File not included in module tree on rustlings

### ISSUE THREAD

**Issue by Shadowblitz16** [rust-analyzer/rust-analyzer#8316]
![image](https://user-images.githubusercontent.com/2453707/113490042-96b17580-947c-11eb-9d4d-8f5085b3ffcc.png)

**Comment by flodiebold** [comment]
This is correct, rustlings has a somewhat weird project structure: https://github.com/rust-lang/rustlings/issues/443, which is also why you won't get good IDE support in those files, sadly.

**Comment by flodiebold** [comment]
It might be a good idea for rustlings to disable this diagnostic in their workspace; and then once we implement #6388, it should work fine.
