### ISSUE TITLE
Associated items are not resolved

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#832]
Some pointers:

- https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_hir/src/nameres.rs#L635 should probably handle `ModuleDef::Struct(s)` by returning `PerNs::types((*s).into())`
- according to @matklad, https://github.com/rust-analyzer/rust-analyzer/blob/b85c189500a47f3c5f7690250611b06e08616c9a/crates/ra_hir/src/ty.rs#L1107-L1132 should then find the associated method. In my tests, `infer_path_expr` didn't seem to get called when triggering hover / go to definition.

Test cases: 

 - hover on `String::new()`
 - `let s = String::new()`, hover on `s`

**Comment by flodiebold** [comment]
For go to definition, this will probably work similar to the way fields and methods currently work: During type inference, when we resolve an associated item, we record it in a map similar to these ones:
https://github.com/rust-analyzer/rust-analyzer/blob/b85c189500a47f3c5f7690250611b06e08616c9a/crates/ra_hir/src/ty.rs#L785-L786
And then we check that when trying to resolve the definition:
https://github.com/rust-analyzer/rust-analyzer/blob/b85c189500a47f3c5f7690250611b06e08616c9a/crates/ra_ide_api/src/goto_definition.rs#L52-L74

But I'd suggest first getting associated methods properly working for type inference (that should take care of the hover case as well).
> In my tests, `infer_path_expr` didn't seem to get called when triggering hover / go to definition.

It does get called as part of type inference, which will be triggered the first time you hover something in a certain function (or use completion, or...).

**Comment by lnicola** [comment]
Update: after #866 this seems to work for local structs, but not for e.g. `std::time::Duration::new()`.

**Comment by flodiebold** [comment]
I see the problem, the remaining index is being set wrongly when resolving across crates. It's easy to fix, but I don't know on what level to test it yet.

**Comment by matklad** [comment]
>but I don't know on what level to test it yet.

Good question! I feel like we should concentrate the bulk of testing on the public API of HIR.

**Comment by vipentti** [comment]
Additionally, associated method generics are not properly resolved yet. See

https://github.com/rust-analyzer/rust-analyzer/blob/3d8a0982a12f3aa4b8c193a841f864b15c3cb66e/crates/ra_hir/src/ty/tests.rs#L721-L742

Currently this resolves to `a = Gen<T>`.

**Comment by flodiebold** [comment]
I think most of the issues brought up here should be fixed. There are still some problems with normalizing associated types, but they're different.

**Comment by lnicola** [comment]
That's right. We should file separate issues for anything that still remains to be done.
