### ISSUE TITLE
"Format document" doesn't do anything?

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#8331]
Steps to replicate:
1. `cargo new ra-fmt && cd ra-fmt`
2. `echo 'fn main() { println!    ("Hello, world!"); }' > src/main.rs`
3. code src/main.rs
4. Ctrl+Shift+I ("Format document")
5. Nothing happens.

I'm using rust-analyzer v0.2.538.

**Comment by jonas-schievink** [comment]
Did you change the formatter in the settings?

**Comment by jyn514** [comment]
![image](https://user-images.githubusercontent.com/23638587/113522647-592e1480-9570-11eb-8dbb-94b8e8e1b968.png)

Do I need to explicitly set it to matklad.rust-analyzer? Is there a way to do that for only rust files? Does you think it makes sense for rust-analyzer to do that itself?

**Comment by jyn514** [comment]
Still doesn't work with `matklad.rust-analyzer` set as the default formatter:
![image](https://user-images.githubusercontent.com/23638587/113522680-9a262900-9570-11eb-8a19-c8934418c28d.png)

**Comment by Veykril** [comment]
You can set it in the settings file for specific languages
```json
"[rust]": {
    "editor.defaultFormatter": "matklad.rust-analyzer"
},
```
but it should work without having to set this explicitly when you only have one formatter for a language installed(if you do have more vscode usually complains and asks which to use).

**Comment by jyn514** [comment]
Ok, I found the issue: I had my default toolchain set to a nightly without the rustfmt component installed. Maybe RA could check the stable and beta toolchains if the default doesn't work?

**Comment by jyn514** [comment]
Also, I think RA should give an error message instead of silently doing nothing.

**Comment by jonas-schievink** [comment]
Ah, found the problem. After fixing it I get a popup saying that a request failed, and this in the output window:

```
[Error - 12:30:57 AM] Request textDocument/formatting failed.
  Message: rustfmt exited with:
                           Status: exit code: 1
                           stdout: 
                           stderr: error: the 'rustfmt' component which provides the command 'rustfmt' is not available for the 'nightly-2021-04-04-x86_64-unknown-linux-gnu' toolchain

  Code: -32900 
```
