### ISSUE TITLE
Renaming items from external crates results in ra rewriting files in ~/.cargo

### ISSUE THREAD

**Issue by jplatte** [rust-analyzer/rust-analyzer#8338]
I just tried to rename an imported symbol (`serde_json::from_str` to `serde_json::from_json_str`) expecting that the import would be changed to rename the symbol locally (`use serde_json::from_str as from_json_str;`). However, ra instead proceeded to rename the original item in `~/.cargo/registry/github.com-{hash}/serde_json-1.0.64/src/de.rs` which is clearly a bad idea and required me to delete parts of `~/.cargo` and `target` to fix.

**Comment by lnicola** [comment]
CC https://github.com/rust-analyzer/rust-analyzer/issues/6623

**Comment by jplatte** [comment]
Didn't find that issue before reporting this one. Closing as duplicate.

**Comment by lnicola** [comment]
Yeah, I can't find it but somebody posted a video of RA renaming a couple dozen files from `rust-src`.
