### ISSUE TITLE
Replace string with char assist will emit broken code for `\n`

### ISSUE THREAD

**Issue by weiznich** [rust-analyzer/rust-analyzer#8372]
I have the following code
```rust
let s = "\n";
```

Now if I apply the "Replace string with char assist" rust-analyzer will change as follows

```rust
let s = `
`;
```

I expect the following code:
```rust
let s = '\n';
```

**Comment by Veykril** [comment]
This was fixed quite a bit ago, and I also can't seem to reproduce it. Can you make sure you are on the most up to date version?

**Comment by weiznich** [comment]
I've used a version from some days ago, updating to the current version fixed that bug :+1:
