### ISSUE TITLE
Bug whith cfg blocks

### ISSUE THREAD

**Issue by JMS55** [rust-analyzer/rust-analyzer#8378]
```rust
#[cfg(feature = "profile")]
pub struct TaskRecord {
    start: Instant,
}

#[cfg(feature = "profile")]
pub type ProfilingReturnType = TaskRecord;
#[cfg(not(feature = "profile"))]
pub type ProfilingReturnType = ();


pub fn profile_task(name: &'static str) -> ProfilingReturnType {
    #[cfg(feature = "profile")]
    { // Error start
        TaskRecord {
            start: Instant::now(),
        }
    } // Error end
    #[cfg(not(feature = "profile"))]
    let _ = name;
}
```

rust-analyzer: "Remove this semicolon"
It says the error is at the marked region

**Comment by DJMcNab** [comment]
Standalone reproduction ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=104a0547c082d66c67f5302274f45713)):
```rust
fn main() {
    let x = {
        #[cfg(not(any()))]
        let a = "first";
        #[cfg(any())]
        let a = 10;
        a
    };
    let y = {
        #[cfg(not(any()))]
        {
            "second"
        }
        #[cfg(any())]
        let a = 10;
    };
    dbg!(x, y);
}
```
Note that rust-analyzer infers the type of `x` to be `&str` correctly, but incorrectly infers the type of `y` to be `()` incorrectly.
![image](https://user-images.githubusercontent.com/36049421/113851440-6b3bcd00-9793-11eb-8284-cc7a5cc50915.png)

It seems like `cfg` directives are not considered correctly for implicit return, which can only happen using a block.

Interestingly, this case gives the type of y as unknown:
```rust
fn main() {
    let y = {
        #[cfg(not(any()))]
        { "second" }
        #[cfg(any())]
        false
    };
}
```
