### ISSUE TITLE
RA can't expand rustc_hir::lang_items::language_item_table

### ISSUE THREAD

**Issue by jyn514** [rust-analyzer/rust-analyzer#8391]
This is just a normal macro, not a proc-macro, so not sure what could be going wrong.

Reproduction steps:
1. Checkout https://github.com/rust-lang/rust/commit/1247250d506084773806e0562ce925938695b19d
2. Open compiler/rustc_hir/src/lang_items.rs
3. Scroll to line 167 and see that it's all red:

![image](https://user-images.githubusercontent.com/23638587/113803663-03ea3280-972b-11eb-8423-c2b9ea1a8ca4.png)

**Comment by edwin0cheng** [comment]
Should be this line : 

https://github.com/rust-lang/rust/blob/1247250d506084773806e0562ce925938695b19d/compiler/rustc_hir/src/lang_items.rs#L49

```rust
#[doc = concat!("The `", stringify!($name), "` lang item.")]
```

See  #8092

**Comment by jyn514** [comment]
Ah ok, that would do it.
