### ISSUE TITLE
./ra-lsp-0.0.1.vsix --force Error: "No such file or directory" macOS

### ISSUE THREAD

**Issue by madmaxio** [rust-analyzer/rust-analyzer#840]
While installing via cargo install-code (Macos):

Packaged: /Users/maxim/src/rust-analyzer/editors/code/ra-lsp-0.0.1.vsix (132 files, 225.9KB)

will run: code --install-extension ./ra-lsp-0.0.1.vsix --force
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

**Comment by matklad** [comment]
does running `code --install-extension ./ra-lsp-0.0.1.vsix --force` manually work?

**Comment by madmaxio** [comment]
No,code: command not found. Seems like vs code not in the path?

**Comment by bjorn3** [comment]
You could open VS Code, goto extenstions, click three dots on the top right corner of the extensions pane and click "Install from VSIX..."

**Comment by madmaxio** [comment]
Nice, worked, thanx.
