### ISSUE TITLE
Lifetime autocompletion consumes type

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#8404]
```rust
pub(crate) struct ConstantCx<'tcx> {
    symbol_name: &<|>str,
}
```

Insert `'` and select the `'tcx` option. `str` gets removed. Resulting in:

```rust
pub(crate) struct ConstantCx<'tcx> {
    symbol_name: &'tcx<|>,
}
```

**Comment by Veykril** [comment]
Not sure how we can fix this, since adding a ' there turns the `str` part into the lifetime which the client then just replaces 🤔
