### ISSUE TITLE
Hover doc displays codes incorrectly.

### ISSUE THREAD

**Issue by EFanZh** [rust-analyzer/rust-analyzer#8416]
Put mouse pointer over an `if` keyword, this is what I got:

![image](https://user-images.githubusercontent.com/2160692/113974253-30f42d80-9870-11eb-9dc1-5af79063e654.png)

There seems to be some extra backslashes (`\`) before quotation marks (`"`).

**Comment by edwin0cheng** [comment]
triage: 

It does not works ONLY in hover on keyword, normal items works correctly : 

![hover](https://user-images.githubusercontent.com/11014119/114156039-bb15c200-9954-11eb-85e3-9b685b29bbda.png)

**Comment by edwin0cheng** [comment]
Fixed by #8560
