### ISSUE TITLE
incorrect-ident-case doesn't look at #[allow()]s of parent scopes

### ISSUE THREAD

**Issue by lf-** [rust-analyzer/rust-analyzer#8417]
Example: set the crate attribute or module attribute of `#![allow(non_upper_case_globals)]` and put an associated const on a trait, RA will report incorrect-ident-case, which it should not, as it does actually consider `non_upper_case_globals` (see `decl_check.rs`), just not recursively upwards.

```rust
#![allow(non_upper_case_globals)]
fn a() {
trait F {
    const haha_im_bad: bool = true;
}
}
```

**Comment by lf-** [comment]
Complaints on twitter: https://twitter.com/Lokathor/status/1379840443341414411

@rustbot claim

**Comment by lf-** [comment]
Oops the bot is not on here. I intend to work on this, in any case.

**Comment by flodiebold** [comment]
CC #6541
