### ISSUE TITLE
Improve experience when writing crate-level documentation

### ISSUE THREAD

**Issue by JMS55** [rust-analyzer/rust-analyzer#8425]
Once already in a documentation block, RA should maybe do stuff like formatting `//!` even when there's spaces in between, and auto-adding it when you add a new line.

**Comment by lnicola** [comment]
See https://rust-analyzer.github.io/manual.html#on-enter.

**Comment by lnicola** [comment]
Closing, since it's already available (thanks @chetankhilosiya for checking). Enabling it by default is a different story (https://github.com/rust-analyzer/rust-analyzer/pull/6037).
