### ISSUE TITLE
Associated types are highlighted as unresolved references

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#8435]
The dark red in the following screenshot represents unresolved references:

<img alt="Screen Shot 2021-04-09 at 1 34 17 pm" src="https://user-images.githubusercontent.com/31783266/114124768-80059580-9938-11eb-969a-21425251c95b.png">

Curiously, [this example](https://github.com/rust-analyzer/rust-analyzer/issues/6995#issuecomment-749418553) from #6995 works fine in the method definition, but not the implementation:

<img alt="Screen Shot 2021-04-09 at 1 41 08 pm" src="https://user-images.githubusercontent.com/31783266/114125167-3ec1b580-9939-11eb-88c4-dbffe7a8feb0.png">

Possibly related: #5003, #6995, #8283

Output of Show RA Version: `nightly-50-g354151df3`

**Comment by Veykril** [comment]
The `Self::Bar` in the `fn foo(_: Self::Bar)` line in the latter screenshot does resolve for me, just not to i32 but to the general type alias of the trait definition(which I think is another issue with us not being able to resolve back to trait impls yet).

The code in your first screenshot uses inherent type aliases which aren't stable, I don't think RA even handles those at all aside from parsing. At least for name classification we don't expect those.

**Comment by arzg** [comment]
@Veykril

> does resolve for me, just not to i32 but to the general type alias of the trait definition

That is curious. What version of r-a are you on?

> The code in your first screenshot uses inherent type aliases which aren’t stable

Oops, you’re right! Here’s a version that does compile but still has unresolved references:

<img alt="Screen Shot 2021-04-10 at 10 31 13 am" src="https://user-images.githubusercontent.com/31783266/114252329-eac1da00-99e7-11eb-907e-5cb44d479033.png">

**Comment by Veykril** [comment]
![image](https://user-images.githubusercontent.com/3757771/114253476-a95f0980-99aa-11eb-845c-a11f31f613d4.png)
I'm on the latest nightly.

Your other screenshot seems to be the same as https://github.com/rust-analyzer/rust-analyzer/issues/8282, though I guess the title there can be improved

**Comment by arzg** [comment]
> Your other screenshot seems to be the same as #8282

 Hmm, you’re right, I didn’t see that issue. Should I close this because there seem to already be issues for a number of different cases regarding associated types?

**Comment by Veykril** [comment]
If that's the only problem left then I'd say yes let's close this
