### ISSUE TITLE
IDE resolution issues in const block

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#8448]
```rust
struct Foo {}

const _: () = {
    impl<'de> serde::Deserialize<'de> for Foo {
        fn deserialize<__D>(__deserializer: __D) -> Result<Self, __D::Error>
        where
            __D: serde::Deserializer<'de>,
        {
            todo!();
        }
    }
};
```

![image](https://user-images.githubusercontent.com/308347/114194233-f1a10c00-9957-11eb-9039-e4405078e4c0.png)

**Comment by Veykril** [comment]
Looks like the `Resolver` in the constructed `SourceAnalyzer` has no scopes when inside an unnamed const. Naming the const results in resolved names.
