### ISSUE TITLE
`completion.addCallParenthesis ` should respect completion location

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#8452]
When completing functions as arguments to a function where the argument is a function type that matches the type of the to be completed item it should ideally not add call parenthesis so that the identifier can be used as short hand.

Example:
```rust
fn filter_func(_: i32) -> bool {
	true
}
let some_option = Some(3);
let filtered = some_option.filter(filter_f$0);
```
Completing the identifier here should not add call parenthesis so that we merely get `some_option.filter(filter_func)`. Completing the parens here is unnecessary as calling the function in that position wouldn't make sense.

**Comment by SomeoneToIgnore** [comment]
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/3148 ?

**Comment by Veykril** [comment]
Very much so, I didn't know we had an issue for this already
