### ISSUE TITLE
Highlight tuple struct fields like regular struct fields

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#8454]
Currently, fields of tuple structs are highlighted like numbers:

<img alt="Screen Shot 2021-04-10 at 12 31 26 pm" src="https://user-images.githubusercontent.com/31783266/114255760-abe85000-99f8-11eb-96fd-3f64bb2511d8.png">

Compare that to this example with a regular struct:

<img alt="Screen Shot 2021-04-10 at 12 33 26 pm" src="https://user-images.githubusercontent.com/31783266/114255786-f4077280-99f8-11eb-9d54-ac14580a6efc.png">

Tuple struct fields are akin to regular struct fields in purpose, so I’d prefer for the fields of tuple structs to be highlighted like the fields of normal structs instead of numbers, with which they share syntax but not usage.

**Comment by Veykril** [comment]
This seems to have been implemented.
