### ISSUE TITLE
When navigating a large codebase, rust-analyzer takes a while to load.

### ISSUE THREAD

**Issue by Milo123459** [rust-analyzer/rust-analyzer#8470]
I have a suggestion, because it takes a while for rust-analyzer to load a file on a large codebase, maybe analyze the file that is currently open first, and all modules being used in that file first before anything else. I've been waiting about 5 minutes for rust-analyzer on vscode to give me intellisense.

**Comment by lnicola** [comment]
That's practically what we do, but we need to run `cargo metadata` (which can take a while to update the `cargo` registry) and `cargo check` (for proc macros and build scripts, which can be disabled).

**Comment by Milo123459** [comment]
Ah thanks. Sorry for making this issue.

**Comment by lnicola** [comment]
No worries. If you have a project where slowness isn't explained by an initial `cargo check`, you should file an issue, since it might be something fixable.
