### ISSUE TITLE
Import code action not working correctly with coc.nvim

### ISSUE THREAD

**Issue by OleStrohm** [rust-analyzer/rust-analyzer#8472]
Using coc.nvim with coc-rust-analyzer with the following code and the cursor on `R` in `Range` I get the action "Consider importing one of these items".
```rust
fn main() {
    let _ = Range { start: 0, end: 1 };
}
```
However after calling that code action, without any intervention, the code ends up as
```rust
use core::ops::Range;

use std::collections::btree_map::Range;

use std::collections::btree_set::Range;

use std::ops::Range;

fn main() {
    let _ = Range { start: 0, end: 1 };
}
```
What I expect to see is a prompt to be able to select one of the options, and not to have all the options inserted into my code.
This may be an issue with coc.nvim or coc-rust-analyzer, so here are all the versions:

vim version: NVIM v0.5.0-dev+1099-g4d5dbea4f
node version: v12.18.2
coc.nvim version: 0.0.80-2cece2600a
rust-analyzer: 2021-04-05
coc-rust-analyzer: 0.40.0

**Comment by flodiebold** [comment]
Hmm. Do you not get the rust-analyzer code `Import` / `Qualify` code actions? "Consider importing one of these items" is coming from rustc and probably can't be improved much (I assume it's marked as not machine-applicable, and I don't think rustc can provide multiple options as separate fixes?). Weirdly, in Emacs I only get the rustc fix on the `fn main()` line, not when the cursor is on `Range`.

**Comment by flodiebold** [comment]
Hmm, which command are you using to apply code actions with CoC?

**Comment by OleStrohm** [comment]
I use `nmap <leader>ac  <Plug>(coc-codeaction)` as per their example configuration.

It does seem that I only receive rustc provided fixes then. Should I open an issue for coc-rust-analyzer instead?

Though I do also get the code actions for extracting into variable and function when using the `<Plug>(coc-codeaction-selected)`, which is a RA code action, right?

**Comment by flodiebold** [comment]
`coc-codeaction` is the wrong function to use, you should use `coc-codeaction-cursor` or `coc-codeaction-selected`. (This is mentioned in the [manual](https://rust-analyzer.github.io/manual.html#vimneovim); IMO `coc-codeaction` is a footgun that shouldn't exist.)

**Comment by OleStrohm** [comment]
Ahh, okay, I'll change it.

Thank you for your help!
