### ISSUE TITLE
Trait function impl code action not working correctly in coc.nvim

### ISSUE THREAD

**Issue by OleStrohm** [rust-analyzer/rust-analyzer#8473]
Using coc.nvim with coc-rust-analyzer with the following code and the cursor inside the impl I get the action "implement the missing item: ...".
```rust
struct Foo(u32);
impl From<Foo> for u32 {

}
```
However after calling that code action the code ends up as
```rust
struct Foo(u32);
impl From<Foo> for u32 {

fn from(_: T) -> Self { todo!() }
}
```
Which both has no indentation or newlines, though that may be intentional, and is easily fixed with rustfmt, but the parameter of the function is `T`, which doesn't seem intentional.

What I expect to see is an implementation with `T` being `Foo`, and maybe correct formatting.

This may be an issue with coc.nvim or coc-rust-analyzer, so here are all the versions:

vim version: NVIM v0.5.0-dev+1099-g4d5dbea4f
node version: v12.18.2
coc.nvim version: 0.0.80-2cece2600a
rust-analyzer: 2021-04-05
coc-rust-analyzer: 0.40.0

**Comment by flodiebold** [comment]
I can't reproduce this in either VSCode or Emacs. It seems to be a CoC bug.

**Comment by OleStrohm** [comment]
It seems this issue is the same as #8472, so I'll close this.
