### ISSUE TITLE
Unsafe associated functions aren't highlighted like unsafe free functions

### ISSUE THREAD

**Issue by danielzfranklin** [rust-analyzer/rust-analyzer#8474]
First off, thank you for creating such an awesome piece of software. I'm amazed by how much works out of the box.

I've configured VSCode to highlight unsafe functions and operators in red.

```json
"editor.semanticTokenColorCustomizations": {
        "[My Theme Name]": {
            "rules": {
                "operator.unsafe": "#ff6600",
                "function.unsafe": "#ff6600"
            }
        }
    },
```

If I input the following code it is incorrectly highlighted.

```rust
fn foo() {
    unsafe { unsafe_fn() };
    unsafe { Foo::unsafe_assoc_fn() };
}

unsafe fn unsafe_fn() {}

pub struct Foo;

impl Foo {
    unsafe fn unsafe_assoc_fn() {}
}
```

Actual:
![actual](https://user-images.githubusercontent.com/10361846/114321638-bc411d80-9b13-11eb-80e4-d2be21254eac.png)

Expected: Associated functions and methods are highlighted as unsafe.

If this is a bug, and you think it's suitable for a beginner, I'd be interested in contributing a PR.

**Comment by Veykril** [comment]
This works fine for me, I believe you might have a bad highlighting rule that isnt applicable here. Can you check the semantic tokens of `unsafe_assoc_fn`? You can do that by pressing `ctrl + shift + p`/`f1` and running `Developer: Inspect Editor Tokens and Scopes`. That will show you a special hover for the token your cursor is on like here 
![image](https://user-images.githubusercontent.com/3757771/114325734-f1f4ff00-9b31-11eb-8b62-fa448dd9283c.png)

I assume your semantic highlighting rules are something like:
```
"method.static:rs": ...,
"method.unsafe:rs": ...,
```
those collide, probably causing static to take priority for you here. You'd need an extra rule
```
"method.static.unsafe:rs": ...
```
set to the unsafe color in that case.

**Comment by danielzfranklin** [comment]
Thank you. I didn't know I needed a separate highlighting rule for methods. I had copied the example I saw in [the changelog](https://rust-analyzer.github.io/thisweek/2020/06/08/changelog-28.html) because I didn't see any docs anywhere else when googling for this feature.

My semantic highlighting modifications to the theme I use were previously only what I included above

```json
"editor.semanticTokenColorCustomizations": {
        "[My Theme Name]": {
            "rules": {
                "operator.unsafe": "#ff6600",
                "function.unsafe": "#ff6600"
            }
        }
    },
}
```

Based on your advice I fixed it to look like
```json
"editor.semanticTokenColorCustomizations": {
        "[My Theme Name]": {
            "rules": {
                "operator.unsafe": "#ff6600",
                "function.unsafe": "#ff6600"
                "method.unsafe": "#ff6600"
            }
        }
    },
}
```

Adding `:rs` as you suggested didn't work, the rules didn't apply to any code.

**Comment by Veykril** [comment]
Right it should be `:rust` but that doesn't matter, that makes it only apply to rust specifically then.

I take it the problem is resolved then?

And yes semantic highlighting isnt well documented in vscode at least from what I remember, we might want to improve our docs on this just because.

**Comment by danielzfranklin** [comment]
Yep, my problem is resolved. I've made a PR that adds this to the docs: https://github.com/rust-analyzer/rust-analyzer.github.io/pull/100
