### ISSUE TITLE
Incorrect mismatched-arg-count inside closure 

### ISSUE THREAD

**Issue by mikeando** [rust-analyzer/rust-analyzer#8479]
This is an interesting bug I ran into when using rust-analyser in VSCode.
After chopping out a lot of code, I've managed to get it down to this reproducer.
It probably can be cut down further, but I think this is enough to easily reproduce it.

```
#[derive(Debug)]
pub struct Error {}

pub trait R {}

pub trait A {
    fn apply_closure(
        &self,
        f: &mut dyn FnMut(&dyn A, &dyn B),
    );

    fn f(&self, p: i32) -> Result<Box<dyn R>, Error>;
}

pub trait B {
    fn f(&self) -> Result<Box<dyn R>, Error>;
}

pub fn load(_a: &dyn A) {
    a.apply_closure(&mut |a, b| {
        b.f().unwrap();
    });
}
```

`cargo build` works just fine, but in the VSCode GUI I get the error:

```
Expected 1 argument, found 0
```

on the line:

```
b.f().unwrap();
```

I'm not sure what version of rust-analyser I'm running behind the scenes - but VSCode updated it today, so it should be recent.  If you need that information, or anything else, let me know and  I'll try to track it down.

**Comment by lnicola** [comment]
Fixed code sample:

```rust
#[derive(Debug)]
pub struct Error {}

pub trait R {}

pub trait A {
    fn apply_closure(&self, f: &mut dyn FnMut(&dyn A, &dyn B));

    fn f(&self, p: i32) -> Result<Box<dyn R>, Error>;
}

pub trait B {
    fn f(&self) -> Result<Box<dyn R>, Error>;
}

pub fn load(a: &dyn A) {
    a.apply_closure(&mut |a, b| {
        b.f().unwrap();
    });
}
```

Looks like we infer `b` to be `&dyn B`, but we resolve `b.f()` to `A::f`. `B::f(b)` works fine.

**Comment by jmrgibson** [comment]
I believe I have the same issue using a closure with `flat_map`. Would people like more examples?

**Comment by lnicola** [comment]
The test case this this bug seems to be working now, let's close it.

@jmrgibson you could file a new one, especially if you have a minimized example.
