### ISSUE TITLE
Consider configuring Clippy

### ISSUE THREAD

**Issue by vipentti** [rust-analyzer/rust-analyzer#848]
According to [rust-lang/rust-clippy#configuration](https://github.com/rust-lang/rust-clippy#configuration): 

> Some lints can be configured in a TOML file named clippy.toml or .clippy.toml. It contains a basic variable = value mapping eg.

We could consider adding Clippy configuration to allow running `cargo clippy` on `rust-analyzer` while developing without reporting large number of warnings that are not relevant to `rust-analyzer`.

For the lints that currently cannot be configured in a `TOML` file we can ignore those (allow those to report warnings) or add some "global" inner attributes that allow them. 

I think ideally running `cargo clippy` on `rust-analyzer` should return no warnings / errors even if it means we allow some lints to pass. This could help people trying to contribute with creating more idiomatic solutions.

**Comment by matklad** [comment]
I personally don't use clippy much, because, while it does find a number of legit issues, it also tends to find a significant number of false-positives ([examples](https://github.com/rust-analyzer/rust-analyzer/pull/754)) and blindly fixing those usually makes code worse. I am also not a fan of suppressing  warnings on each individual expression/function, etc, as that also makes code less readable for trivial reasons. 

Disabling lints in .toml sounds great to me! Is there some preconfigured set of lints with no false positives?

**Comment by vipentti** [comment]
Looks like the actual Enabling/Disabling lints through the config is still pending according to https://github.com/rust-lang/rfcs/pull/2476#issuecomment-404271010 and https://github.com/rust-lang/cargo/issues/5034

I guess an alternative, since clippy allows passing lints as flags to `cargo clippy` e.g. `cargo clippy -- -A clippy::lint_name`, we could provide an alias or a set of flags in some document that would allow running the lints that `rust-analyzer` may be interested in. 

It may even make sense to have `cargo clippy -- -A clippy::all` as the default and then having some explicit `-D` flags for denying particular types of lints.

**Comment by matklad** [comment]
>I guess an alternative, since clippy allows passing lints as flags to `cargo clippy` e.g. `cargo clippy -- -A clippy::lint_name`, we could provide an alias or a set of flags in some document that would allow running the lints that `rust-analyzer` may be interested in.

We can add `cargo lint` command to the `tools` infra, the same way we added `cargo format`.

**Comment by matklad** [comment]
we have `cargo xtask lint` now
