### ISSUE TITLE
New initial check feature always requests "--all-targets"

### ISSUE THREAD

**Issue by wpbrown** [rust-analyzer/rust-analyzer#8484]
I believe this is the new feature added in #8375. I always get check failed when opening my workspace, because unfortunately there are some targets that don't build. These are not built by default so it's usually not an issue, but this new initial check always passes `--all-targets`, which as far as I can tell, can't be configured...

Initial check rerun by clicking exclamation in status bar:

```
[pid 26158] execve("/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo", ["/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo", "check", "--workspace", "--message-format=json", "--manifest-path", ".../Cargo.toml", "--all-targets", "--features", "testing,dev"], 0x559204c46860 /* 45 vars */) = 0
```

Check on save:
```
[pid 27337] execve("/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo", ["/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo", "check", "--workspace", "--message-format=json", "--manifest-path", ".../Cargo.toml", "--features", "testing,dev"], 0x55b572ee0780 /* 45 vars */) = 0
```

Settings:

```
{
    "rust-analyzer.cargo.features": [
        "testing,dev"
    ],
    "rust-analyzer.checkOnSave.allTargets": false
}
```

**Comment by matklad** [comment]
Could you check with the latest commit from master? It avoids building most of the things. 


>but this new initial check always passes --all-targets, which as far as I can tell, can't be configured...

The check is actually quite old, what's new is not sending errors to /dev/null :-)

**Comment by wpbrown** [comment]
Confirmed master is fixed. Thanks!
