### ISSUE TITLE
Consider not combining auto imports with globs

### ISSUE THREAD

**Issue by bluss** [rust-analyzer/rust-analyzer#8490]
Auto importing `ArbitraryOrder` in my crate created a use line at the top of the file that looked like this:

```rust
use crate::{imp_prelude::*, iterators::base::ArbitraryOrder};
```

Since this line is a "custom prelude import", I think it's inappropriate to add the `ArbitraryOrder` import to this line ("imp_prelude" is short for implementation prelude, i.e the `pub(crate)` prelude).

Would it be possible to avoid adding auto imports to glob importing lines?

**Comment by Veykril** [comment]
We should be able to special case single glob import lines I believe yes

**Comment by bluss** [comment]
Thank you!
