### ISSUE TITLE
Add match arms regressed

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#8493]
![image](https://user-images.githubusercontent.com/1711539/114455213-275a2500-9be4-11eb-8500-4a2326f6aad7.png)

https://github.com/matklad/rust-analyzer/commit/c211fb81df35fb06b9035bb8490bdb9b09b158d2

this used to work I think.

**Comment by DJMcNab** [comment]
Minimal reproduction:
```rust
fn match_tuple_fill() {
    match (Some(()),) {
        (Some(()),) => {}
    }
}
```
It's possible that fill match arms has never supported product types, since none of these provide the assist either:
```rust
fn match_tuple_fill() {
    match (Some(()),) {}
    match (Test2 { val: Some(0) }) {}
    match Test2(Some(0)) {}
}
struct Test(Option<i32>);
struct Test2 {
    val: Option<i32>,
}
```

For these, my suggested UX would probably be to expand to
```rust
match (Some(0),) {
    (${0:_},)=>{},
}
```
With an action on the `_` ident to split the arms:
```rust
match (Some(0),) {
    (Some(${0:_}),)=>{},
    (None,)=>{},
}
```

Note: However, rust-analyzer correctly gives the missing match arm diagnostic for all of these examples

**Comment by matklad** [comment]
(should also unindet those tests to match our style)

**Comment by hammypants** [comment]
> ![image](https://user-images.githubusercontent.com/1711539/114455213-275a2500-9be4-11eb-8500-4a2326f6aad7.png)
> 
> [matklad@c211fb8](https://github.com/matklad/rust-analyzer/commit/c211fb81df35fb06b9035bb8490bdb9b09b158d2)
> 
> this used to work I think.

Definitely used to work.

**Comment by Veykril** [comment]
Isn't that match already exhaustive though? I don't think it ever worked in this case specifically. Only a match with a single `_` match arm is special cased to be completely filled.

**Comment by flodiebold** [comment]
It's missing the `(None, None)` case.

**Comment by Jesse-Bakker** [comment]
https://github.com/rust-analyzer/rust-analyzer/blob/e6728a8cd39f9111dcdd654c7c65e99e5a2f1190/crates/ide_assists/src/handlers/fill_match_arms.rs#L474-L491

**Comment by iDawer** [comment]
I don't think this is regressed as the assist history shows it was limited since implemented.

Anyway I'd like to tackle on this.
The minimized example is a bit different, simple to fix https://github.com/rust-analyzer/rust-analyzer/pull/8543

**Comment by iDawer** [comment]
Attempt on this https://github.com/rust-analyzer/rust-analyzer/pull/8565

I think this assist should be replaced with an assist [not yet implemented] offered by match check diagnostic.
Fill match arm assist also carries "expand wildcard" kind of functionality (https://github.com/rust-analyzer/rust-analyzer/issues/8129#issuecomment-803933984) which should be made into its own assist.
Is my considerations correct?

Off-topic: How to lower a generated ast::Pat to hir::Pat? If I want to call `hir_ty::diagnostics::match_check::is_useful` to check if a particular pattern is useful or not. Or to create `Witnesses(Vec<hir::Pat>)>` of missing patterns returned from the function.

**Comment by flodiebold** [comment]
Yes, both are correct.

I think creating the `hir::Pat` directly and turning it into AST later would be the cleaner approach.

**Comment by matklad** [comment]
The example now works, so I think it's fine to consider this particular window repaired.
