### ISSUE TITLE
`rust-analyzer --version` is always nightly

### ISSUE THREAD

**Issue by fannheyward** [rust-analyzer/rust-analyzer#8495]
1. download the latest release from https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-04-12
2. `./rust-analyzer-aarch64-apple-darwin --version` outputs `nightly`

**Comment by fannheyward** [comment]
VSCode `Rust Analyzer: Show RA Version` also returns nightly.

**Comment by crumblingstatue** [comment]
Duplicate of #8239
