### ISSUE TITLE
Feature: show values of constants

### ISSUE THREAD

**Issue by lf-** [rust-analyzer/rust-analyzer#8497]
I would find it really cool and useful if RA could tell me the values of numeric constants. I don't need a super fancy evaluation, even just an MVP that handles math operators would be absolutely rad.

The thing I would love to use this for is for double checking the hex value of bit hacks I've done to generate the right value, e.g. `const TOP: usize = !0 & !(!0 >> 1);`. Currently I either have to tab out of my editor to stuff it into another rust project or the playground, or just hope I got it right.

**Comment by flodiebold** [comment]
We also kind of need this to handle at least array sizes, if not full const generics.

**Comment by lf-** [comment]
> We also kind of need this to handle at least array sizes, if not full const generics.

array sizes: #8799, in a limited way ;)

**Comment by firasuke** [comment]
> > We also kind of need this to handle at least array sizes, if not full const generics.
> 
> array sizes: #8799, in a limited way ;)

How close is `rust-analyzer` to showing values of constants (similar to what Idea does)?

Thanks in advance!

**Comment by lf-** [comment]
> > > We also kind of need this to handle at least array sizes, if not full const generics.
> > 
> > 
> > array sizes: #8799, in a limited way ;)
> 
> How close is `rust-analyzer` to showing values of constants (similar to what Idea does)?
> 
> Thanks in advance!

We currently parse numeric literals for the purposes of array sizes. Adding a basic expression evaluator is probably not very hard with the infrastructure we have now. I'm not sure the exact code paths to hook it up to display in the IDE but I doubt it would be super hard either. My guess is that implementing some form of constant value evaluation is O(1 day) of work.

**Comment by firasuke** [comment]
> > > > We also kind of need this to handle at least array sizes, if not full const generics.
> > > 
> > > 
> > > array sizes: #8799, in a limited way ;)
> > 
> > 
> > How close is `rust-analyzer` to showing values of constants (similar to what Idea does)?
> > Thanks in advance!
> 
> We currently parse numeric literals for the purposes of array sizes. Adding a basic expression evaluator is probably not very hard with the infrastructure we have now. I'm not sure the exact code paths to hook it up to display in the IDE but I doubt it would be super hard either. My guess is that implementing some form of constant value evaluation is O(1 day) of work.

Nice! Thanks for your time and effort!
