### ISSUE TITLE
Cargo check failed

### ISSUE THREAD

**Issue by Milo123459** [rust-analyzer/rust-analyzer#8505]
Everything is defaults.
```
cargo check failed: Checking starship v0.51.0 (C:\Users\milo5\Desktop\GitHUb\starship) error: could not compile `starship` To learn more, run the command again with --verbose.```

**Comment by lnicola** [comment]
Can you try with a nightly version?

**Comment by Milo123459** [comment]
How can I do that on the vscode extension?

**Comment by lnicola** [comment]
Set `rust-analyzer.updates.channel` to `nightly`.

**Comment by Milo123459** [comment]
Happens on nightly.

**Comment by flodiebold** [comment]
Does running `cargo check` in the project work?

**Comment by Milo123459** [comment]
Yes

**Comment by flodiebold** [comment]
Is your project public? Does `cargo check --workspace --all-targets` work?

**Comment by Milo123459** [comment]
https://github.com/Milo123459/starship/blob/typescript < is the code
And yes that command works

**Comment by lnicola** [comment]
That repo seems private.

**Comment by Milo123459** [comment]
https://github.com/Milo123459/starship/tree/typescript < fixed url

**Comment by lnicola** [comment]
TBH I can't reproduce this (with the code on `master`, but it shouldn't matter vs. `nightly`).

**Comment by rishadbaniya** [comment]
This issue should be close coz the PR : #8478 has fixed it, use the newly released nightly version's binary

**Comment by TomaszWaszczyk** [comment]
Anyone has something like:

![image](https://user-images.githubusercontent.com/1605705/116231788-9c3b6c00-a759-11eb-8ccb-f9d11d6e0b14.png) 

?

**Comment by Milo123459** [comment]
yea i do

**Comment by TomaszWaszczyk** [comment]
@Milo123459 Do you know what does it mean? Bad version?? Does it matter?

**Comment by Milo123459** [comment]
No clue I can't fix it

**Comment by TomaszWaszczyk** [comment]
I asked here: https://stackoverflow.com/questions/67282567/yellow-rust-analyzer but got thumb down, maybe bad version.

**Comment by lnicola** [comment]
@TomaszWaszczyk which RA version are you running and is your code public?

**Comment by tkblack** [comment]
Eh... I got the same problem with version of v0.3.1258, but i rollback the version to v0.3.1248, it solved!

**Comment by lnicola** [comment]
@tkblack can you try the pre-release version?

**Comment by tkblack** [comment]
@lnicola it's OK.

**Comment by SkyeYoung** [comment]
I had the same problem, and then after switching to the pre-release version, it was solved. 😸

**Comment by yucccc** [comment]
Switching to the preview version solved this problem, so is this a bug?

**Comment by lnicola** [comment]
@yucccc it is a bug that was fixed on Monday. The next release will include the fix.
