### ISSUE TITLE
Try using the expected enum assist (help-based) inserts serde::__private::Some

### ISSUE THREAD

**Issue by bluss** [rust-analyzer/rust-analyzer#8511]
"Try using the expected enum" inserts  `serde::__private::Some` where `Some` is expected.

See also issue #8512.

Given this code (in ndarray), serde is an optional dependency:

```rust
struct Foo;

impl Foo {
    pub fn f(&self) -> Option<i32> {
        if 3 + 3 == 6 {
            1
        } else {
            None
        }
    }
}
```

There's a diagnostic:
```
[rustc E0308] [E] mismatched types                         
expected enum `std::option::Option<i32>`                   
   found type `{integer}`                                  
—————————————————————————————————————————————————————————— 
[rustc E0308] [H] try using a variant of the expected enum 
```

The full rustc error is this:

```rust
error[E0308]: mismatched types
    --> src/impl_methods.rs:2582:13
     |
2580 |     pub fn f(&self) -> Option<i32> {
     |                        ----------- expected `Option<i32>` because of return type
2581 |         if 3 + 3 == 6 {
2582 |             1
     |             ^
     |             |
     |             expected enum `Option`, found integer
     |             help: try using a variant of the expected enum: `Some(1)`
     |
     = note: expected enum `Option<i32>`
                found type `{integer}`
```

If I use this assist I get the following result, and it is wrong because I expect `Some` instead.

```rust
struct Foo;

impl Foo {
    pub fn f(&self) -> Option<i32> {
        if 3 + 3 == 6 {
            serde::__private::Some(1)
        } else {
            None
        }
    }
}
```

- rust-analyzer 2021-04-05
- Editor: Vim + Coc

**Comment by flodiebold** [comment]
This is a fix provided by rustc and needs to be fixed there.

**Comment by bluss** [comment]
ok. I saw this in json output from `cargo build --message-format=json`:

`"suggested_replacement":"Some(1)","suggestion_applicability":"MaybeIncorrect"`

there is no mention of serde in the json output, is there another place to look?

**Comment by memoryruins** [comment]
I was unable to reproduce with the provided example until I added `use serde;` to the top, which then led to `"suggested_replacement":"serde::__private::Some(1)","suggestion_applicability":"MaybeIncorrect"`.

**Comment by matklad** [comment]
seems to be rustc issue
