### ISSUE TITLE
Struct fields auto-fill.

### ISSUE THREAD

**Issue by iago-lito** [rust-analyzer/rust-analyzer#8513]
In my dreams, when I have typed:
```rust
MyStruct {<|>
```
in an expression, then I'd be happy to see all this appear at once
```rust
MyStruct {
    field_a: <|>,
    field_b: ,
    field_c: ,
}
```
Is that far from being featured?

**Comment by lnicola** [comment]
You can do this by triggering code actions (`Ctrl-.` in Code) after the brace.

**Comment by iago-lito** [comment]
Oh, sorry, lemme check that.
