### ISSUE TITLE
Duplicate trait autoimport completions with trait objects

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#8520]
```rust
mod baz {
    pub trait DefDatabase {
        fn method1(&self);
    }
    pub trait HirDatabase: DefDatabase {
        fn method2(&self);
    }
}

mod bar {
    fn test(db: &dyn crate::baz::HirDatabase) {
        db.metho<|>
    }
}
```

![2021-04-14-205228_927x426_scrot](https://user-images.githubusercontent.com/906069/114763740-71b5e000-9d63-11eb-92d0-225b7d1e7f93.png)

The methods are already inherently available, but they get suggested as autoimports anyway.

**Comment by SomeoneToIgnore** [comment]
Currently autoimoprts are getting scope definitions from `Semantics` and filter out any imports that are contained there:

https://github.com/rust-analyzer/rust-analyzer/blob/c2a63b97a80cb738f800da61c64e748994709c31/crates/ide_db/src/helpers/import_assets.rs#L230

For the current example, `import.item_to_import` in the code is a trait that contains the method.
Looks like we don't consider such traits as "scope definitions"?

**Comment by flodiebold** [comment]
They aren't in scope, but you can call the method anyway. We probably need to add a different check for method completions.

**Comment by SomeoneToIgnore** [comment]
Yes, composing the test from the example and `dbg`-printing items in `scope_definitions` method shows that besides `ModuleDef(BuiltinType(...))` there are only two definitions in scope for the code snippet given: 
* `Local(Local(..))` with name `db`
* `ModuleDef(Function(..))` with name `test`

We get `Semantics` from the completion context: https://github.com/rust-analyzer/rust-analyzer/blob/e1e6e3b925bf7e0f6ca6cbc0d63d59572752653d/crates/ide_completion/src/completions/flyimport.rs#L140
so at least we're not utterly wrong on that side.

Another funny observation is that if I choose the autoimport completion option and insert the use statement, no warning is emitted by `rustc` about the "unused" statement, so technically it's a valid, different way of completing the method albeit I agree that it's odd.

I'm rather clueless on how to look for such items and check that they are fine to use without the import, do you have any ideas?

**Comment by flodiebold** [comment]
Here's the code which decides which traits are considered for a method call:
https://github.com/rust-analyzer/rust-analyzer/blob/e131bfc747df1b21ae6ea04eb9c55001e06b7bf0/crates/hir_ty/src/method_resolution.rs#L623-L635
Maybe the best approach would be to extract this and make it callable from completion, or add a method that checks whether a trait is an "inherent" candidate.
