### ISSUE TITLE
rust-analyzer can't build the gba crate for unknown reasons

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#8523]
<https://gist.github.com/rust-play/a1b80a43f9a768d38811f716d01fbd13>

I don't know why, but rust analyzer says that the cargo check command produced no metadata. The crate builds normally with cargo use in the command line, and it works fine with cargo-watch, so I'm not clear what's going on at all. The log is in the just above.

**Comment by jonas-schievink** [comment]
Does it work with the latest r-a nightly?

**Comment by Lokathor** [comment]
dunno, does the RA plugin update itself every day? i see it download updates sometimes.

**Comment by Veykril** [comment]
The stable release update is every monday, nightly is daily. If you haven't changed any config settings you are on stable. To access the nightly version you have to set the `"rust-analyzer.updates.channel": "nightly"`.

**Comment by Lokathor** [comment]
after an update to nightly it still seems to not work.

**Comment by flodiebold** [comment]
Might be the same as #8505

**Comment by jonas-schievink** [comment]
This seems to be working fine now
