### ISSUE TITLE
CARGO_CFG_TARGET_FEATURE not set for build scripts

### ISSUE THREAD

**Issue by aloucks** [rust-analyzer/rust-analyzer#8548]
I'm having a panic due to using `CARGO_CFG_TARGET_FEATURE ` in `build.rs`. 

The work-around (`"rust-analyzer.cargo.loadOutDirsFromCheck": true`) described in #6556 no longer seems to work.

**Comment by jonas-schievink** [comment]
Can you post the output? We use Cargo to run build scripts

**Comment by aloucks** [comment]
I haven't been able to reproduce it with the latest nightly. I'll re-open if this pops up again.
