### ISSUE TITLE
Support `rustc_skip_array_during_method_dispatch`

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#8552]
Likely part of the 2021 edition, so this is just so we don't forget about this: https://github.com/rust-lang/rust/pull/84147

(Actually if we don't support this type inference will be wrong for 2015 and 2018.)

**Comment by m-ou-se** [comment]
Note that this is already part of Rust 1.53.0 (to be released June 17th) and active in the current editions.
