### ISSUE TITLE
Feature: create a method from an unresolved method call

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-analyzer/rust-analyzer#8555]
Intellij Rust [recently added](https://intellij-rust.github.io/2020/09/21/changelog-131.html) support for creating methods from unresolved method calls. This makes for a nice flow where you can describe the usage of the method at the call site, and then instantly jump to filling out the method body.

This seems like an assist which should be relatively straight forward to implement for impls which all live in the same file, since assists already exist for generating methods in `assists/utils.rs`. Perhaps it's more complex when jumping between files, but maybe someone with more experience on the project can elaborate on this.

## Examples

__intellij rust today__

[![create_method](https://user-images.githubusercontent.com/2467194/115111052-b36ea280-9f7e-11eb-9378-4d838d199709.gif)](https://intellij-rust.github.io/assets/posts/changelog-131/create_method.gif)

**Comment by flodiebold** [comment]
We already have a "generate function" assist and an assist that can extract methods, so between those two, this should be relatively straightforward to add.

**Comment by yoshuawuyts** [comment]
I've started work on this here: https://github.com/rust-analyzer/rust-analyzer/compare/master...yoshuawuyts:whats-a-method-to-a-method-call. Sharing in case I run out of time this weekend to finish it up.

It's currently able to generate a free function from a method call. Next steps are:

1. generate the method inside an `impl block` rather than as a free function.
2. detect what kind of binding the method call has, so that we can correctly infer whether it's `self`, `&self` or `&mut self`.
3. verify external invocations such as `foo.bar()` work (e.g. without `self` in the path)
3. handle static methods such as `Self::my_static_method` correctly as well
4. verify this works correctly when the caller and the struct definition live in separate files

**Comment by yoshuawuyts** [comment]
Made some more progress, but going to call it quits for now. Been at this for a good while and noticing it has taken up most of my weekend at this point. If someone would like to finish up this work, please feel free to!

The biggest blocker to finishing it is ensuring that a new `impl` block is created under the type definition if there is none already. We're close, but not quite there yet.

**Comment by crumblingstatue** [comment]
It would be really cool to also have this work for associated functions without a receiver.

**Comment by yoshuawuyts** [comment]
Closing as this has been implemented in #9804

**Comment by lnicola** [comment]
Does it work for associated methods?

**Comment by yoshuawuyts** [comment]
Oh good point; I forgot to check! Yeah no it doesn't appear to work. I'll open a separate issue just for that (:
