### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Milo123459** [rust-analyzer/rust-analyzer#8556]
I just opened VSCode and got this in task manager as a subprocess:
![img](https://salvage.is-inside.me/OdqTp5gF.png)
Kinda mad, I think this is a bug?

**Comment by bjorn3** [comment]
Does it increase? If not, this is just rust-analyzer using a lot of memory. There have recently been some improvements which will land in the next release on monday I believe.

**Comment by lnicola** [comment]
I think those improvements were in the last week's release.

Is your code public?

**Comment by Milo123459** [comment]
> Does it increase? If not, this is just rust-analyzer using a lot of memory. There have recently been some improvements which will land in the next release on monday I believe.

No, just stays there

**Comment by Milo123459** [comment]
> I think those improvements were in the last week's release.
> 
> Is your code public?

Yes: https://github.com/Milo123459/starship/tree/vlang

**Comment by matklad** [comment]
I wonder if that's the winrt crate?

**Comment by Milo123459** [comment]
Not sure, but it certainly shouldn't be memory leaking

**Comment by bjorn3** [comment]
I wouldn't call 2GB leaking. The winrt is huge and strains even rustc. In addition rust-analyzer needs to keep info about all crates in memory at the same time, while rustc only needs the metadata (memory mapped and lazily decoded, so mostly not counting towards the reported memory usage) of dependencies and info about the current crate. This saves a lot of memory.

**Comment by Milo123459** [comment]
Ah, thanks for clearing that up.
I'll close this.

**Comment by stevenengler** [comment]
I also ran into what seems like a memory leak. I ran out of memory and the oom killer in syslog shows:

```
[  pid  ]   uid    tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[2268759]  1000 2268759 18621490 13659696      144752640  4356466             0 rust-analyzer
Out of memory: Killed process 2268759 (rust-analyzer) total-vm:74485960kB, anon-rss:54639220kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:141360kB oom_score_adj:0
```

Based on how much my system memory usage dropped afterwards, it looks like rust-analyzer was using around 65 GB of memory. RAM dropped from 61 GB to 11.5 GB and swap dropped from 61 GB to 45 GB. The syslog doesn't show that any other processes were killed, and all of my other applications are still running and haven't crashed. I use rust-analyzer with vim+ale.

**Comment by lnicola** [comment]
@stevenengler can you run `rust-analyzer analysis-stats .` in your project and watch the memory usage? What about `rust-analyzer analysis-stats --with-deps .`?
