### ISSUE TITLE
Failed to get file metadata

### ISSUE THREAD

**Issue by AurevoirXavier** [rust-analyzer/rust-analyzer#8573]
So many many this error

```
proc macro returned error: Failed to get file metadata for /root/Documents/darwinia-network/common/target/debug/deps/libparity_scale_codec_derive-e63e0768c2091177.so: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

But if I reopen the file, this error gone

**Comment by edwin0cheng** [comment]
What rustc version you are using ? we only support proc-macro supported up to 1.50 +

And maybe you could try to `cargo clean` and rebuilt the proc-macro to see if the error is gone.
