### ISSUE TITLE
Patch Release Process

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#8589]
I successfully broke the two previous weekly releases, so I think we should establish a low-friction procedure for making patch releases. 

Here's I think how we can do this:

* Use `yyyy-mm-dd.n` tags for point releases where the date points to the previous release: `2021-04-19.3` (a really bad week)
* Trigger the release by pushing to the `point-release` branch (via `cargo xtask release --patch`)
* Use `dist` task to figure-out the tag. Basically, dist does `date --iso > ./target/dist/tag.txt`, we upload that as an artifact, and then the thing that does GH release does `cat tag.txt` to figure the tag out. 
* Make sure that release proper creates changlog between the two proper releases (we don't want to write changlogs for patches)

There's this one thing I am unsure about:

* Should we base point releases by committing on top of the `releaes` branch? (so, backporting fixes)
* Or should we just release the current master?

**Comment by matklad** [comment]
Alternative option -- can we just *yank* the bad release? If we can't yank, then  perhaps we can re-publish previous week's release as a new one?

**Comment by matklad** [comment]
We also need *release blocker* label: the problem is that we knew that somethings fishy 4 days ago :(

**Comment by SomeoneToIgnore** [comment]
> re-publish previous week's release as a new one

I have a suspicion that won't work well with our automatic updates in vscode, it checks for version matches during bootstrapping:

https://github.com/rust-analyzer/rust-analyzer/blob/7d604584954660d255ad0929d3be8ce03f879d0c/editors/code/src/main.ts#L326

so that needs some updating and testing too, not sure if worth it.

**Comment by matklad** [comment]
Decided to YAGNI this, closed in #8621 

@matklad crosses the fingers hoping to not break single handedly three releases in a row
