### ISSUE TITLE
Renaming a tuple struct field replaces its type with the new name

### ISSUE THREAD

**Issue by PatchMixolydic** [rust-analyzer/rust-analyzer#8592]
In this situation, where `<|>` is the cursor:
```rust
struct Foo(i32);

fn baz() {
    let mut x = Foo(4);
    x.0<|> = 5;
}
```

I tried renaming `0` (F2 in VSCode) to `bar`, which resulted in this:
```rust
struct Foo(bar);

fn baz() {
    let mut x = Foo(4);
    x.bar<|> = 5;
}
```

Note that the type of `foo.0` (`i32`) was replaced with `bar`. This is, of course, not valid Rust. Ideally, renaming would either convert the tuple struct to a regular struct:
```rust
struct Foo {
    bar: i32,
}

fn baz() {
    let mut x = Foo(4);
    x.bar<|> = 5;
}
```
... or would simply not be available for tuple structs.

## Version
`rust-analyzer.serverVersion` displays `nightly`; `rust-analyzer-linux --version` displays `rust-analyzer 65a3cc2`.

**Comment by Veykril** [comment]
The problem here is that we unconditionally rename the definition of things here https://github.com/rust-analyzer/rust-analyzer/blob/ad131049c4cd1302af1a5616ff83d0e1f0cadea2/crates/ide/src/references/rename.rs#L501-L531
Which is the range that we get back from `nav.focus_or_full_range`, which is actually a bad way to get the range of the name, as that falls back to the entire items range if there is nothing to focus, as is the case for tuple fields. So we want this to return an `Option` instead returning `None` in case of a tuple field which can be checked similar to how the code checks for `RecordPatField`.

**Comment by dzhu** [comment]
Hi! New contributor here. I looked into this a bit. I see `focus_or_full_range()` is just taking `focus_range`, an `Option<NavigationTarget>`, and defaulting it to the full range, so replacing `nav.focus_or_full_range()` with `nav.focus_range.ok_or_else(|| format_err!("No identifier available to rename"))?` seems to make sense conceptually and prevents the rename from going through in this case. I can open a PR if that looks reasonable, though I have two questions at the moment.

First, the instructions above suggested checking for a tuple field specifically; is my suggestion too large a hammer? Based on the documentation of `NavigationTarget::focus_range`, I think it'll cover the right set of cases (where the full range doesn't include an identifier that could be changed), but I'm not sure.

Second, that change means that the rename is only aborted _after_ the user is prompted for and provides a new name, which isn't a great experience. The same thing already happens in some cases, so maybe it's fine, but I ended up thinking a bit more about the issue (I hope this isn't getting too off-topic). It looks to me like the natural thing to do would be to run some of the checks earlier, with something like this added to `prepare_rename` (cobbled together from what already exists elsewhere):

```rust
    let def = find_definition(&sema, syntax, position)?;
    match def {
        Definition::SelfType(_) => bail!("Cannot rename `Self`"),
        Definition::ModuleDef(ModuleDef::BuiltinType(_)) => bail!("Cannot rename builtin type"),
        _ => {}
    };
    let nav =
        def.try_to_nav(sema.db).ok_or_else(|| format_err!("No references found at position"))?;
    nav.focus_range.ok_or_else(|| format_err!("No identifier available to rename"))?;
```

Does that make sense? In particular, just inserting that will duplicate some work; is it little enough to not worry about (in terms of both code duplication and runtime cost)? Would it be acceptable to reduce the checks done later on or is it possible something will have changed by then?

**Comment by Veykril** [comment]
Ye you are right, there is no point in checking if its a tuple field, instead we should merely check for the `focus_range` and error out if its `None` as you have said.

And yes, we want `prepare_rename` to check for validity of the identifier that is being renamed, so having it check that the definition is renamable as well is definitely a good idea. The duplication is fine I think as it is not too much thats being duplicated(The code already has a few errors that have the same messages while being emitted at different locations in the code).
Reducing the checks later shouldn't be done, I believe a client can send a rename request without sending a `prepare_rename` at all so we still want to validate things properly there as well.
