### ISSUE TITLE
Support the beta channel in VSCode

### ISSUE THREAD

**Issue by dclong** [rust-analyzer/rust-analyzer#8596]
The rust-analyzer extension for VSCode supports stable and nightly channels but the beta channel. Can we support the beta channel as well?

**Comment by lnicola** [comment]
`rust-analyzer` support any reasonably recent Rust compiler, regardless of the toolchain. The preference you're looking at toggles between weekly `rust-analyzer` releases and daily (well, nightly) ones.

**Comment by flodiebold** [comment]
To expand on that, to choose the Rust toolchain you can use the usual ways: `rustup default`, `rustup override` or a `rust-toolchain` file.
