### ISSUE TITLE
rust-analyzer causes machine reboot on big project

### ISSUE THREAD

**Issue by nappa85** [rust-analyzer/rust-analyzer#8599]
I'll try to be more details complete possible, but probably I'll end up giving you a lot of confusion...

I've created a really, REALLY, big workspace, you can find it here: https://github.com/nappa85/serde_fix
The biggest crate on this workspace takes like 8GB of RAM to build, and sometime it makes rustc crash with some kind of UB. I've already opened an issue about it, but at the moment it isn't going anywhere: https://github.com/rust-lang/rust/issues/84245

When rust-analyzer is involved, like when I open with VSCode the workspace, it is really, REALLY rare that the process ends up correctly, it often goes on error, and sometimes it makes my machine instantly reboot, like it goes on kernel panic, but I can't find any log about it.

To add details, while I was developing the project, once it has reached a certain threshold, rust-analyzer started going on error really often with "proc-macro server crashed".

It has to be said, the project is fully made of structs and enums with a lot of derive macro associated.

The hardware is ok, I tested it in any possible way.
Haven't tested rust-analyzer on windows, only on linux, but rustc problem have been replicated on both.

Haven't been able to replicate rustc problem on slower machines (mine is a Ryzen7 with 16GB of RAM), tomorrow I'll get another Ryzen7 machine to test on

**Comment by lnicola** [comment]
We seem to spend a lot of time expanding procedural macros. For unsuspecting readers, this is a 1.2M LOC project.

I'm still waiting for it to load, but I highly doubt that `rust-analyzer` can be responsible for a BSOD or kernel panic. It sounds like a hardware issue, especially as you can't replicate it on other hardware.

**Comment by lnicola** [comment]
I did get a panic, though:

```
thread '<unnamed>' panicked at '

Failed to lookup SOURCE_FILE@0..2939 in this Semantics.
Make sure to use only query nodes, derived from this instance of Semantics.
root node:   SOURCE_FILE@0..2939
known nodes: SOURCE_FILE@0..2939

', crates/hir/src/semantics.rs:635:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:435:5
   2: hir::semantics::SemanticsImpl::find_file::{{closure}}
   3: hir::semantics::SemanticsImpl::find_file
   4: hir::semantics::SemanticsImpl::analyze_impl
   5: hir::semantics::SemanticsImpl::scope
   6: ide_db::helpers::import_assets::ImportAssets::search_for
   7: ide_db::helpers::import_assets::ImportAssets::search_for_imports
   8: ide_completion::completions::flyimport::import_on_the_fly
   9: ide_completion::completions
  10: std::panicking::try
  11: ide::Analysis::completions
  12: rust_analyzer::handlers::handle_completion
  13: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Other than that (and some probably unexpanded macros), features work surprisingly well for a repository this large. Completion is a bit slow, memory usage after playing around for a bit is 4.7 GB.

**Comment by nappa85** [comment]
What hardware are you using? It takes 6 minutes on my Ryzen7 notebook, 30 minutes on the other machine I've been able to test on

**Comment by lnicola** [comment]
It's a 5950X, arguably not the most common CPU :smile:.

**Comment by nappa85** [comment]
You're my savior, so it's not an hardware problem!
Can you help me track it down?

**Comment by lnicola** [comment]
Sorry, but if it crashes your system I still think it's a hardware problem.

**Comment by nappa85** [comment]
Ok, but there is a bug somewhere that causes a panic also in your machine...

**Comment by flodiebold** [comment]
A Rust panic is not going to cause a kernel panic.

**Comment by nappa85** [comment]
> A Rust panic is not going to cause a kernel panic.

Yes, this is sure, but if you take a look at my issue to rustc, you'll see (more than) once it failer telling me "can't alloc 3 Petabyte".
The Panic is really random, once it paniced while panicking, so it looks like an UB to me.
But let's forget the reboot problem, ok? Can we fix the panic? After we'll all have a better Rust

**Comment by flodiebold** [comment]
Just to be clear, the panic @lnicola found has nothing to do with the rustc compilation problems, very likely is also unrelated to the reboots you reported here, and probably will not even impact usage of RA on this workspace most of the time. That said, we should of course fix it.

**Comment by nappa85** [comment]
Ok, tomorrow I'll have access to another ryzen7 machine, to see if I'm able to replicate the problem here too.

**Comment by lnicola** [comment]
To be clear, it would be nice if we could load that project faster. Currently, we seem to spend a lot of time expanding proc macros, but that's not everything, of course.

The panic itself is probably nothing too special, we kinda' have a lot of those anyway.

**Comment by nappa85** [comment]
> To be clear, it would be nice if we could load that project faster. Currently, we seem to spend a lot of time expanding proc macros, but that's not everything, of course.
> 
> The panic itself is probably nothing special, we kinda' have a lot of those anyway.

Wait, but did it panics systematically every time to you?
Because I've been able to run rust-analyzer on the project without errors more than once.

**Comment by lnicola** [comment]
I think I can reproduce the panic if I trigger autocompletion on line 55 in `fix50sp2/src/comp_id_stat_grp.rs` (there's an enum there). But it's just a message in a log window, so you don't really notice it unless you're looking.

**Comment by nappa85** [comment]
Sorry for the long silence, it took me more than 10 days to prove Lenovo support that there were hardware problems even if tests passes. Now with a brand new hardware everything is stable. Closing the issue
