### ISSUE TITLE
Join lines should collapse comemnts

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#86]
Extend Join Lines to atomatically remove `///` when joining doc-comments

```
    /// `Kind` is stored in each node and designates
    /// it's class. Typically it is an fieldless <|>
    /// enum
```

After **Join Lines** action:

```
    /// `Kind` is stored in each node and designates
    /// it's class. Typically it is an fieldless  enum
```

The code and test for this functionality leave  here: https://github.com/matklad/rust-analyzer/blob/cd9c5f4ab205e092b87be6affe6d7e78d877dbf0/crates/ra_editor/src/typing.rs

**Comment by csmoe** [comment]
@matklad what's `<|>` stands for?

**Comment by matklad** [comment]
Position of the cursor. The tests use the same convetion.

Perhaps its a good idea to change it to `<caret>` to make self-explanatory?

**Comment by csmoe** [comment]
`<caret>`is great, but how about `<Cursor>` directly?

**Comment by matklad** [comment]
Hm, let's make it <cursor> to avoid the shift?

**Comment by aochagavia** [comment]
This was closed in https://github.com/rust-analyzer/rust-analyzer/pull/116
