### ISSUE TITLE
Hovering over Some shows `fn Some<i32>(T) -> Option<[unknown]>`

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#860]
```rust
let i = So<|>me(0);
```

Pops up `fn Some<i32>(T) -> Option<[unknown]>` which is a little weird since it's not a function.

**Comment by DJMcNab** [comment]
Well in this case it technically is a function I think.

**Comment by kjeremy** [comment]
I suppose you could look at it that way but that's not what I would expect to see on a hover.

```rust
/// The `Option` type. See [the module level documentation](index.html) for more.
#[derive(Clone, Copy, PartialEq, PartialOrd, Eq, Ord, Debug, Hash)]
#[stable(feature = "rust1", since = "1.0.0")]
pub enum Option<T> {
    /// No value
    #[stable(feature = "rust1", since = "1.0.0")]
    None,
    /// Some value `T`
    #[stable(feature = "rust1", since = "1.0.0")]
    Some(#[stable(feature = "rust1", since = "1.0.0")] T),
}
```

**Comment by DJMcNab** [comment]
Yeah, it's not what you'd expect, but it is at least somewhat correct.

**Comment by flodiebold** [comment]
We could easily adapt the Display implementation to e.g. remove the `fn` for struct/enum variant constructors. What annoys me more is that it's showing `Option<[unknown]>` as the return type when it clearly has inferred the right substitution...

**Comment by daboross** [comment]
I'm finding it interesting that `T` appears in three different places and has a different display in each of them...

The "real" signature is `fn Some<T>(T) -> Option<T>`, but the first `T` is displayed as `i32`, the second as `T`, and the third as `[unknown]`.

**Comment by flodiebold** [comment]
It's a bug with type inference of generics in tuple variant constructors :confused:
