### ISSUE TITLE
Classify the `main` function as used

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#8603]
hi, I still have this while calling codelens run:

<img width="552" alt="Screen Shot 2021-04-20 at 11 51 05 PM" src="https://user-images.githubusercontent.com/33961674/115426944-931b3e00-a233-11eb-8a7d-548eaf6e4e2b.png">

is it possible to remove it?

**Comment by lnicola** [comment]
Do you have `rust-analyzer.lens.methodReferences` disabled?

**Comment by GopherJ** [comment]
@lnicola how should I disable this one in coc-rust-analyzer? I'd like to try

**Comment by lnicola** [comment]
https://github.com/fannheyward/coc-rust-analyzer#configurations.

**Comment by GopherJ** [comment]
Ok I understood what do you mean, actually I still want tto keep  method reference in other places but remove it from the  list of code lens run

**Comment by lnicola** [comment]
In Code all three lenses items (Run, Debug, references) are clickable and have an associated action. I guess we could do one or both of:

 - hide the method references lens on `main`
 - hide the method and type reference lenses on items with 0 references

**Comment by GopherJ** [comment]
I prefer the first  one

**Comment by Veykril** [comment]
I also think the first one is a better idea, when a function has no references seeing the `0 references` still gives the user the information that that function isn't referenced.

So we have to filter out the main function here https://github.com/rust-analyzer/rust-analyzer/blob/70fe7a4515ebdc6222a6565cd4cd1c5fd0c77350/crates/ide/src/annotations.rs#L143-L151, that is if the function is called "main" and defined inside the root module.

**Comment by flodiebold** [comment]
What if we _are_ calling the main method though?

**Comment by GopherJ** [comment]
@flodiebold which case will we call main function?

**Comment by lnicola** [comment]
When it's recursive, for example. That's disallowed in C, but not in Rust AFAIK.

**Comment by flodiebold** [comment]
It just doesn't seem worth special-casing to me. I wouldn't expect the fact that `main` is the entry point to have an effect on the "X references", just like for some function exported from a library.

**Comment by lnicola** [comment]
Yeah, I don't see this warranting a special case.
