### ISSUE TITLE
Auto-import suggestion failing when macros are present in function body

### ISSUE THREAD

**Issue by ElusiveMori** [rust-analyzer/rust-analyzer#8612]
Without macro:

![image](https://user-images.githubusercontent.com/3159552/115574587-d4165f80-a2d2-11eb-8645-fdd281d5e70b.png)

With macro:

![image](https://user-images.githubusercontent.com/3159552/115574625-dc6e9a80-a2d2-11eb-825e-2e13988f80c1.png)

It doesn't seem to matter what macro is being used (I've checked `unimplemented!()`, `todo!()` and `anyhow!()` as well). If there's a macro at all - no suggestions will be provided. This is especially annoying in huge files with hundreds of LOC, where to add an import manually you have to scroll way up.

I've been able to reproduce it with this trivial example in a bare project:
```rust
// hello.rs
pub fn hello() {
    // try typing Stuff here

    assert!(true)
}

// stuff.rs
pub struct Stuff {
    pub foo: u32,
    pub bar: String,
}

// lib.rs
pub mod stuff;
pub mod hello;
```

This issue has been plaguing me for the past month or so, though I can't recall exactly for how long. It's definitely a regression of some sort, because I haven't seen this happen before.

**Comment by jonas-schievink** [comment]
Please try on the newest nightly release, this should be fixed.

**Comment by ElusiveMori** [comment]
> Please try on the newest nightly release, this should be fixed.

Oh wow, yeah, works now! I've tried nightly a week earlier to no luck, and switched back to stable. Thanks a lot.

Closing this issue since it's fixed on my end.
