### ISSUE TITLE
Intellisense just work on root src folder

### ISSUE THREAD

**Issue by dpolicastro** [rust-analyzer/rust-analyzer#8618]
I'm trying to setup intellisense on VSCode but it is not working as expected, I will explain. I have all this directories opened in my vscode:

![image](https://user-images.githubusercontent.com/29067941/115641583-c6230780-a2ef-11eb-8a90-8d4caa74292e.png)

1- Initially I had all the projects inside the `rust` folder, intellisense worked poorly with the `rust` extension.
2- I installed `rust-analyzer` and disabled the official extension, after reloading vscode I started getting the error `rust-analyzer failed to discover workspace`.
3- Then I copied the projects `rust/guessing-game and rust/grrs` to the parent directory, which is also the root dir, and renamed them. So now `rust-analyzer` worked fine for both `src/main.rs` files, but is not working at all for any other file created in src or child directories.

**Comment by matklad** [comment]
Yeah, agree that this is a problem, thanks for the report. You can use `linkedProjects` settings to make rust-analyzer work with the current structure: https://rust-analyzer.github.io/manual.html#rust-analyzer.linkedProjects

I've filed https://github.com/rust-analyzer/rust-analyzer/issues/8622 which desrcribes the underlying issue in some more details.
