### ISSUE TITLE
Detect Rust library source file map automatically according to the current toolchain

### ISSUE THREAD

**Issue by EFanZh** [rust-analyzer/rust-analyzer#8619]
Currently, I need to configure `rust-analyzer.debug.sourceFileMap` manually in order to step into some of the Rust source files. Could rust analyzer detect the source file map automatically according to the current toolchain? For example, if the current toolchain is the stable version, detect and map `/rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0` to `${env:HOME}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust`.

**Comment by matklad** [comment]
cc @vsrs

**Comment by vsrs** [comment]
Yeah, that is possible. One note: if you do not need to to distinguish stable\nightly, and only need to update the rustc id (2fd73fabe469357a12c2c974c140f67e7cdd76d0) you may use `"/rustc/*": "${env:HOME}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust"`. This works for lldb and recent mscpp tools.

@matklad
I know only one reliable way to get the toolchain for a project (taking into account all this RUSTUP_TOOLCHAIN, rust-toolchain, etc.): run and parse `rustup show`. Perhaps you can suggest something else?

**Comment by matklad** [comment]
We use ` rustc --print sysroot ` for this already in rust-analyzer

**Comment by vsrs** [comment]
@matklad Thanks
