### ISSUE TITLE
"Finalize" design of syntax trees

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#862]
As syntax trees are the basis of all of the work, and can be used independently for tools like `rustfmt`, it makes sense that we nail down their design as soon as possible, at least in broad strokes. 

# Requirements

**Absolutely Must Have:** 

* full-fidelity trees: all white space and comments should be preserved in a tree in a structured way (that is, storing source `String` alongside the tree does not cut it) .
* infallible parsing: parsing **any** `&str` should produce a syntax tree, which can be converted back to the source text. Syntax tree must represent the structure of input on the best effort basis: if struct's field is missing a type, the tree *should* have a `StructField` node, and all subsequent fields should be correctly recognized. Similarly, unbalanced `{}` are not the reason to produce a dummy tree.
* ability to map from syntax trees to internal compiler's IRs and ability to map from IRs to syntax trees. Specifically, "compiler" and "ide" parts should share the same tree at *some* level, we shouldn't have a completely separate data structure/parsing algo for IDEs
* ability to represent hygienic macro expansion *somehow*
* "purity": syntax tree for a file should depend only on the file's text and flags (like edition), explicitly passed to the parser. It should not depend on the contents of file system, name of the file or ambient compiler's global state. All semantic information (types, nameres, hygiene) should be stored elsewhere. 

**Must Have**

* parent pointers (compilers traverse trees "top-down", but IDE starts with a cursor offset and has to traverse the tree "bottom-up"). 
* access to absolute offsets
* "mostly untyped" API for traversal: parent, first_child, next_sibling methods which return some kind of a type-erased "Node"
* ability to cheaply update the tree after incremental reparse

**Nice To Have**
* lazy parsing of subtrees
* structured editing API
* immutability 
* compact memory representation
* super fast performance
* flexibility of the representation: ideally, API should not lock us to a particular representation.

See [Swift document](https://github.com/apple/swift/blob/bbaf48a53aff3e2c8a5a7ab3becc13b9a76903a3/lib/Syntax/README.md#design-and-implementation-guidelines) for another good list of key properties.

**Comment by sirgl** [comment]
Also I think, that some kind of interning should be present in this model. It also restricts the shape of the model as you have to use lifetime of intern table or Rc.

It probably relates to Nice to Haves section.

**Comment by matklad** [comment]
Some more thoughts on the issue:

https://gist.github.com/matklad/3ba3163ec9388ca92b01600f46991d77

**Comment by matklad** [comment]
one more iteration: https://github.com/rust-analyzer/rowan/pull/22

**Comment by matklad** [comment]
I think what we've arrived at in `rowan` at the moment is pretty good.

**Comment by matklad** [comment]
or maybe not quite enough: https://github.com/rust-analyzer/rust-analyzer/issues/6857
