### ISSUE TITLE
VSCode extension error: [matklad.rust-analyzer]: 'configuration.property' must be an object

### ISSUE THREAD

**Issue by tidux** [rust-analyzer/rust-analyzer#8630]
This error is thrown on startup, even outside of Rust project folders, so I think it's related to config parsing.

Editor version: https://github.com/cdr/code-server version 3.9.3 (latest release rpm)

Extension version: v0.2.563

**Comment by matklad** [comment]
Should be closed by https://github.com/rust-analyzer/rust-analyzer/commit/905ae2843a5c8e287ede1de053170f874c175736#diff-398f25bff37acc21f1c0951892d8bb57e17af420cbcc0d85128fce137c6609b7
