### ISSUE TITLE
Apply `async` semantic token modifier to `async`/`await` keywords

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#8633]
`async` and `await` are very special, ‘magic’ keywords that I’d like to highlight differently from other keywords.

**Comment by Veykril** [comment]
I believe we can also attach the `async` modifier to async functions then similarly how its done for unsafe.

**Comment by Veykril** [comment]
We need to add the modifier here https://github.com/rust-analyzer/rust-analyzer/blob/20f82191a038b05ead5c4d666fcd75f053a2dc6c/crates/ide/src/syntax_highlighting/tags.rs#L40-L71

Then we want to tag the `async` and `await` keywords with the modifier here, like with unsafe(but keeping the contrlo flow modifier for `await`) https://github.com/rust-analyzer/rust-analyzer/blob/20f82191a038b05ead5c4d666fcd75f053a2dc6c/crates/ide/src/syntax_highlighting/highlight.rs#L230-L242

Check if a method call is calling an async function here https://github.com/rust-analyzer/rust-analyzer/blob/20f82191a038b05ead5c4d666fcd75f053a2dc6c/crates/ide/src/syntax_highlighting/highlight.rs#L397-L427 and whether a function definition is async here https://github.com/rust-analyzer/rust-analyzer/blob/20f82191a038b05ead5c4d666fcd75f053a2dc6c/crates/ide/src/syntax_highlighting/highlight.rs#L283-L309

**Comment by hi-rustin** [comment]
Let me try to fix it.
