### ISSUE TITLE
Configure recursion limit for macro expansion

### ISSUE THREAD

**Issue by Pat-Lafon** [rust-analyzer/rust-analyzer#8640]
As a follow up to https://users.rust-lang.org/t/rust-analyzer-increase-recursion-limit/55057/3, it would be very useful if the recursion limit for macro expansion could be configured/changed. Normally in rust files you can add a `#![recursion_limit = "1024"]` to the file but rust-analyzer does not respect this.

I believe the recursion limit was set to a const value in https://github.com/rust-analyzer/rust-analyzer/pull/5320.

I am unsure how one would go about this.

**Comment by matklad** [comment]
Yeah, seems not super trivial to do, especially given that we want to support attribute syntax for this. I guess, as a first step, we should apply the following diff:

```diff
diff --git a/crates/base_db/src/lib.rs b/crates/base_db/src/lib.rs
index 980a0ed98..19ec4644c 100644
--- a/crates/base_db/src/lib.rs
+++ b/crates/base_db/src/lib.rs
@@ -109,6 +109,17 @@ pub trait SourceDatabase: CheckCanceled + FileLoader + std::fmt::Debug {
     /// The crate graph.
     #[salsa::input]
     fn crate_graph(&self) -> Arc<CrateGraph>;
+
+    #[salsa::transparent]
+    fn crate_limits(&self, crate_id: CrateId) -> CrateLimits;
+}
+
+pub struct CrateLimits {
+    pub macro_expansion_limit: u32,
+}
+
+fn crate_limits() -> CrateLimits {
+    CrateLimits { macro_expansion_limit: 128 }
 }
 
 fn parse_query(db: &dyn SourceDatabase, file_id: FileId) -> Parse<ast::SourceFile> {
```

Then, we should use that query at the call-site to pick the appropriate limit. 


After that, we should introduce *global* limits, set from settings.json (https://github.com/rust-analyzer/rust-analyzer/blob/eee50b6921662dee766c987e1a0b15b371e141d1/crates/rust-analyzer/src/config.rs#L30-L32). 


I suggest punting on the parsing the actual attribute, as we can plumb that later. 

Hm, on the other hand, maybe it would actauly be easier to start with an attr? For that, we need to make sure that this function:

https://github.com/rust-analyzer/rust-analyzer/blob/eee50b6921662dee766c987e1a0b15b371e141d1/crates/hir_def/src/nameres.rs#L209

returns a `DefMap` which contains recursion limit as a field. I think this would be the appropriate place to fetch the attribute from the syntax: 

https://github.com/rust-analyzer/rust-analyzer/blob/eee50b6921662dee766c987e1a0b15b371e141d1/crates/hir_def/src/nameres/collector.rs#L249-L253

At this place, we can't query syntax dirctly, we go via item trees, so this is the thing that ultimatelly  should fetch the  attribute: 

https://github.com/rust-analyzer/rust-analyzer/blob/eee50b6921662dee766c987e1a0b15b371e141d1/crates/hir_def/src/item_tree.rs#L73

Yeah, having typed that, I think we should go with the second approach. 


As a test, we need to set the recursion limit to something low, like `3`, and check that it does in fact limit expansions.

**Comment by edevil** [comment]
Hello folks. Using version v0.3.2062 `recursion_limit` does not seem to be honoured. I have an example repo: https://github.com/edevil/rust-analyzer-recursion

If you open main.rs, LSP can't find the definition for ServerError. However, if I remove some Enum cases suddenly it works.
