### ISSUE TITLE
`mutable` semantic token modifier not given to `&mut self` method definitions

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#8644]
Since mutable variable definitions are given the semantic token modifier, I think it would make sense if methods were given the same treatment.

**Comment by Veykril** [comment]
Relevant code is here https://github.com/rust-analyzer/rust-analyzer/blob/1b4defd2409d6a6120b40a0730e9822a819e971d/crates/ide/src/syntax_highlighting/highlight.rs#L285-L310
The self param has to be checked for exclusive access.
