### ISSUE TITLE
Publishing failed

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#8662]
```
Caused by:
  failed to select a version for the requirement `ra_ap_stdx = "=0.0.50"`
  candidate versions found which didn't match: 0.0.49, 0.0.48, 0.0.47, ...
  location searched: crates.io index
  required by package `ra_ap_tt v0.0.50 (/home/runner/work/rust-analyzer/rust-analyzer/target/package/ra_ap_tt-0.0.50)`
```

**Comment by matklad** [comment]
I personally wouldn't consider this a breaking window -- publishing to crates.io is not our core goal, so maintaining publishing infra across the time should be left to the folks who are intrested in consuming published ra crates.

**Comment by pksunkara** [comment]
I am looking into this but there's something unexpected happening with cargo. https://github.com/frewsxcv/rust-crates-index/pull/53#issuecomment-845846974 and https://github.com/sunng87/cargo-release/issues/224#issuecomment-790395825

**Comment by pksunkara** [comment]
Released a new patch which finally fixes this obscure issue. Publishing should start working from the upcoming sunday.

**Comment by pksunkara** [comment]
It is working as seen in https://github.com/rust-analyzer/rust-analyzer/runs/2707992014?check_suite_focus=true. We can close this issue.
