### ISSUE TITLE
Emit folding ranges for multi-line where clauses

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#8664]
```rust
fn foo()
where
    A: Foo,
    B: Foo,
    C: Foo,
    D: Foo,
{}
```
should be folded into
```rust
fn foo()
where /**/
{}
```
Relevant code is here https://github.com/rust-analyzer/rust-analyzer/blob/691c96e36a9e760d8e6f035377d03223e2f93277/crates/ide/src/folding_ranges.rs

**Comment by lnicola** [comment]
Fixed in #8674
