### ISSUE TITLE
Wrong highlighting of links in /*! doc comments

### ISSUE THREAD

**Issue by halvko** [rust-analyzer/rust-analyzer#8678]
When writing intra-doc links in /*!*/ doc comments, rust_analyzer highlights them in the first line, no matter which line the link is on, specifically when writing this code:
```rust
/*! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non feugiat felis, at
*  turpis,[ThisType][crate::ThisType]  ac tincidunt enim rhoncus quis. Suspendisse at porttitor turpis. Cras vel leo sed neque
*
*  Sed leo dui, tempor ut varius sagittis, [crate::main] consectetur ac eros. Etiam id mi scelerisque,
*/

fn main() {
    println!("Hello, world!");
}

struct ThisType {}
```
in a rust project in Visual Studio Code, rust_analyzer highlights `um dolor sit amet, consecte` as a type, and `ipiscing elit` as a function:

![image](https://user-images.githubusercontent.com/2468434/116236694-aa8c8680-a75f-11eb-881b-532964519f05.png)

This is the case on Arch Linux:
RA version: `2021-04-12-92-g7570212a5`
VS Code version: `1.55.2; 3c4e3df9e89829dce27b7b5c24508306b151f30d; x64` (the code 1.55.2-1 package on arch)

And on Windows:
RA version: `617535393 2021-04-26`
VS code version: `1.54.3; 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8; x64` (Installed with the official installer)

**Comment by Veykril** [comment]
Fixed in #8719, turns out I completely forgot to test this for block comments
