### ISSUE TITLE
When completing a function, and the input matches at least one candidate exactly, function snippets are not included

### ISSUE THREAD

**Issue by YorickPeterse** [rust-analyzer/rust-analyzer#8691]
The title is a bit of a mouthful, but the problem is as follows. Say you have this Rust file (where `|` signals the cursor position):

```rust
use std::alloc::Layout;

fn main() {
    Layout::|
}
```

When triggering completion, all the expected candidates show up: `Layout::from`, `Layout::from_size_align`, etc. When choosing a completion item, snippets and such are all processed as expected. For example, if we choose `Layout::from_size_align`, we end up with this:

```rust
use std::alloc::Layout;

fn main() {
    Layout::from_size_align(size, align)
}
```

The problem arises when one types `Layout::from` and _then_ triggers completion. In this case rust-analyzer still shows the 3 methods you'd expect: `Layout::from`, `Layout::from_size_align`, and `Layout::from_size_align_unchecked`. The problem is that when you choose an entry, snippets are not applied. The result is that you end up with something like this:

```rust
use std::alloc::Layout;

fn main() {
    Layout::from_size_align
}
```

This happens every time the input of the completion query matches at least one function entry. So if the input is `Vec::with_capacity`, you can't complete the method with snippets and all that.

I confirmed this is happening both in NeoVim and when using vscode. Here's a recording showing that happening in vscode:

https://gfycat.com/simplisticidleguernseycow

Here's the same issue happening in NeoVim:

[![asciicast](https://asciinema.org/a/zRToIX90fkOCtU3jmAG8L0KJG.svg)](https://asciinema.org/a/zRToIX90fkOCtU3jmAG8L0KJG)

The expected behaviour here is to get snippet completion, regardless of whether the input is `Layout::fr`, `Layout::`, `Layout::from`, or something else.

My version of rust-analyzer is `rust-analyzer 617535393 2021-04-26 dev`, using Rust `rustc 1.51.0 (2fd73fabe 2021-03-23)` and Cargo `cargo 1.51.0 (43b129a20 2021-03-16)`.

**Comment by Veykril** [comment]
The problem here seems to be that the expected type for completions becomes the already written function's type which then causes us to skip the the snippet completion as we do not want to add calling parens when completing functions where a function is expected

**Comment by flodiebold** [comment]
Yeah, that's what I expected. We probably need to record more detailed information about what type was expected and what type we actually got during inference, but I'm not completely sure what the best way for that is (i.e. whether the 'obvious' way will give us the information we hope). It might need some experimenting.

**Comment by Veykril** [comment]
This shouldn't be too hard to fix in this case I believe, currently the code checks the trailing expression of the function to determine its return type here https://github.com/rust-analyzer/rust-analyzer/blob/544a93ee0815697ff42b79e54d1a7a5a743de1f9/crates/ide_completion/src/context.rs#L379-L387
Instead we should lower the actual return type of the function and use that if I'm not mistaken(which probably wasn't done yet as sema doesn't expose a way to go from arbitrary `ast::Type` to `hir::Type`.

**Comment by flodiebold** [comment]
That would only fix it for this specific case, but already not work for
```rust
fn main() {
    Layout::from|;
}
```
, I believe. I don't think we should be lowering any types in this code.

**Comment by Veykril** [comment]
Mmh that's a good point I guess

**Comment by flodiebold** [comment]
Though actually, reading that code, I'm not sure whether the bug would actually happen in that situation? Seems that the "expected type" logic already involves more special-casing than I thought, so maybe it's fine for now :man_shrugging:

**Comment by Veykril** [comment]
Ye it already quite special cased, which is unfortunately necessary. We can just map the function node to its hir def and take out the return type that way though, so no need to lower anything extra actually.

**Comment by Veykril** [comment]
Fixed in https://github.com/rust-analyzer/rust-analyzer/pull/8715(relevant test is https://github.com/rust-analyzer/rust-analyzer/pull/8715/files#diff-651615d626a57d22f045214c88f3eba75d41e96c0f2f96d121bd2a42b621f520R866-R872)

**Comment by YorickPeterse** [comment]
I just confirmed https://github.com/rust-analyzer/rust-analyzer/pull/8715 solves this issue. Thanks all! :tada:
