### ISSUE TITLE
Pattern type inference fails on an enum variant in a scope with the top-level name of another type

### ISSUE THREAD

**Issue by iDawer** [rust-analyzer/rust-analyzer#8694]
![Screenshot_20210430_110640](https://user-images.githubusercontent.com/7803845/116657695-60cdb700-a97e-11eb-9faf-c91e20403b9f.jpg)
rustc compiles it.
Wen I use a binding like `a @ IntRange(_)`, ra says `a` is of type `IntRange` struct which is incorrect.
The second arm uses full path and has no issue.
 Also I found related discussion https://internals.rust-lang.org/t/bring-enum-variants-in-scope-for-patterns/12104/6

rust-analyzer version: 617535393 2021-04-26 dev
<details> 
  <summary>the code</summary>

```rust
use self::Constructor::*;
struct IntRange {
    range: (),
}
enum Constructor {
    IntRange(IntRange),
}
fn main() {
    match Constructor::IntRange(IntRange { range: () }) {
        IntRange(x) => {}
    //  ^^^^^^^^^^^ wrong highlight, type of `x` not inferred
        Constructor::IntRange(x) => {}
    }
}
```

</details>

**Comment by flodiebold** [comment]
This is a name resolution issue; the way it _should_ work is that the `struct IntRange` only exists in the types namespace, so the glob imports imports the (constructor of the) variant `Constructor::IntRange` in the values namespace; and the lookup in the pattern should happen in the values namespace. I'm not sure where this is going wrong.

**Comment by Veykril** [comment]
The highlighting at least fails here I'm pretty sure, https://github.com/rust-analyzer/rust-analyzer/blob/c7196620abd5e9bab4fbd53388da361f0f6987a1/crates/hir/src/source_analyzer.rs#L549-L551
Semantics path resolution isn't really aware of namespaces, `prefer_value_ns` is false in most cases so the types result is used first.

**Comment by jonas-schievink** [comment]
I think the resolution problem here is that hir_ty calls `Resolver::resolve_path_in_type_ns` with the variant path here:

https://github.com/rust-analyzer/rust-analyzer/blob/99451a5fc25bb6448313633b4385277e50073845/crates/hir_ty/src/infer.rs#L561

This of course resolves to the wrong thing in this case. It should call `Resolver::resolve_path_in_value_ns` instead.

**Comment by flodiebold** [comment]
Huh, yes :thinking:

**Comment by jonas-schievink** [comment]
Hmm, making that change results in `IntRange { range: () }` resolving `IntRange` to the variant as well, which is wrong. I'm not actually sure how this is supposed to work, it seems like `IntRange` needs to be resolved in type namespace here, but what about `Enum::Variant { ... }`?

**Comment by flodiebold** [comment]
That's also type namespace. Record construction uses type namespace, tuple constructors value namespace.

**Comment by jonas-schievink** [comment]
Ah, of course
