### ISSUE TITLE
Vscode's own bracket matching is broken by char/byte literals that contain brackets ('(', '[', '{', '}', ']', ')').

### ISSUE THREAD

**Issue by thomcc** [rust-analyzer/rust-analyzer#8704]
`char` literals (and byte/`u8` literals, e.g. `b'('`) do not seem to have the correct scope to mark them as textual, or whatever it is that should cause vscode to ignore them for bracket matching.

For example, if I have something like this, where my cursor is on the `|`, and I use `editor.action.jumpToBracket`, it jumps to the bracket inside the char literal (e.g. the `'}'`), and not the correct matching bracket at the end of the function:

```rust
pub fn foo(c: char) {|
    if c == '}' {
        println!("right curly");
    } else {
        println!("not");
    }
}
```

As a more visible, (less active) demonstration of the issue; When the cursor is on the nearest `{`, you can see the `}` inside `'}'` become highlighted, as vscode considers it to be the correct "match":

<img width="288" alt="Screen Shot 2021-05-02 at 3 57 47 AM" src="https://user-images.githubusercontent.com/860665/116810784-913a6000-aafa-11eb-9884-6a2f88f1c6ae.png">

Some notes:
- This bug impacts all types of brackets I'm aware of. Or, specifically: any of the characters in `{([])}` can exhibit this — not just closing curly. I've just chosen `}` as an example arbitrarily.

- Everything works correctly for string and byte string literals. That is, brackets inside "}" and `b"}"` are ignored for the purposes of matching.

- I remember that in the past (possibly over a year ago) this bug didn't exist — it worked properly. I could be wrong though, but don't believe so, but it's hard to bisect a huge range like this.

- This bug also causes some extensions to get confused, such as [bracket-pair-colorizer-2](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2), but I imagine fixing this here, will fix it as well (having dug a bit, seems to have copypasted code from vscode's internal bracket matching logic, seemingly just so it's consistent with some not-entirely-documented functionality it appears to hook into).

- Current scope values:
    - `char` literals have textmate scope `constant.character.rust` and semantic scope `characterLiteral`.
    - byte literals have textmate scope `constant.character.rust` and semantic scope `number`.
    - string and bytestring literals (both) are have textmate scope `string.quoted.double.rust` and semantic scope `string`.

---

I did a bit of digging, but it was not immediately obvious *to me* what the fix should be, but I did find some information that seems like it could someone who knows a bit more about this than I do.

VSCode's logic for this lives in this file: https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/editor/contrib/bracketMatching/bracketMatching.ts

It determines whether or not to ignore brackets in a token based on this function: https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/editor/common/modes/supports.ts#L87.

The values that are given to that function seem *seem* to come from here: https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/workbench/services/textMate/common/textMateService.ts#L48, which... I can't find an implementation of. Perhaps this plays into it somehow https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/workbench/services/textMate/browser/abstractTextMateService.ts#L115-L132 ? Not sure!

It *might* come from https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/workbench/services/textMate/common/TMGrammars.ts#L54-L60? That implies that perhaps an extension can define a map of scope name => token type? I have no idea. This feels like it might be the solution though...

I hope the digging here helped — Hopefully it's not a pointer in the wrong direction.

**Comment by Veykril** [comment]
This seems to work fine for me in the current stable release as well as on the nightly release
![image](https://user-images.githubusercontent.com/3757771/116812342-ac36bf80-ab4e-11eb-8fba-a2c08c96f759.png)
The only time I get the behavior described in this issue is when RA hasn't loaded yet.
On what version are you currently?

**Comment by thomcc** [comment]
I was on `rust-analyzer version: 617535393 stable` and just tried `rust-analyzer version: e1bef5310 2021-05-02 nightly`. Both exhibit the issue for me. I'm on macOS, and VSCode version information is:

```
Visual Studio Code
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z (2 wks ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

It happens if the local toolchain is `rustc 1.51.0 (2fd73fabe 2021-03-23)` (latest stable) as well as `rustc 1.53.0-nightly (42816d61e 2021-04-24)` (latest nightly that supports the components I use).

>  The only time I get the behavior described in this issue is when RA hasn't loaded yet.

I'm not sure how to quantify that more precisely, but I'm pretty confident RA has loaded. I have all sorts of type info, autocomplete and the like, and it isn't behaving the way it does when it's not loaded.

I believe I still have the issue when RA is not loaded though, or rather: If I create a `blah.rs` file, and don't add it to the module tree with `mod blah` anywhere, inside that file, the issue persists. (Note: I don't care about the "detached module" case, I'm just checking it to help debug).

I don't believe any of my installed extensions could cause this, but I'll try to determine that more concretely.

**Comment by thomcc** [comment]
I've resolved it, it was a collision with https://marketplace.visualstudio.com/items?itemName=dunstontc.vscode-rust-syntax, which I apparently had installed since... god knows how long ago. Uninstalling it fixes the issue.

Sorry for the trouble.
