### ISSUE TITLE
Add some basic snippets

### ISSUE THREAD

**Issue by Zerotask** [rust-analyzer/rust-analyzer#8707]
I'm used to have snippets for operations I often use and they save time and increase the productivity.
Therefore I suggest to add some basic snippets. A good starting point would be https://github.com/rust-lang/vscode-rust/blob/master/snippets/rust.json

But I'd also add:
- println!()
- flow of control: if/else, loop, while, match, while let
- assert, assert_eq, assert_ne
- Option and Result

**Comment by Veykril** [comment]
We do have completions for a lot of things already 
![image](https://user-images.githubusercontent.com/3757771/116823101-ecb03080-ab82-11eb-81da-9591fff8e8a1.png)
as well as postfix completions https://rust-analyzer.github.io/manual.html#magic-completions.
Do you not get any of these?

**Comment by Zerotask** [comment]
@Veykril Thank you for pointing that out. I thought snippets always have those empty square icons.
