### ISSUE TITLE
Error: Progress handler for token rustAnalyzer/indexing already registered

### ISSUE THREAD

**Issue by CatherineGasnier** [rust-analyzer/rust-analyzer#8723]
Hello,
I'm getting the following error while indexing my rust projects with rust-analyzer. It just started happening today as I was starting VS code. Another symptom is the indexing bar blocked at 42/1202. Is there any logs I could look at or attach here to help debug this?

```
Registering progress handler for token rustAnalyzer/indexing failed.
Error: Progress handler for token rustAnalyzer/indexing already registered
	at Object.onProgress (/home/catg/.vscode-server/extensions/matklad.rust-analyzer-0.2.583/out/src/main.js:5443:23)
	at LanguageClient.onProgress (/home/catg/.vscode-server/extensions/matklad.rust-analyzer-0.2.583/out/src/main.js:13130:45)
	at new ProgressPart (/home/catg/.vscode-server/extensions/matklad.rust-analyzer-0.2.583/out/src/main.js:11109:41)
	at createHandler (/home/catg/.vscode-server/extensions/matklad.rust-analyzer-0.2.583/out/src/main.js:14474:34)
	at handleRequest (/home/catg/.vscode-server/extensions/matklad.rust-analyzer-0.2.583/out/src/main.js:4976:41)
	at processMessageQueue (/home/catg/.vscode-server/extensions/matklad.rust-analyzer-0.2.583/out/src/main.js:4840:17)
	at Immediate._onImmediate (/home/catg/.vscode-server/extensions/matklad.rust-analyzer-0.2.583/out/src/main.js:4830:13)
	at processImmediate (internal/timers.js:456:21)
```
![image](https://user-images.githubusercontent.com/20106734/117026238-87c81800-acf3-11eb-8b06-11c6e2bdfda6.png)

**Comment by Veykril** [comment]
Can you run `Show RA version` and show the version of the plugin you are on right now?

**Comment by CatherineGasnier** [comment]
That shows: "rust-analyzer version: nightly"
In the extension panel, I see:
![image](https://user-images.githubusercontent.com/20106734/117035302-104ab680-acfc-11eb-8a27-2a8ab0809ce4.png)

**Comment by Veykril** [comment]
Hmm, this output seems rather odd. The plugin version is latest stable but the command output is `rust-analyzer version: nightly` indicating a version with a server that contains the version display bug that should've been fixed 😕

Are you using the server that ships with the plugin or have you set an overwrite of the server binary in the config? If you haven't set a config overwite mind trying to reinstall the plugin and see if that fixes it?

**Comment by CatherineGasnier** [comment]
I haven't set a config override AFAIR. 
In case it's useful, this is my VS Code settings.json:
```
{
    "workbench.colorTheme": "Quiet Light",
    "rust-analyzer.serverPath": "~/.cargo/bin/rust-analyzer",
    "remote.SSH.showLoginTerminal": true,
    "rust-analyzer.linkedProjects": [
        "src/arena_collections/Cargo.toml",
        "src/depgraph/Cargo.toml",
        "src/deps/cargo/typing_deps_hash/Cargo.toml",
        "src/facebook/hh_decl/Cargo.toml",
        "src/facebook/hh_decl/cargo/decl_ipc/Cargo.toml",
        "src/facebook/hh_decl/cargo/decl_ipc_ffi/Cargo.toml",
        "src/facebook/hh_decl/cargo/hh_decl_api/Cargo.toml",
        "src/facebook/hh_decl/cargo/hh_decl_client/Cargo.toml",
        "src/facebook/hh_fanout/Cargo.toml",
        "src/facebook/hh_fanout/cargo/hh_fanout_api/Cargo.toml",
        "src/facebook/hh_fanout/cargo/hh_fanout_outproc/Cargo.toml",
        "src/facebook/utils/Cargo.toml",
        "src/facebook/utils/cargo/hh_config/Cargo.toml",
        "src/facebook/utils/cargo/hh_slog/Cargo.toml",
        "src/ocamlrep/Cargo.toml",
        "src/oxidized/Cargo.toml",
        "src/oxidized_by_ref/Cargo.toml",
        "src/utils/eq_modulo_pos/Cargo.toml",
        "test/Cargo.toml",
    ],
    "workbench.editor.enablePreview": false,
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "matklad.rust-analyzer",
    "editor.formatOnPaste": true,
    "editor.formatOnType": true,
    "ocaml-formatter.profile": "own",
}
```

Worth noting that I'm developing on a remote server, hence using the Remote - SSH extensions. Here's a snapshot of all the extensions I have:
![image](https://user-images.githubusercontent.com/20106734/119700577-4a1a6300-be4b-11eb-921d-f393ed929128.png)

The issue went away magically for a while, and it's back now. It does seem that it's breaking indexing as none of the Rust IDE features are working.

I'll try reinstalling 🤞

**Comment by Veykril** [comment]
Ah you are setting `"rust-analyzer.serverPath": "~/.cargo/bin/rust-analyzer",`, so you are using the rustup server binary which would explain the server to client version difference. The rustup binary is updated less often then the plugin.

The particular issue you are running into shouldve been fixed in https://github.com/rust-analyzer/rust-analyzer/pull/8693, I don't know if the latest rustup ships that server but if it does upgrading the server binary should fix the problem.

**Comment by lnicola** [comment]
The, rustup version is reasonably up-to-date (assuming you update it), but this could also be a from-source build.

**Comment by CatherineGasnier** [comment]
Awesome, this seems to have fixed it! Thanks!
