### ISSUE TITLE
cargo format-hook installs bad file on windows

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#875]
After running `cargo format-hook` in my bash shell I get the following error:
> error: cannot spawn .git/hooks/pre-commit: No such file or directory

Note that the file is there and has the correct permissions.  If an argument is passed to `git commit` such as `-a` the script fails with a bad argument. Manually running gives:

> $ ./.git/hooks/pre-commit
> 
> will run: rustup run stable -- cargo fmt
> 
> will run: git update-index --add C:\projects\test\rust-analyzer\a

**Comment by matklad** [comment]
I *think* we might need an .exe extension on windows
