### ISSUE TITLE
"Implement default members" generates wrong code

### ISSUE THREAD

**Issue by zohnannor** [rust-analyzer/rust-analyzer#8750]
![Анимация](https://user-images.githubusercontent.com/35764628/117467726-9ebd7300-af5c-11eb-992d-d78d468b94db.gif)

May be related to #7063?

**Comment by flodiebold** [comment]
No, that seems to be overeager path qualification (turning `self` into `self::cmp` is wrong of course)... I seem to remember we did have a similar bug :thinking:

**Comment by zohnannor** [comment]
Yes, I think they are related. Should this ssue be closed then?

**Comment by flodiebold** [comment]
Yeah, I think that's the same issue. Let's close this one.
