### ISSUE TITLE
Spurious newline in assisted fill struct fields

### ISSUE THREAD

**Issue by djc** [rust-analyzer/rust-analyzer#8785]
This happens consistently for me in VS Code, current nightly:

<img width="427" alt="Screen Shot 2021-05-09 at 22 49 46" src="https://user-images.githubusercontent.com/158471/117586496-dcff9180-b118-11eb-9f1d-ced6096d65fc.png">

**Comment by edwin0cheng** [comment]
It is because we do not remove any newline characters in that case. 

if the cursor is something like the following, it will work properly :
```rust
A { $0
};
```
