### ISSUE TITLE
fill match arm should see through references

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#881]
The following works (there's "fill match arm" in code action list, and it fills variants):

```
    fn convert_tt(&mut self, tt: &tt::TokenTree) {
        match *tt {

        }
    }
```

This does not work (no intention is available):

```
fn convert_tt(&mut self, tt: &tt::TokenTree) {
        match tt {

        }
    }
```

The second case should work just the first one, due to match ergonomics. 

I think in this line we should peel off all references: 

https://github.com/rust-analyzer/rust-analyzer/blob/38add103c3f30493e336a37827a76f48a6e7c584/crates/ra_assists/src/fill_match_arms.rs#L29-L32

**Comment by vipentti** [comment]
Hmm, should we take into account the Edition that is currently used? I believe 2015 would require using `ref` in the match parameters if matching on reference and `&` before as well ?

https://rust-lang-nursery.github.io/edition-guide/rust-2018/ownership-and-lifetimes/default-match-bindings.html#default-match-bindings

**Comment by matklad** [comment]
I believe match egronomics works for 2015 as well: https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=eff7f6a315bc7e78857328e2f8fcf656
