### ISSUE TITLE
Support for projects without `Cargo.toml`

### ISSUE THREAD

**Issue by boehs** [rust-analyzer/rust-analyzer#8818]
I have been using `rust-script` for some small projects. Unfortunately, rust-analyzer won't work because it can't find cargo.toml. Is there a work around for this?

**Comment by memoryruins** [comment]
Check out https://rust-analyzer.github.io/manual.html#non-cargo-based-projects  for how to setup r-a to work without cargo.

**Comment by boehs** [comment]
> Check out https://rust-analyzer.github.io/manual.html#non-cargo-based-projects for how to setup r-a to work without cargo.

Solved!

**Comment by boehs** [comment]
hey @memoryruins, I feel really silly but I just can't for the life of me get any form of autocomplete working with my noncargo project. I put `rust-project.json` in the project root and in it I have

```json
{
    "sysroot_src": "C:/Users/ebrob/.rustup/toolchains/nightly-x86_64-pc-windows-msvc/lib/rustlib/src/rust/library",
    "crates": [
        {
            "root_module": "src/main.rs",
            "edition": "2018",
            "deps": []
        }
    ]
}
```

No errors appear, it seems like it would work, and yet the only source of autocomplete is from tabnine, not fun.

Its surely a silly mistake on my end.

**Comment by lf-** [comment]
> hey @memoryruins, I feel really silly but I just can't for the life of me get any form of autocomplete working with my noncargo project. I put `rust-project.json` in the project root and in it I have
> 
> ```json
> {
>     "sysroot_src": "C:/Users/ebrob/.rustup/toolchains/nightly-x86_64-pc-windows-msvc/lib/rustlib/src/rust/library",
>     "crates": [
>         {
>             "root_module": "src/main.rs",
>             "edition": "2018",
>             "deps": []
>         }
>     ]
> }
> ```
> 
> No errors appear, it seems like it would work, and yet the only source of autocomplete is from tabnine, not fun.
> 
> Its surely a silly mistake on my end.

Huh. I have working completion with this one, which looks to be the same as yours:

```json
{
    "sysroot_src": "/home/jade/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library",
    "crates": [
        {
            "root_module": "src/main.rs",
            "edition": "2015",
            "deps": []
        }
    ]
}
```

Try setting RA_LOG and seeing what you can find, here's one that is not too spammy. Add the below snippet into your JSON settings for your editor, then look in the output view for the R-A language server. It is in `:CocCommand workspace.showOutput` in coc.nvim, and the Output tab next to the terminal with the dropdown "Rust Analyzer Language Server" in VSCode. I hope this will get you some logs that might be useful.

```json
    "rust-analyzer.server.extraEnv": {
        "RA_LOG": "info,salsa::derived::slot=warn,rust_analyzer::main_loop=warn,project_model=debug"
    }
```

**Comment by boehs** [comment]
o/ @lf- , if I did everything right I should be getting output, here it is as a paste (I, unfortunately, could not find anything odd) https://pastie.io/vmjaqb.sql

I can't imagine there is a conflict somewhere, the normal `Rust` extension function(ed) fine, until I uninstalled it in favor of rust script

**Comment by boehs** [comment]
I was hoping the lastest PR's would fix this, but not. I have tried

0. Reinstalling RA for vscode
1. Running `rustup update`
2. Switching to RA nightly

I also am having this issue: ![](https://e.reeee.ee/NRYQYo.png)

It works wonderfully in cargo projects. Please help!

**Comment by boehs** [comment]
The RA server trace in vscode says

`[ERROR rust_analyzer] failed to find any projects in [AbsPathBuf("c:\\Users\\snip\\PersonalFiles\\Code\\stuff\\random\\rust")]`

**Comment by metaclips** [comment]
Hello, so I also need to use rust-project.json to detect my rust projects but slightly for a different case as my projects have a `cargo.toml`.

Here's my architecture.
>Dir
>[rust-project.json](https://github.com/metaclips/workspace-test/blob/master/rust-project.json)
>named folder
>>project one which is a library
>>project two which is a library

Code [here](https://github.com/metaclips/workspace-test).
Is it possible to indicate project 1 and 2 as crates (where rust-analyzer sees the cargo.toml)? 
Can we have interdependencies where a crate(project) depends on the other?

**Comment by flodiebold** [comment]
You probably just want the `linkedProjects` setting. `rust-project.json` means you're not using Cargo at all.

**Comment by metaclips** [comment]
> You probably just want the `linkedProjects` setting. `rust-project.json` means you're not using Cargo at all.

Love and light. Thanks.

**Comment by boehs** [comment]
Closed as partial support has been added
