### ISSUE TITLE
Support new task list in rust doc available since v. 1.52.0

### ISSUE THREAD

**Issue by FrankenApps** [rust-analyzer/rust-analyzer#8821]
This is just a minor feature request, that I wanted to report, because I have not seen anything about this here for now.

Rust 1.52.0 added support for ["task lists"](https://github.com/rust-lang/rust/pull/81766), can also be found in the [changelog](https://github.com/rust-lang/rust/blob/master/RELEASES.md#rustdoc).

Unfortunately it seems rust-analyzer does not support this yet?

At least in vscode I found it to produce this:
![overlay](https://user-images.githubusercontent.com/17967303/118112563-795db880-b3e5-11eb-9d75-535a4a8eb0b4.png)
![code](https://user-images.githubusercontent.com/17967303/118112573-7b277c00-b3e5-11eb-9aa2-8f06efeb3c55.png)

This is how it looks in `rustdoc`:

![rustdoc](https://user-images.githubusercontent.com/17967303/118112960-fab54b00-b3e5-11eb-86c0-198a417d01b7.png)

**Comment by bjorn3** [comment]
It is up to the editor to display the markdown. Rust-analyzer makes a couple of changes to the raw markdown to turn for example ```` ``` ```` into ```` ```rust ````, but there is nothing it can turn task lists into to make the editor suddenly support it. Vscode will need to gain support for task lists.

**Comment by Veykril** [comment]
We do want to change the `pulldown_cmark` options to include `Options::ENABLE_TASKLISTS` though as to not turn the tasks into links as seen in the screenshot.
