### ISSUE TITLE
Missing type parameters in creation of `Default` impl

### ISSUE THREAD

**Issue by kinnison** [rust-analyzer/rust-analyzer#8827]
For reference I am using rust-analyzer via vs-code.

* vs-code extension version `0.3.594`
* Nightly channel
* ```
  PersistentState: {
    lastCheck: 1620934826021,
    releaseId: 42876454,
    serverVersion: '0.2.591'
  }
  ```
* Nightly (`rustc 1.54.0-nightly (5c0292654 2021-05-11)`)

Given the following input code:

```rust
pub mod submod {
    pub struct Foo<T> {
        _bar: *mut T,
    }

    impl<T> Foo<T> {
        pub fn new() -> Self {
            todo!()
        }
    }
}
```

Rust-analyzer offers to "Generate a Default impl from a new fn"  If I use this assist, I get the following impl generated:

```rust
    impl Default for Foo<T> {
        fn default() -> Self {
            Self::new()
        }
    }
```

Note the missing `<T>` for the `impl`

**Comment by Veykril** [comment]
Looks like we aren't accounting for generics like we do in other assists here https://github.com/rust-analyzer/rust-analyzer/blob/1552fdd3bcbecd77971617d16be210c74c88e409/crates/ide_assists/src/handlers/generate_default_from_new.rs#L74-L85
We should instead create the impl block via https://github.com/rust-analyzer/rust-analyzer/blob/1552fdd3bcbecd77971617d16be210c74c88e409/crates/ide_assists/src/utils.rs#L409-L413
