### ISSUE TITLE
code complete cannot select &mut

### ISSUE THREAD

**Issue by Vincentzc** [rust-analyzer/rust-analyzer#8832]
I click TAB to select "&mut guess",but I got "guess" only . Maybe something goes wrong : 

![cp](https://user-images.githubusercontent.com/4166616/118272440-35f26f80-b4f5-11eb-8a2c-acce30432084.gif)

**Comment by flodiebold** [comment]
Weird, I can reproduce this in VSCode, but not in Emacs...

**Comment by Veykril** [comment]
I wonder if this comment here is relevant... https://github.com/rust-analyzer/rust-analyzer/blob/8d713b3e462ce1ff5bdeebc5f2bb6f90310c69ac/crates/ide_completion/src/item.rs#L34-L36

**Comment by Veykril** [comment]
Hmm actually I more surprised this works in Emacs now cause we apparently send this item in `textDocument/completion`:
```

        {
            "label": "&mut test",
            "kind": 6,
            "detail": "()",
            "deprecated": false,
            "preselect": true,
            "sortText": "fffffffa",
            "filterText": "test",
            "insertTextFormat": 1,
            "textEdit": {
                "newText": "test",
                "insert": {
                    "start": {
                        "line": 204,
                        "character": 8
                    },
                    "end": {
                        "line": 204,
                        "character": 8
                    }
                },
                "replace": {
                    "start": {
                        "line": 204,
                        "character": 8
                    },
                    "end": {
                        "line": 204,
                        "character": 8
                    }
                }
            },
            "additionalTextEdits": []
        },
```
Which clearly has the wrong `newText`.
Same in the resolve calls afterwards.

**Comment by Veykril** [comment]
Oh I think I know whats going on here, the `insertReplaceSupport` PR probably broke this and I assume emacs doesnt have that feature yet so it doesn't hit this bug.
