### ISSUE TITLE
Hang in match exhaustiveness

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#8835]
![image](https://user-images.githubusercontent.com/1711539/118287314-03884880-b4dc-11eb-8737-7fcebd3d2288.png)

Get a bunch of "overly long loop: 10s" in this situation

**Comment by matklad** [comment]
cc @iDawer , I haven't debugged this, so I am not 100% positive it's exhaustiveness check, but you might want to be aware

**Comment by iDawer** [comment]
At this example:
```rust
fn foo(kind: SyntaxKind) {
    match (kind, kind) {}
}
```
`RA_PROFILE='*>10000'` reports:
```
48832ms - handle_code_action
        0ms - Semantics::analyze_impl (9 calls)
        0ms - add_missing_impl_members_inner (2 calls)
        0ms - classify_name_ref (1 calls)
        0ms - deref (3 calls)
        3ms - diagnostics (1 calls)
     4954ms - find_path (123008 calls)
     8768ms - mod_path_to_ast (123008 calls)
    35105ms - ???
```
Removing and placing cursor again on the match expr triggers report with the same call stats.

**Comment by iDawer** [comment]
With this patch:
```diff
---------------------------- crates/ide/src/lib.rs ----------------------------
index 99e45633e..eff3d157a 100644
@@ -546,6 +546,8 @@ impl Analysis {
         resolve: bool,
         frange: FileRange,
     ) -> Cancelable<Vec<Assist>> {
+        let _p = profile::span("assists_with_fixes");
+
         let include_fixes = match &assist_config.allowed {
             Some(it) => it.iter().any(|&it| it == AssistKind::None || it == AssistKind::QuickFix),
             None => true,
```
```
58810ms - handle_code_action
    58810ms - assists_with_fixes
            0ms - Semantics::analyze_impl (9 calls)
            0ms - add_missing_impl_members_inner (2 calls)
            0ms - classify_name_ref (1 calls)
            0ms - deref (3 calls)
            4ms - diagnostics (1 calls)
         5600ms - find_path (123008 calls)
         9886ms - mod_path_to_ast (123008 calls)
        43317ms - ???
```
Suspecting `fill_match_arms` assist? Hmm, in this case it calculates `number_of_syntax_kinds^2` arms: 
https://github.com/rust-analyzer/rust-analyzer/blob/92abc56bc928fb2a11b8f5b2a37e3c9ee31102d7/crates/ide_assists/src/handlers/fill_match_arms.rs#L85-L94

**Comment by Veykril** [comment]
Oh ye would make sense if that takes ages there since `SyntaxKind` has around 247 variants... We might wanna skip that assist if the enum has more than n variants and we are completing tuples? At some point its questionable if you really would want to generate n^m match arms.

**Comment by matklad** [comment]
Another high order bit here is that we compute all the arms in the read phase of the assist. We should stop as soon as we find at least *one* arm, and recompute the whole list only when applying.
