### ISSUE TITLE
"Implement default members" on trait methods defined by macro generates invalid code

### ISSUE THREAD

**Issue by Swatinem** [rust-analyzer/rust-analyzer#8841]
Using version: fd109fb58 2021-05-10 stable

Code:

```rust
macro_rules! define_fn {
    ($name:ident, $ty:ident) => {
        define_fn!($name, $ty <>);
    };

    ($name:ident, $ty:ident < $($param:ident),* >) => {
        fn $name<$($param),*>(
            &mut self,
            _param: &mut $ty <$($param),*>,
        ) -> Self
        where
            $($param: Clone),*
        {
            self.clone()
        }
    };
}
trait SomeTrait: Clone {
    fn explicit_fn(&mut self) -> Self {
        self.clone()
    }

    define_fn!(macro_defined_fn, String);

    define_fn!(macro_defined_parameterized_fn, Vec<u8>);
}

#[derive(Clone)]
struct Foo;

impl SomeTrait for Foo {
// <- "implement default members" here
}
```

The assist leads to the following invalid code:

```rust
impl SomeTrait for Foo {
    fn explicit_fn(&mut self) -> Self {
        crate.clone()
    }

    fnmacro_defined_fn<>(&mutself,_param: &mutString<>,)->Selfwhere{crate.clone()}

    fnmacro_defined_parameterized_fn<u8>(&mutself,_param: &mutVec<u8>,)->Selfwhereu8:Clone{crate.clone()}
}
```

More specifically:
* it loses all the whitespace and concatenates everything together
* it leaves empty angle brackets and an empty `where` clause there (not sure if that is valid rust code?)
* no idea where that `crate.clone()` comes from?

Found this while implementing this trait here:

https://github.com/getsentry/relay/blob/802953b0df8228b7d2810ab73e5c11eca527b630/relay-general/src/processor/traits.rs#L11-L32

**Comment by lnicola** [comment]
What happens if you first expand the macro, then trigger the assist? This is probably more than a single issue.

**Comment by flodiebold** [comment]
It's two known issues: 1. whitespace missing in macro expansions, 2. `self` in `self.clone()` being 'qualified' to `crate`. We have issues for both, let me find them...

**Comment by flodiebold** [comment]
1. is #6588, 2. is #7499.
