### ISSUE TITLE
Not all variables bound in or-patterns are considered references or definitions

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#8860]
```rust
enum Either {
    Left(u8),
    Right(u8)
}

fn extract(e: Either) -> u8 {
    match e {
        Either::Left(val) |
        Either::Right(val) => {
            val + 1
        }
    }
}
```

This is currently highlighted like this:

![screenshot-2021-05-17-00:18:32](https://user-images.githubusercontent.com/1786438/118414545-84467080-b6a5-11eb-844a-13f96147b438.png)

I would expect all 2 bindings of `val`, as well as the use in `val + 1` to be highlighted

**Comment by Veykril** [comment]
Hmm this might be tricky to solve, our current infra for this expects things to always only have one definition

**Comment by matklad** [comment]
This *is* one `ide::Definition`, it’s just the Definition itself has many sources. I wonder what’s the best way here:

* treat every Local as having potentially many sources?
* Introduced a MultiLocal enum variant specifically for this case?

My gut feeling is that we should do the second.

**Comment by matklad** [comment]
Rust sparks joy: https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=158fc0b5d29053d7d34022dd7e4a3748

**Comment by Veykril** [comment]
Ye I think I'm in favor of the second approach here as well.
