### ISSUE TITLE
Type consts/statics

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#887]
We currently don't handle consts/statics in type inference at all. This has two parts: We need to use the declared type of the const when referring to it from another location, and we need to run type inference on the bodies of consts.

The first part involves roughly the following steps, I think:
 - add a `ConstSignature` analogous to `FnSignature` that contains the name of the const and the `ra_hir::TypeRef` for the type, and add a query which constructs this (and a method on `Const` which calls it, similar to `Function::signature`). The reason for this is that we don't want to directly refer to the AST during type inference, as the AST changes every time the file is edited in any way. Having this intermediate query means we only need to redo type inference when the type itself is changed.
 - add a `resolver` method on `Const` similar to `Function::resolver` (but without handling generic params)
 - in `ty/lower.rs`, add `Const` to `TypableDef`, and implement `type_for_def` for consts by getting the const signature and turning the `TypeRef` into a `Ty` using `Ty::from_hir` (for the values namespace; consts don't exist in the types namespace)
 - add tests for this in `ty/tests.rs`

I think `static`s will work the same way (and can reuse `ConstSignature`), so it makes sense to do them at the same time.

After that, we'll want to run type inference on const bodies; I think this will involve introducing a `DefWithBody` enum containing `Function`, `Const` and `Static`, and changing a bunch of places that currently use `Function` to use that instead (i.e. the `body_syntax_mapping`, `body_hir`, `expr_scopes` and `infer` queries). But first things first :smile:

**Comment by vipentti** [comment]
I'll try this, I guess now we can add associated consts as well ?

**Comment by flodiebold** [comment]
Yes, I think that will just be a matter of a few lines [here](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_hir/src/ty/infer.rs#L406).

**Comment by vipentti** [comment]
What does const bodies mean in this context? Something like?
```rust
const GLOBAL_CONST: u32 = {
    const IS: u32 = 35;
    const IC: u32 = 63;
    IS + IC + 14
};
```

**Comment by flodiebold** [comment]
Yes, or even just
```rust
const X: u32 = {
    let x = 35;
    let y = 63;
    x + y + 14
};
```
. In general, the value of a constant can be any expression grammar-wise; it's just that rust disallows a lot of operations currently in a const context, but we don't really need to deal with that for now. (The above code becomes legal with Rust 1.33, I think.)

Someone might for example write
```rust
const X: u32 = 123u32.count_ones();
```
, which compiles in current beta, and reasonably expect code completion to work there.

This isn't really high-priority though, since const bodies are usually pretty small :smile:

**Comment by vipentti** [comment]
What about `statics` ? They are somewhat similar to `consts` when it comes to inference, right?

I guess inferring things in their bodies is fine, even though if it may not be allowed to compile ?

**Comment by flodiebold** [comment]
I think statics are basically the same when it comes to types.

Someday we'll maybe want to do const checking, and e.g. only complete const methods in const context, but the rules about what's allowed in consts are changing a lot at the moment so it doesn't make sense to put a lot of work into that, I think. In any case, type inference isn't different in const bodies vs. other expressions as far as I understand; const checking is just another step on top.
