### ISSUE TITLE
rust-analyzer | coc-rust-analyzer broken since RA@2021-05-03

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#8874]
I'm used to working with rust-analyzer & coc-rust-analyzer, but after latest updates, this toolset is broken, I'm not sure if it's rust-analyzer's issue or coc-rust-analyzer or maybe I didn't configure it correctly.

Today I tried to upgrade to RA@2021-05-17 because I hope it fixes my issue, but it crashed again

<img width="963" alt="image" src="https://user-images.githubusercontent.com/33961674/118739964-4c922100-b87d-11eb-8836-6e69fb8cabdc.png">

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/33961674/118740117-a266c900-b87d-11eb-9334-e06ab7f828a0.png">

the only thing that I've done is to call `find references` of `Balance`:

<img width="654" alt="image" src="https://user-images.githubusercontent.com/33961674/118740015-65023b80-b87d-11eb-92ea-cd4c9483794a.png">

https://github.com/parallel-finance/parallel/blob/master/runtime/parallel/src/lib.rs#L606

Ref: #8809

**Comment by GopherJ** [comment]
I do think RA works on regular project, but I'm also sure it doesn't work well with `substrate` blockchain library, it always crashes and it's super slow on indexing.

**Comment by GopherJ** [comment]
Sorry to put @fannheyward here, maybe you have some ideas~

**Comment by GopherJ** [comment]
My environment is:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/33961674/118740322-2620b580-b87e-11eb-9cd4-949b100cf491.png">

**Comment by fannheyward** [comment]
<img width="964" alt="截屏2021-05-19 上午10 55 32" src="https://user-images.githubusercontent.com/345274/118749753-bd8f0400-b890-11eb-8ff9-6d13b6f2cc4a.png">

Tested with `rust nightly-aarch64-apple-darwin` + `cargo 1.54.0-nightly (070e459c2 2021-05-11)` + `rust-analyzer b82458818 2021-05-17 stable`, works. rust-analyzer needs a long time to do indexing and loading metadata.

**Comment by GopherJ** [comment]
@fannheyward thanks for your efforts to reproduce, where can I find the environments that you are using:

- neovim
- coc.nvim version
- coc-settings.json

I would really like to fix my setup

**Comment by fannheyward** [comment]
```
vim version: NVIM v0.5.0-dev+e0a01bdf7
node version: v16.1.0
coc.nvim version: 0.0.80-304b34c2a3 --> feat/lsp-316 branch 
```

```
❯ rust-analyzer --version
rust-analyzer b82458818 2021-05-17 stable
```

`stable` is https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-05-17

**Comment by GopherJ** [comment]
> ```
> vim version: NVIM v0.5.0-dev+e0a01bdf7
> node version: v16.1.0
> coc.nvim version: 0.0.80-304b34c2a3 --> feat/lsp-316 branch 
> ```
> 
> ```
> ❯ rust-analyzer --version
> rust-analyzer b82458818 2021-05-17 stable
> ```
> 
> `stable` is https://github.com/rust-analyzer/rust-analyzer/releases/tag/2021-05-17

strange it should be the same with;

```
cd rust-analyzer
git checkout 2021-05-17
cargo  xtask install --server
```

**Comment by GopherJ** [comment]
@fannheyward I just tested your `feat/lsp-316` branch, it looks better, I succeed to have references after like 10 seconds (RA is slow)

but when I try to checkout `output`, it crashed again

**Comment by fannheyward** [comment]
<img width="957" alt="截屏2021-05-19 下午12 38 09" src="https://user-images.githubusercontent.com/345274/118757148-136aa880-b89f-11eb-92ae-42f5400b8089.png">

@GopherJ  coc release also works, no crashes in output channel.

**Comment by fannheyward** [comment]
@GopherJ I don't have any `rust-analyzer` related configurations in coc-settings.json, you can try this.

**Comment by GopherJ** [comment]
@fannheyward yes I tried to remove the configuration but it still crashes easilly, I suspect it's my macbook m1's issue.

**Comment by GopherJ** [comment]
some other debug logs are:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/33961674/118791434-49248700-b8c9-11eb-927d-486d4d55c97c.png">

**Comment by GopherJ** [comment]
@fannheyward it seems that I've found the issue:

if I comment this line and then uses the one from github release, it starts to work
```
 /* "rust-analyzer.server.path": "~/.cargo/bin/rust-analyzer", */
```

**Comment by GopherJ** [comment]
@fannheyward thanks for your big help, I'll continue to observe if there are other issues, but now the github release one is working from what I see
