### ISSUE TITLE
parameter name inlay hints hiding heurestic is pretty inconsistent

### ISSUE THREAD

**Issue by Frizi** [rust-analyzer/rust-analyzer#8878]
Right now, inlay hints for the parameter name are being hidden if the method name in parameter expression contains a substring of the parameter name. This often leads to weird behaviour if the parameter name is short.

E.g. in this situation, the "x" inlay hint is hidden because of "x" in "max". 
![image](https://user-images.githubusercontent.com/919491/118801313-267e7800-b8a1-11eb-8073-6c3b901d17fd.png)
with "x" from "max" removed:
![image](https://user-images.githubusercontent.com/919491/118801436-4ca41800-b8a1-11eb-8ea3-e58d7531adcf.png)

I would expect to either have both inlays displayed (because neither method contains delimetered "x" or "y" in their name), or both should be hidden due to `x` or `y` existing as a standalone symbol in the whole expression.

**Comment by Veykril** [comment]
I guess we ideally shouldn't hide the hints for method calls that have parameters?
