### ISSUE TITLE
Implement match ergonomics (binding modes) in type inference

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#888]
E.g.
```rust
let x = Some(1);
match &x {
    Some(n) => n, // n should be &i32
}
match &mut x {
    Some(n) => n, // n should be &mut i32
}
```
and so on. We currently just infer wrong types in this situation. To fix this, when walking through patterns with `infer_pat`, we need to keep track of the 'binding mode' and apply it when creating bindings. This is also explained in the [rust reference](https://doc.rust-lang.org/reference/patterns.html#binding-modes); and I think rustc handles it [here](https://github.com/rust-lang/rust/blob/e17c48e2f21eefd59748e364234efc7037a3ec96/src/librustc_typeck/check/_match.rs#L77).

**Comment by h-michael** [comment]
I'll try it :)
