### ISSUE TITLE
incorrect semantic highlight

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#8890]
<img width="628" alt="image" src="https://user-images.githubusercontent.com/33961674/118908218-8d5c6980-b953-11eb-8132-965dadf848d5.png">

**Comment by GopherJ** [comment]
as you can see that I've used `CONF` but it's still marked as gray `Non-used code`

**Comment by Veykril** [comment]
We don't lint unused code. We only show that from rustc which I imagine is being shown here due to `Config::from_file` not yet being used by your code. Pretty confident in that assumption given the function name is also highlight as gray.

**Comment by jonas-schievink** [comment]
Yeah this seems correct
