### ISSUE TITLE
Rust analyzer shows private types in type hints

### ISSUE THREAD

**Issue by weiznich** [rust-analyzer/rust-analyzer#8891]
Consider the following code:

```rust
#[macro_use] extern crate diesel; // 1.4.6
use diesel::prelude::*;

table! {
    users {
        id -> Integer,
        name -> Text,
    }
}

fn test() {
    let f = users::table.filter(users::name.eq("bar"));
}

```

Rust analyzer shows the following type for the variable `f`: `SelectStatement<table, DefaultSelectClause, NoDistinctClause, WhereClause<{unknown}>>`. Now the problem with this is that all types (with the exception of `table`) in this composite type cannot be referenced by a user in a third party crate, as they are not exported through any public API. The `table` type is generated by the `table!` macro, so given only this type name the user cannot see where it comes from.
A better type hint would be the following type (using types from `diesel::dsl`): `Filter<users::table, {unknown}>` or with the `{unknown}` part replaced: `Filter<users::table, Eq<users::name, &'static str>>`. This also matches the type returned by the [corresponding trait function](https://docs.diesel.rs/1.4.x/diesel/query_dsl/trait.QueryDsl.html#method.filter).

I should probably add that rustc itself has a similar bug, where it shows those private types as part of error messages.

**Comment by flodiebold** [comment]
I don't think replacing private types by `{unknown}` would be particularly useful; we shouldn't show ever `{unknown}` except if there are errors. I'd rather show the private type. Showing the `Filter` type alias might be possible; that's #1666.

**Comment by weiznich** [comment]
> I don't think replacing private types by {unknown} would be particularly useful; we shouldn't ever show {unknown} except if there are errors. 

Sorry if that was not clear, replacing private types by `{unknown}` was not my proposal. I've just transformed the private type to the corresponding typedef while leaving the `{unknown}` "type" in place. 
While I'm here: Is there anything I can provide as additional information to get the `{unknown}` type fixed?

> Showing the Filter type alias might be possible; that's #1666.

:+1: Closed in favor of the old bug

**Comment by flodiebold** [comment]
> While I'm here: Is there anything I can provide as additional information to get the {unknown} type fixed?

Well, someone :tm: needs to trace through what type _should_ be there, how it would be inferred, and why that doesn't work right now :slightly_smiling_face:
