### ISSUE TITLE
Import Merge Behavior doc on manual is out of date

### ISSUE THREAD

**Issue by eduardocanellas** [rust-analyzer/rust-analyzer#8892]
Hello, I used to have this setting on my `settings.json` on vscode:

`"rust-analyzer.assist.importMergeBehavior": "full"`

I noticed that there was a warning informing that the "full" value is not accepted anymore. So I went to the user manual to learn about the new options, but only the old ones are there. See the [Auto Import section](https://rust-analyzer.github.io/manual.html#auto-import).

I also noticed that the [nvim-lsp section](https://rust-analyzer.github.io/manual.html#nvim-lsp) also shows an old option ("last") for `importMergeBehavior`.

**Comment by Veykril** [comment]
Good catch, I completely forgot to update those. Note that using `full` and `last` should still work just that they were renamed to more appropriate names in line with rustfmt does. In fact next release `importMergeBehavior` will be renamed to `importGranularity` as well.

I'll update the doc section of auto import.

**Comment by Veykril** [comment]
Fixed in #8893
