### ISSUE TITLE
View Crate Graph resulted in an error

### ISSUE THREAD

**Issue by numfin** [rust-analyzer/rust-analyzer#8903]
Windows 10, Visual Studio Code.

After running: `Rust Analyzer: View Crate Graph`

I get an error:
![image](https://user-images.githubusercontent.com/8134947/119089514-f3f48c80-ba12-11eb-9a4e-c8552f9c0ceb.png)

Extension host log says:
![image](https://user-images.githubusercontent.com/8134947/119089564-07075c80-ba13-11eb-89f5-2be57965d28b.png)

I will provide more info if needed.

**Comment by lnicola** [comment]
You need to [install](https://graphviz.org/download/) GraphViz.

**Comment by pravic** [comment]
Same here. It would be nice to have a better error message :(
