### ISSUE TITLE
Hang in wasmer during item collection

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#8905]
```
λ git clone https://github.com/matklad/wasmer-repro && cd wasmer-repro
Cloning into 'wasmer-repro'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 12 (delta 0), reused 12 (delta 0), pack-reused 0
Receiving objects: 100% (12/12), 7.08 KiB | 7.08 MiB/s, done.

13:21:38|~/tmp/wasmer-repro|master✓
λ rust-analyzer analysis-stats .
Database loaded:     966.26ms, 155minstr
```

For a change, this is a hang **not** in chalk. Perhaps related to nameres changes? Didn't try to minimize yet

**Comment by matklad** [comment]
Good commit: 1f7d2a6c2297de4dedfb42b739e880ad2dd7d5d5
Bad commit: eb08a27f1bd31cc15db4893dded60663effaf3f9

Seems like this might be the attributes name res chage? @jonas-schievink

**Comment by matklad** [comment]
Fun fact: this was to be a repro for a different bug in a different project: https://github.com/wasmerio/wasmer/issues/2328

**Comment by jonas-schievink** [comment]
764241e38 is still good, probably caused by https://github.com/rust-analyzer/rust-analyzer/pull/8898

**Comment by jonas-schievink** [comment]
Repro:

```rust
#[unresolved]
extern "C" {
    #[unresolved]
    fn f();
}
```

**Comment by jonas-schievink** [comment]
This is from js-sys, actually, which was reported as having the same bug in https://github.com/rust-analyzer/rust-analyzer/issues/8414#issuecomment-845607923

**Comment by jonas-schievink** [comment]
I have a suspicion that the ItemTree represents this as

```rust
#[unresolved]
#[unresolved]
fn f(); // IS_IN_EXTERN_BLOCK
```

...and this results in problems further down the line. We need to represent extern blocks as a first-class item in the ItemTree in order to allow attribute macros on them anyways, so I'll do that and see what happens.

Also, having a way to pretty-print ItemTrees in a Rust-like syntax would be handy to debug this.

**Comment by jonas-schievink** [comment]
Hmm, it still hangs while indexing wasmer_compiler

**Comment by jonas-schievink** [comment]
Repro:

```rust
//- /main.rs crate:main deps:proc
#[cfg_attr(not(off), derive(proc::Derive), helper)]
struct S;

//- /proc.rs crate:proc
#[proc_macro_derive(Derive, attributes(helper))]
fn derive() {}
```

I forgot that `cfg_attr` can gate any number of attributes. This is going to require a very different approach for removing the right attribute later on.
