### ISSUE TITLE
"proc macro server crashed" in presence of attribute proc-macros

### ISSUE THREAD

**Issue by Shnatsel** [rust-analyzer/rust-analyzer#8906]
I am aware of #6029, but I'd expect unsupported attribute macros to be ignored, not to crash RA.

rust-analyzer version: `b82458818 2021-05-17 stable`

Panic messages from RA output in VSCode: https://gist.github.com/Shnatsel/f71fa1f070c6547cb282a3ee76c211c0
They are quite spectacular, there's a panic while panicking.

Steps to reproduce: open https://github.com/RustSec/rustsec/tree/main/admin directory in VSCode and navigate to `commands.rs`

**Comment by lnicola** [comment]
That's a proc macro ABI incompatibility with the old version in your `rust-toolchain`. The metadata is versioned, but it seems that the format changed at some point without bumping the version. Regardless of that, we only support the last stable proc macro ABI.

**Comment by Shnatsel** [comment]
Is there a FAQ entry on how to resolve this?

Rust version for reference:
```
> rustc --version --verbose 
rustc 1.52.1 (9bc8c42bb 2021-05-09)
binary: rustc
commit-hash: 9bc8c42bb2f19e745a63f3445f1ac248fb015e53
commit-date: 2021-05-09
host: x86_64-unknown-linux-gnu
release: 1.52.1
LLVM version: 12.0.0
```

**Comment by lnicola** [comment]
You can either:

 - disable proc macro support
 - remove the `rust-toolchain` file
 - wait for multiple proc ABI support to be added to RA (to say the least, that's unlikely to be a priority)

**Comment by lnicola** [comment]
> `rustc 1.52.1 (9bc8c42bb 2021-05-09)`

What does `rustup toolchain list` show?

**Comment by Shnatsel** [comment]
Ah I see, it must be the `toolchain` file that's causing this.

```
> rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)
beta-x86_64-unknown-linux-gnu
nightly-2018-10-12-x86_64-unknown-linux-gnu
nightly-2019-04-12-x86_64-unknown-linux-gnu
nightly-2019-05-22-x86_64-unknown-linux-gnu
nightly-2019-10-17-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.24.1-x86_64-unknown-linux-gnu
1.32.0-x86_64-unknown-linux-gnu
1.39.0-x86_64-unknown-linux-gnu
1.42.0-x86_64-unknown-linux-gnu
1.46.0-x86_64-unknown-linux-gnu (override)
```

**Comment by lnicola** [comment]
Yes, your project's `rust-toolchain` file asks for 1.46. It's the same issue as https://github.com/rust-analyzer/rust-analyzer/issues/8148#issuecomment-810421898.

**Comment by Shnatsel** [comment]
I see, I'll close it in favor of that issue then.
