### ISSUE TITLE
no typehint/typeinfer for async fn on rustc-nightly-2021-05-20 with rust-analyzer

### ISSUE THREAD

**Issue by pymongo** [rust-analyzer/rust-analyzer#8907]
I tried this code:

```rust
async fn foo() -> Result<i32, ()> {
    Ok(1)
}

async fn bar() -> Result<(), ()> {
    let temp = foo().await?;
    Ok(())
}
```

But no typehint/type annotation for variable `temp` if rustc's version is nightly-2021-05-20

If I only change rustc's version by `rustup override set nightly-2021-05-16` and reload vscode's window, the typehint for variable `temp` show correctly.

typehint for `async fn foo() -> Result<i32, ()>` works ok on nightly-2021-05-16, but failed on nightly-2021-05-20

I use the same rust-analyzer executable file, I think this problem cause by rustc.

### Meta

`rust-analyzer --version`:
```
rust-analyzer fd109fb 2021-05-20 dev
```

`rustup show`:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/w/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2021-05-16-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (directory override for '/home/w/temp/no_typehint_for_async_fn_response_on_rustc_0520')
rustc 1.54.0-nightly (40d230204 2021-05-20)
```

**Comment by flodiebold** [comment]
Did something about the representation of futures change in nightly?

**Comment by mati865** [comment]
I think there were more changes than that. In proprietary code which I cannot share and latest nightly proc-macros panic when running rust-analyzer (`target/` was wiped). Rustc works fine with the same code.
I'll try to obtain any logs next week, all I can tell right now the failing proc macro was panicking on out of bounds access to something.

**Comment by flodiebold** [comment]
Changes to the proc macro ABI don't matter for this example, though.

**Comment by pymongo** [comment]
> @pymongo do you get type hints for other, non-async functions?

Only `.await?` on async fn return Result<T> without typehint

![Imgur](https://i.imgur.com/1MGUkDO.png)

rustc nightly-2021-05-20 and nightly-2021-05-21 no typehint for `let temp = foo().await?;`

---

the typehint for .await? on async fn return value works great on nightly-2021-05-16:

![](https://i.imgur.com/z5qHWzC.png)

**Comment by Veykril** [comment]
The new try trait got merged on nightly which causes us to fail when looking up the `OK` assoc type on it as the new version doesn't have that associated type anymore. https://github.com/rust-analyzer/rust-analyzer/blob/3cfe2d0a5d663d29c3d196f9d16e91964780792a/crates/hir_ty/src/infer.rs#L577-L581
<https://doc.rust-lang.org/nightly/std/ops/trait.Try.html>
So this isnt a problem specific to async functions, but to `?` in general I believe.

**Comment by flodiebold** [comment]
Aah right. We should build in a fallback to look for `Output` instead.

**Comment by Veykril** [comment]
Also is there a reason we are resolving the trait via its path instead of the lang item name?

**Comment by flodiebold** [comment]
Judging from the `cfg_attr`, the lang item is new. IIRC the desugaring of `?` worked syntactically, not using a lang item. I'm not sure what the lang item is used for, actually.
