### ISSUE TITLE
VSCode plugin: No Intellisense autocompletion when "Add Call Argument Snippets" is enabled

### ISSUE THREAD

**Issue by mr-briggs** [rust-analyzer/rust-analyzer#8933]
When `rust-analyzer.completion.addCallArgumentSnippets` is enabled for the rust-analyzer VSCode plugin, there is no Intellisense autocompletion available after the argument snippets are added. This means in order to have autocompletion, one has to either disable the aforementioned argument snippets option, or move the cursor out of the function call's brackets.

An example can be [seen here](https://streamable.com/cxjrwe). It shows me being unable to autocomplete a `SnakeMovement` enum after call arguments are added. After moving my cursor out and back in, it's able to properly autocomplete.

This issue might be specific to the VSCode plugin. As far as I can tell, this happens every time rust-analyzer adds call argument snippets (i.e. it's not specific to my code in the example).

It would be ideal if both argument snippets and autocompletion could work simultaneously.

**Comment by Veykril** [comment]
Can confirm this happening with vscode, though you can still invoke autocompletion manually which will show the results again 🤔

**Comment by Veykril** [comment]
Turns out this is caused by VSCode, setting `"editor.suggest.snippetsPreventQuickSuggestions": false` fixes this behavior.
