### ISSUE TITLE
Request/thought: Client agnostic way of adding arguments to runnables

### ISSUE THREAD

**Issue by simrat39** [rust-analyzer/rust-analyzer#8934]
I'm not sure if this is within the scope of the language server, but something cool would be the ability to add custom arguments to runnables without the client doing anything (by reading a json file on project root if it exists maybe). This would atleast prevent having to implement it for every client because tbh it is a desirable feature.

**Comment by matklad** [comment]
I think that's https://github.com/rust-analyzer/rust-analyzer/pull/5954 ?

cc https://github.com/microsoft/language-server-protocol/issues/1239

**Comment by simrat39** [comment]
Sorry for being so late, yes that is what i was thinking of.

Closed as #5954 is already merged

**Comment by matklad** [comment]
Ah, meant to link https://github.com/microsoft/language-server-protocol/issues/944

I wish there was more motion on this feature -- it is one of the best feature of RA. If, on neovim side, you'd wish to add first-class support for it, I'd be happy to implement anything on VS Code side.

The main thing this feature is missing at the moment is configuration persitance and editing. As a user, I want to be able to get the "run" ccommand for a specific test, then edit it, save it, and use the edited command across restarts.
