### ISSUE TITLE
Support for #[rstest] tests

### ISSUE THREAD

**Issue by la10736** [rust-analyzer/rust-analyzer#8964]
Hi,
an user of my crate ask a way to debug (but also just run today fails) `#[rstest]`'s tests https://github.com/la10736/rstest/issues/120 . Today the lens appear correctly but the runner execute something like 

```sh
cargo test --package <package> --bin <binary> -- <test_path> --exact --nocapture
```

That's ok if you have just a single test that use only fixtures but in the case you have cases or value list the procedural macro create a module that contains test functions or other modules.

So maybe in this case the best would be identify this as a _Test module_ like it is.

Today rust-analyzer use a simple heuristic to identify test function (last argument path segment contains `test` word) and this work well to find `rstest`'s ones, but look just hir cannot be useful to find how `rstest` expand it and crate a test module.

So if you are ok I can create a PR that simply catch `rstest` in `runnable_fn` and return a `RunnableKind::TestMod` instead of a `RunnableKind::Test`.

I know that a catch of explicit `rstest` is not the best but I don't have any better idea.

Let me know if you like it and I can send a PR.

**Comment by Veykril** [comment]
Special casing crates like that isn't really something we want to do I think. The main problem here right now is that we don't currently expand attribute macros yet. Once we do we can handle these better though by looking at the expansion for test attributes potentially. Then we could probably just have the lens execute all the tests that the expansion created instead which should fix this.

At least I believe it should work like this.

**Comment by la10736** [comment]
Ok, reasonable. If I was the rust-analyzer maintainer maybe I had said the same thing.

As workaround can we make the `--exact` flag an option via configuration flag?

**Comment by la10736** [comment]
Ok, we're waiting for #6029. Should be fix almost all.

**Comment by Veykril** [comment]
Ye, attribute macros should come soon-ish at which point this can be tackled 👍

**Comment by Veykril** [comment]
So with attribute expansion we do get correct-ish lenses now, but they aren't too helpful the way they are now 
![image](https://user-images.githubusercontent.com/3757771/124005025-e7cbf980-d9d8-11eb-82ef-1ed79affa24e.png)

**Comment by Veykril** [comment]
So I think we probably wanna show `Run case_1`, ... instead of the generic `Run test` when this comes from a macro invocation that yields multiple tests? Also a bit odd that we do not sure a runnable for the module at all.

**Comment by Veykril** [comment]
![image](https://user-images.githubusercontent.com/3757771/124014848-519dd080-d9e4-11eb-8ab6-544c88e20127.png)
This is how that would look like

**Comment by la10736** [comment]
Wow!!! That's really amazing!!!
Thanks a lot!
