### ISSUE TITLE
2021-05-24 release is missing binaries

### ISSUE THREAD

**Issue by cschmatzler** [rust-analyzer/rust-analyzer#8966]
Hi!

Tried to update to the latest version, but had to realize that the newest release is missing un-gzipped binaries from its assets.
As such, the command listed in the docs (https://rust-analyzer.github.io/manual.html#rust-analyzer-language-server-binary), `curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux -o ~/.local/bin/rust-analyzer` does not work for installation as the link is a 404.

I don't know if it's a CI regression or it was missed manually, but would be good to either add those binaries back or update the docs with a new installation method.

Cheers

**Comment by lnicola** [comment]
Thanks! This was https://github.com/rust-analyzer/rust-analyzer/pull/8926. We should update the docs.

**Comment by cschmatzler** [comment]
Missed that one, thanks!
