### ISSUE TITLE
unresolved macro `metrics::histogram!`

### ISSUE THREAD

**Issue by SteinsElite** [rust-analyzer/rust-analyzer#8981]
hello, i'm new to rust and ra, when i use macro 'metrics::histogram!',i could go to the defination of the macro,but it alway report problem with unresolved macro `metrics::histogram!`,i want to figure out why, should i download the metric crate by rustup?

**Comment by SteinsElite** [comment]
<img width="773" alt="Screen Shot 2021-05-25 at 2 41 27 PM" src="https://user-images.githubusercontent.com/69792300/119451108-75c41d00-bd67-11eb-9e4d-3badeb5c9f45.png">

**Comment by lnicola** [comment]
Which version of the `metrics` crate are you using?

**Comment by lnicola** [comment]
We don't support `#[proc_macro_hack]`, but somewhere between `0.13.0-alpha.11` and `0.13.0-alpha.13` `metrics` stopped using that.

**Comment by SteinsElite** [comment]
i use the 0.13.0-alpha.8, so i should update the version of the metric??

**Comment by lnicola** [comment]
Any version later than `0.13.0-alpha.13` should work. I tested the latest one (`0.16`). Attribute proc macros will be implemented soon(ish), so it might start working for that one too, but unless you have good reasons you probably shouldn't use an `-alpha` build anyway.

**Comment by SteinsElite** [comment]
i got it ， thank you

**Comment by lnicola** [comment]
Well, let's close this then.
