### ISSUE TITLE
Unresolved import when using the same crate as a regular and build dep

### ISSUE THREAD

**Issue by azdavis** [rust-analyzer/rust-analyzer#8982]
When a crate B depends on a crate A as both a regular and build dependency, and then tries to reference crate A in its build.rs, rust-analyzer says there is an unresolved import. But, cargo is fine.

Here's a sample workspace that should reproduce the bug: [hmm.zip](https://github.com/rust-analyzer/rust-analyzer/files/6537274/hmm.zip)

`cargo build` in the workspace root reports no errors but rust-analyzer does report an error:
<img width="585" alt="err" src="https://user-images.githubusercontent.com/6496454/119456535-9e103500-bcef-11eb-92a2-f1e7fe15ecbc.png">

- rust-analyzer version: 3022a2c3a 2021-05-24 stable
- client: vscode

**Comment by lnicola** [comment]
Might have been fixed by https://github.com/rust-analyzer/rust-analyzer/pull/8970.

**Comment by lnicola** [comment]
Yeah, works in nightly.
