### ISSUE TITLE
Handle implicit `Sized` bounds

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#8984]
We currently don't add the implicit `Sized` bounds to type parameters, which leads to some inaccuracies in trait solving, so we need to fix this.

Rough steps:
 - find out the exact conditions for the implicit `Sized` bound (is it simply all type parameters and associated types without `?Sized` except trait `Self`? not sure)
 - during [lowering of generic predicates](https://github.com/rust-analyzer/rust-analyzer/blob/4afc1b8c34aab2a0a32e549ab977d756a7066b28/crates/hir_ty/src/lower.rs#L1046-L1059), add the `Sized` bounds for all type parameters that don't have `?Sized` (I feel it makes more sense to add them at this step, rather than in `hir_def`, but I'm not 100% sure) except for trait `Self`
 - similarly, add the bounds for associated types; their bounds are currently lowered directly [in the Chalk integration](https://github.com/rust-analyzer/rust-analyzer/blob/33fdd512e318f86ccd66b84ce6128c03eb44cf77/crates/hir_ty/src/chalk_db.rs#L383-L397), which we should change at some point (maybe now!)
 - make sure we don't suddenly print `+ Sized` everywhere, e.g. when displaying argument `impl Trait` types
 - the `coerce_unsize_apit` test should now work correctly; maybe add some explicit tests with `Sized` bounds in trait impls
 - check `analysis-stats` performance before/after

**Comment by bjorn3** [comment]
> is it simply all type parameters without ?Sized except trait Self?

As far as I am aware that is the case.

**Comment by flodiebold** [comment]
Hmm, associated types get it as well, don't they?

**Comment by bjorn3** [comment]
They would have to for `Self::Foo` to be acceptable as argument and return type.

**Comment by iDawer** [comment]
If nobody working on this yet, I'd like to claim it.

Nice opportunity to learn Chalk!
<details>
<summary>Got some intermediate results</summary>

```rust
//#[test]
//fn play() {
//    check_infer(
//        r#"
#[lang = "sized"]
trait Sized {}

trait Foo {
    fn foo() -> u8;
}
trait Trait<T: Foo + ?Sized, U: Foo> {
    fn bar() {
        T::foo;
    }
}
//"#,
//        expect_test::expect![[]],
//    );
//}
 ```
`dbg!()` output:
```
running 1 test
generic_predicates_query: def = TraitId(TraitId(1)), trait Foo
[crates/hir_ty/src/lower.rs:1096] &explicitly_unsized_tys = {}
[crates/hir_ty/src/lower.rs:1121] predicates = []
generic_predicates_query: def = TraitId(TraitId(2)), trait Trait
[crates/hir_ty/src/lower.rs:1096] &explicitly_unsized_tys = {
    ^0.1,
}
[crates/hir_ty/src/lower.rs:1121] predicates = [
    for<type, type, type> for<> Implemented(^1.1: TraitId(1)),
    for<type, type, type> for<> Implemented(^1.2: TraitId(1)),
    for<type, type, type> for<> Implemented(^1.2: TraitId(0)),
]
generic_predicates_query: def = TraitId(TraitId(0)), trait Sized
[crates/hir_ty/src/lower.rs:1096] &explicitly_unsized_tys = {}
[crates/hir_ty/src/lower.rs:1121] predicates = []
```
</details>

**Comment by jonas-schievink** [comment]
@iDawer Are you still working on this? If not I can pick this up

**Comment by flodiebold** [comment]
@jonas-schievink If you do, note that they did run into some problems: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/implicit.20Sized.20bounds

**Comment by iDawer** [comment]
I apologize for being missing without a notify. I'm back and will continue on this
