### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#9]
The MVP for libsyntax2.0 is to create a small library for code editors, which provides some basic functionality, depending only on the syntax. Specifically, the plan is to port stuff that lives in fall [here](https://github.com/matklad/fall/tree/b00befdfe06a4b3de3301c2fc358bed75b37f4c7/lang/rust/src/editor) and [here](https://github.com/matklad/fall/tree/b00befdfe06a4b3de3301c2fc358bed75b37f4c7/code/rust).

- [x] parse most of the common Rust syntax
- [x] incremental relexing (should be trivial to do, in contrast with incremental reparsing)
- [x] [extend selection](https://github.com/matklad/fall/blob/b00befdfe06a4b3de3301c2fc358bed75b37f4c7/fall/editor/src/extend_selection.rs)
- [x] [file structure](https://github.com/matklad/fall/blob/b00befdfe06a4b3de3301c2fc358bed75b37f4c7/lang/rust/src/editor/mod.rs#L128)
- [x] [project symbols](https://github.com/matklad/fall/blob/b00befdfe06a4b3de3301c2fc358bed75b37f4c7/lang/rust/src/editor/symbol_index.rs)
- [x] [add impl action](https://github.com/matklad/fall/blob/b00befdfe06a4b3de3301c2fc358bed75b37f4c7/lang/rust/src/editor/actions.rs#L39)

**Comment by aochagavia** [comment]
Is this up to date? It would be nice to outline a path to an alpha version that we can announce on Rust internals and publish on the vscode marketplace... I think many people (like me) would get enthusiastic about a language server that you can actually build yourself and it may even attract new contributors!

**Comment by aochagavia** [comment]
Also, from the discussion about the future of the compiler on the internals forum I got the impression that some people in the Rust team would really like the compiler to be more modular... Which aligns very well with the goals of Rust Analyzer. I see for instance that Niko is working on things like Salsa, Chalk, Polonius, etc. Is there a plan to work together to bring Rust Analyzer to a usable state?
