### ISSUE TITLE
Move function CodeLenses above attributes

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#9000]
As it stands, function CodeLenses appear directly above the function signature, below any attributes:

<img width="642" alt="Screen Shot 2021-05-26 at 4 24 26 pm" src="https://user-images.githubusercontent.com/31783266/119612156-e853fc00-be3e-11eb-9495-ac4bc28c8b19.png">

Types have their CodeLenses above attributes, though:

<img width="294" alt="Screen Shot 2021-05-26 at 4 25 41 pm" src="https://user-images.githubusercontent.com/31783266/119612262-0588ca80-be3f-11eb-8461-87ef84a09801.png">

**Comment by Veykril** [comment]
Now I wonder if it would make more sense to move the lenses below the attributes for items instead? If you got a lot of different attributes the lenses would be pushed above them all which disconnects them from the item visually quite a bit I believe? But having the lense cut the attributes off of the item doesn't seem that great either, not sure what I would prefer.

**Comment by SomeoneToIgnore** [comment]
I also like the "moving below" idea more, rustc contains many encouraging examples: 

<img width="715" alt="image" src="https://user-images.githubusercontent.com/2690773/119641285-2bec3d00-be22-11eb-95d4-b87b545ed1aa.png">

In this example, placing the code above the comment or just above the annotations (below the comment) feels quite uncomfortable to use.

**Comment by lnicola** [comment]
![image](https://user-images.githubusercontent.com/308347/119940553-0aad5d00-bf98-11eb-8830-01e878898a61.png)

TBH, this looks a bit weird to me.

**Comment by SomeoneToIgnore** [comment]
In your opinion, would that look less weird if all lens would be moved down, next to the function declaration?

**Comment by lnicola** [comment]
I think they'd look better together, but I have no strong opinion on whether they should be above or below the attributes -- I think I prefer them above, but I'm not too sure.

**Comment by Veykril** [comment]
Oh, my intention was never to split them up 😅 I forgot about the runnables

**Comment by lnicola** [comment]
Yeah, either is fine as long as the lenses sit together.
