### ISSUE TITLE
type inference of return value in async fn

### ISSUE THREAD

**Issue by paulcmmrclly** [rust-analyzer/rust-analyzer#9004]
```rust
async fn get_accounts() -> Result<Vec<String>, ()> {
    let accounts = Vec::<String>::new().iter().map(|x| x.clone()).collect();
    //  ^ Vec<String> but r-a infers {unknown}
    Ok(accounts)
}
```

This works without async.

rust-analyzer: 5a1fd0576 2021-05-26
rustc 1.54.0-nightly (3e99439f4 2021-05-17)

**Comment by cynecx** [comment]
@flodiebold I am currently looking into this. It seems like we get the fully desugared impl trait type (`impl Future<Output = ...>`) here:

https://github.com/rust-analyzer/rust-analyzer/blob/7869b01b702d1f12acb03ac131b6eb90ad82e9bb/crates/hir_ty/src/infer.rs#L561

It doesn't seem right that we use that fully desugared type for further inference. It would make more sense to use the "actual" return type (`Output`). I've tried it locally and it seems to work out. Do you think that this is the right fix? Or is there a deeper problem somewhere?

**Comment by flodiebold** [comment]
Yeah, I think we can't get around some kind of hacky solution where the 'inner' return type is different from the outer one, since we can't do the full generator desugaring right now. Probably keeping track of the async return type in a separate field in the function data would be the right move for now.

**Comment by cynecx** [comment]
> Probably keeping track of the async return type [...]

Are you talking about the fully desugared type (`impl Future`)? Or the `Output` type?

**Comment by flodiebold** [comment]
The latter, probably.
