### ISSUE TITLE
Rewrite import merging to use mutable syntax trees

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#9013]
Our improt merging logic currently takes two import trees and recursively zips together a new one from them, this causes us to completely discard the previous two trees including any kind of order of the imports inside of them, which might be unwanted by the user.

Now that we got mutable trees though we should be able to reimplement that while also getting rid of some rather complex and difficult to read code.

Relevant code to replace/rewrite:
https://github.com/rust-analyzer/rust-analyzer/blob/bb1c7fc0cfe24a8477d943faa932992b9cd48957/crates/ide_db/src/helpers/merge_imports.rs#L74-L181

**Comment by iDawer** [comment]
> this causes us to completely discard the previous two trees including any kind of order of the imports inside of them, which might be unwanted by the user.

Hmm
```rust
use foo::{b, a, d};
use foo::c;
```
so from current behavior giving `foo::{a, b, c, d}` we want it to to give `foo::{b, a, d, c}`?

But how about merging into a sorted tree?
```rust
use foo::{a, b, d}; // sorted
use foo::c;
```
Should it try to play smart by detecting the sorted state and add `c` after `b`? Personally I'd just add it to the end and leave for user to decide (to call rustfmt or whatever).

**Comment by Veykril** [comment]
Ah I didn't mention this, but yes, ideally we would try to insert in a sorted fashion rather than just appending, at least that was my idea. But maybe we want that to be configurable whether we just append or insert ordered. I don't think detecting that the list is sorted works too well(but maybe it does!).
