### ISSUE TITLE
Hovering on non-terminal fn path inconsistent

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#904]
In hover.rs we have:

```rust
let navs = crate::goto_definition::name_definition(db, position.file_id, name);
```

Hovering over `name_definition` gives nice colorized output with visibility information. Hovering over `goto_definition` gives us the same function information but not colorized and no visibility.

**Comment by vipentti** [comment]
It is due to hovering over `goto_definition` going through this branch https://github.com/rust-analyzer/rust-analyzer/blob/84e47113e0ab581c1b2c207cbcb212aa86f83c4a/crates/ra_ide_api/src/hover.rs#L105-L112

I'm not sure what would be the best way to fix this

**Comment by lnicola** [comment]
@kjeremy I think this is solved?
