### ISSUE TITLE
matches! is broken (pat_param support)

### ISSUE THREAD

**Issue by digama0** [rust-analyzer/rust-analyzer#9043]
This fails on the latest nightly:
```rust
fn main() {
    matches!((), ()); // unexpected token in input
}
```
The issue appears to be the new `pat_param` token in the implementation of `matches!` that recently landed on nightly std:
```rust
macro_rules! matches {
    ($expression:expr, $( $pattern:pat_param )|+ $( if $guard: expr )? $(,)?) => {
        match $expression {
            $( $pattern )|+ $( if $guard )? => true,
            _ => false
        }
    }
}
```
My recommendation would be to just make `pat_param` recognized as an alias of `pat` until this is properly supported.

```
rust-analyzer v0.2.612
rustc 1.54.0-nightly (1c6868aa2 2021-05-27)
```

This is a serious regression in nightly and it's important to fix it before the next release.
@matklad, please take a look.

**Comment by jonas-schievink** [comment]
Note that this affects the *Rust* nightly, not the *rust-analyzer* nightly
