### ISSUE TITLE
Fix type inference for try_trait_v2

### ISSUE THREAD

**Issue by cynecx** [rust-analyzer/rust-analyzer#9052]
See https://github.com/rust-analyzer/rust-analyzer/pull/8989#issuecomment-847968737.

According to @flodiebold (https://github.com/rust-analyzer/rust-analyzer/pull/8989#issuecomment-848034036), this seems to be an issue with Chalk.

**Comment by flodiebold** [comment]
The next step would be to try to reproduce this in a Chalk test. I think that should be pretty straightforward.

**Comment by cynecx** [comment]
Hm, this test passes:

```rust
#[test]
fn try_trait_v2() {
    test! {
        program {
            trait Try
            where
                Self: FromResidual<<Self as Try>::Residual>
            {
                type Output;
                type Residual;
            }

            trait FromResidual<R>
            where
                Self: Try {
            }

            enum Infallible {}

            enum Result<O, E> {
                Ok(O),
                Err(E)
            }

            impl<O, E> Try for Result<O, E> {
                type Output = O;
                type Residual = Result<Infallible, E>;
            }

            impl<T, E> FromResidual<Result<Infallible, E>> for Result<T, E> {}
        }

        goal {
            <Result<u32, ()> as Try>::Output = u32
        } yields {
            "Unique; substitution [], lifetime constraints []"
        }
    }
}

```

**Comment by flodiebold** [comment]
That's weird! I think
```rust
#[test]
fn try_trait_v2() {
    test! {
        disable_coherence;
        program {
            trait Try
            where
                Self: FromResidual<<Self as Try>::Residual>
            {
                type Output;
                type Residual;
            }

            trait FromResidual<R> {}

            enum Infallible {}

            enum Result<O, E> {
                Ok(O),
                Err(E)
            }

            impl<O, E> Try for Result<O, E> {
                type Output = O;
                type Residual = Result<Infallible, E>;
            }

            impl<T, E> FromResidual<Result<Infallible, E>> for Result<T, E> {}
        }

        goal {
            exists<T> {
                <Result<u32, ()> as Try>::Output = T
            }
        } yields[SolverChoice::recursive_default()] {
            "Unique; substitution [?0:=Uint(U32)], lifetime constraints []"
        }
    }
}
```
is closer to the RA test, but it still succeeds :thinking:

**Comment by flodiebold** [comment]
Ah,

```rust
#[test]
fn try_trait_v2() {
    test! {
        disable_coherence;
        program {
            trait Try
            where
                Self: FromResidual<<Self as Try>::Residual>
            {
                type Output where Self: FromResidual<<Self as Try>::Residual>;
                type Residual where Self: FromResidual<<Self as Try>::Residual>;
            }

            trait FromResidual<R> {}

            enum Infallible {}

            struct Result<O, E> {}

            impl<O, E> Try for Result<O, E> {
                type Output = O;
                type Residual = Result<Infallible, E>;
            }

            impl<T, E> FromResidual<Result<Infallible, E>> for Result<T, E> {}
        }

        goal {
            exists<T> {
                <Result<i32, u64> as Try>::Output = T
            }
        } yields[SolverChoice::recursive_default()] {
            "Unique; substitution [?0:=Int(I32)], lifetime constraints []"
        }
    }
}
```
fails like RA. We include the where clauses of the trait in the where clauses of the associated type. I'm not sure if that's correct, but I'm also not sure that it's incorrect :thinking:

**Comment by cynecx** [comment]
@flodiebold Why do the associated types have additional bounds? Can we temporarily implement a workaround by not doing that?

**Comment by flodiebold** [comment]
Hmm, since where clauses on associated types are actually unstable, we could probably just not return any where clauses on associated types to Chalk for now :thinking: Separating the where clauses of the trait from those of the associated type would be more complicated, since the query that lowers them combines all where clauses in scope.

**Comment by cynecx** [comment]
@flodiebold Hmm, I am currently looking at:

https://github.com/rust-analyzer/rust-analyzer/blob/f1d163ba51b7a06e2e34ea2b27c4c948a0ff2320/crates/hir_ty/src/utils.rs#L153-L156

Can't we just strip all the parent where clauses of `parent_generics` when we encounter an `GenericDefId::TypeAliasId`?

**Comment by flodiebold** [comment]
I don't think that would be a good idea. Other places expect all where clauses that are in scope to be included; introducing special handling without a principled reason there would probably cause more problems than it fixes. (Plus you can't just strip the where clauses there.) I'd rather remove the where clauses in `associated_ty_data_query`, since they're not supposed to be supported anyway.

**Comment by cynecx** [comment]
Okay, let me try that out quickly.
