### ISSUE TITLE
Feature request: Clippy viewer

### ISSUE THREAD

**Issue by Milo123459** [rust-analyzer/rust-analyzer#9063]
Something that'd be cool for VSCode is a little panel that updates whenever you update code, running `cargo clippy --all-targets --all-features` or whatever. This allows you to visualize what you need to fix, whether it's a warning or an error. It could have different icons represneintg different things, but would be very helpful.

**Comment by bjorn3** [comment]
You can use `"rust-analyzer.checkOnSave.command": "clippy"` to run `cargo clippy` instead of `cargo check`.

**Comment by Milo123459** [comment]
I know. But, it'd be cool if there was a panel parsing cargo clippy. This'd be good for people trying to fix there bugs

**Comment by bjorn3** [comment]
VSCode already has the problems pane which shows both errors and warnings. If rustc or clippy has a suggestion to fix the problem, you can apply it there most of the time.

**Comment by Milo123459** [comment]
I know but that's not what I meant, thanks anyway.
