### ISSUE TITLE
Proc macros tests are slow

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#9067]
Running test suite wit `cargo test -- -Z unstable-options --report-time`  shows that proc macros tests are outliers and are too slow:

```
3.385s test tests::test_version_check ... ok 
3.396s test tests::list_test_macros ... ok 
3.418s test tests::test_derive_serialize_proc_macro_failed ... ok 
3.422s test tests::test_derive_proc_macro_list ... ok 
3.428s test tests::test_derive_serialize_proc_macro ... ok 
```

**Comment by jonas-schievink** [comment]
These run `cargo check --tests --message-format json`. If we make all of them use `proc_macro_test` we could run `cargo build -p proc_macro_test --message-format json`  instead, which only builds a single crate.

**Comment by jonas-schievink** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/9086 reverted back to `cargo check` because this change apparently causes widespread issues on windows

**Comment by jonas-schievink** [comment]
Fixed by https://github.com/rust-analyzer/rust-analyzer/pull/9192
