### ISSUE TITLE
Add semantic token modifier for crate root

### ISSUE THREAD

**Issue by arzg** [rust-analyzer/rust-analyzer#9073]
Making it a modifier allows it to apply both to `std`, a `namespace`, and `crate`, a `keyword`.

**Comment by arzg** [comment]
I stumbled upon this issue again and realised it isn’t 100% clear.

The idea is to be able to differentiate between modules and crates. I’ve added comments for everything that would be given the modifier in this code sample:

```rust
use serde::{Serialize, Deserialize};
//  ^^^^^
use crate::Foo;
//  ^^^^^

impl From<std::collections::HashMap> for Foo {
    //    ^^^
    fn from(map: std::collections::HashMap> -> Self {
        //       ^^^
        Self { map }
    }
}
```

`crate` has the semantic token type `keyword`, and `std` and `serde` have the semantic token type `namespace`. If we were to replace these with a new `crateRoot` semantic token type, then the distinction would be lost. For this reason I think it would be better to use a semantic token modifier; named crates and the `crate` keyword keep their differentiation, and themes stay the same if no changes to them are made.

**Comment by lnicola** [comment]
Sure.
