### ISSUE TITLE
`#[proc_macro]`, `#[proc_macro_attribute]` and `#[proc_macro_derive]` attributes aren't completed

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#9076]
Seems like they should, even without an item they could attach to, since I'm about to write that item

**Comment by Veykril** [comment]
This seems to work for me? Or am I misunderstanding? 
![image](https://user-images.githubusercontent.com/3757771/120191978-e6ad7e00-c21a-11eb-943b-079a9df5657e.png)

**Comment by jonas-schievink** [comment]
Hmm, proc_macro attributes weren't showing up for me, maybe that's a different issue though?

**Comment by Veykril** [comment]
Oh ye I we don't complete those yet I think

**Comment by jonas-schievink** [comment]
Ah I meant `#[proc_macro]`, `#[proc_macro_attribute]` and `#[proc_macro_derive]` aren't showing up

**Comment by Veykril** [comment]
Oh now I see, sorry. Ye those are just missing from the list there
