### ISSUE TITLE
"Failed to download: Got response 401 when trying to fetch info for 2021-5-31 release"

### ISSUE THREAD

**Issue by bill-baggins** [rust-analyzer/rust-analyzer#9103]
I got this error upon attempting to update the rust-analyzer extension today. No idea what is causing the issue, since updating the analyzer in the past has worked without incident.

Here is the verbose traceback of the problem:
`
ERROR [6/1/2021, 2:33:40 PM]: Bootstrap error [Error: Got response 401 when trying to fetch release info for 2021-05-31 release
	at Object.fetchRelease (c:\Users\willi\.vscode\extensions\matklad.rust-analyzer-0.2.621\out\src\main.js:22676:15)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\willi\.vscode\extensions\matklad.rust-analyzer-0.2.621\out\src\main.js:23058:16
	at async downloadWithRetryDialog (c:\Users\willi\.vscode\extensions\matklad.rust-analyzer-0.2.621\out\src\main.js:23101:20)
	at async getServer (c:\Users\willi\.vscode\extensions\matklad.rust-analyzer-0.2.621\out\src\main.js:23057:21)
	at async bootstrapServer (c:\Users\willi\.vscode\extensions\matklad.rust-analyzer-0.2.621\out\src\main.js:22963:18)
	at async bootstrap (c:\Users\willi\.vscode\extensions\matklad.rust-analyzer-0.2.621\out\src\main.js:22899:18)
	at async tryActivate (c:\Users\willi\.vscode\extensions\matklad.rust-analyzer-0.2.621\out\src\main.js:22784:24)
	at async activate (c:\Users\willi\.vscode\extensions\matklad.rust-analyzer-0.2.621\out\src\main.js:22775:5)]
`

**Comment by lnicola** [comment]
Sounds like GitHub rate-limiting you for some reason.

**Comment by bill-baggins** [comment]
No; I get the same error with a pop-up that have these options: "update github auth token", "retry download, or "dismiss"

**Comment by bill-baggins** [comment]
Here is another error I found trying to update the analyzer. Indeed, it seems to be a rate-limit issue with GitHub, which is weird since I am not committing this particular Rust project to a remote repository. How do I fix this?

`
ERROR [6/1/2021, 2:59:01 PM]: Error fetching artifact release info {
  requestUrl: 'https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/tags/2021-05-31',
  releaseTag: '2021-05-31',
  response: {
    headers: Headers {
      [Symbol(map)]: [Object: null prototype] {
        server: [ 'GitHub.com' ],
        date: [ 'Tue, 01 Jun 2021 18:59:01 GMT' ],
        'content-type': [ 'application/json; charset=utf-8' ],
        'content-length': [ '80' ],
        'x-github-media-type': [ 'github.v3; format=json' ],
        'x-ratelimit-limit': [ '60' ],
        'x-ratelimit-remaining': [ '55' ],
        'x-ratelimit-reset': [ '1622576614' ],
        'x-ratelimit-used': [ '5' ],
        'x-ratelimit-resource': [ 'core' ],
        'access-control-expose-headers': [
          'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset'
        ],
        'access-control-allow-origin': [ '*' ],
        'strict-transport-security': [ 'max-age=31536000; includeSubdomains; preload' ],
        'x-frame-options': [ 'deny' ],
        'x-content-type-options': [ 'nosniff' ],
        'x-xss-protection': [ '0' ],
        'referrer-policy': [ 'origin-when-cross-origin, strict-origin-when-cross-origin' ],
        'content-security-policy': [ "default-src 'none'" ],
        vary: [ 'Accept-Encoding, Accept, X-Requested-With' ],
        'x-github-request-id': [ 'C3BD:1644:1BBA38A:5C38925:60B68375' ],
        connection: [ 'close' ]
      }
    },
    status: 401,
    body: '{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}'
  }
}
`

**Comment by bill-baggins** [comment]
fixed
