### ISSUE TITLE
"extract struct from enum variant" does not account for generics

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#9109]
```rust
enum En<T> {
    Var { a: T$0 },
}
```

results in:

```rust
struct Var{ pub a: T }

enum En<T> {
    Var(Var),
}
```

(also I'm not sure why the field is `pub`?)

**Comment by flodiebold** [comment]
> (also I'm not sure why the field is pub?)

Enum variant fields are always public.

**Comment by jonas-schievink** [comment]
Don't they inherit the enum's visibility? In this case I'd expect a private field to be enough

**Comment by flodiebold** [comment]
Hm, yeah, technically they do inherit the enum's visibility. And yeah, the effect would be the same...
