### ISSUE TITLE
Files that are included through a mod in a proc macro do not have auto complete

### ISSUE THREAD

**Issue by tmcnitt** [rust-analyzer/rust-analyzer#9115]
There are crates that allow auto-importing through mod all the files in a directory. [see here](https://github.com/dtolnay/automod). Basically it lists all the files and expands to a mod for each one of them. However, the files that are included through the proc macro do not have auto complete or type information in vscode through rust analyzer (checked 6/2 with nightly and stable, with procMacro true). 

To create a minimal example

- Add automod = "1.0" to dependenices. It returns a token stream with a mod for each file in the directory

- Create src/a.rs that exports a type for example
`pub struct Test {
    a: i32,
}
`

- Create src/main.rs -> use the automod macro to include a.rs and b.rs
   `automod::dir!("src");`

- Create src/b.rs -> export a function that takes the struct as a param
`use crate::a::*;
pub fn test_func(instance: Test) -> i32 {
    instance.a
}`

- You will notice that vscode rust analyzer will highlight errors, but will not bring up intellisense for completeing the attribute name a on instance
- In src/main.rs -> remove the automod and instead mod a and b 
- Now b.rs will autocomplete 

I'm assuming that rust analyzer checks the files for mods before it expands the proc macro

**Comment by bjorn3** [comment]
The proc macro expects that the current working directory is equal to the root of the crate. This is not always true even when using rustc. For example cargo will use the workspace root as current working directory for rustc. Rust-analyzer uses whatever the current working directory was when starting the rust-analyzer process I think.

https://github.com/dtolnay/automod/blob/80e3cc7492b7eeaf695456c3d6007c892895355d/src/lib.rs#L118

**Comment by tmcnitt** [comment]
My fault, passing in an absolute path fixed the issue. Thanks

**Comment by lnicola** [comment]
Do we set `CARGO_MANIFEST_DIR` and friends for proc macros?

**Comment by bjorn3** [comment]
I think so, but automod doesn't use it.

**Comment by tmcnitt** [comment]
If CARGO_MANIFEST_DIR was used in the automod proc macro, wouldn't it point to the macros directory and not the code that is calling it?

**Comment by bjorn3** [comment]
`CARGO_MANIFEST_DIR` will point to the crate root of the crate currently compiling. The proc-macro can read it at runtime (`std::env::var()`). If the proc macro would read it during the compilation of itself (`env!()`)  then `CARGO_MANIFEST_DIR` would point to the crate root of the proc macro.

**Comment by tmcnitt** [comment]
I've changed the automod directory code to the following
```
  let runtime_manifest_dir = match std::env::var("CARGO_MANIFEST_DIR") {
        Ok(val) => val,
        Err(err) => {
            return TokenStream::from(syn::Error::new(Span::call_site(), err).to_compile_error());
        }
    };
   let dir = Path::new(&runtime_manifest_dir).join(path);
```
And it correctly includes the files just getting passed in the rel directory, but am still not getting the rust analyzer autocomplete. There is nothing in the output tabs for rust analyzer in vscode. What is the best way to see more info on what rust analyzer is doing?

**Comment by tmcnitt** [comment]
Thanks for the support! I'm a huge fan of rust analyzer
