### ISSUE TITLE
Incorrect highlighting of operator << in expressions

### ISSUE THREAD

**Issue by Prunoideae** [rust-analyzer/rust-analyzer#9122]
![image](https://user-images.githubusercontent.com/24620047/120594384-7188b580-c473-11eb-80f1-a4a7a637e39e.png)

Looks like the highlighting treated `<<` and `>>` as type notation, which can cause weird highlighting issue in code.

**Comment by Veykril** [comment]
This works fine for me, are you still having this problem?

**Comment by Prunoideae** [comment]
quite sorry about this! It looks like there's something changed the syntax highlighting of .rs files, but surely not on rust-analyzer's side, I will close the issue and examine which plugin caused the trouble now.
