### ISSUE TITLE
`cargo install-code` doesn't work

### ISSUE THREAD

**Issue by osa1** [rust-analyzer/rust-analyzer#913]
I tried this command a few months ago and it didn't work. Someone on one of the chat channels showed me another way to install `rust-analyzer` -- IIRC the problem is not with the Rust parts of the project but rather code plugin installation does not work. I tried this again now to try something, and it still doesn't work.

I'm happy to help with debugging if you tell me what to check.

Basically what happens is; code runs, but none of the features are installed/enabled, and I don't see rust-analyzer plugin in the plugins section.

**Comment by h-michael** [comment]
@osa1 
Could you show me console logs when you executed `cargo install-code`?

**Comment by matklad** [comment]
Here’s all the code that runs on install-code:

https://github.com/rust-analyzer/rust-analyzer/blob/592b906604d60a86af74c5dbb3bf40b2ddcf8061/crates/tools/src/main.rs#L30

If it fail silently that could mean that we need better error reporting there

**Comment by kjeremy** [comment]
Do you have a recent version of npm?

**Comment by detrumi** [comment]
It was failing silently for me as well, but started working by installing Node.js 10. It'd probably help to check the node/npm version.

**Comment by osa1** [comment]
I managed to debug this -- it turns out I didn't have the VSCode/bin directory in my `$PATH`, instead I had a script that `exec`d the VSCode executable. I guess the script had a bug in the argument handling and probably didn't pass the arguments to `code`. I now removed the script and added `VSCode/bin` to my `$PATH` and this now works. 

Sorry for the noise.

**Comment by matklad** [comment]
@osa1 I think we can handle this case better nontheless, see https://github.com/rust-analyzer/rust-analyzer/issues/918
