### ISSUE TITLE
Single apostrophe causes crash

### ISSUE THREAD

**Issue by r00ster91** [rust-analyzer/rust-analyzer#9151]
```rs
'
```
If you run the analyzer on this, you will get:
```
[Error - 10:50:07 PM] Request textDocument/formatting failed.
  Message: rustfmt exited with:
                           Status: exit code: 101
                           stdout: 
                           stderr: error[E0762]: unterminated character literal
 --> <stdin>:1:1
  |
1 | '
  | ^


  Code: -32900
```

**Comment by bjorn3** [comment]
That is not a crash. You likely have formatting kn save enabled, so a formatting requestvhas been sent. Because of the syntax error, the formatring request resulted in the error you showed.

**Comment by lnicola** [comment]
Right, that's a `rustfmt` error, and not a crash or even a panic.
