### ISSUE TITLE
Hover sometimes shows both the implementation and signature

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#9158]
![image](https://user-images.githubusercontent.com/308347/120982955-eadd1c80-c781-11eb-927d-6c5e8f1474e7.png)

I'm not sure what's happening here, but I noticed it when having the focus on another window.

**Comment by flodiebold** [comment]
There's also a bug there with the argument impl trait bounds being printed again in the where clauses.

**Comment by Veykril** [comment]
This seems very odd, I don't even know where we would render the implementation of a function at all 🤔

**Comment by Veykril** [comment]
Oooh, this happens when you press control while hovering.

**Comment by flodiebold** [comment]
So is this just a VSCode feature showing the whole thing it would go to?

**Comment by lnicola** [comment]
It's Alt on my system. But nice, I didn't know about that feature. Wasn't there a recent issue about showing the definition on hover?

**Comment by Veykril** [comment]
Yep this seems to be a vscode thing, it's some kind of preview but I'm not sure how it's pulling the data to show, cause for some functions I only see the raw docs being rendered...

**Comment by lnicola** [comment]
CC https://github.com/rust-analyzer/rust-analyzer/issues/7893
