### ISSUE TITLE
Semantic highlighting for different parts of attributes

### ISSUE THREAD

**Issue by yohan-pg** [rust-analyzer/rust-analyzer#9172]
I can't seem to understand how to recolor different parts of attributes using semantic highlighting. I'm not sure if its a bug or if I just understand poorly; in the following image, I would like to recolor the white parts (attribute syntax) and the green parts (types mentioned by the derive) to two different colors:

<img width="123" alt="Screen Shot 2021-06-07 at 3 52 28 PM" src="https://user-images.githubusercontent.com/35943727/121079639-6225a700-c7a8-11eb-8933-533e5ecd7473.png">

I tried a bunch of stuff: `attribute.attribute` affects both together, `type.attribute` doesn't change the types, `punctuation.attribute` only changes the punctuation inside the attribute...

**Comment by Veykril** [comment]
You can see a token's type and modifiers by invoking the `Inspect Editor Tokens and Scopes` command in VSCode.
![image](https://user-images.githubusercontent.com/3757771/121084037-771e2c80-c7e0-11eb-869f-b619bc00ed4a.png)

You can't specifically color the `Clone` token differently than the `#[` and `]` tokens currently as we do not resolve the `Clone` token. All of these are tagged as `attribute.attribute` currently.

**Comment by Veykril** [comment]
Though for `derive` we could technically force the tag of the tokens in there to be of `macro` since you can only reference macros in there I suppose.

**Comment by yohan-pg** [comment]
Thanks a lot. It makes sense that the tokens aren't resolved, although it would be great if it were possible to separate `#[` and `]` from the rest of the tokens!
