### ISSUE TITLE
Multithreaded Indexing/scanning of crates?

### ISSUE THREAD

**Issue by woody77** [rust-analyzer/rust-analyzer#9175]
On large projects (100s or 1000s of crates, total), it can take a while for rust-analyzer to finish indexing (90 seconds for a ~4600 crate project), while only using 1 of my workstations many cores.

As this graph of crates is much wider than it is deep, even if dependencies need to be indexed before a crate can be indexed, this can be substantially reduced by a pool of threads each indexing and providing the results for merging.

**Comment by jonas-schievink** [comment]
This was implemented by https://github.com/rust-analyzer/rust-analyzer/pull/11281
