### ISSUE TITLE
Consider removing TS linting and bundling? 

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#9178]
Historically, we felt quite a bit of pain due to our complicated build process for the VS Code parts. Just today, an `npm update` broke vscode plugin, for example. However, the amount on typed script code we have is laughable, 3400 lines. It seems that, at this scale, npm ecosystem creates more problem than it solves. 

My proposal is to completely remove mandatory formatting (tsfmt), linting (eslint) and bundling (rollup) out of the equation, and implement the whole extension as a *single* `main.ts` file. 

WDYT?

**Comment by bjorn3** [comment]
Is it possible to not bundle, but still keep multiple files?

**Comment by flodiebold** [comment]
I think things like formatting are very good to have, and we certainly want to typecheck the file, right?

Probably we'll rather just move out the extension at some point?

**Comment by flodiebold** [comment]
> an npm update broke vscode plugin

How did it break? Can we prevent such breakage without throwing out the whole bathwater?

**Comment by lnicola** [comment]
Looks like an issue with a more recent `vsce` (the Code extensions packaging tool), which we can't avoid.

**Comment by matklad** [comment]
>Is it possible to not bundle, but still keep multiple files?

It should be possible, but, to be honest, I see "keep the whole extension in a single file" as a benefit in itself. At less than 5k lines, ability to see everything by just folding bodies of functions is useful. 

>I think things like formatting are very good to have, 

I am not entirely sure, given the quality of implementation issues and the amount of code in question. I think I personally am more frustrated by the front-end lints. 


>How did it break?

So I noticed yet another security vuln banner on the repository. I run `npm update` locally and submitted and r+ the PR. When I installed the new extension version, it just didn't start, at which point I just reveted the commit, without investigating further.

**Comment by lnicola** [comment]
I don't see any changes in `vsce 1.89.0`, but it stops bundling the extension source code into the `vsix`, so Code can't load it any more.

**Comment by lnicola** [comment]
Ah, I tracked this down to https://github.com/microsoft/vscode-vsce/issues/576. Our `.vscodeignore` makes `vsce` exclude `main.js`, but I'm still not sure how to fix it.

**Comment by matklad** [comment]
Having considered this, I don't think it makes sense at the moment. I think at some point we'd want to move the VS Code extension to another repo, and augment it with some real integration tests, and, at that point, the tradeoffs will be very different.
