### ISSUE TITLE
After `cargo install-code`, verify that extension is in fact installed

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#918]
There's `code --list-extensions` command which shows a list of installed extensions:

```
λ code --list-extensions 
bbenoist.Nix
emeraldwalk.RunOnSave
geddski.macros
gerane.Theme-Zenburn
joaompinto.asciidoctor-vscode
kaiwood.center-editor-window
lucax88x.codeacejumper
matklad.nix-lsp-vscode
matklad.ra-lsp
matklad.tom-lsp
ritwickdey.LiveServer
selbh.keyboard-scroll
stkb.rewrap
streetsidesoftware.code-spell-checker
streetsidesoftware.code-spell-checker-russian
vadimcn.vscode-lldb
```

We should use it as a last step of cargo-install to verify that everything works. Specifically, we should check that `ra-lsp` is present in the output. 

The relevant code is here:

https://github.com/rust-analyzer/rust-analyzer/blob/592b906604d60a86af74c5dbb3bf40b2ddcf8061/crates/tools/src/main.rs#L30

**Comment by c410-f3r** [comment]
This seems straightforward so I will give it a try.
