### ISSUE TITLE
Regression: `log::error` detected as namespace inside use statement instead of as a macro

### ISSUE THREAD

**Issue by CleanCut** [rust-analyzer/rust-analyzer#9189]
```toml
# in Cargo.toml dependencies
log = "0.4"
```

```rust
// in main.rs
use log::error;
```

After my stable vscode updated rust-analyzer today (stable channel) `error` in `use log::error;` is erroneously detected as a namespace, whereas it was correctly detected as a macro before. My settings style macros in green italics, but in the screenshot below you can see it is both styled as a namespace (aka module) and the inspector shows that it is being reported as a namespace. I tried switching to the nightly rust-analyzer channel and the problem persists.

At the callsite, the actual `error!(...)` call is correctly detected as a macro.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/5838512/121295179-d5fca800-c8ab-11eb-9a75-c8d2ed921bce.png">

**Comment by CleanCut** [comment]
It looks like rust-analyzer things that `log::error` is `std::error`

<img width="519" alt="image" src="https://user-images.githubusercontent.com/5838512/121295665-ad28e280-c8ac-11eb-8646-6c666b99f3b1.png">

**Comment by Veykril** [comment]
Mmh I can't seem to reproduce this, even with having `std::error` in scope 
![Uploading image.png…]()

**Comment by Veykril** [comment]
Ah okay nvm I can, gotta enable the std feature. Not I actually think we have an issue about this already somewhere let me look...

**Comment by Veykril** [comment]
Yup found it https://github.com/rust-analyzer/rust-analyzer/issues/7903
