### ISSUE TITLE
Outline is not refreshed after vscode extension downloads new rust-analyzer

### ISSUE THREAD

**Issue by rvolgers** [rust-analyzer/rust-analyzer#9199]
When I open an existing workspace in vscode (one with various open files), sometimes the rust-analyzer extension informs me that it needs to download a new version of rust-analyzer. Then after it finishes downloading, I can see syntax highlighting change for the current open file, but the "Outline" window stays blank.

I have to manually close the current open file and re-open it to get the "Outline" window to update.

**Comment by lnicola** [comment]
If you're of VS Code 1.64, the latest versions no longer download anything. The server bundled with the extension.

**Comment by lnicola** [comment]
Closing since this can't really happen any more. @alper if you still have issues, please file a new bug.
