### ISSUE TITLE
Struct add impl assist doesn't indent correctly

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#920]
```rust
fn trans_fn() {
    {
        struct UI128Visitor;

impl UI128Visitor {

}
    }
}
```

**Comment by matklad** [comment]
Yeah, we don't handle reformatting after applying assist. We need to design an API to handle this nicely...

**Comment by matklad** [comment]
Opened https://github.com/rust-analyzer/rust-analyzer/issues/923 for the general problem

**Comment by lnicola** [comment]
Closing as duplicate of #1645 (which is newer, but more complete).
