### ISSUE TITLE
Test WASM build in CI?

### ISSUE THREAD

**Issue by flodiebold** [rust-analyzer/rust-analyzer#9210]
Since it [turns out that just preventing C dependencies is not enough to make sure we build on WASM](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Wasm.20version.20of.20Rust.20Analyzer/near/242327120), maybe we should add `cargo check` of the relevant crates (`ide` and dependencies) for WASM in CI?

**Comment by matklad** [comment]
Might tackle that to https://github.com/matklad/rust-analyzer/blob/546be18e3a91e4844b0dacc76c9f055397b6d89e/.github/workflows/ci.yaml#L64 job.
