### ISSUE TITLE
Don't trigger `self.` smart completion on plain self

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#9211]
![image](https://user-images.githubusercontent.com/1711539/121684061-e5a40880-cac6-11eb-9dd0-e781d4eb154d.png)

I don't think we should be suggesting `self.funcs()` and friends here, it's better to just have `self` at the first position.

**Comment by Veykril** [comment]
This requires server side filtering right? So I guess we first need progress on #7935 here

**Comment by matklad** [comment]
Not necessary -- from the look of its, seems like we using the whole of `self.foo` as (client) fielter text. If we set filter text to just `foo`, then it should work I think

**Comment by Veykril** [comment]
Ah ye okay, I missed the `lookup` field we had for CompletionItems.
