### ISSUE TITLE
Put "Remove unnecessary braces" assist above "Merge imports"

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#9212]
When I have something like

```rust
use std::fs;
use std::process::{Command}<|>;
```

I almost always want to remove the unnecessary braces.

**Comment by matklad** [comment]
One is assist, another fixit for diagnostics. I think the solution is to swap diagnostics before assists here: seems like fixes should always be prioritized:

https://github.com/rust-analyzer/rust-analyzer/blob/447d849c9ecb3d0f7783a56db429ccc526d0d8dc/crates/ide/src/lib.rs#L583
