### ISSUE TITLE
Autocomplete ignores function local types

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#922]
```rust
fn trans_fn() {
    {
        struct UI128Visitor;

       UI128 // no autocomplete suggestion for UI128Visitor
    }
}
```

**Comment by DJMcNab** [comment]
Why was this closed?

**Comment by bjorn3** [comment]
I believe autocompletion doesn't work at all. (at least for me)

**Comment by matklad** [comment]
>I believe autocompletion doesn't work at all. (at least for me)

Common case for this is that `cargo metadata` fails or there's no `rust-src` component in rustup.

**Comment by matklad** [comment]
But yeah, we don't support local items at all yet.

**Comment by flodiebold** [comment]
> Common case for this is that `cargo metadata` fails or there's no `rust-src` component in rustup.

Would be nice if we could surface this to the user somehow...

**Comment by flodiebold** [comment]
I tried using rust-analyzer in `rustc_codegen_cranelift` (where I'm pretty sure the example comes from), and we do provide some completion, though it's quite limited because we can't find any of the rustc dependencies.

**Comment by bjorn3** [comment]
> or there's no rust-src component in rustup.

I have it installed, `rustc_codegen_cranelift` needs it to build a sysroot.

> `rustc_codegen_cranelift` (where I'm pretty sure the example comes from)

Yup, that's correct.

> and we do provide some completion, though it's quite limited because we can't find any of the rustc dependencies.

I didn't get many autocompletions for types of `rustc_codegen_cranelift` itself too.

Note: won't be able to use rust-analyzer till next week. I am stuck at an outdated version of vs code, which isn't supported by it, because my flatpak is too old to install it.

**Comment by matklad** [comment]
> Would be nice if we could surface this to the user somehow...

Fixed i https://github.com/rust-analyzer/rust-analyzer/pull/934/

**Comment by bjorn3** [comment]
> I didn't get many autocompletions for types of rustc_codegen_cranelift itself too.

This was caused by:

```
ERROR [ra_lsp_server::main_loop] loading workspace failed: cargo metadata failed: error during execution of `cargo metadata`: error: failed to parse manifest at `/Users/bjorn/Documents/rustc_codegen_cranelift/Cargo.toml`

Caused by:
  the cargo feature `profile-overrides` requires a nightly version of Cargo, but this is the `stable` channel

```

**Comment by matklad** [comment]
Yeah, we currently pick the toolchain arbitrary. https://github.com/rust-analyzer/rust-analyzer/issues/945 should fix this

**Comment by matklad** [comment]
The workaround is to start `code` from command line, where the toolchain is the right one.

**Comment by flodiebold** [comment]
That would explain why it worked for me -- emacs-lsp starts the server in the project directory already :slightly_smiling_face:

**Comment by bjorn3** [comment]
> #945 should fix this

Forgot about that issue :)
