### ISSUE TITLE
Semantic Highlighting: Tuple field is considered a `number`

### ISSUE THREAD

**Issue by CryZe** [rust-analyzer/rust-analyzer#9220]
![https://i.imgur.com/AsgnyAF.png](https://i.imgur.com/AsgnyAF.png)

When accessing a field, it is usually marked as the semantic token type `property`, but when accessing a field of a tuple, it is not considered a `property` but instead a `number`.

**Comment by lnicola** [comment]
CC https://github.com/rust-analyzer/rust-analyzer/issues/1109

**Comment by Veykril** [comment]
This isn't due to that issue actually, we just didn't highlight tuple field accesses properly.
