### ISSUE TITLE
rust-lang/rust: core::num imports in libstd are unresolved

### ISSUE THREAD

**Issue by lf-** [rust-analyzer/rust-analyzer#9226]
When I open `library/std/src/num.rs`, even with a cherry picked https://github.com/rust-lang/rust/pull/86243, the imports of `core::num::Wrapping` and others are unresolved.

RA version: #9047 merged onto 660a89620

Logs: unsure how to get good logs of project model, the ones I have don't say enough with `project_model=debug` in `RA_LOG`.

Config:
```json
{
    "rust-analyzer.checkOnSave.overrideCommand": [
        "./x.py",
        "check",
        "--json-output"
    ],
    "rust-analyzer.rustfmt.overrideCommand": [
      "./build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt"
    ],
    "rust-analyzer.cargo.runBuildScripts": false,
    "rust-analyzer.procMacro.enable": false
}
```

**Comment by lf-** [comment]
cc #8915

**Comment by flodiebold** [comment]
Probably same as #9203.
