### ISSUE TITLE
Is there a way to auto complete when inputting function parameters?

### ISSUE THREAD

**Issue by FH0** [rust-analyzer/rust-analyzer#9228]
Maybe my description is not accurate enough. So I prepared pictures.
![录制_2021_06_12_20_21_53_488](https://user-images.githubusercontent.com/32861476/121775821-5ed15780-cbbc-11eb-9b58-389267c5faa2.gif)
I need to press ESC twice to trigger auto completion.

**Comment by bjorn3** [comment]
ctrl+space also triggers the autocomplete menu. In this case I think it is VSCode that decides to not request autocompletions. Language servers can't trigger autocompletion themself AFAIK.

**Comment by FH0** [comment]
I tried ctrl+space to no avail even pressed ESC twice. Then I tried Go, no problem, it seems that it is not a limitation of VSCode.
![录制_2021_06_12_22_08_48_956](https://user-images.githubusercontent.com/32861476/121778759-f8076a80-cbca-11eb-98f2-1568ddbfb5bf.gif)

**Comment by FH0** [comment]
By the way, if I want to use `tokio::sync::mpsc::channel`, I have to input full path. Is it possible to only input`tokiompscchan` to make it auto complete?

**Comment by bjorn3** [comment]
> By the way, if I want to use tokio::sync::mpsc::channel, I have to input full path. Is it possible to only inputtokiompscchan to make it auto complete?

If you type `channel` rust-analyzer may give you an auto-import autocomplete suggestion. If you use it `use tokio::sync::mpsc::channel;` will be added at the top of your file.

**Comment by FH0** [comment]
OK. Thanks for your tip. If the function parameter auto-completion is no problem in your test, I will re-issue an issue in VSCode.

**Comment by bjorn3** [comment]
I didn't actually test it myself.

**Comment by FH0** [comment]
solved
![image](https://user-images.githubusercontent.com/32861476/121792266-3467b480-cc25-11eb-8681-fd099620838c.png)
