### ISSUE TITLE
Add option to disable hover documentation

### ISSUE THREAD

**Issue by bitboxx** [rust-analyzer/rust-analyzer#9232]
The hover api documentation are often useless as they can be long (while shown on a small hover pop-up window) and [in the way of error / warning messages](https://github.com/rust-analyzer/rust-analyzer/issues/8722) that are more relevant. 

This pop-up window is meant for a short contextual information, rather than a full API documentation.

No doubt some people like this feature, but please add an option to disable the documentation hover. I've tried toggling on/off the Rust Analyzer hover settings, nothing worked.

![image](https://user-images.githubusercontent.com/2608523/121782041-95e54000-cb9f-11eb-8153-1a7ebf8ae66a.png)

**Comment by lf-** [comment]
The diagnostics buried under stuff is a long-standing bug in VSCode, unfortunately :/
https://github.com/microsoft/vscode/issues/73120
