### ISSUE TITLE
After resolving errors in my code, sometimes rust-analyzer will report an import error in the standard library itself

### ISSUE THREAD

**Issue by joshuawarner32** [rust-analyzer/rust-analyzer#9241]
I haven't been able to nail down specific repro steps - but this has happened many times (10-30 maybe) over the last few months (since I started using rust-analyzer), across several different codebases. The constant factor seems to be:

* I'm using visual studio code with the rust-analyzer extension
* I'm writing code that imports HashMap/HashSet (I _think_ this is required for a repro, though not 100% sure)
* I have several errors in my code that I'm working through
* When I finish correcting errors in my code, rust-analyzer will sometimes report a new error in `~/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/collections/hash/map.rs`, line 8

That line is an import for hashbrown:
```
use hashbrown::hash_map as base;
```

I'm not doing anything fancy with my Cargo.toml (afaik), just using the most recent stable rust, a few third party dependencies.

100% of the time though, the problem goes away if (either):
* I click the error so my editor loads map.rs, then I close that file
* I restart rust-analyzer server

Thus, I suspect this has to do with some in-memory state that sometimes becomes incorrect.

Next time I see this issue, is there anything I can do to capture debug information to help resolve the issue? Log files? A command I can send to the rust-analyzer server to get it to dump its internal state to a file? Thanks!

**Comment by joshuawarner32** [comment]
Here's a screenshot of the error after I've clicked on the error in the Problems screen (so my editor loads the map.rs source from the stdlib): <img width="686" alt="スクリーンショット 2021-06-12 19 32 49" src="https://user-images.githubusercontent.com/182686/121793740-1fecd300-cbb7-11eb-9b84-371c49d4ecd6.png">

**Comment by kpreid** [comment]
I'm getting this type of error too. Previously it behaved as described above, but now opening and closing the affected library file does not make the error disappear; only restarting VS Code does. Using Rust 1.54.0, rust-analyzer v0.2.694, on x86_64 macOS.

Another location where this type of error occurs is `.../.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs` line 1694, "missing match arm". (The analysis evidently does not understand `convert::Infallible` making the missing arm unnecessary.)

**Comment by lnicola** [comment]
@kpreid that's fixed in #9801.

**Comment by jonas-schievink** [comment]
This issue in general is fixed by #9801.
