### ISSUE TITLE
Add import option to disable `super::` imports / always requrie `crate`

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#9254]
Our style discourages `super::` and `self::` imports: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/style.md#import-style. Would be cool if we actually supported this!

**Comment by Veykril** [comment]
We already have this, `importPrefix` with `byCrate` will always force paths to start with `crate` or the extern crate name. The default is set to `plain` though.

**Comment by matklad** [comment]
Yeah, I actualy did set this to `crate`, but forgot to close!
