### ISSUE TITLE
Duplicate macro completions

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#9303]
Given 
```rs
#[macro_export]
macro_rules! foo {}
$0
```
We get two `foo` completions instead of one. The problem seems to be that `foo` appears twice in the scope even though it should only be there once.

**Comment by jonas-schievink** [comment]
The macro is available both from the legacy `macro_rules!` scope, as well as in the non-legacy macro scope in the crate root due to the `#[macro_export]`. Seems like we need to make sure to only add it once when looking for completion items.

**Comment by matklad** [comment]
I think IntelliJ has some general infrastructure for deduping completion items relatively late in the process. For us, I think it's better to sick with not producing duplicates in the first place, which indeed might need some special code for macros

**Comment by flodiebold** [comment]
IMO it's legitimate for names to be returned multiple times from a scope, so we should be deduping all names we get from `process_all_names`.

**Comment by jonas-schievink** [comment]
We would have to do this for every single name, since even non-macros can be in scope multiple times. This snippet shows `S` twice in the completion list:

```rust
mod m {
    pub struct S;
}

use m::S;

fn main() {
    use m::S;

    S$0
}
```

**Comment by flodiebold** [comment]
The same thing happens for shadowed local variables.

**Comment by Veykril** [comment]
The shadowed local appearing twice has a FIXME somewhere as well iirc.

**Comment by matklad** [comment]
Naively, I'd expect it to be a contract of `process_all_names` that it doesn't yield shadowed names.

**Comment by flodiebold** [comment]
> Naively, I'd expect it to be a contract of process_all_names that it doesn't yield shadowed names.

Maybe :thinking: It'd have to keep track of all yielded names, which not every consumer might need.

Another interesting question: If we have the same name in different namespaces (module `foo` and local `foo`), do we yield two completions? If not, what do we show?

**Comment by SomeoneToIgnore** [comment]
> If we have the same name in different namespaces (module foo and local foo), do we yield two completions? If not, what do we show? 

For the flyinport proposals, we render the completion label as `name (fully qualified path)` so should have no issues.

If the name is already in scope, it's rendered without the path (it's not a flyimport anymore, so a separate module is responsible for those)

**Comment by flodiebold** [comment]
To be clear, I'm not asking what we do right now, but what we should do 😄 flyimport is a separate thing of course, but if both are in scope, it's arguably the same completion -- it has the same effect when inserted.

**Comment by flodiebold** [comment]
Although, maybe the completions for type items in value context should always append `::` -- it's the only token that can follow if a value is expected, I think? So then you'd have two completions, `foo` and `foo::` :thinking:
