### ISSUE TITLE
Goto Definition for other named types?

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#931]
Goto definition/hover use the following if on an `ast::Name`:
https://github.com/rust-analyzer/rust-analyzer/blob/fd7240837b5fab6b2854bb63aa3b5c7771b4ddc0/crates/ra_ide_api/src/goto_definition.rs#L161-L173

This is a subset of `ast::NameOwners`. Does it make sense to implement this for the rest of the `ast::NameOwners`? We have a similar situation in getting hover's description and docs.

**Comment by matklad** [comment]
I don't think these should necessary be based on AST categories. Ideally, we should produce nave target directly from hir... So, I think it's ok to reactively fix this one we find cases that don't work
