### ISSUE TITLE
Complete `self`, `super` and `crate` where paths are expected

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#9311]
We currently only complete these in use statements. Doing this is simple but we actually seem to already complete unqualified in a lot of spots where they shouldn't be so I'd like to fix that first.

**Comment by jhgg** [comment]
Does this issue consider completing `self` like here:

```rust
impl Foo {
    fn bar(<|>) {
    }
}
```

It'd be cool if this completed `self`, `&self`, `&mut self`, `mut self` and `self: Arc<Self>`

**Comment by Veykril** [comment]
It was mainly concerned with paths. We should complete `self` as the first param at least. I'm unsure about the rest though with their involvement with spaces.

**Comment by flodiebold** [comment]
We have lots of completions with spaces, that should be fine. We just need to take care to correctly set the edit range in e.g. the `&mut s<|>` case.

**Comment by Veykril** [comment]
Right we got full item completions even, I somehow forgot that 👍
