### ISSUE TITLE
Show "workspace loaded" notification once we've loaded workspace

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#935]
We should give visual feedback when we've successfully imported a rust project. 

We should send an `showMessage` notification on LSP layer. See this PR for an example of such notification: https://github.com/rust-analyzer/rust-analyzer/pull/934

Here's the place where we figure that workspace is loaded:

https://github.com/rust-analyzer/rust-analyzer/blob/e7241274ef052fc3081b6dbc2e80266d6703c80c/crates/ra_lsp_server/src/main_loop.rs#L242-L244

Note that this place sends an `InternalFeedback` notification, which we use in tests for synchronization. After this PR, I think we should be able to remove `InternalFeedback` and maybe even `internal_mode` flag altogether. Here's the place in tests which should be switched to just a usual notification: https://github.com/rust-analyzer/rust-analyzer/blob/e7241274ef052fc3081b6dbc2e80266d6703c80c/crates/ra_lsp_server/tests/heavy_tests/main.rs#L34

Additionally, because notifications are annoying, we should have an option in VSCode to disable notification. See this for an example of client option: https://github.com/rust-analyzer/rust-analyzer/blob/e7241274ef052fc3081b6dbc2e80266d6703c80c/editors/code/package.json#L148-L151

Zulip stream for issue discussion: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/rust-analyzer.23935

**Comment by vipentti** [comment]
I can tackle this
