### ISSUE TITLE
Couldn't alter Rust env (RUSTFLAGS) for cargo-clippy invoked from rust-analyzer

### ISSUE THREAD

**Issue by dmilith** [rust-analyzer/rust-analyzer#9354]
To make long story short:

On my workstation I have `RUSTFLAGS="-C link-arg=-fuse-ld=/usr/local/bin/zld -C target-feature=+sse3,+avx,+avx2,+fma"`
It works beautifully until another cargo-check or cargo-clippy runs in my projects… WITHOUT that RUSTFLAGS set. Then, with each and every code change whole codebase gets rebuilt from scratch (which is normal).

I work around this, by disabling rust-analyzer cargo-check feature (`"rust-analyzer.checkOnSave.enable": false`) and use it from another editor extension (RustEnhanced on ST4) where I can specify env with my RUSTFLAGS for cargo-clippy/cargo-check.

Is it possible to tell rust-analyzer to use my desired env configuration somehow?

**Comment by flodiebold** [comment]
If you're using VSCode, you can just add it to `rust-analyzer.server.extraEnv`. Other editors might have different ways of configuring the environment.

**Comment by Veykril** [comment]
Setting `rust-analyzer.server.extraEnv` should fix this.
