### ISSUE TITLE
Build script of `proc_macro_test` deadlocks

### ISSUE THREAD

**Issue by oxalica** [rust-analyzer/rust-analyzer#9360]
It tries to invoke cargo inside cargo, which deadlocks if they share the same `target` directory. I'm using a global `target` directory to share artifacts between different projects.
https://github.com/rust-analyzer/rust-analyzer/blob/1b05dbba39d5a4d46f321dc962df99038cddbf21/crates/proc_macro_test/build.rs#L20-L24

**Comment by bjorn3** [comment]
> I'm using a global target directory to share artifacts between different projects.

Have you tried sccache instead?

**Comment by jonas-schievink** [comment]
> I'm using a global `target` directory to share artifacts between different projects.

Yeah I guess it's expected that that's going to deadlock. We should probably override any Cargo config for sharing target dirs in the build script.

**Comment by oxalica** [comment]
> We should probably override any Cargo config for sharing target dirs in the build script.

There is a option `--target-dir` for `cargo build`. I'm just not sure where to place the `target` directory. I don't want it lying in some nested source tree. What about just `$OUT_DIR/target`? And then we can also remove the copy step.

**Comment by jonas-schievink** [comment]
Yeah, that sounds reasonable!
