### ISSUE TITLE
Autoimport discards formatting of `use` lines

### ISSUE THREAD

**Issue by eminence** [rust-analyzer/rust-analyzer#9361]
Consider a file that looks like this:

```rust
use std::{
    collections::HashMap,
    convert::TryFrom,
    ffi::OsStr,
    fmt::Display,
    fs::File,
    io::{self, BufReader, Write},
};

fn main() {
    let a = Ordering::Less;
}
```

The `Ordering` type in main isn't imported, so RA provides the option to automatically import it.  If you allow rust-analyzer to import `Ordering`, it will rewrite the first line to look like:

```rust
use std::{cmp::Ordering, collections::HashMap, convert::TryFrom, ffi::OsStr, fmt::Display, fs::File, io::{self, BufReader, Write}};
```
Which removes the original formatting.  In this particular case, the original formatting can be restored by running rustfmt, but the fact that RA doesn't respect the original formatting can be annoying when looking at diffs, and is a minor papercut

**Comment by Veykril** [comment]
cc https://github.com/rust-analyzer/rust-analyzer/issues/9013
