### ISSUE TITLE
generated_tests_are_fresh continuously fails

### ISSUE THREAD

**Issue by kjeremy** [rust-analyzer/rust-analyzer#937]
Every time I start out with a clean branch and run `cargo test` `generated_tests_are_fresh` fails and I have to run `cargo gen-tests` which produces new test files that only differ by line endings.

**Comment by vipentti** [comment]
Do you have git core.autocrlf on? On Windows this converts the line endings to crlf, and I guess the tests expect lf.

**Comment by vipentti** [comment]
I believe I solved it by setting core.autocrlf to false for rust-analyzer, so no line-ending conversions should occur.

**Comment by kjeremy** [comment]
I'm surprised that that fixed the test. Thanks.
