### ISSUE TITLE
Computing item visibility is linear

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#9378]
Updated description:

This function is linear:

https://github.com/rust-analyzer/rust-analyzer/blob/7be2d2f008595114e19aad0aa0608ddedfe3edf7/crates/hir_def/src/item_scope.rs#L112-L117

The relevant data structure is this one:

https://github.com/rust-analyzer/rust-analyzer/blob/0e0d77d0a3361ee08cdb08a9060f5aa6160a5741/crates/hir_def/src/item_scope.rs#L31-L61

As you see, we need a liner lookup to figure out if a particuald def is visible in the scope, and whats it visibility. A brute-force would be to add a second set of hashmaps, mapping defs to name, but I am not sure if that's the most elegant solution. 

I wonder though if we fundamentally need this `visibility_of` operation. It's most critical user is `find_path` functionality.

**Comment by matklad** [comment]
>I wonder if we should perhaps separate visible from module and declared visibility concepts?

Ok, turns out we already have declaration visibility, its just that we didn't actually use it in the IDE and instead go in a roundabout way and ask parent module "hey, whats my visibility?". That's being fixed in #9379, but the linear `visibility_of` still feels wrong to me...

**Comment by matklad** [comment]
cc @SomeoneToIgnore, looks like auto-import might be hitting accidently quadratic path. No action item here yet, just something to be aware of.

**Comment by flodiebold** [comment]
Hmm -- IMO the visibility here is a property of the *name*, and it's not linear to look up by name. `visibility_of` is probably just not an API that should exist? (Declaration visibility is different, of course.)

**Comment by matklad** [comment]
Yeah, I also feel like the caller should always be able to supply the name here, but I haven't yet looked at the call-sites closely.

**Comment by matklad** [comment]
closed by https://github.com/rust-analyzer/rust-analyzer/pull/9647
