### ISSUE TITLE
"Failed to lookup BLOCK_EXPR@0..111 in this Semantics"

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#9382]
Occasionally I get panics like this one from the flyimport completions:

```
Panic context:
> 
version: 488c9ef9c 2021-06-21 dev
request: textDocument/completion CompletionParams {
    text_document_position: TextDocumentPositionParams {
        text_document: TextDocumentIdentifier {
            uri: Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/home/jonas/dev/rust-analyzer/crates/hir_expand/src/db.rs",
                query: None,
                fragment: None,
            },
        },
        position: Position {
            line: 373,
            character: 79,
        },
    },
    work_done_progress_params: WorkDoneProgressParams {
        work_done_token: None,
    },
    partial_result_params: PartialResultParams {
        partial_result_token: None,
    },
    context: Some(
        CompletionContext {
            trigger_kind: Invoked,
            trigger_character: None,
        },
    ),
}

thread '<unnamed>' panicked at '

Failed to lookup BLOCK_EXPR@0..111 in this Semantics.
Make sure to use only query nodes, derived from this instance of Semantics.
root node:   MACRO_STMTS@0..111
known nodes: MACRO_STMTS@0..111, CALL_EXPR@0..227, SOURCE_FILE@0..16426

', crates/hir/src/semantics.rs:717:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:435:5
   2: hir::semantics::SemanticsImpl::find_file::{{closure}}
   3: hir::semantics::SemanticsImpl::find_file
   4: hir::semantics::SemanticsImpl::analyze_impl
   5: hir::semantics::SemanticsImpl::scope
   6: ide_db::helpers::import_assets::ImportAssets::search_for
   7: ide_db::helpers::import_assets::ImportAssets::search_for_imports
   8: ide_completion::completions::flyimport::import_on_the_fly
   9: ide_completion::completions
  10: std::panicking::try
  11: ide::Analysis::completions
  12: rust_analyzer::handlers::handle_completion
  13: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Veykril** [comment]
That looks like we are trying to lookup a `mutable` syntax tree in the semantics given the ranges are the same

**Comment by Veykril** [comment]
Just got this as well
```

Failed to lookup STRUCT@1755..3625 in this Semantics.
Make sure to use only query nodes, derived from this instance of Semantics.
root node:   SOURCE_FILE@0..36988
known nodes: SOURCE_FILE@0..5013
```
unfortunately no backtrace(not sure why im not getting any even tho i should)
Looks like its not macro related after all

**Comment by Veykril** [comment]
Good news though, I found a reliable way to trigger this in the ra repo https://github.com/Veykril/rust-analyzer/pull/new/crash-me, triggering quick fix generation by putting the cursor on the `T!` panics here https://github.com/Veykril/rust-analyzer/blob/3f032fde2bcf21ceb8495b60261b16265e4dda8c\crates\ide_completion\src\completions\record.rs#L35

Though this isnt fly-import related so this might be a different issue.

**Comment by matklad** [comment]
@jonas-schievink are you still getting these error? I tried to reproduce and took a quick look at the code, but I don't think I've seen this.

**Comment by jonas-schievink** [comment]
Haven't gotten this in a while, no. But then, I could have easily missed it, since it doesn't really affect IDE functionality much.

**Comment by matklad** [comment]
> since it doesn't really affect IDE functionality much.

That is a broken window! From-source builds should panic in a really noticable way.

**Comment by jonas-schievink** [comment]
Oh I just use `cargo build --release --features jemalloc` and set the server path, so if we have mechanism to show a message on panic they're probably disabled in my builds

**Comment by matklad** [comment]
Heh, I was sure that panics are loud for devs, but apparently that's not the case? 

In https://github.com/rust-analyzer/rust-analyzer/pull/9937, I made from-source builds more panicky. Not sure if that's too intense, or just intense enough to make us fix bugs faster :)

Lets see if this comes back!
