### ISSUE TITLE
Explicitly name all threads

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#9385]
Yhe name is shown in both a debugger and panic messages making it easier to distinguish between threads without having to look at the full backtrace. You can name a thread by using `thread::Builder` instead of `thread::spawn` and then calling `.name()` on the thread builder.

https://doc.rust-lang.org/stable/std/thread/index.html#naming-threads

**Comment by himanshu007-creator** [comment]
Hi i would like to work on this issue, can you guide further what needs to be done?
thanks

**Comment by flodiebold** [comment]
Basically, search the code base for usage of `thread::spawn` or `jod_thread::spawn`, and replace them by calls of `[jod_]thread::Builder::new().name("some useful name").spawn()`. I think it should be possible to come up with some name just based on what the spawned thread does.

**Comment by alexfertel** [comment]
@himanshu007-creator Are you working on this?

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator Are you working on this?

Yes
