### ISSUE TITLE
Weird span for methods generated by proc macros

### ISSUE THREAD

**Issue by nox** [rust-analyzer/rust-analyzer#9387]
https://github.com/nox/proc-macro-fn-span/blob/2ae9a58221628f842a3719e425e3f3dce599c3d2/src/lib.rs#L14-L15

When hovering `.f1()`, rust-analyzer thinks the definition is on `struct`:

<img width="416" alt="Capture d’écran 2021-06-23 à 15 08 32" src="https://user-images.githubusercontent.com/123095/123102001-e2990880-d434-11eb-9627-3449d69cfe0d.png">

When hovering `.f2()`, rust-analyzer thinks the definition is on the indentation spaces on the same line as the `f1` field:

<img width="429" alt="Capture d’écran 2021-06-23 à 15 09 10" src="https://user-images.githubusercontent.com/123095/123102083-fba1b980-d434-11eb-8ef2-a04f89199368.png">

I'm pretty sure I set the spans correctly, as src links generated by rustdoc do point to the fields as expected.

This is on the latest rust-analyzer nightly, with `rust-analyzer.experimental.procAttrMacros` set to `true`.

**Comment by jonas-schievink** [comment]
Since this is a custom derive, this should also happen without `rust-analyzer.experimental.procAttrMacros`

**Comment by nox** [comment]
@jonas-schievink That is correct.

**Comment by nox** [comment]
Is there anyone that could provide guidance to fix this?

**Comment by lnicola** [comment]
Do the spans change if you add another derive (on a different line, maybe)?

**Comment by jonas-schievink** [comment]
> Is there anyone that could provide guidance to fix this?

I would look into `map_token_{down,up}` and the `TokenMap`s we end up creating for these macro invocations. Unfortunately we don't have good debugging infra for this at the moment, so sprinkling `eprintln!` and `dbg!` around is probably the way to go.
