### ISSUE TITLE
rust-analyzer occupied unreasonable memory while developing web project

### ISSUE THREAD

**Issue by halldong** [rust-analyzer/rust-analyzer#9388]
a simple example is to try the demo code by [**actix-web**](https://github.com/actix/actix-web)
rust-analyzer would eat up 95% memory of my machine.
```bash
# rust-analyzer --version
rust-analyzer 3898387f3 2021-06-23 dev
```

Dependencies:
```toml
[dependencies]
actix-web = "3"
```

Code:
```rs
use actix_web::{get, web, App, HttpServer, Responder};

#[get("/{id}/{name}/index.html")]
async fn index(web::Path((id, name)): web::Path<(u32, String)>) -> impl Responder {
    format!("Hello {}! id:{}", name, id)
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new().service(index))
        .bind("127.0.0.1:8080")?
        .run()
        .await
}
```

**Comment by lnicola** [comment]
What platform are you on? If it's Unix-based, can you try running `time rust-analyzer analysis-stats .`  in your project? There's also a memory CLI argument and a custom Code command that shows some memory usage details.

**Comment by halldong** [comment]
Hi Inicola, this is running on ubuntu 20.04.
```bash
# time rust-analyzer analysis-stats
flag is required: `path`

________________________________________________________
Executed in    2.50 millis    fish           external
   usr time  1033.00 micros  322.00 micros  711.00 micros
   sys time  856.00 micros    0.00 micros  856.00 micros

```

**Comment by halldong** [comment]
I reboot the machine and opened this single demo, **rust-analyzer** still eat up **over 70%** memory, which is unacceptable. I cannot do anything else.

**Comment by bjorn3** [comment]
How much exactly is 70%? How much ram does your system have?

**Comment by halldong** [comment]
It's 4G in total and 2190.3m for the single process.

**Comment by bjorn3** [comment]
This is what I get on the actix-web repo:

```
Failed to create perf counter: Operation not permitted (os error 1)
[ERROR project_model::workspace] cyclic deps: actix_http_test(CrateId(48)) -> actix_http(CrateId(34))
[ERROR project_model::workspace] cyclic deps: actix_web(CrateId(67)) -> actix_http(CrateId(34))
[ERROR project_model::workspace] cyclic deps: actix_web(CrateId(67)) -> actix_test(CrateId(61))
[ERROR project_model::workspace] cyclic deps: actix_web_codegen(CrateId(80)) -> actix_test(CrateId(61))
[ERROR project_model::workspace] cyclic deps: actix_web_codegen(CrateId(80)) -> actix_web(CrateId(67))
[ERROR project_model::workspace] cyclic deps: awc(CrateId(109)) -> actix_http(CrateId(34))
[ERROR project_model::workspace] cyclic deps: awc(CrateId(109)) -> actix_http(CrateId(34))
[ERROR project_model::workspace] cyclic deps: awc(CrateId(109)) -> actix_http_test(CrateId(48))
[ERROR project_model::workspace] cyclic deps: awc(CrateId(109)) -> actix_test(CrateId(61))
[ERROR project_model::workspace] cyclic deps: awc(CrateId(109)) -> actix_web(CrateId(67))
Database loaded:     73.27s, 104mb
Failed to create perf counter: Operation not permitted (os error 1)
  crates: 43, mods: 336, decls: 4548, fns: 3105
Item Collection:     25.32s, 467mb
Failed to create perf counter: Operation not permitted (os error 1)
  exprs: 140367, ??ty: 8299 (5%), ?ty: 15510 (11%), !ty: 144                                                         
Inference:           55.49s, 411mb
Total:               80.81s, 879mb
```

Just 879mb in the end, though actually changing code and the like will increase memory usage due to computing extra things.

**Comment by halldong** [comment]
I really hope such low cost (less than 1GB) can be shown in my machine.
However, it still remains over 2GB after several reproduction.

Anything I can do to debug to gain more detail?
like these data, I don't know how to print out.

**Comment by lnicola** [comment]
What do you get if you press F1 and select the "memory usage" command?

**Comment by halldong** [comment]
I am working in Ubuntu server with NeoVim.

**Comment by flodiebold** [comment]
> It's 4G(3792.9) in total and 1279972(named rust-analyzer) + 1328220(named ~/.cargo/bin/rust-analyzer) for two single process respectively.

There shouldn't be two rust-analyzer processes taking significant amounts of memory, unless you've got two VSCode windows open.

**Comment by halldong** [comment]
right. I just opened `src/main.rs` and `Cargo.toml`

**Comment by flodiebold** [comment]
It doesn't really matter which files you open. I would recommend opening the files with the same NVim instance so that you don't get multiple RA processes.

**Comment by halldong** [comment]
well, actually I do open these file in one nvim instance by `nvim -p ...`

**Comment by flodiebold** [comment]
How do you measure memory usage? Also, it's a bit suspicious if the processes are named differently, maybe they are started by different things.

**Comment by halldong** [comment]
These data( above 1279972 and 1328220) were derived from `top` and their unit is byte, thus 1.22GB and 1.26GB respectively.


reference:
```bash
# ps faux | sed -e '1p' -e '/nvim\|rust-analyzer/!d'
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
user       82927  0.8  0.4  97632 17444 pts/4    Sl+  16:09   0:02  |   \_ nvim -p src/main.rs Cargo.toml
user       82936  0.6  1.4 641448 57596 ?        Ssl  16:09   0:02  |       \_ /usr/bin/node --no-warnings -r /home/user/.local/share/nvim/plugged/coc.nvim/bin/check.js /home/user/.local/share/nvim/plugged/coc.nvim/build/index.js
user       82949 16.2 31.8 2156860 1238604 ?     Sl   16:09   0:50  |           \_ rust-analyzer
user       83159  0.3  1.6 132804 66024 ?        S    16:09   0:00  |           |   \_ /home/user/.cargo/bin/rust-analyzer proc-macro
user       82952 16.2 32.2 2192916 1251176 ?     Sl   16:09   0:50  |           \_ /home/user/.cargo/bin/rust-analyzer
user       83143  0.3  1.7 132808 66304 ?        S    16:09   0:00  |               \_ /home/user/.cargo/bin/rust-analyzer proc-macro
user       84934  0.0  0.0   9160   776 pts/5    S+   16:14   0:00      \_ sed -e 1p -e /nvim\|rust-analyzer/!d
```

**Comment by flodiebold** [comment]
Can you look up the working directories of the two rust-analyzer processes, for example with `readlink /proc/82949/cwd`?

**Comment by halldong** [comment]
Yes, it target to my working directory.

```bash
# readlink /proc/82949/cwd
/home/user/learn/rest_api
```

**Comment by flodiebold** [comment]
What about the other one?

**Comment by halldong** [comment]
The other one got the same answer.

```bash
# readlink /proc/82952/cwd
/home/user/learn/rest_api
```

**Comment by flodiebold** [comment]
I'd suggest opening an issue with CoC about the double processes then.

**Comment by halldong** [comment]
Sounds like more clear on this issue, thanks!
