### ISSUE TITLE
rust-analyzer causes whole project to be invalidated… and rebuilt from scratch every code change :/

### ISSUE THREAD

**Issue by dmilith** [rust-analyzer/rust-analyzer#9393]
This is most serious bug I've encountered so far… 

I use `"rust-analyzer.checkOnSave.enable": false,` setting… but rust-analyzer still does own checks, which causes cargo to rebuild the project from scratch every code change. It drives me crazy. Is there any workaround to tell rust-analyzer to just index, scan or whatever but no check/ clippy?

**Comment by bjorn3** [comment]
Do you happen to have `RUSTFLAGS` set by any chance?

**Comment by dmilith** [comment]
I explicitly unset RUSTFLAGS everywhere I could. Restarted editor, and terminal even.

**Comment by lnicola** [comment]
Are you on Linux? What happens if you start Code from a terminal, does it conflict with a `cargo check` ran from the same place?

**Comment by dmilith** [comment]
No, macOS 11.4. Everything works normally from the terminal. The moment I run rust-analyzer via LSP editor plugin it starts "own build" in background. Then every other cargo clippy or cargo check start over…

**Comment by flodiebold** [comment]
rust-analyzer doesn't do any checks on code changes that could invalidate cargo caches if `checkOnSave` is disabled. When you *start* rust-analyzer, or change the project structure, it needs to build the project to get proc macros and generated code. You can disable this by disabling `rust-analyzer.cargo.runBuildScripts`.

**Comment by dmilith** [comment]
I'm on Sublime Text 4. Will try setting runBuildScripts to false as well…

**Comment by dmilith** [comment]
Well. It has to do something… since I see "Blocking waiting for file lock on build directory" when I try to do compilation. Nothing but rust-analyzer is processing something in background.

**Comment by flodiebold** [comment]
Are you sure the way you're setting `rust-analyzer.checkOnSave.enable` is correct?

**Comment by lnicola** [comment]
Are you using sccache?

**Comment by dmilith** [comment]
No sccache. LSP settings look correct.

**Comment by dmilith** [comment]
Does rust-analyzer accepts Cargo.toml settings like those?

```toml
# The release profile, used for `cargo build --release`.
[profile.release]
opt-level = 'z'
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true


# The benchmarking profile, used for `cargo bench` and `cargo test --release`.
[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = true


# The testing profile, used for `cargo test`.
[profile.test]
opt-level = 1
debug = 2
rpath = false
lto = false
debug-assertions = true
codegen-units = 12
incremental = true
overflow-checks = true


# The development (default) profile, used for `cargo build`.
[profile.dev]
opt-level = 0                 # controls the `--opt-level` the compiler builds with.
                              # 0-1 is good for debugging. 2 is well-optimized. Max is 3.
                              # 's' attempts to reduce size, 'z' reduces size even more.
debug = 2                     # (u32 or bool) Include debug information (debug symbols).
                              # Equivalent to `-C debuginfo=2` compiler flag.
debug-assertions = true       # controls whether debug assertions are enabled
                              # (e.g. debug_assert!() and arithmetic overflow checks)
rpath = false                 # controls whether compiler should set loader paths.
                              # If true, passes `-C rpath` flag to the compiler.
lto = false                   # Link Time Optimization usually reduces size of binaries
                              # and static libraries. Increases compilation time.
                              # If true, passes `-C lto` flag to the compiler, and if a
                              # string is specified like 'thin' then `-C lto=thin` will
                              # be passed.
codegen-units = 8             # if > 1 enables parallel code generation which improves
                              # compile times, but prevents some optimizations.
                              # Passes `-C codegen-units`.
panic = 'unwind'              # panic strategy (`-C panic=...`), can also be 'abort'
incremental = false           # whether or not incremental compilation is enabled
overflow-checks = true        # use overflow checks for integer arithmetic.
                              # Passes the `-C overflow-checks=...` flag to the compiler.
```

It's the only thing that comes to my mind… that regular cargo check/clippy accepts those changes, where rust-analyzer use default compiler settings… then invalidation would make sense.

**Comment by flodiebold** [comment]
No, rust-analyzer just runs `cargo check`. rust-analyzer itself doesn't do anything that touches the target directory except run cargo.

Just to make sure, can you try changing a setting that has an immediately observable effect like `rust-analyzer.completion.addCallParenthesis`?

**Comment by dmilith** [comment]
"rust-analyzer.completion.addCallParenthesis": true  => http://s.verknowsys.com/d3cf90c01cc238ccac76b62b3859714c.png 

"rust-analyzer.completion.addCallParenthesis": false => http://s.verknowsys.com/ba36b57494df3596abe6362f8ae5210d.png

So options work. It makes no sense :/

**Comment by dmilith** [comment]
Well, I disabled all other checks… Have disabled checks and build scripts… and clearly it still does some checks: http://s.verknowsys.com/1b2b86aaf35b33d395632e627e338c06.png

**Comment by flodiebold** [comment]
Those are syntax errors from rust-analyzer's own analysis.

**Comment by flodiebold** [comment]
It might help to get a process tree while the target directory is locked, to see what `cargo` process is running and what started it.

**Comment by dmilith** [comment]
it's all clear now. Turned out to be ~/.cargo/ cached artefacts built with overridden RUSTFLAGS. (figured out thanks to `CARGO_LOG=cargo::core::compiler::fingerprint=info …` cargo option).

Caused by: ```err: RUSTFLAGS has changed: previously ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld", "-C", "split-debuginfo=unpacked", "-C", "target-feature=+sse3,+avx,+avx2,+fma"], now []```

All makes sense now - do not touch RUSTFLAGS ever again :) Thanks for help guys! <3

**Comment by dmilith** [comment]
Also found RUSTFLAGS in another package I don't use anymore… So my bad.
