### ISSUE TITLE
Add unicode character snippets

### ISSUE THREAD

**Issue by obsgolem** [rust-analyzer/rust-analyzer#9401]
In Julia it is rather common to use greek letters when e.g. writing mathematical code. Historically this has been difficult in languages due to how hard it is to type letters from outside your keyboard region. Julia makes this simple by providing IDE support. By typing in the latex symbol name for a character and pressing tab, Julia's autocomplete will replace the latex name with the relevant symbol.

One might argue that there is very little demand for this feature because nobody uses unicode symbols for math in Rust. I argue that the primary reason for this is inconvenience rather than some kind of intrinsic problem with those symbols. Evidence for this claim may be found in Julia. Thus, if this is to happen in Rust, tools like rust-analyzer should support it.

This is the list of replacements Julia uses, which should provide a good starting place for the ones to provide in rust-analyzer: https://docs.julialang.org/en/v1/manual/unicode-input/.

**Comment by obsgolem** [comment]
Assuming this is something that there is interest in, I would be willing to attempt to implement this myself.

**Comment by matklad** [comment]
I think it’s better be served by a separate extension for an editor: https://marketplace.visualstudio.com/items?itemName=yellpika.latex-input

While Julia is for scientific computing, Rust is for systems programming, so, while it makes sense that core Julia tooling supports LaTeX-style input, it would be a net negative for Rust.
