### ISSUE TITLE
Recent version of rust analyzer fails to resolve `self` in methods if the type is imported with super::super::Foo

### ISSUE THREAD

**Issue by kdy1** [rust-analyzer/rust-analyzer#9404]
# Context

Recently rust-analyzer stopped working and I tried various things.
I tried
 - Changing version of rust analyzer
 - Changing rust toolchain (with combination of above)
 - Manually installing rust-analyzer via `.vsix`.
 - Specifying path of rust-analyzer to custom folder.

But none of above worked, and I found RA is working for some files.
I diffed it one-by-one and found the issue.

# Project structure

```
/anayzer/
 - mod.rs
 - expr/
   - mod.rs
   - bin.rs

```

# Bug

`Analyzer` is declared by `/analyzer/mod.rs`
`expr/bin.rs` imported `Analyzer` using `super::super::Analyzer`.
`expr/mod.rs` imports `Analyzer` using `crate::analyzer::Analyzer`.

`self` was `&mut {unknown}` in `bin.rs` and as a result many things were broken in it.

# Env

rust-toolchain:
```
nightly-2021-03-25
```

**Comment by kdy1** [comment]
I retried such imports on my dev branch and it seems like a wrong issue.
Sorry for bothering and I'll reopen it if it was correct.

**Comment by kdy1** [comment]
![image](https://user-images.githubusercontent.com/29931815/123398010-08addc80-d5de-11eb-9550-922979c49c4e.png)

I checkout `ra` branch and tested again.


![image](https://user-images.githubusercontent.com/29931815/123398147-2b3ff580-d5de-11eb-9541-99c391887f8e.png)


This issue is valid for `nightly-2021-03-25` in rust-toolchain.

(My dev branch uses another version and this bug had no effect there)

**Comment by lnicola** [comment]
Can you try using a more recent version (possibly from GitHub releases, but `rustup` doesn't lag by more than a week now)?

That one is three months old, which is quite a lot in RA land.

**Comment by kdy1** [comment]
It works, sorry for bothering.

I tried `nightly-2021-06-09` using rust-toolchain
