### ISSUE TITLE
Rust analyzer reports "file not included in module tree" but code compiles

### ISSUE THREAD

**Issue by alanhkarp** [rust-analyzer/rust-analyzer#9410]
VSCode version 1.57.1
rustc version 1.53.0
rust-analyzer version 0.2.646

I get the error in the title for 4 of the many files in one of my 3 projects.  The error appeared after updating VSCode, rustc, and rust-analyzer without making any changes to the code.  The code builds correctly both on the console and in VSCode.

In addition, two of my 3 projects have the error 

> rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /Users/alan/Documents/Eclipse/multicell/userspace/cellagent/Cargo.toml, cargo 1.53.0 (4369396ce 2021-04-27): Failed to run `cargo metadata --manifest-path /Users/alan/Documents/Eclipse/multicell/userspace/cellagent/Cargo.toml` in `/Users/alan/Documents/Eclipse/multicell/userspace/cellagent`: `cargo metadata` exited with an error:

but the error in the title only occurs for one of them.  The ```cargo metadata``` command runs correctly on the console.

**Comment by flodiebold** [comment]
Does the error message continue?
Is the code for your project available somewhere? Are the files which you are getting the errors for included in the crate normally through `mod` statements, or in some other way?
Are you opening each of the three projects in a separate VSCode instance, with the `Cargo.toml` in the opened root folder?

**Comment by alanhkarp** [comment]
I am still getting the error.  The problem occurs in
https://github.com/earthcomputing/CellAgent/tree/userspace-master/userspace/actix_server
.

I open one project from the Mac Launchpad then the others from the menu
File-New Window.  Each project has its own root folder with its own
Cargo.toml.

--------------
Alan Karp

**Comment by alanhkarp** [comment]
The problem went away when I reloaded the rust-analyzer.

--------------
Alan Karp

**Comment by flodiebold** [comment]
Ok, let's close this issue then.

**Comment by wassou93** [comment]
Issue still happens and even after refresh it comes back, aren't there any solution ?
![Screenshot from 2022-10-13 16-20-52](https://user-images.githubusercontent.com/8655283/195637982-77f40029-720c-44db-883a-03c1d8562754.png)

**Comment by archiexxx** [comment]
> 

Why does this happen.

**Comment by Miro-Andrin** [comment]
For anyone having similar issues ending up here like me. I fixed it by deleting the .vscode folder in my project.  For some reason it was referencing a module I had deleted.

**Comment by manaskarekar** [comment]
I'm running into this issue on `NVIM v0.9.0-dev`. I have added `autochdir` to my rc dotfile that changes the `pwd` to the file's that you specify while launching nvim. 

If I launch nvim with a directory instead, then select the file at the netrw screen, it displays that file correctly and the directory seems to change successfully. In this case, telescope pulls the files in to list in the fuzzy finder correctly, but opening any file here on opens a blank file and a message after a few seconds saying `file not included in module tree`.

I don't know if it's a nvim, rust-analyzer, telescope or netrw issue, but searching for this error brings this issue up, so I thought I would mention it.

I will try disabling rust analyzer and try it again to try and isolate it.

**Comment by hvnsweeting** [comment]
I'm running into this issue because I didn't add "mod libname" to `main.rs`,  rust-analyzer reported this on src/libname.rs.

**Comment by tguichaoua** [comment]
I got this error by typo my file with a capital letter `lib.Rs` before rename as `lib.rs`.
I think Windows file system is case-insensitive.
I fix it by removing the file, reload rust-analyzer, then recreate the file.

**Comment by wassou93** [comment]
I have a Rust project where my sources are in ./src/bin/ everytime I create a new rs file I get this error, the only solution I found is to restart lsp using :LspRestart or restart neovim, but it's annoying that I have to restart something everytime I create a new source file.

**Comment by nklsla** [comment]
My issue was that the file was not included anywhere in the project. I solved it by including the file in the cargo-workspace's `lib.rs`-file:
```pub mod <filename>;```

**Comment by Coconop** [comment]
I have this issue when running rust-analyzer from Vim **within a tmux session**.
I thought that it had to do with interactive/non-login shells but I made sure that my `.bashrc` and  `~/.cargo/env` are sourced.
Opening the same file in Vim **outside tmux session** is fine though.

Any idea why ?

**Comment by TomasBen** [comment]
What nklsla said works for me. If you have a "database.rs" file where this error appears, you have to add "pub mod database" at the top of either your lib.rs or main.rs file.

**Comment by Telokis** [comment]
On Windows, I fixed this issue by deleting my VSCode workspace storage located at `C:\Users\Telokis\AppData\Roaming\Code\User\workspaceStorage`.  
To find the proper folder, I sorted by `Last Modified` and removed the most recent one.

**Comment by Moth-Tolias** [comment]
just got this in kate, even though `pub mod foo` was present; restarting fixed the issue.
