### ISSUE TITLE
High memory usage cause

### ISSUE THREAD

**Issue by saurabh-kushwah** [rust-analyzer/rust-analyzer#9411]
I think I found one reason of high memory usage which can be reproduced using nightly version of rust-analyzer.

Steps to reproduce
  1. create an empty rust project( `cargo new myproject` )
  2. remove the main function from `src/main.rs`

After killing the process from system monitor and adding `main` function from other text editor, rust-analyzer works normaly.
I encountered similar situation in rust-analyzer stable version.

System Info
- rustc 1.55.0-nightly (e82b65026 2021-06-20)
- rust-analyzer `3898387f3` 2021-06-21 stable
- NVIM v0.5.0-dev+nightly-292-gca802046b with nvim-lsp
- Fedora release 34 (Thirty Four)
- Linux 5.12.11-300.fc34.x86_64 `#1` SMP Wed Jun 16 15:47:58 UTC 2021 

Please find screenshots below

![memory_usage](https://user-images.githubusercontent.com/72739196/123503995-1ada5a00-d674-11eb-949e-4abfcdb684c5.png)
![memory_usage_graph](https://user-images.githubusercontent.com/72739196/123503986-0d24d480-d674-11eb-9094-125f062b03fe.png)

I looked other issues i.e #5728 but they may have different reason for high memory allocation.

**Comment by matklad** [comment]
That’s fascinating! Have not looked into this yet, perhaps it’s easy to repro, but it’d be good @saurabh-kushwah if you could clarify the steps to reproduce a bit.

1. Which process are you killing? nvim or rust-analyzer?
2. presumably, if you kill rust-analyzer, it is restarted by the editor?
3. When exactly do you see memory usage go up? After removing main or after killing process/restarting?

**Comment by saurabh-kushwah** [comment]
Looking into process more closely it's neovim that's causing it. And for the memory utilization of rust-analyzer it appear to be small.

1. I've to kill nvim process.
2. The process id of rust analyzer is not changing, so probably not restarted by the editor
3. The memory allocation goes up after removing main only.

![memory](https://user-images.githubusercontent.com/72739196/123508515-8bda3b80-d68d-11eb-8b7c-e50093c52367.png)


Probably some issues with nvim-lsp or neovim, feel free to close the issue if not relevent.

**Comment by matklad** [comment]
Let me cc @simrat39 as someone who knows both neovim and rust analyzer, I wonder if they might now what’s going on here.

**Comment by lnicola** [comment]
TBH, I can't reproduce this with `nvim-lsp`.

**Comment by lnicola** [comment]
Though it did hang after saving the file: https://asciinema.org/a/NJ5qsUzylJCKoAMl3smNrENtd.
