### ISSUE TITLE
Bootstrap Server Error when rust-analyzer is not present

### ISSUE THREAD

**Issue by jaudiger** [rust-analyzer/rust-analyzer#9416]
Hi,

I just built a clean Rust development environment without rust-analyzer (it was intended). Since the extension is now able to update automatically the rust-analyzer binary, I would have expected to download it if it was not found. But instead, I got this error (which is a bit confusing since it doesn't really say that the binary has not been found).

```
Cannot activate rust-analyzer: bootstrap error. See the logs in "OUTPUT > Rust Analyzer Client" (should open automatically). To enable verbose logs use { "rust-analyzer.trace.extension": true }
```

```
INFO [6/28/2021, 10:11:51 AM]: Using server binary at /usr/sbin/rust-analyzer
ERROR [6/28/2021, 10:11:51 AM]: Bootstrap error [Error: Failed to execute /usr/sbin/rust-analyzer --version
	at bootstrapServer (/home/vscode/.vscode-server/extensions/matklad.rust-analyzer-0.2.654/out/src/main.js:23320:15)
	at async bootstrap (/home/vscode/.vscode-server/extensions/matklad.rust-analyzer-0.2.654/out/src/main.js:23249:18)
	at async tryActivate (/home/vscode/.vscode-server/extensions/matklad.rust-analyzer-0.2.654/out/src/main.js:23134:24)
	at async activate (/home/vscode/.vscode-server/extensions/matklad.rust-analyzer-0.2.654/out/src/main.js:23125:5)]
```

I was reading the discussion on this PR: https://github.com/rust-analyzer/rust-analyzer/pull/9267. I can understand that it could be cumbersome to provide the binary yet, but at least, could the error message be updated? To better reflect what's really going on here: just /usr/sbin/rust-analyzer has not been found on the system.

**Comment by lnicola** [comment]
The extension uses a [different path](https://rust-analyzer.github.io/manual.html#vs-code) for the language server. If you set a custom path in the settings, you are responsible for keeping that binary up to date.

Also, `/usr/sbin` is usually reserved for "system" utilities (ones you must run as `root`). `/usr/local/bin` is a more appropriate location.

**Comment by jaudiger** [comment]
Well, in this particular case, I didn't override the default value of `rust-analyzer.server.path` which has the value null in my settings.

Agree about the usage of `/usr/sbin`. If the binary is located here, I understand that it'll not be upgraded by the extension since I'm not using it as root user. But maybe I know from where `/usr/sbin` is coming from. `rustup` was installed using the root user.

**Comment by lnicola** [comment]
Din you install `rust-analyzer` using `rustup`?

**Comment by jaudiger** [comment]
To install `rust-analyzer`, I'm using this package of Archlinux: https://archlinux.org/packages/community/x86_64/rust-analyzer/

**Comment by lnicola** [comment]
That package provides `/usr/bin/rust-analyzer` and you'd normally need to set `rust-analyzer.server.path` to point to that. Maybe you had some leftover workspace `settings.json` with the other path set?

The logic is around https://github.com/rust-analyzer/rust-analyzer/blob/a6b0c05/editors/code/src/main.ts#L242.

**Comment by jaudiger** [comment]
Ok, let me have a look. I didn't see it, but maybe I missed something.

Just to go deeper into my development environment, I'm using the feature from Visual Studio Code to mount a clean development environment by building it from a Dockerfile (aka Remote Container: https://code.visualstudio.com/docs/remote/containers).

Yesterday, I created a fresh setup from the Dockerfile, and that's why I was a bit surprised by the error message.

**Comment by lnicola** [comment]
Yeah, that's a lot of moving parts. Since you mention the Arch package, are you using an Arch container? Because RA needs to be installed on the remote system, not the local one.

**Comment by jaudiger** [comment]
Exactly, I derive my container image from the Archlinux Docker image. Ant that's why the packages were installed as root before switching to a non-root user inside the container image.

**Comment by lnicola** [comment]
Maybe you can share your container or a reduced example. I just tried and it works for me, both with the automatic download and with the Arch package:

![image](https://user-images.githubusercontent.com/308347/123751508-7f89f480-d8c0-11eb-84c2-4b496ea29213.png)

**Comment by jaudiger** [comment]
After few investigations, I think I discovered why I was getting this behavior, it seems I had an orphan setting that was synchronized with the VSCode built-in Settings Sync feature.

I'll close this issue. Thanks, @lnicola for your help !
