### ISSUE TITLE
Support i686-pc-windows-msvc target

### ISSUE THREAD

**Issue by wuxianucw** [rust-analyzer/rust-analyzer#9425]
I have to use win32 sometimes so I need an `i686-pc-windows-msvc` version. I have tried to compile it using `RA_TARGET=i686-pc-windows-msvc` and [succeeded](https://github.com/wuxianucw/rust-analyzer/actions/runs/981224119).

**Comment by lnicola** [comment]
I suggest using the `rustup` version instead. There's a `rust-analyzer-preview` component in the `nightly` toolchain. We've recently been keeping it quite up to date (depending on the PR queue length, but it's been less than five days, and the release from yesterday has already landed).

If you're using Code, every once in a while one of our LSP extensions might change and then you'll need to install an older VSIX.

With the world moving to 64-bit platforms and our memory usage not being great, it feels like building these is a bit wasteful.

**Comment by wuxianucw** [comment]
> I suggest using the `rustup` version instead. There's a `rust-analyzer-preview` component in the `nightly` toolchain. We've recently been keeping it quite up to date (depending on the PR queue length, but it's been less than five days, and the release from yesterday has already landed).
> 
> If you're using Code, every once in a while one of our LSP extensions might change and then you'll need to install an older VSIX.
> 
> With the world moving to 64-bit platforms and our memory usage not being great, it feels like building these is a bit wasteful.

OK, I will consider it.
