### ISSUE TITLE
Refactor Comments Support

### ISSUE THREAD

**Issue by TCROC** [rust-analyzer/rust-analyzer#9427]
It would be cool if we could Refactor our type, variable, and method references in our comments the same way we can in Visual Studio and Omnisharp for C#.

Example:

![image](https://user-images.githubusercontent.com/24307049/123812299-fa074400-d8c1-11eb-9a9c-5dbc235d2d4f.png)

![image](https://user-images.githubusercontent.com/24307049/123812431-15724f00-d8c2-11eb-8584-67f2504ee10b.png)

![image](https://user-images.githubusercontent.com/24307049/123812555-2d49d300-d8c2-11eb-9f12-3ac775c27fb0.png)

**Comment by Veykril** [comment]
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/8242
