### ISSUE TITLE
Question: does not-expanding macros can cause program misbehavior?

### ISSUE THREAD

**Issue by bluretrece** [rust-analyzer/rust-analyzer#9430]
I'm currently dealing with a related issue to #8925. After updating `rustc` and `rust-analyzer`, my current project which is based on `pest-parser`, is complaining that the proc macro server crashed. Although my program compiles, it doesn't returns the expected output. I wonder if this `rust-analyzer` bug might be causing this misbehavior?

**Comment by jonas-schievink** [comment]
rust-analyzer does not perform any disk writes, we call Cargo to build procedural macros, so what you're seeing is probably unrelated (unless there's some incremental compilation issue in rustc)

**Comment by flodiebold** [comment]
Since the question is answered, I think we can close this.
