### ISSUE TITLE
Files not included due to `cfg` directives are treated as error

### ISSUE THREAD

**Issue by saveriomiroddi** [rust-analyzer/rust-analyzer#9438]
I'm conditionally excluding one file from build, using a `cfg` directive:

```rs
#[cfg(target_os = "windows")]
mod mymodule;
```

I'm on Linux, and this causes an error on that file (`mymodule.rs`):

```
file not included in module tree rust-analyzer unlinked-file
```

This shouldn't be an error, otherwise, any project working with configuration-specific files will yield errors.

Currently, I couldn't find any way to work this around, due to RA's exclude directories functionality [not working](#7755). The `include!` macro also yields the error.

VSC version: 1.57.1
RA version: 0.2.654

**Comment by bjorn3** [comment]
You would either have to tell rust-analyzer to actually use windows as target instead of the host system. (no idea how to do this) Or rust-analyzer would need to get an option to analyze the same crate multiple times with different configurations.

**Comment by saveriomiroddi** [comment]
> You would either have to tell rust-analyzer to actually use windows as target instead of the host system. 

Yes, this works for that specific case, but, if I understand your comment correctly, it would cause errors on `cfg` attributes with other O/Ss.

**Comment by bjorn3** [comment]
"file not included in module tree rust-analyzer unlinked-file" is not an error, but an hint I believe. In vscode these only show on the first character of the location they apply to as a gentle dashed underline.

> Yes, this works for that specific case, but, if I understand your comment correctly, it would cause errors on cfg attributes set to other O/Ss.

That takes me to the second suggestion of mine.  It may be non-trivial to implement though and will likely slow down rust-analyzer. It is basically the only way to work with multiple configurations at the same time though I think due to the flexibility of rust's cfg system.

**Comment by saveriomiroddi** [comment]
> "file not included in module tree rust-analyzer unlinked-file" is not an error, but an hint I believe. In vscode these only show on the first character of the location they apply to as a gentle dashed underline.

It definitely is different, however, the problem is that it hurts the workflow equally, as it's treated by VSC as an error; primarily it will be included in the `Go to Next Problem...` (F8 key) VSC command, which is something I use very often.

Nothing really breaking, although it continuously triggers an alarm in the head of those use to have warning/error free projects (=me) :grin:

**Comment by flodiebold** [comment]
You can disable the hint with the `rust-analyzer.diagnostics.disabled` setting.

**Comment by saveriomiroddi** [comment]
> You can disable the hint with the `rust-analyzer.diagnostics.disabled` setting.

**AMAZING!** :grin: 

`"rust-analyzer.diagnostics.disabled": ["unlinked-file"]` solves the problem.

I'm personally fine with the above solution - I think it's a workaround, but I'm not complaining, as it does the job (and at least on my projects, the occurrence of inadvert leftover files is highly unlikely).

Issue can be closed on my side :smile: Thanks everybody for the help :pray:

**Comment by jonas-schievink** [comment]
It looks like the diagnostic has been turned from a hint to an error in https://github.com/rust-analyzer/rust-analyzer/pull/9255
