### ISSUE TITLE
Use workspace dir as cwd when starting rust-analyzer

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#945]
Currently, we are starting rust-analyzer with "random" cwd. Specifically, we use the `cwd` of VS Code process itself.

Instead, we should use the workspace working directory, so that we pick the relevant `rustup` overrides, etc. To do this, we should change this line:

https://github.com/rust-analyzer/rust-analyzer/blob/5232099977d07492c1b6d5e6163c70d4f6eb07df/editors/code/src/server.ts#L17

to be worksace dir instead of `.`.

Ideally we should provide config to override `rustup` toolchain and/or rust/cargo specifically, but just using the right cwd should work in majority of the cases.

**Comment by pnkfelix** [comment]
[Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/how.20to.20debug.20rust-analyzer's.20interaction.20with.20VS.20Code/near/160200912) led me to recommend that we also detect if two directories in the workspace have distinct `rustup` overrides, and issue a warning accordingly.

**Comment by LDSpits** [comment]
I would be interested in taking this issue, I don't have a lot of experience with rust though. Is that still fine?

**Comment by matklad** [comment]
That’s totally fine, especially for this issue: I think only typescript part should be modified

**Comment by LDSpits** [comment]
So after some documentation reading I have come to the conclusion that we can use the rootpath for workspacefolders. But I'm unsure how/where to handle the edge cases.
- what do we do if no folder is opened? fallback to ``'.'`` for the ``cwd``? setting the ``cwd`` to undefined seems to "load". but stops the loading of workspaces (no notification for workspace loaded)
- how do we handle a multi-root workspace? can I pass them through the ``cwd``? or do I need to do this some other way?

**Comment by matklad** [comment]
I think significantly better logic than currently would be to use the first folder if it exists, with fallback to `.`.

Long term, the correct behavior is to have a configuration option for this, populate it automatically from a single folder, and show a warning messages if there are zero or more than one folder, and no explicit config is set.
