### ISSUE TITLE
No Proper MSVC Release Binary

### ISSUE THREAD

**Issue by gluax** [rust-analyzer/rust-analyzer#9469]
The binary release for windows-msvc does not include an executable but rather some unknown file type. Can't find any instructions about downloading the windows release to see if this intended. If it is what do you do with this file?
![image](https://user-images.githubusercontent.com/16431709/124341975-40d09480-db75-11eb-96d2-5319e657a28c.png)

**Comment by lnicola** [comment]
Ouch, that's unfortunate. The file is a Windows executable, but is missing the extension. It should work if you rename it.

What editor are you using?

**Comment by gluax** [comment]
Gnu/Emacs

**Comment by lnicola** [comment]
Ah, okay. Try renaming it.

It's not very easy to update the asset name, since some clients can download them automatically.

**Comment by gluax** [comment]
Yup renaming worked fine! Thanks
