### ISSUE TITLE
`replace_qualified_name_with_use` doesn't import fully qualified paths

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#9472]
```rs
use syntax::ast;

ast::make$0;
```
Invoking the assist here gives us something along the lines of:
```rs
use ast::make;
use syntax::ast;
```
What we want instead is
```rs
use syntax::ast::{self, make};
```

The cause for this is that this assist doesn't emit a full path for import insertion, it merely asks to insert a use statement for `ast::make` so the merging logic doesn't run, instead we should make it emit `syntax::ast::make` so that merging can happen.

**Comment by matklad** [comment]
While we are at it, it makes sense to fix this assist to *not* fire for associated functions. I guess, we should, require that the imported thing resolves before offering the assist.
