### ISSUE TITLE
Record coercions and auto(de)ref in type inference

### ISSUE THREAD

**Issue by Veykril** [rust-analyzer/rust-analyzer#9475]
We should start recording adjustments (for coercions and self parameter autoref / deref) in type inference sooner rather than later so we can handle these cases more correctly!

_Originally posted by @flodiebold in https://github.com/rust-analyzer/rust-analyzer/issues/9468#issuecomment-873440603_

Status: Mostly done, except for recording method receiver coercions.

cc ~~https://github.com/rust-analyzer/rust-analyzer/issues/6107~~, https://github.com/rust-analyzer/rust-analyzer/issues/2677 ~~#9468~~

**Comment by flodiebold** [comment]
[Here's](https://github.com/rust-lang/rust/blob/96859dbaf6229f131fbd427a32aaa95d4f9cb132/compiler/rustc_middle/src/ty/adjustment.rs#L81-L104) rustc's `Adjustment`, we pretty much want the same thing.
We probably want to have a map from `ExprId` to `Vec<Adjustment>` in our `InferenceResult`. We already have `pat_adjustments`, which should also be changed to use `Adjustment`.
For coercion, we should return the list of adjustments from `coerce` like [rustc does](https://github.com/rust-lang/rust/blob/96859dbaf6229f131fbd427a32aaa95d4f9cb132/compiler/rustc_typeck/src/check/coercion.rs#L84).
Our coercion code is pretty much a copied and simplified version of rustc's (except for some name changes where I felt the rustc names were outdated), so we should be able to copy from that for the adjustments as well. 

We should also record adjustments for autoderef and autoref happening on method call receivers.

**Comment by flodiebold** [comment]
We do record method receiver coercions as well now.
