### ISSUE TITLE
IntoIterator on Arrays

### ISSUE THREAD

**Issue by WCarrollSTO** [rust-analyzer/rust-analyzer#9509]
When utilizing `IntoIterator` for arrays (released in Rust-1.53.0), I am getting an error from Rust-Analyzer for the function below: 
<code>`[std::string::String; 3]` is not an iterator</code>

However, when you run the following code, it compiles and properly prints `alloc::string::String` (no borrows) thrice:
```rust
fn test() {
    let foo = ["0".to_owned(), "1".to_owned(), "2".to_owned()];
    for bar in foo {
        print_type_of(bar)
    }
}

fn print_type_of<T>(_: T) {
    println!("{}", std::any::type_name::<T>())
}
```

As expected, you are unable to use the array afterwords, as ownership was taken by the loop.

**Comment by flodiebold** [comment]
The error "[std::string::String; 3] is not an iterator" does not come from rust-analyzer's own analysis, but from rustc. Are you sure your project is using the current rustc version and doesn't have any toolchain overrides?

**Comment by WCarrollSTO** [comment]
I apologize!  I had updated rustc for my terminal in VSCode (WSL), but rust-analyzer was using the system one.  Thank you for the swift reply!
