### ISSUE TITLE
Request: show more documentation information on closure parameters

### ISSUE THREAD

**Issue by jkelleyrtp** [rust-analyzer/rust-analyzer#9515]
Just ran across this - it might be built in or it might not.

When hovering over a type in a closure, I expect to see full documentation, but only get the "Go to XYZ" hint:
<img width="328" alt="Screen Shot 2021-07-06 at 10 08 36 PM" src="https://user-images.githubusercontent.com/10237910/124689561-b6ef3700-dea6-11eb-97d3-1f7c1ac79d4d.png">

I would expect more full documentation, IE when hovering over an explicit type:

<img width="587" alt="Screen Shot 2021-07-06 at 10 09 29 PM" src="https://user-images.githubusercontent.com/10237910/124689626-d71ef600-dea6-11eb-860d-f73ea2c696c8.png">

I'd be happy to contribute but would need to know where to start.

**Comment by Veykril** [comment]
These are just locals like the ones introduced by `let`. Showing the documentation fo the type would be a bit odd, as the type doesn't necessarily have to be a documented one, it could be `()` for example. Also what about data types that consist of multiple types, like tuples or generic structures. It seems rather inconsistent if we were to do this.
