### ISSUE TITLE
Lint autocompletion includes redundant qualifier

### ISSUE THREAD

**Issue by crumblingstatue** [rust-analyzer/rust-analyzer#9518]
For example, trying to autocomplete a clippy lint after typing `clippy::` will show results that include `clippy::`
![image](https://user-images.githubusercontent.com/1521976/124794701-94652880-df4f-11eb-9089-8aeb38fddf7a.png)

Which will result in the autocompleted text being `clippy::clippy::autocompleted_name`, which is incorrect because it includes `clippy::` twice.

 rust-analyzer version: e5c1c8cf2 2021-07-05 stable

**Comment by crumblingstatue** [comment]
I'm interested in trying to fix this. Is there a place where I can ask questions casually and get some basic mentoring, or can I do that by just creating a topic for this on the zulip group?

**Comment by lnicola** [comment]
That's what Zulip is for.

**Comment by Veykril** [comment]
also a duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/7144

**Comment by crumblingstatue** [comment]
Closing as duplicate
