### ISSUE TITLE
Fails to resolve methods on `Option<impl Trait>`

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#9530]
```rs
fn make() -> Option<impl Copy> {
    Some(())
}

fn main() {
    make().unwrap();
}
```

Here, the `.unwrap()` stays unresolved, and no completions after `make().` are offered.

**Comment by flodiebold** [comment]
That's weird :thinking:

**Comment by flodiebold** [comment]
It works for me :thinking:

**Comment by lnicola** [comment]
It doesn't work for me (current `master`, `stable`).

**Comment by flodiebold** [comment]
It indeed doesn't work with current master, so this seems to be a regression.
