### ISSUE TITLE
Open .cargo/git/checkouts files as read-only

### ISSUE THREAD

**Issue by kangalioo** [rust-analyzer/rust-analyzer#9531]
When Ctrl-clicking on items from external crates, rust-analyzer opens the cached code file downloaded by Cargo to show the definition. This is very useful, unfortunately sometimes when I need to make a modification to an external crate, I accidentally modify Cargo's cached version instead of the real file. It would be nice if rust-analyzer opened Cargo's cached code files as read-only, so this mistake cannot occur on accident.

**Comment by Veykril** [comment]
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/5847

**Comment by kangalioo** [comment]
Ah thanks. I tried to search for an existing issue but keywords `read-only cargo checkout` didn't show me that one
