### ISSUE TITLE
`async` is not recognised as keyword

### ISSUE THREAD

**Issue by thomhuds** [rust-analyzer/rust-analyzer#954]
`async` is not recognised as a keyword, but instead in the case of async blocks as the name of a struct in a struct literal, and in the case of `async fn` I'm not really sure what happens.
![image](https://user-images.githubusercontent.com/3267222/54051948-f7592000-41da-11e9-9479-c74e00aeb7f3.png)

**Comment by matklad** [comment]
The fix would be to add `async` the set of keywords in `grammar.ron` and than allow `async` modifier here:

https://github.com/rust-analyzer/rust-analyzer/blob/a9d09b7ec0721e9ad305866a57989d1aa9c67ec1/crates/ra_parser/src/grammar/items.rs#L82

**Comment by c410-f3r** [comment]
Will work on this

**Comment by matklad** [comment]
adding keyword to grammar.ron and running `cargo gen-syntax` should do the trick

**Comment by c410-f3r** [comment]
@matklad Thanks
