### ISSUE TITLE
"Replace qualified path with use" can import the item under the wrong name

### ISSUE THREAD

**Issue by jonas-schievink** [rust-analyzer/rust-analyzer#9540]
```rs
fn main() {
    anyhow::anyhow$0!("error");
}
```

Applying the "Replace qualified path with use" assist generates the following:

```rs
use anyhow::format_err;

fn main() {
    anyhow::anyhow!("error");
}
```

which happens because anyhow has a

```rs
pub use anyhow as format_err;
```

...so it makes sense that we figure out that the `anyhow` macro can also be imported via `format_err`, but it clearly is not the expected result

**Comment by jonas-schievink** [comment]
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/9537, it seems

**Comment by flodiebold** [comment]
Hmm, but separately this would also break if you write `anyhow!("error")` and apply the autoimport assist, wouldn't it? Or do we somehow handle it differently there?

**Comment by Veykril** [comment]
nope, that should also break actually...
