### ISSUE TITLE
syntax highlighting of markdown-embedded rust code blocks with multiple tags

### ISSUE THREAD

**Issue by danieleades** [rust-analyzer/rust-analyzer#9547]
Is Rust Analyzer responsible for syntax highlighting of Rust code blocks embedded in Markdown files in vscode?

It would be good to support multiple tags on fenced blocks. for example

````
```rust
// some rust code here
```
````
is correctly highlighted

but

````
```rust,no_run
// some rust code here
```
````

is not highlighted.

These extra tags are useful for things like [this doctest macro](https://docs.rs/doc-comment/0.3.3/doc_comment/macro.doctest.html)

**Comment by bjorn3** [comment]
> Is Rust Analyzer responsible for syntax highlighting of Rust code blocks embedded in Markdown files in vscode?

Not directly, but it does parse the markdown to change eg ```` ``` ```` into ```` ```rust ````.

> It would be good to support multiple tags on fenced blocks.

Indeed

**Comment by danieleades** [comment]
> > Is Rust Analyzer responsible for syntax highlighting of Rust code blocks embedded in Markdown files in vscode?
> 
> Not directly, but it does parse the markdown to change eg `` ``` `` into `` ```rust ``.
> 

in that case, where should I be posting this issue?

**Comment by bjorn3** [comment]
The problem is probably with rust-analyzer. It should turn ```` ```rust,no_run ```` into the ```` ```rust ```` that the editor expects I think.

**Comment by flodiebold** [comment]
I don't think we do anything at all for Markdown *files*. That would probably the responsibility of the Markdown plugin, which I would assume is built-in in VSCode.

**Comment by bjorn3** [comment]
> I don't think we do anything at all for Markdown _files_.

Missed that last part. I though it was a problem with doc comments.

**Comment by bjorn3** [comment]
> On the other hand, they might not want to add special handling for annotations that only become relevant when you're including the file in Rust documentation. Still, maybe they can offer a solution or workaround.

I think it would make sense to ignore the part after the `,` even if the language is not rust.

**Comment by flodiebold** [comment]
I'd suggest reporting an issue for VSCode, since the Markdown support is built-in.
