### ISSUE TITLE
highlight_related doesn't work with field shorthand

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#9559]
![image](https://user-images.githubusercontent.com/1711539/125190847-ece63f80-e247-11eb-9b0d-557a1c833353.png)

The second debug should be hightlighted, but it isn't

**Comment by Veykril** [comment]
cc https://github.com/rust-analyzer/rust-analyzer/issues/7524

**Comment by matklad** [comment]
yyyep, dupe of #7524. But that shouldn't be too hard to fix I think, we have all the relevant infra already!
