### ISSUE TITLE
Add `for` postfix template

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#9561]
We have `if` and  `while` here:

https://github.com/rust-analyzer/rust-analyzer/blob/325140a165e1081432cb758fc4114a3eff0af490/crates/ide_completion/src/completions/postfix.rs#L93-L101

We should extend this to `for` for types which implement `IntoIter`

![image](https://user-images.githubusercontent.com/1711539/125191439-210f2f80-e24b-11eb-9e9b-5658a6c741ed.png)

**Comment by mahdi-frms** [comment]
I'll have a try at this

**Comment by mahdi-frms** [comment]
Looks like I need to get the Trait object for ```IntoIter``` in order to check if the ```reciever``` has implemented that or not, but how?

should I get it from the completion context?

**Comment by matklad** [comment]
See

https://github.com/rust-analyzer/rust-analyzer/blob/325140a165e1081432cb758fc4114a3eff0af490/crates/ide_db/src/helpers.rs#L133-L136

**Comment by mahdi-frms** [comment]
this can be closed I guess
