### ISSUE TITLE
Feature request: goto definition on a pattern match of a tuple struct should go to that field in the struct

### ISSUE THREAD

**Issue by lf-** [rust-analyzer/rust-analyzer#9587]
Example:
```rust
struct S(u32, u32);
           // ^^^

fn main() {
    match S(1, 1) {
        S(_, a$0) => (),
    }
}
```

The particular case where I ran into this in practice was with a destructure `let S(a, b) = s;` and I wanted to go back to the definition of `b` in the struct.

**Comment by flodiebold** [comment]
I don't know about this. The $0 in your example *is* the definition of (the local variable) `a`. VSCode has a fallback where it invokes "find references" if you do "go to definition" on the definition itself, so it's useful that we correctly return the definition here. And as soon as you have something more complicated than a bind pattern (e.g. `S(_, Some(a))`), there's no obvious place that would correspond to the tuple field anymore. Plus, you can just go 5 characters to the left and go to the struct.

**Comment by lf-** [comment]
You're right. In any case, on further reflection, I think my motivation in wanting this is in large part #9586, so this idea isn't really necessary.
