### ISSUE TITLE
impossible to work with substrate

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#9598]
substrate builds wasm in `build.rs`, if there is a pb in code, then it fails to build wasm. rust-analyzer reports this error which caused finally infinite notifications

<img width="529" alt="image" src="https://user-images.githubusercontent.com/33961674/125585915-fc75cea3-d902-4d0b-8d14-f027eca64052.png">

it never ends and keeps disappearing & re-appearing

**Comment by flodiebold** [comment]
This seems to be a duplicate of #9096? Posting the same issue again will not make it be fixed faster.

**Comment by GopherJ** [comment]
@flodiebold I definitely know, but when this issue makes it impossible to work...I need to post it somewhere, sorry for it.
