### ISSUE TITLE
Simple real-time hierarchical profiling/logging

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#961]
It would be fun to gain visibly into what analyzer is doing, on the high level. 

A couple of usecases:

* after every completion, see how much time has it took
* after every file modification, see if the `item_map` is recomputed, and how long did it took

Also, if we watch both events, and item_map is recomputed for completion, we should see item_map *nested* into completion. 

The API should look roughly like this:

```
fn complete(db: &Db, position: Position) -> Completios {
    let _p = profile("code-completion");
    ....
    // records time on drop
}
```

Behind the scene, there should be an ambient thread-local profiler which maintans the stack of in-progress actions. See, for example, the one from Cargo:

https://github.com/rust-lang/cargo/blob/dd761226d944712a363ea515cb294f4e2b6bdbe5/src/cargo/util/profile.rs

The slight complication is that we need to be able to tweak log-level at runtime. I think we can use LSP options for this? For actually showing the event, `eprintln!` seems like a good start. 

Code wise, I think it should look like this:

* add an hprof crate (or, really, find one on crates.io) which maintains the global profiler singleton with output options and a thread-local stack for event tracing
* add `set_profile_filter` method to `AnalysisHost` which allows changing what is logged at runtime
* add dynamic reconfigurability

**Comment by pasa** [comment]
I would like to implement this but I am quite a newbie so it can take a while.

**Comment by pasa** [comment]
Please, have a look at PR.

**Comment by pasa** [comment]
I've added some docs to public methods latter PR.

**Comment by pasa** [comment]
Can be closed I guess
