### ISSUE TITLE
Feature request: Create a new struct for argument position

### ISSUE THREAD

**Issue by scoopr** [rust-analyzer/rust-analyzer#9610]
In code
```rust
struct Foo;
struct FooDesc {
  pub is_gizmo: bool
}
fn create_foo(foo_desc: &FooDesc) -> Foo { Foo{} }

fn baz() {
  let foo = create_foo();
//                     ^- cursor here
}
```
I'd like a code assist along the lines of `Create FooDesc`,
which would transform the line to something like
```rust
fn baz() {
  let foo = create_foo(&FooDesc {
    is_gizmo: ()
  });
}
```
That is, notice that the cursor is in a argument position that is a struct type, propose to generate the struct if the fields are pub or is crate local, notices that it needs to be passed by ref, and fills in the fields.

This particular code pattern is quite prevalent in `wgpu-rs`, and I think this would be quite helpful shortcut, where I could skip steps like checking the struct type name, writing it, fixing up the ref I forgot, then doing the fill struct fields.

**Comment by Veykril** [comment]
I think a completion would be better than an assist here.

**Comment by Afourcat** [comment]
Hi, is someone working on this? I would like to give it a try. I could use any hint on where to start :smile:.
Thank you.

**Comment by Veykril** [comment]
It's all yours.

Regarding instructions:
You want to make this a completion that basically completes an entire struct literal as requested up there. That should probably live as an extra function in https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide_completion/src/completions/record.rs, that is a 
`pub(crate) fn complete_record_literal(acc: &mut Completions, ctx: &CompletionContext) -> Option<()>` function.

Functionalitywise, you want to check the expected type in [CompletionCtx](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide_completion/src/context.rs#L78) for whether it is a a struct or not. If it is we want to show the completion for the struct type. That will require a function to render the struct literal which should go in a new file in this module here https://github.com/rust-analyzer/rust-analyzer/tree/master/crates/ide_completion/src/render, for an example of how rendering is done that way you can probably take a look at the pattern rendering stuff as that already builds struct patterns which shouldn't be too different, https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide_completion/src/render/pattern.rs.

If you got more concrete questions(coming up), feel free to ask here or on the zulip https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer

**Comment by flodiebold** [comment]
We might want to check that all fields are visible from the current scope so we don't suggest this for e.g. `Vec { buf, len }`.

**Comment by Veykril** [comment]
Logic for that can be used/copied from here https://github.com/rust-analyzer/rust-analyzer/blob/09ec0a15fa06b16a9addca2e3bf8e6f30ff027d0/crates/ide_completion/src/render/pattern.rs#L134-L150(On that note we should probably do the `non_exhaustive` check based on what crate we are in)

**Comment by Afourcat** [comment]
Hello,
Thank you for the time you take to help me out on this one.

I came up with this implementation
![RAExample](https://user-images.githubusercontent.com/35599359/128156745-b551a534-cdd5-4a6a-bb8c-80b6b74c2cbc.gif)
is it the behavior that you guys are waiting for ?

Also, I have a few questions:
- Is `Literal${struct.name}` is acceptable as a completion label ?
- The code in my render file is almost identical to [this one](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide_completion/src/render/pattern.rs) should I follow DRY and abstract common things out ?
- I used the `CompletionKind::Snippet` because the pattern renderer was using it. Is it right ?

I wanted to be sure that the behavior was correct before submitting any Pull Request.

Thank you again

**Comment by Veykril** [comment]
This looks great!
Regarding the questions:
- I think having the label read just the type is better(it would be confusing to the user seeing something else there that isnt whats being completed), but instead set the `detail` differently(which you already seem to have so thats fine). So just use the type name as the laben instead.
- You can try abstracting things out of the both files if you want, but its fine to have it be duplicated for now as well. Abstracting things out can be done in a follow up if required.
- Snippet should be fine

**Comment by Veykril** [comment]
Also we probably want the literal to look like `Foo { field: () }` instead of just `Foo { field }`.

**Comment by flodiebold** [comment]
I think the label should be `Foo {...}`, similar to how we use `foo(...)` for calls when we add the parentheses.

**Comment by Afourcat** [comment]
Here it is,
I used the label `Foo {...}`.

And then I added `:` between the snippet cursor and field name.

![RAExample2](https://user-images.githubusercontent.com/35599359/128185680-34088b18-e567-4c92-b08c-588fb4520bda.gif)

Does it seem right to you?

I didn't know if the actual `()` was mandatory, like in `FooDesc { a: (), b: (), c: () }`. Because it's a snippet, and the user would need to delete them before writing the actual value.
Do you want me to add `()` anyway?

Thanks

**Comment by flodiebold** [comment]
Seems good, let's use the actual ellipsis character `…` though :)

We can make the `()` tab stops in the snippet, I think that would be fine.

**Comment by Afourcat** [comment]
The right character, and `()` tab stop :smiley:.

![RAExample3](https://user-images.githubusercontent.com/35599359/128199399-57d4db2a-4c6a-40b2-ad80-cc2f4a81d5b6.gif)

I broke some tests, but I'm not able to tell if they should be broken by my update or not :thinking:, I will investigate furthermore.

**Comment by Veykril** [comment]
If the failing tests are merely failing due to changed completions thats fine and expected. The tests in `ide_completions/src/tests` test all completions at the same time so failure there is to be expected at least.

**Comment by Afourcat** [comment]
Ok, they all are from `ide_completions/src/tests`.
should I fix them thanks to `env UPDATE_EXPECT=1 cargo test`, or should I post my Pull Request as it is ?

**Comment by Veykril** [comment]
Fix the tests up with that and then make a PR, we'll see if some of these tests were wrongfully updated then.

**Comment by scoopr** [comment]
Closing as #9785 has merged, thank you so much for everyone involved!
