### ISSUE TITLE
`assert_eq!(sth, true)` is suggested to be replaced with (literally) `assert!(..)`

### ISSUE THREAD

**Issue by duongdominhchau** [rust-analyzer/rust-analyzer#9612]
Create a new empty binary project and change `src/main.rs` to

```rust
fn main() {
    let a = 1;
    assert_eq!(a == 1, true);
}
```

Then open this project in VSCode, that `assert_eq!` will be suggested to be replaced. When I apply the suggestion, it becomes `assert!(..)`.

https://user-images.githubusercontent.com/56427890/125624445-489a28b9-83c7-44bc-8183-911adf11b63f.mp4

**Comment by flodiebold** [comment]
This seems to be a clippy lint, so the bad suggestion needs to be reported there.
