### ISSUE TITLE
Goto definition on rustdoc [`T::links`] targets T rather than the target item

### ISSUE THREAD

**Issue by lf-** [rust-analyzer/rust-analyzer#9617]
If you goto definition a link that refers to an item on a trait (maybe also structs/impls), it will go to the trait rather than the item. It would be more useful if it went to the specific item, especially on long definitions.

Another bug I found while writing this one up: If you replace `T` with `Self` in this link, goto definition won't work, but rustdoc will generate the links fine.

```rust
trait T {
   // ^ actual target
    /// Does the thing using [`do_part_of_the_thing`](T::do_part_of_the_thing).
                                           // ^- goto definition here
    /// This one also does the same thing [`T::do_part_of_the_thing`]
    fn do_thing();

    fn do_part_of_the_thing();
    // ^^^^^^^^^^^^^^^^^^^^ expected target
}

fn main() {}
```

Version: a2f83c9

**Comment by Veykril** [comment]
I assume the highlighting is also incorrect? I imagine this is us just not handling those links properly yet. Our intra doc link resolution still has some holes. Relevant code, somewhere in here https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/doc_links.rs

**Comment by lf-** [comment]
No idea on the highlighting, my editor isn't set up to use that component.
