### ISSUE TITLE
Add config settings for highlight_related

### ISSUE THREAD

**Issue by UnkwUsr** [rust-analyzer/rust-analyzer#9618]
https://github.com/rust-analyzer/rust-analyzer/blob/a2f83c956e277b23e20ea2f4f0ac8c5034fe2507/crates/ide/src/highlight_related.rs#L48-L52
https://github.com/rust-analyzer/rust-analyzer/blob/a2f83c956e277b23e20ea2f4f0ac8c5034fe2507/crates/ide/src/highlight_related.rs#L23-L27
Just a bool settings:
`highlight_related.references`
`highlight_related.exit_points`
`highlight_related.break_points`
`highlight_related.yield_points`

**Comment by hi-rustin** [comment]
I am working on this.

**Comment by kdelorey** [comment]
I can knock this out.
