### ISSUE TITLE
.ok() postfix snippet is annoying

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#9636]
For me, it always conflicts with `Reslut::ok`, we either need to make it smarter or to remove it altogether. 

Relevant code: https://github.com/rust-analyzer/rust-analyzer/blob/1dc337645adcc6361c3a1705d15b25f634f4da90/crates/ide_completion/src/completions/postfix.rs#L198-L200

**Comment by Veykril** [comment]
What do you mean with smarter?

Honestly I think ideally we would allow the user to define custom postfix snippets, that way we can remove most defaults ones that might be annoying like `ok` and have the user just add them themselves if they wish to have them.(Could even have a list of common ones in the manual for users to copy/paste from).

**Comment by matklad** [comment]
>Honestly I think ideally we would allow the user to define custom postfix snippets

Actually, that doesn't seem that hard, I guess that's the best way to fix this issue!

> What do you mean with smarter?

I have two approaches in mind: 

* don't suggest a snippet when the method with the same name exists (alothough I did essentially the opposite change for `.not()` recently (hm, I guess that change also made `.ok()` more annoying to me as well))
* only suggest `.ok()` when the outre type is a result.

We also should have "wrap in ok" as a quick fix...

**Comment by matklad** [comment]
#9489 -- that's the change I am talking about
