### ISSUE TITLE
Fill struct fields assist

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#964]
Similarly to https://github.com/rust-analyzer/rust-analyzer/issues/626 which fills match arms, we should have a similar feature to fill missing fields of structs:

```rust
struct ModCollector<'a, D> {
    def_collector: D,
    module_id: ModuleId,
    file_id: FileId,
    raw_items: &'a raw::RawItems,
}

fn foo() {
        ModCollector {
               <|>
        }
}
```

the assist here should fill all of the fields. See the implemention of a similar feature for enums here:

https://github.com/rust-analyzer/rust-analyzer/blob/97a87bf3a68338b1acc2b7a02dfa43096bf47e05/crates/ra_assists/src/fill_match_arms.rs

To fix it, you need to 

* add a new file `ra_assists/src/fill_struct_fields.rs`
* write the `pub(crate) fn` with implemetation and testst
* add assist to the list of assists here: https://github.com/rust-analyzer/rust-analyzer/blob/97a87bf3a68338b1acc2b7a02dfa43096bf47e05/crates/ra_assists/src/lib.rs#L88-L112

**Comment by yanchith** [comment]
@csmoe are you intending on implementing this? I guess the answer is yes since you referenced a PR, but I had to ask anyway. Otherwise I would like to attempt to do this as my first rust-analyzer issue.

I am still in the very early stages of reading the docs and trying things out though, so it may take me some days or weeks before I can produce anything.

**Comment by yanchith** [comment]
A couple of questions came up when I played around, trying to implement it.

First, about desired functionality: do we want to guess some kind of values for filled-in fields, or is outputting placeholders or even struct field shorthand form ok?

Would this be good enough, or do we need something more sophisticated for the assist to be useful?

```rust
struct ModCollector<'a, D> {
    def_collector: D,
    module_id: ModuleId,
    file_id: FileId,
    raw_items: &'a raw::RawItems,
}

fn foo() {
    // filled-in struct fields - need to be hand-editted by user
    ModCollector {
        def_collector,
        module_id,
        file_id,
        raw_items,
    }
}
```

Second, `fill_match_arms` uses `match_expr.expr()` to access the type in the inference result:

```rust
let expr = match_expr.expr()?;

// ... a few lines of code later ...

let node_expr = source_map.node_expr(expr)?;
let match_expr_ty = infer_result[node_expr].clone();
```

in [fill_match_arms.rs](https://github.com/rust-analyzer/rust-analyzer/blob/97a87bf3a68338b1acc2b7a02dfa43096bf47e05/crates/ra_assists/src/fill_match_arms.rs#L22)


`.expr()` is implemented for `MatchExpr`, but not for `StructLit`. It seems to be needed to access the inferred type for the struct literal. Do I understand correctly that `.expr()` corresponds to the ast node of the whole expression? Is it safe for `StructLit` to also implement it, or is there something else that should be used to get the `&Expr`? If `StructLit` should implement `.expr()`, we will probably need to update the template `ra_syntax/src/ast/generated.rs.tera` and regenerate the ast definition in `generated.rs`. Some guidance on how to do that would be appreciated 🍵 

Thanks!

**Comment by matklad** [comment]
>outputting placeholders

I think we should start with this option, just using `()` would be fine. It's better than shorthand in that the user wouldn't have to type `:`.

>corresponds to the ast node of the whole expression?

No (but I see how this is confusing, I wonder if ther's a better name...), `.expr` is always a child accessor, so, for match arm, it gets the expression that is matched against. 

`StructLit` is already an expression, you can use `.into` on it to convert it to the `ast::Expr` (the difference between `ast::StructLit` and `ast::Expr` is just the type, so this is an upcasting operation effectively).

**Comment by csmoe** [comment]
@yanchith that's ok, If you like, just take this :)
