### ISSUE TITLE
the `(use some::path)` is missing when auto-imorting

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#9643]
![image](https://user-images.githubusercontent.com/1711539/126322919-f4df0e79-082d-4d9f-b653-e4f8626c6767.png)

I think this should rather say:

```
CargoOpt (use cargo_metadata::CargoOpt)
```

**Comment by matklad** [comment]
cc @mahdi-frms, i believe you looked into something similar some time ago?

**Comment by mahdi-frms** [comment]
yeah it was me; though I had not faced such issue.

**Comment by mahdi-frms** [comment]
wait, this is not an issue, we only implemented this feature for trait items.

**Comment by matklad** [comment]
I think the `(use ...)` should fire for all auto-imports

**Comment by mahdi-frms** [comment]
OK
but the ```(as ...)``` should be only for trait items, right?

**Comment by matklad** [comment]
Yes!

**Comment by mahdi-frms** [comment]
Right, I'll work at it.
