### ISSUE TITLE
RA confused by proc macro with same name as internal module

### ISSUE THREAD

**Issue by nox** [rust-analyzer/rust-analyzer#9650]
Repro repo: https://github.com/nox/proc-macro-glob-import

RA fails to resolve the `use settings::Settings` import in `src/lib.rs`, as long as there is `mod settings {}` in `macros/src/lib.rs`.

**Comment by jonas-schievink** [comment]
Repro:

```rust
//- /lib.rs crate:lib deps:settings,macros
use macros::settings;
use settings::Settings;
//- /settings.rs crate:settings
pub struct Settings;
//- /macros.rs crate:macros
mod settings {}
pub const settings: () = ();
```

It's weird that we're apparently ignoring the visibility of the `settings` module here
