### ISSUE TITLE
Table of Contents broken in User Manual

### ISSUE THREAD

**Issue by ccope** [rust-analyzer/rust-analyzer#9657]
Compare https://rust-analyzer.github.io/manual.html (broken) from rust-analyzer/rust-analyzer.github.io with the [rust-analyzer/rust-analyzer version](https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/manual.adoc) (correct).

I suspect there is an issue with syncing the manual to the https://github.com/rust-analyzer/rust-analyzer.github.io repository? It looks like the correct version uses `===` indentation levels and the incorrect version has `==`.

**Comment by Veykril** [comment]
What exactly do you mean with broken?

**Comment by ccope** [comment]
It seems like all of the first level children in the table got un-indented. `VS Code` is now in the top level but should be indented (same for all the other editors). Same for most of the items under `Features` and `Diagnostics`.

**Comment by Veykril** [comment]
Ah I see ye that seems odd. Huh so the two files are out of sync it seems? https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/manual.adoc vs https://github.com/rust-analyzer/rust-analyzer.github.io/blob/src/manual.adoc
