### ISSUE TITLE
emacs install instructions

### ISSUE THREAD

**Issue by mgattozzi** [rust-analyzer/rust-analyzer#966]
Hi! I'm trying to get this working with emacs as it does look like there's support, but there's no instructions and anything as easy as the vscode install. I'd like to be able to use this since I have a large work code base that's too big for things like rls/racer. Any help on that front would be greatly appreciated, as I'm sure I'm not the only one! 😄

**Comment by matklad** [comment]
have you seen https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/emacs/ra-emacs-lsp.el ? :)

**Comment by flodiebold** [comment]
Well, admittedly there are basically no instructions there :smile: It's quite possible that I am currently the only user of ra-emacs-lsp.el, so it's probably not going to be completely frictionless. But I think the steps would be roughly
 - install ra_lsp_server with cargo
 - install recent version of `emacs-lsp` (and `dash` and `ht`, but I think `emacs-lsp` requires them anyway?), and set that up
 - add `ra-emacs-lsp.el` to load path and require it
 - run `lsp` in a rust buffer, and hopefully it will start rust-analyzer...
 - maybe bind join-lines and extend-selection to keys

**Comment by mgattozzi** [comment]
@matklad I found that, which is why I thought there was emacs support, but the code there doesn't say the instructions, and having it not be in the README in the `/editors` folder was confusing to me. Does that make sense?

**Comment by mgattozzi** [comment]
Also thanks @flodiebold I'll give it a shot!

**Comment by matklad** [comment]
Yeah, docs are a bit of a mess right now: we have a ton of info, but it is scaterred over gazilion of files, and it is not clear which are user docs and which are developer docs. Fixing this is on my TODO list.

**Comment by mgattozzi** [comment]
Got it working! Had to point it at the project root but the linting shows up! 😄 Appreciate all the help!

**Comment by gnzlbg** [comment]
@mgattozzi how good does this work? this might be the path forward for the rust spacemacs layer

**Comment by matklad** [comment]
This now is documented at https://github.com/rust-analyzer/rust-analyzer/tree/master/docs/user#emacs
