### ISSUE TITLE
Code-generating Attribute Macros fail to resolve outputs even with rust-analyzer.experimental.procAttrMacros

### ISSUE THREAD

**Issue by Dessix** [rust-analyzer/rust-analyzer#9679]
The crate [`aliri_braid`](https://lib.rs/crates/aliri_braid) seems to really confuse Rust-Analyzer due to its nature as a macro annotation, but the part that surprises me is that it seems like `rust-analyzer.experimental.procAttrMacros` has no effect on it.

To repro, import [`aliri`](https://lib.rs/crates/aliri) and use this `main.rs`:

```rust
use aliri::jwt::JwtRef;

fn main() {
    let x = JwtRef::from_str("foo");
}
```

Hover over `JwtRef` or `x` and see that it has absolutely no clue what's going on- even when proc macro support is enabled. It just resolves as `{unknown}`, as it can't find the macro-generated types being exported by the crate.

**Comment by lnicola** [comment]
`JwtRef` actually works fine in the `aliri` repo.

**Comment by Dessix** [comment]
I was using it from another project which imported it; I didn't think to try it from within the repo. I can attempt to minimize my repro if it doesn't occur for you in a project which imports it?

**Comment by lnicola** [comment]
No, I see it too. In another crate, `Jwt` appears to work, but I think that's only because there's a `struct Jwt;` in `aliri`, as if we're completely ignoring the proc macro attribute.

**Comment by Dessix** [comment]
Yep, that's the behaviour I observed. Is it possible we're only expanding attribute macros in the current crate?

**Comment by flodiebold** [comment]
rust-analyzer doesn't really have a notion of a current crate, so that seems unlikely.

**Comment by p3s** [comment]
Seems related to #9782

**Comment by jonas-schievink** [comment]
This is working fine for me locally. Do you get a "proc macro not expanded" diagnostic on the `#[braid]` invocation? Restarting r-a should fix that.

![screenshot-2021-08-04-18:12:33](https://user-images.githubusercontent.com/1786438/128216300-c56e67b8-eb12-4dc9-b593-9c7165f3beff.png)

**Comment by lnicola** [comment]
Now I can't reproduce it either, even with the older versions.

I think we a race condition during load, so maybe I was unlucky that one time.

**Comment by Dessix** [comment]
Odd- it worked, recognizing the type on mine for a moment while loading, then started showing the type as unresolved a moment later:
![image](https://user-images.githubusercontent.com/434942/128283394-ad651598-e7b3-491e-97f4-eb813cba8c0a.png)

**Comment by Dessix** [comment]
Now that errors and warnings are persisted after closing files, this leaves a permanent error after ever (purposefully or otherwise) looking at any file that exhibits this issue:

![image](https://user-images.githubusercontent.com/434942/132081050-351833e1-b80b-44fa-ba6f-1edec6e467e5.png)
With the errors being from these lines, as above:
![image](https://user-images.githubusercontent.com/434942/132081089-ce9025a1-51e3-4857-b5f2-00310ce9f7b5.png)

I attempted to reproduce the issue minimally and could not get it to occur reliably, only seeing it once during initial project creation and once while rearranging the project into a virtual workspace- but each time it resolved itself after trying the same again fresh. Is there any sort of trace or additional information I could gather from my large-project repro, being that this seems to be some sort of load-time race condition?

**Comment by lnicola** [comment]
CC https://github.com/rust-analyzer/rust-analyzer/issues/9997

**Comment by Dessix** [comment]
I'm no longer seeing this repro in my larger projects, and small repro scenarios appear to continue not presenting the issue.

The race condition *may* be fixed, or it may simply be reordered into being silent; @lnicola any idea of changes that may have reordered this or if it may actually be full-on resolved after changes to determinism?

**Comment by lnicola** [comment]
@Dessix I don't know. I don't think it's solved, but just less likely to happen. And it didn't show up in the metrics lately:

![image](https://user-images.githubusercontent.com/308347/136506344-ea24ea99-3fd5-4a4e-8f16-0147cb083ede.png)

#9997 has a possible repro, so we can close this issue in favor of it, if you want.

**Comment by Dessix** [comment]
Let's do that. Refer to #9997 for further discussion.
