### ISSUE TITLE
Add an option to show const value on hover in vscode without having to hold CTRL

### ISSUE THREAD

**Issue by IceSentry** [rust-analyzer/rust-analyzer#9682]
Related to #8497 but that particular issue requires evaluating the const. What I would like is to at least show the value of the const if it doesn't require any evaluation. For example, when using a `const WINDOW_WIDTH: usize = 80` it would be nice if hovering on the const in vscode showed the value because sometimes it's possible to use it far from the declaration.

I'd be interested in making a PR with some guidance.

Edit: This feature is already possible if you hold the CTRL key while hovering. A nice feature would be to have an option to make this always on instead of requiring a key press.

**Comment by lnicola** [comment]
I haven't checked if it's possible, but we show the definition of type aliases on hover. Maybe you could use that as a starting point.

**Comment by BlackHoleFox** [comment]
This works for me today if you hold `CTRL` while hovering over the constant usage
![bp63AK9MV3](https://user-images.githubusercontent.com/20936452/139558517-4e20399a-941b-401e-8216-81cb2a4cdfc9.gif)


Latest VSCode Insiders & Windows 10

**Comment by IceSentry** [comment]
Interesting, is there a reason why it's hidden behind holding CTRL?

**Comment by BlackHoleFox** [comment]
No idea if its intentional or not. Personally I like it since it doesn't make the hoverbox too big when I don't need it.

**Comment by lnicola** [comment]
I think that's a Code feature (showing the definition of an item if you hold a modifier).

**Comment by IceSentry** [comment]
I guess having an option for it to be always on would be nice, but this is already a good solution so I'll close this issue.

**Comment by lnicola** [comment]
No, this seems like a legit feature request.

**Comment by IceSentry** [comment]
In that case I'll edit the title and description to reflect that

**Comment by Veykril** [comment]
With #10785 we now show the expression of consts for now.
