### ISSUE TITLE
rust analyzer sometimes would load out of date cache

### ISSUE THREAD

**Issue by dbsxdbsx** [rust-analyzer/rust-analyzer#9707]
With the latest rust analyzer v.0.2.686(ra afterwards) and vscode v1.58.2, I find a bug:

In my module( a folder in ./src with `mod.rs` inside it), I defined a struct named `AgentPG` in file `agentPG.rs` within the module folder（the same folder of file `mod.rs`, then I wrote  `pub mod agentPG` in `mod.rs`;  But still , ra mentioned `"MISSING: command" `  in file `agentPG.rs`, and when I click the yellow light icon on the left side within vscode editor,  it asked whether to add `mod AgentPg` or `pub mod AgentPg`(the letter is not correct). Finally, the `mod.rs` file would be modified like this：
```
pub mod agentPG;//what I added before manually,
mod AgentPg;// what added automatically by ra，
```
It is easy to see that the auto generated struct name is incorrect.

Just one thing need to mention, before I rename file to  `agentPG.rs`, it was indeed renamed as  `agentPg.rs` using ra.  It seems that ra finally loaded old cache---because when I click link of `referece`, it would refers some to `agentPg.rs`, which is deleted . 
(I rename file by pressing `F2` on file on the explorer tree bar within vscode, then vscode ask me if use ra to do rename, I choose yes)

I am not quite sure if it could be reproduced, as I did other renaming thing  over the whole process.  If I reproduce it , I would give more details.

**Comment by Veykril** [comment]
> Just one thing need to mention, before I rename file to agentPG.rs

When did you rename a file? You didn't mention that earlier. Also following your steps I cannot reproduce this at all. Though that is without renaming anything

**Comment by jonas-schievink** [comment]
This might be a VS Code bug, like https://github.com/rust-analyzer/rust-analyzer/issues/9947

**Comment by Veykril** [comment]
Ah ye this is the issue i was looking for, I'm pretty sure this is the same issue.
