### ISSUE TITLE
Postfix suggestions on types

### ISSUE THREAD

**Issue by jeffa5** [rust-analyzer/rust-analyzer#9714]
When writing and updating function signatures, struct field types etc. it can be repetitive to convert, for example, `u32` to `Option<u32>`, or `u32` to `Vec<u32>`.

Would it be possible to have a postfix for these such that:

```rust
fn f(u: u32.opt$0) {}
```

becomes
```rust
fn f(u: Option<u32>$0) {}
```
Similarly there could be a postfix for `vec`, `result` (not sure how to populate the error variant, perhaps use a tabstop?) and probably others but I think it would be better to start small.

**Comment by Veykril** [comment]
Duplicate of https://github.com/rust-analyzer/rust-analyzer/issues/4360

**Comment by jeffa5** [comment]
Ah, thanks!
