### ISSUE TITLE
MINUS token not allowed at the start of patterns in a pattern list

### ISSUE THREAD

**Issue by mchesser** [rust-analyzer/rust-analyzer#972]
The following (valid rust) reports an error in rust-analyzer:

```rust
let x: Option<i8> = None;
match x {
    Some(-1) => (),
    _ => (),
}
```

I believe that this is as simple as adding the `MINUS` token the `PATTERN_FIRST` token set (e.g. https://github.com/mchesser/rust-analyzer/commit/7eefdc49102b3c951f1c9ce2139dd182dc4e7b19) but I'm not familiar with the code base to be sure that this won't break something.

**Comment by matklad** [comment]
@mchesser yeah, that's exactly what needs to be done here. Could you also add this test case to `crates/ra_syntax/tests/data/parser/ok/` and run `cargo gen-tests` to update test data?

**Comment by matklad** [comment]
> but I'm not familiar with the code base to be sure that this won't break something.

Adding to a first set should not break anything, but it might make error recovery less helpful.
