### ISSUE TITLE
'Rustc: command not found' AND 'Path to shell executable "cargo" does not exist.'

### ISSUE THREAD

**Issue by hollycoder** [rust-analyzer/rust-analyzer#9721]
I installed Rust-Analyzer on the latest VSCode copy but I'm getting errors when I try to run a rust file
first, when I right click on the main.rs file and select run, I get this error:
`/bin/sh: rustc: command not found`

When I click on 'Run' in the file itself, I get this error 

> Executing task: cargo run --package guessing_game --bin guessing_game <
The terminal process failed to launch: Path to shell executable "cargo" does not exist.
Terminal will be reused by tasks, press any key to close it.

**Comment by bjorn3** [comment]
Are rustc and cargo in your `PATH`? Have you just installed rust? If so, you may need to logout and login again to ensure that the `PATH` of vscode includes rustc and cargo.

**Comment by hollycoder** [comment]
> Are rustc and cargo in your `PATH`? Have you just installed rust? If so, you may need to logout and login again to ensure that the `PATH` of vscode includes rustc and cargo.

In VSCode terminal window I can run rustc, cargo ..etc with no problems.

**Comment by hollycoder** [comment]
Suddenly it started working after closing the app and opening it again multiple times out of frustration lol

**Comment by askiiart** [comment]
For me this happened because the path was only modified in `~/.bashrc`, whereas VS Code was running it in `/bin/sh`. I was using Code Runner, so enabling "Code-runner: Run In Terminal" fixed this.
