### ISSUE TITLE
LRU caching does not work with  derive macros

### ISSUE THREAD

**Issue by matklad** [rust-analyzer/rust-analyzer#9745]
We use LRU cache for syntax trees:

https://github.com/rust-analyzer/rust-analyzer/blob/a423b307e60809854174105b565497981f5f3680/crates/base_db/src/lib.rs#L51

The idea here is that syntax trees are heavy, and that we'd rather keep a small working set of those, relying on ItemTree data and DefMaps for most stuff. 

There are two sources of syntax trees -- source code files, and files we get as a result of macro expansion. We added LRU when we only had the first kind. 

The problem is though that macros makes LRU mostly useless, as there are a lot of tiny macrcos. in particular, `src/hir/lib.rs` contains 160+ macro calls (each derive is a macro). So, if you type in that file, the LRU cache is fully burnt through on every change and is pure overhead. 

Experimentally, bumbing LRU size to 1024 for `integrated_completion_benchmark` leads to 10% improvement.

**Comment by matklad** [comment]
cc @jonas-schievink -- one more case where many tiny macro files causes problem. 

CrazyIdea №1047: the reason why small macros don't create problems for rustc is that they all are appended to a giant source-map -- there's literally no difference for rustc between many small files and one big file. I wonder if we can restructure our query system such that we have a single `expand_all(FileId)` query, which expands macros recursively into one flat space of tokens. Then, we can base item trees off that.

**Comment by bjorn3** [comment]
Not only that. Rustc doesn't append anything to the source map when expanding macros. It only creates new token trees with spans pointing to the unexpanded source, but with an extra tag indicating which macro invocation expanded it for diagnostics purposes.

**Comment by lnicola** [comment]
It would be nice to be able to get hit/miss statistics from salsa.

**Comment by jonas-schievink** [comment]
> The problem is though that macros makes LRU mostly useless, as there are a lot of tiny macrcos. in particular, `src/hir/lib.rs` contains 160+ macro calls (each derive is a macro). So, if you type in that file, the LRU cache is fully burnt through on every change and is pure overhead.

I am somewhat surprised that all the expansions are invalidated when you type *anywhere* in the file, that kinda seems wrong?

Is there something that's using the expansion's syntax trees but shouldn't? Or is this the same problem as in https://github.com/rust-analyzer/rust-analyzer/issues/8754#issuecomment-835845174, where `Hygiene::new` ends up adding a dependency on the syntax (which means that `crate_def_map` now directly depends on the syntax node)?

**Comment by matklad** [comment]
Good question. The answer is "because we asked it to":

https://github.com/rust-analyzer/rust-analyzer/blob/314e2e75c09cc6115fc35fd94433b146eb3e325a/crates/hir_expand/src/db.rs#L125-L127

that... doesn't seem especially reasonable -- we do want to expanded stuff in memory I think. But I think it might be too heavy?

**Comment by matklad** [comment]
Quick benchmark:

```
Inference:           15.71s, 114ginstr, 511mb
Total:               24.55s, 186ginstr, 850mb
    91mb FileItemTreeQuery
    55mb HygieneFrameQuery
    45mb CrateDefMapQueryQuery

vs

Inference:           15.27s, 109ginstr, 557mb
Total:               24.18s, 181ginstr, 1034mb
   183mb MacroExpandQuery
    91mb FileItemTreeQuery
    54mb HygieneFrameQuery
    45mb CrateDefMapQueryQuery
```

So, yeah, this is substantial, sadly....

**Comment by matklad** [comment]
Hm, curiously even I commet out this line:

https://github.com/rust-analyzer/rust-analyzer/blob/314e2e75c09cc6115fc35fd94433b146eb3e325a/crates/ide_db/src/lib.rs#L109

I still get reparse queries in the completion benchmark

**Comment by matklad** [comment]
This is very painful in https://github.com/near/nearcore/blob/master/core/primitives/src/views.rs, where completion lags. In that file, there's a bunch of structs, which have a whole ton of derives. 

#9841  and https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/memory.20stats show that the sum total of all macro expansions is roughly 1/2 of the orignial source code. So, expansion of all derives should smaller.

So, `183mb MacroExpandQuery` probably tells us that we can optimize that **a lot**.

**Comment by jonas-schievink** [comment]
So, to clarify what's happening here – we shouldn't actually need the syntax tree data itself, right? Just dependency information so salsa can validate dependent queries (well, modulo bugs in https://github.com/rust-analyzer/rust-analyzer/issues/9745#issuecomment-891121887). Does the LRU cache also delete that dependency information?

**Comment by matklad** [comment]
LRU doesn't evict dep info: if it did, it would be impossible to validate queries which depend on LRUed stuff. 

The problem, is, when you type into a file with a ton of derives, if the only thing you have is dep info, you'll need to re-expand derives (this needs re-validation -- not 100% clear on what's our actual dep structure here). Hm, looking at this more, I think I am confused -- we have confusingly named macro_arg_text query which is a firewall. I guess at this point we need to take a closer look. 

But, anyway, long term it does feel reasonable to me to *not* LRU results of macro expansion -- it seems that macro expanded code should just "be there", and that would be useful for things like find references or symbol index. Given that the actual amount of data there seems small, it seems that we can devise some scheme to store expansions in a compact form.

**Comment by lnicola** [comment]
> Hm, looking at this more, I think I am confused -- we have confusingly named macro_arg_text query which is a firewall. I guess at this point we need to take a closer look.

For context: https://github.com/rust-analyzer/rust-analyzer/pull/5497

**Comment by matklad** [comment]
Ok, I understood what's going on here. The behavior we observe is somewhat reasonable. 

We have the following query setup. The `macro_expand` query expands macros. This query is LRUed. This query depends on macro definition and macro argument. The macro argument is firewalled via `zc`. That means that, when the user types into a file, `macro_arg_text` generally stays the same. So, although  `macro_expand` is evicted from LRU, we know that it didn't change, becues `macro_arg_text` is fresh. 

Now let's explain the behavior of `integrated_completion_benchmark`.

First thing to explain is that there are `impl_data_query (60 calls)` calls. That's easy --- there are 60 manually written impls in the file where we are invoking completion, and we need to re-process all impls. Crucially, there are a lot of derive impls, and impl_datas for those are fresh, because corresponding macro_arg_texts are fresh. 

That being said, we still re-expand every one of those derives, but *not* because of the impl data. Rather, that is due to `ChildBySource` and `source_to_def` infra. When we lookup a syntactic fn in the hir, we ask the containing module to build a source map for all child declarations. And that needs source code of every derive and expands the macros.

So, this means that the assumption in this issue is inccorrect -- derives works work with LRU due to `macro_arg_text` firewall. We cold optimize `source_to_def` though -- we know the (macro) file the definition came from, so we don't need to expand *all* macros.
