### ISSUE TITLE
Auto-import not working in module within the same file 

### ISSUE THREAD

**Issue by mahdi-frms** [rust-analyzer/rust-analyzer#9760]
```rust
struct Struct;
fn main() {}

mod mud {

    fn func() {
        let struct_instance = $0
    }
}
```
In this case, ```Struct``` is not suggested in the completions. However, if I move the ```mud``` module to another file, It works.

**Comment by Veykril** [comment]
Interesting to note here is also that for
```rust
mod mud {
    struct Struct;
    fn func() {
        $0
    }
}
```
we do complete the local `Struct`, but *also* the flyimport version which is obviously not required in this case. May or may not be related.
