### ISSUE TITLE
Add `cargo check` env setting

### ISSUE THREAD

**Issue by sploders101** [rust-analyzer/rust-analyzer#9763]
I use rust-analyzer quite a bit and recently started using private git repositories as dependencies with. Everything works fine in the terminal, but when I try to run rust-analyzer, it fails because it cannot authenticate with the git repository. There doesn't appear to be a way to authenticate it without adding an environment variable, but there is only an option to add *arguments* to cargo commands, not environment variables. Can we get an option to add environment variables like `SSH_AUTH_SOCK` to cargo commands so we can use SSH repository dependencies?

**Comment by flodiebold** [comment]
You can just add the environment variables to `rust-analyzer.server.extraEnv`, or to the environment for your editor.

**Comment by sploders101** [comment]
I just realized that I was actually having issues with cargo caching old commits, and it started working when I put the variable in `.profile`. Does `rust-analyzer.server.extraEnv` work for the `cargo check` command? The description seems to indicate it's only for running tasks and debugger launchers.

**Comment by Veykril** [comment]
`rust-analyzer.server.extraEnv` causes the server to be run with those variables, so all cargo commands invoked by the server will inherit them.

**Comment by sploders101** [comment]
Alright, thanks for the clarification!
