### ISSUE TITLE
rust-analyzer reports issues in libcore when I'm working on other projects

### ISSUE THREAD

**Issue by lilyball** [rust-analyzer/rust-analyzer#9766]
When working in other projects, rust-analyzer often sprouts errors in libstd code. The most common is

```json
{
	"resource": "/Users/lily/.rustup/toolchains/1.54.0-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs",
	"owner": "rustc",
	"code": {
		"value": "missing-match-arm",
		"target": {
			"$mid": 1,
			"external": "https://rust-analyzer.github.io/manual.html#missing-match-arm",
			"path": "/manual.html",
			"scheme": "https",
			"authority": "rust-analyzer.github.io",
			"fragment": "missing-match-arm"
		}
	},
	"severity": 8,
	"message": "missing match arm",
	"source": "rust-analyzer",
	"startLineNumber": 1674,
	"startColumn": 15,
	"endLineNumber": 1674,
	"endColumn": 23
}
```

(also a similar one for `option.rs`), though I know there have been others.

Beyond the fact that this error is wrong (see #4896), I also simply shouldn't be getting errors in stdlib code. Or really in any crate imported from a registry. Crates imported via path from within the workspace are fair game of course. I'm unsure about crates imported via path from outside the workspace; on the one hand I could have modified the crate to be unbuildable, but on the other hand it's conceptually simpler to say "rust-analyzer only shows errors originating from within the workspace"; if I am editing the external crate I probably have an editor open for it anyway.

**Comment by abreis** [comment]
I get this error multiple times a day as well.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/95046/128211695-a8f1d11e-27f2-4839-8a11-6c15218770c7.png">

**Comment by eminence** [comment]
With the latest release of RA, this problem is slightly more annoying because there is no way to remove these errant diagnostics, except to restart rust-analyzer.  Previously opening the file from stdlib and then closing the window would have cleared the diagnostic.
