### ISSUE TITLE
unresolved symbols for generated API

### ISSUE THREAD

**Issue by zeenix** [rust-analyzer/rust-analyzer#9774]
For some reason RA is unable to resolve two imported symbols from another module while `cargo check` (and vim+RA as well) says all is good. Both of these symbols are provided[ by a proc macro](https://gitlab.freedesktop.org/dbus/zbus/-/blob/main/zbus/src/fdo.rs#L43). Strange thing is that these symbols are used from other parts of the code too but RA doens't complain about those.

The version of RA in both VS Code and vim are the same: df0936b4a 2021-08-02 stable

![Screenshot of the problem](https://user-images.githubusercontent.com/2027/128063178-4dcc4ea1-3373-42a1-9951-672373f8ec33.png)

**Comment by bjorn3** [comment]
You will need to set `"rust-analyzer.experimental.procAttrMacros": true` in your vscode config. Otherwise proc macro attributes are not expanded.

**Comment by zeenix** [comment]
> You will need to set `"rust-analyzer.experimental.procAttrMacros": true` in your vscode config. Otherwise proc macro attributes are not expanded.

yeah I know. It's enabled. Is it relevant though? Before this attribute was introduced, there was no errors, just that completion won't work for attribute macros. Also, how come the other usage is fine but RA only complains about these two in this one file?

**Comment by p3s** [comment]
Seems related to https://github.com/rust-analyzer/rust-analyzer/issues/9782

**Comment by flodiebold** [comment]
> Before this attribute was introduced, there was no errors, just that completion won't work for attribute macros. 

That's unlikely to be true; the unresolved import diagnostic has existed for almost a year now.

**Comment by zeenix** [comment]
> > Before this attribute was introduced, there was no errors, just that completion won't work for attribute macros.
> 
> That's unlikely to be true; the unresolved import diagnostic has existed for almost a year now.

I guess I misremember then. :shrug:

**Comment by zeenix** [comment]
I reset my VScode settings/extentions etc and now I can't reproduce this issue.
