### ISSUE TITLE
Crate symbols can't be autocompleted from src/bin/___.rs

### ISSUE THREAD

**Issue by nic-hartley** [rust-analyzer/rust-analyzer#9777]
Apologies if this was already reported; I did check but there are so many open issues that it's entirely possible I missed it.

To reproduce:

- Create a new library project
- Define a type in the `lib.rs`, e.g. `FooBarBaz`
- Crate a binary in `src/bin/`
- Try to autocomplete the new type (including with `crate::`)

No autocomplete works for that new type.

For a more complete example:

## src/lib.rs

```rust
pub struct FooBar;
```

## src/bin/demo.rs

```rust
fn main() {
  // put your cursor at the end of Foo and try to tab-complete FooBar
  let x = Foo
}
```

This isn't a huge deal, like the other little holes in autocomplete, but it is the most frustrating one. (The other I've noticed is that types defined in macros only sometimes autocomplete, which I haven't checked if it's been raised, since I haven't figured out why it's only *sometimes*)

**Comment by jonas-schievink** [comment]
> The other I've noticed is that types defined in macros only sometimes autocomplete

This happens for flyimport completions when completing in the same crate that defines the type, because it uses the symbol index for this, which doesn't handle macros (https://github.com/rust-analyzer/rust-analyzer/issues/4842).

**Comment by lnicola** [comment]
Seems fixed now, please reopen if not:

![image](https://user-images.githubusercontent.com/308347/144069018-b626b62c-b08c-4767-a356-4ad48e20270b.png)
