### ISSUE TITLE
pnet macro import statement is showing as unresolved import

### ISSUE THREAD

**Issue by kushaldas** [rust-analyzer/rust-analyzer#9782]
`Cargo.toml` has only one dependency:

```
[dependencies]
pnet = "0.28.0"
```

And here is the `main.rs`

```Rust
use pnet::packet::icmp::echo_request::MutableEchoRequestPacket;
fn main() {
    println!("Hello, world!");
}
```

`rust-analyzer` can not resolve the import statement.

![image](https://user-images.githubusercontent.com/272303/128156221-685a345c-a776-42a0-8c37-7f6afad1969b.png)

`cargo build` works.

**Comment by Veykril** [comment]
This type seems to be created via an attribute, try enabling the `rust-analyzer.experimental.procAttrMacros` setting.

**Comment by p3s** [comment]
Disabling experimental diagnostics `rust-analyzer.diagnostics.enableExperimental` works for me. Enabling `rust-analyzer.experimental.procAttrMacros` does not help in my case.

**Comment by flodiebold** [comment]
> Disabling experimental diagnostics rust-analyzer.diagnostics.enableExperimental works for me

That just hides the diagnostic and doesn't fix the actual problem.

**Comment by kushaldas** [comment]
> This type seems to be created via an attribute, try enabling the `rust-analyzer.experimental.procAttrMacros` setting.

This worked for my vscode. Thank you. I guess not knowing that those are attribute macros (still new in Rust land) caused the trouble for me.
