### ISSUE TITLE
loading workspace failed: cargo metadata failed: invalid type: null, expected a string at line 1 column 236445

### ISSUE THREAD

**Issue by bjorn3** [rust-analyzer/rust-analyzer#979]
```
ERROR [ra_lsp_server::main_loop] loading workspace failed: cargo metadata failed: invalid type: null, expected a string at line 1 column 236445
```

While working on [cranelift](https://github.com/CraneStation/cranelift)

**Comment by matklad** [comment]
That's a, um, well, disagreement between cargo-metadata, cargo, and cargo.

Commenting this line out should help:

https://github.com/CraneStation/cranelift/blob/ccc309fc6686b2ddbc98bd03749b101be5e9ecf2/Cargo.toml#L26

(cranelift-serde is a library-less package, and dependency on such pacakges causes problems)

See https://github.com/rust-lang/cargo/pull/6534

**Comment by matklad** [comment]
(I probably should say that it was my idea to allow `null` in the metadata instead of skipping thouse deps :sob: )

**Comment by bjorn3** [comment]
Thanks that worked

**Comment by matklad** [comment]
I'll close this issue then, since it's Cargo's problem!
