### ISSUE TITLE
proc-macro panicked: called `Rust::unwrap()` on an `Err` value: ParseFloatError

### ISSUE THREAD

**Issue by gleich** [rust-analyzer/rust-analyzer#9795]
Hello rust-analyzer team! First of all, thank you for the work that you do here. I don't wanna waste your time so I'll cut right to the chase. I am getting the error ``proc macro returned error: proc-macro panicked: called `Result::unwrap()` on an `Err` value: ParseFloatError { kind: Invalid }`` on the following code:

```rs
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug)]
pub struct Config {
	pub name: String,
	pub school_level: String,
	pub school_type: String,
}
```

This error is highlighted on the whole struct as well as the attribute. Below is some more information:

Name of the file: `conf.rs`.
File link: [gleich/kiwi/src/conf.rs](https://github.com/gleich/kiwi/blob/main/src/conf.rs)
Repo link: https://github.com/gleich/kiwi
Rust version: rustc 1.54.0 (a178d0322 2021-07-26)
RA version: 950efff5c 2021-08-05 nightly (tried with RA stable)

Because this error is a rust-analyzer problem running `cargo check` or `cargo build` doesn't have this error.

**Comment by f32by** [comment]
Same problem, too.
It works in `nightly-2021-08-04-x86_64-apple-darwin rustc 1.56.0-nightly (a6ece5615 2021-08-03)` but crashes in `nightly-2021-08-05-x86_64-apple-darwin rustc 1.56.0-nightly (25b764849 2021-08-04)`.

**Comment by hex0x0000** [comment]
Same error

**Comment by bjorn3** [comment]
The difference between those rustc version is: https://github.com/rust-lang/rust/compare/a6ece5615...25b764849 This is probably caused by https://github.com/rust-lang/rust/pull/87267 which added a new `Literal::to_string` method to the proc-macro abi.

**Comment by bjorn3** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/9550#issuecomment-878941070: @alexjg would you mind updating the proc-macro abi for nightly?

**Comment by alexjg** [comment]
I'll sort it this weekend

**Comment by alexjg** [comment]
I'm unable to reproduce this problem with the given repository, toolchain and analyzer versions. Furthermore, all the tests for the abi crate pass in current nightly or in the 2021-08-04 toolchain. Does anyone have a reproducing example I can get a look at? I'm reluctant to make a change without being able to check that it fixes the problem.

**Comment by lnicola** [comment]
The test pass, but `rust-analyzer analysis-stats .` on the RA repo crashes.

**Comment by alexjg** [comment]
Ah, that's done the trick, I'll get fixing.
