### ISSUE TITLE
Feature request: show E0425 "cannot find function" suggested name in the popup

### ISSUE THREAD

**Issue by lf-** [rust-analyzer/rust-analyzer#9797]
I wish rust-analyzer would tell me, for instance, in this example, that the suggested name for the function per rustc is `oopsie`. It's true it highlights that function but it's usually in another file when I actually get this. It would make it a lot easier to see if the suggestion is correct if it said what the name is.

![image](https://user-images.githubusercontent.com/6652840/128449198-26e7e411-f41c-48d8-9a9f-9e739b32d846.png)

![image](https://user-images.githubusercontent.com/6652840/128449545-67ca9ad1-9c20-459c-a058-b50c2919fcdc.png)

Text version of that image:

```rust
fn oopsie() {}
// ^^ suggestion here:
// similarly named function `oopsie` defined here
// [rustc: E0425]

fn main() {
    oopsi();
    // ^^ diagnostic here:
    // cannot find function `oopsi` in this scope
    // [rustc: E0425]
    // ——————————————————————————————————————————
    // a function with a similar name exists
    // [rustc: E0425]
    // suggested quickfix is "a function with a similar name exists"
    println!("Hello, world!");
}

```

**Comment by jonas-schievink** [comment]
I think this has to be addressed on the rustc side, the note text just doesn't include the function's name

**Comment by bjorn3** [comment]
It is included as part of the `suggested_replacement`. Rustc renders it as ``^^^^^ help: a function with a similar name exists: `oopsie` ``.
