### ISSUE TITLE
[semantic tokens] unresolvedReference in trait associated type

### ISSUE THREAD

**Issue by jhgg** [rust-analyzer/rust-analyzer#9802]
See this code snippet:

```rust
struct A(<B as C>::D);
                   ^ `unresolvedReference`
struct B;

trait C {
    type D;
}

impl C for B {
    type D = ();
}

```

`D` however does appear in auto-complete `struct A(<B as C>::$0)`. 

rust-analyzer version: 950efff5c 
2021-08-05 nightly

**Comment by lnicola** [comment]
Might be a duplicate of #8282

**Comment by flodiebold** [comment]
Probably. I think both are just an IDE-layer bug.
