### ISSUE TITLE
It can't properly infer the type of the query entries in Bevy game engine

### ISSUE THREAD

**Issue by adsick** [rust-analyzer/rust-analyzer#9811]
so when I do 
```rust
fn timer_update(time: Res<Time>, mut timer: Query<&mut Timer>) {
    for mut t in timer.iter_mut() {
        t.tick(time.delta());
    }
}
```
I expect ```t``` to be ```&mut Timer``` (and receive proper completions), but it determines ```t``` to be ```<QueryIter<&mut Timer, ()> as IntoIterator>::Item```

link to Bevy game engine repo: https://github.com/bevyengine/bevy
link to that ```.iter_mut()``` : https://github.com/bevyengine/bevy/blob/90586a4c461cde86b8a0e08f0770894e7cf30862/crates/bevy_ecs/src/system/query.rs#L186

and seems like it is everywhere in the Bevy codebase (didn't check that tho).
It makes development harder&slower because I rely on completions very much.

**Comment by Veykril** [comment]
Are you on the latest rust-analyzer version? Inference for queries works fine for me.
![image](https://user-images.githubusercontent.com/3757771/128627339-e8f38f5b-d17c-407f-aed5-090da1bcbef0.png)

**Comment by adsick** [comment]
It is updated and it's version is ```v0.2.702```

**Comment by adsick** [comment]
not sure if it is important, but I'm on Windows 10.

**Comment by adsick** [comment]
![image](https://user-images.githubusercontent.com/24528839/128747174-8353edb9-0aa6-46f3-b74c-4e566eeff6cc.png)
this is from official ```contributors.rs``` example

**Comment by Veykril** [comment]
Iirc bevy implements a bunch of things on tuples via a proc-macro, can you check whether your proc-macro server is crashing? On that note what rustc version are you on?

**Comment by adsick** [comment]
I've just done a ```rustup update``` and the problem still remains.
also I know that there would be a notification about proc-macro crash if it occured.

**Comment by Veykril** [comment]
Mmh then I'm not sure what's wrong here, do you have a repo with this issue or is it possible for you to create minimal reproduction? I assume the snippet you posted should trigger this behaviour already but it does not for me 😕

**Comment by adsick** [comment]
I see this issue in relevant Bevy example code, so I don't think it is something to do with the code itself (I mean that's ok)

**Comment by Veykril** [comment]
Right sorry you said it happens in the example.
So there I can actually reproduce it.

**Comment by Veykril** [comment]
Nope I've spoken too soon, it resolves as well now.
![image](https://user-images.githubusercontent.com/3757771/128751209-54f9dd16-3a5e-46f0-9e0c-ac76594d5a6e.png)

**Comment by adsick** [comment]
yep, I see. so what steps do you recommend to track down the reasons (and what possible fixes might be)?

**Comment by adsick** [comment]
I've finally find out what was causing this.

the reason is that proc-macros were turned off in rust-analyzer settings, I've turned them off a couple of months before because it was crashing with nightly Rust. now I've turned it on and it works as expected, I do not understand why proc-macros are needed here tho, but anyway.

also I'm glad that I didn't reinstall rust-analyzer (it would fix the problem, but we would not find the reason)

**Comment by Veykril** [comment]
Ah sorry, I should've asked to check that setting as well, my suspicion was that its proc-macro related(hence why I asked for server crashes) because bevy uses proc macros to implement traits on tuples.

**Comment by xevrem** [comment]
is there anyway to enable this proc-macro feature in rustic-mode for emacs?

**Comment by flodiebold** [comment]
https://emacs-lsp.github.io/lsp-mode/page/lsp-rust-analyzer/#lsp-rust-analyzer-experimental-proc-attr-macros if your lsp-mode is recent enough.

**Comment by xevrem** [comment]
awesome, thank you! i was looking all over rustic for it, when it was an lsp-rust specific setting 🤦
