### ISSUE TITLE
Empty file in module tree gives syntax error

### ISSUE THREAD

**Issue by ThePuzzlemaker** [rust-analyzer/rust-analyzer#9819]
When an empty file is created (specifically, at least a file with the contents `\n`), and it is included into the module tree, rust-analyzer will give a syntax error when there is no error present.

This error typically takes the following form:
```
Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got '1'
Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got '1'
Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got '1'
Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got '1'
Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got '1'
Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got '1'
No quick fixes available
```

I'm not sure why the repetition exists but it is present.

Here is a screenshot of the error inline in the file:
![image](https://user-images.githubusercontent.com/12666617/128651110-1407a5f3-5a1c-4a41-a391-fc692768924e.png)

It also appears in the errors list, along with errors from issues like #9241:
![image](https://user-images.githubusercontent.com/12666617/128651148-1fdc8e4f-745b-4921-9985-e26338830bef.png)

I have not confirmed that this error occurs on IDEs other than VSCode, but I would assume so.

Information:
IDE: VSCode
Plugin: matklad.rust-analyzer v0.2.637
rust-analyzer version: rust-analyzer f0618a8f0 2021-06-14 stable
Rust: 1.54.0

**Comment by jonas-schievink** [comment]
Can you post the code needed to reproduce this?

**Comment by Veykril** [comment]
I don't think these are rust-analyzer errors, at least to my knowledge we do not have a `NULL` node

**Comment by flodiebold** [comment]
Good point, my guess would be a JSON parser?

**Comment by ThePuzzlemaker** [comment]
Hm, I didn't notice that. I'll have to see what plugin causes this. If it does somehow end up being due to rust-analyzer, I'll reopen this.
