### ISSUE TITLE
Perf issue encountered while working with paritytech/cumulus

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#9848]
rust-analyzer is quite good for most cases, but I still have difficuties to make it work together with cumulus, the following problems discovered:

- high memory usage, 12% of 32GB memory PC
![image](https://user-images.githubusercontent.com/33961674/128891429-a634a63c-ca36-44bf-a9e5-532cc8f1485a.png)
- checkOnSave is super super slow and make editor lag, after every edit & save, I need to wait at least 3~4 minutes to wait `cargo check` finish, which isn't acceptable at all. Even an empty line
- indexing is too slow and no cache persisted, currently if I open https://github.com/parallel-finance/parallel/blob/master/pallets/liquid-staking/src/lib.rs it took 3mins 1sec to finish indexing on a i9-10900k, 32GB PC
![image](https://user-images.githubusercontent.com/33961674/128891628-bdd205d5-3d86-46fa-8e4f-27fcd4d672cb.png)

- #9096

**Comment by GopherJ** [comment]
currently I have no choice but to disable it for all cumulus projects, because it causes lag of my editor. Also I have to say it works very well with non-cumulus project like big actix-web web app, but it just doesn't work well with cumulus and substrate.

**Comment by GopherJ** [comment]
just find some tips to make it faster:

~/.zshrc
```
export SKIP_WASM_BUILD=1
```

~/.vimrc
```
let $SKIP_WASM_BUILD = '1'
```

**Comment by matklad** [comment]
I think the main issue is that the project's build.rs is re-run on every change:

```
λ cargo check
   Compiling heiko-runtime v0.0.1 (/home/matklad/tmp/parallel/runtime/heiko)
   Compiling vanilla-runtime v0.0.1 (/home/matklad/tmp/parallel/runtime/vanilla)
   Compiling parallel-runtime v0.0.1 (/home/matklad/tmp/parallel/runtime/parallel)
    Checking parallel-dev v1.0.0 (/home/matklad/tmp/parallel/node/parallel-dev)
    Checking parallel v1.0.0 (/home/matklad/tmp/parallel/node/parallel)
    Finished dev [unoptimized + debuginfo] target(s) in 25.25s

19:28:48|~/tmp/parallel|master⚡*
λ touch pallets/liquid-staking/src/lib.rs

19:29:18|~/tmp/parallel|master⚡*
λ cargo check
   Compiling parallel-runtime v0.0.1 (/home/matklad/tmp/parallel/runtime/parallel)
   Compiling vanilla-runtime v0.0.1 (/home/matklad/tmp/parallel/runtime/vanilla)
   Compiling heiko-runtime v0.0.1 (/home/matklad/tmp/parallel/runtime/heiko)
    Checking pallet-liquid-staking v3.0.0 (/home/matklad/tmp/parallel/pallets/liquid-staking)
    Checking parallel-dev v1.0.0 (/home/matklad/tmp/parallel/node/parallel-dev)
    Checking parallel v1.0.0 (/home/matklad/tmp/parallel/node/parallel)
    Finished dev [unoptimized + debuginfo] target(s) in 30.46s
```

the expected behavior is that the second `cargo check` shouldn't do anything. Work around on rust-analyzer side:

```json
// .vscode/settings.json
{
    "rust-analyzer.procMacro.enable": false,
    "rust-analyzer.cargo.runBuildScripts": false,
    "rust-analyzer.checkOnSave.enable": false,
}
```

this obviously disables all kinds of features. 

Closing as this seems a problem with a particular build.

**Comment by lnicola** [comment]
Kinda' related to #9096 (misbehaved build script in blockchain project)

**Comment by GopherJ** [comment]
@matklad 

sometimes the cpu goes to 100%

![image](https://user-images.githubusercontent.com/33961674/128900288-3ff479f0-29d0-4e66-94be-d713db33d323.png)

**Comment by lnicola** [comment]
Are you (or your editor) running two instances of RA at the same time? How does the tree view look once you hide the threads?

**Comment by GopherJ** [comment]
I haven't try:

```
+    "rust-analyzer.procMacro.enable": false,
+    "rust-analyzer.cargo.runBuildScripts": false,
```
I'll try them tomorrow

**Comment by GopherJ** [comment]
> Are you (or your editor) running two instances of RA at the same time? How does the tree view look once you hide the threads?

No, I only opened one project, it supposes to have only one instance, not sure if another is `procmacro`

**Comment by lnicola** [comment]
It's not, it would say so:

![image](https://user-images.githubusercontent.com/308347/128901953-3bcb226b-d1c1-4293-b7b0-0224790ebe26.png)

**Comment by flodiebold** [comment]
@GopherJ you already reported indexing taking a while in this repository in #8810 as well.

**Comment by flodiebold** [comment]
The two processes sound like #9388.

**Comment by GopherJ** [comment]
ok thanks @flodiebold I'll check it. Currently I'm using:

https://github.com/rust-analyzer/rust-analyzer/issues/9848#issuecomment-896124106
https://github.com/rust-analyzer/rust-analyzer/issues/9848#issuecomment-896143312

and it's much faster now, although I have to manually run cargo check
