### ISSUE TITLE
Run check on startup

### ISSUE THREAD

**Issue by mankinskin** [rust-analyzer/rust-analyzer#9851]
Sometimes rust analyzer doesn't show cargo check diagnostics, like errors, after startup, unless I make a change to a file and save. I think it would be fair to run cargo check after loading a project to ensure all diagnostics are up to date.

**Comment by lnicola** [comment]
We already do that. What editor are you using and do you have any particular settings? Does it happen in every project?

**Comment by mankinskin** [comment]
I use vscode with the vim plugin, and I tried it with default settings aswell.

I just noticed that, I first thought error diagnostics are broken, I tried restarting several times, but only changing and saving fixed it.

It happened right after I updated the extension and reloaded vscode.

**Comment by mankinskin** [comment]
It is still happening now after I restart. No errors until I change and save.

**Comment by lnicola** [comment]
Maybe it didn't get a chance to download the server binary.

**Comment by lnicola** [comment]
But that's unlikely if the other features work. Does it happen in a new project?

**Comment by mankinskin** [comment]
It should be everything there. It works after I force a cargo check. I presume it is just that cargo check is not being run for some reason.

**Comment by mankinskin** [comment]
Hm it works when I load a new project with an error in it. Something with my old project doesn't seem to fit right.

**Comment by mankinskin** [comment]
It works when I remove the target folder and then reopen the project. It also shows cargo check running in the status bar, which it didn't before. But when I open a new project with a target folder it still runs cargo check... weird

**Comment by lnicola** [comment]
We pass --all-targets by default, so you can get a different set of errors depending on how you run cargo check. And I think we don't always report some errors. Maybe you had a broken file in target for a path dependency or something like that.

But it's a stretch. I don't have other ideas.

**Comment by mankinskin** [comment]
It were pretty common errors, like completely unknown types and such.. I just removed a struct definition before updating and restarting. It works now, if it bumps us again maybe we will have more clues.
