### ISSUE TITLE
100% CPU and unable to kill

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#9853]
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/33961674/129009904-e99aa148-a95f-4c2d-b6f7-7acdfc2b4e22.png">

**Comment by GopherJ** [comment]
if I execute `pkill rust-analyzer` it comes back in a few seconds, I have no idea on what happened, I just upgraded `coc.nvim`, `coc-rust-analyzer` and `rust-analyzer` like before

**Comment by lnicola** [comment]
The LSP client probably restarts the server if it crashes.

Using 100% CPU for 19 seconds isn't unreasonable, especially if it's on start-up.

**Comment by GopherJ** [comment]
indeed I shutdown all vim, nvim , coc.nvim @lnicola

**Comment by lnicola** [comment]
You can attach `gdb` (or `perf top`) to see what it's doing.

**Comment by lnicola** [comment]
Does `rust-analyzer analysis-stats .` finish in your project? What about `rust-analyzer analysis-stats --with-deps .`?

**Comment by GopherJ** [comment]
finally I find there is a process:

```
nvim -p ...rs
```

I kill this process and then killed rust-analyzer but rust-analyzer comes back again:)

**Comment by lnicola** [comment]
If you press F5 in `htop` (or run `ps auxf`) you can see the parent of a process.

**Comment by GopherJ** [comment]
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/33961674/129011757-e16f7665-cac5-4010-95fd-8c3f38e8b084.png">

**Comment by lnicola** [comment]
Okay, I guess CoC remained running after you quit Vim.

**Comment by lnicola** [comment]
Which repository do you get that panic on?

**Comment by bjorn3** [comment]
> The LSP client probably restarts the server if it crashes.

At least for vscode it stops restarting if you quickly kill it 5 times in a row. In htop I first use `\rust-analyzer` to show only rust-analyzer processes and then spam k<enter> to keep killing it as soon as it is restarted.

**Comment by GopherJ** [comment]
sorry I was busy. Forgive me.I'll do it during weekend

**Comment by GopherJ** [comment]
I think I cannot reproduce this anymore
