### ISSUE TITLE
VS Code: Overall inaccurate problem highlights for Live Share guests

### ISSUE THREAD

**Issue by colelawrence** [rust-analyzer/rust-analyzer#9858]
I hope this is in the right place, but while working remotely it seems like 50% of error / warning problem highlights (esp ones propagated through cargo check on save) are placed in the wrong locations.

Perhaps relevant is the fact that we work from Europe to East Coast with what I would guess is typically 500+ms ping time.

I'd love to through more details in this if this is the first time this has been documented.

Thanks!

**Comment by lnicola** [comment]
Next time can you keep an eye on whether it happens with the native diagnostics? The ones from Cargo don't get adjusted even in local sessions.

**Comment by colelawrence** [comment]
@lnicola, is there a technical limitation to how the cargo check errors drift?

Is it because cargo check can correspond to a different version of the file than what is actually shown in document, so the doc positions may not line up correctly when the check comes back?

I would think we could determine which document "version" (VSCode terminology) corresponds to the saved file which cargo check corresponds to. Then, after we get the diagnostics back, we'd have to remap their positions between the save "version" and current editor group "version".

**Comment by lnicola** [comment]
This is https://github.com/rust-analyzer/rust-analyzer/issues/8836, https://github.com/rust-analyzer/rust-analyzer/issues/1471 and https://github.com/microsoft/vscode/issues/103953.

**Comment by colelawrence** [comment]
Thank you so much for the references. It does appear that my issues have been reported in those areas.

Cheers!

**Comment by lnicola** [comment]
Let's close this, then, so we don't have too many duplicates.
