### ISSUE TITLE
suggestion for a Quick Fix for mismatched-arg-count

### ISSUE THREAD

**Issue by LucianoBestia** [rust-analyzer/rust-analyzer#9865]
Firstly, Thank you for rust-analyzer. It is a lifesaver.
Sometimes I have this workflow:
1. I write a function call. Then I generate a new function from this function call.
2. Later I add a parameter to the function call. 
3. I got the warning `mismatched-arg-count`, but there are no Quick Fixes. 
4. There I can see the name and type of the variable and I can manually copy and paste it into the function definition.

I suggest a Quick Fix to do just that. Maybe: `add parameter to function`?
Maybe I can help with a Pull Request if you guide me where to find a similar action.
Thanks.
Here is a short example:

https://user-images.githubusercontent.com/31509965/129188893-13732295-8f9f-4eb4-ad50-d8de576ffc98.mp4

**Comment by lnicola** [comment]
One problem is that it's not obvious which parameter is missing, e.g. `f(10, 20, "boo")` with `fn f(x: i32, s: &str)`.

**Comment by LucianoBestia** [comment]
Just a thought:
in QuickFix show every parameter, so the user can choose which one is missing.
