### ISSUE TITLE
Source map not correctly generated

### ISSUE THREAD

**Issue by EFanZh** [rust-analyzer/rust-analyzer#9872]
#8624 implemented automatic source map detection. Currently, wrong source map is generated. To reproduce, set "rust-analyzer.debug.sourceFileMap" to "auto", then start a debug session with debug lens. Then observe the debug configuration in the debug output pane. You should see the following configuration:

```json
"sourceFileMap": {
  "/rustc/undefined/": "……"
}
```

Notice the “/rustc/undefined/” path in the configuration. It is an invalid path.

**Comment by lnicola** [comment]
@EFanZh I can't test it right now, but can you give #9882 a try?

**Comment by EFanZh** [comment]
Hi @lnicol, I have tested your change, it does seem to work, thanks!
