### ISSUE TITLE
"server" fetcher on very first run shows ERROR where there is no functional error

### ISSUE THREAD

**Issue by shoffmeister** [rust-analyzer/rust-analyzer#9875]
On the very very first run / activation of the the extension, Rust Analyzer shows an error message in the vscode Output window  for the Rust Analyzer Client which is not associated with a functional error:

`ERROR [8/12/2021, 9:30:03 PM]: Cannot rename existing server instance: EntryNotFound (FileSystemError) (FileSystemError): Error: ENOENT: no such file or directory, rename '/home/stefan/.config/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu' -> '/home/stefan/.config/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-unknown-linux-gnu-stale-37983d5545'`

This is clearly caused by there not having been a server binary before - this is the first run of Rust Analyzer on this totally clean machine.

To reproduce
* terminate vscode
* `rm -rf ~/.config/Code` - or to taste ;)
* start vscode
* install Rust Analyzer extension
* File -> Open folder -> some rust project with a top-level Cargo.toml (in my case ripgrep, not that it would matter)
//act: ERROR - see above
//exp: WARN? INFO? Or total silence? 

An "if file exists then rename" is racy in theory with multiple vscode instances doing a server upgrade at the exact same time, but that will happen like ... never? The initializing run of Rust Analyzer on a fresh machine is massively more frequent, and creating an error-free *feeling* offers a nice user experience (IMHO).

**Comment by lnicola** [comment]
Hopefully fixed in #10222. There was a check for this situation, but Code reports that error in an.. interesting way.
