### ISSUE TITLE
Is It possible tu set rust-analyzer debug env flags

### ISSUE THREAD

**Issue by kytas** [rust-analyzer/rust-analyzer#9883]
Hello,
I am using external .so library and i cannot find any settings relating to debug session, 
On run session is everything ok by set up
"rust-analyzer.runnableEnv": 
{
"RUSTFLAGS": "-C link-args=-Wl,-laes_access",
},

Is somewhere variable for debugEnv or is some way to do that ?

**Comment by lnicola** [comment]
That's not a debug, but compile-time option. You can set it in `rust-analyzer.server.extraEnv` or, better, in [`.cargo/config.toml`](https://doc.rust-lang.org/cargo/reference/config.html) or even better, in a build script.

**Comment by kytas** [comment]
in VS code i have this : 
	"settings": {
	
		"rust-analyzer.server.extraEnv": {
			"RUSTFLAGS": "-C link-args=-Wl,-laes_access",
		},
	
		"rust-analyzer.runnableEnv": {
			"RUSTFLAGS": "-C link-args=-Wl,-laes_access",
		},
	}
 in .cargo/config.toml 
[target.x86_64-unknown-linux-gnu]
RUSTFLAGS=["-C","link-args=-Wl,-laes_access"]


No working. If click on run its working on Debug i cannot compile. I try export RUSTFLAGS and its not working too.

**Comment by lnicola** [comment]
That should be:

```toml
[target.x86_64-unknown-linux-gnu]
rustflags=["-C","link-args=-Wl,-laes_access"]
```

And you shouldn't need `rust-analyzer.server.extraEnv` or `rust-analyzer.server.runnableEnv` unless you're starting a program that actually runs `cargo` or `rustc`.

**Comment by kytas** [comment]
still same in debug i cannot compile, because libaes isnt linked. Do u have any other idea ?

**Comment by lnicola** [comment]
What error are you getting? Does `cargo build` work?

**Comment by kytas** [comment]
Now it working i set globally RUSTFLAGS, I dont understand why the .config doesnt work. It doesnt matter, thank u for help.

**Comment by kytas** [comment]
aaahh i found error, i had space in .cargo name.... I am idiot... sry for that
