### ISSUE TITLE
Error in RA code

### ISSUE THREAD

**Issue by mahdi-frms** [rust-analyzer/rust-analyzer#9888]
https://github.com/rust-analyzer/rust-analyzer/blob/c5ddc35a450f15d0df0a231321d06d470f846e2c/crates/ide_assists/src/utils.rs#L132
Shows an error on `trait_impl` identifier:
```
no function or associated item named `trait_impl` found for struct `PathTransform<'_>` in the current scope
function or associated item not found in `PathTransform<'_>` rustc(E0599)
```

**Comment by flodiebold** [comment]
I can't reproduce, and this is a rustc error, so it should be happening on `cargo check` as well (I don't see any cfg shenanigans there either). Maybe you've got some local changes?

**Comment by mahdi-frms** [comment]
I've actually done no change. reloaded the server and it still exist. neither compiler nor `cargo check` give any error.

**Comment by flodiebold** [comment]
Can you try with a separate fresh checkout of rust-analyzer? Do you have any non-default rust-analyzer settings?

**Comment by mahdi-frms** [comment]
> Do you have any non-default rust-analyzer settings?

No.

> Can you try with a separate fresh checkout of rust-analyzer?

Did it and after merging the changes from RA repo, the error went away. I had seen the same thing before elsewhere. Don't know why these things happen really and disappear with no reason.

**Comment by lnicola** [comment]
I've ran into it a couple of times. It's a caching bug, usually caused by pulling or switching branches while RA is running cargo check.

A cargo clean and maybe nuking my sccache cahe directory fixes it.
