### ISSUE TITLE
Toolchain checks in path never works

### ISSUE THREAD

**Issue by gfreezy** [rust-analyzer/rust-analyzer#9907]
https://github.com/rust-analyzer/rust-analyzer/blob/b641a66078ce2f2363e9a3b050ba448b93fb7cb6/editors/code/src/toolchain.ts#L170-L193

`candidates.some(isFileAtPath)` always returns true, because isFileAtPath is an *async* function which return a promise which always evaluates to true.

```js
a = [1, 3]

function isEven(s) {
	return s % 2 === 0;
}

async function asyncIsEven(s) {
	return s % 2 === 0;
}

console.log("sync version should print false: ", a.some(isEven));
console.log("async version always print true: ", a.some(asyncIsEven));
```

**Comment by gfreezy** [comment]
the bug is introduced by this commit: https://github.com/rust-analyzer/rust-analyzer/commit/0448b7364666ba59b39bbd5564fe8a34b67b8f01#diff-1810e9007862088495434a5cfe68a4903cb46f83d45b2f124639827fb803ceb3L184

**Comment by jonas-schievink** [comment]
I'm surprised that there's no warning against that

**Comment by gfreezy** [comment]
Sadly these are all valid js code.

**Comment by gfreezy** [comment]
@jonas-schievink I have a PR #9908  to fix this. Could you review it?
