### ISSUE TITLE
"Check on save command" doesn't work if you add commands to the command

### ISSUE THREAD

**Issue by Lokathor** [rust-analyzer/rust-analyzer#9913]
If you set the check on save command to something such as "build" then things are fine, but if you write (for example) "build --bins" then instead nothing will get checked at all.

**Comment by lnicola** [comment]
Try setting `rust-analyzer.checkOnSave.overrideCommand` to `["cargo", "check", "--bins"]`.

**Comment by bjorn3** [comment]
That needs `--message-format json` as arguments too.

**Comment by lnicola** [comment]
Right, of course. And there's also `rust-analyzer.checkOnSave.extraArgs`.
