### ISSUE TITLE
Extend `fill_struct_fields` assist to support partially filled struct literals

### ISSUE THREAD

**Issue by yanchith** [rust-analyzer/rust-analyzer#992]
We implemented `fill_struct_fields` assist in #964 (PR #989), which was in turn based on #626.

We would like to extend the assist to support partial struct literals. That is, if there is a

```rust
struct S {
    foo: u32,
    bar: i32,
    baz: String
}
```

and a literal `S { bar: 92 }`, the assist should produce `S { foo: (), bar: 92, baz: () }`, preserving the user filled values.

The assist lives in in  [fill_struct_fields.rs](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ra_assists/src/fill_struct_fields.rs)

**Comment by c410-f3r** [comment]
I will try

**Comment by wasd96040501** [comment]
How can I use this feature. I can't find any related command in vscode.
