### ISSUE TITLE
Feature: "Convert to method assist" for static methods

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-analyzer/rust-analyzer#9948]
This is a follow-up to https://github.com/rust-analyzer/rust-analyzer/issues/9616, https://github.com/rust-analyzer/rust-analyzer/pull/9804, and https://github.com/rust-analyzer/rust-analyzer/issues/8555. We should expand `crates/ide_assists/src/handlers/generate_function.rs` to also generate static methods.

## Example

__input__
```rust
struct Foo;

impl Foo {
    fn bar() {
        Self::ba$0z(12_u8, "hello");
    }
}
```
__output__
```rust
struct Foo;

impl Foo {
    fn bar() {
        Self::baz(12_u8, "hello");
    }
    
    fn baz(arg1: u8, arg2: &str) {
        $:0{todo!()}
    }
}
```

**Comment by mahdi-frms** [comment]
I'll work on this.

**Comment by yoshuawuyts** [comment]
Closed by https://github.com/rust-analyzer/rust-analyzer/pull/9994
