### ISSUE TITLE
How to toggle feature to enable/disable code highlighting accordingly ?

### ISSUE THREAD

**Issue by n-eq** [rust-analyzer/rust-analyzer#9951]
Hi,

I am using `rust-analyzer` implicitly through YouCompleMe with Vim, been using the plugin with Rust for a couple of days now and I find it awesome.
However, I struggled to find a way to _virtually_ enable or disable a feature in a package in order to highlight the code that uses it. The only reference to this in the documentation is [this paragraph](https://rust-analyzer.github.io/manual.html#inactive-code) which isn't really helpful.

![image](https://user-images.githubusercontent.com/16545838/130068805-e9de3483-ec22-4564-b356-ab8afc70aa94.png)

Is this currently possible? If so, can you please show me?

**Comment by lnicola** [comment]
Can you post a screenshot? Code highlighting is different from inactive code highlighting.

**Comment by n-eq** [comment]
Thanks @lnicola , glad to hear it is already supported by rust-analyzer. I'll look into YCM.

Closing the issue.

**Comment by lnicola** [comment]
https://github.com/ycm-core/YouCompleteMe#lsp-configuration might help.
