### ISSUE TITLE
Normalization issue with operators or `Deref`

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#9971]
CC #8961

```rust
let s = String::new() + &String::new(); // s is <String as Add<String>>::Output
```

**Comment by lnicola** [comment]
This might be related to `Deref` or something else. The following snipped works as expected:

```rust
use std::ops::Add;

struct S;

impl Add for S {
    type Output = S;

    fn add(self, _rhs: Self) -> Self::Output {
        todo!()
    }
}

fn main() {
    let s = S + S;
}
```

**Comment by flodiebold** [comment]
Actually, `String::new() + String::new()` is a type error, isn't it?

**Comment by flodiebold** [comment]
Yeah, I think the problem is that we don't do coercions on the right hand side in binary ops.

**Comment by lnicola** [comment]
> Actually, String::new() + String::new() is a type error, isn't it?

Well, this is awkward...

**Comment by lnicola** [comment]
Should we also coerce on the LHS?

**Comment by flodiebold** [comment]
There's nothing to really coerce *to* at that point. (rustc [does](https://github.com/rust-lang/rust/blob/db002a06ae9154a35d410550bc5132df883d7baa/compiler/rustc_typeck/src/check/op.rs#L168-L189) coerce to a fresh type variable, but just to avoid too strict lifetime constraints.)

**Comment by lnicola** [comment]
> The problem is that we only do the trait resolution at the end, but we need to do it before checking the right-hand side (with a variable in place of the RHS type). For String, that will tell us that the RHS type has to be &str.
