### ISSUE TITLE
Module resolution in tests

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#9977]
With this setup:

```
# Cargo.toml
[package]
autotests = false

[[test]]
name = "tests"

// tests/tests.rs
mod m;

// tests/m.rs
pub fn foo() {}

// tests/test1.rs
use m::foo;
```

`m` isn't resolved `test1.rs`.

**Comment by bjorn3** [comment]
`test1.rs` is not included in any crate in that example. Does `mod test1;` in `tests.rs` help?

**Comment by lnicola** [comment]
Yeah, sorry. It works, except on the 2015 edition where we only recognize it with `crate::m`. I was looking at the `diesel` code we're using to collect metrics.
