### ISSUE TITLE
Symbol search doesn't find items generated by macros

### ISSUE THREAD

**Issue by lf-** [rust-analyzer/rust-analyzer#9981]
```rust
macro_rules! id {
    ($($i:tt)*) => {
        $($i)*
    };
}

id! {
    struct Struct;
}

fn main() {
    let _ = Struct;
    //  ^   ^ go to type definition or go to definition works here
}
```

I was working on chalk and was searching for some types in the symbol search and could not find them. Confused, I observed that all the affected items are generated by `macro_rules` macros. To reproduce it with the example above, attempt to use the symbol search to find `Struct`, which will not be listed. Go to definition and all other analysis seems to work properly, however.

Version: 8cd171cd949f6c82a9ce50645f6ca68b1249c4c8

**Comment by jonas-schievink** [comment]
This is https://github.com/rust-analyzer/rust-analyzer/issues/4842
