### ISSUE TITLE
Cannot go to definition of RootDatabase.crate_graph in rust-analyzer

### ISSUE THREAD

**Issue by wasd96040501** [rust-analyzer/rust-analyzer#9986]
![image](https://user-images.githubusercontent.com/14040068/130360364-6b82858a-efb2-420e-bff9-72deed64f913.png)

The code is:
https://github.com/rust-analyzer/rust-analyzer/blob/0960d4ebe2f493960296b21be45b06418919dd23/crates/ide/src/prime_caches.rs#L26

**Comment by Veykril** [comment]
The database functions are pretty attribute heavy so most of them(all honestly) require `rust-analyzer.experimental.procAttrMacros` to be enabled for them to be resolvable for RA.

**Comment by wasd96040501** [comment]
> rust-analyzer.experimental.procAttrMacros

OH! It Works! Thank you.
