### ISSUE TITLE
Indexing on every startup

### ISSUE THREAD

**Issue by adsick** [rust-analyzer/rust-analyzer#9991]
every time I run VSC, RA is doing heavy work indexing everything. It looks to me that that could be cached(?) or am I missing something

**Comment by lnicola** [comment]
There's no persistent caching yet (#4712).

**Comment by qwabra** [comment]
shuld i use `rust-analyzer.files.excludeDirs`
```json
{
    // .vscode/settings.json
    "rust-analyzer.files.excludeDirs": [
        "dist",
        "node_modules",
        "public",
        "src"
    ],
}
```
or RA only scans the folder containing the `Cargo.toml` file `./src-tauri/Cargo.toml`
