### ISSUE TITLE
MBE doesn't bracket reference arguments

### ISSUE THREAD

**Issue by lnicola** [rust-analyzer/rust-analyzer#9996]
CC #8961

```rust
struct Options {
    casei: Option<bool>,
}
const CASEI: Options = Options { casei: Some(true) };

macro_rules! toregex {
    ($name:ident, $options:expr) => {
        #[test]
        fn $name() {
            if let Some(casei) = $options.casei {
                foo(casei);
            }
        }
    };
}

toregex!(re_casei, &CASEI);

fn foo(_c: bool) {}
```

If you macro-expand `toregex`, it produces `if let Some(casei) = &CASEI.casei`, causing a compilation error and a and type mismatch. The correct expansion is `if let Some(casei) = (&CASEI).casei`.

**Comment by flodiebold** [comment]
Hmm isn't this supposed to work by introducing 'invisible' parens? But obviously something is going wrong there...

**Comment by lnicola** [comment]
I think so, and we had some changes related to token grouping, IIRC. We should still display the brackets for convenience, though.

**Comment by lnicola** [comment]
This was apparently fixed by https://github.com/rust-analyzer/rust-analyzer/pull/10044. For some reason, it doesn't reproduce without `#[test]` attribute.
